function evidence = assertFRCPhysicalConfiguration(entry, tx)
%ASSERTFRCPHYSICALCONFIGURATION Prove catalog-to-waveform PHY identity.
%
% This assertion is evaluated on the actual PDSCH/PUSCH transmitter output.
% It is deliberately independent of exported configured-value echoes: every
% effective value below is read from the materialized Toolbox configuration,
% resource grid, waveform, or transmitter metadata.

arguments
    entry (1,1) struct
    tx (1,1) struct
end

direction = lower(string(entry.direction));
if ~any(direction == ["downlink","uplink"])
    error("sixgr:conformance:InvalidRuntimeDirection", ...
        "Unsupported FRC runtime direction '%s'.", direction);
end

carrier = localRequiredField(tx, "Carrier");
if direction == "uplink"
    channel = localRequiredField(tx, "PUSCH");
    channelName = "PUSCH";
else
    channel = localRequiredField(tx, "PDSCH");
    channelName = "PDSCH";
end

localAssertNumeric("carrier NSizeGrid", ...
    localProperty(carrier, "NSizeGrid", NaN), entry.carrier.n_prb, ...
    "sixgr:conformance:RuntimeCarrierMismatch");
localAssertNumeric("carrier NStartGrid", ...
    localProperty(carrier, "NStartGrid", NaN), entry.carrier.prb_start, ...
    "sixgr:conformance:RuntimeCarrierMismatch");
localAssertNumeric("carrier subcarrier spacing", ...
    localProperty(carrier, "SubcarrierSpacing", NaN), ...
    entry.carrier.subcarrier_spacing_khz, ...
    "sixgr:conformance:RuntimeCarrierMismatch");
localAssertText("carrier cyclic prefix", ...
    localProperty(carrier, "CyclicPrefix", ""), ...
    entry.carrier.cyclic_prefix, ...
    "sixgr:conformance:RuntimeCarrierMismatch");

expectedPRBSet = double(entry.carrier.prb_start:entry.carrier.prb_end);
localAssertVector("allocated PRB set", ...
    localProperty(channel, "PRBSet", []), expectedPRBSet, ...
    "sixgr:conformance:RuntimeAllocationMismatch");
localAssertText("mapping type", ...
    localProperty(channel, "MappingType", ""), ...
    entry.allocation.mapping_type, ...
    "sixgr:conformance:RuntimeAllocationMismatch");
localAssertVector("symbol allocation", ...
    localProperty(channel, "SymbolAllocation", []), ...
    [entry.allocation.start_symbol, entry.allocation.symbol_length], ...
    "sixgr:conformance:RuntimeAllocationMismatch");

actualModulation = upper(string(localProperty(channel, "Modulation", "")));
expectedModulation = upper(string(entry.coding.modulation));
if isempty(actualModulation) || any(actualModulation ~= expectedModulation)
    localMismatch("sixgr:conformance:RuntimeModulationMismatch", ...
        "modulation", expectedModulation, actualModulation);
end
localAssertNumeric("number of layers", ...
    localProperty(channel, "NumLayers", NaN), entry.mimo.layers, ...
    "sixgr:conformance:RuntimeLayerMismatch");

grid = localRequiredField(tx, "Grid");
waveform = localRequiredField(tx, "Waveform");
expectedGridSize = [12 * double(entry.carrier.n_prb), 14];
if size(grid,1) ~= expectedGridSize(1) || size(grid,2) ~= expectedGridSize(2)
    localMismatch("sixgr:conformance:RuntimeGridShapeMismatch", ...
        "resource-grid first two dimensions", expectedGridSize, ...
        size(grid, [1 2]));
end
actualWaveformPorts = size(waveform, 2);
localAssertNumeric("waveform transmit-port count", actualWaveformPorts, ...
    entry.mimo.tx_antennas, ...
    "sixgr:conformance:RuntimeWaveformPortMismatch");

dmrs = localProperty(channel, "DMRS", []);
if isempty(dmrs)
    error("sixgr:conformance:RuntimeDMRSConfigurationMissing", ...
        "The materialized %s configuration has no DM-RS object.", channelName);
end
localAssertNumeric("DM-RS configuration type", ...
    localProperty(dmrs, "DMRSConfigurationType", NaN), ...
    entry.dmrs.configuration_type, ...
    "sixgr:conformance:RuntimeDMRSConfigurationMismatch");
expectedDMRSLength = 1 + double(string(entry.dmrs.duration) == "double_symbol");
localAssertNumeric("DM-RS duration", ...
    localProperty(dmrs, "DMRSLength", NaN), expectedDMRSLength, ...
    "sixgr:conformance:RuntimeDMRSConfigurationMismatch");
localAssertNumeric("DM-RS Type-A position", ...
    localProperty(dmrs, "DMRSTypeAPosition", NaN), ...
    entry.dmrs.type_a_position, ...
    "sixgr:conformance:RuntimeDMRSConfigurationMismatch");
localAssertNumeric("DM-RS additional position", ...
    localProperty(dmrs, "DMRSAdditionalPosition", NaN), ...
    entry.dmrs.additional_position, ...
    "sixgr:conformance:RuntimeDMRSConfigurationMismatch");
localAssertNumeric("DM-RS CDM groups without data", ...
    localProperty(dmrs, "NumCDMGroupsWithoutData", NaN), ...
    entry.dmrs.num_cdm_groups_without_data, ...
    "sixgr:conformance:RuntimeDMRSConfigurationMismatch");

expectedPorts = double(entry.dmrs.ports(:).');
if direction == "downlink"
    expectedToolboxPorts = expectedPorts - 1000;
else
    expectedToolboxPorts = expectedPorts;
end
localAssertVector("DM-RS ports", ...
    localProperty(dmrs, "DMRSPortSet", []), expectedToolboxPorts, ...
    "sixgr:conformance:RuntimeDMRSConfigurationMismatch");

if ~isfield(entry.dmrs, "symbol_indices")
    error("sixgr:conformance:MissingDMRSSymbolContract", ...
        "FRC %s does not explicitly encode its DM-RS symbol indices.", ...
        string(entry.frc_id));
end
if direction == "uplink"
    subscripts = nrPUSCHDMRSIndices(carrier, channel, ...
        "IndexStyle", "subscript", "IndexBase", "0based");
else
    subscripts = nrPDSCHDMRSIndices(carrier, channel, ...
        "IndexStyle", "subscript", "IndexBase", "0based");
end
actualDMRSSymbols = unique(double(subscripts(:,2)).', "stable");
expectedDMRSSymbols = double(entry.dmrs.symbol_indices(:).');
localAssertVector("DM-RS symbols", actualDMRSSymbols, ...
    expectedDMRSSymbols, ...
    "sixgr:conformance:RuntimeDMRSSymbolMismatch");

configuredDifference_dB = double(entry.dmrs.data_to_dmrs_epre_db);
if abs(configuredDifference_dB + 3) <= 1e-12
    expectedDMRSPowerScale = 2;
else
    expectedDMRSPowerScale = 10.^(-configuredDifference_dB / 10);
end
actualDMRSPowerScale = double(localOptionalField(tx, "DMRSPowerScale", NaN));
if ~(isscalar(actualDMRSPowerScale) && isfinite(actualDMRSPowerScale) && ...
        actualDMRSPowerScale > 0 && ...
        abs(actualDMRSPowerScale - expectedDMRSPowerScale) <= ...
        64 * eps(max(expectedDMRSPowerScale, 1)))
    localMismatch("sixgr:conformance:RuntimeDMRSPowerMismatch", ...
        "DM-RS/data power scale", expectedDMRSPowerScale, ...
        actualDMRSPowerScale);
end

expectedPTRS = isfield(entry, "ptrs") && logical(entry.ptrs.enabled);
actualPTRS = logical(localProperty(channel, "EnablePTRS", false));
if actualPTRS ~= expectedPTRS
    localMismatch("sixgr:conformance:RuntimePTRSMismatch", ...
        "PT-RS enabled state", expectedPTRS, actualPTRS);
end
precodeEvidence = struct( ...
    "TransmissionScheme", "not_applicable_downlink", ...
    "TPMI", NaN, "NativeCodebookApplied", false, ...
    "CodebookStatus", "not_applicable_downlink", ...
    "MatrixSHA256", "", "Bundling", "not_applicable", ...
    "NumPRG", NaN, "MatrixRank", NaN, "TotalPower", NaN);
if direction == "uplink"
    expectedScheme = lower(string(sixgr.util.structGet( ...
        entry.mimo, "precoding_scheme", "noncodebook")));
    actualScheme = lower(string(localProperty( ...
        channel, "TransmissionScheme", "")));
    localAssertText("PUSCH transmission scheme", actualScheme, ...
        expectedScheme, "sixgr:conformance:RuntimePUSCHPrecodingMismatch");
    localAssertNumeric("PUSCH antenna-port count", ...
        localProperty(channel, "NumAntennaPorts", NaN), ...
        entry.mimo.tx_antennas, ...
        "sixgr:conformance:RuntimePUSCHPrecodingMismatch");
    precodeEvidence = localAssertPUSCHPrecoder( ...
        entry, channel, localOptionalField(tx, "PrecodeInfo", struct()));
    actualTransformPrecoding = logical(localProperty( ...
        channel, "TransformPrecoding", false));
    if actualTransformPrecoding ~= logical(entry.waveform.transform_precoding)
        localMismatch("sixgr:conformance:RuntimeTransformPrecodingMismatch", ...
            "transform-precoding state", ...
            logical(entry.waveform.transform_precoding), ...
            actualTransformPrecoding);
    end
    expectedHopping = string(entry.allocation.frequency_hopping);
    actualHopping = lower(string(localProperty(channel, ...
        "FrequencyHopping", "")));
    if expectedHopping == "disabled" && actualHopping ~= "neither"
        localMismatch("sixgr:conformance:RuntimeFrequencyHoppingMismatch", ...
            "frequency-hopping state", "neither", actualHopping);
    end
    localAssertNumeric("DM-RS NID0", ...
        localProperty(dmrs, "NIDNSCID", NaN), entry.dmrs.n_id_0, ...
        "sixgr:conformance:RuntimeDMRSConfigurationMismatch");
    localAssertNumeric("DM-RS nSCID", ...
        localProperty(dmrs, "NSCID", NaN), entry.dmrs.n_scid, ...
        "sixgr:conformance:RuntimeDMRSConfigurationMismatch");
else
    precodeEvidence = localAssertPDSCHPrecoder( ...
        entry, carrier, localOptionalField(tx, "PrecodeInfo", struct()));
    if string(entry.allocation.vrb_to_prb_mapping) == "non_interleaved"
        actualInterleaving = logical(localProperty( ...
            channel, "VRBToPRBInterleaving", false));
        if actualInterleaving
            localMismatch("sixgr:conformance:RuntimeVRBMappingMismatch", ...
                "VRB-to-PRB interleaving", false, true);
        end
    end
end

actualRV = double(localOptionalField(tx, "RV", NaN));
allowedRV = double(entry.harq.rv_sequence(:).');
if isempty(actualRV) || any(~ismember(actualRV(:).', allowedRV))
    localMismatch("sixgr:conformance:RuntimeHARQMismatch", ...
        "HARQ redundancy version", allowedRV, actualRV);
end

evidence = struct( ...
    "Exact", true, ...
    "Direction", direction, ...
    "PhysicalChannel", channelName, ...
    "NSizeGrid", double(localProperty(carrier, "NSizeGrid", NaN)), ...
    "SubcarrierSpacing_kHz", double(localProperty( ...
        carrier, "SubcarrierSpacing", NaN)), ...
    "CyclicPrefix", string(localProperty(carrier, "CyclicPrefix", "")), ...
    "MappingType", string(localProperty(channel, "MappingType", "")), ...
    "SymbolAllocation", double(localProperty( ...
        channel, "SymbolAllocation", [])), ...
    "PRBSet", double(localProperty(channel, "PRBSet", [])), ...
    "Modulation", actualModulation, ...
    "Layers", double(localProperty(channel, "NumLayers", NaN)), ...
    "WaveformTxPorts", double(actualWaveformPorts), ...
    "TransmissionScheme", string(precodeEvidence.TransmissionScheme), ...
    "TPMI", double(precodeEvidence.TPMI), ...
    "NativeCodebookApplied", logical( ...
        precodeEvidence.NativeCodebookApplied), ...
    "CodebookStatus", string(precodeEvidence.CodebookStatus), ...
    "PrecoderMatrixSHA256", string(precodeEvidence.MatrixSHA256), ...
    "PrecoderBundling", string(precodeEvidence.Bundling), ...
    "PrecoderNumPRG", double(precodeEvidence.NumPRG), ...
    "PrecoderMatrixRank", double(precodeEvidence.MatrixRank), ...
    "PrecoderTotalPower", double(precodeEvidence.TotalPower), ...
    "DMRSSymbolIndices", actualDMRSSymbols, ...
    "DMRSPorts", double(localProperty(dmrs, "DMRSPortSet", [])), ...
    "PTRSEnabled", actualPTRS, ...
    "RV", actualRV, ...
    "Source", "materialized_truth_transmitter_objects");
end

function evidence = localAssertPDSCHPrecoder(entry, carrier, precodeInfo)
nLayers = double(entry.mimo.layers);
nTx = double(entry.mimo.tx_antennas);
if nTx == 1 && nLayers == 1
    evidence = struct( ...
        "TransmissionScheme", "direct_layer_to_port", ...
        "TPMI", NaN, "NativeCodebookApplied", false, ...
        "CodebookStatus", "not_applicable_siso", ...
        "MatrixSHA256", "", "Bundling", "wideband", ...
        "NumPRG", 1, "MatrixRank", 1, "TotalPower", 1);
    return;
end
if isempty(fieldnames(precodeInfo))
    error("sixgr:conformance:RuntimePDSCHPrecodingEvidenceMissing", ...
        "Exact multi-port PDSCH requires PDSCH_Tx.PrecodeInfo evidence.");
end
if ~logical(sixgr.util.structGet(precodeInfo, "Active", false))
    error("sixgr:conformance:RuntimePDSCHPrecodingMismatch", ...
        "The multi-port PDSCH transmitter did not apply explicit precoding.");
end
localAssertNumeric("PDSCH precoder layer count", ...
    sixgr.util.structGet(precodeInfo, "NumLayers", NaN), nLayers, ...
    "sixgr:conformance:RuntimePDSCHPrecodingMismatch");
localAssertNumeric("PDSCH precoder port count", ...
    sixgr.util.structGet(precodeInfo, "NumPorts", NaN), nTx, ...
    "sixgr:conformance:RuntimePDSCHPrecodingMismatch");

pages = complex(double(sixgr.util.structGet( ...
    precodeInfo, "MatrixPortsPerPRG", [])));
if isempty(pages)
    base = complex(double(sixgr.util.structGet( ...
        precodeInfo, "MatrixPorts", [])));
    pages = reshape(base, size(base,1), size(base,2), 1);
end
if size(pages,1) ~= nTx || size(pages,2) ~= nLayers
    error("sixgr:conformance:RuntimePDSCHPrecodingMismatch", ...
        "PDSCH precoder shape %s does not match %d ports by %d layers.", ...
        mat2str(size(pages)), nTx, nLayers);
end
if any(~isfinite(real(pages(:))) | ~isfinite(imag(pages(:))))
    error("sixgr:conformance:RuntimePDSCHPrecodingMismatch", ...
        "PDSCH precoder contains nonfinite coefficients.");
end

rawBundling = entry.allocation.prb_bundling_size;
if ischar(rawBundling) || isstring(rawBundling)
    bundling = lower(strtrim(string(rawBundling)));
else
    bundling = string(double(rawBundling));
end
if bundling == "wideband"
    expectedPRG = 1;
    expectedMode = "explicit-wideband";
else
    bundleSize = str2double(bundling);
    if ~(isfinite(bundleSize) && any(bundleSize == [2, 4]))
        error("sixgr:conformance:RuntimePDSCHPrecodingMismatch", ...
            "Unsupported PDSCH PRB-bundling contract '%s'.", bundling);
    end
    prgInfo = nrPRGInfo(carrier, bundleSize);
    expectedPRG = double(prgInfo.NPRG);
    expectedMode = "explicit-prg-bundled";
end
localAssertNumeric("PDSCH precoder PRG count", size(pages,3), ...
    expectedPRG, "sixgr:conformance:RuntimePDSCHPrecodingMismatch");
actualMode = string(sixgr.util.structGet(precodeInfo, "Mode", ""));
localAssertText("PDSCH precoder mode", actualMode, expectedMode, ...
    "sixgr:conformance:RuntimePDSCHPrecodingMismatch");

pageRanks = zeros(1, size(pages,3));
pagePowers = zeros(1, size(pages,3));
pageDigests = strings(1, size(pages,3));
for pageIndex = 1:size(pages,3)
    page = pages(:,:,pageIndex);
    pageRanks(pageIndex) = rank(page, 1e-11);
    pagePowers(pageIndex) = real(trace(page * page'));
    if pageRanks(pageIndex) ~= nLayers
        error("sixgr:conformance:RuntimePDSCHPrecodingMismatch", ...
            "PDSCH precoder page %d has rank %d; expected %d.", ...
            pageIndex, pageRanks(pageIndex), nLayers);
    end
    if abs(pagePowers(pageIndex) - 1) > 1e-10
        error("sixgr:conformance:RuntimePDSCHPrecodingPowerMismatch", ...
            "PDSCH precoder page %d has trace(W*W') %.16g; expected one.", ...
            pageIndex, pagePowers(pageIndex));
    end
    pageDigests(pageIndex) = sixgr.phy.mimo.MatrixContract.digest(page);
end
evidence = struct( ...
    "TransmissionScheme", "type1_su_mimo", ...
    "TPMI", NaN, "NativeCodebookApplied", true, ...
    "CodebookStatus", "materialized_type1_precoder", ...
    "MatrixSHA256", strjoin(pageDigests, "|"), ...
    "Bundling", bundling, "NumPRG", double(size(pages,3)), ...
    "MatrixRank", double(min(pageRanks)), ...
    "TotalPower", double(max(pagePowers)));
end

function evidence = localAssertPUSCHPrecoder(entry, pusch, precodeInfo)
scheme = lower(string(localProperty(pusch, "TransmissionScheme", "")));
expectedScheme = lower(string(sixgr.util.structGet( ...
    entry.mimo, "precoding_scheme", "noncodebook")));
tpmi = NaN;
nativeApplied = false;
status = "not_applicable_noncodebook";
matrixDigest = "";
if expectedScheme == "codebook"
    tpmi = double(localProperty(pusch, "TPMI", NaN));
    expectedTPMI = double(sixgr.util.structGet( ...
        entry.mimo, "tpmi_index", NaN));
    localAssertNumeric("PUSCH TPMI", tpmi, expectedTPMI, ...
        "sixgr:conformance:RuntimePUSCHPrecodingMismatch");
    if isempty(fieldnames(precodeInfo))
        error("sixgr:conformance:RuntimePUSCHPrecodingEvidenceMissing", ...
            "Exact codebook PUSCH requires PUSCH_Tx.PrecodeInfo evidence.");
    end
    nativeApplied = logical(sixgr.util.structGet( ...
        precodeInfo, "NativeCodebookApplied", false));
    if ~nativeApplied
        error("sixgr:conformance:RuntimePUSCHPrecodingMismatch", ...
            "PUSCH_Tx did not apply the configured native codebook TPMI.");
    end
    [~, expectedStatus, expectedWtx] = ...
        sixgr.phy.ul.puschCodebookProjectionMatrix( ...
        double(entry.mimo.layers), double(entry.mimo.tx_antennas), ...
        expectedTPMI, ...
        logical(entry.waveform.transform_precoding));
    actualWtx = double(sixgr.util.structGet(precodeInfo, "MatrixNR", []));
    if ~isequal(size(actualWtx), size(expectedWtx)) || ...
            max(abs(actualWtx(:) - double(expectedWtx(:)))) > 1e-12
        error("sixgr:conformance:RuntimePUSCHPrecodingMismatch", ...
            "The PUSCH_Tx native codebook matrix differs from TPMI %d.", ...
            round(expectedTPMI));
    end
    actualTPMI = double(sixgr.util.structGet(precodeInfo, "PMI", NaN));
    localAssertNumeric("PUSCH applied TPMI", actualTPMI, ...
        expectedTPMI, ...
        "sixgr:conformance:RuntimePUSCHPrecodingMismatch");
    status = string(sixgr.util.structGet(precodeInfo, "CodebookStatus", ""));
    if status ~= string(expectedStatus)
        localMismatch("sixgr:conformance:RuntimePUSCHPrecodingMismatch", ...
            "PUSCH codebook status", expectedStatus, status);
    end
    matrixDigest = string(sixgr.util.structGet( ...
        precodeInfo, "AppliedMatrixSHA256", ""));
    if strlength(matrixDigest) == 0
        error("sixgr:conformance:RuntimePUSCHPrecodingEvidenceMissing", ...
            "Exact codebook PUSCH requires the applied matrix digest.");
    end
elseif expectedScheme == "noncodebook"
    if scheme ~= "noncodebook"
        localMismatch("sixgr:conformance:RuntimePUSCHPrecodingMismatch", ...
            "PUSCH transmission scheme", expectedScheme, scheme);
    end
    if ~isempty(fieldnames(precodeInfo)) && logical(sixgr.util.structGet( ...
            precodeInfo, "NativeCodebookApplied", false))
        error("sixgr:conformance:RuntimePUSCHPrecodingMismatch", ...
            "Non-codebook PUSCH unexpectedly applied native codebook precoding.");
    end
else
    error("sixgr:conformance:RuntimePUSCHPrecodingMismatch", ...
        "Unsupported catalog PUSCH precoding scheme '%s'.", expectedScheme);
end
evidence = struct( ...
    "TransmissionScheme", scheme, ...
    "TPMI", tpmi, ...
    "NativeCodebookApplied", nativeApplied, ...
    "CodebookStatus", status, ...
    "MatrixSHA256", matrixDigest, ...
    "Bundling", "not_applicable", "NumPRG", NaN, ...
    "MatrixRank", NaN, "TotalPower", NaN);
end

function value = localRequiredField(input, name)
if ~isfield(input, name) || isempty(input.(name))
    error("sixgr:conformance:RuntimePHYEvidenceMissing", ...
        "Truth transmitter output is missing required field '%s'.", name);
end
value = input.(name);
end

function value = localOptionalField(input, name, defaultValue)
value = defaultValue;
if isfield(input, name)
    value = input.(name);
end
end

function value = localProperty(input, name, defaultValue)
value = defaultValue;
if isstruct(input) && isfield(input, name)
    value = input.(name);
elseif isobject(input) && isprop(input, name)
    value = input.(name);
end
end

function localAssertNumeric(label, actual, expected, identifier)
actual = double(actual);
expected = double(expected);
if ~(isscalar(actual) && isfinite(actual) && isscalar(expected) && ...
        isfinite(expected) && abs(actual - expected) <= ...
        16 * eps(max(abs(expected), 1)))
    localMismatch(identifier, label, expected, actual);
end
end

function localAssertVector(label, actual, expected, identifier)
actual = double(actual(:).');
expected = double(expected(:).');
if ~isequal(actual, expected)
    localMismatch(identifier, label, expected, actual);
end
end

function localAssertText(label, actual, expected, identifier)
actual = lower(strtrim(string(actual)));
expected = lower(strtrim(string(expected)));
if ~(isscalar(actual) && isscalar(expected) && actual == expected)
    localMismatch(identifier, label, expected, actual);
end
end

function localMismatch(identifier, label, expected, actual)
error(identifier, ...
    "FRC runtime %s mismatch: configured=%s, effective=%s.", ...
    label, localToken(expected), localToken(actual));
end

function token = localToken(value)
if isnumeric(value) || islogical(value)
    token = string(mat2str(value));
else
    token = "'" + join(string(value(:).'), "|") + "'";
end
end
