function T = refreshISACPlotLineage(runFolder,cfg)
%REFRESHISACPLOTLINEAGE Bind ISAC rasters to their finalized source CSV bytes.

arguments
    runFolder (1,:) char
    cfg (1,1) struct
end

T = table();
if ~logical(sixgr.util.structGet(cfg,"isac.enabled",false)) || ...
        ~logical(sixgr.util.structGet(cfg,"isac.output.enabled",false)) || ...
        ~logical(sixgr.util.structGet(cfg,"isac.output.savePNG",false))
    return;
end

structured = logical(sixgr.util.structGet( ...
    cfg,"isac.output.structuredComponentFolders",false));
component = string(sixgr.util.structGet( ...
    cfg,"isac.output.componentFolder","isac"));
if structured && (~isscalar(component) || ...
        isempty(regexp(char(component),'^[A-Za-z0-9_-]+$','once')))
    error("sixgr:isac:InvalidComponentFolder", ...
        "isac.output.componentFolder must be one safe relative folder name.");
end

if structured
    csvDir = fullfile(runFolder,char(component),"csv");
    imageDir = fullfile(runFolder,char(component),"image");
    csvPrefix = replace(component + "/csv/","\","/");
else
    csvDir = runFolder;
    imageDir = runFolder;
    csvPrefix = "";
end

imageFormat = lower(string(sixgr.util.structGet( ...
    cfg,"isac.output.imageFormat","png")));
if imageFormat == "jpeg"
    extension = ".jpeg";
else
    extension = ".png";
end

plotIds = ["isac_scenario_geometry";"isac_range_profile"; ...
    "isac_range_angle_map";"isac_range_doppler_map"];
imagePaths = fullfile(imageDir,plotIds + extension);
sourceCSVs = [ ...
    csvPrefix + "isac_config_resolved.csv|" + csvPrefix + ...
        "isac_target_truth.csv|" + csvPrefix + "isac_runtime_evidence.csv"; ...
    csvPrefix + "isac_range_profile.csv|" + csvPrefix + ...
        "isac_target_truth.csv"; ...
    csvPrefix + "isac_range_angle_map.csv|" + csvPrefix + ...
        "isac_detections.csv|" + csvPrefix + "isac_target_truth.csv"; ...
    csvPrefix + "isac_range_doppler_map.csv|" + csvPrefix + ...
        "isac_target_truth.csv"];

lineagePath = fullfile(csvDir,"isac_plot_lineage.csv");
T = sixgr.visual.writeComponentPlotLineage( ...
    runFolder,lineagePath,plotIds,imagePaths,sourceCSVs, ...
    "sixgr.lls.exportISACArtifacts", ...
    "SourcesAlreadyFinalized",true);
end
