function [row, diagnostic] = runPDSCHTransportBlock(llsCfg, phyCfg, configHash, snrIndex, trialIndex)
%RUNPDSCHTRANSPORTBLOCK Execute one production PDSCH/DL-SCH waveform trial.

% This adapter intentionally delegates coding, rate matching, scrambling,
% modulation, resource mapping, OFDM, soft demapping, rate recovery, LDPC
% decoding, and CRC authority to the existing production PDSCH Tx/Rx pair.

arguments
    llsCfg (1,1) struct
    phyCfg (1,1) struct
    configHash (1,1) string
    snrIndex (1,1) double {mustBePositive,mustBeInteger}
    trialIndex (1,1) double {mustBePositive,mustBeInteger}
end

snrDb = double(llsCfg.simulation.snrDb(snrIndex));
randomnessKey = string(sixgr.util.structGet(llsCfg, ...
    "simulation.commonRandomKey", llsCfg.scenario.id));
bitSeed = sixgr.lls.deterministicSeed(llsCfg.simulation.masterSeed, ...
    randomnessKey, snrIndex, trialIndex, "transport_bits");
noiseSeed = sixgr.lls.deterministicSeed(llsCfg.simulation.masterSeed, ...
    randomnessKey, snrIndex, trialIndex, "awgn");
channelSeed = sixgr.lls.deterministicSeed(llsCfg.channel.seed, ...
    randomnessKey, snrIndex, trialIndex, "channel");

phyCfg.phy.carrier.NSlot = mod(trialIndex-1, ...
    10 * round(double(phyCfg.phy.carrier.SubcarrierSpacing)/15));
previousRng = rng;
restoreRng = onCleanup(@() rng(previousRng)); %#ok<NASGU>
rng(bitSeed, "twister");
trialClock = tic;
[tx, txInfo] = sixgr.phy.dl.PDSCH_Tx(phyCfg, ...
    "ExecutionProfile", "phy_calibration", ...
    "NumTxAnt", double(llsCfg.channel.txAntennas), ...
    "CompactOutput", false);

dataSymbols = tx.PDSCHSymbolsForEvidence(:);
signalEnergyPerOccupiedRE = mean(abs(dataSymbols).^2);
if ~(isscalar(signalEnergyPerOccupiedRE) && isfinite(signalEnergyPerOccupiedRE) ...
        && signalEnergyPerOccupiedRE > 0)
    error("sixgr:lls:InvalidOccupiedREEnergy", ...
        "PDSCH transmitter did not produce finite positive occupied-RE symbol energy.");
end
[channelWaveform, trueChannelGrid, channelInfo] = sixgr.lls.applyChannel( ...
    tx.Waveform, tx.Carrier, llsCfg, channelSeed);
[rxWaveform, noiseInfo] = sixgr.conformance.addReferenceNoise( ...
    channelWaveform, tx.Carrier, snrDb, ...
    "Seed", noiseSeed, ...
    "SignalEnergyPerOccupiedRE", signalEnergyPerOccupiedRE);
noiseWaveform = rxWaveform - channelWaveform;
[noiseGrid, noiseGridInfo] = sixgr.phy.waveform.ofdmDemodulate(tx.Carrier, noiseWaveform);
measuredGridNoiseVariance = mean(abs(noiseGrid(:)).^2);
measuredSNRdB = 10*log10(signalEnergyPerOccupiedRE / measuredGridNoiseVariance);

[rx, rxInfo] = sixgr.phy.dl.PDSCH_Rx(rxWaveform, phyCfg, ...
    "Carrier", tx.Carrier, ...
    "PDSCH", tx.PDSCH, ...
    "PDSCHIndices", tx.PDSCHIndices, ...
    "TransportBlockSize", tx.TransportBlockSize, ...
    "TargetCodeRate", tx.TargetCodeRate, ...
    "RV", tx.RV, ...
    "CodingPlan", tx.CodingPlans, ...
    "NoiseVar", noiseInfo.GridNoiseVariance, ...
    "NoiseVarDomain", "grid", ...
    "MaxIterations", double(llsCfg.receiver.ldpcMaxIterations), ...
    "Algorithm", char(string(llsCfg.receiver.ldpcAlgorithm)), ...
    "ExecutionProfile", "phy_calibration", ...
    "CompactOutput", false, ...
    "FastAWGNPath", strcmpi(string(llsCfg.channel.model), "AWGN"), ...
    "SkipTimingEstimate", true);

txBits = int8(tx.TransportBlock(:));
rxBits = int8(rx.TransportBlock(:));
if numel(txBits) ~= numel(rxBits)
    bitErrors = numel(txBits);
else
    bitErrors = sum(txBits ~= rxBits);
end
crcError = logical(rx.CRCError);
if crcError ~= ~logical(rx.Ok)
    error("sixgr:lls:CRCStatusInconsistent", ...
        "PDSCH receiver Ok and CRCError fields are inconsistent.");
end

accounting = tx.ResourceAccounting;
runtimeSeconds = toc(trialClock);
row = struct( ...
    "ScenarioId", string(llsCfg.scenario.id), ...
    "ConfigSHA256", configHash, ...
    "SNRIndex", double(snrIndex), ...
    "TrialIndex", double(trialIndex), ...
    "TargetSNRdB", snrDb, ...
    "MeasuredSNRdB", measuredSNRdB, ...
    "BitSeed", double(bitSeed), ...
    "NoiseSeed", double(noiseSeed), ...
    "ChannelSeed", double(channelSeed), ...
    "TransportBlockSizeBits", double(numel(txBits)), ...
    "BitErrors", double(bitErrors), ...
    "CRCError", crcError, ...
    "ACK", ~crcError, ...
    "DataREPerLayer", double(accounting.LayerDataRE), ...
    "DMRSRE", double(accounting.DMRSRE), ...
    "PTRSRE", double(accounting.PTRSRE), ...
    "ReservedRE", double(accounting.ReservedRE), ...
    "CodedBitsG", double(accounting.CodedBitCountG), ...
    "ModulationOrder", double(localModulationOrder(llsCfg.pdsch.modulation)), ...
    "TargetCodeRate", double(tx.TargetCodeRate(1)), ...
    "NumLayers", double(tx.PDSCH.NumLayers), ...
    "NumTxPorts", double(llsCfg.pdsch.numberAntennaPorts), ...
    "NumRxAntennas", double(size(rxWaveform,2)), ...
    "SignalEnergyPerOccupiedRE", double(signalEnergyPerOccupiedRE), ...
    "RequestedGridNoiseVariance", double(noiseInfo.GridNoiseVariance), ...
    "MeasuredGridNoiseVariance", double(measuredGridNoiseVariance), ...
    "SampleNoiseVariance", double(noiseInfo.SampleNoiseVariance), ...
    "SampleToGridNoiseGain", double(noiseInfo.SampleToGridNoiseVarianceGain), ...
    "FFTSize", double(localFFTSize(tx.OFDM)), ...
    "ActiveSubcarriers", double(tx.Carrier.NSizeGrid*12), ...
    "WaveformSamples", double(size(tx.Waveform,1)), ...
    "ChannelModel", string(llsCfg.channel.model), ...
    "ChannelRealizationSource", string(channelInfo.Source), ...
    "TrueChannelGridAvailable", logical(channelInfo.TrueChannelGridAvailable), ...
    "TrueChannelGridVariance", double(sixgr.util.structGet(channelInfo, "TrueChannelGridVariance", 0)), ...
    "TrueChannelGridSHA256", localComplexHash(trueChannelGrid), ...
    "ChannelTimingOffsetSamples", double(channelInfo.TimingOffsetSamples), ...
    "MaximumDopplerHz", double(channelInfo.MaximumDopplerHz), ...
    "ChannelEstimationMode", string(llsCfg.receiver.channelEstimation), ...
    "ChannelEstimateSource", string(rx.ChannelEstimateSource), ...
    "ChannelEstimateEngine", string(rx.ChannelEstimateEngine), ...
    "Equalizer", string(llsCfg.receiver.equalizer), ...
    "LLRSource", "nrPDSCHDecode_soft_llr", ...
    "LDPCSource", "sixgr_pdsch_actual_ldpc_rate_recovery_decode", ...
    "CRCSource", "decoded_transport_block_crc", ...
    "TxProcessChain", "tb_crc_ldpc_rate_match_scramble_qam_layers_precoding_grid_dmrs_ofdm", ...
    "RxProcessChain", "ofdm_dmrs_channel_estimate_equalize_soft_llr_rate_recover_ldpc_tb_crc", ...
    "RuntimeSeconds", runtimeSeconds);

diagnostic = struct("Tx",tx,"Rx",rx,"TxInfo",txInfo,"RxInfo",rxInfo, ...
    "NoiseInfo",noiseInfo,"NoiseGridInfo",noiseGridInfo);
end

function q = localModulationOrder(modulation)
switch upper(string(modulation))
    case "QPSK"
        q = 2;
    case "16QAM"
        q = 4;
    case "64QAM"
        q = 6;
    case "256QAM"
        q = 8;
    otherwise
        error("sixgr:lls:UnsupportedModulation", ...
            "Unsupported PDSCH modulation %s.", string(modulation));
end
end

function nfft = localFFTSize(info)
nfft = double(sixgr.util.structGet(info, "Nfft", ...
    sixgr.util.structGet(info, "NFFT", NaN)));
end

function digest = localComplexHash(value)
realBytes = typecast(double(real(value(:))), "uint8");
imagBytes = typecast(double(imag(value(:))), "uint8");
digest = sixgr.util.sha256Hex([realBytes(:); imagBytes(:)]);
end
