function contract = truthContract(llsCfg, trialTable)
%TRUTHCONTRACT Create and validate the explicit waveform-truth declaration.

if isempty(trialTable) || height(trialTable) == 0
    error("sixgr:lls:MissingTrialTruth", ...
        "A valid LLS result requires at least one executed transport-block trial.");
end
expectedLLRSource = "nr" + upper(string(llsCfg.simulation.link)) + "Decode_soft_llr";
requiredSources = all(trialTable.CRCSource == "decoded_transport_block_crc") && ...
    all(trialTable.LLRSource == expectedLLRSource) && ...
    all(trialTable.TrueChannelGridAvailable) && ...
    all(ismember(upper(trialTable.ChannelModel), ...
        ["AWGN","TDL-A","TDL-B","TDL-C","TDL-D","TDL-E", ...
         "CDL-A","CDL-B","CDL-C","CDL-D","CDL-E"]));
if ~requiredSources
    error("sixgr:lls:TruthContractViolation", ...
        "Trial provenance does not prove the required decoded waveform chain.");
end
resourceEvidence = all(trialTable.DataREPerLayer > 0) && ...
    all(trialTable.DMRSRE > 0) && all(trialTable.CodedBitsG > 0) && ...
    all(trialTable.FFTSize > 0) && all(trialTable.ModulationOrder > 0);
if ~resourceEvidence
    error("sixgr:lls:TruthContractViolation", ...
        "Executed trials are missing exact resource-grid/coded-bit/OFDM evidence.");
end
ldpcBackendEvidence = localLDPCBackendEvidence(llsCfg,trialTable);
if ~ldpcBackendEvidence
    error("sixgr:lls:LDPCBackendContractViolation", ...
        "Runtime LDPC backend does not match receiver.useMexLDPC authority.");
end
fixedAllocationEvidence = numel(unique(trialTable.TransportBlockSizeBits)) == 1 && ...
    numel(unique(trialTable.CodedBitsG)) == 1 && ...
    numel(unique(trialTable.TargetCodeRate)) == 1 && ...
    numel(unique(trialTable.ModulationOrder)) == 1 && ...
    numel(unique(trialTable.NumLayers)) == 1;
linkAdaptationEnabled = logical(sixgr.util.structGet(llsCfg,"linkAdaptation.enabled",false));
if ~fixedAllocationEvidence && ~linkAdaptationEnabled
    error("sixgr:lls:FixedMCSContractViolation", ...
        "Basic LLS curve changed TBS, G, code rate, modulation, or rank across the SNR sweep.");
end
linkAdaptationEvidence = localLinkAdaptationEvidence(llsCfg,trialTable);
if ~linkAdaptationEvidence
    error("sixgr:lls:LinkAdaptationTruthContractViolation", ...
        "Link adaptation must be causal and every selected MCS must match its decoded waveform trial.");
end
statisticalClass = string(llsCfg.simulation.statisticalClass);
harqEnabled = logical(sixgr.util.structGet(llsCfg,"harq.enabled",false));
harqEvidence = ~harqEnabled || localHARQEvidence(trialTable);
if ~harqEvidence
    error("sixgr:lls:HARQTruthContractViolation", ...
        "HARQ retransmissions must reuse packet identity and apply position-aware soft combining.");
end
interferenceEvidence = localInterferenceEvidence(llsCfg,trialTable);
if ~interferenceEvidence
    error("sixgr:lls:InterferenceTruthContractViolation", ...
        "Interference evidence must prove an independently encoded waveform/channel and calibrated D/I ratio.");
end
configuredPublicationBudget = statisticalClass == "publication_candidate" && ...
    double(llsCfg.simulation.minTransportBlocks) >= 1000 && ...
    double(llsCfg.simulation.minBlockErrors) >= 100 && ...
    double(llsCfg.simulation.maxTransportBlocks) >= double(llsCfg.simulation.minTransportBlocks);
executedStoppingRuleSatisfied = localExecutedStoppingRuleSatisfied(llsCfg,trialTable);
publicationEligible = configuredPublicationBudget && executedStoppingRuleSatisfied;
contract = table( ...
    string(llsCfg.scenario.id), ...
    true, true, true, true, true, true, true, true, true, true, true, true, ...
    true, true, true, true, harqEvidence, true, interferenceEvidence, ...
    linkAdaptationEvidence,ldpcBackendEvidence, ...
    false, false, false, false, ...
    statisticalClass, configuredPublicationBudget,executedStoppingRuleSatisfied, ...
    publicationEligible, "valid_waveform_truth", ...
    'VariableNames', { ...
    'ScenarioId','WaveformGenerated','ActualLDPC','ActualRateMatching','ActualScrambling', ...
    'ActualModulation','ActualLayerMapping','ActualPrecoding','ActualResourceGrid','ActualOFDM', ...
    'ActualDMRS','ActualChannel','ActualNoise','ActualEqualization','ActualSoftDemapping', ...
    'ActualLDPCDecode','ActualCRC','ActualHARQ','HARQMetricSeparation','ActualInterference', ...
    'ActualLinkAdaptation','ConfiguredLDPCBackendExecuted', ...
    'UsesBLERLookupTable','UsesSyntheticBLER', ...
    'UsesRandomPassFailModel','UsesGeometryAsLLS','StatisticalClass', ...
    'ConfiguredPublicationBudget','ExecutedStoppingRuleSatisfied', ...
    'PublicationEligible','Status'});
end

function valid = localLDPCBackendEvidence(cfg,trials)
required = ["UseMexLDPC","LDPCDecoderEngine"];
valid = all(ismember(required,string(trials.Properties.VariableNames)));
if ~valid
    return;
end
configured = logical(cfg.receiver.useMexLDPC);
if configured
    valid = all(trials.UseMexLDPC) && ...
        all(contains(trials.LDPCDecoderEngine,"ldpc_decode_batch_kernel"));
else
    valid = ~any(trials.UseMexLDPC) && ...
        all(trials.LDPCDecoderEngine == "sixgr.phy.phycode.ldpcDecode");
end
end

function valid = localExecutedStoppingRuleSatisfied(cfg,trials)
indices = unique(double(trials.SNRIndex(:).'));
expected = 1:numel(double(cfg.simulation.snrDb));
valid = isequal(indices,expected);
if ~valid
    return;
end
minN = double(cfg.simulation.minTransportBlocks);
minErrors = double(cfg.simulation.minBlockErrors);
maxN = double(cfg.simulation.maxTransportBlocks);
study = lower(string(cfg.simulation.studyType));
for snrIndex = indices
    point = trials(trials.SNRIndex == snrIndex,:);
    if study == "harq_throughput"
        packetRows = point(point.AttemptIndex == 1,:);
        n = height(packetRows);
        if lower(string(cfg.harq.stoppingMetric)) == "post_harq_residual_bler"
            errors = sum(packetRows.FinalPacketCRCError);
        else
            errors = sum(packetRows.FirstTransmissionCRCError);
        end
    else
        n = height(point);
        errors = sum(point.CRCError);
    end
    valid = n >= minN && (errors >= minErrors || n >= maxN);
    if ~valid
        return;
    end
end
end

function valid = localLinkAdaptationEvidence(cfg,trials)
enabled = logical(sixgr.util.structGet(cfg,"linkAdaptation.enabled",false));
required = ["LinkAdaptationEnabled","LinkAdaptationDecisionSource", ...
    "LinkAdaptationFeedbackTrialIndex","LinkAdaptationFeedbackSINRdB", ...
    "LinkAdaptationSelectedCQI","LinkAdaptationSelectedMCSIndex", ...
    "LinkAdaptationThresholdSource","LinkAdaptationThresholdValueRole", ...
    "LinkAdaptationThresholdCalibrationId","MCSIndex","MCSTable","Modulation"];
if ~enabled
    valid = ~ismember("LinkAdaptationEnabled",string(trials.Properties.VariableNames)) || ...
        ~any(trials.LinkAdaptationEnabled);
    return;
end
valid = all(ismember(required,string(trials.Properties.VariableNames))) && ...
    all(trials.LinkAdaptationEnabled) && ...
    trials.LinkAdaptationDecisionSource(1) == "configured_bootstrap_mcs" && ...
    trials.LinkAdaptationFeedbackTrialIndex(1) == 0 && ...
    all(trials.LinkAdaptationDecisionSource(2:end) == ...
        "previous_trial_receiver_post_equalization_sinr") && ...
    all(trials.LinkAdaptationFeedbackTrialIndex(2:end) == trials.TrialIndex(1:end-1)) && ...
    all(trials.LinkAdaptationSelectedMCSIndex == trials.MCSIndex) && ...
    all(strlength(trials.LinkAdaptationThresholdSource) > 0) && ...
    all(strlength(trials.LinkAdaptationThresholdCalibrationId) > 0);
if ~valid
    return;
end
for index = 1:height(trials)
    profile = sixgr.link.resolveMCSProfile(trials.MCSTable(index),trials.MCSIndex(index));
    valid = profile.Valid && strcmpi(string(profile.Modulation),trials.Modulation(index)) && ...
        abs(double(profile.TargetCodeRate)-double(trials.TargetCodeRate(index))) <= 1e-12;
    if ~valid
        return;
    end
end
end

function valid = localInterferenceEvidence(cfg,trials)
required = ["InterferenceEnabled","InterfererWaveformCount","ConfiguredDIRdB", ...
    "MeasuredDIRdB","MeasuredPreEqualizationSINRdB","InterferenceSource"];
valid = all(ismember(required,string(trials.Properties.VariableNames)));
if ~valid
    return;
end
enabled = logical(sixgr.util.structGet(cfg,"interference.enabled",false));
if enabled
    valid = all(trials.InterferenceEnabled) && ...
        all(trials.InterfererWaveformCount == 1) && ...
        all(trials.InterferenceSource == "independent_transport_block_waveform_and_channel") && ...
        all(isfinite(trials.ConfiguredDIRdB)) && all(isfinite(trials.MeasuredDIRdB)) && ...
        all(isfinite(trials.MeasuredPreEqualizationSINRdB)) && ...
        all(abs(trials.MeasuredDIRdB-trials.ConfiguredDIRdB) <= 0.05);
else
    valid = ~any(trials.InterferenceEnabled) && ...
        all(trials.InterfererWaveformCount == 0) && ...
        all(trials.InterferenceSource == "disabled");
end
end

function valid = localHARQEvidence(trials)
required = ["PacketIndex","AttemptIndex","IsRetransmission", ...
    "RV","HARQSoftCombiningApplied","FirstTransmissionCRCError", ...
    "FinalPacketCRCError","PacketTransmissions"];
valid = all(ismember(required,string(trials.Properties.VariableNames)));
if ~valid
    return;
end
retransmissions = trials.AttemptIndex > 1;
valid = all(trials.IsRetransmission == retransmissions) && ...
    all(trials.HARQSoftCombiningApplied(retransmissions)) && ...
    all(trials.RV >= 0 & trials.RV <= 3) && ...
    all(trials.PacketTransmissions >= trials.AttemptIndex);
end
