function contract = truthContract(llsCfg, trialTable)
%TRUTHCONTRACT Create and validate the explicit waveform-truth declaration.

if isempty(trialTable) || height(trialTable) == 0
    error("sixgr:lls:MissingTrialTruth", ...
        "A valid LLS result requires at least one executed transport-block trial.");
end
expectedLLRSource = "nr" + upper(string(llsCfg.simulation.link)) + "Decode_soft_llr";
requiredSources = all(trialTable.CRCSource == "decoded_transport_block_crc") && ...
    all(trialTable.LLRSource == expectedLLRSource) && ...
    all(trialTable.TrueChannelGridAvailable) && ...
    all(ismember(upper(trialTable.ChannelModel), ...
        ["AWGN","TDL-A","TDL-B","TDL-C","TDL-D","TDL-E", ...
         "CDL-A","CDL-B","CDL-C","CDL-D","CDL-E"]));
if ~requiredSources
    error("sixgr:lls:TruthContractViolation", ...
        "Trial provenance does not prove the required decoded waveform chain.");
end
resourceEvidence = all(trialTable.DataREPerLayer > 0) && ...
    all(trialTable.DMRSRE > 0) && all(trialTable.CodedBitsG > 0) && ...
    all(trialTable.FFTSize > 0) && all(trialTable.ModulationOrder > 0);
if ~resourceEvidence
    error("sixgr:lls:TruthContractViolation", ...
        "Executed trials are missing exact resource-grid/coded-bit/OFDM evidence.");
end
fixedAllocationEvidence = numel(unique(trialTable.TransportBlockSizeBits)) == 1 && ...
    numel(unique(trialTable.CodedBitsG)) == 1 && ...
    numel(unique(trialTable.TargetCodeRate)) == 1 && ...
    numel(unique(trialTable.ModulationOrder)) == 1 && ...
    numel(unique(trialTable.NumLayers)) == 1;
if ~fixedAllocationEvidence
    error("sixgr:lls:FixedMCSContractViolation", ...
        "Basic LLS curve changed TBS, G, code rate, modulation, or rank across the SNR sweep.");
end
statisticalClass = string(llsCfg.simulation.statisticalClass);
publicationEligible = statisticalClass == "publication_candidate" && ...
    double(llsCfg.simulation.minTransportBlocks) >= 1000 && ...
    double(llsCfg.simulation.minBlockErrors) >= 100 && ...
    double(llsCfg.simulation.maxTransportBlocks) >= double(llsCfg.simulation.minTransportBlocks);
contract = table( ...
    string(llsCfg.scenario.id), ...
    true, true, true, true, true, true, true, true, true, true, true, true, ...
    true, true, true, true, ...
    false, false, false, false, ...
    statisticalClass, publicationEligible, "valid_waveform_truth", ...
    'VariableNames', { ...
    'ScenarioId','WaveformGenerated','ActualLDPC','ActualRateMatching','ActualScrambling', ...
    'ActualModulation','ActualLayerMapping','ActualPrecoding','ActualResourceGrid','ActualOFDM', ...
    'ActualDMRS','ActualChannel','ActualNoise','ActualEqualization','ActualSoftDemapping', ...
    'ActualLDPCDecode','ActualCRC','UsesBLERLookupTable','UsesSyntheticBLER', ...
    'UsesRandomPassFailModel','UsesGeometryAsLLS','StatisticalClass','PublicationEligible','Status'});
end
