function [report, valid] = validateResults(cfg, summaryTable, trialTable, truthContract)
%VALIDATERESULTS Evaluate fail-closed scientific result invariants.

toleranceDb = double(sixgr.util.structGet(cfg, "results.snrCalibrationToleranceDb", 0.5));
checks = [ ...
    localCheck("bler_range", all(summaryTable.BLER >= 0 & summaryTable.BLER <= 1), "0 <= BLER <= 1");
    localCheck("bler_monotonic", all(diff(summaryTable.BLER) <= 0), "BLER is non-increasing on ordered SNR points");
    localCheck("error_counts", all(summaryTable.NumBlockErrors <= summaryTable.NumTB), "block errors do not exceed transmitted TBs");
    localCheck("confidence_intervals", all(summaryTable.BLERLowerCI >= 0 & summaryTable.BLERUpperCI <= 1 & ...
        summaryTable.BLERLowerCI <= summaryTable.BLER+1e-12 & ...
        summaryTable.BLER <= summaryTable.BLERUpperCI+1e-12), ...
        "Wilson confidence intervals contain empirical BLER");
    localCheck("decoder_crc_authority", all(trialTable.CRCSource == "decoded_transport_block_crc"), ...
        "every ACK/NACK comes from decoded TB CRC");
    localCheck("soft_llr_authority", all(trialTable.LLRSource == ...
        "nr" + upper(string(cfg.simulation.link)) + "Decode_soft_llr"), ...
        "LDPC receives waveform-derived soft LLRs");
    localCheck("snr_calibration", all(abs(trialTable.MeasuredSNRdB-trialTable.TargetSNRdB) <= toleranceDb), ...
        compose("every measured injected Es/N0 is within %.3g dB", toleranceDb));
    localCheck("configuration_hash", all(strlength(trialTable.ConfigSHA256) == 64), ...
        "every trial contains a SHA-256 configuration hash");
    localCheck("fixed_mcs_tbs", numel(unique(trialTable.TransportBlockSizeBits)) == 1 && ...
        numel(unique(trialTable.CodedBitsG)) == 1 && ...
        numel(unique(trialTable.TargetCodeRate)) == 1 && ...
        numel(unique(trialTable.ModulationOrder)) == 1, ...
        "TBS/G/code-rate/modulation remain fixed across SNR");
    localCheck("truth_contract", all(truthContract{1,["WaveformGenerated","ActualLDPC", ...
        "ActualRateMatching","ActualDMRS","ActualChannel","ActualNoise", ...
        "ActualEqualization","ActualSoftDemapping","ActualLDPCDecode","ActualCRC"]}), ...
        "required waveform truth blocks executed");
    localCheck("no_link_abstraction", ~truthContract.UsesBLERLookupTable && ...
        ~truthContract.UsesSyntheticBLER && ~truthContract.UsesRandomPassFailModel && ...
        ~truthContract.UsesGeometryAsLLS, ...
        "no lookup/synthetic/random-pass/geometry LLS source was active")];
report = struct2table(checks);
valid = all(report.Pass);
end

function row = localCheck(name, pass, evidence)
row = struct("Check",string(name),"Pass",logical(pass), ...
    "Status",string(localStatus(pass)),"Evidence",string(evidence));
end

function value = localStatus(pass)
if pass
    value = "PASS";
else
    value = "FAIL";
end
end
