classdef ConservationLedger
    %CONSERVATIONLEDGER Exact per-flow byte conservation checks.
    methods (Static)
        function result=reconcile(arrived,queued,inFlight,delivered,dropped, ...
                unowned,duplicateDelivered)
            values=double([arrived queued inFlight delivered dropped ...
                unowned duplicateDelivered]);
            if any(values<0) || any(values~=fix(values))
                error("sixgr:mac:InvalidConservationInput", ...
                    "Byte counters must be nonnegative integers.");
            end
            equationError=arrived-(queued+inFlight+delivered+dropped);
            result=struct("ArrivedBytes",arrived,"QueuedBytes",queued, ...
                "InFlightBytes",inFlight,"DeliveredBytes",delivered, ...
                "DroppedBytes",dropped,"UnownedBytes",unowned, ...
                "DuplicateDeliveredBytes",duplicateDelivered, ...
                "EquationErrorBytes",equationError, ...
                "Passed",equationError==0 && unowned==0 && duplicateDelivered==0);
            if ~result.Passed
                error("sixgr:mac:ConservationViolation", ...
                    "Packet/byte conservation failed.");
            end
        end
    end
end
