function [fits, deferral] = harqRetransmissionFitsSymbolBudget(grant, budgetAllocation)
% Retain the stored TB/allocation until this data opportunity can carry it.
% This does not resolve flexible symbols, truncate a codeword, or consume RV.
allocation=double(grant.SymbolAllocation(:).');
budgetAllocation=double(budgetAllocation(:).');
validateattributes(allocation,{'numeric'}, ...
    {'real','finite','integer','nonnegative','numel',2});
validateattributes(budgetAllocation,{'numeric'}, ...
    {'real','finite','integer','nonnegative','numel',2});
assert(allocation(2)>0,'sixgr:mac:InvalidHARQSymbolAllocation', ...
    'A stored HARQ allocation must have a positive symbol count.');
fits=budgetAllocation(2)>0 && allocation(1)>=budgetAllocation(1) && ...
    sum(allocation)<=sum(budgetAllocation);
deferral=table();
if ~fits
    deferral=table(double(grant.Slot),double(grant.RNTI), ...
        double(grant.HARQ.HarqID),string(grant.Direction), ...
        allocation,budgetAllocation,"stored_allocation_outside_symbol_budget", ...
        'VariableNames',{'Slot','RNTI','HARQProcess','Direction', ...
        'StoredSymbolAllocation','AvailableSymbolAllocation','Reason'});
end
end
