function out = buildSLSCampaignCases(cfg)
%BUILDSLSCAMPAIGNCASES Expand the paired AI 10.3.2 SLS case matrix.
%
% The builder is planning-only: it emits immutable case rows and explicit
% configuration deltas, but never launches a simulator. Each expanded
% CasePairKey contains exactly S0--S5 with an unchanged paired-drop seed
% bundle and frozen FTP3 arrival-stream identity.

arguments
    cfg struct
end

cfg = sixgr.studies.ran1ai1032.validateStudyConfig(cfg);
paired = sixgr.studies.ran1ai1032.buildPairedDropPlan(cfg);
base = paired.Plan;
sls = cfg.sls;
reservationPolicy=sixgr.lls6g.config.readConfigFile(string(sls.execution.resource_reservation_policy_path));
entries=sixgr.studies.ran1ai1032.MCSCatalog.optionA();
entryIDs=string(cfg.lls.execution.entry_ids);
firstEntry=entries(entries.entry_id==entryIDs(1),:);
rfBranch=sixgr.studies.ran1ai1032.resolveF1RFBranch(cfg,string(2^double(firstEntry.Qm))+"QAM");
rfIdentity=sixgr.studies.ran1ai1032.rfBranchIdentity(rfBranch);
reservationPolicy.system.linkAbstraction.requiredRFProfileID=rfIdentity;
assert(logical(reservationPolicy.system.resourceReservations.enabled) && ...
    logical(reservationPolicy.system.resourceReservations.commonChannelCalendarEnabled), ...
    'sixgr:ran1ai1032:ResourceReservationPolicy','Study requires control and common-channel reservations.');
txCases = sls.ue_tx_chain_cases;
powerCases = sls.ue_power_cases;
spatialModes = sls.spatial_modes;
deploymentIDs = string({sls.deployments.id});
deploymentTopologies = cell(numel(sls.deployments), 1);
for deploymentIndex = 1:numel(sls.deployments)
    deployment = sls.deployments(deploymentIndex);
    topology = sixgr.studies.ran1ai1032.buildHexWraparoundTopology( ...
        double(sls.sites), double(sls.sectors_per_site), ...
        double(deployment.inter_site_distance_m));
    sixgr.studies.ran1ai1032.validateSLSHexTopology(topology);
    deploymentTopologies{deploymentIndex} = topology;
end

nVariant = numel(txCases) * numel(powerCases) * numel(spatialModes);
nRow = height(base) * nVariant;
rows = repmat(localEmptyRow(), nRow, 1);
rowIndex = 0;
for b = 1:height(base)
    source = base(b, :);
    deploymentIndex = find(deploymentIDs == source.Scenario, 1, "first");
    if isempty(deploymentIndex)
        error("sixgr:ran1ai1032:MissingDeploymentDefinition", ...
            "Scenario %s must have exactly one deployment definition.", ...
            source.Scenario);
    end
    topology = deploymentTopologies{deploymentIndex};
    for txIndex = 1:numel(txCases)
        tx = txCases(txIndex);
        for spatialIndex = 1:numel(spatialModes)
            spatial = spatialModes(spatialIndex);
            for powerIndex = 1:numel(powerCases)
                power = powerCases(powerIndex);
                rowIndex = rowIndex + 1;
                rows(rowIndex) = localBuildRow(cfg, source, tx, spatial, ...
                    power, topology, reservationPolicy);
            end
        end
    end
end

cases = struct2table(rows, "AsArray", true);
validation = sixgr.studies.ran1ai1032.validateSLSCampaignCases(cases, cfg);
out = struct( ...
    "Cases", cases, ...
    "BasePairedDropPlan", paired, ...
    "BasePairCount", paired.PairCount, ...
    "VariantCountPerComparator", nVariant, ...
    "CasePairCount", numel(unique(cases.CasePairKey)), ...
    "CaseCount", height(cases), ...
    "Validation", validation, ...
    "Status", "PASS");
end

function row = localBuildRow(cfg, source, tx, spatial, power, topology, reservationPolicy)
txChains = double(tx.tx_chains);
declaredMaxRank = double(source.MaxRank);
effectiveMaxRank = min(declaredMaxRank, txChains);
physicalRankLimited = effectiveMaxRank < declaredMaxRank;
casePairKey = source.PairKey + ":" + string(tx.id) + ":" + ...
    string(spatial.id) + ":" + string(power.id);
caseID = casePairKey + ":" + source.ComparatorID;
wrapMode = "hex_cluster_min_image";

delta = struct();
delta.study = struct( ...
    "id", char(string(cfg.study.id)), ...
    "case_id", char(caseID), ...
    "case_pair_key", char(casePairKey), ...
    "comparator_id", char(source.ComparatorID), ...
    "representation", char(source.Representation));
% This is a planned execution contract, not proof that calibration or the
% network backend has completed. Keep the execution gate below closed.
delta.study.sls_execution=cfg.sls.execution;
delta.system=reservationPolicy.system;
delta.study.planned_rf_branch=char(cfg.lls.execution.rf_branch);
delta.scenario = struct( ...
    "profileName", char(source.Scenario), ...
    "layout", struct("nSites", double(cfg.sls.sites), ...
        "nSectorsPerSite", double(cfg.sls.sectors_per_site), ...
        "interSiteDistance_m", double(topology.InterSiteDistance_m), ...
        "wraparound", logical(cfg.sls.wrap_around), ...
        "wraparoundMode", char(wrapMode), ...
        "wraparoundTranslationVectors_m", topology.TranslationVectors_m), ...
    "geometry", struct("deployment", "hex_grid", ...
        "wraparound", logical(cfg.sls.wrap_around), ...
        "wraparoundMode", char(wrapMode), ...
        "wraparoundTranslationVectors_m", topology.TranslationVectors_m), ...
    "ue", struct("txPower_dBm", double(power.tx_power_dbm), ...
        "nTxAnt", txChains, ...
        "nUE", double(cfg.sls.cells) * double(cfg.sls.ues_per_cell), ...
        "population_profile", char(source.Population), ...
        "population_assumption_source", ...
        char(cfg.sls.ue_count_assumption_source)));
delta.channel = struct("propagationScenario", char(source.Scenario));
delta.traffic = struct("model", "ftp3", ...
    "arrivalStreamID", char(source.ArrivalStreamID), ...
    "arrivalRateAuthority", char(cfg.sls.ftp3.arrival_rate_policy), ...
    "ftp3", struct( ...
        "fileSizeBytes", double(cfg.sls.ftp3.file_size_bytes), ...
        "direction", char(cfg.sls.ftp3.direction), ...
        "seed", double(source.TrafficSeed)));
delta.antenna_and_array = struct("ue_num_txrus", txChains);
delta.mimo = struct( ...
    "mu_mimo_enable", logical(spatial.mu_mimo_enabled), ...
    "ul_mu_mimo_enable", logical(spatial.ul_mu_mimo_enabled), ...
    "max_rank", effectiveMaxRank, ...
    "rank_adaptation_policy", "adaptive");
delta.phy = struct("pusch", struct( ...
    "numLayers", double(cfg.sls.rank_policy.initial_rank), ...
    "maxLayers", effectiveMaxRank, ...
    "NumAntennaPorts", txChains));
delta.link_adaptation = struct( ...
    "rank_policy", "adaptive", ...
    "constant_total_ue_power_across_ranks", true);
delta.random = struct( ...
    "geometry_seed", double(source.GeometrySeed), ...
    "shadow_seed", double(source.ShadowSeed), ...
    "traffic_seed", double(source.TrafficSeed), ...
    "antenna_orientation_seed", double(source.AntennaOrientationSeed), ...
    "scheduler_seed", double(source.SchedulerSeed), ...
    "propagation_seed", double(source.PropagationSeed));
executionParameters = struct("SeedBundle", struct( ...
    "GeometrySeed", double(source.GeometrySeed), ...
    "ShadowSeed", double(source.ShadowSeed), ...
    "TrafficSeed", double(source.TrafficSeed), ...
    "AntennaOrientationSeed", double(source.AntennaOrientationSeed), ...
    "SchedulerSeed", double(source.SchedulerSeed), ...
    "PropagationSeed", double(source.PropagationSeed)), ...
    "FWAPopulationSpec", struct( ...
        "ProfileID", char(source.Population), ...
        "PopulationSeed", double(source.GeometrySeed), ...
        "ExpectedUECount", double(cfg.sls.cells) * ...
            double(cfg.sls.ues_per_cell)));

identity = struct( ...
    "CasePairKey", char(casePairKey), ...
    "BasePairKey", char(source.PairKey), ...
    "SeedBundleID", char(source.SeedBundleID), ...
    "ArrivalStreamID", char(source.ArrivalStreamID), ...
    "ComparatorID", char(source.ComparatorID), ...
    "ConfigDelta", delta);
digest = string(sixgr.util.sha256Hex(uint8(unicode2native( ...
    jsonencode(identity), "UTF-8"))));

row = localEmptyRow();
row.CaseID = caseID;
row.CasePairKey = casePairKey;
row.BasePairKey = source.PairKey;
row.Scenario = source.Scenario;
row.Population = source.Population;
row.TargetRUPercent = source.TargetRUPercent;
row.IndependentDropID = source.IndependentDropID;
row.ComparatorID = source.ComparatorID;
row.Representation = source.Representation;
row.UETxCase = string(tx.id);
row.UETxChains = txChains;
row.SpatialMode = string(spatial.id);
row.SpatialRole = string(spatial.role);
row.MUMIMOEnabled = logical(spatial.mu_mimo_enabled);
row.ULMUMIMOEnabled = logical(spatial.ul_mu_mimo_enabled);
row.PowerCase = string(power.id);
row.PowerRole = string(power.role);
row.UETxPower_dBm = double(power.tx_power_dbm);
row.InitialRank = double(cfg.sls.rank_policy.initial_rank);
row.ComparatorMaxRank = declaredMaxRank;
row.PhysicalMaxRank = txChains;
row.EffectiveMaxRank = effectiveMaxRank;
row.AdaptiveRank = true;
row.PhysicalRankLimited = physicalRankLimited;
row.GeometrySeed = source.GeometrySeed;
row.ShadowSeed = source.ShadowSeed;
row.TrafficSeed = source.TrafficSeed;
row.AntennaOrientationSeed = source.AntennaOrientationSeed;
row.SchedulerSeed = source.SchedulerSeed;
row.PropagationSeed = source.PropagationSeed;
row.ArrivalStreamID = source.ArrivalStreamID;
row.SeedBundleID = source.SeedBundleID;
row.ConfigDelta = {delta};
row.ExecutionParameters = {executionParameters};
row.ConfigDeltaSHA256 = digest;
row.ExecutionStatus = "blocked_pending_lls_adaptive_calibration";
row.PrimaryResultEligible = false;
row.ExecutionBlocker = "missing_executed_phy_truth_fixed_mcs_calibration";
row.PlannedExecutionArchitecture=string(cfg.sls.execution.architecture);
row.PlannedResultClassification=string(cfg.sls.execution.result_classification);
end

function row = localEmptyRow()
row = struct( ...
    "CaseID", "", "CasePairKey", "", "BasePairKey", "", ...
    "Scenario", "", "Population", "", "TargetRUPercent", 0, ...
    "IndependentDropID", "", "ComparatorID", "", ...
    "Representation", "", "UETxCase", "", "UETxChains", 0, ...
    "SpatialMode", "", "SpatialRole", "", ...
    "MUMIMOEnabled", false, "ULMUMIMOEnabled", false, ...
    "PowerCase", "", "PowerRole", "", "UETxPower_dBm", 0, ...
    "InitialRank", 0, "ComparatorMaxRank", 0, ...
    "PhysicalMaxRank", 0, "EffectiveMaxRank", 0, ...
    "AdaptiveRank", false, "PhysicalRankLimited", false, ...
    "GeometrySeed", 0, "ShadowSeed", 0, "TrafficSeed", 0, ...
    "AntennaOrientationSeed", 0, "SchedulerSeed", 0, ...
    "PropagationSeed", 0, "ArrivalStreamID", "", ...
    "SeedBundleID", "", "ConfigDelta", {cell(1,1)}, ...
    "ExecutionParameters", {cell(1,1)}, ...
    "ConfigDeltaSHA256", "", ...
    "ExecutionStatus", "", "PrimaryResultEligible", false, ...
    "ExecutionBlocker", "", "PlannedExecutionArchitecture", "", ...
    "PlannedResultClassification", "");
end
