classdef MCSEntry
    %MCSENTRY Immutable physical meaning of one 6GR MCS study entry.
    %
    % The entry identifier is deliberately separate from any DCI index.  A
    % representation may bind an entry to an index, but it may not change
    % the entry's Qm/rate meaning while a TB or HARQ process is outstanding.

    properties (SetAccess = private)
        EntryID (1,1) string
        Qm (1,1) double
        TargetCodeRateX1024 (1,1) double
        NominalSpectralEfficiency (1,1) double
        Eligibility (1,1) string
        ModulationFamily (1,1) string
        Waveform (1,1) string
        NewTBAllowed (1,1) logical
        RetransmissionAllowed (1,1) logical
        ReferenceOrigin (1,1) string
    end

    methods
        function obj = MCSEntry(entryID, qm, rateX1024, eligibility, ...
                modulationFamily, waveform, newTBAllowed, ...
                retransmissionAllowed, referenceOrigin)
            arguments
                entryID (1,1) string
                qm (1,1) double
                rateX1024 (1,1) double
                eligibility (1,1) string
                modulationFamily (1,1) string = "square_qam"
                waveform (1,1) string = "CP-OFDM"
                newTBAllowed (1,1) logical = true
                retransmissionAllowed (1,1) logical = true
                referenceOrigin (1,1) string = "6GR_study_candidate"
            end

            if strlength(strtrim(entryID)) == 0 || ...
                    ~any(qm == [2 4 6 8 10]) || ...
                    ~(isfinite(rateX1024) && rateX1024 > 0 && rateX1024 <= 1024) || ...
                    strlength(strtrim(eligibility)) == 0 || ...
                    strlength(strtrim(modulationFamily)) == 0 || ...
                    strlength(strtrim(waveform)) == 0 || ...
                    strlength(strtrim(referenceOrigin)) == 0
                error("sixgr:ran1ai1032:InvalidMCSEntry", ...
                    "MCS entry fields must be finite, explicit, and physically valid.");
            end

            obj.EntryID = strtrim(entryID);
            obj.Qm = qm;
            obj.TargetCodeRateX1024 = rateX1024;
            obj.NominalSpectralEfficiency = qm * rateX1024 / 1024;
            obj.Eligibility = strtrim(eligibility);
            obj.ModulationFamily = strtrim(modulationFamily);
            obj.Waveform = strtrim(waveform);
            obj.NewTBAllowed = newTBAllowed;
            obj.RetransmissionAllowed = retransmissionAllowed;
            obj.ReferenceOrigin = strtrim(referenceOrigin);
        end

        function value = targetCodeRate(obj)
            value = obj.TargetCodeRateX1024 / 1024;
        end

        function value = modulationName(obj)
            switch obj.Qm
                case 2
                    value = "QPSK";
                otherwise
                    value = string(obj.Qm) + "QAM";
            end
        end

        function out = toStruct(obj)
            out = struct( ...
                "entry_id", char(obj.EntryID), ...
                "Qm", obj.Qm, ...
                "target_code_rate_x1024", obj.TargetCodeRateX1024, ...
                "nominal_spectral_efficiency", obj.NominalSpectralEfficiency, ...
                "eligibility", char(obj.Eligibility), ...
                "modulation_family", char(obj.ModulationFamily), ...
                "waveform", char(obj.Waveform), ...
                "new_TB_allowed", obj.NewTBAllowed, ...
                "retransmission_allowed", obj.RetransmissionAllowed, ...
                "reference_origin", char(obj.ReferenceOrigin));
        end
    end

    methods (Static)
        function T = toTable(entries)
            entries = entries(:);
            rows = repmat(struct( ...
                "entry_id", "", ...
                "Qm", NaN, ...
                "target_code_rate_x1024", NaN, ...
                "target_code_rate", NaN, ...
                "nominal_spectral_efficiency", NaN, ...
                "eligibility", "", ...
                "modulation_family", "", ...
                "waveform", "", ...
                "new_TB_allowed", false, ...
                "retransmission_allowed", false, ...
                "reference_origin", ""), numel(entries), 1);
            for k = 1:numel(entries)
                e = entries(k);
                rows(k) = struct( ...
                    "entry_id", e.EntryID, ...
                    "Qm", e.Qm, ...
                    "target_code_rate_x1024", e.TargetCodeRateX1024, ...
                    "target_code_rate", e.targetCodeRate(), ...
                    "nominal_spectral_efficiency", e.NominalSpectralEfficiency, ...
                    "eligibility", e.Eligibility, ...
                    "modulation_family", e.ModulationFamily, ...
                    "waveform", e.Waveform, ...
                    "new_TB_allowed", e.NewTBAllowed, ...
                    "retransmission_allowed", e.RetransmissionAllowed, ...
                    "reference_origin", e.ReferenceOrigin);
            end
            T = struct2table(rows);
        end
    end
end
