function branch=resolveF1RFBranch(study,modulation)
%RESOLVEF1RFBRANCH Select one explicitly configured waveform RF experiment.
id=string(study.lls.execution.rf_branch);
if id=="ideal_debug"
    branch=struct('id',id,'modulation',"any",'tx_evm_percent',0, ...
        'rx_evm_percent',0,'residual_normalized_cfo',0, ...
        'requested_tx_power_dbm',NaN,'power_class_max_dbm',NaN, ...
        'mpr_db',0,'phase_noise_enabled',false, ...
        'power_plane',"normalized_reference_relative_cap", ...
        'classification',"ideal_debug_baseline");
    return;
end
assert(isfield(study.rf,'waveform_branches'), ...
    'sixgr:ran1ai1032:F1RFBranch','Configure rf.waveform_branches before executing a nonideal RF branch.');
entries=study.rf.waveform_branches; found=false;
for i=1:numel(entries)
    if iscell(entries), item=entries{i}; else, item=entries(i); end
    if string(item.id)==id
        assert(~found,'sixgr:ran1ai1032:F1RFBranch','RF branch IDs must be unique.');
        branch=item; found=true;
    end
end
assert(found,'sixgr:ran1ai1032:F1RFBranch','RF branch %s was not configured.',id);
required=["id","modulation","tx_evm_percent","rx_evm_percent", ...
    "residual_normalized_cfo","requested_tx_power_dbm","power_class_max_dbm", ...
    "mpr_db","phase_noise_enabled","power_plane","classification"];
assert(all(isfield(branch,required)), ...
    'sixgr:ran1ai1032:F1RFBranch','RF branch requires explicit EVM/CFO/power/mask assumptions.');
assert(ismember(string(branch.modulation),["any",string(modulation)]), ...
    'sixgr:ran1ai1032:F1RFModulation','RF branch is configured for a different modulation.');
for field=["tx_evm_percent","rx_evm_percent","mpr_db"]
    validateattributes(branch.(field),{'numeric'},{'scalar','real','finite','nonnegative'});
end
for field=["residual_normalized_cfo","requested_tx_power_dbm","power_class_max_dbm"]
    validateattributes(branch.(field),{'numeric'},{'scalar','real','finite'});
end
assert(string(branch.power_plane)=="normalized_reference_relative_cap", ...
    'sixgr:ran1ai1032:F1RFPowerPlane','F1 uses a fixed pre-cap noise reference, not an absolute link budget.');
assert(strlength(string(branch.classification))>0, ...
    'sixgr:ran1ai1032:F1RFBranch','RF assumption classification is required.');
if logical(branch.phase_noise_enabled)
    if isfield(branch,'phase_noise_profile_path')
        definition=sixgr.lls6g.config.readConfigFile(string(branch.phase_noise_profile_path));
        carrier=nrCarrierConfig('NSizeGrid',double(study.lls.execution.grid_prbs), ...
            'SubcarrierSpacing',double(study.carrier.scs_khz));
        ofdm=nrOFDMInfo(carrier);
        branch.phase_noise_profile=sixgr.rf.runtime.resolveMultipolePhaseNoiseProfile( ...
            definition,double(study.carrier.frequency_hz),double(ofdm.SampleRate));
        branch.phase_noise_profile_source=string(definition.source);
        branch.phase_noise_profile_sha256=sixgr.csi.studyFileSHA256(string(branch.phase_noise_profile_path));
    end
    assert(isfield(branch,'phase_noise_profile') && ...
        isfield(branch,'phase_noise_profile_source') && ...
        strlength(string(branch.phase_noise_profile_source))>0, ...
        'sixgr:ran1ai1032:F1PhaseNoiseMask', ...
        'Enabled phase noise requires an explicit versioned profile and source; no default 7GHz mask is substituted.');
end
if isfield(branch,'ptrs')
    p=branch.ptrs;
    assert(all(isfield(p,["enabled","compensation_enabled","time_density","frequency_density","re_offset","port_set"])), ...
        'sixgr:ran1ai1032:F1PTRS','Explicit PTRS mapping and compensation settings are required.');
    assert(~p.compensation_enabled || p.enabled,'sixgr:ran1ai1032:F1PTRS', ...
        'PTRS compensation cannot be enabled without transmitted PTRS.');
end
assumptions=study.rf.additive_evm;
assert(string(assumptions.covariance)=="independent_chains" && ...
    string(assumptions.reference_power)=="clean_signal_per_chain" && ...
    logical(assumptions.tx_power_cap_includes_distortion), ...
    'sixgr:ran1ai1032:F1EVMAssumptions','Explicit independent-chain clean-power composite-cap assumptions are required.');
end
