function out = writeImplementationAudit(repoRoot, outputPath)
%WRITEIMPLEMENTATIONAUDIT Publish the AI 10.3.2 implementation gate.
%
% The audit is intentionally conservative.  Source presence alone is not a
% PASS: PASS rows require an executable focused test or a deterministic
% invariant check.  PARTIAL rows identify implemented machinery that has
% not yet passed the exact 7 GHz / 100 MHz campaign contract.

arguments
    repoRoot (1,1) string = string(pwd)
    outputPath (1,1) string = ""
end

repoRoot = string(java.io.File(char(repoRoot)).getCanonicalPath());
if strlength(outputPath) == 0
    outputPath = fullfile(repoRoot, "results", ...
        "ai_10_3_2_modulation", "implementation_audit.md");
end

rows = [ ...
    localRow("Fixed-MCS F1/F2 execution ledger", "PASS", ...
        "+sixgr/+studies/+ran1ai1032/buildLLSCasePlan.m", ...
        "buildLLSCasePlan", "testRAN1AI1032LLSCasePlan", ...
        "Execution remains planned_not_executed until physical trials populate the retained point rows."); ...
    localRow("Option-A runtime MCS identity", "PASS", ...
        "+sixgr/+studies/+ran1ai1032/validateOptionARuntimeTable.m; +sixgr/+phy/+research/resolveExperimentalMCSTable.m", ...
        "experimental_6gr_ai1032_option_a indices 0--31", ...
        "testRAN1AI1032OptionARuntimeTable", ...
        "This is a 6GR RAN1 study candidate, not a normative TS 38.214 table."); ...
    localRow("Adaptive H-entry SLS calibration", "PARTIAL", ...
        "+sixgr/+studies/+ran1ai1032/validateAdaptiveCalibrationTable.m", ...
        "measured fixed-MCS LLS first-transmission BLER threshold gate", ...
        "testRAN1AI1032AdaptiveCalibrationGate", ...
        "Execute F1 LLS and install uncensored waveform-derived thresholds before adaptive SLS."); ...
    localRow("PUSCH transmitter", "PASS", "+sixgr/+phy/+ul/PUSCH_Tx.m", ...
        "PUSCH_Tx", "testPUSCHULSCHPhaseCore; testPUSCHGrantDrivenTxExact", ""); ...
    localRow("PUSCH receiver", "PASS", "+sixgr/+phy/+ul/PUSCH_Rx.m", ...
        "PUSCH_Rx", "testPUSCHResolvedCodewordDecode", ""); ...
    localRow("CRC", "PASS", "+sixgr/+phy/+ul/PUSCH_Tx.m; +sixgr/+phy/+ul/PUSCH_Rx.m", ...
        "nrCRCEncode/nrCRCDecode", "testPUSCHULSCHPhaseCore", ""); ...
    localRow("Exact TBS and resource accounting", "PASS", ...
        "+sixgr/+phy/+ul/PUSCH_Tx.m; +sixgr/+config/normalizeConfig.m", ...
        "localResolvePUSCHTransportBlockSize/nrTBS", ...
        "testTransportBlockSizeExactness; fastNREApprox default=false", ""); ...
    localRow("LDPC base graph, segmentation, rate matching, encode/decode", "PASS", ...
        "+sixgr/+phy/+ul/PUSCH_Tx.m; +sixgr/+phy/+ul/PUSCH_Rx.m", ...
        "nrCodeBlockSegmentLDPC/nrLDPCEncode/nrRateMatchLDPC/nrRateRecoverLDPC/nrLDPCDecode", ...
        "testPUSCHULSCHPhaseCore; testPUSCHResolvedCodewordDecode", ""); ...
    localRow("Scrambling and modulation/demodulation", "PASS", ...
        "+sixgr/+phy/+ul/PUSCH_Tx.m; +sixgr/+phy/+ul/PUSCH_Rx.m", ...
        "nrPUSCH/nrPUSCHDecode", "testPUSCHULSCHPhaseCore", ""); ...
    localRow("UL 1024QAM coded waveform path", "PASS", ...
        "+sixgr/+phy/+research/PUSCHUCIResourceAdapter.m", ...
        "exact coded CP-OFDM Qm=10 adapter", ...
        "testResearch1024PUSCHUCI: 25/264 PRB, rank 2/4", ...
        "Keep research/6GR provenance; PTRS and hopping remain separate qualification branches."); ...
    localRow("DMRS and practical channel estimation", "PASS", ...
        "+sixgr/+phy/+ul/PUSCH_Tx.m; +sixgr/+phy/+ul/PUSCH_Rx.m", ...
        "nrPUSCHDMRS/nrChannelEstimate", ...
        "testPUSCHResolvedCodewordDecode; testPUSCHMultiLayerPostEqSINR", ""); ...
    localRow("SRS receiver and scheduling measurement", "PASS", ...
        "+sixgr/+phy/+ul/SRS_Rx.m; +sixgr/+link/runSRSChannelEstimation.m", ...
        "SRS_Rx/runSRSChannelEstimation", ...
        "testSRSReceiverNoiseDespreading (24 cases); testSRSPUSCHRankPowerConservation", ""); ...
    localRow("MIMO layer/rank/power normalization", "PASS", ...
        "+sixgr/+phy/+ul/PUSCH_Tx.m; +sixgr/+mimo", ...
        "grant-driven layer mapping and total-power normalization", ...
        "testPUSCHMultiLayerPostEqSINR; testSRSPUSCHRankPowerConservation", ""); ...
    localRow("Equalizer and post-processing SINR", "PASS", ...
        "+sixgr/+phy/+ul/PUSCH_Rx.m", "MMSE/post-equalization evidence", ...
        "testPUSCHMultiLayerPostEqSINR", "MMSE-IRC remains a separate interference campaign gate."); ...
    localRow("HARQ and RV handling", "PASS", ...
        "+sixgr/+l2/+mac; +sixgr/+link/runULPUSCHThroughput.m", ...
        "HARQ process state and frozen grant context", ...
        "testResearch1024PUSCHUCI; causal system waveform replay", ...
        "Run the dedicated ten-state HARQ/TBS-context matrix before result publication."); ...
    localRow("ILLA/CQI and OLLA", "PASS", ...
        "+sixgr/+l2/+mac/SchedulerBase.m; +sixgr/+system/SystemLevelRunner.m", ...
        "selectAMC/delayed receiver CQI/OLLA dB margin", ...
        "testSchedulerOLLADbMarginMapping; testSystemLevelCausalCQIFeedback", ""); ...
    localRow("Thermal noise and measured receiver SINR", "PASS", ...
        "+sixgr/+link; +sixgr/+phy/+ul/PUSCH_Rx.m", ...
        "thermal-noise calibration/post-equalization SINR", ...
        "testThermalNoiseAndNoiseFigure; testPUSCHMultiLayerPostEqSINR", ""); ...
    localRow("CDL/TDL fading and Doppler", "PASS", ...
        "+sixgr/+channel; +sixgr/+link", "concrete CDL/TDL profiles and applied Doppler", ...
        "testDopplerMobilityApplied; strict concrete-profile validation", ...
        "Execute every requested delay-spread case with paired seeds."); ...
    localRow("CFO", "PARTIAL", "+sixgr/+rf; +sixgr/+link", ...
        "CFO injection/correction", "testRAN1AI1032F1RFExecution: actual decoded RF branches", ...
        "Run normalized CFO 0/0.005/0.01 at the exact campaign operating points."); ...
    localRow("Phase noise and PTRS", "PARTIAL", "+sixgr/+rf; +sixgr/+link", ...
        "sample-domain phase noise with CPE/ICI and measured PUSCH PTRS correction", ...
        "testNRInspiredPhaseNoise; testRAN1AI1032PhaseNoisePTRS", ...
        "User-approved TR38.803-inspired 29.55-to-7GHz extrapolation is explicitly assumed, not hardware qualified. Separate PN-off/uncompensated/compensated calibration populations; full statistical calibration remains open."); ...
    localRow("TX/RX EVM", "PARTIAL", "+sixgr/+rf; +sixgr/+link", ...
        "waveform impairment injection and measured EVM", "testRAN1AI1032F1RFExecution: explicit TX/RX samples before receiver noise", ...
        "Run the requested per-chain/common covariance branches and verify no phase-noise double count."); ...
    localRow("MPR / transmit-power cap", "PARTIAL", ...
        "+sixgr/+phy/+ul/+pusch/PUSCHPowerController.m; +sixgr/+rf/+runtime", ...
        "requested/allowed/applied transmit power", "testRAN1AI1032F1RFExecution: physical attenuation with frozen pre-cap noise", ...
        "Bind modulation-dependent cap occupancy to every campaign grant; never subtract MPR from SINR."); ...
    localRow("SLS calibrated abstraction and spatial SINR", "PARTIAL", ...
        "+sixgr/+system/SystemLevelRunner.m; +sixgr/+system/CalibratedLinkPHY.m; +sixgr/+system/+abstraction/evaluateSpatialSINR.m", ...
        "exact-grant calibrated backend; per-resource LMMSE; conditional full-history HARQ; separate estimate exports", ...
        "testCalibratedLinkPHY; testSLSAbstractionSpatialSINR; testSLSCalibrationSourceIntegrity; testSystemFTP3CalibratedDelivery (development fixtures only)", ...
        "Scheduler/TB/file/export integration and S0 adapter are wired. Production spatial-channel/interference and causal rank/MU feedback producers remain unfinished. No qualified BLER/EESM/HARQ dataset exists; fixture integration is not study qualification."); ...
    localRow("SLS received spatial feedback and adaptive rank", "PARTIAL", ...
        "+sixgr/+system/SystemLevelRunner.m; +sixgr/+l2/+mac/SchedulerPF.m", ...
        "UE-state RI/NumLayers and measured MU spatial signatures", ...
        "Static runtime audit: RI initialized but no received-SRS rank update", ...
        "Wire causal modeled SRS/CSI feedback into the approved abstraction backend with explicit model provenance; retain the physical SRS consumer separately. YAML enablement and MCS thresholds alone do not close this gap."); ...
    localRow("SLS resource-utilization calibration", "PARTIAL", ...
        "+sixgr/+system/buildResourceOpportunityTable.m; +sixgr/+studies/+ran1ai1032/calibrateSLSFTP3Loads.m", ...
        "Union of exact scheduled PRB-symbols over independent opportunities including idle cells", ...
        "testSLSResourceOpportunityAccounting; testRAN1AI1032FTP3LoadCalibration", ...
        "Execute S0 with the final scheduler/PHY, freeze measured rates, and qualify control/reference reservations; served/offered bits are not radio utilization."); ...
    localRow("SLS control/reference reservation ownership", "PARTIAL", ...
        "+sixgr/+system/resolveSLSResourceReservations.m; +sixgr/+system/SystemLevelRunner.m", ...
        "exact causal masks, grant collision guard, disclosed conservative scheduler exclusions", ...
        "testSLSResourceReservations", ...
        "Complete runtime PUCCH obligation production and common SSB/SIB1/TRS reservation reconciliation before load calibration."); ...
    localRow("FTP3 file completion and unique payload exports", "PARTIAL", ...
        "+sixgr/+system/FTP3FileLedger.m; +sixgr/+system/SystemTransportBlockState.m; +sixgr/+system/SystemLevelRunner.m", ...
        "immutable first-TX file ranges, first-success delivery, retry-limit drops and censored files", ...
        "testFTP3FileLedger; testSystemTransportBlockState; testSystemFTP3WaveformDelivery", ...
        "Keep completed-file UPT distinct from decoded-TB throughput and wall-clock goodput; qualify final UL SLS campaign/export coverage."); ...
    localRow("SLS case matrix and stochastic runtime binding", "PASS", ...
        "+sixgr/+studies/+ran1ai1032/buildSLSCampaignCases.m; +sixgr/+system/SystemLevelRunner.m", ...
        "17280 explicit cases with paired component seeds and FWA population binding", ...
        "testRAN1AI1032SLSCampaignCases; testRAN1AI1032PairedRuntimeWiring", ...
        "Case construction and replay identity pass; rows are explicitly blocked_pending_lls_adaptive_calibration " + ...
        "and ineligible for primary results until executed-PHY thresholds exist."); ...
    localRow("Finite seven-site hex wrap-around runtime binding", "PASS", ...
        "+sixgr/+studies/+ran1ai1032/buildHexWraparoundTopology.m; " + ...
        "+sixgr/+scenario/wraparoundDistance.m; +sixgr/+system/GeometryEngine.m", ...
        "hex_cluster_min_image with explicit 2x2 cluster translation basis", ...
        "testRAN1AI1032HexTopology; testScenarioGeometryModes; testCanonicalGeometryEngine", ...
        "Every expanded UMa/UMi case carries the same validated finite-cluster basis into runtime association and distance calculations."); ...
    localRow("UE power control", "PARTIAL", ...
        "+sixgr/+rf/+runtime/PUSCHPowerController.m; +sixgr/+link/bindPUSCHPowerControlContext.m", ...
        "PUSCH power-control state", "Implemented machinery", ...
        "Verify 31/35 dBm caps, rank power conservation and MPR occupancy in SLS."); ...
    localRow("O2I, shadow fading, LOS/NLOS and 3GPP geometry", "PARTIAL", ...
        "+sixgr/+channel/TR38901Plus.m; +sixgr/+system/GeometryEngine.m", ...
        "TR 38.901 large-scale state", "Implemented and provenance-labelled", ...
        "Run UMa/UMi 7-site wrap-around paired-drop conformance and population stratification."); ...
    localRow("Antenna pattern, polarization and XPR", "PARTIAL", ...
        "+sixgr/+rf/AntennaArrayFactory.m; +sixgr/+channel", ...
        "array/polarization channel binding", "Implemented machinery", ...
        "Qualify the exact agreed 7 GHz BS/CPE arrays in every mandatory antenna case."); ...
    localRow("FWA Profile-1/Profile-3 population", "PASS", ...
        "+sixgr/+studies/+ran1ai1032/buildFWAPopulation.m; +sixgr/+studies/+ran1ai1032/applyFWAPopulation.m", ...
        "fixed quotas, seeded identity assignment, rooftop floors and per-UE O2I class", ...
        "testRAN1AI1032FWAPopulation", ...
        "Outdoor LOS/NLOS remains receiver/channel evidence and is not assigned by the population generator."); ...
    localRow("FTP3 traffic", "PARTIAL", ...
        "+sixgr/+system/Traffic_FTP3.m; +sixgr/+system/TrafficFactory.m", ...
        "fixed-size continuous-time Poisson file arrivals and event ledger", ...
        "testFTP3TrafficDeterminism", ...
        "Calibrate arrival rate once on S0, freeze the ledger across comparators, and complete paired 21-cell qualification."); ...
    localRow("Paired-drop plan and confidence-interval engine", "PASS", ...
        "+sixgr/+studies/+ran1ai1032/buildPairedDropPlan.m; +sixgr/+studies/+ran1ai1032/pairedDropBootstrap.m", ...
        "S0-S5 seed-bundle identity and independent-drop bootstrap", ...
        "testRAN1AI1032PairedDropPlan", ...
        "Execute all planned drops and retain the resulting drop aggregates before a performance claim."); ...
    localRow("Complete paired 21-cell campaign execution", "PARTIAL", ...
        "+sixgr/+system/SystemLevelRunner.m", ...
        "UMa/UMi calibrated link-abstraction S0-S5 estimates, not waveform truth", ...
        "not yet executed", ...
        "Run every planned comparator/drop and pass result-coverage plus paired-confidence gates.") ...
    ];

itemNames = string({rows.Item});
statusNames = string({rows.Status});
% The requested complete study includes RF, power, arrays and propagation.
% An ideal-RF calibration pass cannot exempt these branches from acceptance.
mandatory = true(size(itemNames));
overallPass = all(statusNames(mandatory) == "PASS");

vienna = [ ...
    localReferenceRow("Hexagonal deployment geometry", "REFERENCE AVAILABLE", ...
        "+networkGeometry/HexagonalGrid.m; +networkGeometry/HexGridRing.m", ...
        "Use for independent coordinate/distance-distribution comparison."); ...
    localReferenceRow("Spatially correlated shadow fading", "REFERENCE AVAILABLE", ...
        "+shadowing/ShadowFadingMapLinearFiltering.m", ...
        "Compare autocorrelation and marginal distribution; retain SixGR implementation ownership."); ...
    localReferenceRow("DL round-robin / best-CQI scheduling", "REFERENCE AVAILABLE", ...
        "+scheduler/RoundRobinScheduler.m; +scheduler/BestCQIScheduler.m", ...
        "Compare deterministic allocation traces under matched CQI inputs."); ...
    localReferenceRow("MIESM", "REFERENCE AVAILABLE", "+tools/MiesmAverager.m", ...
        "Use only as an external calibrated link-abstraction cross-check."); ...
    localReferenceRow("UL scheduling", "NOT A VALID REFERENCE", ...
        "+scheduler/RoundRobinScheduler.m", ...
        "Installed Vienna source explicitly states UL queue support is a future extension."); ...
    localReferenceRow("FTP3", "NOT PRESENT", "Vienna installation inventory", ...
        "No FTP3 generator was found; it cannot close SixGR's FTP3 gap."); ...
    localReferenceRow("6GR UL 1024QAM coded PHY", "NOT A VALID REFERENCE", ...
        "Vienna installation inventory", ...
        "The installed system simulator uses legacy CQI/link abstraction and is not the SixGR Qm=10 waveform authority.") ...
    ];

localAssertSources(repoRoot, rows);
localWriteMarkdown(outputPath, rows, vienna, overallPass);
out = struct("Ok", true, "OverallPass", overallPass, ...
    "AuditTable", rows, "ViennaReferenceTable", vienna, ...
    "OutputPath", string(outputPath));
end

function row = localRow(item, status, source, symbol, evidence, correctiveChange)
row = struct("Item", string(item), "Status", string(status), ...
    "Source", string(source), "FunctionOrClass", string(symbol), ...
    "Evidence", string(evidence), "CorrectiveChange", string(correctiveChange));
end

function row = localReferenceRow(feature, status, source, use)
row = struct("Feature", string(feature), "Status", string(status), ...
    "ViennaSource", string(source), "SixGRUse", string(use));
end

function localAssertSources(repoRoot, rows)
for i = 1:numel(rows)
    paths = split(rows(i).Source, ";");
    for j = 1:numel(paths)
        rel = strtrim(paths(j));
        if strlength(rel) == 0 || ~contains(rel, "/")
            continue;
        end
        absPath = fullfile(repoRoot, strrep(rel, "/", filesep));
        if exist(absPath, "file") ~= 2 && exist(absPath, "dir") ~= 7
            error("sixgr:studies:ran1ai1032:MissingAuditSource", ...
                "Audit source does not exist: %s", rel);
        end
    end
end
end

function localWriteMarkdown(outputPath, rows, vienna, overallPass)
parent = string(fileparts(outputPath));
if strlength(parent) > 0
    sixgr.util.ensureFolder(parent);
end
fid = fopen(outputPath, "w");
if fid < 0
    error("sixgr:studies:ran1ai1032:AuditWriteFailed", ...
        "Cannot write implementation audit: %s", outputPath);
end
cleanup = onCleanup(@() fclose(fid)); %#ok<NASGU>

fprintf(fid, "# AI 10.3.2 modulation implementation audit\n\n");
fprintf(fid, "Overall mandatory implementation gate: **%s**\n\n", ...
    localToken(overallPass, "PASS", "FAIL"));
fprintf(fid, ["PASS requires focused executable evidence or a deterministic invariant. " + ...
    "PARTIAL means machinery exists but the exact campaign branch is not yet qualified. " + ...
    "No performance result is implied by this audit.\n\n"]);
fprintf(fid, "| Item | Status | Source | Class/function | Evidence | Corrective change |\n");
fprintf(fid, "|---|---|---|---|---|---|\n");
for i = 1:numel(rows)
    fprintf(fid, "| %s | **%s** | `%s` | `%s` | %s | %s |\n", ...
        localEscape(rows(i).Item), localEscape(rows(i).Status), ...
        localEscape(rows(i).Source), localEscape(rows(i).FunctionOrClass), ...
        localEscape(rows(i).Evidence), localEscape(rows(i).CorrectiveChange));
end

fprintf(fid, "\n## Licensed Vienna SLS reference boundary\n\n");
fprintf(fid, ["Vienna is used as an external reference and local cross-validation oracle. " + ...
    "Vienna results are never relabelled as SixGR truth, and Vienna source is not embedded " + ...
    "in SixGR artifacts.\n\n"]);
fprintf(fid, "| Feature | Status | Vienna source | SixGR use |\n");
fprintf(fid, "|---|---|---|---|\n");
for i = 1:numel(vienna)
    fprintf(fid, "| %s | **%s** | `%s` | %s |\n", ...
        localEscape(vienna(i).Feature), localEscape(vienna(i).Status), ...
        localEscape(vienna(i).ViennaSource), localEscape(vienna(i).SixGRUse));
end

fprintf(fid, "\n## Current blocking conclusions\n\n");
fprintf(fid, "- No 7 GHz / 100 MHz performance claim is released by this audit.\n");
fprintf(fid, "- FTP3 file-arrival generation is implemented and deterministic; S0 load calibration and paired 21-cell qualification remain open.\n");
fprintf(fid, "- Adaptive SLS planning rows remain blocked and primary-result-ineligible until waveform-derived fixed-MCS thresholds pass the calibration gate.\n");
fprintf(fid, "- RF, exact-array and paired 21-cell campaign branches remain qualification work.\n");
fprintf(fid, "- The coded UL waveform, exact TBS, receiver measurements and causal SLS CQI path have focused passing evidence.\n");
end

function out = localEscape(value)
out = strrep(string(value), "|", "\\|");
out = strrep(out, newline, " ");
end

function value = localToken(condition, trueValue, falseValue)
if condition
    value = trueValue;
else
    value = falseValue;
end
end
