function decision = evaluateSamplingPlan(cfg, eventCount, trialCount)
%EVALUATESAMPLINGPLAN Evaluate the YAML-owned LLS point stopping design.
%
% Publication confidence intervals in this package are ordinary fixed-sample
% Wilson intervals.  Repeatedly inspecting those intervals and stopping when
% they look favorable would invalidate their nominal coverage.  Publication
% runs therefore stop only at the prespecified maximum sample size.  The
% adaptive error-count rule remains available exclusively to diagnostic runs
% whose outputs are explicitly ineligible for publication.

arguments
    cfg (1,1) struct
    eventCount (1,1) double {mustBeNonnegative,mustBeInteger}
    trialCount (1,1) double {mustBeNonnegative,mustBeInteger}
end

if eventCount > trialCount
    error("sixgr:lls:InvalidBinomialCounts", ...
        "Event count cannot exceed trial count.");
end

minimumTrials = double(sixgr.util.structGet(cfg, ...
    "simulation.minTransportBlocks", NaN));
minimumEvents = double(sixgr.util.structGet(cfg, ...
    "simulation.minBlockErrors", NaN));
maximumTrials = double(sixgr.util.structGet(cfg, ...
    "simulation.maxTransportBlocks", NaN));
confidenceLevel = double(sixgr.util.structGet(cfg, ...
    "simulation.confidenceLevel", NaN));
statisticalClass = lower(string(sixgr.util.structGet(cfg, ...
    "simulation.statisticalClass", "")));
samplingPlan = lower(string(sixgr.util.structGet(cfg, ...
    "simulation.samplingPlan", "adaptive_error_count_diagnostic")));
intervalMethod = lower(string(sixgr.util.structGet(cfg, ...
    "simulation.confidenceIntervalMethod", ...
    "wilson_two_sided_fixed_sample")));

if any(~isfinite([minimumTrials, minimumEvents, maximumTrials, confidenceLevel])) || ...
        minimumTrials < 1 || minimumEvents < 1 || maximumTrials < minimumTrials || ...
        confidenceLevel <= 0 || confidenceLevel >= 1
    error("sixgr:lls:InvalidStoppingRule", ...
        "The resolved LLS sampling plan contains invalid trial, event, or confidence limits.");
end
if trialCount > maximumTrials
    error("sixgr:lls:TrialBudgetExceeded", ...
        "Trial count %d exceeds simulation.maxTransportBlocks=%d.", ...
        trialCount, maximumTrials);
end

if trialCount > 0
    [lowerCI, upperCI] = sixgr.lls.stats.wilsonInterval( ...
        eventCount, trialCount, confidenceLevel);
else
    lowerCI = NaN;
    upperCI = NaN;
end

isPublication = statisticalClass == "publication_candidate";
if isPublication
    if samplingPlan ~= "fixed_sample"
        error("sixgr:lls:PublicationSamplingPlanInvalid", ...
            "Publication-candidate LLS requires simulation.samplingPlan=fixed_sample; " + ...
            "ordinary Wilson intervals are not anytime-valid stopping bounds.");
    end
    if intervalMethod ~= "wilson_two_sided_fixed_sample"
        error("sixgr:lls:PublicationIntervalMethodInvalid", ...
            "Publication-candidate LLS requires the implemented fixed-sample Wilson interval method.");
    end
    stop = trialCount >= maximumTrials;
    statisticallyQualified = stop && trialCount == maximumTrials;
    if stop
        reason = "prespecified_fixed_sample_budget_completed";
    else
        reason = "prespecified_fixed_sample_budget_incomplete";
    end
else
    reachedEvents = trialCount >= minimumTrials && eventCount >= minimumEvents;
    reachedMaximum = trialCount >= maximumTrials;
    stop = reachedEvents || reachedMaximum;
    statisticallyQualified = false;
    if reachedEvents
        reason = "diagnostic_minimum_trials_and_errors_reached";
    elseif reachedMaximum
        reason = "diagnostic_maximum_trials_reached";
    elseif trialCount < minimumTrials
        reason = "diagnostic_minimum_trials_not_reached";
    else
        reason = "diagnostic_minimum_errors_not_reached";
    end
end

decision = struct( ...
    "StatisticalClass", statisticalClass, ...
    "SamplingPlan", samplingPlan, ...
    "ConfidenceIntervalMethod", intervalMethod, ...
    "MinimumTrials", minimumTrials, ...
    "MinimumEvents", minimumEvents, ...
    "MaximumTrials", maximumTrials, ...
    "EventCount", double(eventCount), ...
    "TrialCount", double(trialCount), ...
    "ConfidenceLevel", confidenceLevel, ...
    "ConfidenceLower", double(lowerCI), ...
    "ConfidenceUpper", double(upperCI), ...
    "ConfidenceHalfWidth", double((upperCI-lowerCI)/2), ...
    "Stop", logical(stop), ...
    "StatisticallyQualified", logical(statisticallyQualified), ...
    "StoppingReason", string(reason));
end
