function prachCfg = buildPRACHConfigFromRACHCommon(cfg, raCfg)
%BUILDPRACHCONFIGFROMRACHCOMMON Resolve PRACH config from explicit RA config.
base = struct();
base.ScenarioName = char(raCfg.ScenarioName);
base.random_access = struct( ...
    "frequency_range", char(string(sixgr.util.structGet(cfg, "random_access.frequency_range", "FR1"))), ...
    "duplex_mode", char(string(sixgr.util.structGet(cfg, "random_access.duplex_mode", ...
        sixgr.util.structGet(cfg, "frequency.duplex_mode", "TDD")))), ...
    "carrier_frequency_hz", double(sixgr.util.structGet(cfg, "random_access.carrier_frequency_hz", ...
        sixgr.util.structGet(cfg, "frequency.center_frequency_hz", 4e9))), ...
    "carrier_scs_khz", double(raCfg.CarrierSCSkHz), ...
    "n_size_grid", double(raCfg.NSizeGrid), ...
    "configuration_index", double(raCfg.PRACHConfigurationIndex), ...
    "prach_format", char(raCfg.PRACHFormat), ...
    "subcarrier_spacing_khz", double(raCfg.PRACHSubcarrierSpacing), ...
    "root_sequence_index", double(raCfg.RootSequenceIndex), ...
    "zero_correlation_zone", double(raCfg.ZeroCorrelationZoneConfig), ...
    "restricted_set", char(raCfg.RestrictedSetType), ...
    "frequency_start", double(raCfg.FrequencyStart), ...
    "preamble_index", double(raCfg.PreambleIndex), ...
    "num_prach_occasions", 1, ...
    "num_slots", max(80, double(raCfg.PRACHOccasionSlot) + 20), ...
    "detection_threshold", double(sixgr.util.structGet(cfg, "random_access.detection_threshold", 0.02)), ...
    "detection_threshold_mode", char(string(sixgr.util.structGet(cfg, "random_access.detection_threshold_mode", "fixed"))));
base.phy.carrier.NCellID = double(raCfg.NCellID);
base.phy.carrier.NSizeGrid = double(raCfg.NSizeGrid);
base.phy.carrier.SubcarrierSpacing = double(raCfg.CarrierSCSkHz);
base.channel.model = "AWGN";
base.channel.awgnOnly = true;
prachCfg = sixgr.rach.PRACHConfig(base, ...
    "PreambleIndex", double(raCfg.PreambleIndex), ...
    "PRACHConfigurationIndex", double(raCfg.PRACHConfigurationIndex), ...
    "PRACHFormat", char(raCfg.PRACHFormat), ...
    "PRACHSubcarrierSpacing", double(raCfg.PRACHSubcarrierSpacing), ...
    "SequenceIndex", double(raCfg.RootSequenceIndex), ...
    "ZeroCorrelationZone", double(raCfg.ZeroCorrelationZoneConfig), ...
    "FrequencyStart", double(raCfg.FrequencyStart), ...
    "NSizeGrid", double(raCfg.NSizeGrid), ...
    "CarrierSCSkHz", double(raCfg.CarrierSCSkHz), ...
    "RestrictedSet", char(raCfg.RestrictedSetType), ...
    "NumPRACHOccasions", 1, ...
    "NumSlots", max(80, double(raCfg.PRACHOccasionSlot) + 20), ...
    "ChannelModel", "AWGN");
end
