function T = emptyOptionalEvidenceTable(artifactName)
%EMPTYOPTIONALEVIDENCETABLE Producer-owned schemas for optional RA evidence.
%
% A typed zero-row table records only the schema of a campaign that did not
% execute.  It is not runtime evidence and cannot satisfy an enabled
% campaign's row requirement.  Keeping the schema in the RA producer avoids
% divergent recovery/reporting copies of these column definitions.

arguments
    artifactName (1,1) string
end

switch lower(strtrim(artifactName))
    case "ra_negative_trials"
        T = table('Size', [0 8], ...
            'VariableTypes', { ...
            'string','string','string','string','string', ...
            'logical','logical','string'}, ...
            'VariableNames', { ...
            'RunId','NegativeTrialType','InjectedFault', ...
            'ExpectedFailureStage','ObservedFailureStage', ...
            'RACompleted','StrictOk','FailureReason'});
    case "ra_collision_trials"
        T = table('Size', [0 12], ...
            'VariableTypes', { ...
            'string','string','double','double','double','double', ...
            'logical','string','logical','logical','string','string'}, ...
            'VariableNames', { ...
            'RunId','CollisionGroupId','UEId','PreambleIndex', ...
            'PRACHOccasion','RARNTI','Msg3CrcPass', ...
            'ContentionIdentity','Msg4IdentityMatched','RACompleted', ...
            'CollisionOutcome','Status'});
    otherwise
        error("sixgr:phy:ra:UnknownOptionalEvidenceArtifact", ...
            "No producer-owned optional RA schema exists for '%s'.", ...
            artifactName);
end
end
