function [rx, rar] = recoverMsg2RAR(rxWaveform, cfg, raCfg, sched, tx)
%RECOVERMSG2RAR Decode RAR PDSCH after RA-RNTI PDCCH has been recovered.
cfgRx = sixgr.phy.ra.localizeCarrierConfig(cfg, raCfg);
cfgRx = sixgr.phy.ra.localizeRAPDSCHConfig(cfgRx, sched.PDSCH);
[controlRx, controlInfo] = sixgr.phy.ra.blindDecodeRARPDCCH( ...
    rxWaveform, cfgRx, raCfg, sched, ...
    "RNTIAttempted", double(raCfg.RARNTI));
if ~logical(sixgr.util.structGet(controlRx, "CausalGrantDecodeOk", false))
    rx = struct( ...
        "Ok", false, "CRCError", true, ...
        "PDCCHCrcPass", logical(sixgr.util.structGet(controlRx, "Ok", false)), ...
        "PDCCHPayloadMatch", logical(sixgr.util.structGet( ...
            controlRx, "DCIPayloadMatch", false)), ...
        "PDCCHInfo", controlInfo, ...
        "FailureReason", "msg2_control_dci_not_crc_valid_and_matched");
    rar = struct();
    return;
end
controlEvent = sixgr.pdsch.RASIPDSCHContext.decodedControlEvent( ...
    controlRx, controlInfo, "msg2_rar", double(raCfg.RARNTI), ...
    "1_0", sched.DCIBits, ...
    "PDCCHAbsoluteSlot", double(raCfg.Msg2Slot), ...
    "EvidenceRole", "receiver_decode");
strict = sixgr.pdsch.RASIPDSCHContext.materialize( ...
    tx.Carrier, sched.PDSCH, controlEvent, ...
    localProcedureContext(cfgRx, raCfg, sched), ...
    "TransportBlockSize", double(tx.TransportBlockSize), ...
    "NPhysicalRxAntennas", size(rxWaveform, 2), ...
    "ChannelModel", localChannelModel(cfgRx), ...
    "MaxIterations", sixgr.phy.phycode.resolveLDPCMaxIterations( ...
        cfgRx, "Direction", "DL"));
[pdschRx, info] = sixgr.phy.dl.PDSCH_Rx(rxWaveform, cfgRx, ...
    "Carrier", tx.Carrier, ...
    "Assignment", strict.Assignment, ...
    "ResourcePlan", strict.ResourcePlan, ...
    "ReferenceSignalConfig", strict.ReferenceSignalConfig, ...
    "ReceiverConfig", strict.ReceiverConfig, ...
    "CodingPlan", strict.CodingPlans, ...
    "PrecoderBundle", strict.PrecoderBundle, ...
    "IntegrationContext", strict.IntegrationContext, ...
    "ExecutionProfile", "ra_si_strict");
pdschRx = sixgr.pdsch.RASIPDSCHContext. ...
    addCompatibilityEvidence(pdschRx);
rx = pdschRx;
rx.Info = info;
rx.PDCCHControlEvent = strict.ControlEvent;
rx.PDCCHInfo = controlInfo;
if logical(pdschRx.Ok)
    payloadBits = int8(pdschRx.TransportBlock(1:double(tx.RARBitLength)));
    rar = sixgr.mac.ra.decodeMACRAR(payloadBits);
else
    rar = struct();
end
end

function context = localProcedureContext(cfg, raCfg, sched)
context = struct( ...
    "Procedure", "msg2_rar", ...
    "RNTI", double(raCfg.RARNTI), ...
    "RNTIType", "RA-RNTI", ...
    "UEId", double(raCfg.UEId), ...
    "ServingCellId", double(raCfg.NCellID), ...
    "SchedulingCellId", double(raCfg.NCellID), ...
    "CCId", 0, "BWPId", 0, "ConfigurationEpoch", 0, ...
    "PDCCHAbsoluteSlot", double(raCfg.Msg2Slot), ...
    "PDSCHAbsoluteSlot", double(raCfg.Msg2Slot), ...
    "K0", 0, "MCSTable", string(sched.MCSTable), ...
    "MCSIndex", double(raCfg.Msg2PDSCH.MCS), ...
    "TargetCodeRate", double(sched.TargetCodeRate), ...
    "XOverhead", sixgr.phy.dl.resolvePDSCHXOverhead( ...
        cfg, sched.PDSCH.SymbolAllocation), ...
    "RV", double(sched.RV), "NDI", 1, ...
    "HARQProcessId", 0, "TCIStateId", 0, ...
    "ActiveBWPContextPresent", true, "EpochCurrent", true, ...
    "ServingCellActive", true, "MCSContextSupported", true, ...
    "TCIStateActive", true, "UECapability1024QAM", false, ...
    "RRCEnabled1024QAM", false, "DeploymentAllows1024QAM", false, ...
    "FrequencyRange", string(cfg.frequency.range_name), ...
    "OperatingBand", string(cfg.frequency.band_name), ...
    "DeploymentClass", "common_search_space_ra_si", ...
    "FrequencyRangeAllows1024QAM", false, ...
    "BandAllows1024QAM", false);
end

function model = localChannelModel(cfg)
% Resolve the validated concrete profile; a bare CDL/TDL family is never a
% receiver configuration and must not leak into strict Msg2 materialization.
model = sixgr.channel.resolveConcreteProfile(cfg);
end
