function [pdcchRx, pdschRx, msg4] = recoverMsg4Waveform(rxWaveform, cfg, raCfg, sched, tx)
%RECOVERMSG4WAVEFORM Decode temp-C-RNTI PDCCH and Msg4 DL-SCH.
cfgRx = sixgr.phy.ra.localizeCarrierConfig(cfg, raCfg, raCfg.Msg4Slot);
[carrier,~] = sixgr.phy.grid.makeCarrier(cfgRx);
context = sixgr.phy.pdcch.TCMsg4DCIContext.create(raCfg.Msg4DCIReference, ...
    raCfg.TempCRNTI,raCfg.Msg4DCI.harq_ack_repetitions_configured);
schema = sixgr.phy.pdcch.DCISchemaEngine.resolve(context);
cfgRx.phy.pdcch.rnti = double(raCfg.TempCRNTI);
cfgRx.phy.pdcch.KBits = schema.RawBits;
cfgRx.phy.pdcch.dciPayloadBits = schema.RawBits;
cfgRx.phy.pdcch.blindSearch = logical(sixgr.util.structGet(cfg, ...
    "phy.pdcch.blindSearch", false));
sixgr.config.assertRuntimeFeatureUse(cfgRx, "pdcch_blind_search", ...
    cfgRx.phy.pdcch.blindSearch, "recoverMsg4Waveform");
cfgRx.phy.pdcch.allowBlindCandidateTimingEstimate = false;
[commonPDCCH,commonEvidence] = sixgr.phy.ra.buildMsg4CommonPDCCH(cfgRx,raCfg,carrier);
[pdcchRx, pdcchInfo] = sixgr.phy.dl.PDCCH_Rx(rxWaveform, cfgRx, ...
    "Carrier", carrier, "PDCCH",commonPDCCH, "K",schema.RawBits, ...
    "RNTI", double(raCfg.TempCRNTI), "PDCCHScramblingRNTI",0);
pdcchInfo.CommonControlEvidence = commonEvidence;
pdcchRx.Info = pdcchInfo;
if ~logical(sixgr.util.structGet(pdcchRx, "CausalGrantDecodeOk", false))
    pdschRx = struct("Ok", false, "CRCError", true);
    msg4 = struct();
    return;
end
controlEvent = sixgr.pdsch.RASIPDSCHContext.decodedControlEvent( ...
    pdcchRx, pdcchInfo, "msg4_contention_resolution", ...
    double(raCfg.TempCRNTI), "1_0", [], ...
    "PDCCHAbsoluteSlot", double(raCfg.Msg4Slot), ...
    "EvidenceRole", "receiver_decode");
sched = sixgr.phy.ra.msg4ScheduleFromDCI(raCfg,pdcchRx.DCIBits,context);
cfgRx = sixgr.phy.ra.localizeRAPDSCHConfig(cfgRx,sched.PDSCH);
strict = sixgr.pdsch.RASIPDSCHContext.materialize( ...
    carrier, sched.PDSCH, controlEvent, ...
    localProcedureContext(cfgRx, raCfg, sched), ...
    "NPhysicalRxAntennas", size(rxWaveform, 2), ...
    "ChannelModel", localChannelModel(cfgRx), ...
    "MaxIterations", sixgr.phy.phycode.resolveLDPCMaxIterations( ...
        cfgRx, "Direction", "DL"));
[pdschRx, info] = sixgr.phy.dl.PDSCH_Rx(rxWaveform, cfgRx, ...
    "Carrier", carrier, ...
    "Assignment", strict.Assignment, ...
    "ResourcePlan", strict.ResourcePlan, ...
    "ReferenceSignalConfig", strict.ReferenceSignalConfig, ...
    "ReceiverConfig", strict.ReceiverConfig, ...
    "CodingPlan", strict.CodingPlans, ...
    "PrecoderBundle", strict.PrecoderBundle, ...
    "IntegrationContext", strict.IntegrationContext, ...
    "ExecutionProfile", "ra_si_strict");
pdschRx = sixgr.pdsch.RASIPDSCHContext. ...
    addCompatibilityEvidence(pdschRx);
pdschRx.Info = info;
pdschRx.PDCCHControlEvent = strict.ControlEvent;
pdschRx.RecoveredSchedule = sched;
pdschRx.Msg4DCIFieldTable = sched.DCIFieldTable;
pdschRx.Msg4DCIContextDigest = context.Digest;
pdschRx.Msg4DCIReferenceSource = context.Data.FrequencyReferenceSource;
pdschRx.Msg4MACEncodingProfile = "legacy_bounded_not_NR_MAC_RRC";
if logical(pdschRx.Ok)
    payloadBits = int8(pdschRx.TransportBlock);
    msg4 = sixgr.mac.ra.parseMsg4ContentionResolution(payloadBits);
else
    msg4 = struct();
end
end

function context = localProcedureContext(cfg, raCfg, sched)
context = struct( ...
    "DCIContext",sched.DCIContext, ...
    "Procedure", "msg4_contention_resolution", ...
    "RNTI", double(raCfg.TempCRNTI), ...
    "RNTIType", "TC-RNTI", ...
    "UEId", double(raCfg.UEId), ...
    "ServingCellId", double(raCfg.NCellID), ...
    "SchedulingCellId", double(raCfg.NCellID), ...
    "CCId", 0, "BWPId", 0, "ConfigurationEpoch", 0, ...
    "PDCCHAbsoluteSlot", double(raCfg.Msg4Slot), ...
    "PDSCHAbsoluteSlot", double(raCfg.Msg4Slot), ...
    "K0", 0, "MCSTable", string(sched.MCSTable), ...
    "MCSIndex", double(sched.MCS), ...
    "TargetCodeRate", double(sched.TargetCodeRate), ...
    "XOverhead", 0, ...
    "RV", double(sched.RV), "NDI", double(sched.NDI), ...
    "HARQProcessId", double(sched.HARQProcessId), "TCIStateId", 0, ...
    "ActiveBWPContextPresent", true, "EpochCurrent", true, ...
    "ServingCellActive", true, "MCSContextSupported", true, ...
    "TCIStateActive", true, "UECapability1024QAM", false, ...
    "RRCEnabled1024QAM", false, "DeploymentAllows1024QAM", false, ...
    "FrequencyRange", string(cfg.frequency.range_name), ...
    "OperatingBand", string(cfg.frequency.band_name), ...
    "DeploymentClass", "common_search_space_ra_si", ...
    "FrequencyRangeAllows1024QAM", false, ...
    "BandAllows1024QAM", false);
context.CommonQCLReference = sixgr.pdsch.CommonPDSCHQCLReference.fromRA( ...
    cfg,context.Procedure,double(raCfg.NCellID));
end

function model = localChannelModel(cfg)
% Resolve the validated concrete profile; a bare CDL/TDL family is never a
% receiver configuration and must not leak into strict Msg4 materialization.
model = sixgr.channel.resolveConcreteProfile(cfg);
end
