function result = runFourStepRAContentionGroup(cfg, varargin)
%RUNFOURSTEPRACONTENTIONGROUP Waveform-backed multi-UE Msg1/Msg3 contention.
%
% UEs share one PRACH occasion. Different preambles receive orthogonal
% Msg3 grants; same-preamble UEs share the grant and are resolved only when
% the composite PUSCH produces a valid captured RRCSetupRequest.

p = inputParser;
p.addParameter("UEIds", [1 2], ...
    @(x)isnumeric(x) && isvector(x) && numel(x) >= 2);
p.addParameter("PreambleIndices", [7 7], ...
    @(x)isnumeric(x) && isvector(x));
p.addParameter("RelativePowersdB", [0 0], ...
    @(x)isnumeric(x) && isvector(x) && all(isfinite(x)));
p.addParameter("SNRdB", 35, ...
    @(x)isnumeric(x) && isscalar(x) && isfinite(x));
p.addParameter("Seed", 41001, ...
    @(x)isnumeric(x) && isscalar(x) && isfinite(x));
p.parse(varargin{:});
opt = p.Results;

ueIds = double(opt.UEIds(:));
preambles = double(opt.PreambleIndices(:));
powers = double(opt.RelativePowersdB(:));
nUE = numel(ueIds);
if numel(preambles) ~= nUE || numel(powers) ~= nUE
    error("sixgr:phy:ra:InvalidContentionGroup", ...
        "UEIds, PreambleIndices and RelativePowersdB must have equal length.");
end
if numel(unique(ueIds)) ~= nUE || any(preambles < 0 | ...
        preambles > 63 | preambles ~= fix(preambles))
    error("sixgr:phy:ra:InvalidContentionGroup", ...
        "UE IDs must be unique and preamble indices must be integers in [0,63].");
end

raConfigs = cell(nUE, 1);
msg1 = cell(nUE, 1);
occasion = struct();
for ii = 1:nUE
    cfgUE = cfg;
    cfgUE.random_access.preamble_index = preambles(ii);
    raConfigs{ii} = sixgr.mac.ra.RAConfig(cfgUE, ...
        "RunId", "contention_group", "UEId", ueIds(ii), ...
        "AttemptId", 1);
    [msg1{ii}, thisOccasion] = ...
        sixgr.phy.ra.generateMsg1PRACHWaveform( ...
        cfgUE, raConfigs{ii});
    if ii == 1
        occasion = thisOccasion;
    elseif ~localSameOccasion(occasion, thisOccasion)
        error("sixgr:phy:ra:ContentionOccasionMismatch", ...
            "All contention-group UEs must use the same PRACH occasion.");
    end
end

msg1Composite = localComposite(msg1, powers);
[msg1Rx, msg1NoiseVariance] = localAddNoise( ...
    msg1Composite, double(opt.SNRdB), double(opt.Seed));
detector = sixgr.phy.ra.detectMsg1PRACH( ...
    msg1Rx, cfg, raConfigs{1}, occasion);
peaks = double(sixgr.util.structGet( ...
    detector, "CorrelationPeaks", nan(64, 1)));
candidates = double(sixgr.util.structGet( ...
    detector, "CandidatePreambles", 0:63));
threshold = double(sixgr.util.structGet( ...
    detector, "Threshold", NaN));

[groupPreambles, ~, groupOfUE] = unique(preambles, "stable");
nGroups = numel(groupPreambles);
puschTx = cell(nGroups, 1);
groupMembers = cell(nGroups, 1);
groupStrongestUE = nan(nGroups, 1);
groupStrongestIndex = nan(nGroups, 1);
baseRA = raConfigs{1};
numPRB = double(baseRA.Msg3PUSCH.NumPRB);
for gg = 1:nGroups
    members = find(groupOfUE == gg);
    groupMembers{gg} = members;
    [~, localWinner] = max(powers(members));
    strongest = members(localWinner);
    groupStrongestIndex(gg) = strongest;
    groupStrongestUE(gg) = ueIds(strongest);
    ra = raConfigs{strongest};
    prbStart = (gg - 1) * numPRB;
    if prbStart + numPRB > double(ra.NSizeGrid)
        error("sixgr:phy:ra:InsufficientMsg3ContentionResources", ...
            "The active UL BWP cannot place %d orthogonal Msg3 grants.", ...
            nGroups);
    end
    ra.Msg3PUSCH.PRBStart = prbStart;
    grant = sixgr.mac.ra.buildRARULGrant(ra);
    payload = sixgr.mac.ra.buildMsg3Payload( ...
        "UEId", ueIds(strongest), ...
        "UEIdentity", "UE-" + string(round(ueIds(strongest))), ...
        "RRCSetupRequest", true);
    [tx, ~] = sixgr.phy.ra.generateMsg3PUSCHWaveform( ...
        cfg, ra, grant, payload);
    tx.ContentionRAConfig = ra;
    tx.ContentionGrant = grant;
    tx.ContentionPayload = payload;
    puschTx{gg} = tx;
end

% A same-preamble group contains every UE waveform on the same grant.
% Generate the non-strongest payloads as well so capture is decided by the
% actual composite decoder rather than by a Boolean near/far threshold.
msg3Waves = cell(nUE, 1);
msg3TxByUE = cell(nUE, 1);
for ii = 1:nUE
    gg = groupOfUE(ii);
    reference = puschTx{gg};
    ra = raConfigs{ii};
    ra.Msg3PUSCH.PRBStart = ...
        reference.ContentionRAConfig.Msg3PUSCH.PRBStart;
    grant = sixgr.mac.ra.buildRARULGrant(ra);
    payload = sixgr.mac.ra.buildMsg3Payload( ...
        "UEId", ueIds(ii), ...
        "UEIdentity", "UE-" + string(round(ueIds(ii))), ...
        "RRCSetupRequest", true);
    [tx, ~] = sixgr.phy.ra.generateMsg3PUSCHWaveform( ...
        cfg, ra, grant, payload);
    tx.ContentionRAConfig = ra;
    tx.ContentionGrant = grant;
    tx.ContentionPayload = payload;
    msg3TxByUE{ii} = tx;
    msg3Waves{ii} = tx;
end
msg3Composite = localComposite(msg3Waves, powers);
[msg3Rx, msg3NoiseVariance] = localAddNoise( ...
    msg3Composite, double(opt.SNRdB), double(opt.Seed) + 1);

groupRows = repmat(localGroupRow(), nGroups, 1);
decodedUEs = nan(nGroups, 1);
for gg = 1:nGroups
    strongest = groupStrongestIndex(gg);
    tx = msg3TxByUE{strongest};
    [rx, decoded] = sixgr.phy.ra.recoverMsg3PUSCH( ...
        msg3Rx, cfg, tx.ContentionRAConfig, ...
        tx.ContentionGrant, tx);
    crc = logical(sixgr.util.structGet(rx, "Ok", false));
    decodedIdentity = string(sixgr.util.structGet( ...
        decoded, "RRCSetupRequest.UEIdentity", ""));
    decodedUE = localUEFromIdentity(decodedIdentity);
    decodedUEs(gg) = decodedUE;
    members = groupMembers{gg};
    samePreambleCollision = numel(members) > 1;
    capturedMember = any(ueIds(members) == decodedUE);
    captured = samePreambleCollision && crc && capturedMember;
    groupRows(gg) = localGroupRow( ...
        "GroupID", gg, ...
        "PreambleIndex", groupPreambles(gg), ...
        "UECount", numel(members), ...
        "UEIDs", strjoin(string(ueIds(members)), "|"), ...
        "RelativePowersdB", strjoin(string(powers(members)), "|"), ...
        "SamePreambleCollision", samePreambleCollision, ...
        "StrongestUEID", groupStrongestUE(gg), ...
        "NearFar_dB", max(powers(members)) - min(powers(members)), ...
        "Msg3CRC", crc, ...
        "DecodedUEID", decodedUE, ...
        "DecodedRRCSetupRequest", ...
            logical(sixgr.util.structGet( ...
            decoded, "RRCSetupRequestPresent", false)), ...
        "CaptureDetected", captured, ...
        "CapturedStrongest", ...
            captured && decodedUE == groupStrongestUE(gg), ...
        "GrantSHA256", sixgr.rrc.asn1.sha256Hex( ...
            uint8(tx.ContentionGrant.BitVector(:))), ...
        "CompositeWaveformSHA256", localWaveformHash(msg3Composite), ...
        "Status", string(ternary( ...
            crc && (~samePreambleCollision || captured), ...
            "PASS", "UNRESOLVED")));
end

ueRows = repmat(localUERow(), nUE, 1);
for ii = 1:nUE
    gg = groupOfUE(ii);
    peakIndex = find(candidates == preambles(ii), 1);
    peak = NaN;
    if ~isempty(peakIndex) && peakIndex <= numel(peaks)
        peak = peaks(peakIndex);
    end
    msg3Winner = decodedUEs(gg) == ueIds(ii);
    ueRows(ii) = localUERow( ...
        "UEID", ueIds(ii), ...
        "PreambleIndex", preambles(ii), ...
        "RelativePower_dB", powers(ii), ...
        "PRACHPeakMetric", peak, ...
        "PRACHDetected", isfinite(peak) && peak >= threshold, ...
        "CollisionGroupID", gg, ...
        "Msg3Winner", msg3Winner, ...
        "ContentionResolved", msg3Winner, ...
        "Outcome", string(ternary(msg3Winner, ...
            "winner", "contention_loser")), ...
        "Status", string(ternary(msg3Winner, "PASS", "EXPECTED_LOSS")));
end

groups = struct2table(groupRows, "AsArray", true);
ues = struct2table(ueRows, "AsArray", true);
result = struct( ...
    "Resolved", all(groups.Status == "PASS"), ...
    "NumUEs", nUE, "NumPreambleGroups", nGroups, ...
    "Groups", groups, "UEs", ues, ...
    "PRACHDetector", detector, ...
    "Msg1NoiseVariance", msg1NoiseVariance, ...
    "Msg3NoiseVariance", msg3NoiseVariance, ...
    "Msg1CompositeSHA256", localWaveformHash(msg1Composite), ...
    "Msg3CompositeSHA256", localWaveformHash(msg3Composite), ...
    "ExecutionBackend", ...
        "composite_PRACH_and_PUSCH_Tx/PUSCH_Rx", ...
    "ProxyUsed", false, "FallbackUsed", false, ...
    "Source", "production_multi_ue_waveform");
end

function waveform = localComposite(transmissions, powersdB)
reference = transmissions{1}.Waveform;
waveform = zeros(size(reference), "like", reference);
for ii = 1:numel(transmissions)
    candidate = transmissions{ii}.Waveform;
    if ~isequal(size(candidate), size(reference))
        error("sixgr:phy:ra:ContentionWaveformSizeMismatch", ...
            "All contention transmissions must use a common carrier timeline.");
    end
    waveform = waveform + candidate .* ...
        cast(10 .^ (powersdB(ii) / 20), "like", candidate);
end
end

function [rx, noiseVariance] = localAddNoise(waveform, snrDB, seed)
rng(seed, "twister");
signalPower = mean(abs(waveform(:)).^2, "omitnan");
[rx, noiseVariance] = sixgr.util.addAwgnComplex( ...
    waveform, snrDB, "SignalPower", signalPower);
end

function tf = localSameOccasion(a, b)
fields = ["FrameNumber","SlotIndex0","SymbolLocation", ...
    "FrequencyIndex"];
tf = true;
for name = fields
    tf = tf && isequaln( ...
        sixgr.util.structGet(a, name, NaN), ...
        sixgr.util.structGet(b, name, NaN));
end
end

function value = localUEFromIdentity(identity)
token = regexp(char(identity), '^UE-(\d+)$', 'tokens', 'once');
if isempty(token)
    value = NaN;
else
    value = str2double(token{1});
end
end

function hash = localWaveformHash(waveform)
bytes = typecast([real(waveform(:)); imag(waveform(:))], "uint8");
hash = sixgr.rrc.asn1.sha256Hex(bytes);
end

function row = localGroupRow(varargin)
row = struct( ...
    "GroupID", NaN, "PreambleIndex", NaN, "UECount", NaN, ...
    "UEIDs", "", "RelativePowersdB", "", ...
    "SamePreambleCollision", false, "StrongestUEID", NaN, ...
    "NearFar_dB", NaN, "Msg3CRC", false, ...
    "DecodedUEID", NaN, "DecodedRRCSetupRequest", false, ...
    "CaptureDetected", false, "CapturedStrongest", false, ...
    "GrantSHA256", "", ...
    "CompositeWaveformSHA256", "", "Status", "");
for ii = 1:2:nargin
    row.(char(string(varargin{ii}))) = varargin{ii + 1};
end
end

function row = localUERow(varargin)
row = struct( ...
    "UEID", NaN, "PreambleIndex", NaN, ...
    "RelativePower_dB", NaN, "PRACHPeakMetric", NaN, ...
    "PRACHDetected", false, "CollisionGroupID", NaN, ...
    "Msg3Winner", false, "ContentionResolved", false, ...
    "Outcome", "", "Status", "");
for ii = 1:2:nargin
    row.(char(string(varargin{ii}))) = varargin{ii + 1};
end
end

function out = ternary(condition, a, b)
if condition
    out = a;
else
    out = b;
end
end
