function result = runMsg3HARQ(cfg, varargin)
%RUNMSG3HARQ Execute waveform-backed Msg3 HARQ with position-aware combining.
%
% Every row is backed by a PUSCH/UL-SCH transmit and receive execution.
% The decoded RAR grant dimensions are represented by buildRARULGrant;
% retransmissions retain the TB/NDI and apply the configured RV sequence.

p = inputParser;
p.addParameter("UEId", 1, @(x)isnumeric(x) && isscalar(x));
p.addParameter("SNRdB", 35, @(x)isnumeric(x) && isscalar(x));
p.addParameter("RVSequence", [0 2 3 1], ...
    @(x)isnumeric(x) && isvector(x) && ~isempty(x));
p.addParameter("Seed", 31001, @(x)isnumeric(x) && isscalar(x));
p.addParameter("StopOnSuccess", true, ...
    @(x)islogical(x) || isnumeric(x));
p.parse(varargin{:});
opt = p.Results;

raCfg = sixgr.mac.ra.RAConfig(cfg, ...
    "UEId", double(opt.UEId), "AttemptId", 1);
grant = sixgr.mac.ra.buildRARULGrant(raCfg);
payload = sixgr.mac.ra.buildMsg3Payload( ...
    "UEId", double(opt.UEId), ...
    "UEIdentity", "UE-" + string(round(double(opt.UEId))), ...
    "RRCSetupRequest", true);
rvSequence = double(opt.RVSequence(:));
if any(~ismember(rvSequence, [0 1 2 3]))
    error("sixgr:phy:ra:InvalidMsg3HARQRVSequence", ...
        "Msg3 HARQ RV values must be selected from [0,1,2,3].");
end

rows = repmat(localRow(), numel(rvSequence), 1);
priorSoftBuffer = [];
completed = false;
lastTx = struct();
lastRx = struct();
for roundIndex = 1:numel(rvSequence)
    roundGrant = grant;
    roundGrant.RV = rvSequence(roundIndex);
    [tx, ~] = sixgr.phy.ra.generateMsg3PUSCHWaveform( ...
        cfg, raCfg, roundGrant, payload);
    rng(double(opt.Seed) + roundIndex - 1, "twister");
    signalPower = mean(abs(tx.Waveform(:)).^2, "omitnan");
    [rxWaveform, noiseVariance] = sixgr.util.addAwgnComplex( ...
        tx.Waveform, double(opt.SNRdB), ...
        "SignalPower", signalPower);
    [rx, decoded] = sixgr.phy.ra.recoverMsg3PUSCH( ...
        rxWaveform, cfg, raCfg, roundGrant, tx);
    harq = sixgr.link.evaluateHARQDecode( ...
        tx, rx, cfg, priorSoftBuffer);
    currentOK = logical(harq.CurrentDecodeOK) && ...
        logical(sixgr.util.structGet( ...
        decoded, "RRCSetupRequestPresent", false));
    combinedOK = logical(harq.CombinedDecodeOK);
    completed = currentOK || combinedOK;
    softBuffer = harq.HARQSoftBuffer;
    rows(roundIndex) = localRow( ...
        "HARQProcess", 0, ...
        "HARQRound", roundIndex - 1, ...
        "NDI", 1, ...
        "RV", rvSequence(roundIndex), ...
        "TBIdentitySHA256", sixgr.rrc.asn1.asn1SHA256Hex( ...
            int8(tx.TransportBlock(:))), ...
        "RRCSetupRequestSHA256", ...
            string(payload.RRCSetupRequestSHA256), ...
        "CRC", logical(currentOK || combinedOK), ...
        "SoftBufferSHA256", localSoftBufferHash(softBuffer), ...
        "Combined", logical(harq.HARQSoftCombiningApplied), ...
        "CompletionSlot", double(raCfg.Msg3Slot + roundIndex - 1), ...
        "CurrentDecodeOK", logical(currentOK), ...
        "CombinedDecodeOK", logical(combinedOK), ...
        "NoiseVariance", double(noiseVariance), ...
        "MeasuredSINR_dB", double(harq.MeasuredSINR_dB), ...
        "LLRCombiningGain_dB", double(harq.LLRCombiningGain_dB), ...
        "Status", string(ternary(completed, "PASS", "RETRANSMIT")));
    priorSoftBuffer = softBuffer;
    lastTx = tx;
    lastRx = rx;
    if completed && logical(opt.StopOnSuccess)
        rows = rows(1:roundIndex);
        break;
    end
end

result = struct( ...
    "Completed", logical(completed), ...
    "Rounds", struct2table(rows, "AsArray", true), ...
    "Payload", payload, ...
    "Grant", grant, ...
    "LastTx", lastTx, ...
    "LastRx", lastRx, ...
    "ProxyUsed", false, ...
    "FallbackUsed", false, ...
    "ExecutionBackend", "PUSCH_Tx/PUSCH_Rx/UL-SCH", ...
    "Source", "production_waveform_harq");
end

function row = localRow(varargin)
row = struct( ...
    "HARQProcess", NaN, "HARQRound", NaN, "NDI", NaN, ...
    "RV", NaN, "TBIdentitySHA256", "", ...
    "RRCSetupRequestSHA256", "", "CRC", false, ...
    "SoftBufferSHA256", "", "Combined", false, ...
    "CompletionSlot", NaN, "CurrentDecodeOK", false, ...
    "CombinedDecodeOK", false, "NoiseVariance", NaN, ...
    "MeasuredSINR_dB", NaN, "LLRCombiningGain_dB", NaN, ...
    "Status", "");
if nargin == 0
    return;
end
for ii = 1:2:nargin
    row.(char(string(varargin{ii}))) = varargin{ii + 1};
end
end

function hash = localSoftBufferHash(softBuffer)
try
    text = jsonencode(softBuffer);
catch
    text = evalc("disp(softBuffer)");
end
hash = sixgr.rrc.asn1.asn1SHA256Hex( ...
    uint8(unicode2native(text, "UTF-8")));
end

function out = ternary(condition, a, b)
if condition
    out = a;
else
    out = b;
end
end
