function sched = scheduleMsg4(raCfg)
% Exact TC-RNTI DCI 1_0; no custom PRB-count/symbol-count payload.
policy = raCfg.Msg4DCI;
context = sixgr.phy.pdcch.TCMsg4DCIContext.create(raCfg.Msg4DCIReference, ...
    raCfg.TempCRNTI,policy.harq_ack_repetitions_configured);
[rows,~] = sixgr.phy.pdcch.RARDCIContext.defaultA( ...
    context.Data.CyclicPrefix,context.Data.DMRSTypeAPosition);
s = raCfg.Msg4PDSCH;
row = find(rows(:,2)==s.SymbolStart & rows(:,3)==s.NumSymbols & rows(:,4)==0);
assert(numel(row)==1,'sixgr:phy:ra:InvalidMsg4TDRA', ...
    'Configured Msg4 must match a common default-A TDRA row; no custom time allocation may be encoded.');
start = s.PRBStart+raCfg.NStartGrid-context.Data.FrequencyReferenceStart;
fields = struct('format_identifier',1, ...
    'frequency_resource_assignment',sixgr.bwop.RIVFDRA.encode(context.Data.FrequencyReferenceSize,start,s.NumPRB), ...
    'time_resource_assignment',rows(row,1),'vrb_to_prb_mapping',0,'mcs',s.MCS, ...
    'ndi',policy.ndi,'rv',s.RV,'harq_process',policy.harq_process,'dai',0, ...
    'tpc_command_for_pucch',policy.tpc_command_for_pucch, ...
    'pucch_resource_indicator',policy.pucch_resource_indicator, ...
    'pdsch_to_harq_feedback_timing',policy.pdsch_to_harq_feedback_timing);
dci = sixgr.phy.pdcch.DCIPacker.pack(fields,context);
sched = sixgr.phy.ra.msg4ScheduleFromDCI(raCfg,dci.Bits,context);
assert(s.NLayers==1 && ~s.EnablePTRS && string(s.MCSTable)=="qam64" && ...
    string(s.Modulation)==sched.Modulation && abs(s.TargetCodeRate-sched.TargetCodeRate)<1e-12, ...
    'sixgr:phy:ra:InvalidMsg4CommonPDSCH', ...
    'TC-RNTI Msg4 requires common single-layer/no-PT-RS configuration and the actual indicated MCS rate.');
end
