function msg = buildBCCHDLSCHMessage(cfg, varargin)
%BUILDBCCHDLSCHMESSAGE Build the supported SIB1 BCCH-DL-SCH IE tree.
%
% This is the repository's constrained TS 38.331 SIB1 profile for strict
% initial-access evidence. Unsupported optional IEs are rejected by
% validateSIB1ForScenario rather than silently omitted.

p = inputParser;
p.addParameter("CellID", [], @(x) isempty(x) || (isnumeric(x) && isscalar(x)));
p.parse(varargin{:});

if nargin < 1 || isempty(cfg)
    cfg = struct();
end

ncellid = localFirstFinite(p.Results.CellID, ...
    sixgr.util.structGet(cfg, "phy.carrier.NCellID", []), ...
    sixgr.util.structGet(cfg, "phy.NCellID", []), 1);
scsCommon = localFirstFinite( ...
    sixgr.util.structGet(cfg, "phy.carrier.SubcarrierSpacing", []), ...
    sixgr.util.structGet(cfg, "phy.carrier.SubcarrierSpacing_kHz", []), 30);
nSizeGrid = localFirstFinite(sixgr.util.structGet(cfg, "phy.carrier.NSizeGrid", []), 52);
fcHz = localFirstFinite(sixgr.util.structGet(cfg, "phy.fc_Hz", []), ...
    sixgr.util.structGet(cfg, "channel.fc_Hz", []), 4e9);

prachCfg = struct( ...
    "configurationIndex", localFirstFinite(sixgr.util.structGet(cfg, "phy.prach.configurationIndex", []), 16), ...
    "rootSequenceIndex", localFirstFinite(sixgr.util.structGet(cfg, "phy.prach.rootSeqIndex", []), 1), ...
    "zeroCorrelationZoneConfig", localFirstFinite(sixgr.util.structGet(cfg, "phy.prach.zeroCorrelationZone", []), 8), ...
    "restrictedSet", string(sixgr.util.structGet(cfg, "phy.prach.restrictedSet", "UnrestrictedSet")), ...
    "msg1SubcarrierSpacing_kHz", localFirstFinite(sixgr.util.structGet(cfg, "phy.prach.subcarrierSpacing_kHz", []), ...
        sixgr.util.structGet(cfg, "random_access.subcarrier_spacing_khz", []), scsCommon), ...
    "msg1FDM", "one", ...
    "msg1FrequencyStart", 0, ...
    "preambleReceivedTargetPower_dBm", -96, ...
    "preambleTransMax", "n10", ...
    "powerRampingStep", "dB2", ...
    "raResponseWindow", "sl10", ...
    "nPreambles", localFirstFinite(sixgr.util.structGet(cfg, "phy.prach.nPreambles", []), 64), ...
    "preambleFormat", string(sixgr.util.structGet(cfg, "phy.prach.preambleFormat", "A1")));

cellAccess = struct( ...
    "plmn_IdentityList", localPLMNList(cfg), ...
    "trackingAreaCode", localFirstFinite(sixgr.util.structGet(cfg, "rrc.sib1.tac", []), 1), ...
    "cellIdentity", localFirstFinite(sixgr.util.structGet(cfg, "rrc.sib1.cellIdentity", []), ncellid), ...
    "cellReservedForOperatorUse", "notReserved");

servingCommon = struct();
servingCommon.downlinkConfigCommon = struct( ...
    "frequencyInfoDL", struct( ...
        "absoluteFrequencySSB", round(fcHz / 1e5), ...
        "dl_AbsoluteFrequencyPointA", round(fcHz / 1e5), ...
        "scs_SpecificCarrierList", struct( ...
            "offsetToCarrier", 0, ...
            "subcarrierSpacing", localSCSName(scsCommon), ...
            "carrierBandwidth", round(nSizeGrid))), ...
    "initialDownlinkBWP", struct( ...
        "genericParameters", struct( ...
            "locationAndBandwidth", round(nSizeGrid), ...
            "subcarrierSpacing", localSCSName(scsCommon), ...
            "cyclicPrefix", "normal"), ...
        "pdcch_ConfigCommon", struct( ...
            "pdcch_ConfigSIB1", struct( ...
                "controlResourceSetZero", localFirstFinite(sixgr.util.structGet(cfg, "phy.sib1.coreset0Index", []), 0), ...
                "searchSpaceZero", localFirstFinite(sixgr.util.structGet(cfg, "phy.sib1.searchSpaceZero", []), 0)), ...
            "commonSearchSpaceList", struct("searchSpaceId", 0)), ...
        "pdsch_ConfigCommon", struct("pdsch_TimeDomainAllocationList", struct("mappingType", "typeA", "startSymbolAndLength", 12))));
servingCommon.uplinkConfigCommon = struct( ...
    "frequencyInfoUL", struct( ...
        "absoluteFrequencyPointA", round(fcHz / 1e5), ...
        "scs_SpecificCarrierList", struct( ...
            "offsetToCarrier", 0, ...
            "subcarrierSpacing", localSCSName(scsCommon), ...
            "carrierBandwidth", round(nSizeGrid))), ...
    "initialUplinkBWP", struct( ...
        "genericParameters", struct( ...
            "locationAndBandwidth", round(nSizeGrid), ...
            "subcarrierSpacing", localSCSName(scsCommon), ...
            "cyclicPrefix", "normal"), ...
        "rach_ConfigCommon", prachCfg, ...
        "pusch_ConfigCommon", struct("msg3_DeltaPreamble", 0), ...
        "pucch_ConfigCommon", struct("pucch_ResourceCommon", 0)));
servingCommon.ssb_PositionsInBurst = struct("inOneGroup", "10000000");
servingCommon.ssb_periodicityServingCell = "ms20";
servingCommon.dmrs_TypeA_Position = localFirstFinite(sixgr.util.structGet(cfg, "phy.mib.dmrsTypeAPosition", []), 2);

sib1 = struct();
sib1.cellSelectionInfo = struct("q_RxLevMin", -70, "q_QualMin", -20);
sib1.cellAccessRelatedInfo = cellAccess;
sib1.si_SchedulingInfo = struct( ...
    "si_WindowLength", "s20", ...
    "schedulingInfoList", struct("si_BroadcastStatus", "broadcasting", "si_Periodicity", "rf16"));
sib1.servingCellConfigCommon = servingCommon;
sib1.uac_BarringInfo = struct("present", false);

msg = struct();
msg.asn1Release = "TS38331_anchor_profile_r2024a";
msg.profile = "sixgr_sib1_anchor_profile_v1";
msg.message = struct("c1", struct("systemInformationBlockType1", sib1));
sixgr.rrc.asn1.validateSIB1ForScenario(msg, cfg);
end

function list = localPLMNList(cfg)
plmn = string(sixgr.util.structGet(cfg, "rrc.sib1.plmn", "00101"));
plmn = erase(plmn, [" ", "-"]);
if strlength(plmn) < 5
    error("sixgr:rrc:asn1:BadPLMN", "SIB1 PLMN must contain MCC+MNC digits.");
end
list = struct( ...
    "mcc", extractBetween(plmn, 1, 3), ...
    "mnc", extractAfter(plmn, 3), ...
    "trackingAreaCode", localFirstFinite(sixgr.util.structGet(cfg, "rrc.sib1.tac", []), 1), ...
    "cellIdentity", localFirstFinite(sixgr.util.structGet(cfg, "rrc.sib1.cellIdentity", []), ...
    sixgr.util.structGet(cfg, "phy.carrier.NCellID", 1)));
list.mcc = string(list.mcc);
list.mnc = string(list.mnc);
end

function value = localFirstFinite(varargin)
value = NaN;
for i = 1:nargin
    raw = varargin{i};
    if isempty(raw)
        continue;
    end
    raw = double(raw);
    if isscalar(raw) && isfinite(raw)
        value = raw;
        return;
    end
end
end

function name = localSCSName(scs)
switch round(double(scs))
    case 15
        name = "kHz15";
    case 30
        name = "kHz30";
    case 60
        name = "kHz60";
    case 120
        name = "kHz120";
    otherwise
        error("sixgr:rrc:asn1:UnsupportedSCS", ...
            "Unsupported SIB1 common SCS %.3g kHz for anchor profile.", double(scs));
end
end
