function msg = buildBCCHDLSCHMessage(cfg, varargin)
%BUILDBCCHDLSCHMESSAGE Build the supported SIB1 BCCH-DL-SCH IE tree.
%
% This is the repository's constrained TS 38.331 SIB1 profile for strict
% initial-access evidence. Unsupported optional IEs are rejected by
% validateSIB1ForScenario rather than silently omitted.

p = inputParser;
p.addParameter("CellID", [], @(x) isempty(x) || (isnumeric(x) && isscalar(x)));
p.parse(varargin{:});

if nargin < 1 || isempty(cfg)
    cfg = struct();
end

ncellid = localFirstFinite(p.Results.CellID, ...
    sixgr.util.structGet(cfg, "phy.carrier.NCellID", []), ...
    sixgr.util.structGet(cfg, "phy.NCellID", []), 1);
scsCommon = localFirstFinite( ...
    sixgr.util.structGet(cfg, "phy.carrier.SubcarrierSpacing", []), ...
    sixgr.util.structGet(cfg, "phy.carrier.SubcarrierSpacing_kHz", []), 30);
nSizeGrid = localFirstFinite(sixgr.util.structGet(cfg, "phy.carrier.NSizeGrid", []), 52);
fcHz = localFirstFinite(sixgr.util.structGet(cfg, "phy.fc_Hz", []), ...
    sixgr.util.structGet(cfg, "channel.fc_Hz", []), 4e9);
band = localBandNumber(cfg);
arfcn = localNRARFCN(fcHz);
locationAndBandwidth = localBWPResourceIndicatorValue( ...
    0, round(nSizeGrid), 275);

prachCfg = struct( ...
    "configurationIndex", localFirstFinite(sixgr.util.structGet(cfg, "phy.prach.configurationIndex", []), 16), ...
    "rootSequenceIndex", localFirstFinite(sixgr.util.structGet(cfg, "phy.prach.rootSeqIndex", []), 1), ...
    "zeroCorrelationZoneConfig", localFirstFinite(sixgr.util.structGet(cfg, "phy.prach.zeroCorrelationZone", []), 8), ...
    "restrictedSet", string(sixgr.util.structGet(cfg, "phy.prach.restrictedSet", "UnrestrictedSet")), ...
    "msg1SubcarrierSpacing_kHz", localFirstFinite(sixgr.util.structGet(cfg, "phy.prach.subcarrierSpacing_kHz", []), ...
        sixgr.util.structGet(cfg, "random_access.subcarrier_spacing_khz", []), scsCommon), ...
    "msg1FDM", localFDMName(localFirstFinite( ...
        sixgr.util.structGet(cfg, "random_access.msg1_fdm", []), 1)), ...
    "msg1FrequencyStart", localFirstFinite( ...
        sixgr.util.structGet(cfg, "random_access.frequency_start", []), 0), ...
    "preambleReceivedTargetPower_dBm", localFirstFinite( ...
        sixgr.util.structGet(cfg, ...
        "random_access.preamble_received_target_power_dbm", []), -96), ...
    "preambleTransMax", "n" + string(round(localFirstFinite( ...
        sixgr.util.structGet(cfg, "random_access.preamble_trans_max", []), 10))), ...
    "powerRampingStep", "dB" + string(round(localFirstFinite( ...
        sixgr.util.structGet(cfg, "random_access.power_ramping_step_db", []), 2))), ...
    "raResponseWindow", "sl" + string(round(localFirstFinite( ...
        sixgr.util.structGet(cfg, "random_access.ra_response_window_slots", []), 10))), ...
    "nPreambles", localFirstFinite(sixgr.util.structGet(cfg, "phy.prach.nPreambles", []), 64), ...
    "preambleFormat", string(sixgr.util.structGet(cfg, "phy.prach.preambleFormat", ...
        sixgr.util.structGet(cfg, "random_access.prach_format", "A1"))), ...
    "ssbPerRACHChoice", string(sixgr.util.structGet(cfg, ...
        "rrc.sib1.ssb_per_rach_choice", "one")), ...
    "cbPreamblesPerSSB", string(sixgr.util.structGet(cfg, ...
        "rrc.sib1.cb_preambles_per_ssb", "n64")), ...
    "contentionResolutionTimer", "sf" + string(round(localFirstFinite( ...
        sixgr.util.structGet(cfg, ...
        "random_access.ra_contention_resolution_timer_slots", []), 64))));

cellAccess = struct( ...
    "plmn_IdentityList", localPLMNList(cfg), ...
    "trackingAreaCode", localFirstFinite(sixgr.util.structGet(cfg, "rrc.sib1.tac", []), 1), ...
    "cellIdentity", localFirstFinite(sixgr.util.structGet(cfg, "rrc.sib1.cellIdentity", []), ncellid), ...
    "cellReservedForOperatorUse", "notReserved");

servingCommon = struct();
servingCommon.downlinkConfigCommon = struct( ...
    "frequencyInfoDL", struct( ...
        "frequencyBandList", struct("freqBandIndicatorNR", band), ...
        "absoluteFrequencySSB", arfcn, ...
        "dl_AbsoluteFrequencyPointA", arfcn, ...
        "offsetToPointA", 0, ...
        "scs_SpecificCarrierList", struct( ...
            "offsetToCarrier", 0, ...
            "subcarrierSpacing", localSCSName(scsCommon), ...
            "carrierBandwidth", round(nSizeGrid))), ...
    "initialDownlinkBWP", struct( ...
        "genericParameters", struct( ...
            "locationAndBandwidth", locationAndBandwidth, ...
            "subcarrierSpacing", localSCSName(scsCommon), ...
            "cyclicPrefix", "normal"), ...
        "pdcch_ConfigCommon", struct( ...
            "pdcch_ConfigSIB1", struct( ...
                "controlResourceSetZero", localFirstFinite(sixgr.util.structGet(cfg, "phy.sib1.coreset0Index", []), 0), ...
                "searchSpaceZero", localFirstFinite(sixgr.util.structGet(cfg, "phy.sib1.searchSpaceZero", []), 0)), ...
            "commonSearchSpaceList", struct("searchSpaceId", 0)), ...
        "pdsch_ConfigCommon", struct("pdsch_TimeDomainAllocationList", struct("mappingType", "typeA", "startSymbolAndLength", 12))), ...
    "bcch_Config", struct("modificationPeriodCoeff", string( ...
        sixgr.util.structGet(cfg, "rrc.sib1.modification_period_coeff", "n2"))), ...
    "pcch_Config", struct( ...
        "defaultPagingCycle", string(sixgr.util.structGet(cfg, ...
            "rrc.sib1.default_paging_cycle", "rf128")), ...
        "nAndPagingFrameOffset", struct( ...
            "choice", string(sixgr.util.structGet(cfg, ...
                "rrc.sib1.paging_frame_choice", "oneT")), ...
            "offset", localFirstFinite(sixgr.util.structGet(cfg, ...
                "rrc.sib1.paging_frame_offset", []), 0)), ...
        "ns", string(sixgr.util.structGet(cfg, ...
            "rrc.sib1.paging_ns", "one"))));
servingCommon.uplinkConfigCommon = struct( ...
    "frequencyInfoUL", struct( ...
        "frequencyBandList", struct("freqBandIndicatorNR", band), ...
        "absoluteFrequencyPointA", arfcn, ...
        "scs_SpecificCarrierList", struct( ...
            "offsetToCarrier", 0, ...
            "subcarrierSpacing", localSCSName(scsCommon), ...
            "carrierBandwidth", round(nSizeGrid))), ...
    "initialUplinkBWP", struct( ...
        "genericParameters", struct( ...
            "locationAndBandwidth", locationAndBandwidth, ...
            "subcarrierSpacing", localSCSName(scsCommon), ...
            "cyclicPrefix", "normal"), ...
        "rach_ConfigCommon", prachCfg, ...
        "pusch_ConfigCommon", struct("msg3_DeltaPreamble", 0), ...
        "pucch_ConfigCommon", struct("pucch_ResourceCommon", 0)), ...
    "timeAlignmentTimerCommon", string(sixgr.util.structGet(cfg, ...
        "rrc.sib1.time_alignment_timer", "infinity")));
servingCommon.ssb_PositionsInBurst = struct("inOneGroup", ...
    localCanonicalSIB1SSBPositions(cfg));
servingCommon.ssb_periodicityServingCell = string(sixgr.util.structGet(cfg, ...
    "initial_access.ssb.periodicity_ms", "ms20"));
if ~startsWith(servingCommon.ssb_periodicityServingCell, "ms")
    servingCommon.ssb_periodicityServingCell = ...
        "ms" + string(servingCommon.ssb_periodicityServingCell);
end

servingCommon.ss_PBCH_BlockPower = localFirstFinite(sixgr.util.structGet(cfg, ...
    "rrc.sib1.ss_pbch_block_power_dbm", []), -25);
servingCommon.dmrs_TypeA_Position = localFirstFinite(sixgr.util.structGet(cfg, "phy.mib.dmrsTypeAPosition", []), 2);

sib1 = struct();
sib1.cellSelectionInfo = struct("q_RxLevMin", -70, "q_QualMin", -20);
sib1.cellAccessRelatedInfo = cellAccess;
sib1.si_SchedulingInfo = struct( ...
    "si_WindowLength", string(sixgr.util.structGet(cfg, ...
        "rrc.sib1.si_window_length", "s20")), ...
    "schedulingInfoList", struct( ...
        "si_BroadcastStatus", string(sixgr.util.structGet(cfg, ...
            "rrc.sib1.si_broadcast_status", "broadcasting")), ...
        "si_Periodicity", string(sixgr.util.structGet(cfg, ...
            "rrc.sib1.si_periodicity", "rf16")), ...
        "mappedSIBType", string(sixgr.util.structGet(cfg, ...
            "rrc.sib1.mapped_sib_type", "sibType2"))));
sib1.servingCellConfigCommon = servingCommon;
sib1.ue_TimersAndConstants = struct( ...
    "t300", string(sixgr.util.structGet(cfg, "rrc.sib1.t300", "ms200")), ...
    "t301", string(sixgr.util.structGet(cfg, "rrc.sib1.t301", "ms200")), ...
    "t310", string(sixgr.util.structGet(cfg, "rrc.sib1.t310", "ms100")), ...
    "n310", string(sixgr.util.structGet(cfg, "rrc.sib1.n310", "n1")), ...
    "t311", string(sixgr.util.structGet(cfg, "rrc.sib1.t311", "ms1000")), ...
    "n311", string(sixgr.util.structGet(cfg, "rrc.sib1.n311", "n1")), ...
    "t319", string(sixgr.util.structGet(cfg, "rrc.sib1.t319", "ms200")));
sib1.uac_BarringInfo = struct("present", false);

msg = struct();
msg.asn1Release = "3GPP_TS_38_331_V18_9_0";
msg.profile = "3gpp_ts38331_v18_bounded_fr1_sib1";
msg.message = struct("c1", struct("systemInformationBlockType1", sib1));
sixgr.rrc.asn1.validateSIB1ForScenario(msg, cfg);
end

function bitmap = localCanonicalSIB1SSBPositions(cfg)
% The bounded Release-18 codec represents inOneGroup as one octet.  Runtime
% Case-A/B/C burst planning may legitimately use the four-bit short bitmap;
% canonicalize that semantic value before hashing the transmit tree so the
% independently decoded ASN.1 tree is compared in the same representation.
bitmap = string(sixgr.util.structGet( ...
    cfg, "initial_access.ssb.positions_in_burst", "10000000"));
bitmap = erase(strtrim(bitmap), [" ", "_"]);
if ~isscalar(bitmap) || strlength(bitmap) == 0 || ...
        ~all(ismember(char(bitmap), ['0','1']))
    error("sixgr:rrc:asn1:InvalidSSBPositionsInBurst", ...
        "SIB1 ssb-PositionsInBurst must be a nonempty binary bitmap.");
end
if strlength(bitmap) == 4
    bitmap = pad(bitmap, 8, "left", "0");
elseif strlength(bitmap) ~= 8
    error("sixgr:rrc:asn1:UnsupportedSSBPositionsInBurst", ...
        "The bounded FR1 SIB1 profile accepts a 4-bit short or 8-bit medium bitmap.");
end
end

function riv = localBWPResourceIndicatorValue(startRB, lengthRB, nRB)
if ~(isscalar(startRB) && isscalar(lengthRB) && isscalar(nRB) && ...
        all(isfinite([startRB, lengthRB, nRB])) && ...
        all([startRB, lengthRB, nRB] == fix([startRB, lengthRB, nRB])) && ...
        startRB >= 0 && lengthRB >= 1 && ...
        startRB + lengthRB <= nRB)
    error("sixgr:rrc:asn1:InvalidBWPAllocation", ...
        "BWP allocation must be an integer interval inside the reference grid.");
end
if lengthRB - 1 <= floor(nRB / 2)
    riv = nRB * (lengthRB - 1) + startRB;
else
    riv = nRB * (nRB - lengthRB + 1) + (nRB - 1 - startRB);
end
end

function band = localBandNumber(cfg)
raw = string(sixgr.util.structGet(cfg, "frequency.band_name", ...
    sixgr.util.structGet(cfg, "initial_access.band_context", "n78")));
token = regexp(char(raw), '\d+', 'match', 'once');
band = str2double(token);
if ~(isfinite(band) && band >= 1 && band <= 1024)
    error("sixgr:rrc:asn1:UnsupportedBand", ...
        "A concrete NR band such as n78 is required for SIB1.");
end
end

function arfcn = localNRARFCN(fcHz)
frequencyMHz = double(fcHz) / 1e6;
if frequencyMHz < 3000
    arfcn = round(frequencyMHz / 0.005);
elseif frequencyMHz < 24250.08
    arfcn = round(600000 + (frequencyMHz - 3000) / 0.015);
else
    arfcn = round(2016667 + (frequencyMHz - 24250.08) / 0.06);
end
if ~(arfcn >= 0 && arfcn <= 3279165)
    error("sixgr:rrc:asn1:UnsupportedFrequency", ...
        "Carrier frequency %.12g Hz does not map to NR-ARFCN.", fcHz);
end
end

function name = localFDMName(value)
values = [1 2 4 8];
names = ["one","two","four","eight"];
index = find(values == round(double(value)), 1);
if isempty(index)
    error("sixgr:rrc:asn1:UnsupportedSIB1IE", ...
        "msg1-FDM must be 1, 2, 4, or 8.");
end
name = names(index);
end

function list = localPLMNList(cfg)
plmn = string(sixgr.util.structGet(cfg, "rrc.sib1.plmn", "00101"));
plmn = erase(plmn, [" ", "-"]);
if strlength(plmn) < 5
    error("sixgr:rrc:asn1:BadPLMN", "SIB1 PLMN must contain MCC+MNC digits.");
end
list = struct( ...
    "mcc", extractBetween(plmn, 1, 3), ...
    "mnc", extractAfter(plmn, 3), ...
    "trackingAreaCode", localFirstFinite(sixgr.util.structGet(cfg, "rrc.sib1.tac", []), 1), ...
    "cellIdentity", localFirstFinite(sixgr.util.structGet(cfg, "rrc.sib1.cellIdentity", []), ...
    sixgr.util.structGet(cfg, "phy.carrier.NCellID", 1)));
list.mcc = string(list.mcc);
list.mnc = string(list.mnc);
end

function value = localFirstFinite(varargin)
value = NaN;
for i = 1:nargin
    raw = varargin{i};
    if isempty(raw)
        continue;
    end
    raw = double(raw);
    if isscalar(raw) && isfinite(raw)
        value = raw;
        return;
    end
end
end

function name = localSCSName(scs)
switch round(double(scs))
    case 15
        name = "kHz15";
    case 30
        name = "kHz30";
    case 60
        name = "kHz60";
    case 120
        name = "kHz120";
    otherwise
        error("sixgr:rrc:asn1:UnsupportedSCS", ...
            "Unsupported SIB1 common SCS %.3g kHz for anchor profile.", double(scs));
end
end
