classdef PhysicalArrayLink
    %PHYSICALARRAYLINK Configured polarized arrays on an actual CDL waveform.
    % The port precoder is separate from the unit-total-power layer precoder.
    % No received-power normalization, perfect-CSI beam selection or decoder
    % assistance is performed. UL uses the transpose-reciprocal DL channel.
    methods (Static)
        function link=build(s,sampleRate)
            assert(isfield(s,'research_spatial'), ...
                'sixgr:research:MissingSpatialConfig','physical_cdl requires research_spatial.');
            p=s.research_spatial;
            catalog=sixgr.lls6g.config.loadParameterCatalog('scenario');
            assert(all(isfield(p,fieldnames(catalog.sections.research_spatial.parameters))), ...
                'sixgr:research:IncompleteSpatialConfig','Every research_spatial policy must be explicit.');
            assert(string(s.channels.model_type)=="CDL" && ...
                any(string(s.channels.profile)==["CDL-A","CDL-B","CDL-C","CDL-D","CDL-E"]) && ...
                s.channels.doppler_hz==0 && s.channels.mobility_kmph==0 && ...
                ~s.channels.pathloss_enabled && ~s.channels.shadow_fading_enabled && ...
                ~s.channels.spatial_consistency_enabled && ...
                string(p.burst_policy)=="static_independent_slots" && ...
                string(p.timing)=="configured_channel_filter_delay" && ...
                ~p.normalize_channel_outputs, ...
                'sixgr:research:UnsupportedSpatialPolicy', ...
                'Use concrete static CDL, independent bursts, configured filter timing, no geometry losses or receive-array normalization.');
            gnb=localArray(p,'gnb'); ue=localArray(p,'ue');
            wg=localWeights(p,'gnb',s.research_dl.num_layers);
            wu=localWeights(p,'ue',s.research_ul.num_layers);
            assert(prod(ue.Size)>=s.research_dl.num_layers && ...
                prod(gnb.Size)>=s.research_ul.num_layers, ...
                'sixgr:research:InsufficientReceiveElements','Receive arrays must support configured layers.');
            dl=nrCDLChannel('DelayProfile',char(s.channels.profile), ...
                'DelaySpread',s.channels.delay_spread_ns*1e-9, ...
                'MaximumDopplerShift',s.channels.doppler_hz, ...
                'CarrierFrequency',s.frequency.center_frequency_hz, ...
                'SampleRate',sampleRate,'RandomStream','mt19937ar with seed','Seed',p.seed, ...
                'NormalizePathGains',p.normalize_path_gains, ...
                'NormalizeChannelOutputs',p.normalize_channel_outputs);
            dl.TransmitAntennaArray=gnb; dl.ReceiveAntennaArray=ue;
            ul=clone(dl); swapTransmitAndReceive(ul);
            meta=struct('ChannelProfile',string(s.channels.profile), ...
                'ChannelSource',"nrCDLChannel_TR_38_901", ...
                'GNBElements',prod(gnb.Size),'UEElements',prod(ue.Size), ...
                'GNBRFChains',prod(gnb.Size),'UERFChains',prod(ue.Size), ...
                'Architecture',"fully_digital_physical_element_receiver", ...
                'GNBArray',gnb,'UEArray',ue,'DLLayers',size(wg,1),'ULLayers',size(wu,1), ...
                'PrecoderSource',"configured_2D_DFT_per_polarization_no_CSI", ...
                'ULReciprocity',"nrCDLChannel_swapTransmitAndReceive", ...
                'NormalizePathGains',logical(p.normalize_path_gains), ...
                'NormalizeChannelOutputs',logical(p.normalize_channel_outputs), ...
                'NoiseCalibration',"fixed_pre_channel_per_layer_reference_no_received_power_rescaling", ...
                'ChannelTiming',string(p.timing),'BurstPolicy',string(p.burst_policy), ...
                'AcquiredTiming',false,'ContinuousChannelMemory',false,'ChannelSeed',p.seed);
            link=struct('Channels',{{dl,ul}},'Weights',{{wg,wu}}, ...
                'TxElements',[prod(gnb.Size),prod(ue.Size)], ...
                'RxElements',[prod(ue.Size),prod(gnb.Size)],'Manifest',meta);
        end

        function [received,physicalTX,evidence]=apply(link,d,portWaveform)
            w=link.Weights{d}; ch=link.Channels{d};
            assert(size(portWaveform,2)==size(w,1), ...
                'sixgr:research:SpatialPortMismatch','Waveform ports differ from the configured array projection.');
            physicalTX=portWaveform*w;
            inputEnergy=sum(abs(portWaveform).^2,'all');
            physicalEnergy=sum(abs(physicalTX).^2,'all');
            relativeError=abs(inputEnergy-physicalEnergy)/max(inputEnergy,eps);
            assert(relativeError<1e-11,'sixgr:research:ArrayPowerMismatch', ...
                'Physical-element projection must preserve total transmitted energy.');
            reset(ch); % Explicit static independent-burst policy; same seed in DL/UL.
            ci=info(ch);
            delay=ci.ChannelFilterDelay;
            padding=ceil(max(ci.PathDelays)*ch.SampleRate)+delay;
            padded=[physicalTX; zeros(padding,size(physicalTX,2),'like',physicalTX)];
            filtered=ch(padded);
            received=filtered(delay+(1:size(portWaveform,1)),:);
            evidence=struct('PhysicalTxElements',size(physicalTX,2), ...
                'PhysicalRxElements',size(received,2),'ArrayProjectionRelativeEnergyError',relativeError, ...
                'TXTotalSamplePower',physicalEnergy/size(physicalTX,1), ...
                'RXTotalSignalSamplePower',mean(sum(abs(received).^2,2)), ...
                'ChannelFilterDelaySamples',delay);
        end

        function export(root,link)
            sixgr.util.jsonWrite(fullfile(root,'meta','physical_array.json'),link.Manifest);
            for d=1:2
                roles=["gnb","ue"]; w=link.Weights{d};
                [port,element]=ndgrid(1:size(w,1),1:size(w,2));
                T=table(port(:),element(:),real(w(:)),imag(w(:)), ...
                    'VariableNames',{'LogicalPort','PhysicalElement','WeightReal','WeightImag'});
                sixgr.util.csvWriteTable(fullfile(root,'beamforming','csv',roles(d)+"_precoder.csv"),T);
            end
        end
    end
end

function a=localArray(p,role)
sz=reshape(p.([role '_size']),1,[]);
validateattributes(sz,{'numeric'},{'integer','positive','finite','numel',5});
assert(sz(3)<=2 && all(sz(4:5)==1),'sixgr:research:UnsupportedArrayShape', ...
    'research_spatial supports one panel with one or two polarizations.');
spacing=reshape(p.spacing_wavelength,1,[]);
validateattributes(spacing,{'numeric'},{'positive','finite','numel',4});
angles=reshape(p.polarization_angles_deg,1,[]);
validateattributes(angles,{'numeric'},{'finite','numel',sz(3)});
orientation=reshape(p.([role '_orientation_deg']),[],1);
validateattributes(orientation,{'numeric'},{'finite','numel',3});
a=struct('Size',sz,'ElementSpacing',spacing,'PolarizationAngles',angles, ...
    'Orientation',orientation,'Element',char(p.element),'PolarizationModel',char(p.polarization_model));
end

function w=localWeights(p,role,layers)
sz=double(p.([role '_size'])); M=sz(1); N=sz(2); P=sz(3);
v=reshape(p.([role '_dft_vertical']),1,[]);
h=reshape(p.([role '_dft_horizontal']),1,[]);
pol=reshape(p.([role '_dft_polarization']),1,[]);
validateattributes(v,{'numeric'},{'integer','nonnegative','finite','numel',layers,'<',M});
validateattributes(h,{'numeric'},{'integer','nonnegative','finite','numel',layers,'<',N});
validateattributes(pol,{'numeric'},{'integer','nonnegative','finite','numel',layers,'<',P});
[m,n]=ndgrid(0:M-1,0:N-1); % Native nrCDL element order, vertical first.
w=complex(zeros(layers,prod(sz)));
for k=1:layers
    ix=pol(k)*M*N+(1:M*N);
    w(k,ix)=reshape(exp(2j*pi*(m*v(k)/M+n*h(k)/N)),1,[])/sqrt(M*N);
end
assert(norm(w*w'-eye(layers),'fro')<1e-12, ...
    'sixgr:research:NonOrthogonalArrayPorts','Configured DFT/polarization ports must be distinct and semi-unitary.');
end
