classdef SharedChannelLink
    %SHAREDCHANNELLINK Research DL/UL with independently scheduled reception.
    % Native PUSCH is used ONLY for modulation-independent RE/DMRS geometry.
    % No native QPSK bit budget/TBS/decoder is used for the research payload.
    % Standard NR PUSCH callers and their guards remain unchanged.
    methods (Static)
        function a = allocation(scfg,absoluteSlot,direction)
            [s,p,direction]=localConfig(scfg,direction);
            validateattributes(absoluteSlot,{'numeric'}, ...
                {'scalar','integer','nonnegative','finite'});
            frame=sixgr.phy.FrameStructureEngine(s,'FrameCoreOnly',true);
            if direction=="UL"
                allowed=frame.IsULAllocation(absoluteSlot,p.symbol_allocation);
            else
                allowed=frame.IsDLAllocation(absoluteSlot,p.symbol_allocation);
            end
            if frame.DuplexMode~="TDD" || ~allowed
                error(char("sixgr:research:"+direction+"SlotRequired"), ...
                    'Research %s transmission requires a configured %s allocation.',direction,direction);
            end
            carrier=nrCarrierConfig('NSizeGrid',frame.NRB, ...
                'SubcarrierSpacing',frame.SCSkHz, ...
                'CyclicPrefix',char(frame.CyclicPrefix),'NCellID',p.nid, ...
                'NSlot',mod(absoluteSlot,frame.SlotsPerFrame), ...
                'NFrame',mod(floor(absoluteSlot/frame.SlotsPerFrame),1024));
            % This object describes the RE/reference geometry, NOT the grant.
            args={'NumLayers',p.num_layers,'NSizeBWP',frame.NRB, ...
                'NStartBWP',0,'PRBSet',p.prb_start+(0:p.num_prbs-1), ...
                'SymbolAllocation',reshape(p.symbol_allocation,1,[]), ...
                'MappingType',char(p.mapping_type),'RNTI',p.rnti,'NID',p.nid, ...
                'EnablePTRS',false};
            if direction=="UL"
                geometry=nrPUSCHConfig(args{:},'Modulation','QPSK', ...
                    'TransformPrecoding',false,'TransmissionScheme','nonCodebook');
            else
                geometry=nrPDSCHConfig(args{:},'Modulation',char(p.modulation));
            end
            geometry.DMRS.DMRSConfigurationType=p.dmrs_configuration_type;
            geometry.DMRS.DMRSLength=p.dmrs_length;
            geometry.DMRS.DMRSTypeAPosition=p.dmrs_type_a_position;
            geometry.DMRS.DMRSAdditionalPosition=p.dmrs_additional_position;
            geometry.DMRS.NumCDMGroupsWithoutData=p.dmrs_cdm_groups_without_data;
            geometry.DMRS.DMRSPortSet=reshape(p.dmrs_port_set,1,[]);
            geometry.DMRS.NIDNSCID=p.dmrs_identity;
            geometry.DMRS.NSCID=p.dmrs_n_scid;
            if direction=="UL"
                [indices,geometryInfo]=nrPUSCHIndices(carrier,geometry);
                dmrsIndices=nrPUSCHDMRSIndices(carrier,geometry);
                dmrs=nrPUSCHDMRS(carrier,geometry);
                resourceSource="nrPUSCH_geometry_only_plus_explicit_research_Qm";
            else
                [indices,geometryInfo]=nrPDSCHIndices(carrier,geometry);
                dmrsIndices=nrPDSCHDMRSIndices(carrier,geometry);
                dmrs=nrPDSCHDMRS(carrier,geometry);
                resourceSource="nrPDSCH_configured_modulation_and_geometry";
            end
            qm=localQm(p.modulation);
            nRE=size(indices,1);
            assert(size(indices,2)==p.num_layers && nRE==geometryInfo.Gd, ...
                'sixgr:research:ResourceDimensions','Layer-domain geometry mismatch.');
            G=nRE*p.num_layers*qm;
            tbs=nrTBS(char(p.modulation),p.num_layers,p.num_prbs, ...
                geometryInfo.NREPerPRB,p.target_code_rate,0);
            layout=sixgr.phy.phycode.resolveCodingLayout('Direction',direction, ...
                'TransportBlockSize',tbs,'TargetCodeRate',p.target_code_rate, ...
                'RV',p.rv,'Modulation',p.modulation,'NumLayers',p.num_layers, ...
                'RateMatchedBitCount',G);
            a=struct('Direction',direction,'Carrier',carrier,'ReferenceGeometry',geometry, ...
                'DataIndices',indices,'DMRSIndices',dmrsIndices,'DMRSSymbols',dmrs, ...
                'Modulation',string(p.modulation),'Qm',qm,'NumLayers',p.num_layers, ...
                'LayerDataRE',nRE,'G',G,'TransportBlockSize',tbs, ...
                'TargetCodeRate',p.target_code_rate,'RV',p.rv,'CodingLayout',layout, ...
                'NREPerPRB',geometryInfo.NREPerPRB,'AbsoluteSlot',absoluteSlot, ...
                'FFTSize',frame.FFTSize,'SampleRateHz',frame.SampleRate_Hz, ...
                'WindowingSamples',s.waveform.windowing_samples, ...
                'Precoder',eye(p.num_layers)/sqrt(p.num_layers), ...
                'ResearchClass',"optional_research_experiment",'StandardNR',false, ...
                'ResourceSource',resourceSource, ...
                'CodingSource',"NR_LDPC_primitives_with_research_"+direction+"_allocation");
        end

        function tx = transmit(scfg,absoluteSlot,transportBlock,direction)
            a=sixgr.phy.research.SharedChannelLink.allocation(scfg,absoluteSlot,direction);
            validateattributes(transportBlock,{'numeric','logical'},{'vector','finite'});
            assert(all(transportBlock(:)==0 | transportBlock(:)==1), ...
                'sixgr:research:NonBinaryTB','Transport block must contain only binary bits.');
            assert(numel(transportBlock)==a.TransportBlockSize, ...
                'sixgr:research:TBSizeMismatch','TB size differs from scheduled research allocation.');
            tb=int8(transportBlock(:));
            layout=a.CodingLayout;
            crc=sixgr.phy.tb.attachCRC(tb,layout.TBCRCType);
            cbs=sixgr.phy.tb.segmentLDPC(crc,double(layout.BaseGraph));
            encoded=sixgr.phy.phycode.ldpcEncode(cbs,double(layout.BaseGraph));
            cw=sixgr.phy.phycode.rateMatchLDPC(encoded,a.G,a.RV, ...
                char(a.Modulation),a.NumLayers);
            assert(numel(cw)==a.G,'sixgr:research:CodedBudgetMismatch', ...
                'Actual coded payload must exactly fill the Qm-owned bit budget.');
            if a.Direction=="UL"
                scrambled=nrPUSCHScramble(cw,a.ReferenceGeometry.NID,a.ReferenceGeometry.RNTI);
                symbols=nrSymbolModulate(scrambled,char(a.Modulation));
                layers=sixgr.phy.ul.pusch.PUSCHLayerMapper.map(symbols,a.NumLayers);
            else
                layers=nrPDSCH(a.Carrier,a.ReferenceGeometry,cw);
            end
            layerGrid=nrResourceGrid(a.Carrier,a.NumLayers);
            layerGrid(a.DataIndices)=layers;
            layerGrid(a.DMRSIndices)=a.DMRSSymbols;
            grid=reshape(reshape(layerGrid,[],a.NumLayers)*a.Precoder,size(layerGrid));
            [waveform,ofdm]=sixgr.phy.waveform.ofdmModulate(a.Carrier,grid, ...
                'Nfft',a.FFTSize,'SampleRate',a.SampleRateHz,'Windowing',a.WindowingSamples);
            tx=struct('Allocation',a,'TransportBlock',tb,'Codeword',int8(cw), ...
                'LayerSymbols',layers,'Grid',grid,'Waveform',waveform,'OFDM',ofdm, ...
                'ExecutionBackend',"research_"+a.Direction+"_LDPC_1024_capable_waveform", ...
                'StandardNR',false,'UCIExecuted',false,'HARQExecuted',false);
        end

        function rx = receive(scfg,absoluteSlot,waveform,direction)
            % Receiver reconstructs scheduling and DMRS from installed config.
            % No transmitted bits, layout, grid, power or noise is an input.
            [~,p,direction]=localConfig(scfg,direction);
            a=sixgr.phy.research.SharedChannelLink.allocation(scfg,absoluteSlot,direction);
            assert(isnumeric(waveform) && ismatrix(waveform) && ...
                all(isfinite(waveform(:))) && size(waveform,2)>=a.NumLayers, ...
                'sixgr:research:InvalidReceiveWaveform','Finite received IQ with enough antenna columns is required.');
            grid=sixgr.phy.waveform.ofdmDemodulate(a.Carrier,waveform, ...
                'Nfft',a.FFTSize,'SampleRate',a.SampleRateHz);
            dmrsCfg=a.ReferenceGeometry.DMRS;
            [H,nvar,estInfo]=nrChannelEstimate(a.Carrier,grid,a.DMRSIndices, ...
                a.DMRSSymbols,'CDMLengths',dmrsCfg.CDMLengths);
            assert(isscalar(nvar) && isfinite(nvar) && nvar>0, ...
                'sixgr:research:InvalidMeasuredNoise', ...
                'DMRS noise estimate must be finite and positive; no fallback variance is permitted.');
            [observations,h]=nrExtractResources(a.DataIndices,grid,H);
            [equalized,csi]=nrEqualizeMMSE(observations,h,nvar);
            llrByLayer=zeros(a.Qm*a.LayerDataRE,a.NumLayers);
            for layer=1:a.NumLayers
                llrByLayer(:,layer)=nrSymbolDemodulate(equalized(:,layer), ...
                    char(a.Modulation),nvar).*repelem(csi(:,layer),a.Qm);
            end
            % Interleave Qm-bit symbol groups across layers, not individual bits.
            llr=reshape(permute(reshape(llrByLayer,a.Qm,a.LayerDataRE,a.NumLayers), ...
                [1 3 2]),[],1);
            if direction=="UL"
                signs=nrPUSCHPRBS(a.ReferenceGeometry.NID,a.ReferenceGeometry.RNTI, ...
                    a.G,'MappingType','signed');
            else
                signs=nrPDSCHPRBS(a.ReferenceGeometry.NID,a.ReferenceGeometry.RNTI, ...
                    0,a.G,'MappingType','signed');
            end
            llr=llr.*signs;
            layout=a.CodingLayout;
            recovered=sixgr.phy.phycode.rateRecoverLDPC(llr,a.TransportBlockSize, ...
                a.TargetCodeRate,a.RV,char(a.Modulation),a.NumLayers, ...
                double(layout.NumCodeBlocks),[],'CodingLayout',layout);
            [decoded,iterations,parity]=sixgr.phy.phycode.ldpcDecode(recovered, ...
                double(layout.BaseGraph),p.decoder_iterations,p.decoder_algorithm);
            [crc,cbError]=sixgr.phy.tb.desegmentLDPC(decoded, ...
                double(layout.BaseGraph),double(layout.TransportBlockLengthWithCRC));
            [tb,crcOK]=sixgr.phy.tb.checkCRC(crc,layout.TBCRCType);
            rx=struct('TransportBlock',int8(tb),'CRCPass',crcOK && ~any(cbError(:)), ...
                'CodeBlockCRCError',cbError,'Iterations',iterations,'Parity',parity, ...
                'CodewordLLR',llr,'EqualizedSymbols',equalized,'CSI',csi, ...
                'Grid',grid,'ChannelEstimate',H,'NoiseVariance',nvar, ...
                'ChannelEstimateInfo',estInfo,'Allocation',a, ...
                'TimingSource',"preconfigured_lab_slot_boundary", ...
                'NoiseSource',"received_DMRS_nrChannelEstimate", ...
                'ExecutionBackend',"research_"+direction+"_DMRS_MMSE_LDPC_receiver",'StandardNR',false);
        end
    end
end

function [s,p,direction]=localConfig(scfg,direction)
direction=upper(string(direction));
assert(isscalar(direction) && any(direction==["DL","UL"]), ...
    'sixgr:research:InvalidDirection','Research shared-channel direction must be DL or UL.');
section="research_"+lower(direction);
if isa(scfg,'sixgr.lls6g.config.ScenarioConfig'), s=scfg.toStruct(); else, s=scfg; end
assert(isstruct(s) && isscalar(s),'sixgr:research:InvalidConfig','A resolved scenario config is required.');
sixgr.lls6g.config.validateScenarioConfig(s,'AllowPartial',true);
assert(string(sixgr.util.structGet(s,'meta.research_class',''))=="optional_research_experiment" && ...
    logical(sixgr.util.structGet(s,section+".enabled",false)), ...
    'sixgr:research:ExplicitOptInRequired','Research shared channels require explicit opt-in and research classification.');
p=s.(section);
catalog=sixgr.lls6g.config.loadParameterCatalog('scenario');
fields=fieldnames(catalog.sections.(section).parameters);
assert(all(isfield(p,fields)),'sixgr:research:IncompleteULConfig', ...
    'All research shared-channel fields must be configured explicitly.');
assert(p.target_code_rate>0 && p.target_code_rate<1, ...
    'sixgr:research:InvalidCodeRate','Target code rate must be strictly between zero and one.');
assert(~p.transform_precoding && ~p.uci_enabled && ~p.harq_enabled, ...
    'sixgr:research:UnsupportedULProcedure', ...
    'This research UL adapter requires CP-OFDM and explicitly disabled UCI/HARQ.');
assert(numel(p.dmrs_port_set)==p.num_layers && ...
    numel(unique(p.dmrs_port_set))==p.num_layers, ...
    'sixgr:research:DMRSPortMismatch','One distinct DMRS port per layer is required.');
assert(p.prb_start+p.num_prbs<=s.frequency.n_size_grid, ...
    'sixgr:research:AllocationOutsideCarrier','Research UL PRBs exceed the carrier.');
assert(string(p.precoding)=="identity_unit_total_power", ...
    'sixgr:research:UnsupportedPrecoder','The selected research precoder is unsupported.');
end

function qm=localQm(modulation)
catalog=sixgr.lls6g.config.loadParameterCatalog('scenario');
rows=catalog.value_maps.modulation_order_to_name;
names=string({rows.name});
index=find(names==string(modulation));
assert(isscalar(index),'sixgr:research:UnsupportedModulation','Missing catalog modulation order.');
qm=double(rows(index).order);
end
