classdef SharedChannelLink
    %SHAREDCHANNELLINK Research DL/UL with independently scheduled reception.
    % Native PUSCH is used ONLY for modulation-independent RE/DMRS geometry.
    % No native QPSK bit budget/TBS/decoder is used for the research payload.
    % Standard NR PUSCH callers and their guards remain unchanged.
    methods (Static)
        function a = allocation(scfg,absoluteSlot,direction)
            [s,p,direction]=localConfig(scfg,direction);
            validateattributes(absoluteSlot,{'numeric'}, ...
                {'scalar','integer','nonnegative','finite'});
            frame=sixgr.phy.FrameStructureEngine(s,'FrameCoreOnly',true);
            if direction=="UL"
                allowed=frame.IsULAllocation(absoluteSlot,p.symbol_allocation);
            else
                allowed=frame.IsDLAllocation(absoluteSlot,p.symbol_allocation);
            end
            if frame.DuplexMode~="TDD" || ~allowed
                error(char("sixgr:research:"+direction+"SlotRequired"), ...
                    'Research %s transmission requires a configured %s allocation.',direction,direction);
            end
            carrier=nrCarrierConfig('NSizeGrid',frame.NRB, ...
                'SubcarrierSpacing',frame.SCSkHz, ...
                'CyclicPrefix',char(frame.CyclicPrefix),'NCellID',p.nid, ...
                'NSlot',mod(absoluteSlot,frame.SlotsPerFrame), ...
                'NFrame',mod(floor(absoluteSlot/frame.SlotsPerFrame),1024));
            % This object describes the RE/reference geometry, NOT the grant.
            args={'NumLayers',p.num_layers,'NSizeBWP',frame.NRB, ...
                'NStartBWP',0,'PRBSet',p.prb_start+(0:p.num_prbs-1), ...
                'SymbolAllocation',reshape(p.symbol_allocation,1,[]), ...
                'MappingType',char(p.mapping_type),'RNTI',p.rnti,'NID',p.nid, ...
                'EnablePTRS',false};
            if direction=="UL"
                geometry=nrPUSCHConfig(args{:},'Modulation','QPSK', ...
                    'TransformPrecoding',false,'TransmissionScheme','nonCodebook');
            else
                geometry=nrPDSCHConfig(args{:},'Modulation',char(p.modulation));
            end
            geometry.DMRS.DMRSConfigurationType=p.dmrs_configuration_type;
            geometry.DMRS.DMRSLength=p.dmrs_length;
            geometry.DMRS.DMRSTypeAPosition=p.dmrs_type_a_position;
            geometry.DMRS.DMRSAdditionalPosition=p.dmrs_additional_position;
            geometry.DMRS.NumCDMGroupsWithoutData=p.dmrs_cdm_groups_without_data;
            geometry.DMRS.DMRSPortSet=reshape(p.dmrs_port_set,1,[]);
            geometry.DMRS.NIDNSCID=p.dmrs_identity;
            geometry.DMRS.NSCID=p.dmrs_n_scid;
            if direction=="UL"
                [indices,geometryInfo]=nrPUSCHIndices(carrier,geometry);
                dmrsIndices=nrPUSCHDMRSIndices(carrier,geometry);
                dmrs=nrPUSCHDMRS(carrier,geometry);
                resourceSource="nrPUSCH_geometry_only_plus_explicit_research_Qm";
            else
                [indices,geometryInfo]=nrPDSCHIndices(carrier,geometry);
                dmrsIndices=nrPDSCHDMRSIndices(carrier,geometry);
                dmrs=nrPDSCHDMRS(carrier,geometry);
                resourceSource="nrPDSCH_configured_modulation_and_geometry";
            end
            qm=localQm(p.modulation);
            nRE=size(indices,1);
            assert(size(indices,2)==p.num_layers && nRE==geometryInfo.Gd, ...
                'sixgr:research:ResourceDimensions','Layer-domain geometry mismatch.');
            G=nRE*p.num_layers*qm;
            tbs=nrTBS(char(p.modulation),p.num_layers,p.num_prbs, ...
                geometryInfo.NREPerPRB,p.target_code_rate,0);
            layout=sixgr.phy.phycode.resolveCodingLayout('Direction',direction, ...
                'TransportBlockSize',tbs,'TargetCodeRate',p.target_code_rate, ...
                'RV',p.rv,'Modulation',p.modulation,'NumLayers',p.num_layers, ...
                'RateMatchedBitCount',G);
            receiver=localReceiverPolicy(s);
            physicalPorts=p.num_layers;
            if isfield(s,'research_awgn_mimo')
                localRequireIdentityAWGN(s);
                physicalPorts=s.research_awgn_mimo.physical_ports;
                assert(physicalPorts>=p.num_layers, ...
                    'sixgr:research:InsufficientPhysicalPorts', ...
                    'research_awgn_mimo.physical_ports must support the scheduled rank.');
            end
            assert(receiver.ldpc_base_graph~="BG1" || double(layout.BaseGraph)==1, ...
                'sixgr:research:BaseGraphMismatch', ...
                'research_receiver.ldpc_base_graph=BG1 conflicts with the derived TB/rate coding layout.');
            a=struct('Direction',direction,'Carrier',carrier,'ReferenceGeometry',geometry, ...
                'DataIndices',indices,'DMRSIndices',dmrsIndices,'DMRSSymbols',dmrs, ...
                'Modulation',string(p.modulation),'Qm',qm,'NumLayers',p.num_layers, ...
                'LayerDataRE',nRE,'G',G,'TransportBlockSize',tbs, ...
                'TargetCodeRate',p.target_code_rate,'RV',p.rv,'CodingLayout',layout, ...
                'NREPerPRB',geometryInfo.NREPerPRB,'AbsoluteSlot',absoluteSlot, ...
                'FFTSize',frame.FFTSize,'SampleRateHz',frame.SampleRate_Hz, ...
                'WindowingSamples',s.waveform.windowing_samples, ...
                'NumPhysicalPorts',physicalPorts, ...
                'Precoder',eye(p.num_layers,physicalPorts)/sqrt(p.num_layers), ...
                'ResearchClass',"optional_research_experiment",'StandardNR',false, ...
                'ResourceSource',resourceSource, ...
                'CodingSource',"NR_LDPC_primitives_with_research_"+direction+"_allocation");
        end

        function tx = transmit(scfg,absoluteSlot,transportBlock,direction,varargin)
            a=sixgr.phy.research.SharedChannelLink.allocation(scfg,absoluteSlot,direction);
            [~,p]=localConfig(scfg,direction);
            context=localHARQInputs(p,varargin{:});
            validateattributes(transportBlock,{'numeric','logical'},{'vector','finite'});
            assert(all(transportBlock(:)==0 | transportBlock(:)==1), ...
                'sixgr:research:NonBinaryTB','Transport block must contain only binary bits.');
            assert(numel(transportBlock)==a.TransportBlockSize, ...
                'sixgr:research:TBSizeMismatch','TB size differs from scheduled research allocation.');
            tb=int8(transportBlock(:));
            layout=a.CodingLayout;
            crc=sixgr.phy.tb.attachCRC(tb,layout.TBCRCType);
            cbs=sixgr.phy.tb.segmentLDPC(crc,double(layout.BaseGraph));
            encoded=sixgr.phy.phycode.ldpcEncode(cbs,double(layout.BaseGraph));
            cw=sixgr.phy.phycode.rateMatchLDPC(encoded,a.G,a.RV, ...
                char(a.Modulation),a.NumLayers);
            assert(numel(cw)==a.G,'sixgr:research:CodedBudgetMismatch', ...
                'Actual coded payload must exactly fill the Qm-owned bit budget.');
            if a.Direction=="UL"
                scrambled=nrPUSCHScramble(cw,a.ReferenceGeometry.NID,a.ReferenceGeometry.RNTI);
                symbols=nrSymbolModulate(scrambled,char(a.Modulation));
                layers=sixgr.phy.ul.pusch.PUSCHLayerMapper.map(symbols,a.NumLayers);
            else
                layers=nrPDSCH(a.Carrier,a.ReferenceGeometry,cw);
            end
            layerGrid=nrResourceGrid(a.Carrier,a.NumLayers);
            layerGrid(a.DataIndices)=layers;
            layerGrid(a.DMRSIndices)=a.DMRSSymbols;
            grid=reshape(reshape(layerGrid,[],a.NumLayers)*a.Precoder, ...
                size(layerGrid,1),size(layerGrid,2),a.NumPhysicalPorts);
            [waveform,ofdm]=sixgr.phy.waveform.ofdmModulate(a.Carrier,grid, ...
                'Nfft',a.FFTSize,'SampleRate',a.SampleRateHz,'Windowing',a.WindowingSamples);
            tx=struct('Allocation',a,'TransportBlock',tb,'Codeword',int8(cw), ...
                'LayerSymbols',layers,'Grid',grid,'Waveform',waveform,'OFDM',ofdm, ...
                'ExecutionBackend',"research_"+a.Direction+"_LDPC_1024_capable_waveform", ...
                'StandardNR',false,'UCIExecuted',false,'HARQExecuted',logical(p.harq_enabled), ...
                'HARQKey',context.HARQKey,'HARQExecutionScope',"coded_attempt_only_feedback_owned_by_runner");
        end

        function rx = receive(scfg,absoluteSlot,waveform,direction,varargin)
            % Receiver reconstructs scheduling and DMRS from installed config.
            % No transmitted bits, layout, grid, power or noise is an input.
            [s,p,direction]=localConfig(scfg,direction);
            context=localHARQInputs(p,varargin{:});
            a=sixgr.phy.research.SharedChannelLink.allocation(scfg,absoluteSlot,direction);
            receiver=localReceiverPolicy(s);
            perfect=receiver.channel_estimation=="perfect_identity_awgn";
            if perfect
                localRequireIdentityAWGN(s);
            end
            assert(isnumeric(waveform) && ismatrix(waveform) && ...
                all(isfinite(waveform(:))) && size(waveform,2)>=a.NumLayers, ...
                'sixgr:research:InvalidReceiveWaveform','Finite received IQ with enough antenna columns is required.');
            grid=sixgr.phy.waveform.ofdmDemodulate(a.Carrier,waveform, ...
                'Nfft',a.FFTSize,'SampleRate',a.SampleRateHz);
            dmrsCfg=a.ReferenceGeometry.DMRS;
            [H,nvar,estInfo]=nrChannelEstimate(a.Carrier,grid,a.DMRSIndices, ...
                a.DMRSSymbols,'CDMLengths',dmrsCfg.CDMLengths);
            channelSource="received_DMRS_nrChannelEstimate";
            if perfect
                assert(size(grid,3)==a.NumPhysicalPorts, ...
                    'sixgr:research:PerfectCSIAntennaMismatch', ...
                    'Perfect identity-AWGN CSI requires the configured physical receive branches.');
                % The identity channel and layer precoder are installed config,
                % not estimates taken from transmitted bits or symbols. H has
                % subcarrier x symbol x receive-antenna x layer dimensions.
                H=repmat(reshape(a.Precoder.',1,1,a.NumPhysicalPorts,a.NumLayers), ...
                    size(grid,1),size(grid,2),1,1);
                channelSource="perfect_configured_identity_AWGN_and_precoder";
            end
            assert(isscalar(nvar) && isfinite(nvar) && nvar>0, ...
                'sixgr:research:InvalidMeasuredNoise', ...
                'DMRS noise estimate must be finite and positive; no fallback variance is permitted.');
            [observations,h]=nrExtractResources(a.DataIndices,grid,H);
            [equalized,csi]=nrEqualizeMMSE(observations,h,nvar);
            llrByLayer=zeros(a.Qm*a.LayerDataRE,a.NumLayers);
            for layer=1:a.NumLayers
                llrByLayer(:,layer)=nrSymbolDemodulate(equalized(:,layer), ...
                    char(a.Modulation),nvar).*repelem(csi(:,layer),a.Qm);
            end
            % Interleave Qm-bit symbol groups across layers, not individual bits.
            llr=reshape(permute(reshape(llrByLayer,a.Qm,a.LayerDataRE,a.NumLayers), ...
                [1 3 2]),[],1);
            if direction=="UL"
                signs=nrPUSCHPRBS(a.ReferenceGeometry.NID,a.ReferenceGeometry.RNTI, ...
                    a.G,'MappingType','signed');
            else
                signs=nrPDSCHPRBS(a.ReferenceGeometry.NID,a.ReferenceGeometry.RNTI, ...
                    0,a.G,'MappingType','signed');
            end
            llr=llr.*signs;
            layout=a.CodingLayout;
            recovered=sixgr.phy.phycode.rateRecoverLDPC(llr,a.TransportBlockSize, ...
                a.TargetCodeRate,a.RV,char(a.Modulation),a.NumLayers, ...
                double(layout.NumCodeBlocks),[],'CodingLayout',layout);
            combining=struct('Applied',false,'SoftBuffer',struct());
            if p.harq_enabled
                [recovered,combining]=sixgr.phy.harq.combineSoftLLR(recovered, ...
                    context.HARQSoftBuffer,'CurrentLayout',layout, ...
                    'PriorLayout',context.PriorCodingLayout,'HARQKey',context.HARQKey);
                assert(~combining.ResetPrior && ...
                    any(combining.Reason==["no_prior_harq_soft_buffer","position_aware_harq_soft_buffer_accumulated"]), ...
                    'sixgr:research:IncompatibleHARQSoftBuffer', ...
                    'Research HARQ must not silently discard an incompatible receiver soft buffer: %s.',combining.Reason);
            end
            [decoded,iterations,parity]=sixgr.phy.phycode.ldpcDecode(recovered, ...
                double(layout.BaseGraph),p.decoder_iterations,p.decoder_algorithm);
            [crc,cbError]=sixgr.phy.tb.desegmentLDPC(decoded, ...
                double(layout.BaseGraph),double(layout.TransportBlockLengthWithCRC));
            [tb,crcOK]=sixgr.phy.tb.checkCRC(crc,layout.TBCRCType);
            backend="research_"+direction+"_DMRS_MMSE_LDPC_receiver";
            if perfect, backend="research_"+direction+"_perfect_identity_CSI_MMSE_LDPC_receiver"; end
            rx=struct('TransportBlock',int8(tb),'CRCPass',crcOK && ~any(cbError(:)), ...
                'CodeBlockCRCError',cbError,'Iterations',iterations,'Parity',parity, ...
                'CodewordLLR',llr,'EqualizedSymbols',equalized,'CSI',csi, ...
                'Grid',grid,'ChannelEstimate',H,'NoiseVariance',nvar, ...
                'ChannelEstimateInfo',estInfo,'Allocation',a, ...
                'ChannelEstimateSource',channelSource,'PerfectCSI',perfect, ...
                'HARQKey',context.HARQKey,'HARQSoftBuffer',combining.SoftBuffer, ...
                'HARQCombiningApplied',logical(combining.Applied), ...
                'TimingSource',"preconfigured_lab_slot_boundary", ...
                'NoiseSource',"received_DMRS_nrChannelEstimate", ...
                'ExecutionBackend',backend,'StandardNR',false);
        end
    end
end

function [s,p,direction]=localConfig(scfg,direction)
direction=upper(string(direction));
assert(isscalar(direction) && any(direction==["DL","UL"]), ...
    'sixgr:research:InvalidDirection','Research shared-channel direction must be DL or UL.');
section="research_"+lower(direction);
if isa(scfg,'sixgr.lls6g.config.ScenarioConfig'), s=scfg.toStruct(); else, s=scfg; end
assert(isstruct(s) && isscalar(s),'sixgr:research:InvalidConfig','A resolved scenario config is required.');
sixgr.lls6g.config.validateScenarioConfig(s,'AllowPartial',true);
assert(string(sixgr.util.structGet(s,'meta.research_class',''))=="optional_research_experiment" && ...
    logical(sixgr.util.structGet(s,section+".enabled",false)), ...
    'sixgr:research:ExplicitOptInRequired','Research shared channels require explicit opt-in and research classification.');
p=s.(section);
catalog=sixgr.lls6g.config.loadParameterCatalog('scenario');
fields=fieldnames(catalog.sections.(section).parameters);
assert(all(isfield(p,fields)),'sixgr:research:IncompleteULConfig', ...
    'All research shared-channel fields must be configured explicitly.');
assert(p.target_code_rate>0 && p.target_code_rate<1, ...
    'sixgr:research:InvalidCodeRate','Target code rate must be strictly between zero and one.');
assert(~p.transform_precoding && ~p.uci_enabled && ...
    (~p.harq_enabled || isfield(s,'research_harq')), ...
    'sixgr:research:UnsupportedULProcedure', ...
    'This research UL adapter requires CP-OFDM and explicitly disabled UCI/HARQ.');
if p.harq_enabled
    h=s.research_harq;
    assert(all(isfield(h,fieldnames(catalog.sections.research_harq.parameters))) && ...
        string(h.feedback_mode)=="ideal_delayed" && ~isempty(h.rv_sequence) && ...
        h.rv_sequence(1)==0 && h.feedback_drain_slots>=h.feedback_delay_slots, ...
        'sixgr:research:InvalidHARQPolicy', ...
        'Explicit ideal-delayed HARQ needs all policies, first RV zero and sufficient feedback-drain slots.');
end
assert(numel(p.dmrs_port_set)==p.num_layers && ...
    numel(unique(p.dmrs_port_set))==p.num_layers, ...
    'sixgr:research:DMRSPortMismatch','One distinct DMRS port per layer is required.');
assert(p.prb_start+p.num_prbs<=s.frequency.n_size_grid, ...
    'sixgr:research:AllocationOutsideCarrier','Research UL PRBs exceed the carrier.');
assert(string(p.precoding)=="identity_unit_total_power", ...
    'sixgr:research:UnsupportedPrecoder','The selected research precoder is unsupported.');
end

function context=localHARQInputs(p,varargin)
ip=inputParser;
ip.addParameter('HARQKey',"",@(x)ischar(x)||(isstring(x)&&isscalar(x)));
ip.addParameter('HARQSoftBuffer',[],@(x)isempty(x)||isstruct(x));
ip.addParameter('PriorCodingLayout',struct(),@isstruct);
ip.parse(varargin{:}); context=ip.Results; context.HARQKey=string(context.HARQKey);
hasKey=~ismissing(context.HARQKey) && strlength(context.HARQKey)>0;
assert(logical(p.harq_enabled)==hasKey,'sixgr:research:HARQContextRequired', ...
    'Enabled HARQ requires a receiver/scheduler-owned TB identity; disabled HARQ forbids a HARQ context.');
assert(p.harq_enabled || isempty(context.HARQSoftBuffer), ...
    'sixgr:research:UnexpectedHARQSoftBuffer','Disabled HARQ cannot consume a prior soft buffer.');
if ~isempty(context.HARQSoftBuffer)
    prior=context.HARQSoftBuffer;
    assert(isfield(prior,'HARQKey') && string(prior.HARQKey)==context.HARQKey && ...
        isfield(prior,'CodewordIndex') && prior.CodewordIndex==1, ...
        'sixgr:research:IncompatibleHARQSoftBuffer', ...
        'The prior receiver soft buffer must belong to this exact TB/process epoch and codeword.');
end
end

function receiver=localReceiverPolicy(s)
% Absent optional section preserves the existing DMRS/automatic-BG behavior.
receiver=struct('channel_estimation',"dmrs",'noise_estimation',"received_dmrs", ...
    'ldpc_base_graph',"auto");
if isfield(s,'research_receiver')
    assert(all(isfield(s.research_receiver,fieldnames(receiver))), ...
        'sixgr:research:IncompleteReceiverConfig','Every research_receiver field must be explicit.');
    receiver=s.research_receiver;
    names=fieldnames(receiver);
    for k=1:numel(names), receiver.(names{k})=string(receiver.(names{k})); end
end
end

function localRequireIdentityAWGN(s)
valid=string(sixgr.util.structGet(s,'research_link.channel',''))=="identity_awgn" && ...
    string(s.channels.model_type)=="AWGN" && string(s.channels.profile)=="AWGN" && ...
    ~s.channels.pathloss_enabled && ~s.channels.shadow_fading_enabled && ...
    s.channels.doppler_hz==0 && ...
    string(sixgr.util.structGet(s,'research_link.rf',''))=="ideal_no_impairments";
flags=["cfo_enabled","phase_noise_enabled","iq_imbalance_enabled", ...
    "pa_nonlinearity_enabled","timing_offset_enabled"];
for flag=flags, valid=valid && ~logical(sixgr.util.structGet(s,"impairments."+flag,true)); end
assert(valid,'sixgr:research:PerfectCSIRequiresIdentityAWGN', ...
    'perfect_identity_awgn requires explicit identity AWGN, no fading, no losses and ideal RF; it cannot replace a fading-channel estimate.');
end

function qm=localQm(modulation)
catalog=sixgr.lls6g.config.loadParameterCatalog('scenario');
rows=catalog.value_maps.modulation_order_to_name;
names=string({rows.name});
index=find(names==string(modulation));
assert(isscalar(index),'sixgr:research:UnsupportedModulation','Missing catalog modulation order.');
qm=double(rows(index).order);
end
