function occasion = mapPRACHToOccasion(cfg, varargin)
%MAPPRACHTOOCCASION Materialize one canonical PRACH occasion.
%
% OccasionIndex may extend across repetitions.  One exact least-common
% repetition interval is resolved by PRACHOccasionResolver; there is no
% arbitrary slot scan and no all-slot fallback.

p = inputParser;
p.FunctionName = "sixgr.rach.mapPRACHToOccasion";
addRequired(p, "cfg", @(x) isstruct(x) || isobject(x));
addParameter(p, "OccasionIndex", [], ...
    @(x) isempty(x) || (isnumeric(x) && isscalar(x) && isfinite(x) && ...
    x >= 1 && x == fix(x)));
addParameter(p, "NPRACHSlot", [], ...
    @(x) isempty(x) || (isnumeric(x) && isscalar(x) && isfinite(x) && ...
    x >= 0 && x == fix(x)));
addParameter(p, "Carrier", [], ...
    @(x) isempty(x) || isa(x, "nrCarrierConfig"));
addParameter(p, "PRACH", [], ...
    @(x) isempty(x) || isa(x, "nrPRACHConfig"));
parse(p, cfg, varargin{:});
opt = p.Results;

carrier = localCarrier(cfg, opt.Carrier);
prach = localPRACH(cfg, opt.PRACH);
frequencySubtype = localFrequencySubtype(cfg, prach);
msg1FDM = double(sixgr.util.structGet(cfg, "Msg1FDM", ...
    sixgr.util.structGet(cfg, "phy.prach.msg1FDM", 1)));
common = sixgr.util.structGet(cfg, "CommonDirection", ...
    sixgr.util.structGet(cfg, "phy.frame.CommonDirection", strings(0, 0)));
resolved = sixgr.util.structGet(cfg, "ResolvedDirection", ...
    sixgr.util.structGet(cfg, "phy.frame.ResolvedDirection", strings(0, 0)));

timing = sixgr.phy.frame.PRACHOccasionResolver.resolve( ...
    "FrequencyRange", frequencySubtype, ...
    "DuplexMode", string(prach.DuplexMode), ...
    "ConfigurationIndex", double(prach.ConfigurationIndex), ...
    "CarrierSubcarrierSpacingKHz", double(carrier.SubcarrierSpacing), ...
    "CarrierCyclicPrefix", string(carrier.CyclicPrefix), ...
    "NSizeGrid", double(carrier.NSizeGrid), ...
    "NStartGrid", double(carrier.NStartGrid), ...
    "NCellID", double(carrier.NCellID), ...
    "PRACHSubcarrierSpacingKHz", double(prach.SubcarrierSpacing), ...
    "SequenceIndex", double(prach.SequenceIndex), ...
    "PreambleIndex", double(prach.PreambleIndex), ...
    "RestrictedSet", string(prach.RestrictedSet), ...
    "ZeroCorrelationZone", double(prach.ZeroCorrelationZone), ...
    "Msg1FDM", msg1FDM, ...
    "Msg1FrequencyStart", double(prach.FrequencyStart), ...
    "RBOffset", double(prach.RBOffset), ...
    "RBSetOffset", double(prach.RBSetOffset), ...
    "CommonDirection", common, ...
    "ResolvedDirection", resolved);

rows = timing.Occasions;
perPeriod = height(rows);
if perPeriod < 1
    error("sixgr:rach:mapPRACHToOccasion:NoSuchOccasion", ...
        "The canonical PRACH repetition contains no usable occasion.");
end
periodCarrierSlots = double(timing.PeriodCarrierSlots);
if periodCarrierSlots ~= fix(periodCarrierSlots)
    error("sixgr:phy:frame:PRACHCarrierPeriodMisaligned", ...
        "PRACH repetition period %.15g does not align to carrier slots.", ...
        periodCarrierSlots);
end
periodPRACHSlots = double(timing.PeriodPRACHSlots);
if ~(isfinite(periodPRACHSlots) && periodPRACHSlots >= 1 && ...
        periodPRACHSlots == fix(periodPRACHSlots))
    error("sixgr:phy:frame:PRACHPeriodMisaligned", ...
        "PRACH repetition period %.15g does not align to PRACH slots.", ...
        periodPRACHSlots);
end

if isempty(opt.NPRACHSlot)
    if isempty(opt.OccasionIndex)
        target = 1;
    else
        target = double(opt.OccasionIndex);
    end
    periodIndex = floor((target - 1) / perPeriod);
    rowIndex = mod(target - 1, perPeriod) + 1;
else
    if ~isempty(opt.OccasionIndex)
        error("sixgr:rach:mapPRACHToOccasion:ConflictingSelection", ...
            "Select a PRACH occasion by OccasionIndex or NPRACHSlot, not both.");
    end
    requestedPRACHSlot = double(opt.NPRACHSlot);
    periodIndex = floor(requestedPRACHSlot / periodPRACHSlots);
    slotWithinPeriod = mod(requestedPRACHSlot, periodPRACHSlots);
    candidates = find(double(rows.PRACHSlot) == slotWithinPeriod);
    if isempty(candidates)
        error("sixgr:rach:mapPRACHToOccasion:RequestedSlotInactive", ...
            "Requested NPRACHSlot=%d is not active for configuration index %d.", ...
            requestedPRACHSlot, double(prach.ConfigurationIndex));
    end

    % NPRACHSlot alone identifies the PRACH-time slot.  If that slot has
    % multiple time/frequency occasions, the explicit PRACH object fields
    % select the exact canonical row; they are never silently rewritten.
    requestedTimeIndex = double(prach.TimeIndex);
    requestedFrequencyIndex = double(prach.FrequencyIndex);
    requestedActiveSlot = double(prach.ActivePRACHSlot);
    exact = candidates( ...
        double(rows.TimeIndex(candidates)) == requestedTimeIndex & ...
        double(rows.FrequencyIndex(candidates)) == requestedFrequencyIndex & ...
        double(rows.ActivePRACHSlot(candidates)) == requestedActiveSlot);
    if isempty(exact)
        error("sixgr:rach:mapPRACHToOccasion:RequestedOccasionInactive", ...
            "NPRACHSlot=%d does not contain canonical time=%d, frequency=%d, " + ...
            "active-slot=%d for configuration index %d.", ...
            requestedPRACHSlot, requestedTimeIndex, ...
            requestedFrequencyIndex, requestedActiveSlot, ...
            double(prach.ConfigurationIndex));
    end
    rowIndex = exact(1);
    target = periodIndex * perPeriod + rowIndex;
end

row = rows(rowIndex, :);
absoluteSlot = double(row.AbsoluteSlot) + ...
    periodIndex * periodCarrierSlots;
prachSlot = double(row.PRACHSlot) + ...
    periodIndex * periodPRACHSlots;
numerology = sixgr.phy.frame.NumerologyCatalog.resolve( ...
    double(carrier.SubcarrierSpacing), string(carrier.CyclicPrefix), ...
    "generic_waveform_test", "");
slotsPerFrame = double(numerology.SlotsPerFrame);

carrier.NFrame = floor(absoluteSlot / slotsPerFrame);
carrier.NSlot = mod(absoluteSlot, slotsPerFrame);
prach.NPRACHSlot = prachSlot;
prach.ActivePRACHSlot = double(row.ActivePRACHSlot);
prach.TimeIndex = double(row.TimeIndex);
prach.FrequencyIndex = double(row.FrequencyIndex);

try
    symbols = nrPRACH(carrier, prach);
    indices = nrPRACHIndices(carrier, prach);
catch cause
    failure = MException("sixgr:rach:mapPRACHToOccasion:MaterializationFailed", ...
        "Canonical PRACH occasion %d failed Toolbox materialization " + ...
        "(configuration=%d, PRACH slot=%d): %s", ...
        target, double(prach.ConfigurationIndex), prachSlot, cause.message);
    failure = addCause(failure, cause);
    throwAsCaller(failure);
end
if isempty(symbols) || isempty(indices)
    error("sixgr:rach:mapPRACHToOccasion:CanonicalOccasionInactive", ...
        "Canonical resolver selected occasion %d, but nrPRACH and " + ...
        "nrPRACHIndices returned no active resources.", target);
end

occasion = struct( ...
    "Ordinal", target, ...
    "PeriodIndex", periodIndex, ...
    "SlotIndex0", absoluteSlot, ...
    "SlotIndex1", absoluteSlot + 1, ...
    "PRACHSlotIndex0", prachSlot, ...
    "TimeIndex", double(row.TimeIndex), ...
    "ActivePRACHSlot", double(row.ActivePRACHSlot), ...
    "FrequencyIndex", double(row.FrequencyIndex), ...
    "FrequencyStart", double(prach.FrequencyStart), ...
    "SymbolLocation", double(row.ToolboxSymbolLocation), ...
    "PRACHDuration", double(row.ToolboxPRACHDuration), ...
    "CarrierStartSymbol", double(row.StartSymbol), ...
    "CarrierDurationSymbols", double(row.DurationSymbols), ...
    "NumTimeOccasions", double(prach.NumTimeOccasions), ...
    "Carrier", localCarrierSnapshot(carrier), ...
    "PRACH", localPRACHSnapshot(prach), ...
    "TimingResolution", timing, ...
    "Indices", indices, ...
    "Symbols", symbols);
end

function carrier = localCarrier(cfg, override)
if ~isempty(override)
    carrier = override;
    return;
end
if isstruct(cfg) && isfield(cfg, "ToolboxCarrier") && ...
        isa(cfg.ToolboxCarrier, "nrCarrierConfig")
    carrier = cfg.ToolboxCarrier;
    return;
end
carrier = nrCarrierConfig;
carrier.SubcarrierSpacing = double(sixgr.util.structGet(cfg, ...
    "CarrierSCSkHz", ...
    sixgr.util.structGet(cfg, "phy.carrier.SubcarrierSpacing_kHz", ...
    sixgr.util.structGet(cfg, "phy.carrier.SubcarrierSpacing", NaN))));
carrier.NSizeGrid = double(sixgr.util.structGet(cfg, ...
    "NSizeGrid", sixgr.util.structGet(cfg, "phy.carrier.NSizeGrid", NaN)));
carrier.NStartGrid = double(sixgr.util.structGet(cfg, ...
    "NStartGrid", sixgr.util.structGet(cfg, "phy.carrier.NStartGrid", 0)));
carrier.NCellID = double(sixgr.util.structGet(cfg, ...
    "NCellID", sixgr.util.structGet(cfg, "phy.carrier.NCellID", 0)));
carrier.CyclicPrefix = char(string(sixgr.util.structGet(cfg, ...
    "CyclicPrefix", ...
    sixgr.util.structGet(cfg, "phy.carrier.CyclicPrefix", "normal"))));
end

function prach = localPRACH(cfg, override)
if ~isempty(override)
    prach = override;
    return;
end
if isstruct(cfg) && isfield(cfg, "ToolboxPRACH") && ...
        isa(cfg.ToolboxPRACH, "nrPRACHConfig")
    prach = cfg.ToolboxPRACH;
    return;
end
prach = nrPRACHConfig;
range = upper(string(sixgr.util.structGet(cfg, ...
    "FrequencyRange", ...
    sixgr.util.structGet(cfg, "phy.prach.frequencyRange", "FR1"))));
if startsWith(range, "FR2")
    range = "FR2";
end
prach.FrequencyRange = char(range);
prach.DuplexMode = char(sixgr.phy.frame.resolveDuplexMode(cfg));
prach.ConfigurationIndex = double(sixgr.util.structGet(cfg, ...
    "PRACHConfigurationIndex", ...
    sixgr.util.structGet(cfg, "phy.prach.configurationIndex", NaN)));
prach.SubcarrierSpacing = double(sixgr.util.structGet(cfg, ...
    "PRACHSubcarrierSpacing", ...
    sixgr.util.structGet(cfg, "phy.prach.subcarrierSpacing_kHz", NaN)));
prach.SequenceIndex = double(sixgr.util.structGet(cfg, ...
    "SequenceIndex", sixgr.util.structGet(cfg, "phy.prach.rootSeqIndex", 0)));
prach.PreambleIndex = double(localFirstPreamble(sixgr.util.structGet(cfg, ...
    "PreambleIndex", sixgr.util.structGet(cfg, "phy.prach.preambleIndex", 0))));
prach.RestrictedSet = char(string(sixgr.util.structGet(cfg, ...
    "RestrictedSet", ...
    sixgr.util.structGet(cfg, "phy.prach.restrictedSet", "UnrestrictedSet"))));
prach.ZeroCorrelationZone = double(sixgr.util.structGet(cfg, ...
    "ZeroCorrelationZone", ...
    sixgr.util.structGet(cfg, "phy.prach.zeroCorrelationZone", 0)));
prach.FrequencyStart = double(sixgr.util.structGet(cfg, ...
    "FrequencyStart", sixgr.util.structGet(cfg, ...
    "phy.prach.frequencyStart", 0)));
end

function subtype = localFrequencySubtype(cfg, prach)
configured = upper(string(sixgr.util.structGet(cfg, ...
    "FrequencyRangeSubtype", ...
    sixgr.util.structGet(cfg, "phy.frequencyRange", ...
    sixgr.util.structGet(cfg, "frequency.range_name", "")))));
if strlength(configured) > 0 && configured ~= "FR2"
    subtype = configured;
    return;
end
if string(prach.FrequencyRange) == "FR1"
    subtype = "FR1";
    return;
end
fcHz = double(sixgr.util.structGet(cfg, ...
    "CarrierFrequencyHz", ...
    sixgr.util.structGet(cfg, "channel.fc_Hz", ...
    sixgr.util.structGet(cfg, "frequency.center_frequency_hz", 28e9))));
range = sixgr.phy.frame.FrequencyRangeResolver.resolve( ...
    "CenterFrequencyHz", fcHz);
subtype = string(range.FrequencyRange);
end

function value = localFirstPreamble(spec)
values = double(spec(:));
values = values(isfinite(values));
if isempty(values)
    value = 0;
else
    value = values(1);
end
end

function value = localCarrierSnapshot(carrier)
value = struct( ...
    "SubcarrierSpacing", double(carrier.SubcarrierSpacing), ...
    "NSizeGrid", double(carrier.NSizeGrid), ...
    "NStartGrid", double(carrier.NStartGrid), ...
    "NCellID", double(carrier.NCellID), ...
    "NFrame", double(carrier.NFrame), ...
    "NSlot", double(carrier.NSlot), ...
    "CyclicPrefix", char(string(carrier.CyclicPrefix)));
end

function value = localPRACHSnapshot(prach)
value = struct( ...
    "FrequencyRange", char(string(prach.FrequencyRange)), ...
    "DuplexMode", char(string(prach.DuplexMode)), ...
    "ConfigurationIndex", double(prach.ConfigurationIndex), ...
    "SubcarrierSpacing", double(prach.SubcarrierSpacing), ...
    "SequenceIndex", double(prach.SequenceIndex), ...
    "PreambleIndex", double(prach.PreambleIndex), ...
    "RestrictedSet", char(string(prach.RestrictedSet)), ...
    "ZeroCorrelationZone", double(prach.ZeroCorrelationZone), ...
    "FrequencyStart", double(prach.FrequencyStart), ...
    "FrequencyIndex", double(prach.FrequencyIndex), ...
    "ActivePRACHSlot", double(prach.ActivePRACHSlot), ...
    "NPRACHSlot", double(prach.NPRACHSlot), ...
    "TimeIndex", double(prach.TimeIndex), ...
    "Format", char(string(prach.Format)), ...
    "LRA", double(prach.LRA), ...
    "SymbolLocation", double(prach.SymbolLocation), ...
    "PRACHDuration", double(prach.PRACHDuration), ...
    "NumTimeOccasions", double(prach.NumTimeOccasions));
end
