function rows = bindIndependentCSIRSClock(rows, prepared, observation, availableAtSample, epoch)
%BINDINDEPENDENTCSIRSCLOCK Bind actual shared receiver completion timing.
arguments
    rows table
    prepared (1,1) struct
    observation (1,1) sixgr.phy.waveform.WaveformObservationBuffer
    availableAtSample (1,1) double {mustBeInteger,mustBeNonnegative}
    epoch (1,1) double {mustBeInteger,mustBeNonnegative}
end
if isempty(rows), return; end
assert(string(sixgr.util.structGet(prepared,"ExecutionStage","")) == ...
    "csirs_waveform_prepared_not_received" && ...
    observation.isComplete() && ...
    observation.SampleRateHz == prepared.SampleRateHz, ...
    'sixgr:truth:InvalidIndependentCSIRSClockOwner', ...
    'Independent CSI-RS clock binding requires its completed shared observation.');
sourceSlot = double(prepared.RuntimeSlot);
assert(all(rows.Slot == sourceSlot) && ...
    observation.EndSampleExclusive <= availableAtSample, ...
    'sixgr:truth:IndependentCSIRSClockMismatch', ...
    'CSI-RS rows and completed observation must share one source occasion.');
carrier = prepared.Carrier;
slot0 = sourceSlot - 1;
deliveryStart = sixgr.phy.frame.slotStartSample( ...
    carrier,slot0,prepared.SampleRateHz);
deliveryStop = sixgr.phy.frame.slotStartSample( ...
    carrier,slot0+1,prepared.SampleRateHz);
while availableAtSample >= deliveryStop
    slot0 = slot0 + 1;
    deliveryStart = deliveryStop;
    deliveryStop = sixgr.phy.frame.slotStartSample( ...
        carrier,slot0+1,prepared.SampleRateHz);
end
values = struct( ...
    "ObservationStartSample",double(observation.StartSample), ...
    "ObservationEndSampleExclusive",double(observation.EndSampleExclusive), ...
    "ObservationSampleRateHz",double(observation.SampleRateHz), ...
    "ResultAvailableAtSample",double(availableAtSample), ...
    "MeasurementClockEpoch",double(epoch), ...
    "ObservationDeliverySlot",double(slot0+1), ...
    "DeliverySlotStartSample",double(deliveryStart), ...
    "DeliverySlotEndSampleExclusive",double(deliveryStop), ...
    "MeasurementClockDomain","shared_receiver_sample_clock/v1", ...
    "RuntimeTransportMode", ...
        "shared_physical_stream_independent_CSIRS_received_completion");
for name = string(fieldnames(values)).'
    bound = repmat(values.(name),height(rows),1);
    if ismember(name,string(rows.Properties.VariableNames))
        existing = rows.(name);
        blank = localBlank(existing);
        if any(~blank)
            assert(isequaln(existing,bound), ...
                'sixgr:truth:ConflictingIndependentCSIRSClock', ...
                'Existing CSI-RS receiver clock cannot be rebound.');
        else
            rows.(name) = bound;
        end
    else
        rows.(name) = bound;
    end
end
for index = 1:height(rows)
    sixgr.truth.csirsMeasurementAvailability(rows(index,:),true);
end
end

function blank = localBlank(value)
if isnumeric(value)
    blank = isnan(value);
elseif isstring(value)
    blank = ismissing(value) | strlength(strtrim(value)) == 0;
else
    blank = false(size(value));
end
end
