function mapping=bindScheduledPUSCHHARQMapping(base,cfg,grant)
% Bind actual-DL gNB identities to the gNB's scheduled UL total DAI.
% Caller obtains base from buildScheduledHARQACKMapping and must separately
% bind the UL scheduling/capture authority. This pure binding is not PHY proof.
probe=struct('MappingDigest',base.Digest,'UEIndex',base.UEIndex,'RNTI',base.RNTI, ...
    'TargetSlot',base.TargetSlot,'DecodedBits',int8([]),'DecodeOk',false, ...
    'DTXFlag',true,'Transport',"PUSCH");
sixgr.truth.mapScheduledHARQFeedback(base,probe); % Validate base hash/identities without state mutation.
assert(base.Source=="physically_transmitted_dl_schedule_not_ue_feedback_state" && ...
    ~isfield(base,'Transport') && isfield(grant,'ULTotalDAIAuthority') && ...
    isfield(grant,'TimingDecision') && isstruct(grant.TimingDecision) && ...
    isscalar(grant.TimingDecision) && isequal(grant.TimingDecision.Valid,true), ...
    'sixgr:truth:MissingScheduledPUSCHHARQAuthority', ...
    'Retain the independent actual-DL mapping and scheduled UL DAI authority.');
sixgr.phy.grant.assertGrantTimingIdentity(grant,'UL');
policy=sixgr.util.structGet(cfg,'phy.pdcch.operatorControl.connected_dci',struct());
assert(isstruct(policy) && isscalar(policy) && ~isempty(fieldnames(policy)), ...
    'sixgr:truth:MissingScheduledPUSCHHARQAuthority', ...
    'Scheduled UL DAI binding requires the installed connected-DCI policy.');
sixgr.phy.pdcch.ConnectedDCIProfile.validatePolicy(policy);
t=grant.TimingDecision;
assert(upper(string(grant.Direction))=="UL" && grant.UEIndex==base.UEIndex && ...
    grant.RNTI==base.RNTI && t.DataAbsoluteSlot+1==base.TargetSlot && ...
    grant.ServingCell==base.LastGrant.ServingCell, ...
    'sixgr:truth:ScheduledPUSCHHARQContextMismatch', ...
    'PUSCH and DL feedback must share the UE, RNTI, cell and feedback occasion.');
a=grant.ULTotalDAIAuthority;
assert(isstruct(a) && isscalar(a) && all(isfield(a, ...
    {'Digest','ScheduledDLAssignments','ControlAbsoluteSlot','ConfigurationEpoch'})) && ...
    a.Digest==sixgr.phy.pucch.PUCCHUtil.hash(rmfield(a,'Digest')) && ...
    a.ConfigurationEpoch==base.ConfigurationEpoch, ...
    'sixgr:truth:ChangedScheduledPUSCHHARQAuthority','Retain the exact scheduled UL DAI authority.');
% Re-derive the scheduled bits from the retained accepted DL assignments.
% This does not repack a live grant or infer DAI from UE reception counts.
ledger=struct('Version',1,'LastControlAbsoluteSlot',a.ControlAbsoluteSlot, ...
    'Entries',a.ScheduledDLAssignments);
rebuilt=sixgr.truth.prepareScheduledULDAI(ledger,cfg,grant);
assert(isequaln(rebuilt.ULTotalDAIAuthority,a) && ...
    isequal(rebuilt.DCI.Bits,grant.DCI.Bits), ...
    'sixgr:truth:ChangedScheduledPUSCHHARQAuthority', ...
    'The transmitted UL DCI and retained scheduling authority must agree.');
packed=sixgr.phy.pdcch.decodeDCIPayload(grant.DCI.Bits,'0_1',grant.DCI.ContextData);
records=base.Records;
assert(all(isfield(records,{'ControlAbsoluteSlot','ControlStartSymbol','CounterDAIRaw'})) && ...
    isequal([records.CounterDAIRaw],mod(0:base.BitCount-1,4)), ...
    'sixgr:truth:ScheduledPUSCHHARQAssignmentMismatch', ...
    'The full gNB DL schedule must retain its chronological two-bit counters.');
ids=string({records.PHYGrantContextId});
bound=false(1,numel(records));
for entry=reshape(a.ScheduledDLAssignments,1,[])
    d=entry.Assignment;
    hit=find(ids==d.GrantID);
    assert(isscalar(hit),'sixgr:truth:UnexecutedPUSCHHARQAssignment', ...
        'Each DL assignment counted in this UL DAI needs its exact actual-DL identity.');
    r=records(hit);
    assert(~bound(hit) && r.ControlAbsoluteSlot==d.ControlAbsoluteSlot && ...
        r.ControlStartSymbol==d.ControlStartSymbol && r.TargetSlot==d.FeedbackAbsoluteSlot+1 && ...
        r.RNTI==d.RNTI && r.ConfigurationEpoch==d.ConfigurationEpoch && ...
        r.CounterDAIRaw==entry.RawDAI && r.BitIndex==entry.Ordinal, ...
        'sixgr:truth:ScheduledPUSCHHARQAssignmentMismatch', ...
        'An accepted DAI assignment cannot be rebound to a different physical DL obligation.');
    bound(hit)=true;
end
% A later DL control occasion may follow UL DCI preparation. Do not silently
% recompute an already transmitted UL DAI from that later scheduling state.
earlier=[records.ControlAbsoluteSlot]<t.ControlAbsoluteSlot | ...
    ([records.ControlAbsoluteSlot]==t.ControlAbsoluteSlot & ...
     [records.ControlStartSymbol]<t.ControlSymbolAllocation(1));
assert(all(bound(earlier)),'sixgr:truth:MissingEarlierScheduledPUSCHHARQAssignment', ...
    'The retained UL DAI snapshot cannot omit an already earlier physical DL assignment.');
n=base.BitCount;
lastCounter=mod(n-1,4)+1;
total=double(packed.Fields.first_dai)+1;
width=4*floor((n-1)/4)+total+4*double(total<lastCounter);
assert(width>=n && width<=n+3,'sixgr:truth:InvalidScheduledPUSCHHARQWidth', ...
    'Ordinary scalar-TB UL total DAI may add only the final modulo-four positions.');
mapping=struct('BaseMapping',base,'BaseMappingDigest',base.Digest, ...
    'UEIndex',base.UEIndex,'RNTI',base.RNTI,'TargetSlot',base.TargetSlot, ...
    'ConfigurationEpoch',base.ConfigurationEpoch,'BitCount',width, ...
    'PhysicalAssignmentCount',n,'ProtocolPaddingBitIndices',(n+1:width).', ...
    'ULGrantContextID',string(grant.PHYGrant.GrantContextId), ...
    'ULScheduledPayloadHash',string(packed.PayloadHash), ...
    'ULTotalDAIRaw',double(packed.Fields.first_dai), ...
    'ULTotalDAIAuthorityDigest',a.Digest, ...
    'Source',"gnb_actual_dl_mapping_and_scheduled_ul_total_dai");
mapping.Digest=sixgr.phy.pucch.PUCCHUtil.hash(rmfield(mapping,'BaseMapping'));
end
