function trials=bindConfiguredCSITrialDisposition(trials,report)
% Bind completed CSI-only publication to its actual independent PUCCH trial.
% This changes disposition metadata only, never receiver bits or TX scoring.
assert(isstruct(report) && isscalar(report) && ...
    (islogical(report.Processed)||isnumeric(report.Processed)) && ...
    isreal(report.Processed) && isscalar(report.Processed) && ...
    isfinite(report.Processed) && report.Processed==1 && ...
    string(report.CSIUCIChannel)=="PUCCH", ...
    'sixgr:truth:CSITrialDispositionNotCompleted', ...
    'Bind only the completed independently received PUCCH CSI publication.');
required=["Slot","UEIndex","RNTI","ReceiverContextDigest","ReceiverExpectedHARQBitCount"];
assert(istable(trials) && all(ismember(required,string(trials.Properties.VariableNames))), ...
    'sixgr:truth:CSITrialDispositionIdentity','Retain the actual independent receiver trial.');
identity=[report.DueSlot report.UEIndex report.RNTI report.ServingCell];
digest=string(report.ReceiverContextDigest);
assert(isnumeric(identity) && isreal(identity) && all(isfinite(identity)) && ...
    all(identity>=1 & identity==fix(identity)) && isscalar(digest) && ...
    ~ismissing(digest) && strlength(strtrim(digest))>0, ...
    'sixgr:truth:CSITrialDispositionIdentity','Use the completed report identity, not decoded values.');
cellID=NaN(height(trials),1); base=cellID;
if ismember('ServingCell',trials.Properties.VariableNames), cellID=double(trials.ServingCell); end
if ismember('BaseStationID',trials.Properties.VariableNames), base=double(trials.BaseStationID); end
conflict=isfinite(cellID) & isfinite(base) & cellID~=base;
missing=~isfinite(cellID); cellID(missing)=base(missing);
hit=find(trials.Slot==report.DueSlot & trials.UEIndex==report.UEIndex & ...
    trials.RNTI==report.RNTI & cellID==report.ServingCell & ~conflict & ...
    string(trials.ReceiverContextDigest)==digest);
assert(isscalar(hit),'sixgr:truth:CSITrialDispositionIdentity', ...
    'Exactly one independent receiver context/UE/cell/occasion must own this report.');
assert(trials.ReceiverExpectedHARQBitCount(hit)==0, ...
    'sixgr:truth:CSITrialDispositionRequiresCSIOnly', ...
    'Combined HARQ occasions retain their separate actual HARQ disposition reducer.');
delivered=string(report.DeliveryStatus)=="delivered_to_runtime_scheduler";
assert((islogical(report.CSIUCIDecodeOk)||isnumeric(report.CSIUCIDecodeOk)) && ...
    isreal(report.CSIUCIDecodeOk) && isscalar(report.CSIUCIDecodeOk) && ...
    isfinite(report.CSIUCIDecodeOk) && any(report.CSIUCIDecodeOk==[0 1]) && ...
    (~delivered || report.CSIUCIDecodeOk), ...
    'sixgr:truth:CSITrialDispositionInvalidDelivery', ...
    'A delivered report requires a successful independent CSI decode.');
% Processed/rejected evidence is distinct from an applied scheduling change.
% Replace legacy decode-only flags: a stale decoded CSI report was not applied.
for name=["RuntimeStateUpdated","ControlStateChanged","StateChangeApplied"]
    if ~ismember(name,string(trials.Properties.VariableNames))
        trials.(name)=false(height(trials),1);
    end
    trials.(name)(hit)=delivered;
end
trials.RuntimeStateUpdated(hit)=true;
if ~ismember('CSIReportStateChangeApplied',trials.Properties.VariableNames)
    trials.CSIReportStateChangeApplied=NaN(height(trials),1);
end
trials.CSIReportStateChangeApplied(hit)=double(delivered);
end
