function res=bindSharedDLCSICompletion(res,prepared,observation,owner)
% Bind actual receiver CSI before the coordinator commits any DL result.
% Empty CSI tables stay empty. This is chronology/provenance, not RF repair.
assert(isstruct(res) && isscalar(res), ...
    'sixgr:truth:CSICompletionResultRequired','Retain one actual completed DL result.');
if ~isfield(res,'CSIRSTrialTable'), return; end
assert(istable(res.CSIRSTrialTable),'sixgr:truth:CSIRSClockTableRequired', ...
    'CSI result evidence must be a table, including when it is empty.');
if isempty(res.CSIRSTrialTable), return; end
assert(isa(owner,'sixgr.truth.CoupledWaveformStream') && isscalar(owner) && ...
    isa(prepared,'sixgr.link.PreparedDataTransmission') && isscalar(prepared) && ...
    prepared.Direction=="DL" && ...
    isa(observation,'sixgr.phy.waveform.WaveformObservationBuffer') && isscalar(observation), ...
    'sixgr:truth:CSICompletionOwnerRequired', ...
    'Shared CSI must use its actual DL prepared transmission, receive capture and physical owner.');
assert(isfield(res,'ExecutionStage') && string(res.ExecutionStage)=="received_shared_stream_completed" && ...
    isfield(res,'ReceiveTiming'), ...
    'sixgr:truth:CSICompletionNotReceived','A prepared or standalone result cannot claim shared CSI completion.');
available=owner.Events.NextSampleIndex;
assert(~owner.Events.Faulted && ~owner.Physical.Faulted && ...
    owner.Physical.NextSampleIndex==available && ...
    observation.SampleRateHz==owner.SampleRateHz && prepared.SampleRateHz==owner.SampleRateHz && ...
    observation.EndSampleExclusive<=available, ...
    'sixgr:truth:CSICompletionClockMismatch', ...
    'CSI publication must follow the actual complete capture on one nonfaulted physical/event clock.');
bound=sixgr.truth.bindReceivedCSIRSClock(res.CSIRSTrialTable,prepared,observation, ...
    res.ReceiveTiming,available,owner.Physical.ConfigurationEpoch);
for row=1:height(bound)
    sixgr.truth.csirsMeasurementAvailability(bound(row,:),true);
end
res.CSIRSTrialTable=bound;
end
