function constraints=buildHARQPUSCHTimingConstraints(cfg,dlGrant,ulGrants)
% Before-DCI scheduling evidence, never UE receive/ACK/payload authority.
% Ordinary cap1, fixed active carrier/BWP, periodic/no CSI scope. Preserve
% exact allocation/processing provenance so a later K1 candidate cannot use
% a different PDSCH endpoint or invent an early feedback-ready time.
constraints=struct([]);
sixgr.phy.grant.assertGrantTimingIdentity(dlGrant,'DL');
if isempty(ulGrants) || ~dlGrant.TimingDecision.HARQACKRequired, return; end
if ~iscell(ulGrants), ulGrants=num2cell(ulGrants); end
dt=dlGrant.TimingDecision;
for k=1:numel(ulGrants)
    g=ulGrants{k};
    if g.UEIndex~=dlGrant.UEIndex || g.ServingCell~=dlGrant.ServingCell, continue; end
    sixgr.phy.grant.assertGrantTimingIdentity(g,'UL');
    ut=g.TimingDecision;
    if ut.DataDecision.TargetEndTick<=dt.DataDecision.TargetEndTick, continue; end
    switching=sixgr.util.structGet(cfg,'lls6g.resolvedConfig.bandwidth_operation',struct());
    latency=sixgr.util.structGet(cfg,'lls6g.resolvedConfig.power_and_rf_frontend.rf_switching_latency',NaN);
    assert(isfield(switching,'configuration_profile_switching') && ...
        isequal(switching.configuration_profile_switching,false) && ...
        isfield(switching,'dci_based_switching_enabled') && ...
        isequal(switching.dci_based_switching_enabled,false) && ...
        isnumeric(latency) && isscalar(latency) && isfinite(latency) && latency==0, ...
        'sixgr:truth:UnsupportedJointUCITimingScope', ...
        'Joint timing requires explicit fixed-BWP/no-RF-switching configuration; positive switching delays need their own budget.');
    assert(g.RNTI==dlGrant.RNTI && string(dt.ScheduledCCID)==string(ut.ScheduledCCID), ...
        'sixgr:truth:JointUCITimingIdentityMismatch','Joint grants must identify the same UE and carrier.');
    if logical(sixgr.util.structGet(cfg,'phy.csi.reportCSI',false))
        assert(string(sixgr.util.structGet(cfg,'phy.csi.reportTrigger',""))=="periodic", ...
            'sixgr:truth:UnsupportedJointUCITimingScope', ...
            'Aperiodic CSI requires its own processing budget and decoded trigger authority.');
    end
    dlCfg=sixgr.phy.grant.applyPHYGrantToConfig(cfg,dlGrant.PHYGrant);
    ulCfg=sixgr.phy.grant.applyPHYGrantToConfig(cfg,g.PHYGrant);
    dc=sixgr.phy.grid.makeCarrier(dlCfg); uc=sixgr.phy.grid.makeCarrier(ulCfg);
    mus=double([dt.DataDecision.SourceMu dt.DataDecision.TargetMu ...
        dt.HARQACKDecision.TargetMu ut.DataDecision.SourceMu ut.DataDecision.TargetMu]);
    assert(all(mus==mus(1)) && log2(dc.SubcarrierSpacing/15)==mus(1) && ...
        log2(uc.SubcarrierSpacing/15)==mus(1), ...
        'sixgr:truth:UnsupportedJointUCITimingScope', ...
        'Cross-numerology scheduling needs explicit control/data grid projection, not a same-grid shortcut.');
    pdsch=sixgr.phy.grid.pdschConfigFromConfig(dc,dlCfg, ...
        'MappingType',dlGrant.MappingType,'FixedReferenceMode',true);
    [~,~,pusch]=sixgr.phy.grid.allocREsPUSCH(uc,ulCfg, ...
        'MappingType',g.MappingType,'SymbolAllocation',g.SymbolAllocation,'PRBSet',g.PRBSet);
    overlap=0;
    if dt.ControlAbsoluteSlot==dt.DataAbsoluteSlot
        a=dt.ControlSymbolAllocation; b=dlGrant.SymbolAllocation;
        overlap=max(0,min(sum(a),sum(b))-max(a(1),b(1)));
    end
    b=sixgr.phy.frame.harqPUSCHMultiplexingProcessingTime(dc,pdsch,uc,pusch,mus,overlap);
    assert(b.D21Symbols==ut.DataDecision.ProcessingBudget.D21Symbols, ...
        'sixgr:truth:JointPUSCHProcessingAllocationMismatch', ...
        'Joint timing must use the same first-symbol PUSCH allocation as its frozen K2 decision.');
    row=struct('ULTargetTick',ut.DataDecision.TargetTick, ...
        'ULTargetEndTick',ut.DataDecision.TargetEndTick, ...
        'ULWaveformPlacementTick',ut.DataDecision.WaveformPlacementTick, ...
        'PDSCHEndTick',dt.DataDecision.TargetEndTick, ...
        'PDCCHEndTick',max(dt.DataDecision.SourceEndTick,ut.DataDecision.SourceEndTick), ...
        'PDSCHProcessingTicks',b.PDSCHTicks,'PDCCHProcessingTicks',b.PDCCHTicks, ...
        'FeedbackMu',dt.HARQACKDecision.TargetMu, ...
        'ScheduledCCID',string(dt.ScheduledCCID), ...
        'DLGrantContextID',string(dlGrant.PHYGrantContextId), ...
        'ULGrantContextID',string(g.PHYGrantContextId), ...
        'Budget',b,'Source',"gnb_tentative_or_transmitted_grant_allocation_not_UE_feedback");
    if isempty(constraints), constraints=row; else, constraints(end+1)=row; end %#ok<AGROW>
end
end
