function context=buildConfiguredPUCCHReceiveContext(obligation,csiConfig)
% Receive schema from a gNB obligation and installed CSI configuration.
% The caller owns scheduling/transport/occasion authority. This function does
% not infer an occasion or its HARQ/SR count from UE reports or payloads.
arguments
    obligation (1,1) struct
    csiConfig = []
end
names=["ObservationID","ConfigurationEpoch","HARQBitCount","SRBitCount", ...
    "PriorityIndex","CSIReportConfigID","CSIConfigurationEpoch"];
assert(all(isfield(obligation,names)) && ...
    isempty(setdiff(string(fieldnames(obligation)),names)), ...
    'sixgr:truth:InvalidPUCCHReceiveObligation', ...
    'A receive obligation may contain only installed identity and scheduled counts, never TX payload/state.');
for name=["ConfigurationEpoch","HARQBitCount","SRBitCount","PriorityIndex"]
    value=obligation.(name);
    assert(isnumeric(value) && isreal(value) && isscalar(value) && isfinite(value) && ...
        value>=0 && value==fix(value) && value<=flintmax, ...
        'sixgr:truth:InvalidPUCCHReceiveObligation','Invalid receiver obligation field %s.',name);
end
id=string(obligation.ObservationID);
assert(isscalar(id) && ~ismissing(id) && strlength(strtrim(id))>0, ...
    'sixgr:truth:InvalidPUCCHReceiveObligation','An observation must have a receiver-owned identity.');
part1=0; part2=0;
if isempty(csiConfig)
    assert(isequal(string(obligation.CSIReportConfigID),"") && ...
        isnumeric(obligation.CSIConfigurationEpoch) && isscalar(obligation.CSIConfigurationEpoch) && ...
        isnan(obligation.CSIConfigurationEpoch), ...
        'sixgr:truth:MissingInstalledCSIReceiveConfiguration','Do not drop a scheduled CSI obligation.');
else
    assert(isa(csiConfig,'sixgr.phy.mimo.CSIReportConfiguration') && isscalar(csiConfig), ...
        'sixgr:truth:MissingInstalledCSIReceiveConfiguration','Use the installed typed CSI configuration.');
    csiConfig.assertQualifiedWireLayout();
    assert(csiConfig.UCIChannel=="PUCCH" && ...
        isequal(csiConfig.ReportConfigID,string(obligation.CSIReportConfigID)) && ...
        isequal(csiConfig.Epoch,obligation.CSIConfigurationEpoch), ...
        'sixgr:truth:CSIReceiveConfigurationMismatch','CSI report identity, epoch and transport must match the gNB obligation.');
    part1=csiConfig.part1BitCount();
    part2=csiConfig.part2BitCount();
    % The qualified wideband PUCCH schema pads rank-dependent fields inside
    % Part 1. It has no separate Part 2; selected RI is decoded from Part 1.
    assert(part2==0 && isequal(csiConfig.part2BitCountCandidates(),0), ...
        'sixgr:truth:UnresolvedPUCCHCSIReceiveLayout','Do not borrow rank-dependent TX lengths for reception.');
end
total=obligation.HARQBitCount+obligation.SRBitCount+part1;
assert(total>0,'sixgr:truth:EmptyPUCCHReceiveObligation','No payload means no PUCCH receive schema.');
context=sixgr.phy.pucch.UCIReportContext(struct('ReportID',id, ...
    'ConfigurationEpoch',obligation.ConfigurationEpoch,'Sequence1Length',total, ...
    'Sequence2Length',part2,'HARQACKBits',obligation.HARQBitCount, ...
    'SRBits',obligation.SRBitCount,'CSIPart1Bits',part1,'CSIPart2Bits',part2, ...
    'PriorityIndex',obligation.PriorityIndex));
end
