function state=commitSharedULHARQCommand(state,cfg,grant)
% Register the gNB's physically transmitted command, independently of UE DCI.
owner=state.SharedWaveformStream;
key=sixgr.truth.scheduledULHARQReceiverKey(cfg,grant);
target=double(grant.TimingDecision.DataAbsoluteSlot)+1;
commands=owner.readTransmittedULControls(grant.UEIndex,target);
hit=find(cellfun(@(r)r.Binding.GrantContextID==string(grant.PHYGrant.GrantContextId),commands));
assert(isscalar(hit),'sixgr:truth:ULHARQScheduledCommandRequired','Require the actual unique gNB command.');
command=commands{hit}; scheduled=command.Binding.Grant;
assert(key==sixgr.truth.scheduledULHARQReceiverKey(cfg,scheduled) && ...
    isequaln(grant.DCI.Bits,scheduled.DCI.Bits) && ...
    isequaln(grant.TimingDecision,scheduled.TimingDecision) && ...
    grant.TBSBits==scheduled.TBSBits && ...
    target>=sixgr.util.structGet(state,'SweepPointStartSlot',1), ...
    'sixgr:truth:ULHARQScheduledCommandMismatch','Use this point''s scheduled grant, not a UE accepted assignment.');
prior=sixgr.util.structGet(state,'SharedGNBULHARQCommands',{});
assert(~any(cellfun(@(r)r.CommandObservationID==string(command.ObservationID) || ...
    r.GrantContextID==string(scheduled.PHYGrant.GrantContextId),prior)), ...
    'sixgr:truth:DuplicateULHARQScheduledCommand','One physical command must reserve exactly one receive attempt.');
entry=struct('CommandObservationID',string(command.ObservationID), ...
    'GrantContextID',string(scheduled.PHYGrant.GrantContextId),'ReceiverKey',key, ...
    'ScheduledSlot',target,'AvailableAtSample',command.AvailableAtSample, ...
    'Source',"actual_gNB_PDCCH_transmission_not_UE_DCI_result");
% Owner bindings retain the scheduler's original labels. Cross to the MAC
% runtime clock exactly once using the immutable canonical timing decision.
t=scheduled.TimingDecision;
scheduled=sixgr.truth.bindQueuedULGrantOccasion(scheduled,double(t.ControlAbsoluteSlot)+1,target, ...
    floor(double(t.ControlAbsoluteSlot)/state.SlotsPerFrame)+1, ...
    floor((target-1)/state.SlotsPerFrame)+1,double(t.K2));
state.ULHarq.onScheduledULGrant(scheduled,entry.CommandObservationID);
state.SharedGNBULHARQCommands=[prior,{entry}];
end
