function state=completeSharedDLWithoutAcceptedControl(state,item,control)
% Executed DL with an actually rejected PDCCH: no PDSCH decoder is invoked.
% This records a receive disposition, not a CRC, ACK/NACK or PHY trial.
owner=state.SharedWaveformStream;
assert(isa(owner,'sixgr.truth.CoupledWaveformStream') && item.Kind=="PDSCH" && ...
    isstruct(control) && isscalar(control) && isfield(control,'Allowed') && ...
    islogical(control.Allowed) && isscalar(control.Allowed) && ~control.Allowed, ...
    'sixgr:truth:InvalidSharedDLNoDecodeControl','Require a rejected shared DL control completion.');
controls=sixgr.util.structGet(state,'SharedReceivedGrantControls',{});
hit=find(cellfun(@(x)x.Key==control.Key,controls));
assert(isscalar(hit) && isequaln(controls{hit},control), ...
    'sixgr:truth:UnretainedSharedDLNoDecodeControl','The exact received control record must already exist.');
assert(all(isfield(control,{'ReceiverTrial','RejectedControlObservation'})), ...
    'sixgr:truth:MissingSharedDLRejectedControlEvidence','Retain the actual failed PDCCH receiver evidence.');
trial=control.ReceiverTrial;
observation=control.RejectedControlObservation;
assert(isstruct(trial) && isscalar(trial) && ...
    isequal(sixgr.util.structGet(trial,'Crash',true),false) && ...
    isequal(sixgr.util.structGet(trial,'DecodeAttempted',false),true) && ...
    isequal(sixgr.util.structGet(trial,'PDCCHCausalGrantDecodeOk',true),false), ...
    'sixgr:truth:InvalidSharedDLRejectedControlEvidence', ...
    'A receiver crash, unattempted control decode or accepted DCI is not a measured missed command.');
assert(isa(observation,'sixgr.phy.waveform.WaveformObservationBuffer') && observation.isComplete() && ...
    observation.SampleRateHz==owner.SampleRateHz && ...
    observation.EndSampleExclusive==control.AvailableAtSample && ...
    observation.EndSampleExclusive<=owner.Events.NextSampleIndex && ...
    trial.PDCCHObservationStartSample==observation.StartSample && ...
    trial.PDCCHObservationEndSampleExclusive==observation.EndSampleExclusive, ...
    'sixgr:truth:InvalidSharedDLRejectedControlClock','Rejected DCI must bind its completed physical receive window.');
assert(isstruct(control.ReceivedAssignment) && isempty(fieldnames(control.ReceivedAssignment)), ...
    'sixgr:truth:RejectedDLHasReceivedAssignment','A rejected command cannot retain an accepted UE allocation.');
p=item.Context.Prepared; grant=p.RequestBinding.Grant;
identity=item.Context.TransmissionIdentity;
assert(p.Direction=="DL" && isequaln(identity,sixgr.truth.preparedDataTransmissionIdentity(p,item.UE)) && ...
    control.Grant.Direction=="DL" && control.Grant.UEIndex==item.UE && ...
    control.Grant.RNTI==grant.RNTI && ...
    string(control.Grant.PHYGrant.GrantContextId)==string(grant.PHYGrant.GrantContextId), ...
    'sixgr:truth:SharedDLNoDecodeIdentityMismatch','Rejected control and executed data must retain the same grant and UE.');
[post,~,~,~,receiver]=sixgr.truth.sharedObservationEvidence(item.Planes,p);
assert(post.EndSampleExclusive<=owner.Events.NextSampleIndex && ...
    control.AvailableAtSample<=post.EndSampleExclusive, ...
    'sixgr:truth:FutureSharedDLNoDecodeDisposition','Wait for both actual control and data observation completion.');
slot=p.ReceiverConfig.lls6g.runtime.AbsoluteSlotIndex0+1;
validateattributes(slot,{'numeric'},{'scalar','real','finite','integer','positive','<=',state.CurrentSlot});
trace=state.SlotTraceTable;
source=find(double(trace.CanonicalSlot)==slot);
assert(isscalar(source),'sixgr:truth:MissingSharedSourceSlotTrace','Retain the already-started data source slot.');
frame=double(trace.FrameLocal(source));
validateattributes(frame,{'numeric'},{'scalar','real','finite','integer','positive'});
proof=struct('SharedTransmissionID',identity.TransmissionID);
sixgr.truth.validateSharedDataReceptionTX(state,proof,grant,p.Tx.TransportBlock,item.UE,'DL',slot);
% No decoder invocation, UE HARQ transition, feedback row or gNB outcome.
% Missing-DCI gaps are subsequently resolved by actual UCI reception.
row=struct('TransmissionID',identity.TransmissionID,'PHYGrantContextId',identity.PHYGrantContextId, ...
    'UEIndex',item.UE,'RNTI',grant.RNTI,'Direction',"DL",'SourceSlot',slot, ...
    'HARQProcess',grant.HARQ.HarqID,'NDI',logical(grant.HARQ.NDI),'TBSBits',numel(p.Tx.TransportBlock), ...
    'ControlKey',string(control.Key),'ControlObservationStartSample',observation.StartSample, ...
    'ControlAvailableAtSample',control.AvailableAtSample, ...
    'DataObservationStartSample',receiver.StartSample,'DataObservationEndSampleExclusive',receiver.EndSampleExclusive, ...
    'DispositionAvailableAtSample',owner.Events.NextSampleIndex,'SampleRateHz',owner.SampleRateHz, ...
    'DataDecodeAttempted',false,'UEHARQDecisionCreated',false,'FeedbackObservedAtDisposition',false, ...
    'Disposition',"received_DL_command_not_accepted_no_PDSCH_decode", ...
    'Source',"actual_shared_PDCCH_rejection_and_completed_DL_observation");
previous=sixgr.util.structGet(state,'SharedDLNoDecodeDispositionTable',table());
if isempty(previous), next=struct2table(row,'AsArray',true);
else, next=[previous;struct2table(row,'AsArray',true)]; end
ids=sixgr.util.structGet(state,'SharedDataNoDecodeCommittedIDs',strings(0,1));
assert(~any(ids==identity.TransmissionID),'sixgr:truth:DuplicateSharedDataRXCommit', ...
    'One physical data observation has one decode or no-decode disposition.');
state.SharedDLNoDecodeDispositionTable=next;
state.SharedDataNoDecodeCommittedIDs=[ids;identity.TransmissionID];
state.DLCompletedSlots=max(double(sixgr.util.structGet(state,'DLCompletedSlots',0)),slot);
state.DLCompletedFrames=max(double(sixgr.util.structGet(state,'DLCompletedFrames',0)),frame);
end
