function T = emptyCSIRSTrialTable()
%EMPTYCSIRSTRIALTABLE Return the canonical persisted CSI-RS trial schema.

row = struct( ...
    "Direction", "", "SignalFamily", "CSI-RS", "SNR_dB", NaN, "SFN", NaN, "Frame", NaN, "Slot", NaN, "Time_s", NaN, ...
    "CellID", NaN, "BWPID", NaN, "UEIndex", NaN, "RNTI", NaN, ...
    "ResourceID", NaN, "ResourceSetID", NaN, "CSIRSType", "", "NumPorts", NaN, "RowNumber", NaN, ...
    "Density", "", "Periodicity", "", "SymbolLocations", "", "SubcarrierLocations", "", "RBOffset", NaN, "NumRB", NaN, "NRE", NaN, ...
    "Scheduled", false, "Transmitted", false, "Observed", false, "Consumed", false, "Consumer", "", ...
    "ResourceExtractionAttempted", false, "ResourceExtractionAvailable", false, ...
    "ChannelEstimationAttempted", false, "ChannelEstimateAvailable", false, ...
    "ChannelEstimateSource", "", "ChannelEstimator", "", "ChannelInterpolationMethod", "", ...
    "ChannelEstimateConvention", "", "ChannelEstimateNoiseVariance", NaN, ...
    "ChannelEstimationLatency_ms", NaN, "ReceiverPipelineLatency_ms", NaN, ...
    "ReceiverStageLatencySource", "", ...
    "PilotRECount", NaN, "PilotResidualPower", NaN, "PilotResidualNMSE_dB", NaN, ...
    "HestDimensions", "", "HestRxPorts", NaN, "HestTxPorts", NaN, ...
    "CQI", NaN, "RI", NaN, "PMI", NaN, "LI",NaN,"CRI", NaN, "CQISource", "", ...
    "PMI_I11",NaN,"PMI_I12",NaN,"PMI_I13",NaN,"PMI_I2",NaN, ...
    "CSIReportMode", "", "CSIPayloadBitLength", NaN, "CSIPayloadHex", "", ...
    "CSIComputationStatus", "not_attempted", "CSIComputationErrorIdentifier", "", ...
    "CSIMeasurementID", "", "CSIMeasurementDigest", "", ...
    "CSIMeasurementProvenance", "", ...
    "CSIMeasurementStateAvailable", false, ...
    "CSIMeasurementStatus", "not_attempted", ...
    "CSIMeasurementSlot", NaN, ...
    "CSIMeasurementNoiseVariance", NaN, ...
    "NumConfiguredResources", NaN, "NumMeasuredResources", NaN, ...
    "ResourceObjectiveValues", "", "CRISelectionSource", "", ...
    "ConfiguredResourceIDs", "", "CSIRSPhysicalPortCount", NaN, ...
    "CSIRSWaveformPortCount", NaN, ...
    "CSIRSPrecoderSource", "", "CSIRSPrecoderDigests", "", ...
    "CSIRSWaveformPrecoderDigests", "", ...
    "CSIRSPortToElementMatrixDigests", "", ...
    "CSIRSPortProjectionSource", "", ...
    "CSIRSPortProjectionResidualMax", NaN, ...
    "PMIType", "", "PMICodebookMode", "", ...
    "ConditionNumber_dB", NaN, "ConditionNumberStatus", "not_evaluated", ...
    "RankEstimate", NaN, "SingularValues", "", ...
    "SpatialChannelEstimateConvention", "", ...
    "SpatialChannelSnapshotCount", NaN, ...
    "SpatialSignatureToken", "", "SpatialSignatureSHA256", "", ...
    "SpatialSignatureSource", "", "SpatialSignatureSourceSlot", NaN, ...
    "SpatialSignatureMeasurementDirection", "", ...
    "SpatialSignatureReciprocityMode", "", ...
    "SpatialSignatureRawRank", NaN, "SpatialSignatureRetainedRank", NaN, ...
    "SpatialSignatureDetectionThreshold", NaN, ...
    "SpatialSignatureNoiseVariance", NaN, ...
    "SpatialSignatureNoiseMargin_dB", NaN, ...
    "SpatialSignatureSnapshotCount", NaN, ...
    "SpatialSignatureReductionMode", "", ...
    "SpatialSignatureDomain", "", ...
    "SpatialSignatureStatus", "not_attempted", ...
    "SINR_dB", NaN, "SINRSource", "", ...
    "SINRValueRole", "", "SINRValueStatus", "", "SINRMeasurementDomain", "", ...
    "PowerReferencePlane", "", "CSIMeasurementAvailable", false, ...
    "ReportSourceSlot", NaN, "ReportDueSlot", NaN, "ReportDeliveredSlot", NaN, ...
    "ReportProcessed", false, "ReportStatus", "not_enqueued", "ReportIdentity", "", ...
    "MeasurementRSRP_dB", NaN, "MeasurementSource", "", "UpdateOutcome", "", ...
    "RuntimeMaterializationStatus", "", "TxRuntimeMaterializationStatus", "", ...
    "RxRuntimeObservationStatus", "", "RuntimeBlocker", "", "RuntimeEvidenceSource", "", ...
    "RuntimeEventObserved", false, "SourceArtifact", "air_interface/csv/csi_rs_trials.csv", "SourceTable", "air_interface/csv/csi_rs_trials.csv");
T = struct2table(repmat(row, 0, 1), "AsArray", true);
end
