function tf = isImmutableIdentityField(fieldName)
%ISIMMUTABLEIDENTITYFIELD True for provenance fields that cannot be filled.

name = regexprep(lower(char(string(fieldName))), "[^a-z0-9]", "");
exact = ["runid", "runtag", "scenarioid", "confighash", ...
    "configsha256", "resolvedconfigsha256", "executionid", ...
    "finalizationid", "attemptid", "artifactid", ...
    "sourceartifactid", "sourceartifactsha256", "sourcecsvsha256", ...
    "sourcesha256", "gitcommit", "gitdiffsha256"];
tf = any(name == exact) || endsWith(name, "confighash") || ...
    endsWith(name, "configsha256") || endsWith(name, "artifactsha256");
end
