function measurement=measureWaveformGainEnergy(before,after)
% Scoring-only sample energies at the two sides of an executed gain stage.
% No configured gain, reference waveform or receiver estimate is an input.
assert((isa(before,'double') || isa(before,'single')) && ...
    strcmp(class(before),class(after)) && ismatrix(before) && ...
    isequal(size(before),size(after)) && ~isempty(before) && ...
    all(isfinite(before(:))) && all(isfinite(after(:))), ...
    'sixgr:truth:InvalidGainEnergySamples', ...
    'Measure finite, same-sized actual input/output samples in one numeric domain.');
measurement=struct('InputEnergy_mWsample',sum(abs(double(before(:))).^2), ...
    'OutputEnergy_mWsample',sum(abs(double(after(:))).^2), ...
    'SampleElementCount',numel(before),'SampleCount',size(before,1), ...
    'BranchCount',size(before,2), ...
    'Source',"actual_samples_before_after_large_scale_gain", ...
    'ReceiverEstimatorInput',false);
% Conservative floating-point allowance: sample multiplication/casting plus
% double-precision accumulation. This is not a propagation-model tolerance.
measurement.RelativeTolerance=64*double(eps(class(before)))+8*numel(before)*eps;
assert(isfinite(measurement.InputEnergy_mWsample) && ...
    isfinite(measurement.OutputEnergy_mWsample), ...
    'sixgr:truth:GainEnergyOverflow','Executed sample energy is not representable.');
end
