function prepared=prepareConfiguredSRTransmission(state,cfg,h)
% UE-side procedure decision only. It must not define the gNB hypothesis.
prepared=[];
assert(~logical(sixgr.util.structGet(cfg,'mac.phase08.sr.enabled',false)), ...
    'sixgr:truth:UnboundMACSRProcedure','Bind enabled MAC triggers/timers before physical SR transmission.');
states=sixgr.phy.pucch.SchedulingRequestState.atSlot( ...
    state.UEConfiguredSRProcedures{h.UEIndex,h.ServingCell},h.TargetSlot-1);
calendar=h.SRReportCalendar;
hit=arrayfun(@(s)s.Data.SRResourceConfigurationID==calendar.SRResourceConfigurationID,states);
assert(nnz(hit)==1,'sixgr:truth:MissingSRProcedureState','Retain the installed UE SR procedure.');
data=states(hit).Data;
assert(data.ConfigurationEpoch==h.Context.ConfigurationEpoch && data.UEIndex==h.UEIndex && ...
    data.RNTI==h.RNTI && data.ServingCell==h.ServingCell && ...
    data.SchedulingRequestID==calendar.SchedulingRequestID && ...
    data.PeriodSlots==calendar.PeriodSlots && data.OffsetSlots==calendar.OffsetSlots, ...
    'sixgr:truth:SRProcedureIdentityMismatch','UE procedure and installed SR resource must agree.');
if ~data.Transmit, return; end % Negative SR emits no waveform; RX still runs.
[commands,~]=sixgr.truth.findScheduledPUSCHOverlap(state,cfg,h.UEIndex,h.TargetSlot, ...
    [calendar.StartSymbol calendar.NumSymbols]);
assert(isempty(commands),'sixgr:truth:StandaloneSRPUSCHOverlapRequiresMACResolution', ...
    'Positive standalone SR/PUSCH overlap needs received-grant/MAC priority resolution; never emit both silently.');
data.ResourceID=calendar.PUCCHResourceID;
sr=sixgr.phy.pucch.SchedulingRequestState(data);
id=cfg.phy.frame.DefaultIdentity;
ue=struct('UEID',h.UEIndex,'RNTI',h.RNTI,'ServingCell',h.ServingCell, ...
    'PUCCHCell',h.ServingCell,'ComponentCarrier',id.ScheduledCCID,'ActiveULBWP',id.ULBWPID);
[~,~,~,partition]=sixgr.truth.CoupledTruthRuntime.resolveSlotPartition(cfg,h.TargetSlot);
carrier=sixgr.phy.grid.makeCarrier(cfg);
ownership=repmat('F',1,double(carrier.SymbolsPerSlot));
for pair={{'DLSymbolAllocation','D'},{'GuardSymbolAllocation','G'},{'ULSymbolAllocation','U'}}
    value=partition.(pair{1}{1}); ownership(value(1)+(1:value(2)))=pair{1}{2};
end
frame=struct('TargetSlot',h.TargetSlot,'SlotSymbolOwnership',string(ownership), ...
    'FlexibleResolutionProvided',false);
plan=sixgr.phy.pucch.PUCCHConfigBuilder.planSR(cfg,ue,sr,frame);
connected=sixgr.phy.pucch.PUCCHConfigBuilder.materialize(cfg,plan);
args={'Carrier',carrier,'Assignment',connected.Assignment,'Report',connected.Report, ...
    'ReceiverContext',connected.ReceiverContext,'SNR_dB',sixgr.truth.resolvePUCCHConfiguredSNRMetadata(state,cfg), ...
    'ChannelProfile',sixgr.channel.resolveConcreteProfile(cfg),'Seed',h.TargetSlot, ...
    'TimingAdvanceSamples',cfg.SharedULTimingContext.ReceivedRARTiming.Samples};
trial=sixgr.link.runPUCCHWaveformTrial(cfg,args{:},'PrepareOnly',true);
assert(isfield(trial,'PreparedTransmission'),'sixgr:truth:SharedPUCCHPreparationFailed', ...
    'Positive SR must retain its actual typed waveform.');
prepared=struct('Prepared',trial.PreparedTransmission,'Config',cfg,'Arguments',{args}, ...
    'Slot',h.TargetSlot,'UE',h.UEIndex,'GNBReception',h,'UETransmitSRState',sr);
end
