function event=prepareSharedULHARQSchedulerFeedback(state,grant,decision)
% Preflight receive-driven scheduler mutation; no UE TX/acceptance input.
a=decision.ReceiverAttempt.Attempt;
commands=sixgr.util.structGet(state,'SharedGNBULHARQCommands',{});
hit=find(cellfun(@(r)r.CommandObservationID==a.CommandObservationID && ...
    r.GrantContextID==a.GrantContextID && r.ReceiverKey==a.ReceiverKey,commands));
assert(isscalar(hit),'sixgr:truth:ULHARQSchedulerCommandRequired', ...
    'The receive outcome requires its retained physical scheduling lifecycle.');
entity=state.ULHarq; ue=find(entity.UEList==grant.RNTI); pid=double(grant.HARQ.HarqID)+1;
assert(isscalar(ue) && pid>=1 && pid<=entity.NumProcesses, ...
    'sixgr:truth:ULHARQSchedulerProcessRequired','Retain the allocated gNB process.');
p=entity.UEProcs{ue}(pid);
assert(p.Active && p.AwaitingFeedback && p.ScheduledAttemptCount>0 && ...
    p.LastScheduledSlot==double(grant.Slot) && p.LastScheduledCommandID==a.CommandObservationID && ...
    p.NDI==grant.HARQ.NDI && p.NDIEpoch==grant.HARQ.NDIEpoch && p.RV==grant.HARQ.RV, ...
    'sixgr:truth:ULHARQSchedulerAttemptMismatch','Reject stale, duplicate or foreign receive outcomes.');
assert(islogical(decision.DecodeAttempted) && isscalar(decision.DecodeAttempted) && ...
    islogical(decision.CRCPass) && isscalar(decision.CRCPass) && ...
    (decision.DecodeAttempted || ~decision.CRCPass) && ...
    a.EndSampleExclusive<=a.AvailableAtSample && a.AvailableAtSample<=state.SharedWaveformStream.Events.NextSampleIndex, ...
    'sixgr:truth:InvalidULHARQReceiverDecision','Use the completed actual receiver outcome.');
outcome="DTX";
if decision.DecodeAttempted
    outcome="NACK";
    if decision.CRCPass, outcome="ACK"; end
end
event=struct('RNTI',grant.RNTI,'HarqID',grant.HARQ.HarqID,'SourceSlot',double(grant.Slot), ...
    'FeedbackSlot',max(double(grant.Slot)+1,double(state.CurrentSlot)), ...
    'Outcome',outcome,'AvailableAtSample',a.AvailableAtSample,'ReceiverCRCAvailable',decision.DecodeAttempted, ...
    'UEIndex',grant.UEIndex,'ServingCell',grant.ServingCell,'TBSBits',grant.TBSBits, ...
    'RV',grant.HARQ.RV,'IsRetransmission',p.ScheduledAttemptCount>1, ...
    'Ack',outcome=="ACK",'FeedbackOutcome',outcome);
end
