function [usable,crcPass]=puschUCIFieldUsable(e,bits,count)
% Receiver-owned UCI field acceptance shared by CSI and HARQ reducers.
assert(isstruct(e) && isscalar(e) && ...
    all(isfield(e,{'InformationBitCount','CRCApplicable','CRCPass','DecodeUsable','Source','CodeBlockErrors'})) && ...
    e.InformationBitCount==count && isequal(e.CRCApplicable,count>=12) && ...
    string(e.Source)=="nrUCIDecode_received_LLR_and_code_block_error_flags", ...
    'sixgr:truth:InvalidPUSCHUCIReceiverEvidence','UCI length, CRC scope and actual decoder authority must agree.');
assert(islogical(e.DecodeUsable) && isscalar(e.DecodeUsable), ...
    'sixgr:truth:InvalidPUSCHUCIReceiverEvidence','Decode usability must be an explicit receiver boolean.');
crcPass=e.CRCPass;
if e.CRCApplicable
    assert(isscalar(crcPass) && ismember(crcPass,[0 1]) && ...
        islogical(e.CodeBlockErrors) && ~isempty(e.CodeBlockErrors) && ...
        crcPass==double(~any(e.CodeBlockErrors(:))), ...
        'sixgr:truth:InvalidPUSCHUCIReceiverEvidence','Applicable CRC must agree with actual code-block error flags.');
else
    assert(isscalar(crcPass) && isnan(crcPass) && isempty(e.CodeBlockErrors), ...
        'sixgr:truth:InvalidPUSCHUCIReceiverEvidence','Short UCI has no CRC; do not manufacture a pass.');
end
confidenceUsable=true;
if count>0 && count<12
    assert(isfield(e,'ShortConfidenceApplicable') && isequal(e.ShortConfidenceApplicable,true) && ...
        isfield(e,'ShortConfidence') && isstruct(e.ShortConfidence) && isscalar(e.ShortConfidence), ...
        'sixgr:truth:InvalidPUSCHUCIReceiverEvidence','Short UCI requires receiver confidence evidence, not a CRC substitute.');
    c=e.ShortConfidence;
    assert(all(isfield(c,{'Algorithm','PolicySource','MinimumPosterior','Model', ...
        'SignalPresenceQualified','SelectedPosterior','MaximumPosterior', ...
        'UniqueMaximum','DecoderMatchesMaximum','Accepted','CandidateCount','SelectedBits'})) && ...
        c.Algorithm=="codeword_posterior" && ...
        c.Model=="uniform_codewords_factorized_bit_LLR_conditional_on_transmission" && ...
        isequal(c.SignalPresenceQualified,false) && c.CandidateCount==2^count, ...
        'sixgr:truth:InvalidPUSCHUCIReceiverEvidence','Short-UCI confidence must retain its conditional model and coding scope.');
    sixgr.phy.ul.pusch.resolveShortUCIDecisionPolicy(struct( ...
        'algorithm',c.Algorithm,'minimumPosterior',c.MinimumPosterior,'Source',c.PolicySource));
    assert(islogical(c.Accepted) && isscalar(c.Accepted) && ...
        islogical(c.UniqueMaximum) && isscalar(c.UniqueMaximum) && ...
        islogical(c.DecoderMatchesMaximum) && isscalar(c.DecoderMatchesMaximum) && ...
        isnumeric(c.SelectedPosterior) && isscalar(c.SelectedPosterior) && ...
        isnumeric(c.MaximumPosterior) && isscalar(c.MaximumPosterior), ...
        'sixgr:truth:InvalidPUSCHUCIReceiverEvidence','Confidence decision and posterior must be scalar receiver evidence.');
    confidenceUsable=isequal(c.SelectedBits(:),bits(:)) && ...
        c.Accepted && c.UniqueMaximum && c.DecoderMatchesMaximum && ...
        isfinite(c.SelectedPosterior) && c.SelectedPosterior>=c.MinimumPosterior && ...
        c.SelectedPosterior<=1 && c.SelectedPosterior==c.MaximumPosterior;
end
usable=numel(bits)==count && all(ismember(bits,int8([0 1]))) && ...
    (count==0 || e.DecodeUsable) && (~e.CRCApplicable || crcPass==1) && confidenceUsable;
end
