function [usable,crcPass]=puschUCIFieldUsable(e,bits,count)
% Receiver-owned UCI field acceptance shared by CSI and HARQ reducers.
assert(isstruct(e) && isscalar(e) && ...
    all(isfield(e,{'InformationBitCount','CRCApplicable','CRCPass','DecodeUsable','Source','CodeBlockErrors'})) && ...
    e.InformationBitCount==count && isequal(e.CRCApplicable,count>=12) && ...
    string(e.Source)=="nrUCIDecode_received_LLR_and_code_block_error_flags", ...
    'sixgr:truth:InvalidPUSCHUCIReceiverEvidence','UCI length, CRC scope and actual decoder authority must agree.');
assert(islogical(e.DecodeUsable) && isscalar(e.DecodeUsable), ...
    'sixgr:truth:InvalidPUSCHUCIReceiverEvidence','Decode usability must be an explicit receiver boolean.');
crcPass=e.CRCPass;
if e.CRCApplicable
    assert(isscalar(crcPass) && ismember(crcPass,[0 1]) && ...
        islogical(e.CodeBlockErrors) && ~isempty(e.CodeBlockErrors) && ...
        crcPass==double(~any(e.CodeBlockErrors(:))), ...
        'sixgr:truth:InvalidPUSCHUCIReceiverEvidence','Applicable CRC must agree with actual code-block error flags.');
else
    assert(isscalar(crcPass) && isnan(crcPass) && isempty(e.CodeBlockErrors), ...
        'sixgr:truth:InvalidPUSCHUCIReceiverEvidence','Short UCI has no CRC; do not manufacture a pass.');
end
usable=numel(bits)==count && all(ismember(bits,int8([0 1]))) && ...
    (count==0 || e.DecodeUsable) && (~e.CRCApplicable || crcPass==1);
end
