function slot=receivedPUSCHUCIOccasion(owner,harq,grant)
% Original PUSCH occasion, distinct from the later scheduler callback slot.
assert(isa(owner,'sixgr.truth.CoupledWaveformStream') && isscalar(owner), ...
    'sixgr:truth:SharedUCIClockRequired','Retain the physical shared stream owner.');
sixgr.truth.harqFeedbackReceiveTimingFields(harq,grant,true);
e=harq.ReceivedTimingEvidence;
assert(string(e.Direction)=="UL" && e.SampleRateHz==owner.SampleRateHz, ...
    'sixgr:truth:InvalidReceivedPUSCHUCIClock', ...
    'UCI must belong to the received PUSCH in this physical sample domain.');
assert(e.ResultAvailableAtSample<=owner.Events.NextSampleIndex, ...
    'sixgr:truth:FuturePUSCHUCIDelivery', ...
    'Do not deliver UCI before its actual receiver result is available.');
slot=double(e.DataAbsoluteSlot)+1;
end
