function [eligible, evidence] = resolveCSIReceiveReferenceEvidence(state,cfg,ue,servingCell,calendar,targetSlot)
% GNB receive applicability from its own executed reference TX, not UE RX.
% UE measurement success belongs to the separate report producer. A failed
% or absent UE report after an eligible reference must remain observable.

validateattributes(ue,{'numeric'},{'scalar','real','finite','integer','positive'});
validateattributes(servingCell,{'numeric'},{'scalar','real','finite','integer','nonnegative'});
validateattributes(targetSlot,{'numeric'},{'scalar','real','finite','integer','positive'});
assert(istable(calendar),'sixgr:truth:InvalidCSIReceiveCalendar', ...
    'The installed CSI receive calendar must be a table.');

eligible=false(height(calendar),1);
evidence=table();
if isempty(calendar)
    return;
end
assert(ismember('CSIReferenceSlot',calendar.Properties.VariableNames), ...
    'sixgr:truth:InvalidCSIReceiveCalendar', ...
    'The installed CSI calendar must identify its CSI reference slot.');

first=sixgr.util.structGet(state,'SweepPointStartSlot',1);
validateattributes(first,{'numeric'},{'scalar','real','finite','integer','positive'});
owner=sixgr.util.structGet(state,'SharedWaveformStream',[]);
assert(isa(owner,'sixgr.truth.CoupledWaveformStream') && isscalar(owner), ...
    'sixgr:truth:CSIReferenceTXOwnerRequired','A retained TX requires its actual physical owner.');
records=owner.DataTransmissions;
csirsRecords=owner.CSIRSTransmissions;
ledger=sixgr.util.structGet(state,'SharedDataTXLedger',{});
carrier=sixgr.phy.grid.makeCarrier(cfg);

rows=cell(0,1);
for ci=1:height(calendar)
    reference=double(calendar.CSIReferenceSlot(ci));
    if ~(isfinite(reference) && reference==fix(reference) && ...
            reference>=first && reference<=targetSlot)
        continue;
    end
    referenceEnd=sixgr.phy.frame.slotStartSample( ...
        carrier,reference,owner.SampleRateHz);
    if referenceEnd>owner.Events.NextSampleIndex
        continue;
    end
    best=0;
    bestSlot=-Inf;
    bestIndependent=0;
    for ri=1:numel(csirsRecords)
        r=csirsRecords(ri);
        if r.SignalFamily~="CSI-RS" || r.ServingCell~=servingCell || ...
                r.Slot<first || r.Slot>reference || ...
                r.PhysicalConfigurationEpoch~=owner.Physical.ConfigurationEpoch || ...
                r.SampleRateHz~=owner.SampleRateHz || ...
                r.CommittedAtSample>r.EndSampleExclusive || ...
                r.EndSampleExclusive>owner.Events.NextSampleIndex || ...
                ~isequaln(r.ReferenceConfiguration,cfg.phy.csirs) || ...
                ~isequaln(r.ReportConfiguration,cfg.phy.csi.reportConfiguration) || ...
                ~isequaln(r.FrameIdentity,cfg.phy.frame.DefaultIdentity) || ...
                sixgr.truth.isCSIReportingMeasurementGap(cfg,r.Slot)
            continue;
        end
        if r.Slot>=bestSlot
            bestIndependent=ri;
            best=0;
            bestSlot=r.Slot;
        end
    end
    for ri=1:numel(ledger)
        entry=ledger{ri};
        r=sixgr.util.structGet(entry,'CSIReference',struct([]));
        if isempty(r), continue; end
        id=entry.Identity;
        % Cell-common CSI-RS can be embedded in another UE's PDSCH. Match
        % installed resource/BWP identity, not that UE's receive success.
        if id.Direction~="DL" || r.ServingCell~=servingCell || ...
                r.Slot<first || r.Slot>reference || ~r.ReportEnabled || ...
                r.PhysicalConfigurationEpoch~=owner.Physical.ConfigurationEpoch || ...
                id.SampleRateHz~=owner.SampleRateHz || ...
                id.EndSampleExclusive>owner.Events.NextSampleIndex || ...
                ~isequaln(r.ReferenceConfiguration,cfg.phy.csirs) || ...
                ~isequaln(r.ReportConfiguration,cfg.phy.csi.reportConfiguration) || ...
                ~isequaln(r.FrameIdentity,cfg.phy.frame.DefaultIdentity) || ...
                sixgr.truth.isCSIReportingMeasurementGap(cfg,r.Slot)
            continue;
        end
        hit=find(arrayfun(@(x)x.Identity.TransmissionID==id.TransmissionID,records));
        assert(isscalar(hit) && isequaln(records(hit).Identity,id) && ...
            records(hit).FirstActiveSample==entry.FirstActiveSample && ...
            records(hit).CommittedAtSample==entry.CommittedAtSample && ...
            entry.CommittedAtSample<=id.EndSampleExclusive, ...
            'sixgr:truth:CSIReferenceTXNotExecuted', ...
            'A caller-created preparation/ledger cannot establish reference execution.');
        if r.Slot>=bestSlot
            best=ri;
            bestIndependent=0;
            bestSlot=r.Slot;
        end
    end
    if bestIndependent>0
        eligible(ci)=true;
        r=csirsRecords(bestIndependent);
        rows{end+1,1}=struct('UEIndex',ue,'ServingCell',servingCell, ...
            'Slot',r.Slot,'CSIReferenceSlot',reference,'ReportSlot',targetSlot, ...
            'TransmissionID',string(r.ComponentID), ...
            'EmbeddingUEIndex',NaN, ...
            'TransmissionEndSampleExclusive',r.EndSampleExclusive, ...
            'SampleRateHz',owner.SampleRateHz, ...
            'PhysicalConfigurationEpoch',r.PhysicalConfigurationEpoch, ...
            'ResourceSetID',r.ResourceSetID,'WaveformMappedRE',r.WaveformMappedRE, ...
            'Source',"gnb_completed_independent_csirs_TX_not_UE_measurement_outcome"); %#ok<AGROW>
    elseif best>0
        eligible(ci)=true;
        entry=ledger{best}; r=entry.CSIReference;
        rows{end+1,1}=struct('UEIndex',ue,'ServingCell',servingCell, ...
            'Slot',r.Slot,'CSIReferenceSlot',reference,'ReportSlot',targetSlot, ...
            'TransmissionID',string(entry.Identity.TransmissionID), ...
            'EmbeddingUEIndex',entry.Identity.UEIndex, ...
            'TransmissionEndSampleExclusive',entry.Identity.EndSampleExclusive, ...
            'SampleRateHz',owner.SampleRateHz, ...
            'PhysicalConfigurationEpoch',r.PhysicalConfigurationEpoch, ...
            'ResourceSetID',r.ResourceSetID,'WaveformMappedRE',r.WaveformMappedRE, ...
            'Source',"gnb_completed_reference_TX_not_UE_measurement_outcome"); %#ok<AGROW>
    end
end
if ~isempty(rows)
    evidence=struct2table(vertcat(rows{:}),'AsArray',true);
end
end
