function [records,prior,token]=resolveULHARQReceiverState(records,attempt,decision)
% Value-state reducer for gNB reception, separate from UE TX/delivery state.
% The caller proves the actual command/capture. Declared inputs to this pure
% reducer alone are not physical execution evidence.
if nargin<3, decision=[]; end
assert(iscell(records) && isstruct(attempt) && isscalar(attempt) && ...
    all(isfield(attempt,{'ScopeKey','ReceiverKey','NDIEpoch','DataAbsoluteSlot', ...
    'ObservationID','GrantContextID','CommandObservationID','StartSample', ...
    'EndSampleExclusive','SampleRateHz','AvailableAtSample'})), ...
    'sixgr:truth:ULHARQReceiveAttemptRequired','Require a complete scheduled receive-attempt identity.');
for name=["ScopeKey","ReceiverKey","ObservationID","GrantContextID","CommandObservationID"]
    v=attempt.(name);
    assert(isstring(v) && isscalar(v) && ~ismissing(v) && strlength(v)>0, ...
        'sixgr:truth:ULHARQReceiveAttemptRequired','Require scalar nonempty identity %s.',name);
end
for name=["NDIEpoch","DataAbsoluteSlot","StartSample","EndSampleExclusive","AvailableAtSample"]
    validateattributes(attempt.(name),{'numeric'},{'scalar','real','finite','integer','nonnegative','<=',flintmax});
end
validateattributes(attempt.SampleRateHz,{'numeric'},{'scalar','real','finite','positive'});
assert(attempt.StartSample<attempt.EndSampleExclusive && ...
    attempt.EndSampleExclusive<=attempt.AvailableAtSample, ...
    'sixgr:truth:ULHARQReceiveAttemptClock','Do not commit an incomplete or future receive attempt.');
hit=find(cellfun(@(r)r.Attempt.ScopeKey==attempt.ScopeKey,records));
assert(numel(hit)<=1,'sixgr:truth:AmbiguousULHARQReceiverState','One installed process has one receiver state.');
previous=struct(); prior=[];
if ~isempty(hit)
    previous=records{hit}; old=previous.Attempt;
    assert(attempt.NDIEpoch>=old.NDIEpoch && ...
        (attempt.NDIEpoch>old.NDIEpoch || attempt.ReceiverKey==old.ReceiverKey), ...
        'sixgr:truth:StaleULHARQReceiverEpoch','Never reuse older or contradictory process/NDI state.');
    assert(attempt.DataAbsoluteSlot>old.DataAbsoluteSlot && ...
        attempt.EndSampleExclusive>old.EndSampleExclusive && ...
        attempt.AvailableAtSample>=old.AvailableAtSample && ...
        attempt.ObservationID~=old.ObservationID && attempt.GrantContextID~=old.GrantContextID && ...
        attempt.SampleRateHz==old.SampleRateHz, ...
        'sixgr:truth:StaleULHARQReceiveAttempt','Reject duplicate, out-of-order or differently clocked reception.');
    if attempt.ReceiverKey==old.ReceiverKey, prior=previous.SoftBuffer; end
end
sixgr.link.validateULHARQSoftBufferIdentity(prior,attempt.ReceiverKey);
if ~isempty(prior), localValidateSoftEvidence(prior); end
fingerprint=previous;
if ~isempty(fieldnames(previous)) && ~isempty(previous.SoftBuffer)
    % JSON alone aliases +Inf/-Inf/NaN. Filler LLR infinities are legitimate
    % LDPC evidence; hash their numeric bytes, including shape, explicitly.
    for name=["LLRSum","ObservationWeight"]
        v=previous.SoftBuffer.(name);
        fingerprint.SoftBuffer.(name)=struct('Shape',size(v), ...
            'NumericSHA256',sixgr.phy.waveform.WaveformHash.numeric(v));
    end
end
token=struct('Attempt',attempt,'PriorStateDigest',sixgr.phy.pucch.PUCCHUtil.hash(fingerprint));
if isempty(decision), return; end
assert(isstruct(decision) && isscalar(decision) && ...
    all(isfield(decision,{'ReceiverAttempt','DecodeAttempted','CRCPass','SoftBuffer'})) && ...
    isequaln(decision.ReceiverAttempt,token), ...
    'sixgr:truth:ChangedULHARQReceiverState','The decoder must consume the exact retained prior state and receive attempt.');
assert(islogical(decision.DecodeAttempted) && isscalar(decision.DecodeAttempted) && ...
    islogical(decision.CRCPass) && isscalar(decision.CRCPass) && ...
    (decision.DecodeAttempted || ~decision.CRCPass), ...
    'sixgr:truth:InvalidULHARQReceiverDecision','An unattempted decode cannot supply a CRC pass.');
soft=prior;
if decision.DecodeAttempted
    sixgr.link.validateULHARQSoftBufferIdentity(decision.SoftBuffer,attempt.ReceiverKey);
    assert(~isempty(decision.SoftBuffer) && isstruct(decision.SoftBuffer) && ...
        ~isempty(fieldnames(decision.SoftBuffer)), ...
        'sixgr:truth:ULHARQReceiverSoftEvidenceRequired','Attempted decoding must retain its actual rate-recovered soft evidence.');
    soft=decision.SoftBuffer;
    localValidateSoftEvidence(soft);
    if ~isempty(prior)
        assert(isequal(size(soft.LLRSum),size(prior.LLRSum)) && ...
            string(soft.CodingLayoutHash)==string(prior.CodingLayoutHash), ...
            'sixgr:truth:ULHARQReceiverCodingDomainChanged', ...
            'An unchanged process/NDI epoch cannot silently reset an incompatible mother-code layout.');
    end
    if decision.CRCPass, soft=[]; end
else
    assert(isempty(decision.SoftBuffer), ...
        'sixgr:truth:UnattemptedULHARQSoftEvidence','No new decoded soft state may be manufactured for an unattempted TB.');
end
record=struct('Attempt',attempt,'DecodeAttempted',decision.DecodeAttempted, ...
    'CRCPass',decision.CRCPass,'SoftBuffer',soft, ...
    'PriorStateDigest',token.PriorStateDigest, ...
    'Source',"gnb_receiver_crc_and_soft_state_not_UE_transmission_ledger");
if isempty(hit), records{end+1}=record; else, records{hit}=record; end
end

function localValidateSoftEvidence(soft)
assert(isfield(soft,'CodingLayoutHash') && ...
    (ischar(soft.CodingLayoutHash)||isstring(soft.CodingLayoutHash)) && ...
    isscalar(string(soft.CodingLayoutHash)) && ~ismissing(string(soft.CodingLayoutHash)) && ...
    strlength(string(soft.CodingLayoutHash))>0 && ...
    isnumeric(soft.LLRSum) && isreal(soft.LLRSum) && ismatrix(soft.LLRSum) && ...
    ~isempty(soft.LLRSum) && ~any(isnan(soft.LLRSum(:))) && ...
    isnumeric(soft.ObservationWeight) && isreal(soft.ObservationWeight) && ...
    isequal(size(soft.ObservationWeight),size(soft.LLRSum)) && ...
    all(isfinite(soft.ObservationWeight(:))) && all(soft.ObservationWeight(:)>=0), ...
    'sixgr:truth:InvalidULHARQReceiverSoftEvidence', ...
    'Keep an identified mother-code layout, non-NaN real LLRs and matching finite nonnegative observation weights.');
end
