function result=resolveConfiguredSROverlap(calendar,slot,windows,priority)
% Payload-free union of configured SR occasions overlapping UCI resources.
% Windows are pre-multiplexing [startSymbol,numSymbols] rows, not UE bits.
validateattributes(slot,{'numeric'},{'scalar','real','finite','integer','positive'});
validateattributes(windows,{'numeric'},{'2d','ncols',2,'real','finite','integer','nonnegative'});
assert(~isempty(windows) && all(windows(:,2)>0),'sixgr:truth:InvalidSRResourceWindows', ...
    'Provide nonempty pre-multiplexing symbol intervals.');
validateattributes(priority,{'numeric'},{'scalar','real','finite','integer','>=',0,'<=',1});
required={'Slot','StartSymbol','NumSymbols','PriorityIndex','SRResourceConfigurationID', ...
    'SchedulingRequestID','ULResourceAvailable','ObligationID'};
assert(istable(calendar) && all(ismember(required,calendar.Properties.VariableNames)), ...
    'sixgr:truth:InvalidSROpportunityTable','Use the configured SR opportunity table.');
for name={'UEIndex','RNTI','ServingCell','ComponentCarrier','ActiveULBWP','PUCCHConfigurationEpoch'}
    assert(ismember(name{1},calendar.Properties.VariableNames) && ...
        (isempty(calendar) || numel(unique(calendar.(name{1})))==1), ...
        'sixgr:truth:MixedSRReceiverIdentity','Resolve one receiver/BWP/configuration before counting SR bits.');
end
timeOverlap=false(height(calendar),1);
for k=1:size(windows,1)
    timeOverlap=timeOverlap | (calendar.StartSymbol<sum(windows(k,:)) & ...
        windows(k,1)<calendar.StartSymbol+calendar.NumSymbols);
end
mask=calendar.Slot==slot & calendar.ULResourceAvailable & calendar.PriorityIndex==priority & timeOverlap;
rows=sortrows(calendar(mask,:),{'SRResourceConfigurationID'});
ids=double(rows.SRResourceConfigurationID);
assert(numel(unique(ids))==numel(ids),'sixgr:truth:DuplicateSRResourceConfiguration', ...
    'One SR opportunity per installed resource configuration in this slot.');
result=struct('SRResourceConfigurationIDs',ids,'SchedulingRequestIDs',double(rows.SchedulingRequestID), ...
    'ObligationIDs',string(rows.ObligationID),'OpportunityCount',height(rows), ...
    'EncodedBitCount',ceil(log2(height(rows)+1)), ...
    'Source',"configured_time_overlapping_SR_resources_no_UE_payload");
end
