function [grid,evidence]=sharedDataScoringWaveformReference(snapshot,prepared,observation,scoringEvidence)
% Exact post-reception effective DM-RS reference from the executed link IQ.
% The practical receiver never sees this noiseless scoring plane.  This
% function executes no channel or RF model and fits no gain or phase.
arguments
    snapshot (1,1) struct
    prepared (1,1) sixgr.link.PreparedDataTransmission
    observation (1,1) sixgr.phy.waveform.WaveformObservationBuffer
    scoringEvidence (1,1) struct
end
channel="PUSCH";
if prepared.Direction=="DL", channel="PDSCH"; end
assert(snapshot.Contract==channel+"_pilot_channel_capture/v1" && ...
    observation.isComplete() && observation.SampleRateHz==prepared.SampleRateHz && ...
    observation.StartSample==prepared.ReceiveStartSample && ...
    ~logical(scoringEvidence.ReceiverEstimatorInput) && ...
    double(scoringEvidence.AdditionalChannelExecutions)==0 && ...
    double(scoringEvidence.AdditionalRFExecutions)==0, ...
    'sixgr:truth:InvalidDataScoringWaveformReference', ...
    'Use the complete independently retained desired-link waveform on the actual receive clock.');

op=snapshot.ReceiverChannelOperator;
required={'ReceiveCombiningMatrix','CaptureOriginCFOCorrection_Hz', ...
    'AlignedOriginCFOCorrection_Hz','AppliedTimingCorrection_samples','SampleRateHz'};
assert(all(isfield(op,required)) && double(op.SampleRateHz)==prepared.SampleRateHz, ...
    'sixgr:truth:MissingDataScoringReceiverOperator', ...
    'Retain the actual timing, frequency and spatial receiver operations.');
wave=observation.readComplete();
assert(~isempty(wave) && all(isfinite(wave),'all'), ...
    'sixgr:truth:InvalidDataScoringWaveform','The executed desired-link samples must be finite.');
fs=double(prepared.SampleRateHz);
first=double(op.AppliedTimingCorrection_samples);
validateattributes(first,{'numeric'},{'scalar','real','finite','integer','>=',0,'<',size(wave,1)});
absolute=(observation.StartSample:observation.EndSampleExclusive-1).';
aligned=observation.StartSample+first;
phase=-2*pi/fs*(double(op.CaptureOriginCFOCorrection_Hz).* ...
    (absolute-prepared.ReceiveStartSample)+double(op.AlignedOriginCFOCorrection_Hz).*(absolute-aligned));
wave=wave.*cast(exp(1i*phase),'like',wave);
B=double(op.ReceiveCombiningMatrix);
assert(size(B,1)==size(wave,2) && all(isfinite(B),'all'), ...
    'sixgr:truth:InvalidDataScoringReceiveCombiner', ...
    'The scoring waveform must use the executed receive spatial projection.');
wave=wave*cast(conj(B),'like',wave);
wave=wave(first+1:end,:);
[referenceRxGrid,ofdm]=sixgr.phy.waveform.ofdmDemodulate(snapshot.Carrier,wave);
shape=double(snapshot.GridShape);
assert(size(referenceRxGrid,1)==shape(1) && size(referenceRxGrid,2)>=shape(2) && ...
    size(referenceRxGrid,3)==shape(3), ...
    'sixgr:truth:DataScoringOFDMClockMismatch', ...
    'The independently scored waveform must reproduce the receiver FFT grid.');
referenceRxGrid=referenceRxGrid(:,1:shape(2),:);
channelModel=string(sixgr.util.structGet(prepared.InputConfig,'channel.model','AWGN'));
[grid,~,info]=sixgr.phy.rx.channelEstimate(snapshot.Carrier,referenceRxGrid, ...
    snapshot.PilotIndices,snapshot.PilotSymbols,'UseFastMex',false, ...
    'StrictMode',true,'ChannelModel',channelModel, ...
    'ExpectedTxPorts',shape(4),'Method',"LS", ...
    'ContextLabel',channel+"_post_decode_scoring_reference");
assert(isequal([size(grid,1) size(grid,2) size(grid,3) size(grid,4)],shape) && ...
    all(isfinite(grid),'all'), ...
    'sixgr:truth:IncompleteDataScoringChannelReference', ...
    'The noiseless pilot estimator must retain every effective port and receive branch.');
evidence=struct('Source',"same_executed_desired_link_waveform_post_decode_"+channel+"_DMRS_LS", ...
    'ReferencePlane',"effective_"+channel+"_layer_channel_from_actual_tx_RF_channel_loss_before_noise_rx_RF", ...
    'AppliedChannelSource',"actual_executed_link_contribution", ...
    'RFImpairmentsIncluded',true,'ReceiverEstimatorInput',false, ...
    'GainOrPhaseFitted',false,'AdditionalChannelExecutions',0,'AdditionalRFExecutions',0, ...
    'TimingOffsetRelativeReceiveWindow_samples',first, ...
    'ReceiveCombiningMatrix',B,'ScoringEvidence',scoringEvidence, ...
    'ScoringOFDMInfo',ofdm,'ScoringEstimatorInfo',info, ...
    'ReferenceScope',"receiver_retained_DMRS_resources_from_same_executed_noiseless_link_IQ");
end
