function validateCalibrationSources(data,matPath)
% Verify retained source identity; qualification is not inferred from a filename.
assert(isfield(data,'Sources') && istable(data.Sources) && ...
    all(ismember(["Role","RelativePath","SHA256","ExecutionBackend"],string(data.Sources.Properties.VariableNames))), ...
    'sixgr:abstraction:CalibrationSources','Calibration must identify retained waveform fit and independent validation sources.');
T=data.Sources;
if string(sixgr.util.structGet(data,'SourceClassification',''))=="executed_waveform_calibration"
    assert(~any(contains(lower(string(T.ExecutionBackend)),["fixture","test_only","development"])), ...
        'sixgr:abstraction:CalibrationSources','Development/contract fixtures cannot qualify a production calibration.');
end
assert(all(ismember(["fit","validation"],string(T.Role))) && ...
    all(contains(lower(string(T.ExecutionBackend)),"waveform")) && ...
    ~any(contains(lower(string(T.ExecutionBackend)),["proxy","synthetic","fallback"])), ...
    'sixgr:abstraction:CalibrationSources','Both fit and held-out evidence must come from waveform execution.');
digests=strings(height(T),1);
records=cell(height(T),1);
for k=1:height(T)
    path=fullfile(fileparts(matPath),char(T.RelativePath(k)));
    assert(isfile(path),'sixgr:abstraction:CalibrationSources','Missing waveform source %s.',path);
    digests(k)=sixgr.csi.studyFileSHA256(path);
    assert(strcmpi(digests(k),string(T.SHA256(k))), ...
        'sixgr:abstraction:CalibrationDigest','Retained waveform source changed.');
    assert(any(string(T.Role(k))==["fit","validation"]), ...
        'sixgr:abstraction:CalibrationSources','Unknown calibration source role.');
    raw=readtable(path,'TextType','string','VariableNamingRule','preserve');
    required=["CurveID","GridPointIndex","TrialID","AttemptIndex","CRCError", ...
        "PriorAttemptsFailed","WaveformExecuted","CalibrationKeySHA256"];
    assert(~isempty(raw) && all(ismember(required,string(raw.Properties.VariableNames))), ...
        'sixgr:abstraction:CalibrationRawSchema','Retain identifiable waveform trials, not only summary counts.');
    production=string(sixgr.util.structGet(data,'SourceClassification',''))=="executed_waveform_calibration";
    if production
        proof=["EpisodePath","EpisodeSHA256","EpisodeID","CampaignIdentity", ...
            "CaseID","TransportBlockSHA256","NoiseSeed","ChannelSeed"];
        assert(all(ismember(proof,string(raw.Properties.VariableNames))), ...
            'sixgr:abstraction:CalibrationRawSchema', ...
            'Production source rows must identify checksum-protected decoded waveform episodes.');
        raw=raw(:,[required proof]);
        localVerifyEpisodeRows(raw,fileparts(matPath),string(T.Role(k)),data.Curves);
    else
        raw=raw(:,required);
    end
    assert(all(ismember(double(raw.CRCError),[0 1])) && ...
        all(double(raw.WaveformExecuted)==1) && ...
        all(strlength(strtrim(string(raw.TrialID)))>0), ...
        'sixgr:abstraction:CalibrationRawSchema','Conditional calibration must use executed attempts following only earlier failures.');
    raw.Role=repmat(string(T.Role(k)),height(raw),1); records{k}=raw;
end
assert(isempty(intersect(digests(string(T.Role)=="fit"),digests(string(T.Role)=="validation"))), ...
    'sixgr:abstraction:CalibrationSources','Fit and validation cannot reuse the same retained artifact.');
raw=vertcat(records{:});
identity=string(raw.CurveID)+"|"+string(raw.TrialID);
assert(numel(unique(identity))==height(raw), ...
    'sixgr:abstraction:CalibrationPopulation','Repeated trials or shared fit/validation trial identities.');
assert(all(ismember(string(raw.CurveID),string({data.Curves.CurveID}))), ...
    'sixgr:abstraction:CalibrationPopulation','Source rows reference an unknown curve.');
for ci=1:numel(data.Curves)
    curve=data.Curves(ci);
    keySHA=string(sixgr.util.sha256Hex(uint8(unicode2native(jsonencode(curve.Key),'UTF-8'))));
    rows=raw(string(raw.CurveID)==string(curve.CurveID),:);
    expectedAttempt=numel(curve.RVSequence);
    assert(all(double(rows.AttemptIndex)==expectedAttempt) && ...
        all(logical(rows.PriorAttemptsFailed)==(expectedAttempt>1)), ...
        'sixgr:abstraction:CalibrationRawSchema', ...
        'First attempts have no prior failure; retransmissions require a preceding failed attempt.');
    assert(all(strcmpi(string(rows.CalibrationKeySHA256),keySHA)), ...
        'sixgr:abstraction:CalibrationPopulation','Raw waveform physical key differs from its curve.');
    n=numel(curve.TrialCount);
    for role=["fit","validation"]
        r=rows(rows.Role==role,:); index=double(r.GridPointIndex);
        assert(~isempty(r) && all(isfinite(index)) && all(index==fix(index)) && all(index>=1 & index<=n), ...
            'sixgr:abstraction:CalibrationPopulation','Invalid or missing trial populations per SINR-history grid.');
        counts=accumarray(index,1,[n 1]); errors=accumarray(index,double(r.CRCError),[n 1]);
        expectedN=curve.TrialCount; expectedE=curve.ErrorCount;
        if role=="validation", expectedN=curve.ValidationTrialCount; expectedE=curve.ValidationErrorCount; end
        assert(isequal(counts,double(expectedN(:))) && isequal(errors,double(expectedE(:))), ...
            'sixgr:abstraction:CalibrationPopulation','Curve counts must reproduce the retained independent waveform trial populations exactly.');
    end
end
end

function localVerifyEpisodeRows(raw,folder,sourceRole,curves)
meta=fullfile(folder,'campaign.mat');
assert(isfile(meta),'sixgr:abstraction:CalibrationSources', ...
    'Production calibration must retain its frozen waveform campaign.');
m=load(meta,'identity','cases','p');
lastPath=""; lastHash=""; saved=struct();
for rowIndex=1:height(raw)
    r=raw(rowIndex,:);
    relative=string(r.EpisodePath);
    assert(startsWith(relative,"episodes/") || startsWith(relative,"episodes"+string(filesep)), ...
        'sixgr:abstraction:CalibrationSources','Episode proof must stay inside the retained campaign.');
    path=fullfile(folder,char(relative));
    episodeRoot=char(java.io.File(fullfile(folder,'episodes')).getCanonicalPath());
    canonical=char(java.io.File(path).getCanonicalPath());
    assert(startsWith(string(canonical),string(episodeRoot)+string(filesep)), ...
        'sixgr:abstraction:CalibrationSources','Episode proof escapes the retained campaign.');
    assert(isfile(path),'sixgr:abstraction:CalibrationSources','Missing physical episode %s.',path);
    if string(path)~=lastPath
        sixgr.calibration.verifyEpisodeFile(path);
        lastHash=sixgr.csi.studyFileSHA256(path);
        assert(strcmpi(lastHash,string(r.EpisodeSHA256)), ...
            'sixgr:abstraction:CalibrationDigest','Source episode changed after row export.');
        saved=load(path,'episode'); lastPath=string(path);
    end
    assert(strcmpi(lastHash,string(r.EpisodeSHA256)), ...
        'sixgr:abstraction:CalibrationDigest','Rows disagree on the episode checksum.');
    e=saved.episode; a=double(r.AttemptIndex);
    expectedRole="reference"; if sourceRole=="validation", expectedRole="reference_validation"; end
    assert(e.CampaignIdentity==m.identity && e.CampaignIdentity==string(r.CampaignIdentity) && ...
        e.Role==expectedRole && e.CaseID==string(r.CaseID) && ...
        any(string({m.cases.ID})==e.CaseID) && ...
        e.EpisodeID==string(r.EpisodeID) && a>=1 && a<=numel(e.Attempts) && ...
        string(r.TrialID)==e.EpisodeID+"_"+a, ...
        'sixgr:abstraction:CalibrationSources','Source row does not identify its executed waveform episode.');
    attempt=e.Attempts(a);
    curveIndex=find(string({curves.CurveID})==string(r.CurveID));
    assert(isscalar(curveIndex) && numel(curves(curveIndex).SINRAxes_dB)==a, ...
        'sixgr:abstraction:CalibrationRawSchema','Waveform attempt does not match the curve history.');
    axes=curves(curveIndex).SINRAxes_dB;
    caseIndex=find(string({m.cases.ID})==e.CaseID);
    cfg=m.cases(caseIndex).Config;
    link=lower(string(cfg.simulation.link)); x=cfg.(link);
    key=curves(curveIndex).Key;
    requiredKey={'Direction','Modulation','MCSTable','MCSIndex','TargetCodeRate', ...
        'Rank','TBSBits','SCS_kHz','ChannelProfile','TxPorts','RxPorts', ...
        'RFProfileID','ReceiverType'};
    equalizer=lower(string(cfg.receiver.equalizer));
    expectedReceiver="";
    if equalizer=="mmse", expectedReceiver="lmmse"; end
    if equalizer=="zf", expectedReceiver="zf"; end
    assert(all(isfield(key,requiredKey)) && ...
        string(key.Direction)==e.Direction && string(key.Modulation)==string(x.modulation) && ...
        string(key.MCSTable)==string(x.mcsTable) && double(key.MCSIndex)==double(x.mcsIndex) && ...
        double(key.TargetCodeRate)==double(x.targetCodeRate) && ...
        double(key.Rank)==double(x.numberLayers) && ...
        double(key.TBSBits)==double(e.Attempts(a).TBSBits) && ...
        double(key.SCS_kHz)==double(cfg.carrier.subcarrierSpacingKHz) && ...
        string(key.ChannelProfile)==string(m.p.target_channel.model) && ...
        double(key.TxPorts)==double(cfg.channel.txAntennas) && ...
        double(key.RxPorts)==double(cfg.channel.rxAntennas) && ...
        string(key.RFProfileID)=="ideal_rf_no_impairments" && ...
        strlength(expectedReceiver)>0 && string(key.ReceiverType)==expectedReceiver, ...
        'sixgr:abstraction:CalibrationKey', ...
        'The SLS curve key does not match decoded coding, ports, target channel, RF branch or equalizer.');
    digits=zeros(1,a); bases=zeros(1,a);
    for j=1:a
        bases(j)=numel(axes{j});
        match=find(double(axes{j}(:))==double(e.PlannedSNRHistory_dB(j)));
        assert(isscalar(match),'sixgr:abstraction:CalibrationRawSchema', ...
            'Waveform SNR history is absent from the retained reference grid.');
        digits(j)=match;
    end
    stride=[1 cumprod(bases(1:end-1))];
    expectedGrid=1+sum((digits-1).*stride);
    assert(double(r.GridPointIndex)==expectedGrid, ...
        'sixgr:abstraction:CalibrationRawSchema', ...
        'Grid index does not correspond to the physical waveform SNR history.');
    assert(logical(attempt.CRCError)==logical(r.CRCError) && ...
        logical(attempt.PriorAttemptsFailed)==logical(r.PriorAttemptsFailed) && ...
        logical(attempt.WaveformExecuted)==logical(r.WaveformExecuted) && ...
        attempt.TransportBlockSHA256==string(r.TransportBlockSHA256) && ...
        double(attempt.NoiseSeed)==double(r.NoiseSeed) && ...
        double(attempt.ChannelSeed)==double(r.ChannelSeed) && ...
        logical(e.RawTrials{a}.CRCError)==logical(r.CRCError), ...
        'sixgr:abstraction:CalibrationSources','Source row disagrees with the physical decoder episode.');
end
end
