function contract = figureContract()
%FIGURECONTRACT Exact 57-file joint ISAC raster contract.

tdoc = [ ...
"Fig01_integration_chain";"Fig02_bistatic_geometry";"Fig03_coherent_segments"; ...
"Fig04_event_models";"Fig05_timing_update_models"; ...
"Fig06_single_phase_velocity_rmse";"Fig07_single_phase_wrong_peak"; ...
"Fig08_periodic_phase_doppler_lines";"Fig09_periodic_phase_ghost_level"; ...
"Fig10_effective_pattern_collision_flow";"Fig11_configured_effective_patterns"; ...
"Fig12_pattern_pslr_p90";"Fig13_high_sidelobe_probability"; ...
"Fig14_beam_scope_split";"Fig15_best_beam_inclusion_vs_age"; ...
"Fig16_gain_gap_p90_vs_age";"Fig17_measurement_cost_fallback_vs_age"; ...
"Fig18_report_content";"Fig19_puncture_vs_relocation_segments"; ...
"Fig20_coherency_budget_flow";"Fig21_tdd_mask_doppler_response"; ...
"Fig22_tdd_pattern_benchmark_candidate";"Fig23_tdd_doppler_ambiguity"; ...
"Fig24_tdd_delay_ambiguity";"Fig25_velocity_rmse_event_classes"; ...
"Fig26_angle_rmse_event_classes";"Fig27_effective_pattern_derivation_report"; ...
"Fig28_wrong_peak_vs_assistance_window"];
waveform = [ ...
"WFig01_scope_and_baselines";"WFig02_delay_reference_and_cp_boundary"; ...
"WFig03_transmitter_receiver_chains";"WFig04_frame_anchored_q_and_reset"; ...
"WFig05_time_domain_boundary_continuity"; ...
"WFig06_range_doppler_maps_below_at_above_cp"; ...
"WFig07_rmse_pd_pfa_vs_delay_over_cp";"WFig08_papr_ccdf"; ...
"WFig09_psd_aclr_oobe";"WFig10_aperiodic_and_circular_af"; ...
"WFig11_cross_ambiguity_statistics";"WFig12_isi_ici_vs_delay_and_doppler"; ...
"WFig13_shared_resource_evm_bler_throughput"; ...
"WFig14_self_and_intercell_interference"; ...
"WFig15_puncture_robustness_absolute_vs_transmitted_counter"; ...
"WFig16_buffer_latency_complexity"];
joint = [ ...
"JFig01_waveform_pattern_collision_heatmap";"JFig02_budget_selected_action_map"; ...
"JFig03_beyond_cp_with_collision";"JFig04_tdd_sequence_interaction"; ...
"JFig05_pareto_sensing_communication_overhead";"JFig06_decision_summary"];
patent = [ ...
"PFig01_separate_vs_coupled_selection";"PFig02_puncture_vs_relocation"; ...
"PFig03_action_classification";"PFig04_segment_relation_graph"; ...
"PFig05_selection_flowchart";"PFig06_sequence_flow"; ...
"PFig07_system_architecture"];
contract = table([tdoc;waveform;joint;patent], ...
    [repmat("tdoc_10_8_2",numel(tdoc),1); ...
    repmat("tdoc_10_8_3",numel(waveform),1); ...
    repmat("joint",numel(joint),1); ...
    repmat("patent_support",numel(patent),1)], ...
    'VariableNames',{'FigureStem','Folder'});
end
