function evidence = runTR38901ReferenceEvidence(cfg,bundle)
%RUNTR38901REFERENCEEVIDENCE Execute one official TR 38.901 example channel.

% This is supplementary example evidence.  The primary controlled W0-W3
% comparison remains on the deterministic paired target channel so that
% channel realizations are identical across profiles.

backend=cfg.channel.tr38901Backend;
reference=sixgr.util.structGet(backend,"referenceExample",struct());
if ~logical(sixgr.util.structGet(reference,"enabled",false))
    error("sixgr:isac:TR38901ReferenceExampleDisabled", ...
        "channel.tr38901Backend.referenceExample.enabled must be true.");
end
tx=double(cfg.scene.nodes.trp1PositionM(:));
txOrientation=double(cfg.scene.nodes.trp1OrientationDeg(:));
mode=string(reference.sensingMode);
if contains(lower(mode),"monostatic")
    rx=tx; rxOrientation=txOrientation;
else
    rx=double(cfg.scene.nodes.trp2PositionM(:));
    rxOrientation=double(cfg.scene.nodes.trp2OrientationDeg(:));
end
targetCfg=cfg.scene.targets.(char(cfg.scene.activeTarget));
target=struct("PositionM",double(targetCfg.positionM(:)), ...
    "VelocityMps",double(targetCfg.velocityMps(:)), ...
    "OrientationDeg",double(targetCfg.orientationDeg(:)));
context=struct("SensingMode",mode, ...
    "CarrierFrequencyHz",double(bundle.CarrierProfile.frequencyHz), ...
    "SampleRateHz",double(bundle.OFDMInfo.SampleRate), ...
    "Seed",double(reference.seed),"TxPositionM",tx, ...
    "TxOrientationDeg",txOrientation,"RxPositionM",rx, ...
    "RxOrientationDeg",rxOrientation, ...
    "NumReceiveAntennas",double(reference.numReceiveAntennas), ...
    "Targets",target);
[received,metadata]=sixgr.isac.runTR38901ExampleChannel( ...
    cfg,bundle.SensingWaveform(:,1),context);

info=metadata.ChannelInfo;
pathParts=cell(numel(info.PathDelays),1);
backgroundLinks=1+2*contains(lower(mode),"monostatic");
for linkIndex=1:numel(info.PathDelays)
    delays=double(info.PathDelays{linkIndex}(:));
    gains=info.PathGains{linkIndex};
    gains=reshape(gains,size(gains,1),size(gains,2),[]);
    power=squeeze(mean(mean(abs(gains).^2,1),3)).';
    n=min(numel(delays),numel(power));
    component=repmat("target",n,1);
    if linkIndex<=backgroundLinks, component(:)="background"; end
    pathParts{linkIndex}=table(repmat(linkIndex,n,1),component,(1:n).', ...
        delays(1:n),power(1:n),10*log10(max(power(1:n),realmin)), ...
        'VariableNames',{'LinkIndex','Component','PathIndex','DelaySeconds', ...
        'MeanPathPowerLinear','MeanPathPowerDb'});
end
paths=vertcat(pathParts{:});
geometry=table("STX",tx(1),tx(2),tx(3), ...
    'VariableNames',{'Node','X_m','Y_m','Z_m'});
geometry=[geometry;table("SRX",rx(1),rx(2),rx(3), ...
    'VariableNames',geometry.Properties.VariableNames); ...
    table("Target",target.PositionM(1),target.PositionM(2),target.PositionM(3), ...
    'VariableNames',geometry.Properties.VariableNames)];
summary=table(string(metadata.ExampleId),string(metadata.Backend),mode, ...
    double(bundle.CarrierProfile.frequencyHz),double(bundle.OFDMInfo.SampleRate), ...
    numel(bundle.SensingWaveform),size(received,1),size(received,2),height(paths), ...
    string(bundle.SensingWaveformSHA256),string(metadata.ReceivedSHA256), ...
    string(metadata.HelperSHA256),string(metadata.EvidenceClass),false, ...
    'VariableNames',{'ExampleId','Backend','SensingMode','CenterFrequencyHz', ...
    'SampleRateHz','TransmitSamples','ReceivedSamples','ReceiveBranches', ...
    'PathRows','TransmitSHA256','ReceivedSHA256','HelperSHA256', ...
    'EvidenceClass','HardwareValidated'});
evidence=struct("Summary",summary,"Paths",paths,"Geometry",geometry, ...
    "ReceivedWaveform",received,"Metadata",metadata);
end
