function contract=validationFigureContract()
%VALIDATIONFIGURECONTRACT Exact WFig17-WFig36 10.8.3 contract.
stems=(17:36).'; names=[ ...
"linear_convolution_validation";"absolute_vs_transmitted_counter"; ...
"cross_symbol_coherence";"pd_fixed_pfa_vs_delay_cp"; ...
"range_rmse_vs_delay_cp";"doppler_rmse_vs_delay_cp"; ...
"wrong_peak_vs_delay_cp";"C0_minus_B1_incremental_benefit"; ...
"range_doppler_maps_B1_C0";"psd_aclr_oobe_numeric"; ...
"2D_ambiguity_profiles";"cross_correlation_distribution"; ...
"intercell_sensing_performance";"self_interference_sensing_performance"; ...
"pdsch_bler_vs_snr";"pdsch_goodput_vs_snr";"W3_puncture_robustness"; ...
"W3_relocation_coherency";"randomization_tradeoff"; ...
"buffer_latency_complexity"];
contract=table("WFig"+compose("%02d",stems)+"_"+names, ...
    repmat("mat_csv_fig_png_pdf",numel(stems),1), ...
    'VariableNames',{'FigureStem','RequiredFormats'});
end
