function assertMeasuredEqualizerWork(T)
% Actual receiver counters must survive the primary trial/CSV boundary.
names=["EqualizerSolveCount","EqualizerUniqueSolveCount", ...
    "EqualizerCovarianceFactorizationCount"];
assert(istable(T) && height(T)>0 && ...
    all(ismember(names,string(T.Properties.VariableNames))), ...
    'test:MissingEqualizerWorkExport','Actual data trials need executed equalizer counters.');
work=T{:,cellstr(names)};
assert(all(isnan(work) | (isfinite(work) & work>=0 & work==fix(work)),'all'));
measured=isfinite(work(:,1));
assert(any(measured) && all(all(isfinite(work(measured,:)),2)) && ...
    all(work(measured,2)<=work(measured,1)) && all(work(measured,1)>0), ...
    'test:MissingExecutedEqualizerWork','Data execution must retain nonzero solves and valid unique counts.');
assert(all(isnan(T.DetectorComplexityUnits_Modulation)), ...
    'test:DetectorGridProxyExport','Do not restore grid-size products as measured operation counts.');
path=[tempname '.csv']; cleanup=onCleanup(@()delete(path)); %#ok<NASGU>
writetable(T(:,cellstr(names)),path);
restored=readtable(path,'VariableNamingRule','preserve');
assert(isequaln(restored{:,cellstr(names)},work), ...
    'test:EqualizerWorkCSVChanged','CSV must preserve executed work, including unavailable counters.');
end
