function summary=summarizePUCCHDetectorCampaign(v,p,rows)
% Audit table only. Missing RF episodes count conservatively, not as rows.
seeds=validatePUCCHDetectorCampaignPolicy(v,p);
if ~isempty(rows)
    assert(all(ismember(rows.CaseID,string({p.cases.id}))) && ...
        all(isfinite(rows.CampaignEpisode) & rows.CampaignEpisode==fix(rows.CampaignEpisode) & ...
        rows.CampaignEpisode>=1 & rows.CampaignEpisode<=v.episodes), ...
        'test:CampaignRows','Unknown case or campaign episode.');
    assert(all(rows.Seed==reshape(seeds(rows.CampaignEpisode),[],1)), ...
        'test:CampaignRows','Physical row seed differs from the preregistered schedule.');
    assert(all(ismember(rows.EventError,[0 1])) && ...
        height(unique(rows(:,{'CampaignEpisode','CaseID'})))==height(rows), ...
        'test:CampaignRows','Invalid errors or duplicate physical cases.');
end
out=cell(numel(p.cases),1);
for k=1:numel(p.cases)
    caseID=string(p.cases(k).id); executed=0; errors=0;
    if ~isempty(rows)
        selected=rows.CaseID==caseID;
        executed=sum(selected); errors=sum(rows.EventError(selected));
    end
    unavailable=v.episodes-executed;
    upper=1;
    if errors+unavailable<v.episodes
        upper=betaincinv(1-v.family_alpha/numel(p.cases), ...
            errors+unavailable+1,v.episodes-errors-unavailable);
    end
    out{k}=struct('CaseID',caseID,'PlannedEpisodes',v.episodes, ...
        'ExecutedEpisodes',executed,'UnavailableEpisodes',unavailable, ...
        'ObservedEventErrors',errors,'ConservativeFailureUpperBound',upper, ...
        'EventErrorLimit',v.event_error_limit, ...
        'ConfidenceGatePassed',unavailable==0 && upper<=v.event_error_limit, ...
        'DetectorQualified',false,'Scope',"campaign_accounting_pending_independent_evidence_review");
end
summary=struct2table(vertcat(out{:}));
end
