function ok = testPUCCHFixedFormatValidation()
%TESTPUCCHFIXEDFORMATVALIDATION Guard strict typed-format PUCCH anchors.

setup6GRSimToolkit("Verbose", false);

bits = int8([1; 0; 1; 1]);
fixture = sixgr.phy.pucch.PUCCHFixtureFactory.connected(2, bits, ...
    "RNTI", 320);
valid = sixgr.link.runPUCCHWaveformTrial(fixture.Carrier, ...
    "Assignment", fixture.Assignment, ...
    "Report", fixture.Report, ...
    "ReceiverContext", fixture.Context, ...
    "Carrier", fixture.Carrier, ...
    "SNR_dB", 35, ...
    "Seed", 320);
assert(logical(valid.Ok) && double(valid.RequestedFormat) == 2 && ...
    double(valid.ResolvedFormat) == 2 && ~logical(valid.FormatAdapted) && ...
    logical(valid.ControlResourceValidity), ...
    "A valid fixed PUCCH format must execute without format mutation.");
assert(logical(valid.UCIContentMatch) && valid.BitErrors == 0 && ...
    valid.BitsCompared == numel(bits), ...
    "The typed PUCCH trial must expose bit-exact comparison evidence.");

threw = false;
try
    sixgr.phy.pucch.PUCCHFixtureFactory.connected(0, ...
        int8([1; 0; 1; 0]), "RNTI", 320);
catch ME
    threw = strcmp(string(ME.identifier), ...
        "sixgr:phy:pucch:InvalidFormatPayload");
end
assert(threw, ...
    "An incompatible format-0 payload must fail with InvalidFormatPayload.");

fixtureShort = sixgr.phy.pucch.PUCCHFixtureFactory.connected(0, ...
    int8(1), "RNTI", 320);
strict = sixgr.link.runPUCCHWaveformTrial(fixtureShort.Carrier, ...
    "Assignment", fixtureShort.Assignment, ...
    "Report", fixtureShort.Report, ...
    "ReceiverContext", fixtureShort.Context, ...
    "Carrier", fixtureShort.Carrier, ...
    "SNR_dB", 35, ...
    "Seed", 321);
assert(logical(strict.Ok) && strict.RequestedFormat == 0 && ...
    strict.ResolvedFormat == 0 && ~logical(strict.FormatAdapted), ...
    "Connected PUCCH must never silently promote a requested format.");

ok = true;
end
