function ok = testLLSFailClosedEmptyEvidenceGates()
%TESTLLSFAILCLOSEDEMPTYEVIDENCEGATES Required evidence cannot pass vacuously.

setup6GRSimToolkit("Verbose", false);

localMissingPDCCHBindingEvidenceFails();
localMissingKPIBindingEvidenceFails();
localMissingScenarioObjectiveEvidenceFails();
localZeroEffectiveScenarioObjectiveEvidenceFails();
localPersistedMIMOGateFailureReachesRootStatus();
localMissingRequiredMIMOArtifactFailsClosed();
localMissingRequiredArtifactAuditsFailClosed();

ok = true;
end

function localMissingRequiredArtifactAuditsFailClosed()
ctx = llsRootGateFixture("honest_study");
scfg = sixgr.util.structSet(ctx.ScenarioConfig, ...
    "validation.required_artifact_audit", true);
scfg = sixgr.util.structSet(scfg, ...
    "output.artifact_contract_engine.enabled", true);

dlT = readtable(fullfile(ctx.Layout.AirInterfaceCSVDir, "dl_pdsch_trials.csv"), ...
    "VariableNamingRule", "preserve");
ulT = readtable(fullfile(ctx.Layout.AirInterfaceCSVDir, "ul_pusch_trials.csv"), ...
    "VariableNamingRule", "preserve");
opSummary = sixgr.truth.summarizeEffectiveOperatingPoint(scfg, dlT, ulT);
verdict = struct("Failures", strings(0, 1), "CheckDetails", struct());
root = sixgr.truth.evaluateStrictAnchorStatus(ctx.RunFolder, scfg, ...
    ctx.InternalConfig, verdict, dlT, ulT, opSummary);

assert(~logical(root.Status.VisualArtifactGateOk) && ...
    string(root.Status.VisualArtifactGateStatus) == "NOT_EVALUATED", ...
    "A required visual audit must fail closed when its evidence files are absent.");
assert(~logical(root.Status.DuplicateArtifactGateOk) && ...
    string(root.Status.DuplicateArtifactGateStatus) == "NOT_EVALUATED", ...
    "An enabled contract engine must fail closed when its artifact-generation audit is absent.");
assert(~logical(root.Status.ResultOk) && ...
    contains(string(root.Status.StrictAnchorFailureReasons), "visual_artifact_gate_failed") && ...
    contains(string(root.Status.StrictAnchorFailureReasons), "duplicate_artifact_gate_failed"), ...
    "Missing terminal artifact audits must block canonical publication status.");
end

function localMissingRequiredMIMOArtifactFailsClosed()
ctx = llsRootGateFixture("honest_study");
cfg = sixgr.util.structSet(ctx.InternalConfig, "phy.pdsch.numLayers", 2);
cfg = sixgr.util.structSet(cfg, "phy.pusch.numLayers", 2);
dlT = readtable(fullfile(ctx.Layout.AirInterfaceCSVDir, ...
    "dl_pdsch_trials.csv"), "VariableNamingRule", "preserve");
ulT = readtable(fullfile(ctx.Layout.AirInterfaceCSVDir, ...
    "ul_pusch_trials.csv"), "VariableNamingRule", "preserve");
opSummary = sixgr.truth.summarizeEffectiveOperatingPoint( ...
    ctx.ScenarioConfig, dlT, ulT);
verdict = struct("Failures", strings(0, 1), "CheckDetails", struct());

root = sixgr.truth.evaluateStrictAnchorStatus(ctx.RunFolder, ...
    ctx.ScenarioConfig, cfg, verdict, dlT, ulT, opSummary);

assert(~logical(root.Status.ConfiguredEffectivePolicyOk) && ...
    any(contains(string(root.Failures), ...
    "mimo_four_gate_configured_effective_evidence_missing")), ...
    "A strict multi-layer run must not pass without its MIMO four-gate artifact.");
end

function localMissingScenarioObjectiveEvidenceFails()
ctx = llsRootGateFixture("honest_study");
dlT = readtable(fullfile(ctx.Layout.AirInterfaceCSVDir, "dl_pdsch_trials.csv"), ...
    "VariableNamingRule", "preserve");
ulT = readtable(fullfile(ctx.Layout.AirInterfaceCSVDir, "ul_pusch_trials.csv"), ...
    "VariableNamingRule", "preserve");
opSummary = sixgr.truth.summarizeEffectiveOperatingPoint(ctx.ScenarioConfig, dlT, ulT);
verdict = struct("Failures", strings(0, 1), "CheckDetails", struct());

root = sixgr.truth.evaluateStrictAnchorStatus(ctx.RunFolder, ctx.ScenarioConfig, ...
    ctx.InternalConfig, verdict, dlT, ulT, opSummary);

assert(~logical(root.Status.ScenarioObjectiveOk) && ...
    ~logical(root.Status.ScenarioObjectiveEvidenceAvailable) && ...
    string(root.Status.ScenarioObjectiveStatus) == "NOT_EVALUATED", ...
    "Missing strict scenario-objective detail must fail closed as NOT_EVALUATED.");
assert(any(contains(string(root.Failures), "scenario_objective_gate_not_evaluated")), ...
    "The root failure list must identify absent scenario-objective evidence.");
end

function localZeroEffectiveScenarioObjectiveEvidenceFails()
ctx = llsRootGateFixture("honest_study");
delete(fullfile(ctx.Layout.AirInterfaceCSVDir, "dl_pdsch_trials.csv"));
delete(fullfile(ctx.Layout.AirInterfaceCSVDir, "ul_pusch_trials.csv"));

verdict = sixgr.truth.evaluateLLSRuntimeTruthContract( ...
    ctx.RunFolder, ctx.ScenarioConfig, ctx.InternalConfig);
statusT = readtable(fullfile(ctx.Layout.ReportCSVDir, "result_status_summary.csv"), ...
    "VariableNamingRule", "preserve");

assert(~logical(statusT.ScenarioObjectiveOk(1)), ...
    "A strict fixed operating point with zero effective DL/UL rows must not pass its objective.");
assert(any(contains(string(verdict.Failures), ...
    "configured_effective_operating_point_evidence_missing")), ...
    "Zero effective rows must produce a typed scenario-objective evidence failure.");
end

function localPersistedMIMOGateFailureReachesRootStatus()
ctx = llsRootGateFixture("honest_study");
sixgr.util.ensureDir(fullfile(ctx.Layout.BeamformingCSVDir, ".keep"));
mimoT = table(["DL";"UL"], [true;false], [true;true], [true;true], ...
    [true;true], [true;false], ...
    'VariableNames', {'Direction','ScenarioObjectivePass','SpatialContractMatch', ...
    'FixedOperatingPointMatch','AdaptivePolicyConformance','MUExecutionMatch'});
sixgr.util.csvWriteTable(fullfile(ctx.Layout.BeamformingCSVDir, ...
    "mimo_configured_vs_effective.csv"), mimoT);

verdict = sixgr.truth.evaluateLLSRuntimeTruthContract( ...
    ctx.RunFolder, ctx.ScenarioConfig, ctx.InternalConfig);
statusT = readtable(fullfile(ctx.Layout.ReportCSVDir, "result_status_summary.csv"), ...
    "VariableNamingRule", "preserve");
assert(logical(statusT.ConfiguredEffectiveOk(1)), ...
    "A MIMO policy failure must not rewrite an independently measured exact operating-point match.");
assert(~logical(statusT.ConfiguredEffectivePolicyOk(1)) && ~logical(statusT.ResultOk(1)) && ...
    any(contains(string(verdict.Failures), "mimo_four_gate_configured_effective_evidence_failed")), ...
    "A persisted failing MIMO four-gate summary must force policy conformance and the canonical result to fail.");
end

function localMissingPDCCHBindingEvidenceFails()
ctx = llsRootGateFixture("honest_study");
scfg = sixgr.util.structSet(ctx.ScenarioConfig, "control_gating.pdcch_required", true);
cfg = sixgr.util.structSet(ctx.InternalConfig, "control_gating.pdcch_required", true);
delete(fullfile(ctx.Layout.AirInterfaceCSVDir, "dl_pdsch_trials.csv"));
delete(fullfile(ctx.Layout.AirInterfaceCSVDir, "ul_pusch_trials.csv"));

verdict = sixgr.truth.evaluateLLSRuntimeTruthContract(ctx.RunFolder, scfg, cfg);

statusT = readtable(fullfile(ctx.Layout.ReportCSVDir, "result_status_summary.csv"), ...
    "VariableNamingRule", "preserve");
bindingT = readtable(fullfile(ctx.Layout.ReportCSVDir, "pdcch_grant_binding_evidence.csv"), ...
    "VariableNamingRule", "preserve");
assert(height(bindingT) == 0, "Fixture must contain no PDCCH binding evidence for this guard.");
assert(~logical(statusT.PDCCHGrantBindingOk(1)), ...
    "Required PDCCH binding must fail when zero grants carry binding evidence.");
assert(any(contains(string(verdict.Failures), "missing_required_grant_binding_evidence")), ...
    "The empty-evidence failure must identify missing required PDCCH binding evidence.");
end

function localMissingKPIBindingEvidenceFails()
ctx = llsRootGateFixture("honest_study");
bindingPath = fullfile(ctx.Layout.ReportCSVDir, "kpi_objective_binding.csv");
delete(bindingPath);

sixgr.truth.evaluateLLSRuntimeTruthContract(ctx.RunFolder, ctx.ScenarioConfig, ctx.InternalConfig);

statusT = readtable(fullfile(ctx.Layout.ReportCSVDir, "result_status_summary.csv"), ...
    "VariableNamingRule", "preserve");
gateT = readtable(fullfile(ctx.Layout.ReportCSVDir, "kpi_consistency_gate.csv"), ...
    "VariableNamingRule", "preserve");
assert(~logical(statusT.KpiConsistencyOk(1)), ...
    "Strict KPI consistency must fail when objective-binding evidence is absent.");
assert(any(string(gateT.GateName) == "kpi_objective_binding_present" & ~logical(gateT.Pass)), ...
    "KPI gate must report the missing objective-binding artifact.");
assert(any(string(gateT.GateName) == "kpi_objective_binding_mandatory_rows" & ~logical(gateT.Pass)), ...
    "KPI gate must report the four missing mandatory objective rows.");
end
