function ok = testComponentSourceAuthorityClassification()
%TESTCOMPONENTSOURCEAUTHORITYCLASSIFICATION Audit requested component trees.

setup6GRSimToolkit("Verbose", false, "RunToolboxChecks", false);
root = fileparts(fileparts(mfilename("fullpath")));
runFolder = string(tempname);
mkdir(runFolder);
cleanup = onCleanup(@() localCleanup(runFolder)); %#ok<NASGU>

out = sixgr.analytics.buildPHYPackageExecutionAudit(runFolder, root);
T = out.DetailTable;
components = ["pucch","prach","pdcch","rrc","ra","waveform", ...
    "sync","pusch","pdsch","mimo","harq","mac","monitor", ...
    "l2","l3","ia","channel","csi","rach","protocol","rf"];
path = lower(replace(string(T.FilePath), "\", "/"));
selected = false(height(T), 1);
for component = components
    mask = contains(path, "/+" + component + "/");
    assert(any(mask), "Component package +%s has no inventoried MATLAB files.", ...
        component);
    selected = selected | mask;
end
scope = T(selected, :);
assert(height(scope) >= 773, ...
    "Named-folder audit unexpectedly covered only %d source files.", ...
    height(scope));
assert(all(strlength(scope.SourceRole) > 0) && ...
    all(strlength(scope.RuntimeEligibility) > 0) && ...
    all(strlength(scope.ScenarioInputPolicy) > 0), ...
    "Every component source requires an explicit architectural role.");
assert(~any(scope.DuplexAuthorityAssessment == ...
    "FAIL_LOCAL_DUPLEX_AUTHORITY_PARSE"), ...
    "A production component still parses a local duplex authority.");
assert(~any(scope.SameBasenameAssessment == "UNRESOLVED_DUPLICATE_NAME"), ...
    "A same-name component implementation has no explicit ownership disposition.");

tdoc = scope(contains(lower(scope.FilePath), "/+tdoc"), :);
assert(~isempty(tdoc) && all(tdoc.SourceRole == "tdoc_campaign") && ...
    all(tdoc.RuntimeEligibility == "ISOLATED_CAMPAIGN_ONLY"), ...
    "TDoc sources must remain isolated from production runtime defaults.");
csiStudy = scope(startsWith(lower(scope.FilePath), "+sixgr/+csi/"), :);
assert(~isempty(csiStudy) && all(csiStudy.SourceRole == "tdoc_campaign") && ...
    all(contains(csiStudy.StudyFileNamingAssessment, "PASS_")), ...
    "The legacy CSI TDoc namespace must remain explicitly study-named and isolated.");
c0Study = scope(contains(lower(scope.FilePath), "/+c0/+campaigns/"), :);
assert(~isempty(c0Study) && all(c0Study.SourceRole == "offline_study") && ...
    all(contains(c0Study.StudyFileNamingAssessment, "PASS_")), ...
    "Initial-access C0 study campaigns must not look like production entry points.");
isolated = scope(ismember(scope.SourceRole, ...
    ["tdoc_campaign","offline_study","offline_impact_analysis", ...
     "validation_campaign"]), :);
assert(~any(startsWith(isolated.StudyFileNamingAssessment, "FAIL_")), ...
    "An isolated study or validation file still has an ambiguous runtime-like name.");
impact = scope(contains(lower(scope.PrimaryFunctionOrClass), "impact"), :);
assert(~isempty(impact) && ...
    all(impact.SourceRole == "offline_impact_analysis"), ...
    "Impact-analysis sources must be classified as offline analysis.");

prachRuntime = T(T.QualifiedName == "sixgr.rach.runPRACHLLS", :);
assert(height(prachRuntime) == 1 && ...
    prachRuntime.SourceRole == "waveform_runtime_campaign" && ...
    prachRuntime.RuntimeLibraryCandidate, ...
    "The PRACH waveform campaign must remain runtime-capable and YAML-driven.");
zcdpeCampaign = T(T.QualifiedName == ...
    "sixgr.rach.runZCDPEValidationCampaign", :);
assert(height(zcdpeCampaign) == 1 && ...
    zcdpeCampaign.SourceRole == "validation_campaign" && ...
    zcdpeCampaign.RuntimeEligibility == "ISOLATED_VALIDATION_ONLY", ...
    "The fixed ZC-DPE vector matrix must remain validation-only.");

assert(isfile(out.SourceFileInventoryPath) && ...
    isfile(out.SourceFunctionInventoryPath) && ...
    isfile(out.StudyMeasurementRegistryPath), ...
    "The audit must emit reproducible file and function inventories.");
promotion = out.StudyMeasurementRegistryTable;
assert(height(promotion) >= 6 && ...
    ~any(promotion.StudyInputMaySupplyRuntimeDefaults) && ...
    all(promotion.RuntimePromotionPolicy == ...
        "measured_runtime_rows_only_no_study_vector_substitution"), ...
    "Study questions may be promoted only through measured runtime evidence.");
ok = true;
fprintf("[PASS] component authority: %d named-folder files, %d functions.\n", ...
    height(scope), height(out.FunctionTable));
end

function localCleanup(folder)
if isfolder(folder)
    rmdir(folder, "s");
end
end
