function ok = testLLSLinkAdaptationCQI0Policy()
%TESTLLSLINKADAPTATIONCQI0POLICY Separate scheduler blocking from PHY probes.

setup6GRSimToolkit("Verbose",false,"RunToolboxChecks",false);

[cfg, provenance] = sixgr.lls.loadConfig( ...
    "configs/lls/pdsch_awgn_link_adaptation_minus5_diagnostic.yaml");
assert(string(cfg.linkAdaptation.outOfRangeCQIPolicy) == ...
    "minimum_mcs_waveform_probe" && ...
    string(cfg.simulation.statisticalClass) == "diagnostic_only");

publicationProbe = cfg;
publicationProbe.simulation.statisticalClass = "publication_candidate";
localAssertError(@()sixgr.lls.validateConfig(publicationProbe), ...
    "sixgr:lls:DiagnosticCQIProbeForbidden");
badOLLA = cfg;
badOLLA.linkAdaptation.olla.targetBLER = 0.2;
localAssertError(@()sixgr.lls.validateConfig(badOLLA), ...
    "sixgr:lls:OLLATargetBLERStepMismatch");

blockCfg = cfg;
blockCfg.scenario.id = "pdsch_cqi0_block_regression";
blockCfg.simulation.snrDb = -30;
blockCfg.simulation.minTransportBlocks = 3;
blockCfg.simulation.minBlockErrors = 1;
blockCfg.simulation.maxTransportBlocks = 3;
blockCfg.linkAdaptation.initialMCSIndex = 0;
blockCfg.linkAdaptation.outOfRangeCQIPolicy = "block_scheduling";
blockCfg = sixgr.lls.validateConfig(blockCfg);
[summary, trials] = sixgr.lls.runLinkAdaptationSNRPoint( ...
    blockCfg,provenance.ConfigSHA256,1);

assert(height(trials) < blockCfg.simulation.maxTransportBlocks && ...
    logical(summary.TerminalSchedulingBlock) && ...
    string(summary.StoppingReason) == "cqi_zero_out_of_range_scheduling_block" && ...
    double(summary.OutOfRangeCQIFeedbackCount) >= 1, ...
    "Production CQI-0 policy must terminate new-data scheduling without fabricating a TB.");
assert(~any(trials.LinkAdaptationForcedWaveformProbe) && ...
    all(trials.LinkAdaptationSchedulingEligible) && ...
    all(trials.LinkAdaptationOutOfRangeCQIPolicy == "block_scheduling"), ...
    "Block policy must not leak a diagnostic minimum-MCS waveform probe into primary trials.");
assert(trials.OLLAUpdateSource(1) == "no_prior_ack_nack" && ...
    trials.OLLAFeedbackTrialIndex(1) == 0 && isnan(trials.OLLAFeedbackACK(1)), ...
    "The bootstrap trial must not claim a prior ACK/NACK OLLA update.");
assert(all(trials.OLLAStateAuthority == "receiver_harq_feedback_state") && ...
    isequal(double(trials.OLLAUpdateCount(:)), ...
        (0:height(trials)-1).'), ...
    "Standalone link adaptation must export one receiver-owned OLLA update per prior first transmission.");

probeCfg = blockCfg;
probeCfg.scenario.id = "pdsch_cqi0_diagnostic_probe_regression";
probeCfg.linkAdaptation.outOfRangeCQIPolicy = "minimum_mcs_waveform_probe";
probeCfg = sixgr.lls.validateConfig(probeCfg);
[probeSummary, probeTrials] = sixgr.lls.runLinkAdaptationSNRPoint( ...
    probeCfg,provenance.ConfigSHA256,1);
probeContract = sixgr.lls.truthContract(probeCfg,probeTrials);
[~, probeValid] = sixgr.lls.validateResults(probeCfg, ...
    struct2table(probeSummary),probeTrials,probeContract);
probeRows = logical(probeTrials.LinkAdaptationForcedWaveformProbe);
assert(probeValid && height(probeTrials) == probeCfg.simulation.maxTransportBlocks && ...
    any(probeRows) && ~any(probeTrials.LinkAdaptationSchedulingEligible(probeRows)) && ...
    all(probeTrials.LinkAdaptationDecisionClass(probeRows) == ...
        "diagnostic_minimum_mcs_outage_probe") && ...
    all(probeTrials.OLLAUpdateSource(2:end) == ...
        "decoded_transport_block_crc_after_configured_feedback_delay") && ...
    all(probeTrials.OLLAFeedbackTrialIndex(2:end) == ...
        probeTrials.TrialIndex(1:end-1)) && ...
    all(probeTrials.OLLAFeedbackACK(2:end) == ...
        double(~probeTrials.CRCError(1:end-1))) && ...
    all(probeTrials.OLLAStateAuthority == ...
        "receiver_harq_feedback_state") && ...
    isequal(double(probeTrials.OLLAUpdateCount(:)), ...
        (0:height(probeTrials)-1).') && ...
    logical(probeContract.DiagnosticLinkAdaptationProbeUsed) && ...
    ~logical(probeContract.SchedulerEligibleLinkAdaptationEvidence), ...
    "Diagnostic minimum-MCS probes must remain waveform truth but be excluded from scheduler evidence.");

ok = true;
end

function localAssertError(f,expectedIdentifier)
caught = "";
try
    f();
catch ME
    caught = string(ME.identifier);
end
assert(caught == string(expectedIdentifier), ...
    "Expected typed error %s, received %s.",expectedIdentifier,caught);
end
