function ok = testFRCStandardDownlinkFrame()
%TESTFRCSTANDARDDOWNLINKFRAME Execute the real 20-slot TS 38.101-4 grid.

setup6GRSimToolkit("Verbose", false, "RunToolboxChecks", false);
result = sixgr.conformance.runFRCPoint( ...
    "dl_r_pdsch_1_1_4_fdd_awgn", "awgn_static_1x2", ...
    "ValidateSetupOnly", true, ...
    "RequireExactStandardExecution", false, ...
    "RequireExactDataChannelExecution", true, ...
    "PrintTable", false, "Verbose", false);

frame = result.SetupValidation.StandardFrame;
assert(logical(frame.Materialized) && frame.PeriodSlots == 20);
assert(isequal(double(frame.FrameGridSize(1:2)), [624 280]));
assert(isequal(double(frame.WaveformSize), [307200 1]));
assert(frame.SampleRate_Hz == 15.36e6 && ...
    frame.SSBSampleRate_Hz == frame.SampleRate_Hz);
assert(strlength(string(frame.FrameGridSHA256)) == 64 && ...
    strlength(string(frame.FrameWaveformSHA256)) == 64 && ...
    strlength(string(frame.SSBGridSHA256)) == 64);

slots = frame.SlotTable;
assert(height(slots) == 20 && isequal(slots.Slot(:), (0:19).'));
assert(nnz(slots.HasSSB) == 1 && slots.HasSSB(1));
assert(nnz(slots.HasPDSCH) == 19 && ~slots.HasPDSCH(1));
assert(isequal(find(slots.HasTrackingCSIRS).'-1, [10 11]));
assert(nnz(slots.HasAcquisitionCSIRS) == 1 && ...
    slots.HasAcquisitionCSIRS(1));
assert(all(slots.PDCCHRE == 576) && all(slots.OCNGRE > 0));
assert(all(slots.TBSBits(2:end) == 8064));
assert(all(slots.GBits(2:10) == 13728) && ...
    all(slots.GBits(11:12) == 13104) && ...
    all(slots.GBits(13:end) == 13728));

slot0 = frame.AuxiliaryEvidence{1};
assert(slot0.PDCCH.Materialized && ...
    slot0.PDCCH.AggregationLevel == 8 && ...
    slot0.PDCCH.CandidateCount == 1 && ...
    slot0.PDCCH.CORESETPRBs == 48 && ...
    isequal(slot0.PDCCH.ControlSymbols, [0 1]));
assert(slot0.PDCCH.DCIFormat == "1_1" && ...
    slot0.PDCCH.DCIPayloadSource == ...
        "finalized_scheduler_grant_dci_bits" && ...
    slot0.PDCCH.DCIContextDerived && ...
    slot0.PDCCH.DCIEncodeParseRoundTrip && ...
    strlength(slot0.PDCCH.DCIContextDigest) == 64 && ...
    strlength(slot0.PDCCH.DCIPayloadHash) == 64 && ...
    slot0.PDCCH.ScheduledPRBStart == 0 && ...
    slot0.PDCCH.ScheduledNumPRB == 52 && ...
    slot0.PDCCH.ScheduledSymbolStart == 2 && ...
    slot0.PDCCH.ScheduledNumSymbols == 12 && ...
    slot0.PDCCH.ScheduledMCS == 14 && ...
    slot0.PDCCH.ScheduledLayers == 1);
assert(slot0.AcquisitionCSIRS.Materialized && ...
    slot0.AcquisitionCSIRS.NZPRow == 2 && ...
    slot0.AcquisitionCSIRS.NZPPorts == 1 && ...
    slot0.AcquisitionCSIRS.NZPCDMGroupSize == 1 && ...
    slot0.AcquisitionCSIRS.NZPEPRERelativeToSSS_dB == 0 && ...
    slot0.AcquisitionCSIRS.ZPRow == 5 && ...
    slot0.AcquisitionCSIRS.ZPPorts == 4);
assert(slot0.OCNG.Materialized && ...
    slot0.OCNG.ControlRegionRE > 0 && ...
    slot0.OCNG.DataRegionRE > 0);

blockers = string(result.StandardExecution.Blockers);
assert(result.StandardExecution.Exact && isempty(blockers));
assert(~any(blockers == "pdcch_every_pdsch_slot_missing") && ...
    ~any(blockers == "op1_unused_re_waveform_missing") && ...
    ~any(blockers == "pdcch_dci_1_1_context_payload_not_materialized"));
ok = true;
end
