function ok = testMultiUserWaveformRuntimeAuthority()
%TESTMULTIUSERWAVEFORMRUNTIMEAUTHORITY Verify YAML survives into PHY runtime.

setup6GRSimToolkit("Verbose", false);
scenarioPath = fullfile(pwd, "simulator", "configs", "scenarios", ...
    "lls_mimo4x4_multiuser_beamformed_awgn_validation.yaml");
scenario = sixgr.lls6g.config.loadScenarioConfig(scenarioPath);
cfg = sixgr.lls6g.buildInternalConfig(scenario, tempdir);

assert(string(sixgr.util.structGet(cfg, ...
    "run.noiseOperatingMode", "")) == "standalone_awgn_snr_argument", ...
    "The AWGN multi-user validation scenario inherited thermal-noise authority.");
assert(string(sixgr.util.structGet(cfg, ...
    "phy.linkAdaptation.ulSRSToPUSCHLayerSINRPolicy", "")) == ...
    "minimum_layer_mean_post_equalization", ...
    "The SRS-to-PUSCH scheduler policy is not owned by resolved YAML.");
assert(double(sixgr.util.structGet(cfg, ...
    "phy.mimo.measurementMaxAgeSlots", NaN)) == 8, ...
    "Non-strict runtime discarded the YAML spatial-measurement age limit.");
assert(double(sixgr.util.structGet(cfg, ...
    "phy.mimo.precoderPRGSizeRBs", NaN)) == 106, ...
    "Non-strict runtime discarded the YAML precoder PRG authority.");
assert(logical(sixgr.util.structGet(cfg, ...
    "phy.mimo.ulSRSAuthority.enabled", false)), ...
    "Non-strict runtime discarded measured UL-SRS spatial authority.");
assert(double(sixgr.util.structGet(cfg, ...
    "phy.mimo.ulSRSAuthority.maxAgeSlots", NaN)) == 8);
assert(logical(sixgr.util.structGet(cfg, ...
    "phy.mimo.ulSRSAuthority.configuredOverrideForbidden", false)));
assert(double(sixgr.util.structGet(cfg, ...
    "phy.mimo.covariance.minSamples", NaN)) == 16);
assert(double(sixgr.util.structGet(cfg, ...
    "phy.mimo.covariance.maxAgeSlots", NaN)) == 8);
assert(abs(double(sixgr.util.structGet(cfg, ...
    "phy.mimo.covariance.shrinkageFactor", NaN)) - 0.05) < eps);
assert(string(sixgr.util.structGet(cfg, ...
    "phy.pusch.singleUserEqualizer", "")) == "MMSE", ...
    "The YAML-owned single-user UL equalizer was not preserved.");
assert(string(sixgr.util.structGet(cfg, ...
    "phy.pusch.muMIMOEqualizer", "")) == "IRC", ...
    "The YAML-owned UL MU-MIMO equalizer was not preserved.");
assert(string(sixgr.util.structGet(cfg, ...
    "phy.equalization.ircCovarianceEstimation", "")) == ...
    "per_prb_symbol_contribution_sample_covariance", ...
    "The YAML-owned local IRC covariance estimator was not preserved.");
assert(double(sixgr.util.structGet(cfg, ...
    "phy.equalization.ircCovarianceFrequencyWindowPRBs", NaN)) == 1);
assert(double(sixgr.util.structGet(cfg, ...
    "phy.equalization.ircCovarianceTimeWindowSymbols", NaN)) == 1);
assert(abs(double(sixgr.util.structGet(cfg, ...
    "phy.equalization.ircCovarianceShrinkageFactor", NaN)) - 0.05) < eps);
assert(double(sixgr.util.structGet(cfg, ...
    "phy.equalization.ircCovarianceMinimumSamples", NaN)) == 4);

assert(logical(sixgr.util.structGet(cfg, ...
    "rf.frontend.ul_power_control.enabled", false)));
assert(logical(sixgr.util.structGet(cfg, ...
    "rf.frontend.ul_power_control.open_loop_enabled", false)));
assert(~logical(sixgr.util.structGet(cfg, ...
    "rf.frontend.ul_power_control.closed_loop_enabled", true)));
assert(double(sixgr.util.structGet(cfg, ...
    "rf.frontend.configuration_epoch", NaN)) == 1);

srs = sixgr.util.structGet(cfg, ...
    "rf.frontend.ul_power_control.srs", struct());
required = [double(sixgr.util.structGet(srs, "p0_dbm", NaN)), ...
    double(sixgr.util.structGet(srs, "alpha", NaN)), ...
    double(sixgr.util.structGet(srs, "delta_tf_db", NaN)), ...
    double(sixgr.util.structGet(srs, "pcmax_dbm", NaN))];
assert(all(isfinite(required)) && isequal(required, [-80 0.8 0 23]), ...
    "SRS power-control authority was lost or altered during YAML normalization.");

assert(logical(sixgr.util.structGet(cfg, ...
    "phy.pucch.detectPUCCHPUSCHOverlap", false)));
assert(logical(sixgr.util.structGet(cfg, ...
    "phy.pucch.uciOnPUSCHEnabled", false)));
assert(string(sixgr.util.structGet(cfg, ...
    "phy.pucch.unsupportedOverlapPolicy", "")) == ...
    "reject_before_waveform");

assert(string(sixgr.util.structGet(cfg, "phy.duplex.mode", "")) == "FDD");
assert(string(sixgr.util.structGet(cfg, "phy.mimo.reciprocityMode", "")) == "fdd");

gatePath = fullfile(pwd, "simulator", "configs", "scenarios", ...
    "lls_mimo4x4_multiuser_beamformed_cdl_d_fdd_8slot_gate.yaml");
gateScenario = sixgr.lls6g.config.loadScenarioConfig(gatePath);
gateCfg = sixgr.lls6g.buildInternalConfig(gateScenario, tempdir);
assert(logical(sixgr.util.structGet(gateCfg, ...
    "outputs.phySignalDiagnosticEnabled", false)), ...
    "The exact FDD gate must persist same-trial waveform/channel diagnostics.");
assert(logical(sixgr.util.structGet(gateCfg, ...
    "outputs.phySignalDiagnosticCaptureReady", false)), ...
    "The exact FDD gate requested diagnostics without all capture prerequisites.");
assert(logical(sixgr.util.structGet(gateCfg, ...
    "outputs.saveRawWaveforms", false)) && ...
    logical(sixgr.util.structGet(gateCfg, ...
    "outputs.saveChannelSnapshots", false)) && ...
    logical(sixgr.util.structGet(gateCfg, ...
    "outputs.saveConstellations", false)) && ...
    logical(sixgr.util.structGet(gateCfg, "outputs.savePNG", false)), ...
    "The exact FDD gate cannot publish runtime PNGs without their raw sources.");

ok = true;
end
