function ok = testMsg1PRACHWaveformDetection()
cfg = raStrictAnchorConfig();
ra = sixgr.mac.ra.RAConfig(cfg, "RunId", "test_msg1");
[tx, occasion] = sixgr.phy.ra.generateMsg1PRACHWaveform(cfg, ra);
det = sixgr.phy.ra.detectMsg1PRACH(tx.Waveform, cfg, ra, occasion);
ta = sixgr.phy.ra.estimateTimingAdvanceFromPRACH(det,tx.SampleRate_Hz,ra.CarrierSCSkHz);
assert(logical(det.Detected), "MSG1 PRACH must be detected from waveform.");
assert(double(det.DetectedPreambleIndex) == double(ra.PreambleIndex), "Detected RAPID must match transmitted preamble.");
assert(isfinite(double(ta.TimingAdvanceCommand)), "Timing advance command must be derived from PRACH timing evidence.");
assert(logical(det.PropagationTimingEstimateValid) && ...
    isfinite(double(det.PropagationTimingOffsetSamples)), ...
    "MSG1 receiver must expose a finite propagation-relative timing estimate.");
expected = sixgr.phy.ra.resolveRARTimingAdvance(ta.TimingAdvanceCommand, ...
    ra.CarrierSCSkHz,tx.SampleRate_Hz);
assert(ta.Valid && ta.TimingAdvanceSamples==expected.Samples && ...
    abs(ta.QuantizationResidualSamples)<=0.5*ta.StepSamples+1e-10, ...
    "Timing advance must quantize the measured delay to a legal RAR step at the actual sample clock.");
occasionRARNTI = sixgr.phy.ra.computeRARNTIFromOccasion(occasion);
assert(double(ra.RARNTI) == double(occasionRARNTI) && ...
        double(tx.RARNTI) == double(occasionRARNTI), ...
    "MAC, Msg1 TX, and the materialized PRACH occasion must share one TS 38.321 RA-RNTI.");
assert(double(ra.PRACHOccasionOrdinal) == double(occasion.Ordinal), ...
    "Msg1 TX must use the exact canonical PRACH occasion selected by RAConfig.");
ok = true;
end
