function ok=testH4100BoundedRuntimePathGainCapture()
%TESTH4100BOUNDEDRUNTIMEPATHGAINCAPTURE Keep 64-element CDL evidence finite.

setup6GRSimToolkit("Verbose",false);
root=string(tempname)+"_h4_bounded_path_gain";
cleanup=onCleanup(@()localCleanup(root)); %#ok<NASGU>
scenario=sixgr.lls6g.config.loadScenarioConfig(fullfile( ...
    "simulator","configs","scenarios", ...
    "h4_100_cdlc100_connected_impaired_40db_gate.yaml"));
cfg=sixgr.lls6g.buildInternalConfig(scenario,root);
assert(cfg.channel.runtimeElementExpansionChunkSamples==512, ...
    "The H4 64-TXRU channel must use the bounded exact stream partition from YAML.");
cfg=sixgr.util.structSet(cfg,"outputs.continuousRawIQCaptureEnabled",false);
cfg=sixgr.util.structSet(cfg,"run.rootRunFolder",root);
multi=struct("Enabled",true,"NumUsers",1,"RNTIStart",1, ...
    "ExecutionModel","slot_coupled_truth");
state=sixgr.truth.CoupledTruthRuntime.initialize( ...
    cfg,root,multi,struct(),1);
state.CurrentSlot=1;
state.CurrentServingIdx(:)=1;
[state,stream]=sixgr.truth.CoupledWaveformStream.initialize( ...
    state,cfg,{cfg});
[state,~]=stream.advanceSlot(state,cfg); %#ok<ASGLU>

trace=stream.Events.ExecutionTrace;
assert(numel(trace)==1, ...
    "The full-DL H4 slot must retain one exact physical stream interval.");
link=trace{1}.Execution.Links;
assert(isscalar(link) && ...
    link.Replay.RuntimeChannelPathGainCaptureRequested && ...
    link.Replay.RuntimeChannelPathGainCaptureSatisfied && ...
    link.Replay.RuntimeChannelElementExpansionChunkSamples==512 && ...
    link.Replay.ChannelPathGainsAvailable && ...
    string(link.Replay.RuntimeChannelPathGainCaptureScope)== ...
        "first_executed_sample_exact_bounded_diagnostic" && ...
    startsWith(string(link.Replay.RuntimeChannelPathGainDimensions),"1x") && ...
    link.Replay.RuntimeChannelPathGainPreviewElementCount<=4096 && ...
    strlength(string(link.Replay.RuntimeChannelPathGainsSHA256))==64, ...
    "H4 automatic channel evidence must retain one exact executed CDL temporal slice without allocating a full-slot 64-element tensor.");
carrier=sixgr.phy.grid.makeCarrier(cfg);
expectedEnd=sixgr.phy.frame.slotStartSample( ...
    carrier,1,stream.SampleRateHz);
assert(stream.Events.NextSampleIndex==expectedEnd && ...
    stream.channelState(1,"DL").CurrentSampleIndex==expectedEnd, ...
    "Bounded evidence must not shorten or duplicate the authoritative channel advance.");

ok=true;
disp("H4_100_BOUNDED_RUNTIME_PATH_GAIN_CAPTURE_PASS");
end

function localCleanup(pathValue)
if isfolder(pathValue)
    rmdir(pathValue,"s");
end
end
