function ok = testFixedLinkMasterYAMLAuthority()
%TESTFIXEDLINKMASTERYAMLAUTHORITY Fixed-sweep YAML must own the real PHY run.

setup6GRSimToolkit("Verbose", false);

repoRoot = fileparts(fileparts(mfilename("fullpath")));
masterPath = fullfile(repoRoot, "simulator", "configs", "scenarios", ...
    "master_sinr_sweep.yaml");
scfg = sixgr.lls6g.config.loadScenarioConfig(masterPath);
resolved = scfg.toStruct();

runFolder = tempname;
mkdir(runFolder);
cleanupObj = onCleanup(@() localCleanup(runFolder)); %#ok<NASGU>
cfg = sixgr.lls6g.buildInternalConfig(scfg, runFolder);
campaign = resolved.validation.fixed_link_campaign;

assert(string(campaign.configuration_authority) == "master_yaml", ...
    "The fixed sweep must explicitly select master_yaml authority.");
assert(max(double(campaign.snr_db(:))) >= 24, ...
    ["The MCS-20/256QAM fixed-link grid must reach the measured AWGN " ...
    "pass region instead of ending at the former all-fail 10 dB ceiling."]);
smokeCampaign = resolved.execution_scales.smoke.overlay.validation.fixed_link_campaign;
assert(max(double(smokeCampaign.snr_db(:))) >= 24 && ...
    double(smokeCampaign.min_tb_per_point) >= 40 && ...
    double(smokeCampaign.max_tb_per_point) >= 40 && ...
    double(smokeCampaign.trials_per_drop) >= 40, ...
    ["The smoke sweep must include a measured high-SNR pass point and " ...
    "enough one-look trials to make the 0.1 confidence-width gate " ...
    "statistically attainable."]);
assert(isequal(double(cfg.validation.fixed_link_campaign.snr_db), ...
    double(campaign.snr_db(:).')), ...
    "The builder must preserve every configured campaign SNR point.");
assert(isequal(double(cfg.validation.fixed_link_campaign.mcs), ...
    double(campaign.mcs(:).')), ...
    "The builder must preserve every configured campaign MCS point.");
assert(double(cfg.validation.fixed_link_campaign.confidence_level) == ...
    double(campaign.confidence_level), ...
    "The configured confidence level must survive translation.");
assert(double(cfg.validation.fixed_link_campaign.trials_per_drop) == ...
    double(campaign.trials_per_drop), ...
    "The configured trials-per-drop budget must survive translation.");
assert(isequal(double(cfg.validation.fixed_link_campaign.seeds), ...
    double(campaign.seeds(:).')), ...
    "The configured campaign seeds must survive translation.");

localAssertCarrierAndAllocation(cfg, resolved, "dl", "pdsch");
localAssertCarrierAndAllocation(cfg, resolved, "ul", "pusch");
assert(double(cfg.phy.pdsch.nLayers) == double(campaign.layers) && ...
    double(cfg.phy.pusch.nLayers) == double(campaign.layers), ...
    "DL and UL layer counts must come from the master configuration.");
assert(double(cfg.phy.pdsch.dmrs.nPorts) == ...
    double(resolved.reference_signals.pdsch_dmrs_ports) && ...
    double(cfg.phy.pusch.dmrs.nPorts) == ...
    double(resolved.reference_signals.pusch_dmrs_ports), ...
    "DL and UL DM-RS port counts must come from the master configuration.");
assert(logical(cfg.phy.pdsch.enablePTRS) == ...
    logical(campaign.enable_ptrs) && ...
    logical(cfg.phy.pusch.enablePTRS) == ...
    logical(campaign.enable_ptrs), ...
    "PTRS enablement must agree across the master and both PHY chains.");
assert(logical(cfg.phy.harq.enable) == logical(campaign.harq_enabled) && ...
    logical(cfg.mac.harq.enable) == logical(campaign.harq_enabled), ...
    "HARQ enablement must agree across the master and runtime aliases.");
assert(upper(string(cfg.channel.model)) == ...
    upper(string(campaign.channel_model)), ...
    "The fixed-link channel family must come from the master configuration.");
assert(string(cfg.phy.pdsch.executionProfile) == ...
    string(campaign.pdsch_execution_profile), ...
    "The DL execution profile must come from the master configuration.");
assert(~logical(cfg.phy.pusch.measurements.decisionDirectedPostEqSINRBoundEnabled), ...
    "The calibration master must explicitly select the equalizer/H-estimate " + ...
    "post-equalization SINR measurement without the optional " + ...
    "decision-directed residual bound.");

missingConfidence = resolved;
missingConfidence.validation.fixed_link_campaign = rmfield( ...
    missingConfidence.validation.fixed_link_campaign, "confidence_level");
localAssertError(@() sixgr.lls6g.config.validateScenarioConfig( ...
    missingConfidence, "Kind", "scenario", "AllowPartial", false, ...
    "Context", "missing fixed-link confidence"), ...
    "sixgr:lls6g:config:FixedLinkMasterFieldMissing");

conflictingAllocation = resolved;
conflictingAllocation.pdsch.num_prb = ...
    double(conflictingAllocation.pdsch.num_prb) - 1;
localAssertError(@() sixgr.lls6g.config.validateScenarioConfig( ...
    conflictingAllocation, "Kind", "scenario", "AllowPartial", false, ...
    "Context", "conflicting fixed-link PRB count"), ...
    "sixgr:lls6g:config:FixedLinkMasterPRBCountConflict");

% Execute one real DL and one real UL transport block. The deliberately
% non-default confidence, SNR, MCS, and stopping budget must appear in the
% output, proving the production campaign does not rebuild them from
% legacy MATLAB defaults.
focused = resolved;
focusedCampaign = focused.validation.fixed_link_campaign;
focusedCampaign.direction = "both";
focusedCampaign.snr_db = 30.25;
focusedCampaign.mcs = 7;
focusedCampaign.min_tb_per_point = 1;
focusedCampaign.max_tb_per_point = 1;
focusedCampaign.min_errors_for_ci = 0;
focusedCampaign.max_ci_half_width = 1;
focusedCampaign.confidence_level = 0.90;
focusedCampaign.trials_per_drop = 1;
focusedCampaign.seeds = 8675309;
focused.validation.fixed_link_campaign = focusedCampaign;
% PRBSet is BWP-relative. A nonzero carrier offset must not make the valid
% relative allocation [0,49] look out of range.
focused.bwp.dl.n_start_bwp = 96;
focused.bwp.dl.n_size_bwp = 100;
focused.bwp.ul.n_start_bwp = 96;
focused.bwp.ul.n_size_bwp = 100;
sixgr.lls6g.config.validateScenarioConfig(focused, ...
    "Kind", "scenario", "AllowPartial", false, ...
    "Context", "focused fixed-link master fixture");
focusedConfig = sixgr.lls6g.config.ScenarioConfig(focused, ...
    "ConfigPath", masterPath, "Kind", "scenario");
focusedInternal = sixgr.lls6g.buildInternalConfig( ...
    focusedConfig, runFolder);
assert(double(focusedInternal.phy.bwp.dl.NStartBWP) == 96 && ...
    isequal(double(focusedInternal.phy.pdsch.PRBSet), 0:49), ...
    "PDSCH PRBSet must remain BWP-relative for a nonzero BWP start.");
assert(double(focusedInternal.phy.bwp.ul.NStartBWP) == 96 && ...
    isequal(double(focusedInternal.phy.pusch.PRBSet), 0:49), ...
    "PUSCH PRBSet must remain BWP-relative for a nonzero BWP start.");
out = sixgr.lls6g.campaign.runFixedLinkCampaign( ...
    focusedInternal, "WriteArtifacts", false);

assert(out.PointCount == 1 && height(out.DLTrials) == 1 && ...
    height(out.ULTrials) == 1, ...
    "The focused master fixture must execute one real DL and UL trial.");
assert(double(out.Summary.SNR_dB(1)) == 30.25 && ...
    double(out.Summary.MCSIndex(1)) == 7, ...
    "Fractional SNR and selected MCS must reach the campaign unchanged.");
assert(double(out.Summary.ConfidenceLevel(1)) == 0.90 && ...
    double(out.Summary.TrialsPerDrop(1)) == 1, ...
    "Confidence and stopping budget must reach campaign reporting unchanged.");
assert(string(out.Summary.DL_BLER_CI_Method(1)) == "wilson_90pct" && ...
    string(out.Summary.UL_BLER_CI_Method(1)) == "wilson_90pct", ...
    "Configured confidence must drive both DL and UL Wilson intervals.");
localAssertTrialAuthority(out.DLTrials, 30.25, 7, 0.90, ...
    focusedInternal, "DL");
localAssertTrialAuthority(out.ULTrials, 30.25, 7, 0.90, ...
    focusedInternal, "UL");
assert(~any(contains(string(out.ULTrials.PostEqSINRSource), ...
    "decision_directed_symbol_residual")), ...
    "The fixed-sweep YAML measurement policy must reach the production " + ...
    "PUSCH receiver; the optional decision-directed bound remained active.");

fprintf("%s\n", char("Fixed-link master authority: carrier/BWP/PRB/MCS/" + ...
    "rank/DMRS/PTRS/HARQ/channel/SNR/stopping/seeds verified; " + ...
    "1 DL + 1 UL production trial executed."));
ok = true;
end

function localAssertCarrierAndAllocation(cfg, resolved, direction, section)
direction = char(string(direction));
section = char(string(section));
bwp = resolved.bwp.(direction);
internalBWP = cfg.phy.bwp.(direction);
assert(double(internalBWP.NStartBWP) == double(bwp.n_start_bwp) && ...
    double(internalBWP.NSizeBWP) == double(bwp.n_size_bwp), ...
    "%s BWP start/size must come from the master configuration.", ...
    upper(direction));
configured = resolved.(section);
expectedPRBSet = double(configured.prb_start) + ...
    (0:(double(configured.num_prb) - 1));
actualPRBSet = double(cfg.phy.(section).PRBSet);
assert(isequal(actualPRBSet(:).', expectedPRBSet), ...
    "%s PRB allocation must come from the master configuration.", ...
    upper(section));
assert(isequal(double(cfg.phy.(section).SymbolAllocation), ...
    [double(configured.start_symbol), double(configured.num_symbols)]), ...
    "%s symbol allocation must come from the master configuration.", ...
    upper(section));
assert(all(actualPRBSet >= 0) && ...
    all(actualPRBSet < double(bwp.n_size_bwp)), ...
    "%s PRB allocation must stay inside its configured active BWP.", ...
    upper(section));
end

function localAssertTrialAuthority(T, expectedSNR, expectedMCS, ...
        expectedConfidence, cfg, direction)
direction = char(string(direction));
assert(all(double(T.ConfiguredSNR_dB) == expectedSNR) && ...
    all(double(T.SNR_dB) == expectedSNR), ...
    "%s trial rows must preserve the configured fractional SNR.", direction);
assert(all(double(T.FixedLinkConfiguredMCS) == expectedMCS) && ...
    all(double(T.MCS) == expectedMCS), ...
    "%s trial rows must preserve the configured MCS.", direction);
assert(all(double(T.FixedLinkConfidenceLevel) == expectedConfidence), ...
    "%s trial rows must preserve the configured confidence level.", ...
    direction);
assert(all(double(T.FixedLinkConfiguredRank) == 1) && ...
    all(double(T.FixedLinkConfiguredLayers) == 1) && ...
    all(double(T.FixedLinkConfiguredPRBCount) == 50), ...
    "%s trial rows must preserve rank/layers/PRB configuration.", direction);
if direction == "DL"
    profile = sixgr.pdsch.PDSCHMCSResolver.resolve( ...
        string(cfg.phy.pdsch.mcsTable), expectedMCS, ...
        cfg.phy.pdsch.mcsContext);
else
    profile = sixgr.link.resolveMCSProfile( ...
        string(cfg.phy.pusch.mcsTable), expectedMCS);
end
assert(all(upper(string(T.Modulation)) == ...
    upper(string(profile.Modulation))), ...
    "%s modulation must be re-resolved from the selected MCS.", direction);
end

function localAssertError(fcn, expectedIdentifier)
threw = false;
try
    fcn();
catch ME
    threw = true;
    assert(string(ME.identifier) == string(expectedIdentifier), ...
        "Expected %s, received %s: %s", ...
        expectedIdentifier, ME.identifier, ME.message);
end
assert(threw, "Expected error %s was not thrown.", expectedIdentifier);
end

function localCleanup(folder)
if isfolder(folder)
    rmdir(folder, "s");
end
end
