function ok = testSIB1PhysicalElementTDLCausalRecovery()
%TESTSIB1PHYSICALELEMENTTDLCAUSALRECOVERY Non-centred SSB over real 2x2 TDL.

setup6GRSimToolkit("Verbose", false);
root = fileparts(fileparts(mfilename("fullpath")));
scenarioPath = fullfile(root, "simulator", "configs", "scenarios", ...
    "lls_causal_access_to_data_wiring.yaml");
scfg = sixgr.lls6g.config.loadScenarioConfig(scenarioPath);
cfg = sixgr.lls6g.buildInternalConfig(scfg, fullfile(tempdir, ...
    "sixgr_sib1_physical_element_tdl_causal_recovery"));

out = sixgr.link.runCellSearch_MIB_SIB1(cfg, ...
    "NumSubframes", 5, "UseRuntimeChannel", true, "RuntimeSlot", 0);

assert(logical(out.RuntimeChannelStateUsed), ...
    "The physical-element regression must traverse the runtime TDL channel.");
assert(logical(out.Ok) && logical(out.PBCH.Ok), ...
    "Physical-element TDL initial access must pass PBCH and strict SIB1.");
assert(double(out.Sync.NCellID) == double(cfg.phy.carrier.NCellID), ...
    "Blind PSS/SSS recovery selected the wrong physical cell ID.");
assert(abs(double(out.FreqOffsetEstimate_Hz)) <= 1e-6, ...
    "Point-A SSB placement must not be mislabeled as oscillator CFO.");
assert(logical(out.SIB1.DCICrcPass) && logical(out.SIB1.DLSCHCrcPass), ...
    "MIB-derived Type-0 DCI and SIB1 DL-SCH must pass on the same capture.");
assert(logical(out.SIB1.SIB1TreeEqual), ...
    "Decoded SIB1 ASN.1 semantics must equal the transmitted tree.");

assert(abs(double(out.SIB1.SSBCenterFrequencyOffsetHz) + 360e3) <= 1e-6);
assert(abs(double(out.SIB1.SSBPlacementCorrectionAppliedHz) - 360e3) <= 1e-6);

fprintf(["Physical-element TDL SIB1: cell=%d beam=%d CFO=%.3f Hz " + ...
    "PBCH/DCI/DLSCH/tree=PASS.\n"], double(out.Sync.NCellID), ...
    double(out.SSBIndex), double(out.FreqOffsetEstimate_Hz));
ok = true;
end
