function ok = testGrantCacheLiveUCIAuthority()
%TESTGRANTCACHELIVEUCIAUTHORITY Reject replay of occasion-local HARQ-ACK.

cached = struct( ...
    "GrantContextId", "ul-slot-5-original", ...
    "TBSBits", 9224, ...
    "CodeBlockLayoutHash", "immutable-layout", ...
    "ExpectedUCIBits", int8(1), ...
    "MultiplexedHARQACKBits", int8(1), ...
    "UCIOnPUSCHApplied", true, ...
    "UCIOnPUSCHFeedbackGrantIds", "pucch-due-5", ...
    "UCIOnPUSCHFeedbackSourceSlots", 4, ...
    "UCIOnPUSCHFeedbackHARQIds", 0, ...
    "UCIOnPUSCHFeedbackBitCount", 1, ...
    "UCIOnPUSCHEvidenceSource", "slot_5_runtime");

live = struct( ...
    "GrantContextId", "ul-slot-7-retransmission", ...
    "Frame", 1, "Slot", 7, "UEIndex", 1, ...
    "TBSBits", 9224, ...
    "ExpectedUCIBits", int8(0), ...
    "MultiplexedHARQACKBits", int8(0), ...
    "UCIOnPUSCHApplied", true, ...
    "UCIOnPUSCHFeedbackGrantIds", "pucch-due-7", ...
    "UCIOnPUSCHFeedbackSourceSlots", 6, ...
    "UCIOnPUSCHFeedbackHARQIds", 0, ...
    "UCIOnPUSCHFeedbackBitCount", 1, ...
    "UCIOnPUSCHEvidenceSource", "slot_7_runtime");

merged = sixgr.truth.mergeCachedGrantWithLiveRuntime(cached, live);
assert(merged.TBSBits == cached.TBSBits && ...
    string(merged.CodeBlockLayoutHash) == "immutable-layout", ...
    "Immutable HARQ/TB cache authority must be retained.");
assert(isequal(merged.ExpectedUCIBits, int8(0)) && ...
    string(merged.UCIOnPUSCHFeedbackGrantIds) == "pucch-due-7" && ...
    isequal(merged.UCIOnPUSCHFeedbackSourceSlots, 6) && ...
    string(merged.UCIOnPUSCHEvidenceSource) == "slot_7_runtime", ...
    "The current UL occasion must replace every cached UCI binding.");

liveNoUCI = rmfield(live, ["ExpectedUCIBits", ...
    "MultiplexedHARQACKBits", "UCIOnPUSCHApplied", ...
    "UCIOnPUSCHFeedbackGrantIds", ...
    "UCIOnPUSCHFeedbackSourceSlots", ...
    "UCIOnPUSCHFeedbackHARQIds", ...
    "UCIOnPUSCHFeedbackBitCount", "UCIOnPUSCHEvidenceSource"]);
cleared = sixgr.truth.mergeCachedGrantWithLiveRuntime(cached, liveNoUCI);
assert(isempty(cleared.ExpectedUCIBits) && ...
    ~logical(cleared.UCIOnPUSCHApplied) && ...
    strlength(string(cleared.UCIOnPUSCHFeedbackGrantIds)) == 0 && ...
    isempty(cleared.UCIOnPUSCHFeedbackSourceSlots), ...
    "An occasion without UCI must clear stale cached feedback fields.");

ok = true;
fprintf("testGrantCacheLiveUCIAuthority: PASS\n");
end
