function tests = testInitialAccessRAPhaseCore
%TESTINITIALACCESSRAPHASECORE Independent RA arithmetic regression floor.
tests = functiontests(localfunctions);
end

function testRARNTIArithmetic(testCase)
root = localVectorRoot();
input = readtable(fullfile(root, "ra_rnti_test_vectors.csv"), ...
    "TextType", "string", "VariableNamingRule", "preserve");
expectedPath = fullfile(root, "expected_ra_rnti.csv");
expectedOptions = delimitedTextImportOptions( ...
    "NumVariables", 4, ...
    "Delimiter", ",", ...
    "VariableNames", ...
        ["CaseID","ExpectedRARNTI","Formula","ExpectedStatus"], ...
    "VariableTypes", ["string","double","string","string"], ...
    "DataLines", [2 Inf]);
expected = readtable(expectedPath, expectedOptions);
verifyEqual(testCase, height(input), 128);
verifyEqual(testCase, input.CaseID, expected.CaseID);
for ii = 1:height(input)
    actual = sixgr.phy.ra.computeRARNTI( ...
        "SymbolIndex", double(input.s_id(ii)), ...
        "SlotIndex", double(input.t_id(ii)), ...
        "FrequencyIndex", double(input.f_id(ii)), ...
        "ULCarrierId", double(input.ul_carrier_id(ii)));
    verifyEqual(testCase, actual, double(expected.ExpectedRARNTI(ii)), ...
        sprintf("RA-RNTI vector %s mismatched.", input.CaseID(ii)));
end
localVerifyError(testCase, @() sixgr.phy.ra.computeRARNTI( ...
    "SymbolIndex", 14), ...
    "sixgr:phy:ia:InvalidRARNTICoordinates");
end

function testRAPreamblePowerControl(testCase)
root = localVectorRoot();
input = readtable(fullfile(root, ...
    "ra_power_ramping_test_vectors.csv"), ...
    "TextType", "string", "VariableNamingRule", "preserve");
expected = readtable(fullfile(root, ...
    "expected_ra_power_ramping.csv"), ...
    "TextType", "string", "VariableNamingRule", "preserve");
verifyEqual(testCase, height(input), 320);
verifyEqual(testCase, input.CaseID, expected.CaseID);
for ii = 1:height(input)
    actual = sixgr.phy.ia.RAPowerController.resolve( ...
        "PreambleReceivedTargetPowerdBm", ...
            double(input.PreambleReceivedTargetPower_dBm(ii)), ...
        "DeltaPreambledB", double(input.DeltaPreamble_dB(ii)), ...
        "PowerRampingStepdB", ...
            double(input.PowerRampingStep_dB(ii)), ...
        "PreamblePowerRampingCounter", ...
            double(input.PreamblePowerRampingCounter(ii)), ...
        "MeasuredPathlossdB", ...
            double(input.MeasuredPathloss_dB(ii)), ...
        "PCMAXdBm", double(input.PCMAX_dBm(ii)));
    verifyEqual(testCase, actual.PreambleTargetAtGNBdBm, ...
        double(expected.ExpectedPreambleTargetAtGNB_dBm(ii)));
    verifyEqual(testCase, actual.RequestedTxPowerdBm, ...
        double(expected.ExpectedRequestedTxPower_dBm(ii)));
    verifyEqual(testCase, actual.AppliedTxPowerdBm, ...
        double(expected.ExpectedAppliedTxPower_dBm(ii)));
    verifyEqual(testCase, actual.Clipped, ...
        localBool(expected.ExpectedClipped(ii)));
    verifyFalse(testCase, actual.ProxyUsed);
    verifyFalse(testCase, actual.FallbackUsed);
end
end

function testRATimerAndBackoff(testCase)
root = localVectorRoot();
input = readtable(fullfile(root, ...
    "ra_timer_backoff_test_vectors.csv"), ...
    "TextType", "string", "VariableNamingRule", "preserve");
expected = readtable(fullfile(root, ...
    "expected_ra_timer_backoff.csv"), ...
    "TextType", "string", "VariableNamingRule", "preserve");
verifyEqual(testCase, height(input), 96);
verifyEqual(testCase, input.CaseID, expected.CaseID);
for ii = 1:height(input)
    actual = sixgr.phy.ia.RATimingService.resolve( ...
        "NumerologyMu", double(input.Mu(ii)), ...
        "SlotDurationMs", double(input.SlotDuration_ms(ii)), ...
        "PRACHOccasionEndSlot", ...
            double(input.PRACHOccasionEndSlot(ii)), ...
        "RAResponseWindowSlots", ...
            double(input.RAResponseWindow_slots(ii)), ...
        "RARCompletionSlot", double(input.RARCompletionSlot(ii)), ...
        "Msg3CompletionSlot", double(input.Msg3CompletionSlot(ii)), ...
        "ContentionResolutionTimerMs", ...
            double(input.ContentionResolutionTimer_ms(ii)), ...
        "Msg4CompletionSlot", double(input.Msg4CompletionSlot(ii)), ...
        "BackoffIndicatorMs", ...
            double(input.BackoffIndicator_ms(ii)), ...
        "UniformDraw0to1", double(input.UniformDraw0to1(ii)));
    verifyEqual(testCase, actual.ResponseWindowStartSlot, ...
        double(expected.ExpectedResponseWindowStartSlot(ii)));
    verifyEqual(testCase, actual.ResponseWindowLastSlot, ...
        double(expected.ExpectedResponseWindowLastSlot(ii)));
    verifyEqual(testCase, actual.RARInsideWindow, ...
        localBool(expected.ExpectedRARInsideWindow(ii)));
    verifyEqual(testCase, actual.ContentionExpirySlotExclusive, ...
        double(expected.ExpectedContentionExpirySlotExclusive(ii)));
    verifyEqual(testCase, actual.ContentionResolved, ...
        localBool(expected.ExpectedContentionResolved(ii)));
    verifyEqual(testCase, actual.BackoffSlots, ...
        double(expected.ExpectedBackoffSlots(ii)));
    verifyEqual(testCase, actual.RestartEarliestSlot, ...
        double(expected.ExpectedRestartEarliestSlot(ii)));
end
end

function testSSBToROAssociationFloor(testCase)
root = localVectorRoot();
input = readtable(fullfile(root, ...
    "ssb_to_ro_association_test_vectors.csv"), ...
    "TextType", "string", "VariableNamingRule", "preserve");
expectedPath = fullfile(root, ...
    "expected_ssb_to_ro_association_floor.csv");
expectedOptions = detectImportOptions(expectedPath, ...
    "TextType", "string", "VariableNamingRule", "preserve");
expectedOptions = setvartype(expectedOptions, ...
    ["ExpectedROOrdinals0","Scope"], "string");
expected = readtable(expectedPath, expectedOptions);
verifyEqual(testCase, height(input), 120);
verifyEqual(testCase, input.CaseID, expected.CaseID);
for ii = 1:height(input)
    actual = sixgr.phy.ia.SSBToROAssociationEngine.resolve( ...
        "RatioName", input.RatioName(ii), ...
        "SSBsPerRONumerator", ...
            double(input.SSBsPerRONumerator(ii)), ...
        "SSBsPerRODenominator", ...
            double(input.SSBsPerRODenominator(ii)), ...
        "NumActiveSSBs", double(input.NumActiveSSBs(ii)), ...
        "SSBOrdinal0", double(input.SSBOrdinal0(ii)), ...
        "CBPreamblesPerSSB", ...
            double(input.CBPreamblesPerSSB(ii)), ...
        "AssociationPeriodROCount", ...
            double(input.AssociationPeriodROCount(ii)));
    verifyEqual(testCase, actual.ROOrdinalsText, ...
        expected.ExpectedROOrdinals0(ii));
    verifyEqual(testCase, actual.SSBPositionWithinRO0, ...
        double(expected.ExpectedSSBPositionWithinRO0(ii)));
    verifyEqual(testCase, actual.PreambleStart0, ...
        double(expected.ExpectedPreambleStart0(ii)));
    verifyEqual(testCase, actual.PreambleCount, ...
        double(expected.ExpectedPreambleCount(ii)));
    verifyEqual(testCase, actual.Scope, expected.Scope(ii));
    verifyEqual(testCase, actual.NormativeCompleteness, ...
        "bounded_floor_only");
end
end

function testRAConfigUsesConfiguredEventDelays(testCase)
cfg = raStrictAnchorConfig();
actual = sixgr.mac.ra.RAConfig(cfg);
verifyEqual(testCase, ...
    [actual.Msg2Slot, actual.Msg3Slot, actual.Msg4Slot, ...
    actual.SetupCompleteSlot], [1 2 3 4]);
verifyEqual(testCase, actual.TimingSchedule.Source, ...
    "configured_event_delays");

missing = cfg;
missing.random_access.timing = rmfield( ...
    missing.random_access.timing, "msg3_k2_slots");
localVerifyError(testCase, @() sixgr.mac.ra.RAConfig(missing), ...
    "sixgr:mac:ra:MissingMandatoryRACHFields");

shifted = cfg;
shifted.random_access.timing.msg3_k2_slots = 3;
shifted.random_access.timing.msg4_processing_delay_slots = 2;
resolved = sixgr.mac.ra.RAConfig(shifted);
verifyEqual(testCase, ...
    [resolved.Msg2Slot, resolved.Msg3Slot, resolved.Msg4Slot, ...
    resolved.SetupCompleteSlot], [1 4 6 7]);

outside = cfg;
outside.random_access.timing.rar_processing_delay_slots = ...
    outside.random_access.ra_response_window_slots + 1;
localVerifyError(testCase, @() sixgr.mac.ra.RAConfig(outside), ...
    "sixgr:phy:ia:RAROutsideResponseWindow");
end

function testRAConfigAcceptsAllNormativeRestrictedSets(testCase)
cfg = raStrictAnchorConfig();
sets = ["UnrestrictedSet","RestrictedSetTypeA","RestrictedSetTypeB"];
for ii = 1:numel(sets)
    candidate = cfg;
    candidate.random_access.restricted_set = sets(ii);
    actual = sixgr.mac.ra.RAConfig(candidate);
    verifyEqual(testCase, actual.RestrictedSetType, sets(ii));
end
invalid = cfg;
invalid.random_access.restricted_set = "RestrictedSetTypeC";
localVerifyError(testCase, @() sixgr.mac.ra.RAConfig(invalid), ...
    "sixgr:mac:ra:InvalidRestrictedSet");
end

function testCompleteRelease18FR1PRACHReferenceTables(testCase)
catalog = sixgr.phy.ia.PRACHReferenceCatalog.allFR1();
verifyEqual(testCase, height(catalog), 519);
verifyEqual(testCase, ...
    double(catalog.ConfigurationIndex( ...
    catalog.DuplexContext == "FR1_PAIRED_SUL")).', 0:255);
verifyEqual(testCase, ...
    double(catalog.ConfigurationIndex( ...
    catalog.DuplexContext == "FR1_UNPAIRED")).', 0:262);
report = sixgr.phy.ia.PRACHReferenceCatalog. ...
    validateAgainstToolbox();
verifyEqual(testCase, height(report), 519);
verifyEqual(testCase, sum(report.MismatchCount), 0);
verifyFalse(testCase, any(report.SelfConsistencyOnly));
verifyEqual(testCase, unique(report.Status), "PASS");
end

function testToolboxPeakDoesNotTreatCyclicShiftsAsAmbiguity(testCase)
% nrPRACHDetect reports a shared root-sequence correlation vector. Equal
% cyclic-shift peaks are not evidence that several preambles were decoded.
cfg = sixgr.rach.PRACHConfig(struct( ...
    "ScenarioName", "toolbox_peak_ambiguity_regression", ...
    "CarrierFrequencyHz", 700e6, ...
    "DuplexMode", "FDD", ...
    "NSizeGrid", 52, ...
    "PRACHConfigurationIndex", 16, ...
    "PRACHSubcarrierSpacing", 1.25, ...
    "PRACHFormat", "0", ...
    "ChannelModel", "AWGN"), ...
    "PreambleIndex", 7, ...
    "DetectionThresholdMode", "fixed", ...
    "DetectionThreshold", 0.02);
occasion = sixgr.rach.mapPRACHToOccasion(cfg, "OccasionIndex", 1);
tx = sixgr.rach.generatePRACHWaveform( ...
    cfg, "Occasion", occasion, "PreambleIndex", 7);
det = sixgr.rach.PRACHDetector(tx.Waveform, cfg, ...
    "Occasion", occasion, ...
    "CandidatePreambles", 0:63, ...
    "DetectorBackend", "toolbox_peak", ...
    "DetectionThresholdMode", "fixed", ...
    "DetectionThreshold", 0.02);

verifyTrue(testCase, logical(det.Detected));
verifyEqual(testCase, double(det.DetectedPreambleIndex), 7);
verifyEqual(testCase, double(det.CandidatesAboveThreshold), 1);
verifyFalse(testCase, logical(det.MultiCandidateAboveThreshold));
verifyEqual(testCase, ...
    double(det.DetInfo.DetectedPreambleIndicesRaw), 7);
end

function localVerifyError(testCase, call, expectedID)
try
    call();
    verifyFail(testCase, "Expected typed error was not raised.");
catch ME
    verifyEqual(testCase, string(ME.identifier), string(expectedID));
end
end

function value = localBool(token)
value = lower(strtrim(string(token))) == "true";
end

function root = localVectorRoot()
root = fullfile(fileparts(mfilename("fullpath")), ...
    "vectors", "initial_access");
end
