function ok = testCausalRuntimeAntennaPattern()
%TESTCAUSALRUNTIMEANTENNAPATTERN Verify YAML pattern reaches the CDL object.

setup6GRSimToolkit("Verbose", false);
root = fileparts(fileparts(mfilename("fullpath")));
scenarioPath = fullfile(root, "simulator", "configs", "scenarios", ...
    "lls_causal_access_to_data_wiring.yaml");
scfg = sixgr.lls6g.config.loadScenarioConfig(scenarioPath);
cfg = sixgr.lls6g.buildInternalConfig(scfg, fullfile(tempdir, ...
    "sixgr_causal_runtime_antenna_pattern"));

bs = sixgr.rf.AntennaArrayFactory.build(cfg, "bs", ...
    "signal", "pdsch", "numPorts", 2, "numRFChains", 2);
ue = sixgr.rf.AntennaArrayFactory.build(cfg, "ue", ...
    "signal", "pdsch", "numPorts", 2, "numRFChains", 2);
assert(isa(bs.ArrayObj, "phased.NRRectangularPanelArray") && ...
    isa(ue.ArrayObj, "phased.NRRectangularPanelArray"));
assert(isa(bs.ElementObj, "phased.NRAntennaElement") && ...
    isa(ue.ElementObj, "phased.NRAntennaElement"));
assert(isequal(double(bs.ElementObj.Beamwidth), [65 65]));
assert(isequal(double(bs.ElementObj.SidelobeLevel), [30 30]));
assert(double(bs.ElementObj.MaximumAttenuation) == 30);
assert(double(bs.ElementObj.MaximumGain) == 8);

bsMeta = localMeta(bs, "BS");
ueMeta = localMeta(ue, "UE");
[channel, meta] = sixgr.channel.ChannelFactory.create(cfg, ...
    "Model", "CDL", "LinkDirection", "DL", ...
    "SampleRate", 30.72e6, "NumTxAnt", 2, "NumRxAnt", 2, ...
    "Fc_Hz", 780e6, ...
    "TransmitAntennaRuntime", bs, "ReceiveAntennaRuntime", ue, ...
    "TransmitAntennaMeta", bsMeta, "ReceiveAntennaMeta", ueMeta);
cleanup = onCleanup(@() localRelease(channel)); %#ok<NASGU>
assert(isa(channel.Object, "nrCDLChannel"));
assert(isa(channel.Object.TransmitAntennaArray, ...
    "phased.NRRectangularPanelArray"));
assert(isa(channel.Object.ReceiveAntennaArray, ...
    "phased.NRRectangularPanelArray"));
assert(meta.RuntimeArrayGeometryCoupled && ...
    meta.ChannelUsesSameRuntimeAntennaAssumptions);
assert(meta.TransmitElementPatternApplied && ...
    meta.ReceiveElementPatternApplied);
assert(contains(meta.TransmitElementPatternSource, ...
    "AntennaArrayFactory") && contains(meta.ReceiveElementPatternSource, ...
    "AntennaArrayFactory"));

angleTable = sixgr.truth.buildChannelImpulseResponseTable(cfg, ...
    "Directions", ["DL","UL"], "SampleRate_Hz", 30.72e6);
angleColumns = ["AzimuthDeparture_deg","AzimuthArrival_deg", ...
    "ZenithDeparture_deg","ZenithArrival_deg", ...
    "TxArrayOrientationAzimuth_deg","RxArrayOrientationAzimuth_deg", ...
    "AngleCoordinateFrame","AngleStatus"];
assert(~isempty(angleTable) && all(ismember(angleColumns, ...
    string(angleTable.Properties.VariableNames))));
assert(all(isfinite(double(angleTable.AzimuthDeparture_deg))) && ...
    all(isfinite(double(angleTable.AzimuthArrival_deg))) && ...
    all(isfinite(double(angleTable.ZenithDeparture_deg))) && ...
    all(isfinite(double(angleTable.ZenithArrival_deg))));
assert(all(string(angleTable.AngleStatus) == ...
    "available_from_runtime_channel_info") && ...
    all(string(angleTable.AngleCoordinateFrame) == ...
    "3gpp_tr38901_global_coordinate_system"));
assert(all(ismember(["DL","UL"], unique(string(angleTable.Direction)))));

% Prove these are YAML authorities rather than constants hidden in the
% factory.  A second fully resolved configuration must produce different
% System-object properties and different CDL endpoint orientations.
variant = scfg.toStruct();
variant.antenna_and_array.bs_element_frequency_min_hz = 700e6;
variant.antenna_and_array.bs_element_frequency_max_hz = 900e6;
variant.antenna_and_array.bs_element_azimuth_hpbw_deg = 72;
variant.antenna_and_array.bs_element_elevation_hpbw_deg = 48;
variant.antenna_and_array.bs_element_azimuth_sidelobe_attenuation_db = 22;
variant.antenna_and_array.bs_element_elevation_sidelobe_attenuation_db = 27;
variant.antenna_and_array.bs_element_maximum_attenuation_db = 35;
variant.antenna_and_array.bs_element_maximum_gain_dbi = 11;
variant.antenna_and_array.bs_element_polarization_angles_deg = 12;
variant.antenna_and_array.bs_element_polarization_model = 1;
variant.antenna_and_array.bs_element_spacing_horizontal_lambda = 0.35;
variant.antenna_and_array.bs_element_spacing_vertical_lambda = 0.60;
variant.antenna_and_array.bs_boresight_azimuth_deg = 12;
variant.antenna_and_array.bs_boresight_elevation_deg = -3;
variant.antenna_and_array.bs_boresight_slant_deg = 5;
variant.antenna_and_array.ue_element_azimuth_hpbw_deg = 83;
variant.antenna_and_array.ue_element_elevation_hpbw_deg = 57;
variant.antenna_and_array.ue_element_azimuth_sidelobe_attenuation_db = 21;
variant.antenna_and_array.ue_element_elevation_sidelobe_attenuation_db = 24;
variant.antenna_and_array.ue_element_maximum_attenuation_db = 32;
variant.antenna_and_array.ue_element_maximum_gain_dbi = 6;
variant.antenna_and_array.ue_element_polarization_angles_deg = -18;
variant.antenna_and_array.ue_element_polarization_model = 2;
variant.antenna_and_array.ue_element_spacing_horizontal_lambda = 0.45;
variant.antenna_and_array.ue_element_spacing_vertical_lambda = 0.70;
variant.antenna_and_array.ue_boresight_azimuth_deg = -7;
variant.antenna_and_array.ue_boresight_elevation_deg = 4;
variant.antenna_and_array.ue_boresight_slant_deg = -6;
variantCfg = sixgr.lls6g.buildInternalConfig( ...
    sixgr.lls6g.config.ScenarioConfig(variant), ...
    fullfile(tempdir, "sixgr_causal_runtime_antenna_variant"));
variantBS = sixgr.rf.AntennaArrayFactory.build(variantCfg, "bs", ...
    "fc_Hz", 780e6, "signal", "pdsch", "numPorts", 2, "numRFChains", 2);
variantUE = sixgr.rf.AntennaArrayFactory.build(variantCfg, "ue", ...
    "fc_Hz", 780e6, "signal", "pdsch", "numPorts", 2, "numRFChains", 2);
assert(isequal(double(variantBS.ElementObj.FrequencyRange), [700e6 900e6]));
assert(isequal(double(variantBS.ElementObj.Beamwidth), [72 48]));
assert(isequal(double(variantBS.ElementObj.SidelobeLevel), [22 27]));
assert(double(variantBS.ElementObj.MaximumAttenuation) == 35);
assert(double(variantBS.ElementObj.MaximumGain) == 11);
assert(double(variantBS.ElementObj.PolarizationAngle) == 12);
assert(double(variantBS.ElementObj.PolarizationModel) == 1);
assert(max(abs(double(variantBS.ElementSpacing_lambda) - [0.35 0.60])) < 1e-12);
assert(max(abs(double(variantBS.ArrayObj.Spacing(1:2)) - ...
    variantBS.Lambda_m .* [0.60 0.35])) < 1e-12);
assert(isequal(double(variantUE.ElementObj.Beamwidth), [83 57]));
assert(isequal(double(variantUE.ElementObj.SidelobeLevel), [21 24]));
assert(double(variantUE.ElementObj.MaximumGain) == 6);
assert(double(variantUE.ElementObj.PolarizationAngle) == -18);
assert(max(abs(double(variantUE.ElementSpacing_lambda) - [0.45 0.70])) < 1e-12);
assert(max(abs(double(variantUE.ArrayObj.Spacing(1:2)) - ...
    variantUE.Lambda_m .* [0.70 0.45])) < 1e-12);
variantBSMeta = localMeta(variantBS, "BS");
variantUEMeta = localMeta(variantUE, "UE");
[variantChannel, variantMeta] = sixgr.channel.ChannelFactory.create(variantCfg, ...
    "Model", "CDL", "LinkDirection", "DL", ...
    "SampleRate", 30.72e6, "NumTxAnt", 2, "NumRxAnt", 2, ...
    "Fc_Hz", 780e6, ...
    "TransmitAntennaRuntime", variantBS, ...
    "ReceiveAntennaRuntime", variantUE, ...
    "TransmitAntennaMeta", variantBSMeta, ...
    "ReceiveAntennaMeta", variantUEMeta);
variantCleanup = onCleanup(@() localRelease(variantChannel)); %#ok<NASGU>
assert(isequal(double(variantMeta.TransmitArrayOrientation_deg(:).'), [12 3 5]));
assert(isequal(double(variantMeta.ReceiveArrayOrientation_deg(:).'), [-7 -4 -6]));

% Strict pattern coupling must fail closed when a required YAML authority
% is removed; it must never substitute the former 65/30/8 defaults.
missingGain = variant;
missingGain.antenna_and_array = rmfield( ...
    missingGain.antenna_and_array, "bs_element_maximum_gain_dbi");
localAssertError(@() sixgr.lls6g.buildInternalConfig( ...
    sixgr.lls6g.config.ScenarioConfig(missingGain), ...
    fullfile(tempdir, "sixgr_causal_runtime_antenna_missing_gain")), ...
    "sixgr:lls6g:config:MissingRequiredAntennaPatternField");

fprintf(['Causal runtime antenna: YAML 38.901 HPBW/sidelobe/gain pattern ' ...
    'and boresight reached both nrCDLChannel endpoints; AoD/AoA/ZoD/ZoA ' ...
    'were exported from the same resolved CDL profile.\n']);
ok = true;
end

function localAssertError(fcn, expectedIdentifier)
threw = false;
try
    fcn();
catch ME
    threw = true;
    assert(string(ME.identifier) == string(expectedIdentifier), ...
        "Unexpected error identifier: %s", string(ME.identifier));
end
assert(threw, "Expected error %s was not raised.", string(expectedIdentifier));
end

function meta = localMeta(arr, role)
meta = struct( ...
    "NodeType", role, "NodeIndex", 1, ...
    "NumRows", double(arr.Size(1)), ...
    "NumCols", double(arr.Size(2)), ...
    "NumPolarizations", double(arr.NPol), ...
    "PanelRows", double(arr.PanelRows), ...
    "PanelCols", double(arr.PanelCols), ...
    "NumElements", double(arr.NumElements), ...
    "NumPorts", double(arr.NumPorts), ...
    "NumWaveformColumns", double(arr.NumWaveformColumns), ...
    "NumRFChains", double(arr.NumRFChains), ...
    "WaveformDomain", string(arr.WaveformDomain), ...
    "PortCountSource", string(arr.PortCountSource), ...
    "SpacingH_lambda", double(arr.ElementSpacing_m(1) / arr.Lambda_m), ...
    "SpacingV_lambda", double(arr.ElementSpacing_m(2) / arr.Lambda_m), ...
    "Azimuth_deg", 0, "Heading_deg", 0, "Tilt_deg", 0, ...
    "BoresightAzimuth_deg", double(arr.BoresightAzElSlant_deg(1)), ...
    "BoresightElevation_deg", double(arr.BoresightAzElSlant_deg(2)), ...
    "BoresightSlant_deg", double(arr.BoresightAzElSlant_deg(3)), ...
    "HasPhasedArrayObject", true);
end

function localRelease(channel)
try
    if isstruct(channel) && isfield(channel, "Object") && ...
            ~isempty(channel.Object)
        release(channel.Object);
    end
catch
end
end
