function ok = testMultiBWPFrameGrid()
%TESTMULTIBWPFRAMEGRID Exact mixed-numerology BWP activation regression.

setup6GRSimToolkit("Verbose", false, "RunToolboxChecks", false);

carrierGrid = struct("NStartGrid", 0, "NSizeGrid", 273, ...
    "SubcarrierSpacingKHz", 30, "FrequencyRange", "FR1");
zero = sixgr.phy.frame.AbsoluteTime.fromTicks(0);
activation = sixgr.phy.frame.AbsoluteTime.fromFrameSlotSymbol( ...
    0, 4, 0, localNumerology(30));

dl0 = sixgr.phy.frame.BWPConfig(localBWP( ...
    "DL0", "DL", 30, 0, 273, true, zero, ...
    "DL0", "DL0"), carrierGrid);
dl1 = sixgr.phy.frame.BWPConfig(localBWP( ...
    "DL1", "DL", 60, 24, 100, false, activation, ...
    "DL1", "DL1"), carrierGrid);
ul0 = sixgr.phy.frame.BWPConfig(localBWP( ...
    "UL0", "UL", 30, 0, 200, true, zero, ...
    "DL0", "UL0"), carrierGrid);

cc = sixgr.phy.frame.ComponentCarrierConfig(localCarrier(), ...
    {dl0, dl1, ul0});
state = cc.BWPState;
assert(state.ActiveDLBWPID == "DL0" && state.ActiveULBWPID == "UL0", ...
    "DL and UL active BWP identities must be independent.");

issued = sixgr.phy.frame.AbsoluteTime.fromFrameSlotSymbol( ...
    0, 1, 0, dl0);
tooEarly = sixgr.phy.frame.AbsoluteTime.fromFrameSlotSymbol( ...
    0, 2, 0, dl0);
earlyDecision = state.scheduleSwitch("DL", "DL1", tooEarly, ...
    "IssuedTime", issued, ...
    "ControlBWPID", "DL0", ...
    "TriggerSource", "DCI", ...
    "CommandID", "switch-before-configured-time");
assert(~earlyDecision.Accepted && earlyDecision.ReasonCode == ...
    "activation_time_before_configured_time");
decision = state.scheduleSwitch("DL", "DL1", activation, ...
    "IssuedTime", issued, ...
    "ControlBWPID", "DL0", ...
    "TriggerSource", "DCI", ...
    "CommandID", "switch-dl-0-to-1");
assert(decision.Accepted && decision.ReasonCode == "switch_queued");

before = sixgr.phy.frame.AbsoluteTime.fromFrameSlotSymbol(0, 3, 0, dl0);
oldGrant = state.validateGrant(struct( ...
    "CCID", "CC0", "BWPID", "DL0", "Direction", "DL", ...
    "Time", before, "ControlBWPID", "DL0"));
earlyNewGrant = state.validateGrant(struct( ...
    "CCID", "CC0", "BWPID", "DL1", "Direction", "DL", ...
    "Time", before, "ControlBWPID", "DL1"));
assert(oldGrant.Allowed && ~earlyNewGrant.Allowed && ...
    earlyNewGrant.ReasonCode == "inactive_bwp", ...
    "A delayed switch must retain the old BWP before activation.");

after = sixgr.phy.frame.AbsoluteTime.fromFrameSlotSymbol(0, 5, 0, dl0);
newGrant = state.validateGrant(struct( ...
    "CCID", "CC0", "BWPID", "DL1", "Direction", "DL", ...
    "Time", after, "ControlBWPID", "DL1"));
lateOldGrant = state.validateGrant(struct( ...
    "CCID", "CC0", "BWPID", "DL0", "Direction", "DL", ...
    "Time", after, "ControlBWPID", "DL0"));
assert(newGrant.Allowed && ~lateOldGrant.Allowed && ...
    lateOldGrant.ReasonCode == "inactive_bwp");
assert(state.isActiveAt("UL0", "UL", after), ...
    "A DL BWP switch must not alter active UL BWP state.");

state.applyUntil(after);
assert(state.ActiveDLBWPID == "DL1" && state.ActiveULBWPID == "UL0");
history = state.historyTable();
assert(any(history.Event == "SWITCH_ACTIVATION" & ...
    history.ActiveBWPID == "DL1" & ...
    history.ReasonCode == "switch_activated"));

dimensions0 = dl0.resourceGridDimensions(2);
dimensions1 = dl1.resourceGridDimensions(2);
assert(isequal(dimensions0, [3276, 14, 2]));
assert(isequal(dimensions1, [1200, 14, 2]));
grid0 = cc.createResourceGrid("DL0", "DL", 1);
grid1 = cc.createResourceGrid("DL1", "DL", 1);
assert(isequal(size(grid0), [3276, 14]) && ...
    isequal(size(grid1), [1200, 14]), ...
    "Each BWP must retain its own resource-grid dimensions.");

[frame30, slot30, symbol30] = activation.toNumerology(dl0);
[frame60, slot60, symbol60] = activation.toNumerology(dl1);
assert(frame30 == 0 && slot30 == 4 && symbol30 == 0);
assert(frame60 == 0 && slot60 == 8 && symbol60 == 0, ...
    "30-to-60 kHz conversion must use exact time, not copied slot numbers.");

key0 = dl0.resourceKey("PDSCH", "grant-1");
key1 = dl1.resourceKey("PDSCH", "grant-1");
assert(key0 ~= key1 && contains(key0, "CC=CC0|BWP=DL0") && ...
    contains(key1, "CC=CC0|BWP=DL1"), ...
    "Resource keys must include carrier and BWP identity.");

cc.putHARQState("DL", 3, struct("Token", "preserved"));
[harqState, found] = cc.getHARQState("DL", 3);
assert(found && string(harqState.Token) == "preserved");
state.applyUntil(after.plusSlots(2, dl0));
[harqState, found] = cc.getHARQState("DL", 3);
assert(found && string(harqState.Token) == "preserved", ...
    "BWP switching must not discard the component-carrier HARQ namespace.");

% Replay the same semantic transition through the serializable production
% runtime context, then make the waveform-facing scheduler freeze a real
% grant.  This proves the active BWP is consumed outside the standalone
% state object by SchedulerPF -> TimingRelationEngine -> PHY grant freeze.
productionCfg = localProductionSwitchContext();
scheduled = sixgr.link.resolveWaveformGrant( ...
    productionCfg, "DL", 2, "Slot", 2, "HARQProcess", 3);
assert(scheduled.Valid && scheduled.TimingDecision.Valid);
assert(string(scheduled.SourceBWPID) == "1" && ...
    string(scheduled.TargetBWPID) == "1" && scheduled.BWPId == 1, ...
    "The production scheduler did not consume the activated DL BWP.");
assert(scheduled.ControlAbsoluteSlot == 2 && ...
    scheduled.ScheduledAbsoluteSlot == 3 && ...
    scheduled.K0 == 1 && scheduled.K1 == 2);
assert(string(scheduled.TimingDecision.Adapter) == ...
    "sixgr.phy.frame.TimingRelationEngine.resolveProductionGrant");
assert(isfield(scheduled, "PHYGrant") && ...
    scheduled.PHYGrant.IsFrozen && ...
    string(scheduled.PHYGrant.ContractVersion) == "PHYGrant/v1" && ...
    string(scheduled.PHYGrant.LegacyGrantSnapshot.Source) == ...
        "explicit_waveform_grant", ...
    "The waveform-facing path must freeze an executable explicit grant.");

invalid = localBWP("DL_BAD", "DL", 30, 250, 30, false, zero, ...
    "DL0", "DL_BAD");
localAssertError(@() sixgr.phy.frame.BWPConfig(invalid, carrierGrid), ...
    "sixgr:phy:frame:BWPOutsideCarrierGrid");

tmp = string(tempname);
mkdir(tmp);
cleanup = onCleanup(@() rmdir(tmp, "s")); %#ok<NASGU>
tracePath = fullfile(tmp, "bwp_switch_trace.csv");
writetable(history, tracePath);
assert(isfile(tracePath) && dir(tracePath).bytes > 0);
imagePath = fullfile(tmp, "bwp_switch_timeline.png");
fig = figure("Visible", "off");
figCleanup = onCleanup(@() close(fig)); %#ok<NASGU>
activationRows = history.Event == "SWITCH_ACTIVATION";
stairs(double(history.Tick), double(history.Epoch), "LineWidth", 1.5);
xlabel("absolute time (integer ticks)");
ylabel("BWP state epoch");
title("BWP switch timeline");
grid on;
assert(any(activationRows));
exportgraphics(fig, imagePath, "Resolution", 120);
assert(isfile(imagePath) && dir(imagePath).bytes > 1000);

ok = true;
end

function cfg = localBWP(id, direction, scs, startRB, sizeRB, active, ...
        activation, controlBWPID, dataBWPID)
cfg = struct( ...
    "BWPID", id, ...
    "Direction", direction, ...
    "CCID", "CC0", ...
    "ServingCellID", "CELL0", ...
    "FrequencyRange", "FR1", ...
    "SCSKHz", scs, ...
    "CyclicPrefix", "normal", ...
    "NStartBWP", startRB, ...
    "NSizeBWP", sizeRB, ...
    "ControlConfigRef", lower(direction) + "_control_" + id, ...
    "DataConfigRef", lower(direction) + "_data_" + id, ...
    "ControlBWPID", controlBWPID, ...
    "DataBWPID", dataBWPID, ...
    "ActiveInitial", active, ...
    "SwitchActivationTime", activation, ...
    "StateVersion", 1, ...
    "CommonTDDReferenceSCSKHz", 30);
end

function cfg = localCarrier()
cfg = struct( ...
    "CCID", "CC0", ...
    "ServingCellID", "CELL0", ...
    "SchedulingCCIDs", "CC0", ...
    "CenterFrequencyHz", 4e9, ...
    "Band", "n77", ...
    "FrequencyRange", "FR1", ...
    "ChannelBandwidthMHz", 100, ...
    "DuplexMode", "TDD", ...
    "DLCarrierGrid", struct("NStartGrid", 0, "NSizeGrid", 273, ...
    "SubcarrierSpacingKHz", 30), ...
    "ULCarrierGrid", struct("NStartGrid", 0, "NSizeGrid", 273, ...
    "SubcarrierSpacingKHz", 30), ...
    "CarrierIndicatorMap", struct( ...
    "Indicator", 0, "ScheduledCCID", "CC0"));
end

function num = localNumerology(scs)
num = sixgr.phy.frame.NumerologyCatalog.resolve( ...
    scs, "normal", "generic_waveform_test", "");
end

function cfg = localProductionSwitchContext()
cfg = withCanonicalSchedulerTiming(sixgr.config.defaultConfig());
nrb = double(sixgr.util.structGet(cfg, "phy.carrier.NSizeGrid", 273));
cfg.phy.bwp.dl = [ ...
    localRuntimeBWP(0, "DL", true, 0, 0, nrb); ...
    localRuntimeBWP(1, "DL", false, 1, 1, nrb)];
cfg.phy.bwp.ul = localRuntimeBWP(0, "UL", true, 1, 0, nrb);
if isfield(cfg.phy, "frameStructure")
    cfg.phy = rmfield(cfg.phy, "frameStructure");
end
if isfield(cfg.phy, "frame")
    cfg.phy = rmfield(cfg.phy, "frame");
end
cfg = sixgr.phy.frame.FrameRuntimeStateBuilder.attachTimingContext(cfg);
[snapshot, carriers] = ...
    sixgr.phy.frame.FrameRuntimeStateBuilder.build(cfg);
carrier = carriers{1};
dlInitial = carrier.configuredBWP(0, "DL");
activation = sixgr.phy.frame.AbsoluteTime.fromAbsoluteSlotSymbol( ...
    2, 0, dlInitial);
queued = carrier.BWPState.scheduleSwitch("DL", 1, activation, ...
    "IssuedTime", sixgr.phy.frame.AbsoluteTime.fromTicks(0), ...
    "ControlBWPID", 0, "TriggerSource", "RRC", ...
    "CommandID", "production-waveform-bwp-switch");
assert(queued.Accepted);
carrier.BWPState.applyUntil(activation);

runtimeState = snapshot.BWPState(1);
runtimeState.ActiveDLBWPID = 1;
runtimeState.ActiveULBWPID = 0;
runtimeState.Epoch = double(carrier.BWPState.Epoch);
runtimeState.CurrentTick = carrier.BWPState.CurrentTime.tickValue();
runtimeState.PendingCommands = ...
    table2struct(carrier.BWPState.pendingTable());
runtimeState.History = table2struct(carrier.BWPState.historyTable());
snapshot.BWPState(1) = runtimeState;
snapshot.DefaultIdentity.SourceBWPID = 1;
snapshot.DefaultIdentity.DLBWPID = 1;
snapshot.DefaultIdentity.ULBWPID = 0;
cfg.phy.frameStructure.TimingContext = snapshot;
end

function value = localRuntimeBWP( ...
        id, direction, active, controlID, dataID, nrb)
value = struct( ...
    "BWPID", id, ...
    "Direction", direction, ...
    "NStartBWP", 0, ...
    "NSizeBWP", nrb, ...
    "SCSKHz", 30, ...
    "CyclicPrefix", "normal", ...
    "ActiveInitial", active, ...
    "ControlBWPID", controlID, ...
    "DataBWPID", dataID, ...
    "StateVersion", 0, ...
    "SwitchActivationTick", 0);
end

function localAssertError(fcn, expectedIdentifier)
try
    fcn();
catch cause
    assert(string(cause.identifier) == string(expectedIdentifier), ...
        "Expected '%s'; received '%s': %s", ...
        expectedIdentifier, cause.identifier, cause.message);
    return;
end
error("sixgr:tests:ExpectedErrorNotRaised", ...
    "Expected error '%s' was not raised.", expectedIdentifier);
end
