function tests = testInitialAccessSSBPhaseCore
%TESTINITIALACCESSSSBPHASECORE Strict Phase-06 SSB conformance slice.
tests = functiontests(localfunctions);
end

function setupOnce(testCase)
repoRoot = fileparts(fileparts(mfilename("fullpath")));
addpath(repoRoot);
setup6GRSimToolkit("Verbose", false);
testCase.TestData.VectorRoot = fullfile( ...
    repoRoot, "tests", "vectors", "initial_access");
end

function testInitialAccessCapabilityRegistry(testCase)
profile = sixgr.phy.ia.InitialAccessSpecificationProfile.resolve();
verifyEqual(testCase, profile.ProfileID, ...
    "fr1_four_step_ra_rrc_connection_strict_r18");
verifyEqual(testCase, profile.Specifications.TS38211, ...
    "3GPP TS 38.211 V18.8.0");
verifyEqual(testCase, profile.Specifications.TS38331, ...
    "3GPP TS 38.331 V18.9.0");
verifyFalse(testCase, profile.ProxyAllowed);
verifyFalse(testCase, profile.FallbackAllowed);

plan = sixgr.phy.ia.InitialAccessCapabilityRegistry.resolve();
verifyTrue(testCase, plan.Executable);
verifyEqual(testCase, plan.FallbackCount, 0);
verifyEqual(testCase, plan.StateMutationCount, 0);
verifyError(testCase, @() ...
    sixgr.phy.ia.InitialAccessCapabilityRegistry.resolve( ...
    "Procedure", "two_step_ra"), ...
    "sixgr:phy:ia:UnsupportedTwoStepRA");
verifyError(testCase, @() ...
    sixgr.phy.ia.InitialAccessCapabilityRegistry.resolve( ...
    "Procedure", "cfra"), ...
    "sixgr:phy:ia:UnsupportedCFRA");
verifyError(testCase, @() ...
    sixgr.phy.ia.InitialAccessCapabilityRegistry.resolve( ...
    "Procedure", "beam_failure_recovery"), ...
    "sixgr:phy:ia:UnsupportedBFR");
verifyError(testCase, @() ...
    sixgr.phy.ia.InitialAccessCapabilityRegistry.resolve( ...
    "Procedure", "sul_access"), ...
    "sixgr:phy:ia:UnsupportedSUL");
verifyError(testCase, @() ...
    sixgr.phy.ia.InitialAccessCapabilityRegistry.resolve( ...
    "Procedure", "ntn_access"), ...
    "sixgr:phy:ia:UnsupportedNTNAccess");
verifyError(testCase, @() ...
    sixgr.phy.ia.InitialAccessCapabilityRegistry.resolve( ...
    "Procedure", "eredcap_access"), ...
    "sixgr:phy:ia:UnsupportedRedCapAccess");

coverage = localReadStringTable(fullfile( ...
    testCase.TestData.VectorRoot, ...
    "initial_access_declared_coverage_matrix.csv"));
verifyEqual(testCase, height(coverage), 271);
declaredCount = 0;
unsupportedCount = 0;
for rowIndex = 1:height(coverage)
    row = coverage(rowIndex, :);
    if row.ExpectedStatus == "DECLARED"
        resolved = sixgr.phy.ia.InitialAccessCapabilityRegistry.resolve( ...
            "Profile", row.Profile, ...
            "Procedure", row.RandomAccessProcedure);
        verifyTrue(testCase, resolved.Executable);
        verifyEqual(testCase, resolved.FallbackCount, 0);
        declaredCount = declaredCount + 1;
    else
        actual = localCaptureError(@() ...
            sixgr.phy.ia.InitialAccessCapabilityRegistry.resolve( ...
            "Profile", row.Profile, ...
            "Procedure", row.RandomAccessProcedure));
        verifyEqual(testCase, actual, ...
            localExpectedExtensionError(row.RandomAccessProcedure), ...
            sprintf("Wrong extension gate for %s.", row.TupleID));
        unsupportedCount = unsupportedCount + 1;
    end
end
verifyEqual(testCase, declaredCount, 264);
verifyEqual(testCase, unsupportedCount, 7);
end

function testSSBCaseResolverCaseA(testCase)
localVerifyCaseFamily(testCase, "A");
end

function testInitialAccessCarrierContext(testCase)
cfg = localProductionConfig();
context = sixgr.phy.ia.InitialAccessCarrierContext.fromConfig(cfg);
verifyEqual(testCase, context.FrequencyRange, "FR1");
verifyEqual(testCase, context.BandContext, "n78_like");
verifyEqual(testCase, context.Spectrum, "paired");
verifyEqual(testCase, context.NSizeGrid, 51);
verifyEqual(testCase, context.DLBWPSize, 51);
verifyEqual(testCase, context.ULBWPSize, 51);
verifyTrue(testCase, context.Immutable);
verifyEqual(testCase, strlength(context.ContextSHA256), 64);
end

function testSSBCaseResolverCaseB(testCase)
localVerifyCaseFamily(testCase, "B");
end

function testSSBCaseResolverCaseC(testCase)
localVerifyCaseFamily(testCase, "C");
end

function testSSBInvalidLmaxAndIndex(testCase)
vectors = localReadVectors(testCase);
invalid = vectors.Input(lower(vectors.Input.ExpectedValid) == "false", :);
verifyEqual(testCase, height(invalid), 7);
for rowIndex = 1:height(invalid)
    row = invalid(rowIndex, :);
    extra = {};
    if string(row.CaseID) == "SSBCASE-067"
        extra = {"SSBIndex", str2double(row.RequestedLmax)};
    end
    actual = localCaptureError(@() ...
        sixgr.phy.ia.SSBCaseResolver.fromVectorRow(row, extra{:}));
    verifyEqual(testCase, actual, string(row.ExpectedError), ...
        sprintf("Wrong typed failure for %s.", string(row.CaseID)));
end

timing = localTimingStruct( ...
    sixgr.phy.ia.SSBCaseResolver.fromVectorRow( ...
    vectors.Input(vectors.Input.CaseID == "SSBCASE-025", :)));
verifyError(testCase, @() sixgr.phy.ia.SSBBurstPlan.fromTiming( ...
    timing, "ActiveBitmap", "1111"), ...
    "sixgr:phy:ia:InvalidSSBBitmap");
end

function testSSBResourceOwnership(testCase)
inputPath = fullfile(testCase.TestData.VectorRoot, ...
    "ssb_re_mapping_test_vectors.csv");
expectedPath = fullfile(testCase.TestData.VectorRoot, ...
    "expected_ssb_re_ownership.csv");
inputs = localReadStringTable(inputPath);
expected = localReadStringTable(expectedPath);
verifyEqual(testCase, height(expected), 3840);

for inputIndex = 1:height(inputs)
    inputRow = inputs(inputIndex, :);
    actual = sixgr.phy.ia.SSBResourceOwnershipMap.resolve( ...
        str2double(inputRow.NCellID));
    expectedRows = expected(expected.CaseID == inputRow.CaseID, :);
    verifyEqual(testCase, height(actual.Rows), 960);
    verifyEqual(testCase, string(actual.Rows.Owner), ...
        string(expectedRows.Owner), ...
        sprintf("Owner mismatch for %s.", inputRow.CaseID));
    verifyEqual(testCase, double(actual.Rows.Symbol0), ...
        str2double(expectedRows.Symbol0));
    verifyEqual(testCase, double(actual.Rows.Subcarrier0), ...
        str2double(expectedRows.Subcarrier0));
    verifyEqual(testCase, double(actual.Rows.Index0), ...
        str2double(expectedRows.Index0));
    counts = groupsummary(actual.Rows, "Owner");
    localVerifyOwnerCount(testCase, counts, "PSS", 127);
    localVerifyOwnerCount(testCase, counts, "SSS", 127);
    localVerifyOwnerCount(testCase, counts, "PBCH", 432);
    localVerifyOwnerCount(testCase, counts, "PBCH_DMRS", 144);
    localVerifyOwnerCount(testCase, counts, "ZERO", 130);
end
end

function testSSBBurstBitmapAndCandidateTiming(testCase)
vectors = localReadVectors(testCase);
validInput = vectors.Input(lower(vectors.Input.ExpectedValid) == "true", :);
expectedBursts = localReadStringTable(fullfile( ...
    testCase.TestData.VectorRoot, ...
    "expected_ssb_burst_candidates.csv"));
verifyEqual(testCase, height(validInput), 60);
verifyEqual(testCase, height(expectedBursts), 360);

for rowIndex = 1:height(validInput)
    inputRow = validInput(rowIndex, :);
    resolved = sixgr.phy.ia.SSBCaseResolver.fromVectorRow(inputRow);
    timing = localTimingStruct(resolved);
    plan = sixgr.phy.ia.SSBBurstPlan.fromTiming(timing, ...
        "ActiveBitmap", inputRow.ActiveBitmap, ...
        "StrictBitmapRequired", true);
    expectedRows = expectedBursts( ...
        expectedBursts.CaseID == inputRow.CaseID, :);
    verifyEqual(testCase, double(plan.Rows.SSBIndex0), ...
        str2double(expectedRows.SSBIndex0));
    verifyEqual(testCase, double(plan.Rows.CandidateSymbol0), ...
        str2double(expectedRows.CandidateSymbol0));
    verifyEqual(testCase, logical(plan.Rows.Active), ...
        localLogicalColumn(expectedRows.Active));
    verifyEqual(testCase, double(plan.Rows.AbsoluteSymbol0), ...
        str2double(expectedRows.ExpectedAbsoluteSymbol0));
end

cfg = localProductionConfig();
[~, ~, tx] = sixgr.phy.dl.SSB_Tx(cfg, ...
    "NumSubframes", 1, "TimingOnly", true);
verifyEqual(testCase, logical(tx.SSBBurstPlan.ActiveBitmap), ...
    logical([1 0 1 0 1 0 1 0]));
verifyEqual(testCase, double(tx.SSBBurstPlan.ActiveSSBIndices0Based), ...
    [0 2 4 6]);
verifyEqual(testCase, height(tx.SSBResourceOwnership.Rows), 960);
verifyTrue(testCase, tx.SSBGridValidation.ResolvedValid);
[waveform, waveInfo, waveformTx] = sixgr.phy.dl.SSB_Tx(cfg, ...
    "NumSubframes", 1);
verifyNotEmpty(testCase, waveform);
verifyTrue(testCase, all(isfinite(waveform(:))));
verifyEqual(testCase, logical(waveformTx.SSB.ActiveBitmap), ...
    logical([1 0 1 0 1 0 1 0]));
verifyEqual(testCase, waveformTx.SampleRate_Hz, ...
    waveformTx.OFDMSamplingResolution.SampleRateHz);
verifyTrue(testCase, isstruct(waveInfo));
end

function testSSBGridValidation(testCase)
valid = sixgr.phy.ia.SSBGridValidator.validate( ...
    "CarrierSubcarrierSpacingKHz", 30, ...
    "SSBSubcarrierSpacingKHz", 30, ...
    "NStartGrid", 0, "NSizeGrid", 51, ...
    "NStartBWP", 0, "NSizeBWP", 51, ...
    "NCRBSSB", 31, "KSSB", 0);
verifyTrue(testCase, valid.ResolvedValid);
verifyGreaterThan(testCase, strlength(valid.ValidationSHA256), 0);

verifyError(testCase, @() ...
    sixgr.phy.ia.SSBGridValidator.validate( ...
    "CarrierSubcarrierSpacingKHz", 30, ...
    "SSBSubcarrierSpacingKHz", 30, ...
    "NStartGrid", 0, "NSizeGrid", 51, ...
    "NStartBWP", 40, "NSizeBWP", 20, ...
    "NCRBSSB", 31, "KSSB", 0), ...
    "sixgr:phy:ia:InvalidCarrierGrid");
verifyError(testCase, @() ...
    sixgr.phy.ia.SSBGridValidator.validate( ...
    "CarrierSubcarrierSpacingKHz", 30, ...
    "SSBSubcarrierSpacingKHz", 30, ...
    "NStartGrid", 0, "NSizeGrid", 51, ...
    "NStartBWP", 0, "NSizeBWP", 51, ...
    "NCRBSSB", 100, "KSSB", 0), ...
    "sixgr:phy:ia:SSBOutsideCarrier");
end

function testSSBPerBeamPrecodingAndPower(testCase)
vectors = localReadVectors(testCase);
row = vectors.Input(vectors.Input.CaseID == "SSBCASE-025", :);
timing = localTimingStruct( ...
    sixgr.phy.ia.SSBCaseResolver.fromVectorRow(row));
powerDB = [0 -1 -2 -3 -4 -5 -6 -7];
precoders = "beam_" + string(0:7);
plan = sixgr.phy.ia.SSBBurstPlan.fromTiming(timing, ...
    "ActiveBitmap", "10101010", ...
    "PerSSBPowerDB", powerDB, ...
    "PrecoderIDs", precoders, ...
    "StrictBitmapRequired", true);
verifyEqual(testCase, double(plan.PerSSBPowerDB), powerDB);
verifyEqual(testCase, string(plan.PrecoderIDs), precoders);
verifyEqual(testCase, double(plan.Rows.PowerOffset_dB), powerDB(:));
verifyEqual(testCase, string(plan.Rows.PrecoderID), precoders(:));
verifyEqual(testCase, plan.SelectionSource, ...
    "configured_ssb_positions_in_burst");
verifyEqual(testCase, strlength(plan.PlanSHA256), 64);

cfg = localProductionConfig();
cfg.phy.ssb.activeBitmap = "11000000";
cfg.phy.ssb.perSSBPower_dB = [0 -3 0 0 0 0 0 0];
cfg.phy.ssb.precoderIDs = "port_" + string([1 2 1 1 1 1 1 1]);
cfg.phy.ssb.precoderMatrices = [ ...
    1 0; 0 1; 1 0; 1 0; 1 0; 1 0; 1 0; 1 0];
[waveform, info, tx] = sixgr.phy.dl.SSB_Tx(cfg, "NumSubframes", 1);
verifyEqual(testCase, size(waveform, 2), 2);
verifyTrue(testCase, all(isfinite(waveform(:))));
verifyTrue(testCase, logical(info.SSBComposite.Composed));
verifyEqual(testCase, info.SSBComposite.ActiveSSBIndices0Based, [0 1]);
verifyEqual(testCase, tx.NumTransmitAntennas, 2);
verifyEqual(testCase, tx.SSBBurstPlan.PerSSBPowerDB(1:2), [0 -3]);
end

function testSSBNoSignalFailsClosed(testCase)
cfg = localProductionConfig();
[waveform, ~, tx] = sixgr.phy.dl.SSB_Tx(cfg, "NumSubframes", 1);
noSignal = zeros(size(waveform), "like", waveform);
verifyError(testCase, @() sixgr.phy.dl.SSB_Rx( ...
    noSignal, cfg, "SampleRate_Hz", tx.SampleRate_Hz), ...
    "sixgr:phy:ia:SSBNotDetected");
end

function localVerifyCaseFamily(testCase, caseLetter)
vectors = localReadVectors(testCase);
mask = lower(vectors.Input.ExpectedValid) == "true" & ...
    upper(vectors.Input.DeclaredSSBCase) == caseLetter;
inputs = vectors.Input(mask, :);
verifyGreaterThan(testCase, height(inputs), 0);
for rowIndex = 1:height(inputs)
    inputRow = inputs(rowIndex, :);
    expectedRow = vectors.Expected( ...
        vectors.Expected.CaseID == inputRow.CaseID, :);
    verifyEqual(testCase, height(expectedRow), 1);
    actual = sixgr.phy.ia.SSBCaseResolver.fromVectorRow(inputRow);
    verifyEqual(testCase, actual.ResolvedCase, ...
        string(expectedRow.ResolvedCase));
    verifyEqual(testCase, actual.ResolvedSSBSCSKHz, ...
        str2double(expectedRow.ResolvedSSBSCS_kHz));
    verifyEqual(testCase, actual.ResolvedLmax, ...
        str2double(expectedRow.ResolvedLmax));
    verifyEqual(testCase, actual.CandidateSymbols0Based, ...
        localPipeNumeric(expectedRow.CandidateSymbols0Based));
    verifyEqual(testCase, actual.NumCandidates, ...
        str2double(expectedRow.NumCandidates));
    verifyEqual(testCase, actual.PeriodicityMs, ...
        str2double(expectedRow.Periodicity_ms));
end
end

function vectors = localReadVectors(testCase)
vectors = struct();
vectors.Input = localReadStringTable(fullfile( ...
    testCase.TestData.VectorRoot, ...
    "ssb_case_lmax_test_vectors.csv"));
vectors.Expected = localReadStringTable(fullfile( ...
    testCase.TestData.VectorRoot, ...
    "expected_ssb_case_lmax.csv"));
end

function timing = localTimingStruct(resolved)
timing = struct( ...
    "Lmax", double(resolved.Lmax), ...
    "CandidateStartSymbolsWithinHalfFrame", ...
        double(resolved.CandidateSymbols0Based), ...
    "SelectedSSBIndex", double(resolved.SelectedSSBIndex), ...
    "HalfFrameIndex", double(resolved.HalfFrameIndex), ...
    "SSBSubcarrierSpacingKHz", ...
        double(resolved.SSBSubcarrierSpacingKHz), ...
    "BlockPattern", string(resolved.BlockPattern), ...
    "Case", string(resolved.Case), ...
    "PeriodicityMs", double(resolved.PeriodicityMs));
end

function cfg = localProductionConfig()
cfg = struct();
cfg.channel.fc_Hz = 3.5e9;
cfg.frequency.center_frequency_hz = 3.5e9;
cfg.frequency.range_name = "FR1";
cfg.frequency.bandwidth_hz = 20e6;
% This existing Case-B fixture explicitly models paired spectrum.
cfg.frequency.duplex_mode = "FDD";
cfg.phy.frequencyRange = "FR1";
cfg.phy.channelBandwidth_MHz = 20;
cfg.phy.carrier = struct( ...
    "NCellID", 17, ...
    "SubcarrierSpacing_kHz", 30, ...
    "SubcarrierSpacing", 30, ...
    "CyclicPrefix", "normal", ...
    "NStartGrid", 0, ...
    "NSizeGrid", 51);
cfg.phy.ssb = struct( ...
    "enable", true, ...
    "blockPattern", "Case B", ...
    "scs_kHz", 30, ...
    "Lmax", 8, ...
    "periodicity_ms", 20, ...
    "activeBitmap", "10101010", ...
    "perSSBPower_dB", 0, ...
    "precoderIDs", "identity");
cfg.phy.mib = struct( ...
    "enable", true, ...
    "pdcchConfigSIB1", 0, ...
    "dmrsTypeAPosition", 2, ...
    "cellBarred", false, ...
    "intraFreqReselection", false);
cfg.phy.sib1 = struct("coreset0Index", 0, "searchSpaceZero", 0);
cfg.initial_access = struct( ...
    "profile", "fr1_four_step_ra_rrc_connection_strict_r18", ...
    "band_context", "n78_like", ...
    "spectrum", "paired", ...
    "require_explicit_ssb_bitmap", true);
end

function values = localPipeNumeric(textValue)
parts = split(string(textValue), "|");
values = str2double(parts(:)).';
end

function values = localLogicalColumn(raw)
values = lower(strtrim(string(raw))) == "true";
end

function localVerifyOwnerCount(testCase, counts, owner, expected)
mask = string(counts.Owner) == string(owner);
verifyEqual(testCase, nnz(mask), 1);
verifyEqual(testCase, double(counts.GroupCount(mask)), expected);
end

function identifier = localCaptureError(fcn)
identifier = "";
try
    fcn();
catch cause
    identifier = string(cause.identifier);
end
end

function tableOut = localReadStringTable(pathIn)
options = detectImportOptions(pathIn, "TextType", "string");
options = setvartype(options, options.VariableNames, "string");
tableOut = readtable(pathIn, options);
end

function identifier = localExpectedExtensionError(procedure)
switch lower(string(procedure))
    case "two_step_ra"
        identifier = "sixgr:phy:ia:UnsupportedTwoStepRA";
    case "cfra"
        identifier = "sixgr:phy:ia:UnsupportedCFRA";
    case "beam_failure_recovery"
        identifier = "sixgr:phy:ia:UnsupportedBFR";
    case "sul_access"
        identifier = "sixgr:phy:ia:UnsupportedSUL";
    case "ntn_access"
        identifier = "sixgr:phy:ia:UnsupportedNTNAccess";
    case {"redcap_access", "eredcap_access"}
        identifier = "sixgr:phy:ia:UnsupportedRedCapAccess";
    otherwise
        error("sixgr:test:UnknownInitialAccessExtension", ...
            "Unknown extension procedure %s.", string(procedure));
end
end
