function ok = testFourStepRARuntimeChannelBinding()
%TESTFOURSTEPRARUNTIMECHANNELBINDING Four-step RA uses runtime channel state.
cfg = raStrictAnchorConfig();
res = sixgr.truth.CoupledTruthRuntime.runFourStepRARuntime(cfg, ...
    "RunId", "test_ra_runtime_channel", ...
    "UEId", 1, "CellId", 1, "AttemptId", 1, ...
    "RuntimeSlot", 0, "WriteArtifacts", false);

assert(logical(res.RACompleted) && logical(res.StrictOk), ...
    "Runtime-coupled four-step RA must complete Msg1-Msg4.");
assert(logical(res.RuntimeChannelStateUsed), ...
    "Runtime-coupled RA must use the persistent channel-state transport.");
assert(~logical(res.RuntimeSelfLoopWaveformsUsed), ...
    "Runtime-coupled RA must not decode direct TX self-loop waveforms.");
assert(string(res.RuntimeTransportMode) == "persistent_runtime_channel_state", ...
    "Runtime transport mode must disclose persistent channel-state use.");

T = res.ArtifactTables.ra_runtime_stage_waveforms;
assert(height(T) == 4, "Runtime RA must publish one transport row per message.");
assert(isequal(string(T.StageName).', ["Msg1","Msg2","Msg3","Msg4"]), ...
    "Runtime RA stages must be ordered Msg1, Msg2, Msg3, Msg4.");
assert(all(logical(T.RuntimeChannelStateUsed)) && ~any(logical(T.SelfLoopWaveformUsed)), ...
    "Every RA message must traverse the runtime channel-state path.");
assert(any(contains(string(T.RuntimeChannelLinkKey), "dir=UL")) && ...
    any(contains(string(T.RuntimeChannelLinkKey), "dir=DL")), ...
    "Runtime RA must use both UL and DL persistent link keys.");
assert(string(res.Msg3ContentionIdentity) == string(res.Msg4ContentionIdentity), ...
    "Msg4 contention identity must be decoded from the waveform and match Msg3.");
ok = true;
end
