function ok = testCoupledServingRSRPProvenance()
%TESTCOUPLEDSERVINGRSRPPROVENANCE Do not label zero-loss scores as field RSRP.

setup6GRSimToolkit("Verbose", false);
scenario = sixgr.lls6g.config.loadScenarioConfig(fullfile( ...
    "simulator", "configs", "scenarios", ...
    "lls_causal_access_to_data_wiring.yaml"));
cfg = sixgr.lls6g.buildInternalConfig(scenario, tempdir);
assert(logical(sixgr.util.structGet(cfg, "channel.pathlossEnabled", false)) && ...
    string(sixgr.util.structGet(cfg, "channel.pathlossModel", "")) == "nrPathLoss", ...
    "The causal field-wiring scenario must explicitly enable nrPathLoss.");

multiUser = struct("Enabled", false, "NumUsers", 1, "RNTIStart", 1, ...
    "ExecutionModel", "slot_coupled_truth");
state = sixgr.truth.CoupledTruthRuntime.initialize( ...
    cfg, tempdir, multiUser, struct(), 1);
state = sixgr.truth.CoupledTruthRuntime.advanceFrame(state, cfg, multiUser, 1, 20);
row = state.ServingTraceTable(end,:);
assert(isfinite(double(row.ServingRSRP_dBm)) && ...
    isfinite(double(row.Pathloss_dB)) && double(row.Pathloss_dB) > 0 && ...
    string(row.ServingRSRPSource) == ...
    "large_scale_pathloss_applied_per_reference_re_power", ...
    "Pathloss-enabled serving RSRP must have an applied-loss provenance.");

cfgOff = sixgr.util.structSet(cfg, "channel.pathlossEnabled", false);
cfgOff = sixgr.util.structSet(cfgOff, "channel.pathloss.enabled", false);
stateOff = sixgr.truth.CoupledTruthRuntime.initialize( ...
    cfgOff, tempdir, multiUser, struct(), 1);
stateOff = sixgr.truth.CoupledTruthRuntime.advanceFrame( ...
    stateOff, cfgOff, multiUser, 1, 20);
rowOff = stateOff.ServingTraceTable(end,:);
assert(isnan(double(rowOff.ServingRSRP_dBm)) && ...
    string(rowOff.ServingRSRPSource) == ...
    "unavailable_pathloss_disabled_no_field_rsrp", ...
    ["A zero-loss selection score must remain internal and must not be " ...
    "exported as absolute serving RSRP in dBm."]);

ok = true;
end
