function ok = testPDSCHReservedREUnionVectors()
%TESTPDSCHRESERVEDREUNIONVECTORS Execute all 14 reservation-union rows.

setup6GRSimToolkit("Verbose", false, "RunToolboxChecks", false);
vectors = readPDSCHVectorTable("pdsch_reserved_re_test_vectors.csv");
golden = readPDSCHVectorTable( ...
    "expected_pdsch_reserved_re_union.csv");
assert(height(vectors) == 14 && height(golden) == 14, ...
    "The complete 14-row reserved-RE matrix is mandatory.");
assert(isequal(vectors.CaseID, golden.CaseID), ...
    "Reserved-RE input and expected case IDs differ.");

passCount = 0;
negativeCount = 0;
for i = 1:height(vectors)
    allocation = pdschVectorDecodeIntegers(vectors.AllocationRE(i));
    sourceTexts = [ ...
        vectors.SSBRE(i), vectors.CORESETRE(i), ...
        vectors.NZPCSIRSRE(i), vectors.ZPCSIRSRE(i), ...
        vectors.LTECRSRE(i), vectors.RateMatchPatternRE(i)];
    reservations = struct( ...
        "SSB", pdschVectorDecodeIntegers(sourceTexts(1)), ...
        "CORESET", pdschVectorDecodeIntegers(sourceTexts(2)), ...
        "NZPCSIRS", pdschVectorDecodeIntegers(sourceTexts(3)), ...
        "ZPCSIRS", pdschVectorDecodeIntegers(sourceTexts(4)), ...
        "LTECRS", pdschVectorDecodeIntegers(sourceTexts(5)), ...
        "RateMatchPattern", pdschVectorDecodeIntegers(sourceTexts(6)));

    actual = sixgr.pdsch.PDSCHResourceOwnershipMap. ...
        analyze(allocation, reservations);
    oracle = sixgr.pdsch.oracle.ReservedREUnionSpec. ...
        resolveEncoded(vectors.AllocationRE(i), sourceTexts);
    localAssertExpected(actual, oracle, golden(i, :));

    expectedStatus = golden.Status(i);
    expectedToken = golden.ExpectedError(i);
    if expectedStatus == "PASS"
        map = sixgr.pdsch.PDSCHResourceOwnershipMap( ...
            allocation, reservations);
        assert(isequal(map.ReservedUnionIndices(:).', ...
            actual.ReservedUnionIndices), ...
            "Ownership-map reservation mismatch for %s.", ...
            vectors.CaseID(i));
        assert(isequal(map.DataIndices(:).', actual.DataIndices), ...
            "Ownership-map data mismatch for %s.", vectors.CaseID(i));
        assert(all(map.Entries.CollisionCount == 0), ...
            "Resolved ownership contains a collision for %s.", ...
            vectors.CaseID(i));
        passCount = passCount + 1;
    else
        localAssertError(@() sixgr.pdsch.PDSCHResourceOwnershipMap( ...
            allocation, reservations), "sixgr:pdsch:" + expectedToken);
        negativeCount = negativeCount + 1;
    end
end
assert(passCount == 11 && negativeCount == 3, ...
    "Unexpected reservation positive/negative execution counts.");
ok = true;
end

function localAssertExpected(actual, oracle, expected)
caseID = expected.CaseID(1);
assert(actual.AllocationRECount == ...
    str2double(expected.AllocationRECount(1)), ...
    "Allocation count mismatch for %s.", caseID);
assert(actual.ReservedUnionCount == ...
    str2double(expected.ReservedUnionCount(1)), ...
    "Reserved-union count mismatch for %s.", caseID);
assert(actual.DataRECount == str2double(expected.DataRECount(1)), ...
    "Data count mismatch for %s.", caseID);
assert(actual.ReservedOutsideAllocationCount == ...
    str2double(expected.ReservedOutsideAllocationCount(1)), ...
    "Outside-reservation count mismatch for %s.", caseID);
assert(actual.PairwiseOverlapMultiplicity == ...
    str2double(expected.PairwiseOverlapMultiplicity(1)), ...
    "Pairwise-overlap count mismatch for %s.", caseID);
assert(pdschVectorEncodeIntegers(actual.ReservedUnionIndices) == ...
    expected.ExpectedReservedUnion(1), ...
    "Reserved-union indices mismatch for %s.", caseID);
assert(pdschVectorEncodeIntegers(actual.DataIndices) == ...
    expected.ExpectedDataRE(1), ...
    "Data indices mismatch for %s.", caseID);
assert(actual.Status == expected.Status(1), ...
    "Reservation status mismatch for %s.", caseID);
expectedToken = expected.ExpectedError(1);
if strlength(expectedToken) == 0
    assert(strlength(actual.ErrorIdentifier) == 0, ...
        "Unexpected reservation error for %s.", caseID);
else
    assert(actual.ErrorIdentifier == "sixgr:pdsch:" + expectedToken, ...
        "Reservation error mismatch for %s.", caseID);
end

assert(actual.AllocationRECount == oracle.AllocationRECount && ...
    actual.ReservedUnionCount == oracle.ReservedUnionCount && ...
    actual.DataRECount == oracle.DataRECount && ...
    actual.ReservedOutsideAllocationCount == ...
        oracle.ReservedOutsideAllocationCount && ...
    actual.PairwiseOverlapMultiplicity == ...
        oracle.PairwiseOverlapMultiplicity && ...
    isequal(actual.ReservedUnionIndices, ...
        oracle.ReservedUnionIndices) && ...
    isequal(actual.DataIndices, oracle.DataIndices) && ...
    actual.Status == oracle.Status && ...
    erase(actual.ErrorIdentifier, "sixgr:pdsch:") == oracle.ErrorToken, ...
    "Production/oracle reservation mismatch for %s.", caseID);
end

function localAssertError(fn, expectedID)
try
    fn();
catch ME
    assert(string(ME.identifier) == string(expectedID), ...
        "Observed %s, expected %s.", ME.identifier, expectedID);
    return;
end
error("sixgr:test:ExpectedErrorNotThrown", ...
    "Expected error %s was not thrown.", expectedID);
end
