function ok = testTruthValidationProfile()
%TESTTRUTHVALIDATIONPROFILE Truth runner must stay on waveform LLS + truth E2E only.

setup6GRSimToolkit("Verbose", false);

tmp = tempname;
mkdir(tmp);
c = onCleanup(@() rmdir(tmp, "s")); %#ok<NASGU>

out = run_truth_validation_profile( ...
    "ResultsRoot", tmp, ...
    "Verbose", false, ...
    "SetupToolboxChecks", false, ...
    "LinkDuration_s", 0.02, ...
    "LinkMaxSimFrames", 8, ...
    "LinkSNR_dB", 30, ...
    "LinkSNRGrid_dB", [0 20 30], ...
    "LinkSweepFrames", 1, ...
    "E2EDuration_s", 0.02, ...
    "E2EMaxSlots", 24, ...
    "E2EUECount", 2, ...
    "SaveFigures", true, ...
    "GenerateCampaignPlots", true);

assert(out.Ok, "Truth validation profile should complete cleanly.");
assert(~logical(out.Settings.UseFastLinkModel), "Truth validation profile must disable fast link mode.");
assert(~logical(out.Settings.UseMexAcceleration), "Truth validation profile must disable MEX acceleration.");
assert(~logical(out.Settings.UseParallelAcceleration), "Truth validation profile must disable parallel acceleration.");
assert(logical(out.Settings.StrictMode), "Truth validation profile must force strict mode.");
assert(logical(out.Settings.NoProxyTruthContract), "Truth validation profile must enable the no-proxy truth contract.");
assert(~logical(out.Settings.IncludeSystem), "Truth validation profile must exclude system/SLS.");
assert(string(out.Settings.E2EAirModel) == "truth", "Truth validation profile must force truth E2E.");
assert(string(out.Settings.E2ETrafficModel) == "traceReplay", "Truth validation profile must use deterministic traceReplay traffic.");
assert(string(out.Settings.RequestedChannelModel) == "TDL-C", "Truth validation profile must request TDL-C.");
assert(string(out.Settings.NormalizedChannelModel) == "TDL", "Truth validation profile must normalize to TDL family.");
assert(string(out.Settings.TDLProfile) == "TDL-C", "Truth validation profile must normalize to TDL-C profile.");

runFolder = char(string(out.RunFolder));
layout = sixgr.report.resultLayout(runFolder);
supplementalRoot = fullfile(runFolder, "supplemental_link");
supplementalLayout = sixgr.report.resultLayout(supplementalRoot);
assert(contains(lower(string(runFolder)), lower(string([filesep 'e2e' filesep 'truth_validation' filesep 'current']))), ...
    "Truth validation runs must save under /results/e2e/truth_validation/current.");
assert(exist(layout.AirInterfaceDir, "dir") ~= 7, ...
    "Truth validation base run root must stay free of primary link artifacts.");
assert(exist(fullfile(runFolder, "control"), "dir") ~= 7, ...
    "Truth validation base run root must stay free of primary control artifacts.");
assert(exist(fullfile(runFolder, "beamforming"), "dir") ~= 7, ...
    "Truth validation base run root must stay free of primary beamforming artifacts.");
assert(exist(fullfile(runFolder, "harq"), "dir") ~= 7, ...
    "Truth validation base run root must stay free of primary HARQ artifacts.");
assert(exist(fullfile(runFolder, "rf"), "dir") ~= 7, ...
    "Truth validation base run root must stay free of primary RF artifacts.");
assert(exist(fullfile(supplementalLayout.AirInterfaceCSVDir, "lls_kpi_summary.csv"), "file") == 2, ...
    "Truth validation profile is missing supplemental link KPI output.");
assert(exist(fullfile(supplementalLayout.AirInterfaceCSVDir, "multiuser_user_summary.csv"), "file") ~= 2, ...
    "Truth validation profile must not silently export multi-user LLS summaries.");
assert(exist(fullfile(supplementalRoot, "control", "csv", "pdcch_trials.csv"), "file") == 2, ...
    "Truth validation profile is missing supplemental control PDCCH trials.");
assert(exist(fullfile(layout.PacketFlowCSVDir, "probe_e2e_summary_truth.csv"), "file") == 2, ...
    "Truth validation profile is missing truth E2E summary.");
e2eSummary = readtable(fullfile(layout.PacketFlowCSVDir, "probe_e2e_summary_truth.csv"), "VariableNamingRule", "preserve");
assert(logical(e2eSummary.E2ESystemCoupled(1)), ...
    "Truth validation profile truth E2E must now be system-coupled.");
assert(string(e2eSummary.E2ECouplingMode(1)) == "system_waveform_grant_trace", ...
    "Truth validation profile must use the waveform system grant trace coupling mode.");
assert(exist(fullfile(supplementalLayout.AirInterfaceDir, "image"), "dir") == 7, ...
    "Truth validation profile should create supplemental link figure output folder.");
e2eFigDir = fullfile(layout.PacketFlowDir, "image");
assert(exist(e2eFigDir, "dir") == 7, "Truth validation profile should create the E2E figure folder.");
e2ePng = dir(fullfile(e2eFigDir, "*.png"));
assert(~isempty(e2ePng), "Truth validation profile should generate at least one E2E figure.");
assert(exist(layout.ReportImageDir, "dir") == 7, ...
    "Truth validation profile should generate campaign plots.");
assert(exist(fullfile(runFolder, "system", "csv", "system_kpis.csv"), "file") ~= 2, ...
    "Truth validation profile must not produce system KPI exports.");
assert(logical(out.NoProxyScan.Ok), "Truth validation profile primary artifacts must stay free of proxy markers.");
assert(logical(out.SupplementalNoProxyScan.Ok), "Truth validation profile supplemental artifacts must stay free of proxy markers.");
assert(exist(fullfile(runFolder, "meta", "calibration_source.json"), "file") ~= 2, ...
    "Truth validation profile must not export calibration provenance when calibration was not used.");

req = readtable(layout.RequiredOutputsCSV, "VariableNamingRule", "preserve");
paths = lower(string(req.RequiredPath));
hasSystem = contains(paths, "\system\") | contains(paths, "/system/");
assert(~any(hasSystem), "Truth validation profile required outputs must exclude system artifacts.");

approx = readtable(fullfile(runFolder, "meta", "approximations_used.csv"), "VariableNamingRule", "preserve");
if ~isempty(approx) && ismember("Evidence", string(approx.Properties.VariableNames))
    approxEvidence = lower(string(approx.Evidence));
    hasSystemApprox = contains(approxEvidence, "\system\") | contains(approxEvidence, "/system/");
    assert(~any(hasSystemApprox), "Truth validation profile approximations ledger must not claim skipped system artifacts.");
    if ismember("Component", string(approx.Properties.VariableNames))
        assert(~any(string(approx.Component) == "truth_e2e_coupling"), ...
            "Truth validation profile must stop flagging truth E2E as uncoupled.");
    end
end

baseReport = fileread(layout.CampaignReportMD);
assert(contains(baseReport, "- Campaign profile: `TRUTH_VALIDATION_PROFILE`"), ...
    "Base campaign report must state TRUTH_VALIDATION_PROFILE.");
assert(contains(baseReport, "- Campaign entry point: `run_truth_validation_profile`"), ...
    "Base campaign report must record the truth-validation entry point.");
assert(contains(baseReport, "- System mobility: `skipped`"), ...
    "Base campaign report must state that the system run was skipped.");
assert(contains(baseReport, "- Calibration artifacts: `skipped`"), ...
    "Base campaign report must state that calibration artifacts were skipped.");
assert(~contains(baseReport, "- Calibration source:"), ...
    "Base campaign report must not print calibration provenance for truth-only runs.");
assert(contains(baseReport, "## Supplemental Wrapper Artifacts"), ...
    "Base campaign report must disclose supplemental wrapper artifacts explicitly.");
assert(contains(baseReport, "`supplemental_link`"), ...
    "Base campaign report must point supplemental outputs to supplemental_link.");

manifest = jsondecode(fileread(fullfile(runFolder, "meta", "run_manifest.json")));
assert(isfield(manifest, "CampaignProfileMode") && strcmpi(string(manifest.CampaignProfileMode), "truth_validation"), ...
    "Truth validation manifest must record truth_validation mode.");
assert(isfield(manifest, "CampaignProfileLabel") && string(manifest.CampaignProfileLabel) == "TRUTH_VALIDATION_PROFILE", ...
    "Truth validation manifest must record TRUTH_VALIDATION_PROFILE.");
assert(isfield(manifest, "CampaignProfileEntryPoint") && string(manifest.CampaignProfileEntryPoint) == "run_truth_validation_profile", ...
    "Truth validation manifest must record the truth-validation entry point.");
assert(isfield(manifest, "CampaignStrictMode") && logical(manifest.CampaignStrictMode), ...
    "Truth validation manifest must record campaign strict mode explicitly.");
assert(isfield(manifest, "NoProxyTruthContract") && logical(manifest.NoProxyTruthContract), ...
    "Truth validation manifest must record the no-proxy truth contract explicitly.");
assert(isfield(manifest, "OnlyE2E") && logical(manifest.OnlyE2E), ...
    "Truth validation manifest must record OnlyE2E explicitly.");
assert(isfield(manifest, "E2EStrictValidation") && logical(manifest.E2EStrictValidation), ...
    "Truth validation manifest must record E2E strict validation explicitly.");
assert(isfield(manifest, "LinkStrictValidation") && ~logical(manifest.LinkStrictValidation), ...
    "Truth validation manifest must not claim link strict validation on the skipped base campaign.");
assert(isfield(manifest, "SystemStrictValidation") && ~logical(manifest.SystemStrictValidation), ...
    "Truth validation manifest must not claim system strict validation on the skipped base campaign.");
assert(isfield(manifest, "SupplementalArtifactsGenerated") && logical(manifest.SupplementalArtifactsGenerated), ...
    "Truth validation manifest must disclose supplemental artifact generation.");
assert(isfield(manifest, "SupplementalArtifactsCoLocated") && ~logical(manifest.SupplementalArtifactsCoLocated), ...
    "Truth validation manifest must state that supplemental artifacts were not co-located in the base scope.");
assert(isfield(manifest, "SupplementalArtifactRootRelative") && string(manifest.SupplementalArtifactRootRelative) == "supplemental_link", ...
    "Truth validation manifest must point supplemental artifacts to supplemental_link.");
assert(isfield(manifest, "SupplementalArtifactSemantics") && string(manifest.SupplementalArtifactSemantics) == "wrapper_generated_not_part_of_base_campaign_execution", ...
    "Truth validation manifest must describe supplemental artifact semantics honestly.");

truthValidationManifest = jsondecode(fileread(out.ManifestJSON));
assert(isfield(truthValidationManifest, "SupplementalArtifactRootRelative") && string(truthValidationManifest.SupplementalArtifactRootRelative) == "supplemental_link", ...
    "Truth validation wrapper manifest must point supplemental artifacts to supplemental_link.");
assert(isfield(truthValidationManifest, "SupplementalArtifactsCoLocated") && ~logical(truthValidationManifest.SupplementalArtifactsCoLocated), ...
    "Truth validation wrapper manifest must state that supplemental artifacts were not co-located.");

truthValidationReport = fileread(out.ReportMarkdown);
assert(contains(truthValidationReport, "- Base campaign scope: `e2e_only`"), ...
    "Truth validation wrapper report must state that the base campaign scope is e2e_only.");
assert(contains(truthValidationReport, "- Supplemental artifact root: `supplemental_link`"), ...
    "Truth validation wrapper report must point supplemental outputs to supplemental_link.");
assert(contains(truthValidationReport, "were not part of the base campaign execution"), ...
    "Truth validation wrapper report must state that supplemental outputs were not part of the base campaign execution.");

ok = true;
end
