function ok = testFourStepRAResultAdapterDependencies()
%TESTFOURSTEPRARRESULTADAPTERDEPENDENCIES Guard the in-path RA row adapter.

setup6GRSimToolkit("Verbose", false, "RunToolboxChecks", false);
sourcePath = fullfile(pwd, "+sixgr", "+truth", ...
    "runWaveformLinkBundle.m");
source = string(fileread(sourcePath));
startToken = "function r = localApplyFourStepRAEvidenceToPRACHRow";
endToken = "function tables = localEmptyRAEvidenceTables";
startIndex = strfind(source, startToken);
endIndex = strfind(source, endToken);
assert(numel(startIndex) == 1 && ~isempty(endIndex) && ...
    endIndex(1) > startIndex(1), ...
    "Unable to isolate the production four-step RA result adapter.");
adapter = extractBetween(source, startIndex(1), endIndex(1) - 1);
assert(~contains(adapter, "ternary("), ...
    "The RA result adapter must not depend on an undefined ternary helper.");
assert(all(contains(adapter, ["TimingEstimateStatus", ...
    "CFOEstimateAvailability", "CFOValueStatus"])), ...
    "The RA result adapter must materialize timing and CFO availability states.");
assert(contains(adapter, "r.CRCPass = NaN;") && contains(adapter, "r.CRCApplicable = false;") && ...
    contains(adapter, 'r.CRCOutcome = "not_applicable";') && ...
    ~contains(adapter, "r.CRCPass = double(strictOk)"), ...
    "Overall RA acceptance must not be exported as a nonexistent PRACH transport-block CRC.");
assert(contains(adapter, '"RASlotTimeBase","Msg1ScheduledSlot"'), ...
    "The canonical PRACH adapter must retain producer-declared RA source coordinates.");
assert(all(contains(adapter,["EstimatedTimingAdvanceCommand","TimingAdvanceNTA_Tc", ...
    "TimingAdvanceSampleRate_Hz","TimingAdvanceSource","PRACHTimingSampleRate_Hz", ...
    "TAQuantizationResidual_samples","AbsoluteTime.TicksPerSecond"])), ...
    "The canonical adapter must retain decoded RAR timing units and not reinterpret detector samples as microseconds.");

collectorStart = regexp(source, ...
    '(?m)^function \[T, correlationTraceT, raEvidenceTables, \.\.\.\r?\n\s*advancedDLState, advancedULState, observedRET\] = localCollectPRACHTrials\(', 'start');
collectorEnd = strfind(source, "function tf = localShouldRunFourStepRAForPRACH");
assert(numel(collectorStart) == 1 && numel(collectorEnd) == 1 && collectorEnd > collectorStart, ...
    "The guard must isolate the actual PRACH collector, not a similarly named sweep wrapper.");
collector = extractBetween(source, collectorStart(1), collectorEnd(1) - 1);
assert(contains(collector, "r.FailureReason = failure") && ...
    contains(collector, "r.RAFailureReason = failure"), ...
    "The canonical PRACH row must preserve identifier and message on adapter failure.");
assert(contains(collector, "r.CRCApplicable = false;") && ...
    ~contains(collector, "r.CRCPass = 0;") && ~contains(collector, "r.CRCPass = double(detected);") && ...
    ~contains(collector, '"DetectionMetric", double(detected)'), ...
    "Detection-only and failed PRACH execution must not invent CRC or correlation evidence.");
dispatchStart = strfind(source, "function [state, T, correlationTraceT, evidence] =");
dispatchEnd = strfind(source, "function cfg = localApplyMeasuredSSBSelectionForRA");
assert(numel(dispatchStart) == 1 && numel(dispatchEnd) == 1 && dispatchEnd > dispatchStart);
dispatch = extractBetween(source, dispatchStart, dispatchEnd-1);
assert(contains(dispatch, 'receiveThrough = (slotIdx - 1) * sixgr.time.slotDurationSec(cfg)') && ...
    contains(dispatch, '"ReceiveThroughTime_s", receiveThrough') && ...
    contains(dispatch, 'attempt.Continuation = checkpoint;') && ...
    contains(dispatch, 'stages(previousCount+1:end, :)') && ...
    contains(dispatch, 'state.AccessState(ueIdx) = "pending";'), ...
    "The coupled dispatcher must retain bounded continuations and append only newly received stages.");
assert(contains(source, 'if prachSignalOpportunityThisSlot && ~hadPendingRA'), ...
    "An already pending attempt must not start a second Msg1 on another PRACH opportunity.");
ok = true;
fprintf("PASS testFourStepRAResultAdapterDependencies: RA adapter dependencies and failure provenance are explicit.\n");
end
