function ok = testNewDataFrozenGrantNotRefrozen()
%TESTNEWDATAFROZENGRANTNOTREFROZEN Preserve scheduler spatial authority.

setup6GRSimToolkit("Verbose", false);
scenario = sixgr.lls6g.config.loadScenarioConfig(fullfile(pwd, ...
    "simulator", "configs", "scenarios", ...
    "webgui_sinr_sweep_64x4_mu_mimo_repair_slice.yaml"));
cfg = sixgr.lls6g.buildInternalConfig(scenario, tempdir);

% Four configured RF chains feed four logical ports.  A scheduled rank-two
% user receives its own 4x2 logical baseband matrix and exact 64x2 physical
% precoder, while the frozen hardware architecture remains 64x4.
F = complex(zeros(64, 4));
for port = 1:4
    rows = (port-1)*16 + (1:16);
    F(rows, port) = exp(1j * 2*pi*(0:15).' * (port-1) / 16) / 4;
end
% One scheduled UE owns unit total precoder power across both layers.
% Four coefficients of magnitude 1/2 give ||W||_F^2 = 1.
W = [1 0; 0 1; 1 0; 0 1] / 2;
P = F * W;
cfgFreeze = cfg;
cfgFreeze.phy.pdsch.hybridElementToPortMatrix = F;
cfgFreeze.phy.pdsch.numPorts = 4;
cfgFreeze.phy.pdsch.nPorts = 4;
cfgFreeze.phy.pdsch.numRFChains = 4;

grant = struct( ...
    "Direction", "DL", "Frame", 1, "Slot", 6, ...
    "RNTI", 3, "UEIndex", 3, "ServingCell", 1, ...
    "PRBSet", 0:11, "SymbolAllocation", [2 12], ...
    "Modulation", "QPSK", "MCSIndex", 1, ...
    "TargetCodeRate", 0.1884765625, ...
    "NumLayers", 2, "Layers", 2, ...
    "NumLogicalPorts", 4, "NumRFChains", 4, ...
    "PrecodingMatrixLogicalPorts", W, ...
    "PrecodingMatrix", P, ...
    "HybridElementToPortMatrix", F, ...
    "TBSBits", 1192, "TBSBytes", 149, ...
    "TransportBlockSize", 1192, ...
    "IsRetransmission", false, ...
    "HARQ", struct("IsRetransmission", false, "NDI", true), ...
    "ExactPHYFeasibilityChecked", true, ...
    "ExactPHYFeasible", true, ...
    "DCI", struct("BitExactPDCCHPayload", true, ...
        "Bits", int8([0; 1; 0; 1])), ...
    "ControlDecodeOk", true, ...
    "PDCCHGrantBindingOk", true, ...
    "PDCCHGrantDCIId", "phase19-slot6-dci", ...
    "PDCCHGrantDCIFieldsHash", repmat('a', 1, 64), ...
    "PDCCHGrantFieldsHash", repmat('a', 1, 64), ...
    "GrantContextId", "phase19-slot6-new-data-regression");
phyGrant = sixgr.phy.grant.freezePHYGrant(cfgFreeze, "DL", grant, ...
    "SNR_dB", 20, "Frame", 1, "Slot", 6);
tbsBits = double(phyGrant.CodingLayout.TBSBits);
tb = zeros(tbsBits, 1, "int8");
grant.TBSBits = tbsBits;
grant.TBSBytes = floor(tbsBits/8);
grant.TransportBlockSize = tbsBits;
grant.ScheduledTransportBlockSize = tbsBits;
grant.HARQTBContext = struct("TBSBits", tbsBits, "NDI", true, ...
    "OriginalNumLayers", 2);
grant.PHYGrant = phyGrant;

% Reproduce the transient per-user mirror that killed Phase-19 slot 6: it
% contains this user's 64x2 selected beam, not the shared 64x4 RF matrix.
% New-data execution must consume the already frozen PHYGrant and must not
% refreeze from this stale mirror.
cfgExecute = cfg;
cfgExecute.phy.pdsch.hybridElementToPortMatrix = P;
out = sixgr.link.runDLPDSCHThroughput(cfgExecute, ...
    "NumFrames", 1, "SNR_dB", 20, ...
    "StartFrameIndex", 1, "StartSlotIndex", 6, ...
    "GrantSnapshot", grant, "PHYGrant", phyGrant, ...
    "TransportBlockBits", tb);
assert(istable(out.TrialTable) && height(out.TrialTable) == 1, ...
    "The frozen new-data grant must reach one production waveform trial.");
assert(double(out.TrialTable.Layers(1)) == 2 && ...
    logical(out.TrialTable.HybridElementDomainApplied(1)) && ...
    double(out.TrialTable.PhysicalTxAntennas(1)) == 64 && ...
    double(out.TrialTable.TxWaveformColumns(1)) == 64, ...
    "The executed trial must preserve rank two, four RF chains and 64 physical columns.");

% A HARQ retransmission is refrozen to bind current-slot control, but its
% first-transmission RF architecture remains authoritative.  Reproduce the
% full-run failure using the same stale 64x2 per-user cfg against the frozen
% 64x4 grant.
replayGrant = grant;
replayGrant.IsRetransmission = true;
replayGrant.HARQ.IsRetransmission = true;
replayState = struct("CurrentFrame", 2, "CurrentSlot", 41);
replayHARQ = struct("HarqID", 0, "HARQProcess", 0, "NDI", true, ...
    "NDIEpoch", 1, "RV", 2, "IsRetransmission", true, ...
    "TransportBlockContext", grant.HARQTBContext);
refrozen = sixgr.truth.CoupledTruthRuntime. ...
    refreezeReplayGrantPHYContractRuntime( ...
    cfgExecute, replayGrant, "DL", replayState, replayHARQ);
assert(isequal(size(refrozen.PHYGrant.PrecodingState.HybridElementToPortMatrix), ...
    [64 4]) && ...
    isequal(refrozen.PHYGrant.PrecodingState.HybridElementToPortMatrix, F) && ...
    double(refrozen.PHYGrant.AntennaArchitecture.NumRFChains) == 4 && ...
    double(refrozen.PHYGrant.AntennaArchitecture.NumLogicalPorts) == 4, ...
    "HARQ refreeze must restore the exact frozen 64x4 RF architecture before replay.");
ok = true;
end
