function ok = testRecoveryImmutableConfigAuthority()
%TESTRECOVERYIMMUTABLECONFIGAUTHORITY Recovery rejects mutable YAML drift.

setup6GRSimToolkit("Verbose", false);
root = string(tempname);
mkdir(root);
cleanup = onCleanup(@() rmdir(root, "s")); %#ok<NASGU>
metaDir = fullfile(root, "meta");
airDir = fullfile(root, "air_interface", "csv");
mkdir(metaDir);
mkdir(airDir);

executed = sixgr.lls6g.config.loadScenarioConfig( ...
    "simulator/configs/scenarios/webgui_sinr_sweep_64x4_mu_mimo_full.yaml");
drifted = sixgr.lls6g.config.loadScenarioConfig( ...
    "simulator/configs/scenarios/master_geometry_based.yaml");
assert(executed.ConfigHash ~= drifted.ConfigHash);
sixgr.util.jsonWrite(fullfile(metaDir, "scenario_config_resolved.json"), executed.toStruct());
snapshotPath = fullfile(metaDir, "scenario_config_resolved.json");
fid = fopen(snapshotPath, "r");
cleanupFile = onCleanup(@() fclose(fid)); %#ok<NASGU>
snapshotDigest = sixgr.util.sha256Hex(fread(fid, Inf, "*uint8"));
clear cleanupFile;
sixgr.util.jsonWrite(fullfile(metaDir, "scenario_config_identity.json"), struct( ...
    "SchemaVersion", "sixgr_resolved_config_identity/v1", ...
    "ScenarioID", executed.ScenarioID, ...
    "ConfigHash", executed.ConfigHash, ...
    "ResolvedJSONSHA256", snapshotDigest));
sourceT = table(executed.SourceFiles(:), 'VariableNames', {'SourceConfigFile'});
sixgr.util.csvWriteTable(fullfile(metaDir, "scenario_source_chain.csv"), sourceT);
trialT = table(repmat(executed.ConfigHash, 2, 1), ...
    'VariableNames', {'ConfigHash'});
sixgr.util.csvWriteTable(fullfile(airDir, "prach_trials.csv"), trialT);

[resolved, authority] = sixgr.truth.resolveRecoveryScenarioConfig(root, drifted);
assert(resolved.ConfigHash == executed.ConfigHash && authority.ExactMatch && ...
    authority.Authority == "persisted_resolved_config_snapshot", ...
    ["Recovery must use the persisted exact config instead of a later supplied YAML revision. " + ...
    "resolved=%s executed=%s expected=%s persisted=%s supplied=%s authority=%s exact=%d"], ...
    char(resolved.ConfigHash), char(executed.ConfigHash), ...
    char(authority.ExpectedConfigHash), char(authority.PersistedSnapshotHash), ...
    char(authority.SuppliedConfigHash), char(authority.Authority), authority.ExactMatch);

% A legacy fixed-MCS snapshot predating the now-explicit CSI feedback-delay
% field remains valid immutable evidence because no CQI/OLLA decision was
% active. Recovery may accept it only as a recorded compatibility gap.
legacyFixed = executed.toStruct();
legacyFixed.link_adaptation.fixed_or_amc = "fixed";
legacyFixed.link_adaptation.pdsch_link_adaptation_policy = "fixed";
legacyFixed.link_adaptation.pusch_link_adaptation_policy = "fixed";
legacyFixed.link_adaptation = rmfield(legacyFixed.link_adaptation, ...
    "feedback_delay_slots");
legacyFixedHash = sixgr.lls6g.config.hashResolvedScenario(legacyFixed);
sixgr.util.jsonWrite(snapshotPath, legacyFixed);
fid = fopen(snapshotPath, "r");
cleanupFile = onCleanup(@() fclose(fid)); %#ok<NASGU>
legacyFixedDigest = sixgr.util.sha256Hex(fread(fid, Inf, "*uint8"));
clear cleanupFile;
sixgr.util.jsonWrite(fullfile(metaDir, "scenario_config_identity.json"), struct( ...
    "SchemaVersion", "sixgr_resolved_config_identity/v1", ...
    "ScenarioID", executed.ScenarioID, ...
    "ConfigHash", legacyFixedHash, ...
    "ResolvedJSONSHA256", legacyFixedDigest));
sixgr.util.csvWriteTable(fullfile(airDir, "prach_trials.csv"), ...
    table(repmat(legacyFixedHash, 2, 1), 'VariableNames', {'ConfigHash'}));
[resolvedLegacyFixed, legacyFixedAuthority] = ...
    sixgr.truth.resolveRecoveryScenarioConfig(root, executed);
assert(resolvedLegacyFixed.ConfigHash == legacyFixedHash && ...
    legacyFixedAuthority.ExactMatch && ...
    legacyFixedAuthority.Authority == "persisted_resolved_config_snapshot" && ...
    ~legacyFixedAuthority.PersistedSnapshotCurrentCompatibilityOk && ...
    legacyFixedAuthority.PersistedSnapshotCompatibilityStatus == ...
    "legacy_inactive_link_adaptation_feedback_delay_missing", ...
    "Inactive fixed-MCS legacy feedback-delay gaps must be explicit recovery compatibility evidence.");

% Restore the current-schema immutable fixture for the remaining checks.
sixgr.util.jsonWrite(snapshotPath, executed.toStruct());
fid = fopen(snapshotPath, "r");
cleanupFile = onCleanup(@() fclose(fid)); %#ok<NASGU>
snapshotDigest = sixgr.util.sha256Hex(fread(fid, Inf, "*uint8"));
clear cleanupFile;
sixgr.util.jsonWrite(fullfile(metaDir, "scenario_config_identity.json"), struct( ...
    "SchemaVersion", "sixgr_resolved_config_identity/v1", ...
    "ScenarioID", executed.ScenarioID, ...
    "ConfigHash", executed.ConfigHash, ...
    "ResolvedJSONSHA256", snapshotDigest));
sixgr.util.csvWriteTable(fullfile(airDir, "prach_trials.csv"), trialT);

% A completed-run recovery may be published into a different folder, but
% its logical RunTag remains immutable because raw configuration-application
% rows and all other primary evidence are bound to that identity.
sourceRunTag = "immutable_source_run";
sixgr.util.jsonWrite(fullfile(metaDir, "scenario_manifest.json"), struct( ...
    "RunFolder", fullfile(fileparts(root), sourceRunTag), ...
    "ConfigHash", executed.ConfigHash));
caughtIdentityMismatch = false;
caughtIdentifier = "";
try
    sixgr.truth.recoverLLSRunArtifacts(root, executed, ...
        "RunTag", "different_recovery_tag", ...
        "PublicRunFolder", root, ...
        "FinalizationMode", "completed_run_refinalization");
catch ME
    caughtIdentifier = string(ME.identifier);
    caughtIdentityMismatch = string(ME.identifier) == ...
        "sixgr:truth:recover:RunTagIdentityMismatch";
end
assert(caughtIdentityMismatch, ...
    sprintf(['Completed-run recovery must reject a RunTag that conflicts ' ...
    'with immutable source identity. Observed identifier: %s'], ...
    char(caughtIdentifier)));

% Legacy runners stored report-only fields in the resolved snapshot.  The
% file remains digest-checked but cannot be executable config authority;
% recovery must select an exact supplied configuration with the same
% runtime-bound ConfigHash.
legacyView = executed.toStruct();
legacyView.reporting_semantics = struct("configured_parameters_are_nominal", true);
legacyView.resolved_runtime_view = struct("active_grid_num_rbs", 273);
sixgr.util.jsonWrite(snapshotPath, legacyView);
fid = fopen(snapshotPath, "r");
cleanupFile = onCleanup(@() fclose(fid)); %#ok<NASGU>
legacyDigest = sixgr.util.sha256Hex(fread(fid, Inf, "*uint8"));
clear cleanupFile;
sixgr.util.jsonWrite(fullfile(metaDir, "scenario_config_identity.json"), struct( ...
    "SchemaVersion", "sixgr_resolved_config_identity/v1", ...
    "ScenarioID", executed.ScenarioID, ...
    "ConfigHash", executed.ConfigHash, ...
    "ResolvedJSONSHA256", legacyDigest));
[resolvedLegacy, legacyAuthority] = ...
    sixgr.truth.resolveRecoveryScenarioConfig(root, executed);
assert(resolvedLegacy.ConfigHash == executed.ConfigHash && ...
    legacyAuthority.ExactMatch && ...
    legacyAuthority.Authority == "supplied_exact_resolved_config", ...
    "Legacy derived snapshots must fall back only to exact executable configuration authority.");

sixgr.util.jsonWrite(fullfile(metaDir, "scenario_config_resolved.json"), drifted.toStruct());
caught = false;
try
    sixgr.truth.resolveRecoveryScenarioConfig(root, drifted);
catch ME
    caught = ismember(string(ME.identifier), [ ...
        "sixgr:truth:recover:ImmutableConfigUnavailable", ...
        "sixgr:truth:recover:ResolvedConfigSnapshotDigestMismatch"]);
end
assert(caught, ...
    "Recovery must fail closed when neither available resolved config matches runtime evidence.");
ok = true;
end
