function ok = testPDSCHTwoCodewordCoding()
%TESTPDSCHTWOCODEWORDCODING Explicit independent plans for rank-5 CW0/CW1.

setup6GRSimToolkit("Verbose", false, "RunToolboxChecks", false);
rng(52128, "twister");
cfg = [ ...
    struct("A",1536, "R",0.42, "Mod","16QAM", "Qm",4, "NL",2, "RV",0), ...
    struct("A",4096, "R",0.68, "Mod","64QAM", "Qm",6, "NL",3, "RV",2)];
plans = cell(1, 2);
bits = cell(1, 2);
for cw = 1:2
    seg = sixgr.pdsch.oracle.LDPCSegmentationSpec(cfg(cw).A, cfg(cw).R);
    quantum = cfg(cw).Qm * cfg(cw).NL;
    G = quantum * ceil(seg.MotherCodeLength * seg.NumCodeBlocks / quantum);
    plans{cw} = sixgr.pdsch.DLSCHCodingPlan.resolve( ...
        "TransportBlockSize", cfg(cw).A, ...
        "TargetCodeRate", cfg(cw).R, ...
        "RateMatchedBitCount", G, ...
        "RV", cfg(cw).RV, ...
        "Modulation", cfg(cw).Mod, ...
        "NumLayers", cfg(cw).NL, ...
        "CodewordIndex", cw - 1);
    bits{cw} = int8(randi([0 1], cfg(cw).A, 1));
end

encoded = sixgr.pdsch.DLSCHEncoder(bits, plans);
llr = cellfun(@(x) 40 * (1 - 2 * double(x(:))), ...
    encoded.RateMatchedBits, "UniformOutput", false);
decoded = sixgr.pdsch.DLSCHDecoder( ...
    llr, "CodingPlan", plans, "MaxIterations", 12);

assert(decoded.NumCodewords == 2 && all(decoded.CRCPassPerCodeword), ...
    "Both explicitly planned codewords must pass CRC.");
assert(isequal(decoded.TransportBlocks{1}, bits{1}) && ...
    isequal(decoded.TransportBlocks{2}, bits{2}), ...
    "Two-codeword decoded TBs do not match their independent inputs.");
assert(string(plans{1}.PlanID) ~= string(plans{2}.PlanID), ...
    "Codeword plans must have distinct immutable identities.");
assert(isequal(double([plans{1}.NumLayers plans{2}.NumLayers]), [2 3]), ...
    "Rank-5 codeword layer split must remain [2 3].");
fprintf("PDSCH two-codeword coding: rank=5 layers=[2 3], CRC pass=2/2, bit errors=0\n");
ok = true;
end
