function ok = testFlexibleSymbolAllocator()
%TESTFLEXIBLESYMBOLALLOCATOR Validate runtime DL/UL/GUARD decisions.

setup6GRSimToolkit("Verbose", false);
p = struct("PeriodicityMilliseconds", 1, ...
    "NumDownlinkSlots", 0, "NumDownlinkSymbols", 4, ...
    "NumUplinkSlots", 0, "NumUplinkSymbols", 2);
common = sixgr.phy.frame.TDDCommonConfig.resolve( ...
    "ReferenceSubcarrierSpacingKHz", 15, ...
    "ActiveSubcarrierSpacingKHz", 15, "Pattern1", p);
before = common.CommonDirection;

requests = [ ...
    localRequest(0, 4, 4, "DL", "PDSCH"); ...
    localRequest(0, 8, 2, "GUARD", "RF_SWITCH"); ...
    localRequest(0, 10, 2, "UL", "PUSCH")];
state = sixgr.phy.frame.FlexibleSymbolAllocator.allocate( ...
    common, requests, "MinimumGuardSymbols", 2);
assert(isequal(common.CommonDirection, before), ...
    "Runtime allocation mutated common ownership.");
assert(all(state.ResolvedDirection(1, 5:8) == "DL"));
assert(all(state.ResolvedDirection(1, 9:10) == "GUARD"));
assert(all(state.ResolvedDirection(1, 11:12) == "UL"));
assert(all(state.ResolvedDirection(1, 13:14) == "U"));
assert(all(state.AllocationOwner(1, 5:8) == "PDSCH"));
assert(all(state.ResolutionSource(1, 9:10) == "scheduler_runtime"));
guardAvailability = sixgr.phy.frame.SlotFormatResolver.isAvailable( ...
    state, 0, 8, 1, "DL");
assert(~guardAvailability.Available && ...
    guardAvailability.ReasonCode == "allocation_hits_guard");

localAssertError(@() sixgr.phy.frame.FlexibleSymbolAllocator.allocate( ...
    state, localRequest(0, 4, 4, "UL", "PUSCH")), ...
    "sixgr:phy:frame:ConflictingFlexibleSymbolResolution");
localAssertError(@() sixgr.phy.frame.FlexibleSymbolAllocator.allocate( ...
    common, localRequest(0, 0, 2, "UL", "PUCCH")), ...
    "sixgr:phy:frame:AllocationHitsFixedDL");
localAssertError(@() sixgr.phy.frame.FlexibleSymbolAllocator.allocate( ...
    common, localRequest(0, 0, 2, "UL", "PRACH")), ...
    "sixgr:phy:frame:AllocationHitsFixedDL");
localAssertError(@() sixgr.phy.frame.FlexibleSymbolAllocator.allocate( ...
    common, [localRequest(0, 4, 4, "DL", "PDSCH"); ...
    localRequest(0, 8, 4, "UL", "PUSCH")], ...
    "MinimumGuardSymbols", 1), ...
    "sixgr:phy:frame:InsufficientDirectionSwitchGuard");

% PRACH can use a flexible tail only after an explicit UL resolution.
prachState = sixgr.phy.frame.FlexibleSymbolAllocator.allocate( ...
    common, localRequest(0, 11, 1, "UL", "PRACH"));
a = sixgr.phy.frame.SlotFormatResolver.isAvailable( ...
    prachState, 0, 11, 3, "UL");
assert(a.Available);
ok = true;
end

function r = localRequest(slot, start, count, direction, channel)
r = struct("AbsoluteSlot", slot, "StartSymbol", start, ...
    "NumSymbols", count, "Direction", direction, "Channel", channel, ...
    "DecisionSource", "scheduler_runtime");
end

function localAssertError(f, id)
try
    f();
catch ME
    assert(string(ME.identifier) == string(id), ...
        "Observed %s, expected %s.", ME.identifier, id);
    return;
end
error("sixgr:test:ExpectedErrorNotThrown", "Expected %s.", id);
end
