function ok = testCausalSpatialPortRankDependency()
%TESTCAUSALSPATIALPORTRANKDEPENDENCY Verify one YAML-owned spatial contract.

setup6GRSimToolkit("Verbose", false);
root = fileparts(fileparts(mfilename("fullpath")));
scenarioPath = fullfile(root, "simulator", "configs", "scenarios", ...
    "lls_causal_access_to_data_wiring.yaml");
scenario = sixgr.lls6g.config.loadScenarioConfig(scenarioPath);
cfg = sixgr.lls6g.buildInternalConfig(scenario, fullfile(tempdir, ...
    "sixgr_causal_spatial_port_rank_dependency"));

dlLayers = double(sixgr.util.structGet(cfg, "phy.pdsch.nLayers", NaN));
dlPorts = double(sixgr.util.structGet(cfg, "phy.pdsch.numPorts", NaN));
dlDMRSPorts = double(sixgr.util.structGet(cfg, ...
    "phy.pdsch.dmrs.portSet", []));
ulLayers = double(sixgr.util.structGet(cfg, "phy.pusch.nLayers", NaN));
ulPorts = double(sixgr.util.structGet(cfg, ...
    "phy.pusch.NumAntennaPorts", NaN));
ulDMRSPorts = double(sixgr.util.structGet(cfg, ...
    "phy.pusch.dmrs.portSet", []));
csiPorts = double(sixgr.util.structGet(cfg, "phy.csirs.nPorts", NaN));
csiWeights = sixgr.util.structGet(cfg, "phy.csirs.precoderMatrices", []);
ssbWeights = sixgr.util.structGet(cfg, "phy.ssb.precoderMatrices", []);

assert(dlLayers == 2 && dlPorts == 2 && ...
    isequal(dlDMRSPorts(:).', 0:1), ...
    "PDSCH rank, antenna-port and DM-RS-port authorities diverged.");
assert(ulLayers == 2 && ulPorts == 2 && ...
    isequal(ulDMRSPorts(:).', 0:1), ...
    "PUSCH rank, antenna-port and DM-RS-port authorities diverged.");
assert(csiPorts == 2 && isequal(size(csiWeights), [2 2]), ...
    "CSI-RS ports/codebook must span the same two-port DL subspace.");
assert(size(csiWeights, 1) == double(cfg.antenna.bs.numElements) && ...
    rank(double(csiWeights)) == 2, ...
    "CSI-RS codebook does not span the configured physical BS array.");
assert(isequal(size(ssbWeights), [4 2]) && ...
    all(abs(sum(abs(ssbWeights).^2,2) - 1) < 1e-12) && ...
    numel(unique(string(sixgr.util.structGet(cfg, ...
        "phy.ssb.precoderIDs", strings(0,1))))) == 4, ...
    "SSB must expose four distinct unit-power beams on two physical elements.");

[dlBeamCandidates, dlBeamInfo] = sixgr.phy.dl.pmiCodebookCandidates( ...
    cfg, dlLayers, dlPorts, "Mode", "type1_su_mimo");
% TS 38.214 Table 5.2.2.2.1-1: the strict two-port rank-two PMI
% codebook has two matrices, independently of any beam sweep size.
% Use independent normative matrices, not the producer as the test oracle.
expectedRankTwo = cat(3, [1 1; 1 -1]/2, [1 1; 1i -1i]/2);
assert(double(dlBeamInfo.NumCandidates) == 2 && ...
    double(dlBeamInfo.NumBeams) == 2 && numel(dlBeamCandidates) == 2 && ...
    ~logical(dlBeamInfo.GenericDFTApproximationUsed) && ...
    contains(string(dlBeamInfo.Specification), "Table5.2.2.2.1-1"), ...
    "Strict two-port PMI must use the normative codebook, not a beam-sweep approximation.");
assert(isequal([dlBeamCandidates.PMI], [0 1]) && ...
    isequal([dlBeamCandidates.BeamIndices], [1 2]), ...
    "Zero-based PMI and one-based runtime candidate indices must remain distinct.");
for candidateIndex = 1:2
    assert(norm(double(dlBeamCandidates(candidateIndex).W) - ...
        expectedRankTwo(:,:,candidateIndex), "fro") <= 1e-12, ...
        "The strict rank-two PMI matrix differs from TS 38.214.");
end
assert(all(arrayfun(@(x) rank(double(x.W)) == dlLayers && ...
    isequal(size(x.W), [dlPorts dlLayers]) && ...
    norm(double(x.W)' * double(x.W) - eye(dlLayers)/dlLayers, "fro") <= 1e-10, ...
    dlBeamCandidates)), ...
    "A DL PMI candidate must preserve rank and unit total precoder power.");

bs = sixgr.rf.AntennaArrayFactory.build(cfg, "bs", ...
    "signal", "pdsch", "numPorts", dlPorts, "numRFChains", 2);
ue = sixgr.rf.AntennaArrayFactory.build(cfg, "ue", ...
    "signal", "pusch", "numPorts", ulPorts, "numRFChains", 2);
assert(bs.NumElements == 2 && bs.NumPorts == dlPorts && ...
    bs.NumRFChains == 2 && isequal(size(bs.PortToElementMatrix), [2 2]));
assert(ue.NumElements == 2 && ue.NumPorts == ulPorts && ...
    ue.NumRFChains == 2 && isequal(size(ue.PortToElementMatrix), [2 2]));
assert(isequal(double(bs.ElementSpacing_lambda), [0.5 0.5]) && ...
    isequal(double(ue.ElementSpacing_lambda), [0.5 0.5]));

mimoAudit = sixgr.mimo.validateMIMOConfigStrict(cfg);
assert(all(mimoAudit.Pass), ...
    "Strict spatial validation failed: %s", ...
    strjoin(cellstr(mimoAudit.FailureReason(~mimoAudit.Pass)), "; "));

cfg.phy.carrier.NFrame = 0;
cfg.phy.carrier.NSlot = 1; % YAML CSI-RS period/offset is 4:1.
carrier = sixgr.phy.grid.makeCarrier(cfg);
[~, ~, pdsch] = sixgr.phy.grid.allocREsPDSCH(carrier, cfg);
assert(double(pdsch.NumLayers) == dlLayers && ...
    isequal(double(pdsch.DMRS.DMRSPortSet(:).'), dlDMRSPorts(:).'));
% Freeze the selected unit-test grant before resolving a strict precoder;
% this also carries its matrix digest and active context into the resolver.
dlGrant = localFrozenGrantInput(cfg, "DL", dlLayers, dlPorts, expectedRankTwo(:,:,1));
dlGrant.K0 = 0; % Explicit same-slot control for this spatial-only fixture.
dlPHYGrant = sixgr.phy.grant.freezePHYGrant(cfg, "DL", dlGrant, ...
    "SNR_dB", double(cfg.channel.snr_dB), "Frame", 0, "Slot", 1);
cfgDLFrozen = sixgr.phy.grant.applyPHYGrantToConfig(cfg, dlPHYGrant);
dlPrecoder = sixgr.phy.dl.resolvePDSCHPrecoding(pdsch, cfgDLFrozen, ...
    "PrecodingMatrix", dlPHYGrant.PrecodingState.MatrixLogicalPorts, ...
    "FixedReferenceMode", false);
assert(double(dlPrecoder.NumLayers) == dlLayers && ...
    double(dlPrecoder.NumLogicalPorts) == dlPorts && ...
    isequal(size(dlPrecoder.MatrixLogicalPorts), [dlPorts dlLayers]));

[~, ~, pusch] = sixgr.phy.grid.allocREsPUSCH(carrier, cfg);
assert(double(pusch.NumLayers) == ulLayers && ...
    double(pusch.NumAntennaPorts) == ulPorts && ...
    isequal(double(pusch.DMRS.DMRSPortSet(:).'), ulDMRSPorts(:).'));
% Explicit unit-fixture SRS decision, not a measured runtime export. This
% test validates spatial plumbing; the SRS waveform/estimator has separate
% regressions. Production must still reject a missing SRS decision.
cfg.phy.pusch.srsDecision = struct("Authoritative", true, ...
    "MeasurementID", "unit_fixture_spatial_srs", "MeasurementSlot", 0, ...
    "RI", ulLayers, "NumPorts", ulPorts, "TPMI", double(pusch.TPMI));
ulPrecoder = sixgr.phy.ul.resolvePUSCHPrecoding(pusch, cfg, ...
    "FixedReferenceMode", false);
assert(double(ulPrecoder.NumLayers) == ulLayers && ...
    double(ulPrecoder.NumLogicalPorts) == ulPorts && ...
    isequal(size(ulPrecoder.MatrixLogicalPorts), [ulPorts ulLayers]));

% Execute the production transmitters, not a synthetic mapper, and verify
% the actual layer, logical-port, DM-RS and waveform domains.  Scheduled
% waveform entry points intentionally reject an unfrozen configuration-only
% call, so this regression must cross the same immutable-grant boundary as
% the connected runtime.
[dlTx, dlInfo] = sixgr.phy.dl.PDSCH_Tx(cfg, ...
    "PHYGrant", dlPHYGrant, "SchedulerGrantContext", dlGrant, ...
    "CompactOutput", false);
assert(size(dlTx.PDSCHLayerSymbols, 2) == dlLayers && ...
    size(dlTx.PDSCHPortSymbols, 2) == dlPorts && ...
    size(dlTx.DMRSAntennaSymbols, 2) == dlPorts && ...
    size(dlTx.Grid, 3) == dlPorts && size(dlTx.Waveform, 2) == dlPorts);
assert(logical(dlInfo.CodewordLayerMapping.ActualLayersEqualGrantLayers));
assert(double(dlTx.CSIRSRuntimeEvent.ResourceEvents(1).LogicalPortCount) == csiPorts && ...
    double(dlTx.CSIRSRuntimeEvent.PhysicalPortCount) == bs.NumElements);

ulGrant = localFrozenGrantInput(cfg, "UL", ulLayers, ulPorts, ulPrecoder.MatrixLogicalPorts);
ulGrant.TPMI = double(pusch.TPMI);
ulGrant.RI = ulLayers;
ulGrant.SRSCausalUsable = true;
ulGrant.SRSValid = true;
ulGrant.SRSCausalMeasurementId = "unit_fixture_spatial_srs";
ulGrant.LastSuccessfulSRSSlot = 0;
ulPHYGrant = sixgr.phy.grant.freezePHYGrant(cfg, "UL", ulGrant, ...
    "SNR_dB", double(cfg.channel.snr_dB), "Frame", 0, "Slot", 1);
[ulTx, ulInfo] = sixgr.phy.ul.PUSCH_Tx(cfg, ...
    "PHYGrant", ulPHYGrant, "CompactOutput", false);
assert(size(ulTx.PUSCHLayerSymbols, 2) == ulLayers && ...
    size(ulTx.PUSCHPortSymbols, 2) == ulPorts && ...
    size(ulTx.DMRSSymbols, 2) == ulLayers && ...
    size(ulTx.Grid, 3) == ulPorts && size(ulTx.Waveform, 2) == ulPorts);
assert(double(ulInfo.CodewordLayerMapping.NumLayers) == ulLayers && ...
    sum(double(ulInfo.CodewordLayerMapping.LayerCountPerCodeword)) == ulLayers);

% Exercise the production SSB transmitter. Four time-multiplexed SSBs are
% composed with four YAML-selected weight vectors onto the same two
% physical gNB elements. Beam count is therefore independent of rank and
% can exceed physical element count without creating extra spatial layers.
[ssbWaveform, ssbInfo, ssbTx] = sixgr.phy.dl.SSB_Tx( ...
    cfg, "NumSubframes", 2, "SSBIndex", 0);
assert(size(ssbWaveform,2) == bs.NumElements && ...
    double(ssbTx.NumTransmitAntennas) == bs.NumElements && ...
    string(ssbTx.WaveformDomain) == "physical_element_domain");
assert(all(logical(ssbTx.SSBBurstPlan.ActiveBitmap)) && ...
    numel(unique(string(ssbTx.SSBBurstPlan.PrecoderMatrixSHA256))) == 4);
assert(isstruct(ssbInfo) && isfield(ssbInfo,"SSBComposite") && ...
    logical(ssbInfo.SSBComposite.Composed) && ...
    double(ssbInfo.SSBComposite.ComponentCount) == 4);

fprintf(['Causal spatial contract: 4 SSB sweep beams and 2 strict rank-two PMI candidates ' ...
    'over BS/UE 2 elements, 2 RF chains, 2 logical ports, rank 2, DM-RS [0 1], ' ...
    'CSI-RS 2-port and exact PDSCH/PUSCH layer-to-port waveforms PASS.\n']);
ok = true;
end

function grant = localFrozenGrantInput(cfg, direction, nLayers, nPorts, W)
direction = upper(string(direction));
if direction == "DL"
    linkCfg = cfg.phy.pdsch;
else
    linkCfg = cfg.phy.pusch;
end
grant = struct( ...
    "Direction", char(direction), ...
    "Frame", 0, "Slot", 1, "RNTI", 1, "UEIndex", 1, ...
    "ServingCell", 1, ...
    "PRBSet", double(linkCfg.prbSet(:).'), ...
    "SymbolAllocation", double(linkCfg.symbolAllocation(:).'), ...
    "Modulation", char(string(linkCfg.modulation)), ...
    "NumLayers", double(nLayers), "Layers", double(nLayers), ...
    "NumLogicalPorts", double(nPorts), ...
    "TargetCodeRate", double(linkCfg.codeRate), ...
    "MCSIndex", double(linkCfg.mcsIndex), "MCS", double(linkCfg.mcsIndex), ...
    "PrecodingMatrix", double(W), "PrecodingActive", true, ...
    "ControlDecodeOk", true, ...
    "PDCCHGrantBindingRequired", true, ...
    "PDCCHGrantBindingOk", true, ...
    "PDCCHGrantBindingStatus", "pass", ...
    "PDCCHGrantDCIId", char(direction + "-causal-spatial-dci"), ...
    "PDCCHGrantDCIFieldsHash", "causal_spatial_exact_grant", ...
    "PDCCHGrantFieldsHash", "causal_spatial_exact_grant", ...
    "DCICrcPass", true, "PDCCHPayloadMatch", true, ...
    "PDCCHCausalGrantDecodeOk", true, "GrantValid", true, ...
    "GrantContextId", char(direction + "|causal-spatial-regression|frame=0|slot=1"), ...
    "HARQ", struct("HarqID", 0, "NDI", true, "RV", 0, ...
        "IsRetransmission", false));
end
