function ok = testPDSCHCompatibilityFacadeDelegation()
%TESTPDSCHCOMPATIBILITYFACADEDELEGATION Prove façade direction and guards.

setup6GRSimToolkit("Verbose", false);
fixture = StrictPDSCHChainFixture.create(2);
assignment = localConnectedAssignment(fixture.Assignment);
integrationContext = StrictPDSCHChainFixture.integrationContext( ...
    assignment, fixture.PrecoderBundle);
cfg = struct("run", struct( ...
    "pdschExecutionProfile", "connected_strict", ...
    "strictMode", true));

[tx, txInfo] = sixgr.phy.dl.PDSCH_Tx(cfg, ...
    "Carrier", fixture.Carrier, ...
    "TransportBlockBits", fixture.TransportBlocks, ...
    "Assignment", assignment, ...
    "ResourcePlan", fixture.ResourcePlan, ...
    "ReferenceSignalConfig", fixture.ReferenceConfig, ...
    "PrecoderBundle", fixture.PrecoderBundle, ...
    "IntegrationContext", integrationContext, ...
    "ExecutionProfile", "connected_strict");
assert(string(tx.ContractVersion) == "ExplicitPDSCHTransmitter/v1");
assert(logical(tx.CanonicalDelegation) ...
    && string(tx.DelegationTarget) == "sixgr.pdsch.PDSCHTransmitter");
assert(logical(tx.StrictSchedulingOwnership) ...
    && string(tx.SchedulingOwnership) ...
    == "immutable_pdsch_scheduling_assignment");
assert(string(tx.Source) == "explicit_pdsch_dlsch_production_chain");
assert(tx.IntegrationBinding.Status == "PASS");
assert(tx.IntegrationBinding.AssignmentId == assignment.AssignmentId);
assert(tx.IntegrationBinding.PrecoderBinding.PrecoderBundleDigest ...
    == fixture.PrecoderBundle.ImmutableBundleDigest);
assert(logical(txInfo.CanonicalDelegation) ...
    && string(txInfo.DelegationTarget) ...
    == "sixgr.pdsch.PDSCHTransmitter");
assert(isequal(tx.StageTrace.Stage, [ ...
    "assignment";"resource_plan";"dlsch_coding";"scrambling"; ...
    "modulation";"layer_mapping";"precoding";"dmrs_generation"; ...
    "ptrs_generation";"reference_mapping";"resource_grid"; ...
    "ofdm_modulation"]));

[rx, rxInfo] = sixgr.phy.dl.PDSCH_Rx(tx.Waveform, cfg, ...
    "Carrier", fixture.Carrier, ...
    "Assignment", assignment, ...
    "ResourcePlan", fixture.ResourcePlan, ...
    "ReferenceSignalConfig", fixture.ReferenceConfig, ...
    "ReceiverConfig", fixture.ReceiverConfig, ...
    "CodingPlan", tx.CodingPlans, ...
    "PrecoderBundle", fixture.PrecoderBundle, ...
    "IntegrationContext", integrationContext, ...
    "ExecutionProfile", "connected_strict");
assert(string(rx.ContractVersion) == "ExplicitPDSCHReceiver/v1");
assert(logical(rx.CanonicalDelegation) ...
    && string(rx.DelegationTarget) == "sixgr.pdsch.PDSCHReceiver");
assert(logical(rx.StrictSchedulingOwnership));
assert(string(rx.Source) == "explicit_pdsch_dlsch_production_receiver");
assert(rx.IntegrationBinding.BindingDigest ...
    == tx.IntegrationBinding.BindingDigest);
assert(logical(rxInfo.CanonicalDelegation) ...
    && string(rxInfo.DelegationTarget) == "sixgr.pdsch.PDSCHReceiver");
assert(rx.CRCPass && rx.Ok);
assert(isfinite(double(rx.DecodeLatency_s)) && double(rx.DecodeLatency_s) >= 0, ...
    "The compatibility facade must retain the measured canonical LDPC decode latency.");
assert(string(rx.DecodeLatencySource) == "receiver_instrumented_ldpc_decode", ...
    "The compatibility facade must identify the receiver-instrumented latency source.");
assert(numel(rx.DecodeLatencyPerCodeword_s) == numel(tx.CodingPlans) && ...
    all(isfinite(double(rx.DecodeLatencyPerCodeword_s))), ...
    "The compatibility facade must retain one measured decoder latency per codeword.");
assert(isequal(int8(rx.TransportBlock(:)), ...
    int8(vertcat(fixture.TransportBlocks{:}))));
assert(isequal(string(cellfun(@(plan) plan.PlanID, ...
        rx.CodingPlans,"UniformOutput",false)), ...
        string(cellfun(@(plan) plan.PlanID, ...
        tx.CodingPlans,"UniformOutput",false))), ...
    "Strict TX/RX coding-plan identifiers must be identical.");

localAssertIdentifier(@() sixgr.phy.dl.PDSCH_Tx(cfg, ...
    "ExecutionProfile", "connected_strict"), ...
    "sixgr:pdsch:MissingSchedulingAssignment");
localAssertIdentifier(@() sixgr.phy.dl.PDSCH_Rx( ...
    tx.Waveform, cfg, "ExecutionProfile", "connected_strict"), ...
    "sixgr:pdsch:MissingSchedulingAssignment");
localAssertIdentifier(@() sixgr.phy.dl.PDSCH_Rx( ...
    tx.Waveform, cfg, ...
    "Carrier", fixture.Carrier, ...
    "Assignment", assignment, ...
    "ResourcePlan", fixture.ResourcePlan, ...
    "ReferenceSignalConfig", fixture.ReferenceConfig, ...
    "ReceiverConfig", fixture.ReceiverConfig, ...
    "PrecoderBundle", fixture.PrecoderBundle, ...
    "IntegrationContext", integrationContext, ...
    "ExecutionProfile", "connected_strict"), ...
    "sixgr:pdsch:PDSCHReceiver:MissingCodingPlan");
localAssertIdentifier(@() sixgr.phy.dl.PDSCH_Tx(cfg, ...
    "Carrier", fixture.Carrier, ...
    "PDSCH", nrPDSCHConfig, ...
    "TransportBlockBits", fixture.TransportBlocks, ...
    "Assignment", assignment, ...
    "ResourcePlan", fixture.ResourcePlan, ...
    "ReferenceSignalConfig", fixture.ReferenceConfig, ...
    "PrecoderBundle", fixture.PrecoderBundle, ...
    "ExecutionProfile", "connected_strict"), ...
    "sixgr:pdsch:LegacyOverrideNotAllowed");

localAssertIdentifier(@() sixgr.phy.dl.PDSCH_Tx(cfg, ...
    "Carrier", fixture.Carrier, ...
    "TransportBlockBits", fixture.TransportBlocks, ...
    "Assignment", assignment, ...
    "ResourcePlan", fixture.ResourcePlan, ...
    "ReferenceSignalConfig", fixture.ReferenceConfig, ...
    "PrecoderBundle", fixture.PrecoderBundle, ...
    "ExecutionProfile", "connected_strict"), ...
    "sixgr:pdsch:MissingIntegrationContext");

localAssertIdentifier(@() sixgr.phy.dl.PDSCH_Tx(cfg, ...
    "Carrier", fixture.Carrier, ...
    "TransportBlockBits", fixture.TransportBlocks, ...
    "Assignment", assignment, ...
    "ResourcePlan", fixture.ResourcePlan, ...
    "ReferenceSignalConfig", fixture.ReferenceConfig, ...
    "IntegrationContext", integrationContext, ...
    "ExecutionProfile", "connected_strict"), ...
    "sixgr:pdsch:MissingPrecoderTCIBinding");

staleEpoch = integrationContext;
staleEpoch.ConfigurationEpoch = staleEpoch.ConfigurationEpoch + 1;
localAssertIdentifier(@() sixgr.phy.dl.PDSCH_Tx(cfg, ...
    "Carrier", fixture.Carrier, ...
    "TransportBlockBits", fixture.TransportBlocks, ...
    "Assignment", assignment, ...
    "ResourcePlan", fixture.ResourcePlan, ...
    "ReferenceSignalConfig", fixture.ReferenceConfig, ...
    "PrecoderBundle", fixture.PrecoderBundle, ...
    "IntegrationContext", staleEpoch, ...
    "ExecutionProfile", "connected_strict"), ...
    "sixgr:pdsch:StaleUEConfigurationEpoch");

stalePrecoder = StrictPDSCHChainFixture.reversePRGBundle( ...
    fixture.PrecoderBundle);
localAssertIdentifier(@() sixgr.phy.dl.PDSCH_Tx(cfg, ...
    "Carrier", fixture.Carrier, ...
    "TransportBlockBits", fixture.TransportBlocks, ...
    "Assignment", assignment, ...
    "ResourcePlan", fixture.ResourcePlan, ...
    "ReferenceSignalConfig", fixture.ReferenceConfig, ...
    "PrecoderBundle", stalePrecoder, ...
    "IntegrationContext", integrationContext, ...
    "ExecutionProfile", "connected_strict"), ...
    "sixgr:pdsch:StalePrecoderTCIContext");

staleTCI = integrationContext;
staleTCI.ActivatedTCIStates.TCIStateId = ...
    staleTCI.ActivatedTCIStates.TCIStateId + 1;
localAssertIdentifier(@() sixgr.phy.dl.PDSCH_Rx( ...
    zeros(size(tx.Waveform)), cfg, ...
    "Carrier", fixture.Carrier, ...
    "Assignment", assignment, ...
    "ResourcePlan", fixture.ResourcePlan, ...
    "ReferenceSignalConfig", fixture.ReferenceConfig, ...
    "ReceiverConfig", fixture.ReceiverConfig, ...
    "CodingPlan", tx.CodingPlans, ...
    "PrecoderBundle", fixture.PrecoderBundle, ...
    "IntegrationContext", staleTCI, ...
    "ExecutionProfile", "connected_strict"), ...
    "sixgr:pdsch:TCIStateNotActivated");

outsideCarrier = StrictPDSCHChainFixture.cloneAssignment( ...
    assignment, "SymbolAllocation", ...
    [fixture.Carrier.SymbolsPerSlot - 1, 2]);
outsideContext = StrictPDSCHChainFixture.integrationContext( ...
    outsideCarrier, fixture.PrecoderBundle);
localAssertIdentifier(@() sixgr.pdsch.PDSCHTransmitter( ...
    fixture.TransportBlocks, outsideCarrier, fixture.ResourcePlan, ...
    fixture.Carrier, fixture.ReferenceConfig, ...
    "PrecoderBundle", fixture.PrecoderBundle, ...
    "IntegrationContext", outsideContext), ...
    "sixgr:pdsch:PDSCHTransmitter:SymbolAllocationOutsideCarrier");
localAssertIdentifier(@() sixgr.pdsch.PDSCHReceiver( ...
    zeros(size(tx.Waveform)), outsideCarrier, fixture.ResourcePlan, ...
    fixture.Carrier, fixture.ReferenceConfig, fixture.ReceiverConfig, ...
    "PrecoderBundle", fixture.PrecoderBundle, ...
    "IntegrationContext", outsideContext), ...
    "sixgr:pdsch:PDSCHReceiver:SymbolAllocationOutsideCarrier");

fprintf("PDSCH compatibility facades: bound canonical TX/RX passed; " + ...
    "11/11 typed ownership, coding-plan, stale-context, and carrier guards passed.\n");
ok = true;
end

function assignment = localConnectedAssignment(calibration)
data = calibration.toStruct();
data.AssignmentId = string(data.AssignmentId) + "-CONNECTED-FACADE";
data.Profile = "connected_strict";
data.Source = "decoded_dci+ue_context";
data.DecodedDCIId = "DCI-FACADE-001";
data.ScheduledDCIId = "";
data.ControlAuthority = "receiver_crc_valid_decode";
data.DCIFormat = "1_1";
data.DCICRCPass = true;
data.DecodedRNTI = data.RNTI;
data.DCIRNTIMatch = true;
data.PDCCHAbsoluteSlot = data.PDSCHAbsoluteSlot;
data.K0 = 0;
data.SearchSpaceId = "SS-FACADE";
data.CORESETId = "CORESET-FACADE";
data.TCIStateId = 3;
data.TransmissionConfigurationIndication = 3;
assignment = sixgr.pdsch.PDSCHSchedulingAssignment(data);
assignment.validateForExecution();
end

function localAssertIdentifier(fn, expected)
try
    fn();
catch ME
    assert(string(ME.identifier) == string(expected), ...
        "Expected %s, observed %s.", expected, ME.identifier);
    return;
end
error("testPDSCHCompatibilityFacadeDelegation:MissingError", ...
    "Expected typed error %s.", expected);
end
