function ok = testFixedMCSConfigModulationCoherence()
%TESTFIXEDMCSCONFIGMODULATIONCOHERENCE MCS table/index owns modulation/rate.

setup6GRSimToolkit("Verbose", false);
scenarioPath = fullfile(pwd, "simulator", "configs", "scenarios", ...
    "lls_4x4_rank2_bidirectional_focused_validation.yaml");
scfg = sixgr.lls6g.config.loadScenarioConfig(scenarioPath);
cfg = sixgr.lls6g.buildInternalConfig(scfg, ...
    fullfile(tempdir, "sixgr_fixed_mcs_config_coherence"));
assert(strcmpi(string(cfg.validation.run_class), ...
    "functional_waveform_validation"), ...
    "The explicit bounded functional run class must survive internal-config normalization.");

for direction = ["DL","UL"]
    if direction == "DL"
        channelCfg = cfg.phy.pdsch;
    else
        channelCfg = cfg.phy.pusch;
    end
    profile = sixgr.link.resolveMCSProfile( ...
        string(channelCfg.mcsTable), double(channelCfg.mcsIndex));
    assert(logical(profile.Valid), ...
        "%s fixed-MCS profile must resolve through the configured table.", direction);
    assert(strcmpi(string(channelCfg.modulation), string(profile.Modulation)), ...
        ["%s internal modulation must equal the configured MCS table result; " ...
        "legacy channel modulation fields may not overwrite it."], direction);
    assert(abs(double(channelCfg.codeRate) - double(profile.TargetCodeRate)) < 1e-12, ...
        "%s internal code rate must equal the configured MCS table result.", direction);
end

assert(strcmpi(string(cfg.phy.pusch.modulation), "QPSK") && ...
    double(cfg.phy.pusch.mcsIndex) == 4, ...
    "The regression fixture must specifically prove the former UL MCS-4/16QAM conflict.");

trialT = table(2, 2, "QPSK", 4, false, ...
    'VariableNames', {'Layers','RankIndicator','Modulation','MCS','IsWarmupFrame'});
summary = sixgr.truth.summarizeEffectiveOperatingPoint( ...
    scfg, trialT, trialT, cfg);
assert(summary.Configured.DL.Modulation == "QPSK" && ...
    summary.Configured.UL.Modulation == "QPSK", ...
    "Configured/effective status reduction must use the canonical internal " + ...
    "PHY modulation, not a contradictory unresolved legacy order field.");
assert(double(summary.Configured.DL.MCS) == 4 && ...
    double(summary.Configured.UL.MCS) == 4, ...
    "Configured/effective status reduction must use the applied internal MCS index.");
assert(double(summary.DL.ConfiguredMatchRate) == 1 && ...
    double(summary.UL.ConfiguredMatchRate) == 1, ...
    "Canonical internal QPSK/MCS-4 trial rows must reduce to an exact match.");
ok = true;
end
