function ok = testPDSCHRateMatchingIndependent()
%TESTPDSCHRATEMATCHINGINDEPENDENT Check RV0-3 indices against scalar oracle.

setup6GRSimToolkit("Verbose", false, "RunToolboxChecks", false);
cases = [ ...
    struct("A",24,    "R",0.50, "Mod","QPSK",  "Qm",2, "NL",1, "G",400), ...
    struct("A",384,   "R",0.50, "Mod","16QAM", "Qm",4, "NL",2, "G",1600), ...
    struct("A",4096,  "R",0.50, "Mod","64QAM", "Qm",6, "NL",1, "G",6000), ...
    struct("A",10000, "R",0.50, "Mod","256QAM","Qm",8, "NL",2, "G",16000)];

comparisons = 0;
for i = 1:numel(cases)
    cfg = cases(i);
    seg = sixgr.pdsch.oracle.LDPCSegmentationSpec(cfg.A, cfg.R);
    maps = cell(1, 4);
    for rv = 0:3
        oracle = sixgr.pdsch.oracle.RateMatchingIndexSpec( ...
            seg, cfg.G, rv, cfg.Qm, cfg.NL);
        plan = sixgr.pdsch.DLSCHCodingPlan.resolve( ...
            "TransportBlockSize", cfg.A, ...
            "TargetCodeRate", cfg.R, ...
            "RateMatchedBitCount", cfg.G, ...
            "RV", rv, ...
            "Modulation", cfg.Mod, ...
            "NumLayers", cfg.NL);
        map = plan.RateMatchPositionMapZeroBased;
        assert(double(plan.Ncb) == oracle.Ncb, ...
            "A=%d RV=%d Ncb mismatch.", cfg.A, rv);
        assert(double(plan.K0) == oracle.K0, ...
            "A=%d RV=%d k0 mismatch.", cfg.A, rv);
        assert(isequal(double(plan.EPerCodeBlock), oracle.EPerCodeBlock), ...
            "A=%d RV=%d E_r mismatch.", cfg.A, rv);
        assert(isequal(map.OutputBitIndex(:), oracle.OutputBitIndexZeroBased(:)), ...
            "A=%d RV=%d output-index mismatch.", cfg.A, rv);
        assert(isequal(map.MotherCodeBitIndex(:), ...
            oracle.MotherCodeBitIndexZeroBased(:)), ...
            "A=%d RV=%d mother-code bit-index mismatch.", cfg.A, rv);
        assert(isequal(map.CodeBlockIndex(:), ...
            oracle.CodeBlockIndexZeroBased(:)), ...
            "A=%d RV=%d code-block index mismatch.", cfg.A, rv);
        assert(isequal(map.MotherCodeLinearIndex(:), ...
            oracle.MotherCodeLinearIndexZeroBased(:)), ...
            "A=%d RV=%d linear-index mismatch.", cfg.A, rv);
        maps{rv + 1} = map.MotherCodeLinearIndex(:);
        comparisons = comparisons + 1;
    end
    assert(~isequal(maps{1}, maps{2}) && ~isequal(maps{1}, maps{3}), ...
        "A=%d redundancy versions must select different ordered positions.", cfg.A);
end

% Limited-buffer Nref changes Ncb and k0 and must remain position exact.
cfg = cases(3);
seg = sixgr.pdsch.oracle.LDPCSegmentationSpec(cfg.A, cfg.R);
nref = 3000;
for rv = 0:3
    oracle = sixgr.pdsch.oracle.RateMatchingIndexSpec( ...
        seg, cfg.G, rv, cfg.Qm, cfg.NL, nref);
    plan = sixgr.pdsch.DLSCHCodingPlan.resolve( ...
        "TransportBlockSize", cfg.A, ...
        "TargetCodeRate", cfg.R, ...
        "RateMatchedBitCount", cfg.G, ...
        "RV", rv, ...
        "Modulation", cfg.Mod, ...
        "NumLayers", cfg.NL, ...
        "Nref", nref);
    map = plan.RateMatchPositionMapZeroBased;
    assert(double(plan.Ncb) == oracle.Ncb && double(plan.K0) == oracle.K0, ...
        "Limited-buffer RV=%d Ncb/k0 mismatch.", rv);
    assert(isequal(map.MotherCodeLinearIndex(:), ...
        oracle.MotherCodeLinearIndexZeroBased(:)), ...
        "Limited-buffer RV=%d selected-position mismatch.", rv);
    comparisons = comparisons + 1;
end

fprintf(['PDSCH rate matching: %d independent RV/index comparisons ' ...
    '(including Nref); mismatches=0\n'], comparisons);
ok = true;
end
