function ok = testLLSPUSCHHARQACKRuntimeFeedback()
%TESTLLSPUSCHHARQACKRUNTIMEFEEDBACK Verify causal DL ACK transfer on PUSCH.

setup6GRSimToolkit("Verbose", false);

scenario = sixgr.lls6g.config.loadScenarioConfig(fullfile( ...
    "simulator", "configs", "scenarios", ...
    "lls_causal_access_to_data_wiring.yaml"));
resolved = sixgr.lls6g.buildInternalConfig(scenario, tempdir);
assert(logical(sixgr.util.structGet(resolved, ...
    "phy.pucch.uciOnPUSCHEnabled", false)) && ...
    string(sixgr.util.structGet(resolved, ...
    "phy.pusch.uciMultiplexingMode", "")) == ...
    "harq_ack_on_pusch_when_pucch_collides", ...
    ["The causal production scenario must explicitly authorize same-UE " ...
    "HARQ-ACK multiplexing on colliding PUSCH; safe pucch_only fallback " ...
    "would otherwise starve UL data."]);

rnti = 811;
dueSlot = 5;
harq = sixgr.l2.mac.HARQEntityDL(struct());
feedbackRows = repmat(localFeedbackRow(), 2, 1);
for bitIdx = 1:2
    sourceSlot = bitIdx;
    txp = harq.allocate(rnti, sourceSlot, 8, "NewData", true);
    harqId0 = double(txp.HARQ.HarqID);
    grant = struct( ...
        "Direction", "DL", "RNTI", rnti, "TBSBits", 64, ...
        "TBSBytes", 8, "HARQ", txp.HARQ, ...
        "HARQTBContext", struct("TBId", sprintf("DL-%d-%d-%d", ...
        rnti, sourceSlot, harqId0), "TBSBits", 64));
    grant.Modulation='QPSK'; grant.NumLayers=1; grant.TargetCodeRate=.3;
    grant.CodingLayout=sixgr.phy.phycode.resolveCodingLayout( ...
        'Direction','DL','TransportBlockSize',64,'TargetCodeRate',.3, ...
        'RV',double(txp.HARQ.RV),'Modulation','QPSK','NumLayers',1, ...
        'RateMatchedBitCount',2*ceil((64+24)/.3/2));
    harq.onTx(rnti, harqId0, zeros(64, 1, "uint8"), grant, sourceSlot);

    feedbackRows(bitIdx).Direction = "DL";
    feedbackRows(bitIdx).UEIndex = 1;
    feedbackRows(bitIdx).RNTI = rnti;
    feedbackRows(bitIdx).HarqID = harqId0;
    feedbackRows(bitIdx).SourceSlot = sourceSlot;
    feedbackRows(bitIdx).DueSlot = dueSlot;
    feedbackRows(bitIdx).Ack = bitIdx == 1;
    feedbackRows(bitIdx).CurrentDecodeOK = bitIdx == 1;
    feedbackRows(bitIdx).CombinedDecodeOK = bitIdx == 1;
    feedbackRows(bitIdx).ServingCell = 1;
    feedbackRows(bitIdx).BaseStationID = 1;
    feedbackRows(bitIdx).TBSBits = 64;
    feedbackRows(bitIdx).UCIBitCount = 1;
    feedbackRows(bitIdx).RequestedFormat = 0;
    feedbackRows(bitIdx).ResolvedFormat = 0;
    feedbackRows(bitIdx).PUCCHResourceId = "0";
    feedbackRows(bitIdx).PUCCHPRBStart = 0;
    feedbackRows(bitIdx).PUCCHPRBCount = 1;
    feedbackRows(bitIdx).PUCCHSymbolStart = 12;
    feedbackRows(bitIdx).PUCCHNumSymbols = 2;
    feedbackRows(bitIdx).UCIType = "harq_ack";
    feedbackRows(bitIdx).ControlResourceSource = "focused_runtime_fixture";
    feedbackRows(bitIdx).ControlResourceValidity = true;
    feedbackRows(bitIdx).FormatAdaptationReason = "none_strict_assignment";
    feedbackRows(bitIdx).PUCCHGrantId = sprintf("PUCCH-GRANT-%d", bitIdx);
end

state = struct( ...
    "CurrentSlot", dueSlot, "CurrentFrame", 1, "CurrentSNR_dB", 20, ...
    "SlotsPerFrame", 10, "CfgMobility", resolved, ...
    "MultiUser", struct("Enabled", true), ...
    "DLHarq", harq, "DLCombinedLLR", {cell(1, harq.NumProcesses)}, ...
    "DLSchedulers", {{[]}}, ...
    "PendingFeedbackTable", struct2table(feedbackRows), ...
    "PUCCHGrantTraceTable", table(), "HARQTimelineTable", table(), ...
    "HARQSummaryTable", table());
state.DLCombinedLLR{1, 1} = ones(8, 1);
state.DLCombinedLLR{1, 2} = ones(8, 1);
for bitIdx = 1:2
    state = sixgr.truth.CoupledTruthRuntime.schedulePUCCHGrantRuntime( ...
        state, state.PendingFeedbackTable(bitIdx, :));
end

% Reproduce the complete-run ordering: the future K2 PUSCH exists before
% the PDSCH decoder creates its due HARQ-ACK rows.  Reconciliation must bind
% those late-created rows before startSlot can execute standalone PUCCH.
queuedBeforeFeedback = struct( ...
    "Direction", "UL", "UEIndex", 1, "RNTI", rnti, ...
    "GrantContextId", "UL-PUSCH-UCI-LATE-5", "Slot", dueSlot, ...
    "ScheduledAbsoluteSlot", dueSlot);
% Exercise the production slot-entry boundary, not just its isolated
% overlap helper. These are declared reducer-test payloads, not PHY rows.
slotState=sixgr.truth.CoupledTruthRuntime.initialize(resolved,tempname, ...
    struct('Enabled',true,'NumUsers',1,'RNTIStart',rnti,'ExecutionModel','slot_coupled_truth'),struct(),10);
for field=["PendingFeedbackTable","PUCCHGrantTraceTable","DLHarq","DLCombinedLLR"]
    slotState.(field)=state.(field);
end
[slotState,slotGrant,slotBlocked]=sixgr.truth.CoupledTruthRuntime.startSlotWithQueuedUL( ...
    slotState,resolved,'UL',1,1,dueSlot,10,12,queuedBeforeFeedback,true);
assert(isempty(slotBlocked) && isequal(slotGrant.ExpectedUCIPayload.HARQACK,int8([1;0])) && ...
    all(slotState.PUCCHGrantTraceTable.MultiplexedOnPUSCH) && ...
    ~any(slotState.PUCCHGrantTraceTable.GrantExecutedFlag) && ...
    isempty(slotState.PUCCHExecutedCurrentSlotGrantSnapshot), ...
    'Slot entry must bind queued UL before any standalone PUCCH samples are emitted.');
[lateState, lateGrant, lateBlocked] = sixgr.truth.CoupledTruthRuntime. ...
    reconcileQueuedPUSCHAfterDLFeedbackRuntime( ...
    state, queuedBeforeFeedback, true);
assert(isempty(lateBlocked) && numel(lateGrant) == 1 && ...
    logical(lateGrant.UCIOnPUSCHApplied) && ...
    isequal(int8(lateGrant.ExpectedUCIBits(:)), int8([1; 0])) && ...
    all(string(lateState.PendingFeedbackTable.DeliveryMechanism) == "pusch_uci") && ...
    all(lateState.PUCCHGrantTraceTable.MultiplexedOnPUSCH), ...
    ["A PDSCH-created HARQ-ACK must late-bind to an already queued future " ...
    "PUSCH before standalone PUCCH execution."]);

blockedState = state;
[~, blockedGrant, blockedRows] = sixgr.truth.CoupledTruthRuntime. ...
    reconcileQueuedPUSCHAfterDLFeedbackRuntime( ...
    blockedState, queuedBeforeFeedback, false);
assert(isempty(blockedGrant) && height(blockedRows) == 1 && ...
    string(blockedRows.Reason(1)) == "harq_ack_pucch_due_same_slot_same_ue", ...
    "Without UCI-on-PUSCH, the colliding queued PUSCH must be suppressed.");

% A nonempty bit vector is not proof of an exact UCI transfer.  Reject a
% partially populated/stale grant unless the immutable PUCCH grant IDs and
% typed payload were bound through the pending feedback ledger.
unboundBitsGrant = queuedBeforeFeedback;
unboundBitsGrant.ExpectedUCIBits = int8([1; 0]);
unboundBitsGrant.UCIOnPUSCHApplied = true;
[~, unboundGrant, unboundRows] = sixgr.truth.CoupledTruthRuntime. ...
    reconcileQueuedPUSCHAfterDLFeedbackRuntime( ...
    blockedState, unboundBitsGrant, false);
assert(isempty(unboundGrant) && height(unboundRows) == 1, ...
    "Unbound ExpectedUCIBits must not bypass the same-UE PUCCH/PUSCH " + ...
    "collision guard without exact typed-payload lineage.");

puschGrant = struct( ...
    "Direction", "UL", "UEIndex", 1, "RNTI", rnti, ...
    "GrantContextId", "UL-PUSCH-UCI-5", "Slot", dueSlot);
[state, puschGrant] = sixgr.truth.CoupledTruthRuntime. ...
    multiplexDueHARQACKOnPUSCHRuntime(state, puschGrant, dueSlot);
assert(logical(puschGrant.UCIOnPUSCHApplied) && ...
    isequal(int8(puschGrant.ExpectedUCIBits(:)), int8([1; 0])) && ...
    double(puschGrant.UCIOnPUSCHFeedbackBitCount) == 2, ...
    "All same-UE due DL HARQ bits must be placed on the qualified PUSCH grant.");
assert(all(string(state.PendingFeedbackTable.DeliveryMechanism) == "pusch_uci") && ...
    all(state.PUCCHGrantTraceTable.MultiplexedOnPUSCH) && ...
    isempty(sixgr.truth.CoupledTruthRuntime. ...
    pucchFeedbackDueHARQACKRuntime(state, dueSlot)), ...
    "Transferred feedback must be excluded from standalone PUCCH execution.");

harqOut = struct( ...
    "GrantSnapshot", puschGrant, ...
    "ExpectedHARQACKBits", int8([1; 0]), ...
    "DecodedHARQACKBits", int8([1; 1]), ...
    "HARQACKDecodeStatus", "decoded_mismatch", ...
    "HARQACKContentMatch", false);
state = sixgr.truth.CoupledTruthRuntime. ...
    applyDecodedPUSCHHARQACKRuntime(state, harqOut);
assert(all(state.PendingFeedbackTable.Processed), ...
    "PUSCH-decoded HARQ-ACK must close every exact pending feedback row.");
assert(double(state.DLHarq.Stats.Ack) == 2 && ...
    double(state.DLHarq.Stats.Nack) == 0, ...
    ["The DL HARQ entity must consume receiver-decoded bits. The second " ...
    "false ACK proves expected bits were not substituted."]);
assert(all(cellfun(@isempty, state.DLCombinedLLR(1, 1:2))), ...
    "Observed ACKs must clear the matching DL soft buffers.");
traceT = state.PUCCHGrantTraceTable;
assert(~any(traceT.GrantExecutedFlag) && ~any(traceT.PUCCHDecodeOk) && ...
    all(traceT.RuntimeStateUpdated) && all(traceT.MultiplexedOnPUSCH), ...
    "PUSCH UCI consumption must not be mislabeled as a PUCCH waveform execution.");
assert(string(traceT.Status(1)) == "PASS" && string(traceT.Status(2)) == "FAIL" && ...
    ~logical(traceT.FalseAck(1)) && logical(traceT.FalseAck(2)) && ...
    all(string(traceT.RuntimeStateConsumer) == ...
    "HARQEntity.onFeedback_from_PUSCH_UCI"), ...
    "Transferred UCI evidence must expose exact match and false-ACK outcomes per bit.");

% Reproduce UL HARQ grant-snapshot reuse.  The retransmission grant carries
% the previous occasion's transient UCI fields, but a new DL feedback row is
% due on the new occasion.  Production must discard the stale binding and
% bind the new grant identity; replaying the already processed ACK is a
% causal runtime error.
nextDueSlot = dueSlot + 2;
nextFeedback = feedbackRows(1);
nextFeedback.SourceSlot = dueSlot + 1;
nextFeedback.DueSlot = nextDueSlot;
nextFeedback.HarqID = 2;
nextFeedback.Ack = true;
nextFeedback.CurrentDecodeOK = true;
nextFeedback.CombinedDecodeOK = true;
nextFeedback.PUCCHGrantId = "PUCCH-GRANT-REUSED-NEXT";
nextFeedback.DeliveryMechanism = "pucch";
nextFeedback.PUSCHGrantContextId = "";
nextFeedback.MultiplexedBitIndex = NaN;
nextFeedback.Processed = false;
state.PendingFeedbackTable = [state.PendingFeedbackTable; ...
    struct2table(nextFeedback, "AsArray", true)];
state = sixgr.truth.CoupledTruthRuntime.schedulePUCCHGrantRuntime( ...
    state, state.PendingFeedbackTable(end, :));
staleReusedGrant = puschGrant;
staleReusedGrant.Slot = nextDueSlot;
staleReusedGrant.ScheduledAbsoluteSlot = nextDueSlot;
staleReusedGrant.GrantContextId = "UL-PUSCH-UCI-REUSED-7";
[state, reboundGrant] = sixgr.truth.CoupledTruthRuntime. ...
    multiplexDueHARQACKOnPUSCHRuntime(state, staleReusedGrant, nextDueSlot);
assert(string(reboundGrant.UCIOnPUSCHFeedbackGrantIds) == ...
    "PUCCH-GRANT-REUSED-NEXT" && ...
    isequal(int8(reboundGrant.ExpectedUCIBits(:)), int8(1)) && ...
    double(reboundGrant.UCIOnPUSCHFeedbackSourceSlots) == dueSlot + 1 && ...
    double(reboundGrant.UCIOnPUSCHFeedbackHARQIds) == 2, ...
    ["A reused UL HARQ grant must clear the previous occasion's transient " ...
    "UCI binding and bind only the current due-slot feedback row."]);

canonicalTrace = sixgr.truth.CoupledTruthRuntime. ...
    canonicalizePersistedPUCCHGrantTraceTable(traceT);
assert(all(string(canonicalTrace.SourceClassification) == "active_integrated") && ...
    all(string(canonicalTrace.RuntimeMaterializationStatus) == ...
        "active_integrated_pusch_uci_feedback_runtime") && ...
    all(logical(canonicalTrace.ControlObservationAvailable)) && ...
    all(logical(canonicalTrace.FinalizedFlag)) && ...
    all(string(canonicalTrace.NAReason) == ...
        "not_applicable_feedback_observed_and_finalized") && ...
    all(string(canonicalTrace.ValueSource) == "runtime_pusch_uci_feedback_trace"), ...
    "Transferred PUSCH UCI grants must be finalized as observed runtime evidence, never pending PUCCH rows.");

missingBinding = rmfield(puschGrant, "UCIOnPUSCHFeedbackGrantIds");
badOut = harqOut;
badOut.GrantSnapshot = missingBinding;
localAssertError(@() sixgr.truth.CoupledTruthRuntime. ...
    applyDecodedPUSCHHARQACKRuntime(state, badOut), ...
    "sixgr:truth:MissingPUSCHHARQACKBinding");

ok = true;
fprintf("testLLSPUSCHHARQACKRuntimeFeedback: PASS\n");
end

function row = localFeedbackRow()
row = struct( ...
    "Direction", "", "UEIndex", NaN, "RNTI", NaN, ...
    "HarqID", NaN, "SourceSlot", NaN, "DueSlot", NaN, "Ack", false, ...
    "CurrentDecodeOK", false, "CombinedDecodeOK", false, ...
    "ServingCell", NaN, "BaseStationID", NaN, "TBSBits", NaN, ...
    "UCIBitCount", NaN, "RequestedFormat", NaN, "ResolvedFormat", NaN, ...
    "PUCCHResourceId", "", "PUCCHPRBStart", NaN, "PUCCHPRBCount", NaN, ...
    "PUCCHSymbolStart", NaN, "PUCCHNumSymbols", NaN, "UCIType", "", ...
    "ControlResourceSource", "", "ControlResourceValidity", false, ...
    "FormatAdaptationReason", "", "PUCCHGrantId", "", ...
    "DeliveryMechanism", "pucch", "PUSCHGrantContextId", "", ...
    "MultiplexedBitIndex", NaN, "Processed", false);
end

function localAssertError(f, expectedId)
threw = false;
try
    f();
catch ME
    threw = true;
    assert(string(ME.identifier) == string(expectedId), ...
        "Expected %s, received %s.", expectedId, ME.identifier);
end
assert(threw, "Expected typed error %s.", expectedId);
end
