function ok = testRawExecutionEvidenceSnapshot()
%TESTRAWEXECUTIONEVIDENCESNAPSHOT Freeze only actual same-run waveform rows.

ok = false;
runFolder = string(tempname());
cleanup = onCleanup(@() localCleanup(runFolder)); %#ok<NASGU>
mkdir(runFolder);
identity = struct("RunID", "raw-run", "ExecutionID", "exec-raw", ...
    "ScenarioID", "scenario-raw", "ConfigHash", string(repmat('a', 1, 64)));

dl = table(["dl-1";"dl-2"], [1;2], [1;1], [1;2], ...
    ["in_path";"in_path"], ["truth";"truth"], [false;false], ...
    'VariableNames', {'TrialID','Frame','Slot','UEID','EvidenceScope', ...
    'SourceClassification','FallbackFlag'});
dl.PerLayerMetric = [1 2; 3 4];
dl.VariableLengthMetric = {1:3; 4:7};
anchor = dl(1, :);
anchor.TrialID = "anchor-1";
anchor.EvidenceScope = "component_anchor";
link = struct("RawTrials", struct("DL", dl), ...
    "SupplementalStrictRawTrials", struct("PRACH", anchor));

snapshot = sixgr.runtime.snapshotRawExecutionEvidence(runFolder, link, identity);
assert(snapshot.TableCount == 1 && snapshot.RowCount == 2);
indexT = readtable(snapshot.IndexPath, "TextType", "string");
assert(height(indexT) == 1 && indexT.TableName == "rawtrials_dl");
assert(indexT.EvidenceScope == "in_path" && indexT.DuplicateKeyCount == 0);
rawT = readtable(fullfile(fileparts(snapshot.IndexPath), ...
    char(indexT.RelativePath)), "TextType", "string");
assert(indexT.SchemaVersion == "2.0.0" && ...
    indexT.SerializationContract == "sixgr_raw_table_csv/v2");
assert(indexT.ColumnCount == width(rawT) && ...
    indexT.LogicalColumnCount == width(rawT), ...
    "Raw evidence CSV must keep exactly one physical column per logical variable.");
assert(contains(indexT.EncodedColumns, "PerLayerMetric") && ...
    contains(indexT.EncodedColumns, "VariableLengthMetric"));
assert(isequal(sixgr.runtime.RawCSVArrayCodec.decode(rawT.PerLayerMetric(1)), [1 2]));
assert(isequal(sixgr.runtime.RawCSVArrayCodec.decode(rawT.PerLayerMetric(2)), [3 4]));
assert(isequal(sixgr.runtime.RawCSVArrayCodec.decode(rawT.VariableLengthMetric(1)), 1:3));
assert(isequal(sixgr.runtime.RawCSVArrayCodec.decode(rawT.VariableLengthMetric(2)), 4:7));

codecVectors = { ...
    complex(single([1 NaN; Inf -2]), single([3 -4; 5 NaN])), ...
    logical([true false true; false true false]), ...
    int16([-32768 -1 0 1 32767]), ...
    reshape(["alpha" missing "gamma" "delta"], 2, 2), ...
    char([945 946; 947 948])};
for codecIndex = 1:numel(codecVectors)
    expected = codecVectors{codecIndex};
    decoded = sixgr.runtime.RawCSVArrayCodec.decode( ...
        sixgr.runtime.RawCSVArrayCodec.encode(expected));
    assert(strcmp(class(decoded), class(expected)) && ...
        isequal(size(decoded), size(expected)) && isequaln(decoded, expected), ...
        "Raw CSV codec did not preserve class, shape, and values exactly.");
end
assert(all(rawT.RunID == identity.RunID) && ...
    all(rawT.ExecutionID == identity.ExecutionID) && ...
    all(rawT.ScenarioConfigHash == identity.ConfigHash) && ...
    all(rawT.EvidenceScope == "in_path"));

repeat = sixgr.runtime.snapshotRawExecutionEvidence(runFolder, link, identity);
assert(repeat.IndexSHA256 == snapshot.IndexSHA256);

% Independent fixed-link points reuse frame/slot coordinates by design.
% Their primary key is the explicit point/trial/seed hierarchy, not a
% connected-mode grant key whose UE/TB fields are intentionally absent.
fixedFolder = string(tempname());
fixedCleanup = onCleanup(@() localCleanup(fixedFolder)); %#ok<NASGU>
mkdir(fixedFolder);
fixed = table(repmat("DL",3,1), ones(3,1), ones(3,1), ...
    nan(3,1), strings(3,1), nan(3,1), (1:3)', ones(3,1), ...
    ones(3,1), repmat("in_path",3,1), repmat("truth",3,1), ...
    false(3,1), ...
    'VariableNames', {'Direction','Frame','Slot','UEID','TBId', ...
    'HARQRound','FixedLinkPointIndex','FixedLinkTrialIndex', ...
    'FixedLinkSeedIndex','EvidenceScope','SourceClassification', ...
    'FallbackFlag'});
fixedSnapshot = sixgr.runtime.snapshotRawExecutionEvidence( ...
    fixedFolder, struct("RawTrials", struct("DL", fixed)), identity);
fixedIndex = readtable(fixedSnapshot.IndexPath, "TextType", "string");
assert(fixedIndex.DuplicateKeyCount == 0 && ...
    fixedIndex.PrimaryKeyColumns == ...
    "Direction|FixedLinkPointIndex|FixedLinkTrialIndex|FixedLinkSeedIndex", ...
    "Fixed-link raw evidence must use its explicit point/trial/seed key.");

% A later report-identity pass must never invalidate the immutable raw
% index. Re-reading the seal after annotation proves byte preservation.
sixgr.report.annotateScenarioCSVArtifacts(runFolder, identity.ScenarioID, ...
    identity.ConfigHash, "waveform_bundle");
afterAnnotation = sixgr.runtime.snapshotRawExecutionEvidence( ...
    runFolder, link, identity);
assert(afterAnnotation.IndexSHA256 == snapshot.IndexSHA256, ...
    "Report annotation must not change any indexed raw-evidence bytes.");

proxyFolder = string(tempname());
proxyCleanup = onCleanup(@() localCleanup(proxyFolder)); %#ok<NASGU>
mkdir(proxyFolder);
proxy = dl(1, :);
proxy.SourceClassification = "fast_proxy";
localAssertError(@() sixgr.runtime.snapshotRawExecutionEvidence( ...
    proxyFolder, struct("RawTrials", struct("DL", proxy)), identity), ...
    "sixgr:runtime:ProxyRawEvidenceForbidden");

duplicateFolder = string(tempname());
duplicateCleanup = onCleanup(@() localCleanup(duplicateFolder)); %#ok<NASGU>
mkdir(duplicateFolder);
duplicate = [dl(1, :); dl(1, :)];
localAssertError(@() sixgr.runtime.snapshotRawExecutionEvidence( ...
    duplicateFolder, struct("RawTrials", struct("DL", duplicate)), identity), ...
    "sixgr:runtime:RawEvidenceDuplicateKey");

fprintf("PASS testRawExecutionEvidenceSnapshot: immutable in-path snapshot excludes anchors and rejects proxy/duplicates.\n");
ok = true;
end

function localAssertError(fn, identifier)
try
    fn();
    error("testRawExecutionEvidenceSnapshot:ExpectedError", ...
        "Expected %s.", identifier);
catch ME
    assert(strcmp(ME.identifier, identifier), ...
        "Expected %s, received %s: %s", identifier, ME.identifier, ME.message);
end
end

function localCleanup(pathValue)
if isfolder(pathValue)
    rmdir(pathValue, "s");
end
end
