function ok = testFixedLinkMonteCarloCampaign()
%TESTFIXEDLINKMONTECARLOCAMPAIGN Controlled SNR curves must be real fixed-link campaigns.

setup6GRSimToolkit("Verbose", false);

cfg = localFixtureConfig();
snrGrid = [0 5 10 15 20];
tmp = tempname;
mkdir(tmp);
c = onCleanup(@() rmdir(tmp, "s")); %#ok<NASGU>

opt = localCampaignOptions(cfg, snrGrid, 2, 99123);
out = sixgr.truth.runWaveformLinkBundle(cfg, fullfile(tmp, "air_interface"), opt);

T = out.SNRSweep;
assert(istable(T) && height(T) == numel(snrGrid), ...
    "Fixed-link campaign must publish one controlled curve row per configured SNR point.");
assert(isequal(double(T.SNR_dB(:)).', snrGrid), ...
    "Fixed-link campaign must preserve the explicit SNR vector instead of replacing it with the operating point.");
assert(all(string(T.CampaignKind) == "fixed_link_monte_carlo") && ...
    all(string(T.SweepKind) == "fixed_reference_awgn_snr_campaign"), ...
    "Controlled curve rows must identify the fixed-link Monte Carlo source.");
assert(all(logical(T.FixedReferenceMode)) && all(string(T.NoiseOperatingMode) == "standalone_awgn_snr_argument"), ...
    "Fixed-link calibration must run in explicit AWGN SNR mode, separate from receiver-noise truth rows.");
assert(all(double(T.DL_TrialCount) >= 2) && all(double(T.UL_TrialCount) >= 2), ...
    "Each SNR point must accumulate the configured minimum DL and UL waveform trials.");
assert(all(string(T.IntervalMethod) == "CLOPPER_PEARSON_TWO_SIDED") && ...
    all(string(T.DL_BLER_CI_Method) == "CLOPPER_PEARSON_TWO_SIDED") && ...
    all(string(T.UL_BLER_CI_Method) == "CLOPPER_PEARSON_TWO_SIDED"), ...
    "BLER confidence intervals must use the configured exact method.");
assert(all(string(T.NominalIntervalSamplingPlan) == ...
    "FIXED_SAMPLE_DESCRIPTIVE") && ...
    all(string(T.SequentialSamplingPlan) == ...
    "BOUNDED_LOOK_BONFERRONI"), ...
    "Nominal reporting and sequential stopping must be labelled as distinct sampling plans.");
for prefix = ["DL", "UL"]
    seqMethod = string(T.(prefix + "_SequentialIntervalMethod"));
    assert(all(ismember(seqMethod, ["CLOPPER_PEARSON_TWO_SIDED", ...
        "CLOPPER_PEARSON_ONE_SIDED_UPPER"])) && ...
        all(isfinite(double(T.(prefix + "_SequentialLookConfidenceLevel")))) && ...
        all(isfinite(double(T.(prefix + "_SequentialCI_Low")))) && ...
        all(isfinite(double(T.(prefix + "_SequentialCI_High")))) && ...
        all(isfinite(double(T.(prefix + "_SequentialLookIndex")))) && ...
        all(isfinite(double(T.(prefix + "_SequentialAlphaSpentThisLook")))) && ...
        all(isfinite(double(T.(prefix + "_SequentialCumulativeAlphaSpent")))) && ...
        all(strlength(string(T.(prefix + "_SequentialDesignID"))) > 0) && ...
        all(strlength(string(T.(prefix + "_PointStatus"))) > 0), ...
        "%s sequential stopping evidence must be complete and reproducible.", prefix);
end
assert(all(isfinite(double(T.PointSeed))) && numel(unique(double(T.PointSeed))) == height(T), ...
    "Each SNR point must receive a deterministic hierarchical point seed.");

fixedCsv = fullfile(tmp, "air_interface", "csv", "lls_fixed_link_campaign.csv");
assert(exist(fixedCsv, "file") == 2, ...
    "Fixed-link campaign summary CSV must be exported as a distinct artifact.");
csvT = readtable(fixedCsv, "VariableNamingRule", "preserve");
assert(isequal(double(csvT.SNR_dB(:)).', snrGrid), ...
    "Fixed-link campaign CSV must preserve the configured SNR vector.");

canonicalDLPath = fullfile(tmp, "air_interface", "csv", ...
    "dl_pdsch_trials.csv");
canonicalULPath = fullfile(tmp, "air_interface", "csv", ...
    "ul_pusch_trials.csv");
runtimeModePath = fullfile(tmp, "reports", "csv", ...
    "runtime_operating_mode.csv");
controlApplicabilityPath = fullfile(tmp, "reports", "csv", ...
    "live_control_gating_summary.csv");
canonicalPaths = [string(canonicalDLPath); string(canonicalULPath); ...
    string(runtimeModePath); string(controlApplicabilityPath)];
for pathValue = canonicalPaths.'
    assert(exist(pathValue, "file") == 2, ...
        "Fixed-link truth publication is missing canonical artifact: %s", ...
        pathValue);
    canonicalT = readtable(pathValue, "VariableNamingRule", "preserve");
    assert(height(canonicalT) >= 1, ...
        "Fixed-link canonical artifact is empty: %s", pathValue);
end
canonicalDL = readtable(canonicalDLPath, ...
    "VariableNamingRule", "preserve");
canonicalUL = readtable(canonicalULPath, ...
    "VariableNamingRule", "preserve");
assert(height(canonicalDL) == height(out.RawTrials.DL) && ...
    height(canonicalUL) == height(out.RawTrials.UL), ...
    "Canonical DL/UL trial tables must contain every real campaign trial.");
assert(all(string(canonicalDL.SourceArtifact) == ...
    "air_interface/csv/dl_pdsch_trials.csv") && ...
    all(string(canonicalUL.SourceArtifact) == ...
    "air_interface/csv/ul_pusch_trials.csv"), ...
    "Canonical campaign trials must identify their actual canonical source.");
assert(all(strlength(strtrim(string( ...
    canonicalDL.ConfiguredBeamSelectionStrategy))) > 0) && ...
    all(strlength(strtrim(string( ...
    canonicalUL.ConfiguredBeamSelectionStrategy))) > 0), ...
    "Fixed-link canonical trials must preserve the configured beam policy.");
assert(all(string(canonicalDL.GrantControlState) == ...
    "not_applicable_fixed_link_calibration_no_control_lifecycle") && ...
    all(string(canonicalUL.GrantControlState) == ...
    "not_applicable_fixed_link_calibration_no_control_lifecycle"), ...
    "Fixed-link trials must explicitly mark the scheduler/control " + ...
    "lifecycle as not applicable instead of leaving it unavailable.");
runtimeMode = readtable(runtimeModePath, ...
    "VariableNamingRule", "preserve");
assert(all(string(runtimeMode.SchedulerGrantMCSSelectionMode) == ...
    "not_applicable_fixed_link_calibration_no_scheduler_grant"), ...
    "Fixed-link runtime mode must explicitly mark scheduler-grant MCS " + ...
    "selection as not applicable.");
controlApplicability = readtable(controlApplicabilityPath, ...
    "VariableNamingRule", "preserve");
assert(~logical(controlApplicability.PBCHGatingActive(1)) && ...
    ~logical(controlApplicability.PRACHGatingActive(1)) && ...
    ~logical(controlApplicability.PDCCHGatingActive(1)) && ...
    ~logical(controlApplicability.SRSGatingActive(1)) && ...
    ~logical(controlApplicability.TRSGatingActive(1)), ...
    "Fixed-link-only execution must publish disabled control applicability.");
assert(exist(fullfile(tmp, "packet_flow", "csv", ...
    "live_dl_scheduler_grants.csv"), "file") ~= 2 && ...
    exist(fullfile(tmp, "packet_flow", "csv", ...
    "live_ul_scheduler_grants.csv"), "file") ~= 2, ...
    ["Independent fixed-link transport-block trials must not be " ...
    "misrepresented as live scheduler grants."]);
assert(exist(fullfile(tmp, "air_interface", "csv", ...
    "dl_measured_sinr_bler_curve.csv"), "file") == 2 && ...
    exist(fullfile(tmp, "air_interface", "csv", ...
    "ul_measured_sinr_bler_curve.csv"), "file") == 2 && ...
    exist(fullfile(tmp, "air_interface", "csv", ...
    "lls_measured_sinr_summary.csv"), "file") == 2, ...
    "Canonical fixed-link trials must feed receiver-measured SINR analytics.");
kpiReconstructionPath = fullfile(tmp, "reports", "csv", ...
    "kpi_reconstruction_summary.csv");
assert(exist(kpiReconstructionPath, "file") == 2, ...
    "Fixed-link truth must publish raw-derived KPI reconstruction evidence.");
kpiReconstruction = readtable(kpiReconstructionPath, ...
    "VariableNamingRule", "preserve");
strictKPIOk = localAsLogicalVector(kpiReconstruction.StrictOk);
latencyKPI = contains(string(kpiReconstruction.KPIName), "Latency");
formulaOk = localAsLogicalVector(kpiReconstruction.FormulaExecuted);
reconciliationOk = localAsLogicalVector(kpiReconstruction.ReconciliationPass);
applicableKPI = localAsLogicalVector(kpiReconstruction.Applicable);
failedKPI = string(kpiReconstruction.KPIName((applicableKPI & ~formulaOk) | ...
    (applicableKPI & ~latencyKPI & (~reconciliationOk | ~strictKPIOk))));
assert(~isempty(kpiReconstruction) && ...
    all(~applicableKPI | formulaOk) && ...
    all(reconciliationOk(applicableKPI & ~latencyKPI)) && ...
    all(strictKPIOk(applicableKPI & ~latencyKPI)), ...
    "Fixed-link KPI reconstruction must execute every formula and " + ...
    "reconcile every non-latency KPI to raw DL/UL trials. Failed KPI(s): " + ...
    strjoin(failedKPI, ", "));
notApplicable = contains(string(kpiReconstruction.KPIName), ...
    ["HARQ_NACK_Rate","Retransmission_Rate","PRB_Utilization","Latency"]);
assert(all(~applicableKPI(notApplicable)) && ...
    all(string(kpiReconstruction.Status(notApplicable)) == "not_applicable"), ...
    "Disabled HARQ/scheduler/application KPI rows must be explicit not_applicable evidence.");

dlCurveCsv = fullfile(tmp, "reports", "csv", "dl_fixed_link_bler_curve.csv");
ulCurveCsv = fullfile(tmp, "reports", "csv", "ul_fixed_link_bler_curve.csv");
summaryCsv = fullfile(tmp, "reports", "csv", "fixed_link_campaign_summary.csv");
assert(exist(dlCurveCsv, "file") == 2 && exist(ulCurveCsv, "file") == 2 && exist(summaryCsv, "file") == 2, ...
    "Fixed-link campaign must export the report-level BLER curves and summary bundle.");
dlCurve = readtable(dlCurveCsv, "VariableNamingRule", "preserve");
assert(~isempty(dlCurve) && all(isfinite(double(dlCurve.CI_HalfWidth))), ...
    "DL report-level BLER curve must carry finite confidence intervals.");
assert(all(string(dlCurve.IntervalMethod) == ...
    "CLOPPER_PEARSON_TWO_SIDED") && ...
    all(strlength(string(dlCurve.SequentialDesignID)) > 0), ...
    "Report-level BLER curves must preserve nominal and sequential interval provenance.");

requiredAirCsv = [
    "air_interface/csv/lls_fixed_link_campaign.csv"
    "air_interface/csv/lls_snr_sweep.csv"
    "air_interface/csv/fixed_link_campaign_task_plan.csv"
    "air_interface/csv/dl_fixed_link_campaign_trials.csv"
    "air_interface/csv/ul_fixed_link_campaign_trials.csv"
    ];
for relPath = requiredAirCsv.'
    absPath = fullfile(tmp, strrep(relPath, "/", filesep));
    assert(exist(absPath, "file") == 2, "Missing fixed-link air-interface CSV: %s", relPath);
    Ta = readtable(absPath, "VariableNamingRule", "preserve");
    assert(height(Ta) >= 1, "Fixed-link air-interface CSV is empty: %s", relPath);
end
assert(exist(fullfile(tmp, "air_interface", "csv", ...
    "lls_reference_snr_sweep.csv"), "file") ~= 2, ...
    ["A DUT fixed-link sweep must not be duplicated and mislabeled as an " ...
    "independent reference sweep when no independent oracle was supplied."]);

requiredReportCsv = [
    "reports/csv/fixed_snr_sweep_curve_summary.csv"
    "reports/csv/dl_fixed_snr_bler_curve.csv"
    "reports/csv/ul_fixed_snr_bler_curve.csv"
    "reports/csv/dl_fixed_snr_ber_curve.csv"
    "reports/csv/ul_fixed_snr_ber_curve.csv"
    "reports/csv/fixed_snr_sweep_point_completeness.csv"
    "reports/csv/fixed_snr_sweep_curve_crossing.csv"
    ];
for relPath = requiredReportCsv.'
    absPath = fullfile(tmp, strrep(relPath, "/", filesep));
    assert(exist(absPath, "file") == 2, "Missing fixed-link report CSV: %s", relPath);
    Tr = readtable(absPath, "VariableNamingRule", "preserve");
    assert(height(Tr) >= 1, "Fixed-link report CSV is empty: %s", relPath);
end

normalizedSummary = readtable(fullfile(tmp, "reports", "csv", "fixed_snr_sweep_curve_summary.csv"), "VariableNamingRule", "preserve");
assert(height(normalizedSummary) == 2 * numel(snrGrid), ...
    "Normalized fixed-SNR curve summary must have one row per SNR point per enabled direction.");
requiredCurveCols = ["Direction","ChannelModel","SweepKind","NoiseVariable","SNR_dB","ConfiguredSNR_dB", ...
    "AppliedSNR_dB","MeanMeasuredSINR_dB","MedianMeasuredSINR_dB","SINRMinusSNRMean_dB", ...
    "MCS","Modulation","Rank","Layers","TrialCount","TBPassCount","TBFailCount", ...
    "BLER","BLER_CI_Low","BLER_CI_High","BLER_CI_Width","BitErrors","BitsCompared", ...
    "BER","BER_CI_Low","BER_CI_High","BER_CI_Width","Throughput_Mbps","Goodput_Mbps", ...
    "TargetBLER","TargetCrossingSNR_dB","TargetCrossingStatus", ...
    "NominalIntervalMethod","NominalIntervalSamplingPlan","BLER_CI_Method", ...
    "BER_CI_Method","SequentialIntervalMethod","SequentialLookConfidenceLevel", ...
    "SequentialSidedness","SequentialCI_Low","SequentialCI_High", ...
    "SequentialCI_HalfWidth","SequentialLookIndex", ...
    "SequentialAlphaSpentThisLook","SequentialCumulativeAlphaSpent", ...
    "SequentialDesignID","PointStatus","StopReason","Incomplete","Status","FailureCode"];
assert(all(ismember(requiredCurveCols, string(normalizedSummary.Properties.VariableNames))), ...
    "Normalized fixed-SNR curve summary is missing required audit columns.");
assert(all(double(normalizedSummary.TrialCount) >= 2), ...
    "Normalized fixed-SNR curve summary must preserve the configured minimum trials per point.");
assert(all(double(normalizedSummary.BLER) >= 0 & double(normalizedSummary.BLER) <= 1), ...
    "Normalized fixed-SNR BLER values must stay within [0,1].");
assert(all(double(normalizedSummary.BER) >= 0 & double(normalizedSummary.BER) <= 1), ...
    "Normalized fixed-SNR BER values must stay within [0,1].");
assert(all(string(normalizedSummary.NominalIntervalMethod) == ...
    "CLOPPER_PEARSON_TWO_SIDED") && ...
    all(string(normalizedSummary.BLER_CI_Method) == ...
    string(normalizedSummary.NominalIntervalMethod)) && ...
    all(string(normalizedSummary.BER_CI_Method) == ...
    string(normalizedSummary.NominalIntervalMethod)), ...
    "Normalized curves must preserve the YAML-authoritative nominal interval method.");

dlTrialsCsv = readtable(fullfile(tmp, "air_interface", "csv", "dl_fixed_link_campaign_trials.csv"), "VariableNamingRule", "preserve");
requiredTrialCols = ["Direction","SNR_dB","ConfiguredSNR_dB","AppliedSNR_dB","AppliedAWGNSNR_dB", ...
    "MeasuredPostEqSINR_dB","Status","CRCPass","BitErrors","BitsCompared","MCS","Modulation", ...
    "Rank","NumLayers","TBSizeBits","RateMatchedBits","EffectiveCodeRate","FixedLinkCampaign", ...
    "FixedLinkIntervalMethod", ...
    "FixedReferenceMode","FixedLinkPointIndex","FixedLinkDropIndex","FixedLinkTrialIndex","FixedLinkSeedHierarchy", ...
    "RawBER","ScheduledMCSIndex","ScheduledModulation", ...
    "ScheduledOperatingPointMatchesTransmitted", ...
    "ScheduledOperatingPointEvidenceStatus", ...
    "RunID","RunTag","ScenarioID","ConfigHash","ExecutionID"];
assert(all(ismember(requiredTrialCols, string(dlTrialsCsv.Properties.VariableNames))), ...
    "Normalized fixed-link DL trial CSV is missing required audit columns.");
assert(all(localAsLogicalVector(dlTrialsCsv.FixedLinkCampaign)) && all(localAsLogicalVector(dlTrialsCsv.FixedReferenceMode)), ...
    "Normalized fixed-link DL trial CSV must preserve fixed-link reference mode evidence.");
newTBMask = ~localAsLogicalVector(dlTrialsCsv.IsRetransmission);
assert(all(double(dlTrialsCsv.EffectiveCodeRate(newTBMask)) <= 1.0 + 1e-9), ...
    "Normalized fixed-link DL trial CSV must reject effective code rates above 1 for new transport blocks.");
validBER = isfinite(double(dlTrialsCsv.BitsCompared)) & ...
    double(dlTrialsCsv.BitsCompared) > 0;
expectedBER = double(dlTrialsCsv.BitErrors(validBER)) ./ ...
    double(dlTrialsCsv.BitsCompared(validBER));
assert(all(abs(double(dlTrialsCsv.RawBER(validBER)) - expectedBER) <= 1e-15), ...
    "Normalized fixed-link RawBER must equal BitErrors/BitsCompared exactly.");
scheduledModulation = strtrim(string(dlTrialsCsv.ScheduledModulation));
assert(all(~isfinite(double(dlTrialsCsv.ScheduledMCSIndex))) && ...
    all(ismissing(scheduledModulation) | strlength(scheduledModulation) == 0) && ...
    all(~localAsLogicalVector( ...
        dlTrialsCsv.ScheduledOperatingPointMatchesTransmitted)) && ...
    all(string(dlTrialsCsv.ScheduledOperatingPointEvidenceStatus) == ...
        "not_applicable_no_adaptive_scheduled_decision"), ...
    "Fixed-link trials must explicitly mark scheduled operating-point " + ...
    "evidence not applicable rather than fabricating scheduler output.");
for identityName = ["RunID","RunTag","ScenarioID","ConfigHash","ExecutionID"]
    assert(all(strlength(strtrim(string(dlTrialsCsv.(identityName)))) > 0), ...
        "Normalized fixed-link trial identity %s must be populated by runtime execution.", ...
        identityName);
end

if usejava("jvm")
    plotInfo = sixgr.visual.plotFixedSNRSweepCurves(tmp);
    expectedPlots = [
        "reports/image/dl_bler_vs_snr.png"
        "reports/image/ul_bler_vs_snr.png"
        "reports/image/dl_ber_vs_snr.png"
        "reports/image/ul_ber_vs_snr.png"
        "reports/image/dl_throughput_vs_snr.png"
        "reports/image/ul_throughput_vs_snr.png"
        "reports/image/measured_sinr_vs_configured_snr.png"
        "reports/image/fixed_snr_trials_per_point.png"
        "reports/image/fixed_snr_ci_width_vs_snr.png"
        "reports/image/fixed_snr_curve_dashboard.png"
        ];
    for relPath = expectedPlots.'
        absPath = fullfile(tmp, strrep(relPath, "/", filesep));
        assert(exist(absPath, "file") == 2, "Missing fixed-SNR plot: %s", relPath);
    end
    lineage = readtable(fullfile(tmp, "reports", "csv", "fixed_snr_plot_lineage.csv"), "VariableNamingRule", "preserve");
    assert(height(lineage) == numel(expectedPlots), ...
        "Fixed-SNR plot lineage must contain one row per emitted PNG plot file.");
    assert(all(string(lineage.Status) == "rendered"), ...
        "Fixed-SNR plot lineage must report rendered status for every required plot.");
    assert(all(strlength(string(lineage.SourceCSV_SHA256)) == 64), ...
        "Fixed-SNR plot lineage must hash each source CSV.");
    assert(numel(plotInfo.Plots) == numel(expectedPlots), ...
        "Fixed-SNR plot helper must return every rendered PNG path.");
end

tmp2 = tempname;
mkdir(tmp2);
c2 = onCleanup(@() rmdir(tmp2, "s")); %#ok<NASGU>
out2 = sixgr.truth.runWaveformLinkBundle(cfg, fullfile(tmp2, "air_interface"), opt);
T2 = out2.SNRSweep;
cols = ["SNR_dB","PointSeed","DL_FailureCount","UL_FailureCount","DL_BLER","UL_BLER"];
for i = 1:numel(cols)
    a = double(T.(cols(i)));
    b = double(T2.(cols(i)));
    assert(isequaln(a, b), "Fixed-link campaign column %s must be deterministic for the same seed.", cols(i));
end

ok = true;
end

function values = localAsLogicalVector(raw)
if islogical(raw)
    values = logical(raw);
elseif isnumeric(raw)
    values = double(raw) ~= 0;
else
    token = lower(strtrim(string(raw)));
    values = token == "1" | token == "true" | token == "yes" | token == "pass";
end
values = values(:);
end

function cfg = localFixtureConfig()
% Use the dedicated fixed-SNR master rather than mutating a geometry/MU
% system scenario into a calibration profile after YAML authority has been
% installed.  This keeps every disabled auxiliary signal and rank alias
% owned by the source configuration exercised by the test.
scenarioPath = fullfile(pwd, "simulator", "configs", "scenarios", "master_sinr_sweep.yaml");
scfg = sixgr.lls6g.config.loadScenarioConfig(scenarioPath);
scfg = scfg.toStruct();
cfg = sixgr.lls6g.buildInternalConfig(scfg, fullfile(tempdir, "fixed_link_campaign_fixture"));
cfg.run.numFrames = 1;
cfg.run.strictMode = false;
cfg.run.noProxyTruthContract = false;
cfg.run.interferenceExecutionMode = "none";
cfg.run.fixedReferenceMode = true;
cfg.run.noiseOperatingMode = "standalone_awgn_snr_argument";
cfg.lls6g.users.beam_selection_strategy = "fixed_first_beam";
cfg.phy.linkAdaptation.mode = "fixed";
cfg.phy.pdsch.PRBSet = 0:49;
cfg.phy.pdsch.prbSet = 0:49;
cfg.phy.pdsch.numPorts = 1;
cfg.phy.pdsch.enablePTRS = false;
cfg.phy.pdsch.executionProfile = "phy_calibration";
cfg.phy.pdsch.UECapability1024QAM = false;
cfg.phy.pdsch.RRCEnabled1024QAM = false;
cfg.phy.pdsch.DCIEnabled1024QAM = false;
cfg.phy.pdsch.DeploymentAllows1024QAM = false;
cfg.phy.pdsch.FrequencyRangeAllows1024QAM = false;
cfg.phy.pdsch.BandAllows1024QAM = false;
cfg.phy.pdsch.FrequencyRange = "FR1";
cfg.phy.pdsch.OperatingBand = "n77";
cfg.phy.pdsch.DeploymentClass = "macro";
cfg.phy.pdsch.DCIFormat = "1_1";
cfg.phy.pdsch.symbolAllocation = [2 12];
cfg.phy.pdsch.mappingType = "A";
cfg.phy.pusch.prbSet = 0:49;
cfg.phy.pusch.PRBSet = 0:49;
cfg.phy.pusch.enablePTRS = false;
cfg.phy.bwp.dl = struct("NStartBWP",0,"NSizeBWP",273);
cfg.phy.bwp.ul = struct("NStartBWP",0,"NSizeBWP",273);
cfg.run.seed = 4207;
cfg.channel.model = "AWGN";
cfg.channel.awgnOnly = true;
cfg.channel.fading.enable = false;
cfg.channel.bandwidth_Hz = 100e6;
cfg.channel.snr_dB = 18;
cfg.channel.nTxAnt = 1;
cfg.channel.nRxAnt = 1;
cfg.phy.channelBandwidth_MHz = 100;
cfg.phy.nTxAnt = 1;
cfg.phy.nRxAnt = 1;
cfg.phy.carrier.NSizeGrid = 273;
cfg = sixgr.util.structSet(cfg, "phy.numerology.activeGridNumRBs", 273);
cfg = sixgr.util.structSet(cfg, "phy.numerology.configuredGridNumRBs", 273);
cfg.phy.pdsch.nLayers = 1;
cfg.phy.pdsch.numLayers = 1;
cfg.phy.pusch.nLayers = 1;
cfg.phy.pusch.numLayers = 1;
cfg.phy.pbch.enable = false;
cfg.phy.mib.enable = false;
cfg.phy.sib1.enable = false;
cfg.phy.pdcch.enable = false;
cfg.phy.pucch.enable = false;
cfg.phy.srs.enable = false;
cfg = sixgr.util.structSet(cfg, "phy.trs.enable", false);
cfg = sixgr.util.structSet(cfg, "phy.ptrs.enable", false);
cfg = sixgr.util.structSet(cfg, "lls6g.reference_signals.ptrs_enabled", false);
cfg.phy.csirs.enable = false;
cfg.phy.prach.enable = false;
cfg.phy.harq.enable = false;
cfg.mac.harq.enable = false;
cfg.phy.pusch.powerControl.enabled = false;
cfg.powerAndRF.puschPowerControlEnabled = false;
cfg = sixgr.util.structSet(cfg, "lls6g.users.enabled", false);
cfg = sixgr.util.structSet(cfg, "lls6g.users.n_users", 1);
% runWaveformLinkBundle is normally invoked by runSingle, which binds the
% immutable lifecycle identity.  This direct focused test must provide the
% same production precondition explicitly.
cfg.run.runTag = "fixed_link_campaign_fixture";
cfg.run.executionID = "fixed_link_campaign_fixture_execution";
cfg.run.scenarioID = "fixed_link_campaign_fixture";
cfg.meta.executionID = cfg.run.executionID;
cfg.meta.configHash = "";
cfg.meta.configHash = string(sixgr.util.sha256Hex(uint8( ...
    unicode2native(jsonencode(cfg), "UTF-8"))));
end

function opt = localCampaignOptions(cfg, snrGrid, trialsPerPoint, seed)
opt = struct( ...
    "LinkDuration_s", 0.001, ...
    "LinkMaxSimFrames", 1, ...
    "FixedLinkCampaignOnly", true, ...
    "LinkSNR_dB", double(cfg.channel.snr_dB), ...
    "LinkSNRGrid_dB", double(cfg.channel.snr_dB), ...
    "LinkSweepFrames", 1, ...
    "LinkSweepTrialsPerSNR", 1, ...
    "LinkSweepMaxPoints", 1, ...
    "LinkReferenceSweepFrames", trialsPerPoint, ...
    "LinkAdaptiveSweepEnabled", false, ...
    "LinkFixedLinkCampaignEnabled", true, ...
    "LinkFixedLinkSNRGrid_dB", snrGrid, ...
    "LinkFixedLinkMinTrials", trialsPerPoint, ...
    "LinkFixedLinkMaxTrials", trialsPerPoint, ...
    "LinkFixedLinkTrialsPerDrop", 1, ...
    "LinkFixedLinkErrorTarget", 1, ...
    "LinkFixedLinkCIWidthTarget", 1, ...
    "LinkFixedLinkConfidenceLevel", 0.95, ...
    "LinkFixedLinkSeed", seed, ...
    "HARQDiagnosticsEnabled", false, ...
    "LinkAnchorCases", ["DL_PDSCH_Throughput","UL_PUSCH_Throughput"], ...
    "SaveFigures", false);
end
