function ok = testLLSAdaptiveMIMOPolicyGate()
%TESTLLSADAPTIVEMIMOPOLICYGATE AMC does not require fixed modulation/MCS equality.

setup6GRSimToolkit("Verbose", false);
ctx = llsRootGateFixture("pass");
scfg = sixgr.util.structSet(ctx.ScenarioConfig, ...
    "scenario.honesty_mode", "study");
scfg = sixgr.util.structSet(scfg, ...
    "scenario.scenario_mode", "adaptive_link");
scfg = sixgr.util.structSet(scfg, ...
    "link_adaptation.fixed_or_amc", "adaptive");
scfg = sixgr.util.structSet(scfg, ...
    "link_adaptation.pdsch_link_adaptation_policy", "cqi_driven");
scfg = sixgr.util.structSet(scfg, ...
    "link_adaptation.pusch_link_adaptation_policy", "cqi_driven");
cfg = sixgr.util.structSet(ctx.InternalConfig, ...
    "phy.linkAdaptation.mode", "adaptive_link");
cfg = sixgr.util.structSet(cfg, ...
    "phy.linkAdaptation.dlPolicy", "cqi_driven");
cfg = sixgr.util.structSet(cfg, ...
    "phy.linkAdaptation.ulPolicy", "cqi_driven");
cfg = sixgr.util.structSet(cfg, ...
    "phy.linkAdaptation.rankPolicy", "adaptive");

mimoT = table(["DL";"UL"], true(2,1), true(2,1), false(2,1), ...
    true(2,1), true(2,1), [2;2], false(2,1), true(2,1), true(2,1), ...
    'VariableNames', {'Direction','ScenarioObjectivePass', ...
    'SpatialContractMatch','FixedOperatingPointMatch', ...
    'AdaptivePolicyConformance','MUExecutionMatch', ...
    'StrictEligibleRowCount','FixedOperatingPointRequired', ...
    'AdaptivePolicyRequired','AdaptiveMode'});
sixgr.util.ensureDir(fullfile(ctx.Layout.BeamformingCSVDir, ".keep"));
sixgr.util.csvWriteTable(fullfile(ctx.Layout.BeamformingCSVDir, ...
    "mimo_configured_vs_effective.csv"), mimoT);

dlT = readtable(fullfile(ctx.Layout.AirInterfaceCSVDir, ...
    "dl_pdsch_trials.csv"), "VariableNamingRule", "preserve");
ulT = readtable(fullfile(ctx.Layout.AirInterfaceCSVDir, ...
    "ul_pusch_trials.csv"), "VariableNamingRule", "preserve");
opSummary = sixgr.truth.summarizeEffectiveOperatingPoint(scfg, dlT, ulT);
root = sixgr.truth.evaluateStrictAnchorStatus(ctx.RunFolder, scfg, cfg, ...
    struct("Failures", strings(0,1), "CheckDetails", struct()), ...
    dlT, ulT, opSummary);

assert(logical(root.Status.ConfiguredEffectivePolicyOk), ...
    "Adaptive MIMO policy evidence must not require fixed modulation/MCS equality.");
assert(~any(contains(string(root.Failures), ...
    "mimo_four_gate_configured_effective_evidence_failed")), ...
    "The root reducer must evaluate only the operating-point gate applicable to AMC.");

ok = true;
end
