function ok = testYAMLDrivenHybridRFChainAuthority()
%TESTYAMLDRIVENHYBRIDRFCHAINAUTHORITY Prevent rank-based RF-chain overrides.

setup6GRSimToolkit("Verbose", false, "RunToolboxChecks", false);
scenario = sixgr.lls6g.config.loadScenarioConfig(fullfile(pwd, ...
    "simulator", "configs", "scenarios", ...
    "webgui_sinr_sweep_64x4_mu_mimo_full.yaml"));
cfg = sixgr.lls6g.buildInternalConfig(scenario, tempdir);

[dlChains, dlSource] = ...
    sixgr.phy.mimo.resolveDirectionalRFChainAuthority(cfg, "DL", ...
    "RequiredLogicalPorts", 4);
[ulChains, ulSource] = ...
    sixgr.phy.mimo.resolveDirectionalRFChainAuthority(cfg, "UL", ...
    "RequiredLogicalPorts", 2);
assert(dlChains == 4 && ulChains == 2, ...
    "Directional RF-chain authority must preserve the exact YAML capacities.");
assert(dlSource == "runtime.antenna.gnb.NumTxRFChains" && ...
    ulSource == "runtime.antenna.ue.NumTxRFChains", ...
    "The immutable runtime authority must be the primary RF-chain source.");

% A rank-2 user beam does not reduce the configured four-chain gNB. The
% architecture must factor the exact 64x2 selected beam into 64x4 RF and
% 4x2 baseband matrices, with every configured chain participating.
selectedBeam = exp(1j * 2*pi*(0:63).' * [0 1] / 64) / sqrt(128);
hybridCfg = sixgr.util.structSet(cfg, "phy.pdsch.numRFChains", 2);
hybridCfg.phy.beamManagement.hybridBeamformingEnabled = true;
hybridCfg.phy.pdsch.hybridElementToPortMatrix = selectedBeam;
hybridCfg.phy.pdsch.numPorts = 2;
hybridCfg.phy.pdsch.nPorts = 2;
arch = sixgr.rf.AntennaArrayFactory.resolvePortArchitecture(hybridCfg, "bs", ...
    "Signal", "PDSCH", "NumElements", 64, "NumPorts", 2, ...
    "NumRFChains", dlChains, "MinimumPorts", 2);
assert(arch.NumRFChains == 4 && isequal(arch.HybridElementToPortMatrix, selectedBeam), ...
    "Configured 4-chain hybrid architecture must preserve the exact selected 64x2 beam.");
assert(isequal(size(arch.AnalogPrecoderMatrix), [64 4]) && ...
    isequal(size(arch.DigitalPortToRFChainMatrix), [4 2]), ...
    "Configured hybrid factorization must expose physical 64x4 RF and 4x2 baseband matrices.");
assert(all(abs(vecnorm(arch.AnalogPrecoderMatrix, 2, 1) - 1) <= 1e-12) && ...
    all(any(abs(arch.DigitalPortToRFChainMatrix) > 0, 2)) && ...
    norm(arch.AnalogPrecoderMatrix * arch.DigitalPortToRFChainMatrix - selectedBeam, "fro") <= 1e-12, ...
    "All configured RF chains must participate in an exact selected-beam factorization.");

% A stale per-channel mirror must not reduce the hardware authority to the
% per-user rank. This reproduces the Phase-19 slot-6 failure condition.
stale = sixgr.util.structSet(cfg, "phy.pdsch.numRFChains", 2);
assert(sixgr.phy.mimo.resolveDirectionalRFChainAuthority( ...
    stale, "DL", "RequiredLogicalPorts", 4) == 4);

contradictory = sixgr.util.structSet(cfg, ...
    "antenna.bs.numTxRFChains", 2);
localAssertThrows(@() ...
    sixgr.phy.mimo.resolveDirectionalRFChainAuthority( ...
    contradictory, "DL", "RequiredLogicalPorts", 4), ...
    "sixgr:phy:mimo:ContradictoryRFChainAuthority");

insufficient = rmfield(cfg, "runtime");
insufficient = sixgr.util.structSet(insufficient, ...
    "antenna.bs.numTxRFChains", 2);
insufficient = sixgr.util.structSet(insufficient, ...
    "scenario.bs.numTxRFChains", 2);
insufficient.lls6g.antenna_and_array.bs_num_txrus = 2;
localAssertThrows(@() ...
    sixgr.phy.mimo.resolveDirectionalRFChainAuthority( ...
    insufficient, "DL", "RequiredLogicalPorts", 4), ...
    "sixgr:phy:mimo:RFChainCapacityInsufficient");

ok = true;
end

function localAssertThrows(fcn, identifier)
didThrow = false;
try
    fcn();
catch ME
    didThrow = strcmp(string(ME.identifier), string(identifier));
    if ~didThrow
        rethrow(ME);
    end
end
assert(didThrow, "Expected typed error %s.", identifier);
end
