function ok = testLLSDeploymentTopologyConfigWiring()
%TESTLLSDEPLOYMENTTOPOLOGYCONFIGWIRING Ensure LLS layout config honors topology YAML.

setup6GRSimToolkit("Verbose", false);

tmp = tempname;
mkdir(tmp);
c = onCleanup(@() rmdir(tmp, "s")); %#ok<NASGU>

baseScenario = fullfile(pwd, "simulator", "configs", "scenarios", "lls_700mhz_20mhz_2x2_rank2_beam_truth.yaml");
scenarioPath = fullfile(tmp, "lls_topology_probe.yaml");
fid = fopen(scenarioPath, "w");
fprintf(fid, "%s", ['{' ...
    '"inherits":["' strrep(baseScenario, '\', '\\') '"],' ...
    '"meta":{"scenario_id":"lls_topology_probe","description":"layout wiring probe","version":"1","owner":"test","maturity_tag":"regression"},' ...
    '"deployment_topology":{"scenario_type":"multi-cell","site_layout":"hex_grid","cell_type":"UMa","inter_site_distance":500,"num_cells":60,"num_ues":12,"num_trps":1,"trp_topology":"single_trp","trp_sync_mode":"synchronous","trp_switching_mode":"disabled","cell_free_flag":false,"full_duplex_flag":false,"self_interference_path_model":"none"},' ...
    '"users":{"enabled":true,"n_users":12,"execution_model":"slot_coupled_truth"},' ...
    '"mobility":{"ue_speed_kmh":30,"trajectory_model":"linear"},' ...
    '"output":{"save_figures":false,"save_mat":false,"save_csv":false}}']);
fclose(fid);

scfg = sixgr.lls6g.config.loadScenarioConfig(scenarioPath);
cfg = sixgr.lls6g.buildInternalConfig(scfg, fullfile(tmp, "run"));

assert(double(cfg.scenario.layout.nSites) == 20, ...
    "deployment_topology.num_sites must wire into scenario.layout.nSites.");
assert(double(cfg.scenario.layout.nSectorsPerSite) == 3, ...
    "deployment_topology.num_cells with 20 sites must resolve to 3 sectors/site.");
assert(abs(double(cfg.scenario.layout.interSiteDistance_m) - 500) < 1e-9, ...
    "deployment_topology.inter_site_distance must wire into scenario.layout.interSiteDistance_m.");
assert(double(cfg.scenario.nUE) == 12 && double(cfg.scenario.ue.nUE) == 12, ...
    "users.n_users must wire into the LLS scenario UE count.");
assert(logical(cfg.scenario.mobility.enable), ...
    "mobility.ue_speed_kmh must enable scenario mobility.");
assert(all(abs(double(cfg.scenario.mobility.speed_kmh) - [30 30]) < 1e-9), ...
    "mobility.ue_speed_kmh must wire into scenario.mobility.speed_kmh.");
assert(strcmpi(char(string(cfg.scenario.mobility.model)), "straightLine"), ...
    "linear mobility must resolve to the strict-config straightLine mobility token.");

ok = true;
end
