function ok = testArtifactFinalizationFailClosed()
%TESTARTIFACTFINALIZATIONFAILCLOSED Missing producers remain publication failures.

setup6GRSimToolkit("Verbose", false);
runFolder = tempname();
mkdir(runFolder);
cleanup = onCleanup(@() localRemove(runFolder)); %#ok<NASGU>

cfg = struct();
cfg.scenario_id = "artifact_fail_closed_unit";
cfg.frequency = struct("center_frequency_hz", 3.5e9, ...
    "channel_bandwidth_mhz", 100);
cfg.numerology = struct("scs_khz", 30);
cfg.integration = struct("run_mode", "FIXED_SNR_SWEEP");
cfg.output = struct("artifact_contract_engine", localPolicy(true));

result = sixgr.artifact.finalizeRunFailClosed(runFolder, ...
    sixgr.artifact.EvidenceRegistry(), cfg, struct());
assert(result.Executed && ~result.Ok && result.Status == "FAIL");
assert(result.ContractCount > 0 && result.RequiredFailureCount > 0);
assert(result.ErrorIdentifier == "sixgr:artifact:RequiredArtifactGenerationFailed");
assert(isfile(result.AuditPath) && isfile(result.FailurePath));
assert(~isfolder(fullfile(runFolder, "components")), ...
    "A failed contract finalization must not publish a partial component tree.");
status = jsondecode(fileread(fullfile(runFolder, "artifact_generation", ...
    "artifact_contract_finalization_status.json")));
assert(string(status.Status) == "FAIL" && ~logical(status.Ok));

disabledRoot = tempname();
mkdir(disabledRoot);
disabledCleanup = onCleanup(@() localRemove(disabledRoot)); %#ok<NASGU>
cfg.output.artifact_contract_engine = localPolicy(false);
disabled = sixgr.artifact.finalizeRunFailClosed(disabledRoot, ...
    sixgr.artifact.EvidenceRegistry(), cfg, struct());
assert(~disabled.Executed && disabled.Ok && disabled.Status == "DISABLED_BY_YAML");

ok = true;
fprintf("PASS testArtifactFinalizationFailClosed: enabled missing evidence fails closed without hiding completed execution.\n");
end

function policy = localPolicy(enabled)
policy = struct( ...
    "enabled", logical(enabled), ...
    "contract_root", "tests/vectors", ...
    "legacy_reference_root", "artifacts", ...
    "legacy_reference_usage", "coverage_inventory_only", ...
    "catalog_scope", "runtime_in_path", ...
    "profiles", "base", ...
    "domains", "pdsch", ...
    "publish_root", "components", ...
    "source_policy", "runtime_memory_only", ...
    "truth_only", true, ...
    "fail_on_missing_required", true, ...
    "evidence_scope", "in_path", ...
    "require_identity_columns", true, ...
    "require_radio_identity_columns", true, ...
    "atomic_replace", true, ...
    "image_format", "none", ...
    "raster_authority", "post_run_csv_contract_materializer", ...
    "allow_svg", false, ...
    "allow_placeholder_evidence", false);
end

function localRemove(pathValue)
if isfolder(pathValue)
    rmdir(pathValue, "s");
end
end
