function ok = testPDSCHStudyImmutableCodingPlans()
%TESTPDSCHSTUDYIMMUTABLECODINGPLANS Guard exact-plan repetition decoding.

setup6GRSimToolkit("Verbose", false, "RunToolboxChecks", false);
localAssertIdentifier(@() sixgr.pdsch.DLSCHEncoder( ...
    struct("TransportBlockSize",40), struct("Segmentation",struct())), ...
    "sixgr:pdsch:DLSCHEncoder:MissingCodingPlan");
localAssertIdentifier(@() sixgr.pdsch.DLSCHDecoder( ...
    struct("CRCError",false,"Ok",true)), ...
    "sixgr:pdsch:DLSCHDecoder:MissingCodingPlan");
localAssertIdentifier(@() sixgr.pdsch.CodewordLayerMapper( ...
    struct("NumLayers",1)), ...
    "sixgr:pdsch:CodewordLayerMapper:LegacyMetadataForbidden");
localAssertIdentifier(@() sixgr.pdsch.PDSCHScrambler( ...
    struct(), struct(), struct()), ...
    "sixgr:pdsch:PDSCHScrambler:LegacyMetadataForbidden");
localAssertIdentifier(@() sixgr.pdsch.PDSCHModulator(struct()), ...
    "sixgr:pdsch:PDSCHModulator:LegacyMetadataForbidden");

cfg = sixgr.config.defaultConfig();
cfg.channel.model = "AWGN";
cfg.channel.awgnOnly = true;
cfg.channel.nTxAnt = 1;
cfg.channel.nRxAnt = 1;
cfg.pdsch6gr = struct( ...
    "RNTI",4660, ...
    "Numerology",0, ...
    "CarrierFrequencyHz",2e9, ...
    "DuplexMode","FDD", ...
    "ChannelBandwidthMHz",5, ...
    "NSizeGrid",12, ...
    "NTx",1, ...
    "NRx",1, ...
    "NumLayers",1, ...
    "NumCodewords",1, ...
    "ModulationPerCodeword",{{"QPSK"}}, ...
    "TargetCodeRatePerCodeword",308/1024, ...
    "MCSMode","fixed", ...
    "FixedMCS",4, ...
    "MCSUECapability1024QAM",false, ...
    "MCSRRCEnabled1024QAM",false, ...
    "MCSDCIEnabled1024QAM",false, ...
    "MCSDeploymentAllows1024QAM",false, ...
    "MCSFrequencyRange","FR1", ...
    "MCSOperatingBand","n1", ...
    "MCSDeploymentClass","controlled_test", ...
    "MCSFrequencyRangeAllows1024QAM",false, ...
    "MCSBandAllows1024QAM",false, ...
    "HARQEnabled",false, ...
    "MaxHARQTx",1, ...
    "EnablePDSCHRepetition",true, ...
    "RepetitionMode","inter_slot", ...
    "RepetitionCount",2, ...
    "EnablePTRS",false, ...
    "ChannelModel","AWGN", ...
    "SNRdB",35, ...
    "FDRAType","type1_riv", ...
    "RIV",36, ...
    "NumRB",4, ...
    "RBStart",0, ...
    "MappingType","B", ...
    "StartSymbol",2, ...
    "NumSymbols",8, ...
    "DMRSConfigType",1, ...
    "DMRSAdditionalPosition",0, ...
    "DMRSNumPorts",1, ...
    "DMRSPortSet",0, ...
    "QueueBits",512, ...
    "Seed",991);
point = struct( ...
    "ScenarioID","immutable_plan_repetition", ...
    "SNRdB",35, ...
    "FDRAType","type1_riv", ...
    "MappingType","B", ...
    "StartSymbol",2, ...
    "NumSymbols",8, ...
    "ChannelModel","AWGN", ...
    "DelaySpread_ns",30, ...
    "Rank",1, ...
    "RepetitionMode","inter_slot", ...
    "PTRSMode","disabled", ...
    "SpeedKmh",0, ...
    "DMRSAdditionalPosition",0, ...
    "NumTrials",1);
outputDir = tempname;
cleanup = onCleanup(@() localRemoveDirectory(outputDir)); %#ok<NASGU>
study = sixgr.pdsch.runPDSCHStudyLLS( ...
    cfg, "ScenarioMatrix", point, "WriteOutputs", false, ...
    "Verbose", false, "OutputDir", outputDir);

rows = study.TBLevelResults;
assert(height(rows) == 1, ...
    "Focused immutable-plan study must materialize one TB row.");
assert(logical(rows.coding_plan_identity_verified(1)), ...
    "Study repetition must verify identical TX plan IDs and hashes.");
assert(logical(rows.repetition_combining_applied(1)), ...
    "Two study copies must use position-aware recovered-LLR combining.");
assert(string(rows.repetition_combining_mode(1)) == ...
        "position_aware_rate_recovery_soft_buffer", ...
    "Study repetition reported the wrong combining mode.");
assert(string(rows.decode_source(1)) == ...
        "explicit_dlsch_primitives_truth", ...
    "Study repetition must decode through the explicit plan-owned chain.");
assert(string(study.TrialLevelResults.tdra_mode) == "B", ...
    "Study MappingType B must survive TDRA and waveform materialization.");
assert(string(study.TrialLevelResults.modulation_per_cw) == ...
        string(rows.modulation_per_cw) ...
        && abs(double(study.TrialLevelResults. ...
            target_code_rate_per_cw) - ...
            double(rows.target_code_rate_per_cw)) ...
            <= 1e-12, ...
    ["Trial-level modulation/rate must report the materialized ActiveAMC " ...
    "operating point, including any queue-driven MCS backoff."]);
assert(strlength(string(rows.coding_plan_ids(1))) > 0 ...
        && strlength(string(rows.coding_layout_hashes(1))) > 0, ...
    "Study repetition must retain immutable plan IDs and layout hashes.");

fprintf("PDSCH study immutable coding plans: 1 production repetition, " + ...
    "1 position-aware combine, 5/5 typed legacy-signature rejections.\n");
ok = true;
end

function localAssertIdentifier(fn, expected)
try
    fn();
catch cause
    assert(string(cause.identifier) == string(expected), ...
        "Observed %s, expected %s.", cause.identifier, expected);
    return;
end
error("sixgr:test:ExpectedErrorNotThrown", ...
    "Expected error %s was not thrown.", expected);
end

function localRemoveDirectory(pathValue)
if isfolder(pathValue)
    rmdir(pathValue, "s");
end
end
