function ok = testSRSPUSCHRankPowerConservation()
% Exact declared-channel algebra; not a simulated radio measurement.
% An SRS reference SINR must not erase the power split in the selected
% native PUSCH codebook. Compare with independently computed MMSE errors.
assert(exist('nrPUSCHCodebook','file')==2, ...
    'sixgr:test:Required5GToolboxUnavailable','Native PUSCH codebooks are required.');
cfg = struct();
cfg.phy.pusch.transmissionScheme = 'codebook';
cfg.phy.pusch.transformPrecoding = false;
cfg.phy.pusch.NumAntennaPorts = 4;
cfg.phy.pusch.numAntennaPorts = 4;
H = repmat(reshape(complex(eye(4)),1,1,4,4),24,2,1,1);
rows = struct([]);
for referenceSINR_dB = [20 30]
    nVar = 10^(-referenceSINR_dB/10);
    for maxRank = [1 2 4]
        cfg.phy.pusch.maxRankDefault = maxRank;
        raw = sixgr.phy.ul.estimateSRSRITPMI(H,nVar,cfg);
        predicted = sixgr.phy.ul.estimateSRSRITPMI(H,nVar,cfg, ...
            'AbsoluteSINRAnchor_dB',referenceSINR_dB, ...
            'AbsoluteSINRAnchorSource','measured_ul_srs_pilot_reconstruction_sinr', ...
            'AbsoluteSINRAnchorPowerReferencePlane', ...
            'receiver_srs_resource_elements_after_ofdm_demodulation', ...
            'ReferenceSignalPower',1, ...
            'ReferencePowerSource','received_reference_grid_plus_receiver_hest', ...
            'PUSCHToSRSReferenceEnergyRatio',1, ...
            'PUSCHToSRSReferenceEnergySource', ...
            'normalized_fixed_snr_unit_grid_reference_no_device_power_scaling');
        assert(raw.RI==maxRank && predicted.RI==raw.RI && predicted.TPMI==raw.TPMI, ...
            'Declared high-SNR identity fixture must exercise each requested rank.');
        assert(string(predicted.SelectedPostEqSINRValueStatus)=="PASS" && ...
            predicted.SelectedPostEqSINRCalibrationOffset_dB==0 && ...
            abs(predicted.SelectedDisturbancePower-nVar)<1e-12, ...
            'A diagnostic-only result or hidden post-MMSE shift cannot pass calibration.');
        % Native nrPUSCHCodebook is layer-by-port; transpose without
        % conjugation, independently of the production projection helper.
        W = double(nrPUSCHCodebook(raw.RI,4,raw.TPMI,false)).';
        covariance = (eye(raw.RI)+(W'*W)/nVar)\eye(raw.RI);
        expected = 10*log10(1./real(diag(covariance))-1);
        rawError = max(abs(double(raw.SelectedPostEqSINRPerLayer_dB(:))-expected));
        predictionError = max(abs(double(predicted.SelectedPostEqSINRPerLayer_dB(:))-expected));
        assert(rawError<1e-9,'Independent MMSE reference disagrees with raw spatial calculation.');
        row = struct('ReferenceSINR_dB',referenceSINR_dB, ...
            'Rank',raw.RI,'TPMI',raw.TPMI,'TotalPrecoderEnergy',sum(abs(W(:)).^2), ...
            'IndependentMinimumSINR_dB',min(expected), ...
            'PredictedMinimumSINR_dB',predicted.SelectedMinimumLayerMeanPostEqSINR_dB, ...
            'RawError_dB',rawError,'PredictionError_dB',predictionError);
        rows = [rows;row]; %#ok<AGROW>
    end
end
disp(struct2table(rows));
assert(all([rows.PredictionError_dB]<1e-9), ...
    'sixgr:test:SRSRankPowerInflation', ...
    'SRS anchoring must preserve native PUSCH codebook power and independent MMSE SINR at every rank.');
fprintf('SRS_PUSCH_RANK_POWER_CONSERVATION_PASS cases=%d\n',numel(rows));
ok = true;
end
