function ok = testSchedulerMUMIMOGrouping()
%TESTSCHEDULERMUMIMOGROUPING Validate causal shared-PRB PF grouping.

setup6GRSimToolkit("Verbose", false);

tmpRoot = string(tempname);
mkdir(tmpRoot);
cleanup = onCleanup(@()localRemoveTree(tmpRoot)); %#ok<NASGU>
scenarioPath = fullfile(pwd, "simulator", "configs", "scenarios", ...
    "webgui_sinr_sweep_64x4_mu_mimo_repair_slice.yaml");
scenario = sixgr.lls6g.config.loadScenarioConfig(scenarioPath);
cfg = sixgr.lls6g.buildInternalConfig(scenario, fullfile(tmpRoot, "run"));
assert(string(cfg.phy.pdsch.precoding.normalizationConvention) == ...
    "unit_frobenius" && ...
    string(cfg.phy.pusch.precoding.normalizationConvention) == ...
    "unit_frobenius", ...
    ["Both master-YAML data-channel power conventions must reach the " ...
     "production frozen-grant path without a MATLAB default."]);

% Four measured-CSI candidates are ordered equally by PF.  UE 2 shares
% UE 1's PMI, while UE 3 is the first compatible codebook candidate.  The
% scheduler must search beyond the two-user transmission cap and then cap
% the selected group at two transmitted users.
ue = localUEs([0 0 1 0], [10 10 10 10]);
nRF = double(cfg.runtime.antenna.gnb.NumTxRFChains);
muArch = sixgr.rf.AntennaArrayFactory.resolvePortArchitecture(cfg, "bs", ...
    "Signal", "PDSCH", "NumElements", 64, "NumPorts", nRF, ...
    "NumRFChains", nRF, "MinimumPorts", 4, ...
    "MatrixAuthorityScope", "role_only");
F = double(muArch.HybridElementToPortMatrix);
element = (0:63).';
qCorrelatedA = [exp(1i .* 2 .* pi .* element ./ 64), ...
    exp(1i .* 4 .* pi .* element ./ 64), ...
    exp(1i .* 6 .* pi .* element ./ 64), ...
    exp(1i .* 8 .* pi .* element ./ 64)] ./ sqrt(64);
qIndependent = [exp(1i .* 10 .* pi .* element ./ 64), ...
    exp(1i .* 14 .* pi .* element ./ 64), ...
    exp(1i .* 18 .* pi .* element ./ 64), ...
    exp(1i .* 22 .* pi .* element ./ 64)] ./ sqrt(64);
[qCorrelatedB, ~] = qr(0.65 .* qCorrelatedA + 0.75 .* qIndependent, 0);
rawLeakage_dB = 10 * log10(norm(qCorrelatedA' * qCorrelatedB, "fro")^2 / 2);
designed = sixgr.phy.mimo.designMeasuredMUMIMOPair( ...
    qCorrelatedA, qCorrelatedB, cfg, "DL", 2, 2);
assert(rawLeakage_dB > -15 && designed.Compatible && ...
    designed.WorstLeakage_dB <= -15 && ...
    designed.MinimumDesiredGainObserved_dB >= -30, ...
    "A correlated measured pair must pass only after executable block diagonalization, not by relabeling raw overlap.");
assert(isequal(designed.HybridElementToPortMatrix, F) && ...
    string(designed.HybridRFDesignStatus) == "fixed_configured_hybrid_matrix", ...
    ["Measured DL MU design must retain the exact YAML-configured 64x32 " ...
     "phase-only RF hardware matrix and adapt only its baseband block diagonalizer."]);
assert(string(designed.ContractVersion) == "MeasuredMUMIMOPairDesign/v13" && ...
    string(designed.SpatialSignatureSubspaceMode) == ...
        "complete_detectable_subspace" && ...
    abs(norm(designed.Member1PrecoderPhysical, "fro")^2 - 1) <= 1e-12 && ...
    abs(norm(designed.Member2PrecoderPhysical, "fro")^2 - 1) <= 1e-12 && ...
    norm(designed.HybridElementToPortMatrix * ...
        designed.Member1PrecoderLogicalPorts - ...
        designed.Member1PrecoderPhysical, "fro") <= 1e-12 && ...
    norm(designed.HybridElementToPortMatrix * ...
        designed.Member2PrecoderLogicalPorts - ...
        designed.Member2PrecoderPhysical, "fro") <= 1e-12, ...
    "Rank-2 MU design must allocate unit total per-UE power and preserve the exact RF/baseband factorization.");

% Fully digital arrays are not hybrid arrays.  Four independently
% controlled element/RF dimensions must nevertheless support an exact
% measured rank-2 + rank-2 block-diagonalizing precoder.  Conversely, two
% UEs with the same measured subspace remain physically incompatible.
digitalCfg = struct();
digitalCfg.mac.scheduler.muMimoPrecoderLeakageThreshold_dB = -15;
digitalCfg.mac.scheduler.muMimoMinimumDesiredSubspaceGain_dB = -30;
digitalCfg.mac.scheduler.muMimoPhaseOnlyProjectionMaxIterations = 50;
digitalCfg.mac.scheduler.muMimoPhaseOnlyProjectionTolerance = 1e-10;
digitalCfg.mac.scheduler.muMimoSpatialSignatureMode = ...
    "complete_detectable_subspace";
digitalCfg.runtime.antenna.gnb.NumTxRFChains = 4;
qDigitalA = eye(4, 2);
qDigitalB = eye(4);
qDigitalB = qDigitalB(:, 3:4);
digitalDesigned = sixgr.phy.mimo.designMeasuredMUMIMOPair( ...
    qDigitalA, qDigitalB, digitalCfg, "DL", 2, 2, "direct_dl_csirs");
assert(digitalDesigned.Compatible && ...
    string(digitalDesigned.TransmitArchitecture) == ...
        "fully_digital_element_control" && ...
    string(digitalDesigned.HybridRFDesignPolicy) == ...
        "fully_digital_direct_element_control" && ...
    string(digitalDesigned.HybridRFDesignStatus) == ...
        "fully_digital_full_rank_port_to_element_mapping" && ...
    isequal(size(digitalDesigned.Member1PrecoderPhysical), [4 2]) && ...
    isequal(size(digitalDesigned.Member2PrecoderPhysical), [4 2]), ...
    ["A square full-rank four-element/four-RF-chain array must execute " ...
     "measured fully-digital MU precoding without being mislabeled hybrid."]);
digitalIncompatible = sixgr.phy.mimo.designMeasuredMUMIMOPair( ...
    qDigitalA, qDigitalA, digitalCfg, "DL", 2, 2, "direct_dl_csirs");
assert(~digitalIncompatible.Compatible, ...
    ["Identical per-UE measured subspaces must remain incompatible; the " ...
     "fully-digital path must not fabricate spatial separability."]);
fddDesigned = sixgr.phy.mimo.designMeasuredMUMIMOPair( ...
    qCorrelatedA, qCorrelatedB, cfg, "DL", 2, 2, "direct_dl_csirs");
assert(fddDesigned.Compatible && ...
    string(fddDesigned.SpatialAuthorityMode) == "direct_dl_csirs" && ...
    contains(string(fddDesigned.MetricSource), "fdd_csirs_direct_transmit") && ...
    contains(string(fddDesigned.EvidenceSource), "measured_csirs"), ...
    ["FDD MU design must use the directly measured CSI-RS transmit " ...
     "subspace without applying the TDD conjugate-reciprocity transform."]);
ulDesigned = sixgr.phy.mimo.designMeasuredMUMIMOPair( ...
    qCorrelatedA, qCorrelatedB, cfg, "UL", 2, 2);
assert(ulDesigned.Compatible && ...
    string(ulDesigned.ULReceiveProcessingMode) == ...
        "full_dimensional_per_re_irc" && ...
    isequal(size(ulDesigned.Member1AdmissionReceiveCombiner), [64 2]) && ...
    norm(ulDesigned.Member1AdmissionReceiveCombiner' * ...
        ulDesigned.Member1AdmissionReceiveCombiner - eye(2), "fro") <= 1e-12 && ...
    norm(ulDesigned.Member2AdmissionReceiveCombiner' * ...
        ulDesigned.Member2AdmissionReceiveCombiner - eye(2), "fro") <= 1e-12 && ...
    isequal(size(ulDesigned.Member1ReceiveCombiner), [64 64]) && ...
    isequal(ulDesigned.Member1ReceiveCombiner, eye(64)) && ...
    isequal(ulDesigned.Member2ReceiveCombiner, eye(64)) && ...
    norm(ulDesigned.Member1ReceiveCombiner' * ...
        ulDesigned.Member1ReceiveCombiner - eye(64), "fro") <= 1e-12 && ...
    norm(ulDesigned.Member2ReceiveCombiner' * ...
        ulDesigned.Member2ReceiveCombiner - eye(64), "fro") <= 1e-12 && ...
    ulDesigned.WorstLeakage_dB <= -15, ...
    "UL MU admission must use a causal measured nulling diagnostic while " + ...
    "the executable per-RE IRC path preserves all receiver branches.");
ueUL = localUEs([0 0], [10 10]);
for ulIndex = 1:numel(ueUL)
    ueUL(ulIndex).ULBufferBytes = 20000;
    ueUL(ulIndex).SRSValid = true;
    ueUL(ulIndex).SRSCausalUsable = true;
    ueUL(ulIndex).SRSCausalMeasurementId = "measured-srs-" + string(ulIndex);
    ueUL(ulIndex).LastSuccessfulSRSSlot = 1;
end
ueUL(1).MUMIMOSpatialSignature = qCorrelatedA;
ueUL(2).MUMIMOSpatialSignature = qCorrelatedB;
ueUL = localBindMeasuredSpatialSignatures(ueUL, "UL", 0);
ulScheduler = sixgr.l2.mac.SchedulerPF(cfg, "Direction", "UL");
[ulGrants, ~] = ulScheduler.schedule(0, ueUL, ...
    struct("PRBSet", 0:23, "SymbolAllocation", double(cfg.phy.pusch.symbolAllocation)));
assert(numel(ulGrants) == 2 && ...
    all(arrayfun(@(g) logical(g.MUMIMOEnabled) && ...
        isequal(size(g.MUMIMOReceiveCombiningMatrix), [64 64]) && ...
        isequal(g.MUMIMOReceiveCombiningMatrix, eye(64)) && ...
        string(g.MUMIMOReceiveProcessingMode) == ...
            "full_dimensional_per_re_irc" && ...
        string(g.MUMIMOReceiverAlgorithm) == ...
            "full_dimensional_per_re_irc" && ...
        strlength(string(g.MUMIMOAdmissionReceiveCombiningMatrixSHA256)) == 64 && ...
        isequal(size(g.MUMIMOAdmissionReceiveCombiningMatrix), [64 2]), ...
        ulGrants)), ...
    "Every scheduled UL MU grant must freeze the measured admission matrix separately from a full-dimensional IRC preprocessor.");
assert(all(arrayfun(@(g) ...
    isequal(g.PHYGrant.LegacyGrantSnapshot.MUMIMOReceiveCombiningMatrix, eye(64)) && ...
    string(g.PHYGrant.LegacyGrantSnapshot.MUMIMOReceiverAlgorithm) == ...
        "full_dimensional_per_re_irc", ulGrants)), ...
    "The immutable PHY grant must carry the exact full-dimensional UL IRC authority into receiver execution.");
ue(1).MUMIMOSpatialSignature = qCorrelatedA;
ue(2).MUMIMOSpatialSignature = ue(1).MUMIMOSpatialSignature;
ue(3).MUMIMOSpatialSignature = qCorrelatedB;
ue(4).MUMIMOSpatialSignature = ue(1).MUMIMOSpatialSignature;
ue = localBindMeasuredSpatialSignatures(ue, "DL", 0);
scheduler = sixgr.l2.mac.SchedulerPF(cfg, "Direction", "DL");
[grants, info] = scheduler.schedule(0, ue, ...
    struct("PRBSet", 0:23, "SymbolAllocation", [2 12]));
assert(numel(grants) == 2, ...
    "The configured two-user MU opportunity must emit exactly two grants.");
assert(isequal(sort(double([grants.RNTI])), [1 3]), ...
    "MU pairing must search the complete PF candidate set for a compatible measured-PMI peer.");
assert(all(double([grants.MUMIMOGroupSize]) == 2) && ...
    numel(unique(double([grants.MUMIMOGroupId]))) == 1 && ...
    all(string({grants.MUMIMOPairingStatus}) == ...
    "paired_shared_prb_spatial_multiplexing"), ...
    "Both grants must carry one exact shared-PRB MU group identity.");
assert(isequal(double(grants(1).PRBSet(:)), double(grants(2).PRBSet(:))) && ...
    isequal(double(grants(1).SymbolAllocation(:)), ...
    double(grants(2).SymbolAllocation(:))), ...
    "MU grants must occupy identical PRB and symbol resources.");
allDMRSPorts = [double(grants(1).DMRSPortSet(:).'), ...
    double(grants(2).DMRSPortSet(:).')];
assert(numel(unique(allDMRSPorts)) == 4 && ...
    numel(grants(1).DMRSPortSet) == 2 && numel(grants(2).DMRSPortSet) == 2, ...
    "Two rank-2 MU users must receive four disjoint logical DM-RS ports.");
frozen = arrayfun(@(g) logical(g.PHYGrant.IsFrozen) && ...
    strlength(string(g.PHYGrant.PrecodingState.SelectedMatrixSHA256)) > 0, grants);
assert(all(frozen), ...
    "Every MU member must be frozen independently after group finalization.");
assert(all(arrayfun(@(g) g.PHYGrant.AntennaArchitecture.NumLogicalPorts == nRF && ...
    isequal(size(g.PHYGrant.PrecodingState.MatrixLogicalPorts), [nRF 2]) && ...
    isequal(size(g.PHYGrant.PrecodingState.MatrixPhysicalPorts), [64 2]), grants)), ...
    "Two rank-2 DL members must freeze distinct 32-port baseband and 64-element physical precoders.");
assert(all(arrayfun(@(g) ...
    abs(norm(g.PHYGrant.PrecodingState.MatrixPhysicalPorts, "fro")^2 - 1) <= 1e-12 && ...
    abs(norm(g.PHYGrant.PrecodingState.Matrix, "fro")^2 - 1) <= 1e-12, grants)), ...
    "Every frozen rank-2 DL MU grant must satisfy the unit-total-power precoder contract before replay.");
% The coupled truth runtime applies measured CQI/AMC after scheduling and
% then refreezes the exact PHY contract.  That coding-only update must not
% replace the measured MU spatial authority with the scheduler's static
% configured precoder or silently restore per-layer (Frobenius power=rank)
% normalization.
feedback = struct( ...
    "Valid", true, ...
    "CQI", 10, ...
    "RI", 2, ...
    "PMI", double(grants(1).PMI), ...
    "CRI", double(grants(1).CRI), ...
    "MCSIndex", 10, ...
    "MCSSelectionSource", "measured_srs_runtime_link_adaptation", ...
    "MCSValueStatus", "measured_feedback_adapted", ...
    "FeedbackSourceSignal", "SRS", ...
    "CQIProvenance", "measured_srs_receiver_channel_estimate", ...
    "OuterLoopEnabled", false);
amcGrant = sixgr.truth.CoupledTruthRuntime. ...
    applyMeasuredFeedbackAMCToGrantRuntime( ...
    grants(1), feedback, scheduler, cfg, "DL");
assert(logical(amcGrant.Valid) && logical(amcGrant.ExactPHYFeasible), ...
    "Measured-feedback AMC must leave the finalized MU grant executable.");
assert(double(amcGrant.MCSIndex) == 1 && ...
    string(amcGrant.MCSIndexAuthority) == ...
    "yaml_mu_mimo_first_data_mcs_until_data_feedback" && ...
    isfinite(double(amcGrant.RawCQIDerivedMCS)) && ...
    double(amcGrant.RawCQIDerivedMCS) >= double(amcGrant.MCSIndex) && ...
    double(amcGrant.NumLayers) == 2, ...
    "A first shared-PRB MU data grant driven only by SRS must retain the " + ...
    "raw measured CQI evidence and rank-2 spatial authority while using " + ...
    "the YAML-owned conservative first-data MCS.");
dataFeedback = feedback;
dataFeedback.FeedbackSourceSignal = "DL_CSI_REPORT";
dataFeedback.FeedbackCRCPass = true;
dataFeedback.HasSharedMUMIMODataFeedback = true;
dataFeedback.MCSSelectionSource = "runtime_link_adaptation_decision";
dataAdaptedGrant = sixgr.truth.CoupledTruthRuntime. ...
    applyMeasuredFeedbackAMCToGrantRuntime( ...
    grants(1), dataFeedback, scheduler, cfg, "DL");
assert(double(dataAdaptedGrant.MCSIndex) == 10 && ...
    string(dataAdaptedGrant.MCSIndexAuthority) == ...
    "runtime_link_adaptation_decision", ...
    "Actual data-channel feedback must immediately supersede first-data bootstrap authority.");
pilotFeedback = dataFeedback;
pilotFeedback.FeedbackCRCPass = NaN;
pilotFeedback.HasDataFeedback = true;
pilotFeedback.LastDataFeedbackSlot = 7;
pilotFeedback.LastDataFeedbackCRCPass = true;
pilotAdaptedGrant = sixgr.truth.CoupledTruthRuntime. ...
    applyMeasuredFeedbackAMCToGrantRuntime( ...
    grants(1), pilotFeedback, scheduler, cfg, "DL");
assert(double(pilotAdaptedGrant.MCSIndex) == 10 && ...
    string(pilotAdaptedGrant.MCSIndexAuthority) == ...
    "runtime_link_adaptation_decision", ...
    ["A newer pilot report must not erase the persistent fact that genuine " ...
     "shared-data receiver feedback has already completed."]);
initialPilotFeedback = feedback;
initialPilotFeedback.FeedbackCRCPass = NaN;
initialPilotFeedback.HasDataFeedback = false;
initialPilotFeedback.HasSharedMUMIMODataFeedback = false;
initialPilotGrant = sixgr.truth.CoupledTruthRuntime. ...
    applyMeasuredFeedbackAMCToGrantRuntime( ...
    grants(1), initialPilotFeedback, scheduler, cfg, "DL");
assert(double(initialPilotGrant.MCSIndex) == 1 && ...
    string(initialPilotGrant.MCSIndexAuthority) == ...
    "yaml_mu_mimo_first_data_mcs_until_data_feedback", ...
    ["A pilot-only DL CSI-RS report without any earlier data feedback must " ...
     "retain the YAML-owned first-data bootstrap."]);
assert(abs(norm(amcGrant.PHYGrant.PrecodingState.MatrixPhysicalPorts, "fro")^2 - 1) <= 1e-12 && ...
    isequal(double(amcGrant.PHYGrant.PrecodingState.MatrixPhysicalPorts), ...
        double(grants(1).PHYGrant.PrecodingState.MatrixPhysicalPorts)) && ...
    isequal(double(amcGrant.PHYGrant.PrecodingState.MatrixLogicalPorts), ...
        double(grants(1).PHYGrant.PrecodingState.MatrixLogicalPorts)) && ...
    isequal(double(amcGrant.PHYGrant.PrecodingState.HybridElementToPortMatrix), ...
        double(grants(1).PHYGrant.PrecodingState.HybridElementToPortMatrix)) && ...
    string(amcGrant.PHYGrant.PrecodingState.SelectedMatrixSHA256) == ...
        string(grants(1).PHYGrant.PrecodingState.SelectedMatrixSHA256), ...
    "Post-scheduler AMC refreeze must preserve the exact frozen measured-MU spatial contract.");
p1 = double(grants(1).PHYGrant.PrecodingState.MatrixPhysicalPorts);
p2 = double(grants(2).PHYGrant.PrecodingState.MatrixPhysicalPorts);
leakage1 = norm(ue(1).MUMIMOSpatialSignature.' * p2, "fro")^2 ./ ...
    max(norm(ue(1).MUMIMOSpatialSignature.' * p1, "fro")^2, realmin);
leakage2 = norm(ue(3).MUMIMOSpatialSignature.' * p1, "fro")^2 ./ ...
    max(norm(ue(3).MUMIMOSpatialSignature.' * p2, "fro")^2, realmin);
requiredLeakage = 10.^(double(grants(1).MUMIMORequiredLeakageThreshold_dB) ./ 10);
assert(leakage1 <= requiredLeakage && leakage2 <= requiredLeakage, ...
    ["Frozen physical DL MU precoders must satisfy each victim's configured " ...
     "other-user-beam/own-desired-beam leakage ratio without requiring an unnecessarily " ...
     "destructive exact zero-forcing solution."]);
assert(all(string({grants.MUMIMOHybridRFDesignPolicy}) == ...
    "fixed_configured_matrix") && ...
    all(string(arrayfun(@(g) g.PHYGrant.PrecodingState.HybridRFDesignPolicy, ...
    grants, "UniformOutput", false)) == ...
    "fixed_configured_matrix"), ...
    "Scheduler and frozen PHY grants must bind the config-selected hybrid RF design policy.");
projectedMUConfig = sixgr.phy.grant.applyPHYGrantToConfig(cfg, grants(1).PHYGrant);
projectedMUConfig = sixgr.phy.grid.applyRuntimeCarrierTimeline( ...
    projectedMUConfig, double(grants(1).ScheduledAbsoluteSlot) + 1);
assert(isequal(double(projectedMUConfig.phy.pdsch.hybridElementToPortMatrix), ...
    double(grants(1).PHYGrant.PrecodingState.HybridElementToPortMatrix)) && ...
    string(projectedMUConfig.phy.pdsch.hybridElementToPortMatrixSHA256) == ...
    string(grants(1).PHYGrant.PrecodingState.HybridElementToPortMatrixSHA256), ...
    "Grant replay must apply the exact selected phase-only RF matrix, not reconstruct the static base matrix.");
assert(string(projectedMUConfig.phy.pdsch.precoding.normalizationConvention) == ...
    string(grants(1).PHYGrant.PrecodingState.NormalizationConvention) && ...
    string(projectedMUConfig.phy.canonicalGrant.precoderNormalizationConvention) == ...
    "unit_frobenius", ...
    ["Grant replay must bind the immutable measured-MU power convention " ...
     "with the selected matrix instead of reusing a conflicting scenario default."]);
[replayCarrier, ~] = sixgr.phy.grid.makeCarrier(projectedMUConfig);
[~, ~, replayPDSCH] = sixgr.phy.grid.allocREsPDSCH(replayCarrier, projectedMUConfig, ...
    "PRBSet", double(grants(1).PRBSet(:).'), ...
    "SymbolAllocation", double(grants(1).SymbolAllocation(:).'), ...
    "Modulation", char(string(grants(1).Modulation)), ...
    "NumLayers", double(grants(1).NumLayers));
replayPrecoding = sixgr.phy.dl.resolvePDSCHPrecoding(replayPDSCH, projectedMUConfig);
assert(abs(norm(replayPrecoding.MatrixPorts, "fro")^2 - 1) <= 1e-12 && ...
    string(replayPrecoding.AppliedMatrixSHA256) == ...
        string(grants(1).PHYGrant.PrecodingState.SelectedMatrixSHA256) && ...
    isequal(double(replayPrecoding.MatrixLogicalPorts), ...
        double(grants(1).PHYGrant.PrecodingState.MatrixLogicalPorts)) && ...
    isequal(double(replayPrecoding.HybridElementToPortMatrix), ...
        double(grants(1).PHYGrant.PrecodingState.HybridElementToPortMatrix)), ...
    "Frozen MU replay must preserve the exact logical, hybrid and unit-total-power physical matrix through the transmitter resolver.");
% TX uses the actual authored scheduler DCI, not manufactured UE reception.
decodedGrant = grants(1);
decodedGrant.ControlDecodeOk = false;
decodedGrant.PDCCHGrantBindingOk = false;
[muTx, muTxInfo] = sixgr.phy.dl.PDSCH_Tx( ...
    projectedMUConfig, "PHYGrant", decodedGrant.PHYGrant, ...
    "SchedulerGrantContext", decodedGrant, "CompactOutput", true);
assert(size(muTx.Waveform, 2) == 64 && ...
    double(muTxInfo.Precoding.NumLogicalPorts) == nRF && ...
    string(muTxInfo.Precoding.AppliedMatrixSHA256) == ...
        string(grants(1).PHYGrant.PrecodingState.SelectedMatrixSHA256), ...
    ["The production PDSCH transmitter must materialize all 64 element " ...
     "waveforms from the exact frozen 32-port measured-MU baseband precoder."]);
assert(sixgr.phy.grant.resolveDLLogicalPortCount( ...
    projectedMUConfig, grants(1), grants(1).NumLayers) == nRF, ...
    "An explicit RF-port grant/configuration must outrank the two-layer capability ceiling.");
portPriorityCfg = projectedMUConfig;
portPriorityCfg.phy.maxDLLayers = 2;
portPriorityCfg.phy.pdsch.maxLayers = 2;
assert(sixgr.phy.grant.resolveDLLogicalPortCount( ...
    portPriorityCfg, struct(), 2) == nRF, ...
    "Explicit phy.pdsch.numPorts must not be reduced to maxDLLayers during replay pruning.");
try
    invalidPortCfg = portPriorityCfg;
    invalidPortCfg.phy.pdsch.numPorts = 1;
    sixgr.phy.grant.resolveDLLogicalPortCount(invalidPortCfg, struct(), 2);
    error("testSchedulerMUMIMOGrouping:ExpectedLogicalPortFailure", ...
        "A logical-port declaration below the transmitted rank was accepted.");
catch ME
    assert(string(ME.identifier) == ...
        "sixgr:phy:grant:ConfiguredLogicalPortCountOutOfRange", ...
        "Invalid configured logical-port dimensions must fail with the typed contract error.");
end

% A frozen single-user signal matrix is a per-grant selection, not the
% immutable base RF architecture. The next two-user rank-2 opportunity must
% therefore recover every YAML-configured logical RF port from the role-level architecture.
staleSingleUserCfg = projectedMUConfig;
staleSingleUserCfg.phy.pdsch.hybridElementToPortMatrix = ...
    double(grants(1).PHYGrant.PrecodingState.HybridElementToPortMatrix(:, 1:2));
staleSingleUserCfg.phy.pdsch.hybridElementToPortMatrixSHA256 = char( ...
    sixgr.phy.mimo.MatrixContract.digest( ...
    staleSingleUserCfg.phy.pdsch.hybridElementToPortMatrix));
redesigned = sixgr.phy.mimo.designMeasuredMUMIMOPair( ...
    qCorrelatedA, qCorrelatedB, staleSingleUserCfg, "DL", 2, 2);
assert(redesigned.Compatible && ...
    isequal(size(redesigned.HybridElementToPortMatrix), [64 nRF]), ...
    "A previous 64x2 per-grant PDSCH matrix must not override the 64x32 base-array MU design.");

% Exercise the complete production freeze boundary with that stale
% signal-level matrix. This is the late-slot sequence that occurs after a
% single-user beam has already been executed and a measured-SRS MU pair is
% admitted on a later scheduling occasion.
staleSignalScheduler = sixgr.l2.mac.SchedulerPF( ...
    staleSingleUserCfg, "Direction", "DL");
staleSignalGrants = staleSignalScheduler.schedule(0, ue, ...
    struct("PRBSet", 0:23, "SymbolAllocation", [2 12]));
assert(numel(staleSignalGrants) == 2 && ...
    all(arrayfun(@(g) isequal( ...
        double(g.PHYGrant.PrecodingState.HybridElementToPortMatrix), F), ...
        staleSignalGrants)) && ...
    all(string({staleSignalGrants.MUMIMOHybridRFDesignPolicy}) == ...
        "fixed_configured_matrix"), ...
    ["A later measured-SRS MU grant must freeze the YAML-owned role-level " ...
     "hybrid architecture, not a stale per-grant PDSCH beam selection."]);

% Conversely, a malformed role-level matrix is authoritative configuration
% and must still fail loudly instead of being silently regenerated.
invalidBaseCfg = cfg;
invalidBaseCfg.rf.bs.hybridElementToPortMatrix = ...
    staleSingleUserCfg.phy.pdsch.hybridElementToPortMatrix;
try
    sixgr.phy.mimo.designMeasuredMUMIMOPair( ...
        qCorrelatedA, qCorrelatedB, invalidBaseCfg, "DL", 2, 2);
    error("testSchedulerMUMIMOGrouping:ExpectedBaseMatrixShapeFailure", ...
        "Malformed role-level base RF matrix was unexpectedly accepted.");
catch ME
    assert(string(ME.identifier) == ...
        "AntennaArrayFactory:ConfiguredHybridMatrixShapeMismatch", ...
        "A malformed authoritative base RF matrix must retain its typed shape error.");
end
decision = info.CandidateTable;
scheduledRNTI = sort(double(decision.RNTI(logical(decision.Scheduled))));
assert(isequal(scheduledRNTI(:).', [1 3]), ...
    "Candidate-decision truth must identify the same measured-CSI MU pair as the grants.");
pairedDecision = decision(logical(decision.Scheduled), :);
assert(all(pairedDecision.MUMIMOAdmissionEvaluated) && ...
    all(pairedDecision.MUMIMOAdmissionCompatible) && ...
    isequal(sort(double(pairedDecision.MUMIMOAdmissionPeerRNTI)), [1; 3]) && ...
    all(isfinite(double(pairedDecision.MUMIMOAdmissionWorstLeakage_dB))) && ...
    all(string(pairedDecision.MUMIMOAdmissionEvidenceSource) == ...
        "causal_measured_srs_complete_peer_subspace_reciprocity_phase_only_hybrid_and_frozen_baseband"), ...
    "Candidate-decision truth must expose the exact peer, leakage and measured-SRS evidence that admitted the MU pair.");
assert(all(double([grants.MUMIMOPairingMetricValue_dB]) <= ...
        double([grants.MUMIMORequiredLeakageThreshold_dB])) && ...
    all(string({grants.MUMIMOPairingEvidenceSource}) == ...
    "causal_measured_srs_complete_peer_subspace_reciprocity_phase_only_hybrid_and_frozen_baseband") && ...
    all(strlength(string({grants.MUMIMOSpatialFilterMatrixSHA256})) == 64), ...
    "MU grants must retain the measured executable spatial-filter evidence.");
assert(all(string({grants.MUMIMOSpatialDesignEvidenceSource}) == ...
    string({grants.MUMIMOPairingEvidenceSource})) && ...
    all(strlength(string({grants.HybridElementToPortMatrixSHA256})) == 64) && ...
    all(strlength(string({grants.BaseHybridElementToPortMatrixSHA256})) == 64), ...
    "Frozen filter authority and current MU pairing evidence must be independently digest-bound.");

% Receiver completion must not erase the exact frozen MU contract when the
% raw waveform trial is streamed. Conversely, MU annotation must not alter
% receiver-derived measurements.
trialT = table([12.5; 13.0], [true; false], ...
    'VariableNames', {'PostEqSINR_dB','CRCPass'});
annotatedT = sixgr.truth.annotateFrozenMUMIMOTrialEvidence(trialT, grants(1));
assert(isequal(annotatedT.PostEqSINR_dB, trialT.PostEqSINR_dB) && ...
    isequal(annotatedT.CRCPass, trialT.CRCPass), ...
    "Frozen MU evidence annotation must not overwrite receiver measurements.");
assert(all(annotatedT.MUMIMOEnabled) && ...
    all(annotatedT.MUMIMOGroupSize == grants(1).MUMIMOGroupSize) && ...
    all(annotatedT.MUMIMOGroupId == grants(1).MUMIMOGroupId) && ...
    all(annotatedT.MUMIMOPairingStatus == string(grants(1).MUMIMOPairingStatus)) && ...
    all(annotatedT.MUMIMOPairingMetricSource == string(grants(1).MUMIMOPairingMetricSource)) && ...
    all(annotatedT.MUMIMOPairingMetricValue_dB == grants(1).MUMIMOPairingMetricValue_dB) && ...
    all(annotatedT.MUMIMOPairingEvidenceSource == string(grants(1).MUMIMOPairingEvidenceSource)) && ...
    all(annotatedT.MUMIMOSpatialDesignEvidenceSource == string(grants(1).MUMIMOSpatialDesignEvidenceSource)) && ...
    all(annotatedT.HybridElementToPortMatrixSHA256 == string(grants(1).HybridElementToPortMatrixSHA256)) && ...
    all(annotatedT.PRBStart == min(grants(1).PRBSet)) && ...
    all(annotatedT.PRBCount == numel(unique(grants(1).PRBSet))) && ...
    all(annotatedT.SymbolStart == grants(1).SymbolAllocation(1)) && ...
    all(annotatedT.NumSymbols == grants(1).SymbolAllocation(2)), ...
    "Raw trials must preserve every exact MU pairing field from the frozen grant.");

% A different configured PMI without measured CQI is not causal MU
% evidence.  Bootstrap rows remain orthogonal SU grants rather than being
% forced into an MU label.
bootstrapUE = localUEs([0 1 2 3], [1 1 1 1]);
for bootstrapIndex = 1:numel(bootstrapUE)
    % CQI 0 is an explicit out-of-range report, not missing feedback.  A
    % bootstrap scheduling test must instead carry a positive conservative
    % CQI with explicit non-measured provenance and authorization.
    bootstrapUE(bootstrapIndex).FeedbackValid = false;
    bootstrapUE(bootstrapIndex).BootstrapCQIUsableForScheduling = true;
    bootstrapUE(bootstrapIndex).BootstrapCQISource = ...
        "yaml_enabled_conservative_bootstrap_not_measured_cqi";
end
bootstrapScheduler = sixgr.l2.mac.SchedulerPF(cfg, "Direction", "DL");
bootstrapGrants = bootstrapScheduler.schedule(0, bootstrapUE, ...
    struct("PRBSet", 0:23, "SymbolAllocation", [2 12]));
assert(numel(bootstrapGrants) == 2 && ...
    all(double([bootstrapGrants.MUMIMOGroupSize]) == 1) && ...
    ~isequal(double(bootstrapGrants(1).PRBSet(:)), ...
    double(bootstrapGrants(2).PRBSet(:))), ...
    "Unmeasured bootstrap CQI must not be upgraded to shared-PRB MU execution.");
assert(all(arrayfun(@(g) ...
    abs(norm(g.PHYGrant.PrecodingState.MatrixPhysicalPorts, "fro")^2 - 1) <= 1e-12 && ...
    abs(norm(g.PHYGrant.PrecodingState.MatrixLogicalPorts, "fro")^2 - 1) <= 1e-12, ...
    bootstrapGrants)), ...
    "Rank-2 SU fallback grants must split the configured total power equally across layers.");

% Even valid CQI and different PMI values are insufficient without a
% measured spatial matrix.  This guards against restoring the former
% PMI-inequality proxy.
pmiOnlyUE = localUEs([0 1 2 3], [10 10 10 10]);
retxHARQ = sixgr.l2.mac.HARQEntity(cfg, "Direction", "DL", ...
    "NumProcesses", 4, "MaxRetx", 3);
pmiOnlyScheduler = sixgr.l2.mac.SchedulerPF(cfg, "Direction", "DL", ...
    "HARQ", retxHARQ);
pmiOnlyGrants = pmiOnlyScheduler.schedule(0, pmiOnlyUE, ...
    struct("PRBSet", 0:23, "SymbolAllocation", [2 12]));
assert(numel(pmiOnlyGrants) == 2 && ...
    all(double([pmiOnlyGrants.MUMIMOGroupSize]) == 1), ...
    "Different PMI indices without measured matrices must remain SU scheduling.");

% A numeric matrix is also insufficient when its provenance is configured,
% stale, or digest-invalid. This prevents executable/frozen beam matrices
% from being recycled as measured scheduler CSI.
invalidSourceUE = ue(1:2);
invalidSourceUE(1).MUMIMOSpatialSignatureSource = "executed_frozen_phy_grant_precoding_matrix";
invalidSourceUE(2).MUMIMOSpatialSignatureAgeSlots = cfg.phy.mimo.measurementMaxAgeSlots + 1;
invalidSourceScheduler = sixgr.l2.mac.SchedulerPF(cfg, "Direction", "DL");
[invalidSourceGrants, invalidSourceInfo] = invalidSourceScheduler.schedule(0, invalidSourceUE, ...
    struct("PRBSet", 0:23, "SymbolAllocation", [2 12]));
assert(~isempty(invalidSourceGrants) && ...
    all(~logical([invalidSourceGrants.MUMIMOEnabled])) && ...
    ~any(double([invalidSourceGrants.MUMIMOGroupSize]) > 1), ...
    "Non-SRS or stale spatial matrices must not authorize shared-PRB MU execution.");
invalidDecision = invalidSourceInfo.CandidateTable;
assert(any(invalidDecision.MUMIMOAdmissionEvaluated) && ...
    ~any(invalidDecision.MUMIMOAdmissionCompatible) && ...
    all(strlength(string(invalidDecision.MUMIMOAdmissionEvidenceSource( ...
        invalidDecision.MUMIMOAdmissionEvaluated))) > 0), ...
    "Rejected MU admission must retain the exact causal-provenance or age failure instead of appearing unevaluated.");

% Once causal SRS becomes available, two pending rank-2 retransmissions
% with the same allocation shape may share one opportunity. The TB, NDI,
% RV lineage, rank, and TBS stay immutable while a fresh measured spatial
% filter is frozen for the retransmission opportunity.
for grantIndex = 1:2
    original = pmiOnlyGrants(grantIndex);
    harqId = double(original.HARQ.HarqID);
    original.HARQTBContext = struct( ...
        "OriginalNumLayers", double(original.NumLayers), ...
        "TBSBits", double(original.TBSBits), ...
        "HARQProcessId", harqId, ...
        "NDI", logical(original.HARQ.NDI), ...
        "NDIEpoch", double(sixgr.util.structGet(original.HARQ, "NDIEpoch", 1)));
    payload = zeros(round(double(original.TBSBits)), 1, "uint8");
    pmiOnlyScheduler.HARQ.onTx(double(original.RNTI), harqId, ...
        payload, original, 0);
    pmiOnlyScheduler.HARQ.onFeedback(double(original.RNTI), harqId, ...
        "NACK", "SourceSlot", 0, "FeedbackSlot", 4);
end
retxUE = localUEs([0 1 2 3], [10 10 10 10]);
retxUE(1).MUMIMOSpatialSignature = F(:, 1:2);
retxUE(2).MUMIMOSpatialSignature = F(:, 3:4);
retxUE = localBindMeasuredSpatialSignatures(retxUE, "DL", 5);
retxGrants = pmiOnlyScheduler.schedule(5, retxUE, ...
    struct("PRBSet", 0:23, "SymbolAllocation", [2 12]));
assert(numel(retxGrants) == 2 && ...
    all(string({retxGrants.GrantReason}) == "harq_retx_mu_mimo") && ...
    all(logical([retxGrants.IsRetransmission])) && ...
    all(double([retxGrants.MUMIMOGroupSize]) == 2) && ...
    isequal(double(retxGrants(1).PRBSet(:)), double(retxGrants(2).PRBSet(:))), ...
    "Compatible pending HARQ TBs must execute as one measured shared-PRB MU retransmission group.");
for grantIndex = 1:2
    original = pmiOnlyGrants(grantIndex);
    replay = retxGrants([retxGrants.RNTI] == original.RNTI);
    assert(numel(replay) == 1 && replay.TBSBits == original.TBSBits && ...
        replay.NumLayers == original.NumLayers && replay.HARQ.NDI == original.HARQ.NDI && ...
        replay.HARQ.RV ~= original.HARQ.RV && ...
        replay.PHYGrant.HARQProcessKey.IsRetransmission, ...
        "MU retransmission grouping must preserve the original TB spatial/rate contract and advance only HARQ RV.");
end

% If only one member of an earlier MU group is pending, replay its frozen
% beam but clear all current shared-resource labels. Historical group
% identity is retained only in explicit Prior* fields.
singleRetxHARQ = sixgr.l2.mac.HARQEntity(cfg, "Direction", "DL", ...
    "NumProcesses", 4, "MaxRetx", 3);
singleRetxScheduler = sixgr.l2.mac.SchedulerPF(staleSingleUserCfg, "Direction", "DL", ...
    "HARQ", singleRetxHARQ);
[singleOriginal, ~] = singleRetxScheduler.schedule(0, ue([1 3]), ...
    struct("PRBSet", 0:23, "SymbolAllocation", [2 12]));
assert(numel(singleOriginal) == 2 && all([singleOriginal.MUMIMOEnabled]));
original = singleOriginal(1);
harqId = double(original.HARQ.HarqID);
original.HARQTBContext = struct( ...
    "OriginalNumLayers", double(original.NumLayers), ...
    "TBSBits", double(original.TBSBits), ...
    "HARQProcessId", harqId, "NDI", logical(original.HARQ.NDI), ...
    "NDIEpoch", double(sixgr.util.structGet(original.HARQ, "NDIEpoch", 1)));
singleRetxScheduler.HARQ.onTx(double(original.RNTI), harqId, ...
    zeros(round(double(original.TBSBits)), 1, "uint8"), original, 0);
singleRetxScheduler.HARQ.onFeedback(double(original.RNTI), harqId, ...
    "NACK", "SourceSlot", 0, "FeedbackSlot", 4);
singleRetxUE = ue([1 3]);
singleRetxUE(2).DLBufferBytes = 0;
singleReplay = singleRetxScheduler.schedule(5, singleRetxUE, ...
    struct("PRBSet", 0:23, "SymbolAllocation", [2 12]));
singleReplay = singleReplay([singleReplay.RNTI] == original.RNTI);
assert(numel(singleReplay) == 1 && ~singleReplay.MUMIMOEnabled && ...
    singleReplay.MUMIMOGroupSize == 1 && isnan(singleReplay.MUMIMOGroupId) && ...
    string(singleReplay.MUMIMOPairingStatus) == ...
        "retransmission_without_current_shared_mu_peer" && ...
    string(singleReplay.MUMIMOPairingEvidenceSource) == ...
        "no_current_shared_prb_mu_peer" && ...
    singleReplay.PriorMUMIMOGroupSize == 2 && ...
    isfinite(singleReplay.PriorMUMIMOGroupId) && ...
    string(singleReplay.MUMIMOSpatialDesignEvidenceSource) == ...
        "causal_measured_srs_complete_peer_subspace_reciprocity_phase_only_hybrid_and_frozen_baseband", ...
    "An unpaired HARQ replay must not retain stale current MU execution labels.");
assert(isequal(double(singleReplay.PHYGrant.PrecodingState.HybridElementToPortMatrix), F) && ...
    string(singleReplay.PHYGrant.PrecodingState.HybridRFDesignPolicy) == ...
        "fixed_configured_matrix", ...
    ["An unpaired replay of a measured-MU HARQ TB must retain the exact " ...
     "YAML-owned role-level RF architecture even when the scheduler config " ...
     "still carries a stale signal-level beam selection."]);

% The prior immutable PHYGrant, not MU labels, is the authority for an
% orthogonal HARQ replay. Strip every measured-MU provenance field from an
% otherwise valid first transmission and retain only its frozen spatial
% contract. This reproduces a single-user replay after the runtime has
% replaced the scheduler config's signal-level beam mirror.
priorOnlyHARQ = sixgr.l2.mac.HARQEntity(staleSingleUserCfg, ...
    "Direction", "DL", "NumProcesses", 4, "MaxRetx", 3);
priorOnlyScheduler = sixgr.l2.mac.SchedulerPF(staleSingleUserCfg, ...
    "Direction", "DL", "HARQ", priorOnlyHARQ);
priorOnlyOriginal = original;
priorOnlyOriginal.MUMIMOEnabled = false;
priorOnlyOriginal.MUMIMOGroupSize = 1;
priorOnlyOriginal.MUMIMOGroupId = NaN;
priorOnlyOriginal.MUMIMOSpatialDesignContractVersion = "";
priorOnlyOriginal.MUMIMOSpatialDesignEvidenceSource = "";
priorOnlyOriginal.MUMIMOPairingEvidenceSource = "";
priorOnlyOriginal.HARQTBContext = struct( ...
    "OriginalNumLayers", double(priorOnlyOriginal.NumLayers), ...
    "TBSBits", double(priorOnlyOriginal.TBSBits), ...
    "HARQProcessId", double(priorOnlyOriginal.HARQ.HarqID), ...
    "NDI", logical(priorOnlyOriginal.HARQ.NDI), ...
    "NDIEpoch", double(sixgr.util.structGet( ...
        priorOnlyOriginal.HARQ, "NDIEpoch", 1)));
priorOnlyHARQ.onTx(double(priorOnlyOriginal.RNTI), ...
    double(priorOnlyOriginal.HARQ.HarqID), ...
    zeros(round(double(priorOnlyOriginal.TBSBits)), 1, "uint8"), ...
    priorOnlyOriginal, 0);
priorOnlyHARQ.onFeedback(double(priorOnlyOriginal.RNTI), ...
    double(priorOnlyOriginal.HARQ.HarqID), "NACK", ...
    "SourceSlot", 0, "FeedbackSlot", 4);
priorOnlyUE = ue([1 3]);
priorOnlyUE(2).DLBufferBytes = 0;
priorOnlyReplay = priorOnlyScheduler.schedule(5, priorOnlyUE, ...
    struct("PRBSet", 0:23, "SymbolAllocation", [2 12]));
priorOnlyReplay = priorOnlyReplay( ...
    [priorOnlyReplay.RNTI] == priorOnlyOriginal.RNTI);
assert(numel(priorOnlyReplay) == 1 && ...
    logical(priorOnlyReplay.IsRetransmission) && ...
    isequal(double(priorOnlyReplay.PHYGrant.PrecodingState.HybridElementToPortMatrix), ...
        double(priorOnlyOriginal.PHYGrant.PrecodingState.HybridElementToPortMatrix)) && ...
    string(priorOnlyReplay.PHYGrant.PrecodingState.SelectedMatrixSHA256) == ...
        string(priorOnlyOriginal.PHYGrant.PrecodingState.SelectedMatrixSHA256), ...
    ["A single-user HARQ scheduler replay must project and preserve the " ...
     "previous immutable PHYGrant architecture and physical precoder even " ...
     "when no MU provenance label remains."]);

ok = true;
end

function ue = localUEs(pmi, cqi)
n = numel(pmi);
ue = repmat(struct( ...
    "RNTI", 0, ...
    "UEIndex", 0, ...
    "ServingCell", 1, ...
    "DLBufferBytes", 20000, ...
    "CQI", 0, ...
    "RI", 2, ...
    "PMI", 0, ...
    "CRI", 0, ...
    "MeasuredSINR_dB", 15, ...
    "FeedbackValid", true, ...
    "CausalFeedbackUsable", true, ...
    "MUMIMOSpatialSignature", [], ...
    "MUMIMOSpatialSignatureSHA256", "", ...
    "MUMIMOSpatialSignatureSource", "", ...
    "MUMIMOSpatialSignatureSourceSlot", NaN, ...
    "MUMIMOSpatialSignatureAgeSlots", NaN, ...
    "MUMIMOSpatialSignatureConsumerRuntimeSlot", NaN, ...
    "MUMIMOSpatialSignatureMeasurementDirection", "", ...
    "MUMIMOSpatialSignatureReciprocityMode", "", ...
    "MUMIMOSpatialSignatureValid", false, ...
    "HeadOfLineDelay_ms", 1), n, 1);
for index = 1:n
    ue(index).RNTI = index;
    ue(index).UEIndex = index;
    ue(index).CQI = cqi(index);
    ue(index).PMI = pmi(index);
end
end

function ue = localBindMeasuredSpatialSignatures(ue, direction, sourceSlot)
direction = upper(string(direction));
for index = 1:numel(ue)
    w = ue(index).MUMIMOSpatialSignature;
    if isempty(w)
        continue;
    end
    ue(index).MUMIMOSpatialSignatureSHA256 = char( ...
        sixgr.phy.mimo.MatrixContract.digest(w));
    ue(index).MUMIMOSpatialSignatureSource = ...
        "measured_srs_receiver_channel_estimate_pilot_re_frequency_selective_complete_detectable_subspace";
    ue(index).MUMIMOSpatialSignatureSourceSlot = double(sourceSlot) + 1;
    ue(index).MUMIMOSpatialSignatureAgeSlots = 0;
    ue(index).MUMIMOSpatialSignatureConsumerRuntimeSlot = double(sourceSlot) + 1;
    ue(index).MUMIMOSpatialSignatureMeasurementDirection = "UL";
    if direction == "DL"
        ue(index).MUMIMOSpatialSignatureReciprocityMode = "tdd_reciprocity";
    else
        ue(index).MUMIMOSpatialSignatureReciprocityMode = "direct_ul_srs";
    end
    ue(index).MUMIMOSpatialSignatureValid = true;
end
end

function localRemoveTree(folder)
folder = char(string(folder));
if isfolder(folder)
    rmdir(folder, "s");
end
end
