function tests = testInitialAccessImpactAnalysis
%TESTINITIALACCESSIMPACTANALYSIS Contract and dependency execution guards.
tests = functiontests(localfunctions);
end

function testCompleteMatrixAndPairing(testCase)
root = localVectorRoot();
matrix = localRead(fullfile(root, ...
    "initial_access_impact_experiment_matrix.csv"));
families = localRead(fullfile(root, ...
    "initial_access_impact_analysis_families.csv"));
rules = localRead(fullfile(root, ...
    "initial_access_impact_acceptance_rules.csv"));
verifyEqual(testCase, height(matrix), 720);
verifyEqual(testCase, numel(unique(matrix.ExperimentID)), 720);
verifyEqual(testCase, height(families), 60);
verifyEqual(testCase, numel(unique(matrix.FamilyID)), 60);
verifyEqual(testCase, height(rules), 90);
verifyEqual(testCase, numel(unique(matrix.PairID)), 360);
for pairID = unique(matrix.PairID).'
    selected = matrix(matrix.PairID == pairID, :);
    verifyEqual(testCase, height(selected), 2);
    verifyEqual(testCase, sort(selected.Variant), ...
        ["baseline";"treatment"]);
    for name = [ ...
            "Seed","TrialSetID","PayloadSetID", ...
            "ChannelRealizationID","NoiseRealizationID", ...
            "InitialStateID","Factor"]
        verifyEqual(testCase, ...
            numel(unique(selected.(char(name)))), 1);
    end
end
end

function testBeamDependencyUsesMeasuredState(testCase)
beam = sixgr.phy.ia.InitialAccessBeamState.resolve( ...
    "RSRPdBm", [-70 -74 -78 -82], ...
    "Blocked", [true false false false], ...
    "RequestedBeamIndex0", 0, ...
    "SSBPeriodicityMs", 20);
verifyEqual(testCase, beam.SelectedBeamIndex0, 1);
verifyTrue(testCase, beam.RequestedBeamBlocked);
verifyTrue(testCase, beam.BeamMismatch);
verifyEqual(testCase, beam.ReselectionLatencyMs, 20);
verifyFalse(testCase, beam.ProxyUsed);
verifyFalse(testCase, beam.FallbackUsed);
end

function testSIB1SchedulerUsesDeclaredPeriodicity(testCase)
schedule = sixgr.phy.ia.SIB1Schedule.resolve( ...
    "PeriodicityMs", 40, ...
    "WindowLengthMs", 20, ...
    "ObservationStartMs", 7, ...
    "Repetitions", 4);
verifyEqual(testCase, schedule.Occasions.WindowStartMs, ...
    [40;80;120;160]);
verifyEqual(testCase, schedule.NextMonitoringLatencyMs, 33);
verifyFalse(testCase, schedule.ProxyUsed);
verifyFalse(testCase, schedule.FallbackUsed);
end

function testExtensionGatesAreTypedAndFallbackFree(testCase)
calls = { ...
    @()sixgr.phy.ia.InitialAccessCapabilityRegistry.resolve( ...
        "TwoStepRA", true), ...
    @()sixgr.phy.ia.InitialAccessCapabilityRegistry.resolve( ...
        "CFRA", true), ...
    @()sixgr.phy.ia.InitialAccessCapabilityRegistry.resolve( ...
        "BFR", true), ...
    @()sixgr.phy.ia.InitialAccessCapabilityRegistry.resolve( ...
        "SUL", true), ...
    @()sixgr.phy.ia.InitialAccessCapabilityRegistry.resolve( ...
        "NTN", true), ...
    @()sixgr.phy.ia.InitialAccessCapabilityRegistry.resolve( ...
        "RedCap", true)};
ids = [ ...
    "sixgr:phy:ia:UnsupportedTwoStepRA"
    "sixgr:phy:ia:UnsupportedCFRA"
    "sixgr:phy:ia:UnsupportedBFR"
    "sixgr:phy:ia:UnsupportedSUL"
    "sixgr:phy:ia:UnsupportedNTNAccess"
    "sixgr:phy:ia:UnsupportedRedCapAccess"];
for index = 1:numel(calls)
    verifyError(testCase, calls{index}, ids(index));
end
supported = sixgr.phy.ia.InitialAccessCapabilityRegistry.resolve();
verifyEqual(testCase, supported.FallbackCount, 0);
verifyFalse(testCase, supported.Profile.ProxyAllowed);
end

function root = localVectorRoot()
root = fullfile(fileparts(mfilename("fullpath")), ...
    "vectors", "initial_access");
end

function tableOut = localRead(path)
options = detectImportOptions(path, ...
    "TextType", "string", "VariableNamingRule", "preserve");
options = setvartype(options, options.VariableNames, "string");
options.DataLines = [2 Inf];
tableOut = readtable(path, options);
end
