function ok = testCoupledTruthRuntimeSlotDurationBinding()
%TESTCOUPLEDTRUTHRUNTIMESLOTDURATIONBINDING Bind fading state to canonical slot time.

setup6GRSimToolkit("Verbose",false);
tmp = tempname;
mkdir(tmp);
cleanup = onCleanup(@() rmdir(tmp,"s")); %#ok<NASGU>

scenarioPath = fullfile(pwd,"simulator","configs","scenarios", ...
    "webgui_sinr_sweep_64x4_mu_mimo_full.yaml");
scenarioCfg = sixgr.lls6g.config.loadScenarioConfig(scenarioPath);
cfg = sixgr.lls6g.buildInternalConfig(scenarioCfg,fullfile(tmp,"run"));
cfg.scenario.nUE = 1;
cfg.scenario.ue.nUE = 1;

multiUser = struct("Enabled",true,"NumUsers",1,"RNTIStart",8101, ...
    "ExecutionModel","slot_coupled_truth");
state = sixgr.truth.CoupledTruthRuntime.initialize( ...
    cfg,fullfile(tmp,"runtime"),multiUser,struct(),5);
state.CurrentSlot = 5;
state.CurrentFrame = 1;
state.CurrentServingIdx(1) = 1;

grant = struct( ...
    "Direction","DL", ...
    "UEIndex",1, ...
    "RNTI",8101, ...
    "ServingCell",1, ...
    "Frame",1, ...
    "Slot",5, ...
    "PRBSet",0:3, ...
    "SymbolAllocation",[2 10], ...
    "Modulation","QPSK", ...
    "TargetCodeRate",0.1884765625, ...
    "NumLayers",2, ...
    "Layers",2, ...
    "TransportBlockSize",256, ...
    "TBSBits",256, ...
    "TBSBytes",32, ...
    "HARQ",struct("HarqID",0,"HARQProcess",0,"NDI",true,"RV",0));

[~,context] = sixgr.truth.CoupledTruthRuntime.buildTrialContextFromGrant( ...
    state,cfg,1,"DL",grant);
expectedTime_s = (double(state.CurrentSlot)-1)*double(state.SlotDuration_s);
assert(abs(double(context.AbsoluteSampleTime_s)-expectedTime_s) <= eps(expectedTime_s), ...
    "Runtime fading state must use the initialized canonical slot duration.");
assert(abs(double(context.ChannelState.TargetSlotStartTime_s)-expectedTime_s) <= eps(expectedTime_s), ...
    "Channel-state target time must match the canonical slot start time.");
assert(string(context.ChannelState.ContractVersion) ~= "", ...
    "The regression must exercise a real runtime fading-channel state.");

repeatedIdentityGrant = grant;
repeatedIdentityGrant.TransportBlockId = ["dl_tb_same", "dl_tb_same"];
[~, repeatedContext] = sixgr.truth.CoupledTruthRuntime.buildTrialContextFromGrant( ...
    state,cfg,1,"DL",repeatedIdentityGrant);
assert(isscalar(string(repeatedContext.GrantSnapshot.TransportBlockId)) && ...
    string(repeatedContext.GrantSnapshot.TransportBlockId) == "dl_tb_same", ...
    "Repeated identical grant identities must reduce to one immutable scalar ID.");

ambiguousIdentityGrant = grant;
ambiguousIdentityGrant.TransportBlockId = ["dl_tb_a", "dl_tb_b"];
localAssertThrows(@() sixgr.truth.CoupledTruthRuntime.buildTrialContextFromGrant( ...
    state,cfg,1,"DL",ambiguousIdentityGrant), ...
    "sixgr:truth:AmbiguousGrantTransportBlockIdentity");

ok = true;
end

function localAssertThrows(fn, expectedId)
try
    fn();
catch ME
    assert(string(ME.identifier) == string(expectedId), ...
        "Expected error %s, got %s: %s", ...
        string(expectedId), string(ME.identifier), string(ME.message));
    return;
end
error("testCoupledTruthRuntimeSlotDurationBinding:ExpectedErrorMissing", ...
    "Expected error %s was not thrown.", string(expectedId));
end
