function ok = testBrowserPublicationReceipt()
%TESTBROWSERPUBLICATIONRECEIPT Browser receipt is derived fail closed.

root = tempname();
mkdir(root);
cleanup = onCleanup(@() localRemove(root)); %#ok<NASGU>

passed = sixgr.artifact.writeBrowserPublicationReceipt(root, struct( ...
    "Ok", true, "Status", 0, "RunID", "logical_run_42", ...
    "DatabaseRunID", 42, ...
    "DatabasePersisted", true, "BrowserMaterialized", true, ...
    "MissingTableCount", 0, "MissingChartCount", 0, ...
    "GeneratedAtUTC", "2026-08-05T12:00:00Z", ...
    "Identifier", "browser_contract_materialization_ok", ...
    "Message", "strict materialization passed"));
assert(passed.Status == "PASS" && passed.DatabasePersisted && ...
    passed.BrowserMaterialized);
assert(passed.PublicationBackend == "mysql_web" && ...
    passed.SchemaVersion == "1.1.0");

stored = jsondecode(fileread(passed.Path));
assert(string(stored.RunID) == "logical_run_42" && ...
    double(stored.DatabaseRunID) == 42 && string(stored.Status) == "PASS");

filesystem = sixgr.artifact.writeBrowserPublicationReceipt(root, struct( ...
    "RunID", "filesystem-run", "PublicationBackend", "filesystem", ...
    "FilesystemPersisted", true, "DatabasePersisted", false, ...
    "BrowserMaterialized", true, "MissingTableCount", 0, ...
    "MissingChartCount", 0, "GeneratedAtUTC", "2026-08-17T00:00:00Z"));
assert(filesystem.Status == "PASS" && filesystem.FilesystemPersisted && ...
    ~filesystem.DatabasePersisted, ...
    "Canonical filesystem publication must not require or claim MySQL persistence.");

failed = sixgr.artifact.writeBrowserPublicationReceipt(root, struct( ...
    "Ok", false, "Status", 1, "RunID", "42", ...
    "DatabasePersisted", true, "BrowserMaterialized", false, ...
    "MissingTableCount", 7, "MissingChartCount", 11, ...
    "GeneratedAtUTC", "2026-08-05T12:00:00Z", ...
    "Identifier", "browser_contract_materialization_failed", ...
    "Message", "required artifacts missing"));
assert(failed.Status == "FAIL" && ...
    failed.MissingRequiredTableCount == 7 && ...
    failed.MissingRequiredChartCount == 11);

missingDB = sixgr.artifact.writeBrowserPublicationReceipt(root, struct( ...
    "Ok", false, "Status", NaN, "RunID", "", ...
    "DatabasePersisted", false, "BrowserMaterialized", false, ...
    "MissingTableCount", NaN, "MissingChartCount", NaN, ...
    "GeneratedAtUTC", "2026-08-05T12:00:00Z"));
assert(missingDB.Status == "FAIL" && ~missingDB.DatabasePersisted);
% The missing timestamp guard must preserve its own diagnostic, not throw
% MATLAB:error:badMessageArgument while formatting a string-array message.
caught=false;
try
    sixgr.artifact.writeBrowserPublicationReceipt(root,struct());
catch cause
    caught=true;
    assert(strcmp(cause.identifier,'sixgr:artifact:BrowserReceiptTimestampRequired'));
    assert(contains(cause.message,'immutable execution completion timestamp'));
end
assert(caught,'Missing receipt timestamps must remain rejected.');

ok = true;
fprintf("PASS testBrowserPublicationReceipt: publication receipt is actual and fail-closed.\n");
end

function localRemove(pathValue)
if isfolder(pathValue)
    rmdir(pathValue, "s");
end
end
