function ok = testLLSHARQReplayCurrentGrantAuthority()
%TESTLLSHARQREPLAYCURRENTGRANTAUTHORITY Preserve current-slot grant authority on HARQ replay.

setup6GRSimToolkit("Verbose", false);

tmp = tempname;
mkdir(tmp);
cleanup = onCleanup(@() rmdir(tmp, "s")); %#ok<NASGU>

scenarioPath = fullfile(pwd, "simulator", "configs", "scenarios", ...
    "lls_mimo4x4_multiuser_beamformed_awgn_validation.yaml");
scenarioCfg = sixgr.lls6g.config.loadScenarioConfig(scenarioPath);
cfg = sixgr.lls6g.buildInternalConfig(scenarioCfg, fullfile(tmp, "run"));
multiUser = struct( ...
    "Enabled", true, ...
    "NumUsers", 1, ...
    "RNTIStart", 901, ...
    "ExecutionModel", "slot_coupled_truth");
state = sixgr.truth.CoupledTruthRuntime.initialize( ...
    cfg, fullfile(tmp, "run"), multiUser, struct(), 5);
state.CurrentServingIdx(:) = 1;
state.CurrentServingMetric_dBm(:) = -80;
state.CurrentSlot = 5;
state.CurrentFrame = 1;

rnti = double(multiUser.RNTIStart);
tbsBits = 256;
storedGrant = struct( ...
    "Direction", "DL", ...
    "UEIndex", 1, ...
    "RNTI", rnti, ...
    "ServingCell", 1, ...
    "Frame", 1, ...
    "Slot", 1, ...
    "MCS", 1, ...
    "MCSIndex", 1, ...
    "Modulation", "QPSK", ...
    "TargetCodeRate", 0.1171875, ...
    "CQIProvenance", "", ...
    "NumLayers", 1, ...
    "Layers", 1, ...
    "PRBSet", 0:3, ...
    "PRBs", 4, ...
    "SymbolAllocation", [2 10], ...
    "TransportBlockSize", tbsBits, ...
    "TBSBits", tbsBits, ...
    "TBSBytes", tbsBits / 8, ...
    "ExactPHYFeasibilityChecked", false, ...
    "ExactPHYFeasible", false, ...
    "DCI", struct("AuthorityMarker", "stored_stale_dci"), ...
    "ControlDecodeOk", false, ...
    "PDCCHGrantBindingOk", false, ...
    "PDCCHGrantDCIFieldsHash", "stored_hash", ...
    "PDCCHGrantFieldsHash", "stored_hash");

txp = state.DLHarq.allocate(rnti, 1, tbsBits / 8, "NewData", true);
storedGrant.HARQ = txp.HARQ;
state.DLHarq.onTx(rnti, double(txp.HARQ.HarqID), ...
    zeros(tbsBits, 1, "uint8"), storedGrant, 1);
state.DLHarq.onFeedback(rnti, double(txp.HARQ.HarqID), "NACK", ...
    "SourceSlot", 1, "FeedbackSlot", 5);
retx = state.DLHarq.peekRetx(rnti, 5);
assert(~isempty(retx), "Regression fixture must create a pending DL retransmission.");

currentGrant = storedGrant;
currentGrant.Frame = 1;
currentGrant.Slot = 5;
currentGrant.HARQ = retx.HARQ;
currentGrant.IsRetransmission = true;
currentGrant.Valid = true;
currentGrant.ExactPHYFeasibilityChecked = true;
currentGrant.ExactPHYFeasible = true;
currentGrant.ExactPHYFeasibilitySource = ...
    "SchedulerBase.finalizeExactPHYFeasibility";
currentGrant.ExactPHYInfeasibilityReason = "";
currentGrant.ExecutableTBSMode = "faithful_exact_resource_accounting";
currentGrant.DCI = struct("AuthorityMarker", "current_slot_dci");
currentGrant.ControlDecodeOk = true;
currentGrant.PDCCHGrantBindingRequired = true;
currentGrant.PDCCHGrantBindingOk = true;
currentGrant.PDCCHGrantBindingStatus = "matched";
currentGrant.PDCCHGrantDCIId = "current_dci_id";
currentGrant.PDCCHGrantDCIFieldsHash = "current_hash";
currentGrant.PDCCHGrantFieldsHash = "current_hash";
currentGrant.GrantContextId = "DL-C1-U1-R901-F1-S5";

[~, context] = sixgr.truth.CoupledTruthRuntime.buildTrialContextFromGrant( ...
    state, cfg, 1, "DL", currentGrant);
replayGrant = context.GrantSnapshot;

assert(logical(replayGrant.ExactPHYFeasibilityChecked) && ...
    logical(replayGrant.ExactPHYFeasible), ...
    "HARQ replay must retain the current scheduler's exact-PHY feasibility authority.");
assert(string(replayGrant.DCI.AuthorityMarker) == "current_slot_dci", ...
    "HARQ replay must use the current slot's DCI, not the stored first-transmission DCI.");
assert(logical(replayGrant.ControlDecodeOk) && ...
    logical(replayGrant.PDCCHGrantBindingOk), ...
    "HARQ replay must retain the current slot's decoded-PDCCH grant binding.");
assert(string(replayGrant.PDCCHGrantDCIFieldsHash) == "current_hash" && ...
    string(replayGrant.PDCCHGrantFieldsHash) == "current_hash", ...
    "HARQ replay must retain the matching current-slot DCI/grant hashes.");
assert(double(replayGrant.TBSBits) == tbsBits && ...
    numel(context.TransportBlockBits) == tbsBits, ...
    "HARQ replay must still retain the original stored transport block.");
assert(logical(sixgr.util.structGet(replayGrant.PHYGrant, ...
    "HARQProcessKey.IsRetransmission", false)), ...
    "HARQ replay must refreeze the PHY grant with retransmission HARQ context.");

% Execution commit must reduce all exported spatial aliases from the same
% actual waveform rank.  A prior defect updated precoder metadata while the
% scheduler trace retained rank one, making rank-two UL retransmissions look
% like single-layer transmissions in the WebGUI.
traceGrant = currentGrant;
traceGrant.Direction = "UL";
traceGrant.NumLayers = 1;
traceGrant.Layers = 1;
traceGrant.RIUsed = 1;
traceGrant.Rank = 1;
state = sixgr.truth.CoupledTruthRuntime.appendGrantTraceRuntime( ...
    state, traceGrant, "UL", struct());
executedGrant = traceGrant;
executedGrant.NumLayers = 2;
executedGrant.Layers = 2;
executedGrant.RI = 2;
executedGrant.RIUsed = 2;
executedGrant.Rank = 2;
executedGrant.RankIndicator = 2;
state = sixgr.truth.CoupledTruthRuntime.commitGrantExecution( ...
    state, 1, "UL", executedGrant);
assert(height(state.ULGrantTraceTable) == 1, ...
    "Regression fixture must retain one UL grant trace row.");
assert(double(state.ULGrantTraceTable.NumLayers(1)) == 2 && ...
    double(state.ULGrantTraceTable.Layers(1)) == 2 && ...
    double(state.ULGrantTraceTable.RIUsed(1)) == 2 && ...
    double(state.ULGrantTraceTable.Rank(1)) == 2, ...
    "Execution commit must synchronize NumLayers/Layers/RIUsed/Rank to the waveform rank.");

ok = true;
end
