function ok = testLLSMobile2UEScenarioYamlWiring()
%TESTLLSMOBILE2UESCENARIOYAMLWIRING Verify the mobile 2UE study YAML is present and runtime-wired.

setup6GRSimToolkit("Verbose", false);

scenarioPath = fullfile(pwd, "simulator", "configs", "scenarios", ...
    "lls_mobile_2ue_100kmh_1sector_full_capture.yaml");
scfg = sixgr.lls6g.config.loadScenarioConfig(scenarioPath);
resolved = scfg.toStruct();

requiredSections = { ...
    'waveform', ...
    'deployment_topology', ...
    'channels', ...
    'mimo', ...
    'modulation', ...
    'coding', ...
    'reference_signals', ...
    'csi_acquisition_and_reporting', ...
    'link_adaptation', ...
    'harq', ...
    'pucch_resources', ...
    'random_access', ...
    'sib1_and_initial_access', ...
    'random_access_evidence', ...
    'scheduler', ...
    'power_control', ...
    'impairments', ...
    'decoder_output_capture', ...
    'dut_reference_validation', ...
    'channel_rf_configured_vs_applied', ...
    'air_interface', ...
    'traffic', ...
    'energy_efficiency', ...
    'analytics'};
for idx = 1:numel(requiredSections)
    assert(isfield(resolved, requiredSections{idx}), ...
        "Resolved mobile study config must contain section '%s'.", requiredSections{idx});
end

tmp = tempname;
mkdir(tmp);
c = onCleanup(@() rmdir(tmp, "s")); %#ok<NASGU>
cfg = sixgr.lls6g.buildInternalConfig(scfg, fullfile(tmp, "run"));

assert(logical(sixgr.util.structGet(cfg, "phy.waveform.windowingEnabled", false)), ...
    "waveform.windowing_enabled must wire into phy.waveform.windowingEnabled.");
assert(abs(double(sixgr.util.structGet(cfg, "phy.waveform.windowingPercent", NaN)) - 0.025) < 1e-12, ...
    "waveform.windowing_percent must wire into the OFDM windowing runtime config.");
assert(strcmpi(char(string(sixgr.util.structGet(cfg, "phy.pdsch.mcsTable", ""))), "qam256_table2"), ...
    "modulation.dl_mcs_table must wire into phy.pdsch.mcsTable.");
assert(strcmpi(char(string(sixgr.util.structGet(cfg, "phy.pusch.mcsTable", ""))), "qam256_table2"), ...
    "modulation.ul_mcs_table must wire into phy.pusch.mcsTable.");
assert(strcmpi(char(string(sixgr.util.structGet(cfg, "phy.csi.cqiTable", ""))), "table2"), ...
    "link_adaptation.cqi_table must wire into phy.csi.cqiTable.");
assert(strcmpi(char(string(sixgr.util.structGet(cfg, "phy.csi.channelStateInformationMode", ""))), "PMI+CQI+RI"), ...
    "csi_acquisition_and_reporting.channel_state_information_mode must wire into phy.csi.channelStateInformationMode.");
assert(strcmpi(char(string(sixgr.util.structGet(cfg, "phy.csi.codebookType", ""))), "type1"), ...
    "mimo.codebook_type must wire into phy.csi.codebookType.");
assert(double(sixgr.util.structGet(cfg, "phy.carrier.NSizeGrid", NaN)) == 273, ...
    "frequency.n_size_grid must wire into phy.carrier.NSizeGrid.");
assert(double(sixgr.util.structGet(cfg, "phy.numerology.activeGridNumRBs", NaN)) == 273, ...
    "frequency.n_size_grid must wire into the active runtime RB grid.");
assert(isequal(double(sixgr.util.structGet(cfg, "phy.harq.rvSequence", zeros(0, 1))).', [0 2 3 1]), ...
    "harq.rv_sequence must wire into phy.harq.rvSequence.");
assert(strcmpi(char(string(sixgr.util.structGet(cfg, "system.scheduler.type", ""))), "PF"), ...
    "scheduler.type must resolve into system.scheduler.type.");
assert(strcmpi(char(string(sixgr.util.structGet(cfg, "mac.scheduler.type", ""))), "PF"), ...
    "scheduler.type must resolve into mac.scheduler.type.");
assert(double(sixgr.util.structGet(cfg, "phy.pdsch.maxLayers", NaN)) == 2 && ...
    double(sixgr.util.structGet(cfg, "phy.pdsch.numLayers", NaN)) == 2, ...
    "mimo.max_dl_layers must cap the DL runtime layer configuration.");
assert(double(sixgr.util.structGet(cfg, "phy.pusch.maxLayers", NaN)) == 2 && ...
    double(sixgr.util.structGet(cfg, "phy.pusch.numLayers", NaN)) == 2, ...
    "mimo.max_ul_layers must cap the UL runtime layer configuration.");
assert(strcmpi(char(string(sixgr.util.structGet(cfg, "phy.pusch.uciMultiplexingMode", ""))), "pucch_only"), ...
    "pucch_resources.overlap_policy.uci_on_pusch_enabled=false must disable UCI-on-PUSCH multiplexing.");
assert(logical(sixgr.util.structGet(cfg, "phy.pusch.powerControl.enabled", false)), ...
    "power_control.ul_open_loop_enable must enable UL runtime power control.");
assert(abs(double(sixgr.util.structGet(cfg, "phy.pusch.powerControl.p0PUSCH_dBm", NaN)) + 80) < 1e-12, ...
    "power_control.p0_pusch_dBm must wire into phy.pusch.powerControl.p0PUSCH_dBm.");
assert(abs(double(sixgr.util.structGet(cfg, "phy.pusch.powerControl.alpha", NaN)) - 0.8) < 1e-12, ...
    "power_control.alpha_pusch must wire into phy.pusch.powerControl.alpha.");
assert(abs(double(sixgr.util.structGet(cfg, "phy.pusch.powerControl.pcmax_dBm", NaN)) - 23) < 1e-12, ...
    "power_control.pcmax_dBm must wire into phy.pusch.powerControl.pcmax_dBm.");
assert(strcmpi(char(string(sixgr.util.structGet(cfg, "prach_lls.DetectionThresholdMode", ""))), "auto"), ...
    "random_access.detection_threshold_mode must wire into the PRACH runtime config.");
assert(logical(sixgr.util.structGet(cfg, "outputs.rawIQCaptureEnabled", false)), ...
    "run_control.raw_iq_capture_enable must wire into the runtime output config.");
assert(strcmpi(char(string(sixgr.util.structGet(cfg, "phy.pucch.format", ""))), "2"), ...
    "pucch_resources must preserve the requested format-2 runtime default.");
assert(isequal(double(sixgr.util.structGet(cfg, "phy.pucch.PRBSet", NaN)), [2 3 4 5]), ...
    "pucch_resources.resources must wire the default PRB set into cfg.phy.pucch.PRBSet.");
assert(isequal(double(sixgr.util.structGet(cfg, "phy.pucch.SymbolAllocation", NaN)), [8 2]), ...
    "pucch_resources.resources must wire the default symbol allocation into cfg.phy.pucch.SymbolAllocation.");
assert(double(sixgr.util.structGet(cfg, "mac.harq.k1", NaN)) == 4, ...
    "pucch_resources.harq_ack.k1_slots must override the runtime HARQ feedback timing.");
assert(logical(sixgr.util.structGet(cfg, "phy.sib1.enable", false)), ...
    "sib1_and_initial_access must enable the strict SIB1 waveform path.");
objectives = string(sixgr.util.structGet(cfg, "validation.objectives", cell(0, 1)));
assert(any(objectives == "cell_search_mib_sib1") && ...
    any(objectives == "random_access_four_step") && ...
    any(objectives == "channel_rf_strict_validation"), ...
    "The added strict-audit sections must wire their runtime truth objectives into cfg.validation.objectives.");
assert(logical(sixgr.util.structGet(cfg, "phy.impairments.phaseNoiseEnabled", false)), ...
    "impairments.phase_noise_enabled must wire into phy.impairments.phaseNoiseEnabled.");
assert(logical(sixgr.util.structGet(cfg, "perf.exportTimeProfile", false)), ...
    "analytics.export_time_profile must wire into perf.exportTimeProfile.");
assert(abs(double(scfg.get("energy_efficiency.ai_compute_energy_per_flop_score")) - 1e-6) < 1e-12, ...
    "energy_efficiency.ai_compute_energy_per_flop_score must remain available on the resolved ScenarioConfig for runSingle.");
assert(strcmpi(char(string(resolved.channels.profile)), "CDL-C") && logical(resolved.channels.los_enabled), ...
    "The mobile study channel profile must resolve to CDL-C with LOS enabled.");
assert(strcmpi(char(string(resolved.mimo.reciprocity_mode)), "TDD"), ...
    "The mobile study reciprocity mode must resolve to TDD.");
assert(double(resolved.reference_signals.pusch_dmrs_ports) == 2 && ...
    double(resolved.reference_signals.srs_ports) == 2, ...
    "The mobile study UL reference-signal ports must stay aligned with the 2-layer UL configuration.");

ok = true;
end
