function ok = testCanonicalSlotTiming()
%TESTCANONICALSLOTTIMING Canonical slot timing and packet latency guards.

setup6GRSimToolkit("Verbose", false);

slotDur = sixgr.time.slotDurationSec(30);
assert(abs(slotDur - 0.5e-3) < 1e-15, "mu=1 slot duration must be 0.5 ms.");
assert(abs(sixgr.time.slotStartTimeSec(1, slotDur) - 0) < 1e-15, "Slot 1 must start at 0 ms.");
assert(abs(sixgr.time.slotStartTimeSec(2, slotDur) - 0.5e-3) < 1e-15, "Slot 2 must start at 0.5 ms.");
assert(abs(sixgr.time.slotStartTimeSec(21, slotDur) - 10e-3) < 1e-15, "Slot 21 must start at 10 ms.");

[frame1, slotInFrame1] = sixgr.time.canonicalSlotToFrameSlot([1; 2; 21], 20);
assert(isequal(frame1(:), [1; 1; 2]) && isequal(slotInFrame1(:), [1; 2; 1]), ...
    "Canonical slots must map to NR frame/slot without treating the slot as a frame.");
localAssertError(@() sixgr.time.canonicalSlotToFrameSlot(1), ...
    "sixgr:time:MissingSlotsPerFrame");

raw = localRawWithApplicationPacket(21, 22, slotDur, 0.5);
out = sixgr.kpi.reconstructLLSKPISummaryFromRaw(raw, ...
    "StrictMode", true, ...
    "MeasurementWindowSec", 0.02, ...
    "EffectiveBandwidthHz", 1e6);
latRow = out.ReconstructionSummary(strcmp(string(out.ReconstructionSummary.KPIName), "UL_Latency_ms"), :);
assert(height(latRow) == 1 && logical(latRow.StrictOk), "Forward canonical packet timing must pass strict KPI reconstruction.");
assert(abs(double(latRow.ReconstructionValue) - 0.5) < 1e-12, ...
    "Enqueue slot 21 and delivery slot 22 must produce 0.5 ms latency at mu=1; observed %.17g ms.", ...
    double(latRow.ReconstructionValue));

rawMissingProvenance = raw;
rawMissingProvenance.ApplicationPackets = removevars( ...
    rawMissingProvenance.ApplicationPackets, "SameWaveformProtocolComplete");
outMissingProvenance = sixgr.kpi.reconstructLLSKPISummaryFromRaw(rawMissingProvenance, ...
    "StrictMode", true, ...
    "MeasurementWindowSec", 0.02, ...
    "EffectiveBandwidthHz", 1e6);
assert(~logical(outMissingProvenance.StrictOk), ...
    "Strict KPI reconstruction must fail when application delivery lacks waveform-protocol provenance.");
assert(any(contains(string(outMissingProvenance.ReconstructionSummary.FailureReason), ...
    "same_waveform_protocol_completion_evidence_missing")), ...
    "The strict failure must identify missing waveform-protocol completion evidence.");

rawBackwards = localRawWithApplicationPacket(21, 20, slotDur, -0.5);
outBackwards = sixgr.kpi.reconstructLLSKPISummaryFromRaw(rawBackwards, ...
    "StrictMode", true, ...
    "MeasurementWindowSec", 0.02, ...
    "EffectiveBandwidthHz", 1e6);
assert(~logical(outBackwards.StrictOk), "Delivered packets with delivery before enqueue must fail strict reconstruction.");
assert(any(contains(string(outBackwards.ReconstructionSummary.FailureReason), "negative_successful_packet_latency") | ...
    contains(string(outBackwards.ReconstructionSummary.FailureReason), "delivery_slot_before_enqueue_slot")), ...
    "Strict failure must explain the impossible packet timing.");

rawMismatch = localRawWithApplicationPacket(21, 22, slotDur, 1.5);
outMismatch = sixgr.kpi.reconstructLLSKPISummaryFromRaw(rawMismatch, ...
    "StrictMode", true, ...
    "MeasurementWindowSec", 0.02, ...
    "EffectiveBandwidthHz", 1e6);
assert(~logical(outMismatch.StrictOk), "Precomputed latency that disagrees with timestamps must fail strict reconstruction.");
assert(any(contains(string(outMismatch.ReconstructionSummary.FailureReason), "packet_latency_precomputed_mismatch")), ...
    "Strict failure must expose precomputed latency drift.");

ok = true;
end

function localAssertError(fcn, expectedIdentifier)
try
    fcn();
catch cause
    assert(string(cause.identifier) == string(expectedIdentifier), ...
        "Expected %s, received %s.", expectedIdentifier, cause.identifier);
    return;
end
error("sixgr:test:ExpectedErrorNotThrown", ...
    "Expected error %s was not thrown.", expectedIdentifier);
end

function raw = localRawWithApplicationPacket(enqueueSlot, deliverySlot, slotDur, latencyMs)
enqueueTime = sixgr.time.slotStartTimeSec(enqueueSlot, slotDur);
deliveryTime = sixgr.time.slotStartTimeSec(deliverySlot, slotDur);
raw = struct();
raw.UL = localDirectionRows("UL");
raw.DL = localDirectionRows("DL");
raw.PacketSDU = table( ...
    "UL", 1, "ul_pkt_1", "ul_sdu_1", "ul_tb_1", 1000, true, true, ...
    enqueueSlot, deliverySlot, enqueueTime, deliveryTime, ...
    'VariableNames', {'Direction','UEIndex','PacketId','MACSDUId','TransportBlockId', ...
    'PayloadBits','DeliverySuccess','FirstSuccessDelivery','ScheduleSlot','FirstSuccessSlot', ...
    'ScheduleTime_s','DeliveryTime_s'});
raw.ApplicationPackets = table( ...
    "UL", 1, "ul_pkt_1", "ul_pkt_1", 1000, 1000, true, true, ...
    enqueueSlot, deliverySlot, enqueueTime, deliveryTime, latencyMs, ...
    'VariableNames', {'Direction','UEIndex','PacketId','ApplicationPacketId','OfferedBits', ...
    'DeliveredBits','DeliverySuccess','SameWaveformProtocolComplete','EnqueueCanonicalSlot','DeliveryCanonicalSlot', ...
    'EnqueueTime_s','DeliveryTime_s','Latency_ms'});
end

function T = localDirectionRows(direction)
direction = string(direction);
T = table( ...
    direction, 0, true, 0, 1000, 1000, 1000, 1, 1, 0, 1, 0, true, false, 1, 1, 0.001, ...
    'VariableNames', {'Direction','Goodput_Mbps','CRCPass','BitErrors','BitsCompared', ...
    'TBSize_bits','GoodBits','Frame','Slot','HARQProcessId','NDI','RV', ...
    'NewDataFlag','RetransmissionFlag','AirInterfaceObservation_ms','TrialId','SlotDuration_s'});
end
