function ok = testCoupledTruthIndependentSweepPointReset()
%TESTCOUPLEDTRUTHINDEPENDENTSWEEPPOINTRESET Prevent cross-SNR causal state leakage.

setup6GRSimToolkit("Verbose", false);
tmp = tempname;
mkdir(tmp);
c = onCleanup(@() rmdir(tmp, "s")); %#ok<NASGU>

scenarioPath = fullfile(pwd, "simulator", "configs", "scenarios", ...
    "webgui_sinr_sweep_64x4_mu_mimo_full.yaml");
scfg = sixgr.lls6g.config.loadScenarioConfig(scenarioPath);
cfg = sixgr.lls6g.buildInternalConfig(scfg, fullfile(tmp, "run"));
assert(strcmpi(string(cfg.run.snrSweepStatePolicy), ...
    "independent_link_state_per_point"), ...
    "The fixed-SNR production scenario must wire its point-state policy from YAML.");
assert(strcmpi(string(cfg.run.snrSweepInitialAccessStatePolicy), ...
    "independent_per_point"), ...
    "The initial-access qualification policy must be wired from YAML.");

multiUser = struct("Enabled", true, "NumUsers", 2, "RNTIStart", 401, ...
    "SeedStride", 17, "ExecutionModel", "slot_coupled_truth");
state = sixgr.truth.CoupledTruthRuntime.initialize( ...
    cfg, fullfile(tmp, "runtime"), multiUser, struct(), 60);
state.AccessState(:) = "succeeded";
state.CellAcquisitionState(:) = "acquired";
state.DLCombinedLLR{1, 1} = ones(16, 1);
state.ULCombinedLLR{1, 1} = ones(8, 1);
assert(isempty(state.SharedGNBULHARQReceivers));
state.SharedGNBULHARQReceivers={struct('Scope',"declared_pre_boundary_receiver_state",'SoftBuffer',ones(8,1))};
state.SharedGNBULHARQCommands={struct('Scope',"declared_pre_boundary_command")};
state.LatestDLFeedback(1).Valid = true;
state.LatestULFeedback(1).Valid = true;
state.DLQueueBits(:) = 1000;
state.ULQueueBits(:) = 2000;
state.HARQTimelineTable = table(1, "VariableNames", {'EvidenceRow'});

% Declared boundary fixture: a DL attempt in point 1 has UL PUCCH feedback
% scheduled in point 2. This is cancellation bookkeeping, not PHY evidence.
% An UL data CRC is gNB-local and must not be represented as PUCCH feedback.
crossBoundaryFeedback = struct( ...
    "Direction", "DL", "FeedbackForDirection", "DL", "UEIndex", 1, "RNTI", 401, ...
    "HarqID", 0, "SourceSlot", 20, "DueSlot", 24, "Ack", true, ...
    "CurrentDecodeOK", true, "CombinedDecodeOK", true, ...
    "ServingCell", 1, "BaseStationID", 1, "TBSBits", 1024, ...
    "UCIBitCount", 1, "RequestedFormat", 0, "ResolvedFormat", 0, ...
    "PUCCHResourceId", "boundary_test_pucch", ...
    "PUCCHPRBStart", 0, "PUCCHPRBCount", 1, ...
    "PUCCHSymbolStart", 12, "PUCCHNumSymbols", 2, ...
    "UCIType", "harq_ack", ...
    "ControlResourceSource", "test_runtime_feedback_resource", ...
    "ControlResourceValidity", true, "FormatAdaptationReason", "", ...
    "PUCCHGrantId", "boundary-feedback-1", "Processed", false);
state = sixgr.truth.CoupledTruthRuntime.schedulePUCCHGrantRuntime( ...
    state, crossBoundaryFeedback);
state.PendingFeedbackTable = struct2table(crossBoundaryFeedback, "AsArray", true);
assert(isequal(sixgr.truth.CoupledTruthRuntime.pucchFeedbackDueUEsRuntime( ...
    state, 24), 1), ...
    "The pre-reset fixture must expose the cross-boundary feedback as due.");

measRow = table(12, 10, 2, "VariableNames", ...
    {'WidebandCQI','SINR_dB','RIEstimate'});
state = sixgr.truth.CoupledTruthRuntime.publishReferenceSignalMeasurementRuntime( ...
    state, "CSI-RS", "UE", 1, measRow, "ProducerSlot", 5, ...
    "AvailableSlot", 6, "Valid", true, "Direction", "DL");
before = sixgr.truth.CoupledTruthRuntime.consumeReferenceSignalMeasurementRuntime( ...
    state, "CSI-RS", "UE", 1, 20, 20);
assert(logical(before.Usable), "The pre-boundary CSI fixture must be causally usable.");
state.CurrentSlot = 20;
csiTrial = table(20, 12, 10, 2, 0, true, ...
    "receiver_post_equalization_sinr", ...
    "measured_post_equalization_scheduling_input", "OK", ...
    'VariableNames', {'Slot','WidebandCQI','SINR_dB','RIEstimate', ...
    'PMI','CRCPass','SINRSource','SINRValueRole','SINRValueStatus'});
csiTrial.CRI=0; % Explicit declared configured resource; not a PHY measurement.
state = sixgr.truth.CoupledTruthRuntime.enqueueCSIReportRuntime( ...
    state, 1, "DL", csiTrial, cfg, table());
assert(height(state.PendingCSITable) == 1 && ...
    ~logical(state.PendingCSITable.Processed(1)), ...
    "The pre-reset fixture must include one delayed causal CSI report.");

state = sixgr.truth.CoupledTruthRuntime.resetIndependentSweepPointLinkState( ...
    state, cfg, 2, 21);

assert(all(string(state.AccessState) == string(state.ControlGating.PRACHInitialState)) && ...
    all(string(state.CellAcquisitionState) == string(state.ControlGating.PBCHInitialState)) && ...
    ~any(state.ControlEligibility) && ~any(state.SchedulingEligibility), ...
    "YAML-selected independent access must reset every UE to its pre-access state.");
assert(double(state.SweepPointInitialAccessResetCount) == 1, ...
    "The runtime must record the initial-access point-boundary reset.");
assert(height(state.HARQTimelineTable) == 1 && ...
    height(state.ReferenceSignalMeasurementTable) >= 1 && ...
    any(double(state.ReferenceSignalMeasurementTable.ProducerSlot) == 5), ...
    "Independent link-state reset must preserve accumulated truth evidence.");
assert(all(cellfun(@isempty, state.DLCombinedLLR(:))) && ...
    all(cellfun(@isempty, state.ULCombinedLLR(:))) && isempty(state.SharedGNBULHARQReceivers) && ...
    isempty(state.SharedGNBULHARQCommands), ...
    "HARQ combining must not cross an SNR-point boundary.");
assert(height(state.PendingFeedbackTable) == 1 && ...
    logical(state.PendingFeedbackTable.RightCensored(1)) && ...
    string(state.PendingFeedbackTable.CensorScope(1)) == "independent_sweep_point", ...
    "Cross-boundary HARQ feedback must remain as explicit right-censored evidence.");
assert(height(state.PendingCSITable) == 1 && ...
    logical(state.PendingCSITable.RightCensored(1)) && ...
    ~logical(state.PendingCSITable.Processed(1)) && ...
    contains(string(state.PendingCSITable.DeliveryStatus(1)), "right_censored"), ...
    "Cross-boundary CSI must remain as explicit right-censored evidence.");
boundaryGrant = state.PUCCHGrantTraceTable( ...
    string(state.PUCCHGrantTraceTable.PUCCHGrantId) == "boundary-feedback-1", :);
assert(height(boundaryGrant) == 1 && ...
    logical(boundaryGrant.CanceledAtSweepBoundary(1)) && ...
    ~logical(boundaryGrant.GrantExecutedFlag(1)) && ...
    strcmpi(string(boundaryGrant.Status(1)), "CANCELED") && ...
    strcmpi(string(boundaryGrant.PUCCHGrantState(1)), ...
        "canceled_independent_sweep_boundary"), ...
    "Cross-boundary PUCCH evidence must be finalized as canceled without claiming waveform execution.");
assert(isempty(sixgr.truth.CoupledTruthRuntime.pucchFeedbackDueUEsRuntime( ...
    state, 24)), ...
    "Canceled feedback must not remain due against the fresh HARQ entity.");
state = sixgr.truth.CoupledTruthRuntime.startSlot( ...
    state, cfg, "DL", 2, 3, 24, 60, 0); %#ok<NASGU>
assert(~state.LatestDLFeedback(1).Valid && ~state.LatestULFeedback(1).Valid && ...
    all(state.DLQueueBits == 0) && all(state.ULQueueBits == 0), ...
    "Link adaptation feedback and traffic backlog must not cross an independent point boundary.");
after = sixgr.truth.CoupledTruthRuntime.consumeReferenceSignalMeasurementRuntime( ...
    state, "CSI-RS", "UE", 1, 21, 20);
assert(~logical(after.Usable), ...
    "A reference measurement produced before the point boundary must not drive the new point.");
assert(double(state.SweepPointIndex) == 2 && ...
    double(state.SweepPointStartSlot) == 21 && ...
    double(state.SweepPointLinkStateResetCount) == 1, ...
    "Sweep-point boundary metadata must identify the applied reset.");

ok = true;
end
