function ok = testFRCExactFadingChannelStreaming()
%TESTFRCEXACTFADINGCHANNELSTREAMING Chunking preserves full TDL sequence.

setup6GRSimToolkit("Verbose", false, "RunToolboxChecks", false);
if ~(exist("nrTDLChannel", "class") == 8 || ...
        exist("nrTDLChannel", "file") == 2)
    warning("testFRCExactFadingChannelStreaming:Missing5GToolbox", ...
        "Skipping exact TDL streaming test because nrTDLChannel is unavailable.");
    ok = true;
    return;
end

stream = RandStream("mt19937ar", "Seed", 83104);
x = complex(randn(stream, 20000, 4), randn(stream, 20000, 4));
padSamples = 257;
referenceChannel = localChannel();
streamedChannel = localChannel();
[reference, referenceEvidence] = ...
    sixgr.conformance.applyFadingChannelExact( ...
    referenceChannel, x, padSamples, 0);
[streamed, streamedEvidence] = ...
    sixgr.conformance.applyFadingChannelExact( ...
    streamedChannel, x, padSamples, 2048);

scale = max(1, max(abs(reference), [], "all"));
maxAbsDiff = max(abs(reference - streamed), [], "all");
assert(isequal(size(reference), [size(x,1)+padSamples, 4]) && ...
    maxAbsDiff <= 256 * eps(scale), ...
    ["Streaming the same seeded TDL channel must preserve the complete " ...
    "waveform within floating-point roundoff; max difference %.17g."], ...
    maxAbsDiff);
assert(referenceEvidence.Mode == "monolithic_complete_sequence" && ...
    referenceEvidence.ChannelCallCount == 1 && ...
    streamedEvidence.Mode == "streamed_complete_sequence" && ...
    streamedEvidence.ChannelCallCount > 1 && ...
    streamedEvidence.MaximumInputRows <= 2048 && ...
    streamedEvidence.InputSamplesProcessed == size(x,1)+padSamples && ...
    streamedEvidence.FullSequenceProcessed && ...
    ~streamedEvidence.ProxyUsed && ~streamedEvidence.FallbackUsed && ...
    streamedEvidence.ApproximationMode == "none", ...
    "Exact fading-channel streaming evidence is incomplete or mislabeled.");
release(referenceChannel);
release(streamedChannel);
ok = true;
end

function channel = localChannel()
channel = nrTDLChannel;
channel.DelayProfile = "TDL-A";
channel.DelaySpread = 30e-9;
channel.MaximumDopplerShift = 10;
channel.SampleRate = 61.44e6;
channel.NumTransmitAntennas = 4;
channel.NumReceiveAntennas = 4;
channel.MIMOCorrelation = "Low";
channel.TransmissionDirection = "Downlink";
channel.NormalizePathGains = true;
channel.NormalizeChannelOutputs = false;
channel.RandomStream = "mt19937ar with seed";
channel.Seed = 38104;
reset(channel);
end
