function ok = testPRACHShortFormatTimingWindow()
%TESTPRACHSHORTFORMATTIMINGWINDOW Guard B4 repeated-symbol timing selection.

setup6GRSimToolkit("Verbose", false);

cfg = localB4StrictConfig();
occ = sixgr.rach.mapPRACHToOccasion(cfg, "OccasionIndex", 1);
tx = sixgr.phy.prach.generatePRACHWaveform(cfg, "Occasion", occ, "PreambleIndex", 0);
symbolSpacing = double(tx.OFDMInfo.SymbolLengths(1));

for delaySamples = [0 4 8]
    wave = localApplyIntegerDelay(tx.Waveform, delaySamples);
    rx = localAddNoise(wave, 18, 1900 + delaySamples);
    det = sixgr.phy.prach.detectPRACHWaveform(rx, cfg, "Occasion", occ, ...
        "CandidatePreambles", 0, "DetectionThreshold", 0.5);
    assert(logical(det.Detected), "B4 PRACH at 18 dB must be detected.");
    assert(double(det.DetectedPreambleIndex) == 0, "B4 PRACH must detect the transmitted preamble.");
    assert(abs(double(det.TimingOffsetSamples) - double(delaySamples)) <= 1.5, ...
        "B4 timing must select the first-arrival timing peak, not a repeated-symbol peak.");
    assert(isstruct(det.TimingSearchWindow) && logical(det.TimingSearchWindow.SearchApplied), ...
        "B4 detector must apply a receiver timing-search window.");
    assert(double(det.TimingSearchWindow.MaxLagSamples) < symbolSpacing, ...
        "Default B4 timing-search window must exclude the next repeated PRACH symbol peak.");
end

trace = det.CorrelationTrace;
repeatedPeakPresent = any(abs(double(trace.LagSamples) - symbolSpacing - 8) <= 1 & ...
    isfinite(double(trace.CorrelationAbs)));
assert(repeatedPeakPresent, ...
    "B4 correlation trace must preserve repeated-symbol peaks for audit diagnostics.");

assert(strcmpi(char(string(cfg.ChannelModel)), "CDL-D"), ...
    "Strict PRACH config must accept concrete CDL-D channel profiles.");

aliasCfg = struct("canonical_control", struct("random_access", struct("channel_model", "CDL-D")));
aliasCfg = sixgr.lls6g.config.normalizeScenarioAliases(aliasCfg);
assert(strcmpi(char(string(sixgr.util.structGet(aliasCfg, "random_access.channel_model", ""))), "CDL-D"), ...
    "Canonical-control random_access.channel_model must normalize into the runtime random_access section.");

catalog = sixgr.lls6g.config.loadParameterCatalog("scenario");
allowed = string(catalog.sections.random_access.parameters.channel_model.allowed_values);
assert(any(strcmpi(allowed, "CDL-D")), ...
    "Scenario catalog must allow concrete CDL-D for random_access.channel_model.");

ok = true;
end

function cfg = localB4StrictConfig()
base = struct();
base.random_access = struct( ...
    "enabled", true, ...
    "configuration_index", 167, ...
    "prach_format", "B4", ...
    "subcarrier_spacing_khz", 30, ...
    "root_sequence_index", 1, ...
    "sequence_index", 1, ...
    "logical_root_sequence_index", 1, ...
    "zero_correlation_zone", 8, ...
    "restricted_set", "UnrestrictedSet", ...
    "preamble_count", 64, ...
    "preamble_index", 0, ...
    "frequency_start", 0, ...
    "n_cell_id", 1, ...
    "carrier_scs_khz", 30, ...
    "n_size_grid", 273, ...
    "carrier_frequency_hz", 4e9, ...
    "duplex_mode", "TDD", ...
    "frequency_range", "FR1", ...
    "snr_sweep_db", 18, ...
    "timing_offset_sweep_samples", [0 4 8], ...
    "frequency_offset_sweep_hz", [0 100 250], ...
    "detection_threshold", 0.5, ...
    "detection_threshold_mode", "fixed", ...
    "num_trials", 8, ...
    "num_prach_occasions", 4, ...
    "channel_model", "CDL-D", ...
    "statistical_qualification", localShortStatisticalQualification());
cfg = sixgr.phy.prach.buildPRACHConfigFromScenario(base, ...
    "RunFolder", tempdir, "ScenarioName", "b4_timing_window");
end

function q = localShortStatisticalQualification()
% The timing-window test does not make a probability claim, but the strict
% scenario builder must still receive a complete, explicit statistical
% design.  Keep this bounded design local to the test; production values
% remain YAML-owned.
q = struct( ...
    "enabled", true, ...
    "target_false_alarm_probability", 0.1, ...
    "confidence_level", 0.95, ...
    "minimum_trials", 2, ...
    "maximum_trials", 2, ...
    "batch_size_trials", 2, ...
    "minimum_false_alarm_events", 0, ...
    "ci_width_target", 1, ...
    "planned_looks", 1, ...
    "target_missed_detection_probability", 0.1, ...
    "required_detection_snr_db", 18, ...
    "minimum_detection_trials", 2, ...
    "maximum_detection_trials", 2, ...
    "batch_size_detection_trials", 2, ...
    "minimum_missed_detection_events", 0, ...
    "detection_ci_width_target", 1, ...
    "detection_planned_looks", 1, ...
    "deterministic_seeds", [1900 1904]);
end

function wave = localApplyIntegerDelay(wave, delaySamples)
delaySamples = round(double(delaySamples));
if delaySamples > 0
    wave = [complex(zeros(delaySamples, size(wave, 2))); wave(1:end-delaySamples, :)];
end
end

function rx = localAddNoise(waveform, snrDb, seed)
rng(double(seed), "twister");
signalPower = mean(abs(waveform(:)).^2, "omitnan");
noiseVar = signalPower / max(10^(double(snrDb) / 10), eps);
rx = waveform + sqrt(noiseVar / 2) .* (randn(size(waveform)) + 1i .* randn(size(waveform)));
end
