function testLLSRasterAuthority()
%TESTLLSRASTERAUTHORITY Keep one CSV-driven raster producer for LLS runs.

repoRoot = fileparts(fileparts(mfilename("fullpath")));
coveragePath = fullfile(repoRoot, "+sixgr", "+truth", ...
    "exportLLSOutputCoverageArtifacts.m");
runnerPath = fullfile(repoRoot, "+sixgr", "+lls6g", "+runners", "runSingle.m");
reporterPath = fullfile(repoRoot, "+sixgr", "+truth", ...
    "exportLLSReportingBundle.m");
legacyMeasuredPlotterPath = fullfile(repoRoot, "+sixgr", "+analytics", ...
    "generateMeasuredSINRPlots.m");
runtimeCatalogPath = fullfile(repoRoot, "+sixgr", "+artifact", ...
    "ContractCatalog.m");
waveformRegistrationPath = fullfile(repoRoot, "+sixgr", "+artifact", ...
    "registerWaveformLinkEvidence.m");
initialAccessRegistrationPath = fullfile(repoRoot, "+sixgr", "+artifact", ...
    "registerInitialAccessEvidence.m");

coverageSource = string(fileread(coveragePath));
assert(~contains(coverageSource, "function localWritePRBHeatmapFigure"), ...
    "The legacy MATLAB PRB heatmap producer must not return.");
assert(~contains(coverageSource, "function localWritePowerEnergyFigure"), ...
    "The legacy MATLAB power/energy PNG producer must not return.");
assert(contains(coverageSource, "legacy_matlab_raster_emission_suppressed"), ...
    "The CSV-driven raster authority must be explicit in the coverage exporter.");

runnerSource = string(fileread(runnerPath));
assert(contains(runnerSource, "contractRasterAuthority") && ...
    contains(runnerSource, "~contractRasterAuthority"), ...
    "The waveform bundle must suppress legacy MATLAB rasters under the contract engine.");
reporterSource = string(fileread(reporterPath));
assert(contains(reporterSource, ...
    '"output.artifact_contract_engine.enabled", false') && ...
    contains(reporterSource, "usejava(""jvm"") && ~contractRasterAuthority"), ...
    "The reporting bundle must leave raster production to the CSV contract materializer.");
legacyMeasuredPlotterSource = string(fileread(legacyMeasuredPlotterPath));
assert(~contains(legacyMeasuredPlotterSource, "exportgraphics(") && ...
    ~contains(legacyMeasuredPlotterSource, "print(") && ...
    contains(legacyMeasuredPlotterSource, "retired_contract_raster_authority"), ...
    "The retired measured-SINR API must remain a file-free compatibility shim.");
runtimeCatalog = sixgr.artifact.ContractCatalog.load(repoRoot, "runtime_in_path");
assert(height(runtimeCatalog) == 3 && ...
    all(runtimeCatalog.ArtifactType == "CSV"), ...
    "The in-path MATLAB publisher must be CSV-only.");
runtimeCatalogSource = string(fileread(runtimeCatalogPath));
assert(~contains(extractAfter(runtimeCatalogSource, ...
    "function catalog = localRuntimeInPathCatalog"), ...
    '"prach_preamble_correlation.png"') && ...
    ~contains(extractAfter(runtimeCatalogSource, ...
    "function catalog = localRuntimeInPathCatalog"), ...
    '"pdsch_bler_vs_snr.png"') && ...
    ~contains(extractAfter(runtimeCatalogSource, ...
    "function catalog = localRuntimeInPathCatalog"), ...
    '"pusch_bler_vs_snr.png"'), ...
    "Retired runtime raster contracts must not return.");
assert(~contains(string(fileread(waveformRegistrationPath)), ...
    "registerRenderer") && ...
    ~contains(string(fileread(initialAccessRegistrationPath)), ...
    "registerRenderer"), ...
    "Runtime evidence registration must not contain MATLAB renderers.");
auditCall = "audit = sixgr.validation.auditRunArtifacts(runFolder";
assert(contains(runnerSource, auditCall), ...
    "Terminal artifact inventory refresh must remain wired into runSingle.");
auditRegionStart = strfind(runnerSource, "function audit = localRunArtifactAuditIfNeeded");
auditRegionEnd = strfind(extractAfter(runnerSource, auditRegionStart(1)), newline + "function ");
assert(~isempty(auditRegionEnd), "Could not isolate localRunArtifactAuditIfNeeded.");
auditRegion = extractBetween(runnerSource, auditRegionStart(1), ...
    auditRegionStart(1) + auditRegionEnd(1) - 1);
assert(~contains(auditRegion, "if ~audit.Required"), ...
    "Terminal inventory generation must execute even when it is not a mandatory scenario gate.");

fprintf("testLLSRasterAuthority: PASS\n");
end
