function ok = testLLSPlotDataValidation()
%TESTLLSPLOTDATAVALIDATION Guard honest plot gating for LLS reporting.

setup6GRSimToolkit("Verbose", false);

status = sixgr.visual.validatePlotData("relation", [0; 0], [1; 2]);
assert(strcmp(string(status.PlotRenderStatus), "suppressed") && strcmp(string(status.PlotSuppressionReason), "insufficient_unique_x"), ...
    "One-point relation plots must be suppressed instead of rendered as a misleading vs-curve.");

status = sixgr.visual.validatePlotData("trace", 1, 5);
assert(strcmp(string(status.PlotRenderStatus), "suppressed") && strcmp(string(status.PlotSuppressionReason), "insufficient_rows"), ...
    "One-row traces must be suppressed instead of rendered as timelines.");

status = sixgr.visual.validatePlotData("line", [1; 1; 2; 2], [10; 11; 12; 13], "XColumnName", "Frame");
assert(strcmp(string(status.PlotRenderStatus), "suppressed") && strcmp(string(status.PlotSuppressionReason), "insufficient_unique_frame_x_for_line_plot"), ...
    "Frame-based line plots with fewer than three unique x values must be suppressed.");

status = sixgr.visual.validatePlotData("line", [1; 2; 3], [10; 11; 12], "XColumnName", "Frame");
assert(strcmp(string(status.PlotRenderStatus), "rendered"), ...
    "Line plots with at least three monotonic finite frame values may render.");

status = sixgr.visual.validatePlotData("cdf", (1:3).', [NaN; NaN; NaN]);
assert(strcmp(string(status.PlotRenderStatus), "suppressed"), ...
    "All-NaN CDF sources must be suppressed.");

status = sixgr.visual.validatePlotData("relation", [0; 1; 2], [10; 12; 13]);
assert(strcmp(string(status.PlotRenderStatus), "rendered") && logical(status.CountsAsRealPlot), ...
    "Valid multi-point relation plots must remain renderable.");

status = sixgr.visual.validatePlotData("relation", [0; 1; 2], [10; 12; 13], "LLSValidity", "diagnostic_only");
assert(strcmp(string(status.VisualValidity), "diagnostic_only") && ~logical(status.CountsAsRealPlot) && strlength(string(status.WarningBannerText)) > 0, ...
    "Diagnostic-only plots must render with a warning and must not count as real LLS evidence.");

row = sixgr.visual.writePlotManifestRow( ...
    "unit_plot", "reports/image/unit_plot.png", "reports/csv/unit_plot.csv", "reports/csv/unit_plot.csv", ...
    "SNR_dB", "MetricValue", status, ...
    "PlotType", "relation", ...
    "PlotRenderStatus", status.PlotRenderStatus, ...
    "PlotSuppressionReason", status.PlotSuppressionReason, ...
    "CountsAsRealPlot", true, ...
    "AggregationMethod", "none");
assert(strcmp(string(row.SourceCSV), "reports/csv/unit_plot.csv") && strcmp(string(row.PlotId), "unit_plot"), ...
    "Plot manifest rows must retain direct source-CSV provenance.");
assert(ismember("VisualValidity", string(fieldnames(row))) && strcmp(string(row.VisualValidity), "diagnostic_only"), ...
    "Plot manifest rows must carry visual validity.");
assert(all(ismember(["actual_mime_type","declared_mime_type","extension","sha256","byte_count"], string(fieldnames(row)))), ...
    "Plot manifest rows must carry file-signature metadata fields.");

contracts = sixgr.visual.loadVisualArtifactContract();
assert(~isempty(contracts) && all(ismember(["PlotId","ImagePath","SourceCSV","RequiredColumns","MinRows","MinUniqueX","MinUniqueY","LLSValidity"], string(fieldnames(contracts)))), ...
    "Canonical visual artifact contract must load with required schema fields.");
controlSpec = contracts(strcmp(string({contracts.PlotId}), "control_pass_rates"));
controlSource = table(["PBCH";"PDCCH";"PUCCH";"PRACH"], [1.0;0.75;0.8;1.0], [2;6;4;2], [2;8;5;2], ...
    repmat("runtime_control_summary", 4, 1), repmat("control_summary", 4, 1), repmat("diagnostic_only", 4, 1), ...
    'VariableNames', ["Entity","PassRate","PassCount","TrialCount","SourceArtifact","CurveConstruction","truth_status"]);
controlStatus = sixgr.visual.evaluateVisualArtifactContract(controlSpec, controlSource);
assert(strcmp(string(controlStatus.PlotRenderStatus), "rendered") && strcmp(string(controlStatus.VisualValidity), "diagnostic_only"), ...
    "Categorical control-summary plot contracts must validate against category labels and numeric pass rates.");

tmpCleanup = string(tempname);
cleanupTmpCleanup = onCleanup(@() localRemoveFolder(tmpCleanup)); %#ok<NASGU>
mkdir(fullfile(tmpCleanup, "reports", "image"));
localWriteBytes(fullfile(tmpCleanup, "reports", "image", "old_stale.png"), uint8([137 80 78 71 13 10 26 10]));
cleanupReport = sixgr.visual.clearRunImageDirectories(tmpCleanup);
assert(exist(fullfile(tmpCleanup, "reports", "image", "old_stale.png"), "file") ~= 2 && ...
    istable(cleanupReport) && any(logical(cleanupReport.Cleared)), ...
    "Run-start visual cleanup must clear stale image directory contents.");

tmp = string(tempname);
cleanupTmp = onCleanup(@() localRemoveFolder(tmp)); %#ok<NASGU>
mkdir(fullfile(tmp, "reports", "csv"));
mkdir(fullfile(tmp, "reports", "image"));

diagnosticCsv = fullfile(tmp, "reports", "csv", "bler_vs_sinr.csv");
diagnosticT = table(["DL";"DL";"DL"], [1; 2; 3], [0.10; 0.20; 0.30], ...
    'VariableNames', ["Direction","XValue","YValue"]);
writetable(diagnosticT, diagnosticCsv);
fig = figure("Visible", "off", "Color", "w");
cleanupFig = onCleanup(@() close(fig)); %#ok<NASGU>
plot([1 2 3], [0.10 0.20 0.30]);
sixgr.util.exportFigureArtifact(fig, fullfile(tmp, "reports", "image", "bler_vs_sinr.png"));
clear cleanupFig;
prov = sixgr.truth.buildLLSReportingProvenanceTables(tmp, struct(), struct(), table(), struct("run_id", 0));
diagRow = prov.plot_manifest(strcmp(string(prov.plot_manifest.PlotId), "bler_vs_sinr"), :);
assert(~isempty(diagRow) && strcmp(string(diagRow.PlotRenderStatus), "rendered_diagnostic_plot") && ...
    strcmp(string(diagRow.VisualValidity), "diagnostic_only") && ~logical(diagRow.CountsAsRealPlot) && ...
    strlength(string(diagRow.WarningBannerText)) > 0, ...
    "Rendered non-real plots must be diagnostic-only and disclose their warning banner.");
assert(ismember("actual_mime_type", string(prov.plot_manifest.Properties.VariableNames)) && ...
    double(diagRow.byte_count) > 0 && strcmp(string(diagRow.actual_mime_type), "image/png"), ...
    "Rendered plot manifest rows must include actual byte-level MIME evidence.");

latencyCsv = fullfile(tmp, "reports", "csv", "latency_cdf_plot.csv");
writetable(table(1, 1, 'VariableNames', ["latency_ms","cdf_probability"]), latencyCsv);
stalePng = fullfile(tmp, "reports", "image", "latency_cdf.png");
fid = fopen(stalePng, "w");
fprintf(fid, "stale");
fclose(fid);
sixgr.visual.enforceVisualArtifactContract(tmp, "StrictMode", true, "CreateUnavailableCards", true);
unavailablePng = fullfile(tmp, "reports", "image", "latency_cdf_unavailable.png");
assert(exist(stalePng, "file") ~= 2 && exist(unavailablePng, "file") ~= 2, ...
    "Suppressed plots must not leave normal or unavailable-card PNG artifacts in strict mode.");

tmpConst = string(tempname);
cleanupTmpConst = onCleanup(@() localRemoveFolder(tmpConst)); %#ok<NASGU>
mkdir(fullfile(tmpConst, "reports", "csv"));
mkdir(fullfile(tmpConst, "reports", "image"));
constCsv = fullfile(tmpConst, "reports", "csv", "equalized_constellations.csv");
writetable(table([0; 1; 0], [0; 0; 1], ...
    'VariableNames', ["EqualizedReal","EqualizedImag"]), constCsv);
staleConstPng = fullfile(tmpConst, "reports", "image", "equalized_constellations.png");
localWriteBytes(staleConstPng, uint8([137 80 78 71 13 10 26 10 9 9 9 9]));
sixgr.visual.enforceVisualArtifactContract(tmpConst, "StrictMode", true, "CreateUnavailableCards", true);
constUnavailablePng = fullfile(tmpConst, "reports", "image", "equalized_constellations_unavailable.png");
assert(exist(staleConstPng, "file") ~= 2 && exist(constUnavailablePng, "file") ~= 2, ...
    "Constellation plots with missing lineage must be represented only by suppression metadata.");

tmpConstRuntime = string(tempname);
cleanupTmpConstRuntime = onCleanup(@() localRemoveFolder(tmpConstRuntime)); %#ok<NASGU>
mkdir(fullfile(tmpConstRuntime, "air_interface", "csv"));
mkdir(fullfile(tmpConstRuntime, "reports", "csv"));
mkdir(fullfile(tmpConstRuntime, "reports", "image"));
qpskI = repmat([-1; 1; -1; 1] ./ sqrt(2), 4, 1);
qpskQ = repmat([1; 1; -1; -1] ./ sqrt(2), 4, 1);
runtimeConst = table( ...
    repmat("DL", 16, 1), repmat("QPSK", 16, 1), repmat(18, 16, 1), repmat(1001, 16, 1), (1:16).', ...
    repmat(7, 16, 1), repmat(42, 16, 1), repmat(1, 16, 1), repmat(3, 16, 1), repmat(12.5, 16, 1), ...
    qpskI, qpskQ, qpskI + 0.01, qpskQ - 0.01, ...
    repmat(3.5, 16, 1), repmat(-29.1, 16, 1), ...
    repmat("post_equalized_and_reference_unit_power_constellation", 16, 1), repmat("real_lls_evidence", 16, 1), ...
    'VariableNames', ["RuntimeDirection","RuntimeModulation","RuntimeSNR_dB","UEIndex","SampleIndex", ...
    "RuntimeSlot","TBId","LayerIndex","MCSIndex","PostEqSINR_dB", ...
    "ReferenceSymbolReal","ReferenceSymbolImag","EqualizedReal","EqualizedImag", ...
    "RuntimeEVMRms_pct","RuntimeEVM_dB","RuntimeNormalization","RuntimeTruthStatus"]);
writetable(runtimeConst, fullfile(tmpConstRuntime, "air_interface", "csv", "dl_constellation_samples.csv"));
runtimeMeasuredSummary = table( ...
    ["DL"; "UL"], ["all"; "all"], [12.5; 8.75], [0.10; 0.20], ...
    'VariableNames', ["Direction","UEIndex","Goodput_Mbps_mean","BLER_overall"]);
writetable(runtimeMeasuredSummary, ...
    fullfile(tmpConstRuntime, "air_interface", "csv", "lls_measured_sinr_summary.csv"));
runtimeTrials = table( ...
    repmat("DL", 3, 1), [1; 1; 2], repmat(20, 3, 1), repmat(1, 3, 1), [16; 18; 20], ...
    [0; 1; 2], zeros(3, 1), zeros(3, 1), ...
    'VariableNames', ["Direction","UEID","SNR_dB","Frame","Slot", ...
    "PostEqSINR_dB","BLER","BER"]);
writetable(runtimeTrials, ...
    fullfile(tmpConstRuntime, "air_interface", "csv", "dl_pdsch_trials.csv"));
runtimeBeamStats = table( ...
    ["DL";"UL"], repmat("beamforming/csv/beam_management_state_trace.csv", 2, 1), ...
    [20;20], repmat("P2BeamFailureRate", 2, 1), [0;0], [0;0], [0;0], [3;2], ...
    repmat("P2_runtime_beam_state_tracking", 2, 1), repmat("BEAM_STATE_TRACE", 2, 1), ...
    'VariableNames', ["Direction","TraceSource","SNR_dB","Metric","MeanValue", ...
    "P05Value","P95Value","SampleCount","BeamManagementProcedure","SignalSourceFamily"]);
writetable(runtimeBeamStats, ...
    fullfile(tmpConstRuntime, "reports", "csv", "live_beam_p2_refinement_stats.csv"));
[runtimeScfg, runtimeCfg] = localConstellationScenarioConfig();
runtimeManifest = struct( ...
    "CodeVersion", "unit_fixture", ...
    "CodeDetail", "constellation_runtime_lineage", ...
    "RandomSeed", 42, ...
    "GeneratedUTC", "2026-06-21T00:00:00Z", ...
    "RunnerProfile", "unit_fixture", ...
    "RunCompletion", "completed", ...
    "ResultOk", true, ...
    "PartialOk", true, ...
    "ArtifactsGenerated", true, ...
    "DeterministicMode", "deterministic_fixture", ...
    "RequiredCaseCount", 1, ...
    "RequiredFailureCount", 0, ...
    "OptionalPrunedCount", 0);
sixgr.truth.exportLLSReportingBundle(tmpConstRuntime, runtimeScfg, runtimeCfg, struct(), runtimeManifest, struct(), struct());
runtimeEqCsv = fullfile(tmpConstRuntime, "reports", "csv", "equalized_constellations.csv");
runtimeEqPng = fullfile(tmpConstRuntime, "reports", "image", "equalized_constellations.png");
runtimeWaterfallPng = fullfile(tmpConstRuntime, "reports", "image", "gains_losses_waterfall.png");
runtimeWaterfallUnavailable = fullfile(tmpConstRuntime, "reports", "image", "gains_losses_waterfall_unavailable.png");
assert(exist(runtimeEqCsv, "file") == 2 && exist(runtimeEqPng, "file") == 2, ...
    "Measured runtime-prefixed constellation samples must produce the equalized constellation CSV and PNG.");
assert(exist(runtimeWaterfallPng, "file") ~= 2 && exist(runtimeWaterfallUnavailable, "file") ~= 2, ...
    "A single-scenario mixed-units source must publish suppression metadata, not a misleading or unavailable-card PNG.");
runtimeProvenance = sixgr.truth.buildLLSReportingProvenanceTables( ...
    tmpConstRuntime, struct(), struct(), table(), struct("run_id", 0));
runtimePlotManifest = runtimeProvenance.plot_manifest;
runtimeWaterfallManifest = runtimePlotManifest(runtimePlotManifest.PlotId == ...
    "gains_losses_waterfall", :);
assert(height(runtimeWaterfallManifest) == 1 && ...
    runtimeWaterfallManifest.PlotRenderStatus == "suppressed" && ...
    contains(runtimeWaterfallManifest.PlotSuppressionReason, "insufficient_rows"), ...
    ["The one-scenario waterfall must be explicitly suppressed with its " ...
     "low-information reason; an unexplained not_rendered status fails the visual truth gate."]);
runtimeEqT = readtable(runtimeEqCsv, "VariableNamingRule", "preserve");
requiredLineage = ["direction","ue_id","slot","tb_id","layer","modulation","mcs_index","snr_db", ...
    "posteq_sinr_db","symbol_index","reference_symbol_i","reference_symbol_q","equalized_i","equalized_q", ...
    "evm_rms_pct","evm_db","normalization","truth_status"];
assert(all(ismember(requiredLineage, string(runtimeEqT.Properties.VariableNames))), ...
    "Equalized constellation report CSV must carry canonical measured lineage columns.");
assert(all(isfinite(double(runtimeEqT.ue_id))) && all(isfinite(double(runtimeEqT.snr_db))) && all(isfinite(double(runtimeEqT.slot))) && ...
    all(strcmp(string(runtimeEqT.modulation), "QPSK")) && all(strcmp(string(runtimeEqT.truth_status), "real_lls_evidence")), ...
    "Runtime-prefixed constellation lineage must be preserved into canonical report columns.");
relationshipT = readtable(fullfile(tmpConstRuntime, "reports", "csv", "ber_vs_bler.csv"), ...
    "VariableNamingRule", "preserve", "TextType", "string");
assert(all(ismember(["SourceRow","TrialID","UEID","SNR_dB","Frame","Slot","SourceArtifact"], ...
    string(relationshipT.Properties.VariableNames))) && ...
    height(unique(relationshipT, "rows", "stable")) == height(relationshipT), ...
    "Coincident BER/BLER points must retain event identity and must not become duplicate chart-source rows.");
beamOutputsT = readtable(fullfile(tmpConstRuntime, "reports", "csv", "beam_management_outputs.csv"), ...
    "VariableNamingRule", "preserve", "TextType", "string");
beamFailure = beamOutputsT(beamOutputsT.MetricKey == "beam_failure_rate", :);
beamKey = beamFailure(:, ["MetricKey","Entity","Statistic"]);
assert(height(beamFailure) == 8 && height(unique(beamKey, "rows", "stable")) == height(beamFailure) && ...
    any(contains(beamFailure.Statistic, "direction_dl")) && ...
    any(contains(beamFailure.Statistic, "direction_ul")), ...
    "Beam-management aggregates must retain DL/UL/SNR scope in their natural keys.");
trackingT = readtable(fullfile(tmpConstRuntime, "reports", "csv", "cfo_to_tracking_traces.csv"), ...
    "VariableNamingRule", "preserve", "TextType", "string");
assert(all(ismember(["SourceRow","UEID","RNTI","TransportBlockId"], ...
    string(trackingT.Properties.VariableNames))) && ...
    height(unique(trackingT, "rows", "stable")) == height(trackingT), ...
    "Tracking trace rows must preserve source event/UE/TB identity even when measured values coincide.");

prov = sixgr.truth.buildLLSReportingProvenanceTables(tmp, struct(), struct(), table(), struct("run_id", 0));
latencyRow = prov.plot_manifest(strcmp(string(prov.plot_manifest.PlotId), "latency_cdf"), :);
assert(~isempty(latencyRow) && strcmp(string(latencyRow.PlotRenderStatus), "suppressed") && ...
    strcmp(string(latencyRow.VisualValidity), "unavailable") && ~logical(latencyRow.IsUnavailableCard) && ...
    endsWith(string(latencyRow.ImagePath), "latency_cdf.png"), ...
    "Unavailable measurements must remain suppressed manifest rows with no raster card.");

tmpIntegrity = string(tempname);
cleanupTmpIntegrity = onCleanup(@() localRemoveFolder(tmpIntegrity)); %#ok<NASGU>
mkdir(fullfile(tmpIntegrity, "reports", "image"));
pngAsSvg = fullfile(tmpIntegrity, "reports", "image", "png_bytes.svg");
localWriteBytes(pngAsSvg, uint8([137 80 78 71 13 10 26 10 0 0 0 0]));
pngAsSvgInfo = sixgr.visual.inspectVisualArtifactFile(pngAsSvg);
assert(strcmp(string(pngAsSvgInfo.actual_mime_type), "image/png") && ~logical(pngAsSvgInfo.extension_mime_match), ...
    "A .svg artifact containing PNG bytes must be detected as a MIME mismatch.");
pngAsSvgRow = sixgr.visual.writePlotManifestRow( ...
    "png_bytes_svg", "reports/image/png_bytes.svg", "reports/csv/source.csv", "reports/csv/source.csv", ...
    "x", "y", struct("RowCount", 3, "UniqueXCount", 3, "UniqueYCount", 3, "NonNaNYCount", 3), ...
    "PlotType", "relation", "PlotRenderStatus", "rendered_real_plot", ...
    "CountsAsRealPlot", true, "VisualValidity", "real_lls_evidence");
integrityT = sixgr.visual.verifyVisualArtifacts(tmpIntegrity, struct2table(pngAsSvgRow));
assert(any(~logical(integrityT.IntegrityOk) & string(integrityT.FailureCode) == "vector_visual_format_forbidden"), ...
    "The visual artifact verifier must fail every persisted .svg path, including PNG bytes hidden under that extension.");

tmpOrphan = string(tempname);
cleanupTmpOrphan = onCleanup(@() localRemoveFolder(tmpOrphan)); %#ok<NASGU>
mkdir(fullfile(tmpOrphan, "reports", "image"));
orphanPng = fullfile(tmpOrphan, "reports", "image", "orphan.png");
localWriteBytes(orphanPng, uint8([137 80 78 71 13 10 26 10 1 2 3 4]));
orphanIntegrityT = sixgr.visual.verifyVisualArtifacts(tmpOrphan, table());
assert(any(~logical(orphanIntegrityT.IntegrityOk) & ...
        string(orphanIntegrityT.FailureCode) == "unmanifested_visual_artifact"), ...
    "A valid PNG without a plot-manifest lineage row must fail visual integrity.");

tmpComponent = string(tempname);
cleanupTmpComponent = onCleanup(@() localRemoveFolder(tmpComponent)); %#ok<NASGU>
mkdir(fullfile(tmpComponent, "control", "csv"));
mkdir(fullfile(tmpComponent, "control", "image"));
componentSource = fullfile(tmpComponent, "control", "csv", "component_trials.csv");
writetable(table((1:4).', [0.1;0.2;0.4;0.8], nan(4, 1), ...
    'VariableNames', ["Trial","Metric","StructurallyBlank"]), componentSource);
componentImage = fullfile(tmpComponent, "control", "image", "component_metric.png");
imwrite(uint8(repmat(reshape(uint8(0:255), 16, 16), 1, 1, 3)), componentImage);
sixgr.visual.writeComponentPlotLineage(tmpComponent, ...
    fullfile(tmpComponent, "control", "csv", "component_plot_lineage.csv"), ...
    "component_metric", componentImage, componentSource, "testLLSPlotDataValidation");
componentIntegrityT = sixgr.visual.verifyVisualArtifacts(tmpComponent, table());
componentMask = string(componentIntegrityT.ArtifactPath) == "control/image/component_metric.png";
assert(any(componentMask) && all(logical(componentIntegrityT.IntegrityOk(componentMask))), ...
    "A component PNG with exact source CSV lineage and matching hash must pass visual integrity.");
componentLineage = readtable(fullfile(tmpComponent, "control", "csv", ...
    "component_plot_lineage.csv"), "TextType", "string", ...
    "VariableNamingRule", "preserve");
sourceHashBeforeFinalization = string(componentLineage.SourceCSV_SHA256(1));
sixgr.truth.sanitizeLLSArtifactCSVs(tmpComponent);
sourceHashAfterFinalization = string(sixgr.util.sha256Hex( ...
    uint8(fileread(componentSource))));
assert(sourceHashAfterFinalization == sourceHashBeforeFinalization, ...
    ["Component lineage must hash stabilized source CSV bytes that remain " ...
     "unchanged during whole-run finalization."]);
componentIntegrityT = sixgr.visual.verifyVisualArtifacts(tmpComponent, table());
componentMask = string(componentIntegrityT.ArtifactPath) == "control/image/component_metric.png";
assert(any(componentMask) && all(logical(componentIntegrityT.IntegrityOk(componentMask))), ...
    "Whole-run finalization must not invalidate an already accepted component plot lineage.");

tmpNested = string(tempname);
cleanupTmpNested = onCleanup(@() localRemoveFolder(tmpNested)); %#ok<NASGU>
componentRoot = fullfile(tmpNested, "component_anchors", "prach");
mkdir(fullfile(componentRoot, "control", "csv"));
mkdir(fullfile(componentRoot, "reports", "figures"));
nestedSource = fullfile(componentRoot, "control", "csv", "prach_resource_grid.csv");
writetable(table((1:4).', [1;0;1;1], ...
    'VariableNames', ["Occasion","Detected"]), nestedSource);
nestedImage = fullfile(componentRoot, "reports", "figures", "prach_resource_grid.png");
imwrite(uint8(repmat(reshape(uint8(0:255), 16, 16), 1, 1, 3)), nestedImage);
sixgr.visual.writeComponentPlotLineage(componentRoot, ...
    fullfile(componentRoot, "control", "csv", "prach_plot_lineage.csv"), ...
    "prach_resource_grid", nestedImage, nestedSource, "testLLSPlotDataValidation");
nestedIntegrityT = sixgr.visual.verifyVisualArtifacts(tmpNested, table());
nestedMask = string(nestedIntegrityT.ArtifactPath) == ...
    "component_anchors/prach/reports/figures/prach_resource_grid.png";
assert(any(nestedMask) && all(logical(nestedIntegrityT.IntegrityOk(nestedMask))), ...
    ["Nested component lineage paths must resolve against their owning " ...
     "component root, not against the enclosing LLS run root."]);

delete(componentSource);
componentMissingSourceT = sixgr.visual.verifyVisualArtifacts(tmpComponent, table());
componentMask = string(componentMissingSourceT.ArtifactPath) == "control/image/component_metric.png";
assert(any(componentMask) && any(string(componentMissingSourceT.FailureCode(componentMask)) == "source_csv_missing"), ...
    "Component visual lineage must fail when its exact source CSV is missing.");

tmpStale = string(tempname);
cleanupTmpStale = onCleanup(@() localRemoveFolder(tmpStale)); %#ok<NASGU>
mkdir(fullfile(tmpStale, "reports", "image"));
staleSuppressedPng = fullfile(tmpStale, "reports", "image", "latency_cdf.png");
localWriteBytes(staleSuppressedPng, uint8([137 80 78 71 13 10 26 10 1 2 3 4]));
suppressedRow = sixgr.visual.writePlotManifestRow( ...
    "latency_cdf", "reports/image/latency_cdf.png", "reports/csv/latency_cdf_plot.csv", "reports/csv/latency_cdf_plot.csv", ...
    "latency_ms", "cdf_probability", struct("RowCount", 1, "UniqueXCount", 1, "UniqueYCount", 1, "NonNaNYCount", 1), ...
    "PlotType", "cdf", "PlotRenderStatus", "suppressed", ...
    "PlotSuppressionReason", "insufficient_rows", "CountsAsRealPlot", false, "VisualValidity", "unavailable");
staleIntegrityT = sixgr.visual.verifyVisualArtifacts(tmpStale, struct2table(suppressedRow));
assert(any(~logical(staleIntegrityT.IntegrityOk) & string(staleIntegrityT.FailureCode) == "stale_suppressed_normal_artifact"), ...
    "A suppressed plot must fail visual integrity if a normal PNG artifact still exists.");

tmpCard = string(tempname);
cleanupTmpCard = onCleanup(@() localRemoveFolder(tmpCard)); %#ok<NASGU>
mkdir(fullfile(tmpCard, "reports", "image"));
sixgr.visual.writeUnavailablePlotCard(fullfile(tmpCard, "reports", "image", "good_card.png"), "good_card", "not enough runtime evidence");
goodCardPath = fullfile(tmpCard, "reports", "image", "good_card_unavailable.png");
goodCardInfo = sixgr.visual.inspectVisualArtifactFile(goodCardPath);
assert(exist(goodCardPath, "file") ~= 2 && strcmp(string(goodCardInfo.actual_mime_type), "missing"), ...
    "Unavailable measurements must not create raster artifacts.");
sixgr.visual.writeUnavailablePlotCard(fullfile(tmpCard, "reports", "image", "good_card.png"), "good_card", "replacement evidence unavailable");
replacedCardInfo = sixgr.visual.inspectVisualArtifactFile(goodCardPath);
assert(exist(goodCardPath, "file") ~= 2 && strcmp(string(replacedCardInfo.actual_mime_type), "missing"), ...
    "Repeated unavailable publication requests must remain raster-free.");
badCardPath = fullfile(tmpCard, "reports", "image", "bad_card.svg");
localWriteText(badCardPath, "<svg xmlns=""http://www.w3.org/2000/svg""><text>Unavailable</text></svg>");
badCardRow = sixgr.visual.writePlotManifestRow( ...
    "bad_card", "reports/image/bad_card.svg", "reports/csv/source.csv", "reports/csv/source.csv", ...
    "x", "y", struct("RowCount", 0, "UniqueXCount", 0, "UniqueYCount", 0, "NonNaNYCount", 0), ...
    "PlotType", "card", "PlotRenderStatus", "rendered_unavailable_card", ...
    "IsUnavailableCard", true, "CountsAsRealPlot", false, "VisualValidity", "unavailable");
badCardIntegrityT = sixgr.visual.verifyVisualArtifacts(tmpCard, struct2table(badCardRow));
assert(any(~logical(badCardIntegrityT.IntegrityOk) & string(badCardIntegrityT.FailureCode) == "vector_visual_format_forbidden"), ...
    "SVG unavailable cards must fail the raster-only and no-placeholder visual policy.");

tmpRedirect = string(tempname);
cleanupTmpRedirect = onCleanup(@() localRemoveFolder(tmpRedirect)); %#ok<NASGU>
mkdir(fullfile(tmpRedirect, "reports", "image"));
legacySvgRequest = fullfile(tmpRedirect, "reports", "image", "legacy_request.svg");
fig = figure("Visible", "off", "Color", "w");
cleanupRedirectFig = onCleanup(@() close(fig)); %#ok<NASGU>
plot([0 1 2], [0.2 0.5 0.9]);
actualRasterPath = string(sixgr.util.exportFigureArtifact(fig, legacySvgRequest));
clear cleanupRedirectFig;
redirectedPng = fullfile(tmpRedirect, "reports", "image", "legacy_request.png");
redirectedInfo = sixgr.visual.inspectVisualArtifactFile(redirectedPng);
assert(actualRasterPath == string(redirectedPng) && exist(legacySvgRequest, "file") ~= 2 && ...
        exist(redirectedPng, "file") == 2 && string(redirectedInfo.actual_mime_type) == "image/png", ...
    "Legacy SVG export requests must persist a real PNG and must not leave an SVG file.");

tmpSNR = string(tempname);
cleanupTmpSNR = onCleanup(@() localRemoveFolder(tmpSNR)); %#ok<NASGU>
mkdir(fullfile(tmpSNR, "air_interface", "csv"));
mkdir(fullfile(tmpSNR, "reports", "image"));
writetable(localEmptyControlledSNRSweepTable(), fullfile(tmpSNR, "air_interface", "csv", "lls_snr_sweep.csv"));
snrPng = fullfile(tmpSNR, "reports", "image", "bler_vs_snr.png");
fig = figure("Visible", "off", "Color", "w");
cleanupFig = onCleanup(@() close(fig)); %#ok<NASGU>
plot([0 1 2], [0.8 0.5 0.2]);
sixgr.util.exportFigureArtifact(fig, snrPng);
clear cleanupFig;
snrUnavailable = fullfile(tmpSNR, "reports", "image", "bler_vs_snr_unavailable.png");
assert(exist(snrPng, "file") ~= 2 && exist(snrUnavailable, "file") ~= 2, ...
    "An empty controlled SNR sweep must not produce any BLER-vs-SNR raster.");

ok = true;
end

function T = localEmptyControlledSNRSweepTable()
T = table(strings(0,1), zeros(0,1), zeros(0,1), zeros(0,1), zeros(0,1), zeros(0,1), ...
    zeros(0,1), zeros(0,1), zeros(0,1), zeros(0,1), zeros(0,1), zeros(0,1), zeros(0,1), ...
    zeros(0,1), strings(0,1), strings(0,1), zeros(0,1), zeros(0,1), zeros(0,1), zeros(0,1), ...
    strings(0,1), false(0,1), strings(0,1), zeros(0,1), strings(0,1), ...
    'VariableNames', ["direction","snr_db","noise_variance","n_tb","n_crc_fail","bler","bler_ci_low", ...
    "bler_ci_high","n_bits","n_bit_errors","ber","throughput_mbps","goodput_mbps","mcs_index", ...
    "mcs_table","cqi_table","modulation_order","code_rate","tbs","n_layers","rv_sequence", ...
    "harq_enabled","channel_model","seed","truth_status"]);
end

function [scfg, cfg] = localConstellationScenarioConfig()
data = struct();
data = sixgr.util.structSet(data, "meta.scenario_id", "constellation_runtime_lineage_fixture");
data = sixgr.util.structSet(data, "meta.scenario_name", "Constellation runtime lineage fixture");
data = sixgr.util.structSet(data, "meta.scenario_family", "unit_fixture");
data = sixgr.util.structSet(data, "simulation.link_direction", "dl");
data = sixgr.util.structSet(data, "frequency.center_frequency_hz", 4.0e9);
data = sixgr.util.structSet(data, "frequency.bandwidth_hz", 100.0e6);
data = sixgr.util.structSet(data, "frequency.n_size_grid", 273);
data = sixgr.util.structSet(data, "frame.scs_khz", 30);
data = sixgr.util.structSet(data, "waveform.sample_rate_hz", 122.88e6);
data = sixgr.util.structSet(data, "global_radio_scope.channel_bandwidth_hz", 100.0e6);
data = sixgr.util.structSet(data, "users.n_users", 1);
cfg = data;
scfg = sixgr.lls6g.config.ScenarioConfig(data, "ConfigHash", "constellation_runtime_lineage_hash");
end

function localRemoveFolder(path)
try
    if exist(path, "dir") == 7
        rmdir(path, "s");
    end
catch
end
end

function localWriteBytes(filePath, data)
sixgr.util.ensureFolder(fileparts(char(string(filePath))));
fid = fopen(filePath, "w");
assert(fid >= 0, "Failed to create visual byte fixture.");
cleanupObj = onCleanup(@() fclose(fid)); %#ok<NASGU>
fwrite(fid, uint8(data), "uint8");
end

function localWriteText(filePath, textValue)
sixgr.util.ensureFolder(fileparts(char(string(filePath))));
fid = fopen(filePath, "w");
assert(fid >= 0, "Failed to create visual text fixture.");
cleanupObj = onCleanup(@() fclose(fid)); %#ok<NASGU>
fprintf(fid, "%s", char(string(textValue)));
end
