function ok = testSystemLevelCausalCQIFeedback()
%TESTSYSTEMLEVELCAUSALCQIFEEDBACK System AMC must consume delayed receiver CQI.

setup6GRSimToolkit("Verbose", false);

cfg = localConfig();

% A measured CQI-0 report is explicit out-of-range feedback.  It must not
% reopen the first-transmission bootstrap path.
zeroCQIScheduler = sixgr.l2.mac.SchedulerRR(cfg, "Direction", "DL");
zeroCQIUE = struct("RNTI", 701, "CQI", 0, "RI", 1, ...
    "FeedbackValid", true, "CausalFeedbackUsable", true, ...
    "CausalFeedbackStatus", "measured_receiver_feedback_available", ...
    "SchedulerCQISource", "receiver_post_equalization_sinr");
[~, ~, ~, zeroAMC] = zeroCQIScheduler.selectAMC(zeroCQIUE);
assert(string(zeroAMC.MCSSelectionSource) == ...
    "blocked_measured_cqi_zero_out_of_range" && ...
    string(zeroAMC.MCSValueStatus) == ...
    "unavailable_measured_cqi_zero_out_of_range", ...
    "Measured CQI 0 must block new data instead of selecting bootstrap MCS. " + ...
    "Observed source='%s' status='%s' mode='%s' causal='%s'.", ...
    string(zeroAMC.MCSSelectionSource), string(zeroAMC.MCSValueStatus), ...
    string(zeroAMC.Mode), string(zeroAMC.CausalFeedbackStatus));
zeroPlan = zeroCQIScheduler.buildNewDataGrantPlan( ...
    zeroCQIUE, 0:23, [2 12], 4000);
assert(~zeroPlan.Valid && double(zeroPlan.TBSBits) == 0 && ...
    string(zeroPlan.GrantBlocker) == ...
    "blocked_measured_cqi_zero_out_of_range", ...
    "The executable grant boundary must reject measured CQI 0.");

% Coupled-runtime SRS/CSI installation can carry a typed causal-admission
% result independently of the legacy feedback-valid flag.  When that
% measured feedback is admitted and is not a bootstrap preview, CQI mapping
% genuinely executed and must be labelled as inner-loop applied.
causalScheduler = sixgr.l2.mac.SchedulerRR(cfg, "Direction", "UL");
causalMeasuredUE = struct("RNTI", 702, "CQI", 12, "RI", 1, ...
    "FeedbackValid", false, "CausalFeedbackUsable", true, ...
    "CausalFeedbackStatus", "measured_ul_srs_feedback_available", ...
    "BootstrapCQIUsableForScheduling", false, ...
    "BootstrapCQISource", "", ...
    "SchedulerCQISource", "measured_ul_srs_wideband");
[~, ~, ~, causalAMC] = causalScheduler.selectAMC(causalMeasuredUE);
assert(logical(causalAMC.InnerLoopApplied) && ...
    string(causalAMC.MCSSelectionSource) == "runtime_cqi_table", ...
    ["A causally admitted measured SRS/CSI CQI decision must be labelled " + ...
     "as an applied inner-loop decision."]);

ctx = sixgr.core.SimContext(cfg);
nTTI = 7;
res = sixgr.system.SystemLevelRunner.run(ctx, struct( ...
    "NumTTI", nTTI, ...
    "OfferedBitsDL", repmat(12000, nTTI, 1), ...
    "OfferedBitsUL", repmat(12000, nTTI, 1), ...
    "PHYBackend", "waveform"));
assert(res.Ok, "Focused causal system-level waveform run must complete.");
assert(double(res.Details.CQIFeedbackDelaySlots) == 2, ...
    "System runner must consume the configured CQI feedback delay.");

grantT = res.Details.SchedulerGrants;
assert(istable(grantT) && height(grantT) > 0, ...
    "Causal system run must expose waveform-backed grants.");
required = ["InnerLoopEnabled","InnerLoopApplied","OuterLoopEnabled", ...
    "OuterLoopApplied","OLLADeltaDb","OLLAUpdateCount", ...
    "OLLAStateAuthority", ...
    "CausalFeedbackUsable", ...
    "CausalFeedbackStatus","FeedbackAgeSlots","SchedulerCQISource", ...
    "PostEqSINR_dB","PostEqSINRSource"];
for i = 1:numel(required)
    assert(ismember(required(i), string(grantT.Properties.VariableNames)), ...
        "Grant trace missing causal AMC column '%s'.", required(i));
end

bootstrapRows = contains(string(grantT.MCSSelectionSource), ...
    "bootstrap_cqi_conservative");
measuredRows = logical(grantT.InnerLoopApplied) & ...
    logical(grantT.CausalFeedbackUsable) & ...
    contains(lower(string(grantT.SchedulerCQISource)), "post_equal");
assert(any(bootstrapRows), ...
    "At least one first-data grant must retain explicit bootstrap provenance.");
assert(all(~logical(grantT.InnerLoopApplied(bootstrapRows))), ...
    "Bootstrap grants must not be mislabeled as receiver-driven inner-loop decisions.");
assert(any(measuredRows), ...
    "A later grant must consume delayed receiver post-equalization CQI. " + ...
    "MCS sources=%s; scheduler CQI sources=%s; feedback states=%s; " + ...
    "post-EQ sources=%s; CE available=%s; EQ available=%s; DL queue rows=%d; UL queue rows=%d.", ...
    strjoin(unique(string(grantT.MCSSelectionSource)), "|"), ...
    strjoin(unique(string(grantT.SchedulerCQISource)), "|"), ...
    strjoin(unique(string(grantT.CausalFeedbackStatus)), "|"), ...
    strjoin(unique(string(grantT.PostEqSINRSource)), "|"), ...
    mat2str(unique(logical(grantT.ChannelEstimateAvailable)).'), ...
    mat2str(unique(logical(grantT.EqualizationAvailable)).'), ...
    height(res.Details.CQIFeedbackDL), height(res.Details.CQIFeedbackUL));
assert(all(double(grantT.FeedbackAgeSlots(measuredRows)) >= 2), ...
    "Measured CQI must not reach a grant before the configured feedback delay.");
assert(all(~contains(lower(string(grantT.SchedulerCQISource(measuredRows))), ...
    ["configured","system_level","proxy","fallback","evm"])), ...
    "Measured scheduler CQI provenance must not use configured or proxy SINR.");
ollaRows = measuredRows & logical(grantT.OuterLoopApplied);
assert(any(ollaRows) && all(logical(grantT.OuterLoopEnabled(ollaRows))) && ...
    all(double(grantT.OLLAUpdateCount(ollaRows)) >= 1) && ...
    all(isfinite(double(grantT.OLLADeltaDb(ollaRows)))) && ...
    any(abs(double(grantT.OLLADeltaDb(ollaRows))) > 0), ...
    "OLLA must apply a nonzero dB-domain ACK/NACK margin only after feedback.");
assert(all(string(grantT.OLLAStateAuthority(ollaRows)) == ...
    "scheduler_local_state"), ...
    "Standalone system-level scheduling must expose its sole OLLA state authority.");

localAssertFeedbackTimeline(res.Details.CQIFeedbackDL, "DL", grantT);
localAssertFeedbackTimeline(res.Details.CQIFeedbackUL, "UL", grantT);

tmp = tempname;
mkdir(tmp);
cleanup = onCleanup(@() rmdir(tmp, "s")); %#ok<NASGU>
sixgr.truth.exportSystemLevelCanonicalArtifacts( ...
    tmp, localScenarioConfig(), cfg, res);
rawDL = localRead(fullfile(tmp, "air_interface", "csv", "dl_pdsch_trials.csv"));
rawUL = localRead(fullfile(tmp, "air_interface", "csv", "ul_pusch_trials.csv"));
localAssertCanonicalRaw(rawDL, "DL");
localAssertCanonicalRaw(rawUL, "UL");

persistedDL = localRead(fullfile(tmp, "system", "csv", ...
    "dl_cqi_feedback_timeline.csv"));
persistedUL = localRead(fullfile(tmp, "system", "csv", ...
    "ul_cqi_feedback_timeline.csv"));
localAssertFeedbackTimeline(persistedDL, "DL persisted", grantT);
localAssertFeedbackTimeline(persistedUL, "UL persisted", grantT);

ok = true;
end

function localAssertCanonicalRaw(raw, label)
for name = ["InnerLoopEnabled","InnerLoopApplied","OuterLoopEnabled", ...
        "OuterLoopApplied","OLLADeltaDb","OLLAUpdateCount", ...
        "OLLAStateAuthority", ...
        "CausalFeedbackUsable","CausalFeedbackStatus", ...
        "FeedbackAgeSlots","SchedulerCQISource", ...
        "CQISelectionSource","CQIValueStatus","LinkAdaptationApplied"]
    assert(ismember(name, string(raw.Properties.VariableNames)), ...
        "%s canonical raw CSV missing causal AMC column '%s'.", label, name);
end
rawMeasured = logical(raw.InnerLoopApplied);
assert(any(rawMeasured) && all(logical(raw.LinkAdaptationApplied(rawMeasured))), ...
    "%s canonical raw rows must mark executed decisions as applied.", label);
assert(all(contains(lower(string(raw.CQISelectionSource(rawMeasured))), "post_equal")), ...
    "%s canonical CQI source must preserve receiver provenance.", label);
rawOLLA = logical(raw.OuterLoopApplied);
assert(any(rawOLLA) && all(double(raw.OLLAUpdateCount(rawOLLA)) >= 1) && ...
    any(abs(double(raw.OLLADeltaDb(rawOLLA))) > 0), ...
    "%s canonical rows must preserve applied ACK/NACK OLLA state.", label);
end

function cfg = localConfig()
cfg = sixgr.config.defaultConfig();
cfg.run.shortRun = true;
cfg.run.strictMode = false;
cfg.run.useMex = false;
cfg.run.seed = 44021;
cfg.run.runTag = "system_level_causal_cqi_feedback";
cfg.run.executionID = "system_level_causal_cqi_feedback_execution";
cfg.meta.scenarioID = "unit_test_system_level_causal_cqi";
cfg.meta.configHash = repmat('b', 1, 64);
cfg.system.phyBackend = "waveform";
cfg.outputs.saveCSV = false;
cfg.outputs.saveMAT = false;
cfg.outputs.saveFigures = false;
cfg.outputs.saveFIG = false;
cfg.outputs.exportSLSOutputCatalog = false;
cfg.scenario.layout.nSites = 1;
cfg.scenario.layout.nSectorsPerSite = 1;
cfg.scenario.layout.wrapAround = false;
cfg.scenario.ue.nUE = 1;
cfg.scenario.nUE = 1;
cfg.scenario.bs.nTxAnt = 1;
cfg.scenario.bs.nRxAnt = 1;
cfg.scenario.ue.nTxAnt = 1;
cfg.scenario.ue.nRxAnt = 1;
cfg.channel.awgnOnly = true;
cfg.channel.model = "AWGN";
cfg.channel.fading.enable = false;
cfg.phy.duplex.mode = "FDD";
cfg.phy.duplex.fdd = struct( ...
    "dlCenterFrequencyHz", 4.0e9, "ulCenterFrequencyHz", 3.9e9);
cfg.phy.pdcch.symbolAllocation = [0 2];
cfg.phy.pdcch.SymbolAllocation = [0 2];
% Exercise both directions through a real monitored common-DCI pair.  The
% production scheduler correctly refuses to manufacture an UL DCI 0_0
% grant when the search-space authority does not monitor it.
cfg.phy.pdcch.dciFormats = {'1_0', '0_0'};
cfg.phy.pdsch.symbolAllocation = [2 12];
cfg.phy.pdsch.SymbolAllocation = [2 12];
cfg.phy.pdsch.modulation = "QPSK";
cfg.phy.pdsch.codeRate = 120/1024;
cfg.phy.pdsch.mcsTable = "qam64_table1";
cfg.phy.pdsch.cqiTable = "table1";
cfg.phy.pdsch.numLayers = 1;
cfg.phy.pdsch.nLayers = 1;
cfg.phy.pucch.symbolAllocation = [12 2];
cfg.phy.pucch.SymbolAllocation = [12 2];
cfg.phy.pusch.symbolAllocation = [0 14];
cfg.phy.pusch.SymbolAllocation = [0 14];
cfg.phy.pusch.modulation = "QPSK";
cfg.phy.pusch.codeRate = 120/1024;
cfg.phy.pusch.mcsTable = "qam64_table1";
cfg.phy.pusch.cqiTable = "table1";
cfg.phy.pusch.numLayers = 1;
cfg.phy.pusch.nLayers = 1;
cfg.phy.linkAdaptation.mode = "amc";
cfg.phy.linkAdaptation.dlPolicy = "baseline";
cfg.phy.linkAdaptation.ulPolicy = "baseline";
cfg.phy.linkAdaptation.innerLoopFlag = true;
cfg.phy.linkAdaptation.outerLoopFlag = true;
cfg.phy.linkAdaptation.deltaMCSPolicy = "olla";
cfg.phy.linkAdaptation.bootstrapCQIMode = "conservative";
cfg.phy.linkAdaptation.bootstrapMCSIndex = 0;
cfg.phy.linkAdaptation.maximumMCSIndex = 10;
cfg.phy.linkAdaptation.ollaStepDown = 0.9;
cfg.phy.linkAdaptation.ollaStepUp = 0.1;
cfg.phy.linkAdaptation.ollaMarginMinDb = -10;
cfg.phy.linkAdaptation.ollaMarginMaxDb = 10;
cfg.phy.linkAdaptation.feedbackDelaySlots = 2;
cfg.phy.csi.feedbackDelaySlots = 2;
cfg.runtime.link_adaptation = struct( ...
    "Mode", "amc", "DLPolicy", "baseline", "ULPolicy", "baseline", ...
    "MaximumMCSIndex", 10, "InitialMCSIndex", 0);
cfg.mac.scheduler.type = "rr";
cfg.phy.tddTiming = struct( ...
    "allowedK0", 1, "pdcchToPDSCHK0", 1, ...
    "dlHARQFeedbackK1Candidates", 2, ...
    "k1SelectionPolicy", "first_valid_configured", ...
    "allowedK2", 1, "pdcchToPUSCHK2", 1, "ulGrantK2", 1, ...
    "capabilityProfileID", "38.214-v18.8.0-cap1-dmrs-pos0-mu1", ...
    "n1PDSCHProcessingTimeSymbols", 10, ...
    "n2PUSCHPreparationTimeSymbols", 12, ...
    "timingAdvanceTicks", 0);
cfg = sixgr.config.normalizeConfig(cfg);
% Rebuild the immutable frame/timing context after the fixture overrides
% K0/K1/K2.  This is the same production ordering used by YAML expansion:
% normalize values first, then freeze the authoritative timing catalog.
if isfield(cfg.phy, "frameStructure")
    cfg.phy = rmfield(cfg.phy, "frameStructure");
end
if isfield(cfg, "resolved_runtime_view") && ...
        isfield(cfg.resolved_runtime_view, "frame_structure")
    cfg.resolved_runtime_view = rmfield( ...
        cfg.resolved_runtime_view, "frame_structure");
end
if isfield(cfg.phy, "frame")
    cfg.phy = rmfield(cfg.phy, "frame");
end
cfg = sixgr.phy.frame.FrameRuntimeStateBuilder.attachTimingContext(cfg);
sixgr.config.validateConfig(cfg);
end

function localAssertFeedbackTimeline(T, label, grantT)
assert(istable(T) && height(T) > 0, ...
    "%s CQI timeline must contain receiver measurements. %s", ...
    label, localGrantReceiverDiagnostic(grantT, label));
assert(all(double(T.AvailableTTI) - double(T.SourceTTI) == 2), ...
    "%s CQI timeline must enforce the exact configured delay.", label);
assert(all(isfinite(double(T.PostEqSINR_dB))) && ...
    all(double(T.WidebandCQI) >= 0 & double(T.WidebandCQI) <= 15), ...
    "%s CQI timeline must contain finite receiver SINR and valid CQI.", label);
assert(all(~contains(lower(string(T.PostEqSINRSource)), ...
    ["configured","system_level","proxy","fallback","evm"])), ...
    "%s CQI timeline must not contain configured/proxy SINR.", label);
end

function text = localGrantReceiverDiagnostic(T, label)
text = "No grant diagnostics available.";
if ~istable(T) || height(T) == 0 || ...
        ~ismember("Direction", string(T.Properties.VariableNames))
    return;
end
direction = "DL";
if contains(upper(string(label)), "UL")
    direction = "UL";
end
rows = upper(string(T.Direction)) == direction;
if ~any(rows)
    text = direction + " grant rows=0.";
    return;
end
source = localDiagnosticColumn(T, "PostEqSINRSource", rows);
role = localDiagnosticColumn(T, "PostEqSINRValueRole", rows);
ce = localDiagnosticColumn(T, "ChannelEstimateAvailable", rows);
eq = localDiagnosticColumn(T, "EqualizationAvailable", rows);
status = localDiagnosticColumn(T, "PostEqSINRValueStatus", rows);
sinr = localDiagnosticColumn(T, "PostEqSINR_dB", rows);
text = sprintf(["%s grant rows=%d; source=%s; role=%s; status=%s; " + ...
    "CE=%s; EQ=%s; SINR=%s."], direction, nnz(rows), source, role, ...
    status, ce, eq, sinr);
end

function value = localDiagnosticColumn(T, name, rows)
if ~ismember(name, string(T.Properties.VariableNames))
    value = "<missing>";
    return;
end
raw = T.(char(name));
raw = raw(rows, :);
if isnumeric(raw) || islogical(raw)
    value = mat2str(unique(double(raw(:))).');
else
    value = char(strjoin(unique(string(raw(:))), "|"));
end
end

function T = localRead(pathStr)
opts = detectImportOptions(pathStr, "Delimiter", ",");
opts.VariableNamingRule = "preserve";
T = readtable(pathStr, opts);
end

function scfg = localScenarioConfig()
data = struct();
data.meta = struct("scenario_id", "unit_test_system_level_causal_cqi");
data.users = struct("execution_model", "slot_coupled_truth", ...
    "beam_selection_strategy", "runtime_best_beam_per_link");
data.traffic = struct("target_rate_mbps", NaN, "offered_load_mbps", NaN);
data.deployment_topology = struct("num_cells", 1, "num_ues", 1, ...
    "num_sites", 1, "num_sectors_per_site", 1, ...
    "layout_type", "hex_grid", "inter_site_distance", 500, "num_trps", 1);
data.antenna_and_array = struct("bs_array_geometry", "ULA", ...
    "ue_array_geometry", "ULA", "bs_num_antenna_elements", 1, ...
    "ue_num_antenna_elements", 1, "element_spacing_h", 0.5, ...
    "element_spacing_v", 0.5, "polarization", "single_pol");
scfg = sixgr.lls6g.config.ScenarioConfig(data, ...
    "ConfigPath", "unit_test_system_level_causal_cqi");
end
