function ok = testLLSStatisticalQualificationGate()
%TESTLLSSTATISTICALQUALIFICATIONGATE Functional control health is not science.

setup6GRSimToolkit("Verbose", false);
ctx = llsRootGateFixture("pass");
dlT = readtable(fullfile(ctx.Layout.AirInterfaceCSVDir,"dl_pdsch_trials.csv"), ...
    "VariableNamingRule","preserve");
ulT = readtable(fullfile(ctx.Layout.AirInterfaceCSVDir,"ul_pusch_trials.csv"), ...
    "VariableNamingRule","preserve");

prach = struct( ...
    "PRACHRequired",true, ...
    "PRACHStrictOk",true, ...
    "PRACHStatus","strict_prach_waveform_evidence_present", ...
    "PRACHStatisticallyQualified",false, ...
    "PRACHStatisticalStatus","NOT_EVALUATED");
pdcch = struct( ...
    "PDCCHRequired",false, ...
    "PDCCHStrictOk",false, ...
    "PDCCHStatisticallyQualified",false, ...
    "PDCCHStatisticalStatus","not_required");
verdict = struct( ...
    "Failures",strings(0,1), ...
    "CheckDetails",struct("PRACH",prach,"PDCCH",pdcch));

root = sixgr.truth.evaluateStrictAnchorStatus( ...
    ctx.RunFolder,ctx.ScenarioConfig,ctx.InternalConfig,verdict,dlT,ulT,struct());
assert(root.Status.StatisticalQualificationStatus == "NOT_EVALUATED" && ...
    ~root.Status.StatisticalQualificationOk, ...
    "An underpowered required PRACH campaign must remain statistically unresolved.");
assert(root.Status.StandardsConformanceStatus == "NOT_EVALUATED" && ...
    ~root.Status.StandardsConformanceOk, ...
    "Functional PRACH waveform health must not promote standards conformance.");
assert(~root.Status.PublicationQualified && ~root.Status.ResultOk, ...
    "Publication must fail closed while a mandatory statistical gate is unresolved.");
assert(isfile(fullfile(ctx.Layout.ReportCSVDir,"statistical_qualification_gate.csv")), ...
    "The statistical gate must publish a first-class audit artifact.");

% A functional PRACH scenario that explicitly does not request the
% false-alarm/missed-detection campaign must not claim statistical proof,
% but that unrequested campaign is not a publication blocker.
prach.PRACHStatisticalRequired = false;
verdict.CheckDetails.PRACH = prach;
rootOptional = sixgr.truth.evaluateStrictAnchorStatus( ...
    ctx.RunFolder,ctx.ScenarioConfig,ctx.InternalConfig,verdict,dlT,ulT,struct());
assert(rootOptional.Status.StatisticalQualificationStatus == ...
    "NOT_APPLICABLE" && rootOptional.Status.StatisticalQualificationOk, ...
    "An explicitly unrequested PRACH statistical campaign must be N/A.");
ok = true;
end
