function ok = testLLSHARQReplayCurrentGrantAuthority()
%TESTLLSHARQREPLAYCURRENTGRANTAUTHORITY Preserve current-slot grant authority on HARQ replay.

setup6GRSimToolkit("Verbose", false);

tmp = tempname;
mkdir(tmp);
cleanup = onCleanup(@() rmdir(tmp, "s")); %#ok<NASGU>

scenarioPath = fullfile(pwd, "simulator", "configs", "scenarios", ...
    "lls_mimo4x4_multiuser_beamformed_awgn_validation.yaml");
scenarioCfg = sixgr.lls6g.config.loadScenarioConfig(scenarioPath);
cfg = sixgr.lls6g.buildInternalConfig(scenarioCfg, fullfile(tmp, "run"));
multiUser = struct( ...
    "Enabled", true, ...
    "NumUsers", 1, ...
    "RNTIStart", 901, ...
    "ExecutionModel", "slot_coupled_truth");
state = sixgr.truth.CoupledTruthRuntime.initialize( ...
    cfg, fullfile(tmp, "run"), multiUser, struct(), 5);
state.CurrentServingIdx(:) = 1;
state.CurrentServingMetric_dBm(:) = -80;
state.CurrentSlot = 5;
state.CurrentFrame = 1;

rnti = double(multiUser.RNTIStart);
tbsBits = 256;
storedGrant = struct( ...
    "Direction", "DL", ...
    "UEIndex", 1, ...
    "RNTI", rnti, ...
    "ServingCell", 1, ...
    "Frame", 1, ...
    "Slot", 1, ...
    "MCS", 1, ...
    "MCSIndex", 1, ...
    "Modulation", "QPSK", ...
    "TargetCodeRate", 0.1171875, ...
    "CQIProvenance", "", ...
    "NumLayers", 2, ...
    "Layers", 2, ...
    "PRBSet", 0:3, ...
    "PRBs", 4, ...
    "SymbolAllocation", [2 10], ...
    "TransportBlockSize", tbsBits, ...
    "TBSBits", tbsBits, ...
    "TBSBytes", tbsBits / 8, ...
    "ExactPHYFeasibilityChecked", false, ...
    "ExactPHYFeasible", false, ...
    "DCI", struct("AuthorityMarker", "stored_stale_dci"), ...
    "ControlDecodeOk", false, ...
    "PDCCHGrantBindingOk", false, ...
    "PDCCHGrantDCIFieldsHash", "stored_hash", ...
    "PDCCHGrantFieldsHash", "stored_hash", ...
    "GrantReason", "new_data_mu_mimo", ...
    "MUMIMOEnabled", true, ...
    "MUMIMOGroupSize", 2, ...
    "MUMIMOGroupId", 9000001, ...
    "MUMIMOPairingStatus", "paired_shared_prb_spatial_multiplexing", ...
    "MUMIMOPairingMetricSource", "measured_srs_spatial_filter_leakage", ...
    "MUMIMOPairingMetricValue_dB", -40, ...
    "MUMIMOPairingWorstMetricValue_dB", -38, ...
    "MUMIMOPairingEvidenceSource", "causal_measured_srs_subspace_and_runtime_irc_covariance", ...
    "MUMIMOSpatialDesignEvidenceSource", "frozen_first_transmission_spatial_design", ...
    "MUMIMOSpatialFilterMatrixSHA256", repmat('a', 1, 64), ...
    "HARQTBContext", struct("OriginalNumLayers", 2, "TBSBits", tbsBits));

txp = state.DLHarq.allocate(rnti, 1, tbsBits / 8, "NewData", true);
storedGrant.HARQ = txp.HARQ;
state.DLHarq.onTx(rnti, double(txp.HARQ.HarqID), ...
    zeros(tbsBits, 1, "uint8"), storedGrant, 1);
state.DLHarq.onFeedback(rnti, double(txp.HARQ.HarqID), "NACK", ...
    "SourceSlot", 1, "FeedbackSlot", 5);
retx = state.DLHarq.peekRetx(rnti, 5);
assert(~isempty(retx), "Regression fixture must create a pending DL retransmission.");

currentGrant = storedGrant;
currentGrant.Frame = 1;
currentGrant.Slot = 5;
currentGrant.HARQ = retx.HARQ;
currentGrant.IsRetransmission = true;
currentGrant.Valid = true;
currentGrant.ExactPHYFeasibilityChecked = true;
currentGrant.ExactPHYFeasible = true;
currentGrant.ExactPHYFeasibilitySource = ...
    "SchedulerBase.finalizeExactPHYFeasibility";
currentGrant.ExactPHYInfeasibilityReason = "";
currentGrant.ExecutableTBSMode = "faithful_exact_resource_accounting";
currentGrant.DCI = struct("AuthorityMarker", "current_slot_dci");
currentGrant.ControlDecodeOk = true;
currentGrant.PDCCHGrantBindingRequired = true;
currentGrant.PDCCHGrantBindingOk = true;
currentGrant.PDCCHGrantBindingStatus = "matched";
currentGrant.PDCCHGrantDCIId = "current_dci_id";
currentGrant.PDCCHGrantDCIFieldsHash = "current_hash";
currentGrant.PDCCHGrantFieldsHash = "current_hash";
currentGrant.GrantContextId = "DL-C1-U1-R901-F1-S5";
currentGrant.GrantReason = "harq_retx";
currentGrant.MUMIMOEnabled = false;
currentGrant.MUMIMOGroupSize = 1;
currentGrant.MUMIMOGroupId = NaN;
currentGrant.MUMIMOPairingStatus = ...
    "retransmission_without_current_shared_mu_peer";
currentGrant.MUMIMOPairingMetricSource = "not_applicable_without_current_mu_peer";
currentGrant.MUMIMOPairingMetricValue_dB = NaN;
currentGrant.MUMIMOPairingWorstMetricValue_dB = NaN;
currentGrant.MUMIMOPairingEvidenceSource = "no_current_shared_prb_mu_peer";
currentGrant.PriorMUMIMOGroupId = storedGrant.MUMIMOGroupId;
currentGrant.PriorMUMIMOGroupSize = storedGrant.MUMIMOGroupSize;
currentGrant.PriorMUMIMOPairingEvidenceSource = ...
    storedGrant.MUMIMOPairingEvidenceSource;

[~, context] = sixgr.truth.CoupledTruthRuntime.buildTrialContextFromGrant( ...
    state, cfg, 1, "DL", currentGrant);
replayGrant = context.GrantSnapshot;

assert(logical(replayGrant.ExactPHYFeasibilityChecked) && ...
    logical(replayGrant.ExactPHYFeasible), ...
    "HARQ replay must retain the current scheduler's exact-PHY feasibility authority.");
assert(string(replayGrant.DCI.AuthorityMarker) == "current_slot_dci", ...
    "HARQ replay must use the current slot's DCI, not the stored first-transmission DCI.");
assert(logical(replayGrant.ControlDecodeOk) && ...
    logical(replayGrant.PDCCHGrantBindingOk), ...
    "HARQ replay must retain the current slot's decoded-PDCCH grant binding.");
assert(string(replayGrant.PDCCHGrantDCIFieldsHash) == "current_hash" && ...
    string(replayGrant.PDCCHGrantFieldsHash) == "current_hash", ...
    "HARQ replay must retain the matching current-slot DCI/grant hashes.");
assert(double(replayGrant.TBSBits) == tbsBits && ...
    numel(context.TransportBlockBits) == tbsBits, ...
    "HARQ replay must still retain the original stored transport block.");
assert(logical(sixgr.util.structGet(replayGrant.PHYGrant, ...
    "HARQProcessKey.IsRetransmission", false)), ...
    "HARQ replay must refreeze the PHY grant with retransmission HARQ context.");
assert(~logical(replayGrant.MUMIMOEnabled) && ...
    double(replayGrant.MUMIMOGroupSize) == 1 && ...
    isnan(double(replayGrant.MUMIMOGroupId)) && ...
    string(replayGrant.MUMIMOPairingStatus) == ...
        "retransmission_without_current_shared_mu_peer" && ...
    string(replayGrant.MUMIMOPairingEvidenceSource) == ...
        "no_current_shared_prb_mu_peer", ...
    "HARQ replay must use the current slot's SU/MU identity instead of resurrecting the first transmission's MU labels.");
assert(double(replayGrant.PriorMUMIMOGroupId) == storedGrant.MUMIMOGroupId && ...
    double(replayGrant.PriorMUMIMOGroupSize) == storedGrant.MUMIMOGroupSize && ...
    string(replayGrant.PriorMUMIMOPairingEvidenceSource) == ...
        string(storedGrant.MUMIMOPairingEvidenceSource), ...
    "Historical MU identity must survive only through explicit Prior* lineage fields.");
assert(string(replayGrant.MUMIMOSpatialDesignEvidenceSource) == ...
        "frozen_first_transmission_spatial_design" && ...
    string(replayGrant.MUMIMOSpatialFilterMatrixSHA256) == ...
        string(repmat('a', 1, 64)), ...
    "Current-slot MU identity reduction must not erase the frozen HARQ spatial design contract.");

% A current measured-CQI decision may be more conservative than the
% original transport block, but it cannot change an in-flight HARQ coding
% or spatial contract.  Run the production scheduler/runtime boundary far
% enough to reproduce the rank-one small-PRB guard that previously killed
% the rank-two WebGUI slice at slot 11.
cfgAdaptive = cfg;
cfgAdaptive.phy.pdsch.nLayers = 2;
cfgAdaptive.phy.pdsch.numLayers = 2;
cfgAdaptive.phy.pdsch.maxLayers = 2;
cfgAdaptive.phy.linkAdaptation.minPRBForWidebandCQIGrant = 24;
cfgAdaptive.phy.linkAdaptation.smallPRBWidebandCQIMCSFloor = 10;
cfgAdaptive.phy.linkAdaptation.smallPRBWidebandCQIGuardMCSIndex = 1;
cfgAdaptive.runtime.link_adaptation.MaximumMCSIndex = 27;
state.CfgMobility = cfgAdaptive;
state.LatestDLFeedback(1).Valid = true;
state.LatestDLFeedback(1).CQI = 5;
state.LatestDLFeedback(1).RI = 1;
state.LatestDLFeedback(1).MCSIndex = 1;
state.LatestDLFeedback(1).Modulation = "QPSK";
state.LatestDLFeedback(1).TargetCodeRate = 193 / 1024;
state.LatestDLFeedback(1).FeedbackSourceSignal = "CSI-RS";
state.LatestDLFeedback(1).MCSSelectionSource = "measured_runtime_cqi";
state.LatestDLFeedback(1).CQIProvenance = "measured_scheduler_csi_runtime_receiver_sinr";
state.LatestDLFeedback(1).MCSValueStatus = "measured_feedback_adapted";
state.LatestDLFeedback(1).SubbandSINRVector_dB = "";
state.LatestDLFeedback(1).AgedSubbandSINRVector_dB = "";
currentGrant.NumLayers = 2;
currentGrant.Layers = 2;
currentGrant.RI = 2;
currentGrant.RIUsed = 2;
currentGrant.Rank = 2;
currentGrant.RankIndicator = 2;
currentGrant.HARQTBContext = struct("OriginalNumLayers", 2, ...
    "TBSBits", tbsBits);
adaptedRetx = sixgr.truth.CoupledTruthRuntime.applyMeasuredFeedbackAMCToGrantRuntime( ...
    currentGrant, state.LatestDLFeedback(1), [], cfgAdaptive, "DL");
assert(double(adaptedRetx.NumLayers) == 2 && ...
    double(adaptedRetx.Layers) == 2 && ...
    double(adaptedRetx.MCSIndex) == double(currentGrant.MCSIndex) && ...
    string(adaptedRetx.Modulation) == string(currentGrant.Modulation), ...
    "Measured CQI/small-PRB policy must not mutate an in-flight HARQ operating point.");
[~, adaptiveReplay] = sixgr.truth.CoupledTruthRuntime.buildTrialContextFromGrant( ...
    state, cfgAdaptive, 1, "DL", currentGrant);
assert(double(adaptiveReplay.GrantSnapshot.NumLayers) == 2 && ...
    double(adaptiveReplay.GrantSnapshot.Layers) == 2, ...
    "Measured CQI/small-PRB policy must not rewrite a rank-two HARQ retransmission to rank one.");

% The throughput result rebuilds a compact HARQ grant after every physical
% transmission. Missing NumLayers used to be silently backfilled from the
% scheduler's rank-one template on the following replay.
snapshot = struct("Direction", "DL", "Layers", 2, ...
    "PHYGrant", adaptiveReplay.GrantSnapshot.PHYGrant);
snapshot = sixgr.link.finalizeHARQGrantSpatialSnapshot(snapshot, "DL");
assert(double(snapshot.NumLayers) == 2 && double(snapshot.Layers) == 2 && ...
    double(snapshot.TBSInputNumLayers) == 2, ...
    "A persisted HARQ snapshot must carry all rank aliases from the executed frozen PHY grant.");

% Execution commit must reduce all exported spatial aliases from the same
% actual waveform rank.  A prior defect updated precoder metadata while the
% scheduler trace retained rank one, making rank-two UL retransmissions look
% like single-layer transmissions in the WebGUI.
traceGrant = currentGrant;
traceGrant.Direction = "UL";
traceGrant.NumLayers = 1;
traceGrant.Layers = 1;
traceGrant.RIUsed = 1;
traceGrant.Rank = 1;
state = sixgr.truth.CoupledTruthRuntime.appendGrantTraceRuntime( ...
    state, traceGrant, "UL", struct());
executedGrant = traceGrant;
executedGrant.NumLayers = 2;
executedGrant.Layers = 2;
executedGrant.RI = 2;
executedGrant.RIUsed = 2;
executedGrant.Rank = 2;
executedGrant.RankIndicator = 2;
state = sixgr.truth.CoupledTruthRuntime.commitGrantExecution( ...
    state, 1, "UL", executedGrant);
assert(height(state.ULGrantTraceTable) == 1, ...
    "Regression fixture must retain one UL grant trace row.");
assert(double(state.ULGrantTraceTable.NumLayers(1)) == 2 && ...
    double(state.ULGrantTraceTable.Layers(1)) == 2 && ...
    double(state.ULGrantTraceTable.RIUsed(1)) == 2 && ...
    double(state.ULGrantTraceTable.Rank(1)) == 2, ...
    "Execution commit must synchronize NumLayers/Layers/RIUsed/Rank to the waveform rank.");

ok = true;
end
