function ok = testMIMOFrequencySelectiveSpatialSignature()
%TESTMIMOFREQUENCYSELECTIVESPATIALSIGNATURE Preserve opposing subcarriers.

setup6GRSimToolkit("Verbose", false);
h = complex(zeros(2, 1, 2, 1));
h(1, 1, :, 1) = reshape([1; 1], 1, 1, 2, 1);
h(2, 1, :, 1) = reshape([1; -1], 1, 1, 2, 1);

wideband = sixgr.phy.mimo.spatialSignatureFromChannelEstimate( ...
    h, "Rank", 1, "SubspaceMode", "dominant_scheduled_rank");
assert(isequal(size(wideband), [2 1]), ...
    "Legacy wideband reduction should expose one averaged direction.");

[complete, info] = sixgr.phy.mimo.spatialSignatureFromChannelEstimate( ...
    h, "Rank", 1, "SubspaceMode", "complete_detectable_subspace", ...
    "NoiseVariance", 1e-8, "NoiseMargin_dB", 6);
assert(isequal(size(complete), [2 2]) && info.RetainedRank == 2 && ...
    info.RawNumericalRank == 2 && info.SnapshotCount == 2, ...
    ["The complete signature must retain both orthogonal frequency-selective " ...
     "directions that cancel under wideband averaging."]);
assert(string(info.ReductionMode) == "receiver_frequency_time_snapshot_covariance", ...
    "The exported reduction mode must identify snapshot-covariance evidence.");
assert(string(info.WeightingMode) == ...
    "noise_debiased_measured_singular_value_weighted_subspace", ...
    ["Complete spatial evidence must preserve measured signal-mode energy " ...
     "after subtracting the measured estimator-noise covariance."]);

% FDD CSI-RS must expose the transmit-side right-singular subspace of the
% measured DL channel.  It is not the TDD SRS receive subspace and must not
% be conjugated again by the scheduler.
hFDD = complex(zeros(2, 1, 2, 2));
hFDD(1, 1, :, :) = reshape([1 0; 0 0.2], 1, 1, 2, 2);
hFDD(2, 1, :, :) = reshape([0.8 0; 0 0.1], 1, 1, 2, 2);
[txSignature, txInfo] = sixgr.phy.mimo.spatialSignatureFromChannelEstimate( ...
    hFDD, "Rank", 1, "SubspaceMode", "complete_detectable_subspace", ...
    "SpatialDomain", "transmitter", "NoiseVariance", 1e-8, ...
    "NoiseMargin_dB", 6);
assert(isequal(size(txSignature), [2 2]) && ...
    string(txInfo.SpatialDomain) == "transmitter" && ...
    string(txInfo.ReductionMode) == ...
        "transmitter_frequency_time_snapshot_covariance", ...
    "FDD CSI-RS must retain its measured transmit-domain subspace.");
localAssertTypedError(@()sixgr.phy.mimo.spatialSignatureFromChannelEstimate( ...
    hFDD, "SpatialDomain", "configured_precoder"), ...
    "sixgr:mimo:InvalidSpatialSignatureDomain");

% Wideband CSI selection must aggregate the receiver objective per
% frequency snapshot.  The two measured channels below have opposing
% phases; averaging complex H first would erase the second transmit-port
% energy and understate both PMI quality and CQI SINR.
Hsnap = complex(zeros(1,2,2));
Hsnap(:,:,1) = [1 1];
Hsnap(:,:,2) = [1 -1];
candidates = complex(zeros(2,1,2));
candidates(:,:,1) = [1;1] ./ sqrt(2);
candidates(:,:,2) = [1;-1] ./ sqrt(2);
[~, decision] = sixgr.phy.mimo.CodebookEngine.select( ...
    Hsnap,candidates,NoiseVariance=1);
expectedMetric = 0.5 * log2(3);
assert(abs(double(decision.SelectedMetric) - expectedMetric) < 1e-12 && ...
    double(decision.ChannelSnapshotCount) == 2 && ...
    string(decision.FrequencyAggregation) == ...
        "mean_per_snapshot_mutual_information", ...
    ["Frequency-selective CSI must average per-snapshot mutual " ...
     "information without complex-channel phase cancellation."]);
[condDb, condStatus, rankEstimate] = sixgr.mimo.channelConditionNumber(Hsnap);
assert(isfinite(condDb) && string(condStatus) == "valid" && rankEstimate == 2, ...
    "Frequency-selective condition diagnostics must use snapshot covariance.");
state = sixgr.phy.mimo.CSIMeasurementState( ...
    MeasurementID="frequency-selective-csirs",UEID="UE-1", ...
    ResourceType="NZP-CSI-RS",ResourceID="CSI-RS-0", ...
    ResourceOrdinal=0,Slot=0,MaxAgeSlots=8, ...
    ChannelEstimate=Hsnap,NoiseVariance=1, ...
    Provenance="measured_runtime_csirs_receiver_channel_and_noise");
assert(isequal(size(state.ChannelEstimate),[1 2 2]) && ...
    state.ChannelEstimateConvention == "rx_by_tx_by_snapshot" && ...
    strlength(state.Digest) == 64, ...
    "Immutable CSI state must retain, declare and hash the complete canonical snapshot stack.");
consumedSnapshots = sixgr.mimo.spatialSnapshotsFromMeasurementState(state);
assert(isequal(size(consumedSnapshots), [1 2 2]), ...
    "Canonical CSI-state consumption must not collapse the two transmit ports.");
[consumedCondDb, consumedCondStatus, consumedRank] = ...
    sixgr.mimo.channelConditionNumber(consumedSnapshots);
assert(isfinite(consumedCondDb) && consumedCondStatus == "valid" && ...
    consumedRank == 2, ...
    "Canonical CSI-state consumption must retain its measured two-mode spatial evidence.");

localAssertTypedError(@()sixgr.phy.mimo.spatialSignatureFromChannelEstimate( ...
    h, "Rank", 1, "SubspaceMode", "complete_detectable_subspace", ...
    "NoiseMargin_dB", 6), "sixgr:mimo:MissingSpatialSignatureNoiseVariance");
localAssertTypedError(@()sixgr.phy.mimo.spatialSignatureFromChannelEstimate( ...
    h, "Rank", 1, "SubspaceMode", "complete_detectable_subspace", ...
    "NoiseVariance", 1e-8), "sixgr:mimo:MissingSpatialSignatureNoiseMargin");
ok = true;
end

function localAssertTypedError(fn, expectedId)
try
    fn();
catch ME
    assert(string(ME.identifier) == string(expectedId), ...
        "Expected %s, received %s.", expectedId, ME.identifier);
    return;
end
error("testMIMOFrequencySelectiveSpatialSignature:MissingError", ...
    "Expected typed error %s.", expectedId);
end
