function ok = testCoupledTruthCSIReportSourceAuthority()
%TESTCOUPLEDTRUTHCSIREPORTSOURCEAUTHORITY Keep CSI producer labels truthful.

setup6GRSimToolkit("Verbose", false);
tmp = tempname;
mkdir(tmp);
cleanup = onCleanup(@() rmdir(tmp, "s")); %#ok<NASGU>

scenario = sixgr.lls6g.config.loadScenarioConfig(fullfile( ...
    "simulator", "configs", "scenarios", ...
    "lls_causal_access_to_data_wiring.yaml"));
cfg = sixgr.lls6g.buildInternalConfig(scenario, fullfile(tmp, "run"));
cfg.outputs.saveCSV = false;
cfg.outputs.saveMAT = false;
cfg.outputs.saveFigures = false;
cfg.phy.csirs.enable = true;
multiUser = struct("Enabled", true, "NumUsers", 1, "RNTIStart", 701, ...
    "ExecutionModel", "slot_coupled_truth");
state = sixgr.truth.CoupledTruthRuntime.initialize( ...
    cfg, fullfile(tmp, "runtime"), multiUser, struct(), 2);

state.CurrentSlot = 4;
dmrsRow = table(4, 10, 8.5, 1, 0, true, ...
    "receiver_post_equalization_sinr", ...
    "measured_post_equalization_scheduling_input", "OK", ...
    'VariableNames', {'Slot','WidebandCQI','SINR_dB','RIEstimate', ...
    'PMI','CRCPass','SINRSource','SINRValueRole','SINRValueStatus'});
state = sixgr.truth.CoupledTruthRuntime.enqueueCSIReportRuntime( ...
    state, 1, "DL", dmrsRow, cfg, table());
assert(string(state.PendingCSITable.SourceSignal(end)) == "PDSCH-DMRS", ...
    "A DL report without an observed CSI-RS producer must remain PDSCH-DMRS sourced.");

state.CurrentSlot = 5;
ulRow = dmrsRow;
ulRow.Slot(:) = 5;
state = sixgr.truth.CoupledTruthRuntime.enqueueCSIReportRuntime( ...
    state, 1, "UL", ulRow, cfg, table());
assert(string(state.PendingCSITable.SourceSignal(end)) == "PUSCH-DMRS", ...
    "An UL report without an observed SRS producer must remain PUSCH-DMRS sourced.");

state.CurrentSlot = 6;
csirsRow = table(true, true, true, 12, 2, 1, 3, 11.25, ...
    "received_csirs_post_equalization_sinr", ...
    "measured_reference_signal_scheduling_input", "OK", ...
    "nrCSIRSMeasurements_runtime_received_grid", ...
    'VariableNames', {'Observed','CSIMeasurementAvailable', ...
    'ChannelEstimateAvailable','CQI','RI','PMI','CRI','SINR_dB', ...
    'SINRSource','SINRValueRole','SINRValueStatus','MeasurementSource'});
csirsTrial = dmrsRow;
csirsTrial.Slot(:) = 6;
state = sixgr.truth.CoupledTruthRuntime.enqueueCSIReportRuntime( ...
    state, 1, "DL", csirsTrial, cfg, csirsRow);
assert(string(state.PendingCSITable.SourceSignal(end)) == "CSI-RS" && ...
    double(state.PendingCSITable.CQI(end)) == 12 && ...
    double(state.PendingCSITable.RI(end)) == 2 && ...
    double(state.PendingCSITable.PMI(end)) == 1 && ...
    double(state.PendingCSITable.CRI(end)) == 3, ...
    "Observed CSI-RS reports must preserve the receiver-owned CQI/RI/PMI/CRI values.");

refT = state.ReferenceSignalMeasurementTable;
assert(any(string(refT.SignalType) == "PDSCH-DMRS") && ...
    any(string(refT.SignalType) == "PUSCH-DMRS") && ...
    any(string(refT.SignalType) == "CSI-RS"), ...
    "Reference-signal evidence must preserve the actual producer signal for each report.");

ok = true;
end
