function ok = testCausalSpatialPortRankDependency()
%TESTCAUSALSPATIALPORTRANKDEPENDENCY Verify one YAML-owned spatial contract.

setup6GRSimToolkit("Verbose", false);
root = fileparts(fileparts(mfilename("fullpath")));
scenarioPath = fullfile(root, "simulator", "configs", "scenarios", ...
    "lls_causal_access_to_data_wiring.yaml");
scenario = sixgr.lls6g.config.loadScenarioConfig(scenarioPath);
cfg = sixgr.lls6g.buildInternalConfig(scenario, fullfile(tempdir, ...
    "sixgr_causal_spatial_port_rank_dependency"));

dlLayers = double(sixgr.util.structGet(cfg, "phy.pdsch.nLayers", NaN));
dlPorts = double(sixgr.util.structGet(cfg, "phy.pdsch.numPorts", NaN));
dlDMRSPorts = double(sixgr.util.structGet(cfg, ...
    "phy.pdsch.dmrs.portSet", []));
ulLayers = double(sixgr.util.structGet(cfg, "phy.pusch.nLayers", NaN));
ulPorts = double(sixgr.util.structGet(cfg, ...
    "phy.pusch.NumAntennaPorts", NaN));
ulDMRSPorts = double(sixgr.util.structGet(cfg, ...
    "phy.pusch.dmrs.portSet", []));
csiPorts = double(sixgr.util.structGet(cfg, "phy.csirs.nPorts", NaN));
csiWeights = sixgr.util.structGet(cfg, "phy.csirs.precoderMatrices", []);
ssbWeights = sixgr.util.structGet(cfg, "phy.ssb.precoderMatrices", []);

assert(dlLayers == 2 && dlPorts == 2 && ...
    isequal(dlDMRSPorts(:).', 0:1), ...
    "PDSCH rank, antenna-port and DM-RS-port authorities diverged.");
assert(ulLayers == 2 && ulPorts == 2 && ...
    isequal(ulDMRSPorts(:).', 0:1), ...
    "PUSCH rank, antenna-port and DM-RS-port authorities diverged.");
assert(csiPorts == 2 && isequal(size(csiWeights), [2 2]), ...
    "CSI-RS ports/codebook must span the same two-port DL subspace.");
assert(size(csiWeights, 1) == double(cfg.antenna.bs.numElements) && ...
    rank(double(csiWeights)) == 2, ...
    "CSI-RS codebook does not span the configured physical BS array.");
assert(isequal(size(ssbWeights), [4 2]) && ...
    all(abs(sum(abs(ssbWeights).^2,2) - 1) < 1e-12) && ...
    numel(unique(string(sixgr.util.structGet(cfg, ...
        "phy.ssb.precoderIDs", strings(0,1))))) == 4, ...
    "SSB must expose four distinct unit-power beams on two physical elements.");

[dlBeamCandidates, dlBeamInfo] = sixgr.phy.dl.pmiCodebookCandidates( ...
    cfg, dlLayers, dlPorts, "Mode", "type1_su_mimo");
assert(double(dlBeamInfo.NumBeams) == 8 && ~isempty(dlBeamCandidates), ...
    "The YAML-owned eight-beam DL data codebook was not materialized.");
assert(all(arrayfun(@(x) rank(double(x.W)) == dlLayers && ...
    isequal(size(x.W), [dlPorts dlLayers]), dlBeamCandidates)), ...
    "A DL PMI candidate cannot carry the configured rank over the logical ports.");

bs = sixgr.rf.AntennaArrayFactory.build(cfg, "bs", ...
    "signal", "pdsch", "numPorts", dlPorts, "numRFChains", 2);
ue = sixgr.rf.AntennaArrayFactory.build(cfg, "ue", ...
    "signal", "pusch", "numPorts", ulPorts, "numRFChains", 2);
assert(bs.NumElements == 2 && bs.NumPorts == dlPorts && ...
    bs.NumRFChains == 2 && isequal(size(bs.PortToElementMatrix), [2 2]));
assert(ue.NumElements == 2 && ue.NumPorts == ulPorts && ...
    ue.NumRFChains == 2 && isequal(size(ue.PortToElementMatrix), [2 2]));
assert(isequal(double(bs.ElementSpacing_lambda), [0.5 0.5]) && ...
    isequal(double(ue.ElementSpacing_lambda), [0.5 0.5]));

mimoAudit = sixgr.mimo.validateMIMOConfigStrict(cfg);
assert(all(mimoAudit.Pass), ...
    "Strict spatial validation failed: %s", ...
    strjoin(cellstr(mimoAudit.FailureReason(~mimoAudit.Pass)), "; "));

carrier = sixgr.phy.grid.makeCarrier(cfg);
[~, ~, pdsch] = sixgr.phy.grid.allocREsPDSCH(carrier, cfg);
assert(double(pdsch.NumLayers) == dlLayers && ...
    isequal(double(pdsch.DMRS.DMRSPortSet(:).'), dlDMRSPorts(:).'));
dlPrecoder = sixgr.phy.dl.resolvePDSCHPrecoding(pdsch, cfg, ...
    "FixedReferenceMode", false);
assert(double(dlPrecoder.NumLayers) == dlLayers && ...
    double(dlPrecoder.NumLogicalPorts) == dlPorts && ...
    isequal(size(dlPrecoder.MatrixLogicalPorts), [dlPorts dlLayers]));

[~, ~, pusch] = sixgr.phy.grid.allocREsPUSCH(carrier, cfg);
assert(double(pusch.NumLayers) == ulLayers && ...
    double(pusch.NumAntennaPorts) == ulPorts && ...
    isequal(double(pusch.DMRS.DMRSPortSet(:).'), ulDMRSPorts(:).'));
ulPrecoder = sixgr.phy.ul.resolvePUSCHPrecoding(pusch, cfg, ...
    "FixedReferenceMode", false);
assert(double(ulPrecoder.NumLayers) == ulLayers && ...
    double(ulPrecoder.NumLogicalPorts) == ulPorts && ...
    isequal(size(ulPrecoder.MatrixLogicalPorts), [ulPorts ulLayers]));

% Execute the production transmitters, not a synthetic mapper, and verify
% the actual layer, logical-port, DM-RS and waveform domains.
[dlTx, dlInfo] = sixgr.phy.dl.PDSCH_Tx(cfg, "CompactOutput", false);
assert(size(dlTx.PDSCHLayerSymbols, 2) == dlLayers && ...
    size(dlTx.PDSCHPortSymbols, 2) == dlPorts && ...
    size(dlTx.DMRSAntennaSymbols, 2) == dlPorts && ...
    size(dlTx.Grid, 3) == dlPorts && size(dlTx.Waveform, 2) == dlPorts);
assert(logical(dlInfo.CodewordLayerMapping.ActualLayersEqualGrantLayers));
assert(double(dlTx.CSIRSRuntimeEvent.ResourceEvents(1).LogicalPortCount) == csiPorts && ...
    double(dlTx.CSIRSRuntimeEvent.PhysicalPortCount) == bs.NumElements);

[ulTx, ulInfo] = sixgr.phy.ul.PUSCH_Tx(cfg, "CompactOutput", false);
assert(size(ulTx.PUSCHLayerSymbols, 2) == ulLayers && ...
    size(ulTx.PUSCHPortSymbols, 2) == ulPorts && ...
    size(ulTx.DMRSSymbols, 2) == ulLayers && ...
    size(ulTx.Grid, 3) == ulPorts && size(ulTx.Waveform, 2) == ulPorts);
assert(double(ulInfo.CodewordLayerMapping.NumLayers) == ulLayers && ...
    sum(double(ulInfo.CodewordLayerMapping.LayerCountPerCodeword)) == ulLayers);

% Exercise the production SSB transmitter. Four time-multiplexed SSBs are
% composed with four YAML-selected weight vectors onto the same two
% physical gNB elements. Beam count is therefore independent of rank and
% can exceed physical element count without creating extra spatial layers.
[ssbWaveform, ssbInfo, ssbTx] = sixgr.phy.dl.SSB_Tx( ...
    cfg, "NumSubframes", 2, "SSBIndex", 0);
assert(size(ssbWaveform,2) == bs.NumElements && ...
    double(ssbTx.NumTransmitAntennas) == bs.NumElements && ...
    string(ssbTx.WaveformDomain) == "physical_element_domain");
assert(all(logical(ssbTx.SSBBurstPlan.ActiveBitmap)) && ...
    numel(unique(string(ssbTx.SSBBurstPlan.PrecoderMatrixSHA256))) == 4);
assert(isstruct(ssbInfo) && isfield(ssbInfo,"SSBComposite") && ...
    logical(ssbInfo.SSBComposite.Composed) && ...
    double(ssbInfo.SSBComposite.ComponentCount) == 4);

fprintf(['Causal spatial contract: 4 SSB sweep beams and 8 DL data-codebook beams ' ...
    'over BS/UE 2 elements, 2 RF chains, 2 logical ports, rank 2, DM-RS [0 1], ' ...
    'CSI-RS 2-port and exact PDSCH/PUSCH layer-to-port waveforms PASS.\n']);
ok = true;
end
