function ok = testPersistedCompletedRunArtifactRegistration()
%TESTPERSISTEDCOMPLETEDRUNARTIFACTREGISTRATION Recovery replaces stale components.

setup6GRSimToolkit("Verbose", false);
runFolder = string(tempname);
mkdir(runFolder);
cleanup = onCleanup(@() localRemove(runFolder)); %#ok<NASGU>

runID = "persisted_contract_run";
executionID = "execution_persisted_contract_unit";
scfg = sixgr.lls6g.config.loadScenarioConfig( ...
    "simulator/configs/scenarios/master_sinr_sweep.yaml");
scfg = localApplySmokeOverlay(scfg);
scenarioID = string(scfg.ScenarioID);
configHash = string(scfg.ConfigHash);
n = 80;
base = table( ...
    [zeros(40,1); 10*ones(40,1)], repmat("AWGN", n, 1), ones(n,1), ...
    repmat(10, n, 1), repmat("64QAM", n, 1), ...
    [false(40,1); true(40,1)], repmat(scenarioID, n, 1), ...
    repmat(configHash, n, 1), repmat(runID, n, 1), ...
    repmat(executionID, n, 1), true(n,1), true(n,1), true(n,1), ...
    false(n,1), false(n,1), repmat("real_lls_evidence", n, 1), ...
    'VariableNames', ["ConfiguredSNR_dB","ChannelModelApplied", ...
    "Rank","MCSIndex","Modulation","CRCPass","ScenarioID", ...
    "ConfigHash","RunID","ExecutionID","FinalizedFlag", ...
    "CRCApplicable","DecodeAttempted","FallbackFlag", ...
    "PlaceholderFlag","TruthStatus"]);
ul = base;
ul.TransformPrecodingApplied = false(n,1);
ul.FrequencyHoppingApplied = false(n,1);
ul.FrequencyHoppingMode = repmat("none", n, 1);
result = struct("RefinalizedFromPersistedCompletedRun", true, ...
    "Link", struct("RawTrials", struct("DL", base, "UL", ul)));

cfg = sixgr.lls6g.buildInternalConfig(scfg, runFolder);
cfg.run.runTag = char(runID);

% A copied recovery tree may contain an older component schema. Successful
% finalization must atomically replace it rather than accepting it as input.
pdschDir = fullfile(runFolder, "components", "pdsch", "csv");
puschDir = fullfile(runFolder, "components", "pusch", "csv");
mkdir(pdschDir);
mkdir(puschDir);
sixgr.util.csvWriteTable(fullfile(pdschDir, "pdsch_bler_curve.csv"), ...
    table("stale", "STATISTICALLY_QUALIFIED", ...
    'VariableNames', {'Marker','Status'}));
sixgr.util.csvWriteTable(fullfile(puschDir, "pusch_bler_curve.csv"), ...
    table("stale", "STATISTICALLY_QUALIFIED", ...
    'VariableNames', {'Marker','Status'}));

registry = sixgr.artifact.EvidenceRegistry();
[coverage, identity] = ...
    sixgr.artifact.registerPersistedCompletedRunEvidence( ...
    registry, result, scfg, cfg, runID);
assert(identity.RunID == runID && identity.ExecutionID == executionID && ...
    identity.ConfigHash == configHash && ...
    identity.EvidenceOrigin == "persisted_completed_run_truth");
assert(all(coverage.EvidenceOrigin == "persisted_completed_run_truth"));
assert(all(coverage.Registered(coverage.Domain ~= "initial_access")));
[found, registeredDL, provenance] = registry.resolveTable( ...
    "pdsch", "base", "pdsch_bler_curve.csv");
assert(found && all(registeredDL.EvidenceOrigin == ...
    "persisted_completed_run_truth") && ...
    contains(provenance, "persisted_completed_run_truth"));

finalized = sixgr.artifact.finalizeRunFailClosed( ...
    runFolder, registry, scfg, identity);
assert(finalized.Ok && finalized.Status == "PASS" && ...
    finalized.CSVCount == 2 && finalized.RequiredFailureCount == 0, ...
    sprintf(["Persisted contract finalization failed: status=%s id=%s " + ...
    "message=%s contracts=%g failures=%g required=%g"], ...
    finalized.Status, finalized.ErrorIdentifier, finalized.ErrorMessage, ...
    finalized.ContractCount, finalized.FailureCount, ...
    finalized.RequiredFailureCount));
dl = readtable(fullfile(pdschDir, "pdsch_bler_curve.csv"), ...
    "TextType", "string", "VariableNamingRule", "preserve");
ulOut = readtable(fullfile(puschDir, "pusch_bler_curve.csv"), ...
    "TextType", "string", "VariableNamingRule", "preserve");
for T = {dl, ulOut}
    value = T{1};
    assert(~ismember("Marker", string(value.Properties.VariableNames)) && ...
        all(value.EvidenceOrigin == "persisted_completed_run_truth") && ...
        all(value.QualificationProfile == "diagnostic") && ...
        all(value.Status == "MEASURED") && ...
        ~any(value.PublicationQualificationRequested) && ...
        ~any(value.PublicationEligible), ...
        "Recovery must replace stale qualification rows with fail-closed persisted truth.");
end

bad = result;
bad.Link.RawTrials.UL.ExecutionID(:) = "execution_conflict";
localAssertTypedFailure(@() ...
    sixgr.artifact.registerPersistedCompletedRunEvidence( ...
    sixgr.artifact.EvidenceRegistry(), bad, scfg, cfg, runID), ...
    "sixgr:artifact:PersistedExecutionIdentityMismatch");
untrusted = rmfield(result, "RefinalizedFromPersistedCompletedRun");
localAssertTypedFailure(@() ...
    sixgr.artifact.registerPersistedCompletedRunEvidence( ...
    sixgr.artifact.EvidenceRegistry(), untrusted, scfg, cfg, runID), ...
    "sixgr:artifact:PersistedCompletedRunAuthorityRequired");

ok = true;
fprintf("PASS testPersistedCompletedRunArtifactRegistration: stale component " + ...
    "tables replaced from identity-bound persisted waveform truth.\n");
end

function scfg = localApplySmokeOverlay(base)
resolved = sixgr.util.mergeStruct(base.toStruct(), ...
    base.get("execution_scales.smoke.overlay"));
resolved = sixgr.lls6g.config.normalizeScenarioAliases(resolved, ...
    "SourceFiles", base.SourceFiles, "ConfigPath", base.ConfigPath);
sixgr.lls6g.config.validateScenarioConfig(resolved, ...
    "Kind", "scenario", "AllowPartial", false, ...
    "Context", "testPersistedCompletedRunArtifactRegistration smoke overlay");
configHash = sixgr.lls6g.config.hashResolvedScenario(resolved);
scfg = sixgr.lls6g.config.ScenarioConfig(resolved, ...
    "SourceFiles", base.SourceFiles, "ConfigPath", base.ConfigPath, ...
    "ConfigHash", configHash, "Kind", "scenario");
end

function localAssertTypedFailure(fn, identifier)
caught = "";
try
    fn();
catch cause
    caught = string(cause.identifier);
end
assert(caught == identifier, ...
    "Expected typed failure %s; observed %s.", identifier, caught);
end

function localRemove(pathValue)
if isfolder(pathValue)
    rmdir(pathValue, "s");
end
end
