function ok = testSharedDLActualCodeRateFeasibility()
% Reproduce the slot-48 nominal-TBS versus actual rate-matching boundary.
setup6GRSimToolkit('Verbose',false);
s = sixgr.lls6g.config.loadScenarioConfig(fullfile('simulator','configs', ...
    'scenarios','lls_tdd_5mhz_rank2_shared_awgn_20db.yaml'));
cfg = sixgr.lls6g.buildInternalConfig(s,tempname);
scheduler = sixgr.l2.mac.SchedulerPF(cfg,'Direction','DL');
g = struct('Direction','DL','RNTI',1,'Slot',47, ...
    'ScheduledAbsoluteSlot',47,'PRBSet',0,'SymbolAllocation',[2 12], ...
    'Modulation','64QAM','NumLayers',2,'TargetCodeRate',948/1024, ...
    'MCSIndex',28,'MCSTable','qam64_table1','Valid',true, ...
    'CQIUsed',15,'AMCMode','cqi_table','BufferBytesBefore',1414);
actual = scheduler.finalizeExactPHYFeasibility(g);
fprintf('SLOT48_FEASIBILITY TBS=%g G=%g nominalNRE=%g valid=%d\n', ...
    actual.TBSBits,actual.ExactAllocationCodedBitsG, ...
    actual.NREPerPRB,actual.Valid);
assert(actual.Valid && actual.MCSIndex == 27 && ...
    actual.CodedCapacityOriginalMCS == 28 && actual.NumLayers == 2, ...
    'Slot-48 AMC must choose the highest feasible MCS without changing rank.');
assert(actual.TBSBits == nrTBS('64QAM',2,1,138,actual.TargetCodeRate,0), ...
    'Slot-48 repair must use exact nominal nrTBS, not a proxy.');
assert(actual.ExactAllocationCodedBitsG == 1584, ...
    'Slot-48 reproduction must retain the actual reserved-resource budget.');
assert(~actual.Valid || actual.TBSBits/actual.ExactAllocationCodedBitsG <= 0.95, ...
    'test:SharedDLUnsafeInitialCodeRate', ...
    'An allocation that violates the existing HARQ initial-rate guard must not be issued as executable.');
assert(actual.ExactInitialCodeRateWithTBCRC <= 0.95 && ...
    actual.BufferBytesAfter == g.BufferBytesBefore-actual.TBSBytes);
assert(actual.RawCQIDerivedMCS == 28 && actual.CQIUsed == 15, ...
    'Keep the received CQI recommendation distinct from capacity backoff.');
% A feasible full-band, reference-quiet grant must not inherit a backoff
% from the earlier constrained allocation or the nominal sizing cache.
wide = g; wide.PRBSet = 0:24; wide.ScheduledAbsoluteSlot = 43; wide.Slot = 43;
wideResult = scheduler.finalizeExactPHYFeasibility(wide);
assert(wideResult.Valid && wideResult.MCSIndex == 28);
% A fixed-MCS request must be rejected, not silently adapted.
fixed = rmfield(g,{'CQIUsed','AMCMode'});
fixedResult = scheduler.finalizeExactPHYFeasibility(fixed);
assert(~fixedResult.Valid && ~fixedResult.ExactPHYFeasible && ...
    string(fixedResult.GrantBlocker) == 'initial_dl_code_rate_exceeds_actual_capacity');
ok = true;
end
