function ok = testPUCCHGrantDisposition()
%TESTPUCCHGRANTDISPOSITION Guard exact standalone/transfer/cancel semantics.

grants = table( ...
    ["g-transfer";"g-standalone";"g-cancel";"g-unresolved"], ...
    true(4,1), [false;true;false;false], [true;false;false;false], ...
    [true;false;false;false], [true;false;false;false], ...
    [true;false;false;false], [false;false;true;false], true(4,1), ...
    ["ctx-1";"";"";""], ...
    ["pusch_uci_feedback_applied";"standalone_pucch";"cancelled";"pending"], ...
    repmat("PASS",4,1), ...
    'VariableNames', {'PUCCHGrantId','GrantScheduledFlag','GrantExecutedFlag', ...
    'MultiplexedOnPUSCH','PUSCHUCIDecodeOk','UCIContentMatch', ...
    'RuntimeStateUpdated','CanceledAtSweepBoundary','FinalizedFlag', ...
    'PUSCHGrantContextId','PUCCHGrantState','Status'});
trials = table("g-standalone", true, true, true, true, true, false, false, ...
    'VariableNames', {'PUCCHGrantId','DetectionAttempted','DetectionUsable', ...
    'ReceiverUsable','PUCCHDecodeOk','UCIContentMatch','CRCApplicable','CRCPass'});

result = sixgr.truth.classifyPUCCHGrantDisposition(grants, trials);
assert(result.ScheduledCount == 4 && result.TransferredCount == 1 && ...
    result.StandaloneTrialCount == 1 && result.CancelledCount == 1 && ...
    result.UnresolvedCount == 1 && ~result.AllScheduledResolved, ...
    "Grant disposition must distinguish transfer, standalone decode, cancellation, and unresolved rows.");
assert(string(result.Rows.Disposition(1)) == "same_waveform_pusch_uci_decode_consumed" && ...
    string(result.Rows.Disposition(2)) == "matched_standalone_pucch_receiver_trial" && ...
    string(result.Rows.Disposition(3)) == "explicitly_finalized_cancellation", ...
    "Resolved feedback grants must preserve their exact causal disposition.");

allResolved = grants(1:3,:);
result = sixgr.truth.classifyPUCCHGrantDisposition(allResolved, trials);
assert(result.AllScheduledResolved && result.UnresolvedCount == 0, ...
    "A valid UCI-on-PUSCH transfer must not require a fake standalone PUCCH trial.");

badTransfer = grants(1,:);
badTransfer.PUSCHUCIDecodeOk = false;
result = sixgr.truth.classifyPUCCHGrantDisposition(badTransfer, table());
assert(~result.AllScheduledResolved && result.UnresolvedCount == 1, ...
    "A transfer reservation without receiver decode must fail closed.");

bundledGrants = grants(2:3,:);
bundledGrants.PUCCHGrantId = ["g-bundle-1";"g-bundle-2"];
bundledGrants.GrantExecutedFlag(:) = true;
bundledGrants.CanceledAtSweepBoundary(:) = false;
bundledGrants.PUCCHGrantState(:) = "waveform_observed_feedback_applied";
bundledTrials = trials;
bundledTrials.PUCCHGrantId = "pucchoccasion:due=14:ue=1";
bundledTrials.LogicalPUCCHGrantIdSet = "g-bundle-1|g-bundle-2|CSI:REPORT-1";
result = sixgr.truth.classifyPUCCHGrantDisposition(bundledGrants, bundledTrials);
assert(result.AllScheduledResolved && result.StandaloneTrialCount == 2 && ...
    all(result.Rows.StandalonePUCCHTrialMatched), ...
    ['A successfully decoded physical PUCCH occasion must resolve every ' ...
     'logical HARQ-ACK grant explicitly listed in its codebook identity set.']);

terminal = grants(4,:);
terminal.RightCensored = true;
terminal.CensorReason = "finite_runtime_horizon_reached";
terminal.Status = "RIGHT_CENSORED";
result = sixgr.truth.classifyPUCCHGrantDisposition(terminal, table());
assert(result.AllScheduledResolved && result.RightCensoredCount == 1 && ...
    string(result.Rows.Disposition) == "explicitly_finalized_right_censoring", ...
    ['A scheduled feedback occasion beyond the finite execution horizon ' ...
     'must be resolved by its explicit finalized right-censoring record.']);

terminal.FinalizedFlag = false;
result = sixgr.truth.classifyPUCCHGrantDisposition(terminal, table());
assert(~result.AllScheduledResolved && result.UnresolvedCount == 1, ...
    "An unfinalized right-censor marker must fail closed.");
ok = true;
end
