function ok = testLLSActiveIssueGateEvaluatedEmptyRegistry()
%TESTLLSACTIVEISSUEGATEEVALUATEDEMPTYREGISTRY Explicit zero-issue scans pass.

setup6GRSimToolkit("Verbose", false);
ctx = llsRootGateFixture("pass");
registryPath = fullfile(ctx.Layout.ReportCSVDir, "result_issue_registry.csv");
emptyRegistry = table('Size', [0 4], ...
    'VariableTypes', {'string','string','string','string'}, ...
    'VariableNames', {'issue_id','severity','issue_status','issue_category'});
sixgr.util.csvWriteTable(registryPath, emptyRegistry);

runId = "runtime_issue_scan_run";
ctx.InternalConfig = sixgr.util.structSet(ctx.InternalConfig, "run.runTag", runId);
configHash = string(sixgr.util.structGet(ctx.ScenarioConfig, "ConfigHash", ""));
receipt = table( ...
    runId, string(ctx.ScenarioConfig.scenario_id), configHash, "EVALUATED", 0, 11, 0, ...
    "sixgr.truth.exportLLSOutputCoverageArtifacts/localBuildResultIssueRegistry", ...
    "result_issue_registry_evaluation_v1", ...
    "DLTrials|ULTrials|DLGrants|ULGrants|PDCCHTrials|PUCCHGrants|PUCCHTrials|PRACHTrials|PBCHTrials|SRSTrials|ReceiverTrackingTrace", ...
    'VariableNames', {'RunId','ScenarioId','ConfigHash','EvaluationStatus','IssueRowCount', ...
    'SourceTableCount','RuntimeSourceRowCount','Evaluator','SchemaVersion','EvaluatedSources'});
sixgr.util.csvWriteTable(fullfile(ctx.Layout.ReportCSVDir, ...
    "result_issue_registry_evaluation.csv"), receipt);

sixgr.truth.evaluateLLSRuntimeTruthContract( ...
    ctx.RunFolder, ctx.ScenarioConfig, ctx.InternalConfig);
statusT = readtable(fullfile(ctx.Layout.ReportCSVDir, ...
    "result_status_summary.csv"), "VariableNamingRule", "preserve");
if ~logical(statusT.ActiveIssueGateOk(1))
    gateT = readtable(fullfile(ctx.Layout.ReportCSVDir, ...
        "active_issue_gate_summary.csv"), "VariableNamingRule", "preserve");
    disp(statusT(:, intersect(["ActiveIssueGateOk","IssueRegistryStatus", ...
        "IssueRegistryRowCount","IssueRegistryEvaluationValid","FailureReasons"], ...
        string(statusT.Properties.VariableNames), "stable")));
    disp(gateT);
end
assert(logical(statusT.ActiveIssueGateOk(1)));
assert(string(statusT.RunId(1)) == runId);
assert(string(statusT.IssueRegistryStatus(1)) == "PASS");
assert(double(statusT.IssueRegistryRowCount(1)) == 0);
assert(logical(statusT.IssueRegistryEvaluationValid(1)));
truthT = readtable(fullfile(ctx.Layout.ReportCSVDir, ...
    "truth_contract_summary.csv"), "VariableNamingRule", "preserve");
assert(string(truthT.IssueRegistryStatus(1)) == "PASS", ...
    "Truth summary must preserve the evaluated-empty issue-registry PASS state.");
assert(double(truthT.IssueRegistryRows(1)) == 0, ...
    "Truth summary must report zero evaluated issue rows without calling the registry missing.");

ok = true;
fprintf("PASS testLLSActiveIssueGateEvaluatedEmptyRegistry: explicit zero-issue scan accepted.\n");
end
