function ok = testPRACHRuntimeULDirectionAntennaContract()
%TESTPRACHRUNTIMEULDIRECTIONANTENNACONTRACT Guard PRACH UE->gNB channel binding.

scenarioPath = fullfile("simulator", "configs", "scenarios", "master_scenaio_all_file.yaml");
scfg = sixgr.lls6g.config.loadScenarioConfig(scenarioPath);
cfg = sixgr.lls6g.buildInternalConfig(scfg, tempname);
cfg = sixgr.config.normalizeConfig(cfg);

out = sixgr.link.runPRACHDetection(cfg, ...
    "SNR_dB", 18, ...
    "CanonicalSlot", 5, ...
    "PreambleIndex", 0);

assert(logical(out.Ok), "PRACH runtime detection must complete.");
assert(logical(out.Detected), "PRACH Msg1 must be detected at the high-SNR runtime anchor.");
assert(double(out.RxAntennaCount) == 64, ...
    "PRACH runtime must bind UL receiver to the configured 64-port gNB side.");
assert(logical(out.ChannelFadingApplied), "PRACH runtime must exercise the configured fading channel.");
assert(~contains(string(out.Notes), "runtime waveform column count"), ...
    "PRACH runtime must not bind the BS transmit antenna contract to the UL Msg1 waveform.");

multiUser = struct( ...
    "Enabled", true, ...
    "NumUsers", 2, ...
    "RNTIStart", 1, ...
    "ExecutionModel", "slot_coupled_truth");
state = sixgr.truth.CoupledTruthRuntime.initialize(cfg, tempname, multiUser, struct(), 1);
state.CurrentSlot = 5;
state.CurrentServingIdx(:) = 1;
[cfgRuntime, state] = sixgr.truth.CoupledTruthRuntime.applyUserContext(cfg, state, 1, "UL"); %#ok<ASGLU>

runtimeUEWaveformCols = double(sixgr.util.structGet(cfgRuntime, ...
    "lls6g.userContext.RuntimeUEAntenna.NumWaveformColumns", NaN));
runtimeBSWaveformCols = double(sixgr.util.structGet(cfgRuntime, ...
    "lls6g.userContext.RuntimeServingBSAntenna.NumWaveformColumns", NaN));
prachCfg = sixgr.rach.PRACHConfig(cfgRuntime);
assert(runtimeUEWaveformCols == 4, ...
    "Regression setup must include the WebGUI generic four-port UE physical runtime antenna view.");
assert(double(prachCfg.NumTxAntennas) == 4, ...
    "Regression setup must preserve the configured four-port PRACH waveform.");

outRuntime = sixgr.link.runPRACHDetection(cfgRuntime, ...
    "SNR_dB", 18, ...
    "CanonicalSlot", 5, ...
    "PreambleIndex", 0);

assert(logical(outRuntime.Ok), "PRACH runtime-context detection must complete.");
assert(logical(outRuntime.Detected), "PRACH runtime-context Msg1 must be detected.");
assert(double(outRuntime.RxAntennaCount) == runtimeBSWaveformCols, ...
    "PRACH runtime-context receiver must match the runtime gNB waveform-column contract.");
assert(~contains(string(outRuntime.Notes), "runtime waveform column count"), ...
    "PRACH runtime-context must use a PRACH-specific UE logical-port view.");

ok = true;
end
