function ok = testPDSCHReceiverWrongRNTI()
%TESTPDSCHRECEIVERWRONGRNTI Wrong assignment RNTI must not decode.

setup6GRSimToolkit("Verbose", false);
fixture = StrictPDSCHChainFixture.create(1);
tx = sixgr.pdsch.PDSCHTransmitter( ...
    fixture.TransportBlocks, fixture.Assignment, fixture.ResourcePlan, ...
    fixture.Carrier, fixture.ReferenceConfig, ...
    "PrecoderBundle", fixture.PrecoderBundle);
wrong = StrictPDSCHChainFixture.cloneAssignment( ...
    fixture.Assignment,"RNTI",double(fixture.Assignment.get("RNTI"))+1);
rx = sixgr.pdsch.PDSCHReceiver( ...
    tx.Waveform,wrong,fixture.ResourcePlan,fixture.Carrier, ...
    fixture.ReferenceConfig,fixture.ReceiverConfig, ...
    "CodingPlans",tx.CodingPlans, ...
    "PrecoderBundle",fixture.PrecoderBundle);
assert(~rx.CRCPass && rx.CRCError, ...
    "Wrong-RNTI reception must return a controlled CRC failure.");
fprintf("PDSCH strict RX wrong RNTI: controlled CRC failure pass\n");
ok = true;
end
