function tests = testQualificationRecovery
%TESTQUALIFICATIONRECOVERY Focused Phase-19 evaluator recovery contracts.
tests = functiontests(localfunctions);
end

function testQualificationArtifactResolver(testCase)
[root,profile,cleanup] = localResolverFixture(); %#ok<ASGLU>
resolver = sixgr.integration.qualification.ArtifactResolver.create( ...
    root,profile);
resolution = sixgr.integration.qualification.ArtifactResolver.resolve( ...
    resolver,"full_stack_run_manifest.csv");
verifyTrue(testCase,resolution.Resolved);
verifyEqual(testCase,resolution.ResolutionMethod,"MANIFEST_ARTIFACT_ID");
verifyEqual(testCase,resolution.RelativePath, ...
    "reports/csv/full_stack_run_manifest.csv");
verifyTrue(testCase,resolution.HashValid);
end

function testQualificationStringHashComparison(testCase)
hash = string(repmat('a',1,64));
T = table(hash,hash,'VariableNames', ...
    {'ExecutedYAMLSHA256','ResolvedYAMLSHA256'});
observed = localEvaluate("ExecutedYAMLSHA256",T);
expected = localEvaluate("ResolvedYAMLSHA256",T);
result = sixgr.integration.qualification.ValueComparator.compare( ...
    observed,expected,"SHA256_EQUAL",0);
verifyTrue(testCase,result.Passed);
verifyEqual(testCase,observed.Type,"SHA256");
end

function testQualificationNumericColumnResolution(testCase)
T = table(0,0,0,5,0,0,'VariableNames', ...
    {'IllegalFixedDirectionOverrideCount','InvalidDCIGrantCount', ...
    'FalseGrantCount','RequiredFormatsPassed','MismatchCount', ...
    'ConfiguredMeasurementSubstitutionCount'});
names = string(T.Properties.VariableNames);
for name = reshape(names,1,[])
    value = localEvaluate(name,T);
    verifyTrue(testCase,ismember(value.Type,["DOUBLE","INTEGER"]));
    verifyTrue(testCase,isnumeric(value.Value));
end

occupancy = table([true;true],["coreset_re_reservation";""], ...
    'VariableNames',{'CollisionFlag','ReservedReason'});
[adapted,trace] = sixgr.integration.qualification. ...
    EvidenceAdapterRegistry.adapt("resource_grid_occupancy.csv", ...
    occupancy,"IllegalCollisionCount",repmat("a",1,64));
verifyEqual(testCase,adapted.IllegalCollisionCount,1);
verifyEqual(testCase,trace.SourceColumns,"CollisionFlag|ReservedReason");
end

function testQualificationAggregateExpressions(testCase)
T = table(["PASS";"PASS"],[1;2],[1;3],[100;100], ...
    [0;1],[0;0],[0;0], ...
    'VariableNames',{'Status','A','B','CompletenessPct', ...
    'FailedTests','SkippedTests','BlockedTests'});
verifyEqual(testCase,localEvaluate("all(Status)",T).Value,"PASS");
verifyEqual(testCase,localEvaluate("all(isfinite(A))",T).Value,true);
verifyEqual(testCase,localEvaluate("max(A)",T).Value,2);
verifyEqual(testCase,localEvaluate("max(abs(A-B))",T).Value,1);
verifyEqual(testCase,localEvaluate("min(CompletenessPct)",T).Value,100);
verifyEqual(testCase,localEvaluate( ...
    "FailedTests+SkippedTests+BlockedTests",T).Value,1);
end

function testQualificationHighestLowestSNRSelectors(testCase)
T = table([-8;0;10],[.9;.4;.01], ...
    'VariableNames',{'SNR_dB','BLER'});
verifyEqual(testCase,localEvaluate("BLER(highestSNR)",T).Value,.01, ...
    "AbsTol",eps);
verifyEqual(testCase,localEvaluate("BLER(lowestSNR)",T).Value,.9, ...
    "AbsTol",eps);
T = [T;T(end,:)];
verifyError(testCase,@()localEvaluate("BLER(highestSNR)",T), ...
    "FULLSTACK:AmbiguousValueSelector");
end

function testQualificationMultiSourceDifferentSchemas(testCase)
root = string(tempname);
mkdir(root);
cleanup = onCleanup(@()rmdir(root,"s")); %#ok<NASGU>
mkdir(fullfile(root,"qualification_evidence","protocol"));
T1 = table(["R";"R"],["P1";"P2"],[0;0],["PASS";"PASS"], ...
    'VariableNames',{'RunID','PDUId','MismatchCount','Status'});
T2 = table("R","S1",4,0,0,"PASS", ...
    'VariableNames',{'RunID','StatusPDUId','ACK_SN','NACKCount', ...
    'MismatchCount','Status'});
path1=fullfile(root,"qualification_evidence","protocol", ...
    "rlc_pdu_encoding.csv");
path2=fullfile(root,"qualification_evidence","protocol", ...
    "rlc_status_pdus.csv");
writetable(T1,path1);
writetable(T2,path2);
profile=localProfileForFiles(root, ...
    ["rlc_pdu_encoding.csv";"rlc_status_pdus.csv"], ...
    ["qualification_evidence/protocol/rlc_pdu_encoding.csv"; ...
    "qualification_evidence/protocol/rlc_status_pdus.csv"]);
resolver=sixgr.integration.qualification.ArtifactResolver.create( ...
    root,profile);
contract=table("VAL-FIX","Protocol","SC-23", ...
    "rlc_pdu_encoding.csv|rlc_status_pdus.csv", ...
    "BitMismatchCount","0","EQUAL","0","count","true", ...
    "FULLSTACK:RLCMismatch","", ...
    'VariableNames',{'CheckID','Domain','SubcaseID','SourceCSV', ...
    'ObservedExpression','ExpectedExpression','Comparator', ...
    'Tolerance','Units','Required','FailureCode','Notes'});
[result,~,~,adapters]=sixgr.integration.qualification. ...
    MultiSourceValueEvaluator.evaluate(contract,resolver,"R",true);
verifyEqual(testCase,result.Status,"PASS");
verifyGreaterThanOrEqual(testCase,height(adapters),2);
end

function testQualificationMissingValueFailClosed(testCase)
root=string(tempname);
mkdir(root);
cleanup=onCleanup(@()rmdir(root,"s")); %#ok<NASGU>
profile=localProfileForFiles(root,"missing.csv", ...
    "reports/csv/missing.csv",false);
resolver=sixgr.integration.qualification.ArtifactResolver.create( ...
    root,profile);
contract=table("VAL-MISSING","Test","SC-00","missing.csv", ...
    "Count","0","EQUAL","0","count","true", ...
    "FULLSTACK:Missing","", ...
    'VariableNames',{'CheckID','Domain','SubcaseID','SourceCSV', ...
    'ObservedExpression','ExpectedExpression','Comparator', ...
    'Tolerance','Units','Required','FailureCode','Notes'});
[result,trace]=sixgr.integration.qualification. ...
    MultiSourceValueEvaluator.evaluate(contract,resolver,"R",true);
verifyEqual(testCase,result.Status,"FAIL");
verifyEqual(testCase,trace.FailureCode,"FULLSTACK:ValueSourceMissing");
end

function testQualificationComparatorTypes(testCase)
numericA=localEvaluate("A",table(1,'VariableNames',{'A'}));
numericB=localEvaluate("B",table(1.01,'VariableNames',{'B'}));
verifyTrue(testCase,sixgr.integration.qualification.ValueComparator. ...
    compare(numericA,numericB,"WITHIN_ABS_TOLERANCE",.02).Passed);
logicalValue=localEvaluate("true",table());
verifyTrue(testCase,sixgr.integration.qualification.ValueComparator. ...
    compare(logicalValue,logicalValue,"ALL_TRUE",0).Passed);
end

function testQualificationStatusHierarchy(testCase)
[profile,source,values,negatives,audit,regression] = ...
    localReductionFixture("FAIL");
[components,subcases] = sixgr.integration.qualification. ...
    QualificationStatusReducer.reduce(profile,"R",source,values, ...
    negatives,audit,regression);
verifyEqual(testCase,components.Status,"FAIL");
verifyEqual(testCase,subcases.Status,"FAIL");
verifyFalse(testCase,components.CorrectnessChecked);
end

function testQualificationFinalizationOrder(testCase)
[~,~,values,~,audit,regression] = localReductionFixture("PASS");
subcases=table("SC-00",true,"PASS", ...
    'VariableNames',{'SubcaseID','Executed','Status'});
components=table("COMP-1","PASS", ...
    'VariableNames',{'ComponentID','Status'});
publication=table("FAIL",'VariableNames',{'Status'});
acceptance=table("R",true,"FAIL", ...
    'VariableNames',{'RuleID','Required','Status'});
result=sixgr.integration.qualification. ...
    QualificationFinalizationCoordinator.assess( ...
    subcases,values,components,audit,publication,regression,acceptance);
verifyFalse(testCase,result.FinalManifestComplete);
verifyError(testCase,@()sixgr.integration.qualification. ...
    QualificationFinalizationCoordinator. ...
    assertCanWriteFinalManifest(result), ...
    "FULLSTACK:FinalizationIncomplete");
end

function testQualificationInterruptedRun(testCase)
[~,~,values,~,audit,regression] = localReductionFixture("PASS");
subcases=table(["SC-00";"SC-30"],[true;false],["PASS";"FAIL"], ...
    'VariableNames',{'SubcaseID','Executed','Status'});
components=table("COMP-1","PASS", ...
    'VariableNames',{'ComponentID','Status'});
publication=table("PASS",'VariableNames',{'Status'});
acceptance=table("R",true,"PASS", ...
    'VariableNames',{'RuleID','Required','Status'});
result=sixgr.integration.qualification. ...
    QualificationFinalizationCoordinator.assess( ...
    subcases,values,components,audit,publication,regression,acceptance);
verifyEqual(testCase,result.FinalStatus,"INTERRUPTED");
verifyFalse(testCase,result.PublicationComplete);
end

function testQualificationReadOnlyReevaluation(testCase)
[root,profile,cleanup] = localResolverFixture(); %#ok<ASGLU>
before=sixgr.integration.qualification.ArtifactResolver.create(root,profile);
sixgr.integration.qualification.ArtifactResolver.resolve( ...
    before,"full_stack_run_manifest.csv");
after=sixgr.integration.qualification.ArtifactResolver.create(root,profile);
verifyEqual(testCase,before.InventorySHA256,after.InventorySHA256);
verifyEqual(testCase,height(before.Files),height(after.Files));
end

function testQualificationReevaluationDeterminism(testCase)
T=table([1;2],[1;3],[-8;10],[.9;.01], ...
    'VariableNames',{'A','B','SNR_dB','BLER'});
expressions=["max(abs(A-B))","BLER(highestSNR)", ...
    "BLER(lowestSNR)"];
first=strings(numel(expressions),1);
second=first;
for index=1:numel(expressions)
    first(index)=localEvaluate(expressions(index),T).Digest;
    second(index)=localEvaluate(expressions(index),T).Digest;
end
verifyEqual(testCase,first,second);
end

function testPhase18ActualRunRegressionFixture(testCase)
root=fileparts(fileparts(mfilename("fullpath")));
fixture=fullfile(root,"tests","fixtures", ...
    "phase18_actual_20260728_04_minimal");
binding=readtable(fullfile(fixture,"reports","csv", ...
    "full_stack_config_binding.csv"),"TextType","string", ...
    "VariableNamingRule","preserve");
observed=localEvaluate("ExecutedYAMLSHA256",binding);
expected=localEvaluate("ResolvedYAMLSHA256",binding);
verifyTrue(testCase,sixgr.integration.qualification.ValueComparator. ...
    compare(observed,expected,"SHA256_EQUAL",0).Passed);
numeric=readtable(fullfile(fixture,"qualification_evidence", ...
    "frame","numeric_summary.csv"),"TextType","string", ...
    "VariableNamingRule","preserve");
verifyEqual(testCase,localEvaluate( ...
    "IllegalFixedDirectionOverrideCount",numeric).Value,0);
end

function value=localEvaluate(expression,T)
ast=sixgr.integration.qualification.ValueExpressionParser.parse(expression);
value=sixgr.integration.qualification.ValueExpressionEvaluator. ...
    evaluate(ast,T);
end

function [root,profile,cleanup]=localResolverFixture()
sourceRoot=fileparts(fileparts(mfilename("fullpath")));
fixture=fullfile(sourceRoot,"tests","fixtures", ...
    "phase18_actual_20260728_04_minimal");
root=string(tempname);
copyfile(fixture,root);
cleanup=onCleanup(@()rmdir(root,"s"));
profile=localProfileForFiles(root,"full_stack_run_manifest.csv", ...
    "reports/csv/full_stack_run_manifest.csv");
end

function profile=localProfileForFiles(root,names,relative,writeManifest)
if nargin<4,writeManifest=true;end
names=string(names(:));relative=string(relative(:));
artifactID="ART-FIX-"+compose("%03d",(1:numel(names))');
artifactType=repmat("CSV",numel(names),1);
domain=repmat("Fixture",numel(names),1);
evidence=repmat("RUNTIME_MEASURED_OR_DERIVED",numel(names),1);
registry=table(artifactID,domain,artifactType,names,evidence, ...
    'VariableNames',{'ArtifactID','Domain','ArtifactType','FileName', ...
    'EvidenceClass'});
profile=struct("SelectedArtifactRegistry",registry);
if writeManifest
    csvDir=fullfile(root,"reports","csv");
    if ~isfolder(csvDir),mkdir(csvDir);end
    hashes=strings(numel(names),1);
    for index=1:numel(names)
        hashes(index)=sixgr.integration.qualification. ...
            ArtifactResolver.fileHash(fullfile(root, ...
            replace(relative(index),"/",filesep)));
    end
    manifest=table(artifactID,names,relative,hashes, ...
        'VariableNames',{'ArtifactID','FileName','RelativePath','SHA256'});
    writetable(manifest,fullfile(csvDir, ...
        "full_stack_artifact_manifest.csv"));
end
end

function [profile,source,values,negatives,audit,regression]= ...
        localReductionFixture(valueStatus)
profile=struct();
profile.Preset="comprehensive_smoke";
profile.Components=table("COMP-1","Domain","Component","SC-00", ...
    "true","true","evidence.csv","","requirement","Results", ...
    "FULLSTACK:Component", ...
    'VariableNames',{'ComponentID','Domain','Component','SubcaseID', ...
    'MandatoryInComprehensiveSmoke','MandatoryInDeepAcceptance', ...
    'RequiredCSV','RequiredPNG','CorrectnessRequirement', ...
    'WebGUISection','FailureCode'});
profile.Subcases=table("SC-00","Fixture","Test","both","true", ...
    "1","1","fixture","evidence.csv","","Results", ...
    'VariableNames',{'SubcaseID','Name','Category','Direction', ...
    'Mandatory','ComprehensiveBudgetMinutes','DeepBudgetMinutes', ...
    'Description','RequiredCSV','RequiredPNG','WebGUISection'});
source=table("SC-00",true,'VariableNames',{'SubcaseID','Executed'});
values=table("VAL-1","SC-00",true,string(valueStatus), ...
    'VariableNames',{'CheckID','SubcaseID','Required','Status'});
negatives=table("NEG-1","SC-00",true,"PASS", ...
    'VariableNames',{'CaseID','SubcaseID','Mandatory','Status'});
audit=table("ART-1","evidence.csv","CSV",true, ...
    string(repmat('a',1,64)), ...
    true,true,true,true,"PASS", ...
    'VariableNames',{'ArtifactID','FileName','ArtifactType','Present', ...
    'SHA256','HashValid','SchemaValid','MinimumRowsValid', ...
    'SemanticValid','Status'});
regression=table("SUITE",1,0,0,0,0,1,"FAIL", ...
    'VariableNames',{'Suite','MandatoryTests','ExecutedTests', ...
    'PassedTests','FailedTests','SkippedTests','BlockedTests','Status'});
end
