function ok = testCoupledTruthOLLARetransmissionExclusion()
%TESTCOUPLEDTRUTHOLLARETRANSMISSIONEXCLUSION Keep HARQ retx out of OLLA.

setup6GRSimToolkit("Verbose", false, "RunToolboxChecks", false);

cfg = sixgr.config.defaultConfig();
cfg.phy.linkAdaptation.mode = "amc";
cfg.phy.linkAdaptation.dlPolicy = "baseline";
cfg.phy.linkAdaptation.ulPolicy = "baseline";
cfg.phy.linkAdaptation.outerLoopFlag = true;
cfg.phy.linkAdaptation.deltaMCSPolicy = "olla";
cfg.phy.linkAdaptation.ollaStepDown = 0.9;
cfg.phy.linkAdaptation.ollaStepUp = 0.1;
cfg.phy.linkAdaptation.ollaMarginMinDb = -10;
cfg.phy.linkAdaptation.ollaMarginMaxDb = 10;
cfg.phy.linkAdaptation.targetBLER = 0.1;

policy = sixgr.link.resolveOLLAConfig(cfg);
assert(abs(double(policy.ImpliedTargetBLER) - 0.1) < 1e-12 && ...
    abs(double(policy.ConfiguredTargetBLER) - 0.1) < 1e-12, ...
    "Configured OLLA steps must encode the declared target BLER exactly.");
badTargetCfg = cfg;
badTargetCfg.phy.linkAdaptation.targetBLER = 0.2;
try
    sixgr.link.resolveOLLAConfig(badTargetCfg);
    error("sixgr:test:ExpectedOLLATargetMismatch", ...
        "Mismatched OLLA target/steps must fail closed.");
catch ME
    assert(string(ME.identifier) == ...
        "sixgr:link:OLLATargetBLERStepMismatch", ...
        "Unexpected typed error for mismatched OLLA target/steps: %s", ...
        string(ME.identifier));
end

scheduler = sixgr.l2.mac.SchedulerRR(cfg, "Direction", "DL");
state = struct("CfgMobility", cfg, "NumUsers", 1, ...
    "DLSchedulers", {{scheduler}}, "ULSchedulers", {{}}, ...
    "DLLinkAdaptationState", {{struct()}}, ...
    "ULLinkAdaptationState", {{struct()}}, ...
    "SlotDuration_s", 5e-4);

% A data row may carry the decoder CRC alongside the CSI measurement, but
% that hidden field is not a delivered HARQ event. It may advance ILLA once
% the CSI report is delivered; it must not advance OLLA.
csiOnlyState = state;
csiReport = struct("CQI", 8, "RI", 1, "PMI", 0, "CRI", 0, ...
    "SINR_dB", -5, "DueSlot", 3, "SourceSlot", 1, ...
    "ServingCell", 1, "SINRSource", "receiver_post_equalization_sinr", ...
    "SINRValueRole", "measurement", "SINRValueStatus", "measured");
hiddenCRCRow = struct("CRCPass", false, "RV", 0, ...
    "IsRetransmission", false);
[csiOnlyState, adaptedCSI] = ...
    sixgr.truth.CoupledTruthRuntime.applyDeliveredCSIAdaptationRuntime( ...
    csiOnlyState, csiReport, 1, "DL", hiddenCRCRow);
assert(double(adaptedCSI.LinkAdaptationStateUpdateCount) == 1 && ...
    double(adaptedCSI.OLLAUpdateCount) == 0 && ...
    ~logical(adaptedCSI.OLLAFeedbackEligible) && ...
    string(adaptedCSI.OLLAFeedbackExclusionReason) == ...
    "no_ack_nack_feedback" && ...
    abs(double(csiOnlyState.DLLinkAdaptationState{1}.DeltaMCS)) < 1e-12, ...
    "Delivered CSI may update ILLA, but a colocated hidden CRC must not update OLLA.");

firstTransmissionNACK = localFeedback(false, 0, false, 7);
state = sixgr.truth.CoupledTruthRuntime.updateSchedulerAfterFeedbackRuntime( ...
    state, firstTransmissionNACK, "DL");
afterFirstTransmission = state.DLLinkAdaptationState{1};
assert(abs(double(afterFirstTransmission.DeltaMCS) + 0.9) < 1e-12 && ...
    afterFirstTransmission.OLLAUpdateCount == 1, ...
    "A first-transmission NACK must apply exactly one receiver-owned OLLA down-step.");
[schedulerDelta, schedulerCount] = scheduler.getOLLAMCSDelta(4101);
assert(schedulerDelta == 0 && schedulerCount == 0, ...
    "The coupled runtime must not maintain a duplicate scheduler-local OLLA state.");

retransmissionACK = localFeedback(true, 2, true, 11);
state = sixgr.truth.CoupledTruthRuntime.updateSchedulerAfterFeedbackRuntime( ...
    state, retransmissionACK, "DL");
afterRetransmission = state.DLLinkAdaptationState{1};
assert(abs(double(afterRetransmission.DeltaMCS) - double(afterFirstTransmission.DeltaMCS)) < 1e-12 && ...
    afterRetransmission.OLLAUpdateCount == 1, ...
    ["A retransmission ACK must not update first-transmission OLLA. " + ...
    "The coupled runtime must preserve RV and IsRetransmission at the scheduler boundary."]);

nextNewTransmissionACK = localFeedback(true, 0, false, 15);
state = sixgr.truth.CoupledTruthRuntime.updateSchedulerAfterFeedbackRuntime( ...
    state, nextNewTransmissionACK, "DL");
afterNextNewTransmission = state.DLLinkAdaptationState{1};
assert(abs(double(afterNextNewTransmission.DeltaMCS) + 0.8) < 1e-12 && ...
    afterNextNewTransmission.OLLAUpdateCount == 2, ...
    "A later first-transmission ACK must apply exactly one configured OLLA up-step.");

% The receiver-owned CQI/ILLA state and OLLA state have different update
% denominators. Every valid CQI can advance the adaptation state, but an
% RV>0/retransmission outcome must not be counted as an OLLA observation.
cfg.phy.linkAdaptation.innerLoopFlag = true;
firstMetrics = struct("CQI", 8, "RI", 1, "CRCPass", false, ...
    "RV", 0, "IsRetransmission", false);
[firstDecision, adaptationState] = sixgr.link.computeLinkAdaptationDecision( ...
    cfg, "DL", firstMetrics);
assert(firstDecision.OLLAFeedbackEligible && firstDecision.OLLAUpdateCount == 1, ...
    "First-transmission NACK must be explicitly eligible for receiver-owned OLLA.");
firstStateCount = double(firstDecision.StateUpdateCount);

retxMetrics = struct("CQI", 9, "RI", 1, "CRCPass", true, ...
    "RV", 2, "IsRetransmission", true);
[retxDecision, adaptationState] = sixgr.link.computeLinkAdaptationDecision( ...
    cfg, "DL", retxMetrics, "AdaptationState", adaptationState);
assert(double(retxDecision.StateUpdateCount) > firstStateCount && ...
    double(retxDecision.OLLAUpdateCount) == 1 && ...
    ~logical(retxDecision.OLLAFeedbackEligible) && ...
    string(retxDecision.OLLAFeedbackExclusionReason) == "harq_retransmission_feedback_excluded", ...
    ["A retransmission may update measured CQI/ILLA state, but must not " + ...
    "increment or move OLLA."]);

nextMetrics = struct("CQI", 9, "RI", 1, "CRCPass", true, ...
    "RV", 0, "IsRetransmission", false);
[nextDecision, ~] = sixgr.link.computeLinkAdaptationDecision( ...
    cfg, "DL", nextMetrics, "AdaptationState", adaptationState);
assert(nextDecision.OLLAFeedbackEligible && nextDecision.OLLAUpdateCount == 2, ...
    "The next first-transmission ACK must increment the independent OLLA counter.");

ok = true;
end

function row = localFeedback(ack, rv, isRetransmission, sourceSlot)
row = struct( ...
    "UEIndex", 1, ...
    "ServingCell", 1, ...
    "RNTI", 4101, ...
    "TBSBits", 2048, ...
    "Ack", logical(ack), ...
    "HarqID", NaN, ...
    "RV", double(rv), ...
    "IsRetransmission", logical(isRetransmission), ...
    "SourceSlot", double(sourceSlot));
end
