function ok = testMeasuredSINRCurveArtifacts()
%TESTMEASUREDSINRCURVEARTIFACTS Guard geometry-driven measured-SINR outputs.

setup6GRSimToolkit("Verbose", false);
tmp = tempname;
mkdir(tmp);
c = onCleanup(@() rmdir(tmp, "s")); %#ok<NASGU>

legacyFiles = {
    fullfile(tmp, "air_interface", "csv", "lls_snr_sweep.csv")
    fullfile(tmp, "air_interface", "csv", "live_link_snr_sweep.csv")
    fullfile(tmp, "reports", "csv", "per_sweep_comparison_tables.csv")
    };
for i = 1:numel(legacyFiles)
    sixgr.util.ensureDir(legacyFiles{i});
    writetable(table(1, 'VariableNames', {'Deprecated'}), legacyFiles{i});
end
localWriteLegacyAnalyticsFiles(tmp);

trialData = struct();
trialData.dl = localTrialTable("DL");
trialData.ul = localTrialTable("UL");
trialData.pbch = localPBCHTrialTable();
trialData.prach = localPRACHTrialTable();
trialData.srs = localSRSTrialTable();

res = sixgr.analytics.generateMeasuredSINRCurves(tmp, "unit", ...
    "TrialData", trialData, ...
    "ScenarioConfig", struct("global_radio_scope", struct("channel_bandwidth_hz", 100e6)), ...
    "BinCount", 6, ...
    "WriteKPISummary", true, ...
    "UpdateAnchorKPIs", true);
assert(logical(res.Ok), "Measured SINR curve generation did not report Ok=true.");

csvs = [
    "air_interface/csv/dl_measured_sinr_bler_curve.csv"
    "air_interface/csv/ul_measured_sinr_bler_curve.csv"
    "air_interface/csv/dl_measured_sinr_throughput_curve.csv"
    "air_interface/csv/ul_measured_sinr_throughput_curve.csv"
    "air_interface/csv/measured_sinr_distribution.csv"
    "air_interface/csv/distance_vs_sinr.csv"
    "air_interface/csv/lls_measured_sinr_summary.csv"
    "air_interface/csv/live_measured_sinr_summary.csv"
    "air_interface/csv/lls_kpi_summary.csv"
    "air_interface/csv/link_anchor_kpis.csv"
    "reports/csv/throughput_reconciliation.csv"
    "reports/csv/blerber_reconciliation.csv"
    "reports/csv/access_kpi_reconciliation.csv"
    "reports/csv/scheduler_kpi_reconciliation.csv"
    "reports/csv/latency_reconciliation.csv"
    "reports/csv/canonical_kpi_ledger.csv"
    ];
for i = 1:numel(csvs)
    p = fullfile(tmp, strrep(csvs(i), "/", filesep));
    assert(exist(p, "file") == 2, "Missing measured SINR CSV: %s", csvs(i));
    T = readtable(p, "VariableNamingRule", "preserve");
    assert(height(T) >= 1, "Measured SINR CSV is empty: %s", csvs(i));
    if contains(csvs(i), "measured_sinr") || contains(csvs(i), "distance_vs_sinr") || contains(csvs(i), "lls_kpi_summary")
        vars = string(T.Properties.VariableNames);
        assert(~any(vars == "ConfiguredSNR_dB"), "ConfiguredSNR_dB leaked into %s", csvs(i));
        assert(~any(vars == "AppliedAWGNSNR_dB"), "AppliedAWGNSNR_dB leaked into %s", csvs(i));
    end
end

for i = 1:numel(legacyFiles)
    assert(exist(legacyFiles{i}, "file") ~= 2, "Deprecated sweep artifact survived: %s", legacyFiles{i});
end

summary = readtable(fullfile(tmp, "air_interface", "csv", "lls_measured_sinr_summary.csv"), "VariableNamingRule", "preserve");
assert(all(isfinite(double(summary.SINR_median_dB))), "Measured SINR summary contains non-finite median SINR.");
assert(all(string(summary.KPIFormulaVersion) == "measured_posteq_sinr_v2"), "Unexpected measured SINR formula version.");

kpi = readtable(fullfile(tmp, "air_interface", "csv", "lls_kpi_summary.csv"), "VariableNamingRule", "preserve");
assert(all(logical(kpi.KPIReconciliationPass)), "KPI reconciliation did not pass for measured SINR summary.");

% Gross scheduled throughput counts retransmissions, while OfferedBits is
% unique queue input.  A failed first transmission followed by a retry can
% make gross throughput exceed offered throughput without violating bit
% conservation.  Goodput must remain bounded by both quantities.
tmpRetx = tempname;
mkdir(tmpRetx);
cleanupRetx = onCleanup(@() rmdir(tmpRetx, "s")); %#ok<NASGU>
retxTrials = trialData;
retxTrials.dl.OfferedBits = retxTrials.dl.GoodBits;
retxTrials.ul.OfferedBits = retxTrials.ul.GoodBits;
sixgr.analytics.generateMeasuredSINRCurves(tmpRetx, "harq_retx_unit", ...
    "TrialData", retxTrials, "ScenarioConfig", struct(), ...
    "BinCount", 3, "WriteKPISummary", true, ...
    "UpdateAnchorKPIs", false);
retxKpi = readtable(fullfile(tmpRetx, "air_interface", "csv", ...
    "lls_kpi_summary.csv"), "VariableNamingRule", "preserve");
assert(all(logical(retxKpi.KPIReconciliationPass)) && ...
    any(double(retxKpi.Throughput_Mbps) > ...
        double(retxKpi.OfferedThroughput_Mbps)), ...
    ["HARQ retransmission overhead must not fail KPI reconciliation when " ...
     "goodput remains bounded by gross scheduled and offered payload."]);

anchor = readtable(fullfile(tmp, "air_interface", "csv", "link_anchor_kpis.csv"), "VariableNamingRule", "preserve");
assert(~any(contains(string(anchor.Notes), "deferred")), "Anchor KPI notes still contain deferred status.");
requiredCases = ["CellSearch_MIB_SIB1","PRACH_Detection","DL_PDSCH_Throughput", ...
    "UL_PUSCH_Throughput","UL_SRS_ChannelEst","UL_LowPAPR"];
assert(all(ismember(requiredCases, string(anchor.Case))), "Measured SINR anchor KPIs must cover all six Prompt 7 cases.");
for caseName = requiredCases
    mask = strcmp(string(anchor.Case), caseName);
    assert(any(mask) && localAsLogical(anchor.Ok(find(mask, 1))), "Anchor case did not pass from runtime evidence: %s", caseName);
end
assert(all(string(anchor.KPIFormulaVersion) == "measured_posteq_sinr_v2"), "Anchor KPI formula version must be mode-neutral measured_posteq_sinr_v2.");

localAssertGateOk(tmp, "throughput_reconciliation.csv", "ThroughputReconciliationOk");
localAssertGateOk(tmp, "blerber_reconciliation.csv", "BlerBerReconciliationOk");
localAssertGateOk(tmp, "access_kpi_reconciliation.csv", "AccessKpiReconciliationOk");
localAssertGateOk(tmp, "scheduler_kpi_reconciliation.csv", "SchedulerKpiReconciliationOk");
localAssertGateOk(tmp, "latency_reconciliation.csv", "LatencyReconciliationOk");
localAssertGateOk(tmp, "canonical_kpi_ledger.csv", "CanonicalKpiLedgerOk");

% Canonical truth bundles use uppercase DL/UL fields. A zero extra
% ProcedureDelay_ms value must not mask a receiver-measured decode latency.
tmpUpper = tempname;
mkdir(tmpUpper);
cleanupUpper = onCleanup(@() rmdir(tmpUpper, "s")); %#ok<NASGU>
upperDL = localTrialTable("DL");
upperDL.ProcedureDelay_ms(:) = 0;
upperDL.DecodeLatency_ms = 2.5 * ones(height(upperDL), 1);
sixgr.analytics.generateMeasuredSINRCurves(tmpUpper, "uppercase_latency_unit", ...
    "TrialData", struct("DL", upperDL), ...
    "ScenarioConfig", struct(), ...
    "BinCount", 3, "WriteKPISummary", false, "UpdateAnchorKPIs", false);
latencyUpper = readtable(fullfile(tmpUpper, "reports", "csv", ...
    "latency_reconciliation.csv"), "VariableNamingRule", "preserve", "TextType", "string");
assert(abs(double(latencyUpper.MeanLatency_ms(1)) - 2.5) <= 1e-12 && ...
    string(latencyUpper.LatencyEvidenceSource(1)) == "DL.DecodeLatency_ms", ...
    "Receiver decode latency was masked by a zero extra procedure delay.");

% The MATLAB raster producer is retired. Runtime curve CSVs remain the
% authority and the post-run contract materializer owns every final PNG.
plots = sixgr.analytics.generateMeasuredSINRPlots(tmp, "unit", ...
    "MinimumTrialsPerBin", 1);
assert(logical(plots.Ok) && logical(plots.Suppressed) && isempty(plots.Plots), ...
    "The retired MATLAB measured-SINR raster API must emit no images.");
assert(strlength(string(plots.LineageCSV)) == 0, ...
    "Suppressed legacy rasters must not emit a false lineage CSV.");
assert(exist(fullfile(tmp, "reports", "csv", ...
    "measurement_sinr_plot_lineage.csv"), "file") ~= 2, ...
    "The obsolete measured-SINR plot lineage CSV must not return.");
localAssertRelabeledAnalytics(tmp);

% A configured AWGN SNR campaign and receiver-measured SINR analytics are
% two different axes over the same real trials. Generating the latter must
% not erase the former or change its bytes.
tmpSweep = tempname;
mkdir(tmpSweep);
cleanupSweep = onCleanup(@() rmdir(tmpSweep, "s")); %#ok<NASGU>
sweepPath = fullfile(tmpSweep, "air_interface", "csv", "lls_snr_sweep.csv");
sixgr.util.ensureDir(sweepPath);
sweepT = table([-10;0;10], [0.9;0.4;0.05], [0.1;12;31], ...
    'VariableNames', {'SNR_dB','DL_BLER','DL_Throughput_Mbps'});
sixgr.util.csvWriteTable(sweepPath, sweepT);
sweepHashBefore = localFileHash(sweepPath);
sixgr.analytics.generateMeasuredSINRCurves(tmpSweep, "unit_sweep", ...
    "TrialData", trialData, ...
    "ScenarioConfig", struct( ...
        "run", struct("noiseOperatingMode", "standalone_awgn_snr_argument"), ...
        "global_radio_scope", struct("channel_bandwidth_hz", 100e6)), ...
    "BinCount", 6, "WriteKPISummary", false, "UpdateAnchorKPIs", false);
assert(exist(sweepPath, "file") == 2 && ...
    localFileHash(sweepPath) == sweepHashBefore, ...
    ["Measured-SINR analytics must preserve the exact configured-SNR " ...
     "campaign CSV bytes in standalone AWGN sweep mode."]);

% A fixed-link calibration has no propagation geometry. It must still
% publish its aggregate measured-SINR distribution, while the distance
% scatter remains a truthful header-only non-applicable artifact.
tmpFixed = tempname;
mkdir(tmpFixed);
cleanupFixed = onCleanup(@() rmdir(tmpFixed, "s")); %#ok<NASGU>
fixedTrials = struct("dl", localTrialTable("DL"), ...
    "ul", localTrialTable("UL"));
fixedTrials.dl.UEIndex(:) = NaN;
fixedTrials.ul.UEIndex(:) = NaN;
fixedTrials.dl.PropagationDistance_m(:) = NaN;
fixedTrials.ul.PropagationDistance_m(:) = NaN;
fixedTrials.dl.FixedLinkCampaign = true(height(fixedTrials.dl), 1);
fixedTrials.ul.FixedLinkCampaign = true(height(fixedTrials.ul), 1);
sixgr.analytics.generateMeasuredSINRCurves(tmpFixed, "fixed_link_unit", ...
    "TrialData", fixedTrials, ...
    "ScenarioConfig", struct( ...
        "run", struct("fixedLinkCampaignOnly", true), ...
        "validation", struct("fixed_link_campaign", struct("enabled", true))), ...
    "BinCount", 6, "WriteKPISummary", false, ...
    "UpdateAnchorKPIs", false);
fixedDistribution = readtable(fullfile(tmpFixed, "air_interface", ...
    "csv", "measured_sinr_distribution.csv"), ...
    "VariableNamingRule", "preserve");
fixedDistance = readtable(fullfile(tmpFixed, "air_interface", ...
    "csv", "distance_vs_sinr.csv"), ...
    "VariableNamingRule", "preserve");
assert(height(fixedDistribution) >= 2 && ...
    all(isnan(double(fixedDistribution.UEIndex))), ...
    "Fixed-link aggregate measured-SINR distributions were not retained.");
assert(all(endsWith(string(fixedDistribution.SourceArtifact), ...
    "_fixed_link_campaign_trials.csv")), ...
    "Fixed-link derived tables must name their exact primary trial source.");
assert(height(fixedDistance) == 0, ...
    "AWGN fixed-link analytics must not fabricate propagation-distance rows.");
fixedLedger = readtable(fullfile(tmpFixed, "reports", "csv", ...
    "canonical_kpi_ledger.csv"), "VariableNamingRule", "preserve", "TextType", "string");
fixedAccess = readtable(fullfile(tmpFixed, "reports", "csv", ...
    "access_kpi_reconciliation.csv"), "VariableNamingRule", "preserve", "TextType", "string");
fixedScheduler = readtable(fullfile(tmpFixed, "reports", "csv", ...
    "scheduler_kpi_reconciliation.csv"), "VariableNamingRule", "preserve", "TextType", "string");
assert(localAsLogical(fixedLedger.CanonicalKpiLedgerOk(1)) && ...
    ~localAsLogical(fixedLedger.AccessKpiApplicable(1)) && ...
    ~localAsLogical(fixedLedger.SchedulerKpiApplicable(1)), ...
    "The fixed-link canonical KPI ledger must evaluate only in-scope waveform KPI gates.");
assert(~localAsLogical(fixedAccess.AccessKpiReconciliationOk(1)) && ...
    ~localAsLogical(fixedAccess.KPIApplicable(1)) && ...
    string(fixedAccess.EvaluationStatus(1)) == "not_applicable_fixed_link_campaign_only", ...
    "Fixed-link access evidence must remain false/not-applicable, never a fabricated pass.");
assert(~localAsLogical(fixedScheduler.SchedulerKpiReconciliationOk(1)) && ...
    ~localAsLogical(fixedScheduler.KPIApplicable(1)) && ...
    string(fixedScheduler.EvaluationStatus(1)) == "not_applicable_fixed_link_campaign_only", ...
    "Fixed-link scheduler evidence must remain false/not-applicable, never a fabricated pass.");

ok = true;
end

function hash = localFileHash(pathValue)
fid = fopen(pathValue, "rb");
assert(fid >= 0, "Unable to read the configured-SNR fixture.");
cleanupObj = onCleanup(@() fclose(fid)); %#ok<NASGU>
hash = string(sixgr.util.sha256Hex(fread(fid, inf, "*uint8")));
end

function localAssertGateOk(tmp, fileName, flagName)
path = fullfile(tmp, "reports", "csv", fileName);
assert(exist(path, "file") == 2, "Missing KPI reconciliation gate CSV: %s", fileName);
T = readtable(path, "VariableNamingRule", "preserve");
assert(ismember(flagName, string(T.Properties.VariableNames)), ...
    "Gate CSV %s is missing flag %s.", fileName, flagName);
assert(localAsLogical(T.(flagName)(1)), "KPI reconciliation gate did not pass: %s", flagName);
assert(ismember("KPIFormulaVersion", string(T.Properties.VariableNames)) && ...
    string(T.KPIFormulaVersion(1)) == "measured_posteq_sinr_v2", ...
    "Gate CSV %s must carry measured_posteq_sinr_v2.", fileName);
end

function localWriteLegacyAnalyticsFiles(tmp)
csvDir = fullfile(tmp, "analytics", "csv");
imgDir = fullfile(tmp, "analytics", "image");
sixgr.util.ensureFolder(csvDir);
sixgr.util.ensureFolder(imgDir);
legacy = [
    "contract__error-reliability-analytics__bler-vs-snr", "BLER vs SNR";
    "contract__throughput-goodput-spectral-efficiency-analytics__throughput-vs-snr", "throughput vs SNR"
    ];
for i = 1:size(legacy, 1)
    T = table(repmat(legacy(i, 2), 2, 1), [0; 1], [0.5; 0.25], ...
        'VariableNames', {'chart_name','SNR_dB','MetricValue'});
    writetable(T, fullfile(csvDir, legacy(i, 1) + ".csv"));
    imwrite(uint8(repmat(reshape([8 122 112], 1, 1, 3), 24, 32, 1)), ...
        fullfile(imgDir, legacy(i, 1) + ".png"));
end
end

function localAssertRelabeledAnalytics(tmp)
csvDir = fullfile(tmp, "analytics", "csv");
imgDir = fullfile(tmp, "analytics", "image");
specs = [
    "contract__error-reliability-analytics__bler-vs-snr", "contract__error-reliability-analytics__bler-vs-measured-sinr";
    "contract__throughput-goodput-spectral-efficiency-analytics__throughput-vs-snr", "contract__throughput-goodput-spectral-efficiency-analytics__throughput-vs-measured-sinr"
    ];
for i = 1:size(specs, 1)
    for stem = specs(i, :)
        csvPath = fullfile(csvDir, stem + ".csv");
        assert(exist(csvPath, "file") == 2, "Missing relabeled analytics CSV: %s", stem);
        T = readtable(csvPath, "VariableNamingRule", "preserve", "TextType", "string");
        assert(contains(lower(string(T.chart_name(1))), "measured") && ...
            ismember("PostEqSINR_dB", string(T.Properties.VariableNames)) && ...
            ~ismember("SNR_dB", string(T.Properties.VariableNames)), ...
            "Analytics CSV must be relabeled to measured PostEq SINR without SNR_dB injection axis: %s", stem);
        pngPath = fullfile(imgDir, stem + ".png");
        info = sixgr.visual.inspectVisualArtifactFile(pngPath);
        assert(exist(pngPath, "file") == 2 && string(info.actual_mime_type) == "image/png", ...
            "Missing valid relabeled analytics PNG: %s", stem);
    end
end
end

function T = localTrialTable(direction)
n = 12;
ue = repmat([1; 2], n / 2, 1);
slot = (0:n-1).';
sinr = linspace(-2, 18, n).';
crcPass = sinr > 2 | ue == 1;
goodBits = double(crcPass) .* 1000;
bitErrors = double(~crcPass) .* 40;
distance = 80 + ue .* 100 + slot .* 3;
T = table( ...
    repmat(string(direction), n, 1), ...
    slot, ...
    floor(slot ./ 20), ...
    ue, ...
    1000 + ue, ...
    repmat(18, n, 1), ...
    repmat(18, n, 1), ...
    sinr, ...
    localPostEqStatus(direction, n), ...
    true(n, 1), ...
    false(n, 1), ...
    false(n, 1), ...
    crcPass, ...
    goodBits, ...
    repmat(1200, n, 1), ...
    repmat(1000, n, 1), ...
    bitErrors, ...
    goodBits ./ 0.5e-3 ./ 1e6, ...
    repmat(1200, n, 1) ./ 0.5e-3 ./ 1e6, ...
    repmat(0.035, n, 1), ...
    repmat(10.2, n, 1), ...
    repmat(0.5, n, 1), ...
    distance, ...
    sinr - 1, ...
    sinr - 0.5, ...
    90 + distance * 0.02, ...
    repmat(4, n, 1), ...
    4 + mod(slot, 12), ...
    repmat("16QAM", n, 1), ...
    1 + mod(ue, 2), ...
    'VariableNames', {'Direction','Slot','Frame','UEIndex','RNTI','ConfiguredSNR_dB','AppliedAWGNSNR_dB', ...
    'PostEqSINR_dB','PostEqSINRValueStatus','FinalizedFlag','IsWarmupFrame','FallbackFlag','CRCPass', ...
    'GoodBits','OfferedBits','BitsCompared','BitErrors','Goodput_Mbps','OfferedThroughput_Mbps', ...
    'EVM_rms','PAPR_dB','ProcedureDelay_ms', ...
    'PropagationDistance_m','LargeScaleSINR_dB','ReceiverHestSINR_dB','AppliedPathloss_dB', ...
    'AppliedShadowFading_dB','MCS','Modulation','Layers'});
end

function status = localPostEqStatus(direction, n)
if strcmpi(string(direction), "UL")
    status = repmat("OK_decision_residual_bounded", n, 1);
else
    status = repmat("OK", n, 1);
end
end

function T = localPBCHTrialTable()
n = 4;
T = table((0:n-1).', zeros(n,1), repmat([1;2], n/2, 1), 65520 + (1:n).', ...
    true(n,1), linspace(8, 16, n).', repmat("PASS", n, 1), ...
    'VariableNames', {'Frame','Slot','UEIndex','RNTI','SIB1StrictOk','PostEqSINR_dB','Status'});
end

function T = localPRACHTrialTable()
n = 5;
T = table(zeros(n,1), (0:n-1).', ones(n,1), 65520 + (1:n).', ...
    true(n,1), false(n,1), false(n,1), 18 + (0:n-1).', repmat("PASS", n, 1), ...
    'VariableNames', {'Frame','Slot','UEIndex','RNTI','PreambleDetected','MissedDetection', ...
    'FalseAlarm','PeakToNoiseRatio_dB','Status'});
end

function T = localSRSTrialTable()
n = 6;
T = table(zeros(n,1), (0:n-1).', repmat([1;2], n/2, 1), 4660 + (1:n).', ...
    true(n,1), -12 + (0:n-1).' * 0.25, linspace(5, 15, n).', repmat("PASS", n, 1), ...
    'VariableNames', {'Frame','Slot','UEIndex','RNTI','DetectionSuccess','NMSE_dB','PostEqSINR_dB','Status'});
end

function tf = localAsLogical(value)
if islogical(value)
    tf = logical(value(1));
elseif isnumeric(value)
    tf = double(value(1)) ~= 0;
else
    token = lower(strtrim(string(value(1))));
    tf = token == "1" || token == "true" || token == "yes" || token == "pass";
end
end
