function ok = testSchedulerMUMIMOGrouping()
%TESTSCHEDULERMUMIMOGROUPING Validate causal shared-PRB PF grouping.

setup6GRSimToolkit("Verbose", false);

tmpRoot = string(tempname);
mkdir(tmpRoot);
cleanup = onCleanup(@()localRemoveTree(tmpRoot)); %#ok<NASGU>
scenarioPath = fullfile(pwd, "simulator", "configs", "scenarios", ...
    "webgui_sinr_sweep_64x4_mu_mimo_repair_slice.yaml");
scenario = sixgr.lls6g.config.loadScenarioConfig(scenarioPath);
cfg = sixgr.lls6g.buildInternalConfig(scenario, fullfile(tmpRoot, "run"));

% Four measured-CSI candidates are ordered equally by PF.  UE 2 shares
% UE 1's PMI, while UE 3 is the first compatible codebook candidate.  The
% scheduler must search beyond the two-user transmission cap and then cap
% the selected group at two transmitted users.
ue = localUEs([0 0 1 0], [10 10 10 10]);
muArch = sixgr.rf.AntennaArrayFactory.resolvePortArchitecture(cfg, "bs", ...
    "Signal", "PDSCH", "NumElements", 64, "NumPorts", 4, ...
    "NumRFChains", 4, "MinimumPorts", 4);
F = double(muArch.HybridElementToPortMatrix);
element = (0:63).';
qCorrelatedA = [exp(1i .* 2 .* pi .* element ./ 64), ...
    exp(1i .* 4 .* pi .* element ./ 64)] ./ sqrt(64);
qIndependent = [exp(1i .* 10 .* pi .* element ./ 64), ...
    exp(1i .* 14 .* pi .* element ./ 64)] ./ sqrt(64);
[qCorrelatedB, ~] = qr(0.65 .* qCorrelatedA + 0.75 .* qIndependent, 0);
rawLeakage_dB = 10 * log10(norm(qCorrelatedA' * qCorrelatedB, "fro")^2 / 2);
designed = sixgr.phy.mimo.designMeasuredMUMIMOPair( ...
    qCorrelatedA, qCorrelatedB, cfg, "DL", 2, 2);
assert(rawLeakage_dB > -15 && designed.Compatible && ...
    designed.WorstLeakage_dB <= -15 && ...
    designed.MinimumDesiredGainObserved_dB >= -30, ...
    "A correlated measured pair must pass only after executable block diagonalization, not by relabeling raw overlap.");
assert(isequal(abs(designed.HybridElementToPortMatrix) > 1e-14, abs(F) > 1e-14) && ...
    norm(abs(designed.HybridElementToPortMatrix) - abs(F), "fro") <= 1e-12 && ...
    norm(designed.HybridElementToPortMatrix - F, "fro") > 1e-3, ...
    "Measured DL MU design must alter only RF phases while retaining the configured subarray hardware contract.");
ulDesigned = sixgr.phy.mimo.designMeasuredMUMIMOPair( ...
    qCorrelatedA, qCorrelatedB, cfg, "UL", 2, 2);
assert(ulDesigned.Compatible && ...
    isequal(size(ulDesigned.Member1ReceiveCombiner), [64 2]) && ...
    ulDesigned.WorstLeakage_dB <= -15, ...
    "UL MU admission must bind a causal measured receive projection for the configured IRC path.");
ue(1).MUMIMOSpatialSignature = qCorrelatedA;
ue(2).MUMIMOSpatialSignature = ue(1).MUMIMOSpatialSignature;
ue(3).MUMIMOSpatialSignature = qCorrelatedB;
ue(4).MUMIMOSpatialSignature = ue(1).MUMIMOSpatialSignature;
ue = localBindMeasuredSpatialSignatures(ue, "DL", 0);
scheduler = sixgr.l2.mac.SchedulerPF(cfg, "Direction", "DL");
[grants, info] = scheduler.schedule(0, ue, ...
    struct("PRBSet", 0:23, "SymbolAllocation", [2 12]));
assert(numel(grants) == 2, ...
    "The configured two-user MU opportunity must emit exactly two grants.");
assert(isequal(sort(double([grants.RNTI])), [1 3]), ...
    "MU pairing must search the complete PF candidate set for a compatible measured-PMI peer.");
assert(all(double([grants.MUMIMOGroupSize]) == 2) && ...
    numel(unique(double([grants.MUMIMOGroupId]))) == 1 && ...
    all(string({grants.MUMIMOPairingStatus}) == ...
    "paired_shared_prb_spatial_multiplexing"), ...
    "Both grants must carry one exact shared-PRB MU group identity.");
assert(isequal(double(grants(1).PRBSet(:)), double(grants(2).PRBSet(:))) && ...
    isequal(double(grants(1).SymbolAllocation(:)), ...
    double(grants(2).SymbolAllocation(:))), ...
    "MU grants must occupy identical PRB and symbol resources.");
allDMRSPorts = [double(grants(1).DMRSPortSet(:).'), ...
    double(grants(2).DMRSPortSet(:).')];
assert(numel(unique(allDMRSPorts)) == 4 && ...
    numel(grants(1).DMRSPortSet) == 2 && numel(grants(2).DMRSPortSet) == 2, ...
    "Two rank-2 MU users must receive four disjoint logical DM-RS ports.");
frozen = arrayfun(@(g) logical(g.PHYGrant.IsFrozen) && ...
    strlength(string(g.PHYGrant.PrecodingState.SelectedMatrixSHA256)) > 0, grants);
assert(all(frozen), ...
    "Every MU member must be frozen independently after group finalization.");
assert(all(arrayfun(@(g) g.PHYGrant.AntennaArchitecture.NumLogicalPorts == 4 && ...
    isequal(size(g.PHYGrant.PrecodingState.MatrixLogicalPorts), [4 2]) && ...
    isequal(size(g.PHYGrant.PrecodingState.MatrixPhysicalPorts), [64 2]), grants)), ...
    "Two rank-2 DL members must freeze distinct 4-port baseband and 64-element physical precoders.");
assert(norm(ue(3).MUMIMOSpatialSignature.' * ...
    grants(1).PHYGrant.PrecodingState.MatrixPhysicalPorts, "fro") <= 1e-10 && ...
    norm(ue(1).MUMIMOSpatialSignature.' * ...
    grants(2).PHYGrant.PrecodingState.MatrixPhysicalPorts, "fro") <= 1e-10, ...
    "Frozen physical DL MU precoders must null the reciprocal peer SRS subspace.");
assert(all(string({grants.MUMIMOHybridRFDesignPolicy}) == ...
    "measured_srs_phase_only_subarray") && ...
    all(string(arrayfun(@(g) g.PHYGrant.PrecodingState.HybridRFDesignPolicy, ...
    grants, "UniformOutput", false)) == ...
    "measured_srs_phase_only_subarray"), ...
    "Scheduler and frozen PHY grants must bind the config-selected hybrid RF design policy.");
projectedMUConfig = sixgr.phy.grant.applyPHYGrantToConfig(cfg, grants(1).PHYGrant);
assert(isequal(double(projectedMUConfig.phy.pdsch.hybridElementToPortMatrix), ...
    double(grants(1).PHYGrant.PrecodingState.HybridElementToPortMatrix)) && ...
    string(projectedMUConfig.phy.pdsch.hybridElementToPortMatrixSHA256) == ...
    string(grants(1).PHYGrant.PrecodingState.HybridElementToPortMatrixSHA256), ...
    "Grant replay must apply the exact selected phase-only RF matrix, not reconstruct the static base matrix.");
assert(sixgr.phy.grant.resolveDLLogicalPortCount( ...
    projectedMUConfig, grants(1), grants(1).NumLayers) == 4, ...
    "An explicit four-port grant/configuration must outrank the two-layer capability ceiling.");
portPriorityCfg = projectedMUConfig;
portPriorityCfg.phy.maxDLLayers = 2;
portPriorityCfg.phy.pdsch.maxLayers = 2;
assert(sixgr.phy.grant.resolveDLLogicalPortCount( ...
    portPriorityCfg, struct(), 2) == 4, ...
    "Explicit phy.pdsch.numPorts must not be reduced to maxDLLayers during replay pruning.");
try
    invalidPortCfg = portPriorityCfg;
    invalidPortCfg.phy.pdsch.numPorts = 1;
    sixgr.phy.grant.resolveDLLogicalPortCount(invalidPortCfg, struct(), 2);
    error("testSchedulerMUMIMOGrouping:ExpectedLogicalPortFailure", ...
        "A logical-port declaration below the transmitted rank was accepted.");
catch ME
    assert(string(ME.identifier) == ...
        "sixgr:phy:grant:ConfiguredLogicalPortCountOutOfRange", ...
        "Invalid configured logical-port dimensions must fail with the typed contract error.");
end

% A frozen single-user signal matrix is a per-grant selection, not the
% immutable base RF architecture. The next two-user rank-2 opportunity must
% therefore design four logical ports from the role-level architecture.
staleSingleUserCfg = projectedMUConfig;
staleSingleUserCfg.phy.pdsch.hybridElementToPortMatrix = ...
    double(grants(1).PHYGrant.PrecodingState.HybridElementToPortMatrix(:, 1:2));
staleSingleUserCfg.phy.pdsch.hybridElementToPortMatrixSHA256 = char( ...
    sixgr.phy.mimo.MatrixContract.digest( ...
    staleSingleUserCfg.phy.pdsch.hybridElementToPortMatrix));
redesigned = sixgr.phy.mimo.designMeasuredMUMIMOPair( ...
    qCorrelatedA, qCorrelatedB, staleSingleUserCfg, "DL", 2, 2);
assert(redesigned.Compatible && ...
    isequal(size(redesigned.HybridElementToPortMatrix), [64 4]), ...
    "A previous 64x2 per-grant PDSCH matrix must not override the 64x4 base-array MU design.");

% Conversely, a malformed role-level matrix is authoritative configuration
% and must still fail loudly instead of being silently regenerated.
invalidBaseCfg = cfg;
invalidBaseCfg.rf.bs.hybridElementToPortMatrix = ...
    staleSingleUserCfg.phy.pdsch.hybridElementToPortMatrix;
try
    sixgr.phy.mimo.designMeasuredMUMIMOPair( ...
        qCorrelatedA, qCorrelatedB, invalidBaseCfg, "DL", 2, 2);
    error("testSchedulerMUMIMOGrouping:ExpectedBaseMatrixShapeFailure", ...
        "Malformed role-level base RF matrix was unexpectedly accepted.");
catch ME
    assert(string(ME.identifier) == ...
        "AntennaArrayFactory:ConfiguredHybridMatrixShapeMismatch", ...
        "A malformed authoritative base RF matrix must retain its typed shape error.");
end
decision = info.CandidateTable;
scheduledRNTI = sort(double(decision.RNTI(logical(decision.Scheduled))));
assert(isequal(scheduledRNTI(:).', [1 3]), ...
    "Candidate-decision truth must identify the same measured-CSI MU pair as the grants.");
pairedDecision = decision(logical(decision.Scheduled), :);
assert(all(pairedDecision.MUMIMOAdmissionEvaluated) && ...
    all(pairedDecision.MUMIMOAdmissionCompatible) && ...
    isequal(sort(double(pairedDecision.MUMIMOAdmissionPeerRNTI)), [1; 3]) && ...
    all(isfinite(double(pairedDecision.MUMIMOAdmissionWorstLeakage_dB))) && ...
    all(string(pairedDecision.MUMIMOAdmissionEvidenceSource) == ...
        "causal_measured_srs_reciprocity_phase_only_hybrid_and_frozen_baseband"), ...
    "Candidate-decision truth must expose the exact peer, leakage and measured-SRS evidence that admitted the MU pair.");
assert(all(double([grants.MUMIMOPairingMetricValue_dB]) <= -100) && ...
    all(string({grants.MUMIMOPairingEvidenceSource}) == ...
    "causal_measured_srs_reciprocity_phase_only_hybrid_and_frozen_baseband") && ...
    all(strlength(string({grants.MUMIMOSpatialFilterMatrixSHA256})) == 64), ...
    "MU grants must retain the measured executable spatial-filter evidence.");
assert(all(string({grants.MUMIMOSpatialDesignEvidenceSource}) == ...
    string({grants.MUMIMOPairingEvidenceSource})) && ...
    all(strlength(string({grants.HybridElementToPortMatrixSHA256})) == 64) && ...
    all(strlength(string({grants.BaseHybridElementToPortMatrixSHA256})) == 64), ...
    "Frozen filter authority and current MU pairing evidence must be independently digest-bound.");

% Receiver completion must not erase the exact frozen MU contract when the
% raw waveform trial is streamed. Conversely, MU annotation must not alter
% receiver-derived measurements.
trialT = table([12.5; 13.0], [true; false], ...
    'VariableNames', {'PostEqSINR_dB','CRCPass'});
annotatedT = sixgr.truth.annotateFrozenMUMIMOTrialEvidence(trialT, grants(1));
assert(isequal(annotatedT.PostEqSINR_dB, trialT.PostEqSINR_dB) && ...
    isequal(annotatedT.CRCPass, trialT.CRCPass), ...
    "Frozen MU evidence annotation must not overwrite receiver measurements.");
assert(all(annotatedT.MUMIMOEnabled) && ...
    all(annotatedT.MUMIMOGroupSize == grants(1).MUMIMOGroupSize) && ...
    all(annotatedT.MUMIMOGroupId == grants(1).MUMIMOGroupId) && ...
    all(annotatedT.MUMIMOPairingStatus == string(grants(1).MUMIMOPairingStatus)) && ...
    all(annotatedT.MUMIMOPairingMetricSource == string(grants(1).MUMIMOPairingMetricSource)) && ...
    all(annotatedT.MUMIMOPairingMetricValue_dB == grants(1).MUMIMOPairingMetricValue_dB) && ...
    all(annotatedT.MUMIMOPairingEvidenceSource == string(grants(1).MUMIMOPairingEvidenceSource)) && ...
    all(annotatedT.MUMIMOSpatialDesignEvidenceSource == string(grants(1).MUMIMOSpatialDesignEvidenceSource)) && ...
    all(annotatedT.HybridElementToPortMatrixSHA256 == string(grants(1).HybridElementToPortMatrixSHA256)) && ...
    all(annotatedT.PRBStart == min(grants(1).PRBSet)) && ...
    all(annotatedT.PRBCount == numel(unique(grants(1).PRBSet))) && ...
    all(annotatedT.SymbolStart == grants(1).SymbolAllocation(1)) && ...
    all(annotatedT.NumSymbols == grants(1).SymbolAllocation(2)), ...
    "Raw trials must preserve every exact MU pairing field from the frozen grant.");

% A different configured PMI without measured CQI is not causal MU
% evidence.  Bootstrap rows remain orthogonal SU grants rather than being
% forced into an MU label.
bootstrapUE = localUEs([0 1 2 3], [0 0 0 0]);
bootstrapScheduler = sixgr.l2.mac.SchedulerPF(cfg, "Direction", "DL");
bootstrapGrants = bootstrapScheduler.schedule(0, bootstrapUE, ...
    struct("PRBSet", 0:23, "SymbolAllocation", [2 12]));
assert(numel(bootstrapGrants) == 2 && ...
    all(double([bootstrapGrants.MUMIMOGroupSize]) == 1) && ...
    ~isequal(double(bootstrapGrants(1).PRBSet(:)), ...
    double(bootstrapGrants(2).PRBSet(:))), ...
    "Unmeasured bootstrap CQI must not be upgraded to shared-PRB MU execution.");

% Even valid CQI and different PMI values are insufficient without a
% measured spatial matrix.  This guards against restoring the former
% PMI-inequality proxy.
pmiOnlyUE = localUEs([0 1 2 3], [10 10 10 10]);
retxHARQ = sixgr.l2.mac.HARQEntity(cfg, "Direction", "DL", ...
    "NumProcesses", 4, "MaxRetx", 3);
pmiOnlyScheduler = sixgr.l2.mac.SchedulerPF(cfg, "Direction", "DL", ...
    "HARQ", retxHARQ);
pmiOnlyGrants = pmiOnlyScheduler.schedule(0, pmiOnlyUE, ...
    struct("PRBSet", 0:23, "SymbolAllocation", [2 12]));
assert(numel(pmiOnlyGrants) == 2 && ...
    all(double([pmiOnlyGrants.MUMIMOGroupSize]) == 1), ...
    "Different PMI indices without measured matrices must remain SU scheduling.");

% A numeric matrix is also insufficient when its provenance is configured,
% stale, or digest-invalid. This prevents executable/frozen beam matrices
% from being recycled as measured scheduler CSI.
invalidSourceUE = ue(1:2);
invalidSourceUE(1).MUMIMOSpatialSignatureSource = "executed_frozen_phy_grant_precoding_matrix";
invalidSourceUE(2).MUMIMOSpatialSignatureAgeSlots = cfg.phy.mimo.measurementMaxAgeSlots + 1;
invalidSourceScheduler = sixgr.l2.mac.SchedulerPF(cfg, "Direction", "DL");
[invalidSourceGrants, invalidSourceInfo] = invalidSourceScheduler.schedule(0, invalidSourceUE, ...
    struct("PRBSet", 0:23, "SymbolAllocation", [2 12]));
assert(~isempty(invalidSourceGrants) && ...
    all(~logical([invalidSourceGrants.MUMIMOEnabled])) && ...
    ~any(double([invalidSourceGrants.MUMIMOGroupSize]) > 1), ...
    "Non-SRS or stale spatial matrices must not authorize shared-PRB MU execution.");
invalidDecision = invalidSourceInfo.CandidateTable;
assert(any(invalidDecision.MUMIMOAdmissionEvaluated) && ...
    ~any(invalidDecision.MUMIMOAdmissionCompatible) && ...
    all(strlength(string(invalidDecision.MUMIMOAdmissionEvidenceSource( ...
        invalidDecision.MUMIMOAdmissionEvaluated))) > 0), ...
    "Rejected MU admission must retain the exact causal-provenance or age failure instead of appearing unevaluated.");

% Once causal SRS becomes available, two pending rank-2 retransmissions
% with the same allocation shape may share one opportunity. The TB, NDI,
% RV lineage, rank, and TBS stay immutable while a fresh measured spatial
% filter is frozen for the retransmission opportunity.
for grantIndex = 1:2
    original = pmiOnlyGrants(grantIndex);
    harqId = double(original.HARQ.HarqID);
    original.HARQTBContext = struct( ...
        "OriginalNumLayers", double(original.NumLayers), ...
        "TBSBits", double(original.TBSBits), ...
        "HARQProcessId", harqId, ...
        "NDI", logical(original.HARQ.NDI), ...
        "NDIEpoch", double(sixgr.util.structGet(original.HARQ, "NDIEpoch", 1)));
    payload = zeros(round(double(original.TBSBits)), 1, "uint8");
    pmiOnlyScheduler.HARQ.onTx(double(original.RNTI), harqId, ...
        payload, original, 0);
    pmiOnlyScheduler.HARQ.onFeedback(double(original.RNTI), harqId, ...
        "NACK", "SourceSlot", 0, "FeedbackSlot", 4);
end
retxUE = localUEs([0 1 2 3], [10 10 10 10]);
retxUE(1).MUMIMOSpatialSignature = F(:, 1:2);
retxUE(2).MUMIMOSpatialSignature = F(:, 3:4);
retxUE = localBindMeasuredSpatialSignatures(retxUE, "DL", 5);
retxGrants = pmiOnlyScheduler.schedule(5, retxUE, ...
    struct("PRBSet", 0:23, "SymbolAllocation", [2 12]));
assert(numel(retxGrants) == 2 && ...
    all(string({retxGrants.GrantReason}) == "harq_retx_mu_mimo") && ...
    all(logical([retxGrants.IsRetransmission])) && ...
    all(double([retxGrants.MUMIMOGroupSize]) == 2) && ...
    isequal(double(retxGrants(1).PRBSet(:)), double(retxGrants(2).PRBSet(:))), ...
    "Compatible pending HARQ TBs must execute as one measured shared-PRB MU retransmission group.");
for grantIndex = 1:2
    original = pmiOnlyGrants(grantIndex);
    replay = retxGrants([retxGrants.RNTI] == original.RNTI);
    assert(numel(replay) == 1 && replay.TBSBits == original.TBSBits && ...
        replay.NumLayers == original.NumLayers && replay.HARQ.NDI == original.HARQ.NDI && ...
        replay.HARQ.RV ~= original.HARQ.RV && ...
        replay.PHYGrant.HARQProcessKey.IsRetransmission, ...
        "MU retransmission grouping must preserve the original TB spatial/rate contract and advance only HARQ RV.");
end

% If only one member of an earlier MU group is pending, replay its frozen
% beam but clear all current shared-resource labels. Historical group
% identity is retained only in explicit Prior* fields.
singleRetxHARQ = sixgr.l2.mac.HARQEntity(cfg, "Direction", "DL", ...
    "NumProcesses", 4, "MaxRetx", 3);
singleRetxScheduler = sixgr.l2.mac.SchedulerPF(cfg, "Direction", "DL", ...
    "HARQ", singleRetxHARQ);
[singleOriginal, ~] = singleRetxScheduler.schedule(0, ue([1 3]), ...
    struct("PRBSet", 0:23, "SymbolAllocation", [2 12]));
assert(numel(singleOriginal) == 2 && all([singleOriginal.MUMIMOEnabled]));
original = singleOriginal(1);
harqId = double(original.HARQ.HarqID);
original.HARQTBContext = struct( ...
    "OriginalNumLayers", double(original.NumLayers), ...
    "TBSBits", double(original.TBSBits), ...
    "HARQProcessId", harqId, "NDI", logical(original.HARQ.NDI), ...
    "NDIEpoch", double(sixgr.util.structGet(original.HARQ, "NDIEpoch", 1)));
singleRetxScheduler.HARQ.onTx(double(original.RNTI), harqId, ...
    zeros(round(double(original.TBSBits)), 1, "uint8"), original, 0);
singleRetxScheduler.HARQ.onFeedback(double(original.RNTI), harqId, ...
    "NACK", "SourceSlot", 0, "FeedbackSlot", 4);
singleRetxUE = ue([1 3]);
singleRetxUE(2).DLBufferBytes = 0;
singleReplay = singleRetxScheduler.schedule(5, singleRetxUE, ...
    struct("PRBSet", 0:23, "SymbolAllocation", [2 12]));
singleReplay = singleReplay([singleReplay.RNTI] == original.RNTI);
assert(numel(singleReplay) == 1 && ~singleReplay.MUMIMOEnabled && ...
    singleReplay.MUMIMOGroupSize == 1 && isnan(singleReplay.MUMIMOGroupId) && ...
    string(singleReplay.MUMIMOPairingStatus) == ...
        "retransmission_without_current_shared_mu_peer" && ...
    string(singleReplay.MUMIMOPairingEvidenceSource) == ...
        "no_current_shared_prb_mu_peer" && ...
    singleReplay.PriorMUMIMOGroupSize == 2 && ...
    isfinite(singleReplay.PriorMUMIMOGroupId) && ...
    string(singleReplay.MUMIMOSpatialDesignEvidenceSource) == ...
        "causal_measured_srs_reciprocity_phase_only_hybrid_and_frozen_baseband", ...
    "An unpaired HARQ replay must not retain stale current MU execution labels.");

ok = true;
end

function ue = localUEs(pmi, cqi)
n = numel(pmi);
ue = repmat(struct( ...
    "RNTI", 0, ...
    "UEIndex", 0, ...
    "ServingCell", 1, ...
    "DLBufferBytes", 20000, ...
    "CQI", 0, ...
    "RI", 2, ...
    "PMI", 0, ...
    "CRI", 0, ...
    "MeasuredSINR_dB", 15, ...
    "FeedbackValid", true, ...
    "CausalFeedbackUsable", true, ...
    "MUMIMOSpatialSignature", [], ...
    "MUMIMOSpatialSignatureSHA256", "", ...
    "MUMIMOSpatialSignatureSource", "", ...
    "MUMIMOSpatialSignatureSourceSlot", NaN, ...
    "MUMIMOSpatialSignatureAgeSlots", NaN, ...
    "MUMIMOSpatialSignatureConsumerRuntimeSlot", NaN, ...
    "MUMIMOSpatialSignatureMeasurementDirection", "", ...
    "MUMIMOSpatialSignatureReciprocityMode", "", ...
    "MUMIMOSpatialSignatureValid", false, ...
    "HeadOfLineDelay_ms", 1), n, 1);
for index = 1:n
    ue(index).RNTI = index;
    ue(index).UEIndex = index;
    ue(index).CQI = cqi(index);
    ue(index).PMI = pmi(index);
end
end

function ue = localBindMeasuredSpatialSignatures(ue, direction, sourceSlot)
direction = upper(string(direction));
for index = 1:numel(ue)
    w = ue(index).MUMIMOSpatialSignature;
    if isempty(w)
        continue;
    end
    ue(index).MUMIMOSpatialSignatureSHA256 = char( ...
        sixgr.phy.mimo.MatrixContract.digest(w));
    ue(index).MUMIMOSpatialSignatureSource = ...
        "measured_srs_receiver_channel_estimate_dominant_rank_subspace";
    ue(index).MUMIMOSpatialSignatureSourceSlot = double(sourceSlot) + 1;
    ue(index).MUMIMOSpatialSignatureAgeSlots = 0;
    ue(index).MUMIMOSpatialSignatureConsumerRuntimeSlot = double(sourceSlot) + 1;
    ue(index).MUMIMOSpatialSignatureMeasurementDirection = "UL";
    if direction == "DL"
        ue(index).MUMIMOSpatialSignatureReciprocityMode = "tdd_reciprocity";
    else
        ue(index).MUMIMOSpatialSignatureReciprocityMode = "direct_ul_srs";
    end
    ue(index).MUMIMOSpatialSignatureValid = true;
end
end

function localRemoveTree(folder)
folder = char(string(folder));
if isfolder(folder)
    rmdir(folder, "s");
end
end
