function ok = testLLS700MHzFullTruthProfile()
%TESTLLS700MZFULLTRUTHPROFILE Keep the 700 MHz strict truth preset honest and fully enabled where supported.

setup6GRSimToolkit("Verbose", false);

scenarioPath = fullfile(pwd, "simulator", "configs", "scenarios", "lls_700mhz_20mhz_2x2_rank2_beam_truth.yaml");
scfg = sixgr.lls6g.config.loadScenarioConfig(scenarioPath);
cfg = sixgr.lls6g.buildInternalConfig(scfg, fullfile(tempdir, "lls_700mhz_profile_probe"));
resolvedProfile = sixgr.link.resolveMCSProfile(scfg.get("modulation.mcs_table"), scfg.get("modulation.dl_mcs_index"));

assert(any(lower(string(scfg.get("meta.tags"))) == "no-proxy"), ...
    "700 MHz truth preset must stay tagged as no-proxy.");
assert(string(scfg.get("link_adaptation.fixed_or_amc")) == "fixed", ...
    "700 MHz truth preset must sustain its configured nominal operating point by disabling adaptive AMC.");
assert(string(scfg.get("link_adaptation.rank_adaptation_policy")) == "fixed", ...
    "700 MHz truth preset must keep the configured rank fixed.");
assert(string(scfg.get("harq.validation_mode")) == "exercise", ...
    "700 MHz truth preset must exercise HARQ retransmissions.");
assert(logical(scfg.get("control.repetition_enabled")), ...
    "700 MHz truth preset must enable PDCCH repetition.");
assert(logical(scfg.get("control.detection_feedback_enabled")), ...
    "700 MHz truth preset must enable detection feedback.");
assert(logical(scfg.get("random_access.beam_clustering_enabled")) && logical(scfg.get("random_access.ro_clustering_enabled")), ...
    "700 MHz truth preset must enable supported clustering features.");
assert(string(scfg.get("energy_efficiency.sleep_state_model")) == "micro_sleep", ...
    "700 MHz truth preset must enable a nontrivial sleep-state model.");
assert(string(scfg.get("energy_efficiency.bandwidth_adaptation_mode")) == "bwp_like", ...
    "700 MHz truth preset must enable supported bandwidth adaptation.");
assert(~logical(scfg.get("ai_ml.fallback_enabled")), ...
    "700 MHz truth preset must explicitly disable AI fallback for strict no-proxy truth.");
assert(logical(scfg.get("sweeps_and_matrix.snr_sweep.enabled")), ...
    "700 MHz truth preset must enable the explicit SNR sweep.");
snrSweepValues = double(scfg.get("sweeps_and_matrix.snr_sweep.values_db"));
assert(isequal(snrSweepValues(:).', [-30, -20, -10, 0, 10, 20, 30, 40]), ...
    "700 MHz truth preset must use the standardized coarse truth SNR sweep [-30:10:40].");
assert(logical(sixgr.util.structGet(cfg, "run.noProxyTruthContract", false)), ...
    "Internal config must enforce the no-proxy truth contract.");
assert(logical(resolvedProfile.Valid), ...
    "700 MHz truth preset must resolve a valid NR MCS profile.");
assert(string(cfg.phy.pdsch.modulation) == string(resolvedProfile.Modulation) && ...
    abs(double(cfg.phy.pdsch.codeRate) - double(resolvedProfile.TargetCodeRate)) < 1e-9, ...
    "Internal config must derive the DL fixed-MCS modulation and code rate from the resolved NR MCS profile.");
assert(string(cfg.phy.pusch.modulation) == string(resolvedProfile.Modulation) && ...
    abs(double(cfg.phy.pusch.codeRate) - double(resolvedProfile.TargetCodeRate)) < 1e-9, ...
    "Internal config must derive the UL fixed-MCS modulation and code rate from the resolved NR MCS profile.");
assert(string(sixgr.util.structGet(cfg, "phy.harq.validationMode", "")) == "exercise", ...
    "Internal config must propagate HARQ exercise mode.");
assert(string(sixgr.util.structGet(cfg, "phy.linkAdaptation.mode", "")) == "fixed", ...
    "Internal config must propagate the fixed nominal operating point.");

ok = true;
end
