function ok = testQuickPlus20WiringGateYAMLAuthority()
%TESTQUICKPLUS20WIRINGGATEYAMLAUTHORITY Validate the bounded MU gate.

path = fullfile(pwd, "simulator", "configs", "scenarios", ...
    "webgui_sinr_plus20_2x2_mu_mimo_wiring_gate.yaml");
s = sixgr.lls6g.config.loadScenarioConfig(path);
sourceFiles = lower(replace(string(s.SourceFiles), "\", "/"));
assert(any(endsWith(sourceFiles, "/master_sinr_sweep.yaml")) && ...
    ~any(endsWith(sourceFiles, "/master_geometry_based.yaml")), ...
    "The quick SINR gate must inherit only the SINR master, never the geometry master.");
assert(string(s.get("canonical_control.integration.run_mode")) == ...
    "FIXED_SNR_SWEEP" && ...
    ~logical(s.get("canonical_control.launch.geometry_enabled")), ...
    "The executed gate must remain explicitly classified as SINR-sweep mode with geometry disabled.");

assert(double(s.get("canonical_control.topology.num_cells")) == 1);
assert(double(s.get("canonical_control.topology.num_ues")) == 2, ...
    "True MU-MIMO wiring requires at least two UEs.");
assert(double(s.get("antenna_and_array.bs_num_antenna_elements")) == 2);
assert(double(s.get("antenna_and_array.ue_num_antenna_elements")) == 2);
assert(double(s.get("canonical_control.mimo.n_layers")) == 1);
assert(double(s.get("canonical_control.pdsch.layer_count")) == 1 && ...
    double(s.get("canonical_control.pdsch.rank")) == 1, ...
    "The scheduler-owned canonical PDSCH rank must match the waveform rank.");
assert(double(s.get("canonical_control.pdsch.xoh_pdsch")) == 18 && ...
    double(s.get("pdsch.xoh_pdsch")) == 18 && ...
    double(s.get("pusch.xoh_pusch")) == 18, ...
    "Dense all-feature data allocations require explicit YAML xOverhead=18 in every authority alias.");
assert(logical(s.get("canonical_control.mimo.mu_mimo_enable")) && ...
    double(s.get("canonical_control.mimo.max_simultaneous_ue_dl")) == 2);
assert(string(s.get("canonical_control.mimo.mu_mimo_spatial_signature_mode")) == ...
    "dominant_scheduled_rank", ...
    ["The 2x2 MU gate must retain one measured SRS spatial dimension per " ...
     "rank-one scheduled UE so a second rank-one UE has a physical nulling dimension."]);
assert(double(s.get("canonical_control.run.total_slots")) == 30, ...
    ["The wiring gate must include the second UL occasion and close its " ...
     "K1=4 feedback lifecycle at slot 30."]);
assert(~logical(s.get("control_gating.pucch_required")) && ...
    logical(s.get("control_gating.pusch_uci_required")), ...
    "This scenario must require transferred PUSCH UCI without claiming standalone PUCCH.");
assert(isequal(double(s.get("canonical_control.run.seed_list")), 104729));
assert(isequal(double(s.get("sweeps_and_matrix.snr_sweep.values_db")), 20) && ...
    ~logical(s.get("sweeps_and_matrix.snr_sweep.enabled")));
assert(logical(s.get("canonical_control.random_access_evidence.require_runtime_stage_waveforms")) && ...
    logical(s.get("canonical_control.random_access_evidence.allow_runtime_stage_waveform_composition")));
assert(logical(s.get("pucch_resources.overlap_policy.uci_on_pusch_enabled")) && ...
    isequal(double(s.get("tdd_timing.dl_harq_feedback_k1")), 4) && ...
    double(s.get("pucch_resources.harq_ack.k1_slots")) == 4, ...
    ["The bounded all-feature gate must causally align K1=4 HARQ-ACK " ...
     "with its PUSCH occasion and enable UCI-on-PUSCH in YAML."]);

tmp = tempname();
mkdir(tmp);
cleanupTmp = onCleanup(@() localRemove(tmp)); %#ok<NASGU>
cfg = sixgr.lls6g.buildInternalConfig(s, tmp);
assert(double(cfg.run.numTTI) == 30 && double(cfg.channel.snr_dB) == 20);
assert(double(cfg.scenario.nUE) == 2 && double(cfg.scenario.ue.nUE) == 2, ...
    "The canonical YAML UE count must reach both runtime topology aliases.");
assert(double(cfg.channel.nTxAnt) == 2 && double(cfg.channel.nRxAnt) == 2);
assert(logical(cfg.mac.scheduler.muMimoEnabled) && ...
    logical(cfg.mac.scheduler.ulMuMimoEnabled) && ...
    double(cfg.mac.scheduler.muMimoMaxUsersPerPRB) == 2 && ...
    string(cfg.mac.scheduler.muMimoSpatialSignatureMode) == "dominant_scheduled_rank", ...
    "The YAML MU policy must reach the production scheduler without an alias override.");
assert(string(cfg.phy.mimo.muMimoSpatialSignatureMode) == ...
    string(cfg.mac.scheduler.muMimoSpatialSignatureMode), ...
    "SRS measurement and scheduler admission must consume the same YAML spatial-signature policy.");
assert(string(s.get("canonical_control.mimo.ul_mu_mimo_receive_processing_mode")) == ...
    "full_dimensional_per_re_irc" && ...
    string(cfg.phy.mimo.ulMuMimoReceiveProcessingMode) == ...
        "full_dimensional_per_re_irc" && ...
    string(cfg.mac.scheduler.ulMuMimoReceiveProcessingMode) == ...
        "full_dimensional_per_re_irc", ...
    "UL MU-MIMO must preserve all receive branches for per-RE IRC under YAML authority.");
assert(double(cfg.phy.pdsch.numLayers) == 1 && double(cfg.phy.pusch.numLayers) == 1);
assert(logical(cfg.phy.pucch.uciOnPUSCHEnabled) && ...
    string(cfg.phy.pusch.uciMultiplexingMode) == ...
        "harq_ack_on_pusch_when_pucch_collides" && ...
    isequal(double(cfg.phy.tddTiming.dlHARQFeedbackK1Candidates), 4) && ...
    double(cfg.phy.tddTiming.dlHARQFeedbackK1) == 4, ...
    "YAML UCI-on-PUSCH and K1 authority must reach the production PHY runtime.");
policy = sixgr.lls6g.runners.resolveStrictControlEvidencePolicy(s, cfg);
assert(logical(policy.EnablePUSCHUCI) && ~logical(policy.EnablePUCCH) && ...
    logical(policy.PUSCHUCIRequired), ...
    "Strict runtime policy must require same-waveform PUSCH UCI, not standalone PUCCH.");
assert(double(cfg.runtime.phy.dl.NumLayers) == 1 && ...
    double(cfg.runtime.phy.ul.NumLayers) == 1);
assert(double(cfg.phy.pdsch.xOverhead) == 18 && ...
    double(cfg.phy.pusch.xOverhead) == 18 && ...
    double(cfg.runtime.phy.dl.XOverhead) == 18 && ...
    double(cfg.runtime.phy.ul.XOverhead) == 18, ...
    "YAML xOverhead must reach scheduler, waveform and immutable runtime authority.");
% Regression for the exact all-feature allocation that exposed the defect:
% two MU users split 273 PRBs into a 136-PRB grant; the materialized
% PDSCH/PT-RS/CSI-RS ownership plan produced G=86496 for MCS 19.  TBS must
% be sized with the YAML overhead before DCI/HARQ freeze, not reduced later.
scheduler = sixgr.l2.mac.SchedulerPF(cfg, "Direction", "DL");
[tbsBits, ~, nrePerPRB] = scheduler.estimateTBS( ...
    "64QAM", 1, 136, [2 12], 873/1024, "ForceExact", true);
exactRuntimeG = 86496;
assert(double(nrePerPRB) == 132 && ...
    double(tbsBits) == 79896 && double(tbsBits) / exactRuntimeG <= 0.95, ...
    ["The reproduced all-feature grant must be code-rate feasible before " ...
     "waveform execution (TBS=%g, G=%g, effective rate=%.9f)."], ...
    double(tbsBits), exactRuntimeG, double(tbsBits) / exactRuntimeG);
assert(logical(sixgr.util.structGet(cfg, ...
    "validation.random_access_evidence.require_runtime_stage_waveforms", false)));
ok = true;
end

function localRemove(root)
if isfolder(root)
    rmdir(root, "s");
end
end
