function ok = testPRACHLLS(selectedNames)
%TESTPRACHLLS Focused waveform PRACH LLS regression suite.
% Optional names run an explicitly reported subset; no argument runs all.

setup6GRSimToolkit("Verbose", false);

cases={@testContradictoryDuplexRejected,@testNoNoiseSanityDetection, ...
    @testFalseAlarmModeWithPrachDisabled,@testTimingOffsetRecovery, ...
    @testCorrelationTraceMissCase,@testCorrelationTraceFalseAlarmCase, ...
    @testRestrictedSetNCSValidation,@testPRACHOccasionSnapshotIsolation, ...
    @testZCDPEBackwardCompatibleWaveform,@testZCDPENonzeroDPIDetection, ...
    @testZCDPERunnerExports,@testMultipleSNRMonotonicitySanity, ...
    @testWrongPreambleClassification,@testCollisionModeTwoUEs, ...
    @testDeterministicReproducibility};
names=string(cellfun(@func2str,cases,'UniformOutput',false));
if nargin>0
    selectedNames=string(selectedNames);
    assert(~isempty(selectedNames) && all(ismember(selectedNames,names)), ...
        'Every explicitly selected PRACH subtest must exist.');
    cases=cases(ismember(names,selectedNames));
end
for k=1:numel(cases)
    name=func2str(cases{k}); fprintf('PRACH_SUBTEST_START %s\n',name);
    feval(cases{k}); fprintf('PRACH_SUBTEST_PASS %s\n',name);
end
fprintf('PRACH_SUBTEST_COVERAGE %d/%d\n',numel(cases),numel(names));

ok = true;
end

function testNoNoiseSanityDetection()
cfg = localScenario("ScenarioName", "no_noise", "SNRSweep_dB", 100, "NumTrials", 1, "ThresholdSweep", 0.02);
out = sixgr.rach.runPRACHLLS(localBaseConfig(cfg), "WriteOutputs", false, "ScenarioMatrix", cfg);
assert(height(out.ROTable) == 1, "No-noise PRACH smoke must emit one RO row.");
assert(all(out.ROTable.detected), "No-noise PRACH smoke must detect the preamble.");
assert(all(out.ROTable.correct_detection), "No-noise PRACH smoke must classify a correct detection.");
end

function testFalseAlarmModeWithPrachDisabled()
cfg = localScenario("ScenarioName", "false_alarm", "SNRSweep_dB", [-10 0], ...
    "NumTrials", 3, "NumUEsPerRO", 0, "ActivePreamblePattern", false, "ThresholdSweep", 0.02);
out = sixgr.rach.runPRACHLLS(localBaseConfig(cfg), "WriteOutputs", false, "ScenarioMatrix", cfg);
assert(all(~out.TrialTable.preamble_tx_present), ...
    "False-alarm PRACH mode must not claim transmitted preambles.");
assert(all(~out.TrialTable.detected), ...
    "False-alarm PRACH noise-only smoke must not produce detections at the chosen threshold.");
assert(all(out.SummaryBySNR.FalseAlarmProbability == 0), ...
    "FalseAlarmProbability must be derived from trials and be zero for this deterministic noise-only smoke.");
end

function testTimingOffsetRecovery()
cfg = sixgr.rach.PRACHConfig(struct("ScenarioName", "timing_offset", ...
    "CarrierFrequencyHz", 700e6, "DuplexMode", "FDD", "NSizeGrid", 52, ...
    "PRACHConfigurationIndex", 16, "PRACHSubcarrierSpacing", 1.25, ...
    "PRACHFormat", "0", "ChannelModel", "AWGN"), "PreambleIndex", 7);
occ = sixgr.rach.mapPRACHToOccasion(cfg, "OccasionIndex", 1);
tx = sixgr.rach.generatePRACHWaveform(cfg, "Occasion", occ, "PreambleIndex", 7);
delaySamples = 11.25;
n = (0:size(tx.Waveform, 1)-1).';
rx = interp1(n, tx.Waveform, n - delaySamples, "linear", 0);
det = sixgr.rach.PRACHDetector(rx, cfg, "Occasion", occ, ...
    "DetectionThresholdMode", "fixed", "DetectionThreshold", 0.02);
timing = sixgr.rach.estimateTimingOffset(det.TimingOffsetSamples, tx.SampleRate_Hz, delaySamples);
assert(logical(det.Detected), "Timing-offset recovery case must detect the preamble.");
assert(det.DetectedPreambleIndex == 7 && det.DetectedPreambleIndexRaw == 7, ...
    "Tied root-sequence peaks must not replace the receiver-decoded cyclic-shift identity.");
assert(isfinite(det.TimingOffsetSamples), "A detected preamble must retain its measured timing.");
assert(isnan(det.CorrelationTrace.Threshold) && det.CorrelationTrace.DecisionThreshold==det.Threshold, ...
    "Do not overlay the NR decision threshold onto a different diagnostic correlation statistic.");
assert(abs(double(timing.Error_us)) < 0.1, ...
    "Timing-offset recovery error must stay below 0.1 us for the deterministic fractional-delay case.");
assert(isfield(det, "CorrelationTrace") && isstruct(det.CorrelationTrace), ...
    "PRACH detector must expose lag-domain correlation trace evidence.");
assert(all(ismember(["LagSamples","CorrelationAbs","PeakLagSamples","Threshold","NoiseFloor"], ...
    string(fieldnames(det.CorrelationTrace)))), ...
    "PRACH correlation trace must include lag, magnitude, peak, threshold, and noise-floor evidence.");
assert(numel(det.CorrelationTrace.LagSamples) == numel(det.CorrelationTrace.CorrelationAbs) && ...
    any(isfinite(double(det.CorrelationTrace.CorrelationAbs))), ...
    "PRACH correlation trace must contain finite per-lag correlation samples.");
assert(abs(double(det.CorrelationTrace.PeakLagSamples) - delaySamples) < 1.0, ...
    "PRACH correlation trace peak lag must track the known injected preamble delay.");
end

function testCorrelationTraceMissCase()
% Exercise an actual noisy miss, not an out-of-range (>1) detector threshold.
cfg = localScenario("ScenarioName", "trace_miss", "SNRSweep_dB", -20, ...
    "NumTrials", 1, "ThresholdSweep", 0.99);
out = sixgr.rach.runPRACHLLS(localBaseConfig(cfg), "WriteOutputs", false, "ScenarioMatrix", cfg);
assert(istable(out.CorrelationTraceTable) && ~isempty(out.CorrelationTraceTable), ...
    "PRACH miss case must still export measured lag-domain correlation samples.");
assert(all(ismember(localCorrelationTraceColumns(), string(out.CorrelationTraceTable.Properties.VariableNames))), ...
    "PRACH correlation trace export must use the canonical lag-domain schema.");
assert(any(logical(out.CorrelationTraceTable.missed_detection)), ...
    "PRACH miss case must mark missed_detection in correlation trace evidence.");
assert(all(string(out.CorrelationTraceTable.truth_status) == "real_lls_evidence"), ...
    "Measured PRACH correlation trace rows must be marked as real LLS evidence.");
end

function testCorrelationTraceFalseAlarmCase()
cfg = localScenario("ScenarioName", "trace_false_alarm", "SNRSweep_dB", -20, ...
    "NumTrials", 1, "NumUEsPerRO", 0, "ActivePreamblePattern", false, "ThresholdSweep", 0.0);
out = sixgr.rach.runPRACHLLS(localBaseConfig(cfg), "WriteOutputs", false, "ScenarioMatrix", cfg);
assert(istable(out.CorrelationTraceTable) && ~isempty(out.CorrelationTraceTable), ...
    "PRACH false-alarm case must export measured lag-domain correlation samples.");
assert(any(logical(out.CorrelationTraceTable.false_alarm)), ...
    "PRACH false-alarm case must mark false_alarm in correlation trace evidence.");
assert(any(isfinite(double(out.CorrelationTraceTable.correlation_abs))), ...
    "PRACH false-alarm trace must retain the measured noise correlation samples.");
end

function testRestrictedSetNCSValidation()
unrestricted = sixgr.rach.PRACHConfig(localScenario("ScenarioName", "ncs_unrestricted", ...
    "ZeroCorrelationZone", 8), "RestrictedSet", "UnrestrictedSet");
assert(isfinite(double(unrestricted.ZCZNCS)), ...
    "Unrestricted PRACH N_CS must resolve from the concrete 3GPP ZCZ table.");

restrictedA = sixgr.rach.PRACHConfig(localScenario("ScenarioName", "ncs_restricted_a", ...
    "ZeroCorrelationZone", 8), "RestrictedSet", "RestrictedSetTypeA");
assert(isfinite(double(restrictedA.ZCZNCS)), ...
    "Long-sequence restricted-set type A PRACH N_CS must resolve from the concrete 3GPP ZCZ table.");

restrictedB = sixgr.rach.PRACHConfig(localScenario("ScenarioName", "ncs_restricted_b", ...
    "ZeroCorrelationZone", 8), "RestrictedSet", "RestrictedSetTypeB");
assert(isfinite(double(restrictedB.ZCZNCS)), ...
    "Long-sequence restricted-set type B PRACH N_CS must resolve from the concrete 3GPP ZCZ table.");

shortFailedClosed = false;
try
    sixgr.rach.PRACHConfig(localShortPRACHScenario("short_restricted_set", ...
        "ZeroCorrelationZone", 8), "RestrictedSet", "RestrictedSetTypeA");
catch ME
    shortFailedClosed = any(strcmp(string(ME.identifier), ...
        ["sixgr:rach:PRACHConfig:RestrictedSetInvalidForShortFormat", ...
         "sixgr:phy:prach:RestrictedSetInvalidForShortFormat"]));
end
assert(shortFailedClosed, ...
    "Strict PRACH must fail closed for unsupported short-format restricted-set combinations.");
end

function testPRACHOccasionSnapshotIsolation()
cfg = sixgr.rach.PRACHConfig(localScenario("ScenarioName", "occasion_snapshot", ...
    "PreambleIndex", 5), "PreambleIndex", 5);
occ = sixgr.rach.mapPRACHToOccasion(cfg, "OccasionIndex", 1);
originalPreamble = double(occ.PRACH.PreambleIndex);
sixgr.rach.generatePRACHWaveform(cfg, "Occasion", occ, "PreambleIndex", 12);
assert(double(occ.PRACH.PreambleIndex) == originalPreamble, ...
    "PRACH occasion snapshots must not be mutated by later waveform generation.");
end

function testZCDPEBackwardCompatibleWaveform()
cfg = sixgr.rach.PRACHConfig(localScenario("ScenarioName", "zcdpe_compat", ...
    "ZCDPE", struct("Enable", true, "DPI_D", 1, "DPI_d", 0, "NumSymbols", 1), ...
    "PreambleIndex", 3), "PreambleIndex", 3);
occ = sixgr.rach.mapPRACHToOccasion(cfg, "OccasionIndex", 1);
baseline = sixgr.rach.generatePRACHWaveform(cfg, "Occasion", occ, "PreambleIndex", 3);
candidate = sixgr.rach.generateZCDPEWaveform(cfg, "Occasion", occ, "PreambleIndex", 3, "DPI_d", 0);
relErr = norm(candidate.Waveform(:) - baseline.Waveform(:)) / max(norm(baseline.Waveform(:)), eps);
assert(relErr < 1e-6, "ZC-DPE d=0 must be waveform-compatible with baseline NR PRACH.");
end

function testZCDPENonzeroDPIDetection()
cfg = sixgr.rach.PRACHConfig(localShortPRACHScenario("zcdpe_nonzero_dpi", ...
    "ZCDPE", struct("Enable", true, "DPI_D", 2, "DPI_d", 1, "NumSymbols", 2), ...
    "PreambleIndex", 3), "PreambleIndex", 3);
occ = sixgr.rach.mapPRACHToOccasion(cfg, "OccasionIndex", 1);
tx = sixgr.rach.generateZCDPEWaveform(cfg, "Occasion", occ, "PreambleIndex", 3, "DPI_d", 1);
det = sixgr.rach.ZCDPEDetector(tx.Waveform, cfg, "Occasion", occ, ...
    "CandidatePreambles", 3, "DetectionThresholdMode", "fixed", "DetectionThreshold", 0.7);
assert(logical(det.Detected), "ZC-DPE detector must detect a no-noise nonzero-DPI PRACH waveform.");
assert(double(det.DetectedPreambleIndex) == 3, "ZC-DPE detector must preserve the detected preamble index.");
assert(double(det.ZCDPE.DPI_Detected) == 1, "ZC-DPE detector must recover the transmitted DPI index.");
assert(det.ThresholdSource=="zcdpe_configured_fixed_matched_filter" && ...
    det.ThresholdCalibrationStatus=="unqualified_research_detector" && ...
    isempty(det.CorrelationTrace.LagSamples), ...
    "A research decision must not inherit the NR detector's threshold source or lag trace.");
end

function testZCDPERunnerExports()
cfg = localShortPRACHScenario("zcdpe_runner", ...
    "ZCDPE", struct("Enable", true, "DPI_D", 2, "DPI_d", 1, "NumSymbols", 2), ...
    "PreambleIndex", 3, "SNRSweep_dB", 100, "ThresholdSweep", 0.7, "NumTrials", 1);
out = sixgr.rach.runPRACHLLS(localBaseConfig(cfg), "WriteOutputs", false, "ScenarioMatrix", cfg);
assert(all(ismember(["zcdpe_enabled","prach_design","dpi_D","dpi_d_true","dpi_d_detected","dpi_correct"], ...
    string(out.ROTable.Properties.VariableNames))), ...
    "ZC-DPE PRACH runner must export design and DPI evidence columns.");
assert(all(logical(out.ROTable.zcdpe_enabled)), "ZC-DPE runner rows must mark ZC-DPE as enabled.");
assert(all(string(out.ROTable.prach_design) == "zcdpe"), "ZC-DPE runner rows must export the candidate design name.");
assert(all(double(out.ROTable.dpi_d_true) == 1), "ZC-DPE runner must preserve transmitted DPI truth.");
assert(all(logical(out.ROTable.dpi_correct)), "No-noise ZC-DPE runner smoke must recover DPI correctly.");
end

function testMultipleSNRMonotonicitySanity()
cfg = localScenario("ScenarioName", "snr_monotonicity", "SNRSweep_dB", [-35 -25 -15], ...
    "NumTrials", 6, "ThresholdSweep", 0.2);
out = sixgr.rach.runPRACHLLS(localBaseConfig(cfg), "WriteOutputs", false, "ScenarioMatrix", cfg);
detProb = double(out.SummaryBySNR.DetectionProbability);
assert(issorted(detProb), ...
    "DetectionProbability must be nondecreasing over the chosen SNR sweep sanity case.");
end

function testWrongPreambleClassification()
cfg = localScenario("ScenarioName", "wrong_preamble", "CarrierFrequencyHz", 700e6, ...
    "DuplexMode", "FDD", "NSizeGrid", 52, "PRACHConfigurationIndex", 16, ...
    "PRACHSubcarrierSpacing", 1.25, "PRACHFormat", "0", ...
    "NumUEsPerRO", 2, "EnableCollisionMode", false, "PreambleIndex", [5 12], ...
    "NumTrials", 1, "SNRSweep_dB", 30, "ThresholdSweep", 0.02);
out = sixgr.rach.runPRACHLLS(localBaseConfig(cfg), "WriteOutputs", false, "ScenarioMatrix", cfg);
assert(any(out.TrialTable.wrong_preamble), ...
    "Multi-UE different-preamble case must produce at least one wrong-preamble UE classification.");
end

function testCollisionModeTwoUEs()
cfg = localScenario("ScenarioName", "collision_two_ue", "CarrierFrequencyHz", 4e9, ...
    "DuplexMode", "TDD", "CarrierSCSkHz", 30, "NSizeGrid", 273, ...
    "PRACHConfigurationIndex", 86, "PRACHSubcarrierSpacing", 15, "PRACHFormat", "A1", ...
    "NumUEsPerRO", 2, "EnableCollisionMode", true, "NumTrials", 1, ...
    "SNRSweep_dB", 20, "ThresholdSweep", 0.02, "ChannelModel", "TDL-C", ...
    "DelaySpread_ns", 300, "Speed_kmh", 30, "Seed", 77);
out = sixgr.rach.runPRACHLLS(localBaseConfig(cfg), "WriteOutputs", false, "ScenarioMatrix", cfg);
assert(height(out.TrialTable) == 2, ...
    "Two-UE collision PRACH case must emit one trial row per UE.");
assert(numel(unique(out.TrialTable.transmitted_preamble_index)) == 1, ...
    "Collision-mode PRACH case must force the same preamble index across colliding UEs.");
end

function testDeterministicReproducibility()
cfg = localScenario("ScenarioName", "repro", "SNRSweep_dB", [-20 -10], ...
    "NumTrials", 3, "ThresholdSweep", 0.2, "ChannelModel", "TDL-C", ...
    "DelaySpread_ns", 300, "Speed_kmh", 30, "Seed", 333);
out1 = sixgr.rach.runPRACHLLS(localBaseConfig(cfg), "WriteOutputs", false, "ScenarioMatrix", cfg);
out2 = sixgr.rach.runPRACHLLS(localBaseConfig(cfg), "WriteOutputs", false, "ScenarioMatrix", cfg);
ro1 = localDropRuntimeLatencyColumns(out1.ROTable);
ro2 = localDropRuntimeLatencyColumns(out2.ROTable);
assert(isequaln(out1.TrialTable, out2.TrialTable), ...
    "PRACH LLS trials must be reproducible for a fixed seed.");
assert(isequaln(ro1, ro2), ...
    "PRACH LLS RO summaries must be reproducible for a fixed seed.");
end

function base=localBaseConfig(cfg)
% The fixture base must agree with its explicit FDD/TDD scenario authority.
base=sixgr.config.defaultConfig();
base.phy.duplex.mode=cfg.DuplexMode;
% These are small waveform/detection fixtures, not the system catalog's
% inherited 4-TX/64-RX massive-array campaign. Declare the tested layout.
% Production and dedicated antenna-dimension tests keep their own authority.
base.random_access.num_tx_antennas=1;
base.random_access.num_rx_antennas=2;
end

function testContradictoryDuplexRejected()
cfg=localScenario(); base=localBaseConfig(cfg); base.phy.duplex.mode="TDD";
try
    sixgr.rach.runPRACHLLS(base,"WriteOutputs",false,"ScenarioMatrix",cfg);
catch e
    assert(string(e.identifier)=="sixgr:phy:frame:DuplexAuthorityMismatch",e.message);
    return;
end
error('testPRACHLLS:MissingDuplexRejection','Conflicting duplex authorities must still be rejected.');
end

function cfg = localScenario(varargin)
cfg = struct( ...
    "ScenarioName", "prach_test", ...
    "CarrierFrequencyHz", 700e6, ...
    "DuplexMode", "FDD", ...
    "NSizeGrid", 52, ...
    "PRACHConfigurationIndex", 16, ...
    "PRACHSubcarrierSpacing", 1.25, ...
    "PRACHFormat", "0", ...
    "CarrierSCSkHz", 15, ...
    "NumPRACHOccasions", 1, ...
    "NumTrials", 1, ...
    "SNRSweep_dB", 0, ...
    "ThresholdSweep", 0.02, ...
    "ChannelModel", "AWGN", ...
    "DelaySpread_ns", 30, ...
    "Speed_kmh", 3, ...
    "NumUEsPerRO", 1, ...
    "ActivePreamblePattern", true, ...
    "Seed", 101);
for iArg = 1:2:numel(varargin)
    cfg.(varargin{iArg}) = varargin{iArg + 1};
end
end

function cfg = localShortPRACHScenario(name, varargin)
cfg = localScenario("ScenarioName", name, ...
    "CarrierFrequencyHz", 4e9, ...
    "DuplexMode", "TDD", ...
    "CarrierSCSkHz", 30, ...
    "NSizeGrid", 273, ...
    "PRACHConfigurationIndex", 87, ...
    "PRACHSubcarrierSpacing", 15, ...
    "PRACHFormat", "A2", ...
    "NumPRACHOccasions", 1, ...
    "NumTrials", 1, ...
    "SNRSweep_dB", 100, ...
    "ThresholdSweep", 0.7, ...
    "ChannelModel", "AWGN");
for iArg = 1:2:numel(varargin)
    cfg.(varargin{iArg}) = varargin{iArg + 1};
end
end

function T = localDropRuntimeLatencyColumns(T)
drop = intersect("ComputeLatency_ms", string(T.Properties.VariableNames));
if ~isempty(drop)
    T = removevars(T, cellstr(drop));
end
end

function cols = localCorrelationTraceColumns()
cols = ["trial_id","preamble_index","root_sequence_index","restricted_set_type","n_cs", ...
    "zero_correlation_zone_config","lag_samples","lag_us","correlation_abs","threshold", ...
    "noise_floor","peak_lag_samples","timing_advance_samples","detection_result", ...
    "false_alarm","missed_detection","snr_db","cfo_hz","seed","truth_status"];
end
