function ok = testConfiguredProtocolComponentValidation()
%TESTCONFIGUREDPROTOCOLCOMPONENTVALIDATION YAML-shaped DL/UL L2 execution.

setup6GRSimToolkit("Verbose", false, "RunToolboxChecks", false);
root = string(tempname);
mkdir(root);
cleanup = onCleanup(@() rmdir(root, "s")); %#ok<NASGU>

cfg = struct();
% buildInternalConfig publishes the authoritative configured UE count at
% scenario.ue.nUE.  Exercise that production shape so the component
% campaign cannot silently collapse a multi-UE waveform scenario to one UE.
cfg.scenario.ue.nUE = 2;
cfg.protocol = struct( ...
    "enabled", true, "strict", true, "configuration_epoch", 3, ...
    "rlc", struct("sn_bits",18,"poll_pdu",16,"poll_byte",65536, ...
    "max_retx_threshold",8), ...
    "pdcp", struct("sn_bits",18,"cipher_algorithm","NEA0", ...
    "integrity_algorithm","NIA0"), ...
    "sdap", struct("pdu_session_id",1,"default_drb_id",1, ...
    "qfi_to_drb",struct("qfi",9,"drb_id",1)), ...
    "mac", struct("lcid",4), ...
    "component_validation", struct("enabled",true, ...
    "packets_per_ue_direction",2, ...
    "duplicate_reception_check_enabled",true, ...
    "require_configured_bidirectional_execution",true, ...
    "write_png",false), ...
    "traffic", struct("sessions",struct("flow_id","data-1", ...
    "pdu_session_id",1,"qfi",9,"packet_bytes",128, ...
    "direction","BIDIR")));

out = sixgr.protocol.runConfiguredProtocolComponentValidation( ...
    cfg, root, "RunId", "focused-run", ...
    "ScenarioName", "focused-scenario", "WriteArtifacts", true);
assert(out.Ok && out.StrictOk);
T = out.ArtifactTables.execution;
assert(height(T) == 8, ...
    "Two UEs, two directions and two packets must produce eight rows.");
assert(sum(T.Direction == "DL") == 4 && sum(T.Direction == "UL") == 4);
assert(all(T.Delivered) && all(T.DuplicateRejected));
assert(all(~T.ProxyUsed & ~T.FallbackUsed));
assert(all(~T.SameWaveformPayloadIntegration & ...
    ~T.CountsTowardWaveformTruth));
assert(all(T.EvidenceClassification == ...
    "strict_component_execution_not_same_waveform_payload_truth"));
assert(all(out.ArtifactTables.conservation.EquationErrorBytes == 0));
assert(isfile(fullfile(root, "protocol_stack", "csv", ...
    "protocol_configured_component_execution.csv")));
assert(isempty(dir(fullfile(root, "**", "*.png"))) && ...
    isempty(dir(fullfile(root, "**", "*.jpg"))) && ...
    isempty(dir(fullfile(root, "**", "*.jpeg"))) && ...
    isempty(dir(fullfile(root, "**", "*.svg"))), ...
    "Configured protocol component validation must remain CSV-only.");

legacyCfg = cfg;
legacyCfg.protocol.component_validation.write_png = true;
legacyFailedClosed = false;
try
    sixgr.protocol.runConfiguredProtocolComponentValidation( ...
        legacyCfg, root, "RunId", "legacy-raster-negative", ...
        "ScenarioName", "legacy-raster-negative", "WriteArtifacts", true);
catch ME
    legacyFailedClosed = strcmp(ME.identifier, ...
        "sixgr:protocol:LegacyRasterEmissionDisabled");
end
assert(legacyFailedClosed, ...
    "Legacy component PNG emission must fail with the typed raster-authority error.");

for masterName = ["master_sinr_sweep.yaml", "master_geometry_based.yaml"]
    scenario = sixgr.lls6g.config.loadScenarioConfig(fullfile(pwd, ...
        "simulator", "configs", "scenarios", masterName));
    assert(logical(scenario.get( ...
        "canonical_control.protocol_stack.component_validation.enabled", false)));
    assert(double(scenario.get( ...
        "canonical_control.protocol_stack.mac.lcid", NaN)) == 4);
    assert(logical(scenario.get( ...
        "canonical_control.protocol_stack.component_validation.require_configured_bidirectional_execution", ...
        false)));
    assert(~logical(scenario.get( ...
        "canonical_control.protocol_stack.component_validation.write_png", ...
        true)), ...
        "Master scenarios must delegate protocol rasters to the CSV materializer.");
end
ok = true;
end
