function ok = testRunArtifactAudit()
%TESTRUNARTIFACTAUDIT Recursive artifact audit must fail on bad required CSVs/images.

setup6GRSimToolkit("Verbose", false);

assert(usejava("jvm"), ...
    "testRunArtifactAudit requires MATLAB JVM plotting so required PNG artifacts can be audited.");

tmp = tempname;
mkdir(tmp);
cleanupObj = onCleanup(@() rmdir(tmp, "s")); %#ok<NASGU>

snrGrid = [0 8 16];
trialsPerPoint = 20;
cfg = localFixtureConfig(snrGrid, trialsPerPoint);
opt = localCampaignOptions(cfg, snrGrid, trialsPerPoint, 314159);

sixgr.truth.runWaveformLinkBundle(cfg, fullfile(tmp, "air_interface"), opt); %#ok<NASGU>
localWriteAuditPrereqs(tmp, snrGrid, trialsPerPoint);
sixgr.validation.auditFixedSNRSweepRun(tmp, "Strict", false, "WriteOutputs", true);
sixgr.visual.plotFixedSNRSweepCurves(tmp);

artifactAudit = sixgr.validation.auditRunArtifacts(tmp, "Strict", false, "WriteOutputs", true);
assert(logical(artifactAudit.Ok), ...
    "A complete fixed-sweep fixture must pass the recursive artifact audit.");
assert(exist(fullfile(tmp, "reports", "csv", "all_csv_artifact_audit.csv"), "file") == 2, ...
    "The CSV artifact audit table must be written.");
assert(exist(fullfile(tmp, "reports", "csv", "all_image_artifact_audit.csv"), "file") == 2, ...
    "The image artifact audit table must be written.");
assert(exist(fullfile(tmp, "reports", "csv", "artifact_issue_registry.csv"), "file") == 2, ...
    "The artifact issue registry must be written.");
assert(exist(fullfile(tmp, "reports", "json", "artifact_audit_summary.json"), "file") == 2, ...
    "The artifact audit JSON summary must be written.");

csvAudit = readtable(fullfile(tmp, "reports", "csv", "all_csv_artifact_audit.csv"), ...
    "VariableNamingRule", "preserve", "TextType", "string");
imageAudit = readtable(fullfile(tmp, "reports", "csv", "all_image_artifact_audit.csv"), ...
    "VariableNamingRule", "preserve", "TextType", "string");
assert(any(string(csvAudit.relative_path) == "reports/csv/fixed_snr_sweep_audit.csv"), ...
    "The recursive CSV audit must include fixed_snr_sweep_audit.csv.");
assert(any(string(imageAudit.relative_path) == "reports/image/dl_bler_vs_snr.png"), ...
    "The recursive image audit must include the fixed-sweep BLER plot.");

ulCurvePath = fullfile(tmp, "reports", "csv", "ul_fixed_snr_bler_curve.csv");
ulCurve = readtable(ulCurvePath, "VariableNamingRule", "preserve", "TextType", "string");
sixgr.util.csvWriteTable(ulCurvePath, ulCurve([],:));
auditMissingCurve = sixgr.validation.auditRunArtifacts(tmp, "Strict", false, "WriteOutputs", true);
assert(~logical(auditMissingCurve.Ok), ...
    "An empty required fixed-sweep UL BLER curve must fail the recursive artifact audit.");
issueRegistry = readtable(fullfile(tmp, "reports", "csv", "artifact_issue_registry.csv"), ...
    "VariableNamingRule", "preserve", "TextType", "string");
missingCurveRows = string(issueRegistry.relative_path) == "reports/csv/ul_fixed_snr_bler_curve.csv";
assert(any(missingCurveRows), ...
    "The issue registry must point to the exact empty required CSV.");
assert(any(contains(lower(string(issueRegistry.failure_code(missingCurveRows))), "required_csv_empty")), ...
    "The issue registry must explain that the required UL curve is empty.");

sixgr.util.csvWriteTable(ulCurvePath, ulCurve);
blankPlotPath = fullfile(tmp, "reports", "image", "dl_bler_vs_snr.png");
imwrite(uint8(255 * ones(180, 240, 3)), blankPlotPath);
auditBlankImage = sixgr.validation.auditRunArtifacts(tmp, "Strict", false, "WriteOutputs", true);
assert(~logical(auditBlankImage.Ok), ...
    "A blank required fixed-sweep plot must fail the recursive artifact audit.");
issueRegistry = readtable(fullfile(tmp, "reports", "csv", "artifact_issue_registry.csv"), ...
    "VariableNamingRule", "preserve", "TextType", "string");
blankImageRows = string(issueRegistry.relative_path) == "reports/image/dl_bler_vs_snr.png";
assert(any(blankImageRows), ...
    "The issue registry must point to the exact blank required image.");
assert(any(contains(lower(string(issueRegistry.failure_code(blankImageRows))), "required_image_blank_or_low_information")), ...
    "The issue registry must explain that the required BLER image is blank or low-information.");

sixgr.visual.plotFixedSNRSweepCurves(tmp);
orphanPath = fullfile(tmp, "reports", "image", "unmanifested_orphan.png");
imwrite(uint8(repmat(reshape(uint8(mod(0:255, 256)), 16, 16), 1, 1, 3)), orphanPath);
auditOrphan = sixgr.validation.auditRunArtifacts(tmp, "Strict", false, "WriteOutputs", true);
assert(~logical(auditOrphan.Ok), ...
    "A decodable PNG without exact plot lineage must fail the recursive artifact audit.");
orphanRows = string(auditOrphan.ImageAuditTable.relative_path) == ...
    "reports/image/unmanifested_orphan.png";
assert(any(orphanRows) && any(string(auditOrphan.ImageAuditTable.failure_code(orphanRows)) == ...
        "unmanifested_visual_artifact"), ...
    "The recursive audit must classify an orphan PNG as unmanifested visual evidence.");

ok = true;
end

function cfg = localFixtureConfig(snrGrid, trialsPerPoint)
scenarioPath = fullfile(pwd, "simulator", "configs", "scenarios", "variants", "SCN00_BASELINE_CAPACITY.yaml");
scfg = sixgr.lls6g.config.loadScenarioConfig(scenarioPath);
scfg = scfg.toStruct();
scfg.harq.k2 = 2;
scfg.random_access.enabled = false;
scfg.channels.model_type = "AWGN";
scfg.channels.profile = "AWGN";
scfg.simulation.noise_operating_mode = "standalone_awgn_snr_argument";
scfg = sixgr.util.structSet(scfg, "pdsch.execution_profile", "phy_calibration");
scfg = sixgr.util.structSet(scfg, "pdsch.num_ports", 1);
scfg = sixgr.util.structSet(scfg, "pusch.num_ports", 1);
scfg = sixgr.util.structSet(scfg, "reference_signals.pdsch_dmrs_ports", 1);
scfg = sixgr.util.structSet(scfg, "reference_signals.pusch_dmrs_ports", 1);
scfg = sixgr.util.structSet(scfg, "pdsch6gr.dmrs_port_set", 0);
scfg = sixgr.util.structSet(scfg, "pdsch6gr.dmrs_num_ports", 1);
scfg = sixgr.util.structSet(scfg, "mimo.phase07_strict.enabled", false);
scfg = sixgr.util.structSet(scfg, "link_adaptation.fixed_or_amc", "fixed");
scfg = sixgr.util.structSet(scfg, "link_adaptation.pdsch_link_adaptation_policy", "fixed");
scfg = sixgr.util.structSet(scfg, "link_adaptation.pusch_link_adaptation_policy", "fixed");
for path = ["pdsch6gr.mcs_ue_capability_1024qam", ...
        "pdsch6gr.mcs_rrc_enabled_1024qam", ...
        "pdsch6gr.mcs_dci_enabled_1024qam", ...
        "pdsch6gr.mcs_deployment_allows_1024qam", ...
        "pdsch6gr.mcs_frequency_range_allows_1024qam", ...
        "pdsch6gr.mcs_band_allows_1024qam"]
    scfg = sixgr.util.structSet(scfg, path, false);
end
scfg = sixgr.util.structSet(scfg, "pdsch6gr.mcs_frequency_range", "FR1");
scfg = sixgr.util.structSet(scfg, "pdsch6gr.mcs_operating_band", "n77");
scfg = sixgr.util.structSet(scfg, "pdsch6gr.mcs_deployment_class", "fixed_link_calibration");
scfg.validation.fixed_link_campaign = struct( ...
    "enabled", true, ...
    "configuration_authority", "master_yaml", ...
    "direction", "both", ...
    "channel_model", "AWGN", ...
    "snr_db", double(snrGrid(:)).', ...
    "mcs", 4, ...
    "rank", 1, ...
    "layers", 1, ...
    "n_prb", 24, ...
    "min_tb_per_point", double(trialsPerPoint), ...
    "max_tb_per_point", double(trialsPerPoint), ...
    "min_errors_for_ci", 0, ...
    "max_ci_half_width", 1.0, ...
    "confidence_level", 0.95, ...
    "trials_per_drop", 1, ...
    "disable_auxiliary_signals", true, ...
    "enable_ptrs", false, ...
    "fixed_reference_mode", true, ...
    "noise_operating_mode", "standalone_awgn_snr_argument", ...
    "pdsch_execution_profile", "phy_calibration", ...
    "link_adaptation_mode", "fixed", ...
    "harq_enabled", false, ...
    "single_user_mode", true, ...
    "seeds", 314159, ...
    "target_bler", 0.1);
for path = ["reference_signals.ssb_enabled", "reference_signals.pbch_enabled", ...
        "reference_signals.pdcch_dmrs_enabled", "reference_signals.ptrs_enabled", ...
        "reference_signals.ptrs_cpe_correction_enabled", ...
        "reference_signals.csi_rs_enabled", "reference_signals.srs_enabled", ...
        "reference_signals.trs_enabled", "reference_signals.tracking_rs_enabled", ...
        "reference_signals.csi_reporting_enabled", ...
        "reference_signals.cqi_reporting_enabled", ...
        "reference_signals.pmi_reporting_enabled", ...
        "reference_signals.ri_reporting_enabled", ...
        "reference_signals.cri_reporting_enabled", ...
        "control.pdcch_enabled", "control.blind_search_enabled", ...
        "control.pucch_enabled", "initial_access.sib1.enabled", ...
        "initial_access.mib.enabled", "initial_access.ssb.enabled", ...
        "mimo.beam_sweep_enabled", "mimo.mu_mimo_enable", ...
        "mimo.ul_mu_mimo_enable", ...
        "harq.enabled", "pdsch6gr.harq_enabled", ...
        "simulation.harq_diagnostics_enabled"]
    scfg = sixgr.util.structSet(scfg, path, false);
end
for path = ["mimo.n_layers", "mimo.max_dl_layers", "mimo.max_ul_layers", ...
        "pdsch.layer_count", "pdsch6gr.num_layers", ...
        "pusch.layer_count", "pusch.num_layers"]
    scfg = sixgr.util.structSet(scfg, path, 1);
end
scfg = sixgr.util.structSet(scfg, ...
    "reference_signals.ptrs_port_association_policy", ...
    "first_scheduled_dmrs_port");
cfg = sixgr.lls6g.buildInternalConfig(scfg, fullfile(tempdir, "run_artifact_audit_fixture"));
cfg.run.numFrames = 1;
cfg.run.strictMode = false;
cfg.run.noProxyTruthContract = false;
cfg.run.interferenceExecutionMode = "none";
cfg.run.noiseOperatingMode = "receiver_noise_figure_thermal_noise";
cfg.run.seed = 4207;
cfg.channel.model = "AWGN";
cfg.channel.awgnOnly = true;
cfg.channel.fading.enable = false;
cfg.channel.bandwidth_Hz = 10e6;
cfg.channel.snr_dB = 18;
cfg.channel.nTxAnt = 1;
cfg.channel.nRxAnt = 1;
cfg.phy.channelBandwidth_MHz = 10;
cfg.phy.nTxAnt = 1;
cfg.phy.nRxAnt = 1;
cfg.phy.carrier.NSizeGrid = 24;
cfg = sixgr.util.structSet(cfg, "phy.numerology.activeGridNumRBs", 24);
cfg = sixgr.util.structSet(cfg, "phy.numerology.configuredGridNumRBs", 24);
cfg.phy.pdsch.nLayers = 1;
cfg.phy.pdsch.numLayers = 1;
cfg.phy.pdsch.executionProfile = "phy_calibration";
cfg.phy.pdsch.mcsIndex = 4;
cfg.phy.pdsch.modulation = "QPSK";
cfg.phy.pdsch.codeRate = 0.30;
cfg.phy.pdsch.symbolAllocation = [2 12];
cfg.phy.pdsch.mappingType = "A";
cfg.phy.pdsch.prbSet = 0:23;
cfg.phy.pdsch.PRBSet = 0:23;
cfg.phy.pusch.nLayers = 1;
cfg.phy.pusch.numLayers = 1;
cfg.phy.pusch.mcsIndex = 4;
cfg.phy.pusch.modulation = "QPSK";
cfg.phy.pusch.codeRate = 0.30;
cfg.phy.pusch.prbSet = 0:23;
cfg.phy.pusch.PRBSet = 0:23;
cfg.phy.bwp.dl = struct("NStartBWP",0,"NSizeBWP",24);
cfg.phy.bwp.ul = struct("NStartBWP",0,"NSizeBWP",24);
cfg.phy.pbch.enable = false;
cfg.phy.mib.enable = false;
cfg.phy.sib1.enable = false;
cfg.phy.pdcch.enable = false;
cfg.phy.pucch.enable = false;
cfg.phy.srs.enable = false;
cfg = sixgr.util.structSet(cfg, "phy.trs.enable", false);
cfg = sixgr.util.structSet(cfg, "phy.ptrs.enable", false);
cfg.phy.csirs.enable = false;
cfg.phy.prach.enable = false;
cfg.phy.harq.enable = false;
cfg.mac.harq.enable = false;
cfg.phy.pusch.powerControl.enabled = false;
cfg.powerAndRF.puschPowerControlEnabled = false;
cfg = sixgr.util.structSet(cfg, "lls6g.users.enabled", false);
cfg = sixgr.util.structSet(cfg, "lls6g.users.n_users", 1);
end

function opt = localCampaignOptions(cfg, snrGrid, trialsPerPoint, seed)
opt = struct( ...
    "LinkDuration_s", 0.001, ...
    "LinkMaxSimFrames", 1, ...
    "FixedLinkCampaignOnly", true, ...
    "LinkSNR_dB", double(cfg.channel.snr_dB), ...
    "LinkSNRGrid_dB", double(cfg.channel.snr_dB), ...
    "LinkSweepFrames", 1, ...
    "LinkSweepTrialsPerSNR", 1, ...
    "LinkSweepMaxPoints", 1, ...
    "LinkReferenceSweepFrames", trialsPerPoint, ...
    "LinkAdaptiveSweepEnabled", false, ...
    "LinkFixedLinkCampaignEnabled", true, ...
    "LinkFixedLinkSNRGrid_dB", snrGrid, ...
    "LinkFixedLinkMinTrials", trialsPerPoint, ...
    "LinkFixedLinkMaxTrials", trialsPerPoint, ...
    "LinkFixedLinkTrialsPerDrop", 1, ...
    "LinkFixedLinkErrorTarget", 0, ...
    "LinkFixedLinkCIWidthTarget", inf, ...
    "LinkFixedLinkConfidenceLevel", 0.95, ...
    "LinkFixedLinkSeed", seed, ...
    "HARQDiagnosticsEnabled", false, ...
    "LinkAnchorCases", ["DL_PDSCH_Throughput","UL_PUSCH_Throughput"], ...
    "SaveFigures", false);
end

function localWriteAuditPrereqs(runFolder, snrGrid, trialsPerPoint)
layout = sixgr.report.resultLayout(runFolder);
sixgr.util.ensureFolder(layout.MetaDir);
sixgr.util.ensureFolder(layout.ReportCSVDir);

resolved = struct();
resolved.validation = struct( ...
    "run_class", "fixed_snr_sweep_lls", ...
    "fixed_snr_sweep_required", true);
resolved.sweeps_and_matrix = struct( ...
    "fixed_link_calibration", struct( ...
        "enabled", true, ...
        "only", true, ...
        "direction", "both", ...
        "snr_db", double(snrGrid(:)).', ...
        "min_trials", double(trialsPerPoint), ...
        "max_trials", double(trialsPerPoint), ...
        "ci_width_target", 10.0, ...
        "confidence_level", 0.95, ...
        "max_sinr_snr_delta_db", 10.0, ...
        "target_bler", 0.1));
resolved.simulation = struct("noise_operating_mode", "standalone_awgn_snr_argument");
sixgr.util.jsonWrite(fullfile(layout.MetaDir, "scenario_config_resolved.json"), resolved);

runClassT = table( ...
    "fixed_snr_sweep_lls", true, true, true, false, ...
    "4", "QPSK", 1, 1, 1.0, false, ...
    "fixed_snr_sweep_lls uses dedicated fixed-sweep audit gating.", ...
    'VariableNames', {'RunClass','FixedMCSActive','RankFixed','ModulationFixed','AdaptiveMode', ...
    'ConfiguredMCS','ConfiguredModulation','ConfiguredRank','ConfiguredLayers', ...
    'ExactConfiguredEffectiveMatchRate','PublicationLLSEligible','Reason'});
sixgr.util.csvWriteTable(fullfile(layout.ReportCSVDir, "run_classification.csv"), runClassT);
end
