function ok = testPDCCHIntegratedRuntimeEvidenceGate()
%TESTPDCCHINTEGRATEDRUNTIMEEVIDENCEGATE Integrated runtime PDCCH evidence must satisfy strict gate.

setup6GRSimToolkit("Verbose", false);

tmp = tempname;
mkdir(tmp);
c = onCleanup(@() rmdir(tmp, "s")); %#ok<NASGU>
layout = sixgr.report.resultLayout(tmp);
for f = ["ReportCSVDir","AirInterfaceCSVDir","ControlCSVDir"]
    sixgr.util.ensureDir(layout.(f));
end

localWriteMinimalMetadata(layout);
pdcch = localIntegratedPDCCHTrialTable();
sixgr.util.csvWriteTable(fullfile(layout.ControlCSVDir, "pdcch_trials.csv"), pdcch);
sixgr.util.csvWriteTable(fullfile(layout.AirInterfaceCSVDir, "pdcch_trials.csv"), pdcch);

scfg = struct();
scfg = sixgr.util.structSet(scfg, "scenario_id", "integrated_pdcch_evidence_gate");
scfg = sixgr.util.structSet(scfg, "scenario.honesty_mode", "strict");
scfg = sixgr.util.structSet(scfg, "users.execution_model", "slot_coupled_truth");
scfg = sixgr.util.structSet(scfg, "simulation.link_direction", "none");
scfg = sixgr.util.structSet(scfg, "control_gating.pdcch_required", true);
cfg = struct();
% The generic builder derives this objective from pdcch_required.  It must
% not select the standalone-study contract when the raw scenario did not.
cfg = sixgr.util.structSet(cfg, "validation.objectives", ...
    "pdcch_strict_validation");

verdict = sixgr.truth.evaluateLLSRuntimeTruthContract(tmp, scfg, cfg);
summaryT = readtable(fullfile(layout.ReportCSVDir, "truth_contract_summary.csv"), ...
    "VariableNamingRule", "preserve");
assert(logical(summaryT.PDCCHRequired(1)), "Fixture must require PDCCH evidence.");
assert(logical(summaryT.PDCCHStrictOk(1)), ...
    "Integrated grant-coupled PDCCH waveform evidence must satisfy the strict PDCCH gate.");
assert(~contains(strjoin(string(verdict.Failures), "|"), "pdcch_strict"), ...
    "Strict truth failures must not include PDCCH when integrated waveform evidence is complete.");

auditT = readtable(fullfile(layout.ReportCSVDir, "conformance_matrix_runtime_audit.csv"), ...
    "VariableNamingRule", "preserve");
pdcchRow = auditT(string(auditT.Subsystem) == "pdcch", :);
assert(height(pdcchRow) == 1 && logical(pdcchRow.Pass(1)), ...
    "Conformance matrix must recognize integrated PDCCH runtime evidence.");

% Conversely, an explicit scenario objective must retain the standalone
% evidence requirement and may not be satisfied by integrated rows alone.
standaloneScfg = sixgr.util.structSet(scfg, "validation.objectives", ...
    "pdcch_strict_validation");
sixgr.truth.evaluateLLSRuntimeTruthContract(tmp, standaloneScfg, cfg);
standaloneSummary = readtable(fullfile(layout.ReportCSVDir, ...
    "truth_contract_summary.csv"), "VariableNamingRule", "preserve");
assert(~logical(standaloneSummary.PDCCHStrictOk(1)), ...
    "An explicitly requested standalone PDCCH study must require its standalone artifacts.");
ok = true;
end

function localWriteMinimalMetadata(layout)
sixgr.util.csvWriteTable(fullfile(layout.ReportCSVDir, "scenario_summary.csv"), ...
    table("completed", true, true, 'VariableNames', {'RunCompletion','Ok','ResultOk'}));
sixgr.util.csvWriteTable(fullfile(layout.ReportCSVDir, "config_roundtrip_verification.csv"), ...
    table("fixture", "consistent", 'VariableNames', {'CheckName','ConsistencyStatus'}));
sixgr.util.csvWriteTable(fullfile(layout.ReportCSVDir, "browser_runtime_db_consistency.csv"), ...
    table("fixture", "consistent", 'VariableNames', {'CheckName','ConsistencyStatus'}));
sixgr.util.csvWriteTable(fullfile(layout.ReportCSVDir, "summary_vs_raw_consistency.csv"), ...
    table("fixture", "consistent", 'VariableNames', {'CheckName','ConsistencyStatus'}));
sixgr.util.csvWriteTable(fullfile(layout.ReportCSVDir, "value_source_audit.csv"), ...
    table("fixture", "observed", 'VariableNames', {'CheckName','ConsistencyStatus'}));
sixgr.util.csvWriteTable(fullfile(layout.ReportCSVDir, "runtime_operating_mode.csv"), ...
    table(false, false, true, "truth", "waveform", "none", "truth", ...
    'VariableNames', {'ProxyPHYActive','FallbackUsed','WaveformPHYActive', ...
    'ExecutionBackend','PHYMode','ApproximationMode','E2EAirModel'}));
end

function T = localIntegratedPDCCHTrialTable()
T = table( ...
    true, false, false, false, false, false, ...
    true, true, true, ...
    9, 9, 9, 108, 36, 216, 4660, 4660, ...
    "grid_hash", "waveform_hash", "resource_hash", ...
    "nrDCIDecode_crc_masked_by_rnti", ...
    "nrPDCCHSpace_nrPDCCHDecode_nrDCIDecode", ...
    "nrPDCCHResources_coreset_search_space_candidate_mapping", ...
    true, 2, "8|8|4|2|1", "0|0|1", "-6.0|2.0|30.0", ...
    "nrChannelEstimate_pdcch_dmrs", ...
    "sixgr.phy.dl.PDCCH_Tx|sixgr.phy.dl.PDCCH_Rx", ...
    "real_pdcch_waveform_blind_dci_crc_evidence", ...
    true, true, true, true, true, true, false, ...
    'VariableNames', {'StrictOk','ProxyUsed','Skipped','ToolboxMissing','FallbackFlag','PlaceholderFlag', ...
    'DCICrcPass','PDCCHPayloadMatch','GrantValid', ...
    'CandidatesAttempted','PDCCHCandidatesAttempted','BlindDecodeCount', ...
    'PDCCHRECount','PDCCHDMRSRECount','PDCCHEncodedBits','PDCCHDCICrcRNTI','PDCCHScramblingRNTI', ...
    'PDCCHGridHash','PDCCHWaveformHash','PDCCHResourceHash', ...
    'PDCCHCRCDecodeSource','PDCCHBlindDecodeEvidenceSource','PDCCHCCE_REGMappingEvidence', ...
    'PDCCHREGMappingAvailable','PDCCHCORESETDuration','PDCCHSearchSpaceNumCandidates', ...
    'PDCCHCandidateDecodeOKVector','PDCCHCandidateSINRVector_dB', ...
    'ChannelEstimateSource','RuntimeEvidenceSource','TruthStatus', ...
    'StrictReceiverEvidenceOk','DecodeAttempted','DecodeUsable','ReceiverUsable', ...
    'DetectionAttempted','DetectionUsable','NegativeExpectedOk'});
end
