function ok = testLLSPUSCHHARQACKRuntimeFeedback()
%TESTLLSPUSCHHARQACKRUNTIMEFEEDBACK Verify causal DL ACK transfer on PUSCH.

setup6GRSimToolkit("Verbose", false);

rnti = 811;
dueSlot = 5;
harq = sixgr.l2.mac.HARQEntityDL(struct());
feedbackRows = repmat(localFeedbackRow(), 2, 1);
for bitIdx = 1:2
    sourceSlot = bitIdx;
    txp = harq.allocate(rnti, sourceSlot, 8, "NewData", true);
    harqId0 = double(txp.HARQ.HarqID);
    grant = struct( ...
        "Direction", "DL", "RNTI", rnti, "TBSBits", 64, ...
        "TBSBytes", 8, "HARQ", txp.HARQ, ...
        "HARQTBContext", struct("TBId", sprintf("DL-%d-%d-%d", ...
        rnti, sourceSlot, harqId0), "TBSBits", 64));
    harq.onTx(rnti, harqId0, zeros(64, 1, "uint8"), grant, sourceSlot);

    feedbackRows(bitIdx).Direction = "DL";
    feedbackRows(bitIdx).UEIndex = 1;
    feedbackRows(bitIdx).RNTI = rnti;
    feedbackRows(bitIdx).HarqID = harqId0;
    feedbackRows(bitIdx).SourceSlot = sourceSlot;
    feedbackRows(bitIdx).DueSlot = dueSlot;
    feedbackRows(bitIdx).Ack = bitIdx == 1;
    feedbackRows(bitIdx).CurrentDecodeOK = bitIdx == 1;
    feedbackRows(bitIdx).CombinedDecodeOK = bitIdx == 1;
    feedbackRows(bitIdx).ServingCell = 1;
    feedbackRows(bitIdx).BaseStationID = 1;
    feedbackRows(bitIdx).TBSBits = 64;
    feedbackRows(bitIdx).UCIBitCount = 1;
    feedbackRows(bitIdx).RequestedFormat = 1;
    feedbackRows(bitIdx).ResolvedFormat = 1;
    feedbackRows(bitIdx).PUCCHResourceId = sprintf("PUCCH-%d", bitIdx);
    feedbackRows(bitIdx).PUCCHPRBStart = bitIdx - 1;
    feedbackRows(bitIdx).PUCCHPRBCount = 1;
    feedbackRows(bitIdx).PUCCHSymbolStart = 12;
    feedbackRows(bitIdx).PUCCHNumSymbols = 2;
    feedbackRows(bitIdx).UCIType = "harq_ack";
    feedbackRows(bitIdx).ControlResourceSource = "focused_runtime_fixture";
    feedbackRows(bitIdx).ControlResourceValidity = true;
    feedbackRows(bitIdx).FormatAdaptationReason = "none_strict_assignment";
    feedbackRows(bitIdx).PUCCHGrantId = sprintf("PUCCH-GRANT-%d", bitIdx);
end

state = struct( ...
    "CurrentSlot", dueSlot, "CurrentFrame", 1, "CurrentSNR_dB", 20, ...
    "SlotsPerFrame", 10, "CfgMobility", struct( ...
    "run", struct("interferenceExecutionMode", "none")), ...
    "MultiUser", struct("Enabled", true), ...
    "DLHarq", harq, "DLCombinedLLR", {cell(1, harq.NumProcesses)}, ...
    "DLSchedulers", {{[]}}, ...
    "PendingFeedbackTable", struct2table(feedbackRows), ...
    "PUCCHGrantTraceTable", table(), "HARQTimelineTable", table(), ...
    "HARQSummaryTable", table());
state.DLCombinedLLR{1, 1} = ones(8, 1);
state.DLCombinedLLR{1, 2} = ones(8, 1);
for bitIdx = 1:2
    state = sixgr.truth.CoupledTruthRuntime.schedulePUCCHGrantRuntime( ...
        state, state.PendingFeedbackTable(bitIdx, :));
end

puschGrant = struct( ...
    "Direction", "UL", "UEIndex", 1, "RNTI", rnti, ...
    "GrantContextId", "UL-PUSCH-UCI-5", "Slot", dueSlot);
[state, puschGrant] = sixgr.truth.CoupledTruthRuntime. ...
    multiplexDueHARQACKOnPUSCHRuntime(state, puschGrant, dueSlot);
assert(logical(puschGrant.UCIOnPUSCHApplied) && ...
    isequal(int8(puschGrant.ExpectedUCIBits(:)), int8([1; 0])) && ...
    double(puschGrant.UCIOnPUSCHFeedbackBitCount) == 2, ...
    "All same-UE due DL HARQ bits must be placed on the qualified PUSCH grant.");
assert(all(string(state.PendingFeedbackTable.DeliveryMechanism) == "pusch_uci") && ...
    all(state.PUCCHGrantTraceTable.MultiplexedOnPUSCH) && ...
    isempty(sixgr.truth.CoupledTruthRuntime. ...
    pucchFeedbackDueHARQACKRuntime(state, dueSlot)), ...
    "Transferred feedback must be excluded from standalone PUCCH execution.");

harqOut = struct( ...
    "GrantSnapshot", puschGrant, ...
    "ExpectedHARQACKBits", int8([1; 0]), ...
    "DecodedHARQACKBits", int8([1; 1]), ...
    "HARQACKDecodeStatus", "decoded_mismatch", ...
    "HARQACKContentMatch", false);
state = sixgr.truth.CoupledTruthRuntime. ...
    applyDecodedPUSCHHARQACKRuntime(state, harqOut);
assert(all(state.PendingFeedbackTable.Processed), ...
    "PUSCH-decoded HARQ-ACK must close every exact pending feedback row.");
assert(double(state.DLHarq.Stats.Ack) == 2 && ...
    double(state.DLHarq.Stats.Nack) == 0, ...
    ["The DL HARQ entity must consume receiver-decoded bits. The second " ...
    "false ACK proves expected bits were not substituted."]);
assert(all(cellfun(@isempty, state.DLCombinedLLR(1, 1:2))), ...
    "Observed ACKs must clear the matching DL soft buffers.");
traceT = state.PUCCHGrantTraceTable;
assert(~any(traceT.GrantExecutedFlag) && ~any(traceT.PUCCHDecodeOk) && ...
    all(traceT.RuntimeStateUpdated) && all(traceT.MultiplexedOnPUSCH), ...
    "PUSCH UCI consumption must not be mislabeled as a PUCCH waveform execution.");
assert(string(traceT.Status(1)) == "PASS" && string(traceT.Status(2)) == "FAIL" && ...
    ~logical(traceT.FalseAck(1)) && logical(traceT.FalseAck(2)) && ...
    all(string(traceT.RuntimeStateConsumer) == ...
    "HARQEntity.onFeedback_from_PUSCH_UCI"), ...
    "Transferred UCI evidence must expose exact match and false-ACK outcomes per bit.");
canonicalTrace = sixgr.truth.CoupledTruthRuntime. ...
    canonicalizePersistedPUCCHGrantTraceTable(traceT);
assert(all(string(canonicalTrace.SourceClassification) == "active_integrated") && ...
    all(string(canonicalTrace.RuntimeMaterializationStatus) == ...
        "active_integrated_pusch_uci_feedback_runtime") && ...
    all(logical(canonicalTrace.ControlObservationAvailable)) && ...
    all(logical(canonicalTrace.FinalizedFlag)) && ...
    all(string(canonicalTrace.NAReason) == ...
        "not_applicable_feedback_observed_and_finalized") && ...
    all(string(canonicalTrace.ValueSource) == "runtime_pusch_uci_feedback_trace"), ...
    "Transferred PUSCH UCI grants must be finalized as observed runtime evidence, never pending PUCCH rows.");

missingBinding = rmfield(puschGrant, "UCIOnPUSCHFeedbackGrantIds");
badOut = harqOut;
badOut.GrantSnapshot = missingBinding;
localAssertError(@() sixgr.truth.CoupledTruthRuntime. ...
    applyDecodedPUSCHHARQACKRuntime(state, badOut), ...
    "sixgr:truth:MissingPUSCHHARQACKBinding");

ok = true;
fprintf("testLLSPUSCHHARQACKRuntimeFeedback: PASS\n");
end

function row = localFeedbackRow()
row = struct( ...
    "Direction", "", "UEIndex", NaN, "RNTI", NaN, ...
    "HarqID", NaN, "SourceSlot", NaN, "DueSlot", NaN, "Ack", false, ...
    "CurrentDecodeOK", false, "CombinedDecodeOK", false, ...
    "ServingCell", NaN, "BaseStationID", NaN, "TBSBits", NaN, ...
    "UCIBitCount", NaN, "RequestedFormat", NaN, "ResolvedFormat", NaN, ...
    "PUCCHResourceId", "", "PUCCHPRBStart", NaN, "PUCCHPRBCount", NaN, ...
    "PUCCHSymbolStart", NaN, "PUCCHNumSymbols", NaN, "UCIType", "", ...
    "ControlResourceSource", "", "ControlResourceValidity", false, ...
    "FormatAdaptationReason", "", "PUCCHGrantId", "", ...
    "DeliveryMechanism", "pucch", "PUSCHGrantContextId", "", ...
    "MultiplexedBitIndex", NaN, "Processed", false);
end

function localAssertError(f, expectedId)
threw = false;
try
    f();
catch ME
    threw = true;
    assert(string(ME.identifier) == string(expectedId), ...
        "Expected %s, received %s.", expectedId, ME.identifier);
end
assert(threw, "Expected typed error %s.", expectedId);
end
