function ok = testFRCPUSCHStandardSNRContract()
%TESTFRCPUSCHSTANDARDSNRCONTRACT Verify TS 38.104 UL slot-energy SNR.

setup6GRSimToolkit("Verbose", false, "RunToolboxChecks", false);
if ~localHaveRequired5G()
    warning("testFRCPUSCHStandardSNRContract:Missing5G", ...
        "Skipping TS 38.104 PUSCH SNR test because required 5G Toolbox APIs are unavailable.");
    ok = true;
    return;
end

typeA = localCheckMapping("A", 25, 15, [0, 14], 1, 381041);
assert(abs(typeA.PUSCHDataRECount - 3600) <= 1e-9 && ...
        abs(typeA.PUSCHDMRSRECount - 300) <= 1e-9 && ...
        typeA.TransmissionBandwidthNoiseEnergyRECount == 4200 && ...
        typeA.DataBearingSymbolCount == 12 && ...
        typeA.DMRSSymbolCount == 2, ...
    ("Type-A G-FR1 slot accounting must contain 3600 data RE, 300 " + ...
    "boosted DM-RS RE, and 4200 transmission-bandwidth noise RE."));

typeB = localCheckMapping("B", 66, 60, [0, 10], 0, 381042);
assert(abs(typeB.PUSCHDataRECount - 7128) <= 1e-9 && ...
        abs(typeB.PUSCHDMRSRECount - 396) <= 1e-9 && ...
        typeB.TransmissionBandwidthNoiseEnergyRECount == 7920 && ...
        typeB.DataBearingSymbolCount == 9 && ...
        typeB.DMRSSymbolCount == 1, ...
    ("Type-B G-FR2 slot accounting must contain 7128 data RE, 396 " + ...
    "boosted DM-RS RE, and 7920 transmission-bandwidth noise RE."));

rank4 = localCheckRank4Codebook(381043);
assert(abs(rank4.PUSCHDataRECount - 3600) <= 1e-9 && ...
        abs(rank4.PUSCHDMRSRECount - 300) <= 1e-9 && ...
        rank4.PUSCHRawDataPortIndexCount == 14400 && ...
        rank4.PUSCHRawDMRSPortIndexCount == 2400 && ...
        rank4.TransmissionBandwidthNoiseEnergyRECount == 4200 && ...
        rank4.NumLayers == 4 && rank4.NumAntennaPorts == 4 && ...
        rank4.TransmissionScheme == "codebook" && rank4.TPMI == 0 && ...
        abs(rank4.PrecoderTraceWWH - 1) <= 1e-12, ...
    ("G-FR1-A11-1 rank-4 TPMI-0 accounting must use 4200 units of " + ...
    "single-connector signal energy, not count zero-valued DM-RS port " + ...
    "entries or four codebook ports as four times the signal energy."));

fprintf("%s\n", "FRCPUSCHStandardSNRContract: TS 38.104 Type-A and " + ...
    "Type-B slot-energy SNR verified after OFDM demodulation.");
ok = true;
end

function info = localCheckRank4Codebook(seed)
carrier = nrCarrierConfig;
carrier.NCellID = 0;
carrier.NSizeGrid = 25;
carrier.NStartGrid = 0;
carrier.SubcarrierSpacing = 15;
carrier.CyclicPrefix = "normal";
carrier.NSlot = 0;

pusch = nrPUSCHConfig;
pusch.NSizeBWP = 25;
pusch.NStartBWP = 0;
pusch.PRBSet = 0:24;
pusch.SymbolAllocation = [0, 14];
pusch.MappingType = "A";
pusch.Modulation = "64QAM";
pusch.NumLayers = 4;
pusch.RNTI = 1;
pusch.NID = 0;
pusch.TransformPrecoding = false;
pusch.TransmissionScheme = "codebook";
pusch.NumAntennaPorts = 4;
pusch.TPMI = 0;
pusch.FrequencyHopping = "neither";
pusch.EnablePTRS = false;
pusch.DMRS.DMRSConfigurationType = 1;
pusch.DMRS.DMRSTypeAPosition = 2;
pusch.DMRS.DMRSAdditionalPosition = 1;
pusch.DMRS.DMRSLength = 1;
pusch.DMRS.NumCDMGroupsWithoutData = 2;
pusch.DMRS.DMRSPortSet = 0:3;
pusch.DMRS.NIDNSCID = 0;
pusch.DMRS.NSCID = 0;

[dataIndices, dataInfo] = nrPUSCHIndices(carrier, pusch, ...
    "IndexStyle", "index", "IndexBase", "1based");
dmrsIndices = nrPUSCHDMRSIndices(carrier, pusch, ...
    "IndexStyle", "index", "IndexBase", "1based");
codeword = int8(mod((0:(double(dataInfo.G) - 1)).', 2));
dataSymbols = nrPUSCH(carrier, pusch, codeword);
dmrsSymbols = nrPUSCHDMRS(carrier, pusch) .* sqrt(2);
txGrid = nrResourceGrid(carrier, 4);
txGrid(dataIndices) = dataSymbols;
txGrid(dmrsIndices) = dmrsSymbols;
txWaveform = nrOFDMModulate(carrier, txGrid, "Windowing", 0);

[~, codebookStatus, Wtx] = ...
    sixgr.phy.ul.puschCodebookProjectionMatrix(4, 4, 0, false);
precodeInfo = struct( ...
    "NativeCodebookApplied", true, ...
    "PMI", 0, ...
    "MatrixNR", Wtx, ...
    "CodebookStatus", string(codebookStatus), ...
    "Source", "ul_pusch_native_codebook_tpmi");
[~, info] = sixgr.conformance.addPUSCHReferenceNoise( ...
    txWaveform, carrier, pusch, 19.2, ...
    "DMRSPowerScale", 2, ...
    "PrecodeInfo", precodeInfo, ...
    "Seed", seed);
localAssertNear(info.NominalTotalSlotSignalEnergy, 4200, ...
    "rank-4 codebook total slot signal energy");
localAssertNear(info.StandardSNRToOccupiedDataREEsN0Offset_dB, 0, ...
    "rank-4 standard-to-data Es/N0 offset");
localAssertNear(info.ExpectedStandardSNRFromAppliedVariance_dB, 19.2, ...
    "rank-4 expected standard SNR");

try
    sixgr.conformance.addPUSCHReferenceNoise( ...
        txWaveform, carrier, pusch, 19.2, ...
        "DMRSPowerScale", 2, "Seed", seed);
catch cause
    assert(string(cause.identifier) == ...
        "sixgr:conformance:PUSCHPrecodeEvidenceRequired", ...
        "Missing codebook evidence must fail with the typed guard; got %s: %s.", ...
        string(cause.identifier), string(cause.message));
    return;
end
error("testFRCPUSCHStandardSNRContract:MissingCodebookEvidenceAccepted", ...
    "Codebook SNR accounting accepted missing runtime precoder evidence.");
end

function info = localCheckMapping( ...
        mappingType, nPRB, scs_kHz, symbolAllocation, additionalPosition, seed)
carrier = nrCarrierConfig;
carrier.NCellID = 0;
carrier.NSizeGrid = nPRB;
carrier.NStartGrid = 0;
carrier.SubcarrierSpacing = scs_kHz;
carrier.CyclicPrefix = "normal";
carrier.NSlot = 0;

pusch = nrPUSCHConfig;
pusch.NSizeBWP = nPRB;
pusch.NStartBWP = 0;
pusch.PRBSet = 0:(nPRB - 1);
pusch.SymbolAllocation = symbolAllocation;
pusch.MappingType = char(mappingType);
pusch.Modulation = "QPSK";
pusch.NumLayers = 1;
pusch.RNTI = 1;
pusch.NID = 0;
pusch.TransformPrecoding = false;
pusch.TransmissionScheme = "nonCodebook";
pusch.NumAntennaPorts = 1;
pusch.FrequencyHopping = "neither";
pusch.EnablePTRS = false;
pusch.DMRS.DMRSConfigurationType = 1;
pusch.DMRS.DMRSTypeAPosition = 2;
pusch.DMRS.DMRSAdditionalPosition = additionalPosition;
pusch.DMRS.DMRSLength = 1;
pusch.DMRS.NumCDMGroupsWithoutData = 2;
pusch.DMRS.DMRSPortSet = 0;
pusch.DMRS.NIDNSCID = 0;
pusch.DMRS.NSCID = 0;

[dataIndices, dataInfo] = nrPUSCHIndices(carrier, pusch, ...
    "IndexStyle", "index", "IndexBase", "1based");
dmrsIndices = nrPUSCHDMRSIndices(carrier, pusch, ...
    "IndexStyle", "index", "IndexBase", "1based");
codeword = int8(mod((0:(double(dataInfo.G) - 1)).', 2));
dataSymbols = nrPUSCH(carrier, pusch, codeword);
dmrsSymbols = nrPUSCHDMRS(carrier, pusch) .* sqrt(2);

txGrid = nrResourceGrid(carrier, 1);
txGrid(dataIndices) = dataSymbols;
txGrid(dmrsIndices) = dmrsSymbols;
txWaveform = nrOFDMModulate(carrier, txGrid, "Windowing", 0);

% Average independent connector-noise realizations in one call. This keeps
% the realized post-demodulation estimate much tighter than the 0.05 dB
% regression tolerance without normalizing individual noise realizations.
nRealizations = 64;
txWaveforms = repmat(txWaveform, 1, nRealizations);
requestedStandardSNR_dB = 7.25;
[rxWaveforms, info] = sixgr.conformance.addPUSCHReferenceNoise( ...
    txWaveforms, carrier, pusch, requestedStandardSNR_dB, ...
    "DMRSPowerScale", 2, "Seed", seed);

noiseGrid = nrOFDMDemodulate(carrier, rxWaveforms - txWaveforms);
signalGrid = nrOFDMDemodulate(carrier, txWaveform);
symbols = symbolAllocation(1) + (1:symbolAllocation(2));
signalEnergy = sum(abs(signalGrid(:, symbols, 1)).^2, "all");
noiseEnergyPerConnector = sum(abs(noiseGrid(:, symbols, :)).^2, "all") / ...
    nRealizations;
measuredStandardSNR_dB = ...
    10 * log10(signalEnergy / noiseEnergyPerConnector);
delta_dB = measuredStandardSNR_dB - requestedStandardSNR_dB;

assert(abs(signalEnergy - info.NominalTotalSlotSignalEnergy) <= ...
        1e-10 * info.NominalTotalSlotSignalEnergy, ...
    ("Type-%s actual post-demodulation PUSCH+DM-RS energy %.15g " + ...
    "does not match the index/EPRE accounting %.15g."), ...
    mappingType, signalEnergy, info.NominalTotalSlotSignalEnergy);
assert(abs(delta_dB) < 0.05, ...
    ("TS 38.104 Type-%s PUSCH SNR missed after OFDM demodulation: " + ...
    "requested %.4f dB, measured %.4f dB, delta %.4f dB."), ...
    mappingType, requestedStandardSNR_dB, ...
    measuredStandardSNR_dB, delta_dB);
localAssertNear(info.RequestedStandardSNR_dB, ...
    requestedStandardSNR_dB, mappingType + " requested standard SNR");
localAssertNear(info.ExpectedStandardSNRFromAppliedVariance_dB, ...
    requestedStandardSNR_dB, mappingType + " expected standard SNR");
localAssertNear(info.NominalTotalSlotSignalEnergy, ...
    info.TransmissionBandwidthNoiseEnergyRECount, ...
    mappingType + " total slot signal energy");
localAssertNear(info.StandardSNRToOccupiedDataREEsN0Offset_dB, 0, ...
    mappingType + " standard-to-data Es/N0 offset");
localAssertNear(info.EquivalentOccupiedDataREEsN0_dB, ...
    requestedStandardSNR_dB, mappingType + " equivalent data Es/N0");
assert(info.DMRSPowerScaleRelativeToData == 2 && ...
        info.DMRSEPRESameUnits == 2 && ...
        ~logical(info.WaveformPowerUsed) && ...
        ~logical(info.InstantaneousFadingPowerUsed), ...
    ("TS 38.104 PUSCH provenance must disclose exact beta^2=2 and " + ...
    "must not normalize noise from instantaneous waveform/fading power."));
assert(string(info.Standard) == "3GPP TS 38.104 V18.13.0" && ...
        all(ismember(["8.1.1", "11.1.1"], string(info.StandardClauses))), ...
    "TS 38.104 PUSCH noise provenance must cite the governing SNR clauses.");
end

function localAssertNear(actual, expected, label)
tolerance = max(1e-12, 64 * eps(max(abs(double(expected)), 1)));
assert(abs(double(actual) - double(expected)) <= tolerance, ...
    "%s %.15g does not match expected %.15g.", ...
    label, double(actual), double(expected));
end

function tf = localHaveRequired5G()
tf = exist("nrCarrierConfig", "class") == 8 && ...
    exist("nrPUSCHConfig", "class") == 8 && ...
    exist("nrPUSCH", "file") == 2 && ...
    exist("nrPUSCHIndices", "file") == 2 && ...
    exist("nrPUSCHDMRS", "file") == 2 && ...
    exist("nrPUSCHDMRSIndices", "file") == 2 && ...
    exist("nrOFDMModulate", "file") == 2 && ...
    exist("nrOFDMDemodulate", "file") == 2;
end
