function ok = testTDDCausalFourStepRARuntimeTiming(runtimeSlot)
%TESTTDDCAUSALFOURSTEPRARUNTIMETIMING Guard the shared RA timing boundary.
%
% The test uses the production TDD causal-wiring YAML, a concrete CDL-A
% runtime channel, physical antenna expansion, thermal receiver noise, and
% the real Msg1/Msg2/Msg3/Msg4/RRCSetupComplete waveform chain.  It proves
% that decoded Msg1 timing advance establishes Msg3 timing and that the
% PUSCH receiver does not apply a second DM-RS timing shift.

if nargin < 1, runtimeSlot = 2; end
scenarioPath = fullfile("simulator", "configs", "scenarios", ...
    "lls_causal_access_to_data_wiring_tdd.yaml");
scfg = sixgr.lls6g.config.loadScenarioConfig(scenarioPath);
runRoot = tempname;
mkdir(runRoot);
cleanup = onCleanup(@() localCleanup(runRoot)); %#ok<NASGU>
cfg = sixgr.config.normalizeConfig( ...
    sixgr.lls6g.buildInternalConfig(scfg, runRoot));

assert(strcmpi(string(sixgr.util.structGet(cfg, "phy.duplex.mode", "")), "TDD"), ...
    "The timing regression must exercise the YAML-selected TDD profile.");
assert(strcmpi(string(sixgr.util.structGet(cfg, "channel.model", "")), "CDL") && ...
        strcmpi(string(sixgr.util.structGet(cfg, "channel.cdlProfile", "")), "CDL-A") && ...
        strcmpi(string(sixgr.util.structGet(cfg, "channel.fading.profile", "")), "CDL-A"), ...
    "The timing regression must use the concrete configured CDL-A channel.");

multiUser = struct("Enabled", true, "NumUsers", 1, "RNTIStart", 1, ...
    "ExecutionModel", "slot_coupled_truth");
state = sixgr.truth.CoupledTruthRuntime.initialize( ...
    cfg, runRoot, multiUser, struct(), 1);
state.CurrentSlot = runtimeSlot;
state.CurrentServingIdx(:) = 1;
[cfgRuntime, ~] = sixgr.truth.CoupledTruthRuntime.applyUserContext( ...
    cfg, state, 1, "UL");

% Reuse a previously materialized downlink channel, as the real SSB->RA
% transition does. Both direction views refer to one physical fading clock.
[state, dlState] = sixgr.truth.CoupledTruthRuntime.acquireRuntimeChannelStateForControl( ...
    state, cfgRuntime, 1, "DL");
[carrier, ~] = sixgr.phy.grid.makeCarrier(cfgRuntime);
txInfo = struct("OFDM", nrOFDMInfo(carrier));
nBS = double(cfgRuntime.lls6g.userContext.RuntimeServingBSAntennaMeta.NumElements);
nUE = double(cfgRuntime.lls6g.userContext.RuntimeUEAntennaMeta.NumElements);
dlState = sixgr.channel.ChannelFactory.materializeRuntimeChannelState( ...
    dlState, cfgRuntime, complex(zeros(128, nBS)), txInfo, ...
    "NumTxAnt", nBS, "NumRxAnt", nUE, ...
    "TransmitAntennaRuntime", cfgRuntime.lls6g.userContext.RuntimeServingBSAntenna, ...
    "ReceiveAntennaRuntime", cfgRuntime.lls6g.userContext.RuntimeUEAntenna, ...
    "TransmitAntennaMeta", cfgRuntime.lls6g.userContext.RuntimeServingBSAntennaMeta, ...
    "ReceiveAntennaMeta", cfgRuntime.lls6g.userContext.RuntimeUEAntennaMeta);
state = sixgr.truth.CoupledTruthRuntime.commitRuntimeChannelState(state, dlState);
[~, ulState] = sixgr.truth.CoupledTruthRuntime.acquireRuntimeChannelStateForControl( ...
    state, cfgRuntime, 1, "UL");

[result, continuation] = sixgr.truth.CoupledTruthRuntime.runFourStepRARuntime(cfgRuntime, ...
    "RunFolder", runRoot, "RunId", "tdd_causal_ra_timing", ...
    "ScenarioName", "tdd_causal_ra_timing", ...
    "UEId", 1, "CellId", 1, "AttemptId", 1, ...
    "RuntimeNoiseSNR_dB", 12, ...
    "InitialDLChannelState", dlState, "InitialULChannelState", ulState, ...
    "RuntimeSlot", runtimeSlot, "WriteArtifacts", false, "StageAction", "prepare_next_stage");
assert(result.PreparedTransmission.AbsoluteSlot >= runtimeSlot-1, ...
    "A new RA attempt must not prepare an already elapsed PRACH occasion.");
assert(result.RuntimeExecutionState == "pending_stage_receive" && ...
    isempty(result.RuntimeStageRows) && ~result.RACompleted && ~result.RRCConnected && ...
    result.RuntimeDLChannelState.CurrentSampleIndex == dlState.CurrentSampleIndex, ...
    "Preparing Msg1 must not propagate future samples or assert receiver success.");
assert(isequaln(result.RuntimeDLChannelState, dlState) && ...
    isequaln(result.RuntimeULChannelState, ulState), ...
    "Preparation must preserve complete channel identities, objects, and clocks, not empty result defaults.");
for completed = 0:4
    priorRows = result.RuntimeStageRows;
    nextStage = result.NextRuntimeStage;
    nextSlot = result.NextRuntimeStageSlot;
    transmission = result.PreparedTransmission;
    clockBefore = result.RuntimeDLChannelState.CurrentSampleIndex;
    objectInputBefore = result.RuntimeDLChannelState.TotalObjectInputSamples;
    rngBefore = rng;
    [waiting, continuation] = sixgr.truth.CoupledTruthRuntime.runFourStepRARuntime(cfgRuntime, ...
        "Continuation", continuation, "ReceiveThroughTime_s", ...
        transmission.EndTimeExclusive_s - 1/transmission.SampleRate_Hz);
    assert(waiting.RuntimeExecutionState == "pending_stage_receive" && ...
        isequaln(waiting.RuntimeStageRows, priorRows) && ...
        waiting.RuntimeDLChannelState.CurrentSampleIndex == clockBefore && ...
        waiting.RuntimeULChannelState.CurrentSampleIndex == clockBefore && ...
        waiting.RuntimeDLChannelState.TotalObjectInputSamples == objectInputBefore && ...
        isequaln(rng, rngBefore), ...
        "An incomplete receive interval must not advance the shared CDL object, consume noise, or publish a decode.");
    [result, continuation] = sixgr.truth.CoupledTruthRuntime.runFourStepRARuntime(cfgRuntime, ...
        "Continuation", continuation, "StopAfterStage", nextStage, ...
        "ReceiveThroughTime_s", transmission.EndTimeExclusive_s, ...
        "RuntimeSlot", nextSlot+1, ...
        "InitialDLChannelState", result.RuntimeDLChannelState, ...
        "InitialULChannelState", result.RuntimeULChannelState);
    assert(height(result.RuntimeStageRows) == completed+1 && ...
        isequaln(priorRows, result.RuntimeStageRows(1:completed,:)), ...
        "Resuming the physical TDD channel must not repeat or rewrite completed stage execution (completed=%d, received=%d).", ...
        completed, height(result.RuntimeStageRows));
    if completed < 4
        decodedClock = result.RuntimeDLChannelState.CurrentSampleIndex;
        decodedRows = result.RuntimeStageRows;
        [result, continuation] = sixgr.truth.CoupledTruthRuntime.runFourStepRARuntime(cfgRuntime, ...
            "Continuation", continuation, "StageAction", "prepare_next_stage");
        assert(result.RuntimeExecutionState == "pending_stage_receive" && ...
            result.RuntimeDLChannelState.CurrentSampleIndex == decodedClock && ...
            isequaln(result.RuntimeStageRows, decodedRows), ...
            "Preparing the next RA stage must not advance the physical fading clock or add received evidence.");
    end
end
assert(isempty(fieldnames(continuation)) && result.RuntimeExecutionState == "terminal");

assert(logical(result.RACompleted) && logical(result.StrictOk), ...
    "The TDD measured four-step RA waveform chain must complete strictly.");
assert(logical(result.Msg3PUSCHCrcPass), ...
    "Msg3 PUSCH must decode through the production CDL-A receiver chain.");
assert(logical(result.Msg3TimingAdvanceApplied), ...
    "Msg3 must consume the timing advance decoded from Msg1/RAR state.");
assert(~logical(result.Msg3TimingEstimateUsed), ...
    "An already TA-aligned Msg3 waveform must not perform duplicate DM-RS timing acquisition.");
assert(abs(double(result.Msg3AppliedTimingCorrection_samples)) < 1e-12, ...
    "An already TA-aligned Msg3 waveform must receive zero duplicate timing correction.");
assert(string(result.Msg3TimingEstimateSource) == ...
        "runtime_aligned_waveform_no_timing_reacquisition", ...
    "Msg3 timing provenance must identify the established runtime alignment boundary.");
assert(logical(result.Msg3ChannelEstimateAvailable) && ...
        logical(result.Msg3EqualizationAvailable) && ...
        logical(result.Msg3LLRFinite), ...
    "Msg3 must retain measured channel-estimation, equalization, and finite-LLR evidence.");
assert(~logical(result.ProxyUsed) && ~logical(result.Skipped), ...
    "The TDD RA timing regression must not use proxy or skipped evidence.");
assert(logical(result.RuntimeStageWaveformsRequired) && ...
        logical(result.RuntimeStageWaveformsUsed) && ...
        logical(result.RuntimeChannelStateUsed) && ...
        ~logical(result.RuntimeSelfLoopWaveformsUsed), ...
    ["The timing regression must propagate every RA stage through the " ...
    "configured runtime channel; a self-loop waveform is not acceptable."]);

% The shared object's input clock must not be advanced twice using stale
% direction-specific counters when Msg1/2/3/4 alternate UL and DL.
final = result.RuntimeULChannelState;
assert(final.TotalObjectInputSamples == final.WarmupSamples + final.CurrentSampleIndex, ...
    "RA must maintain one exact shared channel input clock across all stages.");
assert(result.RuntimeDLChannelState.CurrentSampleIndex == final.CurrentSampleIndex, ...
    "Both returned TDD direction views must expose the final canonical clock.");

% Counter agreement alone is insufficient: both views could agree on the
% wrong absolute epoch. Check each executed waveform against its declared
% zero-based stage slot, using the actual OFDM sample rate.
stages = result.RuntimeStageRows;
assert(height(stages) == 5, "All five executed RA/RRC stages need timing evidence.");
fs = double(txInfo.OFDM.SampleRate);
expectedStart = round(double(stages.StageSlot) * sixgr.time.slotDurationSec(cfgRuntime) * fs);
assert(all(double(stages.RuntimeChannelStartSample) == expectedStart), ...
    "RA waveform samples must start at their scheduled absolute slot, not a silently clamped later time.");
assert(all(double(stages.RuntimeChannelEndSample) - ...
    double(stages.RuntimeChannelStartSample) == double(stages.TxSampleCount)), ...
    "RA sample intervals must equal the actual transmitted waveform lengths.");

% Bind the access ledger to these actual executed waveform coordinates,
% rather than reconstructing stage times from the current caller slot.
trial = struct("Status", "PASS", "CRCPass", NaN, "Slot", stages.StageSlot(end)+1, ...
    "FullRAEvidenceSource", "sixgr.phy.ra.runFourStepRA");
for name = ["RASlotTimeBase", "Msg1ScheduledSlot", "Msg2ScheduledSlot", ...
        "Msg3ScheduledSlot", "Msg4ScheduledSlot", "SetupCompleteScheduledSlot", ...
        "RACompleted", "RequireRRCSetupComplete", "RRCSetupRequestDecoded", ...
        "RRCSetupDecoded", "SRB1Installed", "RRCSetupCompleteCRC", ...
        "RRCSetupCompleteDecoded", "RRCConnected", "RRCSetupCompletePayloadSHA256"]
    trial.(name) = result.(name);
end
state.CurrentSlot = trial.Slot;
state = sixgr.truth.CoupledTruthRuntime.applyPRACHTrial(state, 1, struct2table(trial));
events = state.InitialAccessLifecycleTraceTable;
raEvents = ["PRACH_MSG1_DETECTED", "MSG2_RAR_DECODED", "MSG3_PUSCH_COMPLETED", ...
    "MSG4_CONTENTION_RESOLUTION_COMPLETED", "RRC_SETUP_COMPLETE_ACCEPTED"];
for k = 1:numel(raEvents)
    event = events(string(events.EventName) == raEvents(k), :);
    assert(height(event) == 1 && event.SourceRASlot == stages.StageSlot(k) && ...
        event.SourceRASlotTimeBase == "absolute_zero_based" && ...
        event.CanonicalSlot == stages.StageSlot(k)+1 && ...
        event.Slot == stages.StageSlot(k)+1, ...
        "The lifecycle event must identify its actual received RA stage, with an explicit zero-to-one-based conversion.");
end

% Physical clock agreement must be paired with legal duplex allocations.
ra = sixgr.mac.ra.RAConfig(cfgRuntime, "RuntimeSlot", runtimeSlot);
frame = sixgr.phy.FrameStructureEngine(cfgRuntime,"FrameCoreOnly",true);
assert(frame.IsDLAllocation(ra.Msg2Slot,[ra.Msg2PDSCH.SymbolStart ra.Msg2PDSCH.NumSymbols]));
assert(frame.IsULAllocation(ra.Msg3Slot,[ra.Msg3PUSCH.SymbolStart ra.Msg3PUSCH.NumSymbols]));
assert(frame.IsDLAllocation(ra.Msg4Slot,[ra.Msg4PDSCH.SymbolStart ra.Msg4PDSCH.NumSymbols]));
assert(frame.IsULAllocation(ra.SetupCompleteSlot,[ra.SetupCompletePUSCH.SymbolStart ra.SetupCompletePUSCH.NumSymbols]));
assert(ra.Msg3Slot == ra.Msg2Slot + ra.TimingSchedule.Msg3K2Slots + ...
    ra.TimingSchedule.Msg3AdditionalDelaySlots);

ok = true;
fprintf(['PASS testTDDCausalFourStepRARuntimeTiming: TDD Msg3 consumed ' ...
    'decoded TA and passed the measured CDL-A receiver without duplicate timing correction.\n']);
end

function localCleanup(pathText)
if isfolder(pathText)
    rmdir(pathText, "s");
end
end
