function ok = testLLSCoupledTruthBootstrapCQIPreview()
%TESTLLSCOUPLEDTRUTHBOOTSTRAPCQIPREVIEW Keep preview bootstrap labeled and rank-safe.

setup6GRSimToolkit("Verbose", false);

tmp = tempname;
mkdir(tmp);
c = onCleanup(@() rmdir(tmp, "s")); %#ok<NASGU>

scenarioPath = fullfile(pwd, "simulator", "configs", "scenarios", ...
    "lls_3gpp_rel20_anchor_4ghz_100mhz_waveform_honest_200ue_1frame.yaml");
scfg = sixgr.lls6g.config.loadScenarioConfig(scenarioPath);
cfg = sixgr.lls6g.buildInternalConfig(scfg, fullfile(tmp, "run"));

multiUser = struct( ...
    "Enabled", true, ...
    "NumUsers", 2, ...
    "RNTIStart", 401, ...
    "SeedStride", 17, ...
    "ExecutionModel", "slot_coupled_truth");
state = sixgr.truth.CoupledTruthRuntime.initialize(cfg, fullfile(tmp, "run"), multiUser, struct(), 1);
state.CurrentServingIdx(:) = 1;
state.LargeScaleState.RxPower_dBm(1, :) = -140;
state.LargeScaleState.RxPower_dBm(1, 1) = -60;

fb = sixgr.truth.CoupledTruthRuntime.latestFeedbackForDirectionRuntime(state, 1, "DL");

assert(~logical(fb.Valid), ...
    "Preview bootstrap before the first real CSI report must remain marked invalid as measured CSI.");
assert(double(fb.CQI) > 0 && double(fb.MCSIndex) > 0 && ...
    logical(sixgr.util.structGet(fb, "BootstrapCQIUsableForScheduling", false)), ...
    "Explicit large-scale-preview bootstrap must provide scheduler CQI/MCS while staying separate from measured CSI.");
assert(isfinite(double(sixgr.util.structGet(fb, "PreviewCQI", NaN))) && ...
    isfinite(double(sixgr.util.structGet(fb, "PreviewMCSIndex", NaN))), ...
    "Preview diagnostics must retain the large-scale CQI/MCS estimate without feeding scheduler AMC.");
assert(strcmpi(char(string(fb.BootstrapCQISource)), "bootstrap_large_scale_interference_preview_cqi"), ...
    "Scheduler-facing bootstrap source must disclose large-scale interference-preview provenance.");
assert(strcmpi(char(string(sixgr.util.structGet(fb, "PreviewCQISource", ""))), ...
    "bootstrap_large_scale_interference_preview_cqi"), ...
    "Large-scale CQI preview must be explicitly labeled as bootstrap geometry evidence.");
assert(isfinite(double(fb.PreviewSINR_dB)) && ~isfinite(double(fb.SINR_dB)), ...
    "Preview bootstrap must keep geometry-preview SINR separate from measured SINR.");
assert(double(fb.RI) == 1, ...
    "Preview bootstrap RI must stay rank-1 until measured RI is available.");

ok = true;
end
