function ok = testLLSAdaptiveDiagnosticArtifactCompletenessScope()
%TESTLLSADAPTIVEDIAGNOSTICARTIFACTCOMPLETENESSSCOPE Publication-only plots do not gate diagnostics.

setup6GRSimToolkit("Verbose", false);
ctx = llsRootGateFixture("adaptive_link");

% This report remains an honest publication-readiness diagnostic.  Its
% failed access-delay CDF requirement must not become a run-level failure
% for an adaptive-system diagnostic, whose canonical runtime artifacts are
% governed by the runtime truth and artifact-contract gates instead.
T = table("reports/image/access_delay_cdf.png", 1, false, ...
    "mandatory_publication_artifact_missing", ...
    'VariableNames', {'MissingArtifacts','RequiredArtifactCount', ...
    'ArtifactCompletenessOk','FailureReason'});
sixgr.util.csvWriteTable(fullfile(ctx.Layout.ReportCSVDir, ...
    "artifact_completeness_summary.csv"), T);

scfg = sixgr.util.structSet(ctx.ScenarioConfig, ...
    "validation.RunClass", "adaptive_system_diagnostic");
verdict = struct("Failures", strings(0, 1), ...
    "CanonicalArtifactGapCount", 0, "RoundtripMismatchCount", 0, ...
    "CheckDetails", struct());
root = sixgr.truth.evaluateStrictAnchorStatus(ctx.RunFolder, scfg, ...
    ctx.InternalConfig, verdict, table(), table(), struct());

assert(logical(root.Status.ArtifactCompletenessOk), ...
    "Publication-only image requirements contaminated adaptive diagnostic status.");
assert(~contains(string(root.Status.ResultStatusReason), ...
    "required_artifacts_missing_or_incomplete"), ...
    "Adaptive diagnostic status retained a publication-only completeness failure.");

% Fixed anchors remain fail-closed against the same persisted publication
% report; the scope distinction must not weaken publication qualification.
fixed = llsRootGateFixture("pass");
sixgr.util.csvWriteTable(fullfile(fixed.Layout.ReportCSVDir, ...
    "artifact_completeness_summary.csv"), T);
fixedVerdict = sixgr.truth.evaluateLLSRuntimeTruthContract( ...
    fixed.RunFolder, fixed.ScenarioConfig, fixed.InternalConfig);
assert(~logical(fixedVerdict.ResultStatus.ArtifactCompletenessOk), ...
    "Fixed-link publication scope accepted a missing mandatory image.");

ok = true;
fprintf("PASS testLLSAdaptiveDiagnosticArtifactCompletenessScope: diagnostic and publication artifact scopes remain distinct.\n");
end
