function ok = testLLSFunctionalWaveformValidationClass()
%TESTLLSFUNCTIONALWAVEFORMVALIDATIONCLASS Bound waveform evidence is not publication evidence.

setup6GRSimToolkit("Verbose", false);

passCtx = llsRootGateFixture("pass");
[passScenario, passCfg] = localDeclareFunctionalClass( ...
    passCtx.ScenarioConfig, passCtx.InternalConfig);
passVerdict = sixgr.truth.evaluateLLSRuntimeTruthContract( ...
    passCtx.RunFolder, passScenario, passCfg);
classT = readtable(fullfile(passCtx.Layout.ReportCSVDir, ...
    "run_classification.csv"), "VariableNamingRule", "preserve", ...
    "TextType", "string");
statusT = readtable(fullfile(passCtx.Layout.ReportCSVDir, ...
    "result_status_summary.csv"), "VariableNamingRule", "preserve", ...
    "TextType", "string");

assert(logical(passVerdict.Ok), ...
    "Complete bounded actual-waveform evidence must pass its functional truth contract.");
assert(string(classT.RunClass(1)) == "functional_waveform_validation", ...
    "The explicit functional waveform run class must remain authoritative.");
assert(~logical(classT.PublicationLLSEligible(1)), ...
    "Bounded functional waveform evidence must never be publication-eligible.");
assert(logical(statusT.RunClassGateOk(1)) && ...
    logical(statusT.ScenarioObjectiveOk(1)), ...
    "Functional validation must retain strict run-class and configured/effective gates.");

mismatchCtx = llsRootGateFixture("configured_effective_mismatch");
[mismatchScenario, mismatchCfg] = localDeclareFunctionalClass( ...
    mismatchCtx.ScenarioConfig, mismatchCtx.InternalConfig);
mismatchVerdict = sixgr.truth.evaluateLLSRuntimeTruthContract( ...
    mismatchCtx.RunFolder, mismatchScenario, mismatchCfg);
mismatchStatus = readtable(fullfile(mismatchCtx.Layout.ReportCSVDir, ...
    "result_status_summary.csv"), "VariableNamingRule", "preserve", ...
    "TextType", "string");
assert(~logical(mismatchVerdict.Ok) && ...
    ~logical(mismatchStatus.ConfiguredEffectiveOk(1)) && ...
    ~logical(mismatchStatus.ScenarioObjectiveOk(1)), ...
    "The functional run class may relax publication sample adequacy only; " + ...
    "it must still fail configured/effective waveform mismatches.");

ok = true;
end

function [scfg, cfg] = localDeclareFunctionalClass(scfg, cfg)
scfg = sixgr.util.structSet(scfg, "validation.RunClass", ...
    "functional_waveform_validation");
scfg = sixgr.util.structSet(scfg, "validation.run_class", ...
    "functional_waveform_validation");
cfg = sixgr.util.structSet(cfg, "validation.RunClass", ...
    "functional_waveform_validation");
cfg = sixgr.util.structSet(cfg, "validation.run_class", ...
    "functional_waveform_validation");
end
