function ok = testFRCSerialParallelDeterminism()
%TESTFRCSERIALPARALLELDETERMINISM Exact FRC TB sharding is reproducible.

setup6GRSimToolkit("Verbose",false,"RunToolboxChecks",false);
if ~license('test','Distrib_Computing_Toolbox')
    error("sixgr:tests:ParallelQualificationUnavailable", ...
        "Parallel Computing Toolbox is required by this focused test.");
end
args = {"ExecutionProfile","full", ...
    "EvaluateSymmetricRegression",false, ...
    "MinTransportBlocks",2,"MaxTransportBlocks",2,"BatchSize",2, ...
    "MinimumBlockErrors",0,"Seed",38104, ...
    "PrintTable",false,"Verbose",false};
serial = sixgr.conformance.runFRCPoint( ...
    "dl_r_pdsch_1_1_4_fdd_awgn","awgn_static_1x2",args{:}, ...
    "ParallelWorkers",0);
parallel = sixgr.conformance.runFRCPoint( ...
    "dl_r_pdsch_1_1_4_fdd_awgn","awgn_static_1x2",args{:}, ...
    "ParallelWorkers",2);

a = serial.PointDetails{1}.TransportBlockAudit;
b = parallel.PointDetails{1}.TransportBlockAudit;
assert(isequaln(serial.Sweep,parallel.Sweep) && ...
    isequaln(a.Delivered,b.Delivered) && ...
    isequaln(a.Attempts,b.Attempts) && ...
    isequaln(a.NoiseSeedByAttempt,b.NoiseSeedByAttempt) && ...
    isequaln(a.RVByAttempt,b.RVByAttempt) && ...
    isequaln(a.AbsoluteSlotByAttempt,b.AbsoluteSlotByAttempt) && ...
    isequaln(a.ChannelStartSampleByAttempt,b.ChannelStartSampleByAttempt), ...
    "Serial and parallel FRC transport-block evidence must be identical.");
assert(isequaln(serial.PointDetails{1}.FirstTransmission, ...
        parallel.PointDetails{1}.FirstTransmission) && ...
    isequaln(serial.PointDetails{1}.LastReceiver, ...
        parallel.PointDetails{1}.LastReceiver), ...
    "Serial and parallel FRC Tx/Rx evidence must be bit-for-bit identical.");
assert(parallel.PointDetails{1}.ParallelExecution && ...
    parallel.PointDetails{1}.ParallelPoolWorkers >= 2, ...
    "Parallel FRC evidence must disclose the active worker count.");
ok = true;
end
