function ok = testUCIOnPUSCHYAMLAuthority()
%TESTUCIONPUSCHYAMLAUTHORITY Prove both YAML boolean states reach runtime.

scenarioRoot = fullfile(pwd, "simulator", "configs", "scenarios");
enabledPath = fullfile(scenarioRoot, ...
    "webgui_sinr_plus20_2x2_mu_mimo_wiring_gate.yaml");
disabledPath = fullfile(scenarioRoot, ...
    "webgui_sinr_plus20_64x4_mu_mimo_quick_truth.yaml");

enabledScenario = sixgr.lls6g.config.loadScenarioConfig(enabledPath);
disabledScenario = sixgr.lls6g.config.loadScenarioConfig(disabledPath);
assert(logical(enabledScenario.get( ...
    "pucch_resources.overlap_policy.uci_on_pusch_enabled")));
assert(~logical(disabledScenario.get( ...
    "pucch_resources.overlap_policy.uci_on_pusch_enabled")));

tmp = tempname();
mkdir(tmp);
cleanupTmp = onCleanup(@() localRemove(tmp)); %#ok<NASGU>
enabledCfg = sixgr.lls6g.buildInternalConfig( ...
    enabledScenario, fullfile(tmp, "enabled"));
disabledCfg = sixgr.lls6g.buildInternalConfig( ...
    disabledScenario, fullfile(tmp, "disabled"));

assert(logical(enabledCfg.phy.pucch.uciOnPUSCHEnabled) && ...
    string(enabledCfg.phy.pusch.uciMultiplexingMode) == ...
        "harq_ack_on_pusch_when_pucch_collides" && ...
    string(enabledCfg.mac.scheduler.uciMultiplexingMode) == ...
        "harq_ack_on_pusch_when_pucch_collides", ...
    "YAML true must explicitly enable UCI-on-PUSCH in PHY and scheduler runtime.");
assert(~logical(disabledCfg.phy.pucch.uciOnPUSCHEnabled) && ...
    string(disabledCfg.phy.pusch.uciMultiplexingMode) == "pucch_only" && ...
    string(disabledCfg.mac.scheduler.uciMultiplexingMode) == "pucch_only", ...
    "YAML false must explicitly disable UCI-on-PUSCH in PHY and scheduler runtime.");

ok = true;
end

function localRemove(root)
if isfolder(root)
    rmdir(root, "s");
end
end
