function ok = testLLSHARQFailureRateTruth()
%TESTLLSHARQFAILURERATETRUTH Keep HARQ failure semantics separate from BLER aliases.

setup6GRSimToolkit("Verbose", false);

harqTimelineT = table( ...
    ["DL"; "DL"; "UL"], ...
    [1; 1; 1], ...
    [false; true; true], ...
    'VariableNames', {'Direction','UEIndex','CombinedDecodeOK'});

tmp = tempname;
mkdir(tmp);
c = onCleanup(@() rmdir(tmp, "s")); %#ok<NASGU>

cfg = sixgr.config.defaultConfig();
dlRaw = table( ...
    [1; 1], [320; 320], [10; 10], [1; 2], [1; 1], [0; 1], [0; 0], [128; 128], [0; 0], [6; 6], [6; 6], [0; 0], ...
    ["FAIL"; "PASS"], [0; 0], [false; false], [false; false], ...
    'VariableNames', {'UEIndex','RNTI','SNR_dB','Frame','Slot','CRCPass','BitErrors','BitsCompared','Goodput_Mbps','ReceiverHestSINR_dB','MeasuredSINR_dB','ChannelGain_dB','Status','Crash','HARQCurrentDecodeOK','HARQCombinedDecodeOK'});
ulRaw = table( ...
    1, 320, 10, 1, 1, 1, 0, 128, 0, 8, 8, 0, "PASS", 0, false, false, ...
    'VariableNames', {'UEIndex','RNTI','SNR_dB','Frame','Slot','CRCPass','BitErrors','BitsCompared','Goodput_Mbps','ReceiverHestSINR_dB','MeasuredSINR_dB','ChannelGain_dB','Status','Crash','HARQCurrentDecodeOK','HARQCombinedDecodeOK'});

rawTrials = struct("DL", dlRaw, "UL", ulRaw, "SRS", table(), "TRS", table());
slotTrace = struct("HARQTimelineTable", harqTimelineT);

artifacts = sixgr.truth.exportLLSLiveDerivedTables(cfg, tmp, rawTrials, struct(), struct(), slotTrace);
observationT = artifacts.HARQ.TimelineTable;
runtimeProcessT = artifacts.RuntimeHARQ.TimelineTable;
assert(height(observationT) == height(dlRaw) + height(ulRaw) && ...
    all(string(observationT.TraceSource) == ...
    [repmat("dl_raw_link_trials", height(dlRaw), 1); repmat("ul_raw_link_trials", height(ulRaw), 1)]), ...
    "Canonical live HARQ observations must be an ordered projection of primary DL/UL trial rows.");
assert(isequal(double(observationT.CRCPass), [double(dlRaw.CRCPass); double(ulRaw.CRCPass)]), ...
    "Canonical live HARQ observation outcomes must reconcile exactly to primary trial CRC values.");
assert(isequal(logical(observationT.CurrentDecodeOK), ...
    [logical(dlRaw.HARQCurrentDecodeOK); logical(ulRaw.HARQCurrentDecodeOK)]) && ...
    isequal(logical(observationT.CombinedDecodeOK), ...
    [logical(dlRaw.HARQCombinedDecodeOK); logical(ulRaw.HARQCombinedDecodeOK)]), ...
    "Canonical live HARQ observations must resolve HARQ-prefixed decoder outcomes without false defaults.");
summaryT = artifacts.HARQ.SummaryTable;
assert(abs(double(summaryT.CRCPassRate(string(summaryT.Direction) == "DL")) - 0.5) < 1e-12 && ...
    abs(double(summaryT.CRCPassRate(string(summaryT.Direction) == "UL")) - 1) < 1e-12, ...
    "Live HARQ CRC summaries must be recomputed from primary trial CRC outcomes.");
assert(height(runtimeProcessT) == height(harqTimelineT) && ...
    isequal(logical(runtimeProcessT.CombinedDecodeOK), logical(harqTimelineT.CombinedDecodeOK)), ...
    "Causal HARQ process state must remain separately available for retransmission/process KPIs.");
persistedObservationT = readtable(artifacts.LiveHARQTimelinePath, ...
    "VariableNamingRule", "preserve", "TextType", "string");
assert(isequal(double(persistedObservationT.CRCPass), double(observationT.CRCPass)), ...
    "Persisted live HARQ observations must retain the primary-trial projection schema and values.");
userPerfT = artifacts.UserPerformance;
assert(height(userPerfT) == 1, "Live-derived user performance export must preserve one UE row.");
assert(abs(double(userPerfT.DL_HARQFailureRate(1)) - 0.5) < 1e-12, ...
    "DL HARQ failure rate must come from DL HARQ decode outcomes.");
assert(abs(double(userPerfT.UL_HARQFailureRate(1))) < 1e-12, ...
    "UL HARQ failure rate must come from UL HARQ decode outcomes.");
assert(double(userPerfT.DL_HARQObservationCount(1)) == 2 && double(userPerfT.UL_HARQObservationCount(1)) == 1, ...
    "Per-direction HARQ observation counts must preserve real support.");
assert(abs(double(userPerfT.HARQFailureRate(1)) - (1/3)) < 1e-12, ...
    "Live-derived HARQ failure rate must follow HARQ timeline truth, not mean(DL_BLER, UL_BLER).");
assert(double(userPerfT.HARQObservationCount(1)) == 3, ...
    "Live-derived HARQ observation count must preserve total HARQ support.");

% System-level waveform rows may have no fixed-link SNR axis.  The report
% layer must retain their real HARQ outcomes and mark SNR unavailable; it
% must neither crash nor substitute a measured SINR field as configured SNR.
dlNoSNRAxis = removevars(dlRaw, "SNR_dB");
ulNoSNRAxis = removevars(ulRaw, "SNR_dB");
noAxisArtifacts = sixgr.truth.exportLLSLiveDerivedTables(cfg, tmp, ...
    struct("DL", dlNoSNRAxis, "UL", ulNoSNRAxis, "SRS", table(), "TRS", table()), ...
    struct(), struct(), struct());
noAxisTimelineT = noAxisArtifacts.HARQ.TimelineTable;
assert(height(noAxisTimelineT) == height(dlRaw) + height(ulRaw), ...
    "HARQ observations without a fixed-link SNR axis must preserve every primary trial row (expected %d, observed %d).", ...
    height(dlRaw) + height(ulRaw), height(noAxisTimelineT));
assert(all(isnan(double(noAxisTimelineT.SNR_dB))), ...
    "Unavailable configured SNR must remain explicit NaN in system-level HARQ observations.");
assert(isequal(double(noAxisTimelineT.CRCPass), [double(dlRaw.CRCPass); double(ulRaw.CRCPass)]), ...
    "Missing fixed-link SNR metadata must not alter primary HARQ decoder outcomes.");

ok = true;
end
