function ok = testSSBTimingResolver()
%TESTSSBTIMINGRESOLVER Exact Case A-G timing and shared-user regression.

setup6GRSimToolkit("Verbose", false);

cases = table( ...
    ["A"; "B"; "C"; "D"; "E"; "F"; "G"], ...
    [2e9; 4e9; 4e9; 28e9; 28e9; 60e9; 60e9], ...
    ["FR1"; "FR1"; "FR1"; "FR2-1"; "FR2-1"; "FR2-2"; "FR2-2"], ...
    [15; 30; 30; 120; 240; 480; 960], ...
    [4; 8; 8; 64; 64; 64; 64], ...
    'VariableNames', ["Case", "CarrierFrequencyHz", "FrequencyRange", ...
    "SSBSCSKHz", "Lmax"]);

for i = 1:height(cases)
    row = cases(i, :);
    actual = sixgr.phy.frame.SSBTimingResolver.resolve( ...
        "Case", row.Case, ...
        "CarrierFrequencyHz", row.CarrierFrequencyHz, ...
        "FrequencyRange", row.FrequencyRange, ...
        "SSBSubcarrierSpacingKHz", row.SSBSCSKHz, ...
        "CarrierSubcarrierSpacingKHz", min(row.SSBSCSKHz, 120), ...
        "Lmax", row.Lmax, ...
        "SSBIndex", row.Lmax - 1);
    assert(actual.Case == row.Case, "Case %s changed during resolution.", row.Case);
    assert(actual.SSBSubcarrierSpacingKHz == row.SSBSCSKHz, ...
        "Case %s resolved the wrong SSB SCS.", row.Case);
    assert(actual.Lmax == row.Lmax, "Case %s resolved the wrong Lmax.", row.Case);
    assert(isequal(actual.CandidateIndices, 0:(row.Lmax - 1)), ...
        "Case %s candidate indices are not exact zero-based indices.", row.Case);
    assert(numel(actual.CandidateStartSymbolsWithinHalfFrame) == row.Lmax, ...
        "Case %s did not return exactly Lmax candidate symbols.", row.Case);
    assert(issorted(actual.CandidateStartSymbolsWithinHalfFrame), ...
        "Case %s candidate symbols are not monotonically ordered.", row.Case);
    assert(actual.SelectedStartSymbol == ...
        actual.CandidateStartSymbolsWithinHalfFrame(end), ...
        "Case %s selected-candidate timing is inconsistent.", row.Case);
    assert(isequal(actual.CandidateStartSymbolsWithinHalfFrame, ...
        localExpectedCandidateSymbols(row.Case, row.Lmax)), ...
        "Case %s candidate symbols differ from the pinned 38.213 vector.", ...
        row.Case);
    assert(logical(actual.ToolboxCaseSupported), ...
        "Installed R2026a 5G Toolbox does not expose Case %s.", row.Case);

    cfgCase = localCaseConfig(row);
    [~, ~, txTimingOnly] = sixgr.phy.dl.SSB_Tx( ...
        cfgCase, "NumSubframes", 1, "TimingOnly", true);
    [~, rxTimingOnly] = sixgr.phy.dl.SSB_Rx( ...
        [], cfgCase, "TimingOnly", true);
    carrierCase = nrCarrierConfig;
    carrierCase.NCellID = cfgCase.phy.carrier.NCellID;
    carrierCase.SubcarrierSpacing = ...
        cfgCase.phy.carrier.SubcarrierSpacing_kHz;
    carrierCase.NStartGrid = cfgCase.phy.carrier.NStartGrid;
    carrierCase.NSizeGrid = cfgCase.phy.carrier.NSizeGrid;
    mibCase = struct("PDCCHConfigSIB1", 0, ...
        "DMRSTypeAPosition", 2, "Source", "test_decoded_mib");
    [type0TimingOnly, ~] = ...
        sixgr.phy.broadcast.deriveType0PDCCHFromMIB( ...
        carrierCase, cfgCase, mibCase, "TimingOnly", true);
    facadeCase = sixgr.phy.FrameStructureEngine(cfgCase);
    expectedCandidates = actual.CandidateStartSymbolsWithinHalfFrame;
    assert(isequal( ...
        txTimingOnly.SSBTiming.CandidateStartSymbolsWithinHalfFrame, ...
        expectedCandidates), ...
        "Case %s transmitter timing-only path diverged.", row.Case);
    assert(isequal( ...
        rxTimingOnly.SSBTiming.CandidateStartSymbolsWithinHalfFrame, ...
        expectedCandidates), ...
        "Case %s receiver timing-only path diverged.", row.Case);
    assert(isequal( ...
        type0TimingOnly.SSBTiming.CandidateStartSymbolsWithinHalfFrame, ...
        expectedCandidates), ...
        "Case %s Type-0 timing selection path diverged.", row.Case);
    assert(isequal(double(facadeCase.SSBCandidateSymbols), ...
        double(expectedCandidates)), ...
        "Case %s frame facade timing path diverged.", row.Case);
end

localAssertError(@() sixgr.phy.frame.SSBTimingResolver.resolve( ...
    "Case", "H", "CarrierFrequencyHz", 4e9, "FrequencyRange", "FR1"), ...
    "sixgr:phy:frame:UnsupportedSSBCase");
localAssertError(@() sixgr.phy.frame.SSBTimingResolver.resolve( ...
    "Case", "D", "CarrierFrequencyHz", 4e9, "FrequencyRange", "FR1"), ...
    "sixgr:phy:frame:SSBCaseFrequencyRangeMismatch");
localAssertError(@() sixgr.phy.frame.SSBTimingResolver.resolve( ...
    "Case", "B", "CarrierFrequencyHz", 4e9, "FrequencyRange", "FR1", ...
    "SSBSubcarrierSpacingKHz", 15), ...
    "sixgr:phy:frame:SSBCaseSCSMismatch");
localAssertError(@() sixgr.phy.frame.SSBTimingResolver.resolve( ...
    "Case", "B", "CarrierFrequencyHz", 4e9, "FrequencyRange", "FR1", ...
    "Lmax", 4), ...
    "sixgr:phy:frame:SSBLmaxMismatch");
localAssertError(@() sixgr.phy.frame.SSBTimingResolver.resolve( ...
    "Case", "A", "CarrierFrequencyHz", 2e9, "FrequencyRange", "FR1", ...
    "SSBIndex", 4), ...
    "sixgr:phy:frame:SSBIndexOutOfRange");
localAssertError(@() sixgr.phy.frame.SSBTimingResolver.resolve( ...
    "Case", "B", "CarrierFrequencyHz", 28e9, "FrequencyRange", "FR1"), ...
    "sixgr:phy:frame:FrequencyRangeMismatch");
localAssertError(@() sixgr.phy.frame.SSBTimingResolver.resolve( ...
    "Case", "B", "CarrierFrequencyHz", 4e9, "FrequencyRange", "FR1", ...
    "CarrierSubcarrierSpacingKHz", 30, "NSizeGrid", 51, ...
    "NCRBSSB", 0, "KSSB", 24), ...
    "sixgr:phy:frame:InvalidKSSB");
localAssertError(@() sixgr.phy.frame.SSBTimingResolver.resolve( ...
    "Case", "B", "CarrierFrequencyHz", 4e9, "FrequencyRange", "FR1", ...
    "CarrierSubcarrierSpacingKHz", 30, "NSizeGrid", 51, ...
    "NCRBSSB", 100), ...
    "sixgr:phy:frame:SSBOutsideCarrierGrid");

cfg = localAnchorConfig();
[waveform, ~, tx] = sixgr.phy.dl.SSB_Tx(cfg, "NumSubframes", 1);
assert(~isempty(waveform), "Standards-valid SSB anchor produced no waveform.");
assert(tx.OFDMWindowingSamples == 0 && ...
    ~tx.OFDMWindowingEnabled && tx.WindowingPercent == 0 && ...
    tx.OFDMSamplingResolution.WindowingSamples == 0 && ...
    tx.SampleRate_Hz == tx.OFDMSamplingResolution.SampleRateHz, ...
    "SSB transmitter did not apply the canonical zero-windowing policy.");
[~, sync] = sixgr.phy.dl.SSB_Rx( ...
    waveform, cfg, "SampleRate_Hz", tx.SampleRate_Hz);
carrier = nrCarrierConfig;
carrier.NCellID = cfg.phy.carrier.NCellID;
carrier.SubcarrierSpacing = cfg.phy.carrier.SubcarrierSpacing_kHz;
carrier.NSizeGrid = cfg.phy.carrier.NSizeGrid;
mib = struct("PDCCHConfigSIB1", 0, "DMRSTypeAPosition", 2, ...
    "Source", "test_decoded_mib");
[type0, ~] = sixgr.phy.broadcast.deriveType0PDCCHFromMIB( ...
    carrier, cfg, mib);
facade = sixgr.phy.FrameStructureEngine(cfg);
expected = tx.SSBTiming.CandidateStartSymbolsWithinHalfFrame;
assert(isequal(sync.SSBTiming.CandidateStartSymbolsWithinHalfFrame, expected), ...
    "SSB receiver did not consume the transmitter timing object.");
assert(isequal(type0.SSBTiming.CandidateStartSymbolsWithinHalfFrame, expected), ...
    "Type-0 CSS derivation did not consume the canonical SSB timing.");
assert(isequal(double(facade.SSBCandidateSymbols), double(expected)), ...
    "FrameStructureEngine did not delegate SSB timing to the canonical resolver.");

bad = cfg;
bad.phy.carrier.NSizeGrid = 52;
[~, warningIDBefore] = lastwarn("");
localAssertError(@() sixgr.phy.dl.SSB_Tx(bad, "NumSubframes", 1), ...
    "sixgr:phy:frame:ConfiguredGridMismatch");
[~, warningIDAfter] = lastwarn;
assert(isequal(bad.phy.carrier.NSizeGrid, 52), ...
    "Invalid SSB grid validation mutated the caller configuration.");
assert(~contains(string(warningIDAfter), "ClampNSizeGrid") && ...
    ~contains(string(warningIDBefore), "ClampNSizeGrid"), ...
    "SSB validation emitted the removed NSizeGrid clamp warning.");

ok = true;
end

function symbols = localExpectedCandidateSymbols(caseLetter, lmax)
n = [0:3, 5:8, 10:13, 15:18]; %#ok<NBRAK>
switch string(caseLetter)
    case "A"
        symbols = reshape([2; 8] + 14 .* n(1:(lmax / 2)), 1, []);
    case "B"
        symbols = reshape([4; 8; 16; 20] + ...
            28 .* n(1:(lmax / 4)), 1, []);
    case "C"
        symbols = reshape([2; 8] + 14 .* n(1:(lmax / 2)), 1, []);
    case "D"
        symbols = reshape([4; 8; 16; 20] + 28 .* n, 1, []);
    case "E"
        symbols = reshape([8; 12; 16; 20; 32; 36; 40; 44] + ...
            56 .* n(1:8), 1, []);
    case {"F", "G"}
        symbols = reshape([2; 9] + 14 .* (0:31), 1, []);
    otherwise
        error("sixgr:test:UnknownSSBCase", ...
            "Unknown pinned SSB case %s.", caseLetter);
end
end

function cfg = localAnchorConfig()
cfg = struct();
cfg.channel.fc_Hz = 4e9;
cfg.frequency.center_frequency_hz = 4e9;
cfg.frequency.range_name = "FR1";
cfg.frequency.bandwidth_hz = 20e6;
cfg.phy.frequencyRange = "FR1";
cfg.phy.channelBandwidth_MHz = 20;
cfg.phy.carrier = struct( ...
    "NCellID", 17, ...
    "SubcarrierSpacing_kHz", 30, ...
    "SubcarrierSpacing", 30, ...
    "CyclicPrefix", "normal", ...
    "NStartGrid", 0, ...
    "NSizeGrid", 51);
cfg.phy.ssb = struct( ...
    "blockPattern", "Case B", ...
    "scs_kHz", 30, ...
    "Lmax", 8, ...
    "periodicity_ms", 20);
cfg.phy.mib = struct( ...
    "pdcchConfigSIB1", 0, ...
    "dmrsTypeAPosition", 2, ...
    "cellBarred", false, ...
    "intraFreqReselection", false);
cfg.phy.sib1 = struct("coreset0Index", 0, "searchSpaceZero", 0);
end

function cfg = localCaseConfig(row)
switch string(row.Case)
    case "A"
        bandwidthMHz = 5;
        carrierSCSKHz = 15;
        nSizeGrid = 25;
    case {"B", "C"}
        bandwidthMHz = 20;
        carrierSCSKHz = 30;
        nSizeGrid = 51;
    case {"D", "E"}
        bandwidthMHz = 100;
        carrierSCSKHz = 120;
        nSizeGrid = 66;
    case "F"
        bandwidthMHz = 400;
        carrierSCSKHz = 480;
        nSizeGrid = 66;
    case "G"
        bandwidthMHz = 400;
        carrierSCSKHz = 960;
        nSizeGrid = 33;
    otherwise
        error("sixgr:test:UnknownSSBCase", ...
            "Unknown SSB case %s.", row.Case);
end
cfg = struct();
cfg.channel.fc_Hz = double(row.CarrierFrequencyHz);
cfg.channel.bandwidth_Hz = bandwidthMHz * 1e6;
cfg.frequency.center_frequency_hz = double(row.CarrierFrequencyHz);
cfg.frequency.range_name = char(row.FrequencyRange);
cfg.frequency.bandwidth_hz = bandwidthMHz * 1e6;
cfg.phy.frequencyRange = char(row.FrequencyRange);
cfg.phy.channelBandwidth_MHz = bandwidthMHz;
cfg.phy.carrier = struct( ...
    "NCellID", 17, ...
    "centerFrequency_Hz", double(row.CarrierFrequencyHz), ...
    "SubcarrierSpacing_kHz", carrierSCSKHz, ...
    "SubcarrierSpacing", carrierSCSKHz, ...
    "CyclicPrefix", "normal", ...
    "NStartGrid", 0, ...
    "NSizeGrid", nSizeGrid);
cfg.phy.ssb = struct( ...
    "enable", true, ...
    "blockPattern", "Case " + string(row.Case), ...
    "scs_kHz", double(row.SSBSCSKHz), ...
    "Lmax", double(row.Lmax), ...
    "periodicity_ms", 20);
cfg.phy.mib = struct( ...
    "pdcchConfigSIB1", 0, ...
    "dmrsTypeAPosition", 2, ...
    "cellBarred", false, ...
    "intraFreqReselection", false);
cfg.phy.sib1 = struct("coreset0Index", 0, "searchSpaceZero", 0);
end

function localAssertError(fcn, expectedID)
threw = false;
try
    fcn();
catch cause
    threw = true;
    assert(string(cause.identifier) == string(expectedID), ...
        "Expected error %s, got %s: %s", ...
        expectedID, cause.identifier, cause.message);
end
assert(threw, "Expected error %s was not thrown.", expectedID);
end
