function ok = testWaveformBundleCoupledConfigAuthority()
%TESTWAVEFORMBUNDLECOUPLEDCONFIGAUTHORITY Guard shared MU config authority.

setup6GRSimToolkit("Verbose", false);
scenario = sixgr.lls6g.config.loadScenarioConfig(fullfile( ...
    pwd, "simulator", "configs", "scenarios", ...
    "webgui_sinr_sweep_64x4_mu_mimo_repair_slice.yaml"));
scenarioCfg = sixgr.lls6g.buildInternalConfig(scenario, tempdir);

% Reproduce the former contamination: UE 1 owns a valid 64x2 per-user
% matrix, while the coupled scheduler needs all four logical cell ports.
perUserCfg = scenarioCfg;
userArch = sixgr.rf.AntennaArrayFactory.resolvePortArchitecture( ...
    scenarioCfg, "bs", "Signal", "PDSCH", "NumElements", 64, ...
    "NumPorts", 2, "NumRFChains", 2, "MinimumPorts", 2);
perUserCfg = sixgr.util.structSet(perUserCfg, ...
    "phy.pdsch.hybridElementToPortMatrix", ...
    userArch.HybridElementToPortMatrix);
perUserCfg = sixgr.util.structSet(perUserCfg, ...
    "phy.pdsch.numPorts", 2);
perUserCfg = sixgr.util.structSet(perUserCfg, ...
    "phy.pdsch.numRFChains", 2);

selected = sixgr.truth.selectWaveformBundleTrialConfig( ...
    scenarioCfg, perUserCfg, true);
cellArch = sixgr.rf.AntennaArrayFactory.resolvePortArchitecture( ...
    selected, "bs", "Signal", "PDSCH", "NumElements", 64, ...
    "NumPorts", 4, "NumRFChains", 4, "MinimumPorts", 4);
assert(isequal(size(cellArch.HybridElementToPortMatrix), [64 4]), ...
    "Coupled truth must retain the complete 64x4 cell architecture.");

uncoupled = sixgr.truth.selectWaveformBundleTrialConfig( ...
    scenarioCfg, perUserCfg, false);
assert(isequal(size(sixgr.util.structGet(uncoupled, ...
    "phy.pdsch.hybridElementToPortMatrix", [])), [64 2]), ...
    "Uncoupled execution must retain its prepared per-user architecture.");

threw = false;
try
    sixgr.rf.AntennaArrayFactory.resolvePortArchitecture( ...
        perUserCfg, "bs", "Signal", "PDSCH", "NumElements", 64, ...
        "NumPorts", 4, "NumRFChains", 4, "MinimumPorts", 4);
catch ME
    threw = string(ME.identifier) == ...
        "AntennaArrayFactory:ConfiguredHybridMatrixShapeMismatch";
end
assert(threw, ...
    "The fixture must reproduce the original per-user 64x2/64x4 mismatch.");

ok = true;
end
