function testChannelConfiguredVsAppliedGate
T = channelRFStrictAnchorResult().Result.ConfiguredVsApplied;
positive = T(T.ExpectedOk, :);
negative = T(~T.ExpectedOk, :);
assert(all(positive.StrictOk & positive.ConfiguredAppliedMatch & positive.FeatureApplied), ...
    "All positive configured-vs-applied rows must pass.");
assert(all(~negative.StrictOk & ~negative.ConfiguredAppliedMatch), ...
    "All negative configured-vs-applied rows must fail closed.");

% A legacy aggregate rf.enable flag must not override enabled stages in the
% resolved sample-domain chain.  The stage trace that actually processed
% the waveform is the configured/applied authority.
cfg = channelRFStrictAnchorResult().Config;
cfg = sixgr.util.structSet(cfg, "rf.enable", false);
probe = sixgr.channel.runStrictChannelRFValidation(cfg, ...
    "RunId", "stage_trace_rf_authority", ...
    "ScenarioName", "stage_trace_rf_authority", ...
    "WriteArtifacts", false);
rfRow = probe.ConfiguredVsApplied( ...
    string(probe.ConfiguredVsApplied.TrialId) == "positive_rf_impairment", :);
assert(height(rfRow) == 1 && logical(rfRow.FeatureConfigured) && ...
    logical(rfRow.FeatureApplied) && logical(rfRow.StrictOk), ...
    "Resolved enabled RF stages must remain authoritative when rf.enable is false.");
end
