function ok = testFixedLinkDerivedReconciliationWiring()
%TESTFIXEDLINKDERIVEDRECONCILIATIONWIRING Fixed trials feed shared analytics.

root = tempname();
cleanup = onCleanup(@() localRemove(root)); %#ok<NASGU>
mkdir(root);

cfg = sixgr.config.defaultConfig();
cfg.run.noiseOperatingMode = "standalone_awgn_snr_argument";
cfg.simulation.noise_operating_mode = "standalone_awgn_snr_argument";
cfg.frequency.bandwidth_hz = 20e6;
cfg.impairments.cfo.enabled = false;
cfg.impairments.cfo.value_hz = 0;
cfg.impairments.phase_noise.enabled = false;
cfg.impairments.phase_noise.model = "none";
cfg.impairments.iq_imbalance.enabled = false;
cfg.impairments.iq_imbalance.model = "none";
cfg.impairments.pa_nonlinearity.enabled = false;
cfg.impairments.pa_nonlinearity.model = "ideal_linear";
cfg.interference.inter_cell_execution_mode = "none";
cfg.interference.intra_cell_execution_mode = "none";
cfg.interference.inter_cell_interference_flag = false;
cfg.interference.intra_cell_interference_flag = false;
cfg.interference.mu_mimo_interference_flag = false;

dl = localTrial("DL", 20);
ul = localTrial("UL", 20);
% Persisted wide CSVs can legitimately rehydrate text columns as cells.
% Derived finalization must accept that exact representation without
% replacing the runtime value or depending on the original MATLAB process.
dl.Modulation = {'256QAM'};
dl.CQIDerivedModulation = {'256QAM'};
ul.Modulation = {'256QAM'};
ul.CQIDerivedModulation = {'256QAM'};
raw = struct("DL", dl, "UL", ul);
artifacts = sixgr.truth.exportLLSLiveDerivedTables( ...
    cfg, root, raw, struct(), struct(), struct());

assert(isstruct(artifacts.RFInterferenceReconciliation), ...
    "Shared analytics must return the RF reconciliation bundle.");
required = [ ...
    "noise_reconciliation.csv"
    "rf_chain_definition.csv"
    "cfo_reconciliation.csv"
    "phase_noise_reconciliation.csv"
    "iq_imbalance_reconciliation.csv"
    "pa_reconciliation.csv"
    "evm_reconciliation.csv"
    "papr_reconciliation.csv"
    "channel_rf_reconciliation.csv"];
for name = required.'
    pathValue = fullfile(root, "reports", "csv", char(name));
    assert(exist(pathValue, "file") == 2, ...
        "Fixed-link analytics did not publish %s.", name);
    T = readtable(pathValue, "TextType", "string", ...
        "VariableNamingRule", "preserve", "Delimiter", ",");
    assert(height(T) > 0, "%s must contain measured/audited rows.", name);
end

cfo = readtable(fullfile(root, "reports", "csv", ...
    "cfo_reconciliation.csv"), "TextType", "string", ...
    "VariableNamingRule", "preserve", "Delimiter", ",");
assert(all(double(cfo.ObservedRows) == 1) && ...
    all(logical(cfo.CfoConfiguredAppliedOk)), ...
    "CFO reconciliation must be backed by the supplied DL/UL trial rows.");
assert(height(artifacts.UserPerformance) == 1 && ...
    double(artifacts.UserPerformance.DL_ObservedRowCount(1)) == 1 && ...
    double(artifacts.UserPerformance.UL_ObservedRowCount(1)) == 1, ...
    "Persisted cell-text trial rows must rebuild the per-UE live summary.");

ok = true;
fprintf("PASS testFixedLinkDerivedReconciliationWiring: fixed trials feed shared analytics.\n");
end

function T = localTrial(direction, snrDb)
row = struct( ...
    'Direction', string(direction), ...
    'UEIndex', 1, ...
    'RNTI', 101, ...
    'Frame', 0, ...
    'Slot', 0, ...
    'ConfiguredSNR_dB', snrDb, ...
    'SNR_dB', snrDb, ...
    'PostEqSINR_dB', snrDb, ...
    'MeasuredTrialSINR_dB', snrDb, ...
    'WidebandCQI', 15, ...
    'CQIDerivedMCS', 20, ...
    'CQIDerivedTargetCodeRate', 0.6665, ...
    'MCSIndex', 20, ...
    'TargetCodeRate', 0.6665, ...
    'CRCPass', true, ...
    'Status', "PASS", ...
    'Crash', false, ...
    'GoodBits', 1000, ...
    'OfferedBits', 1000, ...
    'Goodput_Mbps', 1, ...
    'ReceiverHestSINR_dB', snrDb, ...
    'DecoderTruthProxySINR_dB', NaN, ...
    'EVM_rms', 0.01, ...
    'EVMProxySINR_dB', -20*log10(0.01), ...
    'PAPR_dB', 6, ...
    'InjectedCFO_Hz', 0, ...
    'EstimatedCFO_PreCorrection_Hz', 0, ...
    'ResidualCFO_PostCorrection_Hz', 0, ...
    'InjectedTimingOffset_samples', 0, ...
    'EstimatedTimingOffset_PreCorrection_samples', 0, ...
    'ResidualTimingError_PostCorrection_samples', 0, ...
    'IQImbalanceConfigured', false, ...
    'IQImbalanceApplied', false, ...
    'PhaseNoiseApplied', false, ...
    'PAApplied', false, ...
    'InterferenceApplied', false, ...
    'InterferenceMode', "none", ...
    'InterferenceContributorCount', 0, ...
    'InterferenceAggregatedRxPower_dBm', -Inf, ...
    'InterferencePowerSource', "", ...
    'FullInterfererChannelTruthUsed', false, ...
    'NoiseOperatingMode', "standalone_awgn_snr_argument", ...
    'ReceiverInputSampleNoiseVariance', 1e-3, ...
    'PostEqualizationNoiseVariance', 1.1e-3, ...
    'LLRNoiseVariance', 1.1e-3, ...
    'NoiseVarStatus', "OK", ...
    'NoiseVarStrictFailure', false, ...
    'NoiseVarianceSource', "fixed_link_fixture_waveform_awgn_replay", ...
    'AppliedNoiseSNRSource', "occupied_re_signal_energy_over_effective_grid_noise_variance", ...
    'PostEqualizationNoiseVarianceSource', "fixed_link_fixture_post_equalization_variance", ...
    'LLRNoiseVarianceSource', "fixed_link_fixture_soft_demapper_variance", ...
    'ConfiguredIQGainImbalance_dB', 0, ...
    'ConfiguredIQPhaseImbalance_deg', 0, ...
    'ChannelEstimationMethod', "none", ...
    'LogicalTxPorts', 1, ...
    'ChannelModel', "AWGN");
T = struct2table(row, "AsArray", true);
end

function localRemove(pathValue)
if isfolder(pathValue)
    rmdir(pathValue, "s");
end
end
