function ok = testTDDCausalFourStepRARuntimeTiming()
%TESTTDDCAUSALFOURSTEPRARUNTIMETIMING Guard the shared RA timing boundary.
%
% The test uses the production TDD causal-wiring YAML, a concrete TDL-C
% runtime channel, physical antenna expansion, thermal receiver noise, and
% the real Msg1/Msg2/Msg3/Msg4/RRCSetupComplete waveform chain.  It proves
% that decoded Msg1 timing advance establishes Msg3 timing and that the
% PUSCH receiver does not apply a second DM-RS timing shift.

scenarioPath = fullfile("simulator", "configs", "scenarios", ...
    "lls_causal_access_to_data_wiring_tdd.yaml");
scfg = sixgr.lls6g.config.loadScenarioConfig(scenarioPath);
runRoot = tempname;
mkdir(runRoot);
cleanup = onCleanup(@() localCleanup(runRoot)); %#ok<NASGU>
cfg = sixgr.config.normalizeConfig( ...
    sixgr.lls6g.buildInternalConfig(scfg, runRoot));

assert(strcmpi(string(sixgr.util.structGet(cfg, "phy.duplex.mode", "")), "TDD"), ...
    "The timing regression must exercise the YAML-selected TDD profile.");
assert(strcmpi(string(sixgr.util.structGet(cfg, "channel.model", "")), "TDL") && ...
        strcmpi(string(sixgr.util.structGet(cfg, "channel.tdlProfile", "")), "TDL-C"), ...
    "The timing regression must use the concrete configured TDL-C channel.");

multiUser = struct("Enabled", true, "NumUsers", 1, "RNTIStart", 1, ...
    "ExecutionModel", "slot_coupled_truth");
state = sixgr.truth.CoupledTruthRuntime.initialize( ...
    cfg, runRoot, multiUser, struct(), 1);
state.CurrentSlot = 2;
state.CurrentServingIdx(:) = 1;
[cfgRuntime, ~] = sixgr.truth.CoupledTruthRuntime.applyUserContext( ...
    cfg, state, 1, "UL");

result = sixgr.phy.ra.runFourStepRA(cfgRuntime, ...
    "RunFolder", runRoot, "RunId", "tdd_causal_ra_timing", ...
    "ScenarioName", "tdd_causal_ra_timing", ...
    "UEId", 1, "CellId", 1, "AttemptId", 1, ...
    "RuntimeIntegrationMode", "coupled_truth_runtime", ...
    "UseRuntimeChannel", true, "RuntimeNoiseSNR_dB", 12, ...
    "RuntimeSlot", 2, "WriteArtifacts", false);

assert(logical(result.RACompleted) && logical(result.StrictOk), ...
    "The TDD measured four-step RA waveform chain must complete strictly.");
assert(logical(result.Msg3PUSCHCrcPass), ...
    "Msg3 PUSCH must decode through the production TDL-C receiver chain.");
assert(logical(result.Msg3TimingAdvanceApplied), ...
    "Msg3 must consume the timing advance decoded from Msg1/RAR state.");
assert(~logical(result.Msg3TimingEstimateUsed), ...
    "An already TA-aligned Msg3 waveform must not perform duplicate DM-RS timing acquisition.");
assert(abs(double(result.Msg3AppliedTimingCorrection_samples)) < 1e-12, ...
    "An already TA-aligned Msg3 waveform must receive zero duplicate timing correction.");
assert(string(result.Msg3TimingEstimateSource) == ...
        "runtime_aligned_waveform_no_timing_reacquisition", ...
    "Msg3 timing provenance must identify the established runtime alignment boundary.");
assert(logical(result.Msg3ChannelEstimateAvailable) && ...
        logical(result.Msg3EqualizationAvailable) && ...
        logical(result.Msg3LLRFinite), ...
    "Msg3 must retain measured channel-estimation, equalization, and finite-LLR evidence.");
assert(~logical(result.ProxyUsed) && ~logical(result.Skipped), ...
    "The TDD RA timing regression must not use proxy or skipped evidence.");

ok = true;
fprintf(['PASS testTDDCausalFourStepRARuntimeTiming: TDD Msg3 consumed ' ...
    'decoded TA and passed the measured TDL-C receiver without duplicate timing correction.\n']);
end

function localCleanup(pathText)
if isfolder(pathText)
    rmdir(pathText, "s");
end
end
