function ok = testLLSSummaryRawConsistency()
%TESTLLSSUMMARYRAWCONSISTENCY Raw DL/UL trials must drive the effective operating-point summary.

setup6GRSimToolkit("Verbose", false);

tmp = tempname;
mkdir(tmp);
c = onCleanup(@() rmdir(tmp, "s")); %#ok<NASGU>

scfg = sixgr.lls6g.config.loadScenarioConfig( ...
    fullfile(pwd, "simulator", "configs", "scenarios", "lls_700mhz_20mhz_3bs_30ue_tdlc_browser_coupled.yaml"));
cfg = sixgr.lls6g.buildInternalConfig(scfg, fullfile(tmp, "run"));
cfg.run.numFrames = 1;
cfg.channel.snr_dB = 10;
cfg.channel.model = "AWGN";
cfg.channel.awgnOnly = true;
cfg.run.noiseOperatingMode = "configured_snr_anchor_after_large_scale_gain";
cfg.run.interferenceExecutionMode = "none";

multiUser = struct("Enabled", true, "NumUsers", 1, "RNTIStart", 320, "ExecutionModel", "slot_coupled_truth");
state = sixgr.truth.CoupledTruthRuntime.initialize(cfg, fullfile(tmp, "runtime"), multiUser, struct(), 1);
state.CurrentServingIdx(1) = 1;
state.CurrentServingMetric_dBm(1) = -70;
state.CurrentSlot = 1;
state.CurrentFrame = 1;
state.CurrentSNR_dB = 10;
state.LargeScaleState.BeamIndex(1,1) = 1;
state.LargeScaleState.BeamGain_dB(1,1) = 0;
state.LargeScaleState.RxPower_dBm(1,1) = -70;
state.LargeScaleState.BasePathloss_dB(1,1) = 100;
state.LargeScaleState.Pathloss_dB(1,1) = 100;
state.LargeScaleState.Shadow_dB(1,1) = 0;
state.LargeScaleState.O2I_dB(1,1) = 0;
[cfgDL, state] = sixgr.truth.CoupledTruthRuntime.applyUserContext(cfg, state, 1, "DL");
[cfgUL, state] = sixgr.truth.CoupledTruthRuntime.applyUserContext(cfg, state, 1, "UL");

grant = struct( ...
    "UEIndex", 1, ...
    "RNTI", 320, ...
    "ServingCell", 1, ...
    "CQIUsed", 15, ...
    "RIUsed", 1, ...
    "PMI", 0, ...
    "CRI", 0, ...
    "MCS", 10, ...
    "MCSIndex", 10, ...
    "Modulation", "16QAM", ...
    "TargetCodeRate", 0.33203125, ...
    "MCSTable", "qam64_table1", ...
    "CQITable", "table1", ...
    "AMCMode", "cqi_driven", ...
    "GrantReason", "summary_raw_consistency_unit_test", ...
    "Frame", 1, ...
    "Slot", 1, ...
    "HARQ", struct());

dl = sixgr.link.runDLPDSCHThroughput(cfgDL, ...
    "NumFrames", 1, ...
    "SNR_dB", 10, ...
    "GrantSnapshot", grant, ...
    "InterferenceBundle", struct([]));
ul = sixgr.link.runULPUSCHThroughput(cfgUL, ...
    "NumFrames", 1, ...
    "SNR_dB", 10, ...
    "GrantSnapshot", grant, ...
    "InterferenceBundle", struct([]));

summary = sixgr.truth.summarizeEffectiveOperatingPoint(cfg, dl.TrialTable, ul.TrialTable);
assert(logical(summary.DL.HasSamples) && logical(summary.UL.HasSamples), ...
    "Effective operating-point summary must detect raw DL/UL runtime samples when trial rows exist.");
assert(double(summary.DL.SampleCount) >= 1 && double(summary.UL.SampleCount) >= 1, ...
    "Effective operating-point summary must count raw runtime samples when trial rows exist.");
assert(~contains(lower(string(summary.RuntimeNarrative)), "no runtime-selected operating-point samples were emitted"), ...
    "Runtime narrative must not claim missing runtime-selected samples when raw DL/UL trial rows exist.");
assert(~contains(lower(string(summary.RuntimeQualifiedDescription)), "no runtime-selected operating-point samples"), ...
    "Runtime-qualified description must not claim missing operating-point rows when raw DL/UL trial rows exist.");

ok = true;
end
