function ok = testCausalFeedbackAMC()
%TESTCAUSALFEEDBACKAMC Verify calibrated causal CSI/AMC contracts.

setup6GRSimToolkit("Verbose", false);

cfg = sixgr.config.defaultConfig();
cfg.phy.nRxAnt = 2;
cfg.phy.nTxAnt = 2;
cfg = sixgr.util.structSet(cfg, "phy.csi.maxRank", 2);
cfg = sixgr.util.structSet(cfg, "phy.csi.pmiCodebookMode", "noncodebook");

[csi, info] = sixgr.phy.dl.CSI_Feedback(eye(2), 0.01, cfg, "MaxRank", 2);
assert(double(csi.RI) == 2, ...
    "DL CSI must select rank from the MI-scored receiver objective, not an SVD-gap clamp.");
assert(string(csi.RankSelectionMethod) == "wideband_codebook_post_equalization_mi" && ...
    string(info.RankSelectionObjective) == "sum_log2_one_plus_layer_sinr", ...
    "DL CSI must disclose the rank objective used for PMI/RI selection.");
assert(all(isfinite(double(csi.SelectedLayerSINR_dB(:)))) && ...
    isfinite(double(csi.SelectedMutualInformation_bpcu)), ...
    "DL CSI must expose finite selected-layer SINR and MI diagnostics.");

cfgUL = cfg;
cfgUL = sixgr.util.structSet(cfgUL, "phy.pusch.transmissionScheme", "codebook");
cfgUL = sixgr.util.structSet(cfgUL, "phy.pusch.transformPrecoding", false);
cfgUL = sixgr.util.structSet(cfgUL, "phy.pusch.maxRankDefault", 2);
cfgUL = sixgr.util.structSet(cfgUL, "phy.pusch.NumAntennaPorts", 2);
cfgUL = sixgr.util.structSet(cfgUL, "phy.pusch.numAntennaPorts", 2);
Hest = repmat(reshape(eye(2), 1, 1, 2, 2), [24, 2, 1, 1]);
est = sixgr.phy.ul.estimateSRSRITPMI(Hest, 0.01, cfgUL);
assert(logical(est.Valid) && double(est.RI) == 2, ...
    "UL SRS RI must come from the post-equalization MI objective for a full-rank channel.");
assert(contains(string(est.RISource), "post_equalization_mi") && ...
    isfinite(double(est.RankMutualInformation)), ...
    "UL SRS RI provenance and MI score must be exported.");

cfgAMC = sixgr.config.defaultConfig();
cfgAMC = sixgr.util.structSet(cfgAMC, "phy.linkAdaptation.mode", "amc");
cfgAMC = sixgr.util.structSet(cfgAMC, "phy.linkAdaptation.dlPolicy", "baseline");
cfgAMC = sixgr.util.structSet(cfgAMC, "phy.linkAdaptation.domain", "effective_sinr");
cfgAMC = sixgr.util.structSet(cfgAMC, "phy.linkAdaptation.outerLoopFlag", false);
cfgAMC = sixgr.util.structSet(cfgAMC, "phy.linkAdaptation.maxCSIAgingPenalty_dB", 6);
cfgAMC = sixgr.util.structSet(cfgAMC, "channel.doppler_Hz", 500);
cfgAMC = sixgr.util.structSet(cfgAMC, "phy.numerology.slotDuration_ms", 1);
metrics = struct( ...
    "SINR_dB", 18, ...
    "SINRSource", "post_equalization_sinr_from_equalizer", ...
    "SINRValueRole", "measured_post_equalization_scheduling_input", ...
    "SINRValueStatus", "OK", ...
    "RI", 1, ...
    "CombinedDecodeOK", true);
[fresh, ~] = sixgr.link.computeLinkAdaptationDecision(cfgAMC, "DL", metrics);
metrics.CSIAgeSlots = 10;
[aged, ~] = sixgr.link.computeLinkAdaptationDecision(cfgAMC, "DL", metrics);
assert(logical(fresh.Valid) && logical(aged.Valid), ...
    "Fresh and aged measured SINR decisions must both produce valid AMC decisions.");
assert(double(aged.MCSIndex) <= double(fresh.MCSIndex) && ...
    double(aged.FeedbackAgingPenalty_dB) > 0 && ...
    double(aged.AgedSINR_dB) < double(fresh.AgedSINR_dB), ...
    "CSI aging must reduce the SINR/CQI operating point before MCS selection.");
assert(contains(string(aged.CalibrationProfile), "target_bler") && ...
    string(aged.CalibrationVersion) == "nr_cqi_mcs_table_v1", ...
    "AMC decisions must carry versioned calibration and target-BLER metadata.");

cfgCQIAging = sixgr.util.structSet(cfgAMC, "phy.linkAdaptation.domain", "cqi");
metricsCQIFresh = struct("CQI", 12, "RI", 1, "CSIAgeSlots", 0);
metricsCQIAged = metricsCQIFresh;
metricsCQIAged.CSIAgeSlots = 10;
[freshCQI, ~] = sixgr.link.computeLinkAdaptationDecision(cfgCQIAging, "DL", metricsCQIFresh);
[agedCQI, ~] = sixgr.link.computeLinkAdaptationDecision(cfgCQIAging, "DL", metricsCQIAged);
assert(logical(freshCQI.Valid) && logical(agedCQI.Valid) && ...
    double(agedCQI.ResolvedCQI) < double(freshCQI.ResolvedCQI) && ...
    double(agedCQI.MCSIndex) <= double(freshCQI.MCSIndex) && ...
    double(agedCQI.FeedbackAgingPenalty_dB) > 0, ...
    "Delayed reported CQI must be aged by default before scheduler-facing MCS selection.");

cfgCQI = sixgr.util.structSet(cfgAMC, "phy.linkAdaptation.domain", "cqi");
blocked = sixgr.link.computeLinkAdaptationDecision(cfgCQI, "DL", ...
    struct("CQI", 12, "RI", 1, "CausalFeedbackUsable", false));
assert(~logical(blocked.Valid) && string(blocked.Reason) == "stale_or_unusable_csi_feedback", ...
    "Unusable causal feedback must fail closed instead of consuming a stale CQI.");

stateBeforeCQI0 = struct();
[outOfRange, stateAfterCQI0] = sixgr.link.computeLinkAdaptationDecision(cfgCQI, "DL", ...
    struct("CQI", 0, "RI", 1, "CombinedDecodeOK", false), ...
    "AdaptationState", stateBeforeCQI0);
assert(~logical(outOfRange.Valid) && ...
    string(outOfRange.Reason) == "measured_cqi_zero_out_of_range" && ...
    string(outOfRange.MCSValueStatus) == "unavailable_measured_cqi_zero_out_of_range" && ...
    double(stateAfterCQI0.UpdateCount) == 0, ...
    "CQI 0 must block transmission without selecting MCS 0 or updating ILLA/OLLA state.");

cfgSched = cfgCQI;
cfgSched = sixgr.util.structSet(cfgSched, "phy.linkAdaptation.bootstrapCQIMode", "measured_only");
cfgSched = sixgr.util.structSet(cfgSched, "phy.linkAdaptation.maxCSIAgeSlots", 4);
scheduler = sixgr.l2.mac.SchedulerPF(cfgSched, "Direction", "DL");
[~, ~, ~, amc] = scheduler.selectAMC(struct("RNTI", 7001, "CQI", 11, "CSIAgeSlots", 8));
assert(~logical(amc.CausalFeedbackUsable) && ...
    string(amc.MCSSelectionSource) == "blocked_missing_runtime_cqi" && ...
    contains(string(amc.CausalFeedbackStatus), "stale_csi"), ...
    "Scheduler AMC must reject CQI feedback older than the configured causal age limit.");

ok = true;
end
