function ok = testDirectionalReceivePowerAuthority()
%TESTDIRECTIONALRECEIVEPOWERAUTHORITY Reject DL receive anchors on UL paths.

setup6GRSimToolkit("Verbose", false);
cfg = localBaseConfig();
cfg.lls6g.userContext = struct( ...
    "RuntimeCurrentDirection", "UL", ...
    "RuntimeServingRxPower_dBm", 33.859, ...
    "RuntimeServingRxPowerDirection", "DL", ...
    "RuntimeServingRxPowerSource", ...
        "CoupledTruthRuntime.LargeScaleState.RxPower_dBm", ...
    "RuntimeServingPathloss_dB", 100, ...
    "RuntimeServingBasePathloss_dB", 100, ...
    "RuntimeServingShadowFading_dB", 0, ...
    "RuntimeServingO2I_dB", 0);
ctx = sixgr.rf.PowerContext(cfg, "UL", "NumPorts", 1);
ctx.TotalTxPower_dBm = -10;
ctx.SignalSpecificPowerControl = true;
ctx.SignalSpecificPowerControlSource = "unit_test_pusch_power_control";
cfg.lls6g.runtimePowerContext = ctx;

[~, replay] = sixgr.link.applyWaveformImpairments(ones(256, 1), ...
    cfg, 1e6, "ApplyRFChain", false);
assert(abs(double(replay.ServingRxPower_dBm) - (-110)) < 1e-10, ...
    "UL receive power must come from the UL transmitter budget and pathloss.");
assert(string(replay.ServingRxPowerSource) == ...
    "signal_specific_power_context_link_budget");
assert(string(replay.PowerContextDirection) == "UL");
assert(string(replay.AbsolutePowerReferencePlane) == ...
    "receiver_input_equivalent_link_budget_before_adc");

cfgMissing = localBaseConfig();
cfgMissing.lls6g.userContext = struct( ...
    "RuntimeCurrentDirection", "UL", ...
    "RuntimeServingRxPower_dBm", 33.859, ...
    "RuntimeServingRxPowerDirection", "DL", ...
    "RuntimeServingRxPowerSource", ...
        "CoupledTruthRuntime.LargeScaleState.RxPower_dBm");
cfgMissing.lls6g.runtimePowerContext = sixgr.rf.PowerContext( ...
    cfgMissing, "UL", "NumPorts", 1);
[~, replayMissing] = sixgr.link.applyWaveformImpairments(ones(64, 1), ...
    cfgMissing, 1e6, "ApplyRFChain", false);
assert(isnan(double(replayMissing.ServingRxPower_dBm)));
assert(string(replayMissing.ServingRxPowerSource) == ...
    "unavailable_runtime_rx_power_direction_mismatch");
assert(string(replayMissing.AbsolutePowerReferencePlane) == ...
    "unavailable_normalized_waveform_without_absolute_pathloss_anchor");

ok = true;
end

function cfg = localBaseConfig()
cfg = struct();
cfg.run.noiseOperatingMode = "standalone_awgn_snr_argument";
cfg.channel.snr_dB = 10;
cfg.channel.pathlossEnabled = false;
cfg.phy.impairments = struct( ...
    "cfoEnabled", false, ...
    "phaseNoiseEnabled", false, ...
    "iqImbalanceEnabled", false, ...
    "timingOffsetEnabled", false, ...
    "paNonlinearityEnabled", false);
cfg.powerAndRF.ueTxPower_dBm = 23;
cfg.powerAndRF.bsTxPower_dBm = 23;
end
