function ok = testSRSPUSCHRuntimePriority()
%TESTSRSPUSCHRUNTIMEPRIORITY Causal first-measurement ownership regression.

setup6GRSimToolkit("Verbose", false, "RunToolboxChecks", false);
cfg = struct();
cfg.phy.srs.puschCollisionPolicy = ...
    "prioritize_srs_until_first_valid_measurement";
state = struct("LastSuccessfulSRSSlotByUE", [1; NaN]);
pending = [localGrant(1); localGrant(2)];

decision = localDecision("SRS_PUSCH", 1);
[~, remaining, resolved, collisionRemains, cancelled] = ...
    sixgr.truth.resolveSRSPUSCHRuntimePriority( ...
    state, pending, decision, cfg, 2, 2);
assert(~collisionRemains && cancelled == 1 && numel(remaining) == 1 && ...
    remaining.UEIndex == 2, ...
    "First-measurement SRS priority did not cancel only the exact colliding PUSCH.");
assert(string(resolved.Action) == ...
    "suppress_queued_pusch_execute_first_required_srs" && ...
    logical(resolved.PUSCHGrantCancelled) && ...
    string(resolved.RuntimePriorityReason) == ...
    "first_valid_srs_measurement_missing", ...
    "SRS measurement-priority decision did not preserve its causal evidence.");

[~, unchanged, measured, collisionRemains, cancelled] = ...
    sixgr.truth.resolveSRSPUSCHRuntimePriority( ...
    state, pending, decision, cfg, 2, 1);
assert(collisionRemains && cancelled == 0 && numel(unchanged) == 2 && ...
    string(measured.Action) == ...
    "defer_srs_after_first_valid_measurement", ...
    "Existing valid SRS authority did not preserve queued PUSCH.");

% Due PUCCH carries causal HARQ/UCI and has precedence even before the
% first SRS measurement. It must never be cancelled as if it were PUSCH.
pucchDecision = localDecision("SRS_PUCCH", 1);
[~, unchanged, protected, collisionRemains, cancelled] = ...
    sixgr.truth.resolveSRSPUSCHRuntimePriority( ...
    state, pending, pucchDecision, cfg, 2, 2);
assert(collisionRemains && cancelled == 0 && numel(unchanged) == 2 && ...
    string(protected.Action) == "defer_srs_preserve_due_pucch" && ...
    string(protected.RuntimePriorityReason) == ...
    "due_pucch_uci_already_executed", ...
    "First-measurement priority incorrectly displaced due PUCCH/UCI.");

cfg.phy.srs.puschCollisionPolicy = "preserve_pusch_defer_srs";
[~, unchanged, preserved, collisionRemains, cancelled] = ...
    sixgr.truth.resolveSRSPUSCHRuntimePriority( ...
    state, pending, decision, cfg, 2, 2);
assert(collisionRemains && cancelled == 0 && numel(unchanged) == 2 && ...
    string(preserved.RuntimePriorityReason) == ...
    "configured_policy_preserves_queued_pusch", ...
    "Explicit PUSCH-priority policy was not retained.");

ok = true;
fprintf("[PASS] testSRSPUSCHRuntimePriority causal ownership retained.\n");
end

function grant = localGrant(ueIndex)
grant = struct("UEIndex", double(ueIndex), ...
    "RNTI", double(100 + ueIndex), ...
    "ScheduledAbsoluteSlot", 2);
end

function T = localDecision(pair, ordinal)
T = table();
T.CollisionPair = string(pair);
T.Collision = true;
T.Action = "runtime_srs_measurement_priority_resolution_required";
T.Status = "COLLISION_REQUIRES_RUNTIME_PRIORITY_RESOLUTION";
T.GrantOrdinal = double(ordinal);
end
