function ok=testPUCCHFlatJointReceiver()
% Physical core-receiver integration; declared connector/RF unit fixture.
% This is not shared-clock execution or statistical detector qualification.
setup6GRSimToolkit('Verbose',false);
path='simulator/configs/validation/pucch_flat_joint_receiver_component.yaml';
p=sixgr.lls6g.config.readConfigFile(path);
frozen=sixgr.lls6g.config.readConfigFile(p.fixture_config);
stream=RandStream('Threefry','Seed',p.seed);
folder=fullfile(pwd,'logs',['pucch_flat_joint_receiver_' char(datetime('now','Format','yyyyMMdd_HHmmss_SSS'))]);
mkdir(folder); rows=table(); withheld=0;
for count=reshape(p.payload_bits,1,[])
 for prbs=reshape(p.resource_prbs,1,[])
    bits=int8(randi(stream,[0 1],count,1));
    f=sixgr.phy.pucch.PUCCHFixtureFactory.connected(2,bits,'RNTI',frozen.rnti);
    rrcData=f.RRCContext.Data; rrcData.Resources.NumPRBs=prbs;
    rrc=sixgr.phy.pucch.PUCCHRRCContext(rrcData);
    power=f.UEContext.Data.PowerControlState.Data; power.MRB=prbs;
    ueData=f.UEContext.Data; ueData.RRCContext=rrc;
    ueData.PowerControlState=sixgr.phy.pucch.PUCCHPowerControlState(power);
    txAssignment=sixgr.phy.pucch.PUCCHTransmissionAssignment.fromCombinedUCI( ...
        f.Report,sixgr.phy.pucch.PUCCHUEContext(ueData),f.FrameState);
    tx=sixgr.phy.pucch.PUCCHTransmitter.transmit(f.Carrier,txAssignment,f.Report);
    context=sixgr.phy.pucch.UCIReportContext(struct('ReportID',"gnb_joint_receiver", ...
        'ConfigurationEpoch',1,'Sequence1Length',count,'Sequence2Length',0, ...
        'HARQACKBits',0,'SRBits',0,'CSIPart1Bits',count,'CSIPart2Bits',0,'PriorityIndex',0));
    assignment=sixgr.phy.pucch.PUCCHReceptionAssignment(struct( ...
        'ObservationID',"gnb_joint_receiver",'ResourceID',frozen.resource_id,'RNTI',frozen.rnti, ...
        'AbsoluteSlot0',0,'Source',"declared_gNB_joint_receiver_fixture", ...
        'TimingSource',"received_DMRS_acquisition", ...
        'ResourceSelectionProcedure',"configured_csi"),rrc,context);
    for branches=reshape(p.receive_branches,1,[])
        gains=reshape(frozen.channel_gain_amplitude(1:branches),1,[]).* ...
            exp(1i*reshape(frozen.channel_gain_phase_rad(1:branches),1,[]));
        signal=tx.Waveform*gains;
        energy=sixgr.phy.waveform.measureReceivedOccupiedREEnergy( ...
            f.Carrier,signal,tx.PUCCHIndices,'SignalFamily','PUCCH');
        [~,ofdm]=sixgr.phy.waveform.ofdmDemodulate(f.Carrier,signal);
        transform=sixgr.phy.waveform.convertNoiseVarianceToGridDomain(1,ofdm,'InputDomain','sample');
        window=reshape(frozen.search_window_samples,1,[]);
        delayed=complex(zeros(size(signal,1)+window(2),branches));
        delayed(frozen.transmit_offset_samples+(1:size(signal,1)),:)=signal;
        % This metadata describes the explicit matrix multiplication and
        % white sample noise below, with no TX/RX RF stages in this fixture.
        % It is not fabricated evidence of a full shared-stream execution.
        rf=struct('RFConfiguredStageCount',0,'RFAppliedStageCount',0);
        link=struct('TX',"fixture_tx",'RX',"fixture_rx",'Replay',struct( ...
            'RuntimeChannelTimingTruthSource',"executed_fixed_matrix_operator_zero_delay", ...
            'ChannelFadingApplied',false));
        execution=struct('Links',link,'TX',struct('ID',"fixture_tx",'Replay',rf), ...
            'RX',struct('ID',"fixture_rx",'Replay',rf));
        model=struct('NoiseOperatingMode',"standalone_awgn_snr_argument", ...
            'TransmitterID',"fixture_tx",'ReceiverID',"fixture_rx", ...
            'ReceiveStreamExecutionSegments',{{struct('Execution',execution)}});
        args={'NoiseVariance',NaN,'NoiseVarianceMode','received_dmrs_estimate', ...
            'ChannelProfile','AWGN','DetectionThreshold',frozen.legacy_detection_threshold, ...
            'TimingSearchWindowSamples',window,'ReceivedExecutionEvidence',model};
        for snr=reshape(p.snr_db,1,[])
            variance=energy/10^(snr/10)/transform;
            noise=sqrt(variance/2)*(randn(stream,size(delayed))+1i*randn(stream,size(delayed)));
            for present=[true false]
                observed=double(present)*delayed+noise;
                rx=sixgr.phy.pucch.PUCCHReceiver.receive(observed,f.Carrier,assignment,context,args{:}, ...
                    'ShortUCIReceiverPolicy',p.policy);
                evidence=rx.ShortUCIReceiverEvidence;
                assert(evidence.Applied && ~evidence.PhysicalQualificationPassed && ...
                    ~evidence.TransmittedPayloadUsed && ~evidence.InjectedNoiseVarianceUsed && ...
                    evidence.LayoutHypothesesSearched==1 && rx.ReceiverOnlyAssignment && ...
                    ~rx.ReceiveTiming.OracleTimingUsed && ~rx.CRCApplicable && rx.UCICRCBitCount==0);
                assert(evidence.JointPresenceDecision.HypothesisCount==(diff(window)+1)*2^count && ...
                    rx.ReceiverUsable==(~rx.DTX && evidence.WordAccepted));
                if rx.ReceiverUsable
                    assert(isequal(rx.DecodedSequence1,evidence.Bits));
                else
                    assert(isempty(rx.DecodedSequence1) && isempty(rx.DecodedFields.CSIPart1));
                end
                if present && snr==max(p.snr_db)
                    assert(rx.ReceiverUsable && isequal(rx.DecodedSequence1,bits));
                end
                % Presence is not payload confidence. Reject the uncertain
                % word without falsely calling a detected waveform DTX.
                if present && ~rx.DTX && evidence.ConditionalWordPosterior<1
                    strict=p.policy; strict.minimum_word_posterior=1;
                    rejected=sixgr.phy.pucch.PUCCHReceiver.receive(observed,f.Carrier,assignment,context,args{:}, ...
                        'ShortUCIReceiverPolicy',strict);
                    assert(~rejected.DTX && ~rejected.ReceiverUsable && isempty(rejected.DecodedSequence1) && ...
                        rejected.DetectionOutcome=="detected" && ...
                        rejected.FailureReason=="short_uci_word_confidence_below_policy");
                    withheld=withheld+1;
                end
                row=table(count,prbs,branches,snr,present,rx.DTX,rx.ReceiverUsable, ...
                    evidence.ConditionalWordPosterior,nnz(evidence.Bits~=bits), ...
                    rx.ReceiveTiming.AppliedTimingCorrectionSamples, ...
                    'VariableNames',{'PayloadBits','PRBs','ReceiveBranches','FixtureSNRdB','ProducerPresent', ...
                    'DTX','ReceiverUsable','ConditionalWordPosterior','CandidateBitErrorsAuditOnly','AcquiredOffsetSamples'});
                rows=[rows;row]; %#ok<AGROW>
                writetable(rows,fullfile(folder,'physical_receiver.csv'));
            end
        end
    end
 end
end
assert(withheld>0,'test:MissingWordConfidenceCase','Exercise a detected but withheld noisy word.');
for field=["algorithm","target_false_alarm_probability","minimum_word_posterior"]
    bad=rmfield(p.policy,field);
    reject(@()sixgr.phy.pucch.PUCCHReceiver.receive(observed,f.Carrier,assignment,context,args{:}, ...
        'ShortUCIReceiverPolicy',bad),'sixgr:phy:pucch:InvalidJointShortUCIPolicy');
end
reject(@()sixgr.phy.pucch.PUCCHReceiver.receive(observed,f.Carrier,assignment,context, ...
    'NoiseVariance',NaN,'NoiseVarianceMode','received_dmrs_estimate','ShortUCIReceiverPolicy',p.policy), ...
    'sixgr:phy:rx:FlatAWGNObservationRequired');
badModel=model; badModel.ReceiveStreamExecutionSegments{1}.Execution.Links.Replay.ChannelFadingApplied=true;
reject(@()sixgr.phy.pucch.PUCCHReceiver.receive(observed,f.Carrier,assignment,context, ...
    'NoiseVariance',NaN,'NoiseVarianceMode','received_dmrs_estimate', ...
    'ShortUCIReceiverPolicy',p.policy,'ReceivedExecutionEvidence',badModel), ...
    'sixgr:phy:rx:FlatAWGNObservationRequired');
badModel=model; badModel.ReceiveStreamExecutionSegments{1}.Execution.RX.Replay.RFAppliedStageCount=1;
reject(@()sixgr.phy.pucch.PUCCHReceiver.receive(observed,f.Carrier,assignment,context, ...
    'NoiseVariance',NaN,'NoiseVarianceMode','received_dmrs_estimate', ...
    'ShortUCIReceiverPolicy',p.policy,'ReceivedExecutionEvidence',badModel), ...
    'sixgr:phy:rx:FlatAWGNObservationRequired');
reject(@()sixgr.phy.pucch.PUCCHReceiver.receive(observed,f.Carrier,txAssignment,f.Context,args{:}, ...
    'ShortUCIReceiverPolicy',p.policy),'sixgr:phy:pucch:UnsupportedJointShortUCIReceiver');
reject(@()sixgr.phy.pucch.PUCCHReceiver.receive(observed,f.Carrier,assignment,context, ...
    'NoiseVariance',1,'NoiseVarianceMode','provided', ...
    'ShortUCIReceiverPolicy',p.policy,'ReceivedExecutionEvidence',model), ...
    'sixgr:phy:pucch:UnsupportedJointShortUCIReceiver');
sixgr.util.jsonWrite(fullfile(folder,'scope.json'),struct('Config',p, ...
    'ConfigSHA256',sixgr.util.sha256File(path),'DetectorQualified',false, ...
    'SharedRuntimeIntegrated',false,'Scope',"actual_core_receiver_declared_matrix_connector_fixture", ...
    'ReceiverSHA256',sixgr.util.sha256File(which('sixgr.phy.pucch.PUCCHReceiver'))));
fprintf('PUCCH_FLAT_JOINT_RECEIVER_PASS cases=%d detected_words_withheld=%d qualified=0 shared_runtime=0 folder=%s\n', ...
    height(rows),withheld,folder);
ok=true;
end
function reject(action,id)
try, action(); catch cause
    assert(strcmp(cause.identifier,id),'Expected %s, got %s: %s',id,cause.identifier,cause.message); return;
end
error('test:JointReceiverGuardMissing','Expected %s.',id);
end
