function ok = testFRCReferenceQualificationCFOEvidence()
%TESTFRCREFERENCEQUALIFICATIONCFOEVIDENCE Audit positive-CFO CSV lineage.

setup6GRSimToolkit("Verbose", false, "RunToolboxChecks", false);
root = tempname;
mkdir(root);
cleanup = onCleanup(@() rmdir(root, "s")); %#ok<NASGU>

out = sixgr.conformance.runReferenceQualification(root, ...
    "Profile", "diagnostic", ...
    "EntryIds", "ul_g_fr1_a13_1_atg_awgn", ...
    "MinTransportBlocks", 1, "MaxTransportBlocks", 1, ...
    "BatchSize", 1, "MinimumBlockErrors", 0, "Verbose", false);
points = readtable(out.PointArtifacts.PointCSV, "TextType", "string");
assert(height(points) == 1 && points.ConfiguredModulation(1) == "64QAM" && ...
    abs(points.ConfiguredTargetCodeRate(1) - 948/1024) <= 1e-12 && ...
    abs(points.ConfiguredTargetCodeRate(1) - ...
    points.EffectiveTargetCodeRate(1)) <= 1e-12 && ...
    points.ConfiguredTBSBits(1) == 19968 && ...
    points.EffectiveTBSBits(1) == 19968 && ...
    points.ConfiguredCodedBitsPerSlot(1) == 21600 && ...
    points.EffectiveCodedBitsPerSlot(1) == 21600, ...
    "The UL FRC CSV does not preserve its configured/effective PHY point.");
assert(points.InjectedCFO_Hz(1) == 200 && ...
    isfinite(points.EstimatedCFO_Hz(1)) && ...
    isfinite(points.CFOCorrectionApplied_Hz(1)) && ...
    isfinite(points.ResidualCFOEstimated_Hz(1)) && ...
    isfinite(points.ResidualCFOPhysical_Hz(1)) && ...
    points.CFOPhysicalClosureError_Hz(1) <= 1e-12 && ...
    abs(points.ResidualCFOPhysical_Hz(1)) <= 150 && ...
    abs(points.ResidualCFOEstimated_Hz(1)) <= 150 && ...
    contains(lower(points.CFOEstimateSource(1)), "dmrs") && ...
    contains(lower(points.ResidualCFOEstimateSource(1)), "dmrs"), ...
    "Injected, estimated, applied, or residual UL CFO CSV evidence is invalid.");
assert(points.LastTBReceiverOk(1) && ~points.LastTBCRCError(1) && ...
    isfinite(points.DecoderNoiseVar(1)) && points.DecoderNoiseVar(1) > 0 && ...
    isfinite(points.PostEqSINR_dB(1)) && ...
    ~points.ProxyUsed(1) && ~points.FallbackUsed(1) && ...
    points.ApproximationMode(1) == "none", ...
    "The UL FRC CSV receiver or truth/proxy evidence is invalid.");
ok = true;
end
