function ok = testLLSBundleRuntimeEvidenceExports()
%TESTLLSBUNDLERUNTIMEEVIDENCEEXPORTS Ensure the active LLS bundle preserves antenna and ToD/ToA evidence into raw trial CSVs.

setup6GRSimToolkit("Verbose", false);

tmp = tempname;
mkdir(tmp);
c = onCleanup(@() rmdir(tmp, "s")); %#ok<NASGU>

scfg = sixgr.lls6g.config.loadScenarioConfig( ...
    fullfile(pwd, "simulator", "configs", "scenarios", "lls_100mhz_tdlc_bidirectional_truth.yaml"));
cfg = sixgr.lls6g.buildInternalConfig(scfg, fullfile(tmp, "run"));
% Five canonical slots are the minimal real TDD slice that reaches the
% K2=4 UL grant scheduled from DL slot 1: D,D,D,U,U.  This retains real
% DL/CSI-RS and UL/PUSCH execution while keeping the dedicated gate fast.
slotBudget = 5;
cfg.run.numFrames = slotBudget;
cfg.scenario.nUE = 1;
cfg.scenario.ue.nUE = 1;
cfg = sixgr.util.structSet(cfg, "lls6g.users.n_users", 1);
cfg = sixgr.util.structSet(cfg, "lls6g.users.enabled", true);
cfg = sixgr.util.structSet(cfg, "lls6g.users.execution_model", "slot_coupled_truth");
cfg = sixgr.util.structSet(cfg, "users.n_users", 1);
cfg = sixgr.util.structSet(cfg, "deployment_topology.num_ues", 1);
cfg = sixgr.util.structSet(cfg, "run.strictMode", false);
cfg = sixgr.util.structSet(cfg, "run.noProxyTruthContract", false);
cfg.channel.model = "TDL";
cfg.channel.tdlProfile = "TDL-C";
cfg.channel.awgnOnly = false;
cfg.channel.snr_dB = 18;
cfg.run.interferenceExecutionMode = "full_per_link_channel_waveform_sum";
cfg.phy.csirs.enable = true;
cfg.phy.csirs.nPorts = 1;
cfg.phy.csirs.rowNumber = 1;
slotDuration_s = max(eps, double(sixgr.util.structGet(cfg, "phy.numerology.slotDuration_ms", 1)) / 1e3);

runFolder = fullfile(tmp, "bundle", "air_interface");
opt = struct( ...
    "LinkDuration_s", slotBudget * slotDuration_s, ...
    "LinkMaxSimFrames", slotBudget, ...
    "LinkSNR_dB", cfg.channel.snr_dB, ...
    "LinkSNRGrid_dB", cfg.channel.snr_dB, ...
    "LinkSweepFrames", slotBudget, ...
    "LinkSweepTrialsPerSNR", slotBudget, ...
    "LinkReferenceSweepFrames", slotBudget, ...
    "LinkSweepMaxPoints", 1, ...
    "SaveFigures", false);
out = sixgr.truth.runWaveformLinkBundle(cfg, runFolder, opt);

dlCsv = fullfile(runFolder, "csv", "dl_pdsch_trials.csv");
ulCsv = fullfile(runFolder, "csv", "ul_pusch_trials.csv");
csirsCsv = fullfile(runFolder, "csv", "csi_rs_trials.csv");
assert(exist(dlCsv, "file") == 2 && exist(ulCsv, "file") == 2, ...
    "Waveform bundle must write the canonical raw DL/UL trial CSVs.");
assert(exist(csirsCsv, "file") == 2, ...
    "Waveform bundle must persist the dedicated runtime CSI-RS trial stream when CSI-RS is active.");

dlT = readtable(dlCsv, "VariableNamingRule", "preserve", "Delimiter", ",");
ulT = readtable(ulCsv, "VariableNamingRule", "preserve", "Delimiter", ",");
csirsT = readtable(csirsCsv, "VariableNamingRule", "preserve", "Delimiter", ",");
localAssertBundleEvidence(dlT, "DL", true);
localAssertBundleEvidence(ulT, "UL", false);
localAssertBundleCSIRSEvidence(csirsT);

ok = true;
end

function localAssertBundleCSIRSEvidence(T)
assert(istable(T) && ~isempty(T), ...
    "Runtime CSI-RS stream must contain rows when CSI-RS is active in the waveform bundle fixture.");
requiredVars = {'SignalFamily','Transmitted','Observed','Consumed','MeasurementSource', ...
    'RuntimeMaterializationStatus','TxRuntimeMaterializationStatus', ...
    'RxRuntimeObservationStatus','RuntimeEvidenceSource','RuntimeEventObserved'};
missingVars = requiredVars(~ismember(requiredVars, T.Properties.VariableNames));
assert(isempty(missingVars), ...
    "Runtime CSI-RS stream must preserve waveform-backed evidence columns. Missing: %s", strjoin(string(missingVars), ", "));
assert(all(strcmpi(string(T.SignalFamily), "CSI-RS")) && ...
    all(logical(T.Transmitted)) && all(logical(T.Observed)) && all(logical(T.Consumed)) && ...
    all(logical(T.RuntimeEventObserved)), ...
    "Runtime CSI-RS rows must describe transmitted, observed, and consumed CSI-RS waveform events.");
assert(all(strcmpi(string(T.MeasurementSource), "received_csirs_reference_signal_power")) && ...
    all(strcmpi(string(T.RuntimeMaterializationStatus), ...
        "post_canonical_auxiliary_grid_mapping")) && ...
    all(strcmpi(string(T.TxRuntimeMaterializationStatus), ...
        "post_canonical_auxiliary_grid_mapping")) && ...
    all(strcmpi(string(T.RxRuntimeObservationStatus), "runtime_observed")) && ...
    all(contains(string(T.RuntimeEvidenceSource), "PDSCH_Rx")), ...
    "Runtime CSI-RS rows must be sourced from receiver-observed CSI-RS RE measurements, not config-only scaffolding.");
end

function localAssertBundleEvidence(T, direction, requireAppliedPMI)
assert(istable(T) && ~isempty(T), ...
    "Expected nonempty raw %s bundle trial table.", direction);
requiredVars = { ...
    'BaseStationID','UEIndex','RNTI', ...
    'BSAntennaArrayClass','BSAntennaRows','BSAntennaCols','BSAntennaElements','BSAntennaNumPorts', ...
    'UEAntennaArrayClass','UEAntennaRows','UEAntennaCols','UEAntennaElements','UEAntennaNumPorts', ...
    'AntennaConfigSource','RuntimeAntennaObjectSource','AntennaRuntimeObjectCreated', ...
    'ChannelArrayModel','ChannelObjectSource','ChannelObjectClass','ChannelArrayHandlingStatus','ChannelArrayHandlingBlocker','ChannelGeometryCouplingLevel','GeometryAdapterType','GeometryAdapterSource','GeometryAdapterLimitation','GeometryAdapterPortMapping','ChannelUsesCountOnlyAntennaModel','ChannelUsesSameRuntimeAntennaAssumptions', ...
    'InterferenceChannelObjectSource','InterferenceChannelObjectClass','InterferenceChannelArrayHandlingStatus','InterferenceChannelArrayHandlingBlocker','InterferenceUsesSameRuntimeAntennaAssumptions','InterferencePathUsesSameArrayAssumptions', ...
    'PropagationDistance_m','GeometricPropagationDelay_s','PropagationDelay_s','ToD_s','ToA_s', ...
    'ToDSource','ToASource','ChannelDelaySource','AntennaGeometrySource','SameFlowEvidenceSource', ...
    'AppliedBeamIndexSet','AppliedPrecoderPMI','AppliedPrecoderMatrixSHA256','RequestedBeamIndexSet','RequestedPrecoderPMI','PrecoderSource','AppliedPrecoderSource','RequestedVsAppliedPrecoderPMIMatchStatus', ...
    'RequestedBeamTruthClassification','RequestedPrecoderPMITruthClassification', ...
    'AppliedBeamApplicationSource','AppliedBeamTruthClassification','AppliedPrecoderPMIApplicationSource','AppliedPrecoderPMITruthClassification'};
missingVars = requiredVars(~ismember(requiredVars, T.Properties.VariableNames));
assert(isempty(missingVars), ...
    "Raw %s bundle trial table must preserve antenna and ToD/ToA evidence columns. Missing: %s", ...
    direction, strjoin(string(missingVars), ", "));
assert(any(logical(T.AntennaRuntimeObjectCreated)), ...
    "Raw %s bundle trial rows must confirm runtime antenna object creation.", direction);
assert(any(strlength(string(T.BSAntennaArrayClass)) > 0) && any(strlength(string(T.UEAntennaArrayClass)) > 0), ...
    "Raw %s bundle trial rows must preserve BS/UE runtime array classes.", direction);
assert(any(isfinite(double(T.PropagationDistance_m))) && any(isfinite(double(T.ToD_s))) && any(isfinite(double(T.ToA_s))), ...
    "Raw %s bundle trial rows must preserve finite same-flow propagation and ToD/ToA evidence.", direction);
assert(all(strcmpi(string(T.ChannelArrayModel(isfinite(double(T.PropagationDistance_m)))), "nrtdl_runtime_geometry_correlation_channel")), ...
    "Raw %s bundle trial rows must disclose the active runtime channel-array model honestly.", direction);
mask = isfinite(double(T.PropagationDistance_m));
assert(all(strcmpi(string(T.ChannelObjectSource(mask)), "sixgr.channel.channelfactory.localcreatetdl")) && ...
    all(strcmpi(string(T.ChannelObjectClass(mask)), "nrtdlchannel")) && ...
    all(strcmpi(string(T.ChannelArrayHandlingStatus(mask)), "adapted_geometry_backed_reduced_representation")) && ...
    all(strcmpi(string(T.ChannelArrayHandlingBlocker(mask)), "nrtdlchannel_consumes_custom_spatial_correlation_matrices_not_runtime_array_objects")) && ...
    all(strcmpi(string(T.ChannelGeometryCouplingLevel(mask)), "runtime_geometry_reduced_spatial_correlation")) && ...
    all(strcmpi(string(T.GeometryAdapterType(mask)), "tdl_custom_tx_rx_correlation_from_runtime_element_positions")) && ...
    all(~logical(T.ChannelUsesCountOnlyAntennaModel(mask))) && ...
    all(~logical(T.ChannelUsesSameRuntimeAntennaAssumptions(mask))), ...
    "Raw %s bundle trial rows must disclose the serving TDL channel-object source and reduced geometry adapter boundary.", direction);
interferenceMask = mask & double(T.InterferenceContributorCount) > 0;
if any(interferenceMask)
    intStatus = string(T.InterferenceChannelArrayHandlingStatus(interferenceMask));
    intBlocker = string(T.InterferenceChannelArrayHandlingBlocker(interferenceMask));
    intCountOnly = strcmpi(intStatus, "count_only_spatial_dims_no_runtime_geometry");
    intAdapted = strcmpi(intStatus, "adapted_geometry_backed_reduced_representation");
    assert(all(intCountOnly | intAdapted) && ...
        all(strcmpi(string(T.InterferenceChannelObjectSource(interferenceMask)), "sixgr.channel.channelfactory.localcreatetdl")) && ...
        all(strcmpi(string(T.InterferenceChannelObjectClass(interferenceMask)), "nrtdlchannel")) && ...
        all(~logical(T.InterferenceUsesSameRuntimeAntennaAssumptions(interferenceMask))), ...
        "Raw %s bundle trial rows must keep interferer TDL array handling honest without claiming full runtime-array equivalence.", direction);
    assert(all(intBlocker(intCountOnly) == "runtime_geometry_not_supplied_or_not_mappable_to_tdl_custom_correlation") && ...
        all(intBlocker(intAdapted) == "nrtdlchannel_consumes_custom_spatial_correlation_matrices_not_runtime_array_objects"), ...
        "Raw %s bundle trial rows must use the exact blocker for the interferer TDL handling level.", direction);
    assert(all(logical(T.InterferencePathUsesSameArrayAssumptions(interferenceMask)) == intAdapted), ...
        "Raw %s bundle trial rows must only report matching serving/interferer array-handling assumptions when both use the reduced adapter.", direction);
else
    assert(localAllBlankOrMissing(T.InterferenceChannelArrayHandlingStatus(mask)) && ...
        localAllBlankOrMissing(T.InterferenceChannelObjectSource(mask)) && ...
        all(~logical(T.InterferenceUsesSameRuntimeAntennaAssumptions(mask))) && ...
        all(~logical(T.InterferencePathUsesSameArrayAssumptions(mask))), ...
        "Raw %s bundle trial rows must keep interference-channel array truth empty/false when no overlapping interferer channel was active.", direction);
end
assert(any(strcmpi(string(T.AntennaConfigSource), "browser_yaml_to_buildinternalconfig_to_coupledtruthruntime")), ...
    "Raw %s bundle trial rows must preserve the truthful antenna config provenance.", direction);
if requireAppliedPMI
    assert(any(strlength(string(T.AppliedBeamIndexSet)) > 0), ...
        "Raw %s bundle trial rows must preserve nonempty applied beam identifiers when known.", direction);
    validPMI = double(T.AppliedPrecoderPMI);
    matrixDigest = lower(strtrim(string(T.AppliedPrecoderMatrixSHA256)));
    validMatrixDigest = ~cellfun(@isempty, regexp(cellstr(matrixDigest), ...
        '^[0-9a-f]{64}$', 'once'));
    assert(any(isfinite(validPMI) | validMatrixDigest), ...
        "Raw %s bundle trial rows must preserve a real applied PMI or the exact applied precoder-matrix SHA-256.", direction);
    matrixOnly = ~isfinite(validPMI) & validMatrixDigest;
    assert(all(strcmpi(string(T.AppliedPrecoderPMIApplicationSource(matrixOnly)), ...
        "not_applicable_explicit_matrix_identified_by_sha256")) && ...
        all(strcmpi(string(T.AppliedPrecoderPMITruthClassification(matrixOnly)), ...
        "not_applicable_explicit_matrix_without_scalar_pmi")), ...
        "Raw %s explicit-matrix rows must not fabricate a scalar PMI.", direction);
else
    modeMask = strcmpi(string(T.PrecodingMode), "ul_codebook_tpmi");
    assert(any(modeMask), ...
        "Raw %s bundle trial rows must exercise the active native-codebook PUSCH TPMI path in this focused provenance test.", direction);
    assert(all(strcmpi(string(T.PrecoderSource(modeMask)), "ul_pusch_native_codebook_tpmi")) && ...
        all(strcmpi(string(T.AppliedPrecoderSource(modeMask)), "ul_pusch_native_codebook_tpmi")) && ...
        all(logical(T.BeamformingApplied(modeMask))) && ...
        all(strlength(strtrim(string(T.AppliedBeamIndexSet(modeMask)))) > 0) && ...
        all(isfinite(double(T.AppliedPrecoderPMI(modeMask)))) && ...
        all(strcmpi(string(T.AppliedBeamTruthClassification(modeMask)), "applied_runtime_value")) && ...
        all(strcmpi(string(T.AppliedPrecoderPMITruthClassification(modeMask)), "applied_runtime_value")) && ...
        all(strcmpi(string(T.AppliedBeamApplicationSource(modeMask)), "ul_pusch_native_codebook_tpmi_port_support")) && ...
        all(strcmpi(string(T.AppliedPrecoderPMIApplicationSource(modeMask)), "ul_pusch_native_codebook_tpmi")) && ...
        all(strcmpi(string(T.RequestedVsAppliedPrecoderPMIMatchStatus(modeMask)), "requested_matches_runtime_applied")) && ...
        all(strlength(string(T.RequestedBeamIndexSet(modeMask))) > 0) && ...
        all(strcmpi(string(T.RequestedBeamTruthClassification(modeMask)), "requested_reference")), ...
        "Raw %s bundle trial rows must keep UL requested beam references separate from runtime-applied native PUSCH TPMI and codebook port-support beam truth.", direction);
end
if strcmpi(direction, "UL")
    requiredULVars = {'NoiseVariance','NoiseVarStatus','NoiseVarSource','NoiseVarReason','NoiseVarStrictFailure', ...
        'ReceiverUsable','DecodeAttempted','DecodeUsable','FailureReason', ...
        'FrequencyHoppingApplied','FrequencyHoppingMode','FrequencyHoppingToolboxMode','SecondHopStartPRB'};
    missingULVars = requiredULVars(~ismember(requiredULVars, T.Properties.VariableNames));
    assert(isempty(missingULVars), ...
        "Raw %s bundle trial table must preserve UL noise-variance provenance fields. Missing: %s", ...
        direction, strjoin(string(missingULVars), ", "));
    assert(all(strlength(strtrim(string(T.NoiseVarStatus))) > 0) && ...
        all(strlength(strtrim(string(T.NoiseVarSource))) > 0), ...
        "Raw %s bundle trial rows must retain nonblank UL noise-variance provenance after canonical export.", direction);
    assert(all(strlength(strtrim(string(T.FrequencyHoppingMode))) > 0), ...
        "Raw %s bundle trial rows must retain the runtime-applied frequency-hopping mode after canonical export.", direction);
    disabledMask = ~logical(T.FrequencyHoppingApplied);
    assert(all(strcmpi(string(T.FrequencyHoppingMode(disabledMask)), "none")), ...
        "Raw %s bundle trial rows must label disabled runtime hopping as none, not infer an applied mode from configuration.", direction);
end
end

function tf = localAllBlankOrMissing(values)
if isnumeric(values)
    tf = all(~isfinite(double(values)));
    return;
end
vals = string(values);
vals = strip(vals);
tf = all(strlength(vals) == 0 | strcmpi(vals, "nan") | strcmpi(vals, "missing"));
end
