function ok = testTimingRelationEngine()
%TESTTIMINGRELATIONENGINE Exact K0/K1/K2 and TDD/BWP rejection reasons.

setup6GRSimToolkit("Verbose", false, "RunToolboxChecks", false);
[cc, dl0, ul1, state30, state60] = localFixture();
cc.setAvailabilityResolver(@(carrier, bwp, time, startSymbol, ...
    numSymbols, direction) localAvailability(carrier, bwp, time, ...
    startSymbol, numSymbols, direction, state30, state60));

activation = sixgr.phy.frame.AbsoluteTime.fromAbsoluteSlotSymbol( ...
    10, 0, ul1);
switchDecision = cc.BWPState.scheduleSwitch( ...
    "UL", "UL1", activation, ...
    "IssuedTime", sixgr.phy.frame.AbsoluteTime.fromTicks(0), ...
    "ControlBWPID", "DL0", ...
    "TriggerSource", "RRC", ...
    "CommandID", "activate-ul60");
assert(switchDecision.Accepted);

policy = struct( ...
    "AllowedK0", [0, 1, 3], ...
    "AllowedK1", [1, 18], ...
    "AllowedK2", [1, 8, 18, 21], ...
    "PolicyID", "focused_release18_timing_rows", ...
    "Source", "validated_test_policy");
engine = sixgr.phy.frame.TimingRelationEngine(cc, policy);

sourceControl = sixgr.phy.frame.AbsoluteTime.fromFrameSlotSymbol( ...
    0, 0, 0, dl0);
pdsch = localRequest("same-numerology-pdsch", "PDSCH", ...
    sourceControl, "DL0", "DL0", 1, 2, 10, 0);
rPDSCH = engine.resolvePDSCH(pdsch);
assert(rPDSCH.Valid && rPDSCH.ReasonCode == "timing_relation_valid");
assert(rPDSCH.SourceMu == 1 && rPDSCH.TargetMu == 1 && ...
    rPDSCH.TargetAbsoluteSlot == 1);

opposite = localRequest("fixed-opposite-pusch", "PUSCH", ...
    sourceControl, "DL0", "UL1", 21, 0, 4, 0);
rOpposite = engine.resolvePUSCH(opposite);
assert(~rOpposite.Valid && ...
    rOpposite.ReasonCode == "target_hits_fixed_opposite_direction", ...
    "A fixed-DL target must reject a PUSCH grant without time repair.");

beforeActivation = localRequest("early-ul60", "PUSCH", ...
    sourceControl, "DL0", "UL1", 8, 0, 4, 0);
rBefore = engine.resolvePUSCH(beforeActivation);
assert(~rBefore.Valid && ...
    rBefore.ReasonCode == "target_bwp_inactive_at_target_time");

mixed = localRequest("mixed-numerology-pusch", "PUSCH", ...
    sourceControl, "DL0", "UL1", 18, 0, 10, 2);
rMixed = engine.resolvePUSCH(mixed);
assert(rMixed.Valid && rMixed.SourceMu == 1 && rMixed.TargetMu == 2);
assert(rMixed.TargetAbsoluteSlot == 18 && ...
    rMixed.AvailabilityReasonCode == "available");
assert(rMixed.TargetTick == ...
    sixgr.phy.frame.AbsoluteTime.fromAbsoluteSlotSymbol( ...
    18, 0, ul1).tickValue());

n2 = mixed;
n2.TestID = "insufficient-n2";
n2.MinimumProcessingSymbols = 1000;
rN2 = engine.resolvePUSCH(n2);
assert(~rN2.Valid && rN2.ReasonCode == ...
    "insufficient_n2_processing_time");

harqSource = sixgr.phy.frame.AbsoluteTime.fromFrameSlotSymbol( ...
    0, 0, 2, dl0);
harq = localRequest("mixed-numerology-harq", "HARQ_ACK", ...
    harqSource, "DL0", "UL1", 18, 0, 2, 2);
harq.SourceNumSymbols = 10;
harq.HARQProcessID = 3;
rHARQ = engine.resolveHARQACK(harq);
assert(rHARQ.Valid && rHARQ.K1 == 18 && rHARQ.TargetMu == 2);

n1 = harq;
n1.TestID = "insufficient-n1";
n1.MinimumProcessingSymbols = 1000;
rN1 = engine.resolveHARQACK(n1);
assert(~rN1.Valid && rN1.ReasonCode == ...
    "insufficient_n1_processing_time");

flex = localRequest("unresolved-flex", "PDSCH", ...
    sourceControl, "DL0", "DL0", 3, 0, 4, 0);
rFlex = engine.resolvePDSCH(flex);
assert(~rFlex.Valid && rFlex.ReasonCode == ...
    "target_flexible_symbols_unresolved");

allocation = struct( ...
    "AbsoluteSlot", 3, ...
    "StartSymbol", 0, ...
    "NumSymbols", 4, ...
    "Direction", "DL", ...
    "Channel", "PDSCH", ...
    "DecisionSource", "test_scheduler");
state30 = sixgr.phy.frame.FlexibleSymbolAllocator.allocate( ...
    state30, allocation);
cc.setAvailabilityResolver(@(carrier, bwp, time, startSymbol, ...
    numSymbols, direction) localAvailability(carrier, bwp, time, ...
    startSymbol, numSymbols, direction, state30, state60));
rResolved = engine.resolvePDSCH(flex);
assert(rResolved.Valid && rResolved.ReasonCode == "timing_relation_valid");

badK = mixed;
badK.TestID = "unsupported-k2";
badK.K2 = 7;
rBadK = engine.resolvePUSCH(badK);
assert(~rBadK.Valid && rBadK.ReasonCode == "unsupported_k2", ...
    "An unsupported K value must not be repaired to a later slot.");

trace = engine.traceTable();
assert(height(trace) == 10 && ...
    all(strlength(trace.ReasonCode) > 0) && ...
    all(trace.Status == "PASS" | trace.Status == "REJECTED"));
assert(any(trace.ReasonCode == "target_flexible_symbols_unresolved") && ...
    any(trace.ReasonCode == "insufficient_n1_processing_time") && ...
    any(trace.ReasonCode == "insufficient_n2_processing_time"));

% Exhaust the pinned timing catalogs across every supported processing
% capability numerology.  K0/K2 come from every selected TDRA catalog row;
% K1 comes from every Release-18 default-K1 row for that numerology.
coverage = localExerciseCatalogTimingRows();
assert(coverage.Numerologies == 6 && ...
    coverage.K0Rows == 24 && coverage.K1Rows == 48 && ...
    coverage.K2Rows == 12 && coverage.CapabilityChecks == 24, ...
    "The programmatic timing catalog coverage is incomplete.");

tmp = string(tempname);
mkdir(tmp);
cleanup = onCleanup(@() rmdir(tmp, "s")); %#ok<NASGU>
csvPath = fullfile(tmp, "timing_matrix.csv");
writetable(trace, csvPath);
assert(isfile(csvPath) && dir(csvPath).bytes > 0);
imagePath = fullfile(tmp, "k0_k1_k2_timeline.png");
fig = figure("Visible", "off");
figCleanup = onCleanup(@() close(fig)); %#ok<NASGU>
validRows = trace.TargetTick >= 0;
scatter(double(trace.SourceTick(validRows)), ...
    double(trace.TargetTick(validRows)), 35, ...
    double(trace.Valid(validRows)), "filled");
xlabel("source absolute tick");
ylabel("target absolute tick");
title("K0 / K1 / K2 exact timing");
grid on;
exportgraphics(fig, imagePath, "Resolution", 120);
assert(isfile(imagePath) && dir(imagePath).bytes > 1000);

ok = true;
end

function request = localRequest(testID, procedure, sourceTime, ...
        sourceBWPID, targetBWPID, k, targetStart, targetLength, ...
        minimumProcessingSymbols)
request = struct( ...
    "TestID", testID, ...
    "Procedure", procedure, ...
    "SourceTime", sourceTime, ...
    "SchedulingCCID", "CC0", ...
    "ScheduledCCID", "CC0", ...
    "CarrierIndicator", 0, ...
    "SourceBWPID", sourceBWPID, ...
    "TargetBWPID", targetBWPID, ...
    "SourceNumSymbols", 2, ...
    "TargetStartSymbol", targetStart, ...
    "TargetNumSymbols", targetLength, ...
    "MinimumProcessingSymbols", minimumProcessingSymbols, ...
    "ProcessingTimeReference", "source", ...
    "TimingAdvanceTicks", 0, ...
    "HARQProcessID", 0);
switch upper(procedure)
    case "PDSCH"
        request.K0 = k;
    case "PUSCH"
        request.K2 = k;
    otherwise
        request.K1 = k;
end
end

function [cc, dl0, ul1, state30, state60] = localFixture()
grid = struct("NStartGrid", 0, "NSizeGrid", 273, ...
    "SubcarrierSpacingKHz", 30, "FrequencyRange", "FR1");
zero = sixgr.phy.frame.AbsoluteTime.fromTicks(0);
dl0 = sixgr.phy.frame.BWPConfig(localBWP( ...
    "DL0", "DL", 30, 0, 200, true, zero, "DL0", "DL0"), grid);
ul0 = sixgr.phy.frame.BWPConfig(localBWP( ...
    "UL0", "UL", 30, 0, 200, true, zero, "DL0", "UL0"), grid);
ulActivation = sixgr.phy.frame.AbsoluteTime.fromAbsoluteSlotSymbol( ...
    10, 0, localNumerology(60));
ul1 = sixgr.phy.frame.BWPConfig(localBWP( ...
    "UL1", "UL", 60, 0, 120, false, ulActivation, "DL0", "UL1"), grid);
carrier = struct( ...
    "CCID", "CC0", ...
    "ServingCellID", "CELL0", ...
    "SchedulingCCIDs", "CC0", ...
    "CenterFrequencyHz", 4e9, ...
    "Band", "n77", ...
    "FrequencyRange", "FR1", ...
    "ChannelBandwidthMHz", 100, ...
    "DuplexMode", "TDD", ...
    "DLCarrierGrid", struct("NStartGrid", 0, "NSizeGrid", 273, ...
    "SubcarrierSpacingKHz", 30), ...
    "ULCarrierGrid", struct("NStartGrid", 0, "NSizeGrid", 273, ...
    "SubcarrierSpacingKHz", 30), ...
    "CarrierIndicatorMap", struct( ...
    "Indicator", 0, "ScheduledCCID", "CC0"));
cc = sixgr.phy.frame.ComponentCarrierConfig(carrier, {dl0, ul0, ul1});

pattern = struct( ...
    "PeriodicityMilliseconds", 5, ...
    "NumDownlinkSlots", 2, ...
    "NumDownlinkSymbols", 10, ...
    "NumUplinkSlots", 1, ...
    "NumUplinkSymbols", 2);
common30 = sixgr.phy.frame.TDDCommonConfig.resolve( ...
    "ReferenceSubcarrierSpacingKHz", 30, ...
    "ActiveSubcarrierSpacingKHz", 30, ...
    "CyclicPrefix", "normal", ...
    "Pattern1", pattern);
common60 = sixgr.phy.frame.TDDCommonConfig.resolve( ...
    "ReferenceSubcarrierSpacingKHz", 30, ...
    "ActiveSubcarrierSpacingKHz", 60, ...
    "CyclicPrefix", "normal", ...
    "Pattern1", pattern);
state30 = sixgr.phy.frame.FlexibleSymbolAllocator.initialize(common30);
state60 = sixgr.phy.frame.FlexibleSymbolAllocator.initialize(common60);
end

function result = localAvailability(~, bwp, slotStart, startSymbol, ...
        numSymbols, direction, state30, state60)
[frame, slot, ~, aligned] = slotStart.toNumerology(bwp);
if ~aligned
    result = struct( ...
        "Available", false, ...
        "ReasonCode", "slot_start_not_numerology_aligned", ...
        "ObservedDirections", "UNKNOWN", ...
        "DuplexMode", "TDD");
    return;
end
absoluteSlot = double(frame) * bwp.SlotsPerFrame + double(slot);
if bwp.SCSKHz == 30
    state = state30;
else
    state = state60;
end
result = sixgr.phy.frame.SlotFormatResolver.isAvailable( ...
    state, absoluteSlot, startSymbol, numSymbols, direction);
end

function cfg = localBWP(id, direction, scs, startRB, sizeRB, active, ...
        activation, controlBWPID, dataBWPID)
cfg = struct( ...
    "BWPID", id, ...
    "Direction", direction, ...
    "CCID", "CC0", ...
    "ServingCellID", "CELL0", ...
    "FrequencyRange", "FR1", ...
    "SCSKHz", scs, ...
    "CyclicPrefix", "normal", ...
    "NStartBWP", startRB, ...
    "NSizeBWP", sizeRB, ...
    "ControlConfigRef", lower(direction) + "_control_" + id, ...
    "DataConfigRef", lower(direction) + "_data_" + id, ...
    "ControlBWPID", controlBWPID, ...
    "DataBWPID", dataBWPID, ...
    "ActiveInitial", active, ...
    "SwitchActivationTime", activation, ...
    "StateVersion", 1, ...
    "CommonTDDReferenceSCSKHz", 30);
end

function num = localNumerology(scs)
num = sixgr.phy.frame.NumerologyCatalog.resolve( ...
    scs, "normal", "generic_waveform_test", "");
end

function coverage = localExerciseCatalogTimingRows()
supportedMu = [0, 1, 2, 3, 5, 6];
tdra = sixgr.phy.frame.TimeDomainResourceAllocationCatalog.selectedRows();
channels = string({tdra.Channel});
pdsRows = tdra(channels == "PDSCH");
pusRows = tdra(channels == "PUSCH");
catalogK0 = unique([pdsRows.K0], "stable");
catalogK0 = catalogK0(isfinite(catalogK0));
catalogK2 = unique([pusRows.K2], "stable");
catalogK2 = catalogK2(isfinite(catalogK2));
assert(isequal(catalogK0, [0, 1]) && isequal(catalogK2, 1), ...
    "Selected TDRA catalog timing rows changed without test review.");

coverage = struct("Numerologies", 0, "K0Rows", 0, ...
    "K1Rows", 0, "K2Rows", 0, "CapabilityChecks", 0);
for mu = supportedMu
    [carrier, dl, ul] = localCatalogCarrier(mu);
    capability = sixgr.phy.frame.TimingPolicyCatalog.capability1(mu);
    catalogK1 = sixgr.phy.frame.TimingPolicyCatalog.defaultK1Values(mu);
    legalK2 = ceil((capability.PUSCHN2Symbols + 1) / ...
        ul.SymbolsPerSlot);
    policy = struct( ...
        "AllowedK0", catalogK0, ...
        "AllowedK1", catalogK1, ...
        "AllowedK2", unique([catalogK2, legalK2], "stable"), ...
        "PolicyID", "catalog-exhaustion-mu" + string(mu), ...
        "Source", "pinned_release18_catalog_test");
    engine = sixgr.phy.frame.TimingRelationEngine(carrier, policy);
    source = sixgr.phy.frame.AbsoluteTime.fromAbsoluteSlotSymbol( ...
        1000, 0, dl);

    for rowIndex = 1:numel(pdsRows)
        row = pdsRows(rowIndex);
        request = localRequest("catalog-" + lower(row.ID) + ...
            "-mu" + string(mu), "PDSCH", source, ...
            "DL0", "DL0", row.K0, row.StartSymbol, ...
            row.NumSymbols, 0);
        result = engine.resolvePDSCH(request);
        assert(result.Valid && result.K0 == row.K0 && ...
            result.TargetMu == mu, ...
            "Catalog row %s failed at mu=%d: %s.", ...
            row.ID, mu, result.ReasonCode);
        coverage.K0Rows = coverage.K0Rows + 1;
    end

    for k1 = catalogK1
        request = localRequest("catalog-k1-mu" + string(mu) + ...
            "-k" + string(k1), "HARQ_ACK", source, ...
            "DL0", "UL0", k1, 0, 1, 0);
        request.SourceNumSymbols = 1;
        result = engine.resolveHARQACK(request);
        assert(result.Valid && result.K1 == k1 && ...
            result.TargetMu == mu, ...
            "Catalog K1=%d failed at mu=%d: %s.", ...
            k1, mu, result.ReasonCode);
        coverage.K1Rows = coverage.K1Rows + 1;
    end

    for rowIndex = 1:numel(pusRows)
        row = pusRows(rowIndex);
        request = localRequest("catalog-" + lower(row.ID) + ...
            "-mu" + string(mu), "PUSCH", source, ...
            "DL0", "UL0", row.K2, row.StartSymbol, ...
            row.NumSymbols, 0);
        request.SourceNumSymbols = 1;
        result = engine.resolvePUSCH(request);
        assert(result.Valid && result.K2 == row.K2 && ...
            result.TargetMu == mu, ...
            "Catalog row %s failed at mu=%d: %s.", ...
            row.ID, mu, result.ReasonCode);
        coverage.K2Rows = coverage.K2Rows + 1;
    end

    legalN1 = localRequest("capability-n1-legal-mu" + string(mu), ...
        "HARQ_ACK", source, "DL0", "UL0", max(catalogK1), ...
        0, 1, capability.PDSCHN1Symbols);
    legalN1.SourceNumSymbols = 1;
    legalN1.ProcessingTimeReference = ...
        capability.PDSCHProcessingTimeReference;
    legalN1Result = engine.resolveHARQACK(legalN1);
    assert(legalN1Result.Valid, ...
        "Pinned N1=%d should be feasible at mu=%d and K1=%d: %s.", ...
        capability.PDSCHN1Symbols, mu, max(catalogK1), ...
        legalN1Result.ReasonCode);

    illegalN1 = legalN1;
    illegalN1.TestID = "capability-n1-illegal-mu" + string(mu);
    illegalN1.K1 = min(catalogK1);
    illegalN1.MinimumProcessingSymbols = ...
        capability.PDSCHN1Symbols + 10000;
    illegalN1Result = engine.resolveHARQACK(illegalN1);
    assert(~illegalN1Result.Valid && ...
        illegalN1Result.ReasonCode == ...
            "insufficient_n1_processing_time", ...
        "Illegal N1 case at mu=%d returned valid=%d reason=%s.", ...
        mu, illegalN1Result.Valid, illegalN1Result.ReasonCode);

    legalN2 = localRequest("capability-n2-legal-mu" + string(mu), ...
        "PUSCH", source, "DL0", "UL0", legalK2, ...
        0, 1, capability.PUSCHN2Symbols);
    legalN2.SourceNumSymbols = 1;
    legalN2.ProcessingTimeReference = ...
        capability.PUSCHProcessingTimeReference;
    legalN2Result = engine.resolvePUSCH(legalN2);
    assert(legalN2Result.Valid, ...
        "Pinned N2=%d should be feasible at mu=%d and K2=%d: %s.", ...
        capability.PUSCHN2Symbols, mu, legalK2, ...
        legalN2Result.ReasonCode);

    illegalN2 = legalN2;
    illegalN2.TestID = "capability-n2-illegal-mu" + string(mu);
    illegalN2.K2 = catalogK2(1);
    illegalN2.MinimumProcessingSymbols = ...
        capability.PUSCHN2Symbols + 10000;
    illegalN2Result = engine.resolvePUSCH(illegalN2);
    assert(~illegalN2Result.Valid && ...
        illegalN2Result.ReasonCode == ...
            "insufficient_n2_processing_time", ...
        "Illegal N2 case at mu=%d returned valid=%d reason=%s.", ...
        mu, illegalN2Result.Valid, illegalN2Result.ReasonCode);

    coverage.Numerologies = coverage.Numerologies + 1;
    coverage.CapabilityChecks = coverage.CapabilityChecks + 4;
end
end

function [carrier, dl, ul] = localCatalogCarrier(mu)
[range, centerHz, bandwidthMHz, nrb] = localCatalogGridRow(mu);
scsKHz = 15 * 2^mu;
grid = struct("NStartGrid", 0, "NSizeGrid", nrb, ...
    "SubcarrierSpacingKHz", scsKHz, ...
    "CyclicPrefix", "normal", "FrequencyRange", range);
zero = sixgr.phy.frame.AbsoluteTime.fromTicks(0);
dl = sixgr.phy.frame.BWPConfig(localCatalogBWP( ...
    "DL0", "DL", range, scsKHz, nrb, zero), grid);
ul = sixgr.phy.frame.BWPConfig(localCatalogBWP( ...
    "UL0", "UL", range, scsKHz, nrb, zero), grid);
cfg = struct( ...
    "CCID", "CC0", "ServingCellID", "CELL0", ...
    "SchedulingCCIDs", "CC0", ...
    "CenterFrequencyHz", centerHz, ...
    "DLCenterFrequencyHz", centerHz, ...
    "ULCenterFrequencyHz", centerHz - 100e6, ...
    "Band", "catalog_test", "FrequencyRange", range, ...
    "ChannelBandwidthMHz", bandwidthMHz, "DuplexMode", "FDD", ...
    "DLCarrierGrid", grid, "ULCarrierGrid", grid, ...
    "CarrierIndicatorMap", struct( ...
        "Indicator", 0, "ScheduledCCID", "CC0"));
carrier = sixgr.phy.frame.ComponentCarrierConfig(cfg, {dl, ul});
end

function cfg = localCatalogBWP(id, direction, range, scs, nrb, zero)
cfg = struct( ...
    "BWPID", id, "Direction", direction, ...
    "CCID", "CC0", "ServingCellID", "CELL0", ...
    "FrequencyRange", range, "SCSKHz", scs, ...
    "CyclicPrefix", "normal", "NStartBWP", 0, ...
    "NSizeBWP", nrb, ...
    "ControlConfigRef", "catalog_control", ...
    "DataConfigRef", "catalog_data", ...
    "ControlBWPID", "DL0", "DataBWPID", id, ...
    "ActiveInitial", true, "SwitchActivationTime", zero, ...
    "StateVersion", 0, "CommonTDDReferenceSCSKHz", NaN);
end

function [range, centerHz, bandwidthMHz, nrb] = ...
        localCatalogGridRow(mu)
switch mu
    case 0
        range = "FR1"; centerHz = 4e9; bandwidthMHz = 3; nrb = 15;
    case 1
        range = "FR1"; centerHz = 4e9; bandwidthMHz = 10; nrb = 24;
    case 2
        range = "FR1"; centerHz = 4e9; bandwidthMHz = 20; nrb = 24;
    case 3
        range = "FR2-1"; centerHz = 28e9; bandwidthMHz = 50; nrb = 32;
    case 5
        range = "FR2-2"; centerHz = 60e9; bandwidthMHz = 400; nrb = 66;
    case 6
        range = "FR2-2"; centerHz = 60e9; bandwidthMHz = 400; nrb = 33;
    otherwise
        error("sixgr:test:UnsupportedCatalogMu", ...
            "No test carrier row is configured for mu=%d.", mu);
end
end
