function ok = testFRCPUSCHCFOTracking()
%TESTFRCPUSCHCFOTRACKING Guard measured UL CFO and residual provenance.

setup6GRSimToolkit("Verbose", false, "RunToolboxChecks", false);
cases = { ...
    "ul_g_fr1_a3a_1_awgn", "awgn_1x2", -5.1, 0; ...
    "ul_g_fr1_a13_1_atg_awgn", "atg_awgn_200hz_1x2", 19.1, 200};
subcarrierSpacingHz = 15e3;
for index = 1:size(cases, 1)
    entryId = cases{index, 1};
    conditionId = cases{index, 2};
    snr_dB = cases{index, 3};
    injectedCFO_Hz = cases{index, 4};
    result = sixgr.conformance.runFRCPoint( ...
        entryId, conditionId, "SNRGrid_dB", snr_dB, ...
        "ExecutionProfile", "smoke", ...
        "MinTransportBlocks", 1, "MaxTransportBlocks", 1, ...
        "BatchSize", 1, "MinimumBlockErrors", 0, ...
        "EvaluateSymmetricRegression", false, ...
        "RequireExactStandardExecution", true, ...
        "RequireExactDataChannelExecution", true, ...
        "PrintTable", false, "Verbose", false);
    assert(result.Sweep.DeliveredTransportBlocks(1) == 1 && ...
        result.Sweep.Transmissions(1) == 1, ...
        "UL FRC %s did not decode on its first transmission.", entryId);
    rx = result.PointDetails{1}.LastTransportBlockAttemptRx{1};
    assert(rx.Ok && rx.CFOCorrectionApplied && ...
        rx.CFOEstimateSource == "dmrs_reference_symbol_phase_slope", ...
        "UL FRC %s did not use measured PUSCH DM-RS CFO acquisition.", ...
        entryId);
    assert(rx.ResidualCFOEstimateSource == ...
        "dmrs_reference_symbol_phase_slope_post_receiver_correction", ...
        "UL FRC %s did not disclose its post-correction estimator.", ...
        entryId);
    expectedPhysicalResidual = injectedCFO_Hz - ...
        rx.CFOCorrectionApplied_Hz;
    assert(abs(rx.ResidualCFOPhysical_Hz - expectedPhysicalResidual) < 1e-9, ...
        ("UL FRC %s physical residual must equal injected CFO minus the " + ...
        "actually applied measured correction."), entryId);
    assert(abs(rx.ResidualCFOPhysical_Hz) <= 0.01 * subcarrierSpacingHz, ...
        ("UL FRC %s physical residual %.6f Hz exceeds one percent of " + ...
        "subcarrier spacing."), entryId, rx.ResidualCFOPhysical_Hz);
    assert(isfinite(rx.ResidualCFO_EstimatedPostCorrection_Hz) && ...
        abs(rx.ResidualCFO_EstimatedPostCorrection_Hz) <= ...
        0.01 * subcarrierSpacingHz, ...
        "UL FRC %s receiver residual estimate is unavailable or excessive.", ...
        entryId);
    detail = result.PointDetails{1};
    assert(~detail.ProxyUsed && ~detail.FallbackUsed && ...
        ~detail.TruthUnavailableRescueUsed, ...
        "UL FRC %s used proxy, fallback, or unavailable-truth rescue.", ...
        entryId);
end
ok = true;
end
