function ok = testFTP3TrafficDeterminism()
%TESTFTP3TRAFFICDETERMINISM FTP3 arrivals must be exact and replayable.

setup6GRSimToolkit("Verbose", false);
cfg = sixgr.config.defaultConfig();
cfg.run.seed = 19031;
cfg.traffic.model = "ftp3";
cfg.traffic.ftp3 = struct( ...
    "fileSizeBytes", 500000, ...
    "arrivalRatePerCell_s", 100, ...
    "direction", "UL", ...
    "seed", 77123);

a = sixgr.system.TrafficFactory.generate(cfg, 4, 100, 1e-3, ...
    "NumCells", 3);
b = sixgr.system.TrafficFactory.generate(cfg, 4, 100, 1e-3, ...
    "NumCells", 3);

assert(isequal(a.OfferedBitsUL, b.OfferedBitsUL) && ...
    isequal(a.EventTable, b.EventTable), ...
    "Identical FTP3 seeds/configuration must reproduce the exact event ledger.");
assert(all(a.OfferedBitsDL == 0, "all") && height(a.EventTable) > 0, ...
    "UL FTP3 must not inject DL traffic and must create events in this fixture.");
assert(sum(a.OfferedBitsUL, "all") == ...
    height(a.EventTable) * cfg.traffic.ftp3.fileSizeBytes * 8, ...
    "Offered bits must equal the exact file-event ledger.");
assert(all(a.EventTable.ArrivalTTI >= 1 & a.EventTable.ArrivalTTI <= 100) && ...
    all(a.EventTable.UEID >= 1 & a.EventTable.UEID <= 4), ...
    "Every FTP3 event must map to an in-range TTI and UE.");
assert(a.TransportTruthLabel == ...
    "truthful_application_arrival_ledger_no_tcp_claim" && ...
    ~a.ProxyShapingUsed, ...
    "FTP3 must expose application-arrival truth without a TCP claim.");

cfg.traffic.ftp3.seed = 77124;
c = sixgr.system.TrafficFactory.generate(cfg, 4, 100, 1e-3, ...
    "NumCells", 3);
assert(~isequal(a.EventTable(:, 2:4), c.EventTable(:, 2:4)), ...
    "A different FTP3 seed must produce a different paired-drop ledger.");

cfg.traffic.ftp3.arrivalRatePerCell_s = 0;
z = sixgr.system.TrafficFactory.generate(cfg, 4, 100, 1e-3, ...
    "NumCells", 3);
assert(height(z.EventTable) == 0 && sum(z.OfferedBits, "all") == 0, ...
    "Zero-rate FTP3 must preserve an empty typed ledger without fake arrivals.");

ok = true;
end
