function ok = testPDSCHPTRSPortAssociation()
%TESTPDSCHPTRSPORTASSOCIATION Validate explicit PT-RS/DM-RS association.

setup6GRSimToolkit("Verbose", false, "RunToolboxChecks", false);
policy = struct( ...
    "MinimumPRBs", 3, "MinimumDurationSymbols", 3, ...
    "MinimumMCSIndex", 0, "AllowedRNTITypes", "C-RNTI");
request = struct( ...
    "MappingType", "A", "TimeDensity", 2, ...
    "FrequencyDensity", 2, "REOffset", "01", ...
    "PDSCHDuration", 12, "NPRB", 24, ...
    "MCSIndex", 20, "MCSTable", "qam256", ...
    "RNTIType", "C-RNTI", ...
    "PTRSPortSet", 8, "DMRSPortSet", [0 8]);
before = request;
resolved = sixgr.pdsch.PDSCHPTRSResolver.resolve(request, policy);
assert(resolved.Present && resolved.AssociatedDMRSPort == 8 && ...
    isequaln(request, before), ...
    "A valid nonconsecutive DM-RS port association was not preserved.");

bad = request;
bad.PTRSPortSet = 7;
localAssertError(@() sixgr.pdsch.PDSCHPTRSResolver. ...
    resolve(bad, policy), ...
    "sixgr:pdsch:InvalidPTRSPortAssociation");
multiple = request;
multiple.PTRSPortSet = [0 8];
localAssertError(@() sixgr.pdsch.PDSCHPTRSResolver. ...
    resolve(multiple, policy), ...
    "sixgr:pdsch:InvalidPTRSPortAssociation");
duplicate = request;
duplicate.PTRSPortSet = [8 8];
localAssertError(@() sixgr.pdsch.PDSCHPTRSResolver. ...
    resolve(duplicate, policy), ...
    "sixgr:pdsch:InvalidPTRSPortSet");
ok = true;
end

function localAssertError(fn, expectedID)
try
    fn();
catch ME
    assert(string(ME.identifier) == string(expectedID), ...
        "Observed %s, expected %s.", ME.identifier, expectedID);
    return;
end
error("sixgr:test:ExpectedErrorNotThrown", ...
    "Expected error %s was not thrown.", expectedID);
end
