function ok = testCoupledServingRSRPProvenance()
%TESTCOUPLEDSERVINGRSRPPROVENANCE Do not label zero-loss scores as field RSRP.

setup6GRSimToolkit("Verbose", false);
scenario = sixgr.lls6g.config.loadScenarioConfig(fullfile( ...
    "simulator", "configs", "scenarios", ...
    "lls_causal_access_to_data_wiring.yaml"));
cfg = sixgr.lls6g.buildInternalConfig(scenario, tempdir);
assert(logical(sixgr.util.structGet(cfg, "channel.pathlossEnabled", false)) && ...
    string(sixgr.util.structGet(cfg, "channel.pathlossModel", "")) == "nrPathLoss", ...
    "The causal field-wiring scenario must explicitly enable nrPathLoss.");

multiUser = struct("Enabled", false, "NumUsers", 1, "RNTIStart", 1, ...
    "ExecutionModel", "slot_coupled_truth");
state = sixgr.truth.CoupledTruthRuntime.initialize( ...
    cfg, tempdir, multiUser, struct(), 1);
state = sixgr.truth.CoupledTruthRuntime.advanceFrame(state, cfg, multiUser, 1, 20);
row = state.ServingTraceTable(end,:);
[runtimeRSRP, runtimeSource] = ...
    sixgr.truth.CoupledTruthRuntime.resolveReportableServingRSRPRuntime( ...
    state, 1, double(row.ServingCell));
assert(isfinite(double(row.ServingRSRP_dBm)) && ...
    isfinite(double(row.Pathloss_dB)) && double(row.Pathloss_dB) > 0 && ...
    string(row.ServingRSRPSource) == ...
    "large_scale_pathloss_applied_per_reference_re_power", ...
    "Pathloss-enabled serving RSRP must have an applied-loss provenance.");
assert(abs(double(runtimeRSRP) - double(row.ServingRSRP_dBm)) < 1e-9 && ...
    string(runtimeSource) == string(row.ServingRSRPSource), ...
    ["The public shared-slot measurement boundary must expose the same " ...
    "pathloss-qualified serving RSRP as the canonical serving trace."]);

cfgOff = sixgr.util.structSet(cfg, "channel.pathlossEnabled", false);
cfgOff = sixgr.util.structSet(cfgOff, "channel.pathloss.enabled", false);
stateOff = sixgr.truth.CoupledTruthRuntime.initialize( ...
    cfgOff, tempdir, multiUser, struct(), 1);
stateOff = sixgr.truth.CoupledTruthRuntime.advanceFrame( ...
    stateOff, cfgOff, multiUser, 1, 20);
rowOff = stateOff.ServingTraceTable(end,:);
[runtimeRSRPOff, runtimeSourceOff] = ...
    sixgr.truth.CoupledTruthRuntime.resolveReportableServingRSRPRuntime( ...
    stateOff, 1, double(rowOff.ServingCell));
assert(isnan(double(rowOff.ServingRSRP_dBm)) && ...
    string(rowOff.ServingRSRPSource) == ...
    "unavailable_pathloss_disabled_no_field_rsrp", ...
    ["A zero-loss selection score must remain internal and must not be " ...
    "exported as absolute serving RSRP in dBm."]);
assert(isnan(double(runtimeRSRPOff)) && ...
    string(runtimeSourceOff) == string(rowOff.ServingRSRPSource), ...
    "The public boundary must preserve the pathloss-disabled fail-closed result.");

ok = true;
end
