function ok = testPRACHCorrelationTraceAdapter()
%TESTPRACHCORRELATIONTRACEADAPTER Guard alias handling and truth separation.

setup6GRSimToolkit("Verbose", false);

sourceT = table((1:8).', (-3:4).', [0.1;0.2;0.4;0.9;0.5;0.3;0.2;0.1], ...
    repmat("real_lls_evidence", 8, 1), ...
    'VariableNames', ["SampleIndex","LagSamples","CorrelationAbs","TruthStatus"]);
T = sixgr.visual.normalizePRACHCorrelationTrace(sourceT);
required = ["trial_id","preamble_index","root_sequence_index","restricted_set_type","n_cs", ...
    "zero_correlation_zone_config","lag_samples","lag_us","correlation_abs","threshold", ...
    "noise_floor","peak_lag_samples","timing_advance_samples","detection_result", ...
    "false_alarm","missed_detection","snr_db","cfo_hz","seed","truth_status"];
assert(all(ismember(required, string(T.Properties.VariableNames))) && height(T) == 8, ...
    "PRACH trace adapter must emit the complete canonical schema.");
assert(isequal(T.lag_samples, (-3:4).') && isequal(T.correlation_abs, sourceT.CorrelationAbs), ...
    "PRACH trace adapter must preserve measured lag and correlation values exactly.");
assert(all(T.truth_status == "real_lls_evidence"), ...
    "Explicit source truth status must be preserved.");
assert(all(isnan(T.trial_id)) && all(isnan(T.false_alarm)), ...
    "Unavailable metadata must remain unavailable; the adapter must not invent identity or outcomes.");

noTruth = removevars(sourceT, "TruthStatus");
noTruthT = sixgr.visual.normalizePRACHCorrelationTrace(noTruth);
assert(all(noTruthT.truth_status == "not_available_missing_truth_status"), ...
    "A measured-looking trace without explicit truth provenance must not be promoted to real LLS evidence.");

ok = true;
fprintf("testPRACHCorrelationTraceAdapter: PASS\n");
end
