function ok = testSharedSlotInterferenceSuperposition()
%TESTSHAREDSLOTINTERFERENCESUPERPOSITION Verify strict shared-slot interference sums.

setup6GRSimToolkit("Verbose", false);

nSamples = 96;
nRx = 2;
t = (0:nSamples-1).';
desired = complex(0.25 * ones(nSamples, nRx), 0.05 * ones(nSamples, nRx));
contribA = [exp(1i * 2 * pi * t / 17), 0.5 * exp(1i * 2 * pi * t / 19)] .* 1e-3;
contribB = [0.75 * exp(1i * 2 * pi * t / 23), -0.25 * exp(1i * 2 * pi * t / 29)] .* 1e-3;
replay = struct( ...
    "ServingRxPower_dBm", -55, ...
    "ServingRSRPSource", "unit_test_reference", ...
    "SampleRate_Hz", 30.72e6);

bundle = repmat(localContributionEntry("", zeros(nSamples, nRx)), 2, 1);
bundle(1) = localContributionEntry("cell2_ue7", contribA);
bundle(2) = localContributionEntry("cell3_ue8", contribB);

[interference, meta] = sixgr.link.synthesizeInterferenceWaveform("DL", desired, replay, bundle);
expected = contribA + contribB;
assert(max(abs(interference(:) - expected(:))) < 1e-15, ...
    "Composite interference must equal the exact sum of stored source contributions.");
assert(logical(meta.ContributionTensorAvailable) && size(meta.ContributionTensor, 3) == 2, ...
    "Strict interference metadata must return a per-source contribution tensor.");
assert(max(abs(meta.ContributionTensor(:, :, 1) - contribA), [], "all") < 1e-15 && ...
    max(abs(meta.ContributionTensor(:, :, 2) - contribB), [], "all") < 1e-15, ...
    "Contribution tensor planes must preserve source ordering and samples.");
assert(logical(meta.SampleExactSuperpositionOk) && double(meta.SampleExactSuperpositionError) == 0, ...
    "Sample-exact superposition identity must be reported as exact for deterministic inputs.");
assert(~logical(meta.TxRegenerationUsed) && ~logical(meta.PostChannelNormalizationApplied) && ~logical(meta.RandomPhaseApplied), ...
    "Shared-slot synthesis must not regenerate Tx, normalize post-channel power, or invent receiver phases.");

expectedCov = (double(expected)' * double(expected)) ./ nSamples;
assert(logical(meta.InterferenceCovarianceAvailable) && ...
    max(abs(meta.InterferenceCovariance - expectedCov), [], "all") < 1e-18, ...
    "Interference covariance must be computed from the actual composite contribution samples.");

[mutedInterference, mutedMeta] = sixgr.link.synthesizeInterferenceWaveform("DL", desired, replay, bundle(1));
assert(max(abs(mutedInterference(:) - contribA(:))) < 1e-15 && double(mutedMeta.Contributors) == 1, ...
    "Muting/removing one transmitter must remove only its stored contribution.");

weaker = bundle(1);
weaker.SharedSlotContributionWaveform = contribA .* sqrt(0.5);
[~, strongMeta] = sixgr.link.synthesizeInterferenceWaveform("DL", desired, replay, bundle(1));
[~, weakMeta] = sixgr.link.synthesizeInterferenceWaveform("DL", desired, replay, weaker);
deltaPower_dB = double(weakMeta.AggregatedRxPower_dBm) - double(strongMeta.AggregatedRxPower_dBm);
assert(abs(deltaPower_dB + 3.01029995664) < 1e-9, ...
    "A sqrt(0.5) contribution amplitude change must reduce measured interference power by 3.0103 dB.");

bad = rmfield(bundle(1), "SharedSlotContributionWaveform");
threw = false;
try
    sixgr.link.synthesizeInterferenceWaveform("DL", desired, replay, bad);
catch ME
    threw = strcmp(ME.identifier, "sixgr:link:MissingSharedSlotInterferenceContribution");
end
assert(threw, "Full-truth interference without a shared-slot contribution must fail loudly.");

threw = false;
try
    sixgr.truth.CoupledTruthRuntime.assertSharedSlotInterferenceBundle(bad, "unit_test");
catch ME
    threw = strcmp(ME.identifier, "sixgr:truth:MissingSharedSlotInterferenceContribution");
end
assert(threw, "Grant execution must reject full-truth bundles that would require per-victim regeneration.");

ok = true;
end

function entry = localContributionEntry(sourceId, waveform)
entry = struct( ...
    "InterferenceMode", "full_per_link_channel_waveform_sum", ...
    "SourceId", char(string(sourceId)), ...
    "SharedSlotContributionWaveform", waveform, ...
    "ContributionSampleRate_Hz", 30.72e6, ...
    "ChannelObjectSource", "unit_test_shared_slot_channel", ...
    "ChannelObjectClass", "unit_test_matrix_channel", ...
    "ChannelArrayHandlingStatus", "shared_slot_receiver_contribution", ...
    "ChannelArrayHandlingBlocker", "", ...
    "ChannelGeometryCouplingLevel", "unit_test_exact_samples", ...
    "ChannelUsesSameRuntimeAntennaAssumptions", true, ...
    "GrantSnapshot", struct( ...
        "PrecoderSource", "unit_test_precoder", ...
        "PrecodingMode", "unit_test_mode", ...
        "AppliedBeamIndexSet", "1", ...
        "BeamformingApplied", true, ...
        "ExplicitBeamWeightsApplied", true, ...
        "TransformPrecodingApplied", false));
end
