function ok = testLLSProductionQualificationReduction()
%TESTLLSPRODUCTIONQUALIFICATIONREDUCTION Final evidence must reduce fail closed.

setup6GRSimToolkit("Verbose", false);
root = tempname();
mkdir(fullfile(root,"reports","csv"));
mkdir(fullfile(root,"reports","json"));
cleanup = onCleanup(@()localRemove(root)); %#ok<NASGU>

status = struct("ResultOk",true,"ExecutionCompleted",true, ...
    "RuntimeTruthContractOk",true,"ScenarioObjectiveOk",true, ...
    "MandatorySubsystemsOk",true,"KpiConsistencyOk",true, ...
    "StatisticalQualificationOk",true,"StatisticalQualificationStatus","PASS", ...
    "PublicationLLSEligible",true);

reduced = sixgr.truth.applyProductionQualificationGate(status, root);
assert(reduced.FunctionalRunOk && ~reduced.ProductionGradeOk && ...
    ~reduced.PublicationReady && ~reduced.PublicationQualified);
assert(reduced.OverallQualificationStatus == ...
    "FUNCTIONAL_ONLY_NOT_PRODUCTION_QUALIFIED");

% A completed, truthful waveform whose statistical/scenario objective is
% not met remains a functional run. Scientific/publication qualification
% fails in its own dimension and must not create a circular runtime failure.
objectiveMiss = status;
objectiveMiss.ScenarioObjectiveOk = false;
reducedObjectiveMiss = sixgr.truth.applyProductionQualificationGate( ...
    objectiveMiss, root);
assert(reducedObjectiveMiss.FunctionalRunOk && ...
    ~reducedObjectiveMiss.ScenarioObjectiveQualificationOk && ...
    ~reducedObjectiveMiss.ScientificQualificationOk && ...
    reducedObjectiveMiss.OverallQualificationStatus == ...
    "FUNCTIONAL_ONLY_NOT_PRODUCTION_QUALIFIED", ...
    "Scientific objective failure must not relabel truth execution as failed.");

% Phase-7 owns its own aggregate gate.  If a versioned artifact contains
% both the phase aggregate and a legacy ResultOk alias, qualification must
% name Phase7Ok as the failing authority rather than ambiguously implying
% that the root runtime ResultOk failed.
writetable(table(false,true, ...
    'VariableNames', {'Phase7Ok','ResultOk'}), ...
    fullfile(root,"reports","csv","phase7_truth_gates.csv"));
reduced = sixgr.truth.applyProductionQualificationGate(status, root);
assert(contains(string(reduced.ProductionQualificationFailureReasons), ...
    "Phase7Ok_false") && ...
    ~contains(string(reduced.ProductionQualificationFailureReasons), ...
    "ResultOk_false"), ...
    "Production qualification must identify the Phase-7 aggregate gate.");

writetable(table(true,true,true,true,true,true,true,true,true,true, ...
    'VariableNames', {'ResultOk','Phase7Ok','Phase1Ok','Phase2Ok','Phase3Ok', ...
    'Phase4Ok','Phase5Ok','Phase6Ok','PublicationReadinessOk','Dummy'}), ...
    fullfile(root,"reports","csv","phase7_truth_gates.csv"));
writetable(table(true,true,true,true,true,true,true, ...
    'VariableNames', {'EnergyModelOk','PerformanceProfileOk','LongRunStabilityOk', ...
    'ArtifactCompletenessOk','PlotDataLineageOk','FinalScientificClaimsTruthfulOk', ...
    'TerminalPublicationGatesOk'}), ...
    fullfile(root,"reports","csv","publication_readiness_gate_summary.csv"));
writetable(table([true;true],[true;true], ...
    'VariableNames', {'Required','Pass'}), ...
    fullfile(root,"reports","csv","phy_package_execution_evidence_gate.csv"));
writetable(table([true;true],[true;true],[true;true],[true;true],[true;true], ...
    [true;true],repmat("full",2,1), ...
    repmat("ACTUAL_FRC_FULL_STANDARD_TRUTH_EXECUTION",2,1), ...
    [-1;10],[-0.8;9.7],[0.2;-0.3], ...
    repmat(string(repmat('a',1,64)),2,1), ...
    [300000;10000], ...
    'VariableNames', {'Required','Pass','FullStandardExecutionExact','DataChannelExact', ...
    'StatisticallyQualified','OneSidedReferencePass','Profile', ...
    'EvidenceClass','RequiredSNR_dB','MeasuredSNR_dB','Delta_dB', ...
    'CatalogSHA256','TransportBlocks'}), ...
    fullfile(root,"reports","csv","frc_reference_qualification.csv"));

reduced = sixgr.truth.applyProductionQualificationGate(status, root);
assert(reduced.FunctionalRunOk && reduced.WiringCoverageOk && ...
    reduced.NumericalValidationOk && reduced.ReferenceQualificationOk && ...
    reduced.ScientificQualificationOk && reduced.ProductionGradeOk && ...
    reduced.PublicationReady && reduced.PublicationQualified);
assert(reduced.OverallQualificationStatus == "PRODUCTION_QUALIFIED");
gate = readtable(fullfile(root,"reports","csv", ...
    "production_qualification_gate.csv"), "TextType","string");
assert(height(gate) == 8 && all(logical(gate.Pass)));

% A fixed-SNR campaign cannot inherit NOT_APPLICABLE from the component
% PRACH/PDCCH statistical gate. Its production statistics are owned by the
% Phase-7 seed/campaign/CI/sample/sweep gates and must fail closed.
fixedStatus = status;
fixedStatus.RunClass = "fixed_snr_sweep_lls";
fixedStatus.StatisticalQualificationOk = true;
fixedStatus.StatisticalQualificationStatus = "NOT_APPLICABLE";
phase7Fixed = table(true,false,true,false,true,false,false, ...
    'VariableNames', {'SeedHierarchyOk','CampaignDesignOk', ...
    'CampaignCompletionOk','MultiSeedDropStatisticsOk', ...
    'ConfidenceIntervalsOk','SampleAdequacyOk','SweepDataQualityOk'});
writetable(phase7Fixed, fullfile(root,"reports","csv", ...
    "phase7_truth_gates.csv"));
reducedFixed = sixgr.truth.applyProductionQualificationGate(fixedStatus, root);
assert(~reducedFixed.StatisticalQualificationOk && ...
    reducedFixed.StatisticalQualificationStatus == "FAIL" && ...
    contains(reducedFixed.ProductionQualificationFailureReasons, ...
    "CampaignDesignOk|MultiSeedDropStatisticsOk|SampleAdequacyOk|SweepDataQualityOk"), ...
    "Fixed-SNR production statistics must be reduced from Phase-7 campaign evidence.");

phase7Fixed.CampaignDesignOk = true;
phase7Fixed.MultiSeedDropStatisticsOk = true;
phase7Fixed.SampleAdequacyOk = true;
phase7Fixed.SweepDataQualityOk = true;
writetable(phase7Fixed, fullfile(root,"reports","csv", ...
    "phase7_truth_gates.csv"));
reducedFixed = sixgr.truth.applyProductionQualificationGate(fixedStatus, root);
assert(reducedFixed.StatisticalQualificationOk && ...
    reducedFixed.StatisticalQualificationStatus == "PASS", ...
    "Complete fixed-SNR Phase-7 campaign statistics must satisfy the production statistical gate.");

% Restore the generic Phase-7 fixture used by the lifecycle assertions.
writetable(table(true,true,true,true,true,true,true,true,true,true, ...
    'VariableNames', {'ResultOk','Phase7Ok','Phase1Ok','Phase2Ok','Phase3Ok', ...
    'Phase4Ok','Phase5Ok','Phase6Ok','PublicationReadinessOk','Dummy'}), ...
    fullfile(root,"reports","csv","phase7_truth_gates.csv"));

% ExecutionCompleted is owned by the canonical root lifecycle artifact and
% is not always repeated in the in-memory scenario reducer.  Its persisted
% value must be consumed rather than defaulted to false.
persisted = table(true, 'VariableNames', {'ExecutionCompleted'});
writetable(persisted, fullfile(root,"reports","csv", ...
    "result_status_summary.csv"));
statusWithoutLifecycle = rmfield(status, "ExecutionCompleted");
reduced = sixgr.truth.applyProductionQualificationGate( ...
    statusWithoutLifecycle, root);
assert(reduced.FunctionalRunOk && reduced.ProductionGradeOk, ...
    "Persisted execution-completion authority must satisfy the functional gate.");
persisted.ExecutionCompleted = false;
writetable(persisted, fullfile(root,"reports","csv", ...
    "result_status_summary.csv"));
reduced = sixgr.truth.applyProductionQualificationGate( ...
    statusWithoutLifecycle, root);
assert(~reduced.FunctionalRunOk && ~reduced.ProductionGradeOk, ...
    "A persisted incomplete execution must fail the production gate.");
gate = readtable(fullfile(root,"reports","csv", ...
    "production_qualification_gate.csv"), "TextType","string");
assert(~logical(gate.Pass(gate.Gate == "FunctionalRun")), ...
    "The persisted incomplete lifecycle must be visible in the gate table.");
ok = true;
fprintf("PASS testLLSProductionQualificationReduction: final production reduction is fail closed.\n");
end

function localRemove(pathValue)
if isfolder(pathValue), rmdir(pathValue,"s"); end
end
