function ok = testGeometryHybridAntennaDomain()
%TESTGEOMETRYHYBRIDANTENNADOMAIN Keep data and CSI-RS in one RF domain.

setup6GRSimToolkit("Verbose", false);

scenarioPath = fullfile("simulator", "configs", "scenarios", ...
    "master_geometry_based.yaml");
scenario = sixgr.lls6g.config.loadScenarioConfig(scenarioPath);
cfg = sixgr.lls6g.buildInternalConfig(scenario, ...
    fullfile(tempdir, "sixgr_geometry_hybrid_antenna_domain"));

arch = sixgr.rf.AntennaArrayFactory.resolvePortArchitecture(cfg, "bs", ...
    "Signal", "PDSCH", "MinimumPorts", 2);
assert(arch.HybridBeamformingEnabled, ...
    "Geometry truth must enable the configured hybrid element-domain path.");
assert(arch.NumElements == 64 && arch.NumPorts == 2 && ...
    arch.NumRFChains == 4 && arch.NumWaveformColumns == 64, ...
    ["The master geometry scenario must resolve to 64 physical gNB " ...
     "elements, two logical PDSCH ports and four RF chains."]);
assert(isequal(size(arch.HybridElementToPortMatrix), [64 2]), ...
    "The resolved hybrid element-to-port matrix must be 64-by-2.");

csiPrecoders = double(cfg.phy.csirs.precoderMatrices);
assert(isequal(size(csiPrecoders), [64 4 32]), ...
    "CSI-RS must use the same 64-element domain with four ports and 32 resources.");
for resourceIndex = 1:size(csiPrecoders, 3)
    gram = csiPrecoders(:, :, resourceIndex)' * ...
        csiPrecoders(:, :, resourceIndex);
    assert(norm(gram - eye(4), "fro") <= 1e-10, ...
        "Every configured CSI-RS precoder must be semi-unitary.");
end

grant = struct( ...
    "Direction", "DL", "Frame", 0, "Slot", 0, "RNTI", 101, ...
    "UEIndex", 1, "ServingCell", 1, "PRBSet", 0:5, ...
    "SymbolAllocation", [2 10], "Modulation", "QPSK", ...
    "NumLayers", 2, "Layers", 2, "NumLogicalPorts", 2, ...
    "NumRFChains", 4, "TargetCodeRate", 0.3, "MCSIndex", 1);
phyGrant = sixgr.phy.grant.freezePHYGrant(cfg, "DL", grant, ...
    "SNR_dB", 20, "Frame", 0, "Slot", 0);
physicalMatrix = double(phyGrant.PrecodingState.Matrix);
assert(isequal(size(physicalMatrix), [64 2]) && ...
    phyGrant.AntennaArchitecture.NumWaveformColumns == 64, ...
    "Frozen DL authority must retain the 64-element waveform domain.");
assert(abs(sum(abs(physicalMatrix(:)).^2) - 1) <= 1e-12, ...
    "The frozen physical PDSCH precoder must use unit-total-power normalization.");

ok = true;
end
