function ok = testSRSPUSCHExactCollisionFDDTDD()
%TESTSRSPUSCHEXACTCOLLISIONFDDTDD Shared exact RE arbitration for both duplexes.
%
% Duplex selection controls which slots can carry uplink.  It must not
% select a different collision algorithm.  In every legal UL occasion the
% same Toolbox-derived SRS and scheduled-PUSCH coordinates are compared.

setup6GRSimToolkit("Verbose", false, "RunToolboxChecks", false);
scenarioPaths = [ ...
    fullfile("simulator", "configs", "scenarios", ...
        "lls_causal_access_to_data_wiring.yaml"), ...
    fullfile("simulator", "configs", "scenarios", ...
        "lls_causal_access_to_data_wiring_tdd.yaml")];
expectedDuplex = ["FDD", "TDD"];

for profileIdx = 1:numel(scenarioPaths)
    scenario = sixgr.lls6g.config.loadScenarioConfig( ...
        scenarioPaths(profileIdx));
    cfg = sixgr.config.normalizeConfig( ...
        sixgr.lls6g.buildInternalConfig(scenario, string(tempname)));
    duplex = upper(string(sixgr.phy.frame.resolveDuplexMode(cfg)));
    assert(duplex == expectedDuplex(profileIdx));

    absoluteSlotOneBased = localFindLegalActiveSRSSlot(cfg);
    srs = sixgr.phy.srs.buildSRSConfigFromScenario(cfg);
    srsStart = double(srs.ToolboxSRS.SymbolStart);
    % Build an intentionally overlapping candidate.  The production TDD
    % YAML now correctly reserves its final SRS symbol from ordinary PUSCH,
    % so copying the configured collision-free PUSCH allocation would no
    % longer exercise arbitration at all.
    overlapAllocation = [0 srsStart + 1];
    grant = localScheduledPUSCHGrant(cfg, absoluteSlotOneBased, ...
        overlapAllocation);
    % Use a different SRS UE to prove that UL resource ownership is shared
    % at the gNB and is not incorrectly scoped to a same-UE collision.
    collision = sixgr.phy.frame.resolveSRSPUSCHCollision( ...
        cfg, grant, absoluteSlotOneBased, 2);

    assert(collision.Exact && ~collision.ApproximationUsed, ...
        "%s collision decision was not exact waveform evidence.", duplex);
    assert(string(collision.DuplexMode) == duplex && ...
        collision.Collision && collision.OverlapRECount > 0, ...
        "%s did not detect the known cross-UE SRS/PUSCH RE collision.", duplex);
    assert(collision.SRSUEIndex == 2 && collision.PUSCHUEIndex == 1 && ...
        string(collision.ResourceComparisonDomain) == ...
        "shared_ul_carrier_subcarrier_symbol", ...
        "%s did not retain distinct SRS/PUSCH UE identity in the shared-carrier decision.", duplex);
    assert(string(collision.Action) == ...
        "defer_srs_preserve_scheduled_pusch", ...
        "%s did not preserve the already scheduled PUSCH.", duplex);
    assert(contains(string(collision.SRSAllocationSource), "nrSRS") && ...
        contains(string(collision.PUSCHAllocationSource), "nrPUSCH"), ...
        "%s collision decision was not backed by Toolbox RE indices.", duplex);

    noOverlapAllocation = double(cfg.phy.pusch.SymbolAllocation);
    assert(srsStart >= 1, ...
        "Test scenario must leave at least one symbol before SRS.");
    noOverlapAllocation = [0 srsStart];
    clearGrant = localScheduledPUSCHGrant( ...
        cfg, absoluteSlotOneBased, noOverlapAllocation);
    noCollision = sixgr.phy.frame.resolveSRSPUSCHCollision( ...
        cfg, clearGrant, absoluteSlotOneBased);
    assert(noCollision.Exact && ~noCollision.Collision && ...
        noCollision.OverlapRECount == 0 && ...
        string(noCollision.Action) == "execute_srs", ...
        "%s reported a collision after PUSCH excluded the SRS symbol.", duplex);
end

% UL MU-MIMO needs a causal first SRS measurement before spatial pairing.
% Its ownership policy must be explicit in YAML and must reach the same
% exact RE collision materializer used by both duplex modes.
muScenario = sixgr.lls6g.config.loadScenarioConfig(fullfile( ...
    "simulator", "configs", "scenarios", ...
    "lls_mimo4x4_multiuser_beamformed.yaml"));
muCfg = sixgr.config.normalizeConfig( ...
    sixgr.lls6g.buildInternalConfig(muScenario, string(tempname)));
assert(string(muCfg.phy.srs.puschCollisionPolicy) == ...
    "prioritize_srs_until_first_valid_measurement");
assert(string(muCfg.phy.srs.pucchCollisionPolicy) == ...
    "require_disjoint_symbols_for_first_measurement");
assert(double(muCfg.phy.srs.SymbolStart) == 11 && ...
    double(muCfg.phy.srs.NumSRSSymbols) == 1, ...
    "MU-MIMO SRS first-measurement allocation was not YAML authoritative.");
muSlot = localFindLegalActiveSRSSlot(muCfg);
muSRS = sixgr.phy.srs.buildSRSConfigFromScenario(muCfg);
muGrant = localScheduledPUSCHGrant(muCfg, muSlot, ...
    [0 double(muSRS.ToolboxSRS.SymbolStart) + 1]);
muCollision = sixgr.phy.frame.resolveSRSPUSCHCollision( ...
    muCfg, muGrant, muSlot, 2);
assert(muCollision.Collision && ...
    string(muCollision.ConfiguredCollisionPolicy) == ...
    "prioritize_srs_until_first_valid_measurement" && ...
    string(muCollision.Action) == ...
    "runtime_srs_measurement_priority_resolution_required", ...
    "UL MU-MIMO SRS collision authority did not reach exact RE arbitration.");

missingPolicy = muScenario.toStruct();
missingPolicy.reference_signals.srs = rmfield( ...
    missingPolicy.reference_signals.srs, "pusch_collision_policy");
try
    sixgr.lls6g.buildInternalConfig(missingPolicy, string(tempname));
    error("sixgr:test:ExpectedMissingSRSPUSCHCollisionPolicy", ...
        "UL MU-MIMO accepted an implicit SRS/PUSCH ownership policy.");
catch ME
    assert(string(ME.identifier) == ...
        "sixgr:lls6g:config:MissingSRSPUSCHCollisionPolicy", ...
        "Unexpected missing-policy error: %s", ME.identifier);
end

collidingPUCCH = muScenario.toStruct();
collidingPUCCH.reference_signals.srs.symbol_start = 13;
try
    sixgr.lls6g.buildInternalConfig(collidingPUCCH, string(tempname));
    error("sixgr:test:ExpectedSRSFirstMeasurementPUCCHCollision", ...
        "UL MU-MIMO accepted an SRS allocation that due PUCCH can starve.");
catch ME
    assert(string(ME.identifier) == ...
        "sixgr:lls6g:config:SRSFirstMeasurementPUCCHCollision", ...
        "Unexpected SRS/PUCCH liveness error: %s", ME.identifier);
end

missingPUCCHPolicy = muScenario.toStruct();
missingPUCCHPolicy.reference_signals.srs = rmfield( ...
    missingPUCCHPolicy.reference_signals.srs, "pucch_collision_policy");
try
    sixgr.lls6g.buildInternalConfig(missingPUCCHPolicy, string(tempname));
    error("sixgr:test:ExpectedMissingSRSPUCCHCollisionPolicy", ...
        "UL MU-MIMO accepted an implicit SRS/PUCCH ownership policy.");
catch ME
    assert(string(ME.identifier) == ...
        "sixgr:lls6g:config:MissingSRSPUCCHCollisionPolicy", ...
        "Unexpected missing SRS/PUCCH policy error: %s", ME.identifier);
end

ok = true;
fprintf("[PASS] testSRSPUSCHExactCollisionFDDTDD shared exact arbitration retained.\n");
end

function absoluteSlotOneBased = localFindLegalActiveSRSSlot(cfg)
strictSRS = sixgr.phy.srs.buildSRSConfigFromScenario(cfg);
[probe, ~] = sixgr.phy.grid.makeCarrier(cfg);
slotsPerFrame = 10 * 2^round(log2(double(probe.SubcarrierSpacing) / 15));
duplex = upper(string(sixgr.phy.frame.resolveDuplexMode(cfg)));

for slot0 = 0:(4 * slotsPerFrame - 1)
    legalUL = true;
    if duplex == "TDD"
        partition = sixgr.util.resolveTDDSlotPartition(cfg, slot0);
        legalUL = logical(partition.AllowUL);
    end
    if ~legalUL
        continue;
    end
    [carrier, ~] = sixgr.phy.grid.makeCarrier(cfg, ...
        "Slot", mod(slot0, slotsPerFrame), ...
        "Frame", floor(slot0 / slotsPerFrame));
    if ~isempty(nrSRSIndices(carrier, strictSRS.ToolboxSRS))
        absoluteSlotOneBased = slot0 + 1;
        return;
    end
end
error("sixgr:test:NoLegalActiveSRSOccasion", ...
    "No legal active SRS occasion was found in four frames.");
end

function grant = localScheduledPUSCHGrant(cfg, slotOneBased, symbols)
pusch = cfg.phy.pusch;
grant = struct( ...
    "UEIndex", 1, ...
    "ScheduledAbsoluteSlot", double(slotOneBased), ...
    "Slot", double(slotOneBased), ...
    "PRBSet", double(pusch.PRBSet), ...
    "SymbolAllocation", double(symbols), ...
    "Modulation", char(string(pusch.modulation)), ...
    "NumLayers", double(pusch.numLayers), ...
    "RNTI", double(pusch.RNTI), ...
    "TransformPrecoding", logical(pusch.transformPrecoding), ...
    "TransmissionScheme", char(string(pusch.TransmissionScheme)), ...
    "NumAntennaPorts", double(pusch.NumAntennaPorts), ...
    "TPMI", double(pusch.TPMI), ...
    "NID", double(pusch.NID), ...
    "MappingType", char(string(pusch.mappingType)));
end
