function ok = testLLSULSRSRITPMIEstimator()
%TESTLLSULSRSRITPMIESTIMATOR Verify SRS-based UL RI and TPMI estimation path.

setup6GRSimToolkit("Verbose", false);

if exist("nrPUSCHCodebook", "file") ~= 2
    error('sixgr:test:Required5GToolboxUnavailable', ...
        'The SRS RI/TPMI regression requires nrPUSCHCodebook; an unavailable test cannot pass.');
end

cfg = sixgr.config.defaultConfig();
cfg.phy.nRxAnt = 2;
cfg.phy.nTxAnt = 2;
cfg = sixgr.util.structSet(cfg, "phy.pusch.transmissionScheme", "codebook");
cfg = sixgr.util.structSet(cfg, "phy.pusch.transformPrecoding", false);
cfg = sixgr.util.structSet(cfg, "phy.pusch.maxRankDefault", 2);
cfg = sixgr.util.structSet(cfg, "phy.pusch.NumAntennaPorts", 2);
cfg = sixgr.util.structSet(cfg, "phy.pusch.numAntennaPorts", 2);
cfg = sixgr.util.structSet(cfg, "phy.srs.rankEigenThreshold_dB", 10);

Hwb = cat(3, ...
    [1.10 + 0.10j, 0.18 - 0.02j; 0.12 + 0.01j, 0.92 - 0.08j], ...
    [1.02 + 0.06j, 0.15 + 0.01j; 0.08 - 0.03j, 0.88 - 0.04j]);
Hest = zeros(24, 14, 2, 2);
for k = 1:24
    for l = 1:14
        Hest(k, l, :, :) = Hwb(:, :, 1);
    end
end
Hest(13:24, :, :, :) = repmat(reshape(Hwb(:, :, 2), 1, 1, 2, 2), [12, 14, 1, 1]);

est = sixgr.phy.ul.estimateSRSRITPMI(Hest, 0.01, cfg);
assert(logical(est.Valid), ...
    "SRS estimator must report a valid RI/TPMI estimate for a codebook-capable UL channel.");
assert(isfinite(est.RI) && est.RI >= 1 && est.RI <= 2, ...
    "Estimated RI must stay within the supported UL rank range.");
assert(isfinite(est.TPMI), ...
    "Estimated TPMI must be finite when the UL codebook path is active.");
assert(est.TPMICandidateCount > 0 && isfinite(est.TPMIMutualInformation), ...
    "SRS TPMI estimation must score at least one candidate with a finite MI metric.");
assert(numel(est.SelectedPostEqSINRPerLayer_dB) == round(est.RI) && ...
    all(isfinite(est.SelectedPostEqSINRPerLayer_dB)) && ...
    isfinite(est.SelectedMinimumLayerMeanPostEqSINR_dB) && ...
    isfinite(est.SelectedWidebandMeanPostEqSINR_dB), ...
    "Selected SRS RI/TPMI evidence must retain finite per-layer MMSE post-equalization SINR.");
assert(abs(est.SelectedMinimumLayerMeanPostEqSINR_dB - ...
    min(est.SelectedPostEqSINRPerLayer_dB)) < 1e-10, ...
    "The SRS-to-PUSCH minimum-layer scheduling metric must equal the weakest selected layer.");
assert(strcmp(string(est.SelectedPostEqSINRValueRole), ...
    "diagnostic_relative_spatial_metric_not_data_scheduler_input") && ...
    strcmp(string(est.SelectedPostEqSINRValueStatus), ...
    "DIAGNOSTIC_ONLY_UNCALIBRATED_POWER_PLANE"), ...
    "An unanchored Hest/noise spatial metric must not be presented as an absolute PUSCH scheduler input.");

referencePower = mean(sum(abs(Hest).^2,4),"all");
anchorSINR_dB = 10*log10(referencePower/0.01);
anchorSource = "measured_ul_srs_pilot_reconstruction_sinr";
anchorPlane = "receiver_srs_resource_elements_after_ofdm_demodulation";
powerArgs = {"ReferenceSignalPower",referencePower, ...
    "ReferencePowerSource","received_reference_grid_plus_receiver_hest", ...
    "PUSCHToSRSReferenceEnergyRatio",1, ...
    "PUSCHToSRSReferenceEnergySource","normalized_fixed_snr_unit_grid_reference_no_device_power_scaling"};
estAnchored = sixgr.phy.ul.estimateSRSRITPMI(Hest, 0.01, cfg, ...
    "AbsoluteSINRAnchor_dB", anchorSINR_dB, ...
    "AbsoluteSINRAnchorSource", anchorSource, ...
    "AbsoluteSINRAnchorPowerReferencePlane", anchorPlane,powerArgs{:});
assert(strcmp(string(estAnchored.SelectedPostEqSINRValueRole), ...
    "power_plane_calibrated_predicted_pusch_data_channel_scheduling_input") && ...
    strcmp(string(estAnchored.SelectedPostEqSINRValueStatus), "PASS") && ...
    contains(string(estAnchored.SelectedPostEqSINRSource), ...
    "receiver_measured_srs_reference_power"), ...
    "Only a receiver-measured, power-plane-anchored prediction may become a PUSCH scheduler input.");
assert(max(abs(double(estAnchored.SelectedPostEqSINRPerLayer_dB) - ...
    double(est.SelectedPostEqSINRPerLayer_dB))) < 1e-10 && ...
    estAnchored.SelectedPostEqSINRCalibrationOffset_dB == 0 && ...
    abs(double(estAnchored.SelectedPostEqSINRAnchor_dB) - anchorSINR_dB) < 1e-10 && ...
    strcmp(string(estAnchored.SelectedPostEqSINRAnchorSource), anchorSource) && ...
    strcmp(string(estAnchored.SelectedPostEqSINRPowerReferencePlane), anchorPlane), ...
    "Measured reference power/noise must preserve the independently calculated PUSCH layer split.");
assert(double(estAnchored.SelectedMinimumLayerMeanPostEqSINR_dB) <= ...
    double(estAnchored.SelectedWidebandMeanPostEqSINR_dB) + 1e-10, ...
    "The weakest selected layer must not exceed the actual layer-mean SINR.");

% A one-port codebook is still an exact TS 38.211 PUSCH codebook case:
% rank=1, TPMI=0, W=1.  It must retain the same calibrated post-equalization
% prediction required by the UL scheduler instead of returning after RI.
cfgOnePort = sixgr.util.structSet(cfg, "phy.pusch.NumAntennaPorts", 1);
cfgOnePort = sixgr.util.structSet(cfgOnePort, "phy.pusch.numAntennaPorts", 1);
cfgOnePort = sixgr.util.structSet(cfgOnePort, "phy.pusch.maxRankDefault", 1);
HestOnePort = Hest(:, :, :, 1);
onePortPower = mean(abs(HestOnePort).^2,"all");
onePortArgs = powerArgs; onePortArgs{2} = onePortPower;
onePortRaw = sixgr.phy.ul.estimateSRSRITPMI(HestOnePort,0.01,cfgOnePort);
estOnePort = sixgr.phy.ul.estimateSRSRITPMI(HestOnePort, 0.01, cfgOnePort, ...
    "AbsoluteSINRAnchor_dB", 10*log10(onePortPower/0.01), ...
    "AbsoluteSINRAnchorSource", anchorSource, ...
    "AbsoluteSINRAnchorPowerReferencePlane", anchorPlane,onePortArgs{:});
assert(logical(estOnePort.Valid) && double(estOnePort.RI) == 1 && ...
    double(estOnePort.TPMI) == 0 && double(estOnePort.TPMICandidateCount) == 1, ...
    "One-port codebook SRS must execute the unique rank-1, TPMI-0 candidate.");
assert(double(estOnePort.PUSCHCodebookNumPorts) == 1 && ...
    numel(estOnePort.SelectedPostEqSINRPerLayer_dB) == 1 && ...
    all(isfinite(estOnePort.SelectedPostEqSINRPerLayer_dB)) && ...
    string(estOnePort.SelectedPostEqSINRValueStatus) == "PASS" && ...
    abs(double(estOnePort.SelectedWidebandMeanPostEqSINR_dB) - ...
        double(onePortRaw.SelectedWidebandMeanPostEqSINR_dB)) < 1e-10, ...
    ["One-port SRS must publish a finite, power-plane-calibrated PUSCH " ...
     "scheduler input rather than RI-only bootstrap evidence."]);

powerPlaneAnchorSource = "runtime_ul_srs_power_control_link_budget_sinr";
powerPlaneAnchor = ...
    "receiver_input_equivalent_srs_total_power_over_noise_bandwidth_before_adc";
estPowerAnchored = sixgr.phy.ul.estimateSRSRITPMI(Hest, 0.01, cfg, ...
    "AbsoluteSINRAnchor_dB", anchorSINR_dB, ...
    "AbsoluteSINRAnchorSource", powerPlaneAnchorSource, ...
    "AbsoluteSINRAnchorPowerReferencePlane", powerPlaneAnchor);
assert(string(estPowerAnchored.SelectedPostEqSINRValueStatus) == ...
    "DIAGNOSTIC_ONLY_UNCALIBRATED_POWER_PLANE", ...
    "A total link budget without a measured SRS/PUSCH per-RE conversion cannot authorize scheduling SINR.");

% Joint scaling of the channel and noise power must not alter a SINR or its
% selected RI/TPMI.  This guards against reintroducing a sample/grid power
% conversion into the spatial predictor.
scaledPowerArgs = powerArgs; scaledPowerArgs{2} = 9*referencePower;
estScaled = sixgr.phy.ul.estimateSRSRITPMI(3 .* Hest, 9 .* 0.01, cfg, ...
    "AbsoluteSINRAnchor_dB", anchorSINR_dB, ...
    "AbsoluteSINRAnchorSource", anchorSource, ...
    "AbsoluteSINRAnchorPowerReferencePlane", anchorPlane,scaledPowerArgs{:});
assert(double(estScaled.RI) == double(estAnchored.RI) && ...
    double(estScaled.TPMI) == double(estAnchored.TPMI) && ...
    max(abs(double(estScaled.SelectedPostEqSINRPerLayer_dB(:)) - ...
    double(estAnchored.SelectedPostEqSINRPerLayer_dB(:)))) < 1e-9, ...
    "SRS RI/TPMI and anchored layer SINR must be invariant to a common channel/noise amplitude scaling.");

% The raw SRS pilot-reconstruction residual is a diagnostic measurement,
% not a schedulable CQI.  Only the separately anchored PUSCH prediction may
% be converted to CQI by the SRS producer.
srsMetrics = sixgr.phy.ul.measureULLinkState(Hest, 0.01, cfg, ...
    "ReceivedGrid", complex(zeros(24, 14, 2)), ...
    "ReferenceIndices", zeros(0, 1), ...
    "ReferenceSymbols", zeros(0, 1), ...
    "ChannelEstimateDomain", "srs_port_domain");
assert(~isfinite(double(srsMetrics.CQI)) && ...
    string(srsMetrics.CQIValueStatus) == ...
    "unavailable_until_power_plane_calibrated_pusch_prediction", ...
    "SRS pilot reconstruction must never be exported as a data-channel CQI.");
assert(est.PRBCount == 2 && est.SRSSymbolCount == 14, ...
    "SRS RI/TPMI estimation must preserve both PRB and SRS-symbol observation dimensions.");

HsymCancel = zeros(24, 2, 2, 2);
HsymCancel(:, 1, :, :) = repmat(reshape(eye(2), 1, 1, 2, 2), [24, 1, 1, 1]);
HsymCancel(:, 2, :, :) = -HsymCancel(:, 1, :, :);
estSym = sixgr.phy.ul.estimateSRSRITPMI(HsymCancel, 0.01, cfg);
assert(estSym.SRSSymbolCount == 2 && estSym.PRBCount == 2, ...
    "SRS estimator must expose the observed symbol and PRB counts.");
assert(isfinite(estSym.RI) && estSym.RI == 2, ...
    "SRS RI estimation must use per-symbol covariance; averaging symbols first would erase this rank-2 channel.");
assert(isfinite(estSym.TPMIMutualInformation) && estSym.TPMIMutualInformation > 1, ...
    "SRS TPMI scoring must accumulate post-equalization MI over nonzero per-symbol channel observations.");

cfgMismatch = sixgr.util.structSet(cfg, "phy.pusch.NumAntennaPorts", 2);
cfgMismatch = sixgr.util.structSet(cfgMismatch, "phy.pusch.numAntennaPorts", 2);
cfgMismatch = sixgr.util.structSet(cfgMismatch, "phy.pusch.nLayers", 2);
cfgMismatch = sixgr.util.structSet(cfgMismatch, "phy.pusch.numLayers", 2);
cfgMismatch = sixgr.util.structSet(cfgMismatch, "run.controlGating.pbchRequired", false);
cfgMismatch = sixgr.util.structSet(cfgMismatch, "run.controlGating.prachRequired", false);
cfgMismatch = sixgr.util.structSet(cfgMismatch, "run.controlGating.pdcchRequired", false);
cfgMismatch = sixgr.util.structSet(cfgMismatch, "run.controlGating.srsRequired", true);
cfgMismatch = sixgr.util.structSet(cfgMismatch, "run.controlGating.trsRequired", false);
cfgMismatch = sixgr.util.structSet(cfgMismatch, "run.controlGating.srsMaxAgeSlots", 8);
cfgMismatch = sixgr.util.structSet(cfgMismatch, "run.controlGating.trsMaxAgeSlots", 8);
Hest4 = zeros(24, 14, 2, 4);
Hest4(:, :, :, 1:2) = Hest;
Hest4(:, :, :, 3) = 0.3 .* Hest(:, :, :, 1);
Hest4(:, :, :, 4) = 0.2 .* Hest(:, :, :, 2);
estMismatch = sixgr.phy.ul.estimateSRSRITPMI(Hest4, 0.01, cfgMismatch);
assert(logical(estMismatch.Valid) && isfinite(estMismatch.TPMI), ...
    "SRS TPMI estimation must remain available when SRS ports exceed active PUSCH codebook ports.");
assert(estMismatch.SRSNumTxPorts == 4 && estMismatch.PUSCHCodebookNumPorts == 2 && estMismatch.NumTxPorts == 2, ...
    "SRS estimator must disclose and use the active PUSCH codebook port count for TPMI scoring.");
assert(strcmp(string(estMismatch.PortSelectionSource), "srs_ports_restricted_to_active_pusch_codebook_ports"), ...
    "SRS estimator must explain when wider SRS ports are restricted to the executable PUSCH codebook.");
try
    nrPUSCHCodebook(round(double(estMismatch.RI)), 2, round(double(estMismatch.TPMI)), false);
catch ME
    error("testLLSULSRSRITPMIEstimator:InvalidRuntimeTPMI", ...
        "Estimated TPMI %g must be executable for rank %g on the active 2-port PUSCH codebook: %s", ...
        double(estMismatch.TPMI), double(estMismatch.RI), ME.message);
end

tmp = tempname;
mkdir(tmp);
c = onCleanup(@() rmdir(tmp, "s")); %#ok<NASGU>
multiUser = struct( ...
    "Enabled", true, ...
    "NumUsers", 1, ...
    "RNTIStart", 701, ...
    "ExecutionModel", "slot_coupled_truth");
state = sixgr.truth.CoupledTruthRuntime.initialize(cfgMismatch, fullfile(tmp, "run"), multiUser, struct(), 1);
srsPass = table("PASS",1,1,true,2,12, ...
    true,true,true,true,true,true,true,10,-20,-8, ...
    false,false,false,"", ...
    VariableNames=["Status","Slot","Frame","CRCPass", ...
    "RIEstimate","TPMIEstimate","DetectionAttempted", ...
    "DetectionSuccess","ResourceExtractionAttempted", ...
    "ResourceExtractionAvailable","ChannelEstimateAttempted", ...
    "SRSChannelEstimateAvailable","SRSRuntimeEvidenceUsable", ...
    "ReceiverHestSINR_dB","NMSE_dB","ChannelNMSEThreshold_dB", ...
    "ProxyUsed","Skipped","ToolboxMissing","UsedOracleFields"]);
state = sixgr.truth.CoupledTruthRuntime.applySRSTrial(state, 1, srsPass);
sanitized = double(state.LatestULFeedback(1).PMI);
assert(isnan(sanitized), ...
    "Invalid received TPMI must remain unavailable, never become a configured or first-valid TPMI.");
for strict = [false true]
    candidate = state;
    candidate.CfgMobility.mimo.strict = strict;
    candidate.CfgMobility.phy.pusch.PMI = 1;
    candidate.CfgMobility.phy.pusch.TPMI = 1;
    candidate.LatestULFeedback(1).RI = 1;
    candidate.LatestULFeedback(1).PMI = 5;
    % Rank 1 TPMI 5 is valid for two ports, but cannot survive a rank-2
    % report that omits TPMI. Rank and TPMI belong to the same observation.
    for reportedTPMI = [NaN 12 1.5 -1]
        observed = srsPass;
        observed.TPMIEstimate = reportedTPMI;
        updated = sixgr.truth.CoupledTruthRuntime.applySRSTrial(candidate,1,observed);
        assert(updated.LatestULFeedback(1).RI == 2 && ...
            isnan(updated.LatestULFeedback(1).PMI), ...
            "New rank must not be paired with an old, rounded or configured TPMI.");
    end
    observed = srsPass; observed.TPMIEstimate = 1;
    updated = sixgr.truth.CoupledTruthRuntime.applySRSTrial(candidate,1,observed);
    assert(updated.LatestULFeedback(1).RI == 2 && updated.LatestULFeedback(1).PMI == 1);
    for reportedRI = [NaN 0 1.5]
        observed.RIEstimate = reportedRI;
        updated = sixgr.truth.CoupledTruthRuntime.applySRSTrial(candidate,1,observed);
        assert(isnan(updated.LatestULFeedback(1).RI) && ...
            isnan(updated.LatestULFeedback(1).PMI), ...
            "A TPMI without valid measured rank must not borrow a configured or previous rank.");
    end
end

% A PUSCH DM-RS channel estimate has one channel dimension per effective
% transmission layer, even when the waveform used a wider antenna-port
% codebook. It must never be passed to the SRS port-domain RI/TPMI search.
cfgFourPort = sixgr.util.structSet(cfgMismatch, "phy.pusch.NumAntennaPorts", 4);
cfgFourPort = sixgr.util.structSet(cfgFourPort, "phy.pusch.numAntennaPorts", 4);
precoderInfo = struct( ...
    "PrecodingMode", "ul_codebook_tpmi", ...
    "AppliedPrecoderPMI", 1, ...
    "AppliedPrecoderPMIType", "pusch_codebook", ...
    "AppliedPrecoderCodebookMode", "codebook1_ng1n4n1");
dmrsMetric = sixgr.phy.ul.measureULLinkState(Hest, 0.01, cfgFourPort, ...
    "PrecoderInfo", precoderInfo, ...
    "ChannelEstimateDomain", "pusch_dmrs_effective_layer_domain");
assert(strcmp(string(dmrsMetric.ChannelEstimateDomain), "pusch_dmrs_effective_layer_domain") && ...
    ~logical(dmrsMetric.SRSRITPMIValid), ...
    "PUSCH DM-RS effective-layer evidence must not be mislabeled as a valid SRS RI/TPMI estimate.");
assert(strcmp(string(dmrsMetric.SRSRITPMIStatus), ...
    "not_applicable_pusch_dmrs_effective_layer_domain"), ...
    "PUSCH DM-RS evidence must disclose why SRS RI/TPMI estimation was not run.");
assert(double(dmrsMetric.PMI) == 1 && ...
    strcmp(string(dmrsMetric.PMISource), "ul_runtime_applied_codebook_tpmi"), ...
    "PUSCH DM-RS diagnostics must retain the TPMI actually applied to the waveform.");
assert(strcmp(string(dmrsMetric.RISource), ...
    "ul_pusch_dmrs_effective_layer_rank_descriptor_not_srs_ri"), ...
    "PUSCH DM-RS rank evidence must remain explicitly distinct from an SRS-derived RI.");

try
    sixgr.phy.ul.measureULLinkState(Hest, 0.01, cfgFourPort);
    error("testLLSULSRSRITPMIEstimator:MissingDomainAccepted", ...
        "UL measurement unexpectedly accepted an unspecified channel-estimate domain.");
catch ME
    assert(strcmp(ME.identifier, "sixgr:phy:ul:MissingChannelEstimateDomain"), ...
        "Missing UL channel-estimate domain must fail with the typed production guard.");
end

ok = true;
end
