function tests=testQualificationArtifactAuditSchema
tests=functiontests(localfunctions);
end

function testCanonicalColumnsAndEnums(testCase)
columns=sixgr.integration.qualification. ...
    QualificationArtifactAuditSchema.VariableNames;
types=sixgr.integration.qualification. ...
    QualificationArtifactAuditSchema.ArtifactTypes;
statuses=sixgr.integration.qualification. ...
    QualificationArtifactAuditSchema.StatusValues;
required=["SchemaVersion","RunID","ArtifactID","Domain","SubcaseID", ...
    "RelativePath","ArtifactType","MIMEType","Required","Present", ...
    "Valid","Status","FailureCode","SHA256","ByteCount","GeneratedUTC", ...
    "SourceArtifactIDs","SourceCSVRelativePath","SourceCSV_SHA256", ...
    "SemanticAuditStatus","ProvenanceClass","PublicationStatus", ...
    "ArtifactTypeSource"];
verifyTrue(testCase,all(ismember(required,columns)));
verifyTrue(testCase,all(ismember(["CSV","PNG","OTHER"], ...
    types)));
verifyTrue(testCase,all(ismember(["PASS","FAIL","MISSING", ...
    "INVALID_SCHEMA","INVALID_HASH","INVALID_SEMANTICS", ...
    "UNAVAILABLE","NOT_APPLICABLE"],statuses)));
end
