function ok = testFRCExecutionContractTruthfulness()
%TESTFRCEXECUTIONCONTRACTTRUTHFULNESS Fail closed on unimplemented FRC data.

setup6GRSimToolkit("Verbose", false, "RunToolboxChecks", false);

catalog = sixgr.conformance.frcCatalog();
entryIndex = localEntryIndex(catalog.entries, ...
    "dl_r_pdsch_1_1_4_fdd_awgn");
entry = localItem(catalog.entries, entryIndex);
entry.allocation.full_bandwidth = false;
entry.allocation.frequency_hopping = "enabled";
entry.allocation.resource_allocation_type = "Type1";
entry.allocation.rbg_size_config = "Config1";
entry.allocation.vrb_to_prb_mapping = "interleaved";
entry.allocation.allocated_slots_per_20ms = 18;
entry.waveform.transform_precoding = true;
entry.mimo.correlation_matrix = "custom_not_materialized";
entry.ptrs = struct( ...
    "enabled", true, ...
    "frequency_density", "2", ...
    "time_density", "1", ...
    "requirement_variant", "Yes");
catalog.entries = localReplaceItem(catalog.entries, entryIndex, entry);
catalogPath = localWriteTemporaryCatalog(catalog);
catalogCleanup = onCleanup(@() localDeleteIfPresent(catalogPath)); %#ok<NASGU>

cause = localExpectedExecutionBlock( ...
    entry.id, entry.condition.id, catalogPath);
expectedBlockers = [ ...
    "partial_bandwidth_allocation_not_materialized"; ...
    "frequency_hopping_not_materialized"; ...
    "transform_precoding_not_materialized"; ...
    "ptrs_not_materialized"; ...
    "unsupported_pdsch_resource_allocation_type"; ...
    "unsupported_pdsch_rbg_size_configuration"; ...
    "pdsch_vrb_to_prb_mapping_not_materialized"; ...
    "unsupported_pdsch_slots_per_20ms"; ...
    "unsupported_awgn_static_channel_contract"];
for blocker = expectedBlockers.'
    assert(contains(string(cause.message), blocker), ...
        "Missing fail-closed data-channel blocker '%s'.", blocker);
end

fadingResult = sixgr.conformance.runFRCPoint( ...
    "dl_r_pdsch_1_3_1_fdd_tdla30_10", ...
    "tdla30_10_ula_low_2x2", ...
    "ValidateSetupOnly", true, ...
    "RequireExactStandardExecution", false, ...
    "RequireExactDataChannelExecution", true, ...
    "PrintTable", false, "Verbose", false);
assert(logical(fadingResult.DataChannelExecution.Exact) && ...
    isempty(fadingResult.DataChannelExecution.Blockers), ...
    "The rank-2 fading FRC must materialize its explicit FDD HARQ " + ...
    "timeline and recognized ULA Low correlation contract.");
localAssertFadingHARQCatalogCoverage();

widebandResult = sixgr.conformance.runFRCPoint( ...
    "dl_r_pdsch_1_2_3_fdd_tdla30_10", ...
    "tdla30_10_ula_low_4x4_rank3", ...
    "ValidateSetupOnly", true, ...
    "RequireExactStandardExecution", false, ...
    "RequireExactDataChannelExecution", true, ...
    "PrintTable", false, "Verbose", false);
assert(logical(widebandResult.DataChannelExecution.Exact) && ...
        isempty(widebandResult.DataChannelExecution.Blockers), ...
    "Rank-3 wideband PDSCH must be exact at the selected data-channel boundary.");
assert(string(widebandResult.DataChannelExecution.Contract.PRBBundlingSize) == ...
    "wideband", "Rank-3 PDSCH must retain the standardized wideband bundle.");
widebandTx = widebandResult.SetupValidation.TxEvidence{1};
widebandPHY = widebandTx.PhysicalConfiguration;
assert(logical(widebandPHY.Exact) && ...
        string(widebandPHY.PrecoderBundling) == "wideband" && ...
        double(widebandPHY.PrecoderNumPRG) == 1 && ...
        double(widebandPHY.PrecoderMatrixRank) == 3 && ...
        abs(double(widebandPHY.PrecoderTotalPower) - 1) <= 1e-10, ...
    ("Rank-3 PDSCH must materialize one finite full-rank 4x3 wideband " + ...
    "Type-I precoder page with unit total transmit power."));

codebookResult = sixgr.conformance.runFRCPoint( ...
    "ul_g_fr1_a11_1_tdla30_10_rank4", ...
    "tdla30_10_low_4x4", ...
    "ValidateSetupOnly", true, ...
    "RequireExactStandardExecution", false, ...
    "RequireExactDataChannelExecution", true, ...
    "PrintTable", false, "Verbose", false);
assert(logical(codebookResult.DataChannelExecution.Exact) && ...
        isempty(codebookResult.DataChannelExecution.Blockers) && ...
        lower(string(codebookResult.DataChannelExecution.Contract.PUSCHPrecodingScheme)) == "codebook" && ...
        double(codebookResult.DataChannelExecution.Contract.PUSCHTPMI) == 0, ...
    ("G-FR1-A11-1 must materialize its prescribed rank-4 native " + ...
    "codebook precoder and TPMI index 0."));

localAssertToolboxCorrelationMatrices();
localAssertRuntimePhysicalIdentity(catalog);
localAssertMissingDMRSSymbolContractFails(catalog);
ok = true;
end

function localAssertFadingHARQCatalogCoverage()
dlEntries = [ ...
    "dl_r_pdsch_1_4_1_fdd_tdla30_10"; ...
    "dl_r_pdsch_1_2_1_fdd_tdlc300_100"; ...
    "dl_r_pdsch_1_2_2_fdd_tdla30_10"];
ulEntries = [ ...
    "ul_g_fr1_a5_8_tdla30_10"; ...
    "ul_g_fr1_a4_8_tdlc300_100"; ...
    "ul_g_fr1_a9_1_tdla30_10"];
for entryId = [dlEntries; ulEntries].'
    catalog = sixgr.conformance.frcCatalog();
    entry = localItem(catalog.entries, localEntryIndex( ...
        catalog.entries, entryId));
    result = sixgr.conformance.runFRCPoint(entryId, ...
        string(entry.condition.id), ...
        "ValidateSetupOnly", true, ...
        "RequireExactStandardExecution", false, ...
        "RequireExactDataChannelExecution", true, ...
        "PrintTable", false, "Verbose", false);
    timing = result.DataChannelExecution.Contract.HARQ.Timing;
    assert(logical(result.DataChannelExecution.Exact) && ...
            isempty(result.DataChannelExecution.Blockers) && ...
            logical(timing.ChannelEvolutionBetweenRetransmissionsMaterialized) && ...
            double(timing.RetransmissionSpacingSlots) == 4, ...
        "FRC %s must materialize its explicit four-opportunity HARQ timeline.", ...
        entryId);
    if startsWith(entryId, "dl_")
        assert(logical(timing.FeedbackDelaySpecifiedByStandard) && ...
                logical(timing.ProcessCountSpecifiedByStandard) && ...
                double(timing.FeedbackDelaySlots) == 2, ...
            "DL FRC %s must retain TS 38.101-4 four-process/two-slot timing.", ...
            entryId);
    else
        assert(~logical(timing.FeedbackDelaySpecifiedByStandard) && ...
                ~logical(timing.ProcessCountSpecifiedByStandard) && ...
                contains(string(timing.RetransmissionSpacingSource), ...
                    "harness_assumption"), ...
            ["UL FRC %s must disclose that process count and feedback " + ...
             "delay are harness assumptions, not TS 38.104 requirements."], ...
            entryId);
    end
end
end

function localAssertRuntimePhysicalIdentity(catalog)
entry = localItem(catalog.entries, localEntryIndex( ...
    catalog.entries, "ul_g_fr1_a3a_1_awgn"));
carrier = nrCarrierConfig;
carrier.NSizeGrid = double(entry.carrier.n_prb);
carrier.NStartGrid = double(entry.carrier.prb_start);
carrier.SubcarrierSpacing = double(entry.carrier.subcarrier_spacing_khz);
carrier.CyclicPrefix = char(entry.carrier.cyclic_prefix);

pusch = nrPUSCHConfig;
pusch.PRBSet = double(entry.carrier.prb_start:entry.carrier.prb_end);
pusch.MappingType = char(entry.allocation.mapping_type);
pusch.SymbolAllocation = [double(entry.allocation.start_symbol), ...
    double(entry.allocation.symbol_length)];
pusch.Modulation = char(entry.coding.modulation);
pusch.NumLayers = double(entry.mimo.layers);
pusch.TransformPrecoding = logical(entry.waveform.transform_precoding);
pusch.FrequencyHopping = "neither";
pusch.EnablePTRS = logical(entry.ptrs.enabled);
pusch.DMRS.DMRSConfigurationType = double(entry.dmrs.configuration_type);
pusch.DMRS.DMRSLength = 1;
pusch.DMRS.DMRSTypeAPosition = double(entry.dmrs.type_a_position);
pusch.DMRS.DMRSAdditionalPosition = double(entry.dmrs.additional_position);
pusch.DMRS.NumCDMGroupsWithoutData = ...
    double(entry.dmrs.num_cdm_groups_without_data);
pusch.DMRS.DMRSPortSet = double(entry.dmrs.ports);
pusch.DMRS.NIDNSCID = double(entry.dmrs.n_id_0);
pusch.DMRS.NSCID = double(entry.dmrs.n_scid);

tx = struct( ...
    "Carrier", carrier, "PUSCH", pusch, ...
    "Grid", complex(zeros(12*double(entry.carrier.n_prb), 14, 1)), ...
    "Waveform", complex(zeros(32, double(entry.mimo.tx_antennas))), ...
    "DMRSPowerScale", 2, "RV", 0);
evidence = sixgr.conformance.assertFRCPhysicalConfiguration(entry, tx);
assert(logical(evidence.Exact) && ...
    string(evidence.Source) == "materialized_truth_transmitter_objects", ...
    "An exact runtime PUSCH configuration must pass the physical identity guard.");

mappingMismatch = tx;
mappingMismatch.PUSCH = nrPUSCHConfig;
mappingMismatch.PUSCH.PRBSet = pusch.PRBSet;
mappingMismatch.PUSCH.MappingType = "B";
mappingMismatch.PUSCH.SymbolAllocation = pusch.SymbolAllocation;
mappingMismatch.PUSCH.Modulation = pusch.Modulation;
mappingMismatch.PUSCH.NumLayers = pusch.NumLayers;
mappingMismatch.PUSCH.TransformPrecoding = pusch.TransformPrecoding;
mappingMismatch.PUSCH.FrequencyHopping = pusch.FrequencyHopping;
mappingMismatch.PUSCH.EnablePTRS = pusch.EnablePTRS;
mappingMismatch.PUSCH.DMRS.DMRSConfigurationType = ...
    pusch.DMRS.DMRSConfigurationType;
mappingMismatch.PUSCH.DMRS.DMRSLength = pusch.DMRS.DMRSLength;
mappingMismatch.PUSCH.DMRS.DMRSTypeAPosition = ...
    pusch.DMRS.DMRSTypeAPosition;
mappingMismatch.PUSCH.DMRS.DMRSAdditionalPosition = ...
    pusch.DMRS.DMRSAdditionalPosition;
mappingMismatch.PUSCH.DMRS.NumCDMGroupsWithoutData = ...
    pusch.DMRS.NumCDMGroupsWithoutData;
mappingMismatch.PUSCH.DMRS.DMRSPortSet = pusch.DMRS.DMRSPortSet;
mappingMismatch.PUSCH.DMRS.NIDNSCID = pusch.DMRS.NIDNSCID;
mappingMismatch.PUSCH.DMRS.NSCID = pusch.DMRS.NSCID;
localAssertRuntimeFailure(entry, mappingMismatch, ...
    "sixgr:conformance:RuntimeAllocationMismatch");

modulationMismatch = tx;
modulationMismatch.PUSCH = pusch;
modulationMismatch.PUSCH.Modulation = "16QAM";
localAssertRuntimeFailure(entry, modulationMismatch, ...
    "sixgr:conformance:RuntimeModulationMismatch");
pusch.Modulation = char(entry.coding.modulation);

portMismatch = tx;
portMismatch.Waveform = complex(zeros(32, 2));
localAssertRuntimeFailure(entry, portMismatch, ...
    "sixgr:conformance:RuntimeWaveformPortMismatch");
end

function localAssertRuntimeFailure(entry, tx, expectedIdentifier)
try
    sixgr.conformance.assertFRCPhysicalConfiguration(entry, tx);
catch caught
    assert(string(caught.identifier) == string(expectedIdentifier), ...
        "Unexpected runtime guard failure '%s': %s", ...
        caught.identifier, getReport(caught, "extended", "hyperlinks", "off"));
    return;
end
error("sixgr:tests:FRCRuntimeGuardDidNotFail", ...
    "FRC runtime guard did not reject expected mismatch '%s'.", ...
    expectedIdentifier);
end

function localAssertMissingDMRSSymbolContractFails(catalog)
entryIndex = localEntryIndex(catalog.entries, ...
    "dl_r_pdsch_1_2_1_fdd_atg_awgn");
entry = localItem(catalog.entries, entryIndex);
entry.dmrs = rmfield(entry.dmrs, "symbol_indices");
catalog.entries = localReplaceItem(catalog.entries, entryIndex, entry);
catalogPath = localWriteTemporaryCatalog(catalog);
cleanup = onCleanup(@() localDeleteIfPresent(catalogPath)); %#ok<NASGU>
try
    sixgr.conformance.frcCatalog(catalogPath);
catch caught
    assert(string(caught.identifier) == "sixgr:conformance:InvalidFRCatalog" && ...
        contains(string(caught.message), ".dmrs") && ...
        contains(string(caught.message), "symbol_indices"), ...
        "Missing DM-RS symbols must fail with the typed catalog error.");
    return;
end
error("sixgr:tests:FRCMissingDMRSSymbolContractAccepted", ...
    "The FRC catalog accepted an entry without explicit DM-RS symbols.");
end

function cause = localExpectedExecutionBlock(entryId, conditionId, catalogPath)
args = { ...
    "ValidateSetupOnly", true, ...
    "RequireExactStandardExecution", false, ...
    "RequireExactDataChannelExecution", true, ...
    "PrintTable", false, ...
    "Verbose", false};
if strlength(string(catalogPath)) > 0
    args = [args, {"CatalogPath", catalogPath}]; %#ok<AGROW>
end
try
    sixgr.conformance.runFRCPoint(entryId, conditionId, args{:});
catch caught
    cause = caught;
    assert(string(cause.identifier) == ...
        "sixgr:conformance:IncompleteDataChannelExecution", ...
        "Unexpected fail-closed identifier '%s': %s", ...
        cause.identifier, getReport(cause, "extended", "hyperlinks", "off"));
    return;
end
error("sixgr:tests:FRCExecutionDidNotFailClosed", ...
    "FRC execution unexpectedly proceeded despite an incomplete contract.");
end

function localAssertToolboxCorrelationMatrices()
channel = nrTDLChannel;
cleanup = onCleanup(@() release(channel)); %#ok<NASGU>
channel.NumTransmitAntennas = 2;
channel.NumReceiveAntennas = 2;
channel.TransmissionDirection = "Downlink";
channel.MIMOCorrelation = "Medium";
channelInfo = info(channel);
actualMedium = double(channelInfo.SpatialCorrelationMatrix);
expectedMedium = [ ...
    1, 0.9, 0.3, 0.27; ...
    0.9, 1, 0.27, 0.3; ...
    0.3, 0.27, 1, 0.9; ...
    0.27, 0.3, 0.9, 1];
assert(max(abs(actualMedium - expectedMedium), [], "all") <= 5e-12, ...
    "nrTDLChannel Medium does not match the selected TS 38.101-4 matrix.");

channel.MIMOCorrelation = "Low";
channelInfo = info(channel);
actualLow = double(channelInfo.SpatialCorrelationMatrix);
assert(isequal(actualLow, eye(4)), ...
    "nrTDLChannel Low must be the exact uncorrelated 2x2 matrix.");
end

function path = localWriteTemporaryCatalog(catalog)
path = string(tempname) + ".json";
fid = fopen(path, "wt");
assert(fid >= 0, "Unable to create temporary FRC catalog '%s'.", path);
fileCleanup = onCleanup(@() fclose(fid)); %#ok<NASGU>
count = fwrite(fid, jsonencode(catalog), "char");
assert(count > 0, "Unable to write temporary FRC catalog '%s'.", path);
end

function localDeleteIfPresent(path)
if isfile(path)
    delete(path);
end
end

function index = localEntryIndex(entries, entryId)
matches = false(numel(entries), 1);
for candidateIndex = 1:numel(entries)
    matches(candidateIndex) = ...
        string(localItem(entries, candidateIndex).id) == string(entryId);
end
indices = find(matches);
assert(numel(indices) == 1, ...
    "Expected one catalog entry with id '%s'.", entryId);
index = indices;
end

function sequence = localReplaceItem(sequence, index, value)
if iscell(sequence)
    sequence{index} = value;
else
    sequence(index) = value;
end
end

function item = localItem(sequence, index)
if iscell(sequence)
    item = sequence{index};
else
    item = sequence(index);
end
end
