function ok = testTRSRuntimeControlGatingEvidenceContract()
%TESTTRSRUNTIMECONTROLGATINGEVIDENCECONTRACT Guard coupled TRS/SRS gate wiring.

scenarioPath = fullfile("simulator", "configs", "scenarios", "master_scenaio_all_file.yaml");
scfg = sixgr.lls6g.config.loadScenarioConfig(scenarioPath);
cfg = sixgr.lls6g.buildInternalConfig(scfg, tempname);

assert(double(sixgr.util.structGet(cfg, "phy.srs.period_slots", NaN)) == 20, ...
    "master_scenaio_all_file.yaml must resolve 10 ms SRS periodicity to 20 slots at 30 kHz SCS.");
resolvedSRSSlots = double(sixgr.util.structGet(cfg, "phy.srs.slotWithinPeriod1Based", []));
assert(isequal(resolvedSRSSlots(:).', [5 10 15 20]), ...
    "Master SRS occasions must be explicit UL slots within each 20-slot period.");
assert(double(sixgr.util.structGet(cfg, "phy.srs.maxUEsPerSlot", NaN)) >= 2 && ...
    strcmpi(char(string(sixgr.util.structGet(cfg, "phy.srs.schedulingPolicy", ""))), "multiplex_due_users"), ...
    "Master SRS policy must multiplex both WebGUI UEs on due SRS occasions.");
assert(sixgr.truth.coupledSRSResourceOpportunity(cfg, 10, 1, 2, 20, "multiplex_due_users", 2) && ...
    sixgr.truth.coupledSRSResourceOpportunity(cfg, 10, 2, 2, 20, "multiplex_due_users", 2), ...
    "Both UEs must have an SRS opportunity on the first post-PRACH UL SRS slot.");

multiUser = struct( ...
    "Enabled", true, ...
    "NumUsers", 2, ...
    "RNTIStart", 1, ...
    "ExecutionModel", "slot_coupled_truth");
state = sixgr.truth.CoupledTruthRuntime.initialize(cfg, tempname, multiUser, struct(), 1);
state.CurrentServingIdx = [1; 2];
state.CurrentFrame = 1;
state.CurrentSlot = 1;
state.CurrentSNR_dB = 20;
outs = cell(2, 1);
for ueIdx = 1:2
    [cfgRuntime, state] = sixgr.truth.CoupledTruthRuntime.applyUserContext(cfg, state, ueIdx, "DL"); %#ok<ASGLU>
    out = sixgr.link.runTRSTracking(cfgRuntime, "SNR_dB", 20);
    assert(logical(out.Ok) && logical(out.DetectionSuccess) && logical(out.TRSRuntimeEvidenceUsable), ...
        "Coupled runtime TRS context must produce usable strict receiver evidence for UE %d.", ueIdx);
    assert(isfinite(double(out.DetectionMetric)) && double(out.ResourceCoverageRatio) >= double(out.MinCoverageRatio), ...
        "TRS detection metrics must satisfy the configured resource coverage gate for UE %d.", ueIdx);
    assert(logical(out.TRSTimingEstimateAvailable) && logical(out.TRSCFOEstimateAvailable) && ...
        logical(out.TRSChannelEstimateAvailable), ...
        "TRS runtime evidence must include timing, CFO, and channel-estimate availability for UE %d.", ueIdx);
    outs{ueIdx} = out;
end
out = outs{1};

trsRow = struct2table(struct( ...
    "Frame", 1, ...
    "Slot", 1, ...
    "SNR_dB", 20, ...
    "NMSE_dB", double(out.NMSE_dB), ...
    "DetectionMetric", double(out.DetectionMetric), ...
    "ResourceCoverageRatio", double(out.ResourceCoverageRatio), ...
    "DetectionAttempted", true, ...
    "DetectionSuccess", true, ...
    "DetectionUsable", true, ...
    "TimingTrackingAttempted", true, ...
    "TRSTimingEstimateAvailable", true, ...
    "EstimatedTimingOffset_samples", 0, ...
    "TRSTimingEstimateUsable", true, ...
    "FrequencyTrackingAttempted", true, ...
    "TRSCFOEstimateAvailable", true, ...
    "EstimatedCFO_Hz", 0, ...
    "EstimatedCFO_PreCorrection_Hz", 0, ...
    "TRSCFOEstimateUsable", true, ...
    "ChannelEstimationAttempted", true, ...
    "TRSChannelEstimateAvailable", true, ...
    "TRSRuntimeEvidenceUsable", true, ...
    "StrictOk", true, ...
    "UsedOracleFields", "", ...
    "Status", "PASS"), "AsArray", true);
trsRow = sixgr.truth.CoupledTruthRuntime.canonicalizePersistedControlReferenceTable("TRS", trsRow);
assert(ismember("UsedOracleFields", string(trsRow.Properties.VariableNames)) && ...
    all(strlength(strtrim(string(trsRow.UsedOracleFields))) == 0), ...
    "Canonical TRS rows must keep UsedOracleFields blank when no oracle fields were used.");

ok = true;
end
