function tests = testPUSCHMasterYAMLAuthority
%TESTPUSCHMASTERYAMLAUTHORITY Prove both operator masters own PUSCH runtime.
tests = functiontests(localfunctions);
end

function testBothOperatorMastersOwnPUSCHRuntime(~)
setup6GRSimToolkit("Verbose", false, "RunToolboxChecks", false);

repoRoot = fileparts(fileparts(mfilename("fullpath")));
root = fullfile(repoRoot, "simulator", "configs", "scenarios");
tmp = tempname;
mkdir(tmp);
cleanup = onCleanup(@() localCleanup(tmp)); %#ok<NASGU>

fixed = localLoadBuildAndMaterialize(root, "master_sinr_sweep.yaml", ...
    tmp, 1, 1, "nonCodebook", false, false);
geometry = localLoadBuildAndMaterialize(root, ...
    "master_geometry_based.yaml", tmp, 2, 2, "codebook", true, true);

assert(~logical(fixed.Cfg.phy.pusch.powerControl.enabled) && ...
    logical(geometry.Cfg.phy.pusch.powerControl.enabled), ...
    "Each master must preserve its explicit PUSCH power-control mode.");
assert(~logical(fixed.Cfg.phy.pusch.srsAuthority.required) && ...
    logical(geometry.Cfg.phy.pusch.srsAuthority.required), ...
    "Each master must preserve its explicit measured-SRS authority mode.");
assert(~logical(fixed.Cfg.phy.pusch.srsAuthority.configuredTPMIFallbackAllowed) && ...
    ~logical(geometry.Cfg.phy.pusch.srsAuthority.configuredTPMIFallbackAllowed), ...
    "Neither strict operator mode may allow configured-TPMI fallback.");

% Mutation proves that detailed PUSCH values are read from YAML rather than
% replaced with allocator defaults.
probe = fixed.Resolved;
probe.pusch.rnti = 77;
probe.pusch.scrambling_id = 91;
probe.pusch.uci_beta_offset_ack = 12;
probe.pusch.uci_beta_offset_csi1 = 4.5;
probe.pusch.uci_beta_offset_csi2 = 5.5;
probe.pusch.uci_scaling = 0.75;
probeCfg = sixgr.lls6g.buildInternalConfig( ...
    sixgr.lls6g.config.ScenarioConfig(probe, ...
        "ConfigPath", fixed.Path, "Kind", "scenario"), ...
    fullfile(tmp, "probe"));
[probeCarrier, ~] = sixgr.phy.grid.makeCarrier(probeCfg);
[~, probeInfo, probePUSCH] = sixgr.phy.grid.allocREsPUSCH( ...
    probeCarrier, probeCfg);
assert(double(probePUSCH.RNTI) == 77 && double(probePUSCH.NID) == 91, ...
    "Mutated YAML RNTI/scrambling identity did not reach nrPUSCHConfig.");
assert(double(probeInfo.BetaOffsetACK) == 12 && ...
    double(probeInfo.BetaOffsetCSI1) == 4.5 && ...
    double(probeInfo.BetaOffsetCSI2) == 5.5 && ...
    double(probeInfo.UCIScaling) == 0.75, ...
    "Mutated YAML UCI scaling did not reach the production PUSCH allocator.");

conflict = fixed.Resolved;
conflict.pusch.transmission_scheme = "codebook";
localAssertError(@() sixgr.lls6g.buildInternalConfig(conflict, ...
    fullfile(tmp, "conflict")), "PUSCHCodebookPolicyConflict");

fprintf("PUSCH master YAML authority: both modes materialized; " + ...
    "allocation/MCS/rank/DM-RS/PT-RS/UCI/hopping/power/SRS fields verified.\n");
end

function out = localLoadBuildAndMaterialize(root, fileName, tmp, ...
        expectedLayers, expectedPorts, expectedScheme, expectedPTRS, ...
        expectedPowerControl)
path = fullfile(root, fileName);
raw = sixgr.lls6g.config.readConfigFile(path);
required = [ ...
    "rnti","scrambling_id","mcs_table","mcs_index","modulation", ...
    "target_code_rate_per_codeword","num_layers","num_antenna_ports", ...
    "transmission_scheme","codebook_type","tpmi","rv_per_codeword", ...
    "ndi_per_codeword","harq_process_id","resource_allocation_type", ...
    "mapping_type","prb_start","num_prb","start_symbol","num_symbols", ...
    "frequency_hopping","second_hop_start_prb","transform_precoding", ...
    "dmrs_configuration_type","dmrs_length","dmrs_additional_position", ...
    "dmrs_type_a_position","dmrs_num_cdm_groups_without_data", ...
    "dmrs_port_set","dmrs_nid_nscid","dmrs_nscid", ...
    "dmrs_group_hopping","dmrs_sequence_hopping","ptrs_enabled", ...
    "ptrs_time_density","ptrs_frequency_density","ptrs_re_offset", ...
    "ptrs_port_set","uci_beta_offset_ack","uci_beta_offset_csi1", ...
    "uci_beta_offset_csi2","uci_scaling","power_control", ...
    "srs_authority"];
for field = required
    assert(isfield(raw.pusch, field), ...
        "%s must explicitly configure pusch.%s.", fileName, field);
end

scfg = sixgr.lls6g.config.loadScenarioConfig(path);
resolved = scfg.toStruct();
runFolder = fullfile(tmp, erase(fileName, ".yaml"));
cfg = sixgr.lls6g.buildInternalConfig(scfg, runFolder);
[carrier, ~] = sixgr.phy.grid.makeCarrier(cfg);
[~, info, pusch] = sixgr.phy.grid.allocREsPUSCH(carrier, cfg);

assert(double(cfg.phy.pusch.RNTI) == double(raw.pusch.rnti) && ...
    double(cfg.phy.pusch.NID) == double(raw.pusch.scrambling_id), ...
    "%s did not preserve PUSCH identities.", fileName);
assert(strcmpi(string(cfg.phy.pusch.mcsTable), ...
    string(raw.pusch.mcs_table)) && ...
    double(cfg.phy.pusch.mcsIndex) == double(raw.pusch.mcs_index) && ...
    strcmpi(string(cfg.phy.pusch.modulation), ...
    string(raw.pusch.modulation)) && ...
    isequal(double(cfg.phy.pusch.codeRate(:).'), ...
    double(raw.pusch.target_code_rate_per_codeword(:).')), ...
    "%s did not preserve its PUSCH MCS/coding surface.", fileName);
assert(double(pusch.NumLayers) == expectedLayers && ...
    double(pusch.NumAntennaPorts) == expectedPorts && ...
    strcmpi(string(pusch.TransmissionScheme), expectedScheme), ...
    "%s did not preserve rank/ports/transmission scheme.", fileName);
assert(double(cfg.phy.pusch.resourceAllocationType) == 1 && ...
    strcmpi(string(cfg.phy.pusch.mappingType), ...
    string(raw.pusch.mapping_type)) && ...
    isequal(double(pusch.PRBSet), ...
    double(raw.pusch.prb_start) + (0:(double(raw.pusch.num_prb) - 1))) && ...
    isequal(double(pusch.SymbolAllocation), ...
    [double(raw.pusch.start_symbol) double(raw.pusch.num_symbols)]), ...
    "%s did not preserve PUSCH resource allocation.", fileName);
assert(strcmpi(string(cfg.phy.pusch.frequencyHopping.mode), "none") && ...
    strcmpi(string(pusch.FrequencyHopping), "neither"), ...
    "%s did not normalize the configured disabled hopping mode.", fileName);

dmrs = pusch.DMRS;
assert(double(dmrs.DMRSConfigurationType) == ...
    double(raw.pusch.dmrs_configuration_type) && ...
    double(dmrs.DMRSLength) == double(raw.pusch.dmrs_length) && ...
    double(dmrs.DMRSAdditionalPosition) == ...
    double(raw.pusch.dmrs_additional_position) && ...
    double(dmrs.DMRSTypeAPosition) == ...
    double(raw.pusch.dmrs_type_a_position) && ...
    double(dmrs.NumCDMGroupsWithoutData) == ...
    double(raw.pusch.dmrs_num_cdm_groups_without_data) && ...
    isequal(double(dmrs.DMRSPortSet), double(raw.pusch.dmrs_port_set(:).')) && ...
    double(dmrs.NIDNSCID) == double(raw.pusch.dmrs_nid_nscid) && ...
    double(dmrs.NSCID) == double(raw.pusch.dmrs_nscid), ...
    "%s did not preserve its explicit PUSCH DM-RS configuration.", fileName);
assert(logical(pusch.EnablePTRS) == logical(expectedPTRS), ...
    "%s did not preserve PUSCH PT-RS enablement.", fileName);
if expectedPTRS
    assert(double(pusch.PTRS.TimeDensity) == ...
        double(raw.pusch.ptrs_time_density) && ...
        double(pusch.PTRS.FrequencyDensity) == ...
        double(raw.pusch.ptrs_frequency_density) && ...
        strcmp(string(pusch.PTRS.REOffset), ...
        string(raw.pusch.ptrs_re_offset)) && ...
        isequal(double(pusch.PTRS.PTRSPortSet), ...
        double(raw.pusch.ptrs_port_set(:).')), ...
        "%s did not preserve its explicit PUSCH PT-RS configuration.", ...
        fileName);
end
assert(double(info.BetaOffsetACK) == ...
    double(raw.pusch.uci_beta_offset_ack) && ...
    double(info.BetaOffsetCSI1) == ...
    double(raw.pusch.uci_beta_offset_csi1) && ...
    double(info.BetaOffsetCSI2) == ...
    double(raw.pusch.uci_beta_offset_csi2) && ...
    double(info.UCIScaling) == double(raw.pusch.uci_scaling), ...
    "%s did not apply its UCI beta/scaling configuration.", fileName);
assert(logical(cfg.phy.pusch.powerControl.enabled) == ...
    logical(expectedPowerControl), ...
    "%s did not preserve PUSCH power-control enablement.", fileName);

out = struct("Raw", raw, "Resolved", resolved, "Cfg", cfg, "PUSCH", pusch, ...
    "Info", info, "Path", path);
end

function localAssertError(action, expectedIdentifierFragment)
caught = [];
try
    action();
catch ME
    caught = ME;
end
assert(~isempty(caught), "Expected an error containing '%s'.", ...
    expectedIdentifierFragment);
assert(contains(string(caught.identifier), expectedIdentifierFragment), ...
    "Expected error containing '%s', received '%s': %s", ...
    expectedIdentifierFragment, string(caught.identifier), ...
    string(caught.message));
end

function localCleanup(folder)
if isfolder(folder)
    rmdir(folder, "s");
end
end
