function ok = testLLSRawTrialProvenance()
%TESTLLSRAWTRIALPROVENANCE Verify DL/UL raw trial tables preserve grant/runtime provenance.

setup6GRSimToolkit("Verbose", false);

tmp = tempname;
mkdir(tmp);
c = onCleanup(@() rmdir(tmp, "s")); %#ok<NASGU>

scfg = sixgr.lls6g.config.loadScenarioConfig( ...
    fullfile(pwd, "simulator", "configs", "scenarios", "lls_700mhz_20mhz_3bs_30ue_tdlc_browser_coupled.yaml"));
cfg = sixgr.lls6g.buildInternalConfig(scfg, fullfile(tmp, "run"));
cfg.run.numFrames = 1;
cfg.channel.snr_dB = 10;
cfg.channel.model = "AWGN";
cfg.channel.awgnOnly = true;
cfg.run.noiseOperatingMode = "receiver_noise_figure_thermal_noise";
cfg.run.interferenceExecutionMode = "none";
multiUser = struct("Enabled", true, "NumUsers", 1, "RNTIStart", 320, "ExecutionModel", "slot_coupled_truth");
state = sixgr.truth.CoupledTruthRuntime.initialize(cfg, fullfile(tmp, "runtime"), multiUser, struct(), 1);
state.CurrentServingIdx(1) = 1;
state.CurrentServingMetric_dBm(1) = -70;
state.CurrentSlot = 1;
state.CurrentFrame = 1;
state.CurrentSNR_dB = 10;
state.LargeScaleState.BeamIndex(1,1) = 1;
state.LargeScaleState.BeamGain_dB(1,1) = 0;
state.LargeScaleState.RxPower_dBm(1,1) = -70;
state.LargeScaleState.BasePathloss_dB(1,1) = 100;
state.LargeScaleState.Pathloss_dB(1,1) = 100;
state.LargeScaleState.Shadow_dB(1,1) = 0;
state.LargeScaleState.O2I_dB(1,1) = 0;
[cfgDL, state] = sixgr.truth.CoupledTruthRuntime.applyUserContext(cfg, state, 1, "DL");
[cfgUL, state] = sixgr.truth.CoupledTruthRuntime.applyUserContext(cfg, state, 1, "UL");
cfgDL.phy.pdsch.dmrs.DMRSTypeAPosition = 3;
cfgDL.phy.pdsch.dmrs.typeAPosition = 3;
cfgDL.phy.dmrs.typeAPosition = 3;
cfgDL.lls6g.userContext.BeamIndexSet = "1";

grant = struct( ...
    "UEIndex", 1, ...
    "RNTI", 320, ...
    "ServingCell", 1, ...
    "CQIUsed", 7, ...
    "RIUsed", 1, ...
    "PMI", 0, ...
    "CRI", 0, ...
    "MCSTable", "qam64_table1", ...
    "CQITable", "table1", ...
    "AMCMode", "cqi_driven", ...
    "GrantReason", "unit_test", ...
    "Frame", 1, ...
    "Slot", 1, ...
    "HARQ", struct(), ...
    "PBCHGatingActive", true, ...
    "PRACHGatingActive", true, ...
    "PDCCHGatingActive", true, ...
    "SRSGatingActive", true, ...
    "ControlEligible", true, ...
    "ControlDecodeOk", true, ...
    "DCICrcPass", true, ...
    "PDCCHPayloadMatch", true, ...
    "PDCCHCausalGrantDecodeOk", true, ...
    "PDCCHMissedDetection", false, ...
    "PDCCHFalseAlarm", false, ...
    "GrantValid", true, ...
    "NegativeExpectedOk", false, ...
    "PDCCHBlindSearchEnabled", true, ...
    "PDCCHREGMappingAvailable", true, ...
    "PDCCHControlFailureReason", "pdcch_dci_crc_and_payload_match", ...
    "PDCCHControlEvidenceSource", "pdcch_waveform_dci_crc_and_payload_match", ...
    "ControlDecodeSource", "pdcch_waveform_dci_crc_and_payload_match", ...
    "GrantControlState", "control_ok", ...
    "CellAcquisitionState", "acquired", ...
    "AccessState", "succeeded", ...
    "SRSValidityState", "valid", ...
    "CSIValidityState", "fresh_runtime_srs", ...
    "SRSValid", true, ...
    "SRSAgeSlots", 0);

dl = sixgr.link.runDLPDSCHThroughput(cfgDL, ...
    "NumFrames", 1, ...
    "SNR_dB", 10, ...
    "GrantSnapshot", grant, ...
    "InterferenceBundle", struct([]));
ul = sixgr.link.runULPUSCHThroughput(cfgUL, ...
    "NumFrames", 1, ...
    "SNR_dB", 10, ...
    "GrantSnapshot", grant, ...
    "InterferenceBundle", struct([]));

localAssertRawTrialTable(dl.TrialTable, "DL");
localAssertRawTrialTable(ul.TrialTable, "UL");
localAssertLiveExportsKeepDataArtifactsWithPUCCHSideColumns(dl.TrialTable, ul.TrialTable, tmp);
ok = true;
end

function localAssertLiveExportsKeepDataArtifactsWithPUCCHSideColumns(dlT, ulT, tmpRoot)
runFolder = fullfile(tmpRoot, "live_export_side_column_guard");
layout = sixgr.report.resultLayout(runFolder);
sixgr.util.ensureFolder(layout.ReportCSVDir);
dlT = localAddPUCCHSideColumns(dlT, "DL");
ulT = localAddPUCCHSideColumns(ulT, "UL");
trialT = localAppendCompatTable(dlT, ulT);
sixgr.truth.exportLLSLiveSignalChainTables(runFolder, trialT, table(), struct());

channelState = readtable(fullfile(layout.ReportCSVDir, "live_channel_state_tti.csv"), "VariableNamingRule", "preserve");
stageTrace = readtable(fullfile(layout.ReportCSVDir, "live_tx_rx_stage_trace.csv"), "VariableNamingRule", "preserve");
localAssertDirectionalSource(channelState, "DL", "air_interface/csv/dl_pdsch_trials.csv", "channel-state live export");
localAssertDirectionalSource(channelState, "UL", "air_interface/csv/ul_pusch_trials.csv", "channel-state live export");
localAssertDirectionalSource(stageTrace, "DL", "air_interface/csv/dl_pdsch_trials.csv", "stage-trace live export");
localAssertDirectionalSource(stageTrace, "UL", "air_interface/csv/ul_pusch_trials.csv", "stage-trace live export");
end

function T = localAddPUCCHSideColumns(T, direction)
T.RequestedFormat = repmat(2, height(T), 1);
T.ResolvedFormat = repmat(2, height(T), 1);
T.PUCCHResourceId = repmat("pucch_sidecar_for_" + lower(string(direction)) + "_harq_ack", height(T), 1);
T.UCIType = repmat("harq_ack", height(T), 1);
end

function Tout = localAppendCompatTable(Ta, Tb)
if ~(istable(Ta) && ~isempty(Ta))
    Tout = Tb;
    return;
end
if ~(istable(Tb) && ~isempty(Tb))
    Tout = Ta;
    return;
end
vars = union(string(Ta.Properties.VariableNames), string(Tb.Properties.VariableNames), "stable");
Ta = localEnsureTableVars(Ta, vars, Tb);
Tb = localEnsureTableVars(Tb, vars, Ta);
Tout = [Ta(:, cellstr(vars)); Tb(:, cellstr(vars))];
end

function T = localEnsureTableVars(T, vars, refT)
for ii = 1:numel(vars)
    name = char(vars(ii));
    if ~ismember(name, T.Properties.VariableNames)
        T.(name) = localDefaultColumnLike(refT, name, height(T));
    end
end
end

function col = localDefaultColumnLike(refT, name, n)
if istable(refT) && ismember(name, refT.Properties.VariableNames)
    refCol = refT.(name);
    if islogical(refCol)
        col = false(n, 1);
    elseif isnumeric(refCol)
        col = NaN(n, 1);
    else
        col = strings(n, 1);
    end
else
    col = strings(n, 1);
end
end

function localAssertDirectionalSource(T, direction, expectedArtifact, label)
mask = upper(strtrim(string(T.Direction))) == upper(string(direction));
assert(any(mask), "%s must contain at least one %s row.", label, direction);
assert(all(strcmpi(string(T.SourceArtifact(mask)), expectedArtifact)) && ...
    all(strcmpi(string(T.SourceTable(mask)), expectedArtifact)), ...
    "%s must keep finite-TB %s rows sourced from %s even when PUCCH/UCI side columns are present.", ...
    label, direction, expectedArtifact);
end

function localAssertRawTrialTable(T, direction)
assert(istable(T) && height(T) == 1, ...
    "Expected a single raw %s trial row for provenance validation.", direction);
requiredVars = { ...
    'GrantControlState','ControlDecodeOk','CellAcquisitionState','AccessState','SRSValidityState','CSIValidityState', ...
    'PBCHGatingActive','PRACHGatingActive','PDCCHGatingActive','SRSGatingActive','ControlEligible','SRSValid','SRSAgeSlots', ...
    'InterferenceMode','InterferenceContributorCount','InterferenceAggregatedRxPower_dBm','InterferencePowerSource','FullInterfererChannelTruthUsed', ...
    'ConfiguredBeamSelectionStrategy','PrecoderSource','PrecodingMode','PrecodingApplicationStage','PrecodingActive', ...
    'ExplicitBeamWeightsApplied','TransformPrecodingApplied','BeamformingApplied','AppliedBeamIndexSet', ...
    'AppliedPrecoderPMI','AppliedPrecoderPMIType','AppliedPrecoderCodebookMode','PrecodingNumPorts','PrecodingNumLayers','PrecodingMatrixRows','PrecodingMatrixCols', ...
    'RequestedBeamIndexSet','RequestedPrecoderPMI','RequestedPrecoderSource','AppliedPrecoderSource', ...
    'RequestedBeamTruthClassification','RequestedPrecoderPMITruthClassification', ...
    'AppliedBeamApplicationSource','AppliedBeamTruthClassification','AppliedPrecoderPMIApplicationSource','AppliedPrecoderPMITruthClassification', ...
    'ConfiguredLinkAdaptationMode','ConfiguredMCSSelectionPolicy','SchedulerGrantMCSSelectionMode','RequestedOperatingPointSource', ...
    'MCSAuthority','ModulationAuthority','GrantOperatingPointSource','AppliedOperatingPointSource', ...
    'InjectedCFO_Hz','TrueCFO_Hz','EstimatedCFO_PreCorrection_Hz','EstimatedCFO_Hz','ResidualCFO_PostCorrection_Hz','CFOError_Hz','CFOEstimateAvailability','CFOErrorDefinition','CFOValueStatus', ...
    'TimingEstimateAvailability','TimingErrorDefinition','TimingValueStatus','LargeScaleSINRValueStatus','LargeScaleSINRFinalizedFlag','LargeScaleSINRNAReason', ...
    'PRBStart','AllocatedPRBCount','RunUUID','RunTag','ScenarioID','RunnerProfile','ConfigHash','SourceArtifact','SourceTable','ArtifactClass','SemanticState', ...
    'CountsTowardCoverage','MachineReadable','HumanReadable','RowLifecycleState','PartialRowFlag','FinalizedFlag','FallbackFlag','PlaceholderFlag','NAReason', ...
    'BSAntennaArrayClass','BSAntennaArrayType','BSAntennaElements','BSAntennaNumPorts','UEAntennaArrayClass','UEAntennaArrayType','UEAntennaElements','UEAntennaNumPorts', ...
    'AntennaConfigSource','RuntimeAntennaObjectSource','AntennaRuntimeObjectCreated','ChannelArrayModel','ChannelUsesCountOnlyAntennaModel', ...
    'PropagationDistance_m','GeometricPropagationDelay_s','ToD_s','ToA_s','ChannelDelaySource','AntennaGeometrySource','SameFlowEvidenceSource'};
assert(all(ismember(requiredVars, T.Properties.VariableNames)), ...
    "Raw %s trial table must expose control and interference provenance fields.", direction);
assert(strcmpi(char(string(T.GrantControlState(1))), "control_ok"), ...
    "Raw %s trial table must preserve grant control state.", direction);
assert(logical(T.ControlDecodeOk(1)), ...
    "Raw %s trial table must preserve control-decode success.", direction);
assert(strcmpi(char(string(T.CellAcquisitionState(1))), "acquired"), ...
    "Raw %s trial table must preserve cell-acquisition state.", direction);
assert(strcmpi(char(string(T.AccessState(1))), "succeeded"), ...
    "Raw %s trial table must preserve access state.", direction);
assert(strcmpi(char(string(T.SRSValidityState(1))), "valid"), ...
    "Raw %s trial table must preserve SRS validity state.", direction);
assert(strcmpi(char(string(T.CSIValidityState(1))), "fresh_runtime_srs"), ...
    "Raw %s trial table must preserve CSI validity state.", direction);
assert(strcmpi(char(string(T.ConfiguredMCSSelectionPolicy(1))), "cqi_driven") && ...
    strcmpi(char(string(T.RequestedOperatingPointSource(1))), "cqi_link_adaptation") && ...
    strcmpi(char(string(T.ActualMCSSelectionMode(1))), "scheduler_grant"), ...
    "Raw %s trial table must separate configured AMC policy from scheduler-applied runtime selection.", direction);
assert(~strcmpi(char(string(T.ConfiguredMCSSelectionPolicy(1))), char(string(T.ActualMCSSelectionMode(1)))), ...
    "Raw %s trial table must not relabel configured AMC policy as actual runtime selection.", direction);
assert(double(T.InterferenceContributorCount(1)) == 0, ...
    "Raw %s trial table must report zero contributors when no interference bundle is supplied.", direction);
assert(~logical(T.FullInterfererChannelTruthUsed(1)), ...
    "Raw %s trial table must not claim full interferer truth when no interferers are present.", direction);
assert(logical(T.AntennaRuntimeObjectCreated(1)) && strlength(string(T.AntennaConfigSource(1))) > 0 && ...
    strlength(string(T.RuntimeAntennaObjectSource(1))) > 0, ...
    "Raw %s trial table must preserve active runtime antenna-object provenance.", direction);
assert(strcmpi(char(string(T.ChannelArrayModel(1))), "awgn_no_array_channel"), ...
    "Raw %s trial table must honestly disclose the active AWGN no-array channel shortcut used in this focused provenance test.", direction);
localAssertCFOValueLineage(T, direction);
assert(strcmpi(char(string(T.TimingValueStatus(1))), "NOT_APPLICABLE") || strcmpi(char(string(T.TimingValueStatus(1))), "OK") || strcmpi(char(string(T.TimingValueStatus(1))), "NOT_AVAILABLE"), ...
    "Raw %s trial table must classify timing lineage explicitly.", direction);
assert(strcmpi(char(string(T.LargeScaleSINRValueStatus(1))), "NOT_AVAILABLE") || strcmpi(char(string(T.LargeScaleSINRValueStatus(1))), "MISSING") || strcmpi(char(string(T.LargeScaleSINRValueStatus(1))), "OK"), ...
    "Raw %s trial table must classify large-scale SINR lineage explicitly.", direction);
assert(isfinite(double(T.AllocatedPRBCount(1))) && isfinite(double(T.PRBStart(1))), ...
    "Raw %s trial table must expose PRB start/count from the actual applied grant when allocation exists.", direction);
assert(strlength(string(T.SourceArtifact(1))) > 0 && strlength(string(T.SourceTable(1))) > 0 && ...
    strlength(string(T.RowLifecycleState(1))) > 0, ...
    "Raw %s trial table must preserve canonical artifact and lifecycle provenance.", direction);
assert(isfinite(double(T.PropagationDistance_m(1))) && isfinite(double(T.ToD_s(1))) && isfinite(double(T.ToA_s(1))) && ...
    double(T.ToA_s(1)) >= double(T.ToD_s(1)), ...
    "Raw %s trial table must preserve same-flow timing/geometry evidence.", direction);
if strcmpi(direction, "DL")
    dciVars = {'DCICrcPass','PDCCHPayloadMatch','PDCCHCausalGrantDecodeOk','PDCCHMissedDetection','PDCCHFalseAlarm', ...
        'GrantValid','PDCCHBlindSearchEnabled','PDCCHREGMappingAvailable','PDCCHControlFailureReason','PDCCHControlEvidenceSource','ControlDecodeSource'};
    assert(all(ismember(dciVars, T.Properties.VariableNames)), ...
        "DL raw trial table must expose decoded PDCCH/DCI lineage fields.");
    assert(logical(T.DCICrcPass(1)) && logical(T.PDCCHPayloadMatch(1)) && ...
        logical(T.PDCCHCausalGrantDecodeOk(1)) && logical(T.GrantValid(1)) && ...
        ~logical(T.PDCCHMissedDetection(1)) && ~logical(T.PDCCHFalseAlarm(1)), ...
        "DL raw trial table must preserve successful decoded DCI lineage from the finalized grant.");
    assert(strcmpi(char(string(T.SourceArtifact(1))), "air_interface/csv/dl_pdsch_trials.csv") && ...
        strcmpi(char(string(T.SourceTable(1))), "air_interface/csv/dl_pdsch_trials.csv"), ...
        "DL raw trial table must identify itself as PDSCH evidence, not a control-channel artifact.");
    assert(logical(T.PrecodingActive(1)), ...
        "DL raw trial table must mark active precoding when the browser-owned rank-2 beam path is used.");
    assert(logical(T.ExplicitBeamWeightsApplied(1)) && logical(T.BeamformingApplied(1)), ...
        "DL raw trial table must disclose explicit beam-weight application.");
    assert(strlength(string(T.PrecoderSource(1))) > 0 && strlength(string(T.PrecodingMode(1))) > 0, ...
        "DL raw trial table must expose the applied precoder source and mode.");
    assert(strlength(string(T.AppliedBeamIndexSet(1))) > 0, ...
        "DL raw trial table must expose the applied beam index set when explicit precoding is active.");
    hasCodebookPMI = isfinite(double(T.AppliedPrecoderPMI(1))) && strlength(string(T.AppliedPrecoderPMIType(1))) > 0;
    hasExplicitMatrix = isfinite(double(T.PrecodingMatrixRows(1))) && double(T.PrecodingMatrixRows(1)) > 0 && ...
        isfinite(double(T.PrecodingMatrixCols(1))) && double(T.PrecodingMatrixCols(1)) > 0 && ...
        strlength(string(T.PrecoderSource(1))) > 0;
    assert(hasCodebookPMI || hasExplicitMatrix, ...
        "DL raw trial table must expose either codebook PMI lineage or explicit precoder matrix lineage when precoding is active.");
    assert(strcmpi(char(string(T.MCSAuthority(1))), "scheduler_grant") && strcmpi(char(string(T.ModulationAuthority(1))), "scheduler_grant"), ...
        "DL raw trial table must disclose scheduler-grant authority when the applied operating point comes from the grant.");
else
    assert(ismember("RequestedVsAppliedPrecoderPMIMatchStatus", string(T.Properties.VariableNames)), ...
        "UL raw trial table must expose requested-vs-applied PMI match status.");
    assert(~logical(T.ExplicitBeamWeightsApplied(1)), ...
        "UL raw trial table must not overclaim explicit beam-weight application.");
    assert(strcmpi(char(string(T.PrecoderSource(1))), "ul_pusch_native_codebook_tpmi") && ...
        strcmpi(char(string(T.AppliedPrecoderSource(1))), "ul_pusch_native_codebook_tpmi") && ...
        strcmpi(char(string(T.PrecodingMode(1))), "ul_codebook_tpmi"), ...
        "UL raw trial table must disclose the native PUSCH TPMI source used by the applied waveform precoder.");
    assert(logical(T.BeamformingApplied(1)) && ...
        isfinite(double(T.AppliedPrecoderPMI(1))) && ...
        strcmpi(char(string(T.AppliedPrecoderPMIType(1))), "pusch_codebook") && ...
        strlength(string(T.AppliedPrecoderCodebookMode(1))) > 0, ...
        "UL raw trial table must materialize the applied native PUSCH TPMI when the active UL waveform path uses it.");
    assert(strlength(string(T.RequestedBeamIndexSet(1))) > 0 && ...
        strlength(strtrim(string(T.AppliedBeamIndexSet(1)))) > 0 && ...
        strcmpi(char(string(T.RequestedBeamTruthClassification(1))), "requested_reference") && ...
        strcmpi(char(string(T.AppliedBeamTruthClassification(1))), "applied_runtime_value") && ...
        strcmpi(char(string(T.AppliedPrecoderPMITruthClassification(1))), "applied_runtime_value") && ...
        strcmpi(char(string(T.AppliedBeamApplicationSource(1))), "ul_pusch_native_codebook_tpmi_port_support") && ...
        strcmpi(char(string(T.AppliedPrecoderPMIApplicationSource(1))), "ul_pusch_native_codebook_tpmi") && ...
        strcmpi(char(string(T.RequestedVsAppliedPrecoderPMIMatchStatus(1))), "requested_matches_runtime_applied"), ...
        "UL raw trial table must separate requested beam references from runtime-applied native PUSCH TPMI and codebook port-support beam truth.");
    assert(strcmpi(char(string(T.MCSAuthority(1))), "scheduler_grant") && strcmpi(char(string(T.ModulationAuthority(1))), "scheduler_grant"), ...
        "UL raw trial table must disclose scheduler-grant authority when the applied operating point comes from the grant.");
end
end

function localAssertCFOValueLineage(T, direction)
availability = lower(strtrim(string(T.CFOEstimateAvailability(1))));
definition = lower(strtrim(string(T.CFOErrorDefinition(1))));
status = upper(strtrim(string(T.CFOValueStatus(1))));
cfoError = double(T.CFOError_Hz(1));
if availability == "missing" || status == "NOT_AVAILABLE"
    assert(availability == "missing" && definition == "not_available_without_cfo_estimate" && ...
        status == "NOT_AVAILABLE" && ~isfinite(cfoError), ...
        "Raw %s trial table must preserve missing-estimate CFO lineage instead of backfilling a fake error value.", direction);
else
    assert(availability == "available" && ...
        definition == "residual_post_correction_hz_relative_to_estimated_pre_correction" && ...
        any(status == ["OK","PARTIAL"]) && isfinite(cfoError), ...
        "Raw %s trial table must preserve explicit available-estimate CFO lineage and finite residual error.", direction);
end
end
