function ok = testPDSCHPhaseRunnerHonesty()
%TESTPDSCHPHASERUNNERHONESTY Guard measured, nonrecursive phase evidence.

observed = sixgr.pdsch.PDSCHPhaseArtifactPublisher.executionRow( ...
    "unit_stage", "unit_source", "unit_mode", ...
    ["PASS";"FAIL";"PASS"], 0.125, "observed fixture");
assert(observed.RecordCount == 3 ...
    && observed.PassedCount == 2 ...
    && observed.FailedCount == 1 ...
    && observed.DurationSeconds == 0.125 ...
    && observed.Status == "FAIL", ...
    "Execution accounting must derive counts/status from observed rows.");

passing = sixgr.pdsch.PDSCHPhaseArtifactPublisher.executionRow( ...
    "unit_stage", "unit_source", "unit_mode", true(4, 1), ...
    0.25, "observed fixture");
assert(passing.RecordCount == 4 ...
    && passing.PassedCount == 4 ...
    && passing.FailedCount == 0 ...
    && passing.DurationSeconds == 0.25 ...
    && passing.Status == "PASS", ...
    "Passing execution accounting is inconsistent.");
localAssertIdentifier(@() ...
    sixgr.pdsch.PDSCHPhaseArtifactPublisher.executionRow( ...
    "unit_stage", "unit_source", "unit_mode", ...
    ["PASS";"UNKNOWN"], 0.1), ...
    "sixgr:pdsch:PDSCHPhasePublisher:BadStatusValue");
localAssertIdentifier(@() ...
    sixgr.pdsch.PDSCHPhaseArtifactPublisher.executionRow( ...
    "unit_stage", "unit_source", "unit_mode", "PASS", NaN), ...
    "sixgr:pdsch:PDSCHPhasePublisher:BadDuration");

root = fileparts(fileparts(mfilename("fullpath")));
runnerSource = string(fileread(fullfile(root, ...
    "+sixgr", "+pdsch", "runPDSCHPhaseValidation.m")));
artifactTestSource = string(fileread(fullfile(root, ...
    "tests", "testPDSCHArtifactGeneration.m")));
publisherSource = string(fileread(fullfile(root, ...
    "+sixgr", "+pdsch", "PDSCHPhaseArtifactPublisher.m")));

assert(~contains(artifactTestSource, "runPDSCHPhaseValidation"), ...
    "Artifact-generation test must not recurse through the phase runner.");
assert(contains(runnerSource, ...
    "testPDSCHArtifactGeneration(stageDir, vectorRoot)"), ...
    "Runner must execute the real artifact validator on its stage.");
assert(contains(runnerSource, "recordValidation(assembly, artifactValidation)"), ...
    "Runner must record the observed artifact-test result.");
assert(~contains(runnerSource, "localCompleteArtifactSummary") ...
    && ~contains(runnerSource, "PassedCount = RecordCount") ...
    && ~contains(runnerSource, "DurationSeconds = zeros") ...
    && ~contains(runnerSource, '"Passed", true'), ...
    "Runner still contains an invented pass/count/duration path.");
assert(contains(publisherSource, ...
    "validateInventory(inventory, 19, 11") ...
    && contains(publisherSource, ...
    "validateInventory(inventory, 20, 11"), ...
    "Publisher must enforce the 19-to-20 CSV and 11-PNG contract.");

fprintf([ ...
    'PDSCH runner honesty: observed accounting passes; artifact test is ' ...
    'nonrecursive and runner records its real validator result.\n']);
ok = true;
end

function localAssertIdentifier(fn, expected)
try
    fn();
catch ME
    assert(string(ME.identifier) == string(expected), ...
        "Observed %s; expected %s.", ME.identifier, expected);
    return;
end
error("sixgr:test:ExpectedErrorNotThrown", ...
    "Expected typed error %s.", expected);
end
