function ok = testLLSRawTrialLifecycleTruth()
%TESTLLSRAWTRIALLIFECYCLETRUTH Keep row lifecycle tied to primary raw-truth fields.

setup6GRSimToolkit("Verbose", false);

[dlT, ulT] = localBuildFocusedTrialTables();
localAssertLifecycleTruth(dlT, "DL");
localAssertLifecycleTruth(ulT, "UL");

ok = true;
end

function [dlT, ulT] = localBuildFocusedTrialTables()
tmp = tempname;
mkdir(tmp);
c = onCleanup(@() rmdir(tmp, "s")); %#ok<NASGU>

scfg = sixgr.lls6g.config.loadScenarioConfig( ...
    fullfile(pwd, "simulator", "configs", "scenarios", "lls_700mhz_20mhz_3bs_30ue_tdlc_browser_coupled.yaml"));
cfg = sixgr.lls6g.buildInternalConfig(scfg, fullfile(tmp, "run"));
cfg.run.numFrames = 1;
cfg.channel.snr_dB = 10;
cfg.channel.model = "AWGN";
cfg.channel.awgnOnly = true;
cfg.run.noiseOperatingMode = "receiver_noise_figure_thermal_noise";
cfg.run.interferenceExecutionMode = "none";

multiUser = struct("Enabled", true, "NumUsers", 1, "RNTIStart", 320, "ExecutionModel", "slot_coupled_truth");
state = sixgr.truth.CoupledTruthRuntime.initialize(cfg, fullfile(tmp, "runtime"), multiUser, struct(), 1);
state.CurrentServingIdx(1) = 1;
state.CurrentServingMetric_dBm(1) = -70;
state.CurrentSlot = 1;
state.CurrentFrame = 1;
state.CurrentSNR_dB = 10;
state.LargeScaleState.BeamIndex(1,1) = 1;
state.LargeScaleState.BeamGain_dB(1,1) = 0;
state.LargeScaleState.RxPower_dBm(1,1) = -70;
state.LargeScaleState.BasePathloss_dB(1,1) = 100;
state.LargeScaleState.Pathloss_dB(1,1) = 100;
state.LargeScaleState.Shadow_dB(1,1) = 0;
state.LargeScaleState.O2I_dB(1,1) = 0;
[cfgDL, state] = sixgr.truth.CoupledTruthRuntime.applyUserContext(cfg, state, 1, "DL");
[cfgUL, state] = sixgr.truth.CoupledTruthRuntime.applyUserContext(cfg, state, 1, "UL");

grant = struct( ...
    "UEIndex", 1, ...
    "RNTI", 320, ...
    "ServingCell", 1, ...
    "CQIUsed", 7, ...
    "RIUsed", 1, ...
    "PMI", 0, ...
    "CRI", 0, ...
    "MCSTable", "qam64_table1", ...
    "CQITable", "table1", ...
    "AMCMode", "cqi_driven", ...
    "GrantReason", "lifecycle_truth_unit_test", ...
    "Frame", 1, ...
    "Slot", 1, ...
    "HARQ", struct(), ...
    "PBCHGatingActive", true, ...
    "PRACHGatingActive", true, ...
    "PDCCHGatingActive", true, ...
    "SRSGatingActive", true, ...
    "ControlEligible", true, ...
    "ControlDecodeOk", true, ...
    "GrantControlState", "control_ok", ...
    "CellAcquisitionState", "acquired", ...
    "AccessState", "succeeded", ...
    "SRSValidityState", "valid", ...
    "CSIValidityState", "fresh_runtime_srs", ...
    "SRSValid", true, ...
    "SRSAgeSlots", 0);

dl = sixgr.link.runDLPDSCHThroughput(cfgDL, ...
    "NumFrames", 1, ...
    "SNR_dB", 10, ...
    "GrantSnapshot", grant, ...
    "InterferenceBundle", struct([]));
ul = sixgr.link.runULPUSCHThroughput(cfgUL, ...
    "NumFrames", 1, ...
    "SNR_dB", 10, ...
    "GrantSnapshot", grant, ...
    "InterferenceBundle", struct([]));

dlT = dl.TrialTable;
ulT = ul.TrialTable;
end

function localAssertLifecycleTruth(T, direction)
assert(istable(T) && height(T) == 1, ...
    "Expected a single focused %s raw trial row.", direction);
requiredVars = { ...
    'CRCPass','BitsCompared','Goodput_Mbps','MCSIndex','Modulation','TargetCodeRate', ...
    'PrimaryTruthValueStatus','SecondaryFieldGapFlag','SecondaryFieldGapCount','SecondaryFieldGapReason', ...
    'LargeScaleSINRValueStatus','LargeScaleSINRFinalizedFlag','LargeScaleSINRNAReason', ...
    'RowLifecycleState','PartialRowFlag','FinalizedFlag','NAReason'};
assert(all(ismember(requiredVars, T.Properties.VariableNames)), ...
    "Raw %s trial table must expose lifecycle truth columns.", direction);
assert(logical(T.CRCPass(1)) && isfinite(double(T.BitsCompared(1))) && isfinite(double(T.Goodput_Mbps(1))), ...
    "Focused %s raw trial row must contain real decode outcome fields.", direction);
assert(strcmpi(string(T.PrimaryTruthValueStatus(1)), "OK"), ...
    "Focused %s raw trial row must classify primary runtime truth as OK.", direction);
assert(logical(T.FinalizedFlag(1)) && ~logical(T.PartialRowFlag(1)) && strcmpi(string(T.RowLifecycleState(1)), "finalized"), ...
    "Focused %s raw trial row must finalize when primary truth fields are present.", direction);
assert(strlength(string(T.NAReason(1))) == 0, ...
    "Focused %s finalized raw trial row must not carry a row-level NA reason.", direction);
assert(logical(T.SecondaryFieldGapFlag(1)) && double(T.SecondaryFieldGapCount(1)) >= 1, ...
    "Focused %s raw trial row must preserve secondary gap tracking separately from row finalization.", direction);
assert(contains(string(T.SecondaryFieldGapReason(1)), "large_scale_sinr_not_finalized"), ...
    "Focused %s raw trial row must disclose unresolved preview SINR as a secondary gap.", direction);
assert(strcmpi(string(T.LargeScaleSINRValueStatus(1)), "NOT_AVAILABLE") && ...
    ~logical(T.LargeScaleSINRFinalizedFlag(1)) && ...
    strcmpi(string(T.LargeScaleSINRNAReason(1)), "preview_source_present_value_not_finalized"), ...
    "Focused %s raw trial row must keep large-scale SINR in field-level NOT_AVAILABLE state without downgrading the whole row.", direction);
end
