function ok = testFrameStructureEngine()
%TESTFRAMESTRUCTUREENGINE Exercise the strict canonical compatibility facade.

setup6GRSimToolkit("Verbose", false);

cfg = localCarrierConfig();
cfg = sixgr.util.structSet(cfg, "phy.pdsch.startSymbol", 1);
cfg = sixgr.util.structSet(cfg, "phy.pdsch.numSymbols", 10);
fs = sixgr.phy.FrameStructureEngine(cfg);

assert(double(fs.NRB) == 273, ...
    "100 MHz / 30 kHz FR1 must resolve to the standard 273-RB grid.");
assert(double(fs.ConfiguredGridNumRBs) == 273, ...
    "Configured NSizeGrid is a strict consistency assertion.");
assert(double(fs.FFTSize) == 4096, ...
    "Toolbox-consistent 100 MHz / 30 kHz OFDM uses Nfft=4096.");
assert(double(fs.SampleRate_Hz) == 122880000, ...
    "The OFDM sample rate must be resolved by OFDMSamplingResolver.");
assert(contains(string(fs.ActiveGridSource), "38_104"), ...
    "The carrier grid must retain its pinned 3GPP source table.");
assert(~isprop(fs, "PDSCHStartSymbol") && ~isprop(fs, "PUSCHNumSymbols"), ...
    "The frame facade must not manufacture PDSCH or PUSCH allocations.");
assert(double(sixgr.util.structGet(fs.Config, ...
    "phy.pdsch.startSymbol", NaN)) == 1, ...
    "Explicit caller-owned PDSCH allocation must remain unchanged.");

assert(fs.TDDToken(0) == 'D' && fs.TDDToken(4) == 'U', ...
    "Canonical zero-based full-DL and full-UL slots must be preserved.");
partition = fs.SlotPartition(3);
assert(string(partition.SlotLabel) == "FLEXIBLE_OR_MIXED", ...
    "The partial slot must remain a canonical mixed/flexible slot.");
assert(isequal(double(partition.DLSymbolAllocation), [0 12]), ...
    "The configured partial slot must retain its twelve fixed DL symbols.");
assert(isequal(double(partition.ULSymbolAllocation), [13 1]), ...
    "The configured partial slot must retain its one fixed UL symbol.");
assert(isequal(double( ...
    partition.UnresolvedFlexibleSymbolIndices0Based), 12), ...
    "The intervening flexible symbol must remain unresolved.");
assert(fs.IsDLAllocation(3, [0 12]), ...
    "A fixed-DL allocation in the partial slot must be available.");
assert(fs.IsULAllocation(3, [13 1]), ...
    "A fixed-UL allocation in the partial slot must be available.");
assert(~fs.IsDLAllocation(3, [12 1]) && ...
       ~fs.IsULAllocation(3, [12 1]), ...
    "Unresolved flexible symbols cannot be silently assigned.");

snapshot = fs.toStruct();
attached = sixgr.util.structSet(cfg, "phy.frameStructure", snapshot);
fromSnapshot = sixgr.util.resolveTDDSlotPartition(attached, 3);
assert(isequal(fromSnapshot.CommonDirection, partition.CommonDirection) && ...
       isequal(fromSnapshot.ResolvedDirection, partition.ResolvedDirection), ...
    "The compatibility utility must consume the canonical attached state.");

badGrid = sixgr.util.structSet(cfg, "frequency.n_size_grid", 66);
localAssertThrows(@() sixgr.phy.FrameStructureEngine(badGrid), ...
    "sixgr:phy:frame:ConfiguredGridMismatch");

cfg50 = sixgr.util.structSet(cfg, "frequency.bandwidth_hz", 50e6);
cfg50 = sixgr.util.structSet(cfg50, "frequency.n_size_grid", 133);
fs50 = sixgr.phy.FrameStructureEngine(cfg50);
assert(double(fs50.NRB) == 133 && double(fs50.FFTSize) == 2048, ...
    "50 MHz / 30 kHz FR1 must resolve to 133 RB and Nfft=2048.");

cfg60 = sixgr.util.structSet(cfg, "frame.scs_khz", 60);
cfg60 = sixgr.util.structSet(cfg60, "frequency.n_size_grid", 135);
fs60 = sixgr.phy.FrameStructureEngine(cfg60);
assert(double(fs60.NRB) == 135 && double(fs60.Mu) == 2, ...
    "100 MHz / 60 kHz FR1 must resolve to 135 RB and mu=2.");
assert(abs(sixgr.time.slotDurationSec(60) - 0.25e-3) < eps, ...
    "slotDurationSec must delegate to the exact numerology catalog.");

missingCommon = rmfield(cfg.frame, "tdd_common");
missingCfg = cfg;
missingCfg.frame = missingCommon;
localAssertThrows(@() sixgr.phy.FrameStructureEngine(missingCfg), ...
    "sixgr:phy:frame:MissingTDDCommonConfig");

fdd = sixgr.util.structSet(cfg, "frequency.duplex_mode", "FDD");
fsFDD = sixgr.phy.FrameStructureEngine(fdd);
assert(fsFDD.DuplexMode == "FDD" && ...
       string(fsFDD.TDDPattern) == "not_applicable", ...
    "FDD must not be represented by a synthetic TDD pattern.");
localAssertThrows(@() fsFDD.TDDToken(0), ...
    "sixgr:phy:frame:FDDHasNoTDDToken");

ok = true;
end

function cfg = localCarrierConfig()
cfg = struct();
cfg = sixgr.util.structSet(cfg, "frequency.range_name", "FR1");
cfg = sixgr.util.structSet(cfg, ...
    "frequency.center_frequency_hz", 4e9);
cfg = sixgr.util.structSet(cfg, "frequency.bandwidth_hz", 100e6);
cfg = sixgr.util.structSet(cfg, "frequency.n_size_grid", 273);
cfg = sixgr.util.structSet(cfg, "frequency.n_start_grid", 0);
cfg = sixgr.util.structSet(cfg, "frequency.duplex_mode", "TDD");
cfg = sixgr.util.structSet(cfg, "frame.scs_khz", 30);
cfg = sixgr.util.structSet(cfg, "frame.cp_type", "normal");
cfg = sixgr.util.structSet(cfg, "frame.tdd_common", struct( ...
    "ReferenceSubcarrierSpacingKHz", 30, ...
    "Pattern1", struct( ...
        "PeriodicityMilliseconds", 2.5, ...
        "NumDownlinkSlots", 3, ...
        "NumDownlinkSymbols", 12, ...
        "NumUplinkSlots", 1, ...
        "NumUplinkSymbols", 1)));
end

function localAssertThrows(fcn, expectedId)
didThrow = false;
try
    fcn();
catch ME
    didThrow = true;
    assert(string(ME.identifier) == string(expectedId), ...
        "Expected %s but received %s: %s", ...
        string(expectedId), string(ME.identifier), string(ME.message));
end
assert(didThrow, "Expected error %s was not thrown.", string(expectedId));
end
