function ok = testSchedulerAMCNoFixedMCSFallback()
%TESTSCHEDULERAMCNOFIXEDMCSFALLBACK AMC must not promote configured MCS.

setup6GRSimToolkit("Verbose", false);

tmp = tempname;
mkdir(tmp);
c = onCleanup(@() rmdir(tmp, "s")); %#ok<NASGU>

scenarioPath = fullfile(pwd, "simulator", "configs", "scenarios", ...
    "lls_3gpp_rel20_anchor_4ghz_100mhz_waveform_honest_200ue_1frame.yaml");
scfg = sixgr.lls6g.config.loadScenarioConfig(scenarioPath);
cfg = sixgr.lls6g.buildInternalConfig(scfg, fullfile(tmp, "run"));
cfg = sixgr.util.structSet(cfg, "phy.linkAdaptation.mode", "amc");
cfg = sixgr.util.structSet(cfg, "phy.linkAdaptation.dlPolicy", "baseline");
cfg = sixgr.util.structSet(cfg, "phy.linkAdaptation.rankPolicy", "adaptive");
cfg = sixgr.util.structSet(cfg, "phy.pdsch.mcsIndex", 26);
% This is an isolated grant/waveform unit campaign without geometry and
% receiver-power context, so its SNR argument explicitly owns AWGN.
cfg = sixgr.util.structSet(cfg, "run.noiseOperatingMode", ...
    "standalone_awgn_snr_argument");
% This isolated scheduler fixture deliberately changes the canonical
% authority as well as compatibility aliases. Production code is
% runtime-authority-first; mutating only a stale legacy alias must not
% influence scheduling.
cfg = sixgr.util.structSet(cfg, "runtime.link_adaptation.Mode", "amc");
cfg = sixgr.util.structSet(cfg, "runtime.link_adaptation.DLPolicy", "baseline");
cfg = sixgr.util.structSet(cfg, "runtime.link_adaptation.RankPolicy", "adaptive");
cfg = sixgr.util.structSet(cfg, "runtime.link_adaptation.InitialMCSIndex", 1);
cfg = sixgr.util.structSet(cfg, "runtime.link_adaptation.MaximumMCSIndex", 31);
cfg = sixgr.util.structSet(cfg, "runtime.phy.dl.MCSIndex", 26);
cfg = sixgr.util.structSet(cfg, "phy.pdsch.mappingType", "A");
cfg = sixgr.util.structSet(cfg, "phy.pusch.mappingType", "A");
cfg = sixgr.util.structSet(cfg, "phy.pdsch.dmrs.portSet", 0);
cfg = sixgr.util.structSet(cfg, "phy.pdsch.dmrs.nPorts", 1);
cfg = sixgr.util.structSet(cfg, "phy.pdsch.executionProfile", "scheduler_truth");
cfg = sixgr.util.structSet(cfg, "run.pdschExecutionProfile", "scheduler_truth");
cfg = sixgr.util.structSet(cfg, "phy.pusch.executionProfile", "scheduler_truth");
cfg = sixgr.util.structSet(cfg, "run.puschExecutionProfile", "scheduler_truth");
cfg.phy.pdsch.UECapability1024QAM = false;
cfg.phy.pdsch.UECapability1024QAMVariant = "not_supported";
cfg.phy.pdsch.RRCEnabled1024QAM = false;
cfg.phy.pdsch.DCIEnabled1024QAM = false;
cfg.phy.pdsch.DeploymentAllows1024QAM = false;
cfg.phy.pdsch.FrequencyRangeAllows1024QAM = false;
cfg.phy.pdsch.BandAllows1024QAM = false;
cfg.phy.pdsch.FrequencyRange = "FR1";
cfg.phy.pdsch.OperatingBand = "n78";
cfg.phy.pdsch.DeploymentClass = "scheduler_amc_unit_fixture";

scheduler = sixgr.l2.mac.SchedulerPF(cfg, "Direction", "DL");
ue = struct("CQI", NaN, "RI", 1);
[~, layers, ~, amc] = scheduler.selectAMC(ue);

assert(strcmpi(char(string(amc.Mode)), "bootstrap_cqi_conservative"), ...
    "Missing-CQI AMC must be labeled as conservative bootstrap, not measured CQI-table AMC.");
assert(double(amc.MCSIndex) == 1, ...
    "Missing CQI in AMC mode must use the conservative live-bootstrap MCS, not configured MCS 26 or a zero-MCS sink.");
assert(strcmpi(char(string(amc.MCSSelectionSource)), "bootstrap_cqi_conservative_lab_default") && ...
    strcmpi(char(string(amc.MCSValueStatus)), "bootstrap_not_measured_cqi"), ...
    "Bootstrap AMC must disclose that the selected MCS is not measured CQI evidence.");
assert(double(layers) == 1, ...
    "Scheduler layers must respect the runtime RI when no measured multi-layer RI exists.");
planBootstrap = scheduler.buildNewDataGrantPlan( ...
    struct("RNTI", 44, "CQI", NaN, "RI", 1), 0:11, [0 14], 1000);
assert(planBootstrap.Valid && strcmpi(char(string(planBootstrap.AMCMode)), "bootstrap_cqi_conservative"), ...
    "Grant plans must preserve bootstrap AMC provenance for missing-CQI scheduling.");
assert(strcmpi(char(string(planBootstrap.MCSSelectionSource)), "bootstrap_cqi_conservative_lab_default") && ...
    strcmpi(char(string(planBootstrap.MCSValueStatus)), "bootstrap_not_measured_cqi"), ...
    "Grant plans must expose bootstrap MCS source/status for CSV and DB wiring.");

cfgMeasuredOnly = sixgr.util.structSet(cfg, "phy.linkAdaptation.bootstrapCQIMode", "require_measured_cqi");
measuredOnlyScheduler = sixgr.l2.mac.SchedulerPF(cfgMeasuredOnly, "Direction", "DL");
[~, ~, ~, amcBlocked] = measuredOnlyScheduler.selectAMC(struct("CQI", NaN, "RI", 1));
assert(strcmpi(char(string(amcBlocked.Mode)), "cqi_required_no_runtime_feedback") && ...
    strcmpi(char(string(amcBlocked.MCSValueStatus)), "unavailable_missing_runtime_cqi"), ...
    "Measured-only AMC mode must fail closed when no runtime CQI is available.");
planBlocked = measuredOnlyScheduler.buildNewDataGrantPlan( ...
    struct("RNTI", 45, "CQI", NaN, "RI", 1), 0:11, [0 14], 1000);
assert(~planBlocked.Valid && double(planBlocked.TBSBits) == 0 && ...
    strcmpi(char(string(planBlocked.GrantBlocker)), "blocked_until_runtime_cqi_feedback"), ...
    "Measured-only AMC must block new-data grants until runtime CQI feedback exists.");

ue.CQI = 3;
[~, ~, ~, amcCQI] = scheduler.selectAMC(ue);
assert(strcmpi(char(string(amcCQI.Mode)), "cqi_table") && ...
    strcmpi(char(string(amcCQI.MCSValueStatus)), "measured_cqi_mapped"), ...
    "Valid runtime CQI must stay labeled as CQI-table AMC.");
assert(double(amcCQI.MCSIndex) < 26, ...
    "CQI-driven AMC must not reuse the configured fixed MCS override.");
planCQI = scheduler.buildNewDataGrantPlan( ...
    struct("RNTI", 46, "CQI", 3, "RI", 1), 0:11, [0 14], 1000);
assert(planCQI.Valid && double(planCQI.CQIUsed) == 3 && ...
    double(planCQI.RawCQIDerivedMCS) == double(amcCQI.RawCQIDerivedMCS), ...
    "Grant plans must carry the direct CQI->MCS lineage used to choose the executable MCS.");

cfgBounded = sixgr.util.structSet(cfg, "runtime.link_adaptation.MaximumMCSIndex", 5);
cfgBounded = sixgr.util.structSet(cfgBounded, "phy.linkAdaptation.maximumMCSIndex", 5);
boundedScheduler = sixgr.l2.mac.SchedulerPF(cfgBounded, "Direction", "DL");
[boundedModulation, ~, boundedCodeRate, boundedAMC] = ...
    boundedScheduler.selectAMC(struct("CQI", 15, "RI", 1));
boundedProfile = sixgr.link.resolveMCSProfile(boundedScheduler.resolveMCSTable(), 5);
assert(double(boundedAMC.MCSIndex) == 5 && ...
    logical(boundedAMC.MaximumMCSBoundApplied) && ...
    contains(string(boundedAMC.MCSValueStatus), "clamped_to_yaml_maximum_mcs") && ...
    strcmpi(string(boundedModulation), string(boundedProfile.Modulation)) && ...
    abs(double(boundedCodeRate) - double(boundedProfile.TargetCodeRate)) < 1e-12, ...
    "Measured adaptive AMC must be physically re-resolved and clamped to the YAML maximum MCS.");

[~, ~, cqi4MCS] = sixgr.link.amcFromCQI(4, "", NaN, cfg, "DL");
badGrant = struct( ...
    "Direction", "DL", ...
    "RNTI", 9001, ...
    "Frame", 0, "Slot", 0, "ControlAbsoluteSlot", 0, ...
    "ScheduledAbsoluteSlot", 0, "HARQFeedbackAbsoluteSlot", 4, ...
    "ControlSymbolAllocation", [0 2], ...
    "HARQFeedbackSymbolAllocation", [0 2], ...
    "TimingAdvanceTicks", int64(0), "HARQProcessID", 0, ...
    "K0", 0, "K1", 4, ...
    "ExactPHYFeasibilityChecked", true, "ExactPHYFeasible", true, ...
    "DCI", struct("BitExactPDCCHPayload", true), ...
    "ControlDecodeOk", true, "DCICrcPass", true, ...
    "PDCCHPayloadMatch", true, "PDCCHCausalGrantDecodeOk", true, ...
    "PDCCHGrantBindingRequired", true, "PDCCHGrantBindingOk", true, ...
    "GrantValid", true, ...
    "PDCCHGrantDCIId", "unit-dci-dl", ...
    "PDCCHGrantDCIFieldsHash", "unit-hash-dl", ...
    "PDCCHGrantFieldsHash", "unit-hash-dl", ...
    "PRBSet", 0:15, ...
    "SymbolAllocation", [2 12], ...
    "NumLayers", 1, ...
    "Layers", 1, ...
    "MCSIndex", 13, ...
    "MCS", 13, ...
    "Modulation", "16QAM", ...
    "TargetCodeRate", 658/1024, ...
    "TBSBits", 0, ...
    "TBSBytes", 0, ...
    "MCSTable", scheduler.resolveMCSTable(), ...
    "CQITable", scheduler.resolveCQITable());
badFeedback = struct("Valid", true, "CQI", 4, "RI", 1, "PMI", NaN, "CRI", NaN, ...
    "SINR_dB", 18, "MCSIndex", 13, "TargetCodeRate", 658/1024, "Modulation", "16QAM", ...
    "RawCQIDerivedMCS", 13, "MCSSelectionSource", "runtime_link_adaptation_decision", ...
    "MCSValueStatus", "measured_feedback_adapted");
cfgFixed = sixgr.util.structSet(cfg, "runtime.link_adaptation.Mode", "fixed");
cfgFixed = sixgr.util.structSet(cfgFixed, "runtime.link_adaptation.DLPolicy", "fixed");
cfgFixed = sixgr.util.structSet(cfgFixed, "phy.linkAdaptation.mode", "fixed");
cfgFixed = sixgr.util.structSet(cfgFixed, "phy.linkAdaptation.dlPolicy", "fixed");
fixedInput = badGrant;
fixedInput.MCSIndex = 4;
fixedInput.MCS = 4;
fixedInput.Modulation = "QPSK";
fixedInput.TargetCodeRate = 308/1024;
fixedInput.AMCMode = "fixed_mcs";
fixedInput.MCSIndexAuthority = "configured_fixed_mcs";
fixedInput.GrantOperatingPointSource = "configured_fixed_mcs";
fixedOutput = sixgr.truth.CoupledTruthRuntime. ...
    realignGrantAMCFromMeasuredFeedbackRuntime( ...
    fixedInput, badFeedback, scheduler, cfgFixed, "DL");
assert(isequaln(fixedOutput, fixedInput), ...
    "Valid measured CQI must remain measurement evidence and must not mutate a YAML-fixed DL grant.");
fixedMultiUser = struct("Enabled", true, "NumUsers", 1, "RNTIStart", 9101, ...
    "SeedStride", 17, "ExecutionModel", "slot_coupled_truth");
fixedState = sixgr.truth.CoupledTruthRuntime.initialize( ...
    cfgFixed, fullfile(tmp, "fixed_scheduler_state"), fixedMultiUser, struct(), 1);
fixedState.CurrentServingIdx(:) = 1;
fixedState.CurrentServingMetric_dBm(:) = -70;
fixedState.CurrentSlot = 5;
fixedState.CurrentFrame = 1;
fixedState.DLQueueBits(:) = 1e6;
fixedState.LatestDLFeedback(1).Valid = true;
fixedState.LatestDLFeedback(1).CQI = 13;
fixedState.LatestDLFeedback(1).MCSIndex = 24;
fixedState.LatestDLFeedback(1).Modulation = "64QAM";
fixedState.LatestDLFeedback(1).TargetCodeRate = 772/1024;
fixedState.LatestDLFeedback(1).MCSSelectionSource = "runtime_cqi_table_raw";
[~, fixedUEState] = sixgr.truth.CoupledTruthRuntime. ...
    buildSchedulerUEStateRuntime(fixedState, cfgFixed, 1, "DL", 1);
assert(isnan(double(fixedUEState.MCSIndex)) && ...
    double(fixedUEState.FeedbackMCSIndex) == 24 && ...
    string(fixedUEState.MCSIndexAuthority) == "configured_fixed_default" && ...
    strlength(strtrim(string(fixedUEState.Modulation))) == 0 && ...
    isnan(double(fixedUEState.TargetCodeRate)), ...
    "Coupled scheduler state must retain CQI-derived MCS only as feedback evidence in fixed mode.");
fixedScheduler = sixgr.l2.mac.SchedulerPF(cfgFixed, "Direction", "DL");
[fixedMod, ~, fixedRate, fixedAMC] = fixedScheduler.selectAMC(fixedUEState);
configuredFixedMCS = double(sixgr.util.structGet( ...
    cfgFixed, "runtime.phy.dl.MCSIndex", cfgFixed.phy.pdsch.mcsIndex));
configuredFixedProfile = sixgr.link.resolveMCSProfile( ...
    fixedScheduler.resolveMCSTable(), configuredFixedMCS);
assert(string(fixedAMC.Mode) == "fixed_mcs" && ...
    double(fixedAMC.MCSIndex) == configuredFixedMCS && ...
    string(fixedMod) == string(configuredFixedProfile.Modulation) && ...
    abs(double(fixedRate) - double(configuredFixedProfile.TargetCodeRate)) < 1e-12, ...
    "SchedulerBase must consume configured fixed-MCS authority after measured CSI arrives.");
fixedGrant = sixgr.truth.CoupledTruthRuntime.realignGrantAMCFromMeasuredFeedbackRuntime( ...
    badGrant, badFeedback, scheduler, cfg, "DL");
assert(double(fixedGrant.CQIUsed) == 4 && double(fixedGrant.RawCQIDerivedMCS) == double(cqi4MCS), ...
    "Final grant AMC realignment must recompute RawCQIDerivedMCS from CQIUsed, not preserve stale feedback metadata.");
assert(double(fixedGrant.MCSIndex) <= double(cqi4MCS) && ...
    strcmpi(char(string(fixedGrant.MCSValueStatus)), "clamped_to_cqi_max"), ...
    "Final CQI-table grant MCS must be clamped to the configured CQI-derived MCS ceiling.");
boundedFeedback = badFeedback;
boundedFeedback.CQI = 15;
boundedFeedback.MCSIndex = 13;
boundedFeedback.RawCQIDerivedMCS = 13;
boundedGrant = sixgr.truth.CoupledTruthRuntime.realignGrantAMCFromMeasuredFeedbackRuntime( ...
    badGrant, boundedFeedback, boundedScheduler, cfgBounded, "DL");
assert(double(boundedGrant.MCSIndex) == 5 && ...
    logical(boundedGrant.MaximumMCSBoundApplied) && ...
    double(boundedGrant.ConfiguredMaximumMCSIndex) == 5 && ...
    contains(string(boundedGrant.MCSValueStatus), "clamped_to_yaml_maximum_mcs"), ...
    "Post-feedback grant realignment must enforce the same YAML maximum MCS as initial scheduling.");
frozenMod = string(sixgr.util.structGet(fixedGrant, "PHYGrant.CodingLayout.Modulation", ""));
assert(strlength(strtrim(frozenMod)) > 0 && strcmpi(char(frozenMod), char(string(fixedGrant.Modulation))), ...
    "Measured-feedback AMC realignment must re-freeze PHYGrant so TX cannot see stale coding-layout modulation. " + ...
    "Frozen='%s', runtime='%s', blocker='%s'.", frozenMod, string(fixedGrant.Modulation), ...
    string(sixgr.util.structGet(fixedGrant, "GrantBlocker", "")));
staleGrant = fixedGrant;
stalePDSCH = nrPDSCHConfig;
stalePDSCH.PRBSet = double(staleGrant.PRBSet);
stalePDSCH.SymbolAllocation = double(staleGrant.SymbolAllocation);
stalePDSCH.NumLayers = double(staleGrant.NumLayers);
stalePDSCH.RNTI = double(sixgr.util.structGet(staleGrant, "RNTI", 1));
if strcmpi(char(string(fixedGrant.Modulation)), "64QAM")
    stalePDSCH.Modulation = "QPSK";
else
    stalePDSCH.Modulation = "64QAM";
end
staleGrant.PDSCHConfig = stalePDSCH;
rngState = rng;
restoreRng = onCleanup(@() rng(rngState)); %#ok<NASGU>
staleReplay = sixgr.link.runDLPDSCHThroughput(cfg, ...
    "NumFrames", 1, ...
    "SNR_dB", 24, ...
    "GrantSnapshot", staleGrant, ...
    "InterferenceBundle", struct([]));
clear restoreRng
assert(isstruct(staleReplay) && isfield(staleReplay, "TrialTable") && height(staleReplay.TrialTable) == 1, ...
    "DL frozen-grant replay must ignore stale legacy PDSCHConfig objects instead of crashing on modulation mismatch.");

cfg = sixgr.util.structSet(cfg, "phy.linkAdaptation.outerLoopFlag", true);
cfg = sixgr.util.structSet(cfg, "phy.linkAdaptation.deltaMCSPolicy", "olla");
cfg = sixgr.util.structSet(cfg, "phy.linkAdaptation.ollaStepUp", 0.2);
cfg = sixgr.util.structSet(cfg, "phy.linkAdaptation.ollaStepDown", 1.0);
cfg = sixgr.util.structSet(cfg, "phy.linkAdaptation.deltaMCSMin", -6);
cfg = sixgr.util.structSet(cfg, "phy.linkAdaptation.deltaMCSMax", 6);
cfg = sixgr.util.structSet(cfg, "phy.pusch.nLayers", 2);
cfg = sixgr.util.structSet(cfg, "phy.pusch.numLayers", 2);
cfg = sixgr.util.structSet(cfg, "phy.pusch.maxLayers", 2);
cfg = sixgr.util.structSet(cfg, "phy.pusch.dmrs.nPorts", 2);
cfg = sixgr.util.structSet(cfg, "phy.pusch.dmrs.portSet", [0 1]);
cfg = sixgr.util.structSet(cfg, "phy.pusch.transformPrecoding", false);
cfg = sixgr.util.structSet(cfg, "runtime.phy.ul.NumLayers", 2);
cfg = sixgr.util.structSet(cfg, "runtime.phy.ul.NumLogicalPorts", 2);
ollaScheduler = sixgr.l2.mac.SchedulerPF(cfg, "Direction", "DL");
ueOLLA = struct("RNTI", 9001, "CQI", 12, "RI", 1);
[~, ~, ~, amcBeforeNack] = ollaScheduler.selectAMC(ueOLLA);
ollaScheduler.updateAfterRx(struct("RNTI", 9001, "TBSBits", 2048, "Ack", false));
[~, ~, ~, amcAfterNack] = ollaScheduler.selectAMC(ueOLLA);
assert(logical(amcAfterNack.OuterLoopApplied) && double(amcAfterNack.OLLAUpdateCount) >= 1, ...
    "Scheduler OLLA must be applied only after ACK/NACK feedback updates the per-UE loop state.");
assert(double(amcAfterNack.MCSIndex) < double(amcBeforeNack.MCSIndex), ...
    "A scheduler-side NACK must reduce the next CQI-table MCS through the OLLA delta.");
[deltaBeforeRetxAck, countBeforeRetxAck] = ollaScheduler.getOLLAMCSDelta(9001);
ollaScheduler.updateAfterRx(struct( ...
    "RNTI", 9001, "TBSBits", 2048, "Ack", true, ...
    "RV", 2, "IsRetransmission", true));
[deltaAfterRetxAck, countAfterRetxAck] = ollaScheduler.getOLLAMCSDelta(9001);
assert(abs(double(deltaAfterRetxAck) - double(deltaBeforeRetxAck)) < 1e-12 && ...
    double(countAfterRetxAck) == double(countBeforeRetxAck), ...
    "HARQ retransmission ACK must not relax the first-transmission OLLA backoff.");
ollaScheduler.updateAfterRx(struct( ...
    "RNTI", 9001, "TBSBits", 2048, "Ack", true, ...
    "RV", 0, "IsRetransmission", false));
[deltaAfterNewDataAck, countAfterNewDataAck] = ollaScheduler.getOLLAMCSDelta(9001);
assert(double(deltaAfterNewDataAck) > double(deltaAfterRetxAck) && ...
    double(countAfterNewDataAck) == double(countAfterRetxAck) + 1, ...
    "A new-data RV0 ACK must still update the first-transmission OLLA loop.");

ulScheduler = sixgr.l2.mac.SchedulerPF(cfg, "Direction", "UL");
grant = struct( ...
    "RNTI", 9001, ...
    "Direction", "UL", ...
    "Frame", 0, "Slot", 4, "ControlAbsoluteSlot", 3, ...
    "ScheduledAbsoluteSlot", 4, "HARQFeedbackAbsoluteSlot", 8, ...
    "ControlSymbolAllocation", [0 2], ...
    "HARQFeedbackSymbolAllocation", [0 2], ...
    "TimingAdvanceTicks", int64(0), "HARQProcessID", 0, ...
    "K2", 1, "K1", 4, ...
    "ExactPHYFeasibilityChecked", true, "ExactPHYFeasible", true, ...
    "DCI", struct("BitExactPDCCHPayload", true), ...
    "ControlDecodeOk", true, "DCICrcPass", true, ...
    "PDCCHPayloadMatch", true, "PDCCHCausalGrantDecodeOk", true, ...
    "PDCCHGrantBindingRequired", true, "PDCCHGrantBindingOk", true, ...
    "GrantValid", true, ...
    "PDCCHGrantDCIId", "unit-dci-ul", ...
    "PDCCHGrantDCIFieldsHash", "unit-hash-ul", ...
    "PDCCHGrantFieldsHash", "unit-hash-ul", ...
    "PRBSet", 0:23, ...
    "SymbolAllocation", [0 14], ...
    "NumLayers", 1, ...
    "Layers", 1, ...
    "MCSIndex", 0, ...
    "MCS", 0, ...
    "Modulation", "QPSK", ...
    "TargetCodeRate", 78/1024, ...
    "TBSBits", 0, ...
    "TBSBytes", 0, ...
    "MCSTable", ulScheduler.resolveMCSTable(), ...
    "CQITable", ulScheduler.resolveCQITable());
[bootstrapTBSBits, ~] = ulScheduler.estimateTBS("QPSK", 1, numel(grant.PRBSet), grant.SymbolAllocation, 78/1024, ...
    "ForceExact", true);
feedback = struct("Valid", true, "CQI", 12, "RI", 1, "PMI", NaN, "CRI", NaN, ...
    "SINR_dB", 24, "MCSIndex", NaN, "TargetCodeRate", NaN, "Modulation", "");
feedback.CSIAgingModel = "per_subband_layer_jakes_measured_csi";
feedback.SubbandSINRVector_dB = "24|21|18";
feedback.AgedSubbandSINRVector_dB = "24|19|15";
feedback.PostEqSINRPerLayer_dB = "24";
feedback.AgedPostEqSINRPerLayer_dB = "24";
feedback.SubbandAgingPenaltyVector_dB = "0|2|3";
feedback.LayerAgingPenaltyVector_dB = "0";
grantCQI = sixgr.truth.CoupledTruthRuntime.realignGrantAMCFromMeasuredFeedbackRuntime( ...
    grant, feedback, ulScheduler, cfg, "UL");

assert(double(grantCQI.CQIUsed) == 12, ...
    "Measured feedback CQI must be consumed by the final grant, not only exported later.");
assert(double(grantCQI.MCSIndex) > 0, ...
    "Measured CQI feedback must update the actual UL grant MCS before PHY execution.");
assert(double(grantCQI.TBSBits) > double(bootstrapTBSBits), ...
    "Measured CQI feedback must update the actual UL grant TBS before PHY execution.");
assert(strcmpi(char(string(grantCQI.CSIAgingModel)), "per_subband_layer_jakes_measured_csi") && ...
    strlength(string(grantCQI.AgedSubbandSINRVector_dB)) > 0, ...
    "Executable grant must retain aged measured CSI metadata consumed by AMC.");
frozenULMod = string(sixgr.util.structGet(grantCQI, "PHYGrant.CodingLayout.Modulation", ""));
assert(strlength(strtrim(frozenULMod)) > 0 && strcmpi(char(frozenULMod), char(string(grantCQI.Modulation))), ...
    "Measured-feedback UL AMC realignment must re-freeze PHYGrant so TX cannot see stale coding-layout modulation. " + ...
    "Frozen='%s', runtime='%s', blocker='%s'.", frozenULMod, string(grantCQI.Modulation), ...
    string(sixgr.util.structGet(grantCQI, "GrantBlocker", "")));
staleULGrant = grantCQI;
stalePUSCH = nrPUSCHConfig;
stalePUSCH.PRBSet = double(staleULGrant.PRBSet);
stalePUSCH.SymbolAllocation = double(staleULGrant.SymbolAllocation);
stalePUSCH.NumLayers = double(staleULGrant.NumLayers);
stalePUSCH.RNTI = double(sixgr.util.structGet(staleULGrant, "RNTI", 1));
stalePUSCH.NumAntennaPorts = max(1, double(sixgr.util.structGet(staleULGrant, "NumPorts", staleULGrant.NumLayers)));
if strcmpi(char(string(staleULGrant.Modulation)), "16QAM")
    stalePUSCH.Modulation = "QPSK";
else
    stalePUSCH.Modulation = "16QAM";
end
staleULGrant.PUSCHConfig = stalePUSCH;
rngStateUL = rng;
restoreRngUL = onCleanup(@() rng(rngStateUL)); %#ok<NASGU>
cfgULRank1 = sixgr.util.structSet(cfg, "phy.pusch.dmrs.portSet", 0);
cfgULRank1 = sixgr.util.structSet(cfgULRank1, "phy.pusch.dmrs.nPorts", 1);
cfgULRank1 = sixgr.util.structSet(cfgULRank1, "phy.pusch.nLayers", 1);
cfgULRank1 = sixgr.util.structSet(cfgULRank1, "phy.pusch.numLayers", 1);
staleULReplay = sixgr.link.runULPUSCHThroughput(cfgULRank1, ...
    "NumFrames", 1, ...
    "SNR_dB", 24, ...
    "GrantSnapshot", staleULGrant, ...
    "InterferenceBundle", struct([]));
clear restoreRngUL
assert(isstruct(staleULReplay) && isfield(staleULReplay, "TrialTable") && height(staleULReplay.TrialTable) == 1, ...
    "UL frozen-grant replay must ignore stale legacy PUSCHConfig objects instead of crashing on modulation mismatch.");

feedbackRank2 = feedback;
feedbackRank2.RI = 2;
grantRank2 = sixgr.truth.CoupledTruthRuntime.realignGrantAMCFromMeasuredFeedbackRuntime( ...
    grant, feedbackRank2, ulScheduler, cfg, "UL");
assert(double(grantRank2.RIUsed) == 1 && double(grantRank2.Rank) == 1 && ...
    double(grantRank2.NumLayers) == 1 && double(grantRank2.Layers) == 1 && ...
    string(grantRank2.RankAuthority) == "finalized_grant_spatial_contract" && ...
    string(grantRank2.RankDecisionReason) == "measured_ri_deferred_to_future_grant", ...
    "Measured RI must not mutate an already finalized grant's immutable spatial contract.");
assert(double(grantRank2.TBSBits) == double(grantCQI.TBSBits), ...
    "A deferred RI update must preserve finalized TBS; rank-2 applies only to a future grant.");

ok = true;
end
