function ok = testFrozenHybridArchitectureGuards()
%TESTFROZENHYBRIDARCHITECTUREGUARDS Typed stale/frozen matrix failures.

setup6GRSimToolkit("Verbose", false);

cfgStale = sixgr.config.defaultConfig();
cfgStale.phy.pdsch.precoding.matrix = zeros(64, 1);
pdsch = struct("NumLayers", 2);
localAssertTypedError(@() sixgr.phy.dl.resolvePDSCHPrecoding(pdsch, cfgStale), ...
    "sixgr:phy:dl:PDSCHPrecoding:StaleExplicitMatrixContext");

cfgHybrid = sixgr.config.defaultConfig();
cfgHybrid.scenario.bs.nTxAnt = 64;
cfgHybrid.scenario.ue.nRxAnt = 4;
cfgHybrid.antenna.bs.numElements = 64;
cfgHybrid.antenna.ue.numElements = 4;
cfgHybrid.antenna.bs.numRFChains = 2;
cfgHybrid.rf.bs.numRFChains = 2;
cfgHybrid.phy.nTxAnt = 64;
cfgHybrid.phy.nRxAnt = 4;
cfgHybrid.channel.nTxAnt = 64;
cfgHybrid.channel.nRxAnt = 4;
cfgHybrid.phy.pdsch.numLayers = 2;
cfgHybrid.phy.pdsch.nLayers = 2;
cfgHybrid.phy.pdsch.numPorts = 2;
cfgHybrid.phy.pdsch.nPorts = 2;
cfgHybrid.phy.pdsch.precoding.matrix = eye(2);
cfgHybrid.phy.pdsch.precodingMatrix = eye(2);
cfgHybrid.phy.pdsch.W = eye(2);
cfgHybrid.phy.beamManagement.hybridBeamformingEnabled = true;
cfgHybrid.mimo.strict = true;

arch = sixgr.rf.AntennaArrayFactory.resolvePortArchitecture(cfgHybrid, "bs", ...
    "Signal", "PDSCH", "NumElements", 64, "NumPorts", 2, ...
    "NumRFChains", 2, "MinimumPorts", 2);
frozenArchitecture = double(arch.HybridElementToPortMatrix);
frozenArchitecture(1, 1) = frozenArchitecture(1, 1) + 1e-3;

grant = struct( ...
    "Direction", "DL", ...
    "Frame", 0, ...
    "Slot", 0, ...
    "RNTI", 101, ...
    "UEIndex", 1, ...
    "ServingCell", 1, ...
    "PRBSet", 0:5, ...
    "SymbolAllocation", [2 10], ...
    "Modulation", "QPSK", ...
    "NumLayers", 2, ...
    "Layers", 2, ...
    "NumLogicalPorts", 2, ...
    "NumRFChains", 2, ...
    "TargetCodeRate", 0.587890625, ...
    "MCSIndex", 4, ...
    "PrecodingMatrixLogicalPorts", eye(2), ...
    "PrecodingMatrix", frozenArchitecture, ...
    "HybridElementToPortMatrix", frozenArchitecture);
localAssertTypedError(@() sixgr.phy.grant.freezePHYGrant( ...
    cfgHybrid, "DL", grant, "SNR_dB", 20, "Frame", 0, "Slot", 0), ...
    "sixgr:phy:grant:FrozenHybridArchitectureMismatch");

aliasGrant = struct("Direction", "DL", "NumLayers", 2, "Layers", 1);
localAssertTypedError(@() sixgr.phy.grant.resolveGrantSpatialContract(aliasGrant), ...
    "sixgr:phy:grant:GrantSpatialAliasMismatch");

retxGrant = struct("Direction", "DL", "NumLayers", 2, "Layers", 2, "IsRetransmission", true);
tbContext = struct("OriginalNumLayers", 1);
localAssertTypedError(@() sixgr.phy.grant.resolveGrantSpatialContract(retxGrant, ...
    "TBContext", tbContext, "RequireTBContextMatch", true), ...
    "sixgr:phy:grant:HARQSpatialContractMismatch");

cfgHybrid.phy.csirs.enable = true;
cfgHybrid.phy.csirs.nPorts = 4;
cfgHybrid.phy.csirs.numPorts = 4;
validGrant = grant;
validGrant.PrecodingMatrix = arch.HybridElementToPortMatrix;
validGrant.HybridElementToPortMatrix = arch.HybridElementToPortMatrix;
phyGrant = sixgr.phy.grant.freezePHYGrant( ...
    cfgHybrid, "DL", validGrant, "SNR_dB", 20, "Frame", 0, "Slot", 0);
frozenReplayGrant = validGrant;
frozenReplayGrant.PHYGrant = phyGrant;
assert(isempty(sixgr.truth.selectGrantReplayPDSCHPrecodingMatrix(frozenReplayGrant)), ...
    "A frozen hybrid PHYGrant must suppress the physical-matrix Tx override to avoid double element-domain expansion.");
nonFrozenReplayGrant = rmfield(frozenReplayGrant, "PHYGrant");
nonFrozenReplayGrant.PrecodingMatrixLogicalPorts = eye(2);
assert(isequal(sixgr.truth.selectGrantReplayPDSCHPrecodingMatrix(nonFrozenReplayGrant), eye(2)), ...
    "A non-frozen replay must prefer the logical-port matrix over the element-domain matrix.");
projectedCfg = sixgr.phy.grant.applyPHYGrantToConfig(cfgHybrid, phyGrant);
assert(double(projectedCfg.phy.csirs.nPorts) == 4 && ...
    double(projectedCfg.phy.csirs.numPorts) == 4, ...
    "Applying a PDSCH PHYGrant must preserve the independently configured CSI-RS logical-port count.");

logicalMatrix = [1 0.25; 0.4 1];
physicalMatrix = double(arch.HybridElementToPortMatrix) * logicalMatrix;
jobGrant = validGrant;
jobGrant.PrecodingMatrixLogicalPorts = logicalMatrix;
jobGrant.PrecodingMatrix = physicalMatrix;
jobGrant.DCI = struct("Bits", int8(0));
trialContext = struct("GrantSnapshot", jobGrant, "HARQContext", struct());
job = sixgr.truth.buildGrantPHYJob(cfgHybrid, "DL", 20, 1, struct(), trialContext);
assert(isequal(job.GrantSnapshot.PrecodingMatrix, physicalMatrix), ...
    "Grant-job construction must not renormalize the frozen element-domain precoder.");
assert(norm(job.GrantSnapshot.PrecodingMatrix - ...
    double(arch.HybridElementToPortMatrix) * logicalMatrix, "fro") <= 1e-12, ...
    "Grant-job physical and logical precoders must remain in the exact frozen hybrid subspace.");

ok = true;
end

function localAssertTypedError(fn, expectedIdentifier)
try
    fn();
catch ME
    assert(strcmp(ME.identifier, expectedIdentifier), ...
        "Expected typed error '%s'; observed '%s': %s", ...
        expectedIdentifier, ME.identifier, ME.message);
    assert(~strcmp(ME.identifier, "MATLAB:error:badMessageArgument"), ...
        "Typed guard was masked by an invalid MATLAB error message argument.");
    return;
end
error("testFrozenHybridArchitectureGuards:MissingExpectedError", ...
    "Expected typed error '%s' was not raised.", expectedIdentifier);
end
