function ok = testConformanceFRC(varargin)
%TESTCONFORMANCEFRC Run the standards-anchored mandatory NR FRC gate.
%
%   testConformanceFRC() runs the real complete-waveform truth-chain gate.
%   It does not use LUT, logistic, fast-proxy, synthetic, or fallback rows.
%
%   testConformanceFRC("Profile","contract-only") intentionally limits the
%   test to catalog anchors plus exact Tx TBS/G setup validation. This
%   profile never reports a conformance point as passed. The same explicit
%   opt-in is available to constrained CI jobs through:
%
%       SIXGR_FRC_TEST_PROFILE=contract-only
%
%   With no explicit profile the real gate is mandatory. testAll invokes
%   testConformanceFRCContract instead so the ordinary regression suite
%   remains bounded. A setup-only, statistically unqualified, or incomplete
%   selected data-channel reproduction can never satisfy the real gate.

setup6GRSimToolkit("Verbose", false, "RunToolboxChecks", false);
opt = localParseOptions(varargin{:});

catalog = sixgr.conformance.frcCatalog();
localAssertCatalogAnchors(catalog);
mandatory = localMandatoryCases();

[preflight, preflightDiagnostics] = localPreflight(mandatory);
emptyReport = localReportFromPreflight(mandatory, preflight);

if opt.Profile == "contract-only"
    disp(emptyReport);
    setupFailures = ~reshape([preflight.SetupPass], [], 1);
    if any(setupFailures)
        localThrowFailure("sixgr:tests:ConformanceFRCContractFailed", ...
            "FRC contract-only setup validation failed.", ...
            preflightDiagnostics(setupFailures));
    end
    fprintf(1, [ ...
        'FRC contract-only profile completed: catalog and Tx TBS/G setup ' ...
        'contracts passed. No conformance, normative, statistical, or ' ...
        'symmetric +/-%.1f dB pass is asserted.\n'], opt.Tolerance_dB);
    ok = true;
    return;
end

preflightFailures = ~reshape([preflight.SetupPass], [], 1) | ...
    ~reshape([preflight.DataChannelExact], [], 1) | ...
    ~reshape([preflight.FullWaveformExact], [], 1);
if any(preflightFailures)
    disp(emptyReport);
    localThrowFailure("sixgr:tests:ConformanceFRCDataChannelExecutionBlocked", ...
        ["The real FRC gate did not start Monte Carlo because at least one " ...
        "mandatory complete-waveform point cannot yet be reproduced exactly. " ...
        "Every printed 'pass' value is therefore false."], ...
        preflightDiagnostics(preflightFailures));
end

numCases = height(mandatory);
results = cell(numCases, 1);
runDiagnostics = strings(numCases, 1);
for index = 1:numCases
    try
        results{index} = sixgr.conformance.runFRCPoint( ...
            mandatory.EntryId(index), mandatory.Condition(index), ...
            "ExecutionProfile", "full", ...
            "Tolerance_dB", opt.Tolerance_dB, ...
            "RequireExactStandardExecution", true, ...
            "RequireExactDataChannelExecution", true, ...
            "AssertPass", false, ...
            "PrintTable", false, ...
            "Verbose", opt.Verbose);
    catch cause
        runDiagnostics(index) = sprintf( ...
            "%s | %s: %s (%s)", ...
            mandatory.FRC(index), mandatory.Condition(index), ...
            string(cause.message), string(cause.identifier));
    end
end

[report, gatePass, resultDiagnostics] = ...
    localConsolidateResults(mandatory, results, runDiagnostics);
disp(report);

if any(~gatePass)
    localThrowFailure("sixgr:tests:ConformanceFRCGateFailed", ...
        ["Mandatory complete-waveform FRC reference gate failed. The standard " ...
        "defines a one-sided operating-point requirement; the +/-%.1f dB " ...
        "crossing is a separate, nonnormative simulator-regression gate. " ...
        "Measured and required deltas are listed below."], ...
        resultDiagnostics(~gatePass), opt.Tolerance_dB);
end

ok = true;
end

function opt = localParseOptions(varargin)
ip = inputParser;
ip.FunctionName = "testConformanceFRC";
ip.addParameter("Profile", "", @localTextScalar);
ip.addParameter("Tolerance_dB", 1.0, ...
    @(v) isnumeric(v) && isreal(v) && isscalar(v) && isfinite(v) && v > 0);
ip.addParameter("Verbose", true, @localLogicalScalar);
ip.parse(varargin{:});
opt = ip.Results;

profile = strtrim(lower(string(opt.Profile)));
if strlength(profile) == 0
    profile = strtrim(lower(string(getenv("SIXGR_FRC_TEST_PROFILE"))));
end
if strlength(profile) == 0
    profile = "gate";
end
profile = replace(profile, "_", "-");
if ~any(profile == ["gate", "contract-only"])
    error("sixgr:tests:InvalidConformanceFRCProfile", ...
        ["FRC test profile must be 'gate' or the explicit " ...
        "'contract-only' opt-in, not '%s'."], profile);
end
opt.Profile = profile;
opt.Tolerance_dB = double(opt.Tolerance_dB);
opt.Verbose = logical(opt.Verbose);
end

function mandatory = localMandatoryCases()
mandatory = table();
mandatory.EntryId = [ ...
    "dl_r_pdsch_1_1_4_fdd_awgn"; ...
    "dl_r_pdsch_1_3_6_fdd_atg_awgn"; ...
    "dl_r_pdsch_1_4_1_fdd_atg_awgn"; ...
    "ul_g_fr1_a3a_1_awgn"; ...
    "ul_g_fr1_a13_1_atg_awgn"; ...
    "dl_r_pdsch_1_1_1_fdd_tdlb100_400"; ...
    "ul_g_fr1_a3_8_tdlb100_400"];
mandatory.FRC = [ ...
    "R.PDSCH.1-1.4 FDD"; ...
    "R.PDSCH.1-3.6 FDD"; ...
    "R.PDSCH.1-4.1 FDD"; ...
    "G-FR1-A3A-1"; ...
    "G-FR1-A13-1"; ...
    "R.PDSCH.1-1.1 FDD"; ...
    "G-FR1-A3-8"];
mandatory.Condition = [ ...
    "awgn_static_1x2"; ...
    "atg_awgn_220hz_2x2"; ...
    "atg_awgn_220hz_2x2"; ...
    "awgn_1x2"; ...
    "atg_awgn_200hz_1x2"; ...
    "tdlb100_400_ula_low_2x2"; ...
    "tdlb100_400_low_1x2"];
mandatory.RequiredSNR_dB = ...
    [3.2; 13.6; 22.5; -5.1; 19.1; -0.8; -2.3];
end

function [rows, diagnostics] = localPreflight(mandatory)
numCases = height(mandatory);
rows = repmat(struct( ...
    "SetupPass", false, ...
    "DataChannelExact", false, ...
    "FullWaveformExact", false, ...
    "RequiredSNR_dB", NaN), numCases, 1);
diagnostics = strings(numCases, 1);

for index = 1:numCases
    try
        result = sixgr.conformance.runFRCPoint( ...
            mandatory.EntryId(index), mandatory.Condition(index), ...
            "ExecutionProfile", "smoke", ...
            "ValidateSetupOnly", true, ...
            "RequireExactStandardExecution", false, ...
            "RequireExactDataChannelExecution", false, ...
            "AssertPass", false, ...
            "PrintTable", false, ...
            "Verbose", false);

        rows(index).SetupPass = logical(result.SetupValidationOnly) && ...
            logical(result.SetupValidation.Pass);
        rows(index).DataChannelExact = ...
            logical(result.DataChannelExecution.Exact);
        rows(index).FullWaveformExact = ...
            logical(result.StandardExecution.Exact);
        rows(index).RequiredSNR_dB = double(result.RequiredSNR_dB);
        selectedContract = result.DataChannelExecution.Contract;
        assert(string(selectedContract.ContractVersion) == ...
            "sixgr_frc_selected_data_channel/v1", ...
            "FRC setup must disclose its selected data-channel contract.");
        if contains(mandatory.Condition(index), "tdl")
            correlation = selectedContract.Correlation;
            assert(logical(correlation.Exact) && ...
                string(correlation.ToolboxMIMOCorrelation) == "Low", ...
                "Mandatory fading anchors must resolve their exact Low correlation.");
            blockers = string(result.DataChannelExecution.Blockers);
            assert(~any(blockers == ...
                "fading_harq_process_timing_not_materialized"), ...
                "Mandatory fading anchors must materialize their selected HARQ timing.");
            assert(rows(index).DataChannelExact && ...
                logical(selectedContract.HARQ.SelectedHarnessTimingExact), ...
                "Fading data-channel execution requires explicit slot-spaced HARQ timing.");
            if startsWith(mandatory.EntryId(index), "dl_")
                assert(logical(selectedContract.HARQ.ProcessTimingExact) && ...
                    logical(selectedContract.HARQ.ProcessTimingSpecifiedByStandard), ...
                    ["The mandatory DL anchor must reproduce the four-process, " ...
                    "two-slot ACK timing in TS 38.101-4 Table 5.2.2.1.1-2."]);
            else
                assert(~logical(selectedContract.HARQ.ProcessTimingExact) && ...
                    ~logical(selectedContract.HARQ.ProcessTimingSpecifiedByStandard), ...
                    ["TS 38.104 clause 8.2.1 does not specify UL process " ...
                    "count or feedback delay; the selected FDD harness must " ...
                    "remain disclosed as a nonnormative timing assumption."]);
            end
        end

        assert(result.ApproximationMode == "none", ...
            "FRC setup must not advertise an approximation mode.");
        assert(result.Source == "existing_truth_phy_execution", ...
            "FRC setup must be sourced from the existing truth PHY.");
        assert(logical(result.StandardExecution.NoProxyOrFallbackUsed), ...
            "FRC setup must explicitly exclude proxy and fallback execution.");
        assert(~logical(result.NormativePass) && ...
            ~logical(result.ReferencePointPass) && ...
            ~logical(result.ProjectDiagnosticPass) && ...
            ~logical(result.StatisticallyQualified), ...
            ["Setup-only FRC validation must not be marked normative, " ...
            "reference-point, project-diagnostic, or statistically " ...
            "qualified pass."]);

        localAssertNear(result.RequiredSNR_dB, ...
            mandatory.RequiredSNR_dB(index), ...
            mandatory.EntryId(index) + " required SNR");
        setupTable = result.SetupValidation.Table;
        if startsWith(mandatory.EntryId(index), "dl_")
            expectedSlots = [1; 10; 11];
            assert(height(setupTable) == 3 && ...
                isequal(double(setupTable.slot(:)), expectedSlots), ...
                ["DL FRC setup must validate ordinary slot 1 and both " ...
                "tracking CSI-RS slots 10 and 11."]);
            trackingRows = ismember(double(setupTable.slot), [10, 11]);
            assert(all(setupTable.tracking_csirs_materialized(trackingRows)) && ...
                ~any(setupTable.tracking_csirs_materialized(~trackingRows)), ...
                ["DL setup must materialize tracking CSI-RS only in slots " ...
                "10 and 11."]);
        else
            assert(height(setupTable) == 1 && double(setupTable.slot(1)) == 0, ...
                "UL FRC setup must contain its ordinary slot-zero row.");
        end
        assert(all(setupTable.pass), ...
            "Every FRC setup slot must pass exact TBS/G validation.");
        assert(all(double(setupTable.required_TBS_bits) == ...
            double(setupTable.actual_TBS_bits)), ...
            "FRC setup must reproduce the catalog transport-block size.");
        assert(all(double(setupTable.required_G_bits) == ...
            double(setupTable.actual_G_bits)), ...
            "FRC setup must reproduce the catalog rate-matched G.");

        if rows(index).DataChannelExact
            fullBlockers = string(result.StandardExecution.Blockers);
            fullBlockers = fullBlockers(strlength(fullBlockers) > 0);
            detail = "exact selected data channel; full-waveform blockers: " + ...
                strjoin(fullBlockers, "; ");
        else
            blockers = string(result.DataChannelExecution.Blockers);
            blockers = blockers(strlength(blockers) > 0);
            detail = "incomplete selected data-channel reproduction: " + ...
                strjoin(blockers, "; ");
        end
        diagnostics(index) = sprintf("%s | %s: %s", ...
            mandatory.FRC(index), mandatory.Condition(index), detail);
    catch cause
        diagnostics(index) = sprintf("%s | %s: setup failed: %s (%s)", ...
            mandatory.FRC(index), mandatory.Condition(index), ...
            string(cause.message), string(cause.identifier));
    end
end
end

function report = localReportFromPreflight(mandatory, preflight)
numCases = height(mandatory);
required = reshape([preflight.RequiredSNR_dB], [], 1);
missing = ~isfinite(required);
required(missing) = mandatory.RequiredSNR_dB(missing);
report = table();
report.FRC = reshape(mandatory.FRC, [], 1);
report.condition = reshape(mandatory.Condition, [], 1);
report.required_SNR_dB = reshape(required, [], 1);
report.measured_SNR_dB = nan(numCases, 1);
report.delta_dB = nan(numCases, 1);
report.pass = false(numCases, 1);
end

function [report, gatePass, diagnostics] = ...
        localConsolidateResults(mandatory, results, runDiagnostics)
numCases = height(mandatory);
required = mandatory.RequiredSNR_dB;
measured = nan(numCases, 1);
delta = nan(numCases, 1);
gatePass = false(numCases, 1);
diagnostics = strings(numCases, 1);

for index = 1:numCases
    if strlength(runDiagnostics(index)) > 0
        diagnostics(index) = runDiagnostics(index);
        continue;
    end

    result = results{index};
    required(index) = double(result.RequiredSNR_dB);
    measured(index) = double(result.MeasuredSNRAtTarget_dB);
    delta(index) = double(result.Delta_dB);

    exact = logical(result.StandardExecution.Exact) && ...
        logical(result.StandardExecution.NormativeResultEligible) && ...
        logical(result.DataChannelExecution.Exact) && ...
        logical(result.DataChannelExecution.ReferencePointResultEligible);
    referencePoint = logical(result.ReferencePointPass);
    statisticallyQualified = logical(result.StatisticallyQualified);
    symmetric = logical(result.ProjectDiagnosticPass);
    gatePass(index) = exact && logical(result.NormativePass) && referencePoint && ...
        statisticallyQualified && symmetric;

    assert(result.ApproximationMode == "none", ...
        "FRC result must not use an approximation.");
    assert(result.Source == "existing_truth_phy_execution", ...
        "FRC result must come from existing truth PHY execution.");
    assert(logical(result.StandardExecution.NoProxyOrFallbackUsed), ...
        "FRC result must explicitly exclude proxy or fallback execution.");
    assert(logical(result.StandardExecution.Exact) && ...
        logical(result.StandardExecution.NormativeResultEligible) && ...
        logical(result.NormativePass), ...
        ["The full FRC gate requires exact complete-waveform execution and " ...
        "a statistically supported normative operating-point pass."]);
    assert(logical(result.DataChannelExecution.Exact), ...
        "The selected FRC data-channel execution must be exact.");
    assert(result.NormativeSemantics == ...
        "one_sided_minimum_performance_at_required_snr", ...
        "FRC normative result must retain one-sided 3GPP semantics.");
    assert(~logical(result.ProjectDiagnosticNormative), ...
        "The symmetric SNR-crossing diagnostic must remain nonnormative.");
    assert(result.ProjectDiagnosticSemantics == ...
        "symmetric_snr_at_target_crossing_nonnormative_regression_check", ...
        "FRC symmetric crossing must be labelled as a project diagnostic.");

    diagnostics(index) = sprintf([ ...
        "%s | %s: required %.3f dB, measured %.3f dB, delta %.3f dB; " ...
        "data-channel-exact=%d, reference-point=%d, reference-CI-support=%d, " ...
        "statistically-qualified=%d, symmetric-project-gate=%d"], ...
        mandatory.FRC(index), mandatory.Condition(index), required(index), ...
        measured(index), delta(index), exact, referencePoint, ...
        logical(result.ReferencePointConfidenceSupportsPass), ...
        statisticallyQualified, symmetric);
end

report = table();
report.FRC = reshape(mandatory.FRC, [], 1);
report.condition = reshape(mandatory.Condition, [], 1);
report.required_SNR_dB = reshape(required, [], 1);
report.measured_SNR_dB = reshape(measured, [], 1);
report.delta_dB = reshape(delta, [], 1);
report.pass = reshape(gatePass, [], 1);
end

function localAssertCatalogAnchors(catalog)
assert(string(catalog.schema_version) == "1.0.0", ...
    "Unexpected FRC catalog schema version.");
assert(string(catalog.catalog_id) == "nr_frc_release18", ...
    "Unexpected FRC catalog id.");
assert(string(catalog.research_class) == "baseline_benchmark", ...
    "FRC catalog must be a baseline benchmark.");
assert(double(catalog.expected_entry_count) == 21 && ...
    numel(catalog.entries) == double(catalog.expected_entry_count), ...
    ["Selected Release 18 FRC catalog must contain the ten Phase 1 " ...
    "anchors plus the eleven declared representative coverage records."]);

policy = catalog.project_diagnostic_policy;
assert(~logical(policy.normative), ...
    "Symmetric SNR crossing must not be represented as a 3GPP rule.");
assert(string(policy.comparison_mode) == ...
    "symmetric_snr_at_target_crossing", ...
    "Unexpected FRC project diagnostic comparison mode.");
localAssertNear(policy.tolerance_db, 1.0, ...
    "catalog project tolerance");
assert(string(policy.normative_requirement_semantics) == ...
    "one_sided_minimum_performance_at_required_snr", ...
    "Catalog must preserve one-sided standards requirement semantics.");

expected = localExpectedCatalogAnchors();
for index = 1:numel(expected.EntryId)
    entry = localCatalogEntry(catalog.entries, expected.EntryId(index));
    label = expected.EntryId(index);

    localAssertText(entry.frc_id, expected.FRC(index), label + " FRC");
    localAssertText(entry.direction, expected.Direction(index), ...
        label + " direction");
    localAssertText(entry.condition.id, expected.Condition(index), ...
        label + " condition");
    localAssertText(entry.coding.modulation, expected.Modulation(index), ...
        label + " modulation");
    localAssertText(entry.condition.kind, expected.ConditionKind(index), ...
        label + " condition kind");
    localAssertText(entry.condition.model, expected.ChannelModel(index), ...
        label + " channel model");
    localAssertText(entry.requirement.metric, expected.Metric(index), ...
        label + " metric");
    localAssertText(entry.requirement.comparator, expected.Comparator(index), ...
        label + " comparator");

    localAssertNear(entry.coding.target_code_rate_numerator, ...
        expected.RateNumerator(index), label + " rate numerator");
    assert(double(entry.coding.target_code_rate_denominator) == 1024, ...
        "%s code-rate denominator must be 1024.", label);
    localAssertNear(entry.coding.tbs_bits, expected.TBSBits(index), ...
        label + " TBS");
    localAssertNear(entry.coding.g_bits_per_slot, expected.GBits(index), ...
        label + " G");
    localAssertNear(entry.mimo.layers, expected.Layers(index), ...
        label + " layers");
    localAssertNear(entry.dmrs.additional_position, ...
        expected.DMRSAdditionalPosition(index), ...
        label + " DM-RS additional position");
    localAssertNear(entry.dmrs.num_cdm_groups_without_data, ...
        expected.CDMGroups(index), label + " CDM groups");
    localAssertNear(entry.dmrs.data_to_dmrs_epre_db, ...
        expected.DataToDMRSEPRE_dB(index), label + " DM-RS EPRE");
    localAssertNear(entry.condition.delay_spread_ns, ...
        expected.DelaySpread_ns(index), label + " delay spread");
    localAssertNear(entry.condition.max_doppler_hz, ...
        expected.Doppler_Hz(index), label + " Doppler");
    localAssertNear(entry.condition.frequency_offset_hz, ...
        expected.FrequencyOffset_Hz(index), label + " frequency offset");
    localAssertNear(entry.requirement.target_fraction, ...
        expected.TargetFraction(index), label + " target");
    localAssertNear(entry.requirement.required_snr_db, ...
        expected.RequiredSNR_dB(index), label + " required SNR");
    localAssertNear(entry.harq.max_transmissions, ...
        expected.MaxHARQTransmissions(index), ...
        label + " HARQ transmissions");

    assert(logical(entry.requirement.normative), ...
        "%s requirement must be normative.", label);
    localAssertText(entry.requirement.semantics, ...
        "one_sided_minimum_performance_at_required_snr", ...
        label + " requirement semantics");
    localAssertText(entry.allocation.mapping_type, "A", ...
        label + " mapping type");
    assert(logical(entry.allocation.full_bandwidth), ...
        "%s must use the full FRC bandwidth.", label);
    localAssertText(entry.allocation.frequency_hopping, "disabled", ...
        label + " frequency hopping");
    localAssertText(entry.waveform.name, "CP-OFDM", ...
        label + " waveform");
    assert(~logical(entry.waveform.transform_precoding), ...
        "%s must use CP-OFDM without transform precoding.", label);
    assert(double(entry.dmrs.configuration_type) == 1 && ...
        string(entry.dmrs.duration) == "single_symbol" && ...
        double(entry.dmrs.type_a_position) == 2, ...
        "%s has the wrong DM-RS type/duration/type-A position.", label);

    if expected.Direction(index) == "downlink"
        localAssertText(entry.physical_channel, "PDSCH", ...
            label + " physical channel");
        localAssertText(entry.receiver_role, "UE-Rx", ...
            label + " receiver role");
        localAssertText(entry.standard.document, "3GPP TS 38.101-4", ...
            label + " standard");
        localAssertText(entry.standard.version, "18.11.0", ...
            label + " standard version");
        assert(double(entry.carrier.channel_bandwidth_mhz) == 10 && ...
            double(entry.carrier.subcarrier_spacing_khz) == 15 && ...
            double(entry.carrier.n_prb) == 52 && ...
            double(entry.allocation.start_symbol) == 2 && ...
            double(entry.allocation.symbol_length) == 12, ...
            "%s has the wrong DL carrier/allocation anchor.", label);
    else
        localAssertText(entry.physical_channel, "PUSCH", ...
            label + " physical channel");
        localAssertText(entry.receiver_role, "gNB-Rx", ...
            label + " receiver role");
        localAssertText(entry.standard.document, "3GPP TS 38.104", ...
            label + " standard");
        localAssertText(entry.standard.version, "18.13.0", ...
            label + " standard version");
        assert(double(entry.carrier.channel_bandwidth_mhz) == 5 && ...
            double(entry.carrier.subcarrier_spacing_khz) == 15 && ...
            double(entry.carrier.n_prb) == 25 && ...
            double(entry.allocation.start_symbol) == 0 && ...
            double(entry.allocation.symbol_length) == 14, ...
            "%s has the wrong UL carrier/allocation anchor.", label);
        assert(isequal(double(entry.dmrs.ports(:).'), 0) && ...
            isequal(double(entry.dmrs.symbol_indices(:).'), [2, 11]), ...
            "%s has the wrong UL DM-RS ports or symbols.", label);
    end

    if expected.MaxHARQTransmissions(index) == 1
        expectedRV = 0;
    else
        expectedRV = [0, 2, 3, 1];
    end
    assert(isequal(double(entry.harq.rv_sequence(:).'), expectedRV), ...
        "%s has the wrong HARQ redundancy-version sequence.", label);

    if expected.ConditionKind(index) == "fading"
        assert(any(string(entry.condition.model) == ["TDL-A", "TDL-B"]) && ...
            ~any(string(entry.condition.model) == ["TDL", "CDL"]), ...
            "%s fading profile must be concrete, not a model family.", label);
    end
end
end

function expected = localExpectedCatalogAnchors()
expected = struct();
expected.EntryId = [ ...
    "dl_r_pdsch_1_1_4_fdd_awgn"; ...
    "dl_r_pdsch_1_3_6_fdd_atg_awgn"; ...
    "dl_r_pdsch_1_4_1_fdd_atg_awgn"; ...
    "dl_r_pdsch_1_1_1_fdd_tdlb100_400"; ...
    "dl_r_pdsch_1_3_1_fdd_tdla30_10"; ...
    "dl_r_pdsch_1_4_1_fdd_tdla30_10"; ...
    "ul_g_fr1_a3a_1_awgn"; ...
    "ul_g_fr1_a13_1_atg_awgn"; ...
    "ul_g_fr1_a3_8_tdlb100_400"; ...
    "ul_g_fr1_a5_8_tdla30_10"];
expected.FRC = [ ...
    "R.PDSCH.1-1.4 FDD"; ...
    "R.PDSCH.1-3.6 FDD"; ...
    "R.PDSCH.1-4.1 FDD"; ...
    "R.PDSCH.1-1.1 FDD"; ...
    "R.PDSCH.1-3.1 FDD"; ...
    "R.PDSCH.1-4.1 FDD"; ...
    "G-FR1-A3A-1"; ...
    "G-FR1-A13-1"; ...
    "G-FR1-A3-8"; ...
    "G-FR1-A5-8"];
expected.Direction = [ ...
    "downlink"; "downlink"; "downlink"; "downlink"; "downlink"; ...
    "downlink"; "uplink"; "uplink"; "uplink"; "uplink"];
expected.Condition = [ ...
    "awgn_static_1x2"; ...
    "atg_awgn_220hz_2x2"; ...
    "atg_awgn_220hz_2x2"; ...
    "tdlb100_400_ula_low_2x2"; ...
    "tdla30_10_ula_low_2x2"; ...
    "tdla30_10_ula_low_2x2"; ...
    "awgn_1x2"; ...
    "atg_awgn_200hz_1x2"; ...
    "tdlb100_400_low_1x2"; ...
    "tdla30_10_low_1x2"];
expected.Modulation = [ ...
    "QPSK"; "64QAM"; "256QAM"; "QPSK"; "64QAM"; ...
    "256QAM"; "QPSK"; "64QAM"; "QPSK"; "64QAM"];
expected.RateNumerator = ...
    [602; 666; 841; 308; 517; 841; 99; 948; 193; 567];
expected.TBSBits = ...
    [8064; 26632; 45096; 3904; 42016; 45096; 704; 19968; 1352; 12040];
expected.GBits = ...
    [13728; 41184; 54912; 13104; 82368; 54912; 7200; 21600; 7200; 21600];
expected.Layers = [1; 1; 1; 1; 2; 1; 1; 1; 1; 1];
expected.DMRSAdditionalPosition = [1; 1; 1; 2; 1; 1; 1; 1; 1; 1];
expected.CDMGroups = [1; 1; 1; 1; 1; 1; 2; 2; 2; 2];
expected.DataToDMRSEPRE_dB = [0; 0; 0; 0; 0; 0; -3; -3; -3; -3];
expected.ConditionKind = [ ...
    "awgn"; "awgn"; "awgn"; "fading"; "fading"; ...
    "fading"; "awgn"; "awgn"; "fading"; "fading"];
expected.ChannelModel = [ ...
    "AWGN"; "AWGN"; "AWGN"; "TDL-B"; "TDL-A"; ...
    "TDL-A"; "AWGN"; "AWGN"; "TDL-B"; "TDL-A"];
expected.DelaySpread_ns = [0; 0; 0; 100; 30; 30; 0; 0; 100; 30];
expected.Doppler_Hz = [0; 0; 0; 400; 10; 10; 0; 0; 400; 10];
expected.FrequencyOffset_Hz = [0; 220; 220; 0; 0; 0; 0; 200; 0; 0];
expected.Metric = [ ...
    "block_error_rate"; ...
    "fraction_of_maximum_throughput"; ...
    "fraction_of_maximum_throughput"; ...
    "fraction_of_maximum_throughput"; ...
    "fraction_of_maximum_throughput"; ...
    "fraction_of_maximum_throughput"; ...
    "block_error_rate"; ...
    "fraction_of_maximum_throughput"; ...
    "fraction_of_maximum_throughput"; ...
    "fraction_of_maximum_throughput"];
expected.Comparator = [ ...
    "less_than_or_equal"; ...
    "greater_than_or_equal"; ...
    "greater_than_or_equal"; ...
    "greater_than_or_equal"; ...
    "greater_than_or_equal"; ...
    "greater_than_or_equal"; ...
    "less_than_or_equal"; ...
    "greater_than_or_equal"; ...
    "greater_than_or_equal"; ...
    "greater_than_or_equal"];
expected.TargetFraction = ...
    [1e-5; 0.70; 0.70; 0.70; 0.70; 0.70; 1e-5; 0.70; 0.70; 0.70];
expected.RequiredSNR_dB = ...
    [3.2; 13.6; 22.5; -0.8; 19.4; 24.6; -5.1; 19.1; -2.3; 12.3];
expected.MaxHARQTransmissions = [1; 4; 4; 4; 4; 4; 1; 4; 4; 4];
end

function entry = localCatalogEntry(entries, entryId)
matches = false(numel(entries), 1);
for index = 1:numel(entries)
    candidate = localSequenceItem(entries, index);
    matches(index) = string(candidate.id) == string(entryId);
end
indices = find(matches);
assert(numel(indices) == 1, ...
    "Expected exactly one FRC catalog record with id '%s'.", entryId);
entry = localSequenceItem(entries, indices);
end

function value = localSequenceItem(sequence, index)
if iscell(sequence)
    value = sequence{index};
else
    value = sequence(index);
end
end

function localAssertText(actual, expected, label)
assert(string(actual) == string(expected), ...
    "%s is '%s'; expected '%s'.", ...
    label, string(actual), string(expected));
end

function localAssertNear(actual, expected, label)
actual = double(actual);
expected = double(expected);
tolerance = max(1e-12, 64 * eps(max(abs(expected), 1)));
assert(isscalar(actual) && isfinite(actual) && ...
    abs(actual - expected) <= tolerance, ...
    "%s is %.15g; expected %.15g.", label, actual, expected);
end

function localThrowFailure(identifier, heading, diagnostics, varargin)
diagnostics = string(diagnostics);
diagnostics = diagnostics(strlength(diagnostics) > 0);
if isempty(diagnostics)
    details = "(no diagnostic detail was produced)";
else
    details = strjoin("  - " + diagnostics, newline);
end
headingText = string(sprintf(char(heading), varargin{:}));
message = strjoin([headingText; string(details(:))], string(newline));
error(char(identifier), "%s", char(message));
end

function tf = localTextScalar(value)
tf = ischar(value) || (isstring(value) && isscalar(value));
end

function tf = localLogicalScalar(value)
tf = (islogical(value) || isnumeric(value)) && isscalar(value) && ...
    isfinite(double(value)) && any(double(value) == [0, 1]);
end
