function ok = testKPIHARQDeduplicatedGoodput()
%TESTKPIHARQDEDUPLICATEDGOODPUT Duplicate TB delivery must not inflate goodput.

setup6GRSimToolkit("Verbose", false);

raw = struct();
raw.UL = table( ...
    repmat("UL", 3, 1), [1; 1; 0], [true; true; false], [0; 0; 100], [1000; 1000; 1000], ...
    [1000; 1000; 1000], [1000; 1000; 0], [1; 1; 1], [1; 2; 3], ["ul_tb_1"; "ul_tb_1"; "ul_tb_2"], ...
    [0; 0; 0], [0; 2; 3], [0; 0; 1], [1; 1; 1], [1; 2; 3], ...
    'VariableNames', {'Direction','Goodput_Mbps','CRCPass','BitErrors','BitsCompared', ...
    'TBSize_bits','GoodBits','Frame','Slot','TransportBlockId','HARQProcessId','RV','NDI', ...
    'AirInterfaceObservation_ms','TrialId'});
raw.DL = localDirectionTable("DL", 40.137091);

out = sixgr.kpi.reconstructLLSKPISummaryFromRaw(raw, "StrictMode", true);
ulGoodput = out.ReconstructionSummary(strcmp(string(out.ReconstructionSummary.KPIName), ...
    "UL_TB_Delivery_Goodput_Mbps"), :);
assert(abs(double(ulGoodput.NumeratorValue(1)) - 1000) < 1e-9, ...
    "Duplicate successful delivery for the same TB must count only once.");
assert(double(ulGoodput.DuplicateDeliveryCount(1)) == 1, ...
    "Duplicate delivery must be visible in reconstruction evidence.");
assert(sum(logical(out.HARQDeliveryTraceUL.DuplicateDelivery)) == 1, ...
    "HARQ trace must mark the duplicate successful attempt.");

ok = true;
end

function T = localDirectionTable(direction, goodput)
T = table( ...
    repmat(string(direction), 2, 1), [goodput; 0], [true; false], [0; 1], [1000; 1000], ...
    [1000; 1000], [1000; 0], [1; 1], [1; 2], string([direction + "_tb_1"; direction + "_tb_2"]), ...
    [0; 0], [0; 0], [0; 0], [1; 1], [1; 2], ...
    'VariableNames', {'Direction','Goodput_Mbps','CRCPass','BitErrors','BitsCompared', ...
    'TBSize_bits','GoodBits','Frame','Slot','TransportBlockId','HARQProcessId','RV','NDI', ...
    'AirInterfaceObservation_ms','TrialId'});
end
