function ok = testPDSCHBLERScientificGate()
%TESTPDSCHBLERSCIENTIFICGATE Reject schema-valid non-waterfall evidence.

setup6GRSimToolkit("Verbose",false,"RunToolboxChecks",false);

campaignID = [ ...
    "BLER-AWGN-QPSK"; "BLER-AWGN-64QAM"; ...
    "BLER-TDL-R2-16QAM"; "BLER-CDL-R4-64QAM"; ...
    "BLER-AWGN-1024QAM"; "BLER-AWGN-HARQ-0231"; ...
    "BLER-AWGN-PTRS-PN"];
channel = ["AWGN";"AWGN";"TDL-A";"CDL-C";"AWGN";"AWGN";"AWGN"];
rank = [1;1;2;4;1;1;1];
modulation = ["QPSK";"64QAM";"16QAM";"64QAM"; ...
    "1024QAM";"QPSK";"256QAM"];
mcs = [4;18;10;18;23;4;25];
snrGrid = [ ...
    -2 2 6 10; 8 12 16 20; 5 10 15 20; ...
    10 15 20 25; 20 25 30 35; -4 0 4 8; 15 20 25 30];

rows = repmat(localRow(),0,1);
errors = [4 2 1 0];
for campaignIndex = 1:numel(campaignID)
    for pointIndex = 1:4
        row = localRow();
        row.CampaignID = campaignID(campaignIndex);
        row.OperatingPointID = "OP-" + compose("%02d",pointIndex);
        row.SNRdB = snrGrid(campaignIndex,pointIndex);
        row.ChannelModel = channel(campaignIndex);
        row.Rank = rank(campaignIndex);
        row.MCSIndex = mcs(campaignIndex);
        row.Modulation = modulation(campaignIndex);
        row.TBErrors = errors(pointIndex);
        row.BLER = row.TBErrors / row.Trials;
        rows(end+1,1) = row; %#ok<AGROW>
    end
end
valid = struct2table(rows,"AsArray",true);
sixgr.pdsch.PDSCHPhaseArtifactPublisher. ...
    assertBLERScientificValidity(valid);

allZero = valid;
allZero.TBErrors(:) = 0;
allZero.BLER(:) = 0;
try
    sixgr.pdsch.PDSCHPhaseArtifactPublisher. ...
        assertBLERScientificValidity(allZero);
    error("sixgr:test:PDSCHBLERScientificGateDidNotFail", ...
        "All-zero BLER evidence unexpectedly passed the scientific gate.");
catch cause
    assert(cause.identifier == ...
        "sixgr:pdsch:PDSCHPhasePublisher:BLERWaterfallNotObserved", ...
        "Unexpected all-zero BLER failure identifier: %s",cause.identifier);
end

fprintf("PDSCH scientific BLER gate: 7/7 transitions accepted; " + ...
    "all-zero evidence rejected.\n");
ok = true;
end

function row = localRow()
row = struct( ...
    "CampaignID","", ...
    "OperatingPointID","", ...
    "SNRdB",0, ...
    "ChannelModel","", ...
    "Rank",1, ...
    "MCSIndex",0, ...
    "Modulation","", ...
    "Trials",8, ...
    "TBErrors",0, ...
    "BLER",0, ...
    "ConfidenceLevel",0.95, ...
    "CILower",0, ...
    "CIUpper",1, ...
    "CIHalfWidth",0.5, ...
    "MinErrorsRequired",1, ...
    "StopReason","FIXED_TRIAL_BUDGET_COMPLETE", ...
    "Status","PASS");
end
