function ok = testPRACHB4CanonicalActiveSlot()
%TESTPRACHB4CANONICALACTIVESLOT Validate index-157 active-slot ordering.

setup6GRSimToolkit("Verbose", false, "RunToolboxChecks", false);
scenarioPath = fullfile(pwd, "simulator", "configs", "scenarios", ...
    "webgui_sinr_sweep_64x4_mu_mimo_full.yaml");
scenario = sixgr.lls6g.config.loadScenarioConfig(scenarioPath);
tmp = tempname;
mkdir(tmp);
cleanup = onCleanup(@() localCleanup(tmp)); %#ok<NASGU>
cfg = sixgr.lls6g.buildInternalConfig(scenario, fullfile(tmp, "run"));

prachCfg = sixgr.rach.PRACHConfig(cfg, ...
    "NumPRACHOccasions", 1, "NumTrials", 1);
assert(double(prachCfg.PRACHConfigurationIndex) == 157 && ...
    string(prachCfg.ResolvedPRACHFormat) == "B4", ...
    "The target FR1-unpaired PRACH point must resolve index 157/B4.");
assert(double(prachCfg.ToolboxPRACH.ActivePRACHSlot) == 1 && ...
    double(prachCfg.FirstActiveOccasion.ActivePRACHSlot) == 1, ...
    "Index 157/B4 must install canonical ActivePRACHSlot=1 before derived Toolbox properties are queried.");
assert(ismember(double(prachCfg.FirstActiveOccasion.SlotIndex1), ...
    double(sixgr.util.structGet(cfg, ...
    "phy.prach.validSlots1Based", []))), ...
    "The first materialized B4 occasion must belong to the resolved carrier-slot catalog.");

% Exercise the production four-step-RA constructor and waveform path, not
% only the direct PRACHConfig object.  The occasion is serialized and then
% reconstructed by generatePRACHSequence, where losing ActivePRACHSlot
% previously caused nrPRACH to reject every coupled Msg1 attempt.
raCfg = sixgr.mac.ra.RAConfig(cfg, ...
    "RunId", "prach_b4_production_path", ...
    "ScenarioName", "prach_b4_production_path", ...
    "UEId", 1, "CellId", 1);
assert(logical(sixgr.util.structGet(cfg, "phy.pdsch.enablePTRS", false)) && ...
    logical(raCfg.Msg2PDSCH.EnablePTRS) && ...
    logical(raCfg.Msg3PUSCH.EnablePTRS) && ...
    logical(raCfg.Msg4PDSCH.EnablePTRS) && ...
    logical(raCfg.SetupCompletePUSCH.EnablePTRS) && ...
    all(double(raCfg.Msg2PDSCH.PTRSPortSet) == 0) && ...
    all(double(raCfg.Msg3PUSCH.PTRSPortSet) == 0), ...
    "Enabled YAML PT-RS authority must reach every four-step RA waveform stage with explicit port 0.");
cfgRA = sixgr.phy.ra.localizeCarrierConfig(cfg, raCfg);
[tx, occasion] = sixgr.phy.ra.generateMsg1PRACHWaveform(cfgRA, raCfg);
assert(~isempty(tx.Waveform) && all(isfinite(tx.Waveform(:))), ...
    "Production Msg1 B4 waveform must be nonempty and finite.");
assert(double(tx.PRACH.ActivePRACHSlot) == 1 && ...
    double(occasion.ActivePRACHSlot) == 1, ...
    "Production Msg1 reconstruction must preserve canonical ActivePRACHSlot=1.");
ok = true;
end

function localCleanup(pathText)
if isfolder(pathText)
    rmdir(pathText, "s");
end
end
