function ok = testCausalFourStepRAEndToEnd()
%TESTCAUSALFOURSTEPRANEDTOEND Guard the measured Msg1-to-connected chain.

scenarioPath = fullfile("simulator", "configs", "scenarios", ...
    "lls_causal_access_to_data_wiring.yaml");
scfg = sixgr.lls6g.config.loadScenarioConfig(scenarioPath);
runRoot = tempname;
mkdir(runRoot);
cleanup = onCleanup(@() localCleanup(runRoot)); %#ok<NASGU>
cfg = sixgr.config.normalizeConfig( ...
    sixgr.lls6g.buildInternalConfig(scfg, runRoot));
multiUser = struct("Enabled", true, "NumUsers", 1, "RNTIStart", 1, ...
    "ExecutionModel", "slot_coupled_truth");
state = sixgr.truth.CoupledTruthRuntime.initialize( ...
    cfg, runRoot, multiUser, struct(), 1);
state.CurrentSlot = 2;
state.CurrentServingIdx(:) = 1;
[cfgRuntime, ~] = sixgr.truth.CoupledTruthRuntime.applyUserContext( ...
    cfg, state, 1, "UL");

result = sixgr.phy.ra.runFourStepRA(cfgRuntime, ...
    "RunFolder", runRoot, "RunId", "causal_four_step_ra_e2e", ...
    "ScenarioName", "causal_four_step_ra_e2e", ...
    "UEId", 1, "CellId", 1, "AttemptId", 1, ...
    "RuntimeIntegrationMode", "coupled_truth_runtime", ...
    "UseRuntimeChannel", true, "RuntimeNoiseSNR_dB", 30, ...
    "RuntimeSlot", 2, "WriteArtifacts", false);

assert(logical(result.RACompleted) && logical(result.StrictOk), ...
    "The measured four-step RA and RRCSetupComplete chain must pass strict.");
assert(~logical(result.ProxyUsed) && ~logical(result.Skipped), ...
    "The causal RA regression must not use proxy or skipped evidence.");
assert(logical(result.Msg2DCICrcPass) && logical(result.Msg2PDSCHCrcPass), ...
    "Msg2 must be recovered from CRC-valid RA-RNTI PDCCH and RAR PDSCH.");
assert(logical(result.Msg3PUSCHCrcPass), ...
    "Msg3 must be recovered from the decoded RAR UL grant.");
assert(logical(result.Msg4PDCCHCrcPass) && logical(result.Msg4PDSCHCrcPass), ...
    "Msg4 must be recovered from CRC-valid TC-RNTI PDCCH and PDSCH.");
assert(logical(result.RRCSetupCompleteCRC) && ...
    logical(result.RRCSetupCompleteDecoded) && logical(result.RRCConnected), ...
    "RRCSetupComplete must traverse the measured UL waveform into connected state.");

T = result.RuntimeStageRows;
expectedStages = ["Msg1";"Msg2";"Msg3";"Msg4";"RRCSetupComplete"];
expectedDirections = ["UL";"DL";"UL";"DL";"UL"];
assert(height(T) == numel(expectedStages) && ...
    isequal(string(T.StageName), expectedStages) && ...
    isequal(string(T.Direction), expectedDirections), ...
    "The runtime channel stages must execute once in causal DL/UL order.");
assert(all(logical(T.RuntimeChannelStateUsed)) && ...
    all(double(T.TxPortCount) == 1) && ...
    all(double(T.RuntimeChannelPhysicalTxElements) == 2) && ...
    all(double(T.RxPortCount) == 2), ...
    ["Every RA stage must traverse one logical waveform port, the configured " ...
     "two-element physical transmitter, and both physical receive branches."]);

ok = true;
fprintf('%s\n', ['PASS testCausalFourStepRAEndToEnd: Msg1, Msg2, Msg3, ' ...
    'Msg4, and RRCSetupComplete passed the persistent measured CDL chain.']);
end

function localCleanup(pathText)
if isfolder(pathText)
    rmdir(pathText, "s");
end
end
