function ok = testLLS700MHzFullTruthProfile()
%TESTLLS700MZFULLTRUTHPROFILE Keep the 700 MHz strict truth preset honest and fully enabled where supported.

setup6GRSimToolkit("Verbose", false);

scenarioPath = fullfile(pwd, "simulator", "configs", "scenarios", "lls_700mhz_20mhz_2x2_rank2_beam_truth.yaml");
scfg = sixgr.lls6g.config.loadScenarioConfig(scenarioPath);
cfg = sixgr.lls6g.buildInternalConfig(scfg, fullfile(tempdir, "lls_700mhz_profile_probe"));
resolvedProfile = sixgr.link.resolveMCSProfile(scfg.get("modulation.mcs_table"), scfg.get("modulation.dl_mcs_index"));

assert(any(lower(string(scfg.get("meta.tags"))) == "no-proxy"), ...
    "700 MHz truth preset must stay tagged as no-proxy.");
assert(string(scfg.get("link_adaptation.fixed_or_amc")) == "fixed", ...
    "700 MHz truth preset must sustain its configured nominal operating point by disabling adaptive AMC.");
assert(string(scfg.get("link_adaptation.rank_adaptation_policy")) == "fixed", ...
    "700 MHz truth preset must keep the configured rank fixed.");
assert(string(scfg.get("simulation.noise_operating_mode")) == ...
    "standalone_awgn_snr_argument" && ...
    ~logical(scfg.get("channels.pathloss_enabled")) && ...
    ~logical(scfg.get("channels.shadow_fading_enabled")), ...
    "Fixed-SNR truth must use normalized fading without geometry loss.");
assert(string(scfg.get("harq.validation_mode")) == "exercise", ...
    "700 MHz truth preset must exercise HARQ retransmissions.");
assert(logical(scfg.get("control.repetition_enabled")), ...
    "700 MHz truth preset must enable PDCCH repetition.");
assert(logical(scfg.get("control.detection_feedback_enabled")), ...
    "700 MHz truth preset must enable detection feedback.");
assert(logical(scfg.get("random_access.beam_clustering_enabled")) && logical(scfg.get("random_access.ro_clustering_enabled")), ...
    "700 MHz truth preset must enable supported clustering features.");
assert(string(scfg.get("energy_efficiency.sleep_state_model")) == "micro_sleep", ...
    "700 MHz truth preset must enable a nontrivial sleep-state model.");
assert(string(scfg.get("energy_efficiency.bandwidth_adaptation_mode")) == "bwp_like", ...
    "700 MHz truth preset must enable supported bandwidth adaptation.");
assert(~logical(scfg.get("ai_ml.fallback_enabled")), ...
    "700 MHz truth preset must explicitly disable AI fallback for strict no-proxy truth.");
assert(logical(scfg.get("sweeps_and_matrix.snr_sweep.enabled")), ...
    "700 MHz truth preset must enable the explicit SNR sweep.");
snrSweepValues = double(scfg.get("sweeps_and_matrix.snr_sweep.values_db"));
assert(isequal(snrSweepValues(:).', [-30, -20, -10, 0, 10, 20, 30, 40]), ...
    "700 MHz truth preset must use the standardized coarse truth SNR sweep [-30:10:40].");
assert(logical(sixgr.util.structGet(cfg, "run.noProxyTruthContract", false)), ...
    "Internal config must enforce the no-proxy truth contract.");
assert(logical(resolvedProfile.Valid), ...
    "700 MHz truth preset must resolve a valid NR MCS profile.");
assert(string(cfg.phy.pdsch.modulation) == string(resolvedProfile.Modulation) && ...
    abs(double(cfg.phy.pdsch.codeRate) - double(resolvedProfile.TargetCodeRate)) < 1e-9, ...
    "Internal config must derive the DL fixed-MCS modulation and code rate from the resolved NR MCS profile.");
assert(string(cfg.phy.pusch.modulation) == string(resolvedProfile.Modulation) && ...
    abs(double(cfg.phy.pusch.codeRate) - double(resolvedProfile.TargetCodeRate)) < 1e-9, ...
    "Internal config must derive the UL fixed-MCS modulation and code rate from the resolved NR MCS profile.");
assert(string(sixgr.util.structGet(cfg, "phy.harq.validationMode", "")) == "exercise", ...
    "Internal config must propagate HARQ exercise mode.");
assert(string(sixgr.util.structGet(cfg, "phy.linkAdaptation.mode", "")) == "fixed", ...
    "Internal config must propagate the fixed nominal operating point.");
assert(string(cfg.phy.pdsch.executionProfile) == "phy_calibration" && ...
    string(cfg.phy.pusch.executionProfile) == "phy_calibration", ...
    "DL and UL calibration ownership must be resolved from YAML.");
assert(isequal(double(cfg.phy.pdsch.SymbolAllocation), [2 12]) && ...
    isequal(double(cfg.phy.pusch.SymbolAllocation), [0 14]) && ...
    numel(cfg.phy.pdsch.PRBSet) == 106 && numel(cfg.phy.pusch.PRBSet) == 106, ...
    "YAML must own the complete DL/UL time-frequency allocation.");
assert(logical(cfg.rf.hardware.agc.enabled) && ...
    double(cfg.rf.hardware.adc.resolutionBits) == 12 && ...
    abs(double(cfg.rf.hardware.adc.fullScale) - 1) < eps, ...
    "An explicit AGC/ADC profile must protect the physical-power waveform from ADC clipping.");

coupledPaths = [ ...
    string(fullfile(pwd, "simulator", "configs", "scenarios", ...
        "lls_700mhz_20mhz_multiuser_macro_amc.yaml"))
    string(fullfile(pwd, "simulator", "configs", "scenarios", ...
        "lls_700mhz_20mhz_3bs_30ue_tdlc_browser_coupled.yaml"))];
for i = 1:numel(coupledPaths)
    coupledScenario = sixgr.lls6g.config.loadScenarioConfig(coupledPaths(i));
    coupledCfg = sixgr.lls6g.buildInternalConfig(coupledScenario, ...
        fullfile(tempdir, "lls_700mhz_coupled_profile_probe_" + string(i)));
    assert(string(coupledCfg.phy.pdsch.executionProfile) == "scheduler_truth" && ...
        string(coupledCfg.phy.pusch.executionProfile) == "scheduler_truth", ...
        ["Coupled multi-user descendants must override the fixed-link " + ...
        "phy_calibration profile through YAML for both DL and UL."]);
end

ok = true;
end
