function ok = testLLSOperatingPointAuthority()
%TESTLLSOPERATINGPOINTAUTHORITY Requested CQI and actual grant operating point must stay disambiguated.

setup6GRSimToolkit("Verbose", false);

tmp = tempname;
mkdir(tmp);
c = onCleanup(@() rmdir(tmp, "s")); %#ok<NASGU>

scfg = sixgr.lls6g.config.loadScenarioConfig( ...
    fullfile(pwd, "simulator", "configs", "scenarios", "lls_700mhz_20mhz_3bs_30ue_tdlc_browser_coupled.yaml"));
cfg = sixgr.lls6g.buildInternalConfig(scfg, fullfile(tmp, "run"));
cfg.run.numFrames = 1;
cfg.channel.snr_dB = 10;
cfg.channel.model = "AWGN";
cfg.channel.awgnOnly = true;
cfg.run.noiseOperatingMode = "configured_snr_anchor_after_large_scale_gain";
cfg.run.interferenceExecutionMode = "none";

multiUser = struct("Enabled", true, "NumUsers", 1, "RNTIStart", 320, "ExecutionModel", "slot_coupled_truth");
state = sixgr.truth.CoupledTruthRuntime.initialize(cfg, fullfile(tmp, "runtime"), multiUser, struct(), 1);
state.CurrentServingIdx(1) = 1;
state.CurrentServingMetric_dBm(1) = -70;
state.CurrentSlot = 1;
state.CurrentFrame = 1;
state.CurrentSNR_dB = 10;
state.LargeScaleState.BeamIndex(1,1) = 1;
state.LargeScaleState.BeamGain_dB(1,1) = 0;
state.LargeScaleState.RxPower_dBm(1,1) = -70;
state.LargeScaleState.BasePathloss_dB(1,1) = 100;
state.LargeScaleState.Pathloss_dB(1,1) = 100;
state.LargeScaleState.Shadow_dB(1,1) = 0;
state.LargeScaleState.O2I_dB(1,1) = 0;
[cfgDL, state] = sixgr.truth.CoupledTruthRuntime.applyUserContext(cfg, state, 1, "DL");
[cfgUL, state] = sixgr.truth.CoupledTruthRuntime.applyUserContext(cfg, state, 1, "UL");

grant = struct( ...
    "UEIndex", 1, ...
    "RNTI", 320, ...
    "ServingCell", 1, ...
    "CQIUsed", 15, ...
    "RIUsed", 1, ...
    "PMI", 0, ...
    "CRI", 0, ...
    "MCS", 10, ...
    "MCSIndex", 10, ...
    "Modulation", "16QAM", ...
    "TargetCodeRate", 0.33203125, ...
    "MCSTable", "qam64_table1", ...
    "CQITable", "table1", ...
    "AMCMode", "cqi_driven", ...
    "GrantReason", "operating_point_authority_unit_test", ...
    "Frame", 1, ...
    "Slot", 1, ...
    "HARQ", struct());

dl = sixgr.link.runDLPDSCHThroughput(cfgDL, ...
    "NumFrames", 1, ...
    "SNR_dB", 10, ...
    "GrantSnapshot", grant, ...
    "InterferenceBundle", struct([]));
ul = sixgr.link.runULPUSCHThroughput(cfgUL, ...
    "NumFrames", 1, ...
    "SNR_dB", 10, ...
    "GrantSnapshot", grant, ...
    "InterferenceBundle", struct([]));

localAssertOperatingPointAuthority(dl.TrialTable, "DL");
localAssertOperatingPointAuthority(ul.TrialTable, "UL");
ok = true;
end

function localAssertOperatingPointAuthority(T, direction)
assert(istable(T) && height(T) == 1, ...
    "Expected a single %s row for operating-point authority validation.", direction);
requiredVars = {'LinkAdaptationMode','ConfiguredLinkAdaptationMode','ActualMCSSelectionMode','ConfiguredMCSSelectionPolicy', ...
    'SchedulerGrantMCSSelectionMode','RequestedOperatingPointSource', ...
    'WidebandCQI','CQIDerivedMCS','CQIDerivedModulation','CQIDerivedTargetCodeRate','MCS','Modulation','TargetCodeRate', ...
    'MCSAuthority','ModulationAuthority','GrantOperatingPointSource','AppliedOperatingPointSource'};
assert(all(ismember(requiredVars, T.Properties.VariableNames)), ...
    "Raw %s trial row must expose requested/derived/actual operating-point lineage.", direction);
assert(strlength(string(T.LinkAdaptationMode(1))) > 0, ...
    "Raw %s trial row must preserve a non-empty link-adaptation intent label.", direction);
assert(strlength(string(T.ConfiguredLinkAdaptationMode(1))) > 0 && ...
    strcmpi(char(string(T.ConfiguredMCSSelectionPolicy(1))), "cqi_driven") && ...
    strcmpi(char(string(T.RequestedOperatingPointSource(1))), "cqi_link_adaptation"), ...
    "Raw %s trial row must preserve the configured AMC policy separately from the applied runtime source.", direction);
assert(strcmpi(char(string(T.ActualMCSSelectionMode(1))), "scheduler_grant"), ...
    "Raw %s trial row must disclose that the transmitted operating point came from the applied scheduler grant.", direction);
assert(strcmpi(char(string(T.SchedulerGrantMCSSelectionMode(1))), "cqi_driven"), ...
    "Raw %s trial row must preserve the scheduler-grant AMC mode separately from the grant-source authority token.", direction);
assert(~strcmpi(char(string(T.ActualMCSSelectionMode(1))), char(string(T.ConfiguredMCSSelectionPolicy(1)))), ...
    "Raw %s trial row must not relabel configured AMC policy as the actual runtime selection mode.", direction);
assert(strcmpi(char(string(T.MCSAuthority(1))), "scheduler_grant") && ...
    strcmpi(char(string(T.ModulationAuthority(1))), "scheduler_grant") && ...
    strcmpi(char(string(T.GrantOperatingPointSource(1))), "scheduler_grant") && ...
    strcmpi(char(string(T.AppliedOperatingPointSource(1))), "scheduler_grant"), ...
    "Raw %s trial row must not relabel CQI-derived estimates as the applied operating point.", direction);
assert(isfinite(double(T.WidebandCQI(1))) && isfinite(double(T.CQIDerivedMCS(1))) && strlength(string(T.CQIDerivedModulation(1))) > 0, ...
    "Raw %s trial row must preserve the CQI-derived recommendation separately.", direction);
assert(double(T.MCS(1)) == 10 && strcmpi(char(string(T.Modulation(1))), "16QAM"), ...
    "Raw %s trial row must preserve the actual grant-applied operating point separately from CQI-derived recommendations.", direction);
assert(double(T.MCS(1)) == 10 && strcmpi(char(string(T.MCSAuthority(1))), "scheduler_grant") && ...
    strcmpi(char(string(T.ModulationAuthority(1))), "scheduler_grant"), ...
    "Raw %s trial row must preserve the actual grant-applied operating point even when the CQI-derived recommendation may coincide.", direction);
end
