function ok = testFourStepRARuntimeStageComposer()
%TESTFOURSTEPRARUNTIMESTAGECOMPOSER Coupled RA composes strict runtime waveforms.
cfg = raStrictAnchorConfig();
res = sixgr.truth.CoupledTruthRuntime.runFourStepRARuntime(cfg, ...
    "RunId", "test_ra_runtime_stage_composer", ...
    "UEId", 1, "CellId", 1, "AttemptId", 1, ...
    "RuntimeSlot", 0, ...
    "RequireRuntimeStageWaveforms", true, ...
    "WriteArtifacts", false);

assert(logical(res.RACompleted) && logical(res.StrictOk), ...
    "Coupled runtime RA must complete Msg1-Msg4 when composing strict stage waveforms.");
assert(logical(res.RuntimeStageWaveformsRequired), ...
    "The result must disclose that strict runtime stage waveforms were required.");
assert(logical(res.RuntimeStageWaveformsUsed), ...
    "The coupled composer must mark the propagated stage waveforms as consumed.");
assert(logical(res.RuntimeChannelStateUsed), ...
    "Composed RA stage waveforms must traverse the runtime channel-state transport.");
assert(~logical(res.RuntimeSelfLoopWaveformsUsed), ...
    "Strict coupled RA stage composition must not fall back to self-loop waveforms.");
assert(string(res.RuntimeTransportMode) == "coupled_runtime_stage_waveform_composer", ...
    "Runtime transport mode must disclose coupled stage-waveform composition.");

T = res.ArtifactTables.ra_runtime_stage_waveforms;
expectedStages = ["Msg1","Msg2","Msg3","Msg4","RRCSetupComplete"];
assert(height(T) == numel(expectedStages), ...
    "Strict runtime RA must publish one composed transport row per waveform-carried message.");
assert(isequal(string(T.StageName).', expectedStages), ...
    "Strict runtime RA stages must include ordered Msg1-Msg4 and RRCSetupComplete.");
assert(all(logical(T.RuntimeStageWaveformUsed)), ...
    "Every RA stage must consume a composed propagated waveform.");
assert(all(logical(T.RuntimeChannelStateUsed)), ...
    "Every composed RA stage must be backed by runtime channel state.");
assert(~any(logical(T.SelfLoopWaveformUsed)), ...
    "No composed RA stage may use direct TX self-loop samples.");
assert(all(string(T.WaveformSource) == "coupled_runtime_stage_waveform_composer"), ...
    "Strict composed RA stages must identify their waveform source.");
assert(any(contains(string(T.RuntimeChannelLinkKey), "dir=UL")) && ...
    any(contains(string(T.RuntimeChannelLinkKey), "dir=DL")), ...
    "Strict composed RA must use both UL and DL persistent link keys.");
ok = true;
end
