function ok = testLLSMeasurementSidecarIntegrity()
%TESTLLSMEASUREMENTSIDECARINTEGRITY Keep measurements separate from labels.

tmp = tempname;
mkdir(tmp);
c = onCleanup(@() rmdir(tmp, "s")); %#ok<NASGU>

layout = sixgr.report.resultLayout(tmp);
sixgr.util.ensureFolder(layout.AirInterfaceCSVDir);
sixgr.util.ensureFolder(layout.ReportCSVDir);

rawT = table( ...
    ["DL"; "DL"], [1; 1], [3; 4], [101; 102], ...
    [12.5; NaN], [true; false], ...
    [11.0; 9.5], [NaN; NaN], [true; true], ...
    ["PASS"; "FAIL"], ...
    ["available_runtime_abstraction"; "unavailable"], ...
    ["system_level_scheduler_grant_trace"; "proxy_debug_only"], ...
    'VariableNames', {'Direction','Frame','Slot','UEID', ...
    'PostEqSINR_dB','CRCPass','SystemLevelSINR_dB', ...
    'DecoderTruthProxySINR_dB','ControlObservationAvailable', ...
    'Status','ValueStatus','ValueSource'});
sixgr.util.csvWriteTable(fullfile(layout.AirInterfaceCSVDir, "dl_pdsch_trials.csv"), rawT);

bindingT = table( ...
    ["frame.scs_khz"; "frequency.bandwidth_hz"], ...
    ["Carrier_Numerology_Grid"; "Carrier_Numerology_Grid"], ...
    ["30"; ""], ["30"; "100000000"], ...
    ["measured_runtime_evidence_published"; "evidence_not_applicable"], ...
    'VariableNames', {'ParameterId','FeatureFamily','RuntimeAppliedEvidenceValue', ...
    'RuntimeMeasuredEvidenceValue','RuntimeMeasuredStatus'});
sixgr.util.csvWriteTable(fullfile(layout.ReportCSVDir, "parameter_binding_matrix.csv"), bindingT);

out = sixgr.truth.exportLLSMeasurementSidecars(tmp);
assert(logical(out.Ok), "Measurement-sidecar audit must pass for split measurement views.");

measurementPath = fullfile(layout.ReportCSVDir, "measurements", "dl_pdsch_measurements.csv");
provenancePath = fullfile(layout.ReportCSVDir, "provenance_sidecars", "dl_pdsch_provenance.csv");
tracePath = fullfile(layout.ReportCSVDir, "measurements", "parameter_binding_runtime_values.csv");
assert(exist(measurementPath, "file") == 2, "DL measurement view must be written.");
assert(exist(provenancePath, "file") == 2, "DL provenance sidecar must be written.");
assert(exist(tracePath, "file") == 2, "Parameter traceability value view must be written.");

measurementT = readtable(measurementPath, "VariableNamingRule", "preserve", "TextType", "string");
provenanceT = readtable(provenancePath, "VariableNamingRule", "preserve", "TextType", "string");
traceT = readtable(tracePath, "VariableNamingRule", "preserve", "TextType", "string");

assert(all(ismember(["Direction","Frame","Slot","UEID","PostEqSINR_dB","CRCPass"], string(measurementT.Properties.VariableNames))), ...
    "Measurement view must preserve keys and measured numeric/boolean columns.");
assert(~any(ismember(["Status","ValueStatus","ValueSource"], string(measurementT.Properties.VariableNames))), ...
    "Measurement view must not carry status/source provenance columns.");
assert(~any(ismember(["SystemLevelSINR_dB","DecoderTruthProxySINR_dB", ...
        "ControlObservationAvailable"], string(measurementT.Properties.VariableNames))), ...
    "Measurement view must not carry proxy/system-level/availability evidence columns.");
assert(~localTableContainsToken(measurementT, ["available_runtime_abstraction","unavailable","proxy"]), ...
    "Measurement view must not carry label/proxy/unavailable tokens.");
assert(all(ismember(["Status","ValueStatus","ValueSource", ...
        "SystemLevelSINR_dB","DecoderTruthProxySINR_dB", ...
        "ControlObservationAvailable"], string(provenanceT.Properties.VariableNames))) && ...
    localTableContainsToken(provenanceT, ["available_runtime_abstraction","unavailable","proxy"]), ...
    "Provenance sidecar must retain label/source diagnostics.");
assert(any(string(traceT.ParameterId) == "frame.scs_khz" & ...
    string(traceT.ValueKind) == "RuntimeAppliedEvidenceValue" & string(traceT.Value) == "30"), ...
    "Parameter traceability value view must preserve runtime-applied values without status columns.");

ok = true;
end

function tf = localTableContainsToken(T, tokens)
tf = false;
tokens = lower(string(tokens(:)));
vars = string(T.Properties.VariableNames);
for v = vars
    vals = lower(string(T.(char(v))));
    for token = tokens.'
        if any(contains(vals, token))
            tf = true;
            return;
        end
    end
end
end
