function ok = testRAArtifactSchemas()
tmp = tempname;
cfg = raStrictAnchorConfig();
cfg.random_access.pathloss_dB = 80;
res = sixgr.phy.ra.runFourStepRA(cfg, ...
    "RunFolder", tmp, "RunId", "test_ra_artifacts", "WriteArtifacts", true);
assert(logical(res.StrictOk), "Artifact schema test requires a strict successful RA run.");
csvDir = fullfile(tmp, "control", "csv");
required = ["ra_attempts.csv","ra_state_transitions.csv","msg1_prach_detection.csv", ...
    "msg2_rar_trials.csv","msg2_pdcch_candidates.csv","msg3_pusch_trials.csv", ...
    "msg4_contention_resolution.csv","msg4_trials.csv","ra_timer_events.csv","ra_negative_trials.csv", ...
    "ra_collision_trials.csv","ra_oracle_guard.csv","ra_runtime_stage_waveforms.csv"];
for ii = 1:numel(required)
    path = fullfile(csvDir, required(ii));
    assert(exist(path, "file") == 2, "Missing RA artifact: %s", path);
    T = readtable(path, "TextType", "string");
    if ~any(required(ii) == ["ra_negative_trials.csv","ra_collision_trials.csv"])
        assert(height(T) > 0, "Required positive RA artifact must have rows: %s", required(ii));
    end
end
attempts = readtable(fullfile(csvDir, "ra_attempts.csv"), "TextType", "string");
assert(all(ismember(["RunId","RABindingSource","RARBytesHex","Msg3ContentionIdentity", ...
    "PowerPathloss_dB","PowerPathlossSource","PreambleRequestedTxPower_dBm", ...
    "PreambleTxPower_dBm","Msg3RequestedTxPower_dBm","Msg3TxPower_dBm", ...
    "FailureReason","UsedOracleFields","StrictOk"], string(attempts.Properties.VariableNames))), ...
    "ra_attempts.csv schema is missing required columns.");
msg1 = readtable(fullfile(csvDir, "msg1_prach_detection.csv"), "TextType", "string");
assert(all(ismember(["PowerPathloss_dB","PreambleRequestedTxPower_dBm", ...
    "PreambleTxPower_dBm","PreambleTxAmplitudeScale"], string(msg1.Properties.VariableNames))), ...
    "msg1_prach_detection.csv schema is missing PRACH power-control columns.");
msg3 = readtable(fullfile(csvDir, "msg3_pusch_trials.csv"), "TextType", "string");
assert(all(ismember(["Msg3Pathloss_dB","Msg3RequestedTxPower_dBm", ...
    "Msg3TxPower_dBm","Msg3TxAmplitudeScale"], string(msg3.Properties.VariableNames))), ...
    "msg3_pusch_trials.csv schema is missing Msg3 power-control columns.");
runtimeStages = readtable(fullfile(csvDir, "ra_runtime_stage_waveforms.csv"), "TextType", "string");
assert(all(ismember(["StageName","Direction","WaveformSource","RuntimeTransportMode", ...
    "RuntimeChannelStateUsed","SelfLoopWaveformUsed"], string(runtimeStages.Properties.VariableNames))), ...
    "ra_runtime_stage_waveforms.csv schema is missing runtime transport evidence columns.");
figDir = fullfile(tmp, "reports", "figures");
figs = ["ra_procedure_timeline.png","msg1_prach_correlation.png","msg2_rar_pdcch_candidates.png", ...
    "msg3_pusch_constellation.png","msg4_contention_resolution_flow.png","ra_collision_outcome.png"];
for ii = 1:numel(figs)
    assert(exist(fullfile(figDir, figs(ii)), "file") == 2, "Missing RA figure: %s", figs(ii));
end
ok = true;
end
