function ok = testExplicitHARQReplayAuthority()
%TESTEXPLICITHARQREPLAYAUTHORITY TB context does not imply retransmission.

setup6GRSimToolkit("Verbose", false, "RunToolboxChecks", false);
tbContext = struct("TBSBits", 1024, "NDI", true, ...
    "OriginalNumLayers", 2);
newGrant = struct("Direction", "DL", "NumLayers", 2, "Layers", 2, ...
    "IsRetransmission", false, ...
    "HARQ", struct("IsRetransmission", false, "NDI", true), ...
    "HARQTBContext", tbContext);
newPHY = struct("HARQProcessKey", struct("IsRetransmission", false));
newContext = struct("IsRetransmission", false, ...
    "TransportBlockContext", tbContext);
assert(~sixgr.phy.grant.isExplicitHARQRetransmission( ...
    newGrant, newPHY, newContext), ...
    "A current-TB context and matching NDI must not relabel new data as HARQ replay.");

retxGrant = newGrant;
retxGrant.IsRetransmission = true;
assert(sixgr.phy.grant.isExplicitHARQRetransmission( ...
    retxGrant, newPHY, newContext), ...
    "An explicit scheduler retransmission flag must authorize HARQ replay.");
retxGrant.IsRetransmission = false;
retxContext = newContext;
retxContext.IsRetransmission = true;
assert(sixgr.phy.grant.isExplicitHARQRetransmission( ...
    retxGrant, newPHY, retxContext), ...
    "An explicit HARQ-context retransmission flag must authorize replay.");

ok = true;
end
