function ok = testLLSMultiUserSummaryRuntimeArtifacts()
%TESTLLSMULTIUSERSUMMARYRUNTIMEARTIFACTS Verify truthful user-summary status fields on the active LLS export path.

setup6GRSimToolkit("Verbose", false);

tmp = tempname;
mkdir(tmp);
c = onCleanup(@() rmdir(tmp, "s")); %#ok<NASGU>

baseScenario = fullfile(pwd, "simulator", "configs", "scenarios", "lls_700mhz_20mhz_3bs_30ue_tdlc_browser_coupled.yaml");
scenarioPath = fullfile(tmp, "__lls_multiuser_user_summary_focus.yaml");
fid = fopen(scenarioPath, "w");
assert(fid >= 0, "Unable to create focused multi-user user-summary scenario file.");
fprintf(fid, "%s", ['{' ...
    '"inherits":["' strrep(baseScenario, '\', '\\') '"],' ...
    '"meta":{"scenario_id":"lls_multiuser_user_summary_runtime_artifacts","description":"focused multi-user summary semantics test","version":"1","owner":"test","maturity_tag":"experimental"},' ...
    '"simulation":{"n_frames":4,"n_slots":1,"n_subframes":1,"monte_carlo_iterations":1,"random_seed":73051,"snr_db":8,"snr_sweep_offsets_db":[0],"noise_operating_mode":"configured_snr_anchor_after_large_scale_gain"},' ...
    '"run_control":{"execution_mode":"LLS","num_workers":1},' ...
    '"deployment_topology":{"inter_site_distance":640,"num_cells":3,"num_ues":4,"num_trps":3},' ...
    '"mobility":{"ue_speed_kmh":42,"trajectory_model":"zigzag","update_period_s":0.001},' ...
    '"mimo":{"n_tx_ant":4,"n_rx_ant":2},' ...
    '"antenna_and_array":{"bs_num_antenna_elements":4,"ue_num_antenna_elements":2,"element_spacing_h":0.75,"element_spacing_v":0.5,"polarization":"single"},' ...
    '"channels":{"doppler_source_mode":"derive_from_ue_speed","mobility_kmph":42},' ...
    '"interference":{"inter_cell_execution_mode":"full_per_link_channel_waveform_sum"},' ...
    '"users":{"enabled":true,"n_users":4,"execution_model":"slot_coupled_truth","beam_selection_strategy":"fixed_first_beam","save_user_tables":true},' ...
    '"output":{"backend":"filesystem","profile":"lls_multiuser_user_summary_runtime_artifacts","save_figures":false,"save_png":false,"save_mat":false}}']);
fclose(fid);

out = run_6g_phy_lls_single(scenarioPath, tmp, "summary");
assert(out.Ok, "Focused multi-user user-summary semantics run should complete.");

runFolder = char(string(out.RunFolder));
summaryFile = fullfile(runFolder, "air_interface", "csv", "multiuser_user_summary.csv");
assert(exist(summaryFile, "file") == 2, "Focused LLS run must emit multiuser_user_summary.csv.");

summaryT = readtable(summaryFile, "VariableNamingRule", "preserve");
assert(istable(summaryT) && ~isempty(summaryT), ...
    "Focused LLS run must populate multiuser_user_summary.csv.");

requiredVars = { ...
    'ObservedRowCount','SummaryRowValid','RuntimeDataPresent','UserHadAnySuccessfulTx', ...
    'UserHadAnySuccessfulRx','PartialSuccess','AllObservedRowsSuccessful','SummaryStatus', ...
    'Ok','OkDefinition','Throughput_Mbps','PassRate','BLER'};
assert(all(ismember(requiredVars, summaryT.Properties.VariableNames)), ...
    "multiuser_user_summary.csv must expose truthful row-validity and partial-success fields.");

assert(all(strcmp(string(summaryT.OkDefinition), "compatibility_alias_of_summary_row_valid")), ...
    "User summary CSV must disclose the compatibility Ok meaning.");
assert(all(logical(summaryT.Ok) == logical(summaryT.SummaryRowValid)), ...
    "Compatibility Ok must match SummaryRowValid for every multi-user summary row.");

runtimeMask = logical(summaryT.RuntimeDataPresent);
assert(any(runtimeMask), "Focused LLS run must produce at least one runtime-backed multi-user summary row.");
assert(all(logical(summaryT.SummaryRowValid(runtimeMask))), ...
    "Runtime-backed user summary rows must be marked valid.");
assert(all(logical(summaryT.Ok(runtimeMask))), ...
    "Runtime-backed user summary rows must not be mislabeled with Ok=0.");

throughputMask = runtimeMask & isfinite(double(summaryT.Throughput_Mbps)) & (double(summaryT.Throughput_Mbps) > 0);
if any(throughputMask)
    assert(all(logical(summaryT.Ok(throughputMask))), ...
        "Rows with real throughput must not be mislabeled as invalid or unsuccessful summaries.");
    assert(all(logical(summaryT.UserHadAnySuccessfulTx(throughputMask))) & all(logical(summaryT.UserHadAnySuccessfulRx(throughputMask))), ...
        "Rows with real throughput must preserve successful-transfer semantics.");
end

partialMask = runtimeMask & isfinite(double(summaryT.PassRate)) & ...
    double(summaryT.PassRate) > 0 & double(summaryT.PassRate) < 1;
if any(partialMask)
    assert(all(logical(summaryT.PartialSuccess(partialMask))), ...
        "Rows with mixed pass/fail observations must export PartialSuccess=true.");
    assert(all(strcmpi(string(summaryT.SummaryStatus(partialMask)), "partial_success")), ...
        "Rows with mixed pass/fail observations must export partial_success summary status.");
    assert(all(~logical(summaryT.AllObservedRowsSuccessful(partialMask))), ...
        "Rows with mixed pass/fail observations must not claim all-success semantics.");
end

allSuccessMask = runtimeMask & isfinite(double(summaryT.PassRate)) & abs(double(summaryT.PassRate) - 1) < 1e-9;
if any(allSuccessMask)
    assert(all(logical(summaryT.AllObservedRowsSuccessful(allSuccessMask))), ...
        "Rows with pass rate 1 must export all-success semantics.");
    assert(all(strcmpi(string(summaryT.SummaryStatus(allSuccessMask)), "all_success")), ...
        "Rows with pass rate 1 must export all_success summary status.");
end

allFailedMask = runtimeMask & isfinite(double(summaryT.PassRate)) & abs(double(summaryT.PassRate)) < 1e-9 & ...
    ~logical(summaryT.UserHadAnySuccessfulTx);
if any(allFailedMask)
    assert(all(strcmpi(string(summaryT.SummaryStatus(allFailedMask)), "all_failed")), ...
        "Rows with no successful transfers must export all_failed summary status.");
end

ok = true;
end
