function ok = testFRCMultiLayerPDSCHReceiverBundle()
%TESTFRCMULTILAYERPDSCHRECEIVERBUNDLE Prove rank-4 FRC Tx/Rx ownership.

setup6GRSimToolkit("Verbose", false);

if exist("nrPDSCH", "file") ~= 2 || exist("nrTDLChannel", "file") ~= 2
    warning("testFRCMultiLayerPDSCHReceiverBundle:Missing5G", ...
        "Skipping the rank-4 FRC waveform regression because 5G Toolbox APIs are unavailable.");
    ok = true;
    return;
end

result = sixgr.conformance.runFRCPoint( ...
    "dl_r_pdsch_1_2_4_fdd_tdla30_10", ...
    "tdla30_10_ula_low_4x4", ...
    "SNRGrid_dB", 15.6, ...
    "ExecutionProfile", "smoke", ...
    "MinTransportBlocks", 1, ...
    "MaxTransportBlocks", 1, ...
    "BatchSize", 1, ...
    "MinimumBlockErrors", 0, ...
    "EvaluateSymmetricRegression", false, ...
    "ChannelChunkSlots", 1, ...
    "RequireExactDataChannelExecution", true, ...
    "AssertPass", false, ...
    "PrintTable", false, ...
    "Verbose", false);

assert(logical(result.DataChannelExecution.Exact) && ...
    isempty(result.DataChannelExecution.Blockers), ...
    "The rank-4 fading FRC must be exact at the data-channel boundary.");
assert(height(result.Sweep) == 1 && ...
    double(result.Sweep.TransportBlocks(1)) == 1, ...
    "The focused regression must execute exactly one genuine transport block.");
detail = result.PointDetails{1};
application = detail.Propagation.ChannelApplication;
assert(detail.ChannelChunkSlots == 1 && ...
    detail.Propagation.ChannelChunkSamples > 0 && ...
    application.Mode == "streamed_complete_sequence" && ...
    application.ChannelCallCount > 1 && ...
    application.FullSequenceProcessed && ...
    ~application.ProxyUsed && ~application.FallbackUsed, ...
    ["The rank-4 fading FRC must process its complete standard frame " ...
    "through the exact stateful streamed TDL path."]);
assert(double(detail.FirstTransmission.PrecodingPower.NumLayers) == 4, ...
    "The FRC transmitter did not execute four PDSCH layers.");
assert(logical(detail.LastReceiver.CalibrationReceiverBundleReused), ...
    "The receiver must reuse the immutable transmitter calibration " + ...
    "bundle after proving base-grid ownership on every layer.");
assert(~logical(detail.ProxyUsed) && ~logical(detail.FallbackUsed) && ...
    ~logical(detail.TruthUnavailableRescueUsed), ...
    "The rank-4 FRC receiver regression must not use proxy or fallback data.");

fprintf("FRCMultiLayerPDSCHReceiverBundle: rank-4 exact Tx/Rx ownership verified.\n");
ok = true;
end
