function ok = testAgendaMeasurementExports()
% Verify requested measurement content is sourced from executed evidence.
setup6GRSimToolkit("Verbose", false);
tmp = tempname;
mkdir(tmp);
cleanup = onCleanup(@() localCleanup(tmp)); %#ok<NASGU>

scenarioPath = fullfile("simulator", "configs", "scenarios", ...
    "lls_tdd_5mhz_rank2_4tx2rx_awgn_0db.yaml");
scfg = sixgr.lls6g.config.loadScenarioConfig(scenarioPath);
cfg = sixgr.lls6g.buildInternalConfig(scfg, tmp);
layout = sixgr.report.resultLayout(tmp);
folders = [string(layout.AirInterfaceCSVDir), string(layout.HARQCSVDir), ...
    string(layout.PacketFlowCSVDir), string(layout.ReportCSVDir), ...
    string(layout.BeamformingCSVDir)];
for folder = folders, sixgr.util.ensureFolder(folder); end

dl = table([1;0], [0;50], [100;100], [0.12;0.12], [0.01;0.02], ...
    [2;2], [1000;1000], [0;1], [1;0], [20;20], ...
    'VariableNames', {'CRCPass','BitErrors','BitsCompared','RSOverheadFraction', ...
    'EVM_rms','Layers','TBSize_bits','HARQAttempt','CurrentDecodeOK','ActualEmittedPower_dBm'});
sixgr.util.csvWriteTable(fullfile(layout.AirInterfaceCSVDir, "dl_pdsch_trials.csv"), dl);
sixgr.util.csvWriteTable(fullfile(layout.AirInterfaceCSVDir, "ul_pusch_trials.csv"), dl);

pbch = table([-3;-4], ["[-10 -11]";"[-9 -12]"], [5;6], ["PASS";"PASS"], ...
    'VariableNames', {'SS_RSRP_dB_re_UnitOccupiedRE_Es', ...
    'SSBWindowReferenceRSRQPerReceiveAntenna_dB','SS_SINR_dB','Status'});
sixgr.util.csvWriteTable(fullfile(layout.AirInterfaceCSVDir, "pbch_trials.csv"), pbch);
prach = table([7;7], [7;8], [1;1], [1;2], ["PASS";"FAIL"], ...
    'VariableNames', {'RequestedPreambleIndex','DetectedPreambleIndex', ...
    'PreambleDetected','PreambleAttemptNumber','Status'});
sixgr.util.csvWriteTable(fullfile(layout.AirInterfaceCSVDir, "prach_trials.csv"), prach);
pdcch = table([1;0], ["PASS";"FAIL"], 'VariableNames', ...
    {'PDCCHCausalGrantDecodeOk','Status'});
sixgr.util.csvWriteTable(fullfile(layout.AirInterfaceCSVDir, "pdcch_trials.csv"), pdcch);
pucch = table([1;0], [0;1], [0;0], [0;1], [0;1], [11;11], ...
    'VariableNames', {'UCIContentMatch','FalseAck','ExpectedAck','DTXFlag','DecodedAck','BitsCompared'});
sixgr.util.csvWriteTable(fullfile(layout.AirInterfaceCSVDir, "pucch_trials.csv"), pucch);
csirs = table([-2;-1], [-10;-9], [4;5], [3;4], [18;20], [1;2], [0;0], ...
    'VariableNames', {'MeasurementRelativeRSRP_dB','MeasurementRSRQ_dB', ...
    'ReferenceMeasuredSINR_dB','CQI','PMI','RI','CRI'});
sixgr.util.csvWriteTable(fullfile(layout.AirInterfaceCSVDir, "csi_rs_trials.csv"), csirs);
csiFeedback = table([0.002;0.004], 'VariableNames', {'CSIAgeSeconds'});
sixgr.util.csvWriteTable(fullfile(layout.AirInterfaceCSVDir, "csi_feedback_reports.csv"), csiFeedback);
srs = table(["PASS";"PASS"], 'VariableNames', {'Status'});
sixgr.util.csvWriteTable(fullfile(layout.AirInterfaceCSVDir, "srs_trials.csv"), srs);

timeline = table(["DL";"DL";"UL"], ["p1";"p1";"p2"], [1;2;1], ...
    [0;1;1], [0;1;1], [0;1;0], [1000;1000;800], [1;1;1], [0;0;0], [0;0;0], ...
    'VariableNames', {'Direction','PacketID','Attempt','CurrentDecodeOK', ...
    'CombinedDecodeOK','IsRetransmission','TBSize_bits','FeedbackObservationAvailable', ...
    'FeedbackApplied','FeedbackStaleIgnored'});
sixgr.util.csvWriteTable(fullfile(layout.HARQCSVDir, "harq_process_timeline.csv"), timeline);
ledger = table(["DL";"UL"], [1;0], 'VariableNames', {'Direction','DeliverySuccess'});
sixgr.util.csvWriteTable(fullfile(layout.PacketFlowCSVDir, ...
    "live_application_packet_delivery_ledger.csv"), ledger);
power = table([0.1;0.3], 'VariableNames', {'cumulative_energy_j'});
sixgr.util.csvWriteTable(fullfile(layout.ReportCSVDir, "live_power_runtime_table.csv"), power);
occupancy = table([24;48], 'VariableNames', {'occupancy_value'});
sixgr.util.csvWriteTable(fullfile(layout.ReportCSVDir, ...
    "contract__air-interface-frame-slot-symbol-grid__re-occupancy-heatmap.csv"), occupancy);
beamState = table([0;1], 'VariableNames', {'BeamFailureFlag'});
sixgr.util.csvWriteTable(fullfile(layout.BeamformingCSVDir, "beam_management_state_trace.csv"), beamState);
beamEvents = table([1;0], [0.005;NaN], 'VariableNames', {'FailureEventFlag','SwitchLatency_s'});
sixgr.util.csvWriteTable(fullfile(layout.BeamformingCSVDir, "beam_management_event_trace.csv"), beamEvents);

manifest = struct("CodeVersion", "test", "CodeDetail", "agenda_measurements", ...
    "RandomSeed", 1, "GeneratedUTC", "test", "RunnerProfile", "test", ...
    "RunCompletion", "completed", "DeterministicMode", "test");
out = sixgr.truth.exportLLSReportingBundle(tmp, scfg, cfg, struct("Ok", true), ...
    manifest, struct("StartedUTC", "test", "ElapsedSeconds", 1), struct());
rows = out.CategoryRows;
requiredObserved = ["initial_transmission_bler","residual_bler", ...
    "undetected_block_error_probability","resource_occupancy", ...
    "grant_failure_probability","uci_block_error_rate","nack_to_ack_probability", ...
    "dtx_to_ack_probability","uplink_drop_probability","csi_rsrp","csi_rsrq", ...
    "csi_sinr","cqi","pmi","ri","cri","csi_age","beam_outage", ...
    "ss_rsrp","ss_rsrq","ss_sinr","wrong_identity_probability", ...
    "access_attempt_count","feedback_association_error","retransmission_cost", ...
    "total_device_energy"];
for key = requiredObserved
    selected = rows(rows.MetricKey == key, :);
    assert(~isempty(selected) && any(selected.CountsTowardCoverage), ...
        "Requested measurement did not retain executed evidence: %s", key);
end
assert(all(rows.Availability(rows.MetricKey == "cli_rssi") == "disabled"));
assert(all(rows.Availability(rows.MetricKey == "unused_reserved_resources") == "disabled"));
assert(~any(rows.CountsTowardCoverage(rows.MetricKey == "srs_rsrp")), ...
    "Missing SRS-RSRP must remain unavailable rather than becoming a synthetic zero.");
ok = true;
end

function localCleanup(path)
if exist(path, "dir") == 7
    rmdir(path, "s");
end
end
