classdef CanonicalScenarioRunner
    %CANONICALSCENARIORUNNER Fresh-run authority for mandatory scenarios.
    methods (Static)
        function result=run(scenarios,outputDir,executor)
            scenarios=string(scenarios(:));
            if isempty(scenarios)
                error("sixgr:validation:CanonicalScenarioNotExecuted", ...
                    "At least one canonical scenario is required.");
            end
            if nargin<3 || ~isa(executor,"function_handle")
                error("sixgr:validation:CanonicalScenarioNotExecuted", ...
                    "Canonical scenarios require a production executor.");
            end
            sixgr.util.ensureFolder(outputDir);
            rows=repmat(struct("ScenarioID","","Tier","SMOKE","RunID","", ...
                "RunClass","","SourceCommit","","ScenarioSHA256","", ...
                "StartUTC","","EndUTC","","RuntimeStatus","FAIL", ...
                "ArtifactStatus","FAIL","Status","FAIL"),numel(scenarios),1);
            runIDs=strings(numel(scenarios),1);
            for index=1:numel(scenarios)
                scenario=scenarios(index);
                if ~isfile(scenario)
                    error("sixgr:validation:CanonicalScenarioNotExecuted", ...
                        "Canonical scenario is missing: %s.",scenario);
                end
                startUTC=string(datetime("now","TimeZone","UTC", ...
                    "Format","yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"));
                execution=executor(scenario,string(outputDir));
                if ~isstruct(execution)
                    error("sixgr:validation:CanonicalScenarioNotExecuted", ...
                        "Scenario executor returned no structured runtime evidence.");
                end
                required=["RunID","RunClass","SourceCommit","ScenarioSHA256", ...
                    "RuntimeStatus","ArtifactStatus"];
                for name=required
                    if ~isfield(execution,char(name))
                        error("sixgr:validation:CanonicalScenarioNotExecuted", ...
                            "Scenario runtime evidence is missing %s.",name);
                    end
                end
                if string(execution.RuntimeStatus)~="PASS" || ...
                        string(execution.ArtifactStatus)~="PASS"
                    error("sixgr:validation:CanonicalScenarioNotExecuted", ...
                        "Canonical scenario %s did not pass.",scenario);
                end
                runIDs(index)=string(execution.RunID);
                [~,scenarioID]=fileparts(scenario);
                rows(index)=struct("ScenarioID",string(scenarioID), ...
                    "Tier","SMOKE","RunID",runIDs(index), ...
                    "RunClass",sixgr.validation.RunClass.parse(execution.RunClass), ...
                    "SourceCommit",string(execution.SourceCommit), ...
                    "ScenarioSHA256",string(execution.ScenarioSHA256), ...
                    "StartUTC",startUTC,"EndUTC",string(datetime("now", ...
                    "TimeZone","UTC","Format","yyyy-MM-dd'T'HH:mm:ss.SSS'Z'")), ...
                    "RuntimeStatus","PASS","ArtifactStatus","PASS","Status","PASS");
            end
            if numel(unique(runIDs))~=numel(runIDs)
                error("sixgr:validation:ArtifactStale", ...
                    "Canonical scenarios reused a RunID.");
            end
            result=struct("Table",struct2table(rows,"AsArray",true), ...
                "Passed",true,"Status","PASS");
        end
    end
end
