classdef CurveComparisonEngine
    %CURVECOMPARISONENGINE Newcombe point and bounded curve decisions.
    methods (Static)
        function result = comparePoint(dutErrors,dutTrials, ...
                referenceErrors,referenceTrials,confidenceLevel,margin)
            if double(dutTrials) == 0 || double(referenceTrials) == 0
                data = struct( ...
                    "DUTEstimate",NaN, ...
                    "ReferenceEstimate",NaN, ...
                    "Difference",NaN,"DifferenceCILow",NaN, ...
                    "DifferenceCIHigh",NaN, ...
                    "EquivalenceMargin",double(margin), ...
                    "EquivalenceVerdict","INCOMPLETE", ...
                    "NonInferiorityVerdict","INCOMPLETE", ...
                    "ConfidenceLevel",double(confidenceLevel));
                result = sixgr.validation.PointComparisonResult(data);
                return;
            end
            dut = sixgr.validation.BinomialIntervalEngine.wilson( ...
                dutErrors,dutTrials,confidenceLevel);
            reference = sixgr.validation.BinomialIntervalEngine.wilson( ...
                referenceErrors,referenceTrials,confidenceLevel);
            delta = dut.Estimate-reference.Estimate;
            deltaLower = delta-sqrt( ...
                (dut.Estimate-dut.Lower)^2 + ...
                (reference.Upper-reference.Estimate)^2);
            deltaUpper = delta+sqrt( ...
                (dut.Upper-dut.Estimate)^2 + ...
                (reference.Estimate-reference.Lower)^2);
            deltaLower = max(-1,deltaLower);
            deltaUpper = min(1,deltaUpper);
            margin = double(margin);
            equivalent = deltaLower >= -margin && deltaUpper <= margin;
            noninferior = deltaUpper <= margin;
            data = struct( ...
                "DUTEstimate",dut.Estimate, ...
                "ReferenceEstimate",reference.Estimate, ...
                "Difference",delta,"DifferenceCILow",deltaLower, ...
                "DifferenceCIHigh",deltaUpper, ...
                "EquivalenceMargin",margin, ...
                "EquivalenceVerdict",localEquivalence(equivalent), ...
                "NonInferiorityVerdict",localNoninferiority(noninferior), ...
                "ConfidenceLevel",double(confidenceLevel));
            result = sixgr.validation.PointComparisonResult(data);
        end
        function result = compareCurve(dut,reference,policy)
            joined = sixgr.validation.OperatingPointJoiner.join(dut,reference);
            minimumOverlap = double(policy.MinimumCurveOverlap);
            if ~joined.Passed || joined.MatchedCount < minimumOverlap
                result = struct("Join",joined, ...
                    "EquivalenceVerdict","INCOMPLETE", ...
                    "NonInferiorityVerdict","INCOMPLETE", ...
                    "PointResults",table(),"Passed",false);
                return;
            end
            dutKeys = localKeys(dut);
            refKeys = localKeys(reference);
            rows = repmat(struct("PointKey","","Difference",NaN, ...
                "DifferenceCILow",NaN,"DifferenceCIHigh",NaN, ...
                "EquivalenceVerdict","","NonInferiorityVerdict",""), ...
                joined.MatchedCount,1);
            matched = joined.Report.PointKey(joined.Report.JoinStatus=="MATCH");
            for index = 1:numel(matched)
                di = find(dutKeys==matched(index),1);
                ri = find(refKeys==matched(index),1);
                point = sixgr.validation.CurveComparisonEngine.comparePoint( ...
                    dut.ErrorCount(di),dut.TrialCount(di), ...
                    reference.ErrorCount(ri),reference.TrialCount(ri), ...
                    policy.ConfidenceLevel,policy.EquivalenceMargin).toStruct();
                rows(index) = struct("PointKey",matched(index), ...
                    "Difference",point.Difference, ...
                    "DifferenceCILow",point.DifferenceCILow, ...
                    "DifferenceCIHigh",point.DifferenceCIHigh, ...
                    "EquivalenceVerdict",point.EquivalenceVerdict, ...
                    "NonInferiorityVerdict",point.NonInferiorityVerdict);
            end
            pointResults = struct2table(rows,"AsArray",true);
            eqPass = all(pointResults.EquivalenceVerdict=="PASS_EQUIVALENT");
            niPass = all(pointResults.NonInferiorityVerdict=="PASS_NONINFERIOR");
            result = struct("Join",joined,"PointResults",pointResults, ...
                "EquivalenceVerdict",localEquivalence(eqPass), ...
                "NonInferiorityVerdict",localNoninferiority(niPass), ...
                "Passed",eqPass&&niPass);
        end
        function verdict = highSNR(errorCount,trialCount,confidenceLevel,target)
            bound = sixgr.validation.BinomialIntervalEngine.exactUpper( ...
                errorCount,trialCount,confidenceLevel);
            if bound.Upper <= double(target)
                verdict = "PASS_NONINFERIOR";
            else
                verdict = "FAIL_INFERIOR";
            end
        end
    end
end

function keys = localKeys(input)
keys = strings(height(input),1);
for index = 1:height(input)
    keys(index) = sixgr.validation.OperatingPointKey.canonical(input(index,:));
end
end
function out = localEquivalence(condition)
if condition, out = "PASS_EQUIVALENT"; else, out = "FAIL_NOT_EQUIVALENT"; end
end
function out = localNoninferiority(condition)
if condition, out = "PASS_NONINFERIOR"; else, out = "FAIL_INFERIOR"; end
end
