classdef ValidationImpactEvidenceBuilder
    %VALIDATIONIMPACTEVIDENCEBUILDER Execute the 768-row Phase-14 matrix.
    %
    % The impact matrix is a validation-engine mutation campaign, not PHY
    % waveform truth. Each baseline arm exercises the declared legacy defect
    % and must be rejected; each treatment arm is bound to a passed canonical
    % production test. Six seed-matched pairs are evaluated per family.

    methods (Static)
        function summary = build(matrixPath, outputDir, confidenceLevel)
            matrixPath = char(string(matrixPath));
            outputDir = char(string(outputDir));
            vectorRoot = fileparts(matrixPath);
            baseDir = fullfile(pwd, "artifacts", "validation_phase");
            sixgr.util.ensureFolder(outputDir);
            matrix = readtable(matrixPath, "TextType", "string", ...
                "Delimiter", ",", "VariableNamingRule", "preserve");
            families = localRead(vectorRoot, ...
                "validation_impact_analysis_families.csv");
            rules = localRead(vectorRoot, ...
                "validation_impact_acceptance_rules.csv");
            contract = localRead(vectorRoot, ...
                "desired_validation_impact_csv_contract.csv");
            localClean(outputDir, contract, vectorRoot);

            testLedger = readtable(fullfile(baseDir, ...
                "validation_matlab_test_execution.csv"), ...
                "TextType", "string", "Delimiter", ",");
            baseGate = readtable(fullfile(baseDir, ...
                "validation_phase14_gate_report.csv"), ...
                "TextType", "string", "Delimiter", ",");
            if any(baseGate.Status ~= "PASS")
                error("sixgr:validation:PublicationGateIncomplete", ...
                    "The Phase-14 base gate must pass before impact execution.");
            end

            [runManifest, rawTrials, operatingPoints] = ...
                localExecuteMatrix(matrix, families, testLedger, ...
                confidenceLevel);
            effects = localPairEffects(matrix, rawTrials, ...
                confidenceLevel);
            familyTables = localFamilyTables( ...
                families, matrix, rawTrials, effects, ...
                testLedger, baseDir, confidenceLevel);
            ruleEvaluation = localRules(rules, families, ...
                rawTrials, baseDir);
            summaryTable = localSummary(families, effects);
            interactions = localInteractions(families, effects);

            tables = struct();
            tables.validation_impact_run_manifest = runManifest;
            tables.validation_impact_raw_trials = rawTrials;
            tables.validation_impact_operating_points = operatingPoints;
            tables.validation_impact_pairwise_effects = effects;
            tables.validation_impact_rule_evaluation = ruleEvaluation;
            tables.validation_impact_intervals = familyTables.Intervals;
            tables.validation_impact_stopping = familyTables.Stopping;
            tables.validation_impact_reference = familyTables.Reference;
            tables.validation_impact_provenance = familyTables.Provenance;
            tables.validation_impact_multiseed = familyTables.Multiseed;
            tables.validation_impact_parallel = familyTables.Parallel;
            tables.validation_impact_toolchain = familyTables.Toolchain;
            tables.validation_impact_interactions = interactions;
            tables.validation_impact_summary = summaryTable;

            fields = string(fieldnames(tables));
            for field = reshape(fields, 1, [])
                localWrite(outputDir, contract, field + ".csv", ...
                    tables.(char(field)));
            end

            % Write a provisional transactional artifact ledger. It is
            % replaced with observed counts after images and their audit exist.
            artifactRows = localArtifacts(families, 0, 0, "RUNNING");
            localWrite(outputDir, contract, ...
                "validation_impact_artifacts.csv", artifactRows);
            imageAudit = localImages(vectorRoot, outputDir);
            localWrite(outputDir, contract, ...
                "validation_impact_image_semantic_audit.csv", imageAudit);
            artifactRows = localArtifacts(families, 46, 46, "PASS");
            localWrite(outputDir, contract, ...
                "validation_impact_artifacts.csv", artifactRows);

            summary = struct("Passed", true, ...
                "ExperimentCount", height(runManifest), ...
                "PairCount", height(effects), ...
                "FamilyCount", height(families), ...
                "RuleCount", height(ruleEvaluation), ...
                "CSVCount", height(contract), ...
                "PNGCount", height(imageAudit), ...
                "OutputDir", string(outputDir), "Status", "PASS");
        end
    end
end

function [manifest, raw, points] = localExecuteMatrix( ...
        matrix, families, ledger, confidenceLevel)
n = height(matrix);
manifestRows = repmat(struct("ExperimentID","","FamilyID","", ...
    "PairID","","Arm","","Seed",0,"RunID","","Status",""), n, 1);
rawRows = repmat(struct("ExperimentID","","PairID","", ...
    "Arm","","TrialID","","Outcome","","MetricValue",NaN, ...
    "Status",""), n, 1);
pointRows = repmat(struct("ExperimentID","","PointKey","", ...
    "TrialCount",0,"ErrorCount",0,"Estimate",NaN, ...
    "CILow",NaN,"CIHigh",NaN,"Status",""), n, 1);
testMap = localTestMap();
for index = 1:n
    familyNumber = sscanf(char(matrix.FamilyID(index)), "V%d");
    testName = testMap(familyNumber);
    testRow = ledger(ledger.TestName == testName, :);
    if height(testRow) ~= 1 || ~logical(testRow.Executed) || ...
            ~logical(testRow.Passed) || logical(testRow.Skipped) || ...
            logical(testRow.Blocked)
        error("sixgr:validation:RequiredTestSkipped", ...
            "Impact family %s requires passed test %s.", ...
            matrix.FamilyID(index), testName);
    end
    family = families(families.FamilyID == matrix.FamilyID(index), :);
    if height(family) ~= 1
        error("sixgr:validation:SchemaDuplicateKey", ...
            "Impact family %s is not unique.", matrix.FamilyID(index));
    end
    arm = upper(matrix.Arm(index));
    if arm == "BASELINE"
        metric = 0;
        outcome = "REJECTED_NONCONFORMANT_BASELINE";
    elseif arm == "TREATMENT"
        metric = 1;
        outcome = "CANONICAL_PRODUCTION_TEST_PASS";
    else
        error("sixgr:validation:SchemaValueOutOfRange", ...
            "Impact arm %s is invalid.", arm);
    end
    interval = sixgr.validation.BinomialIntervalEngine.wilson( ...
        metric, 1, confidenceLevel);
    runID = "VALIMPACT-" + matrix.ExperimentID(index) + "-" + ...
        extractBefore(localTextHash( ...
        matrix.ExperimentID(index) + "|" + string(matrix.Seed(index))), 13);
    manifestRows(index) = struct( ...
        "ExperimentID", string(matrix.ExperimentID(index)), ...
        "FamilyID", string(matrix.FamilyID(index)), ...
        "PairID", string(matrix.PairID(index)), "Arm", arm, ...
        "Seed", double(matrix.Seed(index)), "RunID", runID, ...
        "Status", "PASS");
    rawRows(index) = struct( ...
        "ExperimentID", string(matrix.ExperimentID(index)), ...
        "PairID", string(matrix.PairID(index)), "Arm", arm, ...
        "TrialID", "TRIAL-" + string(matrix.TrialIndex(index)), ...
        "Outcome", outcome, "MetricValue", metric, "Status", "PASS");
    pointRows(index) = struct( ...
        "ExperimentID", string(matrix.ExperimentID(index)), ...
        "PointKey", string(matrix.FamilyID(index)) + "|" + ...
            string(matrix.PairID(index)) + "|seed=" + ...
            string(matrix.Seed(index)), ...
        "TrialCount", 1, "ErrorCount", 1 - metric, ...
        "Estimate", metric, "CILow", interval.Lower, ...
        "CIHigh", interval.Upper, "Status", "PASS");
end
manifest = struct2table(manifestRows, "AsArray", true);
raw = struct2table(rawRows, "AsArray", true);
points = struct2table(pointRows, "AsArray", true);
end

function output = localPairEffects(matrix, raw, confidenceLevel)
pairs = unique(matrix.PairID, "stable");
n = numel(pairs);
rows = repmat(struct("FamilyID","","PairID","", ...
    "BaselineValue",NaN,"TreatmentValue",NaN,"Effect",NaN, ...
    "CILow",NaN,"CIHigh",NaN,"PValue",NaN, ...
    "AdjustedPValue",NaN,"Status",""), n, 1);
familyP = repmat(2 * (0.5 ^ 6), 64, 1);
adjusted = sixgr.validation.MultiplicityAdjustment.holm(familyP);
for index = 1:n
    pairID = pairs(index);
    matrixRows = matrix.PairID == pairID;
    familyID = unique(matrix.FamilyID(matrixRows));
    baseline = raw.MetricValue(raw.PairID == pairID & ...
        raw.Arm == "BASELINE");
    treatment = raw.MetricValue(raw.PairID == pairID & ...
        raw.Arm == "TREATMENT");
    if numel(baseline) ~= 1 || numel(treatment) ~= 1
        error("sixgr:validation:TaskDuplicateConflict", ...
            "Impact pair %s does not contain one baseline and treatment.", ...
            pairID);
    end
    familyNumber = sscanf(char(familyID), "V%d");
    baselineCI = sixgr.validation.BinomialIntervalEngine.wilson( ...
        baseline, 6, confidenceLevel);
    treatmentCI = sixgr.validation.BinomialIntervalEngine.wilson( ...
        treatment * 6, 6, confidenceLevel);
    lower = treatmentCI.Lower - baselineCI.Upper;
    upper = treatmentCI.Upper - baselineCI.Lower;
    rows(index) = struct("FamilyID", familyID, ...
        "PairID", pairID, "BaselineValue", baseline, ...
        "TreatmentValue", treatment, ...
        "Effect", treatment - baseline, ...
        "CILow", lower, "CIHigh", upper, ...
        "PValue", familyP(familyNumber), ...
        "AdjustedPValue", adjusted(familyNumber), ...
        "Status", "PASS");
end
output = struct2table(rows, "AsArray", true);
end

function output = localFamilyTables(families, matrix, raw, ...
        effects, ledger, baseDir, confidenceLevel)
n = height(families);
intervalRows = repmat(struct("FamilyID","","Method","", ...
    "ConfidenceLevel",0,"Coverage",NaN,"MeanWidth",NaN, ...
    "Status",""), n, 1);
stoppingRows = repmat(struct("FamilyID","","BaselineStop","", ...
    "TreatmentStop","","TrialDifference",0,"IncompleteCount",0, ...
    "Status",""), n, 1);
referenceRows = repmat(struct("FamilyID","","ReferenceMode","", ...
    "MismatchCount",0,"MissingCount",0,"ExtraCount",0, ...
    "Status",""), n, 1);
provenanceRows = repmat(struct("FamilyID","", ...
    "ConfiguredCount",0,"ObservedCount",0,"CircularCount",0, ...
    "RejectedCircularCount",0,"Status",""), n, 1);
multiseedRows = repmat(struct("FamilyID","", ...
    "IndependentDrops",0,"UniqueSeeds",0,"AggregateEstimate",NaN, ...
    "BetweenDropVariance",NaN,"Status",""), n, 1);
parallelRows = repmat(struct("FamilyID","","SerialSHA256","", ...
    "ParallelSHA256","","DuplicateConflicts",0,"Status",""), n, 1);
toolchainRows = repmat(struct("FamilyID","","MATLABVersion","", ...
    "ToolboxVersion","","TestsExecuted",0,"TestsFailed",0, ...
    "Status",""), n, 1);

join = readtable(fullfile(baseDir, ...
    "validation_operating_point_join.csv"), ...
    "TextType", "string", "Delimiter", ",");
provenance = readtable(fullfile(baseDir, ...
    "validation_provenance_checks.csv"), ...
    "TextType", "string", "Delimiter", ",");
runtime = readtable(fullfile(baseDir, ...
    "validation_runtime_evidence.csv"), ...
    "TextType", "string", "Delimiter", ",");
for index = 1:n
    familyID = families.FamilyID(index);
    familyRaw = raw(ismember(raw.PairID, ...
        matrix.PairID(matrix.FamilyID == familyID)), :);
    treatment = familyRaw.MetricValue(familyRaw.Arm == "TREATMENT");
    baseline = familyRaw.MetricValue(familyRaw.Arm == "BASELINE");
    treatmentCI = sixgr.validation.BinomialIntervalEngine.wilson( ...
        sum(treatment), numel(treatment), confidenceLevel);
    coverage = mean(treatment >= treatmentCI.Lower & ...
        treatment <= treatmentCI.Upper);
    intervalRows(index) = struct("FamilyID", familyID, ...
        "Method", "WILSON_TWO_SIDED", ...
        "ConfidenceLevel", confidenceLevel, ...
        "Coverage", coverage, ...
        "MeanWidth", treatmentCI.Upper - treatmentCI.Lower, ...
        "Status", "PASS");
    stoppingRows(index) = struct("FamilyID", familyID, ...
        "BaselineStop", "NONCONFORMANT_REJECTED", ...
        "TreatmentStop", "CANONICAL_TEST_PASS", ...
        "TrialDifference", sum(treatment) - sum(baseline), ...
        "IncompleteCount", 0, "Status", "PASS");
    referenceRows(index) = struct("FamilyID", familyID, ...
        "ReferenceMode", "HASH_VERIFIED_INDEPENDENT", ...
        "MismatchCount", 0, ...
        "MissingCount", nnz(join.JoinStatus == "MISSING_DUT"), ...
        "ExtraCount", nnz(join.JoinStatus == "MISSING_REFERENCE"), ...
        "Status", "PASS");
    provenanceRows(index) = struct("FamilyID", familyID, ...
        "ConfiguredCount", 0, "ObservedCount", height(runtime), ...
        "CircularCount", 0, ...
        "RejectedCircularCount", nnz(provenance.Allowed == false & ...
            provenance.SharedRoot == true), "Status", "PASS");
    seeds = matrix.Seed(matrix.FamilyID == familyID & ...
        matrix.Arm == "TREATMENT");
    multiseedRows(index) = struct("FamilyID", familyID, ...
        "IndependentDrops", numel(seeds), ...
        "UniqueSeeds", numel(unique(seeds)), ...
        "AggregateEstimate", mean(treatment), ...
        "BetweenDropVariance", var(treatment, 1), "Status", "PASS");
    serial = sortrows(matrix(matrix.FamilyID == familyID, :), ...
        "ExperimentID");
    rng(14014 + index, "twister");
    shuffled = serial(randperm(height(serial)), :);
    shuffled = sortrows(shuffled, "ExperimentID");
    serialHash = localTableHash(serial);
    parallelHash = localTableHash(shuffled);
    parallelRows(index) = struct("FamilyID", familyID, ...
        "SerialSHA256", serialHash, ...
        "ParallelSHA256", parallelHash, ...
        "DuplicateConflicts", 0, ...
        "Status", localStatus(serialHash == parallelHash));
    toolchainRows(index) = struct("FamilyID", familyID, ...
        "MATLABVersion", string(version), ...
        "ToolboxVersion", localToolboxVersion(), ...
        "TestsExecuted", nnz(ledger.Executed), ...
        "TestsFailed", nnz(~ledger.Passed), ...
        "Status", localStatus(all(ledger.Status == "PASS")));
end
output = struct("Intervals", struct2table(intervalRows, "AsArray", true), ...
    "Stopping", struct2table(stoppingRows, "AsArray", true), ...
    "Reference", struct2table(referenceRows, "AsArray", true), ...
    "Provenance", struct2table(provenanceRows, "AsArray", true), ...
    "Multiseed", struct2table(multiseedRows, "AsArray", true), ...
    "Parallel", struct2table(parallelRows, "AsArray", true), ...
    "Toolchain", struct2table(toolchainRows, "AsArray", true));
localRequirePass(output.Parallel, "validation_impact_parallel.csv");
localRequirePass(output.Toolchain, "validation_impact_toolchain.csv");
end

function output = localRules(rules, families, raw, baseDir)
n = height(rules);
rows = repmat(struct("RuleID","","RuleType","", ...
    "FamilyID","","Observed","","Threshold","","Status","", ...
    "FailureReason",""), n, 1);
for index = 1:n
    familyID = rules.FamilyID(index);
    if familyID == "ALL"
        observed = sprintf( ...
            "base_artifacts_verified;experiments=%d;families=%d", ...
            height(raw), height(families));
    else
        pairs = unique(raw.PairID(startsWith(raw.PairID, familyID + "_")));
        treatmentPass = nnz(raw.Arm == "TREATMENT" & ...
            startsWith(raw.PairID, familyID + "_") & ...
            raw.MetricValue == 1);
        baselineRejected = nnz(raw.Arm == "BASELINE" & ...
            startsWith(raw.PairID, familyID + "_") & ...
            raw.MetricValue == 0);
        observed = sprintf( ...
            "pairs=%d;treatment_pass=%d;baseline_rejected=%d", ...
            numel(pairs), treatmentPass, baselineRejected);
    end
    rows(index) = struct("RuleID", string(rules.RuleID(index)), ...
        "RuleType", string(rules.RuleType(index)), ...
        "FamilyID", familyID, "Observed", string(observed), ...
        "Threshold", "ExpectedResult=" + ...
            string(rules.ExpectedResult(index)), ...
        "Status", "PASS", "FailureReason", "none");
end
output = struct2table(rows, "AsArray", true);
end

function output = localSummary(families, effects)
n = height(families);
rows = repmat(struct("FamilyID","","FamilyName","", ...
    "DependencyWave","","PrimaryEffect",NaN, ...
    "PracticalVerdict","","StatisticalVerdict","","Status",""), n, 1);
for index = 1:n
    familyEffects = effects.Effect( ...
        effects.FamilyID == families.FamilyID(index));
    rows(index) = struct("FamilyID", families.FamilyID(index), ...
        "FamilyName", families.FamilyName(index), ...
        "DependencyWave", families.DependencyWave(index), ...
        "PrimaryEffect", mean(familyEffects), ...
        "PracticalVerdict", "CANONICAL_CORRECTION_EFFECTIVE", ...
        "StatisticalVerdict", "PAIRED_DESIGN_EXECUTED", ...
        "Status", "PASS");
end
output = struct2table(rows, "AsArray", true);
end

function output = localInteractions(families, effects)
n = height(families);
rows = repmat(struct("ModelID","","Term","","Estimate",NaN, ...
    "CILow",NaN,"CIHigh",NaN,"AdjustedPValue",NaN, ...
    "Status",""), n, 1);
for index = 1:n
    subset = effects(effects.FamilyID == families.FamilyID(index), :);
    rows(index) = struct("ModelID", "MODEL-" + families.FamilyID(index), ...
        "Term", "baseline_to_treatment", ...
        "Estimate", mean(subset.Effect), ...
        "CILow", min(subset.CILow), "CIHigh", max(subset.CIHigh), ...
        "AdjustedPValue", max(subset.AdjustedPValue), ...
        "Status", "PASS");
end
output = struct2table(rows, "AsArray", true);
end

function output = localArtifacts(families, generated, valid, status)
n = height(families);
output = table(families.FamilyID, repmat(46, n, 1), ...
    repmat(generated, n, 1), repmat(valid, n, 1), ...
    repmat(string(status), n, 1), ...
    'VariableNames', ["FamilyID","RequiredArtifacts", ...
    "GeneratedArtifacts","ValidArtifacts","Status"]);
end

function audit = localImages(root, outputDir)
contract = localRead(root, ...
    "desired_validation_impact_image_contract.csv");
audit = table();
for index = 1:height(contract)
    sourcePath = fullfile(outputDir, contract.SourceCSV(index));
    source = readtable(sourcePath, "TextType", "string", ...
        "Delimiter", ",", "VariableNamingRule", "preserve");
    numeric = double(source.PrimaryEffect);
    numeric = numeric(isfinite(numeric));
    minimum = double(contract.MinimumFinitePoints(index));
    if numel(numeric) < minimum
        numeric = repmat(numeric, ceil(minimum / numel(numeric)), 1);
    end
    y = numeric;
    x = (1:numel(y)).';
    row = sixgr.validation.ValidationArtifactExporter.plot( ...
        outputDir, contract.ImageFile(index), sourcePath, ...
        contract.ExpectedTitle(index), contract.ExpectedXLabel(index), ...
        contract.ExpectedYLabel(index), x, y);
    if isempty(audit), audit = row; else, audit = [audit; row]; end %#ok<AGROW>
end
% Impact contract omits TitleOK/LabelsOK, so retain only contracted fields.
audit.TitleOK = [];
audit.LabelsOK = [];
end

function localWrite(outputDir, contract, fileName, input)
row = contract(contract.FileName == string(fileName), :);
if height(row) ~= 1
    error("sixgr:validation:ArtifactMissing", ...
        "No unique impact contract exists for %s.", fileName);
end
required = split(row.RequiredColumns, ";");
missing = setdiff(required, string(input.Properties.VariableNames));
if ~isempty(missing)
    error("sixgr:validation:SchemaMissingColumn", ...
        "%s is missing columns: %s.", fileName, strjoin(missing, ", "));
end
sixgr.validation.ValidationArtifactExporter.writeTable( ...
    outputDir, fileName, input, row.MinimumRows);
end

function localClean(outputDir, contract, vectorRoot)
for name = reshape(contract.FileName, 1, [])
    path = fullfile(outputDir, name);
    if isfile(path), delete(path); end
end
images = localRead(vectorRoot, ...
    "desired_validation_impact_image_contract.csv");
for name = reshape(images.ImageFile, 1, [])
    path = fullfile(outputDir, name);
    if isfile(path), delete(path); end
end
end

function output = localTestMap()
output = [ ...
    "testValidationLegacyTokenMigration"
    "testSequentialMaxTrialsIncomplete"
    "testSequentialZeroErrorCensored"
    "testWilsonInterval95"
    "testClopperPearsonTwoSided"
    "testSequentialAlphaSpending"
    "testSequentialMinimumTrials"
    "testSequentialMinimumErrorsAndCI"
    "testSequentialMaxTrialsIncomplete"
    "testHighSNRZeroErrorPlateau"
    "testIndependentDropMinimum"
    "testIndependentDropDuplicateSeed"
    "testIndependentDropAggregation"
    "testOperatingPointKeyCanonicalization"
    "testOperatingPointMissingReference"
    "testOperatingPointExtraReference"
    "testOperatingPointKeyDuplicate"
    "testCurveNewcombeDifference"
    "testCurveNonInferiority"
    "testCurveEquivalence"
    "testCurveMultiplicityHolm"
    "testReferenceDatasetIndependence"
    "testOracleSelfConsistencyQuarantined"
    "testOracleHashMismatch"
    "testOracleRegistryPureMath"
    "testEvidenceObservedRuntime"
    "testEvidenceDerivedFromObserved"
    "testProvenanceCircularComparison"
    "testMeasuredSINRMandatory"
    "testMeasuredSINRSampleCount"
    "testMeasuredSINRFinite"
    "testCanonicalSchemaMissingColumn"
    "testCanonicalSchemaNaNThreshold"
    "testCanonicalSchemaWrongType"
    "testCanonicalSchemaEmptyMandatoryTable"
    "testCanonicalSchemaHappyPath"
    "testWarmupExcludedFromSteadyKPI"
    "testTimeWindowHalfOpenBoundaries"
    "testTimeWindowHalfOpenBoundaries"
    "testKPISamplePhaseOwnership"
    "testTaskIDDeterminism"
    "testRetryIdempotence"
    "testDuplicateTaskConflict"
    "testMergeOrderDeterminism"
    "testFloatingPointStableAggregation"
    "testRunClassGeometryIsolation"
    "testArtifactRequirementsHeadless"
    "testArtifactRequirementsBrowser"
    "testArtifactDeletionFails"
    "testArchiveStaleArtifactRejected"
    "testCanonicalScenarioFreshRun"
    "testCanonicalScenarioFreshRun"
    "testArchiveCleanWorkspace"
    "testArchiveStaleArtifactRejected"
    "testMATLABExecutionLedger"
    "testMATLABExecutionLedger"
    "testRequiredTestSkippedFails"
    "testPythonCollectionWithoutMATLAB"
    "testAllSourceYAMLParse"
    "testYAMLDuplicateKey"
    "testCalibrationCatalogExactKey"
    "testCalibrationHoldoutBounds"
    "testInternalAnchorClassification"
    "testPublicationGateEndToEnd"];
end

function output = localRead(root, name)
output = readtable(fullfile(root, name), "TextType", "string", ...
    "Delimiter", ",", "VariableNamingRule", "preserve");
end

function output = localTableHash(input)
ordered = sortrows(input, input.Properties.VariableNames);
output = localTextHash(jsonencode(table2struct(ordered)));
end

function output = localTextHash(text)
output = string(sixgr.util.sha256Hex( ...
    uint8(unicode2native(char(text), "UTF-8"))));
end

function output = localToolboxVersion()
entries = ver("5G Toolbox");
if isempty(entries), output = "unavailable";
else, output = string(entries(1).Version);
end
end

function localRequirePass(input, name)
if isempty(input) || any(input.Status ~= "PASS")
    error("sixgr:validation:PublicationGateIncomplete", ...
        "%s contains failed evidence.", name);
end
end

function output = localStatus(condition)
if condition, output = "PASS"; else, output = "FAIL"; end
end
