function episode=executeEpisode(cfg,history,rv,seeds,identity)
% Production Tx/Rx; stop at success, retain original TB and mother-code LLRs.
payload=[]; soft=[]; layout=struct(); records=struct([]); raw=cell(0,1); resolved=cell(0,1);
for attempt=1:numel(rv)
    cfg.simulation.snrDb=history(attempt);
    phy=sixgr.lls.buildPHYConfig(cfg,history(attempt));
    phy.phy.carrier.NSlot=mod(attempt-1,10*round(double(phy.phy.carrier.SubcarrierSpacing)/15));
    resolved{end+1,1}=phy; %#ok<AGROW>
    plan=struct('Bits',seeds(1),'Noise',seeds(2*attempt),'Channel',seeds(2*attempt+1));
    [row,d]=sixgr.lls.runTransportBlock(cfg,phy,identity,1,attempt, ...
        'PacketIndex',1,'AttemptIndex',attempt,'TransportBlockBits',payload, ...
        'RV',rv(attempt),'HARQSoftBuffer',soft,'HARQSoftBufferLayout',layout, ...
        'RandomSeeds',plan);
    if attempt==1, payload=d.Tx.TransportBlock; end
    assert(isequal(payload,d.Tx.TransportBlock) && numel(payload)==row.TransportBlockSizeBits, ...
        'sixgr:calibration:TBIdentity','HARQ retransmission changed transport block identity.');
    assert(attempt==1 || row.HARQSoftCombiningApplied, ...
        'sixgr:calibration:SoftCombining','HARQ retransmission discarded its soft buffer.');
    assert(row.CRCError || row.BitErrors==0, ...
        'sixgr:calibration:CRCScoring','CRC success disagrees with independent TB scoring.');
    if isfield(d.Tx,'PDSCHIndices'), indices=d.Tx.PDSCHIndices; else, indices=d.Tx.PUSCHIndices; end
    % Exact applied SISO channel at actual DATA REs, not a scalar SINR
    % repeated over a fading grid. This truth is used for scoring, never RX.
    h=double(d.TrueChannelGrid);
    assert(size(h,3)==1 && size(h,4)==1,'sixgr:calibration:FeatureDimensions','SISO feature adapter only.');
    n0=double(d.NoiseInfo.GridNoiseVariance);
    gamma=abs(h(double(indices(:)))).^2 * ...
        double(d.NoiseInfo.SignalEnergyPerOccupiedRE)/n0;
    assert(~isempty(gamma) && all(isfinite(gamma)) && all(gamma>=0), ...
        'sixgr:calibration:Feature','Missing applied-channel per-data-RE SINR.');
    rec=struct('Attempt',attempt,'RV',rv(attempt),'SNRdB',history(attempt), ...
        'CRCError',logical(row.CRCError),'TBSBits',numel(payload), ...
        'TransportBlockSHA256',string(sixgr.util.sha256Hex(uint8(payload(:)))), ...
        'PriorAttemptsFailed',attempt>1,'WaveformExecuted',true, ...
        'BitsSeed',plan.Bits,'NoiseSeed',plan.Noise,'ChannelSeed',plan.Channel, ...
        'SINRLinear',gamma,'SINRSource',"applied_channel_per_data_re_pre_combining", ...
        'DataRECount',numel(gamma),'GridNoiseVariance',n0, ...
        'HARQSoftCombiningApplied',logical(row.HARQSoftCombiningApplied));
    if isempty(records), records=rec; else, records(end+1)=rec; end %#ok<AGROW>
    raw{end+1,1}=row; %#ok<AGROW>
    if ~row.CRCError, break; end
    soft=d.Rx.HARQSoftBuffer;
    if isfield(d.Tx,'PUSCH') && isfield(d.Tx,'CodingLayout')
        layout=d.Tx.CodingLayout;
    elseif isfield(d.Tx,'CodingLayouts')
        layout=d.Tx.CodingLayouts;
    else
        layout=d.Tx.CodingLayout;
    end
end
episode=struct('Attempts',records,'RawTrials',{raw},'ResolvedConfig',cfg, ...
    'ResolvedPHYConfigurations',{resolved}, ...
    'Delivered',~records(end).CRCError,'PrimaryStudyAccepted',false, ...
    'ChannelEvolution',"independent_attempt_realizations", ...
    'ReceiverAssumption',"practical_dmrs_known_noise_ideal_timing");
end
