function fields=csiReferenceSINRPublication(observation,configuredSNR)
% Publish the receiver's reference-RE measurement, never its CQI objective.
% This does not recompute SINR, infer missing observations or alter payloads.
arguments
    observation (1,1) struct
    configuredSNR (1,1) double {mustBeReal}
end
fields=struct('ConfiguredSNR_dB',configuredSNR, ...
    'ConfiguredSNRSource',"configured_operating_point_metadata", ...
    'SNRValueRole',"configured_operating_point_metadata", ...
    'MeasuredTrialSINR_dB',NaN,'MeasuredTrialSINRSource',"", ...
    'MeasuredTrialSINRValueRole',"unavailable", ...
    'MeasuredTrialSINRValueStatus',"unavailable", ...
    'MeasuredTrialSINRNAReason',"csi_rs_reference_measurement_unavailable", ...
    'MeasuredTrialSINRMeasurementDomain',"",'MeasuredSINR_dB',NaN, ...
    'MeasuredSINRDomain',"");
value=sixgr.util.structGet(observation,'ReferenceMeasuredSINR_dB',NaN);
status=string(sixgr.util.structGet(observation,'ReferenceMeasuredSINRStatus',"not_attempted"));
validateattributes(value,{'numeric'},{'scalar','real'});
if ~isfinite(value) || ~any(status==["available","measured"]), return; end
source=string(sixgr.util.structGet(observation,'ReferenceMeasuredSINRSource',""));
domain=string(sixgr.util.structGet(observation,'SINRMeasurementDomain',""));
assert(logical(sixgr.util.structGet(observation,'Observed',false)) && ...
    isscalar(source) && strlength(source)>0 && ...
    isscalar(domain) && strlength(domain)>0 && ...
    ~contains(lower(source),["fallback","proxy","configured"]), ...
    'sixgr:link:CSIReferenceSINRPublicationAuthority', ...
    'A finite reference SINR requires an actual observation, source and reference-RE domain.');
fields.MeasuredTrialSINR_dB=double(value);
fields.MeasuredTrialSINRSource=source;
fields.MeasuredTrialSINRValueRole="received_reference_RE_power_ratio_estimate";
fields.MeasuredTrialSINRValueStatus="OK";
fields.MeasuredTrialSINRNAReason="";
fields.MeasuredTrialSINRMeasurementDomain=domain;
fields.MeasuredSINR_dB=double(value);
fields.MeasuredSINRDomain=domain;
% SINR_dB / SINRSource / SINRMeasurementDomain belong to the separate
% selected-PMI receiver objective. Do not overwrite them with this plane.
end
