function prepared = prepareCSIRSTransmission(cfg, snr_dB, options)
%PREPARECSIRSTRANSMISSION Prepare one independent cell-common CSI-RS slot.
% The shared waveform owner executes channel, RF, noise and reception.
arguments
    cfg (1,1) struct
    snr_dB (1,1) double {mustBeFinite}
    options.RuntimeSlot (1,1) double {mustBeInteger,mustBePositive}
    options.Frame (1,1) double = NaN
    options.ApplyPA (1,1) logical = false
end

[cfg, timeline] = sixgr.phy.grid.applyRuntimeCarrierTimeline( ...
    cfg, options.RuntimeSlot, options.Frame);
carrier = sixgr.phy.grid.makeCarrier(cfg);
[scheduled, ~] = sixgr.phy.refsig.csirsOccasion( ...
    cfg, timeline.AbsoluteSlotIndex0);
if ~scheduled
    configuredPeriod = double(sixgr.util.structGet( ...
        cfg, "phy.csirs.period_slots", NaN));
    configuredOffset = double(sixgr.util.structGet( ...
        cfg, "phy.csirs.offset_slots", NaN));
    error("sixgr:link:CSIRSPreparationOutsideOccasion", ...
        ['Runtime slot %d is outside the configured CSI-RS calendar ' ...
         '(period=%g offset=%g).'], options.RuntimeSlot, ...
        configuredPeriod, configuredOffset);
end

waveformPorts = double(sixgr.util.structGet(cfg, "channel.nTxAnt", NaN));
validateattributes(waveformPorts, {'numeric'}, ...
    {'scalar','real','finite','integer','positive'});
materialized = sixgr.phy.refsig.materializeCSIRSPhysicalGrid( ...
    carrier, cfg, "WaveformPortCount", waveformPorts, ...
    "OwnershipMode", "emit");
assert(materialized.Event.Scheduled && materialized.Event.Transmitted && ...
    any(materialized.Grid ~= 0, 'all'), ...
    'sixgr:link:CSIRSPreparationEmpty', ...
    'A scheduled independent CSI-RS producer must transmit nonzero grid REs.');
[waveform, ofdmInfo] = sixgr.phy.waveform.ofdmModulate( ...
    carrier, materialized.Grid);

receiverCfg = cfg;
receiverCfg = sixgr.util.structSet(receiverCfg, "channel.snr_dB", snr_dB);
receiverCfg = sixgr.util.structSet(receiverCfg, ...
    "lls6g.userContext.RuntimeSignalFamily", "CSI-RS");
receiverCfg = sixgr.util.structSet(receiverCfg, ...
    "lls6g.userContext.RuntimeCurrentDirection", "DL");
receiverCfg = sixgr.util.structSet(receiverCfg, ...
    "lls6g.userContext.Direction", "DL");
receiverCfg = sixgr.util.structSet(receiverCfg, "channel.linkDirection", "DL");
txInfo = struct("OFDM", ofdmInfo, "OFDMInfo", ofdmInfo, ...
    "PortGrid", materialized.Grid, ...
    "PowerNormalizationGridSource", "exact_independent_csirs_physical_port_grid", ...
    "CSIRSRuntimeEvent", materialized.Event);
[transmitSamples, powerContext] = sixgr.rf.applyPowerContext( ...
    waveform, receiverCfg, "DL", txInfo, "ApplyPA", options.ApplyPA);
receiverCfg = sixgr.util.structSet(receiverCfg, ...
    "lls6g.runtimePowerContext", powerContext);

tx = struct("Carrier", carrier, "Waveform", waveform, "Grid", materialized.Grid, ...
    "OFDMInfo", ofdmInfo, "CSIRSIndices", materialized.Indices, ...
    "CSIRSSymbols", materialized.Symbols, "CSIRSInfo", materialized.Info, ...
    "CSIRSPhysicalIndices", materialized.Event.WaveformIndices, ...
    "CSIRS", materialized.Configuration, ...
    "CSIRSRuntimeEvent", materialized.Event, ...
    "PowerContext", powerContext);
prepared = struct( ...
    "ExecutionStage", "csirs_waveform_prepared_not_received", ...
    "Tx", tx, "TxInfo", txInfo, "Carrier", carrier, ...
    "ReceiverConfig", receiverCfg, "PowerContext", powerContext, ...
    "TransmitSamples", transmitSamples, ...
    "SampleRateHz", double(ofdmInfo.SampleRate), ...
    "NumSamples", size(transmitSamples,1), ...
    "NumPhysicalTransmitAntennas", size(transmitSamples,2), ...
    "RequestedSNR_dB", double(snr_dB), ...
    "RuntimeSlot", double(options.RuntimeSlot), ...
    "Timeline", timeline, ...
    "RFExecutionDeferred", ~logical(powerContext.PAApplied), ...
    "PAExecutionDeferred", logical(powerContext.PAExecutionDeferred), ...
    "ChannelExecutionDeferred", true, ...
    "ReferenceIdentity", localReferenceIdentity(cfg, timeline, materialized));
end

function identity = localReferenceIdentity(cfg, timeline, materialized)
event = materialized.Event;
identity = struct( ...
    "SignalFamily", "CSI-RS", ...
    "AbsoluteSlotIndex0", double(timeline.AbsoluteSlotIndex0), ...
    "AbsoluteSlotIndexOneBased", double(timeline.AbsoluteSlotIndexOneBased), ...
    "CellID", double(sixgr.util.structGet(cfg, "phy.carrier.NCellID", NaN)), ...
    "ResourceSetID", double(event.ResourceSetID), ...
    "ResourceIDs", string(event.ResourceIDs), ...
    "PhysicalGridDigest", sixgr.phy.mimo.MatrixContract.digest(materialized.Grid), ...
    "PrecoderDigests", string(event.PrecoderDigests), ...
    "Source", "configured_periodic_cell_common_csirs_physical_grid");
end
