function [modulation,experimental]=resolvePUSCHTransportModulation(tx)
% Reporting/coding must not interpret a geometry-only QPSK object as data.
experimental=string(sixgr.util.structGet(tx,'PUSCHRole',''))== ...
    "native_geometry_only_not_transport_modulation";
if experimental
    assert(isfield(tx,'Modulation') && isfield(tx,'ResearchTransport') && isfield(tx,'StandardNR') && ...
        isa(tx.ResearchTransport,'sixgr.phy.research.PUSCHUCIResourceAdapter') && ...
        string(tx.Modulation)==tx.ResearchTransport.Modulation && ...
        isequal(tx.StandardNR,false), ...
        'sixgr:research:MissingTransportModulation','Geometry-only PUSCH requires explicit experimental modulation evidence.');
    modulation=string(tx.Modulation);
else
    modulation=string(sixgr.util.structGet(tx,'Modulation', ...
        sixgr.util.structGet(tx,'PUSCH.Modulation','')));
end
end
