function scoring=scoreIndependentPUSCHUCI(rx,context,payload)
% Post-reception comparison only; return no replacement receiver evidence.
assert(isstruct(rx) && isscalar(rx) && ...
    isa(context,'sixgr.phy.ul.pusch.PUSCHUCIReceiveContext') && isscalar(context), ...
    'sixgr:pusch:InvalidIndependentUCIScoring','Use the actual receiver result and bound context.');
assert(~any(isfield(rx,{'ExpectedHARQACKBits','ExpectedCSIPart1Bits','ExpectedCSIPart2Bits', ...
    'HARQACKContentMatch','CSI1ContentMatch','CSI2ContentMatch'})), ...
    'sixgr:pusch:ReceiverScoringLeak','Independent receiver output cannot contain TX scoring.');
fields=["DecodedHARQACKBits","DecodedCSIPart1Bits","DecodedCSIPart2Bits","DecodedConfiguredGrantUCIBits"];
resultFields=["DecodedHARQACK","DecodedCSIPart1","DecodedCSIPart2","DecodedConfiguredGrantUCI"];
evidence=sixgr.util.structGet(rx,'UCIReceiverEvidence',struct());
hasEvidence=isstruct(evidence) && isscalar(evidence) && ~isempty(fieldnames(evidence));
if hasEvidence
    assert(isfield(evidence,'ReceiverContextDigest') && ...
        string(evidence.ReceiverContextDigest)==context.Digest && all(isfield(rx,fields)), ...
        'sixgr:pusch:UCIReceiverContextMismatch','Preserve the actual demultiplexer context and all decoded fields.');
else
    % PUSCH_Rx can stop at the strict noise-estimate gate, before demapping.
    % That is an unavailable receive result, not a missing annotation to fill
    % with presumed decoded bits. Accept only this explicitly reported path.
    assert(isequal(sixgr.util.structGet(rx,'NoiseVarStrictFailure',[]),true) && ...
        isequal(sixgr.util.structGet(rx,'DecodeAttempted',[]),false) && ...
        isequal(sixgr.util.structGet(rx,'ULSCHDecodeAttempted',[]),false) && ...
        isequal(sixgr.util.structGet(rx,'ReceiverUsable',[]),false), ...
        'sixgr:pusch:MissingIndependentUCIEvidence','Unexplained missing UCI evidence is not a valid receiver completion.');
end
decoded=struct();
for k=1:numel(fields)
    bits=sixgr.util.structGet(rx,fields(k),int8([]));
    assert((isnumeric(bits)||islogical(bits)) && isreal(bits) && ...
        (isvector(bits)||isempty(bits)) && all(isfinite(bits(:))) && all(bits(:)==0|bits(:)==1) && ...
        (hasEvidence || isempty(bits)), ...
        'sixgr:pusch:InvalidIndependentUCIScoringBits','Only actual finite binary decoded vectors may be compared.');
    decoded.(resultFields(k))=bits;
end
scoring=sixgr.phy.ul.pusch.PUSCHUCIDemultiplexer.score(decoded,payload);
end
