function fields=ssbPowerReferenceEvidence(source)
% Copy typed same-producer power-reference evidence into existing rows.
% Empty values describe unavailable fields, never substitute trial rows.
if nargin<1, source=struct(); end
fields=struct();
for name=["SS_RSRP_dB_re_UnitOccupiedRE_Es","SS_RSRPRawObserved_dB_re_UnitOccupiedRE_Es", ...
        "ReferenceSignalTxEPRE_dB_re_UnitOccupiedRE_Es","MeasuredReferenceSignalChannelGain_dB", ...
        "SSMeasurementFFTSize","ReferenceSignalTxMeasurementFFTSize", ...
        "SSPowerReferenceOffset_dB","ReferenceSignalTxPowerReferenceOffset_dB"]
    value=double(sixgr.util.structGet(source,name,NaN));
    assert(isscalar(value),'sixgr:link:SSBPowerEvidenceShape','SSB scalar power metadata must be scalar.');
    fields.(name)=value;
end
for name=["SS_RSRPPerReceiveAntenna_dB_re_UnitOccupiedRE_Es", ...
        "SS_RSRPRawObservedPerReceiveAntenna_dB_re_UnitOccupiedRE_Es", ...
        "SSBWindowRSSIPerReceiveAntenna_dB_re_UnitOccupiedRE_Es", ...
        "ReferenceSignalTxEPREPerAntenna_dB_re_UnitOccupiedRE_Es", ...
        "SSSINRDesiredPowerPerReceiveAntenna_UnitOccupiedRE_Es", ...
        "SSSINRNoiseInterferencePowerPerReceiveAntenna_UnitOccupiedRE_Es"]
    value=string(sixgr.util.structGet(source,name,""));
    assert(isscalar(value),'sixgr:link:SSBPowerEvidenceShape','SSB vector evidence requires one token per trial.');
    fields.(name)=value;
end
end
