function [data,meta] = buildPublicFigureData(runDirectory,basename,scenario)
%BUILDPUBLICFIGUREDATA Canonical data contract for public NTN figures.
arguments
    runDirectory (1,1) string
    basename (1,1) string
    scenario (1,1) struct
end
cfg=scenario; c=double(cfg.geometry.speed_of_light_m_s);
meta=struct("EvidenceClass","ANALYTICAL","CalibrationStatus", ...
    "NOT_APPLICABLE","ClaimStatus","PUBLIC_TDOC_INPUT", ...
    "Provenance","configured_equation","Assumptions",localAssumptions(cfg));
switch basename
    case "fig_2_01_resilient_ul_framework"
        data=table(["GNSS-based";"GNSS-degraded";"GNSS-free/GNSS-less"], ...
            ["current position";"last position + uncertainty"; ...
             "reference area / DL estimate"], ...
            repmat("coarse UL time/frequency pre-compensation",3,1), ...
            repmat("initial uplink acquisition",3,1), ...
            repmat("residual correction",3,1), ...
            repmat("ordinary PUSCH/PUCCH/tracking",3,1), ...
            repmat("ordinary-UL bound exceedance -> correction/reacquisition/suspend",3,1), ...
            'VariableNames',{'Mode','PositionAuthority','CoarsePrecompensation', ...
            'Acquisition','ResidualCorrection','OrdinaryUL','FeedbackRule'});
        meta=localDiagramMeta(meta);
    case "fig_2_02_delay_reference_convention"
        h=localRead(runDirectory,"gnss_degraded_holdover");
        h=h(h.CarrierId==string(cfg.public_figures.geometric_frequency_carrier_ids(1)) & ...
            h.Oscillator_ppm==min(h.Oscillator_ppm),:);
        data=unique(h(:,{'DeltaTauSL_s','ULRPArrivalError_s','PositionAge_s'}));
        data.DeltaTauSL_us=data.DeltaTauSL_s*1e6;
        data.ULRPArrivalError_us=data.ULRPArrivalError_s*1e6;
        data.ReferenceULRPArrivalError_us=-double(cfg.geometry.timing_mapping.kappa_t)*data.DeltaTauSL_us;
        data.ErrorCombinationRule(:)=string(cfg.geometry.timing_mapping.sign_convention);
    case "fig_2_03_timing_bound_vs_age"
        ages=double(cfg.gnss_degraded.ages_s(:));
        speeds=double(cfg.gnss_degraded.speeds_kmh(:));
        [speed,age]=ndgrid(speeds,ages);
        ue=double(cfg.gnss_degraded.initial_ue_position_error_los_m)+ ...
            speed(:)/3.6.*age(:)*cosd(double(cfg.public_figures.holdover_motion_projection_deg));
        total=ue+double(cfg.gnss_degraded.satellite_position_error_los_m);
        data=table(speed(:),age(:),ue,total,total/c, ...
            double(cfg.geometry.timing_mapping.kappa_t)*total/c*1e6, ...
            repmat(double(cfg.public_figures.holdover_motion_projection_deg),numel(total),1), ...
            'VariableNames',{'Speed_kmh','PositionAge_s','UELOSRangeErrorBound_m', ...
            'CombinedLOSRangeErrorBound_m','DeltaTauSL_s','AbsoluteET_us', ...
            'MotionProjection_deg'});
    case "fig_2_04_frequency_bound_vs_speed"
        speeds=double(cfg.gnss_degraded.speeds_kmh(:)); ids=string(cfg.public_figures.geometric_frequency_carrier_ids(:));
        rows=cell(numel(ids),1);
        for i=1:numel(ids)
            carrier=localCarrier(cfg,ids(i));
            radial=speeds/3.6*cosd(double(cfg.public_figures.holdover_motion_projection_deg))+ ...
                double(cfg.gnss_degraded.satellite_radial_velocity_error_mps);
            rows{i}=table(repmat(ids(i),numel(speeds),1),speeds,radial, ...
                repmat(double(carrier.f_ul_hz),numel(speeds),1), ...
                double(carrier.f_ul_hz)/c*radial/1e3, ...
                'VariableNames',{'CarrierId','Speed_kmh','RadialVelocityBound_m_s', ...
                'ULCarrier_Hz','GeometricFrequencyErrorBound_kHz'});
        end
        data=vertcat(rows{:});
    case "fig_2_05_reference_area_timing_cdf"
        radii=double(cfg.public_figures.timing_cdf_radii_km(:)); rows=cell(numel(radii),1);
        for i=1:numel(radii)
            raw=localRawReference(runDirectory,radii(i),double(cfg.public_figures.timing_cdf_elevation_deg));
            t=localCDF(abs(raw.ULRPArrivalError_s)*1e6,"AbsoluteET_us");
            t.Radius_km(:)=radii(i); t.P95_us(:)=prctile(abs(raw.ULRPArrivalError_s)*1e6,95);
            rows{i}=t;
        end
        data=vertcat(rows{:}); meta.EvidenceClass="MONTE_CARLO_GEOMETRY";meta.Provenance="exact_spherical_earth_monte_carlo";
    case "fig_2_06_reference_area_cfo_cdf"
        radius=double(cfg.public_figures.cfo_cdf_radius_km);elev=double(cfg.public_figures.cfo_cdf_elevation_deg);
        raw=localRawReference(runDirectory,radius,elev);
        a=localCDF(abs(raw.DifferentialCFO_SBand_Hz)/1e3,"AbsoluteDifferentialCFO_kHz");a.Carrier(:)="2 GHz";
        b=localCDF(abs(raw.DifferentialCFO_Ka_Hz)/1e3,"AbsoluteDifferentialCFO_kHz");b.Carrier(:)="30 GHz";
        a.P95_kHz(:)=prctile(abs(raw.DifferentialCFO_SBand_Hz)/1e3,95);
        b.P95_kHz(:)=prctile(abs(raw.DifferentialCFO_Ka_Hz)/1e3,95);
        data=[a;b];data.Radius_km(:)=radius;data.Elevation_deg(:)=elev;
        meta.EvidenceClass="MONTE_CARLO_GEOMETRY";meta.Provenance="differential_after_reference_centre_compensation";
    case "fig_2_07_timing_vs_elevation"
        t=localRead(runDirectory,"reference_area_summary");radius=double(cfg.public_figures.elevation_sensitivity_radius_km);
        t=t(abs(t.ReferenceAreaRadius_m-radius*1e3)<1e-6,:);
        a=table(t.Elevation_deg,t.P95AbsoluteDeltaTauSL_s*1e6,repmat("one-way |deltaTauSL|",height(t),1), ...
            'VariableNames',{'Elevation_deg','P95_us','Metric'});
        b=table(t.Elevation_deg,t.P95AbsoluteULRPArrivalError_s*1e6,repmat("ULRP |eT|, kappaT=2",height(t),1), ...
            'VariableNames',{'Elevation_deg','P95_us','Metric'});
        data=[a;b];data.Radius_km(:)=radius;meta.EvidenceClass="MONTE_CARLO_GEOMETRY";meta.Provenance="exact_spherical_earth_monte_carlo";
    case "fig_2_08_cfo_vs_elevation"
        t=localRead(runDirectory,"reference_area_summary");radius=double(cfg.public_figures.elevation_sensitivity_radius_km);
        t=t(abs(t.ReferenceAreaRadius_m-radius*1e3)<1e-6,:);
        a=table(t.Elevation_deg,t.P95AbsoluteDifferentialCFO_SBand_Hz/1e3,repmat("2 GHz",height(t),1), ...
            'VariableNames',{'Elevation_deg','P95_kHz','Carrier'});
        b=table(t.Elevation_deg,t.P95AbsoluteDifferentialCFO_Ka_Hz/1e3,repmat("30 GHz",height(t),1), ...
            'VariableNames',{'Elevation_deg','P95_kHz','Carrier'});
        data=[a;b];data.Radius_km(:)=radius;meta.EvidenceClass="MONTE_CARLO_GEOMETRY";meta.Provenance="differential_after_reference_centre_compensation";
    case "fig_2_09_acquisition_vs_ordinary_regions"
        theta=linspace(0,2*pi,361).';r=cfg.public_figures.acquisition_region;
        a=table(double(r.acquisition_cfo_radius_khz)*cos(theta), ...
            double(r.acquisition_timing_radius_us)*sin(theta), ...
            repmat("initial acquisition conceptual bound",numel(theta),1), ...
            'VariableNames',{'ResidualCFO_kHz','ResidualTimingError_us','Region'});
        b=table(double(r.ordinary_ul_cfo_radius_khz)*cos(theta), ...
            double(r.ordinary_ul_timing_radius_us)*sin(theta), ...
            repmat("ordinary UL conceptual bound",numel(theta),1), ...
            'VariableNames',{'ResidualCFO_kHz','ResidualTimingError_us','Region'});
        data=[a;b];data.EmpiricalContoursAvailable(:)=false;
        meta=localDiagramMeta(meta);meta.CalibrationStatus="BLOCKED_PENDING_JOINT_PRACH_PUSCH_ACCEPTANCE";meta.ClaimStatus="CONCEPTUAL_ONLY";
    case "fig_2_10_compensation_responsibility"
        data=table(["Regenerative payload / satellite-side ULRP"; ...
            "Transparent payload / network feeder compensation"; ...
            "Transparent payload / UE gateway-side ULRP compensation"], ...
            ["satellite";"gateway/network ULRP";"gateway-side ULRP"], ...
            ["UE service-link pre-compensation";"UE service-link pre-compensation";"UE service + feeder-equivalent compensation"], ...
            ["satellite terminates UL";"network removes feeder timing/frequency";"UE includes gateway/feeder term"], ...
            ["service-link assistance";"network feeder assistance";"gateway-reference assistance to UE"], ...
            'VariableNames',{'Architecture','ULRPLocation','UEResponsibility','FeederResponsibility','AssistanceImplication'});
        meta=localDiagramMeta(meta);
    case "fig_2_12_koffset_ta_timeline"
        data=table((1:8).',["aNB DL frame/slots";"UL scheduling relation"; ...
            "K2-like offset + k_offset";"DL propagation to UE"; ...
            "UE-applied timing adjustment";"UE UL frame/transmission"; ...
            "UL propagation to aNB ULRP";"TA report conveys applied timing"], ...
            ["aNB";"aNB";"aNB";"air";"UE";"UE";"air";"UE->aNB"], ...
            ["reference";"scheduling";"configured relation";"delay"; ...
            "correction";"transmission";"arrival";"report"], ...
            'VariableNames',{'EventOrder','Event','Lane','Function'});
        meta=localDiagramMeta(meta);meta.EvidenceClass="EVENT_PROCEDURE";meta.Provenance="configured_timeline";
    case "fig_2_13_beam_rtt_spread"
        k=localRead(runDirectory,"k_offset_samples");k=k(k.SCS_kHz==max(k.SCS_kHz),:);
        elev=unique(k.Elevation_deg);spread=zeros(numel(elev),1);
        for i=1:numel(elev),rtt=k.RTT_s(k.Elevation_deg==elev(i));spread(i)=(max(rtt)-min(rtt))*1e3;end
        data=table(elev,spread,repmat(double(cfg.k_offset.beam_diameter_km),numel(elev),1), ...
            repmat("max RTT - min RTT across circular beam",numel(elev),1), ...
            'VariableNames',{'Elevation_deg','DifferentialRTTSpread_ms','BeamDiameter_km','Definition'});
        meta.EvidenceClass="MONTE_CARLO_GEOMETRY";meta.Provenance="exact_spherical_earth_monte_carlo";
    case "fig_2_14_koffset_excess_delay_cdf"
        k=localRead(runDirectory,"k_offset_samples");k=k(k.SCS_kHz==120,:);
        columns=["UEExcessDelay_s","BeamExcessDelay_s","CellExcessDelay_s"];
        labels=["UE-specific";"Beam-specific";"Cell-specific"];rows=cell(3,1);
        for i=1:3
            values=double(k.(columns(i)))*1e3;t=localCDF(values,"ExcessDelay_ms");t.Level(:)=labels(i);
            t.Mean_ms(:)=mean(values);t.P95_ms(:)=prctile(values,95);t.Maximum_ms(:)=max(values);rows{i}=t;
        end
        data=vertcat(rows{:});meta.EvidenceClass="SCHEDULER_SYSTEM";meta.Provenance="absolute_rtt_equal_weight_eight_beams";
    case "fig_2_15_koffset_update_timescale"
        data=localRead(runDirectory,"rtt_update_timescale");
    case "fig_2_16_compensation_state_matrix"
        t=localRead(runDirectory,"compensation_state_matrix");profile="REG_SAT_ULRP";
        if ~any(t.ProfileId==profile),profile=t.ProfileId(1);end
        data=t(t.ProfileId==profile,:);
        data.MatrixRow=replace(extractBefore(data.Domain,"_"),["dl","ul"],["DL","UL"]);
        data.MatrixColumn=replace(extractAfter(data.Domain,"_"),["timing","frequency"],["Timing","Frequency"]);
        meta=localDiagramMeta(meta);
    case "fig_2_17_state_aware_chain"
        data=table((1:6).',["DL carrier-offset and timing-drift measurements"; ...
            "Network-provided compensation state"; ...
            "Normalize observations / remove known network components"; ...
            "Estimate range rate and UE oscillator error"; ...
            "Select state-dependent UL coefficient rule"; ...
            "Apply UL timing/frequency correction and form mismatch"], ...
            ["input";"input";"processing";"estimation";"selection";"output"], ...
            'VariableNames',{'NodeOrder','Node','NodeType'});
        meta=localDiagramMeta(meta);meta.Provenance="public_state_aware_chain";
    case "fig_2_18_estimator_observation_interval"
        intervals=double(cfg.public_figures.estimator.observation_intervals_s(:));
        sigmaTiming=double(cfg.public_figures.estimator.timing_sigma_us(:))*1e-6;
        carriers=double(cfg.public_figures.estimator.carrier_hz(:));
        [f,sigmaT,T]=ndgrid(carriers,sigmaTiming,intervals);
        sigmaA=double(cfg.public_figures.estimator.oscillator_sigma_fractional);
        sigmaB=sqrt(2)*sigmaT./T;sigmaRho=.5*sqrt(sigmaA^2+sigmaB.^2);
        data=table(f(:),sigmaT(:)*1e6,T(:),repmat(sigmaA,numel(f),1), ...
            sigmaB(:),sigmaRho(:),f(:).*sigmaRho(:), ...
            'VariableNames',{'ULCarrier_Hz','TimingSigma_us','ObservationInterval_s', ...
            'OscillatorSigma_fractional','TimingDifferenceSigma_fractional', ...
            'RangeRateSigma_fractional','ULResidualFrequencySigma_Hz'});
    case "fig_2_19_search_threshold_scaling"
        n=double(cfg.public_figures.search_threshold.hypotheses(:));p=double(cfg.public_figures.search_threshold.pfa_total);
        eta=-log(1-(1-p).^(1./n));nref=double(cfg.public_figures.search_threshold.reference_hypotheses);
        etaRef=-log(1-(1-p)^(1/nref));
        data=table(n,eta,10*log10(eta/etaRef),repmat(p,numel(n),1),repmat(nref,numel(n),1), ...
            'VariableNames',{'Hypotheses','Eta','RelativeThresholdPenalty_dB','TotalPFA','ReferenceHypotheses'});
    case "fig_2_20_timing_pipeline_cdf"
        p=localRead(runDirectory,"timing_pipeline");p=p(p.SCS_kHz==120,:);
        columns=["UEPipelineSlots","BeamPipelineSlots","CellPipelineSlots"];
        labels=["UE-specific";"Beam-specific";"Cell-specific"];rows=cell(3,1);
        for i=1:3
            values=double(p.(columns(i)));t=localCDF(values,"PipelineSlots");t.Level(:)=labels(i);
            t.MeanSlots(:)=mean(values);t.P95Slots(:)=prctile(values,95);t.MaximumSlots(:)=max(values);rows{i}=t;
        end
        data=vertcat(rows{:});meta.EvidenceClass="SCHEDULER_SYSTEM";meta.Provenance="absolute_rtt_plus_processing_delay";
    case "fig_2_21_ta_guard_and_collision"
        bounds=[double(cfg.public_figures.ta_guard.beam_bound_ms);double(cfg.public_figures.ta_guard.report_steps_ms(:))];
        labels=["Beam-specific bound";string(cfg.public_figures.ta_guard.report_steps_ms(:))+" ms report step"];
        scs=double(cfg.public_figures.ta_guard.scs_khz(:));rows=cell(numel(scs),1);
        for i=1:numel(scs)
            slot=1/(scs(i)/15);rows{i}=table(repmat(scs(i),numel(bounds),1),labels,bounds, ...
                repmat(slot,numel(bounds),1),ceil(bounds/slot), ...
                'VariableNames',{'SCS_kHz','GuardSource','TimingBound_ms','SlotDuration_ms','RequiredGuardSlots'});
        end
        data=vertcat(rows{:});
    case "fig_2_22_residual_cfo_impact"
        x=double(cfg.public_figures.residual_cfo.normalized_grid(:));snr=double(cfg.public_figures.residual_cfo.input_snr_db(:));
        [epsilon,snrDb]=ndgrid(x,snr);g=ones(size(epsilon));mask=epsilon>0;g(mask)=(sin(pi*epsilon(mask))./(pi*epsilon(mask))).^2;
        gamma=10.^(snrDb/10);gammaEff=gamma.*g./(1+gamma.*(1-g));sir=g./max(1-g,eps);
        data=table(epsilon(:),snrDb(:),g(:),10*log10(sir(:)),10*log10(gammaEff(:)), ...
            snrDb(:)-10*log10(gammaEff(:)), ...
            'VariableNames',{'AbsoluteNormalizedCFO','InputSNR_dB','CoherentPowerGain', ...
            'ICISIR_dB','EffectiveSNR_dB','EffectiveSNRLoss_dB'});
    otherwise
        error("sixgr:ntn:resilientsync:UnknownPublicFigure", ...
            "No canonical data model exists for %s.",basename);
end
data.Properties.VariableUnits=localUnits(data);
meta.Assumptions.SampleCount=localSampleCount(data,cfg,basename);
meta.Assumptions.ErrorCombinationRule=string(cfg.geometry.timing_mapping.sign_convention);
end

function meta=localDiagramMeta(meta)
meta.EvidenceClass="ARCHITECTURE_DIAGRAM";meta.CalibrationStatus="NOT_APPLICABLE";
meta.ClaimStatus="CONCEPTUAL_OR_CATEGORICAL";meta.Provenance="configured_public_diagram";
end
function a=localAssumptions(cfg)
a=struct("OrbitType",string(cfg.geometry.orbit.type), ...
    "Altitude_km",double(cfg.geometry.orbit.altitude_km), ...
    "Elevation_deg",double(cfg.public_figures.baseline_elevation_deg), ...
    "BeamDiameter_km",double(cfg.k_offset.beam_diameter_km), ...
    "BeamRadius_km",double(cfg.k_offset.beam_diameter_km)/2, ...
    "CarrierUL_Hz",double([cfg.carriers.f_ul_hz]), ...
    "SCS_kHz",double(cfg.k_offset.scs_khz(:).'), ...
    "Seed",double(cfg.seed),"SampleCount",NaN, ...
    "TimingMappingFactor",double(cfg.geometry.timing_mapping.kappa_t), ...
    "ErrorCombinationRule",string(cfg.geometry.timing_mapping.sign_convention), ...
    "GeometryModel",string(cfg.gnss_free.geometry));
end
function n=localSampleCount(data,cfg,basename)
if any(basename==["fig_2_05_reference_area_timing_cdf","fig_2_06_reference_area_cfo_cdf", ...
        "fig_2_07_timing_vs_elevation","fig_2_08_cfo_vs_elevation"])
    n=double(cfg.gnss_free.drops_per_point);
elseif any(basename==["fig_2_13_beam_rtt_spread","fig_2_14_koffset_excess_delay_cdf", ...
        "fig_2_20_timing_pipeline_cdf"])
    n=double(cfg.k_offset.ue_drops_per_beam);
else
    n=height(data);
end
end
function carrier=localCarrier(cfg,id)
ids=string({cfg.carriers.id});index=find(ids==id,1);
if isempty(index),error("sixgr:ntn:resilientsync:MissingCarrier","Configured carrier %s is missing.",id);end
carrier=cfg.carriers(index);
end
function T=localRead(root,name)
path=fullfile(char(root),'tables',char(name+".csv"));
if exist(path,'file')~=2,error("sixgr:ntn:resilientsync:MissingFigureSource","Missing figure source %s.",path);end
T=readtable(path,'TextType','string','VariableNamingRule','preserve');
end
function raw=localRawReference(root,radiusKm,elevationDeg)
path=fullfile(char(root),'raw','campaign_a_reference_area', ...
    sprintf('reference_area_r%gkm_e%gdeg.mat',radiusKm,elevationDeg));
if exist(path,'file')~=2,error("sixgr:ntn:resilientsync:MissingFigureSource","Missing reference-area raw data %s.",path);end
s=load(path,'raw');raw=s.raw;
end
function T=localCDF(values,name)
values=sort(double(values(isfinite(values))));
if isempty(values),error("sixgr:ntn:resilientsync:EmptyCDF","CDF input is empty.");end
n=min(2000,numel(values));index=unique(round(linspace(1,numel(values),n))).';
T=table(values(index),index/numel(values),'VariableNames',{char(name),'CDF'});
end
function units=localUnits(T)
units=repmat({''},1,width(T));names=string(T.Properties.VariableNames);
for i=1:numel(names)
    n=names(i);
    if endsWith(n,"_us"),units{i}='us';elseif endsWith(n,"_ms"),units{i}='ms'; ...
    elseif endsWith(n,"_m_s"),units{i}='m/s';elseif endsWith(n,"_s"),units{i}='s'; ...
    elseif endsWith(n,"_Hz"),units{i}='Hz'; ...
    elseif endsWith(n,"_kHz"),units{i}='kHz';elseif endsWith(n,"_kmh"),units{i}='km/h'; ...
    elseif endsWith(n,"_km"),units{i}='km'; ...
    elseif endsWith(n,"_m"),units{i}='m';elseif contains(n,"deg"),units{i}='deg'; ...
    elseif contains(n,"CDF"),units{i}='1';elseif contains(n,"fractional"),units{i}='1';end
end
end
