classdef TrafficGeneratorFactory
    %TRAFFICGENERATORFACTORY Packet/session traffic for strict protocol runs.

    methods (Static)
        function traffic = generateCompatible(cfg,nUE,nTTI,tti_s)
            arguments
                cfg (1,1) struct
                nUE (1,1) double {mustBeInteger,mustBePositive}
                nTTI (1,1) double {mustBeInteger,mustBePositive}
                tti_s (1,1) double {mustBePositive}
            end
            protocol = sixgr.util.structGet(cfg,"protocol",struct());
            if ~logical(sixgr.util.structGet(protocol,"enabled",false))
                error("sixgr:protocol:UnsupportedCapability", ...
                    "Strict packet traffic was requested without protocol.enabled.");
            end
            seed = double(sixgr.util.structGet(cfg,"run.seed",1));
            sessionSpec = sixgr.util.structGet( ...
                protocol,"traffic.sessions",[]);
            if isempty(sessionSpec)
                error("sixgr:traffic:InvalidTrafficProfile", ...
                    "protocol.traffic.sessions must be configured explicitly.");
            end
            if iscell(sessionSpec)
                sessionSpec = [sessionSpec{:}];
            end
            durationMs = nTTI*tti_s*1000;
            offeredDL = zeros(nTTI,nUE);
            offeredUL = zeros(nTTI,nUE);
            packetRows = repmat(localPacketRow(),0,1);
            sessionRows = repmat(localSessionRow(),0,1);
            for ue = 1:nUE
                for sessionIndex = 1:numel(sessionSpec)
                    item = sessionSpec(sessionIndex);
                    profile = upper(string(localGet(item, ...
                        ["profile_id","ProfileID"],"CBR")));
                    packetBytes = double(localGet(item, ...
                        ["packet_bytes","PacketBytes"],1500));
                    rateMbps = double(localGet(item, ...
                        ["rate_mbps","RateMbps"],100));
                    periodMs = double(localGet(item, ...
                        ["period_ms","PeriodMs"],packetBytes*8/rateMbps/1000));
                    direction = upper(string(localGet(item, ...
                        ["direction","Direction"],"BIDIR")));
                    config = struct( ...
                        "SessionID","UE"+ue+"-S"+sessionIndex, ...
                        "FlowID","F"+sessionIndex, ...
                        "ProfileID",profile, ...
                        "PduSessionID",double(localGet(item, ...
                            ["pdu_session_id","PduSessionID"],1)), ...
                        "QFI",double(localGet(item,["qfi","QFI"],9)), ...
                        "FiveQI",double(localGet(item, ...
                            ["five_qi","FiveQI"],9)), ...
                        "PacketBytes",packetBytes, ...
                        "DeadlineMs",double(localGet(item, ...
                            ["deadline_ms","DeadlineMs"],50)), ...
                        "MasterSeed",seed);
                    session = sixgr.traffic18.TrafficSession(config);
                    generatorOptions = {"PeriodMs",periodMs};
                    if profile == "POISSON"
                        generatorOptions = {"LambdaPPS", ...
                            max(eps,rateMbps*1e6/(8*packetBytes))};
                    elseif profile == "XR_PDU_SET"
                        generatorOptions = {"PeriodMs",periodMs, ...
                            "PDUSetPackets",double(localGet(item, ...
                            ["pdu_set_packets","PDUSetPackets"],4))};
                    end
                    packets = session.generate(0,durationMs, ...
                        generatorOptions{:});
                    for packetIndex = 1:numel(packets)
                        packet = packets(packetIndex);
                        slot = min(nTTI,max(1, ...
                            floor(packet.ArrivalTime_ms/(tti_s*1000))+1));
                        bits = packet.PacketBytes*8;
                        if direction == "DL"
                            offeredDL(slot,ue) = offeredDL(slot,ue)+bits;
                        elseif direction == "UL"
                            offeredUL(slot,ue) = offeredUL(slot,ue)+bits;
                        elseif direction == "BIDIR"
                            if mod(packetIndex-1,2)==0
                                offeredDL(slot,ue) = offeredDL(slot,ue)+bits;
                            else
                                offeredUL(slot,ue) = offeredUL(slot,ue)+bits;
                            end
                        else
                            error("sixgr:traffic:InvalidTrafficProfile", ...
                                "Traffic direction must be DL, UL or BIDIR.");
                        end
                        packetRows(end+1,1) = localPacketRow(packet,ue, ...
                            direction); %#ok<AGROW>
                    end
                    sessionRows(end+1,1) = localSessionRow(session,ue, ...
                        numel(packets),sum([packets.PacketBytes]), ...
                        durationMs,direction); %#ok<AGROW>
                end
            end
            packetTable = struct2table(packetRows);
            sessionTable = struct2table(sessionRows);
            flowTable = localFlowTable(sessionSpec);
            traffic = struct( ...
                "Model","protocol_packet_sessions", ...
                "Transport","UDP", ...
                "FlowDirection",localDirection(sessionTable), ...
                "PacketDelayBudget_ms",min(sessionTable.Deadline_ms), ...
                "OfferedBits",offeredDL+offeredUL, ...
                "OfferedBitsDL",offeredDL, ...
                "OfferedBitsUL",offeredUL, ...
                "MeanBitsPerUEPerTTI",mean(offeredDL+offeredUL,1), ...
                "FlowTable",flowTable, ...
                "FlowCount",height(flowTable), ...
                "PacketTable",packetTable, ...
                "SessionTable",sessionTable, ...
                "ModelSource","sixgr.traffic18.TrafficGeneratorFactory", ...
                "Deterministic",true, ...
                "ProxyShapingUsed",false, ...
                "TransportSemanticClass","packet_accurate_udp", ...
                "TransportTruthLabel","strict_protocol_packet_events", ...
                "TransportApproximationReason","none");
        end
    end
end

function value = localGet(input,names,defaultValue)
value = defaultValue;
for name = names
    if isfield(input,char(name))
        value = input.(char(name));
        return;
    end
end
end

function row = localPacketRow(packet,ue,direction)
if nargin==0
    packet = struct("PacketID","","SessionID","","FlowID","", ...
        "ArrivalTime_ms",0,"PacketBytes",0,"PduSessionID",0, ...
        "QFI",0,"FiveQI",0,"Deadline_ms",0,"PDUSetID","", ...
        "RandomStream","","PayloadSHA256","");
    ue=0; direction="";
end
row = struct("PacketID",string(packet.PacketID), ...
    "SessionID",string(packet.SessionID),"FlowID",string(packet.FlowID), ...
    "UEID",double(ue),"Direction",string(direction), ...
    "ArrivalTime_ms",double(packet.ArrivalTime_ms), ...
    "PacketBytes",double(packet.PacketBytes), ...
    "PduSessionID",double(packet.PduSessionID), ...
    "QFI",double(packet.QFI),"FiveQI",double(packet.FiveQI), ...
    "Deadline_ms",double(packet.Deadline_ms), ...
    "PDUSetID",string(packet.PDUSetID), ...
    "RandomStream",string(packet.RandomStream), ...
    "PayloadSHA256",string(packet.PayloadSHA256));
end

function row = localSessionRow(session,ue,packets,bytes,stopMs,direction)
if nargin==0
    session=[];ue=0;packets=0;bytes=0;stopMs=0;direction="";
    row=struct("SessionID","","UEID",0,"ProfileID","", ...
        "PduSessionID",0,"QFI",0,"FiveQI",0,"Deadline_ms",0, ...
        "Direction","","PacketsGenerated",0,"BytesGenerated",0, ...
        "StartTime_ms",0,"StopTime_ms",0,"RandomStream","");
    return;
end
row=struct("SessionID",session.SessionID,"UEID",double(ue), ...
    "ProfileID",session.ProfileID,"PduSessionID",session.PduSessionID, ...
    "QFI",session.QFI,"FiveQI",session.FiveQI, ...
    "Deadline_ms",session.DeadlineMs,"Direction",string(direction), ...
    "PacketsGenerated",packets,"BytesGenerated",bytes, ...
    "StartTime_ms",0,"StopTime_ms",stopMs, ...
    "RandomStream",session.StreamIdentity);
end

function value = localDirection(tableValue)
directions=unique(tableValue.Direction);
if numel(directions)==1
    value=directions(1);
else
    value="BIDIR";
end
end

function value = localFlowTable(spec)
n=numel(spec);
value=table('Size',[n 12], ...
    'VariableTypes',{'string','double','double','string','string', ...
    'double','double','double','double','double','string','string'}, ...
    'VariableNames',{'Name','QFI','FiveQI','Protocol','Direction', ...
    'PacketDelayBudget_ms','PacketSize_bytes','PacketInterval_ms', ...
    'Rate_Mbps','Weight','Burstiness','ServiceProfile'});
for index=1:n
    item=spec(index);
    packetBytes=double(localGet(item,["packet_bytes","PacketBytes"],1500));
    rateMbps=double(localGet(item,["rate_mbps","RateMbps"],100));
    value(index,:)={string(localGet(item,["flow_id","FlowID"],"F"+index)), ...
        double(localGet(item,["qfi","QFI"],9)), ...
        double(localGet(item,["five_qi","FiveQI"],9)),"UDP", ...
        upper(string(localGet(item,["direction","Direction"],"BIDIR"))), ...
        double(localGet(item,["deadline_ms","DeadlineMs"],50)), ...
        packetBytes,packetBytes*8/rateMbps/1000,rateMbps,1, ...
        "packet_session",upper(string(localGet(item, ...
        ["profile_id","ProfileID"],"CBR")))};
end
end
