classdef PUSCHPowerController
    %PUSCHPOWERCONTROLLER Exact PUSCH open/closed-loop power application.

    methods (Static)
        function result = resolve(varargin)
            ip = inputParser;
            ip.addParameter("LoopId", [], @(x) isnumeric(x) && isscalar(x));
            ip.addParameter("AdjustmentMode", "", @(x) ischar(x) || isstring(x));
            ip.addParameter("Mu", [], @(x) isnumeric(x) && isscalar(x));
            ip.addParameter("MRB", [], @(x) isnumeric(x) && isscalar(x));
            ip.addParameter("P0Nominal_dBm", [], @(x) isnumeric(x) && isscalar(x));
            ip.addParameter("P0UE_dB", [], @(x) isnumeric(x) && isscalar(x));
            ip.addParameter("Alpha", [], @(x) isnumeric(x) && isscalar(x));
            ip.addParameter("MeasuredPathloss_dB", [], @(x) isnumeric(x) && isscalar(x));
            ip.addParameter("DeltaTF_dB", [], @(x) isnumeric(x) && isscalar(x));
            ip.addParameter("PreviousF_dB", [], @(x) isnumeric(x) && isscalar(x));
            ip.addParameter("TPCDelta_dB", [], @(x) isnumeric(x) && isscalar(x));
            ip.addParameter("PCMAX_dBm", [], @(x) isnumeric(x) && isscalar(x));
            ip.addParameter("ReferenceWaveformPower_dBm", [], @(x) isnumeric(x) && isscalar(x));
            ip.addParameter("PathlossReferenceRS", "", @(x) ischar(x) || isstring(x));
            ip.parse(varargin{:});
            o = ip.Results;

            mu = localInteger(o.Mu, 0, 4, "Mu");
            mrb = localInteger(o.MRB, 1, inf, "MRB");
            alpha = double(o.Alpha);
            if ~(isscalar(alpha) && isfinite(alpha) && alpha >= 0 && alpha <= 1)
                error("sixgr:pusch:InvalidPowerControlAlpha", ...
                    "PUSCH power-control alpha must be finite in [0,1].");
            end
            pathloss = double(o.MeasuredPathloss_dB);
            referenceRS = strtrim(string(o.PathlossReferenceRS));
            if ~(isscalar(pathloss) && isfinite(pathloss) && pathloss >= 0) ...
                    || strlength(referenceRS) == 0 ...
                    || contains(lower(referenceRS), "configured_snr")
                error("sixgr:pusch:PathlossMeasurementMissing", ...
                    "PUSCH power control requires measured nonnegative pathloss and its RS identity.");
            end
            mode = lower(strtrim(string(o.AdjustmentMode)));
            if mode == "accumulated"
                updatedF = localFinite(o.PreviousF_dB, "PreviousF_dB") + ...
                    localFinite(o.TPCDelta_dB, "TPCDelta_dB");
            elseif mode == "absolute"
                updatedF = localFinite(o.TPCDelta_dB, "TPCDelta_dB");
            else
                error("sixgr:pusch:InvalidPowerAdjustmentMode", ...
                    "AdjustmentMode must be accumulated or absolute.");
            end
            requested = localFinite(o.P0Nominal_dBm, "P0Nominal_dBm") + ...
                localFinite(o.P0UE_dB, "P0UE_dB") + ...
                10 * log10((2 ^ mu) * mrb) + alpha * pathloss + ...
                localFinite(o.DeltaTF_dB, "DeltaTF_dB") + updatedF;
            pcmax = localFinite(o.PCMAX_dBm, "PCMAX_dBm");
            applied = min(pcmax, requested);
            reference = localFinite(o.ReferenceWaveformPower_dBm, ...
                "ReferenceWaveformPower_dBm");
            scale = 10 ^ ((applied - reference) / 20);

            result = struct( ...
                "LoopId", localInteger(o.LoopId, 0, inf, "LoopId"), ...
                "AdjustmentMode", mode, ...
                "Mu", mu, ...
                "MRB", mrb, ...
                "P0Nominal_dBm", double(o.P0Nominal_dBm), ...
                "P0UE_dB", double(o.P0UE_dB), ...
                "Alpha", alpha, ...
                "MeasuredPathloss_dB", pathloss, ...
                "DeltaTF_dB", double(o.DeltaTF_dB), ...
                "PreviousF_dB", double(o.PreviousF_dB), ...
                "TPCDelta_dB", double(o.TPCDelta_dB), ...
                "UpdatedF_dB", updatedF, ...
                "RequestedPower_dBm", requested, ...
                "PCMAX_dBm", pcmax, ...
                "AppliedPower_dBm", applied, ...
                "PowerHeadroom_dB", pcmax - requested, ...
                "ReferenceWaveformPower_dBm", reference, ...
                "AmplitudeScale", scale, ...
                "Clipped", applied < requested, ...
                "PathlossReferenceRS", referenceRS, ...
                "FormulaIncludesMuFactor", true, ...
                "Source", "TS_38_213_PUSCH_power_control");
        end

        function [waveform, evidence] = apply(waveform, result)
            if ~isstruct(result) || ~isfield(result, "AmplitudeScale")
                error("sixgr:pusch:PowerControlStateMissing", ...
                    "Resolved PUSCH power-control evidence is required.");
            end
            if ~(isnumeric(waveform) && ~isempty(waveform) && ...
                    all(isfinite(real(waveform(:)))) && all(isfinite(imag(waveform(:)))))
                error("sixgr:pusch:InvalidWaveform", ...
                    "PUSCH power control requires a finite nonempty waveform.");
            end
            inputPower = mean(abs(double(waveform(:))).^2);
            waveform = waveform .* double(result.AmplitudeScale);
            outputPower = mean(abs(double(waveform(:))).^2);
            measuredGain = 10 * log10(outputPower / inputPower);
            expectedGain = 20 * log10(double(result.AmplitudeScale));
            evidence = result;
            evidence.InputMeanPower = inputPower;
            evidence.OutputMeanPower = outputPower;
            evidence.ExpectedGain_dB = expectedGain;
            evidence.MeasuredGain_dB = measuredGain;
            evidence.PowerError_dB = abs(measuredGain - expectedGain);
            evidence.WaveformScaled = true;
        end
    end
end

function value = localInteger(raw, minimum, maximum, name)
value = double(raw);
if ~(isscalar(value) && isfinite(value) && value == fix(value) ...
        && value >= minimum && value <= maximum)
    error("sixgr:pusch:InvalidPowerControlInteger", ...
        "%s must be an integer in [%g,%g].", name, minimum, maximum);
end
end

function value = localFinite(raw, name)
value = double(raw);
if ~(isscalar(value) && isfinite(value))
    error("sixgr:pusch:InvalidPowerControlValue", ...
        "%s must be a finite scalar.", name);
end
end
