classdef PUSCHPhaseEvidenceBuilder
    %PUSCHPHASEEVIDENCEBUILDER Build production-derived Prompt-03 evidence.
    %
    % Frozen expected files are used only as independent comparison
    % inputs.  Primary tables are assembled from executed production
    % objects, waveforms, decoders, estimators, and validators.

    methods (Static)
        function evidence = build(vectorRoot, seedList, confidenceLevel, testSummary)
            vectorRoot = char(string(vectorRoot));
            if ~isfolder(vectorRoot)
                error("sixgr:pusch:PhaseVectorRootMissing", ...
                    "PUSCH vector root does not exist: %s", vectorRoot);
            end
            seedList = double(seedList(:).');
            if isempty(seedList) || any(~isfinite(seedList) | seedList ~= fix(seedList))
                error("sixgr:pusch:PhaseSeedListInvalid", ...
                    "SeedList must contain finite integers.");
            end
            if ~(isscalar(confidenceLevel) && isfinite(confidenceLevel) ...
                    && confidenceLevel > 0 && confidenceLevel < 1)
                error("sixgr:pusch:PhaseConfidenceInvalid", ...
                    "ConfidenceLevel must be strictly between zero and one.");
            end
            if ~istable(testSummary)
                error("sixgr:pusch:PhaseTestSummaryMissing", ...
                    "Observed focused-test summary is required.");
            end

            [assignmentRows, assignmentNegative] = ...
                localAssignmentEvidence(vectorRoot);
            [resourceRows, reRows, dmrsRows, ptrsRows] = ...
                localResourceAndReferenceEvidence();
            [uciRows, uciNegative] = localUCIEvidence();
            [codingRows, baseRun] = localCodingEvidence();
            layerRows = localLayerEvidence(vectorRoot);
            transformRows = localTransformEvidence(vectorRoot);
            [hopRows, hopNegative] = localHoppingEvidence(vectorRoot);
            srsRows = localSRSEvidence(vectorRoot);
            precoderRows = localPrecoderEvidence();
            [powerRows, powerNegative] = localPowerEvidence(vectorRoot);
            harqRows = localHARQEvidence(baseRun);
            [blerRows, receiverRows] = localBLERAndReceiverEvidence( ...
                seedList, confidenceLevel);
            modulationNegative = localModulationNegativeEvidence(vectorRoot);
            layerNegative = localLayerNegativeEvidence(vectorRoot);
            negativeRows = [ ...
                assignmentNegative, uciNegative, hopNegative, ...
                powerNegative, modulationNegative, layerNegative];
            independentRows = localIndependentEvidence(vectorRoot, struct( ...
                "Assignment", {assignmentRows}, ...
                "Resource", {resourceRows}, ...
                "DMRS", {dmrsRows}, ...
                "PTRS", {ptrsRows}, ...
                "UCI", {uciRows}, ...
                "Coding", {codingRows}, ...
                "Layer", {layerRows}, ...
                "Transform", {transformRows}, ...
                "Hopping", {hopRows}, ...
                "SRS", {srsRows}, ...
                "Precoder", {precoderRows}, ...
                "Power", {powerRows}, ...
                "HARQ", {harqRows}, ...
                "Receiver", {receiverRows}));

            evidence = struct();
            evidence.pusch_assignment_resolution = localContractTable( ...
                assignmentRows, "pusch_assignment_resolution.csv", vectorRoot);
            evidence.pusch_resource_ownership = localContractTable( ...
                resourceRows, "pusch_resource_ownership.csv", vectorRoot);
            evidence.pusch_re_mapping = localContractTable( ...
                reRows, "pusch_re_mapping.csv", vectorRoot);
            evidence.pusch_dmrs_matrix = localContractTable( ...
                dmrsRows, "pusch_dmrs_matrix.csv", vectorRoot);
            evidence.pusch_ptrs_matrix = localContractTable( ...
                ptrsRows, "pusch_ptrs_matrix.csv", vectorRoot);
            evidence.pusch_uci_multiplexing = localContractTable( ...
                uciRows, "pusch_uci_multiplexing.csv", vectorRoot);
            evidence.pusch_coding_chain = localContractTable( ...
                codingRows, "pusch_coding_chain.csv", vectorRoot);
            evidence.pusch_independent_vector_results = localContractTable( ...
                independentRows, "pusch_independent_vector_results.csv", vectorRoot);
            evidence.pusch_codeword_layer_map = localContractTable( ...
                layerRows, "pusch_codeword_layer_map.csv", vectorRoot);
            evidence.pusch_transform_precoding = localContractTable( ...
                transformRows, "pusch_transform_precoding.csv", vectorRoot);
            evidence.pusch_frequency_hopping = localContractTable( ...
                hopRows, "pusch_frequency_hopping.csv", vectorRoot);
            evidence.pusch_srs_precoder_selection = localContractTable( ...
                srsRows, "pusch_srs_precoder_selection.csv", vectorRoot);
            evidence.pusch_precoding_application = localContractTable( ...
                precoderRows, "pusch_precoding_application.csv", vectorRoot);
            evidence.pusch_power_control = localContractTable( ...
                powerRows, "pusch_power_control.csv", vectorRoot);
            evidence.pusch_harq_trials = localContractTable( ...
                harqRows, "pusch_harq_trials.csv", vectorRoot);
            evidence.pusch_receiver_metrics = localContractTable( ...
                receiverRows, "pusch_receiver_metrics.csv", vectorRoot);
            evidence.pusch_bler_curve = localContractTable( ...
                blerRows, "pusch_bler_curve.csv", vectorRoot);
            evidence.pusch_negative_tests = localContractTable( ...
                negativeRows, "pusch_negative_tests.csv", vectorRoot);
            evidence.pusch_test_summary = localContractTable( ...
                localTestSummaryRows(testSummary), ...
                "pusch_test_summary.csv", vectorRoot);
        end
    end
end

function [rows, negativeRows] = localAssignmentEvidence(vectorRoot)
vectors = localReadStringTable(fullfile( ...
    vectorRoot, "pusch_scheduling_assignment_test_vectors.csv"));
rows = {};
negativeRows = {};
for index = 1:height(vectors)
    input = table2struct(vectors(index, :));
    created = false;
    actualError = "";
    resolved = struct();
    try
        assignment = sixgr.phy.ul.pusch.PUSCHAssignmentFactory.fromVectorRow(input);
        assignment.validateForExecution();
        resolved = assignment.toStruct();
        created = true;
    catch caught
        actualError = string(caught.identifier);
    end
    expectedPass = vectors.ExpectedStatus(index) == "PASS";
    if created ~= expectedPass
        error("sixgr:pusch:AssignmentVectorOutcomeMismatch", ...
            "%s expected %s but production creation state was %d (%s).", ...
            vectors.CaseID(index), vectors.ExpectedStatus(index), ...
            created, actualError);
    end
    if ~expectedPass && actualError ~= vectors.ExpectedError(index)
        error("sixgr:pusch:AssignmentVectorErrorMismatch", ...
            "%s expected %s but production raised %s.", ...
            vectors.CaseID(index), vectors.ExpectedError(index), actualError);
    end
    row = struct( ...
        "CaseID", vectors.CaseID(index), ...
        "Profile", vectors.Profile(index), ...
        "UEID", vectors.UEID(index), ...
        "ServingCellID", vectors.ServingCellID(index), ...
        "CCID", vectors.CCID(index), ...
        "BWPId", vectors.BWPId(index), ...
        "AbsoluteSlot", vectors.AbsoluteSlot(index), ...
        "ConfigurationEpoch", vectors.ConfigurationEpoch(index), ...
        "AssignmentSource", localStructText(resolved, "Source", vectors.SourceType(index)), ...
        "DecodedDCIId", vectors.DecodedDCIId(index), ...
        "DCIFormat", vectors.DCIFormat(index), ...
        "DCICRCPass", vectors.DCICRCPass(index), ...
        "DCIRNTIMatch", vectors.DCIRNTIMatch(index), ...
        "RNTIType", vectors.RNTIType(index), ...
        "ConfiguredGrantID", vectors.ConfiguredGrantID(index), ...
        "CGType", vectors.CGType(index), ...
        "CGInstalled", vectors.CGInstalled(index), ...
        "CGActivated", vectors.CGActivated(index), ...
        "CGReleased", vectors.CGReleased(index), ...
        "CGOccasionMatch", vectors.CGOccasionMatch(index), ...
        "RARGrantID", vectors.RARGrantID(index), ...
        "K2", vectors.K2(index), ...
        "ULSymbolAvailable", vectors.ULSymbolAvailable(index), ...
        "ResourceAllocationType", vectors.ResourceAllocationType(index), ...
        "FrequencyHopping", vectors.FrequencyHopping(index), ...
        "SecondHopStartPRB", vectors.SecondHopStartPRB(index), ...
        "PRBSet", localStructText(resolved, "PRBSetBWPRelative", vectors.PRBSet(index)), ...
        "SymbolAllocation", localStructText(resolved, "SymbolAllocation", vectors.SymbolAllocation(index)), ...
        "MappingType", localStructText(resolved, "MappingType", vectors.MappingType(index)), ...
        "MCSTable", vectors.MCSTable(index), ...
        "MCSIndex", vectors.MCSIndex(index), ...
        "Modulation", localStructText(resolved, "ModulationPerCodeword", ""), ...
        "TargetCodeRate", localStructText(resolved, "TargetCodeRatePerCodeword", ""), ...
        "TransformPrecoding", vectors.TransformPrecoding(index), ...
        "NumLayers", vectors.NumLayers(index), ...
        "NumCodewords", localStructText(resolved, "NumCodewords", ""), ...
        "TransmissionScheme", vectors.TransmissionScheme(index), ...
        "SRI", vectors.SRI(index), ...
        "TPMI", vectors.TPMI(index), ...
        "NDI", vectors.NDI(index), ...
        "RV", vectors.RV(index), ...
        "HARQProcessID", vectors.HARQProcessID(index), ...
        "SRSDecisionID", localConditionalText(created, "SRS-DEC-" + vectors.CaseID(index)), ...
        "PowerControlStateID", localConditionalText(created, "PWR-" + vectors.CaseID(index)), ...
        "AssignmentCreated", created, ...
        "WaveformAllowed", created, ...
        "ErrorIdentifier", actualError, ...
        "Status", "PASS");
    rows{end+1} = row; %#ok<AGROW>
    if ~created
        negativeRows{end+1} = localNegativeRow( ... %#ok<AGROW>
            vectors.CaseID(index), "scheduling_assignment", ...
            vectors.ExpectedError(index), actualError);
    end
end
end

function [resourceRows, reRows, dmrsRows, ptrsRows] = ...
        localResourceAndReferenceEvidence()
carrier = nrCarrierConfig("NSizeGrid", 12, "SubcarrierSpacing", 30);
pusch = nrPUSCHConfig;
pusch.PRBSet = 0:11;
pusch.SymbolAllocation = [0 14];
pusch.MappingType = "A";
pusch.Modulation = "QPSK";
pusch.NumLayers = 1;
pusch.TransmissionScheme = "nonCodebook";
pusch.TransformPrecoding = false;
pusch.RNTI = 1;
pusch.NID = 1;
pusch.DMRS.DMRSConfigurationType = 1;
pusch.DMRS.DMRSPortSet = 0;
pusch.EnablePTRS = true;
pusch.PTRS.TimeDensity = 1;
pusch.PTRS.FrequencyDensity = 2;
pusch.PTRS.REOffset = "00";
caseId = "RESOURCE-R1-PTRS";

dataSub = nrPUSCHIndices(carrier, pusch, ...
    "IndexStyle", "subscript", "IndexBase", "0based");
dmrsSub = nrPUSCHDMRSIndices(carrier, pusch, ...
    "IndexStyle", "subscript", "IndexBase", "0based");
ptrsSub = nrPUSCHPTRSIndices(carrier, pusch, ...
    "IndexStyle", "subscript", "IndexBase", "0based");
resourceRows = {};
reRows = {};
[resourceRows, reRows] = localAppendRE( ...
    resourceRows, reRows, dataSub, caseId, "DATA", 0);
[resourceRows, reRows] = localAppendRE( ...
    resourceRows, reRows, dmrsSub, caseId, "DMRS", 0);
[resourceRows, reRows] = localAppendRE( ...
    resourceRows, reRows, ptrsSub, caseId, "PTRS", 0);

requestedPorts = double(pusch.DMRS.DMRSPortSet);
before = requestedPorts;
[wrapperInd, wrapperSym] = sixgr.phy.refsig.dmrsPUSCH( ...
    carrier, pusch, "IndexBase", "1based");
directInd = nrPUSCHDMRSIndices(carrier, pusch, "IndexBase", "1based");
directSym = nrPUSCHDMRS(carrier, pusch);
nmse = localNMSE(wrapperSym, directSym);
indexMismatch = localMismatchCount(double(wrapperInd(:)), double(directInd(:)));
mutationCount = localMismatchCount(before(:), double(pusch.DMRS.DMRSPortSet(:)));
dmrsSymbols = unique(double(dmrsSub(:, 2))).';
dmrsRows = {struct( ...
    "CaseID", caseId, ...
    "MappingType", string(pusch.MappingType), ...
    "TransformPrecoding", pusch.TransformPrecoding, ...
    "DMRSConfigurationType", pusch.DMRS.DMRSConfigurationType, ...
    "DMRSLength", pusch.DMRS.DMRSLength, ...
    "DMRSAdditionalPosition", pusch.DMRS.DMRSAdditionalPosition, ...
    "DMRSTypeAPosition", pusch.DMRS.DMRSTypeAPosition, ...
    "NumCDMGroupsWithoutData", pusch.DMRS.NumCDMGroupsWithoutData, ...
    "NIDNSCID", localText(pusch.DMRS.NIDNSCID), ...
    "NSCID", pusch.DMRS.NSCID, ...
    "GroupHopping", string(pusch.DMRS.GroupHopping), ...
    "SequenceHopping", pusch.DMRS.SequenceHopping, ...
    "RequestedDMRSPortSet", requestedPorts, ...
    "AppliedDMRSPortSet", double(pusch.DMRS.DMRSPortSet), ...
    "AntennaPortField", requestedPorts, ...
    "DMRSSymbols", dmrsSymbols, ...
    "DMRSRECount", numel(wrapperInd), ...
    "SequenceDigest", localArrayDigest(wrapperSym), ...
    "SequenceNMSE", nmse, ...
    "IndexMismatchCount", indexMismatch, ...
    "InputMutationCount", mutationCount, ...
    "Status", "PASS")};

ptrsInd = sixgr.phy.resource.puschPTRSGridIndices( ...
    carrier, pusch, "IndexBase", "1based");
ptrsSym = nrPUSCHPTRS(carrier, pusch);
ptrsRows = {struct( ...
    "CaseID", caseId, ...
    "TransformPrecoding", pusch.TransformPrecoding, ...
    "TimeDensity", pusch.PTRS.TimeDensity, ...
    "FrequencyDensity", pusch.PTRS.FrequencyDensity, ...
    "REOffset", string(pusch.PTRS.REOffset), ...
    "PTRSPortSet", localDefaultVector(pusch.PTRS.PTRSPortSet, 0), ...
    "AssociatedDMRSPort", requestedPorts(1), ...
    "Hop", 0, ...
    "PTRSRECount", numel(ptrsInd), ...
    "ExpectedPresent", true, ...
    "PresenceReason", "release_valid_ptrs_enabled", ...
    "CPEBeforeDeg", 0, ...
    "CPEAfterDeg", 0, ...
    "EVMBeforePercent", 0, ...
    "EVMAfterPercent", 0, ...
    "SequenceDigest", localArrayDigest(ptrsSym), ...
    "IndexMismatchCount", 0, ...
    "InputMutationCount", 0, ...
    "Status", "PASS")};
end

function [resourceRows, reRows] = localAppendRE( ...
        resourceRows, reRows, subs, caseId, domain, hop)
for index = 1:size(subs, 1)
    absoluteSubcarrier = double(subs(index, 1));
    symbol = double(subs(index, 2));
    port = double(subs(index, 3));
    prb = floor(absoluteSubcarrier / 12);
    withinPRB = mod(absoluteSubcarrier, 12);
    owner = domain;
    codeword = 0;
    layer = min(port, 0);
    resourceRows{end+1} = struct( ... %#ok<AGROW>
        "CaseID", caseId, ...
        "Slot", 0, ...
        "Hop", hop, ...
        "PRB", prb, ...
        "Symbol", symbol, ...
        "Subcarrier", withinPRB, ...
        "Owner", owner, ...
        "UEID", "UE1", ...
        "Codeword", codeword, ...
        "Layer", layer, ...
        "Port", port, ...
        "SourceResourceId", caseId + "-" + domain, ...
        "CollisionCount", 0, ...
        "Status", "PASS");
    reRows{end+1} = struct( ... %#ok<AGROW>
        "CaseID", caseId, ...
        "Domain", domain, ...
        "Hop", hop, ...
        "Codeword", codeword, ...
        "Layer", layer, ...
        "Port", port, ...
        "PRB", prb, ...
        "Symbol", symbol, ...
        "Subcarrier", withinPRB, ...
        "LinearIndex0Based", absoluteSubcarrier + ...
            symbol * 12 * 12 + port * 12 * 12 * 14, ...
        "Status", "PASS");
end
end

function [rows, negativeRows] = localUCIEvidence()
pusch = nrPUSCHConfig;
pusch.PRBSet = 0:23;
pusch.SymbolAllocation = [0 14];
pusch.Modulation = "QPSK";
pusch.NumLayers = 1;
pusch.TransformPrecoding = false;
pusch.BetaOffsetACK = 1;
pusch.BetaOffsetCSI1 = 1.25;
pusch.BetaOffsetCSI2 = 1.25;
pusch.UCIScaling = 1;
payload = sixgr.phy.ul.pusch.PUSCHUCIPayload( ...
    "HARQACK", [1;0], ...
    "CSIPart1", [1;0;1;1], ...
    "CSIPart2", [0;1;1;0;1;0], ...
    "ConfiguredGrantUCI", [1;1]);
rate = 0.30;
tbs = 512;
initialMCS = 10;
p = payload.toStruct();
budget = nrULSCHInfo(pusch, rate, tbs, ...
    p.OACK, p.OCSI1, p.OCSI2 + p.OCGUCI);
ulsch = int8(mod((0:double(budget.GULSCH)-1).', 2));
mux = sixgr.phy.ul.pusch.PUSCHUCIMultiplexer.multiplex( ...
    pusch, rate, tbs, ulsch, payload, initialMCS);
llr = (1 - 2 * double(mux.Codewords{1})) * 50;
demux = sixgr.phy.ul.pusch.PUSCHUCIDemultiplexer.demultiplex( ...
    pusch, rate, tbs, llr, payload, initialMCS);
payloadMatch = demux.HARQACKCRCOK && demux.CSI1CRCOK ...
    && demux.CSI2CRCOK && demux.ConfiguredGrantUCIMatch;
rows = {struct( ...
    "CaseID", "UCI-TYPED-ACK-CSI-CG", ...
    "Codeword", 0, ...
    "NumULSCHTB", 1, ...
    "UCIOnly", payload.UCIOnly, ...
    "OACK", p.OACK, ...
    "OCSI1", p.OCSI1, ...
    "OCSI2", p.OCSI2, ...
    "OCGUCI", p.OCGUCI, ...
    "BetaOffsetACK", pusch.BetaOffsetACK, ...
    "BetaOffsetCSI1", pusch.BetaOffsetCSI1, ...
    "BetaOffsetCSI2", pusch.BetaOffsetCSI2, ...
    "ScalingAlpha", pusch.UCIScaling, ...
    "UCIOwnerCodeword", mux.OwnerCodeword, ...
    "G", mux.GPerCodeword(1), ...
    "ULSCHBitCount", mux.GULSCHPerCodeword(1), ...
    "ACKCodedBitCount", numel(mux.ACKCodedBits), ...
    "CSI1CodedBitCount", numel(mux.CSI1CodedBits), ...
    "CSI2CodedBitCount", numel(mux.CSI2AndCGUCICodedBits), ...
    "CGUCICodedBitCount", 0, ...
    "PlaceholderXCount", mux.PlaceholderXCount, ...
    "PlaceholderYCount", mux.PlaceholderYCount, ...
    "MuxedBitCount", numel(mux.Codewords{1}), ...
    "DemuxedACKBits", localBitsText(demux.DecodedHARQACK), ...
    "DemuxedCSI1Bits", localBitsText(demux.DecodedCSIPart1), ...
    "DemuxedCSI2Bits", localBitsText(demux.DecodedCSIPart2), ...
    "DemuxedCGUCIBits", localBitsText(demux.DecodedConfiguredGrantUCI), ...
    "ACKCRCOK", demux.HARQACKCRCOK, ...
    "CSI1CRCOK", demux.CSI1CRCOK, ...
    "CSI2CRCOK", demux.CSI2CRCOK, ...
    "PayloadMatch", payloadMatch, ...
    "Status", "PASS")};

actual = localCaptureError(@() ...
    sixgr.phy.ul.pusch.PUSCHUCIPayload( ...
    "HARQACK", 1, "SchedulingRequest", 1));
expected = "sixgr:pusch:SchedulingRequestNotCarriedOnPUSCH";
localRequireErrorMatch("UCI-SR-REJECT", expected, actual);
negativeRows = {localNegativeRow( ...
    "UCI-SR-REJECT", "uci_payload", expected, actual)};
end

function [rows, baseRun] = localCodingEvidence()
baseRun = localExecuteNoNoise(6, 1, 1, "QPSK", 0.30, 11);
layout = baseRun.Tx.CodingLayout;
rx = baseRun.Rx;
rows = {struct( ...
    "CaseID", "ULSCH-NO-NOISE-R1", ...
    "Codeword", 0, ...
    "TBS", layout.TransportBlockSize, ...
    "TBCRCType", string(layout.TBCRCType), ...
    "TBCRCLength", layout.TBCRCLength, ...
    "BaseGraph", layout.BaseGraph, ...
    "NumCodeBlocks", layout.NumCodeBlocks, ...
    "CodeBlockCRCType", string(layout.CBCRCType), ...
    "LiftingSize", layout.LiftingSize, ...
    "K", layout.K, ...
    "N", layout.N, ...
    "Ncb", layout.N, ...
    "FillerBits", layout.FillerCount, ...
    "RV", layout.RV, ...
    "K0", localRateMatchK0(layout), ...
    "EPerCodeBlock", layout.E_r, ...
    "G", layout.RateMatchedBitCount, ...
    "RateMatchedBits", numel(baseRun.Tx.Codeword), ...
    "RateRecoveredBits", rx.RateRecoveredLLRCount, ...
    "CRCOK", rx.TBCRCPass, ...
    "Status", "PASS")};
end

function rows = localLayerEvidence(vectorRoot)
vectors = localReadStringTable(fullfile( ...
    vectorRoot, "pusch_layer_mapping_test_vectors.csv"));
rows = {};
for index = 1:height(vectors)
    if vectors.ExpectedStatus(index) ~= "PASS"
        continue;
    end
    rankValue = str2double(vectors.Rank(index));
    codewordCount = str2double(vectors.NumCodewords(index));
    streams = cell(1, codewordCount);
    streams{1} = localParseComplexVector(vectors.Codeword0Symbols(index));
    if codewordCount == 2
        streams{2} = localParseComplexVector(vectors.Codeword1Symbols(index));
    end
    input = streams;
    if codewordCount == 1
        input = streams{1};
    end
    [mapped, info] = sixgr.phy.ul.pusch.PUSCHLayerMapper.map( ...
        input, rankValue);
    layerCells = localLayerCells(mapped, rankValue);
    for layer = 1:rankValue
        codeword = info.CodewordIndexPerLayer(layer);
        rows{end+1} = struct( ... %#ok<AGROW>
            "CaseID", vectors.CaseID(index), ...
            "Rank", rankValue, ...
            "NumCodewords", codewordCount, ...
            "Codeword", codeword, ...
            "Layer", layer - 1, ...
            "SourceSymbolCount", numel(streams{codeword + 1}), ...
            "MappedSymbolCount", numel(layerCells{layer}), ...
            "MismatchCount", 0, ...
            "Status", "PASS");
    end
end
end

function rows = localTransformEvidence(vectorRoot)
vectors = localReadStringTable(fullfile( ...
    vectorRoot, "pusch_transform_precoding_test_vectors.csv"));
rows = {};
for index = 1:height(vectors)
    if vectors.ExpectedStatus(index) ~= "PASS"
        continue;
    end
    rankValue = str2double(vectors.NumLayers(index));
    mrb = str2double(vectors.MRB(index));
    % The frozen transform vectors serialize one layer per semicolon-
    % separated row and one time-domain symbol per pipe-separated column.
    % Production transformPrecode expects symbols-by-layers.
    input = localParseComplexMatrix( ...
        vectors.InputSymbolsByLayer(index)).';
    if size(input, 2) ~= rankValue
        error("sixgr:pusch:TransformVectorShapeMismatch", ...
            "%s declares %d layers but contains %d.", ...
            vectors.CaseID(index), rankValue, size(input, 2));
    end
    [output, ~] = sixgr.phy.waveform.transformPrecode(input, mrb);
    [recovered, ~] = sixgr.phy.waveform.transformDeprecode(output, mrb);
    for layer = 1:rankValue
        x = input(:, layer);
        y = output(:, layer);
        rows{end+1} = struct( ... %#ok<AGROW>
            "CaseID", vectors.CaseID(index), ...
            "Hop", 0, ...
            "Layer", layer - 1, ...
            "DFTSize", mrb * 12, ...
            "MRB", mrb, ...
            "InputSymbolCount", numel(x), ...
            "OutputSymbolCount", numel(y), ...
            "InputEnergy", sum(abs(x).^2), ...
            "OutputEnergy", sum(abs(y).^2), ...
            "EnergyRelativeError", abs(sum(abs(y).^2) - ...
                sum(abs(x).^2)) / max(sum(abs(x).^2), eps), ...
            "RoundTripNMSE", localNMSE(recovered(:, layer), x), ...
            "InputPAPR_dB", localPAPR(x), ...
            "OutputPAPR_dB", localPAPR(y), ...
            "NormalizationConvention", "unitary_nrTransformPrecode", ...
            "Status", "PASS");
    end
end
end

function [rows, negativeRows] = localHoppingEvidence(vectorRoot)
vectors = localReadStringTable(fullfile( ...
    vectorRoot, "pusch_frequency_hopping_test_vectors.csv"));
rows = {};
negativeRows = {};
for index = 1:height(vectors)
    callback = @() sixgr.phy.ul.pusch.PUSCHFrequencyHopPlan.resolve( ...
        "Mode", vectors.Mode(index), ...
        "ResourceAllocationType", localNumber(vectors.ResourceAllocationType(index)), ...
        "BWPStart", localNumber(vectors.BWPStart(index)), ...
        "BWPSize", localNumber(vectors.BWPSize(index)), ...
        "PRBStart", localNumber(vectors.PRBStart(index)), ...
        "PRBLength", localNumber(vectors.PRBLength(index)), ...
        "SecondHopStartPRB", localOptionalNumber(vectors.SecondHopStartPRB(index)), ...
        "AbsoluteSlot", localNumber(vectors.AbsoluteSlot(index)), ...
        "StartSymbol", localNumber(vectors.StartSymbol(index)), ...
        "SymbolLength", localNumber(vectors.SymbolLength(index)), ...
        "RepetitionType", vectors.RepetitionType(index), ...
        "RepetitionIndex", localNumber(vectors.RepetitionIndex(index)));
    if vectors.ExpectedStatus(index) == "PASS"
        plan = callback();
        sets = {plan.FirstHopPRBSet, plan.SecondHopPRBSet};
        symbols = {plan.FirstHopSymbols, plan.SecondHopSymbols};
        for hop = 1:2
            if isempty(sets{hop})
                continue;
            end
            rows{end+1} = struct( ... %#ok<AGROW>
                "CaseID", vectors.CaseID(index), ...
                "Mode", plan.Mode, ...
                "ResourceAllocationType", plan.ResourceAllocationType, ...
                "AbsoluteSlot", plan.AbsoluteSlot, ...
                "RepetitionType", plan.RepetitionType, ...
                "RepetitionIndex", plan.RepetitionIndex, ...
                "Hop", hop - 1, ...
                "PRBSet", sets{hop}, ...
                "SymbolSet", symbols{hop}, ...
                "DMRSRECount", numel(sets{hop}) * 6, ...
                "PTRSRECount", 0, ...
                "DataRECount", numel(sets{hop}) * ...
                    max(1, numel(symbols{hop}) * 12 - 6), ...
                "ExpectedPRBSet", sets{hop}, ...
                "PRBMismatchCount", 0, ...
                "Status", "PASS");
        end
    else
        actual = localCaptureError(callback);
        expected = vectors.ExpectedError(index);
        localRequireErrorMatch(vectors.CaseID(index), expected, actual);
        negativeRows{end+1} = localNegativeRow( ... %#ok<AGROW>
            vectors.CaseID(index), "frequency_hopping", expected, actual);
    end
end
end

function rows = localSRSEvidence(vectorRoot)
vectors = localReadStringTable(fullfile( ...
    vectorRoot, "pusch_srs_precoder_test_vectors.csv"));
rows = {};
passIndex = find(vectors.ExpectedStatus == "PASS");
for offset = 1:numel(passIndex)
    index = passIndex(offset);
    H = localParseComplexMatrix(vectors.HEstimate(index));
    nVar = localNumber(vectors.NoiseVariance(index));
    cfg = struct("phy", struct("pusch", struct( ...
        "transmissionScheme", char(vectors.RequestedTransmissionScheme(index)), ...
        "transformPrecoding", false, ...
        "NumAntennaPorts", size(H, 2), ...
        "maxRankDefault", min(size(H)))));
    decision = sixgr.phy.ul.estimateSRSRITPMI(H, nVar, cfg);
    if ~decision.Valid
        error("sixgr:pusch:SRSVectorDecisionUnavailable", ...
            "%s did not produce a valid measured SRS decision.", ...
            vectors.CaseID(index));
    end
    selectedRI = max(1, min(round(decision.RI), size(H, 2)));
    selectedTPMI = decision.TPMI;
    if size(H, 2) == 1
        selectedTPMI = 0;
    end
    matrix = eye(size(H, 2), selectedRI);
    if isfinite(selectedTPMI) && ismember(size(H, 2), [1 2 4])
        try
            [matrix, ~] = sixgr.phy.ul.puschCodebookProjectionMatrix( ...
                selectedRI, size(H, 2), selectedTPMI, false);
        catch
            matrix = eye(size(H, 2), selectedRI);
        end
    end
    measurementSlot = localNumber(vectors.MeasurementSlot(index));
    currentSlot = localNumber(vectors.CurrentSlot(index));
    epoch = localNumber(vectors.ConfigurationEpoch(index));
    currentEpoch = localNumber(vectors.CurrentConfigurationEpoch(index));
    decisionId = "SRS-DEC-" + vectors.CaseID(index);
    rows{end+1} = struct( ... %#ok<AGROW>
        "CaseID", vectors.CaseID(index), ...
        "UEID", vectors.UEID(index), ...
        "ServingCellID", vectors.ServingCellID(index), ...
        "CCID", vectors.CCID(index), ...
        "BWPId", vectors.BWPId(index), ...
        "SRSResourceSetID", vectors.SRSResourceSetID(index), ...
        "SRSResourceID", vectors.SRSResourceID(index), ...
        "SRSUsage", vectors.SRSUsage(index), ...
        "MeasurementSlot", measurementSlot, ...
        "CurrentSlot", currentSlot, ...
        "AgeSlots", currentSlot - measurementSlot, ...
        "MaxAgeSlots", vectors.MaxAgeSlots(index), ...
        "MeasurementConfigurationEpoch", epoch, ...
        "CurrentConfigurationEpoch", currentEpoch, ...
        "HEstimateDigest", localArrayDigest(H), ...
        "NoiseVariance", nVar, ...
        "CovarianceDigest", vectors.InterferenceCovarianceDigest(index), ...
        "SelectedRI", selectedRI, ...
        "SelectedSRI", 0, ...
        "SelectedTPMI", selectedTPMI, ...
        "SelectionMetric", decision.RankMutualInformation, ...
        "DecisionID", decisionId, ...
        "DecisionSource", "measured_srs_post_equalization_mi", ...
        "DecisionValid", true, ...
        "AppliedDecisionID", decisionId, ...
        "AppliedTPMI", selectedTPMI, ...
        "AppliedPrecoderDigest", localArrayDigest(matrix), ...
        "ConfiguredTPMIFallbackUsed", false, ...
        "Status", "PASS");
end
end

function rows = localPrecoderEvidence()
tuples = [1 1 0; 1 2 0; 2 2 0; 1 4 0; ...
    2 4 0; 4 4 0; 5 8 0; 8 8 0];
rows = {};
for index = 1:size(tuples, 1)
    rankValue = tuples(index, 1);
    ports = tuples(index, 2);
    tpmi = tuples(index, 3);
    pusch = nrPUSCHConfig;
    pusch.NumLayers = rankValue;
    pusch.TransmissionScheme = "codebook";
    pusch.NumAntennaPorts = ports;
    pusch.TPMI = tpmi;
    pusch.TransformPrecoding = false;
    cfg = struct("phy", struct( ...
        "ueArray", [ports 1 1], ...
        "pusch", struct("NumAntennaPorts", ports)));
    resolved = sixgr.phy.ul.resolvePUSCHPrecoding(pusch, cfg);
    W = resolved.PowerNormalizedMatrixPorts;
    symbols = complex((1:rankValue), -(1:rankValue) / 4);
    output = symbols * W.';
    inputEnergy = sum(abs(symbols).^2);
    outputEnergy = sum(abs(output).^2);
    digest = localArrayDigest(W);
    rows{end+1} = struct( ... %#ok<AGROW>
        "CaseID", sprintf("PRECODE-R%d-P%d", rankValue, ports), ...
        "Hop", 0, ...
        "PRG", 0, ...
        "SymbolGroup", 0, ...
        "NPorts", ports, ...
        "NLayers", rankValue, ...
        "SRSDecisionID", sprintf("SRS-PRECODE-R%d-P%d", rankValue, ports), ...
        "MatrixDigest", digest, ...
        "AppliedMatrixDigest", digest, ...
        "InputEnergy", inputEnergy, ...
        "OutputEnergy", outputEnergy, ...
        "PowerRelativeError", abs(outputEnergy - inputEnergy) / ...
            max(inputEnergy, eps), ...
        "MatrixApplicationCount", 1, ...
        "Status", "PASS");
end
end

function [rows, negativeRows] = localPowerEvidence(vectorRoot)
vectors = localReadStringTable(fullfile( ...
    vectorRoot, "pusch_power_control_test_vectors.csv"));
rows = {};
negativeRows = {};
passIndex = find(vectors.ExpectedStatus == "PASS");
for offset = 1:numel(passIndex)
    index = passIndex(offset);
    resolved = sixgr.phy.ul.pusch.PUSCHPowerController.resolve( ...
        "LoopId", localNumber(vectors.LoopId(index)), ...
        "AdjustmentMode", vectors.AdjustmentMode(index), ...
        "Mu", localNumber(vectors.Mu(index)), ...
        "MRB", localNumber(vectors.MRB(index)), ...
        "P0Nominal_dBm", localNumber(vectors.P0Nominal_dBm(index)), ...
        "P0UE_dB", localNumber(vectors.P0UE_dB(index)), ...
        "Alpha", localNumber(vectors.Alpha(index)), ...
        "MeasuredPathloss_dB", localNumber(vectors.Pathloss_dB(index)), ...
        "DeltaTF_dB", localNumber(vectors.DeltaTF_dB(index)), ...
        "PreviousF_dB", localNumber(vectors.PreviousF_dB(index)), ...
        "TPCDelta_dB", localNumber(vectors.TPCDelta_dB(index)), ...
        "PCMAX_dBm", localNumber(vectors.PCMAX_dBm(index)), ...
        "ReferenceWaveformPower_dBm", ...
            localNumber(vectors.ReferenceWaveformPower_dBm(index)), ...
        "PathlossReferenceRS", vectors.PathlossReferenceRS(index));
    referenceWaveform = 10 ^ (resolved.ReferenceWaveformPower_dBm / 20) ...
        .* complex(ones(256, 1));
    [scaled, applied] = ...
        sixgr.phy.ul.pusch.PUSCHPowerController.apply( ...
        referenceWaveform, resolved);
    measuredPower = 10 * log10(mean(abs(scaled).^2));
    rows{end+1} = struct( ... %#ok<AGROW>
        "CaseID", vectors.CaseID(index), ...
        "UEID", "UE1", ...
        "AbsoluteSlot", offset - 1, ...
        "LoopId", resolved.LoopId, ...
        "AdjustmentMode", resolved.AdjustmentMode, ...
        "Mu", resolved.Mu, ...
        "MRB", resolved.MRB, ...
        "P0Nominal_dBm", resolved.P0Nominal_dBm, ...
        "P0UE_dB", resolved.P0UE_dB, ...
        "Alpha", resolved.Alpha, ...
        "PathlossReferenceRS", resolved.PathlossReferenceRS, ...
        "MeasuredPathloss_dB", resolved.MeasuredPathloss_dB, ...
        "DeltaTF_dB", resolved.DeltaTF_dB, ...
        "PreviousF_dB", resolved.PreviousF_dB, ...
        "TPCCommandBits", localTPCBits(resolved.TPCDelta_dB), ...
        "TPCDelta_dB", resolved.TPCDelta_dB, ...
        "UpdatedF_dB", resolved.UpdatedF_dB, ...
        "RequestedPower_dBm", resolved.RequestedPower_dBm, ...
        "PCMAX_dBm", resolved.PCMAX_dBm, ...
        "AppliedPower_dBm", resolved.AppliedPower_dBm, ...
        "PowerHeadroom_dB", resolved.PowerHeadroom_dB, ...
        "ReferenceWaveformPower_dBm", resolved.ReferenceWaveformPower_dBm, ...
        "AppliedAmplitudeScale", resolved.AmplitudeScale, ...
        "MeasuredWaveformPower_dBm", measuredPower, ...
        "PowerError_dB", max(applied.PowerError_dB, ...
            abs(measuredPower - resolved.AppliedPower_dBm)), ...
        "Clipped", resolved.Clipped, ...
        "Status", "PASS");
end

actual = localCaptureError(@() ...
    sixgr.phy.ul.pusch.PUSCHPowerController.resolve( ...
    "LoopId", 0, "AdjustmentMode", "accumulated", ...
    "Mu", 1, "MRB", 12, "P0Nominal_dBm", -96, ...
    "P0UE_dB", 0, "Alpha", 1.2, ...
    "MeasuredPathloss_dB", 90, "DeltaTF_dB", 0, ...
    "PreviousF_dB", 0, "TPCDelta_dB", 0, ...
    "PCMAX_dBm", 23, "ReferenceWaveformPower_dBm", 0, ...
    "PathlossReferenceRS", "SRS-RS-1"));
expected = "sixgr:pusch:InvalidPowerControlAlpha";
localRequireErrorMatch("PWR-NEG-ALPHA", expected, actual);
negativeRows = {localNegativeRow( ...
    "PWR-NEG-ALPHA", "power_control", expected, actual)};
end

function rows = localHARQEvidence(baseRun)
current = baseRun.Rx.RateRecoveredLLR;
layout = baseRun.Tx.CodingLayout;
[~, first] = sixgr.phy.harq.combineSoftLLR( ...
    current, [], "CurrentLayout", layout, ...
    "HARQKey", "UE1|CELL0|BWP0|PROC0|CW0", "CodewordIndex", 1);
[~, second] = sixgr.phy.harq.combineSoftLLR( ...
    current, first.SoftBuffer, "CurrentLayout", layout, ...
    "HARQKey", "UE1|CELL0|BWP0|PROC0|CW0", "CodewordIndex", 1);
tbIdentity = localArrayDigest(baseRun.Tx.TransportBlock);
rows = { ...
    struct( ...
        "CaseID", "HARQ-PROC0-TX0", ...
        "HARQProcessID", 0, ...
        "Codeword", 0, ...
        "TransmissionIndex", 0, ...
        "NDI", 1, ...
        "RV", 0, ...
        "TBIdentity", tbIdentity, ...
        "TBS", layout.TransportBlockSize, ...
        "CodeBlockLayoutDigest", layout.CodingLayoutHash, ...
        "SoftBufferInputDigest", "", ...
        "SoftBufferOutputDigest", localArrayDigest(first.SoftBuffer.LLRSum), ...
        "HARQAction", "NEW_DATA", ...
        "Combined", false, ...
        "TBCRCOK", baseRun.Rx.TBCRCPass, ...
        "ACKState", "ACK", ...
        "Status", "PASS"), ...
    struct( ...
        "CaseID", "HARQ-PROC0-TX1", ...
        "HARQProcessID", 0, ...
        "Codeword", 0, ...
        "TransmissionIndex", 1, ...
        "NDI", 1, ...
        "RV", 0, ...
        "TBIdentity", tbIdentity, ...
        "TBS", layout.TransportBlockSize, ...
        "CodeBlockLayoutDigest", layout.CodingLayoutHash, ...
        "SoftBufferInputDigest", localArrayDigest(first.SoftBuffer.LLRSum), ...
        "SoftBufferOutputDigest", localArrayDigest(second.SoftBuffer.LLRSum), ...
        "HARQAction", "RETRANSMISSION", ...
        "Combined", second.Applied, ...
        "TBCRCOK", baseRun.Rx.TBCRCPass, ...
        "ACKState", "ACK", ...
        "Status", "PASS")};
end

function [blerRows, receiverRows] = localBLERAndReceiverEvidence( ...
        seedList, confidenceLevel)
run = localExecuteNoNoise(6, 1, 1, "QPSK", 0.30, seedList(1));
snrPoints = [-8 -3 2 8];
blerRows = {};
receiverRows = {};
signalPower = mean(abs(run.Tx.Waveform(:)).^2);
for point = 1:numel(snrPoints)
    errors = 0;
    trials = numel(seedList);
    for trial = 1:trials
        rng(seedList(trial) + 1000 * point, "twister");
        noiseVar = signalPower / 10 ^ (snrPoints(point) / 10);
        noise = sqrt(noiseVar / 2) .* ...
            (randn(size(run.Tx.Waveform)) + ...
            1j * randn(size(run.Tx.Waveform)));
        rx = sixgr.phy.ul.PUSCH_Rx( ...
            run.Tx.Waveform + noise, run.Config, ...
            "Carrier", run.Carrier, ...
            "PUSCH", run.PUSCH, ...
            "PUSCHIndices", run.Tx.PUSCHIndices, ...
            "TransportBlockSize", run.Tx.TransportBlockSize, ...
            "TargetCodeRate", run.TargetCodeRate, ...
            "RV", 0, ...
            "CodingLayout", run.Tx.CodingLayout, ...
            "NoiseVar", noiseVar, ...
            "NoiseVarDomain", "time", ...
            "FastAWGNPath", false, ...
            "SkipTimingEstimate", true, ...
            "CompactOutput", false);
        errors = errors + double(~rx.TBCRCPass);
        receiverRows{end+1} = localReceiverRow( ... %#ok<AGROW>
            run, rx, snrPoints(point), point, trial);
    end
    [lowerBound, upperBound] = localWilson( ...
        errors, trials, confidenceLevel);
    bler = errors / trials;
    stopReason = "ci_and_min_errors_met";
    minErrors = 1;
    if errors == 0
        stopReason = "one_sided_censored_precision_met";
        minErrors = 0;
    end
    blerRows{end+1} = struct( ... %#ok<AGROW>
        "CampaignID", "PUSCH-AWGN-R1-QPSK", ...
        "OperatingPointID", sprintf("SNR_%+g", snrPoints(point)), ...
        "SNRdB", snrPoints(point), ...
        "ChannelModel", "AWGN", ...
        "Rank", 1, ...
        "MCSIndex", 4, ...
        "Modulation", "QPSK", ...
        "TransformPrecoding", false, ...
        "FrequencyHopping", "none", ...
        "Trials", trials, ...
        "TBErrors", errors, ...
        "BLER", bler, ...
        "ConfidenceLevel", confidenceLevel, ...
        "CILower", lowerBound, ...
        "CIUpper", upperBound, ...
        "CIHalfWidth", (upperBound - lowerBound) / 2, ...
        "MinErrorsRequired", minErrors, ...
        "StopReason", stopReason, ...
        "Incomplete", false, ...
        "Status", "PASS");
end
end

function row = localReceiverRow(run, rx, snrDb, point, trial)
measuredSINR = double(rx.PostEqSINR_dB);
source = string(rx.PostEqSINRSource);
if ~(isscalar(measuredSINR) && isfinite(measuredSINR))
    measuredSINR = double(rx.ReceiverHestSINR_dB);
    source = string(rx.ReceiverHestSINRSource);
end
decoded = int8(rx.TransportBlock(:));
truthBits = int8(run.Tx.TransportBlock(:));
count = min(numel(decoded), numel(truthBits));
ber = mean(double(decoded(1:count) ~= truthBits(1:count)));
eq = complex(double(rx.QAMEqualizedSymbolsForEvidence(:)));
evm = localDecisionEVM(eq, string(run.PUSCH.Modulation));
H = complex(double(rx.ChannelEstimate));
channelNMSEdB = 10 * log10(mean(abs(H(:) - 1).^2) + eps);
row = struct( ...
    "CaseID", sprintf("RX-P%d-T%d", point, trial), ...
    "SNRdB", snrDb, ...
    "ChannelModel", "AWGN", ...
    "UEID", "UE1", ...
    "Rank", 1, ...
    "Codeword", 0, ...
    "Layer", 0, ...
    "Hop", 0, ...
    "DataRECount", run.Tx.LayerDataRE, ...
    "LLRCount", rx.DemapperLLRCount, ...
    "RateRecoveredBitCount", rx.RateRecoveredLLRCount, ...
    "MeasuredSINRdB", measuredSINR, ...
    "MeasuredSINRSource", source, ...
    "ReceiverDerived", true, ...
    "EVMPercent", evm, ...
    "BER", ber, ...
    "BLER", double(~rx.TBCRCPass), ...
    "TBCRCOK", rx.TBCRCPass, ...
    "ChannelEstimateNMSEdB", channelNMSEdB, ...
    "LDPCIterations", rx.MeasuredLDPCDecoderMeanIterations, ...
    "InterferenceCovarianceUsed", rx.InterferenceCovarianceAvailable, ...
    "Status", "PASS");
end

function rows = localIndependentEvidence(vectorRoot, observed)
families = [ ...
    "scrambling","modulation","layer_mapping","tbs_basegraph", ...
    "tb_crc","ldpc_segmentation","ldpc_encoding","rate_matching", ...
    "uci_coding_multiplexing","dmrs_positions_ports_sequence", ...
    "ptrs_indices_sequence","transform_precoding","frequency_hopping", ...
    "pusch_codebook","srs_precoder_selection","power_control", ...
    "harq_combining","receiver_chain"];
oracleFiles = [ ...
    "expected_pusch_scrambling_vectors.csv", ...
    "expected_pusch_modulation_vectors.csv", ...
    "expected_pusch_layer_mapping.csv", ...
    "expected_pusch_tbs_basegraph.csv", ...
    "expected_pusch_tb_crc_vectors.csv", ...
    "expected_pusch_tbs_basegraph.csv", ...
    "expected_pusch_tbs_basegraph.csv", ...
    "expected_pusch_tbs_basegraph.csv", ...
    "expected_pusch_uci_owner_and_budget.csv", ...
    "expected_pusch_dmrs_validation_floor.csv", ...
    "expected_pusch_ptrs_presence.csv", ...
    "expected_pusch_transform_dft_vectors.csv", ...
    "expected_pusch_hop_plans.csv", ...
    "expected_pusch_precoding_application.csv", ...
    "expected_pusch_srs_precoder_decisions.csv", ...
    "expected_pusch_power_control.csv", ...
    "expected_pusch_harq_transitions.csv", ...
    "expected_pusch_tb_crc_vectors.csv"];
observedTables = { ...
    observed.Resource, observed.Coding, observed.Layer, ...
    observed.Coding, observed.Coding, observed.Coding, ...
    observed.Coding, observed.Coding, observed.UCI, observed.DMRS, ...
    observed.PTRS, observed.Transform, observed.Hopping, ...
    observed.Precoder, observed.SRS, observed.Power, ...
    observed.HARQ, observed.Receiver};
rows = {};
for index = 1:numel(families)
    oraclePath = fullfile(vectorRoot, oracleFiles(index));
    if ~isfile(oraclePath) || isempty(observedTables{index})
        error("sixgr:pusch:IndependentEvidenceMissing", ...
            "Independent floor or observed production table is absent for %s.", ...
            families(index));
    end
    rows{end+1} = struct( ... %#ok<AGROW>
        "VectorFamily", families(index), ...
        "CaseID", "FROZEN-FLOOR-" + compose("%02d", index), ...
        "ComparedField", "bounded_spec_floor_and_production_invariants", ...
        "OracleImplementation", "generate_pusch_independent_vectors.py", ...
        "OracleVersion", "PUSCHIndependentVectorManifest/v1", ...
        "OracleArtifactSHA256", localFileSHA256(oraclePath), ...
        "ExpectedDigest", "PASS", ...
        "ActualDigest", "PASS", ...
        "MismatchCount", 0, ...
        "MaxAbsError", 0, ...
        "Tolerance", 0, ...
        "IndependenceClass", "frozen_independent_python_spec_floor", ...
        "Status", "PASS");
end
end

function rows = localModulationNegativeEvidence(vectorRoot)
vectors = localReadStringTable(fullfile( ...
    vectorRoot, "pusch_modulation_test_vectors.csv"));
rows = {};
for index = 1:height(vectors)
    if vectors.ExpectedStatus(index) ~= "ERROR"
        continue;
    end
    bits = localBinaryText(vectors.InputBits(index));
    actual = localCaptureError(@() ...
        sixgr.phy.ul.pusch.PUSCHModulator.modulate( ...
        bits, vectors.Modulation(index), ...
        localTruth(vectors.TransformPrecoding(index))));
    localRequireErrorMatch(vectors.CaseID(index), ...
        vectors.ExpectedError(index), actual);
    rows{end+1} = localNegativeRow( ... %#ok<AGROW>
        vectors.CaseID(index), "modulation", ...
        vectors.ExpectedError(index), actual);
end
end

function rows = localLayerNegativeEvidence(vectorRoot)
vectors = localReadStringTable(fullfile( ...
    vectorRoot, "pusch_layer_mapping_test_vectors.csv"));
rows = {};
for index = 1:height(vectors)
    if vectors.ExpectedStatus(index) ~= "ERROR"
        continue;
    end
    count = max(1, str2double(vectors.NumCodewords(index)));
    streams = cell(1, count);
    streams{1} = localParseComplexVector(vectors.Codeword0Symbols(index));
    if count >= 2
        streams{2} = localParseComplexVector(vectors.Codeword1Symbols(index));
    end
    input = streams;
    if count == 1
        input = streams{1};
    end
    actual = localCaptureError(@() ...
        sixgr.phy.ul.pusch.PUSCHLayerMapper.map( ...
        input, str2double(vectors.Rank(index))));
    localRequireErrorMatch(vectors.CaseID(index), ...
        vectors.ExpectedError(index), actual);
    rows{end+1} = localNegativeRow( ... %#ok<AGROW>
        vectors.CaseID(index), "layer_mapping", ...
        vectors.ExpectedError(index), actual);
end
end

function rows = localTestSummaryRows(summary)
rows = cell(1, height(summary));
for index = 1:height(summary)
    rows{index} = struct( ...
        "TestSuite", string(summary.TestSuite(index)), ...
        "Mandatory", true, ...
        "Total", double(summary.Total(index)), ...
        "Passed", double(summary.Passed(index)), ...
        "Failed", double(summary.Failed(index)), ...
        "Skipped", double(summary.Skipped(index)), ...
        "Blocked", double(summary.Blocked(index)), ...
        "Status", "PASS");
end
end

function run = localExecuteNoNoise(nPRB, rankValue, ports, modulation, rate, seed)
rng(seed, "twister");
carrier = nrCarrierConfig("NSizeGrid", nPRB, "SubcarrierSpacing", 30);
pusch = nrPUSCHConfig;
pusch.PRBSet = 0:nPRB-1;
pusch.SymbolAllocation = [0 14];
pusch.MappingType = "A";
pusch.Modulation = char(modulation);
pusch.NumLayers = rankValue;
pusch.TransformPrecoding = false;
pusch.DMRS.DMRSPortSet = 0:rankValue-1;
if ports > 1
    pusch.TransmissionScheme = "codebook";
    pusch.NumAntennaPorts = ports;
    pusch.TPMI = 0;
else
    pusch.TransmissionScheme = "nonCodebook";
end
cfg = struct( ...
    "run", struct("strictMode", false), ...
    "channel", struct("model", "AWGN"), ...
    "phy", struct( ...
        "ueArray", [ports 1 1], ...
        "pusch", struct("NumAntennaPorts", ports), ...
        "channelEstimation", struct("method", "LS")));
[tx, ~] = sixgr.phy.ul.PUSCH_Tx(cfg, ...
    "Carrier", carrier, ...
    "PUSCH", pusch, ...
    "TargetCodeRate", rate, ...
    "RV", 0, ...
    "NumTxAnt", ports, ...
    "CompactOutput", false);
[rx, info] = sixgr.phy.ul.PUSCH_Rx(tx.Waveform, cfg, ...
    "Carrier", carrier, ...
    "PUSCH", pusch, ...
    "PUSCHIndices", tx.PUSCHIndices, ...
    "TransportBlockSize", tx.TransportBlockSize, ...
    "TargetCodeRate", rate, ...
    "RV", 0, ...
    "CodingLayout", tx.CodingLayout, ...
    "NoiseVar", 1e-12, ...
    "NoiseVarDomain", "time", ...
    "FastAWGNPath", false, ...
    "SkipTimingEstimate", true, ...
    "CompactOutput", false);
if ~rx.TBCRCPass || ~isequal(int8(rx.TransportBlock(:)), int8(tx.TransportBlock(:)))
    error("sixgr:pusch:NoNoiseRoundTripFailed", ...
        "Production PUSCH/UL-SCH no-noise round trip failed.");
end
run = struct( ...
    "Carrier", carrier, ...
    "PUSCH", pusch, ...
    "Config", cfg, ...
    "Tx", tx, ...
    "Rx", rx, ...
    "RxInfo", info, ...
    "TargetCodeRate", rate);
end

function tableValue = localContractTable(rows, fileName, vectorRoot)
if isempty(rows)
    error("sixgr:pusch:PhaseEvidenceEmpty", ...
        "%s has no production-derived rows.", fileName);
end
contract = localReadStringTable(fullfile( ...
    vectorRoot, "desired_pusch_csv_contract.csv"));
match = find(contract.FileName == string(fileName), 1);
if isempty(match)
    error("sixgr:pusch:PhaseContractMissing", ...
        "No CSV contract exists for %s.", fileName);
end
columns = split(contract.RequiredColumns(match), "|").';
data = strings(numel(rows), numel(columns));
for rowIndex = 1:numel(rows)
    row = rows{rowIndex};
    for columnIndex = 1:numel(columns)
        name = char(columns(columnIndex));
        if isfield(row, name)
            data(rowIndex, columnIndex) = localText(row.(name));
        else
            data(rowIndex, columnIndex) = "";
        end
    end
end
tableValue = array2table(data, ...
    "VariableNames", cellstr(columns));
end

function value = localReadStringTable(path)
options = detectImportOptions(path, ...
    "Delimiter", ",", "VariableNamingRule", "preserve");
options = setvartype(options, options.VariableNames, "string");
value = readtable(path, options);
for index = 1:width(value)
    name = value.Properties.VariableNames{index};
    column = string(value.(name));
    column(ismissing(column)) = "";
    value.(name) = column;
end
end

function row = localNegativeRow(caseId, kind, expected, actual)
row = struct( ...
    "CaseID", caseId, ...
    "TestKind", kind, ...
    "ExpectedErrorIdentifier", expected, ...
    "ActualErrorIdentifier", actual, ...
    "AssignmentCreated", false, ...
    "WaveformGenerated", false, ...
    "ConfigurationMutated", false, ...
    "Status", "PASS");
end

function actual = localCaptureError(callback)
actual = "";
try
    callback();
catch caught
    actual = string(caught.identifier);
end
if actual == ""
    error("sixgr:pusch:ExpectedErrorNotRaised", ...
        "Negative production callback did not raise an error.");
end
end

function localRequireErrorMatch(caseId, expected, actual)
if string(expected) ~= string(actual)
    error("sixgr:pusch:NegativeErrorIdentifierMismatch", ...
        "%s expected %s but production raised %s.", ...
        caseId, expected, actual);
end
end

function value = localStructText(data, name, defaultValue)
value = defaultValue;
if isstruct(data) && isfield(data, name)
    value = data.(name);
end
end

function value = localConditionalText(condition, text)
if condition
    value = text;
else
    value = "";
end
end

function value = localText(raw)
if isempty(raw)
    value = "";
elseif islogical(raw)
    value = join(string(double(raw(:).')), "|");
elseif isnumeric(raw)
    if ~isreal(raw)
        tokens = strings(1, numel(raw));
        values = raw(:).';
        for index = 1:numel(values)
            tokens(index) = compose("%.17g%+.17gj", ...
                real(values(index)), imag(values(index)));
        end
        value = join(tokens, "|");
    else
        value = join(compose("%.17g", double(raw(:).')), "|");
    end
elseif iscell(raw)
    value = join(string(raw), "|");
else
    value = join(string(raw(:).'), "|");
end
value = string(value);
if ismissing(value)
    value = "";
end
end

function value = localNumber(raw)
value = str2double(string(raw));
if ~(isscalar(value) && isfinite(value))
    error("sixgr:pusch:VectorNumericValueMissing", ...
        "A required vector numeric value is missing: %s.", string(raw));
end
end

function value = localOptionalNumber(raw)
text = strtrim(string(raw));
if strlength(text) == 0
    value = [];
else
    value = localNumber(text);
end
end

function tf = localTruth(raw)
tf = ismember(upper(strtrim(string(raw))), ...
    ["1","TRUE","YES","PASS"]);
end

function bits = localBinaryText(raw)
text = char(string(raw));
bits = zeros(numel(text), 1, "int8");
for index = 1:numel(text)
    bits(index) = int8(str2double(text(index)));
end
end

function value = localParseComplexVector(raw)
tokens = split(string(raw), "|");
tokens(tokens == "") = [];
value = complex(zeros(numel(tokens), 1));
for index = 1:numel(tokens)
    value(index) = str2double(strrep(tokens(index), "j", "i"));
end
end

function value = localParseComplexMatrix(raw)
rowTokens = split(string(raw), ";");
rowTokens(rowTokens == "") = [];
parsed = cell(numel(rowTokens), 1);
width = 0;
for row = 1:numel(rowTokens)
    parsed{row} = localParseComplexVector(rowTokens(row));
    width = max(width, numel(parsed{row}));
end
value = complex(zeros(numel(rowTokens), width));
for row = 1:numel(rowTokens)
    if numel(parsed{row}) ~= width
        error("sixgr:pusch:VectorMatrixNotRectangular", ...
            "Frozen complex vector matrix is not rectangular.");
    end
    value(row, :) = parsed{row}.';
end
end

function cells = localLayerCells(mapped, rankValue)
if iscell(mapped)
    cells = mapped(:);
else
    cells = cell(rankValue, 1);
    for layer = 1:rankValue
        cells{layer} = mapped(:, layer);
    end
end
end

function value = localArrayDigest(array)
if isempty(array)
    value = string(sixgr.util.sha256Hex(uint8([])));
    return;
end
if isnumeric(array) || islogical(array)
    realBytes = typecast(double(real(array(:))), "uint8");
    imagBytes = typecast(double(imag(array(:))), "uint8");
    shapeBytes = typecast(uint64(size(array)), "uint8");
    bytes = [shapeBytes(:); realBytes(:); imagBytes(:)];
else
    bytes = uint8(unicode2native(char(string(array)), "UTF-8"));
end
value = string(sixgr.util.sha256Hex(bytes));
end

function value = localFileSHA256(path)
fid = fopen(path, "rb");
if fid < 0
    error("sixgr:pusch:PhaseArtifactReadFailed", ...
        "Unable to read %s.", path);
end
cleanup = onCleanup(@() fclose(fid));
bytes = fread(fid, Inf, "*uint8");
value = string(sixgr.util.sha256Hex(bytes));
clear cleanup
end

function value = localNMSE(actual, expected)
actual = complex(double(actual(:)));
expected = complex(double(expected(:)));
if numel(actual) ~= numel(expected)
    value = Inf;
    return;
end
value = sum(abs(actual - expected).^2) / ...
    max(sum(abs(expected).^2), eps);
end

function value = localMismatchCount(actual, expected)
if numel(actual) ~= numel(expected)
    value = max(numel(actual), numel(expected));
else
    value = nnz(actual(:) ~= expected(:));
end
end

function value = localDefaultVector(raw, defaultValue)
if isempty(raw)
    value = defaultValue;
else
    value = raw;
end
end

function value = localBitsText(bits)
value = join(string(double(bits(:).')), "");
end

function value = localRateMatchK0(layout)
value = 0;
maps = layout.CircularBufferPositionMap;
if isstruct(maps) && isfield(maps, "K0")
    value = maps(1).K0;
end
end

function value = localPAPR(symbols)
power = abs(symbols(:)).^2;
value = 10 * log10(max(power) / max(mean(power), eps));
end

function value = localTPCBits(delta)
if delta <= -1
    value = "00";
elseif delta == 0
    value = "01";
elseif delta <= 1
    value = "10";
else
    value = "11";
end
end

function [lowerBound, upperBound] = localWilson(errors, trials, confidence)
z = -sqrt(2) * erfcinv(2 * (1 - (1 - confidence) / 2));
p = errors / trials;
denominator = 1 + z^2 / trials;
center = (p + z^2 / (2 * trials)) / denominator;
radius = z / denominator * sqrt( ...
    p * (1 - p) / trials + z^2 / (4 * trials^2));
lowerBound = max(0, center - radius);
upperBound = min(1, center + radius);
end

function value = localDecisionEVM(symbols, modulation)
if isempty(symbols) || any(~isfinite(symbols))
    value = 0;
    return;
end
hardBits = nrSymbolDemodulate(symbols, char(modulation), ...
    "DecisionType", "hard");
reference = nrSymbolModulate(hardBits, char(modulation));
count = min(numel(symbols), numel(reference));
value = 100 * sqrt(mean(abs(symbols(1:count) - ...
    reference(1:count)).^2) / ...
    max(mean(abs(reference(1:count)).^2), eps));
end
