function policy=resolveShortUCIDecisionPolicy(policy)
% Explicit receiver policy. Only standalone component calls use catalog defaults.
% Production PUSCH_Rx must pass its resolved cfg.phy.pusch.shortUCIDecision.
if nargin==0
    catalog=sixgr.config.loadCoreCatalog();
    entry=catalog.parameters.phy.pusch.shortUCIDecision;
    policy=struct('algorithm',string(entry.algorithm.default), ...
        'minimumPosterior',entry.minimumPosterior.default, ...
        'Source',"core_catalog_component_default");
end
id='sixgr:pusch:InvalidShortUCIDecisionPolicy';
assert(isstruct(policy) && isscalar(policy) && ...
    all(isfield(policy,{'algorithm','minimumPosterior'})) && ...
    all(ismember(fieldnames(policy),{'algorithm','minimumPosterior','Source'})), ...
    id,'phy.pusch.shortUCIDecision requires only algorithm and minimumPosterior (plus optional Source).');
assert((ischar(policy.algorithm) && isrow(policy.algorithm)) || ...
    (isstring(policy.algorithm) && isscalar(policy.algorithm)),id, ...
    'phy.pusch.shortUCIDecision.algorithm must be codeword_posterior.');
assert(string(policy.algorithm)=="codeword_posterior",id, ...
    'phy.pusch.shortUCIDecision.algorithm must be codeword_posterior.');
p=policy.minimumPosterior;
assert(isnumeric(p) && isreal(p) && isscalar(p) && isfinite(p) && p>0.5 && p<1, ...
    id,'phy.pusch.shortUCIDecision.minimumPosterior must be finite and strictly between 0.5 and 1.');
if ~isfield(policy,'Source'), policy.Source="explicit_receiver_policy"; end
assert(isstring(policy.Source) && isscalar(policy.Source) && ...
    ismember(policy.Source,["explicit_receiver_policy","core_catalog_component_default"]), ...
    id,'Short-UCI policy Source must identify explicit configuration or standalone catalog defaults.');
policy.algorithm=string(policy.algorithm);
policy.minimumPosterior=double(p);
end
