function decode = DLSCHDecoder(arg1, varargin)
%DLSCHDECODER Execute DL-SCH decoding from an immutable coding plan.
%   DLSCHDecoder(llr,"CodingPlan",plan,...) inverts the immutable plan:
%   rate recovery, optional position-aware HARQ combining, LDPC decoding,
%   code-block desegmentation/CRC, and transport-block CRC.

[codingPlan, remaining, explicit] = localExtractCodingPlan(varargin);
if ~explicit
    error("sixgr:pdsch:DLSCHDecoder:MissingCodingPlan", ...
        "DL-SCH decoding requires an immutable DLSCHCodingPlan; metadata RX summaries and inferred coding defaults are forbidden.");
end
decode = localDecodeExplicit(arg1, codingPlan, remaining{:});
end

function decode = localDecodeExplicit(llr, plans, varargin)
ip = inputParser;
ip.FunctionName = "sixgr.pdsch.DLSCHDecoder explicit path";
ip.addParameter("MaxIterations", 12, ...
    @(x) isnumeric(x) && isscalar(x) && isfinite(x) && x >= 1);
ip.addParameter("Algorithm", "Normalized min-sum", ...
    @(x) ischar(x) || isstring(x));
ip.addParameter("PriorRecoveredLLR", [], ...
    @(x) isempty(x) || isnumeric(x) || islogical(x) || isstruct(x) || iscell(x));
ip.addParameter("PriorCodingPlan", [], ...
    @(x) isempty(x) || isstruct(x) || iscell(x) || ...
    isa(x, "sixgr.pdsch.DLSCHCodingPlan"));
ip.addParameter("HARQKey", "", @(x) ischar(x) || isstring(x));
ip.parse(varargin{:});
opt = ip.Results;

[llrCells, planCells] = localNormalizeCodewords(llr, plans);
codewords = cell(1, numel(planCells));
for cw = 1:numel(planCells)
    prior = localSelectCodeword(opt.PriorRecoveredLLR, cw);
    priorLayout = localResolvePriorLayout(opt.PriorCodingPlan, cw);
    codewords{cw} = localDecodeCodeword(llrCells{cw}, planCells{cw}, ...
        round(double(opt.MaxIterations)), char(string(opt.Algorithm)), ...
        prior, priorLayout, char(string(opt.HARQKey)));
end
if isscalar(codewords)
    decode = codewords{1};
    return;
end
tbCells = cellfun(@(x) x.TransportBlock, codewords, "UniformOutput", false);
crcPass = cellfun(@(x) x.CRCPass, codewords);
active = cellfun(@(x) x.ActiveIterations, codewords, "UniformOutput", false);
decode = struct( ...
    "ContractVersion", "ExplicitDLSCHDecode/v1", ...
    "NumCodewords", uint8(numel(codewords)), ...
    "Codewords", {codewords}, ...
    "CodingPlanIDs", string(cellfun(@(x) x.CodingPlanID, ...
        codewords, "UniformOutput", false)), ...
    "TransportBlock", vertcat(tbCells{:}), ...
    "TransportBlocks", {tbCells}, ...
    "CRCPass", all(crcPass), ...
    "CRCError", any(~crcPass), ...
    "CRCPassPerCodeword", logical(crcPass), ...
    "CRCErrorPerCodeword", logical(~crcPass), ...
    "ActiveIterations", [active{:}], ...
    "Source", "explicit_dlsch_primitives_truth");
end

function out = localDecodeCodeword(llr, plan, maxIterations, algorithm, ...
        prior, priorLayout, harqKey)
llr = localValidateLLR(llr, plan);
layout = plan.toCodingLayout();
if isempty(plan.Nref)
    [recovered, recoveryInfo] = sixgr.phy.phycode.rateRecoverLDPC( ...
        llr, double(plan.TransportBlockSize), plan.TargetCodeRate, ...
        double(plan.RV), plan.Modulation, double(plan.NumLayers), ...
        double(plan.NumCodeBlocks), [], "CodingLayout", layout);
else
    [recovered, recoveryInfo] = sixgr.phy.phycode.rateRecoverLDPC( ...
        llr, double(plan.TransportBlockSize), plan.TargetCodeRate, ...
        double(plan.RV), plan.Modulation, double(plan.NumLayers), ...
        double(plan.NumCodeBlocks), double(plan.Nref), ...
        "CodingLayout", layout);
end

if isempty(prior)
    combined = recovered;
    [~, harqInfo] = sixgr.phy.harq.combineSoftLLR( ...
        recovered, [], "CurrentLayout", layout, ...
        "HARQKey", harqKey, ...
        "CodewordIndex", double(plan.CodewordIndex) + 1);
else
    if isempty(priorLayout) && ~(isstruct(prior) && ...
            (isfield(prior, "CodingLayout") || isfield(prior, "SoftBuffer")))
        error("sixgr:pdsch:DLSCHDecoder:MissingPriorCodingPlan", ...
            ["PriorRecoveredLLR requires PriorCodingPlan unless the prior " ...
            "decoder result carries its CodingLayout or SoftBuffer."]);
    end
    [combined, harqInfo] = sixgr.phy.harq.combineSoftLLR( ...
        recovered, prior, "CurrentLayout", layout, ...
        "PriorLayout", priorLayout, "HARQKey", harqKey, ...
        "CodewordIndex", double(plan.CodewordIndex) + 1);
end

[decodedCodeBlocks, activeIterations, finalParityChecks] = ...
    sixgr.phy.phycode.ldpcDecode(combined, double(plan.BaseGraph), ...
    maxIterations, algorithm);
if size(decodedCodeBlocks, 1) ~= double(plan.CodeBlockLength) || ...
        size(decodedCodeBlocks, 2) ~= double(plan.NumCodeBlocks)
    error("sixgr:pdsch:DLSCHDecoder:PlanMismatch", ...
        "LDPC decoder output shape does not match the immutable coding plan.");
end
[tbCRCBlock, cbCRCError] = sixgr.phy.tb.desegmentLDPC( ...
    decodedCodeBlocks, layout);
[transportBlock, tbCRCPass, tbCRCError] = sixgr.phy.tb.checkCRC( ...
    tbCRCBlock, plan.TBCRCType);
if numel(transportBlock) ~= double(plan.TransportBlockSize)
    error("sixgr:pdsch:DLSCHDecoder:PlanMismatch", ...
        "Decoded transport block length does not match plan A.");
end
cbCRCError = logical(double(cbCRCError(:)) ~= 0);
if double(plan.NumCodeBlocks) == 1
    cbCRCError = false;
end

out = struct( ...
    "ContractVersion", "ExplicitDLSCHDecodeCodeword/v1", ...
    "CodewordIndex", plan.CodewordIndex, ...
    "CodingPlan", plan.toStruct(), ...
    "CodingPlanID", plan.PlanID, ...
    "CodingLayout", layout, ...
    "InputRateMatchedLLR", double(llr(:)), ...
    "RateRecoveredLLR", double(recovered), ...
    "RateRecoveryInfo", recoveryInfo, ...
    "HARQCombinedLLR", double(combined), ...
    "HARQCombineInfo", harqInfo, ...
    "SoftBuffer", sixgr.util.structGet(harqInfo, "SoftBuffer", struct()), ...
    "DecodedCodeBlocks", int8(decodedCodeBlocks), ...
    "ActiveIterations", double(activeIterations), ...
    "FinalParityChecks", finalParityChecks, ...
    "DesegmentedTransportBlockWithCRC", int8(tbCRCBlock(:)), ...
    "CodeBlockCRCError", cbCRCError, ...
    "CodeBlockCRCPass", ~cbCRCError, ...
    "TransportBlock", int8(transportBlock(:)), ...
    "TransportBlocks", {{int8(transportBlock(:))}}, ...
    "CRCPass", logical(tbCRCPass), ...
    "CRCError", logical(tbCRCError), ...
    "CRCPassPerCodeword", logical(tbCRCPass), ...
    "CRCErrorPerCodeword", logical(tbCRCError), ...
    "DecodeLatency_s", NaN, ...
    "DecoderIterations", double(mean(activeIterations, "omitnan")), ...
    "Source", "explicit_dlsch_primitives_truth");
end

function llr = localValidateLLR(llr, plan)
if ~(isnumeric(llr) || islogical(llr)) || ~isvector(llr) || isempty(llr)
    error("sixgr:pdsch:DLSCHDecoder:BadLLR", ...
        "Each codeword LLR input must be a non-empty real numeric vector.");
end
llr = double(llr(:));
if ~isreal(llr) || any(isnan(llr))
    error("sixgr:pdsch:DLSCHDecoder:BadLLR", ...
        "Rate-matched LLR values must be real and cannot contain NaN.");
end
if numel(llr) ~= double(plan.RateMatchedBitCount)
    error("sixgr:pdsch:DLSCHDecoder:RateMatchedBitCountMismatch", ...
        "Received %d LLRs; coding plan requires G=%d.", ...
        numel(llr), double(plan.RateMatchedBitCount));
end
end

function [plan, remaining, explicit] = localExtractCodingPlan(args)
plan = [];
remaining = args;
explicit = false;
if isempty(args)
    return;
end
if localIsPlanCollection(args{1})
    plan = args{1};
    remaining = args(2:end);
    explicit = true;
    return;
end
for i = 1:2:(numel(args) - 1)
    if (ischar(args{i}) || isstring(args{i})) && ...
            strcmpi(string(args{i}), "CodingPlan")
        plan = args{i + 1};
        if ~localIsPlanCollection(plan)
            error("sixgr:pdsch:DLSCHDecoder:BadCodingPlan", ...
                "CodingPlan must be a DLSCHCodingPlan or a cell of plans.");
        end
        remaining(i:(i + 1)) = [];
        explicit = true;
        return;
    end
end
end

function tf = localIsPlanCollection(value)
tf = isa(value, "sixgr.pdsch.DLSCHCodingPlan");
if iscell(value)
    tf = ~isempty(value) && all(cellfun( ...
        @(x) isa(x, "sixgr.pdsch.DLSCHCodingPlan"), value(:)));
end
end

function [llr, plans] = localNormalizeCodewords(llr, plans)
if ~iscell(plans)
    plans = {plans};
else
    plans = reshape(plans, 1, []);
end
if ~iscell(llr)
    if numel(plans) ~= 1
        error("sixgr:pdsch:DLSCHDecoder:CodewordCountMismatch", ...
            "Two coding plans require a cell containing two LLR vectors.");
    end
    llr = {llr};
else
    llr = reshape(llr, 1, []);
end
if numel(llr) ~= numel(plans) || ~ismember(numel(plans), [1 2])
    error("sixgr:pdsch:DLSCHDecoder:CodewordCountMismatch", ...
        "DL-SCH decoding requires one or two equally counted LLRs and plans.");
end
indices = cellfun(@(x) double(x.CodewordIndex), plans);
if ~isequal(indices, 0:(numel(plans) - 1))
    error("sixgr:pdsch:DLSCHDecoder:CodewordIndexMismatch", ...
        "Coding plans must be ordered with zero-based indices 0..N-1.");
end
end

function value = localSelectCodeword(value, cw)
if iscell(value)
    if numel(value) >= cw
        value = value{cw};
    else
        value = [];
    end
end
end

function layout = localResolvePriorLayout(value, cw)
value = localSelectCodeword(value, cw);
if isa(value, "sixgr.pdsch.DLSCHCodingPlan")
    layout = value.toCodingLayout();
elseif isstruct(value)
    layout = value;
else
    layout = [];
end
end
