function rx = PDSCHReceiver(rxWaveform, assignment, resourcePlan, varargin)
%PDSCHRECEIVER Execute the canonical assignment-owned PDSCH receiver.
%   RX = PDSCHReceiver(WAVEFORM,ASSIGNMENT,RESOURCEPLAN,CARRIER, ...
%       REFERENCECONFIG,RECEIVERCONFIG,Name,Value,...)
% Configuration structs, TX copies, transmitted bits, CRC outcomes, and
% transmitter intermediates are not accepted at this RX trust boundary.
rx = localStrictReceiver(rxWaveform, assignment, resourcePlan, varargin{:});
end

function rx = localStrictReceiver(rxWaveform, assignment, resourcePlan, varargin)
if ~isa(resourcePlan, "sixgr.pdsch.PDSCHResourcePlan")
    error("sixgr:pdsch:PDSCHReceiver:MissingResourcePlan", ...
        "Strict PDSCH RX requires an immutable PDSCHResourcePlan.");
end
assignment.validateForExecution();
if any(assignment.Profile == ["connected_strict","ra_si_strict","scheduler_truth"]) && ...
        string(assignment.get("ControlAuthority")) ~= "receiver_crc_valid_decode"
    error("sixgr:pdsch:PDSCHReceiver:TransmitterAssignmentAtReceiver", ...
        "A transmitter-scheduled assignment cannot authorize PDSCH reception. " + ...
        "Construct a receiver-owned assignment from an actual CRC-valid DCI decode.");
end
if numel(varargin) < 3
    error("sixgr:pdsch:PDSCHReceiver:IncompleteStrictSignature", ...
        "Strict PDSCH RX requires carrier, referenceConfig, and " + ...
        "receiverConfig after the resource plan.");
end
carrier = varargin{1};
referenceConfig = varargin{2};
receiverConfig = varargin{3};
nv = varargin(4:end);
if ~isa(carrier, "nrCarrierConfig")
    error("sixgr:pdsch:PDSCHReceiver:InvalidCarrier", ...
        "Strict PDSCH RX requires an explicit nrCarrierConfig.");
end
localRXValidateCarrierSymbolBoundary(assignment, carrier);
if ~isa(referenceConfig, ...
        "sixgr.pdsch.PDSCHReferenceSignalConfig")
    error("sixgr:pdsch:PDSCHReceiver:MissingImmutableReferenceConfiguration", ...
        "Strict PDSCH RX requires PDSCHReferenceSignalConfig.");
end
referenceConfig.validateForExecution();
referenceData = referenceConfig.toStruct();
referenceSignals = sixgr.pdsch.PDSCHReferenceSignalGenerator.generate( ...
    assignment,resourcePlan,carrier,referenceConfig);
referenceRuntime = referenceData;
referenceRuntime.DMRSSymbolsPerPort = ...
    referenceSignals.DMRSSymbolsPerPort;
referenceRuntime.PTRSSymbolsPerPort = ...
    referenceSignals.PTRSSymbolsPerPort;
referenceRuntime.DMRSCDMLengths = double( ...
    referenceSignals.MaterializedPDSCH.DMRS.CDMLengths);

ip = inputParser;
ip.FunctionName = "sixgr.pdsch.PDSCHReceiver strict path";
ip.addParameter("CodingPlans", [], ...
    @(x) isempty(x) || isa(x, "sixgr.pdsch.DLSCHCodingPlan") ...
        || iscell(x));
ip.addParameter("PrecoderBundle", [], ...
    @(x) isempty(x) || isa(x, "sixgr.pdsch.PDSCHPrecoderBundle"));
ip.addParameter("IntegrationContext", struct(), ...
    @(x) isstruct(x) && isscalar(x));
ip.addParameter("HARQManager", [], ...
    @(x) isempty(x) || isa(x, "sixgr.pdsch.PDSCHHARQManager"));
ip.addParameter("PriorRecoveredLLR", [], ...
    @(x) isempty(x) || isnumeric(x) || islogical(x) || ...
        isstruct(x) || iscell(x));
ip.addParameter("PriorCodingPlan", [], ...
    @(x) isempty(x) || isstruct(x) || iscell(x) || ...
        isa(x, "sixgr.pdsch.DLSCHCodingPlan"));
ip.addParameter("HARQKey", "", @(x) ischar(x) || isstring(x));
ip.addParameter("InterferenceCovariance", [], ...
    @(x) isempty(x) || isnumeric(x));
ip.addParameter("InterferenceCovarianceInfo", struct(), ...
    @(x) isstruct(x) && isscalar(x));
ip.addParameter("InterferenceCovarianceIncludesNoise", false, ...
    @(x) islogical(x) || (isnumeric(x) && isscalar(x)));
ip.addParameter("EnablePTRSCPECorrection", true, ...
    @(x) islogical(x) || (isnumeric(x) && isscalar(x)));
ip.addParameter("EnableDMRSResidualPostEqSINRBound", false, ...
    @(x) islogical(x) || (isnumeric(x) && isscalar(x)));
ip.addParameter("EnableDecisionDirectedPostEqSINRBound", false, ...
    @(x) islogical(x) || (isnumeric(x) && isscalar(x)));
ip.addParameter("TrueChannel", [], @(x) isempty(x) || isnumeric(x));
ip.addParameter("OracleTestMode", false, ...
    @(x) islogical(x) || (isnumeric(x) && isscalar(x)));
ip.addParameter("UseMexLDPC",false, ...
    @(x) (islogical(x) || isnumeric(x)) && isscalar(x));
ip.parse(nv{:});
opt = ip.Results;
if ~isempty(opt.TrueChannel) && ~logical(opt.OracleTestMode)
    error("sixgr:pdsch:PDSCHReceiver:OracleTestModeRequired", ...
        "TrueChannel is an explicit perfect-CSI oracle and requires OracleTestMode=true.");
end
if logical(opt.OracleTestMode) && isempty(opt.TrueChannel)
    error("sixgr:pdsch:PDSCHReceiver:MissingTrueChannel", ...
        "OracleTestMode=true requires a nonempty runtime TrueChannel tensor.");
end

integrationBinding = localRXResolveIntegrationBinding( ...
    assignment, opt.IntegrationContext, opt.PrecoderBundle);
if ~(isnumeric(rxWaveform) && ismatrix(rxWaveform) ...
        && ~isempty(rxWaveform) && all(isfinite(real(rxWaveform(:)))) ...
        && all(isfinite(imag(rxWaveform(:)))))
    error("sixgr:pdsch:PDSCHReceiver:InvalidWaveform", ...
        "Received waveform must be a nonempty finite numeric matrix.");
end
if ~any(abs(rxWaveform(:)) > 0)
    error("sixgr:pdsch:PDSCHReceiver:NoReceivedSignal", ...
        "Strict PDSCH reception rejects an all-zero received waveform.");
end

[contract, receiver] = localStrictContract( ...
    assignment, resourcePlan, referenceRuntime, receiverConfig);
plans = localRXCodingPlans( ...
    opt.CodingPlans, contract, resourcePlan, receiver);
receiverPipelineTic = tic;
ofdmTic = tic;
[rxGrid, ofdmInfo] = sixgr.phy.waveform.ofdmDemodulate( ...
    carrier, rxWaveform, referenceRuntime.OFDMOptions{:});
ofdmLatency_ms = 1e3 .* toc(ofdmTic);
if size(rxGrid, 3) ~= receiver.NPhysicalRxAntennas
    error("sixgr:pdsch:PDSCHReceiver:ReceivePortCountMismatch", ...
        "OFDM grid has %d ports; receiver config requires %d.", ...
        size(rxGrid,3), receiver.NPhysicalRxAntennas);
end

if receiver.IsResourceSelective && ~logical(opt.OracleTestMode) && isempty(opt.PrecoderBundle)
    % Practical DM-RS estimation observes H*W in the layer-port domain.
    % It does not need the gNB's physical-port precoding matrix W.
    [expectedDMRS, dmrsIndices] = localRXLogicalReferences( ...
        resourcePlan.DMRSIndicesPerPort, ...
        referenceRuntime.DMRSSymbolsPerPort, "dmrs", carrier, contract);
else
    [expectedDMRS, dmrsIndices] = localRXReferencePorts( ...
        resourcePlan.DMRSIndicesPerPort, ...
        referenceRuntime.DMRSSymbolsPerPort, "dmrs", opt.PrecoderBundle, ...
        carrier, contract, receiver);
end
if isempty(dmrsIndices)
    error("sixgr:pdsch:PDSCHReceiver:MissingDMRSReference", ...
        "Strict PDSCH reception requires explicit DM-RS evidence.");
end
[dataPRB, dataSymbol] = localRXCoordinates(resourcePlan.DataIndices, carrier);
resourceSelectiveChannel = receiver.IsResourceSelective ...
    || logical(opt.OracleTestMode);
if resourceSelectiveChannel
    channelEstimationTic = tic;
    if logical(opt.OracleTestMode)
        [channelGain, estimatedNoiseVariance, dmrsResidual, ...
            channelEstimationInfo, channelEstimateNMSE] = ...
            localResolvePerfectChannelOracle(rxGrid, opt.TrueChannel, ...
            resourcePlan, referenceRuntime, carrier, contract, ...
            receiver, opt.PrecoderBundle);
    else
        [channelGain, estimatedNoiseVariance, dmrsResidual, ...
            channelEstimationInfo, channelEstimateNMSE] = ...
            localEstimateFadingChannel(rxGrid, resourcePlan, ...
            referenceRuntime, carrier, contract, receiver, ...
            opt.PrecoderBundle);
    end
    channelEstimationLatency_ms = 1e3 .* toc(channelEstimationTic);
    equalizationTic = tic;
    [layerValues, dataPortSymbols, equalizedGrid, equalizationInfo] = ...
        localEqualizeFadingResources(rxGrid, channelGain, ...
        resourcePlan.DataIndices, estimatedNoiseVariance, ...
        receiver.NoiseVariance, contract.NumLayers, ...
        opt.InterferenceCovariance, ...
        logical(opt.InterferenceCovarianceIncludesNoise));
    equalizationLatency_ms = 1e3 .* toc(equalizationTic);
    [expectedPTRS, ptrsIndices] = localRXLogicalReferences( ...
        resourcePlan.PTRSIndicesPerPort, ...
        referenceRuntime.PTRSSymbolsPerPort, "ptrs", ...
        carrier, contract);
    if logical(opt.EnablePTRSCPECorrection)
        [layerValues, ptrsInfo] = localPTRSCorrectionLayers( ...
            layerValues, dataSymbol, rxGrid, channelGain, ...
            ptrsIndices, expectedPTRS, carrier, ...
            estimatedNoiseVariance, receiver.NoiseVariance);
    else
        ptrsInfo = localDisabledPTRSCorrectionInfo( ...
            carrier, "disabled_by_runtime_configuration");
    end
    equalizedGrid = localMapEqualizedLayerResources( ...
        equalizedGrid, resourcePlan.DataIndices, layerValues);
    deprecoderTrace = localRXIdentityTrace( ...
        dataPRB, dataSymbol, ...
        "estimated_effective_layer_channel", contract.NumLayers);
    if logical(opt.OracleTestMode)
        channelEstimationMode = "ideal_true_channel_per_resource";
        channelEstimateScope = ...
            "runtime_path_gain_oracle_resource_selective_effective_layer_channel";
    else
        channelEstimationMode = "dmrs_nr_channel_estimate_per_resource";
        channelEstimateScope = ...
            "dmrs_backed_resource_selective_effective_layer_channel";
    end
    rawMeasuredPostEqualizationSINR = double( ...
        equalizationInfo.MeasuredPostEqualizationSINRdBPerLayer);
    measuredPostEqualizationSINR = rawMeasuredPostEqualizationSINR;
    layerSymbolNoiseVariance = double( ...
        equalizationInfo.PostEqualizationNoiseVariancePerResourceLayer);
    noiseVariance = mean(layerSymbolNoiseVariance,"all","omitnan");
else
    channelEstimationTic = tic;
    [channelGain, estimatedNoiseVariance, dmrsResidual] = ...
        localEstimateAWGNChannel(rxGrid, dmrsIndices, expectedDMRS);
    channelEstimationLatency_ms = 1e3 .* toc(channelEstimationTic);
    channelEstimationInfo = struct( ...
        "EngineUsed","explicit_awgn_scalar_per_physical_port_ls", ...
        "ChannelModel","AWGN", ...
        "HestSize",size(channelGain), ...
        "EstimatorUsesTrueChannel",false);
    channelEstimateNMSE = localNormalizedResidual( ...
        dmrsResidual, localExtractPortSymbols(rxGrid,dmrsIndices));
    equalizationTic = tic;
    equalizedGrid = localApplyPortChannelInverse(rxGrid, channelGain);
    equalizationLatency_ms = 1e3 .* toc(equalizationTic);
    [expectedPTRS, ptrsIndices] = localRXReferencePorts( ...
        resourcePlan.PTRSIndicesPerPort, ...
        referenceRuntime.PTRSSymbolsPerPort, "ptrs", ...
        opt.PrecoderBundle, carrier, contract, receiver);
    if logical(opt.EnablePTRSCPECorrection)
        [equalizedGrid, ptrsInfo] = localPTRSCorrection( ...
            equalizedGrid, ptrsIndices, expectedPTRS, carrier);
    else
        ptrsInfo = localDisabledPTRSCorrectionInfo( ...
            carrier, "disabled_by_runtime_configuration");
    end
    dataPortSymbols = localExtractPortSymbols( ...
        equalizedGrid, resourcePlan.DataIndices);
    if isempty(opt.PrecoderBundle)
        if size(dataPortSymbols,1) ~= contract.NumLayers
            error("sixgr:pdsch:PDSCHReceiver:MissingPrecoderBundle", ...
                "Identity reception requires one physical port per PDSCH layer.");
        end
        layerValues = dataPortSymbols;
        deprecoderTrace = localRXIdentityTrace( ...
            dataPRB, dataSymbol, "effective_channel", contract.NumLayers);
    else
        if opt.PrecoderBundle.NLayerPorts ~= contract.NumLayers ...
                || opt.PrecoderBundle.NPhysicalTxAntennas ~= ...
                size(dataPortSymbols,1)
            error("sixgr:pdsch:PDSCHReceiver:PrecoderDimensionMismatch", ...
                "Receiver precoder bundle dimensions do not match grid/rank.");
        end
        [layerValues, deprecoderTrace] = opt.PrecoderBundle.deapply( ...
            dataPortSymbols, dataPRB, dataSymbol, ...
            "Domain", "effective_channel");
    end
    equalizationInfo = struct( ...
        "EngineUsed","explicit_awgn_per_port_inverse", ...
        "Domain","physical_port_then_explicit_deprecoding");
    channelEstimationMode = "awgn_scalar_per_physical_port";
    channelEstimateScope = "AWGN_only_not_fading_full_grid";
    measuredLayerNoiseVariance = localAWGNLayerNoiseVariance( ...
        estimatedNoiseVariance,channelGain,opt.PrecoderBundle, ...
        dataPRB,dataSymbol,contract.NumLayers);
    rawMeasuredPostEqualizationSINR = 10*log10( ...
        1./max(measuredLayerNoiseVariance,eps));
    measuredPostEqualizationSINR = rawMeasuredPostEqualizationSINR;
    configuredPreEqualizationNoise = localEffectiveNoiseVariance( ...
        estimatedNoiseVariance,receiver.NoiseVariance);
    decoderLayerNoiseVariance = localAWGNLayerNoiseVariance( ...
        configuredPreEqualizationNoise,channelGain,opt.PrecoderBundle, ...
        dataPRB,dataSymbol,contract.NumLayers);
    layerSymbolNoiseVariance = repmat( ...
        reshape(decoderLayerNoiseVariance,1,[]), ...
        size(layerValues,2),1);
    noiseVariance = mean(decoderLayerNoiseVariance,"omitnan");
end

dmrsPostEqResidual = localUnavailablePDSCHResidual( ...
    "dmrs_residual", contract.NumLayers);
if logical(opt.EnableDMRSResidualPostEqSINRBound) && resourceSelectiveChannel
    dmrsPostEqResidual = localEstimatePDSCHDMRSPostEqResidual( ...
        rxGrid, channelGain, resourcePlan, referenceRuntime, carrier, ...
        contract, estimatedNoiseVariance, receiver.NoiseVariance, ...
        opt.InterferenceCovariance, ...
        logical(opt.InterferenceCovarianceIncludesNoise));
    [measuredPostEqualizationSINR, layerSymbolNoiseVariance, ...
        dmrsPostEqResidual] = localApplyPDSCHResidualBound( ...
        measuredPostEqualizationSINR, layerSymbolNoiseVariance, ...
        dmrsPostEqResidual);
end
decisionPostEqResidual = localUnavailablePDSCHResidual( ...
    "decision_directed", contract.NumLayers);
if logical(opt.EnableDecisionDirectedPostEqSINRBound)
    decisionPostEqResidual = ...
        localEstimatePDSCHDecisionDirectedPostEqResidual( ...
        layerValues, contract);
    [measuredPostEqualizationSINR, layerSymbolNoiseVariance, ...
        decisionPostEqResidual] = localApplyPDSCHResidualBound( ...
        measuredPostEqualizationSINR, layerSymbolNoiseVariance, ...
        decisionPostEqResidual);
end
noiseVariance = mean(layerSymbolNoiseVariance,"all","omitnan");
equalizationInfo.RawMeasuredPostEqualizationSINRdBPerLayer = ...
    double(rawMeasuredPostEqualizationSINR);
equalizationInfo.MeasuredPostEqualizationSINRdBPerLayer = ...
    double(measuredPostEqualizationSINR);
equalizationInfo.PostEqualizationNoiseVariancePerResourceLayer = ...
    double(layerSymbolNoiseVariance);
equalizationInfo.DMRSResidualBound = dmrsPostEqResidual;
equalizationInfo.DecisionDirectedResidualBound = decisionPostEqResidual;
equalizationInfo.DMRSResidualBoundEnabled = ...
    logical(opt.EnableDMRSResidualPostEqSINRBound);
equalizationInfo.DecisionDirectedResidualBoundEnabled = ...
    logical(opt.EnableDecisionDirectedPostEqSINRBound);
layerSymbols = layerValues.';
codewordSymbols = sixgr.pdsch.CodewordLayerMapper( ...
    layerSymbols, contract.NumLayers, "Operation", "demap");
codewordNoiseVariance = sixgr.pdsch.CodewordLayerMapper( ...
    layerSymbolNoiseVariance, contract.NumLayers, "Operation", "demap");
if contract.NumCodewords == 1
    codewordSymbols = {codewordSymbols};
    codewordNoiseVariance = {codewordNoiseVariance};
else
    codewordSymbols = reshape(codewordSymbols,1,[]);
    codewordNoiseVariance = reshape(codewordNoiseVariance,1,[]);
end

demapperNoiseVariance = max(double(noiseVariance), eps);
scrambledLLR = cell(1, contract.NumCodewords);
descrambledLLR = cell(1, contract.NumCodewords);
demodulationInfo = cell(1, contract.NumCodewords);
descramblingInfo = cell(1, contract.NumCodewords);
for cw = 1:contract.NumCodewords
    cwNoiseVariance = max(double(codewordNoiseVariance{cw}(:)),eps);
    if numel(cwNoiseVariance) ~= numel(codewordSymbols{cw}) ...
            || any(~isfinite(cwNoiseVariance) | cwNoiseVariance <= 0)
        error("sixgr:pdsch:PDSCHReceiver:DemapperNoiseShapeMismatch", ...
            "Layer-to-codeword noise mapping must produce one finite " + ...
            "positive variance for every equalized codeword symbol.");
    end
    [scrambledLLR{cw}, demodulationInfo{cw}] = ...
        sixgr.pdsch.PDSCHModulator(codewordSymbols{cw}, ...
        contract.Modulation(cw), "Operation", "soft-demap", ...
        "NoiseVariance", cwNoiseVariance);
    [descrambledLLR{cw}, descramblingInfo{cw}] = ...
        sixgr.pdsch.PDSCHScrambler(scrambledLLR{cw}, ...
        contract.RNTI, cw - 1, contract.NID, ...
        "Operation", "llr-descramble");
end

decode = sixgr.pdsch.DLSCHDecoder( ...
    localRXUnwrapOne(descrambledLLR), ...
    "CodingPlan", localRXUnwrapOne(plans), ...
    "MaxIterations", receiver.MaxIterations, ...
    "Algorithm", receiver.Algorithm, ...
    "PriorRecoveredLLR", opt.PriorRecoveredLLR, ...
    "PriorCodingPlan", opt.PriorCodingPlan, ...
    "HARQKey", opt.HARQKey, ...
    "UseMexLDPC",logical(opt.UseMexLDPC));
[transportBlocks, crcPass] = localDecodedResults( ...
    decode, contract.NumCodewords);
harqResults = localProcessHARQ(opt.HARQManager, assignment, ...
    plans, decode, receiver, crcPass);
metrics = localStrictMetrics(resourcePlan, dmrsIndices, ptrsIndices, ...
    layerSymbols, codewordSymbols, scrambledLLR, descrambledLLR, ...
    decode, contract, noiseVariance, crcPass, receiverConfig, ...
    channelGain, channelEstimateNMSE,measuredPostEqualizationSINR);

receiverPipelineLatency_ms = 1e3 .* toc(receiverPipelineTic);
decodeLatency_ms = 1e3 .* double(sixgr.util.structGet( ...
    decode,"DecodeLatency_s",NaN));
decodeLatency_ms = mean(decodeLatency_ms(:),"omitnan");

stageTrace = table( ...
    ["ofdm_demodulation";"dmrs_extraction";"channel_noise_estimation"; ...
     "ptrs_correction";"data_extraction";"equalization"; ...
     "layer_demap";"soft_demodulation";"llr_descrambling"; ...
     "dlsch_decoding"], ...
    repmat("PASS",10,1), ...
    [numel(rxGrid);numel(dmrsIndices);numel(channelGain); ...
     numel(ptrsIndices);numel(dataPortSymbols);numel(layerValues); ...
     sum(cellfun(@numel,codewordSymbols)); ...
     sum(cellfun(@numel,scrambledLLR)); ...
     sum(cellfun(@numel,descrambledLLR)); ...
     sum(cellfun(@numel,transportBlocks))], ...
    [ofdmLatency_ms;NaN;channelEstimationLatency_ms;NaN;NaN; ...
     equalizationLatency_ms;NaN;NaN;NaN;decodeLatency_ms], ...
    'VariableNames', {'Stage','Status','MaterializedElementCount', ...
    'StageLatency_ms'});

rx = struct();
rx.ContractVersion = "ExplicitPDSCHReceiver/v1";
rx.Assignment = assignment;
rx.ResourcePlan = resourcePlan;
rx.Carrier = carrier;
rx.IntegrationBinding = integrationBinding;
rx.ReferenceConfig = referenceConfig;
rx.ReceiverConfig = receiverConfig;
rx.CodingPlans = plans;
rx.OFDMGrid = rxGrid;
rx.OFDMInfo = ofdmInfo;
rx.ChannelGainPerPhysicalPort = [];
rx.EffectiveLayerChannelEstimate = [];
if resourceSelectiveChannel
    rx.EffectiveLayerChannelEstimate = channelGain;
else
    rx.ChannelGainPerPhysicalPort = channelGain;
end
rx.ChannelEstimationMode = channelEstimationMode;
rx.ChannelEstimateScope = channelEstimateScope;
rx.ChannelEstimationInfo = channelEstimationInfo;
rx.EqualizationInfo = equalizationInfo;
rx.InterferenceCovariance = opt.InterferenceCovariance;
rx.InterferenceCovarianceInfo = opt.InterferenceCovarianceInfo;
rx.InterferenceCovarianceIncludesNoise = ...
    logical(opt.InterferenceCovarianceIncludesNoise);
rx.ChannelEstimateNMSESource = metrics.ChannelEstimateNMSESource;
rx.EstimatedNoiseVariance = estimatedNoiseVariance;
rx.NoiseVarianceUsedForLLR = demapperNoiseVariance;
rx.NoiseVarianceUsedForLLRPerCodewordSymbol = codewordNoiseVariance;
rx.NoiseVarianceUsedForLLRConvention = ...
    "per_equalized_symbol_after_layer_to_codeword_mapping";
rx.DMRSResidual = dmrsResidual;
rx.DMRSPostEqualizationResidual = dmrsPostEqResidual;
rx.DecisionDirectedPostEqualizationResidual = decisionPostEqResidual;
rx.PostEqSINRRawEqualizerPerLayer_dB = ...
    double(rawMeasuredPostEqualizationSINR);
rx.PostEqSINRDMRSResidualBoundApplied = ...
    logical(dmrsPostEqResidual.Applied);
rx.PostEqSINRDecisionResidualBoundApplied = ...
    logical(decisionPostEqResidual.Applied);
rx.DMRSResidualPostEqSINRBoundEnabled = ...
    logical(opt.EnableDMRSResidualPostEqSINRBound);
rx.DecisionDirectedPostEqSINRBoundEnabled = ...
    logical(opt.EnableDecisionDirectedPostEqSINRBound);
rx.PTRSCorrection = ptrsInfo;
rx.EqualizedGrid = equalizedGrid;
rx.DataPortSymbols = dataPortSymbols;
rx.DeprecoderTrace = deprecoderTrace;
rx.LayerSymbols = layerSymbols;
rx.CodewordSymbols = codewordSymbols;
rx.ScrambledLLR = scrambledLLR;
rx.DemodulationInfo = demodulationInfo;
rx.DescrambledLLR = descrambledLLR;
rx.DescramblingInfo = descramblingInfo;
rx.Decode = decode;
rx.DecodeLatency_s = double(sixgr.util.structGet( ...
    decode,"DecodeLatency_s",NaN));
rx.DecodeLatencyPerCodeword_s = double(sixgr.util.structGet( ...
    decode,"DecodeLatencyPerCodeword_s",rx.DecodeLatency_s));
rx.DecodeLatencySource = string(sixgr.util.structGet( ...
    decode,"DecodeLatencySource","unavailable"));
rx.OFDMDemodulationLatency_ms = double(ofdmLatency_ms);
rx.ChannelEstimationLatency_ms = double(channelEstimationLatency_ms);
rx.EqualizationLatency_ms = double(equalizationLatency_ms);
rx.ReceiverPipelineLatency_ms = double(receiverPipelineLatency_ms);
rx.ReceiverStageLatencySource = "matlab_tic_toc_canonical_pdsch_receiver_stages";
rx.TransportBlocks = transportBlocks;
rx.TransportBlock = vertcat(transportBlocks{:});
rx.CRCPassPerCodeword = logical(crcPass);
rx.CRCErrorPerCodeword = logical(~crcPass);
rx.CRCPass = all(crcPass);
rx.CRCError = any(~crcPass);
rx.HARQResults = harqResults;
rx.Metrics = metrics;
rx.StageTrace = stageTrace;
rx.Source = "explicit_pdsch_dlsch_production_receiver";
rx.OracleTestMode = logical(opt.OracleTestMode);
rx.EstimatorUsesTrueChannel = logical(sixgr.util.structGet( ...
    channelEstimationInfo,"EstimatorUsesTrueChannel",false));
end

function binding = localRXResolveIntegrationBinding( ...
        assignment, context, precoderBundle)
strictProfile = any(assignment.Profile == ...
    ["connected_strict","sps_strict","ra_si_strict"]);
if ~strictProfile
    binding = struct( ...
        "Required", false, ...
        "Profile", assignment.Profile, ...
        "Status", "NOT_REQUIRED_PHY_CALIBRATION");
    return;
end
if isempty(fieldnames(context))
    error("sixgr:pdsch:MissingIntegrationContext", ...
        "Strict PDSCH RX requires the explicit active BWP/CC/epoch/TCI " + ...
        "integration context.");
end
if isempty(precoderBundle)
    % A practical receiver estimates H*W from received logical-port DM-RS.
    % Active BWP/CC/epoch/QCL validation is still mandatory, but the UE
    % does not own the transmitter's applied physical-port matrix digest.
    % Omitting argument three explicitly leaves TX-matrix binding unevaluated.
    binding = sixgr.pdsch.PDSCHIntegrationValidator.bind(assignment, context);
else
    % Explicit matrix-assisted callers must retain the full binding guard.
    binding = sixgr.pdsch.PDSCHIntegrationValidator.bind( ...
        assignment, context, precoderBundle);
end
end

function localRXValidateCarrierSymbolBoundary(assignment, carrier)
allocation = double(assignment.get("SymbolAllocation"));
if numel(allocation) ~= 2 || any(~isfinite(allocation)) ...
        || any(allocation ~= fix(allocation)) ...
        || allocation(1) < 0 || allocation(2) < 1 ...
        || allocation(1) + allocation(2) > double(carrier.SymbolsPerSlot)
    error("sixgr:pdsch:PDSCHReceiver:SymbolAllocationOutsideCarrier", ...
        "Assignment SymbolAllocation=%s is outside the carrier's " + ...
        "%d-symbol slot.", mat2str(allocation), carrier.SymbolsPerSlot);
end
end

function [contract, receiver] = localStrictContract( ...
        assignment, plan, referenceConfig, receiverConfig)
if ~isstruct(referenceConfig) || ~isscalar(referenceConfig)
    error("sixgr:pdsch:PDSCHReceiver:InvalidReferenceConfig", ...
        "Reference configuration must be a scalar struct.");
end
referenceRequired = ["DataScramblingIdentityNID","DMRSSymbolsPerPort", ...
    "PTRSSymbolsPerPort","NPhysicalTxAntennas","OFDMOptions"];
missing = referenceRequired(~isfield(referenceConfig, referenceRequired));
if ~isempty(missing)
    error("sixgr:pdsch:PDSCHReceiver:IncompleteReferenceConfig", ...
        "Reference configuration is missing: %s.", ...
        strjoin(cellstr(missing), ", "));
end
if ~iscell(referenceConfig.OFDMOptions) ...
        || mod(numel(referenceConfig.OFDMOptions),2) ~= 0
    error("sixgr:pdsch:PDSCHReceiver:InvalidOFDMOptions", ...
        "OFDMOptions must be a cell array of name-value pairs.");
end
if ~isstruct(receiverConfig) || ~isscalar(receiverConfig)
    error("sixgr:pdsch:PDSCHReceiver:InvalidReceiverConfig", ...
        "Receiver configuration must be a scalar struct.");
end
receiverRequired = ["TransportBlockSizes","ChannelModel", ...
    "MaxIterations","Algorithm","LLRConvention","NPhysicalRxAntennas"];
missing = receiverRequired(~isfield(receiverConfig, receiverRequired));
if ~isempty(missing)
    error("sixgr:pdsch:PDSCHReceiver:IncompleteReceiverConfig", ...
        "Receiver configuration is missing: %s.", ...
        strjoin(cellstr(missing), ", "));
end
if string(receiverConfig.LLRConvention) ~= "positive_favours_bit_zero"
    error("sixgr:pdsch:PDSCHReceiver:UnsupportedLLRConvention", ...
        "Strict PDSCH decoding requires positive LLR to favour bit zero.");
end

contract = struct();
contract.NumCodewords = double(assignment.get("NumCodewords"));
contract.NumLayers = double(assignment.get("NumLayers"));
contract.LayerCount = localRXNumeric( ...
    assignment.get("LayerCountPerCodeword"),contract.NumCodewords, ...
    "LayerCountPerCodeword");
contract.Modulation = localRXStrings( ...
    assignment.get("ModulationPerCodeword"),contract.NumCodewords, ...
    "ModulationPerCodeword");
contract.TargetCodeRate = localRXNumeric( ...
    assignment.get("TargetCodeRatePerCodeword"),contract.NumCodewords, ...
    "TargetCodeRatePerCodeword");
contract.RV = localRXNumeric( ...
    assignment.get("RVPerCodeword"),contract.NumCodewords,"RVPerCodeword");
contract.RNTI = double(assignment.get("RNTI"));
contract.NID = double(referenceConfig.DataScramblingIdentityNID);
if contract.NumCodewords ~= 1 + double(contract.NumLayers > 4) ...
        || sum(contract.LayerCount) ~= contract.NumLayers ...
        || ~isequal(contract.LayerCount,plan.LayerCountPerCodeword)
    error("sixgr:pdsch:PDSCHReceiver:CodewordLayerMismatch", ...
        "Assignment and resource-plan codeword/layer contracts differ.");
end
qms = arrayfun(@localRXQm,contract.Modulation);
if ~isequal(qms,plan.QmPerCodeword)
    error("sixgr:pdsch:PDSCHReceiver:ModulationResourcePlanMismatch", ...
        "Assignment modulation orders differ from the resource plan.");
end
if ~isequal(double(assignment.get("PRBSetCarrierRelative")),plan.PRBSet) ...
        || ~isequal(double(assignment.get("SymbolAllocation")),plan.SymbolAllocation)
    error("sixgr:pdsch:PDSCHReceiver:AssignmentResourcePlanMismatch", ...
        "Assignment PRB/symbol allocation differs from the resource plan.");
end
if ~(isscalar(contract.NID) && isfinite(contract.NID) ...
        && contract.NID == fix(contract.NID) ...
        && contract.NID >= 0 && contract.NID <= 1023)
    error("sixgr:pdsch:PDSCHReceiver:InvalidScramblingIdentity", ...
        "DataScramblingIdentityNID must be an integer in [0,1023].");
end

receiver = struct();
receiver.TransportBlockSizes = localRXNumeric( ...
    receiverConfig.TransportBlockSizes,contract.NumCodewords, ...
    "TransportBlockSizes");
if any(receiver.TransportBlockSizes <= 0 ...
        | receiver.TransportBlockSizes ~= fix(receiver.TransportBlockSizes))
    error("sixgr:pdsch:PDSCHReceiver:InvalidTransportBlockSizes", ...
        "TransportBlockSizes must be positive integers.");
end
receiver.MaxIterations = double(receiverConfig.MaxIterations);
if ~(isscalar(receiver.MaxIterations) && isfinite(receiver.MaxIterations) ...
        && receiver.MaxIterations >= 1 ...
        && receiver.MaxIterations == fix(receiver.MaxIterations))
    error("sixgr:pdsch:PDSCHReceiver:InvalidMaxIterations", ...
        "MaxIterations must be a positive integer.");
end
receiver.Algorithm = char(string(receiverConfig.Algorithm));
receiver.ReferencePhysicalTxAntennas = ...
    double(referenceConfig.NPhysicalTxAntennas);
if ~(isscalar(receiver.ReferencePhysicalTxAntennas) ...
        && isfinite(receiver.ReferencePhysicalTxAntennas) ...
        && receiver.ReferencePhysicalTxAntennas >= 1 ...
        && receiver.ReferencePhysicalTxAntennas == ...
            fix(receiver.ReferencePhysicalTxAntennas))
    error("sixgr:pdsch:PDSCHReceiver:InvalidReferenceTransmitPortCount", ...
        "NPhysicalTxAntennas must be a positive integer.");
end
receiver.ChannelModel = upper(strtrim(string(receiverConfig.ChannelModel)));
receiver.NPhysicalRxAntennas = double(receiverConfig.NPhysicalRxAntennas);
if ~(isscalar(receiver.NPhysicalRxAntennas) ...
        && isreal(receiver.NPhysicalRxAntennas) && isfinite(receiver.NPhysicalRxAntennas) ...
        && receiver.NPhysicalRxAntennas >= 1 ...
        && receiver.NPhysicalRxAntennas == fix(receiver.NPhysicalRxAntennas))
    error("sixgr:pdsch:PDSCHReceiver:InvalidReceivePortCount", ...
        "NPhysicalRxAntennas must be a finite positive integer.");
end
receiver.IsFading = startsWith(receiver.ChannelModel,"TDL-") ...
    || startsWith(receiver.ChannelModel,"CDL-") ...
    || startsWith(receiver.ChannelModel,"NTN-TDL-") ...
    || startsWith(receiver.ChannelModel,"NTN-CDL-");
receiver.IsStaticMIMO = receiver.ChannelModel == "STATIC-MIMO";
% Unequal AWGN port dimensions are not a diagonal per-port channel. Estimate
% the effective layer channel from received DM-RS on every actual RX branch.
% Keep the actual channel model and the equal-port legacy AWGN path intact.
receiver.IsAWGNReceiveDiversity = receiver.ChannelModel == "AWGN" ...
    && receiver.NPhysicalRxAntennas ~= receiver.ReferencePhysicalTxAntennas;
receiver.IsResourceSelective = receiver.IsFading ...
    || receiver.IsStaticMIMO || receiver.IsAWGNReceiveDiversity;
if receiver.ChannelModel ~= "AWGN" ...
        && ~receiver.IsResourceSelective
    error("sixgr:pdsch:PDSCHReceiver:ConcreteFadingProfileRequired", ...
        "ChannelModel must be AWGN, STATIC-MIMO, or a concrete " + ...
        "terrestrial/NTN TDL/CDL profile; bare model families and unrecognized " + ...
        "tokens are not executable.");
end
receiver.DMRSCDMLengths = [];
if receiver.IsResourceSelective
    if ~isfield(referenceConfig,"DMRSCDMLengths")
        error("sixgr:pdsch:PDSCHReceiver:MissingDMRSCDMLengths", ...
            "Fading reception requires the explicit DMRSCDMLengths " + ...
            "used to generate the scheduled DM-RS ports.");
    end
    receiver.DMRSCDMLengths = double( ...
        referenceConfig.DMRSCDMLengths(:).');
    if isempty(receiver.DMRSCDMLengths) ...
            || any(~isfinite(receiver.DMRSCDMLengths)) ...
            || any(receiver.DMRSCDMLengths < 1) ...
            || any(receiver.DMRSCDMLengths ~= ...
                fix(receiver.DMRSCDMLengths))
        error("sixgr:pdsch:PDSCHReceiver:InvalidDMRSCDMLengths", ...
            "DMRSCDMLengths must contain explicit positive integers.");
    end
end
if receiver.IsResourceSelective ...
        && receiver.NPhysicalRxAntennas < contract.NumLayers
    error("sixgr:pdsch:PDSCHReceiver:InsufficientReceiveRank", ...
        "Resource-selective reception requires at least NumLayers independent " + ...
        "receive observations for the scheduled spatial rank.");
end
receiver.UseExactFlatPRGEstimator = logical(sixgr.util.structGet( ...
    receiverConfig, "UseExactFlatPRGEstimator", false));
if ~isscalar(receiver.UseExactFlatPRGEstimator)
    error("sixgr:pdsch:PDSCHReceiver:InvalidFlatPRGEstimatorAuthority", ...
        "UseExactFlatPRGEstimator must be a scalar logical authority.");
end
receiver.NoiseVariance = [];
if isfield(receiverConfig,"NoiseVariance") ...
        && ~isempty(receiverConfig.NoiseVariance)
    value = double(receiverConfig.NoiseVariance);
    if ~(isscalar(value) && isfinite(value) && value >= 0)
        error("sixgr:pdsch:PDSCHReceiver:InvalidNoiseVariance", ...
            "NoiseVariance must be a finite nonnegative grid-domain scalar.");
    end
    receiver.NoiseVariance = value;
end
receiver.Nref = [];
if isfield(receiverConfig,"Nref")
    receiver.Nref = receiverConfig.Nref;
end
receiver.Raw = receiverConfig;
end

function plans = localRXCodingPlans(raw,contract,resourcePlan,receiver)
if isempty(raw)
    error("sixgr:pdsch:PDSCHReceiver:MissingCodingPlan", ...
        ("Strict PDSCH RX requires the immutable DLSCHCodingPlan " + ...
        "object(s) resolved from the receiver allocation and retained TB coding state."));
end
if isa(raw,"sixgr.pdsch.DLSCHCodingPlan")
    plans = num2cell(reshape(raw,1,[]));
elseif iscell(raw)
    plans = reshape(raw,1,[]);
else
    error("sixgr:pdsch:PDSCHReceiver:InvalidCodingPlan", ...
        "CodingPlans must contain immutable DLSCHCodingPlan objects.");
end
if numel(plans) ~= contract.NumCodewords
    error("sixgr:pdsch:PDSCHReceiver:CodingPlanCountMismatch", ...
        "Strict PDSCH RX requires exactly %d coding plan(s).", ...
        contract.NumCodewords);
end
nref = localRXOptional(receiver.Nref,contract.NumCodewords);
for cw = 1:contract.NumCodewords
    plan = plans{cw};
    if ~isa(plan,"sixgr.pdsch.DLSCHCodingPlan") ...
            || ~isscalar(plan) || ~logical(plan.Immutable) ...
            || strlength(string(plan.PlanID)) == 0 ...
            || strlength(string(plan.CodingLayoutHash)) == 0
        error("sixgr:pdsch:PDSCHReceiver:InvalidCodingPlan", ...
            ("Coding plan %d must be one immutable DLSCHCodingPlan " + ...
            "with a nonempty PlanID and CodingLayoutHash."),cw-1);
    end
    matches = double(plan.CodewordIndex) == cw-1 ...
        && double(plan.TransportBlockSize) == ...
            receiver.TransportBlockSizes(cw) ...
        && abs(double(plan.TargetCodeRate) - ...
            contract.TargetCodeRate(cw)) <= 1e-12 ...
        && double(plan.RateMatchedBitCount) == ...
            resourcePlan.GPerCodeword(cw) ...
        && double(plan.RV) == contract.RV(cw) ...
        && upper(string(plan.Modulation)) == ...
            upper(contract.Modulation(cw)) ...
        && double(plan.NumLayers) == contract.LayerCount(cw);
    if ~isempty(nref{cw})
        matches = matches && ~isempty(plan.Nref) ...
            && double(plan.Nref) == double(nref{cw});
    end
    if ~matches
        error("sixgr:pdsch:PDSCHReceiver:CodingPlanContractMismatch", ...
            ("Coding plan %d differs from the immutable assignment, " + ...
            "resource plan, or receiver transport-block contract."),cw-1);
    end
    layout = plan.toCodingLayout();
    if string(layout.CodingLayoutHash) ~= string(plan.CodingLayoutHash)
        error("sixgr:pdsch:PDSCHReceiver:CodingPlanContractMismatch", ...
            "Coding plan %d layout hash does not match its PlanID.",cw-1);
    end
end
end

function [expected, unionIndices] = localRXReferencePorts( ...
        indexCells, symbolCells, domain, bundle, carrier, contract, receiver)
[logicalSymbols, unionIndices] = localRXLogicalReferences( ...
    indexCells, symbolCells, domain, carrier, contract);
[prb,symbol] = localRXCoordinates(unionIndices,carrier);
txPorts = receiver.ReferencePhysicalTxAntennas;
if isempty(unionIndices)
    expected = complex(zeros(txPorts,0));
    return;
end
if isempty(bundle)
    if txPorts ~= contract.NumLayers
        error("sixgr:pdsch:PDSCHReceiver:MissingPrecoderBundle", ...
            "Identity reference processing requires one physical port per layer.");
    end
    expected = logicalSymbols;
else
    if bundle.NLayerPorts ~= contract.NumLayers ...
            || bundle.NPhysicalTxAntennas ~= txPorts
        error("sixgr:pdsch:PDSCHReceiver:PrecoderDimensionMismatch", ...
            "Reference precoder dimensions differ from receiver rank/ports.");
    end
    expected = bundle.apply(logicalSymbols,prb,symbol,"Domain",domain);
end
end

function [logicalSymbols, unionIndices] = localRXLogicalReferences( ...
        indexCells, symbolCells, domain, carrier, contract)
if ~iscell(indexCells) || ~isrow(indexCells) ...
        || numel(indexCells) ~= contract.NumLayers ...
        || ~iscell(symbolCells) || ~isrow(symbolCells) ...
        || numel(symbolCells) ~= contract.NumLayers
    error("sixgr:pdsch:PDSCHReceiver:ReferencePortCountMismatch", ...
        "%s indices and symbols require one cell per layer port.",upper(domain));
end
planeSize = carrier.NSizeGrid*12*carrier.SymbolsPerSlot;
unionIndices = unique([indexCells{:}],"sorted");
if any(unionIndices < 0 | unionIndices >= planeSize)
    error("sixgr:pdsch:PDSCHReceiver:ReferenceIndexOutsideGrid", ...
        "%s contains an index outside the carrier grid.",upper(domain));
end
logicalSymbols = complex(zeros(contract.NumLayers,numel(unionIndices)));
for layer = 1:contract.NumLayers
    indices = double(indexCells{layer}(:));
    symbols = symbolCells{layer};
    if ~(isnumeric(symbols) && isvector(symbols) ...
            && numel(symbols) == numel(indices) ...
            && all(isfinite(real(symbols(:)))) ...
            && all(isfinite(imag(symbols(:)))))
        error("sixgr:pdsch:PDSCHReceiver:ReferenceSymbolCountMismatch", ...
            "%s symbols do not match layer-port %d indices.", ...
            upper(domain),layer-1);
    end
    [present,position] = ismember(indices,unionIndices);
    if any(~present)
        error("sixgr:pdsch:PDSCHReceiver:ReferenceIndexMismatch", ...
            "Unable to resolve %s layer-port indices.",upper(domain));
    end
    logicalSymbols(layer,position) = complex(double(symbols(:)));
end
end

function [gain,noiseVariance,residual] = localEstimateAWGNChannel( ...
        grid,indices,expected)
observed = localExtractPortSymbols(grid,indices);
if ~isequal(size(observed),size(expected))
    error("sixgr:pdsch:PDSCHReceiver:DMRSShapeMismatch", ...
        "Observed and expected DM-RS matrices have different shapes.");
end
nPorts = size(observed,1);
gain = complex(zeros(nPorts,1));
residual = complex(zeros(size(observed)));
for port = 1:nPorts
    energy = sum(abs(expected(port,:)).^2);
    if ~(isfinite(energy) && energy > 0)
        error("sixgr:pdsch:PDSCHReceiver:MissingDMRSPortEvidence", ...
            "Physical port %d has no nonzero DM-RS evidence.",port-1);
    end
    gain(port) = sum(conj(expected(port,:)).*observed(port,:))/energy;
    if ~(isfinite(real(gain(port))) && isfinite(imag(gain(port))) ...
            && abs(gain(port)) > eps)
        error("sixgr:pdsch:PDSCHReceiver:InvalidChannelEstimate", ...
            "Physical port %d produced a zero or nonfinite AWGN estimate.",port-1);
    end
    residual(port,:) = observed(port,:) - gain(port)*expected(port,:);
end
noiseVariance = mean(abs(residual(:)).^2);
if ~(isscalar(noiseVariance) && isfinite(noiseVariance) && noiseVariance >= 0)
    error("sixgr:pdsch:PDSCHReceiver:InvalidNoiseEstimate", ...
        "DM-RS residual did not produce a valid noise variance.");
end
end

function [hest,noiseVariance,residual,info,pilotNMSE] = ...
        localEstimateFadingChannel(grid,plan,referenceConfig, ...
        carrier,contract,receiver,precoderBundle)
indexCells = plan.DMRSIndicesPerPort;
symbolCells = referenceConfig.DMRSSymbolsPerPort;
counts = cellfun(@numel,indexCells);
symbolCounts = cellfun(@numel,symbolCells);
if any(counts ~= counts(1)) || any(symbolCounts ~= counts)
    error("sixgr:pdsch:PDSCHReceiver:FadingDMRSMatrixShapeMismatch", ...
        "Resource-selective MIMO estimation requires an equal explicit " + ...
        "DM-RS observation count on every scheduled layer port.");
end
count = counts(1);
planeSize = carrier.NSizeGrid*12*carrier.SymbolsPerSlot;
refInd = zeros(count,contract.NumLayers);
refSym = complex(zeros(count,contract.NumLayers));
for layer = 1:contract.NumLayers
    indices = double(indexCells{layer}(:));
    symbols = complex(double(symbolCells{layer}(:)));
    if any(indices < 0 | indices >= planeSize) ...
            || any(~isfinite(real(symbols)) | ~isfinite(imag(symbols))) ...
            || ~all(abs(symbols) > 0)
        error("sixgr:pdsch:PDSCHReceiver:InvalidFadingDMRSReference", ...
            "Fading DM-RS indices must lie in the carrier grid and every " + ...
            "scheduled layer reference symbol must be finite and nonzero.");
    end
    refInd(:,layer) = indices + 1 + planeSize*(layer-1);
    refSym(:,layer) = symbols;
end
if ~isempty(precoderBundle) && precoderBundle.NPRG > 1
    flatPRGEligible = receiver.UseExactFlatPRGEstimator ...
        && receiver.ChannelModel == "STATIC-MIMO" ...
        && contract.NumLayers == 1;
    if flatPRGEligible
        [hest,noiseVariance,info] = localEstimateFlatChannelPerPRG( ...
            grid,carrier,refInd,refSym,receiver,contract,precoderBundle);
    else
        [hest,noiseVariance,info] = localEstimateFadingChannelPerPRG( ...
            grid,carrier,refInd,refSym,receiver,contract,precoderBundle);
        info.ExactFlatPRGEstimatorRequested = ...
            logical(receiver.UseExactFlatPRGEstimator);
        info.ExactFlatPRGEstimatorEligible = false;
        info.ExactFlatPRGEstimatorUsed = false;
        if receiver.UseExactFlatPRGEstimator
            info.ExactFlatPRGEstimatorDisabledReason = ...
                "requires_static_mimo_rank_one_prg_bundle";
        else
            info.ExactFlatPRGEstimatorDisabledReason = "disabled_by_config";
        end
    end
else
    [hest,noiseVariance,info] = localEstimateFadingChannelKernel( ...
        grid,carrier,refInd,refSym,receiver,contract, ...
        "sixgr.pdsch.PDSCHReceiver.strict_fading");
end

expectedShape = [carrier.NSizeGrid*12,carrier.SymbolsPerSlot, ...
    receiver.NPhysicalRxAntennas,contract.NumLayers];
actualShape = size(hest);
actualShape(end+1:4) = 1;
if ~isequal(actualShape(1:4),expectedShape) ...
        || any(~isfinite(real(hest(:)))) ...
        || any(~isfinite(imag(hest(:))))
    error("sixgr:pdsch:PDSCHReceiver:InvalidFadingChannelEstimate", ...
        "DM-RS estimation must return a finite K-by-L-by-NRx-by-rank " + ...
        "per-resource effective channel tensor.");
end
if logical(sixgr.util.structGet(info,"ScalarFastPathUsed",false)) ...
        || contains(lower(string(sixgr.util.structGet( ...
        info,"EngineUsed",""))),["scalar","mex"])
    error("sixgr:pdsch:PDSCHReceiver:ScalarFadingEstimateForbidden", ...
        "A scalar channel-estimation engine cannot serve a fading PDSCH.");
end
[residual,pilotNMSE] = localFadingPilotResidual( ...
    grid,hest,indexCells,symbolCells,carrier,contract);
if ~(isscalar(noiseVariance) && isfinite(noiseVariance) ...
        && noiseVariance >= 0)
    error("sixgr:pdsch:PDSCHReceiver:InvalidNoiseEstimate", ...
        "DM-RS estimation did not return a finite nonnegative noise estimate.");
end
info.PilotReconstructionNMSE = double(pilotNMSE);
info.PilotReconstructionNMSESource = ...
    "received_dmrs_minus_estimated_effective_channel_times_known_dmrs";
end

function [hest,noiseVariance,info] = localEstimateFlatChannelPerPRG( ...
        grid,carrier,refInd,refSym,receiver,contract,bundle)
% Exact measured-DMRS LS for flat MIMO with PRG-discontinuous precoding.
if receiver.ChannelModel ~= "STATIC-MIMO" || contract.NumLayers ~= 1 ...
        || bundle.NLayerPorts ~= 1 || bundle.NPRG <= 1
    error("sixgr:pdsch:PDSCHReceiver:FlatPRGEstimatorIneligible", ...
        "Exact flat PRG LS requires STATIC-MIMO, rank one, and multiple PRGs.");
end
K = double(carrier.NSizeGrid) * 12;
L = double(carrier.SymbolsPerSlot);
nRx = size(grid, 3);
hest = complex(zeros(K, L, nRx, 1, "like", grid));
noiseValues = NaN(double(bundle.NPRG), 1);
pilotCounts = zeros(double(bundle.NPRG), 1);
coefficients = complex(NaN(double(bundle.NPRG), nRx));
covered = false(K, 1);
for prgIndex = 1:double(bundle.NPRG)
    prbs = double(bundle.PRGToPRBMap{prgIndex}(:).');
    zeroBased = double(refInd(:,1) - 1);
    subcarrier = mod(zeroBased, K);
    mask = ismember(floor(subcarrier / 12), prbs);
    indices = double(refInd(mask,1));
    symbols = complex(double(refSym(mask,1)));
    if isempty(indices) || numel(indices) ~= numel(symbols)
        error("sixgr:pdsch:PDSCHReceiver:IncompleteFlatPRGDMRSEvidence", ...
            "Flat PRG %d has no aligned DM-RS evidence.", prgIndex - 1);
    end
    observations = nrExtractResources(indices, grid);
    if isvector(observations)
        observations = observations(:);
    end
    if size(observations, 1) ~= numel(symbols)
        error("sixgr:pdsch:PDSCHReceiver:FlatPRGDMRSShapeMismatch", ...
            "Flat PRG %d observation/reference dimensions differ.", prgIndex - 1);
    end
    energy = sum(abs(symbols).^2);
    if ~(isfinite(energy) && energy > 0)
        error("sixgr:pdsch:PDSCHReceiver:MissingFlatPRGDMRSEvidence", ...
            "Flat PRG %d has zero DM-RS energy.", prgIndex - 1);
    end
    coefficient = (conj(symbols).' * observations) ./ energy;
    residual = observations - symbols * coefficient;
    dof = numel(residual) - numel(coefficient);
    if dof > 0
        noiseValues(prgIndex) = sum(abs(residual(:)).^2) ./ dof;
    else
        noiseValues(prgIndex) = mean(abs(residual(:)).^2);
    end
    if ~isfinite(noiseValues(prgIndex)) || noiseValues(prgIndex) < 0 ...
            || any(~isfinite(real(coefficient)) | ~isfinite(imag(coefficient)))
        error("sixgr:pdsch:PDSCHReceiver:InvalidFlatPRGEstimate", ...
            "Flat PRG %d produced a nonfinite channel/noise estimate.", prgIndex - 1);
    end
    targetSubcarriers = reshape((12 * prbs(:).' + (0:11).'), [], 1);
    for rxPort = 1:nRx
        hest(targetSubcarriers + 1, :, rxPort, 1) = ...
            cast(coefficient(rxPort), "like", grid);
    end
    covered(targetSubcarriers + 1) = true;
    pilotCounts(prgIndex) = numel(symbols);
    coefficients(prgIndex, :) = coefficient;
end
scheduledSubcarriers = false(K, 1);
scheduledPRBs = double(bundle.PRBSet(:).');
scheduled = reshape((12 * scheduledPRBs(:).' + (0:11).'), [], 1);
scheduledSubcarriers(scheduled + 1) = true;
if any(scheduledSubcarriers & ~covered) || any(pilotCounts <= 0)
    error("sixgr:pdsch:PDSCHReceiver:IncompleteFlatPRGEstimate", ...
        "Flat PRG LS did not cover every scheduled subcarrier.");
end
noiseVariance = sum(noiseValues .* pilotCounts) ./ sum(pilotCounts);
info = struct( ...
    "EngineUsed", "exact_flat_static_mimo_ls_per_prg_stitched", ...
    "ChannelModel", char(receiver.ChannelModel), ...
    "HestSize", size(hest), ...
    "NoiseVar", double(noiseVariance), ...
    "ScalarFastPathUsed", false, ...
    "PRGAware", true, ...
    "PRGCount", double(bundle.NPRG), ...
    "PRGSet", localReceiverPRGSet(carrier, bundle), ...
    "PRGBundleSizeRB", double(bundle.PRGSize), ...
    "PRGPilotCounts", double(pilotCounts), ...
    "EstimatedCoefficients", coefficients, ...
    "PrecoderBundleDigest", string(bundle.ImmutableBundleDigest), ...
    "InterpolationMethod", ...
        "constant_within_each_prg_from_prg_local_received_dmrs_ls", ...
    "EffectiveChannelConvention", ...
        "received_effective_layer_channel_after_frozen_prg_precoding", ...
    "ExactFlatPRGEstimatorRequested", true, ...
    "ExactFlatPRGEstimatorEligible", true, ...
    "ExactFlatPRGEstimatorUsed", true, ...
    "ExactFlatPRGEstimatorDisabledReason", "");
end

function [hest,noiseVariance,residual,info,pilotNMSE] = ...
        localResolvePerfectChannelOracle(grid,truePhysicalChannel,plan, ...
        referenceConfig,carrier,contract,receiver,precoderBundle)
% Resolve the exact physical channel generated by the same waveform filter
% into the scheduled effective layer domain.  This path is an explicit LLS
% calibration oracle; it is never selected by scheduler/connected profiles.
K = double(carrier.NSizeGrid)*12;
L = double(carrier.SymbolsPerSlot);
nRx = double(receiver.NPhysicalRxAntennas);
nTx = double(receiver.ReferencePhysicalTxAntennas);
nLayers = double(contract.NumLayers);
actual = size(truePhysicalChannel);
actual(end+1:4) = 1;
expected = [K L nRx nTx];
if ~isequal(actual(1:4),expected) ...
        || any(~isfinite(real(truePhysicalChannel(:)))) ...
        || any(~isfinite(imag(truePhysicalChannel(:))))
    error("sixgr:pdsch:PDSCHReceiver:InvalidTrueChannelTensor", ...
        "TrueChannel must be a finite K-by-L-by-NRx-by-NTx tensor of size %s; received %s.", ...
        mat2str(expected),mat2str(actual(1:4)));
end
if isempty(receiver.NoiseVariance) || ~isscalar(receiver.NoiseVariance) ...
        || ~isfinite(receiver.NoiseVariance) || receiver.NoiseVariance < 0
    error("sixgr:pdsch:PDSCHReceiver:MissingOracleNoiseVariance", ...
        "Perfect-CSI PDSCH calibration requires an explicit finite grid-domain NoiseVariance.");
end

if isempty(precoderBundle)
    if nTx ~= nLayers
        error("sixgr:pdsch:PDSCHReceiver:MissingOraclePrecoderBundle", ...
            "Perfect-CSI projection from %d physical ports to %d layers requires the exact precoder bundle.", ...
            nTx,nLayers);
    end
    hest = reshape(complex(double(truePhysicalChannel)),[K L nRx nLayers]);
    projectionSource = "identity_physical_port_to_layer_mapping";
else
    if precoderBundle.NPhysicalTxAntennas ~= nTx ...
            || precoderBundle.NLayerPorts ~= nLayers
        error("sixgr:pdsch:PDSCHReceiver:OraclePrecoderDimensionMismatch", ...
            "True-channel tensor/precoder dimensions disagree with the scheduled physical-port/layer contract.");
    end
    hest = complex(zeros(K,L,nRx,nLayers,"like",truePhysicalChannel));
    for prbIndex = 1:numel(precoderBundle.PRBSet)
        prb = double(precoderBundle.PRBSet(prbIndex));
        subcarriers = 12*prb + (1:12);
        for symbolIndex = 1:numel(precoderBundle.ScheduledSymbols)
            symbol = double(precoderBundle.ScheduledSymbols(symbolIndex));
            W = precoderBundle.slice(prb,symbol);
            for sc = subcarriers
                physical = reshape(truePhysicalChannel(sc,symbol+1,:,:),nRx,nTx);
                hest(sc,symbol+1,:,:) = reshape(physical*W,1,1,nRx,nLayers);
            end
        end
    end
    projectionSource = "exact_runtime_physical_channel_times_frozen_precoder_slice";
end

[residual,pilotNMSE] = localFadingPilotResidual( ...
    grid,hest,plan.DMRSIndicesPerPort, ...
    referenceConfig.DMRSSymbolsPerPort,carrier,contract);
noiseVariance = double(receiver.NoiseVariance);
info = struct( ...
    "Method","ideal", ...
    "EngineUsed","ideal_true_channel_runtime_oracle", ...
    "ChannelModel",receiver.ChannelModel, ...
    "HestSize",double(size(hest)), ...
    "NoiseVar",noiseVariance, ...
    "ScalarFastPathUsed",false, ...
    "EstimatorUsesTrueChannel",true, ...
    "OracleTestMode",true, ...
    "PhysicalChannelSize",double(actual(1:4)), ...
    "EffectiveChannelProjectionSource",projectionSource, ...
    "InterpolationMethod","none_exact_per_resource", ...
    "EffectiveChannelConvention","H_physical_times_frozen_precoder", ...
    "PilotReconstructionNMSE",double(pilotNMSE), ...
    "PilotReconstructionNMSESource", ...
        "received_dmrs_minus_exact_effective_channel_times_known_dmrs");
end

function [hest,noiseVariance,info] = localEstimateFadingChannelPerPRG( ...
        grid,carrier,refInd,refSym,receiver,contract,bundle)
% Estimate the effective layer channel independently on each PRG.
%
% A frequency-selective precoder makes H_eff(k)=H_phys(k)W_prg(k)
% discontinuous at PRG boundaries.  Interpolating all DM-RS observations in
% one nrChannelEstimate invocation smooths across those discontinuities and
% creates a large, deterministic high-rank error floor.  The UE knows the
% scheduled PRG partition from the grant/precoder context, so run the same
% standards-backed estimator within each frozen PRG and stitch only that
% PRG's subcarriers into the effective-channel tensor.
if bundle.NLayerPorts ~= contract.NumLayers
    error("sixgr:pdsch:PDSCHReceiver:PrecoderLayerDimensionMismatch", ...
        "PRG-aware channel estimation requires one precoder layer port per scheduled layer.");
end
if bundle.NSymbolGroups ~= 1
    error("sixgr:pdsch:PDSCHReceiver:UnsupportedTimeSelectivePrecoderEstimate", ...
        "PRG-aware effective-channel estimation currently requires one " + ...
        "frozen symbol-group page. A time-selective precoder requires " + ...
        "DM-RS-bearing estimation in every symbol group.");
end
K = double(carrier.NSizeGrid)*12;
L = double(carrier.SymbolsPerSlot);
nRx = size(grid,3);
nLayers = double(contract.NumLayers);
planeSize = K*L;
hest = complex(zeros(K,L,nRx,nLayers,"like",grid));
coveredSubcarriers = false(K,1);
noiseValues = NaN(double(bundle.NPRG),1);
pilotCounts = zeros(double(bundle.NPRG),1);

for prgIndex = 1:double(bundle.NPRG)
    prbs = double(bundle.PRGToPRBMap{prgIndex}(:).');
    if isempty(prbs)
        error("sixgr:pdsch:PDSCHReceiver:EmptyPrecoderPRG", ...
            "Precoder PRG %d contains no scheduled PRBs.",prgIndex-1);
    end
    layerMasks = false(size(refInd));
    for layer = 1:nLayers
        zeroBased = double(refInd(:,layer)-1-planeSize*(layer-1));
        subcarrier = mod(zeroBased,K);
        layerMasks(:,layer) = ismember(floor(subcarrier/12),prbs);
    end
    counts = sum(layerMasks,1);
    if any(counts ~= counts(1)) || counts(1) == 0
        error("sixgr:pdsch:PDSCHReceiver:IncompletePRGDMRSEvidence", ...
            "Precoder PRG %d requires an equal nonzero DM-RS observation " + ...
            "count on every scheduled layer; observed %s.", ...
            prgIndex-1,mat2str(counts));
    end
    regionalInd = zeros(counts(1),nLayers);
    regionalSym = complex(zeros(counts(1),nLayers));
    for layer = 1:nLayers
        regionalInd(:,layer) = refInd(layerMasks(:,layer),layer);
        regionalSym(:,layer) = refSym(layerMasks(:,layer),layer);
    end
    [regionalH,regionalNoise] = localEstimateFadingChannelKernel( ...
        grid,carrier,regionalInd,regionalSym,receiver,contract, ...
        "sixgr.pdsch.PDSCHReceiver.strict_fading_prg_" + ...
        string(prgIndex-1));
    targetSubcarriers = reshape((12*prbs(:).'+(0:11).'),[],1);
    if any(targetSubcarriers < 0 | targetSubcarriers >= K)
        error("sixgr:pdsch:PDSCHReceiver:PrecoderPRGOutsideCarrier", ...
            "Precoder PRG %d lies outside the active carrier grid.",prgIndex-1);
    end
    hest(targetSubcarriers+1,:,:,:) = ...
        regionalH(targetSubcarriers+1,:,:,:);
    coveredSubcarriers(targetSubcarriers+1) = true;
    noiseValues(prgIndex) = double(regionalNoise);
    pilotCounts(prgIndex) = double(counts(1))*nLayers;
end
scheduledSubcarriers = false(K,1);
scheduledPRBs = double(bundle.PRBSet(:).');
scheduledSubcarrierIndex = reshape( ...
    (12*scheduledPRBs(:).'+(0:11).'),[],1);
scheduledSubcarriers(scheduledSubcarrierIndex+1) = true;
if any(scheduledSubcarriers & ~coveredSubcarriers) ...
        || any(~isfinite(noiseValues)) || any(pilotCounts <= 0)
    error("sixgr:pdsch:PDSCHReceiver:IncompletePRGChannelEstimate", ...
        "PRG-aware estimation did not cover every scheduled subcarrier.");
end
noiseVariance = sum(noiseValues.*pilotCounts)/sum(pilotCounts);
info = struct( ...
    "EngineUsed","nrChannelEstimate_prg_stitched", ...
    "HestSize",size(hest), ...
    "NoiseVar",double(noiseVariance), ...
    "ScalarFastPathUsed",false, ...
    "PRGAware",true, ...
    "PRGCount",double(bundle.NPRG), ...
    "PRGSet",localReceiverPRGSet(carrier,bundle), ...
    "PRGBundleSizeRB",double(bundle.PRGSize), ...
    "PRGPilotCounts",double(pilotCounts), ...
    "PrecoderBundleDigest",string(bundle.ImmutableBundleDigest), ...
    "InterpolationMethod", ...
        "independent_nrChannelEstimate_within_frozen_prg_boundaries");
end

function prgSet = localReceiverPRGSet(carrier,bundle)
% Return the standards-facing one-based PRG page assigned to every BWP PRB.
% Unscheduled PRBs remain zero; no page is inferred beyond the frozen
% precoder bundle carried by the grant.
prgSet = zeros(double(carrier.NSizeGrid),1);
for prgIndex = 1:double(bundle.NPRG)
    prbs = double(bundle.PRGToPRBMap{prgIndex}(:));
    if isempty(prbs) || any(prbs < 0 | prbs >= double(carrier.NSizeGrid)) ...
            || any(prgSet(prbs + 1) ~= 0)
        error("sixgr:pdsch:PDSCHReceiver:InvalidPrecoderPRGPartition", ...
            "The frozen precoder bundle contains an empty, overlapping, or out-of-BWP PRG page.");
    end
    prgSet(prbs + 1) = prgIndex;
end
if any(prgSet(double(bundle.PRBSet(:)) + 1) == 0)
    error("sixgr:pdsch:PDSCHReceiver:IncompletePrecoderPRGPartition", ...
        "The frozen precoder bundle does not map every scheduled PDSCH PRB to a PRG page.");
end
end

function [hest,noiseVariance,info] = localEstimateFadingChannelKernel( ...
        grid,carrier,refInd,refSym,receiver,contract,contextLabel)
[hest,noiseVariance,info] = sixgr.phy.rx.channelEstimate( ...
    carrier,grid,refInd,refSym, ...
    "CDMLengths",receiver.DMRSCDMLengths, ...
    "AveragingWindow",[0 0], ...
    "StrictMode",true, ...
    "ChannelModel",receiver.ChannelModel, ...
    "ExpectedTxPorts",contract.NumLayers, ...
    "ContextLabel",string(contextLabel), ...
    "Method","LS");
end

function [residual,nmse] = localFadingPilotResidual( ...
        grid,hest,indexCells,symbolCells,carrier,contract)
[logicalSymbols,unionIndices] = localRXLogicalReferences( ...
    indexCells,symbolCells,"dmrs",carrier,contract);
observed = localExtractPortSymbols(grid,unionIndices);
predicted = complex(zeros(size(observed)));
[~,symbols] = localRXCoordinates(unionIndices,carrier);
K = carrier.NSizeGrid*12;
subcarriers = mod(unionIndices,K);
for re = 1:numel(unionIndices)
    H = reshape(hest(subcarriers(re)+1,symbols(re)+1,:,:), ...
        size(grid,3),contract.NumLayers);
    predicted(:,re) = H*logicalSymbols(:,re);
end
residual = observed-predicted;
nmse = localNormalizedResidual(residual,observed);
end

function [layerValues,rxValues,equalizedGrid,info] = ...
        localEqualizeFadingResources(rxGrid,hest,indices, ...
        estimatedNoise,configuredNoise,numLayers,Rinterference, ...
        covarianceIncludesNoise)
noiseVariance = localEffectiveNoiseVariance( ...
    estimatedNoise,configuredNoise);
[rxValues,hValues] = nrExtractResources(indices+1,rxGrid,hest);
nResources = size(rxValues,1);
nRx = size(rxValues,2);
[disturbanceCovariance, covarianceInfo] = ...
    localRXDisturbanceCovariance(Rinterference, ...
    covarianceIncludesNoise, noiseVariance, nRx, nResources);
equalized = complex(zeros(nResources,numLayers));
postEqNoise = NaN(nResources,numLayers);
equalizerWeights = complex(NaN(nResources,numLayers,nRx));
effectiveResponse = complex(NaN(nResources,numLayers,numLayers));
desiredAccumulator = zeros(1,numLayers);
interferenceNoiseAccumulator = zeros(1,numLayers);
for resource = 1:nResources
    H = reshape(hValues(resource,:,:),nRx,numLayers);
    y = reshape(rxValues(resource,:),nRx,1);
    resourceCovariance = localRXCovarianceAtResource( ...
        disturbanceCovariance, resource, nRx);
    whitenedH = resourceCovariance\H;
    G = (H'*whitenedH + eye(numLayers))\whitenedH';
    A = G*H;
    for layer = 1:numLayers
        desiredGain = A(layer,layer);
        if ~(isfinite(real(desiredGain)) && isfinite(imag(desiredGain)) ...
                && abs(desiredGain) > sqrt(eps))
            error("sixgr:pdsch:PDSCHReceiver:FadingEqualizationFailed", ...
                "Layer-domain LMMSE equalization encountered a singular desired response.");
        end
        interferencePower = sum(abs(A(layer,:)).^2) ...
            - abs(desiredGain)^2;
        transformedNoisePower = real( ...
            G(layer,:)*resourceCovariance*G(layer,:)');
        interferenceNoisePower = max(0,real(interferencePower)) ...
            + max(0,real(transformedNoisePower));
        % The demapper consumes the unit-desired-gain result. Preserve the
        % exact composite row applied to y instead of reconstructing a
        % diagnostic weight from H after the receiver has completed.
        unitGainWeight = G(layer,:) ./ desiredGain;
        equalizerWeights(resource,layer,:) = reshape( ...
            unitGainWeight,1,1,nRx);
        effectiveResponse(resource,layer,:) = reshape( ...
            unitGainWeight*H,1,1,numLayers);
        equalized(resource,layer) = unitGainWeight*y;
        postEqNoise(resource,layer) = interferenceNoisePower ...
            / max(abs(desiredGain)^2,eps);
        desiredAccumulator(layer) = desiredAccumulator(layer) ...
            + abs(desiredGain)^2;
        interferenceNoiseAccumulator(layer) = ...
            interferenceNoiseAccumulator(layer) + interferenceNoisePower;
    end
end
if size(equalized,1) ~= numel(indices) ...
        || size(equalized,2) ~= numLayers ...
        || any(~isfinite(real(equalized(:)))) ...
        || any(~isfinite(imag(equalized(:)))) ...
        || any(~isfinite(postEqNoise(:))) || any(postEqNoise(:) < 0)
    error("sixgr:pdsch:PDSCHReceiver:FadingEqualizationFailed", ...
        "Unbiased layer-domain LMMSE equalization must produce one finite " + ...
        "symbol and noise variance per data RE and scheduled layer.");
end
sinrLinear = desiredAccumulator ./ max(interferenceNoiseAccumulator,eps);
measuredSINRdB = 10*log10(max(sinrLinear,realmin));
layerValues = equalized.';
rxValues = rxValues.';
equalizedGrid = complex(zeros(size(rxGrid,1),size(rxGrid,2),numLayers));
equalizedGrid = localMapEqualizedLayerResources( ...
    equalizedGrid,indices,layerValues);
info = struct( ...
    "EngineUsed",covarianceInfo.EngineUsed, ...
    "Domain","dmrs_estimated_effective_layer_channel", ...
    "PreEqualizationNoiseVariance",double(noiseVariance), ...
    "InterferenceCovarianceAvailable",logical(covarianceInfo.Available), ...
    "InterferenceCovarianceIncludesNoise",logical(covarianceInfo.IncludesNoise), ...
    "DisturbanceCovariance",disturbanceCovariance, ...
    "PostEqualizationNoiseVariancePerResourceLayer",double(postEqNoise), ...
    "MeasuredPostEqualizationSINRdBPerLayer",double(measuredSINRdB), ...
    "CSI",double(sinrLinear));
algorithmUsed = "MMSE";
if logical(covarianceInfo.Available)
    algorithmUsed = "MMSE-IRC";
end
perRESINRLinear = 1 ./ max(postEqNoise,eps);
info.EqualizerResult = struct( ...
    "ContractVersion","PDSCHResourceSelectiveEqualizerResult/v1", ...
    "AlgorithmUsed",algorithmUsed, ...
    "EngineUsed",string(covarianceInfo.EngineUsed), ...
    "Equation","s_hat_l=(G_l*y)/(G_l*H_l)", ...
    "SymbolCovarianceConvention","unit_layer_symbol_covariance", ...
    "EqualizedSymbols",equalized, ...
    "PostEqSINRLinear",double(perRESINRLinear), ...
    "PostEqSINRPerRE_dB",10.*log10(max(perRESINRLinear,eps)), ...
    "PerLayerSINR_dB",double(measuredSINRdB), ...
    "W",equalizerWeights, ...
    "EffectiveResponseWH",effectiveResponse, ...
    "CovarianceIncludesNoise",logical(covarianceIncludesNoise || isempty(Rinterference)), ...
    "NoiseAddedExactlyOnce",true, ...
    "PreEqualizationNoiseVariance",double(noiseVariance), ...
    "NRE",double(nResources), ...
    "NumRxAnt",double(nRx), ...
    "NumTxPorts",double(numLayers), ...
    "SolveCount",double(nResources), ...
    "UniqueSolveCount",double(nResources), ...
    "CovarianceFactorizationCount",double(nResources));
info.UniqueSolveCount = double(nResources);
info.SolveCount = double(nResources);
info.CovarianceFactorizationCount = double(nResources);
end

function [C, info] = localRXDisturbanceCovariance(Rinterference, ...
        includesNoise, noiseVariance, nRx, nResources)
info = struct("Available",false,"IncludesNoise",false, ...
    "PerRE",false, ...
    "EngineUsed","explicit_unbiased_layer_domain_lmmse");
if isempty(Rinterference)
    C = max(double(noiseVariance),eps)*eye(nRx);
    return;
end
R = double(Rinterference);
isStatic = ismatrix(R) && size(R,1) == nRx && size(R,2) == nRx;
isPerRE = ndims(R) == 3 && size(R,1) == nResources && ...
    size(R,2) == nRx && size(R,3) == nRx;
if ~(isStatic || isPerRE) || any(~isfinite(real(R(:)))) ...
        || any(~isfinite(imag(R(:))))
    error("sixgr:pdsch:PDSCHReceiver:InvalidInterferenceCovariance", ...
        ['Interference covariance must be a finite NRx-by-NRx matrix or ' ...
         'an NRE-by-NRx-by-NRx tensor aligned to the PDSCH data REs.']);
end
if isStatic
    C = localPrepareRXCovariance(R, includesNoise, noiseVariance, nRx);
else
    C = complex(zeros(size(R)));
    for resource = 1:nResources
        C(resource,:,:) = localPrepareRXCovariance( ...
            squeeze(R(resource,:,:)), includesNoise, noiseVariance, nRx);
    end
end
info.Available = true;
info.IncludesNoise = logical(includesNoise);
info.PerRE = logical(isPerRE);
if isPerRE
    info.EngineUsed = "explicit_unbiased_layer_domain_per_re_lmmse_irc";
else
    info.EngineUsed = "explicit_unbiased_layer_domain_lmmse_irc";
end
end

function C = localPrepareRXCovariance(R, includesNoise, noiseVariance, nRx)
R = (R + R')/2;
if logical(includesNoise)
    C = R;
else
    C = R + max(double(noiseVariance),0)*eye(nRx);
end
[V,D] = eig(C,"vector");
floorValue = max(eps(max(1,norm(C,"fro"))),eps);
D = max(real(D),floorValue);
C = V*diag(D)*V';
C = (C + C')/2;
end

function C = localRXCovarianceAtResource(covariance, resource, nRx)
if ismatrix(covariance)
    C = covariance;
else
    C = reshape(covariance(resource,:,:),nRx,nRx);
end
end

function info = localUnavailablePDSCHResidual(kind,numLayers)
info = struct( ...
    "Available",false, ...
    "Applied",false, ...
    "Kind",char(string(kind)), ...
    "Source",char("post_equalization_" + string(kind) + "_unavailable"), ...
    "Status","unavailable", ...
    "NAReason","not_enabled_or_not_computed", ...
    "NoiseVariancePerLayer",NaN(1,double(numLayers)), ...
    "SINRdBPerLayer",NaN(1,double(numLayers)), ...
    "SampleCountPerLayer",zeros(1,double(numLayers)), ...
    "RawEqualizerSINRdBPerLayer",NaN(1,double(numLayers)));
end

function info = localEstimatePDSCHDMRSPostEqResidual( ...
        rxGrid,hest,plan,referenceConfig,carrier,contract, ...
        estimatedNoise,configuredNoise,Rinterference,covarianceIncludesNoise)
info = localUnavailablePDSCHResidual("dmrs_residual",contract.NumLayers);
if ndims(Rinterference) == 3
    % A data-RE covariance tensor has no implied coordinate mapping to the
    % DM-RS REs. Reusing it by row order or averaging would fabricate a
    % receiver quantity, so leave this optional bound explicitly unavailable.
    info.NAReason = "data_re_covariance_not_defined_on_dmrs_re";
    return;
end
try
    [logicalDMRS,unionIndices] = localRXLogicalReferences( ...
        plan.DMRSIndicesPerPort,referenceConfig.DMRSSymbolsPerPort, ...
        "dmrs",carrier,contract);
    [equalizedDMRS,~,~,~] = localEqualizeFadingResources( ...
        rxGrid,hest,unionIndices,estimatedNoise,configuredNoise, ...
        contract.NumLayers,Rinterference,covarianceIncludesNoise);
catch ME
    info.NAReason = char("dmrs_post_equalization_failed:" + string(ME.identifier));
    return;
end
noise = NaN(1,contract.NumLayers);
sinr = NaN(1,contract.NumLayers);
counts = zeros(1,contract.NumLayers);
for layer = 1:contract.NumLayers
    active = abs(logicalDMRS(layer,:)) > 0;
    valid = active & isfinite(real(logicalDMRS(layer,:))) ...
        & isfinite(imag(logicalDMRS(layer,:))) ...
        & isfinite(real(equalizedDMRS(layer,:))) ...
        & isfinite(imag(equalizedDMRS(layer,:)));
    if ~any(valid)
        continue;
    end
    reference = logicalDMRS(layer,valid);
    received = equalizedDMRS(layer,valid);
    referencePower = mean(abs(reference).^2,"omitnan");
    residualPower = mean(abs(received-reference).^2,"omitnan");
    if isfinite(referencePower) && referencePower > 0 ...
            && isfinite(residualPower) && residualPower >= 0
        noise(layer) = max(residualPower/referencePower,eps);
        sinr(layer) = 10*log10(1/noise(layer));
        counts(layer) = nnz(valid);
    end
end
if ~any(isfinite(noise))
    info.NAReason = "no_finite_active_layer_dmrs_pairs";
    return;
end
info.Available = true;
info.Source = "canonical_pdsch_dmrs_post_equalization_residual";
info.Status = "OK";
info.NAReason = "";
info.NoiseVariancePerLayer = double(noise);
info.SINRdBPerLayer = double(sinr);
info.SampleCountPerLayer = double(counts);
end

function info = localEstimatePDSCHDecisionDirectedPostEqResidual( ...
        layerValues,contract)
info = localUnavailablePDSCHResidual( ...
    "decision_directed",contract.NumLayers);
noise = NaN(1,contract.NumLayers);
sinr = NaN(1,contract.NumLayers);
counts = zeros(1,contract.NumLayers);
firstLayer = 1;
for codeword = 1:contract.NumCodewords
    constellation = localPDSCHDecisionConstellation( ...
        contract.Modulation(codeword));
    lastLayer = firstLayer + contract.LayerCount(codeword) - 1;
    if isempty(constellation)
        firstLayer = lastLayer + 1;
        continue;
    end
    for layer = firstLayer:lastLayer
        received = reshape(layerValues(layer,:),[],1);
        valid = isfinite(real(received)) & isfinite(imag(received));
        received = received(valid);
        if isempty(received)
            continue;
        end
        % Bound peak memory for wide allocations and high-order QAM.  The
        % decision remains an exact nearest-neighbour decision; chunking
        % only changes how the distance matrix is materialized.
        nearest = complex(zeros(size(received)));
        chunkSize = max(1,floor(2^20/max(numel(constellation),1)));
        for first = 1:chunkSize:numel(received)
            last = min(numel(received),first+chunkSize-1);
            distance = abs(received(first:last) - ...
                reshape(constellation,1,[])).^2;
            [~,nearestIndex] = min(distance,[],2);
            nearest(first:last) = constellation(nearestIndex);
        end
        referencePower = mean(abs(nearest).^2,"omitnan");
        residualPower = mean(abs(received-nearest).^2,"omitnan");
        if isfinite(referencePower) && referencePower > 0 ...
                && isfinite(residualPower) && residualPower >= 0
            noise(layer) = max(residualPower/referencePower,eps);
            sinr(layer) = 10*log10(1/noise(layer));
            counts(layer) = numel(received);
        end
    end
    firstLayer = lastLayer + 1;
end
if ~any(isfinite(noise))
    info.NAReason = "no_finite_equalized_symbols_for_supported_modulation";
    return;
end
info.Available = true;
info.Source = "canonical_pdsch_decision_directed_post_equalization_residual";
info.Status = "OK";
info.NAReason = "";
info.NoiseVariancePerLayer = double(noise);
info.SINRdBPerLayer = double(sinr);
info.SampleCountPerLayer = double(counts);
end

function constellation = localPDSCHDecisionConstellation(modulation)
constellation = complex([]);
token = upper(strrep(strrep(char(string(modulation)),"-","")," ",""));
switch token
    case "QPSK"
        qm = 2;
    case "16QAM"
        qm = 4;
    case "64QAM"
        qm = 6;
    case "256QAM"
        qm = 8;
    case "1024QAM"
        qm = 10;
    otherwise
        return;
end
M = 2^qm;
bits = zeros(M*qm,1,"int8");
for symbol = 0:M-1
    offset = symbol*qm;
    for bit = 1:qm
        bits(offset+bit) = int8(bitget(uint32(symbol),qm-bit+1));
    end
end
try
    constellation = complex(nrSymbolModulate(bits,token));
catch
    constellation = complex([]);
end
end

function [sinrPerLayer,noisePerResourceLayer,info] = ...
        localApplyPDSCHResidualBound(sinrPerLayer,noisePerResourceLayer,info)
if ~logical(info.Available)
    return;
end
raw = double(sinrPerLayer(:).');
unbounded = raw;
boundSINR = double(info.SINRdBPerLayer(:).');
boundNoise = double(info.NoiseVariancePerLayer(:).');
if numel(raw) ~= numel(boundSINR) ...
        || size(noisePerResourceLayer,2) ~= numel(boundNoise)
    error("sixgr:pdsch:PDSCHReceiver:ResidualBoundLayerMismatch", ...
        "Post-equalization residual evidence must match the scheduled layer count.");
end
applied = false(size(raw));
for layer = 1:numel(raw)
    if isfinite(boundSINR(layer)) ...
            && (~isfinite(raw(layer)) || boundSINR(layer) < raw(layer))
        raw(layer) = boundSINR(layer);
        applied(layer) = true;
    end
    if isfinite(boundNoise(layer)) && boundNoise(layer) > 0
        noisePerResourceLayer(:,layer) = max( ...
            double(noisePerResourceLayer(:,layer)),boundNoise(layer));
    end
end
sinrPerLayer = double(raw);
info.Applied = any(applied);
info.AppliedPerLayer = logical(applied);
info.RawEqualizerSINRdBPerLayer = double(unbounded);
if info.Applied
    info.Status = "OK_BOUND_APPLIED";
end
end

function [layerValues,info] = localPTRSCorrectionLayers( ...
        layerValues,dataSymbols,rxGrid,hest,indices,expected, ...
        carrier,estimatedNoise,configuredNoise)
cpe = zeros(carrier.SymbolsPerSlot,1);
observations = zeros(carrier.SymbolsPerSlot,1);
if isempty(indices)
    info = localDisabledPTRSCorrectionInfo(carrier, "disabled_no_ptrs");
    return;
end
noiseVariance = localEffectiveNoiseVariance( ...
    estimatedNoise,configuredNoise);
[received,hValues] = nrExtractResources(indices+1,rxGrid,hest);
[equalized,~] = nrEqualizeMMSE(received,hValues,noiseVariance);
equalized = equalized.';
[~,ptrsSymbols] = localRXCoordinates(indices,carrier);
for symbol = unique(ptrsSymbols,"stable")
    selected = ptrsSymbols == symbol;
    reference = expected(:,selected);
    observed = equalized(:,selected);
    active = abs(reference) > 0;
    if any(active(:))
        phasor = sum(observed(active).*conj(reference(active)));
        cpe(symbol+1) = angle(phasor);
        observations(symbol+1) = nnz(active);
        dataMask = dataSymbols == symbol;
        layerValues(:,dataMask) = layerValues(:,dataMask) ...
            .* exp(-1j*cpe(symbol+1));
    end
end
active = observations > 0;
info = struct("Enabled",true,"Applied",any(active),"CPEPerSymbolRad",cpe, ...
    "ObservationCountPerSymbol",observations, ...
    "CorrectedSymbolCount",double(nnz(active)), ...
    "MeanCPE_deg",localMeanPTRSCPE(cpe, active), ...
    "Status","explicit_ptrs_cpe_corrected_after_mimo_equalization", ...
    "NAReason","");
end

function grid = localMapEqualizedLayerResources(grid,indices,values)
if size(values,2) ~= numel(indices) ...
        || size(values,1) ~= size(grid,3)
    error("sixgr:pdsch:PDSCHReceiver:EqualizedResourceShapeMismatch", ...
        "Equalized layer values do not match the target resource grid.");
end
for layer = 1:size(grid,3)
    plane = grid(:,:,layer);
    plane(indices+1) = values(layer,:);
    grid(:,:,layer) = plane;
end
end

function value = localEffectiveNoiseVariance(estimated,configured)
value = double(estimated);
if ~isempty(configured)
    value = double(configured);
end
if ~(isscalar(value) && isfinite(value) && value >= 0)
    error("sixgr:pdsch:PDSCHReceiver:InvalidNoiseEstimate", ...
        "Equalization requires a finite nonnegative grid noise variance.");
end
value = max(value,eps);
end

function nmse = localNormalizedResidual(residual,observed)
numerator = sum(abs(residual(:)).^2);
denominator = sum(abs(observed(:)).^2);
nmse = numerator/max(denominator,eps);
if ~(isscalar(nmse) && isfinite(nmse) && nmse >= 0)
    error("sixgr:pdsch:PDSCHReceiver:InvalidPilotResidual", ...
        "DM-RS reconstruction residual must be finite and nonnegative.");
end
end

function grid = localApplyPortChannelInverse(grid,gain)
for port = 1:size(grid,3)
    grid(:,:,port) = grid(:,:,port)/gain(port);
end
end

function [grid,info] = localPTRSCorrection(grid,indices,expected,carrier)
cpe = zeros(carrier.SymbolsPerSlot,1);
observations = zeros(carrier.SymbolsPerSlot,1);
if isempty(indices)
    info = localDisabledPTRSCorrectionInfo(carrier, "disabled_no_ptrs");
    return;
end
observed = localExtractPortSymbols(grid,indices);
[~,symbols] = localRXCoordinates(indices,carrier);
for symbol = unique(symbols,"stable")
    selected = symbols == symbol;
    reference = expected(:,selected);
    received = observed(:,selected);
    active = abs(reference) > 0;
    if any(active(:))
        phasor = sum(received(active).*conj(reference(active)));
        cpe(symbol+1) = angle(phasor);
        observations(symbol+1) = nnz(active);
        grid(:,symbol+1,:) = grid(:,symbol+1,:) .* exp(-1j*cpe(symbol+1));
    end
end
active = observations > 0;
info = struct("Enabled",true,"Applied",any(active),"CPEPerSymbolRad",cpe, ...
    "ObservationCountPerSymbol",observations, ...
    "CorrectedSymbolCount",double(nnz(active)), ...
    "MeanCPE_deg",localMeanPTRSCPE(cpe, active), ...
    "Status","explicit_ptrs_cpe_corrected", ...
    "NAReason","");
end

function info = localDisabledPTRSCorrectionInfo(carrier, reason)
info = struct("Enabled",false,"Applied",false, ...
    "CPEPerSymbolRad",zeros(carrier.SymbolsPerSlot,1), ...
    "ObservationCountPerSymbol",zeros(carrier.SymbolsPerSlot,1), ...
    "CorrectedSymbolCount",0,"MeanCPE_deg",NaN, ...
    "Status",char(string(reason)),"NAReason",char(string(reason)));
end

function value = localMeanPTRSCPE(cpe, active)
value = NaN;
if any(active)
    value = rad2deg(mean(abs(double(cpe(active))), "omitnan"));
end
end

function values = localExtractPortSymbols(grid,indices)
values = complex(zeros(size(grid,3),numel(indices)));
for port = 1:size(grid,3)
    plane = grid(:,:,port);
    values(port,:) = plane(indices+1);
end
end

function [prb,symbol] = localRXCoordinates(indices,carrier)
K = carrier.NSizeGrid*12;
indices = double(indices(:).');
subcarrier = mod(indices,K);
symbol = floor(indices/K);
prb = floor(subcarrier/12);
if any(symbol < 0 | symbol >= carrier.SymbolsPerSlot)
    error("sixgr:pdsch:PDSCHReceiver:ResourceIndexOutsideGrid", ...
        "A resource-plan index lies outside the carrier grid.");
end
end

function [blocks,pass] = localDecodedResults(decode,count)
if count == 1
    blocks = {int8(decode.TransportBlock(:))};
    pass = logical(decode.CRCPass);
else
    if ~isfield(decode,"Codewords") || numel(decode.Codewords) ~= count
        error("sixgr:pdsch:PDSCHReceiver:DLSCHDecodeContractMismatch", ...
            "Explicit multi-codeword decoder output is incomplete.");
    end
    blocks = cell(1,count);
    pass = false(1,count);
    for idx = 1:count
        blocks{idx} = int8(decode.Codewords{idx}.TransportBlock(:));
        pass(idx) = logical(decode.Codewords{idx}.CRCPass);
    end
end
end

function results = localProcessHARQ(manager,assignment,plans,decode,receiver,crcPass)
if isempty(manager)
    results = cell(1,0);
    return;
end
raw = receiver.Raw;
required = ["NewDataPerCodeword","TBIdentityDigestPerCodeword"];
missing = required(~isfield(raw,required));
if ~isempty(missing)
    error("sixgr:pdsch:PDSCHReceiver:IncompleteHARQReceiverConfig", ...
        "HARQ manager use requires receiver fields: %s.", ...
        strjoin(cellstr(missing),", "));
end
newData = logical(localRXNumeric( ...
    raw.NewDataPerCodeword,numel(plans),"NewDataPerCodeword"));
identity = localRXStrings( ...
    raw.TBIdentityDigestPerCodeword,numel(plans), ...
    "TBIdentityDigestPerCodeword");
results = cell(1,numel(plans));
for cw = 1:numel(plans)
    if numel(plans) == 1
        decoded = decode;
    else
        decoded = decode.Codewords{cw};
    end
    recovered = double(decoded.RateRecoveredLLR);
    valid = isfinite(recovered);
    nref = plans{cw}.Nref;
    if isempty(nref), nref = plans{cw}.Ncb; end
    ndi = localRXNumeric(assignment.get("NDIPerCodeword"), ...
        numel(plans),"NDIPerCodeword");
    observation = struct( ...
        "UEId",double(assignment.get("UEId")), ...
        "ServingCellId",double(assignment.get("ServingCellId")), ...
        "SchedulingCellId",double(assignment.get("SchedulingCellId")), ...
        "CCId",double(assignment.get("CCId")), ...
        "BWPId",double(assignment.get("BWPId")), ...
        "HARQProcessId",double(assignment.get("HARQProcessId")), ...
        "CodewordIndex",cw-1, ...
        "ConfigurationEpoch",double(assignment.get("ConfigurationEpoch")), ...
        "NDI",ndi(cw), ...
        "NewData",newData(cw), ...
        "RV",double(plans{cw}.RV), ...
        "TBIdentityDigest",identity(cw), ...
        "TBS",double(plans{cw}.TransportBlockSize), ...
        "CodingPlanDigest",string(plans{cw}.CodingLayoutHash), ...
        "BaseGraph",double(plans{cw}.BaseGraph), ...
        "LiftingSize",double(plans{cw}.LiftingSize), ...
        "CodeBlockLayout",plans{cw}.toCodingLayout(), ...
        "FillerPositions",{plans{cw}.FillerPositionsZeroBased}, ...
        "Ncb",double(plans{cw}.Ncb), ...
        "Nref",double(nref), ...
        "RateRecoveredLLR",recovered, ...
        "ValidPositionMask",valid, ...
        "DecodeOK",logical(crcPass(cw)));
    [~,results{cw}] = manager.process(observation);
end
end

function trace = localRXIdentityTrace(prb,symbol,domain,rank)
count = numel(prb);
resourceIndex = (0:count-1).';
PRB = prb(:);
Symbol = symbol(:);
PRG = zeros(count,1);
SymbolGroup = zeros(count,1);
Domain = repmat(string(domain),count,1);
Operation = repmat("deapply",count,1);
ResolvedMatrixDigest = repmat("identity_rank_"+string(rank),count,1);
AppliedMatrixDigest = ResolvedMatrixDigest;
trace = table(resourceIndex,PRB,Symbol,PRG,SymbolGroup,Domain, ...
    Operation,ResolvedMatrixDigest,AppliedMatrixDigest, ...
    'VariableNames', {'ResourceIndex','PRB','Symbol','PRG','SymbolGroup', ...
    'Domain','Operation','ResolvedMatrixDigest','AppliedMatrixDigest'});
end

function layerNoise = localAWGNLayerNoiseVariance( ...
        preEqualizationNoise,gain,bundle,prb,symbol,numLayers)
% Convert grid-domain noise through the exact AWGN inverse/deprecoder path.
preEqualizationNoise = double(preEqualizationNoise);
gain = complex(double(gain(:)));
if ~(isscalar(preEqualizationNoise) && isfinite(preEqualizationNoise) ...
        && preEqualizationNoise >= 0) ...
        || any(~isfinite(real(gain)) | ~isfinite(imag(gain)) ...
        | abs(gain) <= eps)
    error("sixgr:pdsch:PDSCHReceiver:InvalidAWGNNoiseTransform", ...
        "AWGN post-equalization noise conversion requires finite noise and channel gains.");
end
portNoise = preEqualizationNoise./abs(gain).^2;
if isempty(bundle)
    if numel(portNoise) ~= numLayers
        error("sixgr:pdsch:PDSCHReceiver:AWGNNoiseLayerMismatch", ...
            "Identity AWGN noise conversion requires one physical port per layer.");
    end
    layerNoise = reshape(portNoise,1,[]);
    return;
end
if bundle.NPhysicalTxAntennas ~= numel(portNoise) ...
        || bundle.NLayerPorts ~= numLayers ...
        || numel(prb) ~= numel(symbol) || isempty(prb)
    error("sixgr:pdsch:PDSCHReceiver:AWGNNoisePrecoderMismatch", ...
        "AWGN noise conversion does not match the resolved precoder resources.");
end
accumulator = zeros(1,numLayers);
for resource = 1:numel(prb)
    page = bundle.slice(prb(resource),symbol(resource));
    inverse = page\eye(size(page,1));
    covariance = inverse*diag(portNoise)*inverse';
    accumulator = accumulator + real(diag(covariance)).';
end
layerNoise = accumulator/numel(prb);
if any(~isfinite(layerNoise) | layerNoise < 0)
    error("sixgr:pdsch:PDSCHReceiver:InvalidAWGNLayerNoise", ...
        "The exact inverse/deprecoder transform produced invalid layer noise.");
end
end

function metrics = localStrictMetrics(plan,dmrsIndices,ptrsIndices, ...
        layerSymbols,codewordSymbols,scrambledLLR,descrambledLLR, ...
        decode,contract,noiseVariance,crcPass,receiverConfig, ...
        channelGain,pilotReconstructionNMSE,measuredSINRPerLayer)
safeNoise = max(double(noiseVariance),eps);
if isempty(measuredSINRPerLayer)
    sinrPerLayer = zeros(1,contract.NumLayers);
    for layer = 1:contract.NumLayers
        sinrPerLayer(layer) = 10*log10( ...
            mean(abs(layerSymbols(:,layer)).^2)/safeNoise);
    end
else
    sinrPerLayer = double(measuredSINRPerLayer(:).');
    if numel(sinrPerLayer) ~= contract.NumLayers ...
            || any(~isfinite(sinrPerLayer))
        error("sixgr:pdsch:PDSCHReceiver:InvalidMeasuredSINR", ...
            "Receiver-derived post-equalization SINR must contain one " + ...
            "finite value per scheduled layer.");
    end
end
evmPerCodeword = zeros(1,contract.NumCodewords);
rateRecoveredCount = zeros(1,contract.NumCodewords);
iterations = zeros(1,contract.NumCodewords);
for cw = 1:contract.NumCodewords
    hardBits = sixgr.pdsch.PDSCHModulator(codewordSymbols{cw}, ...
        contract.Modulation(cw),"Operation","hard-demap");
    remodulated = sixgr.pdsch.PDSCHModulator( ...
        hardBits,contract.Modulation(cw));
    denominator = max(mean(abs(remodulated).^2),eps);
    evmPerCodeword(cw) = sqrt(mean(abs( ...
        codewordSymbols{cw}(:)-remodulated(:)).^2)/denominator);
    if contract.NumCodewords == 1
        decoded = decode;
    else
        decoded = decode.Codewords{cw};
    end
    rateRecoveredCount(cw) = numel(decoded.RateRecoveredLLR);
    iterations(cw) = mean(double(decoded.ActiveIterations(:)),"omitnan");
end
channelNMSE = double(pilotReconstructionNMSE);
channelNMSESource = ...
    "dmrs_pilot_reconstruction_residual_not_true_channel_oracle";
if isfield(receiverConfig,"ReferenceChannelGain") ...
        && ~isempty(receiverConfig.ReferenceChannelGain)
    truthGain = complex(double(receiverConfig.ReferenceChannelGain(:)));
    if numel(truthGain) ~= numel(channelGain)
        error("sixgr:pdsch:PDSCHReceiver:ReferenceChannelShapeMismatch", ...
            "ReferenceChannelGain must contain one value per physical port.");
    end
    channelNMSE = sum(abs(channelGain-truthGain).^2) ...
        / max(sum(abs(truthGain).^2),eps);
    channelNMSESource = ...
        "explicit_awgn_reference_gain_test_contract";
end
metrics = struct( ...
    "DataRECount",double(plan.ExactDataRECount), ...
    "DMRSRECount",double(numel(dmrsIndices)), ...
    "PTRSRECount",double(numel(ptrsIndices)), ...
    "ChannelEstimateNMSE",double(channelNMSE), ...
    "ChannelEstimateNMSESource",channelNMSESource, ...
    "MeasuredPostEqualizationSINRdBPerLayer",sinrPerLayer, ...
    "EVMPerCodeword",evmPerCodeword, ...
    "ScrambledLLRCountPerCodeword",cellfun(@numel,scrambledLLR), ...
    "DescrambledLLRCountPerCodeword",cellfun(@numel,descrambledLLR), ...
    "FiniteDescrambledLLRCountPerCodeword", ...
        cellfun(@(x) nnz(isfinite(x)),descrambledLLR), ...
    "RateRecoveredBitCountPerCodeword",rateRecoveredCount, ...
    "LDPCIterationCountPerCodeword",iterations, ...
    "BERPerCodeword",NaN(1,contract.NumCodewords), ...
    "BLERPerCodeword",double(~crcPass), ...
    "TBCRCPassPerCodeword",logical(crcPass), ...
    "BERStatus","unavailable_without_external_decoded_bit_reference");
end

function values = localRXNumeric(raw,count,name)
values = double(raw(:).');
if numel(values) ~= count || any(~isfinite(values))
    error("sixgr:pdsch:PDSCHReceiver:CodewordParameterMismatch", ...
        "%s must contain one finite value per codeword.",name);
end
end

function values = localRXStrings(raw,count,name)
values = reshape(string(raw),1,[]);
if numel(values) ~= count || any(strlength(strtrim(values)) == 0)
    error("sixgr:pdsch:PDSCHReceiver:CodewordParameterMismatch", ...
        "%s must contain one nonempty value per codeword.",name);
end
end

function qm = localRXQm(modulation)
switch upper(erase(string(modulation)," "))
    case "QPSK", qm = 2;
    case "16QAM", qm = 4;
    case "64QAM", qm = 6;
    case "256QAM", qm = 8;
    case "1024QAM", qm = 10;
    otherwise
        error("sixgr:pdsch:PDSCHReceiver:UnsupportedModulation", ...
            "Unsupported PDSCH modulation '%s'.",modulation);
end
end

function cells = localRXOptional(raw,count)
if isempty(raw)
    cells = repmat({[]},1,count);
    return;
end
raw = double(raw(:).');
if isscalar(raw), raw = repmat(raw,1,count); end
if numel(raw) ~= count || any(~isfinite(raw)) ...
        || any(raw <= 0 | raw ~= fix(raw))
    error("sixgr:pdsch:PDSCHReceiver:CodewordParameterMismatch", ...
        "Nref must be empty or one positive integer per codeword.");
end
cells = num2cell(raw);
end

function value = localRXUnwrapOne(cells)
if numel(cells) == 1
    value = cells{1};
else
    value = cells;
end
end
