function rx = PDSCHReceiver(rxWaveform, assignment, resourcePlan, varargin)
%PDSCHRECEIVER Execute the canonical assignment-owned PDSCH receiver.
%   RX = PDSCHReceiver(WAVEFORM,ASSIGNMENT,RESOURCEPLAN,CARRIER, ...
%       REFERENCECONFIG,RECEIVERCONFIG,Name,Value,...)
% Configuration structs, TX copies, transmitted bits, CRC outcomes, and
% transmitter intermediates are not accepted at this RX trust boundary.
rx = localStrictReceiver(rxWaveform, assignment, resourcePlan, varargin{:});
end

function rx = localStrictReceiver(rxWaveform, assignment, resourcePlan, varargin)
if ~isa(resourcePlan, "sixgr.pdsch.PDSCHResourcePlan")
    error("sixgr:pdsch:PDSCHReceiver:MissingResourcePlan", ...
        "Strict PDSCH RX requires an immutable PDSCHResourcePlan.");
end
assignment.validateForExecution();
if numel(varargin) < 3
    error("sixgr:pdsch:PDSCHReceiver:IncompleteStrictSignature", ...
        ["Strict PDSCH RX requires carrier, referenceConfig, and " ...
        "receiverConfig after the resource plan."]);
end
carrier = varargin{1};
referenceConfig = varargin{2};
receiverConfig = varargin{3};
nv = varargin(4:end);
if ~isa(carrier, "nrCarrierConfig")
    error("sixgr:pdsch:PDSCHReceiver:InvalidCarrier", ...
        "Strict PDSCH RX requires an explicit nrCarrierConfig.");
end
localRXValidateCarrierSymbolBoundary(assignment, carrier);
if ~isa(referenceConfig, ...
        "sixgr.pdsch.PDSCHReferenceSignalConfig")
    error("sixgr:pdsch:PDSCHReceiver:MissingImmutableReferenceConfiguration", ...
        "Strict PDSCH RX requires PDSCHReferenceSignalConfig.");
end
referenceConfig.validateForExecution();
referenceData = referenceConfig.toStruct();
referenceSignals = sixgr.pdsch.PDSCHReferenceSignalGenerator.generate( ...
    assignment,resourcePlan,carrier,referenceConfig);
referenceRuntime = referenceData;
referenceRuntime.DMRSSymbolsPerPort = ...
    referenceSignals.DMRSSymbolsPerPort;
referenceRuntime.PTRSSymbolsPerPort = ...
    referenceSignals.PTRSSymbolsPerPort;
referenceRuntime.DMRSCDMLengths = double( ...
    referenceSignals.MaterializedPDSCH.DMRS.CDMLengths);

ip = inputParser;
ip.FunctionName = "sixgr.pdsch.PDSCHReceiver strict path";
ip.addParameter("CodingPlans", [], ...
    @(x) isempty(x) || isa(x, "sixgr.pdsch.DLSCHCodingPlan") ...
        || iscell(x));
ip.addParameter("PrecoderBundle", [], ...
    @(x) isempty(x) || isa(x, "sixgr.pdsch.PDSCHPrecoderBundle"));
ip.addParameter("IntegrationContext", struct(), ...
    @(x) isstruct(x) && isscalar(x));
ip.addParameter("HARQManager", [], ...
    @(x) isempty(x) || isa(x, "sixgr.pdsch.PDSCHHARQManager"));
ip.addParameter("PriorRecoveredLLR", [], ...
    @(x) isempty(x) || isnumeric(x) || islogical(x) || ...
        isstruct(x) || iscell(x));
ip.addParameter("PriorCodingPlan", [], ...
    @(x) isempty(x) || isstruct(x) || iscell(x) || ...
        isa(x, "sixgr.pdsch.DLSCHCodingPlan"));
ip.addParameter("HARQKey", "", @(x) ischar(x) || isstring(x));
ip.parse(nv{:});
opt = ip.Results;

integrationBinding = localRXResolveIntegrationBinding( ...
    assignment, opt.IntegrationContext, opt.PrecoderBundle);
if ~(isnumeric(rxWaveform) && ismatrix(rxWaveform) ...
        && ~isempty(rxWaveform) && all(isfinite(real(rxWaveform(:)))) ...
        && all(isfinite(imag(rxWaveform(:)))))
    error("sixgr:pdsch:PDSCHReceiver:InvalidWaveform", ...
        "Received waveform must be a nonempty finite numeric matrix.");
end
if ~any(abs(rxWaveform(:)) > 0)
    error("sixgr:pdsch:PDSCHReceiver:NoReceivedSignal", ...
        "Strict PDSCH reception rejects an all-zero received waveform.");
end

[contract, receiver] = localStrictContract( ...
    assignment, resourcePlan, referenceRuntime, receiverConfig);
plans = localRXCodingPlans( ...
    opt.CodingPlans, contract, resourcePlan, receiver);
[rxGrid, ofdmInfo] = sixgr.phy.waveform.ofdmDemodulate( ...
    carrier, rxWaveform, referenceRuntime.OFDMOptions{:});
if size(rxGrid, 3) ~= receiver.NPhysicalRxAntennas
    error("sixgr:pdsch:PDSCHReceiver:ReceivePortCountMismatch", ...
        "OFDM grid has %d ports; receiver config requires %d.", ...
        size(rxGrid,3), receiver.NPhysicalRxAntennas);
end

[expectedDMRS, dmrsIndices] = localRXReferencePorts( ...
    resourcePlan.DMRSIndicesPerPort, ...
    referenceRuntime.DMRSSymbolsPerPort, "dmrs", opt.PrecoderBundle, ...
    carrier, contract, receiver);
if isempty(dmrsIndices)
    error("sixgr:pdsch:PDSCHReceiver:MissingDMRSReference", ...
        "Strict PDSCH reception requires explicit DM-RS evidence.");
end
[dataPRB, dataSymbol] = localRXCoordinates(resourcePlan.DataIndices, carrier);
if receiver.IsResourceSelective
    [channelGain, estimatedNoiseVariance, dmrsResidual, ...
        channelEstimationInfo, channelEstimateNMSE] = ...
        localEstimateFadingChannel(rxGrid, resourcePlan, ...
        referenceRuntime, carrier, contract, receiver);
    [layerValues, dataPortSymbols, equalizedGrid, equalizationInfo] = ...
        localEqualizeFadingResources(rxGrid, channelGain, ...
        resourcePlan.DataIndices, estimatedNoiseVariance, ...
        receiver.NoiseVariance, contract.NumLayers);
    [expectedPTRS, ptrsIndices] = localRXLogicalReferences( ...
        resourcePlan.PTRSIndicesPerPort, ...
        referenceRuntime.PTRSSymbolsPerPort, "ptrs", ...
        carrier, contract);
    [layerValues, ptrsInfo] = localPTRSCorrectionLayers( ...
        layerValues, dataSymbol, rxGrid, channelGain, ...
        ptrsIndices, expectedPTRS, carrier, ...
        estimatedNoiseVariance, receiver.NoiseVariance);
    equalizedGrid = localMapEqualizedLayerResources( ...
        equalizedGrid, resourcePlan.DataIndices, layerValues);
    deprecoderTrace = localRXIdentityTrace( ...
        dataPRB, dataSymbol, ...
        "estimated_effective_layer_channel", contract.NumLayers);
    channelEstimationMode = "dmrs_nr_channel_estimate_per_resource";
    channelEstimateScope = ...
        "dmrs_backed_resource_selective_effective_layer_channel";
else
    [channelGain, estimatedNoiseVariance, dmrsResidual] = ...
        localEstimateAWGNChannel(rxGrid, dmrsIndices, expectedDMRS);
    channelEstimationInfo = struct( ...
        "EngineUsed","explicit_awgn_scalar_per_physical_port_ls", ...
        "ChannelModel","AWGN", ...
        "HestSize",size(channelGain), ...
        "EstimatorUsesTrueChannel",false);
    channelEstimateNMSE = localNormalizedResidual( ...
        dmrsResidual, localExtractPortSymbols(rxGrid,dmrsIndices));
    equalizedGrid = localApplyPortChannelInverse(rxGrid, channelGain);
    [expectedPTRS, ptrsIndices] = localRXReferencePorts( ...
        resourcePlan.PTRSIndicesPerPort, ...
        referenceRuntime.PTRSSymbolsPerPort, "ptrs", ...
        opt.PrecoderBundle, carrier, contract, receiver);
    [equalizedGrid, ptrsInfo] = localPTRSCorrection( ...
        equalizedGrid, ptrsIndices, expectedPTRS, carrier);
    dataPortSymbols = localExtractPortSymbols( ...
        equalizedGrid, resourcePlan.DataIndices);
    if isempty(opt.PrecoderBundle)
        if size(dataPortSymbols,1) ~= contract.NumLayers
            error("sixgr:pdsch:PDSCHReceiver:MissingPrecoderBundle", ...
                "Identity reception requires one physical port per PDSCH layer.");
        end
        layerValues = dataPortSymbols;
        deprecoderTrace = localRXIdentityTrace( ...
            dataPRB, dataSymbol, "effective_channel", contract.NumLayers);
    else
        if opt.PrecoderBundle.NLayerPorts ~= contract.NumLayers ...
                || opt.PrecoderBundle.NPhysicalTxAntennas ~= ...
                size(dataPortSymbols,1)
            error("sixgr:pdsch:PDSCHReceiver:PrecoderDimensionMismatch", ...
                "Receiver precoder bundle dimensions do not match grid/rank.");
        end
        [layerValues, deprecoderTrace] = opt.PrecoderBundle.deapply( ...
            dataPortSymbols, dataPRB, dataSymbol, ...
            "Domain", "effective_channel");
    end
    equalizationInfo = struct( ...
        "EngineUsed","explicit_awgn_per_port_inverse", ...
        "Domain","physical_port_then_explicit_deprecoding");
    channelEstimationMode = "awgn_scalar_per_physical_port";
    channelEstimateScope = "AWGN_only_not_fading_full_grid";
end
layerSymbols = layerValues.';
codewordSymbols = sixgr.pdsch.CodewordLayerMapper( ...
    layerSymbols, contract.NumLayers, "Operation", "demap");
if contract.NumCodewords == 1
    codewordSymbols = {codewordSymbols};
else
    codewordSymbols = reshape(codewordSymbols,1,[]);
end

noiseVariance = estimatedNoiseVariance;
if ~isempty(receiver.NoiseVariance)
    noiseVariance = receiver.NoiseVariance;
end
demapperNoiseVariance = max(double(noiseVariance), eps);
scrambledLLR = cell(1, contract.NumCodewords);
descrambledLLR = cell(1, contract.NumCodewords);
demodulationInfo = cell(1, contract.NumCodewords);
descramblingInfo = cell(1, contract.NumCodewords);
for cw = 1:contract.NumCodewords
    [scrambledLLR{cw}, demodulationInfo{cw}] = ...
        sixgr.pdsch.PDSCHModulator(codewordSymbols{cw}, ...
        contract.Modulation(cw), "Operation", "soft-demap", ...
        "NoiseVariance", demapperNoiseVariance);
    [descrambledLLR{cw}, descramblingInfo{cw}] = ...
        sixgr.pdsch.PDSCHScrambler(scrambledLLR{cw}, ...
        contract.RNTI, cw - 1, contract.NID, ...
        "Operation", "llr-descramble");
end

decode = sixgr.pdsch.DLSCHDecoder( ...
    localRXUnwrapOne(descrambledLLR), ...
    "CodingPlan", localRXUnwrapOne(plans), ...
    "MaxIterations", receiver.MaxIterations, ...
    "Algorithm", receiver.Algorithm, ...
    "PriorRecoveredLLR", opt.PriorRecoveredLLR, ...
    "PriorCodingPlan", opt.PriorCodingPlan, ...
    "HARQKey", opt.HARQKey);
[transportBlocks, crcPass] = localDecodedResults( ...
    decode, contract.NumCodewords);
harqResults = localProcessHARQ(opt.HARQManager, assignment, ...
    plans, decode, receiver, crcPass);
metrics = localStrictMetrics(resourcePlan, dmrsIndices, ptrsIndices, ...
    layerSymbols, codewordSymbols, scrambledLLR, descrambledLLR, ...
    decode, contract, noiseVariance, crcPass, receiverConfig, ...
    channelGain, channelEstimateNMSE);

stageTrace = table( ...
    ["ofdm_demodulation";"dmrs_extraction";"channel_noise_estimation"; ...
     "ptrs_correction";"data_extraction";"equalization"; ...
     "layer_demap";"soft_demodulation";"llr_descrambling"; ...
     "dlsch_decoding"], ...
    repmat("PASS",10,1), ...
    [numel(rxGrid);numel(dmrsIndices);numel(channelGain); ...
     numel(ptrsIndices);numel(dataPortSymbols);numel(layerValues); ...
     sum(cellfun(@numel,codewordSymbols)); ...
     sum(cellfun(@numel,scrambledLLR)); ...
     sum(cellfun(@numel,descrambledLLR)); ...
     sum(cellfun(@numel,transportBlocks))], ...
    'VariableNames', {'Stage','Status','MaterializedElementCount'});

rx = struct();
rx.ContractVersion = "ExplicitPDSCHReceiver/v1";
rx.Assignment = assignment;
rx.ResourcePlan = resourcePlan;
rx.Carrier = carrier;
rx.IntegrationBinding = integrationBinding;
rx.ReferenceConfig = referenceConfig;
rx.ReceiverConfig = receiverConfig;
rx.CodingPlans = plans;
rx.OFDMGrid = rxGrid;
rx.OFDMInfo = ofdmInfo;
rx.ChannelGainPerPhysicalPort = [];
rx.EffectiveLayerChannelEstimate = [];
if receiver.IsResourceSelective
    rx.EffectiveLayerChannelEstimate = channelGain;
else
    rx.ChannelGainPerPhysicalPort = channelGain;
end
rx.ChannelEstimationMode = channelEstimationMode;
rx.ChannelEstimateScope = channelEstimateScope;
rx.ChannelEstimationInfo = channelEstimationInfo;
rx.EqualizationInfo = equalizationInfo;
rx.ChannelEstimateNMSESource = metrics.ChannelEstimateNMSESource;
rx.EstimatedNoiseVariance = estimatedNoiseVariance;
rx.NoiseVarianceUsedForLLR = demapperNoiseVariance;
rx.DMRSResidual = dmrsResidual;
rx.PTRSCorrection = ptrsInfo;
rx.EqualizedGrid = equalizedGrid;
rx.DataPortSymbols = dataPortSymbols;
rx.DeprecoderTrace = deprecoderTrace;
rx.LayerSymbols = layerSymbols;
rx.CodewordSymbols = codewordSymbols;
rx.ScrambledLLR = scrambledLLR;
rx.DemodulationInfo = demodulationInfo;
rx.DescrambledLLR = descrambledLLR;
rx.DescramblingInfo = descramblingInfo;
rx.Decode = decode;
rx.TransportBlocks = transportBlocks;
rx.TransportBlock = vertcat(transportBlocks{:});
rx.CRCPassPerCodeword = logical(crcPass);
rx.CRCErrorPerCodeword = logical(~crcPass);
rx.CRCPass = all(crcPass);
rx.CRCError = any(~crcPass);
rx.HARQResults = harqResults;
rx.Metrics = metrics;
rx.StageTrace = stageTrace;
rx.Source = "explicit_pdsch_dlsch_production_receiver";
end

function binding = localRXResolveIntegrationBinding( ...
        assignment, context, precoderBundle)
strictProfile = any(assignment.Profile == ...
    ["connected_strict","sps_strict","ra_si_strict"]);
if ~strictProfile
    binding = struct( ...
        "Required", false, ...
        "Profile", assignment.Profile, ...
        "Status", "NOT_REQUIRED_PHY_CALIBRATION");
    return;
end
if isempty(fieldnames(context))
    error("sixgr:pdsch:MissingIntegrationContext", ...
        "Strict PDSCH RX requires the explicit active BWP/CC/epoch/TCI " + ...
        "integration context.");
end
binding = sixgr.pdsch.PDSCHIntegrationValidator.bind( ...
    assignment, context, precoderBundle);
end

function localRXValidateCarrierSymbolBoundary(assignment, carrier)
allocation = double(assignment.get("SymbolAllocation"));
if numel(allocation) ~= 2 || any(~isfinite(allocation)) ...
        || any(allocation ~= fix(allocation)) ...
        || allocation(1) < 0 || allocation(2) < 1 ...
        || allocation(1) + allocation(2) > double(carrier.SymbolsPerSlot)
    error("sixgr:pdsch:PDSCHReceiver:SymbolAllocationOutsideCarrier", ...
        "Assignment SymbolAllocation=%s is outside the carrier's " + ...
        "%d-symbol slot.", mat2str(allocation), carrier.SymbolsPerSlot);
end
end

function [contract, receiver] = localStrictContract( ...
        assignment, plan, referenceConfig, receiverConfig)
if ~isstruct(referenceConfig) || ~isscalar(referenceConfig)
    error("sixgr:pdsch:PDSCHReceiver:InvalidReferenceConfig", ...
        "Reference configuration must be a scalar struct.");
end
referenceRequired = ["DataScramblingIdentityNID","DMRSSymbolsPerPort", ...
    "PTRSSymbolsPerPort","NPhysicalTxAntennas","OFDMOptions"];
missing = referenceRequired(~isfield(referenceConfig, referenceRequired));
if ~isempty(missing)
    error("sixgr:pdsch:PDSCHReceiver:IncompleteReferenceConfig", ...
        "Reference configuration is missing: %s.", ...
        strjoin(cellstr(missing), ", "));
end
if ~iscell(referenceConfig.OFDMOptions) ...
        || mod(numel(referenceConfig.OFDMOptions),2) ~= 0
    error("sixgr:pdsch:PDSCHReceiver:InvalidOFDMOptions", ...
        "OFDMOptions must be a cell array of name-value pairs.");
end
if ~isstruct(receiverConfig) || ~isscalar(receiverConfig)
    error("sixgr:pdsch:PDSCHReceiver:InvalidReceiverConfig", ...
        "Receiver configuration must be a scalar struct.");
end
receiverRequired = ["TransportBlockSizes","ChannelModel", ...
    "MaxIterations","Algorithm","LLRConvention","NPhysicalRxAntennas"];
missing = receiverRequired(~isfield(receiverConfig, receiverRequired));
if ~isempty(missing)
    error("sixgr:pdsch:PDSCHReceiver:IncompleteReceiverConfig", ...
        "Receiver configuration is missing: %s.", ...
        strjoin(cellstr(missing), ", "));
end
if string(receiverConfig.LLRConvention) ~= "positive_favours_bit_zero"
    error("sixgr:pdsch:PDSCHReceiver:UnsupportedLLRConvention", ...
        "Strict PDSCH decoding requires positive LLR to favour bit zero.");
end

contract = struct();
contract.NumCodewords = double(assignment.get("NumCodewords"));
contract.NumLayers = double(assignment.get("NumLayers"));
contract.LayerCount = localRXNumeric( ...
    assignment.get("LayerCountPerCodeword"),contract.NumCodewords, ...
    "LayerCountPerCodeword");
contract.Modulation = localRXStrings( ...
    assignment.get("ModulationPerCodeword"),contract.NumCodewords, ...
    "ModulationPerCodeword");
contract.TargetCodeRate = localRXNumeric( ...
    assignment.get("TargetCodeRatePerCodeword"),contract.NumCodewords, ...
    "TargetCodeRatePerCodeword");
contract.RV = localRXNumeric( ...
    assignment.get("RVPerCodeword"),contract.NumCodewords,"RVPerCodeword");
contract.RNTI = double(assignment.get("RNTI"));
contract.NID = double(referenceConfig.DataScramblingIdentityNID);
if contract.NumCodewords ~= 1 + double(contract.NumLayers > 4) ...
        || sum(contract.LayerCount) ~= contract.NumLayers ...
        || ~isequal(contract.LayerCount,plan.LayerCountPerCodeword)
    error("sixgr:pdsch:PDSCHReceiver:CodewordLayerMismatch", ...
        "Assignment and resource-plan codeword/layer contracts differ.");
end
qms = arrayfun(@localRXQm,contract.Modulation);
if ~isequal(qms,plan.QmPerCodeword)
    error("sixgr:pdsch:PDSCHReceiver:ModulationResourcePlanMismatch", ...
        "Assignment modulation orders differ from the resource plan.");
end
if ~isequal(double(assignment.get("PRBSetCarrierRelative")),plan.PRBSet) ...
        || ~isequal(double(assignment.get("SymbolAllocation")),plan.SymbolAllocation)
    error("sixgr:pdsch:PDSCHReceiver:AssignmentResourcePlanMismatch", ...
        "Assignment PRB/symbol allocation differs from the resource plan.");
end
if ~(isscalar(contract.NID) && isfinite(contract.NID) ...
        && contract.NID == fix(contract.NID) ...
        && contract.NID >= 0 && contract.NID <= 1023)
    error("sixgr:pdsch:PDSCHReceiver:InvalidScramblingIdentity", ...
        "DataScramblingIdentityNID must be an integer in [0,1023].");
end

receiver = struct();
receiver.TransportBlockSizes = localRXNumeric( ...
    receiverConfig.TransportBlockSizes,contract.NumCodewords, ...
    "TransportBlockSizes");
if any(receiver.TransportBlockSizes <= 0 ...
        | receiver.TransportBlockSizes ~= fix(receiver.TransportBlockSizes))
    error("sixgr:pdsch:PDSCHReceiver:InvalidTransportBlockSizes", ...
        "TransportBlockSizes must be positive integers.");
end
receiver.MaxIterations = double(receiverConfig.MaxIterations);
if ~(isscalar(receiver.MaxIterations) && isfinite(receiver.MaxIterations) ...
        && receiver.MaxIterations >= 1 ...
        && receiver.MaxIterations == fix(receiver.MaxIterations))
    error("sixgr:pdsch:PDSCHReceiver:InvalidMaxIterations", ...
        "MaxIterations must be a positive integer.");
end
receiver.Algorithm = char(string(receiverConfig.Algorithm));
receiver.ReferencePhysicalTxAntennas = ...
    double(referenceConfig.NPhysicalTxAntennas);
if ~(isscalar(receiver.ReferencePhysicalTxAntennas) ...
        && isfinite(receiver.ReferencePhysicalTxAntennas) ...
        && receiver.ReferencePhysicalTxAntennas >= 1 ...
        && receiver.ReferencePhysicalTxAntennas == ...
            fix(receiver.ReferencePhysicalTxAntennas))
    error("sixgr:pdsch:PDSCHReceiver:InvalidReferenceTransmitPortCount", ...
        "NPhysicalTxAntennas must be a positive integer.");
end
receiver.ChannelModel = upper(strtrim(string(receiverConfig.ChannelModel)));
receiver.IsFading = startsWith(receiver.ChannelModel,"TDL-") ...
    || startsWith(receiver.ChannelModel,"CDL-");
receiver.IsStaticMIMO = receiver.ChannelModel == "STATIC-MIMO";
receiver.IsResourceSelective = receiver.IsFading ...
    || receiver.IsStaticMIMO;
if receiver.ChannelModel ~= "AWGN" ...
        && ~receiver.IsResourceSelective
    error("sixgr:pdsch:PDSCHReceiver:ConcreteFadingProfileRequired", ...
        ["ChannelModel must be AWGN, STATIC-MIMO, or a concrete " ...
        "TDL-*/CDL-* profile; bare model families and unrecognized " ...
        "tokens are not executable."]);
end
receiver.DMRSCDMLengths = [];
if receiver.IsResourceSelective
    if ~isfield(referenceConfig,"DMRSCDMLengths")
        error("sixgr:pdsch:PDSCHReceiver:MissingDMRSCDMLengths", ...
            ["Fading reception requires the explicit DMRSCDMLengths " ...
            "used to generate the scheduled DM-RS ports."]);
    end
    receiver.DMRSCDMLengths = double( ...
        referenceConfig.DMRSCDMLengths(:).');
    if isempty(receiver.DMRSCDMLengths) ...
            || any(~isfinite(receiver.DMRSCDMLengths)) ...
            || any(receiver.DMRSCDMLengths < 1) ...
            || any(receiver.DMRSCDMLengths ~= ...
                fix(receiver.DMRSCDMLengths))
        error("sixgr:pdsch:PDSCHReceiver:InvalidDMRSCDMLengths", ...
            "DMRSCDMLengths must contain explicit positive integers.");
    end
end
receiver.NPhysicalRxAntennas = double(receiverConfig.NPhysicalRxAntennas);
if ~(isscalar(receiver.NPhysicalRxAntennas) ...
        && receiver.NPhysicalRxAntennas >= 1 ...
        && receiver.NPhysicalRxAntennas == fix(receiver.NPhysicalRxAntennas))
    error("sixgr:pdsch:PDSCHReceiver:InvalidReceivePortCount", ...
        "NPhysicalRxAntennas must be a positive integer.");
end
if ~receiver.IsResourceSelective ...
        && receiver.NPhysicalRxAntennas ~= ...
        receiver.ReferencePhysicalTxAntennas
    error("sixgr:pdsch:PDSCHReceiver:ReceiveReferencePortMismatch", ...
        ["AWGN scalar-per-port reception requires NPhysicalRxAntennas " ...
        "to match reference-config physical transmit ports."]);
end
if receiver.IsResourceSelective ...
        && receiver.NPhysicalRxAntennas < contract.NumLayers
    error("sixgr:pdsch:PDSCHReceiver:InsufficientReceiveRank", ...
        ["Fading reception requires at least NumLayers independent " ...
        "receive observations for the scheduled spatial rank."]);
end
receiver.NoiseVariance = [];
if isfield(receiverConfig,"NoiseVariance") ...
        && ~isempty(receiverConfig.NoiseVariance)
    value = double(receiverConfig.NoiseVariance);
    if ~(isscalar(value) && isfinite(value) && value >= 0)
        error("sixgr:pdsch:PDSCHReceiver:InvalidNoiseVariance", ...
            "NoiseVariance must be a finite nonnegative grid-domain scalar.");
    end
    receiver.NoiseVariance = value;
end
receiver.Nref = [];
if isfield(receiverConfig,"Nref")
    receiver.Nref = receiverConfig.Nref;
end
receiver.Raw = receiverConfig;
end

function plans = localRXCodingPlans(raw,contract,resourcePlan,receiver)
if isempty(raw)
    error("sixgr:pdsch:PDSCHReceiver:MissingCodingPlan", ...
        ("Strict PDSCH RX requires the immutable DLSCHCodingPlan " + ...
        "object(s) produced by the matching transmitter."));
end
if isa(raw,"sixgr.pdsch.DLSCHCodingPlan")
    plans = num2cell(reshape(raw,1,[]));
elseif iscell(raw)
    plans = reshape(raw,1,[]);
else
    error("sixgr:pdsch:PDSCHReceiver:InvalidCodingPlan", ...
        "CodingPlans must contain immutable DLSCHCodingPlan objects.");
end
if numel(plans) ~= contract.NumCodewords
    error("sixgr:pdsch:PDSCHReceiver:CodingPlanCountMismatch", ...
        "Strict PDSCH RX requires exactly %d coding plan(s).", ...
        contract.NumCodewords);
end
nref = localRXOptional(receiver.Nref,contract.NumCodewords);
for cw = 1:contract.NumCodewords
    plan = plans{cw};
    if ~isa(plan,"sixgr.pdsch.DLSCHCodingPlan") ...
            || ~isscalar(plan) || ~logical(plan.Immutable) ...
            || strlength(string(plan.PlanID)) == 0 ...
            || strlength(string(plan.CodingLayoutHash)) == 0
        error("sixgr:pdsch:PDSCHReceiver:InvalidCodingPlan", ...
            ("Coding plan %d must be one immutable DLSCHCodingPlan " + ...
            "with a nonempty PlanID and CodingLayoutHash."),cw-1);
    end
    matches = double(plan.CodewordIndex) == cw-1 ...
        && double(plan.TransportBlockSize) == ...
            receiver.TransportBlockSizes(cw) ...
        && abs(double(plan.TargetCodeRate) - ...
            contract.TargetCodeRate(cw)) <= 1e-12 ...
        && double(plan.RateMatchedBitCount) == ...
            resourcePlan.GPerCodeword(cw) ...
        && double(plan.RV) == contract.RV(cw) ...
        && upper(string(plan.Modulation)) == ...
            upper(contract.Modulation(cw)) ...
        && double(plan.NumLayers) == contract.LayerCount(cw);
    if ~isempty(nref{cw})
        matches = matches && ~isempty(plan.Nref) ...
            && double(plan.Nref) == double(nref{cw});
    end
    if ~matches
        error("sixgr:pdsch:PDSCHReceiver:CodingPlanContractMismatch", ...
            ("Coding plan %d differs from the immutable assignment, " + ...
            "resource plan, or receiver transport-block contract."),cw-1);
    end
    layout = plan.toCodingLayout();
    if string(layout.CodingLayoutHash) ~= string(plan.CodingLayoutHash)
        error("sixgr:pdsch:PDSCHReceiver:CodingPlanContractMismatch", ...
            "Coding plan %d layout hash does not match its PlanID.",cw-1);
    end
end
end

function [expected, unionIndices] = localRXReferencePorts( ...
        indexCells, symbolCells, domain, bundle, carrier, contract, receiver)
[logicalSymbols, unionIndices] = localRXLogicalReferences( ...
    indexCells, symbolCells, domain, carrier, contract);
[prb,symbol] = localRXCoordinates(unionIndices,carrier);
txPorts = receiver.ReferencePhysicalTxAntennas;
if isempty(unionIndices)
    expected = complex(zeros(txPorts,0));
    return;
end
if isempty(bundle)
    if txPorts ~= contract.NumLayers
        error("sixgr:pdsch:PDSCHReceiver:MissingPrecoderBundle", ...
            "Identity reference processing requires one physical port per layer.");
    end
    expected = logicalSymbols;
else
    if bundle.NLayerPorts ~= contract.NumLayers ...
            || bundle.NPhysicalTxAntennas ~= txPorts
        error("sixgr:pdsch:PDSCHReceiver:PrecoderDimensionMismatch", ...
            "Reference precoder dimensions differ from receiver rank/ports.");
    end
    expected = bundle.apply(logicalSymbols,prb,symbol,"Domain",domain);
end
end

function [logicalSymbols, unionIndices] = localRXLogicalReferences( ...
        indexCells, symbolCells, domain, carrier, contract)
if ~iscell(indexCells) || ~isrow(indexCells) ...
        || numel(indexCells) ~= contract.NumLayers ...
        || ~iscell(symbolCells) || ~isrow(symbolCells) ...
        || numel(symbolCells) ~= contract.NumLayers
    error("sixgr:pdsch:PDSCHReceiver:ReferencePortCountMismatch", ...
        "%s indices and symbols require one cell per layer port.",upper(domain));
end
planeSize = carrier.NSizeGrid*12*carrier.SymbolsPerSlot;
unionIndices = unique([indexCells{:}],"sorted");
if any(unionIndices < 0 | unionIndices >= planeSize)
    error("sixgr:pdsch:PDSCHReceiver:ReferenceIndexOutsideGrid", ...
        "%s contains an index outside the carrier grid.",upper(domain));
end
logicalSymbols = complex(zeros(contract.NumLayers,numel(unionIndices)));
for layer = 1:contract.NumLayers
    indices = double(indexCells{layer}(:));
    symbols = symbolCells{layer};
    if ~(isnumeric(symbols) && isvector(symbols) ...
            && numel(symbols) == numel(indices) ...
            && all(isfinite(real(symbols(:)))) ...
            && all(isfinite(imag(symbols(:)))))
        error("sixgr:pdsch:PDSCHReceiver:ReferenceSymbolCountMismatch", ...
            "%s symbols do not match layer-port %d indices.", ...
            upper(domain),layer-1);
    end
    [present,position] = ismember(indices,unionIndices);
    if any(~present)
        error("sixgr:pdsch:PDSCHReceiver:ReferenceIndexMismatch", ...
            "Unable to resolve %s layer-port indices.",upper(domain));
    end
    logicalSymbols(layer,position) = complex(double(symbols(:)));
end
end

function [gain,noiseVariance,residual] = localEstimateAWGNChannel( ...
        grid,indices,expected)
observed = localExtractPortSymbols(grid,indices);
if ~isequal(size(observed),size(expected))
    error("sixgr:pdsch:PDSCHReceiver:DMRSShapeMismatch", ...
        "Observed and expected DM-RS matrices have different shapes.");
end
nPorts = size(observed,1);
gain = complex(zeros(nPorts,1));
residual = complex(zeros(size(observed)));
for port = 1:nPorts
    energy = sum(abs(expected(port,:)).^2);
    if ~(isfinite(energy) && energy > 0)
        error("sixgr:pdsch:PDSCHReceiver:MissingDMRSPortEvidence", ...
            "Physical port %d has no nonzero DM-RS evidence.",port-1);
    end
    gain(port) = sum(conj(expected(port,:)).*observed(port,:))/energy;
    if ~(isfinite(real(gain(port))) && isfinite(imag(gain(port))) ...
            && abs(gain(port)) > eps)
        error("sixgr:pdsch:PDSCHReceiver:InvalidChannelEstimate", ...
            "Physical port %d produced a zero or nonfinite AWGN estimate.",port-1);
    end
    residual(port,:) = observed(port,:) - gain(port)*expected(port,:);
end
noiseVariance = mean(abs(residual(:)).^2);
if ~(isscalar(noiseVariance) && isfinite(noiseVariance) && noiseVariance >= 0)
    error("sixgr:pdsch:PDSCHReceiver:InvalidNoiseEstimate", ...
        "DM-RS residual did not produce a valid noise variance.");
end
end

function [hest,noiseVariance,residual,info,pilotNMSE] = ...
        localEstimateFadingChannel(grid,plan,referenceConfig, ...
        carrier,contract,receiver)
indexCells = plan.DMRSIndicesPerPort;
symbolCells = referenceConfig.DMRSSymbolsPerPort;
counts = cellfun(@numel,indexCells);
symbolCounts = cellfun(@numel,symbolCells);
if any(counts ~= counts(1)) || any(symbolCounts ~= counts)
    error("sixgr:pdsch:PDSCHReceiver:FadingDMRSMatrixShapeMismatch", ...
        ["Resource-selective MIMO estimation requires an equal explicit " ...
        "DM-RS observation count on every scheduled layer port."]);
end
count = counts(1);
planeSize = carrier.NSizeGrid*12*carrier.SymbolsPerSlot;
refInd = zeros(count,contract.NumLayers);
refSym = complex(zeros(count,contract.NumLayers));
for layer = 1:contract.NumLayers
    indices = double(indexCells{layer}(:));
    symbols = complex(double(symbolCells{layer}(:)));
    if any(indices < 0 | indices >= planeSize) ...
            || any(~isfinite(real(symbols)) | ~isfinite(imag(symbols))) ...
            || ~all(abs(symbols) > 0)
        error("sixgr:pdsch:PDSCHReceiver:InvalidFadingDMRSReference", ...
            ["Fading DM-RS indices must lie in the carrier grid and every " ...
            "scheduled layer reference symbol must be finite and nonzero."]);
    end
    refInd(:,layer) = indices + 1 + planeSize*(layer-1);
    refSym(:,layer) = symbols;
end
[hest,noiseVariance,info] = sixgr.phy.rx.channelEstimate( ...
    carrier,grid,refInd,refSym, ...
    "CDMLengths",receiver.DMRSCDMLengths, ...
    "AveragingWindow",[0 0], ...
    "StrictMode",true, ...
    "ChannelModel",receiver.ChannelModel, ...
    "ExpectedTxPorts",contract.NumLayers, ...
    "ContextLabel","sixgr.pdsch.PDSCHReceiver.strict_fading", ...
    "Method","LS");
expectedShape = [carrier.NSizeGrid*12,carrier.SymbolsPerSlot, ...
    receiver.NPhysicalRxAntennas,contract.NumLayers];
actualShape = size(hest);
actualShape(end+1:4) = 1;
if ~isequal(actualShape(1:4),expectedShape) ...
        || any(~isfinite(real(hest(:)))) ...
        || any(~isfinite(imag(hest(:))))
    error("sixgr:pdsch:PDSCHReceiver:InvalidFadingChannelEstimate", ...
        ["DM-RS estimation must return a finite K-by-L-by-NRx-by-rank " ...
        "per-resource effective channel tensor."]);
end
if logical(sixgr.util.structGet(info,"ScalarFastPathUsed",false)) ...
        || contains(lower(string(sixgr.util.structGet( ...
        info,"EngineUsed",""))),["scalar","mex"])
    error("sixgr:pdsch:PDSCHReceiver:ScalarFadingEstimateForbidden", ...
        "A scalar channel-estimation engine cannot serve a fading PDSCH.");
end
[residual,pilotNMSE] = localFadingPilotResidual( ...
    grid,hest,indexCells,symbolCells,carrier,contract);
if ~(isscalar(noiseVariance) && isfinite(noiseVariance) ...
        && noiseVariance >= 0)
    error("sixgr:pdsch:PDSCHReceiver:InvalidNoiseEstimate", ...
        "DM-RS estimation did not return a finite nonnegative noise estimate.");
end
info.PilotReconstructionNMSE = double(pilotNMSE);
info.PilotReconstructionNMSESource = ...
    "received_dmrs_minus_estimated_effective_channel_times_known_dmrs";
end

function [residual,nmse] = localFadingPilotResidual( ...
        grid,hest,indexCells,symbolCells,carrier,contract)
[logicalSymbols,unionIndices] = localRXLogicalReferences( ...
    indexCells,symbolCells,"dmrs",carrier,contract);
observed = localExtractPortSymbols(grid,unionIndices);
predicted = complex(zeros(size(observed)));
[~,symbols] = localRXCoordinates(unionIndices,carrier);
K = carrier.NSizeGrid*12;
subcarriers = mod(unionIndices,K);
for re = 1:numel(unionIndices)
    H = reshape(hest(subcarriers(re)+1,symbols(re)+1,:,:), ...
        size(grid,3),contract.NumLayers);
    predicted(:,re) = H*logicalSymbols(:,re);
end
residual = observed-predicted;
nmse = localNormalizedResidual(residual,observed);
end

function [layerValues,rxValues,equalizedGrid,info] = ...
        localEqualizeFadingResources(rxGrid,hest,indices, ...
        estimatedNoise,configuredNoise,numLayers)
noiseVariance = localEffectiveNoiseVariance( ...
    estimatedNoise,configuredNoise);
[rxValues,hValues] = nrExtractResources(indices+1,rxGrid,hest);
[equalized,csi] = nrEqualizeMMSE(rxValues,hValues,noiseVariance);
if size(equalized,1) ~= numel(indices) ...
        || size(equalized,2) ~= numLayers ...
        || any(~isfinite(real(equalized(:)))) ...
        || any(~isfinite(imag(equalized(:))))
    error("sixgr:pdsch:PDSCHReceiver:FadingEqualizationFailed", ...
        ["MMSE equalization must produce one finite symbol per data RE " ...
        "and scheduled layer."]);
end
layerValues = equalized.';
rxValues = rxValues.';
equalizedGrid = complex(zeros(size(rxGrid,1),size(rxGrid,2),numLayers));
equalizedGrid = localMapEqualizedLayerResources( ...
    equalizedGrid,indices,layerValues);
info = struct( ...
    "EngineUsed","nrEqualizeMMSE", ...
    "Domain","dmrs_estimated_effective_layer_channel", ...
    "NoiseVariance",double(noiseVariance), ...
    "CSI",double(csi));
end

function [layerValues,info] = localPTRSCorrectionLayers( ...
        layerValues,dataSymbols,rxGrid,hest,indices,expected, ...
        carrier,estimatedNoise,configuredNoise)
cpe = zeros(carrier.SymbolsPerSlot,1);
observations = zeros(carrier.SymbolsPerSlot,1);
if isempty(indices)
    info = struct("Enabled",false,"CPEPerSymbolRad",cpe, ...
        "ObservationCountPerSymbol",observations, ...
        "Status","disabled_no_ptrs");
    return;
end
noiseVariance = localEffectiveNoiseVariance( ...
    estimatedNoise,configuredNoise);
[received,hValues] = nrExtractResources(indices+1,rxGrid,hest);
[equalized,~] = nrEqualizeMMSE(received,hValues,noiseVariance);
equalized = equalized.';
[~,ptrsSymbols] = localRXCoordinates(indices,carrier);
for symbol = unique(ptrsSymbols,"stable")
    selected = ptrsSymbols == symbol;
    reference = expected(:,selected);
    observed = equalized(:,selected);
    active = abs(reference) > 0;
    if any(active(:))
        phasor = sum(observed(active).*conj(reference(active)));
        cpe(symbol+1) = angle(phasor);
        observations(symbol+1) = nnz(active);
        dataMask = dataSymbols == symbol;
        layerValues(:,dataMask) = layerValues(:,dataMask) ...
            .* exp(-1j*cpe(symbol+1));
    end
end
info = struct("Enabled",true,"CPEPerSymbolRad",cpe, ...
    "ObservationCountPerSymbol",observations, ...
    "Status","explicit_ptrs_cpe_corrected_after_mimo_equalization");
end

function grid = localMapEqualizedLayerResources(grid,indices,values)
if size(values,2) ~= numel(indices) ...
        || size(values,1) ~= size(grid,3)
    error("sixgr:pdsch:PDSCHReceiver:EqualizedResourceShapeMismatch", ...
        "Equalized layer values do not match the target resource grid.");
end
for layer = 1:size(grid,3)
    plane = grid(:,:,layer);
    plane(indices+1) = values(layer,:);
    grid(:,:,layer) = plane;
end
end

function value = localEffectiveNoiseVariance(estimated,configured)
value = double(estimated);
if ~isempty(configured)
    value = double(configured);
end
if ~(isscalar(value) && isfinite(value) && value >= 0)
    error("sixgr:pdsch:PDSCHReceiver:InvalidNoiseEstimate", ...
        "Equalization requires a finite nonnegative grid noise variance.");
end
value = max(value,eps);
end

function nmse = localNormalizedResidual(residual,observed)
numerator = sum(abs(residual(:)).^2);
denominator = sum(abs(observed(:)).^2);
nmse = numerator/max(denominator,eps);
if ~(isscalar(nmse) && isfinite(nmse) && nmse >= 0)
    error("sixgr:pdsch:PDSCHReceiver:InvalidPilotResidual", ...
        "DM-RS reconstruction residual must be finite and nonnegative.");
end
end

function grid = localApplyPortChannelInverse(grid,gain)
for port = 1:size(grid,3)
    grid(:,:,port) = grid(:,:,port)/gain(port);
end
end

function [grid,info] = localPTRSCorrection(grid,indices,expected,carrier)
cpe = zeros(carrier.SymbolsPerSlot,1);
observations = zeros(carrier.SymbolsPerSlot,1);
if isempty(indices)
    info = struct("Enabled",false,"CPEPerSymbolRad",cpe, ...
        "ObservationCountPerSymbol",observations, ...
        "Status","disabled_no_ptrs");
    return;
end
observed = localExtractPortSymbols(grid,indices);
[~,symbols] = localRXCoordinates(indices,carrier);
for symbol = unique(symbols,"stable")
    selected = symbols == symbol;
    reference = expected(:,selected);
    received = observed(:,selected);
    active = abs(reference) > 0;
    if any(active(:))
        phasor = sum(received(active).*conj(reference(active)));
        cpe(symbol+1) = angle(phasor);
        observations(symbol+1) = nnz(active);
        grid(:,symbol+1,:) = grid(:,symbol+1,:) .* exp(-1j*cpe(symbol+1));
    end
end
info = struct("Enabled",true,"CPEPerSymbolRad",cpe, ...
    "ObservationCountPerSymbol",observations, ...
    "Status","explicit_ptrs_cpe_corrected");
end

function values = localExtractPortSymbols(grid,indices)
values = complex(zeros(size(grid,3),numel(indices)));
for port = 1:size(grid,3)
    plane = grid(:,:,port);
    values(port,:) = plane(indices+1);
end
end

function [prb,symbol] = localRXCoordinates(indices,carrier)
K = carrier.NSizeGrid*12;
indices = double(indices(:).');
subcarrier = mod(indices,K);
symbol = floor(indices/K);
prb = floor(subcarrier/12);
if any(symbol < 0 | symbol >= carrier.SymbolsPerSlot)
    error("sixgr:pdsch:PDSCHReceiver:ResourceIndexOutsideGrid", ...
        "A resource-plan index lies outside the carrier grid.");
end
end

function [blocks,pass] = localDecodedResults(decode,count)
if count == 1
    blocks = {int8(decode.TransportBlock(:))};
    pass = logical(decode.CRCPass);
else
    if ~isfield(decode,"Codewords") || numel(decode.Codewords) ~= count
        error("sixgr:pdsch:PDSCHReceiver:DLSCHDecodeContractMismatch", ...
            "Explicit multi-codeword decoder output is incomplete.");
    end
    blocks = cell(1,count);
    pass = false(1,count);
    for idx = 1:count
        blocks{idx} = int8(decode.Codewords{idx}.TransportBlock(:));
        pass(idx) = logical(decode.Codewords{idx}.CRCPass);
    end
end
end

function results = localProcessHARQ(manager,assignment,plans,decode,receiver,crcPass)
if isempty(manager)
    results = cell(1,0);
    return;
end
raw = receiver.Raw;
required = ["NewDataPerCodeword","TBIdentityDigestPerCodeword"];
missing = required(~isfield(raw,required));
if ~isempty(missing)
    error("sixgr:pdsch:PDSCHReceiver:IncompleteHARQReceiverConfig", ...
        "HARQ manager use requires receiver fields: %s.", ...
        strjoin(cellstr(missing),", "));
end
newData = logical(localRXNumeric( ...
    raw.NewDataPerCodeword,numel(plans),"NewDataPerCodeword"));
identity = localRXStrings( ...
    raw.TBIdentityDigestPerCodeword,numel(plans), ...
    "TBIdentityDigestPerCodeword");
results = cell(1,numel(plans));
for cw = 1:numel(plans)
    if numel(plans) == 1
        decoded = decode;
    else
        decoded = decode.Codewords{cw};
    end
    recovered = double(decoded.RateRecoveredLLR);
    valid = isfinite(recovered);
    nref = plans{cw}.Nref;
    if isempty(nref), nref = plans{cw}.Ncb; end
    ndi = localRXNumeric(assignment.get("NDIPerCodeword"), ...
        numel(plans),"NDIPerCodeword");
    observation = struct( ...
        "UEId",double(assignment.get("UEId")), ...
        "ServingCellId",double(assignment.get("ServingCellId")), ...
        "SchedulingCellId",double(assignment.get("SchedulingCellId")), ...
        "CCId",double(assignment.get("CCId")), ...
        "BWPId",double(assignment.get("BWPId")), ...
        "HARQProcessId",double(assignment.get("HARQProcessId")), ...
        "CodewordIndex",cw-1, ...
        "ConfigurationEpoch",double(assignment.get("ConfigurationEpoch")), ...
        "NDI",ndi(cw), ...
        "NewData",newData(cw), ...
        "RV",double(plans{cw}.RV), ...
        "TBIdentityDigest",identity(cw), ...
        "TBS",double(plans{cw}.TransportBlockSize), ...
        "CodingPlanDigest",string(plans{cw}.CodingLayoutHash), ...
        "BaseGraph",double(plans{cw}.BaseGraph), ...
        "LiftingSize",double(plans{cw}.LiftingSize), ...
        "CodeBlockLayout",plans{cw}.toCodingLayout(), ...
        "FillerPositions",{plans{cw}.FillerPositionsZeroBased}, ...
        "Ncb",double(plans{cw}.Ncb), ...
        "Nref",double(nref), ...
        "RateRecoveredLLR",recovered, ...
        "ValidPositionMask",valid, ...
        "DecodeOK",logical(crcPass(cw)));
    [~,results{cw}] = manager.process(observation);
end
end

function trace = localRXIdentityTrace(prb,symbol,domain,rank)
count = numel(prb);
resourceIndex = (0:count-1).';
PRB = prb(:);
Symbol = symbol(:);
PRG = zeros(count,1);
SymbolGroup = zeros(count,1);
Domain = repmat(string(domain),count,1);
Operation = repmat("deapply",count,1);
ResolvedMatrixDigest = repmat("identity_rank_"+string(rank),count,1);
AppliedMatrixDigest = ResolvedMatrixDigest;
trace = table(resourceIndex,PRB,Symbol,PRG,SymbolGroup,Domain, ...
    Operation,ResolvedMatrixDigest,AppliedMatrixDigest, ...
    'VariableNames', {'ResourceIndex','PRB','Symbol','PRG','SymbolGroup', ...
    'Domain','Operation','ResolvedMatrixDigest','AppliedMatrixDigest'});
end

function metrics = localStrictMetrics(plan,dmrsIndices,ptrsIndices, ...
        layerSymbols,codewordSymbols,scrambledLLR,descrambledLLR, ...
        decode,contract,noiseVariance,crcPass,receiverConfig, ...
        channelGain,pilotReconstructionNMSE)
safeNoise = max(double(noiseVariance),eps);
sinrPerLayer = zeros(1,contract.NumLayers);
for layer = 1:contract.NumLayers
    sinrPerLayer(layer) = 10*log10( ...
        mean(abs(layerSymbols(:,layer)).^2)/safeNoise);
end
evmPerCodeword = zeros(1,contract.NumCodewords);
rateRecoveredCount = zeros(1,contract.NumCodewords);
iterations = zeros(1,contract.NumCodewords);
for cw = 1:contract.NumCodewords
    hardBits = sixgr.pdsch.PDSCHModulator(codewordSymbols{cw}, ...
        contract.Modulation(cw),"Operation","hard-demap");
    remodulated = sixgr.pdsch.PDSCHModulator( ...
        hardBits,contract.Modulation(cw));
    denominator = max(mean(abs(remodulated).^2),eps);
    evmPerCodeword(cw) = sqrt(mean(abs( ...
        codewordSymbols{cw}(:)-remodulated(:)).^2)/denominator);
    if contract.NumCodewords == 1
        decoded = decode;
    else
        decoded = decode.Codewords{cw};
    end
    rateRecoveredCount(cw) = numel(decoded.RateRecoveredLLR);
    iterations(cw) = mean(double(decoded.ActiveIterations(:)),"omitnan");
end
channelNMSE = double(pilotReconstructionNMSE);
channelNMSESource = ...
    "dmrs_pilot_reconstruction_residual_not_true_channel_oracle";
if isfield(receiverConfig,"ReferenceChannelGain") ...
        && ~isempty(receiverConfig.ReferenceChannelGain)
    truthGain = complex(double(receiverConfig.ReferenceChannelGain(:)));
    if numel(truthGain) ~= numel(channelGain)
        error("sixgr:pdsch:PDSCHReceiver:ReferenceChannelShapeMismatch", ...
            "ReferenceChannelGain must contain one value per physical port.");
    end
    channelNMSE = sum(abs(channelGain-truthGain).^2) ...
        / max(sum(abs(truthGain).^2),eps);
    channelNMSESource = ...
        "explicit_awgn_reference_gain_test_contract";
end
metrics = struct( ...
    "DataRECount",double(plan.ExactDataRECount), ...
    "DMRSRECount",double(numel(dmrsIndices)), ...
    "PTRSRECount",double(numel(ptrsIndices)), ...
    "ChannelEstimateNMSE",double(channelNMSE), ...
    "ChannelEstimateNMSESource",channelNMSESource, ...
    "MeasuredPostEqualizationSINRdBPerLayer",sinrPerLayer, ...
    "EVMPerCodeword",evmPerCodeword, ...
    "ScrambledLLRCountPerCodeword",cellfun(@numel,scrambledLLR), ...
    "DescrambledLLRCountPerCodeword",cellfun(@numel,descrambledLLR), ...
    "FiniteDescrambledLLRCountPerCodeword", ...
        cellfun(@(x) nnz(isfinite(x)),descrambledLLR), ...
    "RateRecoveredBitCountPerCodeword",rateRecoveredCount, ...
    "LDPCIterationCountPerCodeword",iterations, ...
    "BERPerCodeword",NaN(1,contract.NumCodewords), ...
    "BLERPerCodeword",double(~crcPass), ...
    "TBCRCPassPerCodeword",logical(crcPass), ...
    "BERStatus","unavailable_without_external_decoded_bit_reference");
end

function values = localRXNumeric(raw,count,name)
values = double(raw(:).');
if numel(values) ~= count || any(~isfinite(values))
    error("sixgr:pdsch:PDSCHReceiver:CodewordParameterMismatch", ...
        "%s must contain one finite value per codeword.",name);
end
end

function values = localRXStrings(raw,count,name)
values = reshape(string(raw),1,[]);
if numel(values) ~= count || any(strlength(strtrim(values)) == 0)
    error("sixgr:pdsch:PDSCHReceiver:CodewordParameterMismatch", ...
        "%s must contain one nonempty value per codeword.",name);
end
end

function qm = localRXQm(modulation)
switch upper(erase(string(modulation)," "))
    case "QPSK", qm = 2;
    case "16QAM", qm = 4;
    case "64QAM", qm = 6;
    case "256QAM", qm = 8;
    case "1024QAM", qm = 10;
    otherwise
        error("sixgr:pdsch:PDSCHReceiver:UnsupportedModulation", ...
            "Unsupported PDSCH modulation '%s'.",modulation);
end
end

function cells = localRXOptional(raw,count)
if isempty(raw)
    cells = repmat({[]},1,count);
    return;
end
raw = double(raw(:).');
if isscalar(raw), raw = repmat(raw,1,count); end
if numel(raw) ~= count || any(~isfinite(raw)) ...
        || any(raw <= 0 | raw ~= fix(raw))
    error("sixgr:pdsch:PDSCHReceiver:CodewordParameterMismatch", ...
        "Nref must be empty or one positive integer per codeword.");
end
cells = num2cell(raw);
end

function value = localRXUnwrapOne(cells)
if numel(cells) == 1
    value = cells{1};
else
    value = cells;
end
end
