classdef PDSCHPhaseFocusedTestExecutor
    %PDSCHPHASEFOCUSEDTESTEXECUTOR Execute the selected nonrecursive suite.

    methods (Static)
        function [summary, execution] = run(vectorRoot, suiteNames)
            if nargin < 2
                suiteNames = sixgr.pdsch. ...
                    PDSCHPhaseFocusedTestExecutor.requiredSuiteNames();
            end
            names = string(suiteNames(:));
            names = names(names ~= "testPDSCHArtifactGeneration");
            vectorRoot = char(string(vectorRoot));
            testsDir = fileparts(fileparts(vectorRoot));
            if ~isfolder(testsDir)
                error("sixgr:pdsch:PDSCHFocusedTests:TestsMissing", ...
                    "Unable to locate the focused MATLAB test directory.");
            end
            priorPath = path;
            pathCleanup = onCleanup(@() path(priorPath));
            addpath(testsDir);

            summaryRows = repmat( ...
                sixgr.pdsch.PDSCHPhaseFocusedTestExecutor. ...
                emptySummaryRow(), numel(names), 1);
            execution = table();
            for i = 1:numel(names)
                suite = names(i);
                sourcePath = string(which(char(suite)));
                started = tic;
                errorIdentifier = "";
                errorMessage = "";
                detail = "";
                try
                    if strlength(sourcePath) == 0
                        error("sixgr:pdsch:PDSCHFocusedTests:TestMissing", ...
                            "Unable to resolve focused test %s.", suite);
                    end
                    returned = feval(char(suite));
                    passed = (islogical(returned) || isnumeric(returned)) ...
                        && isscalar(returned) ...
                        && isfinite(double(returned)) ...
                        && logical(returned);
                    if ~passed
                        errorIdentifier = ...
                            "sixgr:pdsch:PDSCHFocusedTests:ReturnedFalse";
                        errorMessage = "Focused test returned false.";
                    else
                        detail = "function returned true";
                    end
                catch ME
                    errorIdentifier = string(ME.identifier);
                    if strlength(errorIdentifier) == 0
                        errorIdentifier = ...
                            "sixgr:pdsch:PDSCHFocusedTests:UntypedError";
                    end
                    errorMessage = string(ME.message);
                    passed = false;
                end
                duration = toc(started);
                status = string(sixgr.pdsch. ...
                    PDSCHPhaseFocusedTestExecutor.ternary( ...
                    passed, "PASS", "FAIL"));
                summaryRows(i) = struct( ...
                    "TestSuite", suite, ...
                    "Total", 1, ...
                    "Passed", double(passed), ...
                    "Failed", double(~passed), ...
                    "Skipped", 0, ...
                    "Blocked", 0, ...
                    "Status", status);
                row = sixgr.pdsch.PDSCHPhaseArtifactPublisher. ...
                    executionRow( ...
                    "focused_test_function", suite, ...
                    "direct_feval_one_call", status, duration, ...
                    detail + string( ...
                    sixgr.pdsch.PDSCHPhaseFocusedTestExecutor. ...
                    ternary(strlength(sourcePath) > 0, ...
                    " | " + sourcePath, "")), ...
                    errorIdentifier, errorMessage);
                if isempty(execution)
                    execution = row;
                else
                    execution = [execution; row]; %#ok<AGROW>
                end
            end
            summary = struct2table(summaryRows);
            clear pathCleanup
            path(priorPath);

            failed = execution(execution.Status ~= "PASS", :);
            if ~isempty(failed)
                details = failed.Source + "=" + failed.ErrorIdentifier ...
                    + ": " + failed.ErrorMessage;
                error("sixgr:pdsch:PDSCHFocusedTests:SuiteFailed", ...
                    "Focused production test failure(s): %s", ...
                    strjoin(cellstr(details), " | "));
            end
        end

        function names = requiredSuiteNames()
            names = [ ...
                "testPDSCHSchedulingAssignment"; ...
                "testPDSCHSPSAssignment"; ...
                "testPDSCHFDRAFromDecodedDCI"; ...
                "testPDSCHTDRAFromDecodedDCI"; ...
                "testPDSCHMCSResolver"; ...
                "testPDSCHPhaseEvidenceMCSFailClosed"; ...
                "testPDSCHConfigMaterializerNoMutation"; ...
                "testPDSCHDMRSInvalidCombinations"; ...
                "testPDSCHDMRSNoMutation"; ...
                "testPDSCHDMRSSymbolPositionVectors"; ...
                "testPDSCHDMRSPortTableVectors"; ...
                "testPDSCHDMRSSequenceIndependent"; ...
                "testPDSCHPTRSPresenceVectors"; ...
                "testPDSCHPTRSIndicesIndependent"; ...
                "testPDSCHPTRSPortAssociation"; ...
                "testPDSCHPTRSPhaseNoiseBenefit"; ...
                "testPDSCHReservedREUnionVectors"; ...
                "testPDSCHResourceOwnershipMap"; ...
                "testPDSCHNoDataDMRSPTRSReservedOverlap"; ...
                "testPDSCHExactGFromResourcePlan"; ...
                "testPDSCHRateMatchPatternIntegration"; ...
                "testPDSCHTBSAndBaseGraphVectors"; ...
                "testPDSCHTBCRCVectors"; ...
                "testPDSCHCodeBlockSegmentationIndependent"; ...
                "testPDSCHLDPCEncodingIndependent"; ...
                "testPDSCHRateMatchingIndependent"; ...
                "testPDSCHDLSCHNoNoiseRoundTrip"; ...
                "testPDSCHTwoCodewordCoding"; ...
                "testPDSCHScramblingIndependentVectors"; ...
                "testPDSCHModulationIndependentVectors"; ...
                "testPDSCHSoftDemodulationLLRSign"; ...
                "testPDSCH1024QAMRoundTrip"; ...
                "testPDSCHLayerMappingIndependentVectors"; ...
                "testPDSCHRank1To8NoNoiseRoundTrip"; ...
                "testPDSCHPrecoderBundleVectors"; ...
                "testPDSCHPRGMatrixMultiplicationIndependent"; ...
                "testPDSCHPRGDataDMRSPTRSConsistency"; ...
                "testPDSCHFrequencySelectivePrecoderEndToEnd"; ...
                "testPDSCHPrecoderPowerConservation"; ...
                "testPDSCHReceiverNoNoiseExact"; ...
                "testPDSCHReceiverNoSignal"; ...
                "testPDSCHReceiverAWGN"; ...
                "testPDSCHReceiverTDL"; ...
                "testPDSCHReceiverCDL"; ...
                "testPDSCHReceiverLLRScalingConvention"; ...
                "testPDSCHReceiverWrongRNTI"; ...
                "testPDSCHReceiverWrongScramblingIdentity"; ...
                "testPDSCHReceiverWrongDMRSPort"; ...
                "testPDSCHReceiverWrongPRGMap"; ...
                "testPDSCHFadingHighRank"; ...
                "testPDSCHBLERStopPolicy"; ...
                "testPDSCHHARQTransitionVectors"; ...
                "testPDSCHHARQPositionAwareCombining"; ...
                "testPDSCHHARQRVSequence0231"; ...
                "testPDSCHHARQNDIReset"; ...
                "testPDSCHHARQTwoCodewords"; ...
                "testPDSCHHARQRejectsWrongTB"; ...
                "testPDSCHHARQCombiningGain"; ...
                "testPDSCHActiveBWPBinding"; ...
                "testPDSCHCrossCarrierBinding"; ...
                "testPDSCHTCIStateBinding"; ...
                "testPDSCHQCLStatePropagation"; ...
                "testPDSCHTwoTRPTransmissionOccasions"; ...
                "testPDSCHDeclaredCoverageMatrix"; ...
                "testPDSCHPhaseRunnerHonesty"; ...
                "testCampaignPDSCHCalibrationBinding"; ...
                "testPDSCHArtifactGeneration"; ...
                "testPDSCH6GR"; ...
                "testPDSCH6GRMultiCodewordStudy"; ...
                "testPDSCHTwoCodewordHARQContext"; ...
                "testPDSCHCodewordLayerHighRank"; ...
                "testPDSCHStudyImmutableCodingPlans"; ...
                "testPDSCHGrantDrivenTxExact"; ...
                "testPDSCHLLRScalingConvention"; ...
                "testPDSCHMultiPortPrecoding"; ...
                "testMultiPortDMRSReceiverMetrics"; ...
                "testPDSCHSISORegression"; ...
                "testResourceAccountingExact"; ...
                "testHARQTBContextInvariants"; ...
                "testHARQSoftBufferPositionAware"; ...
                "testCodingLayoutContracts"; ...
                "testTransportBlockSizeExactness"];
        end
    end

    methods (Static, Access = private)
        function row = emptySummaryRow()
            row = struct( ...
                "TestSuite", "", "Total", 0, "Passed", 0, ...
                "Failed", 0, "Skipped", 0, "Blocked", 0, ...
                "Status", "");
        end

        function value = ternary(condition, whenTrue, whenFalse)
            if logical(condition)
                value = whenTrue;
            else
                value = whenFalse;
            end
        end
    end
end
