classdef PDSCHCalibrationFacadeAdapter
    %PDSCHCALIBRATIONFACADEADAPTER Freeze legacy calibration inputs.
    %
    % This adapter is the only bridge from the configuration-oriented
    % PDSCH_Tx/PDSCH_Rx signatures to the canonical assignment-owned
    % production chain.  It performs no coding, scrambling, modulation,
    % layer mapping, precoding, grid mapping, OFDM processing, channel
    % estimation, equalization, or decoding.

    methods (Static)
        function ownership = resolveMCSOwnership(cfg, phyGrant, numCodewords)
            arguments
                cfg (1,1) struct
                phyGrant (1,1) struct
                numCodewords (1,1) double {mustBeInteger,mustBeInRange(numCodewords,1,2)}
            end
            ownership = localResolveMCSOwnership( ...
                cfg, phyGrant, numCodewords);
        end

        function bundle = materialize(cfg, carrier, pdsch, request)
            arguments
                cfg (1,1) struct
                carrier (1,1) nrCarrierConfig
                pdsch (1,1) nrPDSCHConfig
                request (1,1) struct
            end

            request = localValidateRequest(request);
            [modulation, layerCount] = localCodewordGeometry(pdsch);
            numCodewords = numel(layerCount);
            if double(request.NumLayers) ~= double(pdsch.NumLayers)
                error("sixgr:pdsch:CalibrationNumLayersMismatch", ...
                    ("Calibration MCS context NumLayers must equal the " + ...
                    "materialized PDSCH rank."));
            end
            receiverOnly = logical(request.ReceiverOnly);
            suppliedCodingPlans = localSuppliedCodingPlans( ...
                request.CodingPlans, numCodewords, receiverOnly);
            if receiverOnly
                targetRateRequested = cellfun( ...
                    @(plan) double(plan.TargetCodeRate), ...
                    suppliedCodingPlans);
                rv = cellfun(@(plan) double(plan.RV), ...
                    suppliedCodingPlans);
                localAssertOptionalExactVector( ...
                    request.TargetCodeRate, targetRateRequested, ...
                    "sixgr:pdsch:CalibrationCodingPlanRateMismatch", ...
                    "TargetCodeRate");
                localAssertOptionalExactVector( ...
                    request.RV, rv, ...
                    "sixgr:pdsch:CalibrationCodingPlanRVMismatch", ...
                    "RV");
            else
                targetRateRequested = localExactPerCodeword( ...
                    request.TargetCodeRate, numCodewords, ...
                    "sixgr:pdsch:CalibrationCodeRateCountMismatch");
                rv = localPerCodeword(request.RV, numCodewords, ...
                    "sixgr:pdsch:CalibrationRVCountMismatch");
            end
            if any(rv ~= fix(rv) | rv < 0 | rv > 3)
                error("sixgr:phy:dl:PDSCHBadRV", ...
                    "Calibration PDSCH RV must contain integers in [0,3].");
            end
            xOverhead = double(request.XOverhead);
            if ~(isscalar(xOverhead) && isfinite(xOverhead) ...
                    && ismember(xOverhead, [0 6 12 18]))
                error("sixgr:pdsch:InvalidXOverhead", ...
                    "Calibration XOverhead must be one of 0, 6, 12, or 18.");
            end

            [mcsTable, mcsIndex, mcsProfiles] = ...
                localExactTableBackedMCS(request, modulation, ...
                targetRateRequested);
            targetRate = double([mcsProfiles.TargetCodeRate]);
            qm = double([mcsProfiles.Qm]);

            ports = double(pdsch.DMRS.DMRSPortSet(:).');
            if isempty(ports)
                policy = string(request.DMRSPortResolutionPolicy);
                if policy ~= ...
                        "explicit_calibration_rank_order_ports"
                    error("sixgr:pdsch:MissingCalibrationDMRSPortSet", ...
                        "Calibration requires an explicit DM-RS port set " + ...
                        "or the named explicit_calibration_rank_order_ports " + ...
                        "factory policy.");
                end
                % The named calibration policy is frozen into provenance;
                % canonical execution never sees an empty/unowned default.
                ports = 0:(double(pdsch.NumLayers) - 1);
                pdsch.DMRS.DMRSPortSet = ports;
            end
            if numel(ports) ~= double(pdsch.NumLayers)
                error("sixgr:pdsch:DMRSPortLayerCountMismatch", ...
                    "Calibration requires one explicit DM-RS port per layer.");
            end

            [dmrsIndices, dmrsSymbols] = localDMRS( ...
                carrier, pdsch, ports, request.DMRSAmplitudeScale);
            [ptrsIndices, ptrsSymbols, ptrsPorts] = localPTRS( ...
                carrier, pdsch, double(pdsch.NumLayers));
            [dataIndices, dataIndicesInfo] = ...
                localDataIndices(carrier, pdsch);
            allocation = localAllocation(carrier, ...
                double(pdsch.PRBSet(:).'), ...
                double(pdsch.SymbolAllocation(:).'));
            referenceUnion = unique( ...
                [dmrsIndices{:}, ptrsIndices{:}], "sorted");
            accounted = unique([dataIndices, referenceUnion], "sorted");
            implicitReserved = setdiff(allocation, accounted, "stable");
            explicitReserved = double(request.ReservedREZeroBased(:).');
            if any(~ismember(explicitReserved, allocation))
                error("sixgr:pdsch:ReservedREOutsideAllocation", ...
                    "A calibration reservation lies outside the PDSCH allocation.");
            end
            reservation = unique( ...
                [implicitReserved, explicitReserved], "sorted");
            ownership = sixgr.pdsch.PDSCHResourceOwnershipMap( ...
                allocation, struct("Other", reservation));

            [legacyPrecoder, precoderBundle] = localPrecoder( ...
                cfg, pdsch, request.PrecodingMatrix);
            nPhysicalPorts = double(legacyPrecoder.NumWaveformColumns);
            if isempty(precoderBundle)
                nPhysicalPorts = double(pdsch.NumLayers);
            end
            [windowingSamples, windowingInfo] = ...
                sixgr.phy.waveform.resolveOFDMWindowing(cfg, carrier);
            referenceData = localMaterializerReference(carrier,pdsch);
            referenceData.DataScramblingIdentityNID = double(pdsch.NID);
            referenceData.DMRSMultiplexing = char(string( ...
                sixgr.util.structGet(cfg, ...
                "phy.pdsch.dmrs.multiplexing", "basic")));
            referenceData.NPhysicalTxAntennas = nPhysicalPorts;
            referenceData.OFDMOptions = { ...
                "Windowing", double(windowingSamples)};
            referenceData.DMRSAmplitudeScale = ...
                double(request.DMRSAmplitudeScale);
            referenceData.PTRSAmplitudeScale = 1;
            referenceConfig = ...
                sixgr.pdsch.PDSCHReferenceSignalConfig(referenceData);

            provisionalContext = localPlanContext( ...
                carrier, pdsch, dmrsIndices, ptrsIndices, ...
                ports, layerCount, qm, ones(1, numCodewords), ...
                referenceConfig.ConfigurationDigest);
            provisionalPlan = sixgr.pdsch.PDSCHResourcePlan( ...
                ownership, provisionalContext);
            if ~isequal(double(provisionalPlan.DataIndices(:).'), ...
                    double(dataIndices(:).'))
                error("sixgr:pdsch:CalibrationResourcePlanMismatch", ...
                    "The immutable calibration resource plan differs from " + ...
                    "the final PDSCH data-index kernel output.");
            end

            if receiverOnly
                tbs = cellfun( ...
                    @(plan) double(plan.TransportBlockSize), ...
                    suppliedCodingPlans);
                scheduledTBS = tbs;
                localAssertOptionalExactVector( ...
                    request.TransportBlockSizes, tbs, ...
                    "sixgr:pdsch:CalibrationCodingPlanTBSMismatch", ...
                    "TransportBlockSizes");
            else
                [scheduledTBS, tbs] = localTransportBlockSizes( ...
                    pdsch, provisionalPlan, ...
                    double(dataIndicesInfo.NREPerPRB), ...
                    targetRateRequested, xOverhead, ...
                    request.TransportBlockSizes);
            end
            nrePerPRBForTBS = localNREPerPRBForTBS( ...
                dataIndicesInfo.NREPerPRB);
            codingPlans = cell(1, numCodewords);
            codeBlockCounts = zeros(1, numCodewords);
            for cw = 1:numCodewords
                if receiverOnly
                    codingPlans{cw} = suppliedCodingPlans{cw};
                    localAssertSuppliedCodingPlan( ...
                        codingPlans{cw}, cw - 1, tbs(cw), ...
                        targetRate(cw), ...
                        provisionalPlan.GPerCodeword(cw), rv(cw), ...
                        modulation(cw), layerCount(cw));
                else
                    codingPlans{cw} = sixgr.pdsch.DLSCHCodingPlan.resolve( ...
                        "TransportBlockSize", tbs(cw), ...
                        "TargetCodeRate", targetRate(cw), ...
                        "RateMatchedBitCount", ...
                            provisionalPlan.GPerCodeword(cw), ...
                        "RV", rv(cw), ...
                        "Modulation", modulation(cw), ...
                        "NumLayers", layerCount(cw), ...
                        "CodewordIndex", cw - 1);
                end
                codeBlockCounts(cw) = ...
                    double(codingPlans{cw}.NumCodeBlocks);
            end
            finalContext = provisionalContext;
            finalContext.CodeBlockCountPerCodeword = codeBlockCounts;
            resourcePlan = sixgr.pdsch.PDSCHResourcePlan( ...
                ownership, finalContext);
            if ~isequal(resourcePlan.GPerCodeword, ...
                    provisionalPlan.GPerCodeword)
                error("sixgr:pdsch:CalibrationGContractMutation", ...
                    "Code-block resolution changed the exact G contract.");
            end

            assignmentRequest = localAssignmentRequest( ...
                carrier, pdsch, mcsTable, mcsIndex, mcsProfiles, ...
                layerCount, ports, ptrsPorts, rv, xOverhead, request);
            absoluteSlot = localAbsoluteSlot(carrier);
            if request.ExecutionProfile == "scheduler_truth"
                assignmentRequest = localApplySchedulerTruthAssignmentContext( ...
                    assignmentRequest, request.SchedulerGrantContext, absoluteSlot);
                assignment = sixgr.pdsch.PDSCHAssignmentFactory.forSchedulerTruth( ...
                    assignmentRequest, struct( ...
                        "AbsoluteSlot", absoluteSlot, ...
                        "ResourceAvailable", true));
            else
                assignment = sixgr.pdsch.PDSCHAssignmentFactory.forCalibration( ...
                    assignmentRequest, struct( ...
                        "AbsoluteSlot", absoluteSlot, ...
                        "ResourceAvailable", true));
            end

            materializedPDSCH = ...
                sixgr.pdsch.PDSCHConfigMaterializer.fromAssignment( ...
                    assignment, referenceData);
            localAssertPDSCHUnchanged(materializedPDSCH, pdsch);

            transportBlocks = localTransportBlocks( ...
                request.TransportBlockBits, tbs, ...
                receiverOnly);
            receiverConfig = localReceiverConfig( ...
                cfg, request, tbs, nPhysicalPorts, ...
                legacyPrecoder, carrier, referenceConfig);

            bundle = struct( ...
                "ContractVersion", ...
                    "PDSCHExplicitGrantFacadeAdapter/v2", ...
                "Assignment", assignment, ...
                "ResourcePlan", resourcePlan, ...
                "Carrier", carrier, ...
                "PDSCH", pdsch, ...
                "ReferenceConfig", referenceConfig, ...
                "ReferenceData", referenceData, ...
                "ReceiverConfig", receiverConfig, ...
                "PrecoderBundle", precoderBundle, ...
                "LegacyPrecoder", legacyPrecoder, ...
                "TransportBlocks", {transportBlocks}, ...
                "TransportBlockSizes", tbs, ...
                "ScheduledTransportBlockSizes", scheduledTBS, ...
                "NREPerPRBForTBS", nrePerPRBForTBS, ...
                "RequestedTargetCodeRate", targetRateRequested, ...
                "TargetCodeRate", targetRate, ...
                "RV", rv, ...
                "XOverhead", xOverhead, ...
                "CodingPlans", {codingPlans}, ...
                "DMRSIndicesPerPort", {dmrsIndices}, ...
                "DMRSSymbolsPerPort", {dmrsSymbols}, ...
                "PTRSIndicesPerPort", {ptrsIndices}, ...
                "PTRSSymbolsPerPort", {ptrsSymbols}, ...
                "WindowingInfo", windowingInfo, ...
                "DMRSPortResolutionPolicy", ...
                    string(request.DMRSPortResolutionPolicy), ...
                "Source", localExplicitGrantAdapterSource( ...
                    request.ExecutionProfile));
        end
    end
end

function ownership = localResolveMCSOwnership(cfg, phyGrant, count)
hasGrant = ~isempty(fieldnames(phyGrant));
if hasGrant
    [tables, tableSource] = localFirstPresent(phyGrant, [ ...
        "CodingLayout.MCSTablePerCodeword", ...
        "MCSTablePerCodeword", ...
        "CodingLayout.MCSTable", ...
        "MCSTable"]);
    [indices, indexSource] = localFirstPresent(phyGrant, [ ...
        "CodingLayout.MCSIndexPerCodeword", ...
        "MCSIndexPerCodeword", ...
        "CodingLayout.MCSIndex", ...
        "MCSIndex", "MCS"]);
    ownerPrefix = "PHYGrant.";
else
    [tables, tableSource] = localFirstPresent(cfg, [ ...
        "phy.pdsch.mcsTablePerCodeword", ...
        "phy.pdsch.mcsTable"]);
    [indices, indexSource] = localFirstPresent(cfg, [ ...
        "phy.pdsch.mcsIndexPerCodeword", ...
        "phy.pdsch.mcsIndex", ...
        "phy.pdsch.configuredMCSIndex"]);
    ownerPrefix = "cfg.";
end
tables = string(tables);
tables = tables(:).';
indices = double(indices(:).');
if numel(tables) ~= count || any(strlength(strtrim(tables)) == 0)
    error("sixgr:pdsch:MissingCodewordSpecificMCS", ...
        "%s calibration ownership must provide exactly %d explicit " + ...
        "MCS table token(s), one per codeword.", ...
        ownerPrefix, count);
end
if numel(indices) ~= count || any(~isfinite(indices) ...
        | indices ~= fix(indices) | indices < 0)
    error("sixgr:pdsch:MissingCodewordSpecificMCS", ...
        "%s calibration ownership must provide exactly %d explicit " + ...
        "nonnegative integer MCS index token(s), one per codeword.", ...
        ownerPrefix, count);
end

logicalNames = [ ...
    "UECapability1024QAM","RRCEnabled1024QAM", ...
    "DCIEnabled1024QAM","DeploymentAllows1024QAM", ...
    "FrequencyRangeAllows1024QAM","BandAllows1024QAM"];
logicalPaths = { ...
    ["UECapability1024QAM", ...
     "MCSContext.UECapability1024QAM", ...
     "LegacyGrantSnapshot.UECapability1024QAM", ...
     "LegacyGrantSnapshot.MCSContext.UECapability1024QAM", ...
     "phy.pdsch.UECapability1024QAM", ...
     "phy.pdsch.mcsContext.UECapability1024QAM"], ...
    ["RRCEnabled1024QAM", ...
     "MCSContext.RRCEnabled1024QAM", ...
     "LegacyGrantSnapshot.RRCEnabled1024QAM", ...
     "LegacyGrantSnapshot.MCSContext.RRCEnabled1024QAM", ...
     "phy.pdsch.RRCEnabled1024QAM", ...
     "phy.pdsch.mcsContext.RRCEnabled1024QAM"], ...
    ["DCIEnabled1024QAM", ...
     "MCSContext.DCIEnabled1024QAM", ...
     "LegacyGrantSnapshot.DCIEnabled1024QAM", ...
     "LegacyGrantSnapshot.MCSContext.DCIEnabled1024QAM", ...
     "phy.pdsch.DCIEnabled1024QAM", ...
     "phy.pdsch.mcsContext.DCIEnabled1024QAM"], ...
    ["DeploymentAllows1024QAM", ...
     "MCSContext.DeploymentAllows1024QAM", ...
     "LegacyGrantSnapshot.DeploymentAllows1024QAM", ...
     "LegacyGrantSnapshot.MCSContext.DeploymentAllows1024QAM", ...
     "phy.pdsch.DeploymentAllows1024QAM", ...
     "phy.pdsch.mcsContext.DeploymentAllows1024QAM"], ...
    ["FrequencyRangeAllows1024QAM", ...
     "MCSContext.FrequencyRangeAllows1024QAM", ...
     "LegacyGrantSnapshot.FrequencyRangeAllows1024QAM", ...
     "LegacyGrantSnapshot.MCSContext.FrequencyRangeAllows1024QAM", ...
     "phy.pdsch.FrequencyRangeAllows1024QAM", ...
     "phy.pdsch.mcsContext.FrequencyRangeAllows1024QAM"], ...
    ["BandAllows1024QAM", ...
     "MCSContext.BandAllows1024QAM", ...
     "LegacyGrantSnapshot.BandAllows1024QAM", ...
     "LegacyGrantSnapshot.MCSContext.BandAllows1024QAM", ...
     "phy.pdsch.BandAllows1024QAM", ...
     "phy.pdsch.mcsContext.BandAllows1024QAM"]};
if hasGrant
    contextRoot = phyGrant;
else
    contextRoot = cfg;
end
contextSources = strings(1,numel(logicalNames));
for idx = 1:numel(logicalNames)
    [value, source] = localFirstPresent( ...
        contextRoot, logicalPaths{idx});
    if isempty(value) && hasGrant
        [value, source] = localFirstPresent(cfg, [ ...
            "phy.pdsch." + logicalNames(idx), ...
            "phy.pdsch.mcsContext." + logicalNames(idx)]);
        if ~isempty(value)
            source = "cfg." + source;
        end
    end
    if isempty(value)
        error("sixgr:pdsch:Incomplete1024QAMCapabilityContext", ...
            "Calibration ownership must explicitly provide %s as a " + ...
            "logical scalar, including when the selected MCS is below " + ...
            "1024QAM.", logicalNames(idx));
    end
    if ~(islogical(value) && isscalar(value))
        error("sixgr:pdsch:Invalid1024QAMCapabilityContext", ...
            "%s must be an explicit logical scalar.", logicalNames(idx));
    end
    ownership.(logicalNames(idx)) = value;
    contextSources(idx) = source;
end

textNames = ["FrequencyRange","OperatingBand","DeploymentClass"];
textPaths = { ...
    ["FrequencyRange","MCSContext.FrequencyRange", ...
     "LegacyGrantSnapshot.FrequencyRange", ...
     "LegacyGrantSnapshot.MCSContext.FrequencyRange", ...
     "phy.pdsch.FrequencyRange", ...
     "phy.pdsch.mcsContext.FrequencyRange"], ...
    ["OperatingBand","MCSContext.OperatingBand", ...
     "LegacyGrantSnapshot.OperatingBand", ...
     "LegacyGrantSnapshot.MCSContext.OperatingBand", ...
     "phy.pdsch.OperatingBand", ...
     "phy.pdsch.mcsContext.OperatingBand"], ...
    ["DeploymentClass","MCSContext.DeploymentClass", ...
     "LegacyGrantSnapshot.DeploymentClass", ...
     "LegacyGrantSnapshot.MCSContext.DeploymentClass", ...
     "phy.pdsch.DeploymentClass", ...
     "phy.pdsch.mcsContext.DeploymentClass"]};
textSources = strings(1,numel(textNames));
for idx = 1:numel(textNames)
    [value, source] = localFirstPresent(contextRoot, textPaths{idx});
    if isempty(value) && hasGrant
        [value, source] = localFirstPresent(cfg, [ ...
            "phy.pdsch." + textNames(idx), ...
            "phy.pdsch.mcsContext." + textNames(idx)]);
        if ~isempty(value)
            source = "cfg." + source;
        end
    end
    if isempty(value)
        error("sixgr:pdsch:Incomplete1024QAMDeploymentContext", ...
            "Calibration ownership must explicitly provide nonempty %s, " + ...
            "including when the selected MCS is below 1024QAM.", ...
            textNames(idx));
    end
    value = string(value);
    if ~isscalar(value) || strlength(strtrim(value)) == 0
        error("sixgr:pdsch:Invalid1024QAMDeploymentContext", ...
            "%s must be a nonempty string scalar.", textNames(idx));
    end
    ownership.(textNames(idx)) = value;
    textSources(idx) = source;
end

[dciFormat, dciFormatSource] = localFirstPresent(contextRoot, [ ...
    "DCIFormat", ...
    "MCSContext.DCIFormat", ...
    "CodingLayout.DCIFormat", ...
    "LegacyGrantSnapshot.DCIFormat", ...
    "LegacyGrantSnapshot.MCSContext.DCIFormat", ...
    "LegacyGrantSnapshot.CodingLayout.DCIFormat", ...
    "phy.pdsch.DCIFormat", ...
    "phy.pdsch.mcsContext.DCIFormat"]);
if isempty(dciFormat) && hasGrant
    [dciFormat, dciFormatSource] = localFirstPresent(cfg, [ ...
        "phy.pdsch.DCIFormat", ...
        "phy.pdsch.mcsContext.DCIFormat"]);
    if ~isempty(dciFormat)
        dciFormatSource = "cfg." + dciFormatSource;
    end
end
if isempty(dciFormat)
    % This token is intentionally not a 1024QAM-enabling DCI format. The
    % MCS resolver therefore remains fail closed for 1024QAM while legacy
    % non-1024 calibration points retain explicit provenance.
    dciFormat = "not_applicable_calibration";
    dciFormatSource = "adapter.explicit_non_1024_fail_closed_token";
end
dciFormat = string(dciFormat);
if ~isscalar(dciFormat) || strlength(strtrim(dciFormat)) == 0
    error("sixgr:pdsch:InvalidCalibrationDCIFormat", ...
        "Calibration DCIFormat must be a nonempty string scalar.");
end
ownership.DCIFormat = dciFormat;
[capabilityVariant, capabilityVariantSource] = localFirstPresent( ...
    contextRoot, [ ...
    "UECapability1024QAMVariant", ...
    "MCSContext.UECapability1024QAMVariant", ...
    "LegacyGrantSnapshot.UECapability1024QAMVariant", ...
    "LegacyGrantSnapshot.MCSContext.UECapability1024QAMVariant", ...
    "phy.pdsch.UECapability1024QAMVariant", ...
    "phy.pdsch.mcsContext.UECapability1024QAMVariant"]);
if isempty(capabilityVariant) && hasGrant
    [capabilityVariant, capabilityVariantSource] = localFirstPresent( ...
        cfg, [ ...
        "phy.pdsch.UECapability1024QAMVariant", ...
        "phy.pdsch.mcsContext.UECapability1024QAMVariant"]);
    if ~isempty(capabilityVariant)
        capabilityVariantSource = "cfg." + capabilityVariantSource;
    end
end
if isempty(capabilityVariant)
    capabilityVariant = "";
    capabilityVariantSource = ...
        "adapter.explicit_non_1024_empty_capability_variant";
end
capabilityVariant = string(capabilityVariant);
if ~isscalar(capabilityVariant)
    error("sixgr:pdsch:Invalid1024QAMCapabilityVariant", ...
        "UECapability1024QAMVariant must be a string scalar.");
end
ownership.UECapability1024QAMVariant = capabilityVariant;

[maxMIMOLayers, maxMIMOLayersSource] = localFirstPresent( ...
    contextRoot, [ ...
    "MaxNumberMIMOLayersPDSCH", ...
    "MCSContext.MaxNumberMIMOLayersPDSCH", ...
    "LegacyGrantSnapshot.MaxNumberMIMOLayersPDSCH", ...
    "LegacyGrantSnapshot.MCSContext.MaxNumberMIMOLayersPDSCH", ...
    "phy.pdsch.MaxNumberMIMOLayersPDSCH", ...
    "phy.pdsch.mcsContext.MaxNumberMIMOLayersPDSCH"]);
if isempty(maxMIMOLayers) && hasGrant
    [maxMIMOLayers, maxMIMOLayersSource] = localFirstPresent(cfg, [ ...
        "phy.pdsch.MaxNumberMIMOLayersPDSCH", ...
        "phy.pdsch.mcsContext.MaxNumberMIMOLayersPDSCH"]);
    if ~isempty(maxMIMOLayers)
        maxMIMOLayersSource = "cfg." + maxMIMOLayersSource;
    end
end
if isempty(maxMIMOLayers)
    maxMIMOLayers = NaN;
    maxMIMOLayersSource = ...
        "adapter.explicit_non_1024_nan_max_mimo_layers";
end
maxMIMOLayers = double(maxMIMOLayers);
if ~(isscalar(maxMIMOLayers) && (isnan(maxMIMOLayers) ...
        || (isfinite(maxMIMOLayers) && maxMIMOLayers == ...
        fix(maxMIMOLayers) && maxMIMOLayers >= 1)))
    error("sixgr:pdsch:Invalid1024QAMMaxNumberMIMOLayersPDSCH", ...
        ("MaxNumberMIMOLayersPDSCH must be NaN for non-1024 " + ...
        "calibration or a positive integer capability."));
end
ownership.MaxNumberMIMOLayersPDSCH = maxMIMOLayers;
ownership.MCSTablePerCodeword = tables;
ownership.MCSIndexPerCodeword = indices;
ownership.OwnershipSource = struct( ...
    "Table", ownerPrefix + tableSource, ...
    "Index", ownerPrefix + indexSource, ...
    "Capability", contextSources, ...
    "Deployment", textSources, ...
    "DCIFormat", dciFormatSource, ...
    "CapabilityVariant", capabilityVariantSource, ...
    "MaxNumberMIMOLayersPDSCH", maxMIMOLayersSource);
end

function [value, source] = localFirstPresent(valueStruct, paths)
value = [];
source = "";
for idx = 1:numel(paths)
    [candidate, present] = localGetPath(valueStruct, paths(idx));
    if present && ~isempty(candidate)
        value = candidate;
        source = paths(idx);
        return;
    end
end
end

function [value, present] = localGetPath(valueStruct, path)
parts = split(string(path), ".");
value = valueStruct;
present = true;
for idx = 1:numel(parts)
    name = char(parts(idx));
    if ~isstruct(value) || ~isscalar(value) || ~isfield(value,name)
        value = [];
        present = false;
        return;
    end
    value = value.(name);
end
end

function request = localValidateRequest(request)
required = ["TargetCodeRate","RV","XOverhead", ...
    "MCSTablePerCodeword","MCSIndexPerCodeword", ...
    "UECapability1024QAM","RRCEnabled1024QAM", ...
    "DCIEnabled1024QAM","DCIFormat","DeploymentAllows1024QAM", ...
    "UECapability1024QAMVariant","MaxNumberMIMOLayersPDSCH", ...
    "NumLayers", ...
    "FrequencyRange","OperatingBand","DeploymentClass", ...
    "FrequencyRangeAllows1024QAM","BandAllows1024QAM", ...
    "TransportBlockSizes","TransportBlockBits","CodingPlans", ...
    "PrecodingMatrix", ...
    "ReservedREZeroBased","DMRSAmplitudeScale", ...
    "DMRSPortResolutionPolicy", ...
    "NPhysicalRxAntennas","NoiseVariance","NoiseVarianceDomain", ...
    "MaxIterations","Algorithm"];
missing = required(~isfield(request, required));
if ~isempty(missing)
    error("sixgr:pdsch:IncompleteCalibrationFacadeRequest", ...
        "Calibration façade request is missing: %s.", ...
        strjoin(cellstr(missing), ", "));
end
if ~isfield(request, "ExecutionProfile")
    request.ExecutionProfile = "phy_calibration";
end
request.ExecutionProfile = lower(strtrim(string(request.ExecutionProfile)));
if ~any(request.ExecutionProfile == ["phy_calibration","scheduler_truth"])
    error("sixgr:pdsch:InvalidExplicitGrantAdapterProfile", ...
        "Explicit grant adapter profile '%s' is unsupported.", ...
        request.ExecutionProfile);
end
if ~isfield(request, "SchedulerGrantContext")
    request.SchedulerGrantContext = struct();
end
if request.ExecutionProfile == "scheduler_truth" && ...
        ~(isstruct(request.SchedulerGrantContext) && ...
        ~isempty(fieldnames(request.SchedulerGrantContext)))
    error("sixgr:pdsch:MissingSchedulerTruthGrantContext", ...
        "scheduler_truth materialization requires the decoded scheduler grant context.");
end
capabilityFields = [ ...
    "UECapability1024QAM","RRCEnabled1024QAM", ...
    "DCIEnabled1024QAM","DeploymentAllows1024QAM", ...
    "FrequencyRangeAllows1024QAM","BandAllows1024QAM"];
for idx = 1:numel(capabilityFields)
    name = capabilityFields(idx);
    if ~(islogical(request.(name)) && isscalar(request.(name)))
        error("sixgr:pdsch:Incomplete1024QAMCapabilityContext", ...
            "%s must be present as an explicit logical scalar.", name);
    end
end
textFields = ["FrequencyRange","OperatingBand","DeploymentClass","DCIFormat"];
for idx = 1:numel(textFields)
    name = textFields(idx);
    value = string(request.(name));
    if ~isscalar(value)
        error("sixgr:pdsch:Invalid1024QAMDeploymentContext", ...
            "%s must be an explicit string scalar.", name);
    end
    request.(name) = value;
end
variant = string(request.UECapability1024QAMVariant);
if ~isscalar(variant)
    error("sixgr:pdsch:Invalid1024QAMCapabilityVariant", ...
        "UECapability1024QAMVariant must be a string scalar.");
end
request.UECapability1024QAMVariant = variant;
maxLayers = double(request.MaxNumberMIMOLayersPDSCH);
if ~(isscalar(maxLayers) && (isnan(maxLayers) ...
        || (isfinite(maxLayers) && maxLayers == fix(maxLayers) ...
        && maxLayers >= 1)))
    error("sixgr:pdsch:Invalid1024QAMMaxNumberMIMOLayersPDSCH", ...
        "MaxNumberMIMOLayersPDSCH must be NaN or a positive integer.");
end
request.MaxNumberMIMOLayersPDSCH = maxLayers;
numLayers = double(request.NumLayers);
if ~(isscalar(numLayers) && isfinite(numLayers) ...
        && numLayers == fix(numLayers) ...
        && numLayers >= 1 && numLayers <= 8)
    error("sixgr:pdsch:InvalidCalibrationNumLayers", ...
        "Calibration NumLayers must be an integer from 1 through 8.");
end
request.NumLayers = numLayers;
if ~isfield(request, "ReceiverOnly")
    request.ReceiverOnly = false;
end
scale = double(request.DMRSAmplitudeScale);
if ~(isscalar(scale) && isfinite(scale) && scale > 0)
    error("sixgr:phy:dl:PDSCHDMRSEPREDifferenceInvalid", ...
        "DM-RS calibration amplitude scale must be finite and positive.");
end
end

function [modulation, layerCount] = localCodewordGeometry(pdsch)
nLayers = double(pdsch.NumLayers);
if ~(isscalar(nLayers) && isfinite(nLayers) ...
        && nLayers == fix(nLayers) && nLayers >= 1 && nLayers <= 8)
    error("sixgr:phy:dl:PDSCHCodewordLayerScope", ...
        "PDSCH supports ranks 1-8 in this calibration path.");
end
if nLayers <= 4
    layerCount = nLayers;
else
    splits = {[2 3], [3 3], [3 4], [4 4]};
    layerCount = splits{nLayers - 4};
end
modulation = string(pdsch.Modulation);
modulation = upper(strrep(strtrim(modulation(:).'), " ", ""));
if numel(modulation) ~= numel(layerCount)
    error("sixgr:phy:dl:PDSCHMissingCodewordSpecificModulation", ...
        "Calibration requires one modulation token per codeword.");
end
supported = ["QPSK","16QAM","64QAM","256QAM","1024QAM"];
if any(~ismember(modulation, supported))
    error("sixgr:pdsch:UnsupportedNRModulation", ...
        "Calibration contains an unsupported PDSCH modulation.");
end
end

function values = localPerCodeword(raw, count, identifier)
values = double(raw(:).');
if isscalar(values) && count > 1
    values = repmat(values, 1, count);
end
if numel(values) ~= count || any(~isfinite(values))
    error(identifier, ...
        "Calibration requires exactly %d finite codeword values.", count);
end
end

function values = localExactPerCodeword(raw,count,identifier)
values = double(raw(:).');
if numel(values) ~= count || any(~isfinite(values))
    error(identifier, ...
        ("Calibration requires exactly %d finite codeword values; " + ...
        "scalar replication across enabled codewords is forbidden."), ...
        count);
end
end

function plans = localSuppliedCodingPlans(raw,count,receiverOnly)
if isempty(raw)
    if receiverOnly
        error("sixgr:pdsch:CalibrationReceiverMissingCodingPlan", ...
            ("Calibration RX requires the immutable DLSCHCodingPlan " + ...
            "object(s) produced by the matching transmitter."));
    end
    plans = cell(1,0);
    return;
end
if isa(raw,"sixgr.pdsch.DLSCHCodingPlan")
    plans = num2cell(reshape(raw,1,[]));
elseif iscell(raw)
    plans = reshape(raw,1,[]);
else
    error("sixgr:pdsch:CalibrationReceiverInvalidCodingPlan", ...
        "CodingPlans must contain immutable DLSCHCodingPlan objects.");
end
if numel(plans) ~= count
    error("sixgr:pdsch:CalibrationReceiverCodingPlanCountMismatch", ...
        "Calibration RX requires exactly %d coding plan(s).",count);
end
for cw = 1:count
    plan = plans{cw};
    if ~isa(plan,"sixgr.pdsch.DLSCHCodingPlan") ...
            || ~isscalar(plan) || ~logical(plan.Immutable) ...
            || strlength(string(plan.PlanID)) == 0 ...
            || strlength(string(plan.CodingLayoutHash)) == 0
        error("sixgr:pdsch:CalibrationReceiverInvalidCodingPlan", ...
            ("Calibration RX coding plan %d must be one immutable " + ...
            "DLSCHCodingPlan with a nonempty PlanID and layout hash."), ...
            cw-1);
    end
end
end

function localAssertOptionalExactVector(raw,expected,identifier,name)
if isempty(raw)
    return;
end
actual = double(raw(:).');
expected = double(expected(:).');
if numel(actual) ~= numel(expected) || any(~isfinite(actual)) ...
        || any(abs(actual-expected) > 1e-12)
    error(identifier, ...
        ("Calibration RX %s must exactly match the supplied immutable " + ...
        "coding plan(s)."),name);
end
end

function localAssertSuppliedCodingPlan(plan,codewordIndex,tbs,rate,g,rv, ...
        modulation,numLayers)
matches = double(plan.CodewordIndex) == double(codewordIndex) ...
    && double(plan.TransportBlockSize) == double(tbs) ...
    && abs(double(plan.TargetCodeRate)-double(rate)) <= 1e-12 ...
    && double(plan.RateMatchedBitCount) == double(g) ...
    && double(plan.RV) == double(rv) ...
    && upper(string(plan.Modulation)) == upper(string(modulation)) ...
    && double(plan.NumLayers) == double(numLayers);
if ~matches
    error("sixgr:pdsch:CalibrationReceiverCodingPlanMismatch", ...
        ("Calibration RX coding plan %d differs from the immutable " + ...
        "assignment/resource/codeword contract."),codewordIndex);
end
layout = plan.toCodingLayout();
required = ["BaseGraph","FillerPositions","RV", ...
    "TransportBlockSize","RateMatchedBitCount","CodingLayoutHash"];
missing = required(~isfield(layout,required));
if ~isempty(missing)
    error("sixgr:pdsch:CalibrationReceiverIncompleteCodingPlan", ...
        "Coding plan %d layout is missing: %s.",codewordIndex, ...
        strjoin(cellstr(missing),", "));
end
if string(layout.CodingLayoutHash) ~= string(plan.CodingLayoutHash)
    error("sixgr:pdsch:CalibrationReceiverCodingPlanMismatch", ...
        "Coding plan %d layout hash does not match its immutable identity.", ...
        codewordIndex);
end
end

function [tableNames, indices, profiles] = ...
        localExactTableBackedMCS(request, modulation, requestedRates)
count = numel(modulation);
tableNames = string(request.MCSTablePerCodeword);
tableNames = tableNames(:).';
indices = double(request.MCSIndexPerCodeword(:).');
if numel(tableNames) ~= count || any(strlength(strtrim(tableNames)) == 0) ...
        || numel(indices) ~= count || any(~isfinite(indices) ...
        | indices ~= fix(indices) | indices < 0)
    error("sixgr:pdsch:MissingCodewordSpecificMCS", ...
        ("Calibration requires exactly one explicit nonempty MCS table " + ...
        "and nonnegative integer MCS index per codeword."));
end
context = struct( ...
    "NumCodewords", count, ...
    "RNTIType", "C-RNTI", ...
    "SelectionSource", char(localExplicitGrantAdapterSource( ...
        request.ExecutionProfile)), ...
    "UECapability1024QAM", request.UECapability1024QAM, ...
    "RRCEnabled1024QAM", request.RRCEnabled1024QAM, ...
    "DCIEnabled1024QAM", request.DCIEnabled1024QAM, ...
    "DCIFormat", request.DCIFormat, ...
    "UECapability1024QAMVariant", ...
        request.UECapability1024QAMVariant, ...
    "MaxNumberMIMOLayersPDSCH", ...
        request.MaxNumberMIMOLayersPDSCH, ...
    "NumLayers", request.NumLayers, ...
    "DeploymentAllows1024QAM", ...
        request.DeploymentAllows1024QAM, ...
    "FrequencyRange", request.FrequencyRange, ...
    "OperatingBand", request.OperatingBand, ...
    "DeploymentClass", request.DeploymentClass, ...
    "FrequencyRangeAllows1024QAM", ...
        request.FrequencyRangeAllows1024QAM, ...
    "BandAllows1024QAM", request.BandAllows1024QAM, ...
    "ExecutionProfile", char(request.ExecutionProfile), ...
    "CalibrationTokenPerCodeword", tableNames, ...
    "CalibrationModulationPerCodeword", modulation, ...
    "CalibrationQmPerCodeword", arrayfun(@localQm, modulation), ...
    "CalibrationTargetCodeRatePerCodeword", requestedRates);
profiles = sixgr.pdsch.PDSCHMCSResolver.resolve( ...
    tableNames, indices, context);
resolvedModulation = upper(string({profiles.Modulation}));
if ~isequal(resolvedModulation, modulation)
    error("sixgr:pdsch:CalibrationMCSModulationMismatch", ...
        ("Explicit MCS table/index resolves modulation %s, but the " + ...
        "PDSCH configuration selects %s."), ...
        strjoin(resolvedModulation, ","), strjoin(modulation, ","));
end
resolvedRates = double([profiles.TargetCodeRate]);
if any(abs(resolvedRates - requestedRates) > 1e-12)
    error("sixgr:pdsch:CalibrationMCSRateMismatch", ...
        ("Explicit MCS table/index resolves target rate %s, but the " + ...
        "calibration request selects %s. Calibration does not substitute " + ...
        "a nearest MCS."), ...
        mat2str(resolvedRates, 15), mat2str(requestedRates, 15));
end
end

function qm = localQm(modulation)
switch upper(string(modulation))
    case "QPSK", qm = 2;
    case "16QAM", qm = 4;
    case "64QAM", qm = 6;
    case "256QAM", qm = 8;
    case "1024QAM", qm = 10;
end
end

function [indices, symbols] = localDMRS(carrier, pdsch, ports, scale)
sub = nrPDSCHDMRSIndices(carrier, pdsch, ...
    "IndexStyle", "subscript", "IndexBase", "0based");
values = complex(nrPDSCHDMRS(carrier, pdsch)) .* double(scale);
K = double(carrier.NSizeGrid) * 12;
indices = cell(1, numel(ports));
symbols = cell(1, numel(ports));
for layer = 1:numel(ports)
    % Toolbox subscript column 3 is the zero-based layer ordinal, not
    % the configured logical DM-RS port identifier.
    mask = double(sub(:,3)) == (layer-1);
    indices{layer} = double(sub(mask,1) + K * sub(mask,2)).';
    symbols{layer} = complex(values(:,layer));
    if numel(indices{layer}) ~= numel(symbols{layer})
        error("sixgr:pdsch:CalibrationDMRSShapeMismatch", ...
            "DM-RS index/symbol counts differ for logical port %d.", ...
            ports(layer));
    end
end
end

function [indices, symbols, ports] = localPTRS(carrier, pdsch, rankValue)
indices = repmat({zeros(1,0)}, 1, rankValue);
symbols = repmat({complex(zeros(0,1))}, 1, rankValue);
ports = zeros(1,0);
if ~logical(pdsch.EnablePTRS)
    return;
end
dmrsPorts = double(pdsch.DMRS.DMRSPortSet(:).');
ports = double(pdsch.PTRS.PTRSPortSet(:).');
if numel(ports) ~= 1
    error("sixgr:pdsch:InvalidPTRSPortAssociation", ...
        "Calibration PT-RS requires one logical port.");
end
layer = find(dmrsPorts == ports,1);
if isempty(layer) || layer > rankValue
    error("sixgr:pdsch:InvalidPTRSPortAssociation", ...
        "PT-RS port %d has no scheduled layer.",ports);
end
dmrsSub = nrPDSCHDMRSIndices(carrier,pdsch, ...
    "IndexStyle","subscript","IndexBase","0based");
if isempty(dmrsSub)
    detail = sprintf([ ...
        'PT-RS cannot be materialized because the replay PDSCH has no ' ...
        'active DM-RS RE. SymbolAllocation=%s MappingType=%s ' ...
        'DMRSTypeAPosition=%g DMRSAdditionalPosition=%g DMRSLength=%g ' ...
        'PRBCount=%d NumLayers=%d.'], ...
        mat2str(double(pdsch.SymbolAllocation(:).')), ...
        char(string(pdsch.MappingType)), ...
        double(pdsch.DMRS.DMRSTypeAPosition), ...
        double(pdsch.DMRS.DMRSAdditionalPosition), ...
        double(pdsch.DMRS.DMRSLength), ...
        numel(pdsch.PRBSet), double(pdsch.NumLayers));
    error("sixgr:pdsch:PTRSRequiresActiveDMRS", "%s", detail);
end
request = struct( ...
    "PRBSet",double(pdsch.PRBSet(:).'), ...
    "SymbolAllocation",double(pdsch.SymbolAllocation(:).'), ...
    "DMRSSymbols",unique(double(dmrsSub(:,2))).', ...
    "TimeDensity",double(pdsch.PTRS.TimeDensity), ...
    "FrequencyDensity",double(pdsch.PTRS.FrequencyDensity), ...
    "REOffset",string(pdsch.PTRS.REOffset), ...
    "GridNumPRB",double(carrier.NSizeGrid), ...
    "RNTI",double(pdsch.RNTI), ...
    "DMRSConfigurationType", ...
        double(pdsch.DMRS.DMRSConfigurationType), ...
    "AssociatedDMRSPort",ports);
resolved = sixgr.pdsch.PDSCHPTRSResolver.resolveIndices(request);
toolboxSub = nrPDSCHPTRSIndices(carrier,pdsch, ...
    "IndexStyle","subscript","IndexBase","0based");
toolboxValues = complex(nrPDSCHPTRS(carrier,pdsch));
K = double(carrier.NSizeGrid)*12;
toolboxMask = double(toolboxSub(:,3)) == (layer-1);
toolboxIndices = double(toolboxSub(toolboxMask,1) ...
    + K*toolboxSub(toolboxMask,2));
resolvedIndices = double(resolved.Indices0Based(:));
if any(~ismember(toolboxIndices,resolvedIndices))
    error("sixgr:pdsch:PTRSReferenceSymbolCatalogMismatch", ...
        "The active Toolbox PT-RS catalog contains an index absent " + ...
        "from the independently resolved canonical PT-RS plan.");
end
% ReservedPRB/ReservedRE can legally deactivate a subset of the raw
% standard PT-RS pattern.  Retain canonical ordering while applying that
% explicit active-resource mask, then require exact Toolbox agreement.
activeResolved = resolvedIndices(ismember( ...
    resolvedIndices,toolboxIndices));
if ~isequal(activeResolved,toolboxIndices(:))
    error("sixgr:pdsch:PTRSActiveResourceMismatch", ...
        "Canonical and Toolbox active PT-RS index ordering differs.");
end
values = toolboxValues(:);
if numel(values) ~= numel(activeResolved)
    error("sixgr:pdsch:PTRSReferenceSymbolShapeMismatch", ...
        "Toolbox PT-RS symbol count differs from the active canonical " + ...
        "PT-RS index plan.");
end
indices{layer} = activeResolved(:).';
symbols{layer} = values(:);
end

function [data, info] = localDataIndices(carrier, pdsch)
[sub, info] = nrPDSCHIndices(carrier, pdsch, ...
    "IndexStyle", "subscript", "IndexBase", "0based");
K = double(carrier.NSizeGrid) * 12;
data = unique(double(sub(:,1) + K * sub(:,2)), "sorted").';
if isempty(data)
    error("sixgr:phy:dl:PDSCHNoDataRE", ...
        "Calibration PDSCH has no final data RE.");
end
end

function allocation = localAllocation(carrier, prbs, symbols)
if numel(symbols) ~= 2 || any(symbols ~= fix(symbols)) ...
        || symbols(1) < 0 || symbols(2) < 1 ...
        || symbols(1) + symbols(2) > carrier.SymbolsPerSlot
    error("sixgr:pdsch:InvalidPDSCHSymbolAllocation", ...
        "Calibration SymbolAllocation is outside the carrier slot.");
end
subcarriers = reshape(12 * prbs(:).' + (0:11).', 1, []);
scheduled = symbols(1) + (0:(symbols(2) - 1));
[k,l] = ndgrid(subcarriers, scheduled);
allocation = sort(double(k(:) ...
    + 12 * double(carrier.NSizeGrid) * l(:))).';
end

function context = localPlanContext(carrier, pdsch, dmrs, ptrs, ...
        logicalPorts, layers, qm, blocks, referenceDigest)
context = struct( ...
    "PRBSet", double(pdsch.PRBSet(:).'), ...
    "SymbolAllocation", double(pdsch.SymbolAllocation(:).'), ...
    "GridNumPRB", double(carrier.NSizeGrid), ...
    "GridSymbolsPerSlot", double(carrier.SymbolsPerSlot), ...
    "BWPStartPRB", double(carrier.NStartGrid), ...
    "AbsoluteSlot", localAbsoluteSlot(carrier), ...
    "UnavailableIndices", zeros(1,0), ...
    "DMRSIndicesPerPort", {dmrs}, ...
    "PTRSIndicesPerPort", {ptrs}, ...
    "DMRSLogicalPortSet", double(logicalPorts), ...
    "PTRSLogicalPortSet", double(logicalPorts), ...
    "LayerCountPerCodeword", double(layers), ...
    "QmPerCodeword", double(qm), ...
    "CodeBlockCountPerCodeword", double(blocks), ...
    "ReferenceConfigurationDigest", string(referenceDigest));
end

function [scheduled, selected] = localTransportBlockSizes( ...
        pdsch, plan, nrePerPRBForTBS, requestedRate, xOverhead, override)
nreForTBS = localNREPerPRBForTBS(nrePerPRBForTBS);
scheduled = double(nrTBS(pdsch.Modulation, pdsch.NumLayers, ...
    numel(plan.PRBSet), nreForTBS, requestedRate, xOverhead));
scheduled = round(double(scheduled(:).'));
if isempty(override)
    selected = scheduled;
else
    selected = round(double(override(:).'));
    if numel(selected) ~= numel(scheduled) ...
            || any(~isfinite(selected) | selected <= 0)
        error("PDSCH_Tx:BadReplayTBSize", ...
            "Calibration TBS override must contain one positive size per codeword.");
    end
end
end

function value = localNREPerPRBForTBS(value)
value = double(value);
if ~(isscalar(value) && isfinite(value) ...
        && value == fix(value) && value >= 0)
    error("sixgr:pdsch:InvalidCalibrationNREPerPRBForTBS", ...
        "Calibration TBS requires the scalar integer NREPerPRB " + ...
        "reported by nrPDSCHIndices.");
end
value = min(156,value);
end

function assignmentRequest = localAssignmentRequest(carrier, pdsch, tableNames, ...
        indices, profiles, layers, ports, ptrsPorts, rv, xOverhead, ...
        calibrationRequest)
rankValue = double(pdsch.NumLayers);
numCodewords = numel(layers);
assignmentRequest = struct( ...
    "UEId", 1, ...
    "RNTI", double(pdsch.RNTI), ...
    "RNTIType", "C-RNTI", ...
    "ServingCellId", double(carrier.NCellID), ...
    "SchedulingCellId", double(carrier.NCellID), ...
    "CCId", 0, "BWPId", 0, "ConfigurationEpoch", 0, ...
    "PRBSetBWPRelative", double(pdsch.PRBSet(:).'), ...
    "PRBSetCarrierRelative", double(pdsch.PRBSet(:).'), ...
    "SymbolAllocation", double(pdsch.SymbolAllocation(:).'), ...
    "MappingType", string(pdsch.MappingType), ...
    "MCSTablePerCodeword", tableNames, ...
    "MCSIndexPerCodeword", indices, ...
    "ModulationPerCodeword", string({profiles.Modulation}), ...
    "QmPerCodeword", double([profiles.Qm]), ...
    "TargetCodeRatePerCodeword", ...
        double([profiles.TargetCodeRate]), ...
    "TBScalingPerCodeword", ones(1,numCodewords), ...
    "XOverhead", xOverhead, ...
    "NumLayers", rankValue, ...
    "NumCodewords", numCodewords, ...
    "LayerCountPerCodeword", layers, ...
    "DMRSPortSet", ports, ...
    "PTRSPortSet", ptrsPorts, ...
    "NDIPerCodeword", ones(1,numCodewords), ...
    "RVPerCodeword", rv, "HARQProcessId", 0, ...
    "UECapability1024QAM", ...
        calibrationRequest.UECapability1024QAM, ...
    "RRCEnabled1024QAM", ...
        calibrationRequest.RRCEnabled1024QAM, ...
    "DCIEnabled1024QAM", ...
        calibrationRequest.DCIEnabled1024QAM, ...
    "DCIFormat", calibrationRequest.DCIFormat, ...
    "UECapability1024QAMVariant", ...
        calibrationRequest.UECapability1024QAMVariant, ...
    "MaxNumberMIMOLayersPDSCH", ...
        calibrationRequest.MaxNumberMIMOLayersPDSCH, ...
    "DeploymentAllows1024QAM", ...
        calibrationRequest.DeploymentAllows1024QAM, ...
    "FrequencyRange", calibrationRequest.FrequencyRange, ...
    "OperatingBand", calibrationRequest.OperatingBand, ...
    "DeploymentClass", calibrationRequest.DeploymentClass, ...
    "FrequencyRangeAllows1024QAM", ...
        calibrationRequest.FrequencyRangeAllows1024QAM, ...
    "BandAllows1024QAM", ...
        calibrationRequest.BandAllows1024QAM);
end

function request = localApplySchedulerTruthAssignmentContext( ...
        request, grant, absoluteSlot)
if ~(isstruct(grant) && ~isempty(fieldnames(grant)))
    error("sixgr:pdsch:MissingSchedulerTruthGrantContext", ...
        "scheduler_truth assignment requires a nonempty decoded grant context.");
end
if ~logical(sixgr.util.structGet(grant, "PDCCHGrantBindingOk", false)) || ...
        ~logical(sixgr.util.structGet(grant, "ControlDecodeOk", false))
    error("sixgr:pdsch:MissingSchedulerTruthPDCCHBinding", ...
        "scheduler_truth assignment requires successful decoded PDCCH binding.");
end
dciId = string(sixgr.util.structGet(grant, "PDCCHGrantDCIId", ""));
if strlength(strtrim(dciId)) == 0
    error("sixgr:pdsch:MissingSchedulerTruthDCIId", ...
        "scheduler_truth assignment requires the decoded DCI identity.");
end
request.UEId = double(sixgr.util.structGet(grant, "UEIndex", ...
    sixgr.util.structGet(grant, "UEID", request.UEId)));
request.RNTI = double(sixgr.util.structGet(grant, "RNTI", request.RNTI));
request.ServingCellId = double(sixgr.util.structGet(grant, ...
    "ServingCell", request.ServingCellId));
request.SchedulingCellId = double(sixgr.util.structGet(grant, ...
    "SchedulingCell", request.ServingCellId));
request.CCId = double(sixgr.util.structGet(grant, "CCId", request.CCId));
request.BWPId = double(sixgr.util.structGet(grant, "BWPId", request.BWPId));
request.ConfigurationEpoch = double(sixgr.util.structGet(grant, ...
    "ConfigurationEpoch", request.ConfigurationEpoch));
request.HARQProcessId = double(sixgr.util.structGet(grant, ...
    "HARQProcess", sixgr.util.structGet(grant, ...
    "HarqID", request.HARQProcessId)));
request.NDIPerCodeword = repmat(double(logical(sixgr.util.structGet( ...
    grant, "NDI", true))), 1, request.NumCodewords);
request.DecodedDCIId = dciId;
request.DCIFormat = string(sixgr.util.structGet(grant, ...
    "PDCCHGrantDCIFormat", request.DCIFormat));
request.SearchSpaceId = double(sixgr.util.structGet(grant, ...
    "PDCCHGrantSearchSpaceId", sixgr.util.structGet(grant, ...
    "SearchSpaceID", NaN)));
request.CORESETId = double(sixgr.util.structGet(grant, ...
    "PDCCHGrantCORESETId", sixgr.util.structGet(grant, ...
    "CORESETID", NaN)));
timing = sixgr.pdsch.resolveSchedulerPDSCHTiming(grant, absoluteSlot);
request.PDCCHAbsoluteSlot = timing.PDCCHAbsoluteSlot;
request.K0 = timing.K0;
request.DecodedRNTI = request.RNTI;
request.DCICRCPass = true;
request.DCIRNTIMatch = true;
end

function source = localExplicitGrantAdapterSource(profile)
if lower(strtrim(string(profile))) == "scheduler_truth"
    source = "decoded_scheduler_grant_to_canonical_assignment";
else
    source = "explicit_phy_calibration_to_canonical_assignment";
end
end

function slot = localAbsoluteSlot(carrier)
slotsPerFrame = 10 * 2^(log2(double(carrier.SubcarrierSpacing) / 15));
slot = round(double(carrier.NFrame) * slotsPerFrame ...
    + double(carrier.NSlot));
end

function reference = localMaterializerReference(carrier,pdsch)
nidNSCID = double(pdsch.DMRS.NIDNSCID);
if isempty(nidNSCID)
    % nrPDSCHConfig defines an empty NIDNSCID as inheritance from the
    % carrier physical-cell identity, not the independent PDSCH data-
    % scrambling identity.
    nidNSCID = double(carrier.NCellID);
end
nscid = double(pdsch.DMRS.NSCID);
if isempty(nscid)
    nscid = 0;
end
reference = struct( ...
    "NID", double(pdsch.NID), ...
    "DMRSConfigurationType", ...
        double(pdsch.DMRS.DMRSConfigurationType), ...
    "DMRSTypeAPosition", double(pdsch.DMRS.DMRSTypeAPosition), ...
    "DMRSAdditionalPosition", ...
        double(pdsch.DMRS.DMRSAdditionalPosition), ...
    "DMRSLength", double(pdsch.DMRS.DMRSLength), ...
    "NumCDMGroupsWithoutData", ...
        double(pdsch.DMRS.NumCDMGroupsWithoutData), ...
    "NIDNSCID", nidNSCID, ...
    "NSCID", nscid, ...
    "EnablePTRS", logical(pdsch.EnablePTRS));
if pdsch.EnablePTRS
    reference.PTRSTimeDensity = double(pdsch.PTRS.TimeDensity);
    reference.PTRSFrequencyDensity = ...
        double(pdsch.PTRS.FrequencyDensity);
    reference.PTRSREOffset = string(pdsch.PTRS.REOffset);
end
end

function localAssertPDSCHUnchanged(actual, expected)
numeric = ["PRBSet","SymbolAllocation","NumLayers","RNTI","NID"];
for idx = 1:numel(numeric)
    name = numeric(idx);
    if ~isequal(double(actual.(name)), double(expected.(name)))
        error("sixgr:pdsch:CalibrationMaterializationMismatch", ...
            "Assignment materialization changed PDSCH.%s.", name);
    end
end
if ~isequal(upper(string(actual.Modulation)), ...
        upper(string(expected.Modulation))) ...
        || upper(string(actual.MappingType)) ...
            ~= upper(string(expected.MappingType))
    error("sixgr:pdsch:CalibrationMaterializationMismatch", ...
        "Assignment materialization changed modulation or mapping type.");
end
end

function [legacy, bundle] = localPrecoder(cfg, pdsch, matrix)
legacy = sixgr.phy.dl.resolvePDSCHPrecoding(pdsch, cfg, ...
    "PrecodingMatrix", matrix);
bundle = [];
if ~logical(legacy.Active)
    return;
end
prbs = double(pdsch.PRBSet(:).');
symbols = double(pdsch.SymbolAllocation(1)) ...
    + (0:(double(pdsch.SymbolAllocation(2)) - 1));
nPRG = double(legacy.NumPRG);
if nPRG == 1
    mode = "wideband_fixed_matrix";
    prgSize = 0;
else
    mode = "prg_noncodebook";
    prgSize = numel(prbs) / nPRG;
    if prgSize ~= fix(prgSize) || prgSize < 1
        error("sixgr:pdsch:PDSCHPrecoderBundle:IncompletePRGCoverage", ...
            "Calibration PRG pages must partition the scheduled PRBs " + ...
            "exactly.");
    end
end
normalization = lower(strtrim(string(sixgr.util.structGet(legacy, ...
    "NormalizationConvention", "explicit_no_normalization"))));
spec = struct( ...
    "Mode", mode, ...
    "NPorts", double(legacy.NumWaveformColumns), ...
    "NLayers", double(pdsch.NumLayers), ...
    "NPRG", nPRG, "NSymbolGroups", 1, ...
    "PRGSize", prgSize, "PRBSet", prbs, ...
    "ScheduledSymbols", symbols, ...
    "SymbolGroupMap", zeros(1,numel(symbols)), ...
    "W", reshape(complex(double(legacy.MatrixPortsPerPRG)), ...
        [size(legacy.MatrixPortsPerPRG,1), ...
         size(legacy.MatrixPortsPerPRG,2), nPRG, 1]), ...
    "MatrixSource", "calibration_" + string(legacy.Source), ...
    "CodebookIdentifier", "", ...
    "NormalizationConvention", normalization, ...
    "NormalizationTolerance", 1e-10);
bundle = sixgr.pdsch.PDSCHPrecoderBundle(spec);
end

function blocks = localTransportBlocks(raw, sizes, receiverOnly)
count = numel(sizes);
if receiverOnly
    if ~isempty(raw)
        error("sixgr:pdsch:CalibrationReceiverRejectsTransportBlockBits", ...
            ("Calibration RX does not accept transmitted transport-block " + ...
            "bits at its trust boundary."));
    end
    blocks = repmat({int8(zeros(0,1))},1,count);
    return;
end
if isempty(raw)
    blocks = cell(1,count);
    for cw = 1:count
        blocks{cw} = int8(randi([0 1], sizes(cw), 1));
    end
elseif iscell(raw)
    blocks = reshape(raw,1,[]);
else
    blocks = {raw};
end
if numel(blocks) ~= count
    error("sixgr:pdsch:DLSCHEncoder:CodewordCountMismatch", ...
        "Calibration requires one transport block per codeword.");
end
for cw = 1:count
    bits = double(blocks{cw}(:));
    if numel(bits) ~= sizes(cw) ...
            || any(~isfinite(bits) | (bits ~= 0 & bits ~= 1))
        error("sixgr:pdsch:DLSCHEncoder:TransportBlockSizeMismatch", ...
            "Calibration transport block %d differs from TBS=%d.", ...
            cw - 1, sizes(cw));
    end
    blocks{cw} = int8(bits);
end
end

function receiver = localReceiverConfig(cfg, request, tbs, ...
        nPhysicalPorts, legacyPrecoder, carrier, referenceConfig)
model = localReceiverChannelModel(cfg);
if logical(sixgr.util.structGet(cfg, "channel.awgnOnly", false))
    model = "AWGN";
end
nRx = double(request.NPhysicalRxAntennas);
if ~(isscalar(nRx) && isfinite(nRx) && nRx == fix(nRx) && nRx >= 1)
    nRx = nPhysicalPorts;
end
if model == "AWGN" && (nPhysicalPorts > 1 || nRx > 1 ...
        || double(legacyPrecoder.NumPRG) > 1)
    model = "STATIC-MIMO";
end
noiseVariance = localGridNoiseVariance( ...
    request.NoiseVariance, request.NoiseVarianceDomain, ...
    carrier, referenceConfig.get("OFDMOptions"));
receiver = struct( ...
    "TransportBlockSizes", double(tbs), ...
    "ChannelModel", char(model), ...
    "MaxIterations", double(request.MaxIterations), ...
    "Algorithm", char(string(request.Algorithm)), ...
    "LLRConvention", "positive_favours_bit_zero", ...
    "NPhysicalRxAntennas", nRx, ...
    "UseExactFlatPRGEstimator", logical(sixgr.util.structGet(cfg, ...
        "phy.pdsch.dmrs.useExactFlatStaticMIMOPRGEstimator", ...
        sixgr.util.structGet(cfg, ...
            "phy.pdsch.dmrs.useExactAWGNPRGEstimator", false))));
if ~isempty(noiseVariance)
    receiver.NoiseVariance = double(noiseVariance);
end
end

function model = localReceiverChannelModel(cfg)
% The receiver consumes an executable small-scale waveform profile, not
% the large-scale propagation authority.  In particular, TR38901 and ray
% tracing configurations must carry their explicitly configured concrete
% TDL/CDL profile through the immutable transmitter/receiver bundle.  Use
% the same fail-closed resolver as the system replay path so the bundle
% cannot silently reintroduce the broad channel-family token.
model = upper(strtrim(string(sixgr.channel.resolveConcreteProfile(cfg))));
end

function value = localGridNoiseVariance(raw, domain, carrier, ofdmOptions)
if isempty(raw)
    value = [];
    return;
end
domain = lower(strtrim(string(domain)));
if any(domain == ["grid","frequency"])
    value = double(raw);
    return;
end
calibration = sixgr.phy.waveform.calibrateOFDMNoiseTransform( ...
    carrier, ofdmOptions{:});
[value, ~] = sixgr.phy.waveform.convertNoiseVarianceToGridDomain( ...
    raw, calibration, "InputDomain", domain, ...
    "Source", "pdsch_calibration_facade");
end
