classdef PDSCHResourceOwnershipMap
    %PDSCHRESOURCEOWNERSHIPMAP Authoritative zero-based PDSCH RE ownership.
    %
    % A resolved map contains every RE in the explicit carrier-slot
    % universe.  Allocation, frame-direction availability, reservation
    % provenance, DM-RS logical ports, PT-RS logical ports, and data are
    % represented independently before ResolvedStatus is assigned.  No
    % owner-priority rule is used to hide an illegal overlap.

    properties (SetAccess = immutable)
        UniverseIndices (:,1) double
        AllocationIndices (:,1) double
        UnavailableIndices (:,1) double
        ReservedUnionIndices (:,1) double
        DMRSUnionIndices (:,1) double
        PTRSUnionIndices (:,1) double
        DataIndices (:,1) double
        DMRSIndicesPerPort (1,:) cell
        PTRSIndicesPerPort (1,:) cell
        DMRSLogicalPortSet (1,:) double
        PTRSLogicalPortSet (1,:) double
        Entries table
        ReservationSources (1,1) struct
        PairwiseOverlapMultiplicity (1,1) double
        CollisionIndices (:,1) double
        GridNumPRB (1,1) double
        GridSymbolsPerSlot (1,1) double
        BWPStartPRB (1,1) double
        AbsoluteSlot (1,1) double
        ReferencesResolved (1,1) logical
        IndexBase (1,1) string
    end

    methods
        function obj = PDSCHResourceOwnershipMap(allocationIndices, ...
                reservationSources, varargin)
            diagnostic = sixgr.pdsch.PDSCHResourceOwnershipMap.analyze( ...
                allocationIndices, reservationSources, varargin{:});
            if diagnostic.Status == "ERROR"
                error(diagnostic.ErrorIdentifier, "%s", ...
                    diagnostic.ErrorMessage);
            end

            obj.UniverseIndices = diagnostic.UniverseIndices(:);
            obj.AllocationIndices = diagnostic.AllocationIndices(:);
            obj.UnavailableIndices = diagnostic.UnavailableIndices(:);
            obj.ReservedUnionIndices = diagnostic.ReservedUnionIndices(:);
            obj.DMRSUnionIndices = diagnostic.DMRSUnionIndices(:);
            obj.PTRSUnionIndices = diagnostic.PTRSUnionIndices(:);
            obj.DataIndices = diagnostic.DataIndices(:);
            obj.DMRSIndicesPerPort = diagnostic.DMRSIndicesPerPort;
            obj.PTRSIndicesPerPort = diagnostic.PTRSIndicesPerPort;
            obj.DMRSLogicalPortSet = diagnostic.DMRSLogicalPortSet;
            obj.PTRSLogicalPortSet = diagnostic.PTRSLogicalPortSet;
            obj.ReservationSources = diagnostic.ReservationSources;
            obj.PairwiseOverlapMultiplicity = ...
                diagnostic.PairwiseOverlapMultiplicity;
            obj.CollisionIndices = diagnostic.CollisionIndices(:);
            obj.GridNumPRB = diagnostic.GridNumPRB;
            obj.GridSymbolsPerSlot = diagnostic.GridSymbolsPerSlot;
            obj.BWPStartPRB = diagnostic.BWPStartPRB;
            obj.AbsoluteSlot = diagnostic.AbsoluteSlot;
            obj.ReferencesResolved = diagnostic.ReferencesResolved;
            obj.IndexBase = "zero_based";
            obj.Entries = diagnostic.Entries;
        end

        function resolved = resolve(obj, context)
            %RESOLVE Add explicit availability and logical reference ports.
            required = ["UniverseIndices","UnavailableIndices", ...
                "DMRSIndicesPerPort","PTRSIndicesPerPort", ...
                "DMRSLogicalPortSet","PTRSLogicalPortSet", ...
                "GridNumPRB","GridSymbolsPerSlot","BWPStartPRB", ...
                "AbsoluteSlot"];
            if ~isstruct(context) || ~isscalar(context)
                error("sixgr:pdsch:InvalidOwnershipResolutionContext", ...
                    "Ownership resolution context must be a scalar struct.");
            end
            missing = required(~isfield(context, required));
            if ~isempty(missing)
                error("sixgr:pdsch:IncompleteOwnershipResolutionContext", ...
                    "Ownership resolution context is missing: %s.", ...
                    strjoin(cellstr(missing), ", "));
            end
            resolved = sixgr.pdsch.PDSCHResourceOwnershipMap( ...
                obj.AllocationIndices, obj.ReservationSources, ...
                "UniverseIndices", context.UniverseIndices, ...
                "UnavailableIndices", context.UnavailableIndices, ...
                "DMRSIndicesPerPort", context.DMRSIndicesPerPort, ...
                "PTRSIndicesPerPort", context.PTRSIndicesPerPort, ...
                "DMRSLogicalPortSet", context.DMRSLogicalPortSet, ...
                "PTRSLogicalPortSet", context.PTRSLogicalPortSet, ...
                "GridNumPRB", context.GridNumPRB, ...
                "GridSymbolsPerSlot", context.GridSymbolsPerSlot, ...
                "BWPStartPRB", context.BWPStartPRB, ...
                "AbsoluteSlot", context.AbsoluteSlot, ...
                "ReferencesResolved", true);
        end

        function value = toStruct(obj)
            value = struct( ...
                "UniverseIndices", obj.UniverseIndices, ...
                "AllocationIndices", obj.AllocationIndices, ...
                "UnavailableIndices", obj.UnavailableIndices, ...
                "ReservedUnionIndices", obj.ReservedUnionIndices, ...
                "DMRSUnionIndices", obj.DMRSUnionIndices, ...
                "PTRSUnionIndices", obj.PTRSUnionIndices, ...
                "DataIndices", obj.DataIndices, ...
                "DMRSIndicesPerPort", {obj.DMRSIndicesPerPort}, ...
                "PTRSIndicesPerPort", {obj.PTRSIndicesPerPort}, ...
                "DMRSLogicalPortSet", obj.DMRSLogicalPortSet, ...
                "PTRSLogicalPortSet", obj.PTRSLogicalPortSet, ...
                "Entries", obj.Entries, ...
                "ReservationSources", obj.ReservationSources, ...
                "PairwiseOverlapMultiplicity", ...
                obj.PairwiseOverlapMultiplicity, ...
                "CollisionIndices", obj.CollisionIndices, ...
                "GridNumPRB", obj.GridNumPRB, ...
                "GridSymbolsPerSlot", obj.GridSymbolsPerSlot, ...
                "BWPStartPRB", obj.BWPStartPRB, ...
                "AbsoluteSlot", obj.AbsoluteSlot, ...
                "ReferencesResolved", obj.ReferencesResolved, ...
                "IndexBase", obj.IndexBase);
        end
    end

    methods (Static)
        function diagnostic = analyze(allocationIndices, reservationSources, varargin)
            ip = inputParser;
            ip.FunctionName = ...
                "sixgr.pdsch.PDSCHResourceOwnershipMap.analyze";
            ip.addParameter("UniverseIndices", zeros(1,0));
            ip.addParameter("UnavailableIndices", zeros(1,0));
            ip.addParameter("DMRSIndicesPerPort", cell(1,0));
            ip.addParameter("PTRSIndicesPerPort", cell(1,0));
            ip.addParameter("DMRSLogicalPortSet", zeros(1,0));
            ip.addParameter("PTRSLogicalPortSet", zeros(1,0));
            ip.addParameter("GridNumPRB", NaN);
            ip.addParameter("GridSymbolsPerSlot", NaN);
            ip.addParameter("BWPStartPRB", NaN);
            ip.addParameter("AbsoluteSlot", NaN);
            ip.addParameter("ReferencesResolved", false, ...
                @(x) islogical(x) && isscalar(x));
            ip.parse(varargin{:});
            opt = ip.Results;

            allocation = sixgr.pdsch.PDSCHResourceOwnershipMap. ...
                validateIndexVector(allocationIndices, ...
                "InvalidPDSCHAllocationRE", false);
            if ~isstruct(reservationSources) || ~isscalar(reservationSources)
                error("sixgr:pdsch:InvalidReservationSources", ...
                    "Reservation sources must be a scalar struct.");
            end

            canonicalNames = [ ...
                "SSB","CORESET","NZPCSIRS","ZPCSIRS","LTECRS", ...
                "RateMatchPattern","Other"];
            suppliedNames = string(fieldnames(reservationSources));
            unknown = setdiff(suppliedNames, canonicalNames, "stable");
            if ~isempty(unknown)
                error("sixgr:pdsch:UnsupportedReservationSource", ...
                    "Unsupported PDSCH reservation source(s): %s.", ...
                    strjoin(cellstr(unknown), ", "));
            end

            normalized = struct();
            sourceSets = cell(1, numel(canonicalNames));
            for i = 1:numel(canonicalNames)
                name = canonicalNames(i);
                if isfield(reservationSources, name)
                    values = reservationSources.(name);
                else
                    values = zeros(1, 0);
                end
                values = sixgr.pdsch.PDSCHResourceOwnershipMap. ...
                    validateIndexVector(values, "InvalidReservedRE", true);
                normalized.(name) = values(:).';
                sourceSets{i} = values(:).';
            end
            unionAll = unique([sourceSets{:}], "sorted");
            unavailable = sixgr.pdsch.PDSCHResourceOwnershipMap. ...
                validateIndexVector(opt.UnavailableIndices, ...
                "InvalidUnavailableRE", true);
            dmrsByPort = sixgr.pdsch.PDSCHResourceOwnershipMap. ...
                validateIndexCells(opt.DMRSIndicesPerPort, ...
                "InvalidDMRSIndices");
            ptrsByPort = sixgr.pdsch.PDSCHResourceOwnershipMap. ...
                validateIndexCells(opt.PTRSIndicesPerPort, ...
                "InvalidPTRSIndices");
            dmrsLogicalPorts = sixgr.pdsch.PDSCHResourceOwnershipMap. ...
                validateLogicalPorts(opt.DMRSLogicalPortSet, ...
                numel(dmrsByPort), "InvalidDMRSPortSet", ...
                logical(opt.ReferencesResolved));
            ptrsLogicalPorts = sixgr.pdsch.PDSCHResourceOwnershipMap. ...
                validateLogicalPorts(opt.PTRSLogicalPortSet, ...
                numel(ptrsByPort), "InvalidPTRSPortSet", ...
                logical(opt.ReferencesResolved));
            dmrsUnion = unique([dmrsByPort{:}], "sorted");
            ptrsUnion = unique([ptrsByPort{:}], "sorted");

            universe = sixgr.pdsch.PDSCHResourceOwnershipMap. ...
                validateIndexVector(opt.UniverseIndices, ...
                "InvalidOwnershipUniverse", true);
            if isempty(universe)
                universe = unique([allocation,unionAll,unavailable, ...
                    dmrsUnion,ptrsUnion], "sorted");
            end
            mentioned = unique([allocation,unionAll,unavailable, ...
                dmrsUnion,ptrsUnion], "sorted");
            entriesUniverse = unique([universe,mentioned], "sorted");

            [gridNumPRB, gridSymbols, bwpStart, absoluteSlot] = ...
                sixgr.pdsch.PDSCHResourceOwnershipMap.validateGeometry( ...
                opt.GridNumPRB, opt.GridSymbolsPerSlot, ...
                opt.BWPStartPRB, opt.AbsoluteSlot);
            if isfinite(gridNumPRB)
                planeSize = 12 * gridNumPRB * gridSymbols;
                outsideGrid = entriesUniverse( ...
                    entriesUniverse >= planeSize);
            else
                outsideGrid = zeros(1,0);
            end

            outsideReservation = setdiff(unionAll, allocation, "stable");
            outsideReference = setdiff( ...
                union(dmrsUnion,ptrsUnion), allocation, "stable");
            unavailableReference = intersect( ...
                union(dmrsUnion,ptrsUnion), unavailable, "stable");
            dmrsPTRS = intersect(dmrsUnion, ptrsUnion, "stable");
            dmrsReserved = intersect(dmrsUnion, unionAll, "stable");
            ptrsReserved = intersect(ptrsUnion, unionAll, "stable");
            collisionIndices = unique([unavailableReference,dmrsPTRS, ...
                dmrsReserved,ptrsReserved], "sorted");
            unavailableInside = intersect(allocation, unavailable, "stable");
            reservedInside = intersect(allocation, unionAll, "stable");
            unavailableOrReserved = union(unavailableInside,reservedInside);
            data = setdiff(allocation, ...
                union(unavailableOrReserved,union(dmrsUnion,ptrsUnion)), ...
                "stable");

            overlap = 0;
            for i = 1:numel(sourceSets)
                for j = (i + 1):numel(sourceSets)
                    overlap = overlap + numel(intersect( ...
                        sourceSets{i}, sourceSets{j}));
                end
            end

            status = "PASS";
            errorIdentifier = "";
            errorMessage = "";
            if ~isempty(outsideGrid)
                status = "ERROR";
                errorIdentifier = "sixgr:pdsch:OwnershipREOutsideCarrierGrid";
                errorMessage = sprintf( ...
                    "%d ownership RE(s) lie outside the explicit carrier-slot grid.", ...
                    numel(outsideGrid));
            elseif ~isempty(setdiff(allocation, universe, "stable"))
                status = "ERROR";
                errorIdentifier = "sixgr:pdsch:AllocationOutsideOwnershipUniverse";
                errorMessage = ...
                    "The explicit ownership universe does not contain the full PDSCH allocation.";
            elseif ~isempty(outsideReservation)
                status = "ERROR";
                errorIdentifier = "sixgr:pdsch:ReservedREOutsideAllocation";
                errorMessage = sprintf( ...
                    "%d reserved RE(s) lie outside the scheduled PDSCH allocation.", ...
                    numel(outsideReservation));
            elseif ~isempty(outsideReference)
                status = "ERROR";
                errorIdentifier = "sixgr:pdsch:ReferenceREOutsideAllocation";
                errorMessage = sprintf( ...
                    "%d DM-RS/PT-RS RE(s) lie outside the scheduled allocation.", ...
                    numel(outsideReference));
            elseif ~isempty(collisionIndices)
                status = "ERROR";
                errorIdentifier = "sixgr:pdsch:DataDMRSPTRSReservedCollision";
                errorMessage = sprintf( ...
                    "%d illegal availability/reference/reservation overlap(s) were resolved.", ...
                    numel(collisionIndices));
            elseif isempty(data)
                status = "ERROR";
                if logical(opt.ReferencesResolved)
                    errorIdentifier = ...
                        "sixgr:pdsch:NoPDSCHDataREAfterReferenceSignals";
                    errorMessage = ...
                        "No PDSCH data RE remains after availability, reservation, DM-RS, and PT-RS resolution.";
                else
                    errorIdentifier = ...
                        "sixgr:pdsch:NoPDSCHDataREAfterReservation";
                    errorMessage = ...
                        "No PDSCH data RE remains after availability and reservation resolution.";
                end
            end

            diagnostic = struct( ...
                "UniverseIndices", universe(:).', ...
                "AllocationIndices", allocation(:).', ...
                "UnavailableIndices", unavailable(:).', ...
                "ReservedUnionIndices", reservedInside(:).', ...
                "DMRSUnionIndices", dmrsUnion(:).', ...
                "PTRSUnionIndices", ptrsUnion(:).', ...
                "DataIndices", data(:).', ...
                "OutsideReservationIndices", ...
                    outsideReservation(:).', ...
                "OutsideReferenceIndices", outsideReference(:).', ...
                "OutsideGridIndices", outsideGrid(:).', ...
                "CollisionIndices", collisionIndices(:).', ...
                "AllocationRECount", numel(allocation), ...
                "UnavailableInsideAllocationCount", ...
                    numel(unavailableInside), ...
                "ReservedUnionCount", numel(reservedInside), ...
                "DMRSUnionCount", numel(dmrsUnion), ...
                "PTRSUnionCount", numel(ptrsUnion), ...
                "DataRECount", numel(data), ...
                "ReservedOutsideAllocationCount", ...
                    numel(outsideReservation), ...
                "ReferenceOutsideAllocationCount", ...
                    numel(outsideReference), ...
                "PairwiseOverlapMultiplicity", double(overlap), ...
                "ReservationSources", normalized, ...
                "DMRSIndicesPerPort", {dmrsByPort}, ...
                "PTRSIndicesPerPort", {ptrsByPort}, ...
                "DMRSLogicalPortSet", dmrsLogicalPorts, ...
                "PTRSLogicalPortSet", ptrsLogicalPorts, ...
                "GridNumPRB", gridNumPRB, ...
                "GridSymbolsPerSlot", gridSymbols, ...
                "BWPStartPRB", bwpStart, ...
                "AbsoluteSlot", absoluteSlot, ...
                "ReferencesResolved", logical(opt.ReferencesResolved), ...
                "Status", string(status), ...
                "ErrorIdentifier", string(errorIdentifier), ...
                "ErrorMessage", string(errorMessage), ...
                "IndexBase", "zero_based");
            diagnostic.Entries = sixgr.pdsch. ...
                PDSCHResourceOwnershipMap.buildEntries( ...
                    diagnostic, entriesUniverse);
        end
    end

    methods (Static, Access = private)
        function values = validateIndexVector(values, token, allowEmpty)
            if ~isnumeric(values) || ~isvector(values) || ...
                    (~allowEmpty && isempty(values)) || ...
                    any(~isfinite(values)) || any(values ~= floor(values)) || ...
                    any(values < 0)
                error("sixgr:pdsch:" + string(token), ...
                    "RE indices must be zero-based nonnegative integer vectors.");
            end
            values = double(values(:).');
            if numel(unique(values, "stable")) ~= numel(values)
                error("sixgr:pdsch:DuplicateREIndex", ...
                    "An RE index list must not contain duplicate entries.");
            end
            values = sort(values);
        end

        function cells = validateIndexCells(value, token)
            if ~iscell(value) || ~isrow(value)
                error("sixgr:pdsch:" + string(token), ...
                    "Reference indices must be a row cell array, one cell per logical port.");
            end
            cells = value;
            for i = 1:numel(cells)
                cells{i} = sixgr.pdsch.PDSCHResourceOwnershipMap. ...
                    validateIndexVector(cells{i}, token, true);
            end
        end

        function ports = validateLogicalPorts(value, count, token, required)
            if isempty(value) && count == 0
                ports = zeros(1,0);
                return;
            end
            if isempty(value) && ~required
                ports = 0:(count-1);
                return;
            end
            if ~isnumeric(value) || ~isvector(value) ...
                    || numel(value) ~= count || any(~isfinite(value)) ...
                    || any(value ~= floor(value)) || any(value < 0) ...
                    || any(value > 23) ...
                    || numel(unique(value,"stable")) ~= numel(value)
                error("sixgr:pdsch:" + string(token), ...
                    "Logical port sets must explicitly contain one unique " + ...
                    "zero-based port in 0...23 per reference-index cell.");
            end
            ports = double(value(:).');
        end

        function [gridNumPRB, symbols, bwpStart, slot] = ...
                validateGeometry(gridNumPRB, symbols, bwpStart, slot)
            values = [gridNumPRB,symbols,bwpStart,slot];
            allNaN = all(isnan(values));
            if allNaN
                return;
            end
            if any(~isfinite(values)) || any(values ~= floor(values)) ...
                    || gridNumPRB < 1 || symbols < 1 ...
                    || ~ismember(symbols,[12 14]) ...
                    || bwpStart < 0 || slot < 0
                error("sixgr:pdsch:InvalidOwnershipGridGeometry", ...
                    "GridNumPRB, GridSymbolsPerSlot (12 or 14), " + ...
                    "BWPStartPRB, and AbsoluteSlot must be explicit " + ...
                    "nonnegative integer geometry.");
            end
            gridNumPRB = double(gridNumPRB);
            symbols = double(symbols);
            bwpStart = double(bwpStart);
            slot = double(slot);
        end

        function entries = buildEntries(diagnostic, indices)
            indices = double(indices(:));
            count = numel(indices);
            inside = ismember(indices,diagnostic.AllocationIndices);
            available = ~ismember(indices,diagnostic.UnavailableIndices);
            owner = repmat("outside_pdsch_allocation",count,1);
            sourceList = strings(count,1);
            sourceCount = zeros(count,1);
            dmrsPorts = strings(count,1);
            ptrsPorts = strings(count,1);
            logicalPortCount = zeros(count,1);
            collisionTypes = strings(count,1);
            collisionCount = zeros(count,1);
            errorStatus = repmat("none",count,1);
            names = string(fieldnames(diagnostic.ReservationSources));
            ownerBySource = struct( ...
                "SSB", "reserved_ssb", ...
                "CORESET", "reserved_coreset_pdcch", ...
                "NZPCSIRS", "reserved_nzp_csi_rs", ...
                "ZPCSIRS", "reserved_zp_csi_rs", ...
                "LTECRS", "reserved_lte_crs", ...
                "RateMatchPattern", "reserved_rate_match_pattern", ...
                "Other", "reserved_other");

            % Build membership once per ownership set.  The previous
            % scalar-in-loop implementation repeated a binary search for
            % every RE/source/port tuple (hundreds of thousands of calls
            % for a 100 MHz carrier).  These logical matrices encode the
            % identical zero-based set membership while keeping runtime
            % proportional to the number of ownership sets.
            sourceMembership = false(count,numel(names));
            for j = 1:numel(names)
                sourceMembership(:,j) = ismember(indices, ...
                    diagnostic.ReservationSources.(names(j)));
            end
            dmrsMembership = false(count,numel( ...
                diagnostic.DMRSIndicesPerPort));
            for j = 1:size(dmrsMembership,2)
                dmrsMembership(:,j) = ismember(indices, ...
                    diagnostic.DMRSIndicesPerPort{j});
            end
            ptrsMembership = false(count,numel( ...
                diagnostic.PTRSIndicesPerPort));
            for j = 1:size(ptrsMembership,2)
                ptrsMembership(:,j) = ismember(indices, ...
                    diagnostic.PTRSIndicesPerPort{j});
            end

            sourceCount = sum(sourceMembership,2);
            for j = 1:numel(names)
                sourceList = sixgr.pdsch.PDSCHResourceOwnershipMap. ...
                    appendToken(sourceList,sourceMembership(:,j),names(j));
            end
            dmrsCount = sum(dmrsMembership,2);
            for j = 1:size(dmrsMembership,2)
                dmrsPorts = sixgr.pdsch.PDSCHResourceOwnershipMap. ...
                    appendToken(dmrsPorts,dmrsMembership(:,j), ...
                    string(diagnostic.DMRSLogicalPortSet(j)));
            end
            ptrsCount = sum(ptrsMembership,2);
            for j = 1:size(ptrsMembership,2)
                ptrsPorts = sixgr.pdsch.PDSCHResourceOwnershipMap. ...
                    appendToken(ptrsPorts,ptrsMembership(:,j), ...
                    string(diagnostic.PTRSLogicalPortSet(j)));
            end
            logicalPortCount = dmrsCount + ptrsCount;

            referenceUnavailable = ~available & logicalPortCount > 0;
            dmrsPTRS = dmrsCount > 0 & ptrsCount > 0;
            dmrsReserved = dmrsCount > 0 & sourceCount > 0;
            ptrsReserved = ptrsCount > 0 & sourceCount > 0;
            collisionTypes = sixgr.pdsch.PDSCHResourceOwnershipMap. ...
                appendToken(collisionTypes,referenceUnavailable, ...
                "reference_unavailable");
            collisionTypes = sixgr.pdsch.PDSCHResourceOwnershipMap. ...
                appendToken(collisionTypes,dmrsPTRS,"dmrs_ptrs");
            collisionTypes = sixgr.pdsch.PDSCHResourceOwnershipMap. ...
                appendToken(collisionTypes,dmrsReserved,"dmrs_reserved");
            collisionTypes = sixgr.pdsch.PDSCHResourceOwnershipMap. ...
                appendToken(collisionTypes,ptrsReserved,"ptrs_reserved");
            collisionCount = double(referenceUnavailable) + ...
                double(dmrsPTRS) + double(dmrsReserved) + ...
                double(ptrsReserved);

            outsideWithEvidence = ~inside & ...
                (sourceCount > 0 | logicalPortCount > 0);
            errorStatus(outsideWithEvidence) = "resource_outside_allocation";
            unavailableInside = inside & ~available;
            owner(unavailableInside) = "unavailable_by_frame_direction";
            collisionInside = inside & available & collisionCount > 0;
            owner(collisionInside) = "collision_error";
            errorStatus(collisionInside) = "illegal_overlap";
            eligible = inside & available & collisionCount == 0;
            owner(eligible & sourceCount > 1) = "reserved_multi_source";
            for j = 1:numel(names)
                oneSource = eligible & sourceCount == 1 & ...
                    sourceMembership(:,j);
                owner(oneSource) = string(ownerBySource.(names(j)));
            end
            noSource = eligible & sourceCount == 0;
            owner(noSource & dmrsCount > 0) = "pdsch_dmrs";
            owner(noSource & dmrsCount == 0 & ptrsCount > 0) = ...
                "pdsch_ptrs";
            owner(noSource & dmrsCount == 0 & ptrsCount == 0) = ...
                "pdsch_data";

            if isfinite(diagnostic.GridNumPRB)
                K = 12 * diagnostic.GridNumPRB;
                subcarrier = mod(indices,K);
                symbol = floor(indices/K);
                gridPRB = floor(subcarrier/12);
                prb = diagnostic.BWPStartPRB + gridPRB;
                bwpRelativePRB = gridPRB;
                absoluteSlot = repmat(diagnostic.AbsoluteSlot,count,1);
            else
                subcarrier = nan(count,1);
                symbol = nan(count,1);
                gridPRB = nan(count,1);
                prb = nan(count,1);
                bwpRelativePRB = nan(count,1);
                absoluteSlot = nan(count,1);
            end
            resolvedStatus = owner;
            entries = table(indices,absoluteSlot,symbol,subcarrier,gridPRB,prb, ...
                bwpRelativePRB,inside,available,owner,resolvedStatus,sourceList, ...
                sourceCount,dmrsPorts,ptrsPorts,logicalPortCount, ...
                collisionTypes,collisionCount,errorStatus, ...
                'VariableNames', { ...
                'Index0Based','AbsoluteSlot','Symbol0Based', ...
                'Subcarrier0Based','GridPRB0Based','CarrierPRB0Based', ...
                'BWPRelativePRB0Based','InsidePDSCHAllocation', ...
                'AvailableByFrameDirection','Owner','ResolvedStatus', ...
                'ReservationSources','ReservationSourceCount', ...
                'DMRSLogicalPorts','PTRSLogicalPorts', ...
                'LogicalPortCount','CollisionTypes','CollisionCount', ...
                'ErrorStatus'});
        end

        function values = appendToken(values, mask, token)
            mask = logical(mask(:));
            if ~any(mask)
                return;
            end
            empty = mask & strlength(values) == 0;
            values(empty) = string(token);
            populated = mask & ~empty;
            values(populated) = values(populated) + "|" + string(token);
        end
    end
end
