classdef PDSCHTBSScalarInputValidator
    %PDSCHTBSSCALARINPUTVALIDATOR Validate scalar PDSCH TBS ingress.
    %
    % This is a production trust boundary for callers that describe the
    % allocation before materializing nrCarrierConfig/nrPDSCHConfig.  It
    % validates only physical allocation inputs; it does not duplicate the
    % independent TBS/base-graph oracle.

    methods (Static)
        function normalized = validate(request)
            arguments
                request (1,1) struct
            end

            required = [ ...
                "NPRB","NScheduledSymbols","NDMRSREPerPRB", ...
                "NOverheadREPerPRB","Qm","TargetCodeRate", ...
                "NumLayers","TBScaling"];
            missing = required(~isfield(request, required));
            if ~isempty(missing)
                error( ...
                    "sixgr:pdsch:PDSCHTBSScalarInputValidator:MissingField", ...
                    "Scalar PDSCH TBS input is missing: %s.", ...
                    strjoin(cellstr(missing), ", "));
            end

            nPRB = sixgr.pdsch.PDSCHTBSScalarInputValidator. ...
                integer(request.NPRB);
            if ~(isfinite(nPRB) && nPRB >= 1 && nPRB <= 275)
                sixgr.pdsch.PDSCHTBSScalarInputValidator.fail( ...
                    "NPRBOutOfRange", ...
                    "NPRB must be an integer in [1,275].");
            end
            nSymbols = sixgr.pdsch.PDSCHTBSScalarInputValidator. ...
                integer(request.NScheduledSymbols);
            if ~(isfinite(nSymbols) && nSymbols >= 1 && nSymbols <= 14)
                sixgr.pdsch.PDSCHTBSScalarInputValidator.fail( ...
                    "SymbolAllocationEmpty", ...
                    "NScheduledSymbols must be an integer in [1,14].");
            end
            nDMRS = sixgr.pdsch.PDSCHTBSScalarInputValidator. ...
                nonnegativeInteger(request.NDMRSREPerPRB, ...
                "NDMRSREPerPRB");
            nOverhead = sixgr.pdsch.PDSCHTBSScalarInputValidator. ...
                nonnegativeInteger(request.NOverheadREPerPRB, ...
                "NOverheadREPerPRB");
            qm = sixgr.pdsch.PDSCHTBSScalarInputValidator.integer(request.Qm);
            if ~ismember(qm, [2 4 6 8 10])
                sixgr.pdsch.PDSCHTBSScalarInputValidator.fail( ...
                    "UnsupportedQm", ...
                    "Qm must be one of 2, 4, 6, 8, or 10.");
            end
            targetCodeRate = double(request.TargetCodeRate);
            if ~(isscalar(targetCodeRate) && isfinite(targetCodeRate) ...
                    && targetCodeRate > 0 && targetCodeRate <= 1)
                sixgr.pdsch.PDSCHTBSScalarInputValidator.fail( ...
                    "TargetCodeRateOutOfRange", ...
                    "TargetCodeRate must be finite in (0,1].");
            end
            numLayers = sixgr.pdsch.PDSCHTBSScalarInputValidator. ...
                integer(request.NumLayers);
            if ~(isfinite(numLayers) && numLayers >= 1 && numLayers <= 8)
                sixgr.pdsch.PDSCHTBSScalarInputValidator.fail( ...
                    "NumLayersOutOfRange", ...
                    "NumLayers must be an integer in [1,8].");
            end
            tbScaling = double(request.TBScaling);
            if ~(isscalar(tbScaling) && isfinite(tbScaling) ...
                    && tbScaling > 0 && tbScaling <= 1)
                sixgr.pdsch.PDSCHTBSScalarInputValidator.fail( ...
                    "TBScalingOutOfRange", ...
                    "TBScaling must be finite in (0,1].");
            end

            nREPrime = 12 * nSymbols - nDMRS - nOverhead;
            if nREPrime <= 0
                sixgr.pdsch.PDSCHTBSScalarInputValidator.fail( ...
                    "NegativeDataRE", ...
                    "DM-RS and overhead leave no PDSCH data RE per PRB.");
            end

            normalized = struct( ...
                "NPRB", nPRB, ...
                "NScheduledSymbols", nSymbols, ...
                "NDMRSREPerPRB", nDMRS, ...
                "NOverheadREPerPRB", nOverhead, ...
                "Qm", qm, ...
                "TargetCodeRate", targetCodeRate, ...
                "NumLayers", numLayers, ...
                "TBScaling", tbScaling, ...
                "NREPrimePerPRB", nREPrime, ...
                "Source", "production_pdsch_tbs_scalar_input_validation");
        end
    end

    methods (Static, Access = private)
        function value = integer(value)
            value = double(value);
            if ~(isscalar(value) && isfinite(value) ...
                    && value == fix(value))
                value = NaN;
            end
        end

        function value = nonnegativeInteger(value, name)
            value = sixgr.pdsch.PDSCHTBSScalarInputValidator.integer(value);
            if ~(isfinite(value) && value >= 0)
                sixgr.pdsch.PDSCHTBSScalarInputValidator.fail( ...
                    "InvalidResourceOverhead", ...
                    "%s must be a nonnegative integer.", name);
            end
        end

        function fail(token, message, varargin)
            id = "sixgr:pdsch:PDSCHTBSScalarInputValidator:" + token;
            error(char(id), message, varargin{:});
        end
    end
end
