classdef RASIPDSCHContext
    %RASIPDSCHCONTEXT Materialize strict common-procedure PDSCH ownership.
    %
    % This adapter is intentionally narrow: it supports the rank-one DCI
    % format 1_0 PDSCH used by Msg2/RAR, Msg4 contention resolution, and
    % SIB1.  The scheduling assignment is created only from a CRC-valid
    % PDCCH decoder event.  No configured PDSCH object is accepted as
    % scheduling ownership.  Transmitters use an explicit scheduled-DCI
    % event; receivers use a CRC-valid decoded-DCI event.

    methods (Static)
        function event = scheduledControlEvent(procedure, rnti, ...
                dciFormat, bits, varargin)
            ip = inputParser;
            ip.FunctionName = "sixgr.pdsch.RASIPDSCHContext.scheduledControlEvent";
            ip.addParameter("PDCCHAbsoluteSlot", 0, ...
                @(x) isnumeric(x) && isscalar(x) && isfinite(x) ...
                && x == fix(x) && x >= 0);
            ip.addParameter("PDCCHDataIndicesOneBased", [], ...
                @(x) isempty(x) || isnumeric(x));
            ip.addParameter("PDCCHDMRSIndicesOneBased", [], ...
                @(x) isempty(x) || isnumeric(x));
            ip.parse(varargin{:});
            opt = ip.Results;
            procedure = localProcedure(procedure);
            rntiType = localExpectedRNTIType(procedure);
            localRequireRNTI(rnti, rntiType);
            if upper(strtrim(string(dciFormat))) ~= "1_0"
                error("sixgr:pdsch:InvalidDCIRNTIProcedure", ...
                    "%s requires DCI format 1_0.", procedure);
            end
            bits = int8(bits(:));
            if isempty(bits) || any(bits ~= 0 & bits ~= 1)
                error("sixgr:pdsch:InvalidScheduledProcedureDCI", ...
                    "The scheduled DCI payload must be a nonempty binary vector.");
            end
            event = localControlEventIdentity(procedure, rnti, rntiType, ...
                bits, double(opt.PDCCHAbsoluteSlot));
            event.EvidenceRole = "transmitter_schedule";
            event.ControlAuthority = "transmitter_scheduled_dci";
            event.CRCPass = false;
            event.RNTIMatch = false;
            event.PayloadMatch = false;
            event.CausalGrantDecodeOk = false;
            event.DecodedRNTI = NaN;
            event.PDCCHDataIndicesOneBased = ...
                double(opt.PDCCHDataIndicesOneBased(:));
            event.PDCCHDMRSIndicesOneBased = ...
                double(opt.PDCCHDMRSIndicesOneBased(:));
            event.DecoderInfo = struct();
            event.Source = "actual_transmitter_scheduled_dci_event";
        end

        function event = decodedControlEvent(pdcchRx, pdcchInfo, ...
                procedure, rnti, dciFormat, expectedBits, varargin)
            ip = inputParser;
            ip.FunctionName = "sixgr.pdsch.RASIPDSCHContext.decodedControlEvent";
            ip.addParameter("PDCCHAbsoluteSlot", 0, ...
                @(x) isnumeric(x) && isscalar(x) && isfinite(x) ...
                && x == fix(x) && x >= 0);
            ip.addParameter("PDCCHDataIndicesOneBased", [], ...
                @(x) isempty(x) || isnumeric(x));
            ip.addParameter("PDCCHDMRSIndicesOneBased", [], ...
                @(x) isempty(x) || isnumeric(x));
            ip.addParameter("EvidenceRole", "receiver_decode", ...
                @(x) ischar(x) || isstring(x));
            ip.parse(varargin{:});
            opt = ip.Results;

            procedure = localProcedure(procedure);
            rntiType = localExpectedRNTIType(procedure);
            localRequireRNTI(rnti, rntiType);
            if upper(strtrim(string(dciFormat))) ~= "1_0"
                error("sixgr:pdsch:InvalidDCIRNTIProcedure", ...
                    "%s requires DCI format 1_0.", procedure);
            end
            if ~(isstruct(pdcchRx) && isscalar(pdcchRx) ...
                    && logical(sixgr.util.structGet(pdcchRx, "Ok", false)) ...
                    && double(sixgr.util.structGet(pdcchRx, "ErrFlag", 1)) == 0)
                error("sixgr:pdsch:UnvalidatedProcedureControlDCI", ...
                    "%s PDSCH ownership requires a CRC-valid PDCCH decoder event.", ...
                    procedure);
            end

            decodedBits = int8(sixgr.util.structGet( ...
                pdcchRx, "DCIBits", int8([])));
            decodedBits = decodedBits(:);
            if isempty(decodedBits) || any(decodedBits ~= 0 & decodedBits ~= 1)
                error("sixgr:pdsch:UnvalidatedProcedureControlDCI", ...
                    "The decoded DCI payload must be a nonempty binary vector.");
            end
            expectedBits = int8(expectedBits(:));
            payloadMatch = true;
            if ~isempty(expectedBits)
                payloadMatch = isequal(decodedBits, expectedBits);
                causal = logical(sixgr.util.structGet( ...
                    pdcchRx, "CausalGrantDecodeOk", false));
                if ~payloadMatch || ~causal
                    error("sixgr:pdsch:ProcedureDCIPayloadMismatch", ...
                        "CRC passed but decoded %s DCI does not match the scheduled control event.", ...
                        procedure);
                end
            end

            event = localControlEventIdentity(procedure, rnti, rntiType, ...
                decodedBits, double(opt.PDCCHAbsoluteSlot));
            event.EvidenceRole = string(opt.EvidenceRole);
            event.ControlAuthority = "receiver_crc_valid_decode";
            event.CRCPass = true;
            event.RNTIMatch = true;
            event.PayloadMatch = logical(payloadMatch);
            event.CausalGrantDecodeOk = logical(isempty(expectedBits) || ...
                sixgr.util.structGet(pdcchRx, "CausalGrantDecodeOk", false));
            event.DecodedRNTI = double(rnti);
            event.PDCCHDataIndicesOneBased = ...
                double(opt.PDCCHDataIndicesOneBased(:));
            event.PDCCHDMRSIndicesOneBased = ...
                double(opt.PDCCHDMRSIndicesOneBased(:));
            event.DecoderInfo = pdcchInfo;
            event.Source = "actual_pdcch_crc_valid_decoder_event";
        end

        function bundle = materialize(carrier, pdsch, event, context, varargin)
            ip = inputParser;
            ip.FunctionName = "sixgr.pdsch.RASIPDSCHContext.materialize";
            ip.addParameter("TransportBlockSize", [], ...
                @(x) isempty(x) || (isnumeric(x) && isscalar(x) ...
                && isfinite(x) && x == fix(x) && x > 0));
            ip.addParameter("NPhysicalRxAntennas", 1, ...
                @(x) isnumeric(x) && isscalar(x) && isfinite(x) ...
                && x == fix(x) && x >= 1);
            ip.addParameter("ChannelModel", "AWGN", ...
                @(x) ischar(x) || isstring(x));
            ip.addParameter("MaxIterations", 20, ...
                @(x) isnumeric(x) && isscalar(x) && isfinite(x) ...
                && x == fix(x) && x >= 1);
            ip.addParameter("MaterializationRole", "receiver", ...
                @(x) ischar(x) || (isstring(x) && isscalar(x)));
            ip.parse(varargin{:});
            opt = ip.Results;

            if ~isa(carrier, "nrCarrierConfig") || ~isa(pdsch, "nrPDSCHConfig")
                error("sixgr:pdsch:InvalidRASIWaveformConfiguration", ...
                    "RA/SI strict materialization requires explicit carrier and PDSCH objects.");
            end
            context = localValidateProcedureContext(context);
            materializationRole = lower(strtrim(string(opt.MaterializationRole)));
            if ~any(materializationRole == ["transmitter","receiver"])
                error("sixgr:pdsch:InvalidRASIMaterializationRole", ...
                    "MaterializationRole must be transmitter or receiver.");
            end
            event = localValidateEvent(event, context, materializationRole);
            rankValue = double(pdsch.NumLayers);
            if rankValue ~= 1
                error("sixgr:pdsch:UnsupportedRASIPDSCHRank", ...
                    "The common-procedure DCI 1_0 adapter supports rank-one PDSCH only.");
            end
            decodedGrant = localParseProcedureDCI( ...
                event.Bits, context.Procedure, carrier, context);
            localValidateDecodedGrant( ...
                decodedGrant, context, pdsch, carrier);
            event.DecodedGrant = decodedGrant;
            event.FieldProvenance = localFieldProvenance( ...
                context.Procedure, event.ControlAuthority);

            mcsContext = struct( ...
                "NumCodewords", 1, ...
                "RNTIType", string(context.RNTIType), ...
                "SelectionSource", string(event.ControlAuthority), ...
                "UECapability1024QAM", false, ...
                "RRCEnabled1024QAM", false, ...
                "DCIEnabled1024QAM", false, ...
                "DeploymentAllows1024QAM", false, ...
                "FrequencyRange", string(context.FrequencyRange), ...
                "OperatingBand", string(context.OperatingBand), ...
                "DeploymentClass", string(context.DeploymentClass), ...
                "FrequencyRangeAllows1024QAM", ...
                    localRequiredLogical( ...
                        context, "FrequencyRangeAllows1024QAM"), ...
                "BandAllows1024QAM", ...
                    localRequiredLogical(context, "BandAllows1024QAM"));
            mcs = sixgr.pdsch.PDSCHMCSResolver.resolve( ...
                string(context.MCSTable), ...
                double(decodedGrant.MCSIndex), mcsContext);
            if upper(string(pdsch.Modulation)) ~= upper(string(mcs.Modulation)) ...
                    || abs(double(context.TargetCodeRate) ...
                    - double(mcs.TargetCodeRate)) > 1e-12
                error("sixgr:pdsch:MCSAssignmentMismatch", ...
                    ['The procedure PDSCH and target rate do not match the ' ...
                     'decoded DCI MCS table/index: table=%s index=%d, ' ...
                     'configured modulation=%s rate=%.17g, decoded ' ...
                     'modulation=%s rate=%.17g.'], ...
                    char(string(context.MCSTable)), ...
                    round(double(decodedGrant.MCSIndex)), ...
                    char(string(pdsch.Modulation)), ...
                    double(context.TargetCodeRate), ...
                    char(string(mcs.Modulation)), ...
                    double(mcs.TargetCodeRate));
            end

            referenceAdapter = localReferenceAdapter(pdsch);
            reference = sixgr.pdsch.PDSCHReferenceSignalConfig( ...
                referenceAdapter);
            decoded = localDecodedDCI( ...
                event, context, decodedGrant, pdsch, mcs);
            ue = localUEContext(context);
            frame = struct( ...
                "AbsoluteSlot", double(context.PDSCHAbsoluteSlot), ...
                "ResourceAvailable", true);
            harq = struct( ...
                "ProcessId", double(context.HARQProcessId), ...
                "Consistent", true);
            if materializationRole == "transmitter"
                assignment = sixgr.pdsch.PDSCHAssignmentFactory.fromScheduledDCI( ...
                    decoded, sixgr.pdsch.PDSCHUEContext(ue), frame, harq);
            else
                assignment = sixgr.pdsch.PDSCHAssignmentFactory.fromDecodedDCI( ...
                    decoded, sixgr.pdsch.PDSCHUEContext(ue), frame, harq);
            end
            materialized = sixgr.pdsch.PDSCHConfigMaterializer. ...
                fromAssignment(assignment, referenceAdapter);
            localAssertMaterialization(materialized, pdsch);

            dmrsIndices = localDMRS( ...
                carrier, materialized, assignment.get("DMRSPortSet"));
            ptrsIndices = localPTRS( ...
                carrier, materialized, rankValue);
            allocation = localAllocation(carrier, ...
                double(assignment.get("PRBSetCarrierRelative")), ...
                double(assignment.get("SymbolAllocation")));
            reservations = localControlReservations( ...
                event, allocation, carrier);
            toolboxData = localToolboxDataIndices(carrier, materialized);
            referenceUnion = unique([dmrsIndices{:},ptrsIndices{:}], "sorted");
            controlReserved = zeros(1,0);
            if isfield(reservations, "CORESET")
                controlReserved = double(reservations.CORESET(:).');
            end
            % NumCDMGroupsWithoutData can exclude RE which do not carry a
            % DM-RS symbol on the selected port.  Preserve those RE as
            % explicit no-data ownership instead of inflating exact G.
            reservations.Other = setdiff(allocation, ...
                unique([toolboxData,referenceUnion,controlReserved], "sorted"), ...
                "stable");
            ownership = sixgr.pdsch.PDSCHResourceOwnershipMap( ...
                allocation, reservations);
            planContext = localPlanContext(assignment, carrier, ...
                dmrsIndices, ptrsIndices, 1, ...
                reference.ConfigurationDigest);
            provisionalPlan = sixgr.pdsch.PDSCHResourcePlan( ...
                ownership, planContext);

            tbs = localTBS(opt.TransportBlockSize, assignment, ...
                carrier, materialized);
            coding = sixgr.pdsch.DLSCHCodingPlan.resolve( ...
                "TransportBlockSize", tbs, ...
                "TargetCodeRate", double(assignment.get( ...
                    "TargetCodeRatePerCodeword")), ...
                "RateMatchedBitCount", provisionalPlan.GPerCodeword, ...
                "RV", double(assignment.get("RVPerCodeword")), ...
                "Modulation", string(assignment.get( ...
                    "ModulationPerCodeword")), ...
                "NumLayers", 1, "CodewordIndex", 0);
            planContext.CodeBlockCountPerCodeword = ...
                double(coding.NumCodeBlocks);
            resourcePlan = sixgr.pdsch.PDSCHResourcePlan( ...
                ownership, planContext);
            expectedData = setdiff(toolboxData, controlReserved, "stable");
            if ~isequal(sort(resourcePlan.DataIndices(:).'), ...
                    sort(expectedData(:).'))
                error("sixgr:pdsch:RASIDataResourceMismatch", ...
                    ['Strict resource-plan DataIndices differ from the ' ...
                     'actual PDSCH data mapping.']);
            end
            if ~isequal(resourcePlan.GPerCodeword, ...
                    provisionalPlan.GPerCodeword)
                error("sixgr:pdsch:RASIGContractMutation", ...
                    "Code-block materialization changed the exact PDSCH G contract.");
            end

            precoder = localIdentityPrecoder(assignment);
            integration = localIntegrationContext( ...
                assignment, carrier, precoder, context);
            channelModel = localChannelModel(opt.ChannelModel);
            if channelModel == "AWGN" ...
                    && double(opt.NPhysicalRxAntennas) ~= rankValue
                error("sixgr:pdsch:PDSCHReceiver:ReceiveReferencePortMismatch", ...
                    "AWGN common-procedure reception requires one receive port.");
            end
            receiver = struct( ...
                "TransportBlockSizes", double(tbs), ...
                "ChannelModel", char(channelModel), ...
                "MaxIterations", double(opt.MaxIterations), ...
                "Algorithm", "Normalized min-sum", ...
                "LLRConvention", "positive_favours_bit_zero", ...
                "NPhysicalRxAntennas", double(opt.NPhysicalRxAntennas));

            bundle = struct( ...
                "ContractVersion", "RASIPDSCHContext/v1", ...
                "Procedure", string(context.Procedure), ...
                "ControlEvent", event, ...
                "Assignment", assignment, ...
                "ResourcePlan", resourcePlan, ...
                "Carrier", carrier, ...
                "PDSCH", materialized, ...
                "ReferenceSignalConfig", reference, ...
                "ReceiverConfig", receiver, ...
                "CodingPlans", {{coding}}, ...
                "PrecoderBundle", precoder, ...
                "IntegrationContext", integration, ...
                "TransportBlockSize", double(tbs), ...
                "ExecutionProfile", "ra_si_strict", ...
                "Source", string(event.ControlAuthority) + ...
                    "_common_procedure_materialization");
        end

        function rx = addCompatibilityEvidence(rx)
            %ADDCompatibilityEvidence Preserve truthful legacy report fields.
            metrics = sixgr.util.structGet(rx, "Metrics", struct());
            channelGain = sixgr.util.structGet( ...
                rx, "ChannelGainPerPhysicalPort", []);
            if isempty(channelGain)
                channelGain = sixgr.util.structGet( ...
                    rx, "EffectiveLayerChannelEstimate", []);
            end
            sinr = double(sixgr.util.structGet( ...
                metrics, "MeasuredPostEqualizationSINRdBPerLayer", NaN));
            nmse = double(sixgr.util.structGet( ...
                metrics, "ChannelEstimateNMSE", NaN));
            finiteLLR = double(sixgr.util.structGet( ...
                metrics, "FiniteDescrambledLLRCountPerCodeword", 0));
            totalLLR = double(sixgr.util.structGet( ...
                metrics, "DescrambledLLRCountPerCodeword", 0));
            iterations = double(sixgr.util.structGet( ...
                metrics, "LDPCIterationCountPerCodeword", NaN));
            rx.ChannelEstimate = channelGain;
            rx.ChannelEstimateAvailable = ~isempty(channelGain) ...
                && all(isfinite(real(channelGain(:)))) ...
                && all(isfinite(imag(channelGain(:))));
            rx.EqualizationAvailable = ~isempty(sixgr.util.structGet( ...
                rx, "EqualizedGrid", []));
            rx.ChannelEstimateMethod = string(sixgr.util.structGet( ...
                rx, "ChannelEstimationMode", ""));
            rx.ChannelEstimatePilotResidualNMSE_dB = localLinearToDb(nmse);
            rx.PostEqSINR_dB = mean(sinr, "omitnan");
            rx.ReceiverHestSINR_dB = rx.PostEqSINR_dB;
            rx.ReceiverHestSINRSource = ...
                "canonical_pdsch_dmrs_estimate_and_equalizer";
            rx.PreEqualizationNoiseVar = double(sixgr.util.structGet( ...
                rx, "EstimatedNoiseVariance", NaN));
            rx.DecoderNoiseVar = mean(double(sixgr.util.structGet( ...
                rx, "NoiseVarianceUsedForLLR", NaN)), "omitnan");
            rx.LLRFinite = all(finiteLLR == totalLLR) && all(totalLLR > 0);
            rx.DemapperLLRCount = sum(totalLLR);
            rx.DecoderIterations = mean(iterations, "omitnan");
            rx.TimingEstimateUsed = false;
            rx.RawTimingEstimate_samples = NaN;
            rx.AppliedTimingCorrection_samples = 0;
            rx.TimingEstimateSource = ...
                "assignment_aligned_common_procedure_waveform";
            rx.StrictReceiverEvidenceOk = logical( ...
                rx.ChannelEstimateAvailable && rx.EqualizationAvailable ...
                && rx.LLRFinite && isfinite(rx.ReceiverHestSINR_dB));
        end
    end
end

function event = localControlEventIdentity(procedure, rnti, rntiType, bits, slot)
idPayload = struct( ...
    "Procedure", char(procedure), ...
    "RNTI", double(rnti), ...
    "RNTIType", char(rntiType), ...
    "DCIFormat", "1_0", ...
    "PDCCHAbsoluteSlot", double(slot), ...
    "Bits", double(bits(:).'));
bytes = uint8(unicode2native( ...
    jsonencode(orderfields(idPayload)), "UTF-8"));
event = struct( ...
    "Present", true, ...
    "Id", "RA-SI-DCI-" + string(sixgr.util.sha256Hex(bytes)), ...
    "Procedure", string(procedure), ...
    "EvidenceRole", "", ...
    "ControlAuthority", "", ...
    "CRCPass", false, ...
    "RNTIMatch", false, ...
    "PayloadMatch", false, ...
    "CausalGrantDecodeOk", false, ...
    "Format", "1_0", ...
    "RNTI", double(rnti), ...
    "DecodedRNTI", NaN, ...
    "RNTIType", string(rntiType), ...
    "Bits", int8(bits(:)), ...
    "PayloadHex", sixgr.rrc.asn1.bitsToHex(bits), ...
    "PDCCHAbsoluteSlot", double(slot), ...
    "PDCCHDataIndicesOneBased", zeros(0,1), ...
    "PDCCHDMRSIndicesOneBased", zeros(0,1), ...
    "DecoderInfo", struct(), ...
    "Source", "");
end

function context = localValidateProcedureContext(context)
if ~(isstruct(context) && isscalar(context))
    error("sixgr:pdsch:IncompleteRASIProcedureContext", ...
        "RA/SI procedure context must be a scalar struct.");
end
    required = [ ...
        "Procedure","RNTI","RNTIType","UEId","ServingCellId", ...
        "SchedulingCellId","CCId","BWPId","ConfigurationEpoch", ...
        "PDCCHAbsoluteSlot","PDSCHAbsoluteSlot","K0","MCSTable", ...
        "MCSIndex","TargetCodeRate","XOverhead","RV","NDI","HARQProcessId", ...
        "TCIStateId","ActiveBWPContextPresent","EpochCurrent", ...
        "ServingCellActive","MCSContextSupported","TCIStateActive", ...
        "UECapability1024QAM","RRCEnabled1024QAM", ...
        "DeploymentAllows1024QAM","FrequencyRange","OperatingBand", ...
        "DeploymentClass","FrequencyRangeAllows1024QAM", ...
        "BandAllows1024QAM"];
missing = required(~isfield(context, required));
if ~isempty(missing)
    error("sixgr:pdsch:IncompleteRASIProcedureContext", ...
        "RA/SI procedure context is missing: %s.", ...
        strjoin(cellstr(missing), ", "));
end
context.Procedure = localProcedure(context.Procedure);
expected = localExpectedRNTIType(context.Procedure);
if upper(strtrim(string(context.RNTIType))) ~= expected
    error("sixgr:pdsch:InvalidDCIRNTIProcedure", ...
        "Procedure %s requires %s, not %s.", ...
        context.Procedure, expected, string(context.RNTIType));
end
localRequireRNTI(context.RNTI, expected);
if double(context.PDCCHAbsoluteSlot) + double(context.K0) ...
        ~= double(context.PDSCHAbsoluteSlot)
    error("sixgr:pdsch:AssignmentSlotBindingMismatch", ...
        "Procedure PDCCHAbsoluteSlot + K0 must equal PDSCHAbsoluteSlot.");
end
end

function event = localValidateEvent(event, context, role)
if ~(isstruct(event) && isscalar(event) ...
        && logical(sixgr.util.structGet(event, "Present", false)))
    error("sixgr:pdsch:UnvalidatedProcedureControlDCI", ...
        "RA/SI assignment requires an explicit scheduled or decoded DCI event.");
end
authority = string(sixgr.util.structGet(event, "ControlAuthority", ""));
if role == "receiver"
    if authority ~= "receiver_crc_valid_decode" ...
            || ~logical(sixgr.util.structGet(event, "CRCPass", false)) ...
            || ~logical(sixgr.util.structGet(event, "RNTIMatch", false))
        error("sixgr:pdsch:UnvalidatedProcedureControlDCI", ...
            "Receiver RA/SI assignment requires a CRC-valid decoded DCI event.");
    end
elseif authority ~= "transmitter_scheduled_dci" ...
        || logical(sixgr.util.structGet(event, "CRCPass", false)) ...
        || logical(sixgr.util.structGet(event, "RNTIMatch", false))
    error("sixgr:pdsch:InvalidScheduledProcedureDCI", ...
        "Transmitter RA/SI assignment requires scheduled DCI ownership without receiver claims.");
end
if string(event.Procedure) ~= string(context.Procedure) ...
        || upper(string(event.RNTIType)) ~= upper(string(context.RNTIType)) ...
        || double(event.RNTI) ~= double(context.RNTI) ...
        || upper(string(event.Format)) ~= "1_0"
    error("sixgr:pdsch:InvalidDCIRNTIProcedure", ...
        "Decoded DCI event does not belong to the requested RA/SI procedure.");
end
if double(event.PDCCHAbsoluteSlot) ~= double(context.PDCCHAbsoluteSlot)
    error("sixgr:pdsch:AssignmentSlotBindingMismatch", ...
        "Decoded DCI event slot does not match the procedure context.");
end
end

function grant = localParseProcedureDCI(bits, procedure, carrier, context)
bits = int8(bits(:).');
procedure = localProcedure(procedure);
if procedure == "msg2_rar"
    if ~isfield(context,"DCIContext") || ...
            ~isa(context.DCIContext,"sixgr.phy.pdcch.DCIContext") || ...
            context.DCIContext.Data.RNTIType ~= "RA-RNTI" || ...
            context.DCIContext.Data.RNTIValue ~= context.RNTI
        error("sixgr:phy:pdcch:missing_dci_context", ...
            "Msg2 requires its receiver-known RA-RNTI common DCI context.");
    end
    decoded = sixgr.phy.pdcch.DCIParser.parse(bits,context.DCIContext);
    f = decoded.Fields;
    if f.vrb_to_prb_mapping ~= 0
        error("sixgr:pdsch:UnsupportedRARInterleaving", ...
            "Interleaved RAR VRB mapping is not materialized by this adapter.");
    end
    grant = struct("PRBStart",f.prb_start + f.reference_start - double(carrier.NStartGrid), ...
        "PRBCount",f.num_prb,"SymbolAllocation",[f.symbol_start f.num_symbols], ...
        "MCSIndex",f.mcs,"RV",0,"NDI",1,"VRBToPRBMapping","non_interleaved", ...
        "TDRAIndex",f.time_resource_assignment,"SIIndicator",NaN, ...
        "TBScaling",f.tb_scaling_factor,"MappingType",f.mapping_type, ...
        "DecodedFieldSource","crc_valid_ra_rnti_dci_payload_bits");
    return;
end
if procedure == "msg4_contention_resolution"
    if ~isfield(context,"DCIContext") || ...
            ~isa(context.DCIContext,"sixgr.phy.pdcch.DCIContext") || ...
            context.DCIContext.Data.RNTIType ~= "TC-RNTI" || ...
            context.DCIContext.Data.RNTIValue ~= context.RNTI
        error("sixgr:phy:pdcch:missing_dci_context", ...
            "Msg4 requires its receiver-known TC-RNTI CORESET0/common DCI context.");
    end
    decoded = sixgr.phy.pdcch.DCIParser.parse(bits,context.DCIContext);
    f = decoded.Fields;
    assert(f.vrb_to_prb_mapping==0,'sixgr:pdsch:UnsupportedMsg4Interleaving', ...
        'Interleaved Msg4 is not materialized by this adapter.');
    grant = struct("PRBStart",f.prb_start+f.reference_start-double(carrier.NStartGrid), ...
        "PRBCount",f.num_prb,"SymbolAllocation",[f.symbol_start f.num_symbols], ...
        "MCSIndex",f.mcs,"RV",f.rv,"NDI",f.ndi,"HARQProcessId",f.harq_process, ...
        "VRBToPRBMapping","non_interleaved","TDRAIndex",f.time_resource_assignment, ...
        "SIIndicator",NaN,"MappingType",f.mapping_type, ...
        "TPCCommandForPUCCH",f.tpc_command_for_pucch, ...
        "PUCCHResourceIndicator",f.pucch_resource_indicator, ...
        "PDSCHToHARQFeedbackTimingIndicator",f.pdsch_to_harq_feedback_timing, ...
        "DecodedFieldSource","crc_valid_tc_rnti_dci_payload_bits");
    return;
end
requiredBits = sixgr.phy.pdcch.dciPayloadSizeBits(double(carrier.NSizeGrid),"1_0");
if numel(bits)~=requiredBits || any(bits~=0 & bits~=1)
    error("sixgr:pdsch:ProcedureDCIFieldOutOfRange", ...
        "The %s DCI format 1_0 payload must contain exactly %d bits.",procedure,requiredBits);
end
if procedure == "sib1"
    nRB = double(carrier.NSizeGrid);
    rivWidth = ceil(log2(nRB * (nRB + 1) / 2));
    [riv,pos] = localReadUInt(bits,1,rivWidth);
    [tdra,pos] = localReadUInt(bits,pos,4);
    [vrb,pos] = localReadUInt(bits,pos,1);
    [mcsIndex,pos] = localReadUInt(bits,pos,5);
    [rv,pos] = localReadUInt(bits,pos,2);
    [siIndicator,~] = localReadUInt(bits,pos,1);
    [prbCount,prbStart] = localDecodeRIV(nRB,riv);
    mapping = "non_interleaved";
    if vrb == 1
        mapping = "interleaved";
    end
    if tdra ~= 0
        error("sixgr:pdsch:ProcedureDCIFieldOutOfRange", ...
            "The supported SIB1 common-search-space profile requires TDRA row 0.");
    end
    if siIndicator ~= 0
        error("sixgr:pdsch:ProcedureDCIFieldOutOfRange", ...
            "The supported SI-RNTI profile requires the SIB1 SI indicator.");
    end
    grant = struct( ...
        "PRBStart", double(prbStart), ...
        "PRBCount", double(prbCount), ...
        "SymbolAllocation", [2 12], ...
        "MCSIndex", double(mcsIndex), ...
        "RV", double(rv), ...
        "NDI", 1, ...
        "VRBToPRBMapping", mapping, ...
        "TDRAIndex", double(tdra), ...
        "SIIndicator", double(siIndicator), ...
        "DecodedFieldSource", "crc_valid_si_rnti_dci_payload_bits");
end
if grant.PRBCount < 1 ...
        || grant.PRBStart + grant.PRBCount > double(carrier.NSizeGrid) ...
        || grant.SymbolAllocation(2) < 1 ...
        || sum(grant.SymbolAllocation) > double(carrier.SymbolsPerSlot) ...
        || grant.MCSIndex < 0 || grant.MCSIndex > 31 ...
        || ~ismember(grant.RV,0:3) || ~ismember(grant.NDI,[0 1])
    error("sixgr:pdsch:ProcedureDCIFieldOutOfRange", ...
        "Decoded RA/SI DCI contains a field outside the active carrier/profile.");
end
end

function localValidateDecodedGrant(grant, context, pdsch, carrier)
if isfield(grant,'HARQProcessId') && grant.HARQProcessId~=context.HARQProcessId
    error('sixgr:pdsch:ProcedureDCIFieldMismatch','Msg4 HARQ process must come from the decoded DCI.');
end
decodedPRB = double(grant.PRBStart) ...
    + (0:(double(grant.PRBCount)-1));
configuredPRB = double(pdsch.PRBSet(:).');
configuredSymbols = double(pdsch.SymbolAllocation(:).');
    if ~isprop(pdsch, "VRBToPRBInterleaving") ...
            || ~(islogical(pdsch.VRBToPRBInterleaving) ...
            || (isnumeric(pdsch.VRBToPRBInterleaving) ...
            && isscalar(pdsch.VRBToPRBInterleaving) ...
            && isfinite(pdsch.VRBToPRBInterleaving)))
        error("sixgr:pdsch:IncompleteRASIProcedureContext", ...
            "RA/SI PDSCH requires explicit VRB-to-PRB mapping state.");
    end
    if logical(pdsch.VRBToPRBInterleaving)
        mapping = "interleaved";
    else
        mapping = "non_interleaved";
    end
if ~isequal(decodedPRB,configuredPRB) ...
        || ~isequal(double(grant.SymbolAllocation),configuredSymbols) ...
        || double(grant.MCSIndex) ~= double(context.MCSIndex) ...
        || double(grant.RV) ~= double(context.RV) ...
        || double(grant.NDI) ~= double(context.NDI) ...
        || string(grant.VRBToPRBMapping) ~= mapping
    error("sixgr:pdsch:ProcedureDCIFieldMismatch", ...
        '%s', ['CRC-valid DCI scheduling fields do not match the procedure ' ...
        'PDSCH materialization/context.']);
end
if any(decodedPRB < 0 | decodedPRB >= double(carrier.NSizeGrid))
    error("sixgr:pdsch:ProcedureDCIFieldOutOfRange", ...
        "Decoded DCI PRBs lie outside the active common-procedure BWP.");
end
if isfield(grant,"MappingType") && string(grant.MappingType)~=string(pdsch.MappingType)
    error("sixgr:pdsch:ProcedureDCIFieldMismatch","PDSCH mapping type differs from decoded common TDRA.");
end
end

function provenance = localFieldProvenance(procedure, authority)
if string(authority) == "transmitter_scheduled_dci"
    decoded = "transmitter_scheduled_dci_payload_bits";
else
    decoded = "crc_valid_dci_payload_bits";
end
procedureOwned = "validated_common_procedure_context";
provenance = struct( ...
    "PRBSet", decoded, ...
    "SymbolAllocation", decoded, ...
    "MCSIndex", decoded, ...
    "RV", decoded, ...
    "NDI", decoded, ...
    "VRBToPRBMapping", procedureOwned, ...
    "MCSTable", procedureOwned, ...
    "TargetCodeRate", "derived_from_control_mcs_index_and_procedure_table", ...
    "MappingType", procedureOwned, ...
    "DMRSConfiguration", procedureOwned, ...
    "XOverhead", procedureOwned, ...
    "TCIState", procedureOwned);
if localProcedure(procedure) == "sib1"
    provenance.VRBToPRBMapping = decoded;
    provenance.NDI = "fixed_sib1_new_transport_block_procedure_state";
elseif localProcedure(procedure) == "msg2_rar"
    provenance.VRBToPRBMapping = decoded;
    provenance.NDI = "new_rar_transport_block_procedure_state_not_dci_field";
    provenance.RV = "ra_rnti_redundancy_version_zero_not_dci_field";
    provenance.TBScaling = decoded;
    provenance.MappingType = "decoded_tdra_index_and_installed_common_allocation_table";
end
end

function [value,next] = localReadUInt(bits,pos,width)
if pos < 1 || width < 1 || pos + width - 1 > numel(bits)
    error("sixgr:pdsch:ProcedureDCIFieldOutOfRange", ...
        "DCI bit-field read extends beyond the payload.");
end
value = uint64(0);
for idx = 1:width
    value = bitshift(value,1) + uint64(bits(pos+idx-1) ~= 0);
end
value = double(value);
next = pos + width;
end

function [lengthRB,startRB] = localDecodeRIV(nRB,riv)
lengthRB = floor(double(riv) / nRB) + 1;
startRB = double(riv) - nRB * (lengthRB - 1);
if lengthRB > nRB - startRB
    lengthRB = nRB - lengthRB + 2;
    startRB = nRB - 1 - startRB;
end
end

function decoded = localDecodedDCI( ...
        event, context, decodedGrant, pdsch, mcs)
prbSet = double(decodedGrant.PRBStart) ...
    + (0:(double(decodedGrant.PRBCount)-1));
ports = double(pdsch.DMRS.DMRSPortSet(:).');
if isempty(ports)
    error("sixgr:pdsch:MissingProcedureDMRSPort", ...
        "RA/SI procedure PDSCH requires an explicit logical DM-RS port.");
end
ptrsConfigId = "";
ptrsPorts = zeros(1,0);
if logical(pdsch.EnablePTRS)
    ptrsConfigId = string(context.Procedure) + "-PTRS";
    ptrsPorts = double(pdsch.PTRS.PTRSPortSet(:).');
end
decoded = struct( ...
    "Present", true, ...
    "Id", string(event.Id), ...
    "CRCPass", logical(event.CRCPass), ...
    "RNTIMatch", logical(event.RNTIMatch), ...
    "FieldsInRange", true, ...
    "Format", "1_0", ...
    "RNTI", double(context.RNTI), ...
    "DecodedRNTI", double(event.DecodedRNTI), ...
    "RNTIType", string(context.RNTIType), ...
    "DCIEnabled1024QAM", false, ...
    "PDCCHAbsoluteSlot", double(context.PDCCHAbsoluteSlot), ...
    "SearchSpaceId", string(context.Procedure) + "-COMMON-SS", ...
    "CORESETId", string(context.Procedure) + "-CORESET", ...
    "FDRAType", "type1", ...
    "FrequencyDomainAssignmentRaw", string(event.PayloadHex), ...
    "RBGSize", 1, ...
    "VRBToPRBMapping", string(decodedGrant.VRBToPRBMapping), ...
    "InterleaverBundleSize", 2, ...
    "PRBSetBWPRelative", prbSet, ...
    "PRBSetCarrierRelative", prbSet, ...
    "TDRAListId", string(context.Procedure) + "-TDRA", ...
    "TDRARowIndex", localTDRARow(decodedGrant), ...
    "K0", double(context.K0), ...
    "SLIV", NaN, ...
    "SymbolAllocation", double(decodedGrant.SymbolAllocation(:).'), ...
    "MappingType", upper(string(pdsch.MappingType)), ...
    "MCSTablePerCodeword", string(context.MCSTable), ...
    "MCSIndexPerCodeword", double(decodedGrant.MCSIndex), ...
    "ModulationPerCodeword", upper(string(mcs.Modulation)), ...
    "QmPerCodeword", double(mcs.Qm), ...
    "TargetCodeRatePerCodeword", double(mcs.TargetCodeRate), ...
    "TBScalingPerCodeword", double(sixgr.util.structGet(decodedGrant,"TBScaling",1)), ...
    "XOverhead", double(context.XOverhead), ...
    "NumLayers", 1, ...
    "NumCodewords", 1, ...
    "LayerCountPerCodeword", 1, ...
    "AntennaPortField", ports, ...
    "DMRSConfigId", string(context.Procedure) + "-DMRS", ...
    "DMRSPortSet", ports, ...
    "PTRSConfigId", ptrsConfigId, ...
    "PTRSPortSet", ptrsPorts, ...
    "NDIPerCodeword", double(decodedGrant.NDI), ...
    "RVPerCodeword", double(decodedGrant.RV), ...
    "DAI", 0, ...
    "TCIStateId", double(context.TCIStateId), ...
    "RateMatchPatternIds", strings(1,0), ...
    "ZPCSIRSResourceIds", strings(1,0), ...
    "TransmissionConfigurationIndication", double(context.TCIStateId));
end

function ue = localUEContext(context)
ue = struct( ...
    "UEId", double(context.UEId), ...
    "ServingCellId", double(context.ServingCellId), ...
    "SchedulingCellId", double(context.SchedulingCellId), ...
    "CCId", double(context.CCId), ...
    "BWPId", double(context.BWPId), ...
    "ConfigurationEpoch", double(context.ConfigurationEpoch), ...
    "ActiveBWPContextPresent", ...
        localRequiredLogical(context, "ActiveBWPContextPresent"), ...
    "EpochCurrent", localRequiredLogical(context, "EpochCurrent"), ...
    "ServingCellActive", ...
        localRequiredLogical(context, "ServingCellActive"), ...
    "MCSContextSupported", ...
        localRequiredLogical(context, "MCSContextSupported"), ...
    "TCIStateActive", ...
        localRequiredLogical(context, "TCIStateActive"), ...
    "UECapability1024QAM", ...
        localRequiredLogical(context, "UECapability1024QAM"), ...
    "RRCEnabled1024QAM", ...
        localRequiredLogical(context, "RRCEnabled1024QAM"), ...
    "DeploymentAllows1024QAM", ...
        localRequiredLogical(context, "DeploymentAllows1024QAM"), ...
    "FrequencyRange", string(context.FrequencyRange), ...
    "OperatingBand", string(context.OperatingBand), ...
    "DeploymentClass", string(context.DeploymentClass), ...
    "FrequencyRangeAllows1024QAM", ...
        localRequiredLogical(context, "FrequencyRangeAllows1024QAM"), ...
    "BandAllows1024QAM", ...
        localRequiredLogical(context, "BandAllows1024QAM"));
end

function reference = localReferenceAdapter(pdsch)
if isprop(pdsch.DMRS,"DMRSEnhancedR18") ...
        && logical(pdsch.DMRS.DMRSEnhancedR18)
    multiplexing = "enhanced";
else
    multiplexing = "basic";
end
% TS 38.214 Table 4.1-1: data EPRE relative to DM-RS EPRE. Both
% transmitter and receiver derive this from the materialized CDM ownership.
cdmGroups = localRequiredObjectNumber(pdsch.DMRS, "NumCDMGroupsWithoutData");
dmrsType = localRequiredObjectNumber(pdsch.DMRS, "DMRSConfigurationType");
validateattributes(cdmGroups, {'numeric'}, ...
    {'scalar','integer','>=',1,'<=',2 + double(dmrsType == 2)});
epreRatios = [0 -3 -4.77];
epreRatio = epreRatios(cdmGroups);
reference = struct( ...
    "NID", localRequiredObjectNumber(pdsch, "NID"), ...
    "DataScramblingIdentityNID", ...
        localRequiredObjectNumber(pdsch, "NID"), ...
    "DMRSConfigurationType", ...
        localRequiredObjectNumber(pdsch.DMRS, "DMRSConfigurationType"), ...
    "DMRSTypeAPosition", ...
        localRequiredObjectNumber(pdsch.DMRS, "DMRSTypeAPosition"), ...
    "DMRSAdditionalPosition", ...
        localRequiredObjectNumber(pdsch.DMRS, "DMRSAdditionalPosition"), ...
    "DMRSLength", localRequiredObjectNumber(pdsch.DMRS, "DMRSLength"), ...
    "NumCDMGroupsWithoutData", ...
        localRequiredObjectNumber(pdsch.DMRS, "NumCDMGroupsWithoutData"), ...
    "NIDNSCID", localRequiredObjectNumber(pdsch.DMRS, "NIDNSCID"), ...
    "NSCID", localRequiredObjectNumber(pdsch.DMRS, "NSCID"), ...
    "DMRSMultiplexing",multiplexing, ...
    "EnablePTRS", logical(pdsch.EnablePTRS), ...
    "NPhysicalTxAntennas",double(pdsch.NumLayers), ...
    "OFDMOptions",{cell(1,0)}, ...
    "PDSCHToDMRSEPRERatio_dB",epreRatio, ...
    "DMRSPowerAllocationSource","TS38.214_Table4.1-1", ...
    "DMRSAmplitudeScale",10^(-epreRatio/20), ...
    "PTRSAmplitudeScale",1);
if reference.EnablePTRS
    reference.PTRSTimeDensity = double(pdsch.PTRS.TimeDensity);
    reference.PTRSFrequencyDensity = double(pdsch.PTRS.FrequencyDensity);
    reference.PTRSREOffset = string(pdsch.PTRS.REOffset);
end
end

function localAssertMaterialization(actual, expected)
fields = ["PRBSet","SymbolAllocation","NumLayers","RNTI","NID"];
for idx = 1:numel(fields)
    field = fields(idx);
    if ~isequal(double(actual.(field)), double(expected.(field)))
        error("sixgr:pdsch:RASIMaterializationMismatch", ...
            "Assignment materialization changed PDSCH.%s.", field);
    end
end
expectedPorts = double(expected.DMRS.DMRSPortSet);
if upper(string(actual.Modulation)) ~= upper(string(expected.Modulation)) ...
        || upper(string(actual.MappingType)) ~= upper(string(expected.MappingType)) ...
        || ~isequal(double(actual.DMRS.DMRSPortSet), expectedPorts)
    error("sixgr:pdsch:RASIMaterializationMismatch", ...
        "Assignment materialization changed modulation, mapping, or DM-RS ports.");
end
end

function indices = localDMRS(carrier, pdsch, ports)
sub = nrPDSCHDMRSIndices(carrier, pdsch, ...
    "IndexStyle", "subscript", "IndexBase", "0based");
K = double(carrier.NSizeGrid) * 12;
indices = cell(1, numel(ports));
for idx = 1:numel(ports)
    mask = double(sub(:,3)) == double(ports(idx));
    indices{idx} = double(sub(mask,1) + K * sub(mask,2)).';
    if isempty(indices{idx})
        error("sixgr:pdsch:RASIDMRSShapeMismatch", ...
            "No DM-RS indices were generated for logical port %d.", ...
            ports(idx));
    end
end
end

function indices = localPTRS(carrier, pdsch, rankValue)
indices = repmat({zeros(1,0)}, 1, rankValue);
if ~logical(pdsch.EnablePTRS)
    return;
end
sub = nrPDSCHPTRSIndices(carrier, pdsch, ...
    "IndexStyle", "subscript", "IndexBase", "0based");
K = double(carrier.NSizeGrid) * 12;
ports = unique(double(sub(:,3)), "stable");
for idx = 1:numel(ports)
    layer = ports(idx) + 1;
    mask = double(sub(:,3)) == ports(idx);
    indices{layer} = double(sub(mask,1) + K * sub(mask,2)).';
end
end

function allocation = localAllocation(carrier, prbSet, symbolAllocation)
subcarriers = reshape(12 * prbSet(:).' + (0:11).', 1, []);
symbols = symbolAllocation(1) + (0:symbolAllocation(2)-1);
[k,l] = ndgrid(subcarriers, symbols);
allocation = sort(double(k(:) + 12 * carrier.NSizeGrid * l(:))).';
end

function indices = localToolboxDataIndices(carrier, pdsch)
sub = nrPDSCHIndices(carrier, pdsch, ...
    "IndexStyle", "subscript", "IndexBase", "0based");
if isempty(sub)
    error("sixgr:pdsch:NoPDSCHDataREAfterReferenceSignals", ...
        "The materialized RA/SI PDSCH contains no data RE.");
end
K = double(carrier.NSizeGrid) * 12;
indices = unique(double(sub(:,1) + K * sub(:,2)), "sorted").';
end

function reservations = localControlReservations(event, allocation, carrier)
plane = double(carrier.NSizeGrid) * 12 * double(carrier.SymbolsPerSlot);
indices = [double(event.PDCCHDataIndicesOneBased(:)); ...
    double(event.PDCCHDMRSIndicesOneBased(:))];
if isempty(indices)
    reservations = struct();
    return;
end
if any(~isfinite(indices) | indices ~= fix(indices) | indices < 1)
    error("sixgr:pdsch:InvalidProcedureControlRE", ...
        "PDCCH reservation indices must be positive one-based integers.");
end
zeroBased = unique(mod(indices - 1, plane), "sorted").';
reservations = struct("CORESET", ...
    intersect(allocation, zeroBased, "stable"));
end

function context = localPlanContext( ...
        assignment, carrier, dmrs, ptrs, blocks, referenceDigest)
ports = double(assignment.get("DMRSPortSet"));
context = struct( ...
    "PRBSet", double(assignment.get("PRBSetCarrierRelative")), ...
    "SymbolAllocation", double(assignment.get("SymbolAllocation")), ...
    "GridNumPRB", double(carrier.NSizeGrid), ...
    "GridSymbolsPerSlot",double(carrier.SymbolsPerSlot), ...
    "BWPStartPRB",double(carrier.NStartGrid), ...
    "AbsoluteSlot",double(assignment.get("PDSCHAbsoluteSlot")), ...
    "UnavailableIndices",zeros(1,0), ...
    "DMRSIndicesPerPort", {dmrs}, ...
    "PTRSIndicesPerPort", {ptrs}, ...
    "DMRSLogicalPortSet",ports, ...
    "PTRSLogicalPortSet",ports, ...
    "LayerCountPerCodeword", ...
        double(assignment.get("LayerCountPerCodeword")), ...
    "QmPerCodeword", double(assignment.get("QmPerCodeword")), ...
    "CodeBlockCountPerCodeword", double(blocks), ...
    "ReferenceConfigurationDigest",string(referenceDigest));
end

function tbs = localTBS(requested, assignment, carrier, pdsch)
% TS 38.214 TBS uses the standardized N_RE-per-PRB accounting, while the
% exact rate-matching G below uses the actual data indices after PT-RS and
% other reservations.  PT-RS frequency density can make actual data RE
% nonuniform across PRBs; rejecting that valid mapping conflates these two
% distinct quantities.
computed = sixgr.pdsch.TBSCalculator(carrier, pdsch, ...
    double(assignment.get("TargetCodeRatePerCodeword")), ...
    double(assignment.get("XOverhead")),double(assignment.get("TBScalingPerCodeword")));
computed = double(computed);
if isempty(requested)
    tbs = computed;
elseif double(requested) ~= computed
    error("sixgr:pdsch:RASITransportBlockSizeMismatch", ...
        "Persisted TBS=%d differs from exact assignment/resource TBS=%d.", ...
        double(requested), computed);
else
    tbs = double(requested);
end
end

function index = localTDRARow(grant)
index = double(sixgr.util.structGet(grant,"TDRAIndex",NaN));
if ~isfinite(index)
    error('sixgr:pdsch:MissingProcedureTDRAIndex','RA/SI assignment requires its decoded on-air TDRA index.');
end
end

function bundle = localIdentityPrecoder(assignment)
rankValue = double(assignment.get("NumLayers"));
prbs = double(assignment.get("PRBSetCarrierRelative"));
allocation = double(assignment.get("SymbolAllocation"));
symbols = allocation(1) + (0:allocation(2)-1);
mode = "wideband_fixed_matrix";
if rankValue == 1
    mode = "siso_identity";
end
spec = struct( ...
    "Mode", mode, ...
    "NPorts", rankValue, ...
    "NLayers", rankValue, ...
    "NPRG", 1, ...
    "NSymbolGroups", 1, ...
    "PRGSize", 0, ...
    "PRBSet", prbs, ...
    "ScheduledSymbols", symbols, ...
    "SymbolGroupMap", zeros(1,numel(symbols)), ...
    "W", reshape(eye(rankValue),rankValue,rankValue,1,1), ...
    "MatrixSource", "ra_si_common_procedure_identity", ...
    "CodebookIdentifier", "", ...
    "NormalizationConvention", "semi_unitary");
bundle = sixgr.pdsch.PDSCHPrecoderBundle(spec);
end

function context = localIntegrationContext(assignment, carrier, precoder, procedureContext)
data = assignment.toStruct();
assignmentDigest = assignment.validateForExecution();
reference=sixgr.pdsch.CommonPDSCHQCLReference.validate( ...
    sixgr.util.structGet(procedureContext,'CommonQCLReference',struct()),data);
reference.PrecoderContextId="RA-SI-PRECODER-"+string(data.AssignmentId);
reference.PrecoderBundleDigest=precoder.ImmutableBundleDigest;
reference.PrecoderAssignmentId=string(data.AssignmentId);
reference.PrecoderAssignmentValidationDigest=string(assignmentDigest);
reference.PrecoderConfigurationEpoch=double(data.ConfigurationEpoch);
context = struct( ...
    "ActiveServingCellIds", unique([double(data.ServingCellId), ...
        double(data.SchedulingCellId)]), ...
    "ActiveCCIds", double(data.CCId), ...
    "ActiveBWPId", double(data.BWPId), ...
    "ActiveBWPStartPRB", 0, ...
    "ActiveBWPNumPRB", double(carrier.NSizeGrid), ...
    "ConfigurationEpoch", double(data.ConfigurationEpoch), ...
    "CarrierIndicatorValid", true, ...
    "CrossCarrierSchedulingEnabled", true, ...
    "CommonQCLReference", reference);
end

function value = localRequiredObjectNumber(obj, name)
if ~isprop(obj, name)
    error("sixgr:pdsch:IncompleteRASIReferenceConfiguration", ...
        "RA/SI reference configuration is missing property %s.", name);
end
value = double(obj.(name));
if ~(isscalar(value) && isfinite(value))
    error("sixgr:pdsch:IncompleteRASIReferenceConfiguration", ...
        "RA/SI reference property %s must be an explicit finite scalar.", ...
        name);
end
end

function value = localRequiredLogical(data, name)
value = data.(name);
if ~(islogical(value) && isscalar(value))
    error("sixgr:pdsch:IncompleteRASIProcedureContext", ...
        "RA/SI procedure field %s must be an explicit logical scalar.", ...
        name);
end
end

function procedure = localProcedure(value)
procedure = lower(strtrim(string(value)));
if ~any(procedure == ["msg2_rar","msg4_contention_resolution","sib1"])
    error("sixgr:pdsch:InvalidDCIRNTIProcedure", ...
        "Unsupported RA/SI PDSCH procedure '%s'.", procedure);
end
end

function type = localExpectedRNTIType(procedure)
switch localProcedure(procedure)
    case "msg2_rar"
        type = "RA-RNTI";
    case "msg4_contention_resolution"
        type = "TC-RNTI";
    case "sib1"
        type = "SI-RNTI";
end
end

function localRequireRNTI(value, type)
value = double(value);
if ~(isscalar(value) && isfinite(value) && value == fix(value) ...
        && value >= 0 && value <= 65535)
    error("sixgr:pdsch:InvalidDCIRNTIProcedure", ...
        "%s value must be an integer in [0,65535].", type);
end
if type == "SI-RNTI" && value ~= 65535
    error("sixgr:pdsch:InvalidDCIRNTIProcedure", ...
        "SIB1 requires SI-RNTI 65535.");
end
end

function model = localChannelModel(value)
model = upper(strtrim(string(value)));
if model == "AWGN" || startsWith(model, "TDL-") ...
        || startsWith(model, "CDL-")
    return;
end
error("sixgr:pdsch:PDSCHReceiver:ConcreteFadingProfileRequired", ...
    "ChannelModel must be AWGN or a concrete TDL-*/CDL-* profile.");
end

function value = localLinearToDb(value)
if ~(isscalar(value) && isfinite(value) && value >= 0)
    value = NaN;
elseif value == 0
    value = -Inf;
else
    value = 10 * log10(value);
end
end
