classdef ComponentQualificationPublisher
    %COMPONENTQUALIFICATIONPUBLISHER Fresh phase-pack evidence publication.
    %
    % The checked-in artifacts/ tree is a contract/reference inventory only.
    % Every published file is regenerated by the selected production phase
    % runner in a transaction-owned stage, validated against tests/vectors,
    % and then atomically installed beneath:
    %   <run>/components/<domain>/qualification/{csv,png,logs}
    %
    % Qualification evidence is deliberately distinct from in-path scenario
    % evidence.  The manifest never labels a component-validation campaign as
    % the waveform execution of the parent WebGUI scenario.

    methods (Static)
        function result = run(runFolder, options)
            arguments
                runFolder (1,1) string
                options.Components string = "all"
                options.SeedList (1,:) double = [11 23 47 89]
                options.ConfidenceLevel (1,1) double = 0.95
                options.Strict (1,1) logical = true
                options.ReplaceExisting (1,1) logical = false
            end
            if ~options.Strict
                error("sixgr:artifact:QualificationStrictRequired", ...
                    "Component qualification publication requires Strict=true.");
            end
            if any(~isfinite(options.SeedList) | ...
                    options.SeedList ~= fix(options.SeedList))
                error("sixgr:artifact:QualificationSeedInvalid", ...
                    "Qualification seeds must be finite integers.");
            end
            if ~(isfinite(options.ConfidenceLevel) && ...
                    options.ConfidenceLevel > 0 && ...
                    options.ConfidenceLevel < 1)
                error("sixgr:artifact:QualificationConfidenceInvalid", ...
                    "ConfidenceLevel must be strictly between zero and one.");
            end

            repositoryRoot = sixgr.artifact.ContractCatalog.repositoryRoot();
            runFolder = localOwnedRunFolder(runFolder, repositoryRoot);
            if ~isfolder(runFolder)
                mkdir(runFolder);
            end
            rasterDefaults = sixgr.visual.RasterFigureStyle.installDefaults();
            rasterDefaultsCleanup = onCleanup(@() ...
                sixgr.visual.RasterFigureStyle.restoreDefaults(rasterDefaults)); %#ok<NASGU>
            auditDir = fullfile(runFolder, "artifact_generation");
            manifestPath = fullfile(auditDir, ...
                "component_qualification_manifest.csv");
            summaryPath = fullfile(auditDir, ...
                "component_qualification_summary.csv");
            registry = localRunnerRegistry(repositoryRoot);
            components = localSelectComponents(options.Components, registry);
            catalog = sixgr.artifact.ContractCatalog.load(repositoryRoot, ...
                "phase_pack");
            catalog = catalog(lower(catalog.Profile) == "base" & ...
                ismember(lower(catalog.Domain), components), :);

            stageRoot = fullfile(runFolder, ...
                ".cq_" + localShortUUID());
            mkdir(stageRoot);
            stageCleanup = onCleanup(@() ...
                localDeleteOwnedDirectory(stageRoot, runFolder)); %#ok<NASGU>
            rows = repmat(localEmptyManifestRow(), 0, 1);
            domainRows = repmat(localEmptyDomainRow(), numel(components), 1);
            for componentIndex = 1:numel(components)
                domain = components(componentIndex);
                spec = registry(registry.Domain == domain, :);
                sourceStage = fullfile(stageRoot, domain, "o");
                publishStage = fullfile(stageRoot, domain, "p");
                mkdir(fileparts(sourceStage));
                started = tic;
                try
                    summary = localInvokeRunner(spec.RunnerID, repositoryRoot, ...
                        sourceStage, options);
                    runnerPassed = localRunnerPassed(summary);
                    if ~runnerPassed
                        error("sixgr:artifact:QualificationRunnerFailed", ...
                            "%s returned Passed=false.", spec.RunnerID);
                    end
                    selected = catalog(lower(catalog.Domain) == domain, :);
                    [componentRows, contractOk] = localStageContract( ...
                        sourceStage, publishStage, selected, domain);
                    if ~contractOk
                        failed = componentRows(componentRows.Status ~= "PASS", :);
                        error("sixgr:artifact:QualificationContractFailed", ...
                            "%s failed %d/%d base artifact requirements; first=%s (%s).", ...
                            domain, height(failed), height(componentRows), ...
                            failed.FileName(1), failed.Message(1));
                    end
                    publishedComponents = unique(componentRows.Component, "stable");
                    for publishedIndex = 1:numel(publishedComponents)
                        component = publishedComponents(publishedIndex);
                        target = fullfile(runFolder, "components", component, ...
                            "qualification");
                        localAtomicReplaceDirectory(fullfile(publishStage, component), ...
                            target, runFolder, options.ReplaceExisting);
                    end
                    componentRows.PublishedRelativePath = ...
                        "components/" + componentRows.Component + ...
                        "/qualification/" + componentRows.PublishedRelativePath;
                    % A later successful replacement supersedes failed
                    % attempts for this domain.  Keeping those quarantined
                    % CSV/PNG files beneath the run root makes a recursive
                    % filesystem count look like accepted evidence, even
                    % though they are deliberately absent from the manifest.
                    % Remove only this domain's transaction-owned failure
                    % directories after the validated publish succeeds.
                    localClearDomainFailures(runFolder, domain);
                    rows = [rows; table2struct(componentRows)]; %#ok<AGROW>
                    domainRows(componentIndex) = localDomainRow(domain, ...
                        height(selected), height(componentRows), ...
                        nnz(componentRows.ArtifactType == "CSV"), ...
                        nnz(componentRows.ArtifactType == "PNG"), ...
                        toc(started), "PASS", "");
                catch cause
                    % Failed runner output is diagnostic, never accepted
                    % component evidence.  Keep it outside the run root so
                    % recursive result counts and the WebGUI cannot mistake
                    % failed CSV/PNG files for published artifacts.
                    failureRoot = localFailureRoot(runFolder);
                    failureTarget = fullfile(failureRoot, ...
                        domain + "_" + localShortUUID());
                    if isfolder(sourceStage)
                        if ~isfolder(fileparts(failureTarget))
                            mkdir(fileparts(failureTarget));
                        end
                        movefile(sourceStage, failureTarget);
                    end
                    % A failed refresh invalidates the previously published
                    % files for the selected domain.  Leaving that directory
                    % in place made recursive filesystem views look current
                    % even after the canonical manifest correctly removed
                    % the domain.  Quarantine the stale publication outside
                    % the run root; never silently fall back to an older
                    % successful component pack.
                    localQuarantinePublishedDomain(runFolder, domain);
                    domainRows(componentIndex) = localDomainRow(domain, ...
                        height(catalog(lower(catalog.Domain) == domain, :)), ...
                        0, 0, 0, toc(started), "FAIL", ...
                        string(cause.identifier) + " | " + string(cause.message));
                end
            end

            manifest = localRowsTable(rows);
            summaryTable = struct2table(domainRows, "AsArray", true);
            % Component waves are deliberately resumable.  Preserve earlier
            % validated domains and replace only the domains selected for this
            % invocation.  The manifest remains a list of successfully
            % published immutable files; failed refresh attempts are recorded
            % in the summary/failure quarantine without erasing the last
            % accepted evidence for unrelated components.
            manifest = localMergePriorTable(manifestPath, manifest, ...
                components, ["Domain","ArtifactType","FileName"]);
            summaryTable = localMergePriorTable(summaryPath, summaryTable, ...
                components, "Domain");
            acceptedDomains = summaryTable.Domain( ...
                upper(strtrim(string(summaryTable.Status))) == "PASS");
            for acceptedIndex = 1:numel(acceptedDomains)
                localClearDomainFailures(runFolder, acceptedDomains(acceptedIndex));
            end
            if ~isfolder(auditDir)
                mkdir(auditDir);
            end
            localAtomicWriteTable(manifestPath, manifest);
            localAtomicWriteTable(summaryPath, summaryTable);
            result = struct( ...
                "Passed", all(summaryTable.Status == "PASS"), ...
                "DomainCount", height(summaryTable), ...
                "PassedDomainCount", nnz(summaryTable.Status == "PASS"), ...
                "CSVCount", nnz(manifest.ArtifactType == "CSV"), ...
                "PNGCount", nnz(manifest.ArtifactType == "PNG"), ...
                "ManifestPath", string(manifestPath), ...
                "SummaryPath", string(summaryPath), ...
                "Manifest", manifest, "Summary", summaryTable);
        end
    end
end

function registry = localRunnerRegistry(root)
domain = ["frame_grid";"initial_access";"pdcch";"pdsch"; ...
    "pucch";"pusch";"rsla";"mimo";"channel";"rf";"mac"; ...
    "protocol";"waveform";"validation";"integration"];
runnerID = ["frame_grid";"initial_access";"pdcch";"pdsch"; ...
    "pucch";"pusch";"rsla";"mimo";"channel";"rf";"mac"; ...
    "protocol";"waveform";"validation";"integration"];
vectorRoot = strings(numel(domain), 1);
for index = 1:numel(domain)
    vectorRoot(index) = string(fullfile(root, "tests", "vectors", domain(index)));
end
registry = table(domain, runnerID, vectorRoot, ...
    'VariableNames', {'Domain','RunnerID','VectorRoot'});
end

function components = localSelectComponents(requested, registry)
requested = lower(strtrim(string(requested(:))));
requested(requested == "") = [];
if isempty(requested) || any(requested == "all")
    components = registry.Domain;
else
    unknown = setdiff(requested, registry.Domain, "stable");
    if ~isempty(unknown)
        error("sixgr:artifact:UnknownQualificationComponent", ...
            "Unknown component qualification domain(s): %s.", ...
            strjoin(unknown, ", "));
    end
    components = unique(requested, "stable");
end
end

function summary = localInvokeRunner(id, root, outputDir, options)
vectorRoot = fullfile(root, "tests", "vectors", id);
switch id
    case "frame_grid"
        [manifest, testSummary] = runFrameGridPhaseTests(outputDir, ...
            "RunTests", true);
        summary = struct("Passed", logical(manifest.AllStatusPass), ...
            "Manifest", manifest, "TestSummary", testSummary);
    case "initial_access"
        summary = sixgr.phy.ia.runInitialAccessPhaseValidation( ...
            "VectorRoot", vectorRoot, "OutputDir", outputDir, ...
            "SeedList", options.SeedList, ...
            "ConfidenceLevel", options.ConfidenceLevel, "Strict", true);
    case "pdcch"
        summary = sixgr.phy.pdcch.runPDCCHPhaseValidation( ...
            "VectorRoot", vectorRoot, "OutputDir", outputDir, ...
            "SeedList", options.SeedList, ...
            "ConfidenceLevel", options.ConfidenceLevel, ...
            "Strict", true, "FastTestMode", false);
    case "pdsch"
        summary = sixgr.pdsch.runPDSCHPhaseValidation( ...
            "VectorRoot", vectorRoot, "OutputDir", outputDir, ...
            "SeedList", options.SeedList, ...
            "ConfidenceLevel", options.ConfidenceLevel, "Strict", true);
    case "pucch"
        summary = sixgr.phy.pucch.runPUCCHPhaseValidation( ...
            "VectorRoot", vectorRoot, "OutputDir", outputDir, ...
            "SeedList", options.SeedList, ...
            "ConfidenceLevel", options.ConfidenceLevel, ...
            "Strict", true, "FastTestMode", false);
    case "pusch"
        summary = sixgr.phy.ul.pusch.runPUSCHPhaseValidation( ...
            "VectorRoot", vectorRoot, "OutputDir", outputDir, ...
            "SeedList", options.SeedList, ...
            "ConfidenceLevel", options.ConfidenceLevel, "Strict", true);
    case "rsla"
        summary = sixgr.phy.rsla.runRSLAPhaseValidation( ...
            "VectorRoot", vectorRoot, "OutputDir", outputDir, ...
            "SeedList", options.SeedList, ...
            "ConfidenceLevel", options.ConfidenceLevel, "Strict", true);
    case "mimo"
        summary = sixgr.phy.mimo.runMIMOCSIBeamformingPhaseValidation( ...
            "VectorRoot", vectorRoot, "OutputDir", string(outputDir), ...
            "SeedList", options.SeedList, ...
            "ConfidenceLevel", options.ConfidenceLevel, "Strict", true);
    case "channel"
        summary = sixgr.channel.runtime.runChannelGeometryPhaseValidation( ...
            "VectorRoot", vectorRoot, "OutputDir", outputDir, ...
            "SeedList", options.SeedList, ...
            "ConfidenceLevel", options.ConfidenceLevel, "Strict", true);
    case "rf"
        summary = sixgr.rf.runtime.runRFFrontEndPhaseValidation( ...
            "VectorRoot", vectorRoot, "OutputDir", outputDir, ...
            "SeedList", options.SeedList, ...
            "ConfidenceLevel", options.ConfidenceLevel, "Strict", true);
    case "mac"
        summary = sixgr.l2.mac.runMACHARQSchedulingPhaseValidation( ...
            "VectorRoot", vectorRoot, "OutputDir", outputDir, ...
            "SeedList", options.SeedList, ...
            "ConfidenceLevel", options.ConfidenceLevel, "Strict", true);
    case "protocol"
        summary = sixgr.protocol.runProtocolStackPhaseValidation( ...
            "VectorRoot", string(vectorRoot), "OutputDir", string(outputDir), ...
            "SeedList", options.SeedList, ...
            "ConfidenceLevel", options.ConfidenceLevel, "Strict", true);
    case "waveform"
        summary = sixgr.phy.waveform.runWaveformPhaseValidation( ...
            "VectorRoot", vectorRoot, "OutputDir", outputDir, ...
            "SeedList", options.SeedList, ...
            "ConfidenceLevel", options.ConfidenceLevel, "Strict", true);
    case "validation"
        summary = sixgr.validation.runValidationPhaseValidation( ...
            "VectorRoot", vectorRoot, "OutputDir", outputDir, ...
            "SeedList", options.SeedList, "Strict", true);
    case "integration"
        summary = sixgr.integration.runTwoModeIntegrationValidation( ...
            "RunMatrix", fullfile(vectorRoot, ...
            "integration_actual_run_matrix.csv"), ...
            "OutputDir", outputDir, "Strict", true);
    otherwise
        error("sixgr:artifact:QualificationRunnerMissing", ...
            "No runner is registered for %s.", id);
end
end

function value = localRunnerPassed(summary)
if ~(isstruct(summary) && isscalar(summary))
    error("sixgr:artifact:QualificationSummaryInvalid", ...
        "The component runner did not return a scalar summary struct.");
end
fields = ["Passed","Pass","Ok","AllStatusPass"];
value = false;
for field = fields
    if isfield(summary, field)
        candidate = summary.(field);
        if islogical(candidate) || isnumeric(candidate)
            value = isscalar(candidate) && logical(candidate);
            return;
        end
    end
end
error("sixgr:artifact:QualificationSummaryMissingVerdict", ...
    "The component runner summary has no scalar pass verdict.");
end

function [manifest, ok] = localStageContract(sourceRoot, publishRoot, catalog, domain)
if ~isfolder(sourceRoot)
    error("sixgr:artifact:QualificationOutputMissing", ...
        "%s produced no output directory.", domain);
end
svg = dir(fullfile(sourceRoot, "**", "*.svg"));
if ~isempty(svg)
    error("sixgr:artifact:QualificationSVGForbidden", ...
        "%s generated %d forbidden SVG artifact(s).", domain, numel(svg));
end
mkdir(publishRoot);
rows = repmat(localEmptyManifestRow(), height(catalog), 1);
for index = 1:height(catalog)
    contract = catalog(index, :);
    row = localEmptyManifestRow();
    row.Domain = domain;
    row.Component = contract.Component;
    row.Profile = "base";
    row.EvidenceScope = "component_validation_campaign";
    row.ArtifactType = contract.ArtifactType;
    row.FileName = contract.FileName;
    row.ContractID = contract.ContractID;
    matches = dir(fullfile(sourceRoot, "**", contract.FileName));
    matches = matches(~[matches.isdir]);
    if numel(matches) ~= 1
        row.Status = "MISSING";
        row.Message = "expected_one_fresh_file_observed_" + string(numel(matches));
        rows(index) = row;
        continue;
    end
    sourcePath = fullfile(matches(1).folder, matches(1).name);
    try
        if contract.ArtifactType == "CSV"
            kind = "csv";
            T = readtable(sourcePath, "Delimiter", ",", ...
                "ReadVariableNames", true, "TextType", "string", ...
                "VariableNamingRule", "preserve");
            localValidateCSV(T, contract);
            row.RowCount = height(T);
            row.SourceCSV = "";
            row.SourceCSV_SHA256 = "";
        else
            kind = "png";
            info = imfinfo(sourcePath);
            if lower(string(info.Format)) ~= "png" || ...
                    info.Width < contract.MinimumWidth || ...
                    info.Height < contract.MinimumHeight
                error("sixgr:artifact:QualificationPNGInvalid", ...
                    "%s is not a contract-sized PNG (%dx%d).", ...
                    contract.FileName, info.Width, info.Height);
            end
            row.Width = info.Width;
            row.Height = info.Height;
            row.SourceCSV = contract.SourceCSV;
            sourceNames = localSplitList(contract.SourceCSV);
            sourceHashes = strings(numel(sourceNames), 1);
            for sourceIndex = 1:numel(sourceNames)
                [~, stem, extension] = fileparts(sourceNames(sourceIndex));
                sourceMatches = dir(fullfile(sourceRoot, "**", ...
                    string(stem) + string(extension)));
                sourceMatches = sourceMatches(~[sourceMatches.isdir]);
                if numel(sourceMatches) ~= 1
                    error("sixgr:artifact:QualificationPNGSourceMissing", ...
                        "%s requires one fresh source %s; observed %d.", ...
                        contract.FileName, sourceNames(sourceIndex), ...
                        numel(sourceMatches));
                end
                sourceHashes(sourceIndex) = localFileSHA256(fullfile( ...
                    sourceMatches(1).folder, sourceMatches(1).name));
            end
            row.SourceCSV_SHA256 = sixgr.util.sha256Hex(strjoin( ...
                sort(sourceNames) + "=" + sourceHashes, newline));
        end
        targetDir = fullfile(publishRoot, contract.Component, kind);
        if ~isfolder(targetDir)
            mkdir(targetDir);
        end
        targetPath = fullfile(targetDir, contract.FileName);
        [copied, message] = copyfile(sourcePath, targetPath, "f");
        if ~copied
            error("sixgr:artifact:QualificationCopyFailed", "%s", message);
        end
        row.SHA256 = localFileSHA256(targetPath);
        fileInfo = dir(targetPath);
        row.ByteSize = fileInfo.bytes;
        row.PublishedRelativePath = kind + "/" + contract.FileName;
        row.Status = "PASS";
    catch cause
        row.Status = "FAIL";
        row.Message = string(cause.identifier) + " | " + string(cause.message);
    end
    rows(index) = row;
end
manifest = struct2table(rows, "AsArray", true);
ok = all(manifest.Status == "PASS");
end

function localValidateCSV(T, contract)
required = localSplitList(contract.RequiredColumns);
missing = setdiff(required, string(T.Properties.VariableNames), "stable");
if ~isempty(missing)
    error("sixgr:artifact:QualificationColumnsMissing", ...
        "%s lacks %s.", contract.FileName, strjoin(missing, ", "));
end
if height(T) < contract.MinimumRows
    error("sixgr:artifact:QualificationRowsMissing", ...
        "%s has %d rows; contract minimum is %d.", ...
        contract.FileName, height(T), contract.MinimumRows);
end
keys = localSplitList(contract.PrimaryKey);
if ~isempty(keys)
    if ~all(ismember(keys, string(T.Properties.VariableNames)))
        error("sixgr:artifact:QualificationPrimaryKeyMissing", ...
            "%s lacks primary-key columns.", contract.FileName);
    end
    keyT = T(:, cellstr(keys));
    if height(unique(keyT, "rows", "stable")) ~= height(T)
        error("sixgr:artifact:QualificationPrimaryKeyDuplicate", ...
            "%s contains duplicate primary-key rows.", contract.FileName);
    end
end
if height(T) > 1 && height(unique(T, "rows", "stable")) ~= height(T)
    error("sixgr:artifact:QualificationDuplicateRows", ...
        "%s contains exact duplicate rows.", contract.FileName);
end
if ismember("Status", string(T.Properties.VariableNames))
    status = upper(strtrim(string(T.Status)));
    if any(ismissing(status) | status ~= "PASS")
        error("sixgr:artifact:QualificationNonPassingRow", ...
            "%s contains a non-PASS Status row.", contract.FileName);
    end
end
end

function localAtomicReplaceDirectory(stage, target, ownerRoot, replaceExisting)
localAssertOwnedPath(stage, ownerRoot);
localAssertOwnedPath(target, ownerRoot);
if isfolder(target) && ~replaceExisting
    error("sixgr:artifact:QualificationTargetExists", ...
        "Qualification target already exists: %s.", target);
end
backup = target + ".bak_" + localShortUUID();
hadExisting = isfolder(target);
if hadExisting
    movefile(target, backup);
end
try
    if ~isfolder(fileparts(target))
        mkdir(fileparts(target));
    end
    [ok, message] = movefile(stage, target);
    if ~ok
        error("sixgr:artifact:QualificationPublishFailed", "%s", message);
    end
catch cause
    if hadExisting && ~isfolder(target) && isfolder(backup)
        movefile(backup, target);
    end
    rethrow(cause);
end
if isfolder(backup)
    localDeleteOwnedDirectory(backup, ownerRoot);
end
end

function folder = localOwnedRunFolder(folder, repositoryRoot)
folder = string(char(java.io.File(char(folder)).getCanonicalPath()));
resultsRoot = string(char(java.io.File(fullfile(repositoryRoot, ...
    "results")).getCanonicalPath()));
if folder == resultsRoot || ~startsWith(lower(folder), ...
        lower(resultsRoot + string(filesep)))
    error("sixgr:artifact:QualificationRunFolderUnsafe", ...
        "Qualification output must be one run beneath %s: %s.", ...
        resultsRoot, folder);
end
end

function localAssertOwnedPath(pathValue, ownerRoot)
pathValue = string(char(java.io.File(char(pathValue)).getCanonicalPath()));
ownerRoot = string(char(java.io.File(char(ownerRoot)).getCanonicalPath()));
if pathValue == ownerRoot || ~startsWith(lower(pathValue), ...
        lower(ownerRoot + string(filesep)))
    error("sixgr:artifact:QualificationPathEscape", ...
        "Path escapes run folder %s: %s.", ownerRoot, pathValue);
end
end

function localDeleteOwnedDirectory(pathValue, ownerRoot)
if isfolder(pathValue)
    localAssertOwnedPath(pathValue, ownerRoot);
    rmdir(pathValue, "s");
end
end

function localClearDomainFailures(runFolder, domain)
failureRoot = localFailureRoot(runFolder);
if ~isfolder(failureRoot)
    return;
end
entries = dir(fullfile(failureRoot, char(domain + "_*")));
entries = entries([entries.isdir]);
for index = 1:numel(entries)
    localDeleteOwnedDirectory(fullfile(entries(index).folder, ...
        entries(index).name), fileparts(runFolder));
end
remaining = dir(failureRoot);
remainingNames = string({remaining.name});
remaining = remaining(remainingNames ~= "." & remainingNames ~= "..");
if isempty(remaining)
    localDeleteOwnedDirectory(failureRoot, fileparts(runFolder));
end
end

function failureRoot = localFailureRoot(runFolder)
[campaignRoot, runName] = fileparts(char(runFolder));
failureRoot = fullfile(campaignRoot, ...
    ".component_qualification_failures", runName);
end

function localQuarantinePublishedDomain(runFolder, domain)
published = fullfile(runFolder, "components", domain, "qualification");
if ~isfolder(published)
    return;
end
failureRoot = localFailureRoot(runFolder);
destination = fullfile(failureRoot, ...
    domain + "_stale_" + localShortUUID(), "last_published");
localAssertOwnedPath(published, runFolder);
localAssertOwnedPath(destination, fileparts(runFolder));
if ~isfolder(fileparts(destination))
    mkdir(fileparts(destination));
end
[ok, message] = movefile(published, destination);
if ~ok
    error("sixgr:artifact:QualificationStaleQuarantineFailed", ...
        "Cannot quarantine stale %s publication: %s", domain, message);
end
componentRoot = fileparts(published);
if isfolder(componentRoot)
    remaining = dir(componentRoot);
    names = string({remaining.name});
    remaining = remaining(names ~= "." & names ~= "..");
    if isempty(remaining)
        localDeleteOwnedDirectory(componentRoot, runFolder);
    end
end
end

function localAtomicWriteTable(pathValue, T)
sixgr.util.ensureDir(pathValue);
temporary = string(pathValue) + ".tmp_" + localShortUUID() + ".csv";
cleanup = onCleanup(@() localDeleteFile(temporary)); %#ok<NASGU>
writetable(T, temporary, "Delimiter", ",", "QuoteStrings", true);
[ok, message] = movefile(temporary, pathValue, "f");
if ~ok
    error("sixgr:artifact:QualificationManifestWriteFailed", "%s", message);
end
end

function merged = localMergePriorTable(pathValue, current, replacedDomains, sortKeys)
merged = current;
if ~isfile(pathValue)
    if ~isempty(sortKeys) && height(merged) > 0
        merged = sortrows(merged, sortKeys);
    end
    return;
end
prior = readtable(pathValue, "Delimiter", ",", ...
    "ReadVariableNames", true, "TextType", "string", ...
    "VariableNamingRule", "preserve");
if ~ismember("Domain", string(prior.Properties.VariableNames)) || ...
        ~isequal(string(prior.Properties.VariableNames), ...
            string(current.Properties.VariableNames))
    error("sixgr:artifact:QualificationPriorManifestSchemaMismatch", ...
        "Cannot resume qualification because %s has an incompatible schema.", ...
        pathValue);
end
keep = ~ismember(lower(strtrim(string(prior.Domain))), ...
    lower(strtrim(string(replacedDomains(:)))));
prior = prior(keep, :);
if isempty(prior)
    merged = current;
elseif isempty(current)
    merged = prior;
else
    try
        merged = [prior; current];
    catch cause
        error("sixgr:artifact:QualificationPriorManifestTypeMismatch", ...
            "Cannot resume qualification from %s: %s", pathValue, cause.message);
    end
end
if ~isempty(sortKeys) && height(merged) > 0
    merged = sortrows(merged, sortKeys);
end
end

function values = localSplitList(value)
value = strtrim(string(value));
if strlength(value) == 0
    values = strings(0, 1);
else
    values = strtrim(string(regexp(char(value), '[|;,]', 'split')).');
    values = values(values ~= "");
end
end

function hash = localFileSHA256(pathValue)
fid = fopen(pathValue, "rb");
if fid < 0
    error("sixgr:artifact:QualificationHashReadFailed", ...
        "Cannot read %s.", pathValue);
end
cleanup = onCleanup(@() fclose(fid)); %#ok<NASGU>
hash = string(sixgr.util.sha256Hex(fread(fid, Inf, "*uint8")));
end

function rows = localRowsTable(structRows)
if isempty(structRows)
    rows = struct2table(repmat(localEmptyManifestRow(), 0, 1));
else
    rows = struct2table(structRows, "AsArray", true);
    rows = sortrows(rows, ["Domain","ArtifactType","FileName"]);
end
end

function row = localEmptyManifestRow()
row = struct("Domain","", "Component","", "Profile","", "EvidenceScope","", ...
    "ContractID","", "ArtifactType","", "FileName","", ...
    "SourceCSV","", "SourceCSV_SHA256","", ...
    "PublishedRelativePath","", "SHA256","", "ByteSize",0, ...
    "RowCount",0, "Width",0, "Height",0, ...
    "Status","NOT_EVALUATED", "Message","");
end

function row = localEmptyDomainRow()
row = struct("Domain","", "ContractCount",0, "PublishedCount",0, ...
    "CSVCount",0, "PNGCount",0, "DurationSeconds",0, ...
    "Status","NOT_EVALUATED", "Message","");
end

function row = localDomainRow(domain, contractCount, publishedCount, ...
        csvCount, pngCount, duration, status, message)
row = struct("Domain",string(domain), ...
    "ContractCount",double(contractCount), ...
    "PublishedCount",double(publishedCount), ...
    "CSVCount",double(csvCount), "PNGCount",double(pngCount), ...
    "DurationSeconds",double(duration), "Status",string(status), ...
    "Message",string(message));
end

function value = localUUID()
value = lower(string(char(java.util.UUID.randomUUID())));
end

function value = localShortUUID()
value = extractBefore(localUUID(), 9);
end

function localDeleteFile(pathValue)
if isfile(pathValue)
    delete(pathValue);
end
end
