function mismatch = computeMismatchConfidence(rhoHat, rhoPredicted, sigmaRho, stateVersion, ids)
%COMPUTEMISMATCHCONFIDENCE Calculate signed and normalized mismatch.

if ~(isscalar(sigmaRho) && isfinite(sigmaRho) && sigmaRho > 0)
    error("sixgr:ntn:resilientsync:InvalidMismatchSigma", ...
        "Mismatch sigma must be finite and positive.");
end
signed = double(rhoHat) - double(rhoPredicted);
normalized = signed ./ double(sigmaRho);
confidence = erf(abs(normalized) ./ sqrt(2));
mismatch = struct("Signed", signed, "Absolute", abs(signed), ...
    "Normalized", normalized, "Confidence", confidence, ...
    "StateVersion", double(stateVersion), ...
    "BeamId", string(sixgr.util.structGet(ids,"BeamId","")), ...
    "SatelliteId", string(sixgr.util.structGet(ids,"SatelliteId","")), ...
    "ReferenceId", string(sixgr.util.structGet(ids,"ReferenceId","")));
end
