function strictCfg = buildPRACHConfigFromScenario(baseCfg, varargin)
%BUILDPRACHCONFIGFROMSCENARIO Build a strict, scenario-bound PRACH config.
%
% Strict PRACH validation deliberately fails when required RACH parameters
% are not present in the resolved scenario/internal config. This prevents a
% conformance run from passing due to hidden PRACH defaults.

p = inputParser;
p.FunctionName = "sixgr.phy.prach.buildPRACHConfigFromScenario";
addRequired(p, "baseCfg", @(x) isstruct(x) || isobject(x));
addParameter(p, "RunFolder", "", @(x) ischar(x) || isstring(x));
addParameter(p, "ScenarioName", "", @(x) ischar(x) || isstring(x));
parse(p, baseCfg, varargin{:});
opt = p.Results;

cfg = localStruct(baseCfg);
missing = strings(0, 1);
required = { ...
    "random_access.enabled", ...
    "random_access.configuration_index", ...
    "random_access.prach_format", ...
    "random_access.subcarrier_spacing_khz", ...
    "random_access.root_sequence_index", ...
    "random_access.zero_correlation_zone", ...
    "random_access.restricted_set", ...
    "random_access.preamble_count", ...
    "random_access.preamble_index", ...
    "random_access.frequency_start", ...
    "random_access.n_cell_id", ...
    "random_access.snr_sweep_db", ...
    "random_access.timing_offset_sweep_samples", ...
    "random_access.frequency_offset_sweep_hz"};
for ii = 1:numel(required)
    if localIsMissing(sixgr.util.structGet(cfg, required{ii}, []))
        missing(end + 1, 1) = required{ii}; %#ok<AGROW>
    end
end
if ~isempty(missing)
    error("sixgr:phy:prach:MissingStrictConfigField", ...
        "Strict PRACH validation requires explicit resolved scenario field(s): %s.", ...
        strjoin(missing, ", "));
end
if ~logical(sixgr.util.structGet(cfg, "random_access.enabled", false))
    error("sixgr:phy:prach:PRACHDisabledStrictFailure", ...
        "Strict PRACH validation cannot pass when random_access.enabled=false.");
end

runFolder = char(string(opt.RunFolder));
if strlength(string(runFolder)) == 0
    runFolder = char(string(sixgr.util.structGet(cfg, "prach_lls.OutputDir", pwd)));
end
scenarioName = string(opt.ScenarioName);
if strlength(strtrim(scenarioName)) == 0
    scenarioName = string(sixgr.util.structGet(cfg, "meta.scenarioID", ...
        sixgr.util.structGet(cfg, "scenario.id", "prach_strict_validation")));
end

prachCfg = sixgr.rach.PRACHConfig(cfg, "OutputDir", runFolder);
prachCfg.ScenarioName = char(scenarioName);
prachCfg.BindingSource = string(sixgr.util.structGet(cfg, "random_access.binding_source", "scenario_config"));
prachCfg.NumPreambles = round(double(sixgr.util.structGet(cfg, "random_access.preamble_count", 64)));
prachCfg.NCellID = round(double(sixgr.util.structGet(cfg, "random_access.n_cell_id", prachCfg.NCellID)));
prachCfg.SNRSweep_dB = double(sixgr.util.structGet(cfg, "random_access.snr_sweep_db", prachCfg.SNRSweep_dB));
prachCfg.TimingOffsetSweepSamples = double(sixgr.util.structGet(cfg, "random_access.timing_offset_sweep_samples", [0 4 8]));
prachCfg.FrequencyOffsetSweepHz = double(sixgr.util.structGet(cfg, "random_access.frequency_offset_sweep_hz", [0 250]));
prachCfg.StatisticalQualification = localStatisticalQualification(cfg);
prachCfg.UseParallel = logical(sixgr.util.structGet(cfg, "run.useParallel", false));
prachCfg.ParallelRequestedWorkers = max(1, round(double(sixgr.util.structGet( ...
    cfg, "run.parallelRequestedWorkers", sixgr.util.structGet(cfg, "run.numWorkers", 1)))));
prachCfg.ParallelPoolKind = string(sixgr.util.structGet(cfg, "run.parallelPoolKind", "auto"));
prachCfg.ParallelExecutionAuthority = "resolved_scenario_run_control";
prachCfg.ConfigHash = sixgr.phy.prach.hashPRACHConfig(prachCfg);
% Runtime output location is execution context, not physical configuration.
% Add it only after hashing so identical PRACH configurations retain the
% same digest when executed under different run roots.
prachCfg.RunFolder = string(runFolder);
prachCfg.StrictUnsupportedReason = "";
prachCfg.StrictConfigSource = "resolved_scenario_random_access";
prachCfg.StrictValidation = sixgr.phy.prach.validatePRACHConfigStrict(prachCfg);
strictCfg = prachCfg;
end

function design = localStatisticalQualification(cfg)
raw = sixgr.util.structGet(cfg, "random_access.statistical_qualification", []);
if ~(isstruct(raw) && isscalar(raw))
    error("sixgr:phy:prach:MissingStatisticalQualificationConfig", ...
        "Strict PRACH validation requires random_access.statistical_qualification.");
end
design = struct( ...
    "Enabled", logical(localRequired(raw, "enabled")), ...
    "TargetProbability", double(localRequired(raw, "target_false_alarm_probability")), ...
    "ConfidenceLevel", double(localRequired(raw, "confidence_level")), ...
    "MinimumTrials", double(localRequired(raw, "minimum_trials")), ...
    "MaximumTrials", double(localRequired(raw, "maximum_trials")), ...
    "BatchSizeTrials", double(localRequired(raw, "batch_size_trials")), ...
    "MinimumFalseAlarmEvents", double(localRequired(raw, "minimum_false_alarm_events")), ...
    "CIWidthTarget", double(localRequired(raw, "ci_width_target")), ...
    "PlannedLooks", double(localRequired(raw, "planned_looks")), ...
    "DetectionTargetProbability", double(localRequired(raw, "target_missed_detection_probability")), ...
    "DetectionRequiredSNRdB", double(localRequired(raw, "required_detection_snr_db")), ...
    "DetectionMinimumTrials", double(localRequired(raw, "minimum_detection_trials")), ...
    "DetectionMaximumTrials", double(localRequired(raw, "maximum_detection_trials")), ...
    "DetectionBatchSizeTrials", double(localRequired(raw, "batch_size_detection_trials")), ...
    "MinimumMissedDetectionEvents", double(localRequired(raw, "minimum_missed_detection_events")), ...
    "DetectionCIWidthTarget", double(localRequired(raw, "detection_ci_width_target")), ...
    "DetectionPlannedLooks", double(localRequired(raw, "detection_planned_looks")), ...
    "DeterministicSeeds", double(localRequired(raw, "deterministic_seeds")));
localValidateStatisticalQualification(design);
end

function value = localRequired(source, name)
if ~isfield(source,name) || isempty(source.(name))
    error("sixgr:phy:prach:MissingStatisticalQualificationField", ...
        "Strict PRACH statistical qualification requires '%s'.", name);
end
value = source.(name);
end

function localValidateStatisticalQualification(design)
if ~design.Enabled
    error("sixgr:phy:prach:StatisticalQualificationDisabled", ...
        "Strict PRACH validation requires statistical_qualification.enabled=true.");
end
integerValues = [design.MinimumTrials design.MaximumTrials design.BatchSizeTrials ...
    design.MinimumFalseAlarmEvents design.PlannedLooks design.DetectionMinimumTrials ...
    design.DetectionMaximumTrials design.DetectionBatchSizeTrials ...
    design.MinimumMissedDetectionEvents design.DetectionPlannedLooks ...
    design.DeterministicSeeds(:).'];
if any(~isfinite(integerValues) | integerValues ~= fix(integerValues)) || ...
        design.MinimumTrials < 1 || design.MaximumTrials < design.MinimumTrials || ...
        design.BatchSizeTrials < 1 || design.MinimumFalseAlarmEvents < 0 || ...
        design.PlannedLooks < 1 || design.DetectionMinimumTrials < 1 || ...
        design.DetectionMaximumTrials < design.DetectionMinimumTrials || ...
        design.DetectionBatchSizeTrials < 1 || design.MinimumMissedDetectionEvents < 0 || ...
        design.DetectionPlannedLooks < 1 || isempty(design.DetectionRequiredSNRdB) || ...
        any(~isfinite(design.DetectionRequiredSNRdB)) || numel(design.DeterministicSeeds) < 2
    error("sixgr:phy:prach:InvalidStatisticalQualification", ...
        "PRACH statistical qualification requires valid integer budgets and at least two deterministic seeds.");
end
if ~(isfinite(design.TargetProbability) && design.TargetProbability > 0 && design.TargetProbability < 1 && ...
        isfinite(design.ConfidenceLevel) && design.ConfidenceLevel > 0 && design.ConfidenceLevel < 1 && ...
        isfinite(design.CIWidthTarget) && design.CIWidthTarget > 0 && ...
        isfinite(design.DetectionTargetProbability) && design.DetectionTargetProbability > 0 && ...
        design.DetectionTargetProbability < 1 && isfinite(design.DetectionCIWidthTarget) && ...
        design.DetectionCIWidthTarget > 0)
    error("sixgr:phy:prach:InvalidStatisticalQualification", ...
        "PRACH target probability, confidence level and CI width must be explicit valid probabilities/widths.");
end
requiredLooks = ceil(design.MaximumTrials/design.BatchSizeTrials);
if design.PlannedLooks < requiredLooks
    error("sixgr:phy:prach:InvalidStatisticalQualification", ...
        "PRACH planned_looks must cover every configured batch look (%d required).", requiredLooks);
end
detectionRequiredLooks = ceil(design.DetectionMaximumTrials/design.DetectionBatchSizeTrials);
if design.DetectionPlannedLooks < detectionRequiredLooks
    error("sixgr:phy:prach:InvalidStatisticalQualification", ...
        "PRACH detection_planned_looks must cover every configured batch look (%d required).", ...
        detectionRequiredLooks);
end
end

function cfg = localStruct(baseCfg)
if isstruct(baseCfg)
    cfg = baseCfg;
elseif isobject(baseCfg)
    cfg = struct(baseCfg);
else
    error("sixgr:phy:prach:BadConfigInput", "Unsupported PRACH config input.");
end
end

function tf = localIsMissing(value)
tf = isempty(value);
if tf
    return;
end
if isstring(value) || ischar(value)
    tf = strlength(strtrim(string(value))) == 0;
end
end
