function phyGrant = freezePHYGrant(cfg, direction, grant, varargin)
%FREEZEPHYGRANT Build the immutable PHY grant contract used by TX/RX/HARQ.
% Keep this file ASCII-only.

ip = inputParser;
ip.addParameter("SNR_dB", NaN, @(x) isempty(x) || (isnumeric(x) && isscalar(x)));
ip.addParameter("Frame", NaN, @(x) isempty(x) || (isnumeric(x) && isscalar(x)));
ip.addParameter("Slot", NaN, @(x) isempty(x) || (isnumeric(x) && isscalar(x)));
ip.addParameter("HARQContext", struct(), @(x) isempty(x) || isstruct(x));
ip.parse(varargin{:});
opt = ip.Results;

if nargin < 1 || ~isstruct(cfg)
    cfg = struct();
end
if nargin < 2 || strlength(string(direction)) == 0
    direction = sixgr.util.structGet(grant, "Direction", "DL");
end
if nargin < 3 || ~isstruct(grant)
    grant = struct();
end
direction = upper(string(direction));
if ~(direction == "DL" || direction == "UL")
    error("sixgr:phy:grant:BadDirection", ...
        "PHYGrant direction must be DL or UL. Got '%s'.", char(direction));
end

% Check before reuse as well as before construction: a frozen coding layout
% does not authorize reuse of the previous attempt's slot/symbol clock.
sixgr.phy.grant.assertGrantTimingIdentity(grant,direction);
existing = sixgr.util.structGet(grant, "PHYGrant", struct());
if localCanReuseFrozenPHYGrant(existing, cfg, direction, grant, opt)
    sixgr.phy.grant.assertPHYGrantDimensions(existing, "reuse_existing_phygrant");
    phyGrant = existing;
    return;
end

isUL = direction == "UL";
root = localChannelRoot(isUL);
runtimeRoot = localRuntimeDirectionRoot(isUL);
spatialContract = sixgr.phy.grant.resolveGrantSpatialContract(grant, ...
    "Direction", direction, ...
    "TBContext", sixgr.util.structGet(grant, "HARQTBContext", struct()), ...
    "RequireTBContextMatch", sixgr.phy.grant.isExplicitHARQRetransmission( ...
        grant, existing, opt.HARQContext));
frame = localFirstFiniteScalar(opt.Frame, sixgr.util.structGet(grant, "Frame", []), NaN);
slot = localFirstFiniteScalar(opt.Slot, sixgr.util.structGet(grant, "Slot", []), frame);
rnti = localFirstFiniteScalar(sixgr.util.structGet(grant, "RNTI", []), ...
    sixgr.util.structGet(cfg, root + ".RNTI", []), NaN);
ueIndex = localFirstFiniteScalar(sixgr.util.structGet(grant, "UEIndex", []), ...
    sixgr.util.structGet(grant, "UEID", []), ...
    sixgr.util.structGet(cfg, "lls6g.userContext.UEIndex", []), NaN);
servingCell = localFirstFiniteScalar(sixgr.util.structGet(grant, "ServingCell", []), ...
    sixgr.util.structGet(grant, "BaseStationID", []), ...
    sixgr.util.structGet(cfg, "lls6g.userContext.RuntimeServingCell", []), ...
    sixgr.util.structGet(cfg, "scenario.bs.cell_id", []), NaN);

numLayers = double(spatialContract.NumLayers);
numCodewords = localPositiveInteger(localFirstFiniteScalar( ...
    sixgr.util.structGet(grant, "NumCodewords", []), ...
    sixgr.util.structGet(grant, "CodewordCount", []), ...
    1 + double(numLayers > 4)), 1);
[dmrsPortSet, dmrsPortSetSource] = ...
    sixgr.phy.grant.resolveScheduledDMRSPortSet( ...
    cfg, direction, numLayers, grant);
[ptrsEnabled, ptrsPortSet, ptrsPortSetSource] = ...
    sixgr.phy.grant.resolveScheduledPTRSPortSet( ...
    cfg, direction, dmrsPortSet, grant);

prbSet = localResolvePRBSet(cfg, grant, root);
symbolAllocation = localResolveSymbolAllocation(cfg, grant, root);
[frequencyHoppingMode, frequencyHoppingToolboxMode, secondHopStartPRB] = ...
    localResolvePUSCHFrequencyHopping(cfg, grant, isUL);
modulation = char(string(localFirstNonempty( ...
    sixgr.util.structGet(grant, "Modulation", ""), ...
    sixgr.util.structGet(cfg, runtimeRoot + ".Modulation", ""), ...
    sixgr.util.structGet(cfg, root + ".modulation", "QPSK"))));
targetCodeRate = localFirstFiniteScalar( ...
    sixgr.util.structGet(grant, "TargetCodeRate", []), ...
    sixgr.util.structGet(cfg, runtimeRoot + ".TargetCodeRate", []), ...
    sixgr.util.structGet(cfg, root + ".codeRate", []), NaN);
xOverhead = localFirstFiniteScalar( ...
    sixgr.util.structGet(grant, "XOverhead", []), ...
    sixgr.util.structGet(cfg, root + ".xOverhead", []), 0);
nrePerPRB = localFirstFiniteScalar(sixgr.util.structGet(grant, "NREPerPRB", []), NaN);
tbsBits = localFirstFiniteScalar( ...
    sixgr.util.structGet(grant, "TBSBits", []), ...
    sixgr.util.structGet(grant, "TransportBlockSize", []), ...
    sixgr.util.structGet(grant, "TBSize_bits", []), NaN);
tbsBytes = localFirstFiniteScalar(sixgr.util.structGet(grant, "TBSBytes", []), floor(max(tbsBits, 0) / 8));

[ant, prec] = localResolveAntennaAndPrecoding(cfg, grant, direction, numLayers, numCodewords);

resourceAllocation = struct( ...
    "PRBSet", double(prbSet(:).'), ...
    "PRBStart", localFirstFiniteScalar(min(double(prbSet(:))), sixgr.util.structGet(grant, "PRBStart", []), NaN), ...
    "PRBCount", double(numel(prbSet)), ...
    "SymbolAllocation", double(symbolAllocation(:).'), ...
    "SymbolStart", double(symbolAllocation(1)), ...
    "NumSymbols", double(symbolAllocation(2)), ...
    "FrequencyHoppingMode", char(frequencyHoppingMode), ...
    "FrequencyHoppingToolboxMode", char(frequencyHoppingToolboxMode), ...
    "FrequencyHoppingEnabled", logical(frequencyHoppingMode ~= "none"), ...
    "SecondHopStartPRB", double(secondHopStartPRB));

codingLayout = struct( ...
    "Modulation", char(modulation), ...
    "MCSIndex", localFirstFiniteScalar(sixgr.util.structGet(grant, "MCSIndex", []), ...
        sixgr.util.structGet(grant, "MCS", []), ...
        sixgr.util.structGet(cfg, runtimeRoot + ".MCSIndex", []), ...
        sixgr.util.structGet(cfg, root + ".mcsIndex", []), NaN), ...
    "MCSTable", char(string(localFirstNonempty(sixgr.util.structGet(grant, "MCSTable", ""), ...
        sixgr.util.structGet(cfg, runtimeRoot + ".MCSTable", ""), ...
        sixgr.util.structGet(cfg, root + ".mcsTable", "")))), ...
    "CQITable", char(string(localFirstNonempty(sixgr.util.structGet(grant, "CQITable", ""), ...
        sixgr.util.structGet(cfg, "link_adaptation.cqiTable", "")))), ...
    "TargetCodeRate", double(targetCodeRate), ...
    "XOverhead", double(xOverhead), ...
    "NREPerPRB", double(nrePerPRB), ...
    "TBSInputModulation", char(modulation), ...
    "TBSInputNumLayers", double(numLayers), ...
    "TBSInputNPRB", double(numel(prbSet)), ...
    "TBSInputNREPerPRB", double(nrePerPRB), ...
    "TBSInputTargetCodeRate", double(targetCodeRate), ...
    "TBSInputXOverhead", double(xOverhead), ...
    "TBSInputSource", char(string(sixgr.util.structGet(grant, ...
        "TBSInputSource", sixgr.util.structGet(grant, ...
        "ResourceAccountingSource", "transmitter_grant_resource_accounting")))), ...
    "TBSBits", double(tbsBits), ...
    "TBSBytes", double(tbsBytes), ...
    "NumLayers", double(numLayers), ...
    "NumCodewords", double(numCodewords), ...
    "DMRSPortSet", double(dmrsPortSet(:).'), ...
    "DMRSPortSetSource", char(string(dmrsPortSetSource)), ...
    "PTRSEnabled", logical(ptrsEnabled), ...
    "PTRSPortSet", double(ptrsPortSet(:).'), ...
    "PTRSPortSetSource", char(string(ptrsPortSetSource)));

noiseContext = struct( ...
    "SNR_dB", double(localFirstFiniteScalar(opt.SNR_dB, ...
        sixgr.util.structGet(cfg, "channel.snr_dB", []), NaN)), ...
    "NoiseVariance", localFirstFiniteScalar(sixgr.util.structGet(grant, "NoiseVariance", []), NaN), ...
    "NoiseSource", char(string(sixgr.util.structGet(grant, "NoiseSource", ""))));

channelStateKey = struct( ...
    "Direction", char(direction), ...
    "Frame", double(frame), ...
    "Slot", double(slot), ...
    "RNTI", double(rnti), ...
    "UEIndex", double(ueIndex), ...
    "ServingCell", double(servingCell), ...
    "ChannelModel", char(string(sixgr.util.structGet(cfg, "channel.model", "AWGN"))), ...
    "FadingProfile", char(localResolveFadingProfile(cfg)));

harqContext = opt.HARQContext;
harqFromGrant = sixgr.util.structGet(grant, "HARQ", struct());
harqProcessKey = struct( ...
    "Direction", char(direction), ...
    "RNTI", double(rnti), ...
    "HARQProcess", localFirstFiniteScalar( ...
        sixgr.util.structGet(harqContext, "HARQProcess", []), ...
        sixgr.util.structGet(harqContext, "HarqID", []), ...
        sixgr.util.structGet(harqFromGrant, "HARQProcess", []), ...
        sixgr.util.structGet(harqFromGrant, "HarqID", []), NaN), ...
    "RV", localFirstFiniteScalar( ...
        sixgr.util.structGet(harqContext, "RV", []), ...
        sixgr.util.structGet(harqFromGrant, "RV", []), ...
        sixgr.util.structGet(grant, "RV", []), NaN), ...
    "NDI", logical(localFirstFiniteScalar( ...
        sixgr.util.structGet(harqContext, "NDI", []), ...
        sixgr.util.structGet(harqFromGrant, "NDI", []), 1)), ...
    "IsRetransmission", sixgr.phy.grant.isExplicitHARQRetransmission( ...
        grant, existing, harqContext));

grantContextId = char(string(sixgr.util.structGet(grant, "GrantContextId", "")));
if strlength(string(grantContextId)) == 0
    grantContextId = localComposeContextId(direction, servingCell, ueIndex, rnti, frame, slot);
end
runtimeAuthorityDigest = localRuntimeAuthorityDigest(cfg);
configurationAuthority = struct( ...
    "ContractVersion", "sixgr_frozen_configuration_authority/v1", ...
    "RuntimeOperatingAuthoritySHA256", char(runtimeAuthorityDigest), ...
    "SourceConfigSHA256", char(string(sixgr.util.structGet(cfg, "meta.configHash", ""))), ...
    "Source", char(localRuntimeAuthoritySource(cfg)));

phyGrant = struct( ...
    "ContractVersion", "PHYGrant/v1", ...
    "IsFrozen", true, ...
    "Immutable", true, ...
    "MutationPolicy", "copy_only_recompute_forbidden_after_schedule", ...
    "Direction", char(direction), ...
    "GrantContextId", char(grantContextId), ...
    "PHYGrantId", char(grantContextId), ...
    "AntennaArchitecture", ant, ...
    "ResourceAllocation", resourceAllocation, ...
    "CodingLayout", codingLayout, ...
    "PrecodingState", prec, ...
    "NoiseContext", noiseContext, ...
    "ChannelStateKey", channelStateKey, ...
    "HARQProcessKey", harqProcessKey, ...
    "ConfigurationAuthority", configurationAuthority, ...
    "LegacyGrantSnapshot", grant);

phyGrant.DimensionContract = sixgr.phy.grant.assertPHYGrantDimensions( ...
    phyGrant, "freeze_phygrant");
end

function root = localChannelRoot(isUL)
if isUL
    root = "phy.pusch";
else
    root = "phy.pdsch";
end
end

function root = localRuntimeDirectionRoot(isUL)
if isUL
    root = "runtime.phy.ul";
else
    root = "runtime.phy.dl";
end
end

function tf = localIsFrozenPHYGrant(value)
tf = isstruct(value) && ~isempty(fieldnames(value)) && ...
    logical(sixgr.util.structGet(value, "IsFrozen", false)) && ...
    isfield(value, "AntennaArchitecture") && ...
    isfield(value, "ResourceAllocation") && ...
    isfield(value, "CodingLayout") && ...
    isfield(value, "PrecodingState");
end

function tf = localFrozenPHYGrantHasConsistentDimensions(value)
tf = false;
if ~localIsFrozenPHYGrant(value)
    return;
end
ant = sixgr.util.structGet(value, "AntennaArchitecture", struct());
coding = sixgr.util.structGet(value, "CodingLayout", struct());
prec = sixgr.util.structGet(value, "PrecodingState", struct());
numPorts = round(double(sixgr.util.structGet(ant, "NumWaveformColumns", NaN)));
numLogicalPorts = round(double(sixgr.util.structGet(ant, "NumLogicalPorts", NaN)));
numLayers = round(double(sixgr.util.structGet(coding, "NumLayers", ...
    sixgr.util.structGet(ant, "NumLayers", NaN))));
W = sixgr.util.structGet(prec, "MatrixPorts", sixgr.util.structGet(prec, "Matrix", []));
if isempty(W) || ~isnumeric(W)
    return;
end
if ndims(W) > 2 && size(W, 3) == 1
    W = squeeze(W);
end
if ~ismatrix(W)
    return;
end
Wlogical = sixgr.util.structGet(prec, "MatrixLogicalPorts", []);
logicalOK = true;
if logical(sixgr.util.structGet(prec, "HybridElementDomainApplied", false))
    logicalOK = isnumeric(Wlogical) && ismatrix(Wlogical) && ...
        size(Wlogical, 1) == numLogicalPorts && size(Wlogical, 2) == numLayers;
end
tf = isfinite(numPorts) && isfinite(numLogicalPorts) && isfinite(numLayers) && ...
    numLogicalPorts >= numLayers && numPorts >= numLogicalPorts && ...
    size(W, 1) == numPorts && size(W, 2) == numLayers && logicalOK;
end

function tf = localCanReuseFrozenPHYGrant(existing, cfg, direction, grant, opt)
tf = false;
if ~(localIsFrozenPHYGrant(existing) && localFrozenPHYGrantHasConsistentDimensions(existing))
    return;
end
if upper(string(sixgr.util.structGet(existing, "Direction", ""))) ~= upper(string(direction))
    return;
end
% Rebinding a legal new occasion still requires a new attempt snapshot.
% Identical TBS/precoding/resources alone cannot reuse the old clock.
if ~isequaln(sixgr.util.structGet(existing,'LegacyGrantSnapshot.TimingDecision',struct()), ...
        sixgr.util.structGet(grant,'TimingDecision',struct()))
    return;
end
frozenAuthorityDigest = string(sixgr.util.structGet(existing, ...
    "ConfigurationAuthority.RuntimeOperatingAuthoritySHA256", ""));
runtimeAuthorityDigest = localRuntimeAuthorityDigest(cfg);
if strlength(frozenAuthorityDigest) > 0 && strlength(runtimeAuthorityDigest) > 0 && ...
        frozenAuthorityDigest ~= runtimeAuthorityDigest
    error("sixgr:phy:grant:FrozenConfigurationAuthorityMismatch", ...
        ['Frozen %s grant configuration authority %s differs from the current ' ...
        'runtime operating authority %s; grant regeneration during replay is forbidden.'], ...
        char(direction), char(frozenAuthorityDigest), char(runtimeAuthorityDigest));
end

harqContext = sixgr.util.structGet(opt, "HARQContext", struct());
harqFromGrant = sixgr.util.structGet(grant, "HARQ", struct());
requestedIsRetx = sixgr.phy.grant.isExplicitHARQRetransmission( ...
    grant, existing, harqContext);
existingIsRetx = logical(sixgr.util.structGet(existing, "HARQProcessKey.IsRetransmission", false));
if requestedIsRetx ~= existingIsRetx
    return;
end

requestedRV = localFirstFiniteScalar( ...
    sixgr.util.structGet(harqContext, "RV", []), ...
    sixgr.util.structGet(harqFromGrant, "RV", []), ...
    sixgr.util.structGet(grant, "RV", []), NaN);
existingRV = localFirstFiniteScalar(sixgr.util.structGet(existing, "HARQProcessKey.RV", []), NaN);
if ~localScalarMatches(requestedRV, existingRV, 0)
    return;
end

requestedNDI = localFirstFiniteScalar( ...
    sixgr.util.structGet(harqContext, "NDI", []), ...
    sixgr.util.structGet(harqFromGrant, "NDI", []), NaN);
existingNDI = localFirstFiniteScalar(sixgr.util.structGet(existing, "HARQProcessKey.NDI", []), NaN);
if ~localScalarMatches(requestedNDI, existingNDI, 0)
    return;
end

requestedHarqProc = localFirstFiniteScalar( ...
    sixgr.util.structGet(harqContext, "HARQProcess", []), ...
    sixgr.util.structGet(harqContext, "HarqID", []), ...
    sixgr.util.structGet(harqFromGrant, "HARQProcess", []), ...
    sixgr.util.structGet(harqFromGrant, "HarqID", []), NaN);
existingHarqProc = localFirstFiniteScalar(sixgr.util.structGet(existing, "HARQProcessKey.HARQProcess", []), NaN);
if ~localScalarMatches(requestedHarqProc, existingHarqProc, 0)
    return;
end

isUL = direction == "UL";
root = localChannelRoot(isUL);
requestedPRBSet = localResolvePRBSet(cfg, grant, root);
existingPRBSet = double(sixgr.util.structGet(existing, "ResourceAllocation.PRBSet", []));
if ~localNumericVectorMatches(requestedPRBSet, existingPRBSet)
    return;
end

requestedSymbolAllocation = localResolveSymbolAllocation(cfg, grant, root);
existingSymbolAllocation = double(sixgr.util.structGet(existing, "ResourceAllocation.SymbolAllocation", []));
if ~localNumericVectorMatches(requestedSymbolAllocation, existingSymbolAllocation)
    return;
end

[requestedHoppingMode, ~, requestedSecondHop] = ...
    localResolvePUSCHFrequencyHopping(cfg, grant, isUL);
existingHoppingMode = lower(strtrim(string(sixgr.util.structGet(existing, ...
    "ResourceAllocation.FrequencyHoppingMode", "none"))));
if requestedHoppingMode ~= existingHoppingMode
    return;
end
if requestedHoppingMode ~= "none"
    existingSecondHop = double(sixgr.util.structGet(existing, ...
        "ResourceAllocation.SecondHopStartPRB", NaN));
    if ~localScalarMatches(requestedSecondHop, existingSecondHop, 0)
        return;
    end
end

requestedNumLayers = localPositiveInteger(localFirstFiniteScalar( ...
    sixgr.util.structGet(grant, "NumLayers", []), ...
    sixgr.util.structGet(grant, "Layers", []), ...
    sixgr.util.structGet(cfg, root + ".numLayers", []), ...
    sixgr.util.structGet(cfg, root + ".nLayers", []), 1), 1);
existingNumLayers = localFirstFiniteScalar(sixgr.util.structGet(existing, "CodingLayout.NumLayers", []), NaN);
if ~localScalarMatches(requestedNumLayers, existingNumLayers, 0)
    return;
end

requestedModulation = char(string(localFirstNonempty( ...
    sixgr.util.structGet(grant, "Modulation", ""), ...
    sixgr.util.structGet(cfg, root + ".modulation", "QPSK"))));
existingModulation = char(string(sixgr.util.structGet(existing, "CodingLayout.Modulation", "")));
if ~localTextMatches(requestedModulation, existingModulation)
    return;
end

requestedTargetCodeRate = localFirstFiniteScalar( ...
    sixgr.util.structGet(grant, "TargetCodeRate", []), ...
    sixgr.util.structGet(cfg, root + ".codeRate", []), NaN);
existingTargetCodeRate = localFirstFiniteScalar(sixgr.util.structGet(existing, "CodingLayout.TargetCodeRate", []), NaN);
if ~localScalarMatches(requestedTargetCodeRate, existingTargetCodeRate, 1e-12)
    return;
end

requestedTBSBits = localFirstFiniteScalar( ...
    sixgr.util.structGet(grant, "TBSBits", []), ...
    sixgr.util.structGet(grant, "TransportBlockSize", []), ...
    sixgr.util.structGet(grant, "TBSize_bits", []), NaN);
existingTBSBits = localFirstFiniteScalar(sixgr.util.structGet(existing, "CodingLayout.TBSBits", []), NaN);
if ~localScalarMatches(requestedTBSBits, existingTBSBits, 0)
    return;
end

requestedXOverhead = localFirstFiniteScalar( ...
    sixgr.util.structGet(grant, "XOverhead", []), ...
    sixgr.util.structGet(cfg, root + ".xOverhead", []), 0);
existingXOverhead = localFirstFiniteScalar(sixgr.util.structGet(existing, "CodingLayout.XOverhead", []), NaN);
if ~localScalarMatches(requestedXOverhead, existingXOverhead, 1e-12)
    return;
end

requestedNREPerPRB = localFirstFiniteScalar( ...
    sixgr.util.structGet(grant, "TBSInputNREPerPRB", []), ...
    sixgr.util.structGet(grant, "NREPerPRB", []), NaN);
existingNREPerPRB = localFirstFiniteScalar( ...
    sixgr.util.structGet(existing, "CodingLayout.TBSInputNREPerPRB", []), ...
    sixgr.util.structGet(existing, "CodingLayout.NREPerPRB", []), NaN);
if ~localScalarMatches(requestedNREPerPRB, existingNREPerPRB, 0)
    return;
end

tf = true;
end

function digest = localRuntimeAuthorityDigest(cfg)
digest = string(sixgr.util.structGet(cfg, ...
    "runtime.OperatingAuthoritySHA256", ""));
if strlength(strtrim(digest)) == 0
    digest = string(sixgr.util.structGet(cfg, "meta.configHash", ""));
end
digest = strtrim(digest);
end

function source = localRuntimeAuthoritySource(cfg)
if strlength(string(sixgr.util.structGet(cfg, ...
        "runtime.OperatingAuthoritySHA256", ""))) > 0
    source = "runtime_operating_authority";
elseif strlength(string(sixgr.util.structGet(cfg, "meta.configHash", ""))) > 0
    source = "resolved_scenario_config_hash";
else
    source = "unavailable_legacy_config";
end
end

function tf = localScalarMatches(requested, actual, tol)
if nargin < 3
    tol = 0;
end
tf = true;
if ~(isscalar(requested) && isfinite(double(requested)))
    return;
end
tf = isscalar(actual) && isfinite(double(actual)) && abs(double(requested) - double(actual)) <= tol;
end

function tf = localNumericVectorMatches(requested, actual)
requested = double(requested(:).');
actual = double(actual(:).');
requested = requested(isfinite(requested));
actual = actual(isfinite(actual));
if isempty(requested)
    tf = true;
    return;
end
tf = numel(requested) == numel(actual) && all(abs(requested - actual) <= 1e-9);
end

function tf = localTextMatches(requested, actual)
requested = upper(strtrim(string(requested)));
actual = upper(strtrim(string(actual)));
if strlength(requested) < 1
    tf = true;
    return;
end
tf = strlength(actual) >= 1 && requested == actual;
end

function prbSet = localResolvePRBSet(cfg, grant, root)
prbSet = sixgr.util.structGet(grant, "PRBSet", []);
if isempty(prbSet)
    prbStart = localFirstFiniteScalar(sixgr.util.structGet(grant, "PRBStart", []), NaN);
    prbCount = localFirstFiniteScalar( ...
        sixgr.util.structGet(grant, "AllocatedPRBCount", []), ...
        sixgr.util.structGet(grant, "PRBCount", []), ...
        sixgr.util.structGet(grant, "PRBs", []), NaN);
    if isfinite(prbStart) && isfinite(prbCount) && prbCount >= 1
        prbSet = round(prbStart):(round(prbStart) + round(prbCount) - 1);
    end
end
if isempty(prbSet)
    prbSet = sixgr.util.structGet(cfg, root + ".prbSet", []);
end
if isempty(prbSet)
    error("sixgr:phy:grant:MissingPRBSet", ...
        "PHYGrant requires an explicit PRBSet (or PRBStart plus PRBCount) " + ...
        "from the scheduled grant or resolved channel configuration.");
end
prbSet = localExpandPRBSet(prbSet);
if isempty(prbSet)
    error("sixgr:phy:grant:EmptyPRBSet", "PHYGrant requires a non-empty PRBSet.");
end
end

function prbSet = localExpandPRBSet(raw)
if ~(isnumeric(raw) && isreal(raw))
    error("sixgr:phy:grant:InvalidPRBSet", ...
        "PHYGrant PRBSet must be a real numeric vector.");
end
raw = double(raw(:).');
if isempty(raw)
    prbSet = [];
    return;
end
if any(~isfinite(raw)) || any(raw ~= fix(raw)) || any(raw < 0)
    error("sixgr:phy:grant:InvalidPRBSet", ...
        "PHYGrant PRBSet must contain finite nonnegative integers.");
end
if numel(raw) == 2 && raw(2) > raw(1)
    prbSet = round(raw(1)):round(raw(2));
else
    prbSet = unique(round(raw), "stable");
end
end

function symbolAllocation = localResolveSymbolAllocation(cfg, grant, root)
symbolAllocation = sixgr.util.structGet(grant, "SymbolAllocation", []);
if isempty(symbolAllocation)
    symbolAllocation = sixgr.util.structGet(cfg, root + ".symbolAllocation", []);
end
if isempty(symbolAllocation)
    error("sixgr:phy:grant:MissingSymbolAllocation", ...
        "PHYGrant requires an explicit SymbolAllocation from the scheduled " + ...
        "grant or resolved channel configuration.");
end
symbolAllocation = double(symbolAllocation(:).');
if numel(symbolAllocation) < 2 || ~all(isfinite(symbolAllocation(1:2)))
    error("sixgr:phy:grant:BadSymbolAllocation", ...
        "PHYGrant requires SymbolAllocation [start numSymbols].");
end
symbolAllocation = round(symbolAllocation(1:2));
if symbolAllocation(1) < 0 || symbolAllocation(2) < 1
    error("sixgr:phy:grant:BadSymbolAllocation", ...
        "Invalid SymbolAllocation [%d %d].", symbolAllocation(1), symbolAllocation(2));
end
end

function [mode, toolboxMode, secondHop] = localResolvePUSCHFrequencyHopping(cfg, grant, isUL)
mode = "none";
toolboxMode = "neither";
secondHop = NaN;
if ~isUL
    return;
end

raw = string(localFirstNonempty( ...
    sixgr.util.structGet(grant, "FrequencyHoppingMode", ""), ...
    sixgr.util.structGet(grant, "FrequencyHopping", ""), ...
    sixgr.util.structGet(grant, "PUSCHConfig.FrequencyHopping", ""), ...
    sixgr.util.structGet(cfg, "phy.pusch.frequencyHopping.mode", ""), ...
    sixgr.util.structGet(cfg, "phy.pusch.frequencyHopping", "none")));
token = lower(regexprep(strtrim(raw), "[-_ ]", ""));
switch token
    case {"", "none", "neither", "disabled", "off", "false"}
        mode = "none";
        toolboxMode = "neither";
    case {"intraslot", "intra"}
        mode = "intra_slot";
        toolboxMode = "intraSlot";
    case {"interslot", "inter"}
        mode = "inter_slot";
        toolboxMode = "interSlot";
    otherwise
        error("sixgr:phy:grant:InvalidPUSCHFrequencyHoppingMode", ...
            "Frozen UL grant has unsupported PUSCH frequency-hopping mode '%s'.", ...
            char(raw));
end

if mode == "none"
    return;
end
secondHop = localFirstFiniteScalar( ...
    sixgr.util.structGet(grant, "SecondHopStartPRB", []), ...
    sixgr.util.structGet(grant, "PUSCHConfig.SecondHopStartPRB", []), ...
    sixgr.util.structGet(cfg, "phy.pusch.frequencyHopping.secondHopStartPRB", []), ...
    NaN);
if ~(isscalar(secondHop) && isfinite(secondHop) && secondHop == fix(secondHop) && secondHop >= 0)
    error("sixgr:phy:grant:MissingPUSCHSecondHopStartPRB", ...
        "Enabled PUSCH frequency hopping requires a finite nonnegative integer second-hop start PRB.");
end
secondHop = double(secondHop);
end

function [ant, prec] = localResolveAntennaAndPrecoding(cfg, grant, direction, numLayers, numCodewords)
isUL = direction == "UL";
matrixLogicalPorts = [];
elementDomainApplied = false;
waveformDomain = "logical_port";
hybridElementToPortMatrix = [];
dlPMIMeta = struct( ...
    "PMI", localFirstFiniteScalar( ...
        sixgr.util.structGet(grant, "AppliedPrecoderPMI", []), ...
        sixgr.util.structGet(grant, "PMI", []), ...
        sixgr.util.structGet(grant, "TPMI", []), NaN), ...
    "PMIType", string(localFirstNonempty( ...
        sixgr.util.structGet(grant, "AppliedPrecoderPMIType", ""), "")), ...
    "CodebookMode", string(localFirstNonempty( ...
        sixgr.util.structGet(grant, "AppliedPrecoderCodebookMode", ""), ...
        sixgr.util.structGet(grant, "PMICodebookMode", ""), "")), ...
    "BeamIndices", double(sixgr.util.structGet(grant, "BeamIndices", [])), ...
    "CSIRSPortBasisApplied", false, ...
    "CSIResourceIndex", NaN, ...
    "PMICodebookMatrixCSIPorts", [], ...
    "PMICodebookMatrixCSIPortsSHA256", "", ...
    "CSIRSPortToElementMatrix", [], ...
    "CSIRSPortToElementMatrixSHA256", "", ...
    "ComposedElementMatrix", [], ...
    "ComposedElementMatrixSHA256", "");
if isUL
    txEntity = "UE";
    rxEntity = "gNB";
    numElements = localPositiveInteger(localFirstFiniteScalar( ...
        sixgr.util.structGet(grant, "NumElements", []), ...
        sixgr.util.structGet(grant, "TxElements", []), ...
        sixgr.util.structGet(cfg, "antenna.ue.numElements", []), ...
        sixgr.util.structGet(cfg, "scenario.ue.nTxAnt", []), ...
        sixgr.util.structGet(cfg, "mimo.ue_n_tx_ant", []), ...
        sixgr.util.structGet(cfg, "phy.pusch.NumAntennaPorts", []), 1), 1);
    numRx = localPositiveInteger(localFirstFiniteScalar( ...
        sixgr.util.structGet(grant, "NumRxAntennas", []), ...
        sixgr.util.structGet(grant, "RxAntennas", []), ...
        sixgr.util.structGet(cfg, "antenna.bs.numElements", []), ...
        sixgr.util.structGet(cfg, "scenario.bs.nRxAnt", []), ...
        sixgr.util.structGet(cfg, "channel.ul.nRxAnt", []), ...
        sixgr.util.structGet(cfg, "phy.ul.nRxAnt", []), ...
        sixgr.util.structGet(cfg, "scenario.bs.nTxAnt", []), numLayers), numLayers);
    logicalPorts = localPositiveInteger(localFirstFiniteScalar( ...
        sixgr.util.structGet(grant, "NumLogicalPorts", []), ...
        sixgr.util.structGet(grant, "PortCount", []), ...
        sixgr.util.structGet(grant, "PrecodingNumPorts", []), ...
        sixgr.util.structGet(cfg, "phy.pusch.NumAntennaPorts", []), ...
        sixgr.util.structGet(cfg, "phy.pusch.numPorts", []), ...
        sixgr.util.structGet(cfg, "phy.pusch.nPorts", []), ...
        sixgr.util.structGet(grant, "NumTxAnt", []), numElements), numLayers);
    logicalPorts = min(max(logicalPorts, numLayers), max(numElements, numLayers));
    transmissionScheme = lower(strtrim(string(localFirstNonempty( ...
        sixgr.util.structGet(grant, "TransmissionScheme", ""), ...
        sixgr.util.structGet(cfg, "phy.pusch.TransmissionScheme", ""), ...
        sixgr.util.structGet(cfg, "phy.pusch.transmissionScheme", ""), ...
        "nonCodebook"))));
    transformPrecoding = logical(localFirstFiniteScalar( ...
        sixgr.util.structGet(grant, "TransformPrecoding", []), ...
        sixgr.util.structGet(cfg, "phy.pusch.transformPrecoding", []), false));
    nativeCodebookApplied = transmissionScheme == "codebook";
    tpmi = localFirstFiniteScalar( ...
        sixgr.util.structGet(grant, "TPMI", []), ...
        sixgr.util.structGet(grant, "PMI", []), ...
        sixgr.util.structGet(cfg, "phy.pusch.TPMI", []), ...
        sixgr.util.structGet(cfg, "phy.pusch.PMI", []), NaN);
    codebookStatus = "";
    codebookMatrixNR = [];
    codebookRightInverse = [];
    ulLogicalRaw = localFirstMatrix(sixgr.util.structGet(grant, "PrecodingMatrixLogicalPorts", []), ...
        sixgr.util.structGet(grant, "LogicalPrecodingMatrix", []));
    ulRaw = sixgr.util.structGet(grant, "PrecodingMatrix", []);
    if nativeCodebookApplied
        localValidateULSRSCodebookAuthority(cfg, grant, numLayers, logicalPorts, tpmi);
        try
            [selectedLogicalMatrix, codebookStatus, codebookMatrixNR, codebookRightInverse] = ...
                sixgr.phy.ul.puschCodebookProjectionMatrix( ...
                numLayers, logicalPorts, tpmi, transformPrecoding);
        catch ME
            error("sixgr:phy:grant:UnsupportedULCodebook", ...
                "Cannot freeze the scheduled UL TPMI/codebook selection: %s", ME.message);
        end
        if ~isempty(ulLogicalRaw)
            suppliedLogicalMatrix = localNormalizeDLMatrix( ...
                ulLogicalRaw, logicalPorts, numLayers);
            residual = norm(suppliedLogicalMatrix - selectedLogicalMatrix, "fro") ./ ...
                max(norm(selectedLogicalMatrix, "fro"), eps);
            if residual > 1e-12
                error("sixgr:phy:grant:ULCodebookMatrixMismatch", ...
                    "Scheduled UL logical matrix differs from TPMI=%d codebook matrix (relative residual %.3g).", ...
                    round(double(tpmi)), residual);
            end
        end
        matrixLogicalPorts = double(selectedLogicalMatrix);
    else
        if isempty(ulLogicalRaw)
            matrixLogicalPorts = [];
        else
            matrixLogicalPorts = localNormalizeDLMatrix(ulLogicalRaw, logicalPorts, numLayers);
        end
    end
    [matrixPorts, numWaveformColumns, waveformDomain, elementDomainApplied, hybridElementToPortMatrix, matrixLogicalPorts] = ...
        localMaterializeElementDomainPrecoder(cfg, "ue", "PUSCH", numElements, logicalPorts, ...
        numLayers, matrixLogicalPorts, ulRaw, grant);
    if nativeCodebookApplied
        active = true;
        mode = localTernary(transformPrecoding, ...
            "transform_precoding_codebook_tpmi", "ul_codebook_tpmi");
        source = "ul_pusch_native_codebook_tpmi_from_frozen_causal_srs_grant";
        stage = localTernary(transformPrecoding, ...
            "dft_spread_then_nrPUSCH_native_codebook_precoding", ...
            "nrPUSCH_native_codebook_precoding_during_modulation");
    else
        active = logical(sixgr.util.structGet(grant, "PrecodingActive", false));
        mode = localFirstNonempty(sixgr.util.structGet(grant, "PrecodingMode", ""), "ul_direct_mapping");
        source = localFirstNonempty(sixgr.util.structGet(grant, "PrecoderSource", ""), "ul_frozen_logical_ports");
        stage = localFirstNonempty(sixgr.util.structGet(grant, "PrecodingApplicationStage", ""), "nrPUSCH_native_or_direct_mapping");
    end
else
    txEntity = "gNB";
    rxEntity = "UE";
    wRaw = localFirstMatrix( ...
        sixgr.util.structGet(grant, "PrecodingMatrix", []), ...
        sixgr.util.structGet(cfg, "phy.pdsch.precoding.matrix", []), ...
        sixgr.util.structGet(cfg, "phy.pdsch.precodingMatrix", []), ...
        sixgr.util.structGet(cfg, "phy.pdsch.W", []));
    numElements = localPositiveInteger(localFirstFiniteScalar( ...
        sixgr.util.structGet(grant, "NumElements", []), ...
        sixgr.util.structGet(grant, "TxElements", []), ...
        sixgr.util.structGet(cfg, "antenna.bs.numElements", []), ...
        sixgr.util.structGet(cfg, "scenario.bs.nTxAnt", []), ...
        sixgr.util.structGet(cfg, "mimo.n_tx_ant", []), ...
        sixgr.util.structGet(cfg, "channel.nTxAnt", []), ...
        sixgr.util.structGet(cfg, "phy.nTxAnt", []), numLayers), numLayers);
    numRx = localPositiveInteger(localFirstFiniteScalar( ...
        sixgr.util.structGet(grant, "NumRxAntennas", []), ...
        sixgr.util.structGet(grant, "RxAntennas", []), ...
        sixgr.util.structGet(cfg, "antenna.ue.numElements", []), ...
        sixgr.util.structGet(cfg, "scenario.ue.nRxAnt", []), ...
        sixgr.util.structGet(cfg, "mimo.n_rx_ant", []), ...
        sixgr.util.structGet(cfg, "channel.nRxAnt", []), ...
        sixgr.util.structGet(cfg, "phy.nRxAnt", []), numLayers), numLayers);
    logicalPorts = localResolveDLLogicalPortCount(cfg, grant, numLayers);
    logicalPorts = min(max(logicalPorts, numLayers), max(numElements, numLayers));
    wLogicalRaw = localFirstMatrix( ...
        sixgr.util.structGet(grant, "PrecodingMatrixLogicalPorts", []), ...
        sixgr.util.structGet(grant, "LogicalPrecodingMatrix", []));
    matrixPortCount = localMatrixPortCount(wRaw, numLayers);
    matrixSourceOverride = "";
    inputMatrixUsed = false;
    if isempty(wRaw) && isempty(wLogicalRaw)
        scheduledPMI = localFirstFiniteScalar( ...
            sixgr.util.structGet(grant, "AppliedPrecoderPMI", []), ...
            sixgr.util.structGet(grant, "PMI", []), ...
            sixgr.util.structGet(grant, "TPMI", []), ...
            sixgr.util.structGet(cfg, "phy.pdsch.PMI", []), ...
            sixgr.util.structGet(cfg, "phy.pdsch.pmi", []), NaN);
        if isfinite(scheduledPMI)
            [matrixLogicalPorts, matrixSourceOverride, dlPMIMeta] = ...
                localResolveDLLogicalPrecoder(cfg, grant, numLayers, logicalPorts, numElements);
        else
            matrixLogicalPorts = localRectIdentity(logicalPorts, numLayers, ...
                localResolvePrecoderNormalizationConvention(cfg, grant, "bs", "PDSCH"));
            matrixSourceOverride = "frozen_identity_ports_no_scheduled_pmi";
        end
    elseif ~isempty(wLogicalRaw)
        matrixLogicalPorts = localNormalizeDLMatrix(wLogicalRaw, logicalPorts, numLayers);
        inputMatrixUsed = true;
    elseif isfinite(matrixPortCount) && round(double(matrixPortCount)) == logicalPorts
        matrixLogicalPorts = localNormalizeDLMatrix(wRaw, logicalPorts, numLayers);
        inputMatrixUsed = true;
    elseif isfinite(matrixPortCount) && matrixPortCount > logicalPorts && ~localDLHybridElementDomainEnabled(cfg)
        [matrixLogicalPorts, matrixSourceOverride, dlPMIMeta] = ...
            localResolveDLLogicalPrecoder(cfg, grant, numLayers, logicalPorts, numElements);
    else
        matrixLogicalPorts = [];
        inputMatrixUsed = true;
    end
    [matrixPorts, numWaveformColumns, waveformDomain, elementDomainApplied, hybridElementToPortMatrix, matrixLogicalPorts] = ...
        localMaterializeElementDomainPrecoder(cfg, "bs", "PDSCH", numElements, logicalPorts, ...
        numLayers, matrixLogicalPorts, wRaw, grant);
    if logical(dlPMIMeta.CSIRSPortBasisApplied)
        expectedElementMatrix = double(dlPMIMeta.ComposedElementMatrix);
        residual = norm(double(matrixPorts) - expectedElementMatrix, "fro") ./ ...
            max(norm(expectedElementMatrix, "fro"), eps);
        if ~isequal(size(matrixPorts), size(expectedElementMatrix)) || ...
                ~(isfinite(residual) && residual <= 1e-9)
            error("sixgr:phy:grant:DLPMICSIRSBasisExecutionMismatch", ...
                ['Frozen PDSCH matrix does not reproduce B_CSIRS*W_PMI in the ' ...
                 'physical element domain (relative residual %.3g).'], residual);
        end
    end
    active = logicalPorts > 1 || numLayers > 1 || inputMatrixUsed;
    mode = localFirstNonempty(sixgr.util.structGet(grant, "PrecodingMode", ""), ...
        localTernary(active, "explicit-wideband", "siso-bypass"));
    source = localFirstNonempty(matrixSourceOverride, sixgr.util.structGet(grant, "PrecoderSource", ""), ...
        localTernary(inputMatrixUsed, "frozen_explicit_matrix", "frozen_identity_ports"));
    stage = localFirstNonempty(sixgr.util.structGet(grant, "PrecodingApplicationStage", ""), ...
        localTernary(active, "nrPDSCHPrecode_before_RE_mapping", "none"));
end

selectedMatrix = matrixPorts;
if isUL && nativeCodebookApplied
    selectedMatrix = matrixLogicalPorts;
end

ant = struct( ...
    "Direction", char(direction), ...
    "TxEntity", char(txEntity), ...
    "RxEntity", char(rxEntity), ...
    "NumElements", double(numElements), ...
    "NumPanels", double(localPositiveInteger(localFirstFiniteScalar( ...
        sixgr.util.structGet(grant, "NumPanels", []), 1), 1)), ...
    "NumRFChains", double(localPositiveInteger(localFirstFiniteScalar( ...
        sixgr.util.structGet(grant, "NumRFChains", []), logicalPorts), logicalPorts)), ...
    "NumTxRUs", double(localPositiveInteger(localFirstFiniteScalar( ...
        sixgr.util.structGet(grant, "NumTxRUs", []), logicalPorts), logicalPorts)), ...
    "NumLogicalPorts", double(logicalPorts), ...
    "NumLayers", double(numLayers), ...
    "NumCodewords", double(numCodewords), ...
    "NumWaveformColumns", double(numWaveformColumns), ...
    "WaveformDomain", char(waveformDomain), ...
    "ElementDomainPrecoding", logical(elementDomainApplied), ...
    "NumRxAntennas", double(numRx), ...
    "NumTxAntennas", double(numWaveformColumns));

prec = struct( ...
    "Active", logical(active), ...
    "Mode", char(string(mode)), ...
    "Source", char(string(source)), ...
    "ApplicationStage", char(string(stage)), ...
    "NumPorts", double(numWaveformColumns), ...
    "NumLogicalPorts", double(logicalPorts), ...
    "NumWaveformColumns", double(numWaveformColumns), ...
    "NumLayers", double(numLayers), ...
    "NumCodewords", double(numCodewords), ...
    "Matrix", double(matrixPorts), ...
    "MatrixPorts", double(matrixPorts), ...
    "MatrixPhysicalPorts", double(matrixPorts), ...
    "MatrixLogicalPorts", double(matrixLogicalPorts), ...
    "MatrixRows", double(size(matrixPorts, 1)), ...
    "MatrixCols", double(size(matrixPorts, 2)), ...
    "WaveformDomain", char(waveformDomain), ...
    "HybridElementDomainApplied", logical(elementDomainApplied), ...
    "HybridElementToPortMatrix", double(hybridElementToPortMatrix), ...
    "HybridElementToPortMatrixSHA256", char(sixgr.phy.mimo.MatrixContract.digest( ...
        double(hybridElementToPortMatrix))), ...
    "BaseHybridElementToPortMatrixSHA256", char(string(sixgr.util.structGet( ...
        grant, "BaseHybridElementToPortMatrixSHA256", ""))), ...
    "HybridRFDesignPolicy", char(string(sixgr.util.structGet( ...
        grant, "MUMIMOHybridRFDesignPolicy", "fixed_configured_matrix"))), ...
    "HybridRFDesignStatus", char(string(sixgr.util.structGet( ...
        grant, "MUMIMOHybridRFDesignStatus", ""))), ...
    "TransmitArchitecture", char(string(sixgr.util.structGet( ...
        grant, "MUMIMOTransmitArchitecture", ""))), ...
    "SelectedMatrixSHA256", char(sixgr.phy.mimo.MatrixContract.digest(double(selectedMatrix))), ...
    "AppliedMatrixSHA256", char(sixgr.phy.mimo.MatrixContract.digest(double(matrixPorts))), ...
    "WidebandOnly", true, ...
    "PMI", localFirstFiniteScalar(sixgr.util.structGet(grant, "PMI", []), ...
        sixgr.util.structGet(grant, "AppliedPrecoderPMI", []), NaN), ...
    "TPMI", localFirstFiniteScalar(sixgr.util.structGet(grant, "TPMI", []), ...
        sixgr.util.structGet(grant, "PMI", []), NaN), ...
    "BeamIndices", double(sixgr.util.structGet(grant, "BeamIndices", [])));
prec.NormalizationConvention = char(localResolvePrecoderNormalizationConvention( ...
    cfg, grant, localTernary(isUL, "ue", "bs"), localTernary(isUL, "PUSCH", "PDSCH")));
if isUL
    prec.TransmissionScheme = char(transmissionScheme);
    prec.TransformPrecodingApplied = logical(transformPrecoding);
    prec.NativeCodebookApplied = logical(nativeCodebookApplied);
    prec.CodebookMode = char(string(localFirstNonempty( ...
        sixgr.util.structGet(grant, "CodebookType", ""), ...
        sixgr.util.structGet(cfg, "phy.pusch.CodebookType", ""), ...
        sixgr.util.structGet(cfg, "phy.pusch.codebookType", ""))));
    if nativeCodebookApplied && strlength(strtrim(string(prec.CodebookMode))) == 0
        error("sixgr:phy:grant:MissingULCodebookType", ...
            "Codebook PUSCH requires an explicit MATLAB/3GPP codebook " + ...
            "family in pusch.codebook_type; an internal provenance label " + ...
            "cannot be used as nrPUSCHConfig.CodebookType.");
    end
    prec.CodebookStatus = char(string(codebookStatus));
    prec.MatrixNR = double(codebookMatrixNR);
    prec.MatrixRightInverse = double(codebookRightInverse);
    if nativeCodebookApplied
        prec.PMI = double(round(tpmi));
        prec.TPMI = double(round(tpmi));
        prec.PMIType = "pusch_codebook";
        prec.AuthoritativeSRSDecisionUsed = logical(sixgr.util.structGet( ...
            grant, "SRSCausalUsable", false));
        prec.SRSMeasurementID = char(string(sixgr.util.structGet( ...
            grant, "SRSCausalMeasurementId", "")));
        prec.SRSMeasurementSlot = double(sixgr.util.structGet( ...
            grant, "LastSuccessfulSRSSlot", NaN));
    end
else
    prec.PMI = double(dlPMIMeta.PMI);
    prec.PMIType = char(string(dlPMIMeta.PMIType));
    prec.CodebookMode = char(string(dlPMIMeta.CodebookMode));
    prec.BeamIndices = double(dlPMIMeta.BeamIndices);
    prec.CSIRSPortBasisApplied = logical(dlPMIMeta.CSIRSPortBasisApplied);
    prec.CSIResourceIndex = double(dlPMIMeta.CSIResourceIndex);
    prec.PMICodebookMatrixCSIPorts = double(dlPMIMeta.PMICodebookMatrixCSIPorts);
    prec.PMICodebookMatrixCSIPortsSHA256 = char(string( ...
        dlPMIMeta.PMICodebookMatrixCSIPortsSHA256));
    prec.CSIRSPortToElementMatrix = double(dlPMIMeta.CSIRSPortToElementMatrix);
    prec.CSIRSPortToElementMatrixSHA256 = char(string( ...
        dlPMIMeta.CSIRSPortToElementMatrixSHA256));
    prec.ComposedElementMatrixSHA256 = char(string( ...
        dlPMIMeta.ComposedElementMatrixSHA256));
end
end

function localValidateULSRSCodebookAuthority(cfg, grant, nLayers, nPorts, tpmi)
if ~(isscalar(tpmi) && isfinite(tpmi) && tpmi >= 0 && tpmi == round(tpmi))
    error("sixgr:phy:grant:MissingULTPMI", ...
        "Codebook PUSCH requires a finite non-negative integer TPMI in the scheduled grant.");
end
strictMIMO = logical(sixgr.util.structGet(cfg, "mimo.strict", ...
    sixgr.util.structGet(cfg, "phy.mimo.strict", false)));
if ~strictMIMO
    return;
end
causalUsable = logical(sixgr.util.structGet(grant, "SRSCausalUsable", false));
srsValid = logical(sixgr.util.structGet(grant, "SRSValid", false));
measurementId = strtrim(string(sixgr.util.structGet(grant, ...
    "SRSCausalMeasurementId", "")));
measurementSlot = double(sixgr.util.structGet(grant, ...
    "LastSuccessfulSRSSlot", NaN));
ri = localFirstFiniteScalar( ...
    sixgr.util.structGet(grant, "RI", []), ...
    sixgr.util.structGet(grant, "RIUsed", []), ...
    sixgr.util.structGet(grant, "NumLayers", []), NaN);
if ~causalUsable || ~srsValid || strlength(measurementId) == 0 || ...
        ~(isscalar(measurementSlot) && isfinite(measurementSlot))
    error("sixgr:mimo:MissingSRSState", ...
        "Strict codebook PUSCH grant requires a usable causal SRS measurement identity and slot.");
end
if ~(isscalar(ri) && isfinite(ri) && round(ri) == round(nLayers))
    error("sixgr:mimo:RankIdentityMismatch", ...
        "Causal SRS RI %g differs from scheduled PUSCH layers %d.", ri, nLayers);
end
if nPorts < nLayers
    error("sixgr:mimo:PortIdentityMismatch", ...
        "Scheduled PUSCH codebook ports %d are fewer than layers %d.", nPorts, nLayers);
end
end

function [Wphysical, nWaveformColumns, waveformDomain, elementDomainApplied, F, Wlogical] = ...
        localMaterializeElementDomainPrecoder(cfg, role, signal, nElements, nLogicalPorts, nLayers, Wlogical, Wraw, grant)
% Preserve the two distinct contracts: NR mapping uses logical ports, while
% an enabled hybrid RF/baseband architecture emits one waveform column per
% physical element. A frozen grant stores both matrices explicitly.
if isempty(Wlogical)
    Wlogical = [];
else
    Wlogical = localNormalizeDLMatrix(Wlogical, nLogicalPorts, nLayers);
end
Wphysical = Wlogical;
nWaveformColumns = nLogicalPorts;
waveformDomain = "logical_port";
elementDomainApplied = false;
F = [];

frozenRFChains = double(sixgr.util.structGet(grant, "NumRFChains", NaN));
if ~(isscalar(frozenRFChains) && isfinite(frozenRFChains) && frozenRFChains >= nLogicalPorts && ...
        frozenRFChains == round(frozenRFChains))
    frozenRFChains = NaN;
end
matrixAuthorityScope = "signal_then_role";
if localUsesMeasuredMUMIMOBaseArchitecture(grant, signal)
    % A signal-level PDSCH matrix is a selection owned by one earlier
    % grant.  It is not the immutable hybrid-array architecture used to
    % design a new measured-SRS MU group.  Bind strict measured-MU grants
    % to the YAML-owned role matrix, exactly as the MU designer does, and
    % then retain the existing residual/digest guards below.
    matrixAuthorityScope = "role_only";
end
arch = sixgr.rf.AntennaArrayFactory.resolvePortArchitecture(cfg, string(role), ...
    "Signal", string(signal), "NumElements", double(nElements), ...
    "NumPorts", double(nLogicalPorts), "NumRFChains", frozenRFChains, ...
    "MinimumPorts", double(nLayers), ...
    "MatrixAuthorityScope", matrixAuthorityScope);
if ~logical(sixgr.util.structGet(arch, "HybridBeamformingEnabled", false))
    if isempty(Wlogical)
        if isempty(Wraw)
            Wlogical = localRectIdentity(nLogicalPorts, nLayers, ...
                localResolvePrecoderNormalizationConvention(cfg, grant, role, signal));
        else
            Wlogical = localNormalizeDLMatrix(Wraw, nLogicalPorts, nLayers);
        end
    end
    Wphysical = Wlogical;
    return;
end

F = double(sixgr.util.structGet(arch, "HybridElementToPortMatrix", []));
if isempty(F) || ~ismatrix(F) || size(F, 1) ~= nElements || size(F, 2) ~= nLogicalPorts
    error("sixgr:phy:grant:HybridMatrixShapeMismatch", ...
        "Hybrid %s architecture matrix is %dx%d; expected %dx%d element-by-logical-port.", ...
        char(signal), size(F, 1), size(F, 2), nElements, nLogicalPorts);
end
frozenF = double(sixgr.util.structGet(grant, "HybridElementToPortMatrix", []));
if ~isempty(frozenF)
    if ~ismatrix(frozenF) || ~isequal(size(frozenF), [nElements nLogicalPorts]) || ...
            any(~isfinite(real(frozenF(:)))) || any(~isfinite(imag(frozenF(:))))
        error("sixgr:phy:grant:FrozenHybridArchitectureShapeMismatch", ...
            "Frozen %s hybrid architecture must be a finite %dx%d element-by-logical-port matrix.", ...
            char(signal), nElements, nLogicalPorts);
    end
    architectureResidual = norm(F - frozenF, "fro") / max(norm(frozenF, "fro"), eps);
    if architectureResidual > 1e-12
        configuredPolicy = lower(strtrim(string(sixgr.util.structGet(cfg, ...
            "mac.scheduler.muMimoHybridRFDesignPolicy", ...
            sixgr.util.structGet(cfg, "phy.mimo.muMimoHybridRFDesignPolicy", ...
            "fixed_configured_matrix")))));
        frozenPolicy = lower(strtrim(string(sixgr.util.structGet(grant, ...
            "MUMIMOHybridRFDesignPolicy", "fixed_configured_matrix"))));
        adaptivePolicy = "measured_srs_phase_only_subarray";
        if upper(string(signal)) ~= "PDSCH" || configuredPolicy ~= adaptivePolicy || ...
                frozenPolicy ~= configuredPolicy
            error("sixgr:phy:grant:FrozenHybridArchitectureMismatch", ...
                ['Frozen %s RF/baseband architecture differs from the architecture resolved with ' ...
                 'the frozen RF-chain count (relative residual %.3g).'], ...
                char(signal), architectureResidual);
        end
        localValidateAdaptiveHybridGrant(F, frozenF, grant);
    end
    F = frozenF;
end

rawPorts = localMatrixPortCount(Wraw, nLayers);
if isempty(Wlogical) && ~isempty(Wraw) && isfinite(rawPorts) && round(rawPorts) == nElements
    WrawPhysical = localNormalizeDLMatrix(Wraw, nElements, nLayers);
    Wlogical = pinv(F) * WrawPhysical;
elseif isempty(Wlogical) && ~isempty(Wraw)
    Wlogical = localNormalizeDLMatrix(Wraw, nLogicalPorts, nLayers);
end

if isempty(Wlogical)
    Wlogical = localRectIdentity(nLogicalPorts, nLayers, ...
        localResolvePrecoderNormalizationConvention(cfg, grant, role, signal));
end
Wphysical = F * Wlogical;
if isfinite(rawPorts) && round(rawPorts) == nElements
    WrawPhysical = localNormalizeDLMatrix(Wraw, nElements, nLayers);
    residual = norm(Wphysical - WrawPhysical, "fro") / max(norm(WrawPhysical, "fro"), eps);
    if residual > 1e-9
        error("sixgr:phy:grant:HybridPrecoderSubspaceMismatch", ...
            "The frozen %s %dx%d element-domain precoder is outside the configured %dx%d hybrid logical-port subspace (relative residual %.3g).", ...
            char(signal), size(WrawPhysical, 1), size(WrawPhysical, 2), size(F, 1), size(F, 2), residual);
    end
    Wphysical = WrawPhysical;
end
nWaveformColumns = size(Wphysical, 1);
waveformDomain = "element";
elementDomainApplied = true;
end

function tf = localUsesMeasuredMUMIMOBaseArchitecture(grant, signal)
tf = false;
if upper(strtrim(string(signal))) ~= "PDSCH"
    return;
end
contractVersion = strtrim(string(sixgr.util.structGet(grant, ...
    "MUMIMOSpatialDesignContractVersion", "")));
evidenceSource = lower(strtrim(string(sixgr.util.structGet(grant, ...
    "MUMIMOSpatialDesignEvidenceSource", ""))));
currentMeasuredMU = logical(sixgr.util.structGet( ...
    grant, "MUMIMOEnabled", false)) && ...
    double(sixgr.util.structGet(grant, "MUMIMOGroupSize", 0)) >= 2;
historicalMeasuredMU = logical(sixgr.util.structGet( ...
    grant, "IsRetransmission", false)) && ...
    double(sixgr.util.structGet(grant, "PriorMUMIMOGroupSize", 0)) >= 2;
tf = (currentMeasuredMU || historicalMeasuredMU) && ...
    startsWith(contractVersion, "MeasuredMUMIMOPairDesign/") && ...
    (contains(evidenceSource, "measured_srs") || ...
     contains(evidenceSource, "measured_csirs"));
end

function localValidateAdaptiveHybridGrant(baseF, frozenF, grant)
contractVersion = string(sixgr.util.structGet(grant, ...
    "MUMIMOSpatialDesignContractVersion", ""));
subspaceMode = lower(strtrim(string(sixgr.util.structGet(grant, ...
    "MUMIMOSpatialSignatureSubspaceMode", ""))));
designStatus = string(sixgr.util.structGet(grant, "MUMIMOSpatialDesignStatus", ""));
evidenceSource = string(sixgr.util.structGet(grant, ...
    "MUMIMOSpatialDesignEvidenceSource", ...
    sixgr.util.structGet(grant, "MUMIMOPairingEvidenceSource", "")));
if contractVersion ~= "MeasuredMUMIMOPairDesign/v13" || ...
        subspaceMode ~= "complete_detectable_subspace" || ...
        designStatus ~= "compatible_executable_measured_spatial_design" || ...
        evidenceSource ~= "causal_measured_srs_complete_peer_subspace_reciprocity_phase_only_hybrid_and_frozen_baseband"
    error("sixgr:phy:grant:FrozenHybridArchitectureAuthorityMissing", ...
        "Adaptive hybrid RF phases require a compatible v13 joint-per-victim " + ...
        "unit-total-power complete-peer-subspace measured-SRS design and its " + ...
        "exact causal reciprocity evidence source.");
end
baseSupport = abs(baseF) > 1e-14;
frozenSupport = abs(frozenF) > 1e-14;
magnitudeResidual = norm(abs(baseF) - abs(frozenF), "fro") ./ ...
    max(norm(abs(baseF), "fro"), eps);
if ~isequal(baseSupport, frozenSupport) || magnitudeResidual > 1e-12 || ...
        any(abs(sum(abs(frozenF).^2, 1) - sum(abs(baseF).^2, 1)) > 1e-12)
    error("sixgr:phy:grant:FrozenHybridArchitectureHardwareMismatch", ...
        "Adaptive hybrid RF matrix changed the configured subarray support, " + ...
        "constant-modulus magnitudes, or per-chain normalization (residual %.3g).", ...
        magnitudeResidual);
end
expectedBaseDigest = strtrim(string(sixgr.util.structGet(grant, ...
    "BaseHybridElementToPortMatrixSHA256", "")));
actualBaseDigest = string(sixgr.phy.mimo.MatrixContract.digest(baseF));
if strlength(expectedBaseDigest) ~= 64 || expectedBaseDigest ~= actualBaseDigest
    error("sixgr:phy:grant:FrozenHybridArchitectureBaseDigestMismatch", ...
        "Adaptive hybrid RF grant is not bound to the configured base architecture digest.");
end
expectedFrozenDigest = strtrim(string(sixgr.util.structGet(grant, ...
    "HybridElementToPortMatrixSHA256", "")));
actualFrozenDigest = string(sixgr.phy.mimo.MatrixContract.digest(frozenF));
if strlength(expectedFrozenDigest) ~= 64 || expectedFrozenDigest ~= actualFrozenDigest
    error("sixgr:phy:grant:FrozenHybridArchitectureDigestMismatch", ...
        "Adaptive hybrid RF grant matrix differs from its frozen matrix digest.");
end
end

function W = localNormalizeDLMatrix(Wraw, nPorts, nLayers)
if isempty(Wraw)
    W = localRectIdentity(nPorts, nLayers);
    return;
end
Wraw = double(Wraw);
if ndims(Wraw) > 2 && size(Wraw, 3) == 1
    Wraw = squeeze(Wraw);
end
if ~ismatrix(Wraw)
    error("sixgr:phy:grant:BadPrecodingMatrix", ...
        "PHYGrant DL PrecodingState.Matrix must be a 2-D matrix.");
end
if size(Wraw, 2) == nLayers
    W = Wraw;
elseif size(Wraw, 1) == nLayers
    W = Wraw.';
elseif size(Wraw, 2) > nLayers && size(Wraw, 1) >= nLayers
    W = Wraw(:, 1:nLayers);
else
    error("sixgr:phy:grant:BadPrecodingMatrix", ...
        "DL precoding matrix must be Nports-by-Nlayers or transpose. Got %dx%d for %d layer(s).", ...
        size(Wraw, 1), size(Wraw, 2), nLayers);
end
end

function nPorts = localResolveDLLogicalPortCount(cfg, grant, nLayers)
    nPorts = sixgr.phy.grant.resolveDLLogicalPortCount(cfg, grant, nLayers);
end

function nPorts = localMaxNRLogicalPDSCHPorts()
% Prevent element-array counts such as 64 from becoming logical NR waveform
% ports unless the scenario explicitly requests that logical port count.
nPorts = 32;
end

function [W, source, meta] = localResolveDLLogicalPrecoder(cfg, grant, nLayers, nPorts, nElements)
source = "";
W = [];
pmi = localFirstFiniteScalar( ...
    sixgr.util.structGet(grant, "AppliedPrecoderPMI", []), ...
    sixgr.util.structGet(grant, "PMI", []), ...
    sixgr.util.structGet(grant, "TPMI", []), ...
    sixgr.util.structGet(cfg, "phy.pdsch.PMI", []), ...
    sixgr.util.structGet(cfg, "phy.pdsch.pmi", []), NaN);
mode = localFirstNonempty( ...
    sixgr.util.structGet(grant, "AppliedPrecoderCodebookMode", ""), ...
    sixgr.util.structGet(grant, "PMICodebookMode", ""), ...
    sixgr.util.structGet(cfg, "phy.csi.pmiCodebookMode", ""), ...
    "type1_su_mimo");
meta = struct("PMI", double(pmi), "PMIType", "", ...
    "CodebookMode", string(mode), "BeamIndices", zeros(1, 0), ...
    "CSIRSPortBasisApplied", false, "CSIResourceIndex", NaN, ...
    "PMICodebookMatrixCSIPorts", [], ...
    "PMICodebookMatrixCSIPortsSHA256", "", ...
    "CSIRSPortToElementMatrix", [], ...
    "CSIRSPortToElementMatrixSHA256", "", ...
    "ComposedElementMatrix", [], ...
    "ComposedElementMatrixSHA256", "");
if ~isfinite(pmi)
    error("sixgr:phy:grant:MissingDLPMI", ...
        ["A scheduled multi-port DL grant without an explicit precoding matrix " ...
         "requires a finite PMI/TPMI. The frozen grant cannot substitute identity precoding."]);
end
try
    [candidates, info] = sixgr.phy.dl.pmiCodebookCandidates( ...
        cfg, nLayers, nPorts, "Mode", mode);
    if isempty(candidates)
        error("sixgr:phy:grant:EmptyDLPMICodebook", ...
            "No DL PMI candidates exist for %d port(s), %d layer(s), mode '%s'.", ...
            nPorts, nLayers, char(string(mode)));
    end
    pmi0 = round(double(pmi));
    if pmi0 ~= double(pmi) || pmi0 < 0 || pmi0 >= numel(candidates)
        error("sixgr:phy:grant:DLPMIOutOfRange", ...
            "Scheduled DL PMI=%g is invalid for mode '%s' with %d candidate(s).", ...
            double(pmi), char(string(mode)), numel(candidates));
    end
    idx = pmi0 + 1;
    Wcand = double(candidates(idx).W);
    if ~isequal(size(Wcand), [nPorts nLayers])
        error("sixgr:phy:grant:DLPMICodebookShapeMismatch", ...
            ["Scheduled DL PMI=%d resolved to a %dx%d matrix; the frozen grant " ...
             "requires %dx%d (logical ports by layers)."], ...
            pmi0, size(Wcand, 1), size(Wcand, 2), nPorts, nLayers);
    end
    Wcsi = localNormalizeScheduledDLCodebookMatrix(Wcand, ...
        localResolvePrecoderNormalizationConvention(cfg, grant, "bs", "PDSCH"));
    [W, basisMeta] = localComposeDLPMIWithCSIRSPortBasis( ...
        cfg, grant, Wcsi, nElements, nPorts, nLayers);
    if logical(basisMeta.Applied)
        source = "frozen_dl_pmi_codebook_composed_with_csirs_port_basis";
    else
        source = "frozen_dl_pmi_codebook_from_scheduled_grant";
    end
    meta.PMI = double(pmi0);
    meta.PMIType = string(sixgr.util.structGet(candidates(idx), "PMIType", ""));
    meta.CodebookMode = string(sixgr.util.structGet(candidates(idx), ...
        "CodebookMode", sixgr.util.structGet(info, "Mode", mode)));
    meta.BeamIndices = double(sixgr.util.structGet(candidates(idx), ...
        "BeamIndices", []));
    meta.CSIRSPortBasisApplied = logical(basisMeta.Applied);
    meta.CSIResourceIndex = double(basisMeta.CSIResourceIndex);
    meta.PMICodebookMatrixCSIPorts = double(Wcsi);
    meta.PMICodebookMatrixCSIPortsSHA256 = ...
        sixgr.phy.mimo.MatrixContract.digest(double(Wcsi));
    meta.CSIRSPortToElementMatrix = double(basisMeta.CSIRSPortToElementMatrix);
    meta.CSIRSPortToElementMatrixSHA256 = char(string( ...
        basisMeta.CSIRSPortToElementMatrixSHA256));
    meta.ComposedElementMatrix = double(basisMeta.ComposedElementMatrix);
    meta.ComposedElementMatrixSHA256 = char(string( ...
        basisMeta.ComposedElementMatrixSHA256));
catch ME
    if startsWith(string(ME.identifier), "sixgr:phy:grant:")
        rethrow(ME);
    end
    wrapped = MException("sixgr:phy:grant:DLPMIMaterializationFailed", ...
        "Failed to materialize scheduled DL PMI=%g: %s", double(pmi), ME.message);
    wrapped = addCause(wrapped, ME);
    throwAsCaller(wrapped);
end
end

function [WpdschPorts, meta] = localComposeDLPMIWithCSIRSPortBasis( ...
        cfg, grant, Wcsi, nElements, nPorts, nLayers)
% A Type-I PMI is defined in the measured CSI-RS antenna-port basis.  If
% CSI-RS ports were spatially filtered by B_CSIRS, data must use
% B_CSIRS*W_PMI in the physical element domain.  PDSCH may itself expose a
% logical port projection P, so freeze P\(B*W) only when the exact physical
% target lies in that configured subspace.
meta = struct("Applied", false, "CSIResourceIndex", NaN, ...
    "CSIRSPortToElementMatrix", [], ...
    "CSIRSPortToElementMatrixSHA256", "", ...
    "ComposedElementMatrix", [], "ComposedElementMatrixSHA256", "");
WpdschPorts = double(Wcsi);
precoders = sixgr.util.structGet(cfg, "phy.csirs.precoderMatrices", []);
if isempty(precoders)
    return;
end
if ~isnumeric(precoders) || any(~isfinite(real(precoders(:)))) || ...
        any(~isfinite(imag(precoders(:))))
    error("sixgr:phy:grant:InvalidCSIRSPortBasis", ...
        "phy.csirs.precoderMatrices must be a finite numeric tensor.");
end
nResources = size(precoders, 3);
cri = localFirstFiniteScalar( ...
    sixgr.util.structGet(grant, "CRI", []), ...
    sixgr.util.structGet(grant, "AppliedCRI", []), ...
    sixgr.util.structGet(cfg, "phy.csi.selectedCRI", []), ...
    sixgr.util.structGet(cfg, "phy.beamManagement.selectedCRI", []), NaN);
if ~isfinite(cri)
    if nResources ~= 1
        error("sixgr:phy:grant:MissingDLCRIForCSIRSBasis", ...
            ['A scheduled PMI with %d CSI-RS resources requires the causal ' ...
             'zero-based CRI used to select its physical port basis.'], nResources);
    end
    cri = 0;
end
cri0 = round(double(cri));
if cri0 ~= double(cri) || cri0 < 0 || cri0 >= nResources
    error("sixgr:phy:grant:DLCRIOutOfRange", ...
        "Scheduled CRI=%g is outside the configured CSI-RS resource range [0,%d].", ...
        double(cri), nResources - 1);
end
B = complex(double(precoders(:, :, cri0 + 1)));
if ~isequal(size(B), [nElements nPorts])
    error("sixgr:phy:grant:CSIRSPortBasisShapeMismatch", ...
        ['CSI-RS resource CRI=%d has a %dx%d physical-element by CSI-port ' ...
         'basis; scheduled PDSCH requires %dx%d.'], ...
        cri0, size(B, 1), size(B, 2), nElements, nPorts);
end
gramResidual = norm(B' * B - eye(nPorts), "fro");
if gramResidual > 1e-10
    error("sixgr:phy:grant:CSIRSPortBasisNotSemiUnitary", ...
        "CSI-RS resource CRI=%d port basis is not semi-unitary (residual %.3g).", ...
        cri0, gramResidual);
end
targetElementMatrix = B * Wcsi;
arch = sixgr.rf.AntennaArrayFactory.resolvePortArchitecture(cfg, "bs", ...
    "Signal", "PDSCH", "NumElements", double(nElements), ...
    "NumPorts", double(nPorts), "MinimumPorts", double(nLayers));
P = complex(double(sixgr.util.structGet(arch, "PortToElementMatrix", [])));
if ~isequal(size(P), [nElements nPorts]) || ...
        any(~isfinite(real(P(:)))) || any(~isfinite(imag(P(:))))
    error("sixgr:phy:grant:InvalidPDSCHPortProjection", ...
        "PDSCH port-to-element projection must be a finite %dx%d matrix.", ...
        nElements, nPorts);
end
projectionGramResidual = norm(P' * P - eye(nPorts), "fro");
if projectionGramResidual > 1e-10
    error("sixgr:phy:grant:PDSCHPortProjectionNotSemiUnitary", ...
        "PDSCH port-to-element projection is not semi-unitary (residual %.3g).", ...
        projectionGramResidual);
end
WpdschPorts = P' * targetElementMatrix;
projectionResidual = norm(P * WpdschPorts - targetElementMatrix, "fro") ./ ...
    max(norm(targetElementMatrix, "fro"), eps);
if ~(isfinite(projectionResidual) && projectionResidual <= 1e-9)
    error("sixgr:phy:grant:CSIRSPMIPrecoderOutsidePDSCHSubspace", ...
        ['B_CSIRS*W_PMI for CRI=%d is outside the configured PDSCH port ' ...
         'subspace (relative residual %.3g).'], cri0, projectionResidual);
end
meta.Applied = true;
meta.CSIResourceIndex = double(cri0);
meta.CSIRSPortToElementMatrix = B;
meta.CSIRSPortToElementMatrixSHA256 = ...
    sixgr.phy.mimo.MatrixContract.digest(B);
meta.ComposedElementMatrix = targetElementMatrix;
meta.ComposedElementMatrixSHA256 = ...
    sixgr.phy.mimo.MatrixContract.digest(targetElementMatrix);
end

function W = localNormalizeScheduledDLCodebookMatrix(W, convention)
convention = lower(strtrim(string(convention)));
W = double(W);
if convention == "unit_frobenius"
    scale = norm(W, "fro");
    if ~(isscalar(scale) && isfinite(scale) && scale > 0)
        error("sixgr:phy:grant:DLPMICodebookNormalizationFailure", ...
            "Scheduled DL PMI resolved to a zero or non-finite precoding matrix.");
    end
    W = W ./ scale;
elseif ~any(convention == ["semi_unitary", "explicit_no_normalization"])
    error("sixgr:mimo:PrecoderNormalizationConventionUnsupported", ...
        "Unsupported frozen PDSCH precoder normalization convention '%s'.", ...
        char(convention));
end
end

function tf = localDLHybridElementDomainEnabled(cfg)
tf = logical(sixgr.util.structGet(cfg, "phy.pdsch.hybridBeamformingEnabled", ...
    sixgr.util.structGet(cfg, "phy.pdsch.hybridBeamforming", ...
    sixgr.util.structGet(cfg, "rf.bs.hybridBeamformingEnabled", ...
    sixgr.util.structGet(cfg, "rf.bs.hybridBeamforming", ...
    sixgr.util.structGet(cfg, "antenna.bs.hybridBeamformingEnabled", ...
    sixgr.util.structGet(cfg, "antenna.bs.hybridBeamforming", ...
    sixgr.util.structGet(cfg, "phy.beamManagement.hybridBeamformingEnabled", false))))))));
end

function W = localRectIdentity(nPorts, nLayers, normalizationConvention)
if nargin < 3 || strlength(strtrim(string(normalizationConvention))) == 0
    normalizationConvention = "semi_unitary";
end
W = zeros(max(1, nPorts), max(1, nLayers));
activeStreams = min(size(W, 1), size(W, 2));
coefficient = 1 / sqrt(activeStreams);
if lower(strtrim(string(normalizationConvention))) == "semi_unitary"
    coefficient = 1;
end
for i = 1:activeStreams
    W(i, i) = coefficient;
end
end

function convention = localResolvePrecoderNormalizationConvention(cfg, grant, role, signal)
explicit = string(sixgr.util.structGet(grant, "PrecoderNormalizationConvention", ""));
if strlength(strtrim(explicit)) > 0
    convention = lower(strtrim(explicit));
elseif upper(strtrim(string(signal))) == "PUSCH" || lower(strtrim(string(role))) == "ue"
    convention = lower(strtrim(string(sixgr.util.structGet(cfg, ...
        "phy.pusch.precoding.normalizationConvention", ...
        sixgr.util.structGet(cfg, "pusch.precoder_normalization_convention", ...
        "semi_unitary")))));
else
    convention = lower(strtrim(string(sixgr.util.structGet(cfg, ...
        "phy.pdsch.precoding.normalizationConvention", ...
        sixgr.util.structGet(cfg, "pdsch.precoder_normalization_convention", ...
        "semi_unitary")))));
end
if ~any(convention == ["unit_frobenius","semi_unitary","explicit_no_normalization"])
    error("sixgr:mimo:PrecoderNormalizationConventionUnsupported", ...
        "Unsupported frozen %s precoder normalization convention '%s'.", ...
        char(string(signal)), convention);
end
end

function ports = localMatrixPortCount(W, nLayers)
ports = NaN;
if isempty(W) || ~isnumeric(W)
    return;
end
if ndims(W) > 2 && size(W, 3) == 1
    W = squeeze(W);
end
if ~ismatrix(W)
    return;
end
if size(W, 2) == nLayers
    ports = double(size(W, 1));
elseif size(W, 1) == nLayers
    ports = double(size(W, 2));
else
    ports = double(size(W, 1));
end
end

function W = localFirstMatrix(varargin)
W = [];
for i = 1:nargin
    raw = varargin{i};
    if isnumeric(raw) && ~isempty(raw)
        W = raw;
        return;
    end
end
end

function profile = localResolveFadingProfile(cfg)
model = upper(string(sixgr.util.structGet(cfg, "channel.model", "")));
if startsWith(model, "TDL")
    profile = string(sixgr.util.structGet(cfg, "channel.tdlProfile", model));
elseif startsWith(model, "CDL")
    profile = string(sixgr.util.structGet(cfg, "channel.cdlProfile", model));
else
    profile = model;
end
end

function value = localFirstFiniteScalar(varargin)
value = NaN;
for i = 1:nargin
    raw = varargin{i};
    if isempty(raw) || ~(isnumeric(raw) || islogical(raw))
        continue;
    end
    raw = double(raw(:));
    raw = raw(isfinite(raw));
    if ~isempty(raw)
        value = raw(1);
        return;
    end
end
end

function value = localPositiveInteger(value, fallback)
if ~(isscalar(value) && isfinite(double(value)) && double(value) >= 1)
    value = fallback;
end
value = max(1, round(double(value)));
end

function value = localFirstNonempty(varargin)
value = "";
for i = 1:nargin
    raw = string(varargin{i});
    raw = raw(~ismissing(raw));
    if ~isempty(raw) && strlength(strtrim(raw(1))) > 0
        value = raw(1);
        return;
    end
end
end

function out = localTernary(tf, a, b)
if logical(tf)
    out = a;
else
    out = b;
end
end

function token = localComposeContextId(direction, servingCell, ueIndex, rnti, frame, slot)
token = sprintf('%s|cell=%s|ue=%s|rnti=%s|frame=%s|slot=%s', ...
    char(direction), localIntegerToken(servingCell), localIntegerToken(ueIndex), ...
    localIntegerToken(rnti), localIntegerToken(frame), localIntegerToken(slot));
end

function token = localIntegerToken(value)
value = round(double(value));
if ~(isscalar(value) && isfinite(value))
    token = "na";
else
    token = sprintf('%d', value);
end
end
