function phyGrant = freezePHYGrant(cfg, direction, grant, varargin)
%FREEZEPHYGRANT Build the immutable PHY grant contract used by TX/RX/HARQ.
% Keep this file ASCII-only.

ip = inputParser;
ip.addParameter("SNR_dB", NaN, @(x) isempty(x) || (isnumeric(x) && isscalar(x)));
ip.addParameter("Frame", NaN, @(x) isempty(x) || (isnumeric(x) && isscalar(x)));
ip.addParameter("Slot", NaN, @(x) isempty(x) || (isnumeric(x) && isscalar(x)));
ip.addParameter("HARQContext", struct(), @(x) isempty(x) || isstruct(x));
ip.parse(varargin{:});
opt = ip.Results;

if nargin < 1 || ~isstruct(cfg)
    cfg = struct();
end
if nargin < 2 || strlength(string(direction)) == 0
    direction = sixgr.util.structGet(grant, "Direction", "DL");
end
if nargin < 3 || ~isstruct(grant)
    grant = struct();
end
direction = upper(string(direction));
if ~(direction == "DL" || direction == "UL")
    error("sixgr:phy:grant:BadDirection", ...
        "PHYGrant direction must be DL or UL. Got '%s'.", char(direction));
end

existing = sixgr.util.structGet(grant, "PHYGrant", struct());
if localCanReuseFrozenPHYGrant(existing, cfg, direction, grant, opt)
    sixgr.phy.grant.assertPHYGrantDimensions(existing, "reuse_existing_phygrant");
    phyGrant = existing;
    return;
end

isUL = direction == "UL";
root = localChannelRoot(isUL);
frame = localFirstFiniteScalar(opt.Frame, sixgr.util.structGet(grant, "Frame", []), NaN);
slot = localFirstFiniteScalar(opt.Slot, sixgr.util.structGet(grant, "Slot", []), frame);
rnti = localFirstFiniteScalar(sixgr.util.structGet(grant, "RNTI", []), ...
    sixgr.util.structGet(cfg, root + ".RNTI", []), NaN);
ueIndex = localFirstFiniteScalar(sixgr.util.structGet(grant, "UEIndex", []), ...
    sixgr.util.structGet(grant, "UEID", []), ...
    sixgr.util.structGet(cfg, "lls6g.userContext.UEIndex", []), NaN);
servingCell = localFirstFiniteScalar(sixgr.util.structGet(grant, "ServingCell", []), ...
    sixgr.util.structGet(grant, "BaseStationID", []), ...
    sixgr.util.structGet(cfg, "lls6g.userContext.RuntimeServingCell", []), ...
    sixgr.util.structGet(cfg, "scenario.bs.cell_id", []), NaN);

numLayers = localPositiveInteger(localFirstFiniteScalar( ...
    sixgr.util.structGet(grant, "NumLayers", []), ...
    sixgr.util.structGet(grant, "Layers", []), ...
    sixgr.util.structGet(cfg, root + ".numLayers", []), ...
    sixgr.util.structGet(cfg, root + ".nLayers", []), 1), 1);
numCodewords = localPositiveInteger(localFirstFiniteScalar( ...
    sixgr.util.structGet(grant, "NumCodewords", []), ...
    sixgr.util.structGet(grant, "CodewordCount", []), ...
    1 + double(numLayers > 4)), 1);

prbSet = localResolvePRBSet(cfg, grant, root);
symbolAllocation = localResolveSymbolAllocation(cfg, grant, root);
modulation = char(string(localFirstNonempty( ...
    sixgr.util.structGet(grant, "Modulation", ""), ...
    sixgr.util.structGet(cfg, root + ".modulation", "QPSK"))));
targetCodeRate = localFirstFiniteScalar( ...
    sixgr.util.structGet(grant, "TargetCodeRate", []), ...
    sixgr.util.structGet(cfg, root + ".codeRate", []), NaN);
xOverhead = localFirstFiniteScalar( ...
    sixgr.util.structGet(grant, "XOverhead", []), ...
    sixgr.util.structGet(cfg, root + ".xOverhead", []), 0);
nrePerPRB = localFirstFiniteScalar(sixgr.util.structGet(grant, "NREPerPRB", []), NaN);
tbsBits = localFirstFiniteScalar( ...
    sixgr.util.structGet(grant, "TBSBits", []), ...
    sixgr.util.structGet(grant, "TransportBlockSize", []), ...
    sixgr.util.structGet(grant, "TBSize_bits", []), NaN);
tbsBytes = localFirstFiniteScalar(sixgr.util.structGet(grant, "TBSBytes", []), floor(max(tbsBits, 0) / 8));

[ant, prec] = localResolveAntennaAndPrecoding(cfg, grant, direction, numLayers, numCodewords);

resourceAllocation = struct( ...
    "PRBSet", double(prbSet(:).'), ...
    "PRBStart", localFirstFiniteScalar(min(double(prbSet(:))), sixgr.util.structGet(grant, "PRBStart", []), NaN), ...
    "PRBCount", double(numel(prbSet)), ...
    "SymbolAllocation", double(symbolAllocation(:).'), ...
    "SymbolStart", double(symbolAllocation(1)), ...
    "NumSymbols", double(symbolAllocation(2)));

codingLayout = struct( ...
    "Modulation", char(modulation), ...
    "MCSIndex", localFirstFiniteScalar(sixgr.util.structGet(grant, "MCSIndex", []), ...
        sixgr.util.structGet(grant, "MCS", []), sixgr.util.structGet(cfg, root + ".mcsIndex", []), NaN), ...
    "MCSTable", char(string(localFirstNonempty(sixgr.util.structGet(grant, "MCSTable", ""), ...
        sixgr.util.structGet(cfg, root + ".mcsTable", "")))), ...
    "CQITable", char(string(localFirstNonempty(sixgr.util.structGet(grant, "CQITable", ""), ...
        sixgr.util.structGet(cfg, "link_adaptation.cqiTable", "")))), ...
    "TargetCodeRate", double(targetCodeRate), ...
    "XOverhead", double(xOverhead), ...
    "NREPerPRB", double(nrePerPRB), ...
    "TBSBits", double(tbsBits), ...
    "TBSBytes", double(tbsBytes), ...
    "NumLayers", double(numLayers), ...
    "NumCodewords", double(numCodewords));

noiseContext = struct( ...
    "SNR_dB", double(localFirstFiniteScalar(opt.SNR_dB, ...
        sixgr.util.structGet(cfg, "channel.snr_dB", []), NaN)), ...
    "NoiseVariance", localFirstFiniteScalar(sixgr.util.structGet(grant, "NoiseVariance", []), NaN), ...
    "NoiseSource", char(string(sixgr.util.structGet(grant, "NoiseSource", ""))));

channelStateKey = struct( ...
    "Direction", char(direction), ...
    "Frame", double(frame), ...
    "Slot", double(slot), ...
    "RNTI", double(rnti), ...
    "UEIndex", double(ueIndex), ...
    "ServingCell", double(servingCell), ...
    "ChannelModel", char(string(sixgr.util.structGet(cfg, "channel.model", "AWGN"))), ...
    "FadingProfile", char(localResolveFadingProfile(cfg)));

harqContext = opt.HARQContext;
harqFromGrant = sixgr.util.structGet(grant, "HARQ", struct());
harqProcessKey = struct( ...
    "Direction", char(direction), ...
    "RNTI", double(rnti), ...
    "HARQProcess", localFirstFiniteScalar( ...
        sixgr.util.structGet(harqContext, "HARQProcess", []), ...
        sixgr.util.structGet(harqContext, "HarqID", []), ...
        sixgr.util.structGet(harqFromGrant, "HARQProcess", []), ...
        sixgr.util.structGet(harqFromGrant, "HarqID", []), NaN), ...
    "RV", localFirstFiniteScalar( ...
        sixgr.util.structGet(harqContext, "RV", []), ...
        sixgr.util.structGet(harqFromGrant, "RV", []), ...
        sixgr.util.structGet(grant, "RV", []), NaN), ...
    "NDI", logical(localFirstFiniteScalar( ...
        sixgr.util.structGet(harqContext, "NDI", []), ...
        sixgr.util.structGet(harqFromGrant, "NDI", []), 1)), ...
    "IsRetransmission", logical(sixgr.util.structGet(harqContext, "IsRetransmission", ...
        sixgr.util.structGet(harqFromGrant, "IsRetransmission", ...
        sixgr.util.structGet(grant, "IsRetransmission", false)))));

grantContextId = char(string(sixgr.util.structGet(grant, "GrantContextId", "")));
if strlength(string(grantContextId)) == 0
    grantContextId = localComposeContextId(direction, servingCell, ueIndex, rnti, frame, slot);
end

phyGrant = struct( ...
    "ContractVersion", "PHYGrant/v1", ...
    "IsFrozen", true, ...
    "Immutable", true, ...
    "MutationPolicy", "copy_only_recompute_forbidden_after_schedule", ...
    "Direction", char(direction), ...
    "GrantContextId", char(grantContextId), ...
    "PHYGrantId", char(grantContextId), ...
    "AntennaArchitecture", ant, ...
    "ResourceAllocation", resourceAllocation, ...
    "CodingLayout", codingLayout, ...
    "PrecodingState", prec, ...
    "NoiseContext", noiseContext, ...
    "ChannelStateKey", channelStateKey, ...
    "HARQProcessKey", harqProcessKey, ...
    "LegacyGrantSnapshot", grant);

phyGrant.DimensionContract = sixgr.phy.grant.assertPHYGrantDimensions( ...
    phyGrant, "freeze_phygrant");
end

function root = localChannelRoot(isUL)
if isUL
    root = "phy.pusch";
else
    root = "phy.pdsch";
end
end

function tf = localIsFrozenPHYGrant(value)
tf = isstruct(value) && ~isempty(fieldnames(value)) && ...
    logical(sixgr.util.structGet(value, "IsFrozen", false)) && ...
    isfield(value, "AntennaArchitecture") && ...
    isfield(value, "ResourceAllocation") && ...
    isfield(value, "CodingLayout") && ...
    isfield(value, "PrecodingState");
end

function tf = localFrozenPHYGrantHasConsistentDimensions(value)
tf = false;
if ~localIsFrozenPHYGrant(value)
    return;
end
ant = sixgr.util.structGet(value, "AntennaArchitecture", struct());
coding = sixgr.util.structGet(value, "CodingLayout", struct());
prec = sixgr.util.structGet(value, "PrecodingState", struct());
numPorts = round(double(sixgr.util.structGet(ant, "NumLogicalPorts", NaN)));
numLayers = round(double(sixgr.util.structGet(coding, "NumLayers", ...
    sixgr.util.structGet(ant, "NumLayers", NaN))));
W = sixgr.util.structGet(prec, "MatrixPorts", sixgr.util.structGet(prec, "Matrix", []));
if isempty(W) || ~isnumeric(W)
    return;
end
if ndims(W) > 2 && size(W, 3) == 1
    W = squeeze(W);
end
if ~ismatrix(W)
    return;
end
tf = isfinite(numPorts) && isfinite(numLayers) && numPorts >= numLayers && ...
    size(W, 1) == numPorts && size(W, 2) == numLayers;
end

function tf = localCanReuseFrozenPHYGrant(existing, cfg, direction, grant, opt)
tf = false;
if ~(localIsFrozenPHYGrant(existing) && localFrozenPHYGrantHasConsistentDimensions(existing))
    return;
end
if upper(string(sixgr.util.structGet(existing, "Direction", ""))) ~= upper(string(direction))
    return;
end

harqContext = sixgr.util.structGet(opt, "HARQContext", struct());
harqFromGrant = sixgr.util.structGet(grant, "HARQ", struct());
requestedIsRetx = logical(sixgr.util.structGet(harqContext, "IsRetransmission", ...
    sixgr.util.structGet(harqFromGrant, "IsRetransmission", ...
    sixgr.util.structGet(grant, "IsRetransmission", false))));
existingIsRetx = logical(sixgr.util.structGet(existing, "HARQProcessKey.IsRetransmission", false));
if requestedIsRetx ~= existingIsRetx
    return;
end

requestedRV = localFirstFiniteScalar( ...
    sixgr.util.structGet(harqContext, "RV", []), ...
    sixgr.util.structGet(harqFromGrant, "RV", []), ...
    sixgr.util.structGet(grant, "RV", []), NaN);
existingRV = localFirstFiniteScalar(sixgr.util.structGet(existing, "HARQProcessKey.RV", []), NaN);
if ~localScalarMatches(requestedRV, existingRV, 0)
    return;
end

requestedNDI = localFirstFiniteScalar( ...
    sixgr.util.structGet(harqContext, "NDI", []), ...
    sixgr.util.structGet(harqFromGrant, "NDI", []), NaN);
existingNDI = localFirstFiniteScalar(sixgr.util.structGet(existing, "HARQProcessKey.NDI", []), NaN);
if ~localScalarMatches(requestedNDI, existingNDI, 0)
    return;
end

requestedHarqProc = localFirstFiniteScalar( ...
    sixgr.util.structGet(harqContext, "HARQProcess", []), ...
    sixgr.util.structGet(harqContext, "HarqID", []), ...
    sixgr.util.structGet(harqFromGrant, "HARQProcess", []), ...
    sixgr.util.structGet(harqFromGrant, "HarqID", []), NaN);
existingHarqProc = localFirstFiniteScalar(sixgr.util.structGet(existing, "HARQProcessKey.HARQProcess", []), NaN);
if ~localScalarMatches(requestedHarqProc, existingHarqProc, 0)
    return;
end

isUL = direction == "UL";
root = localChannelRoot(isUL);
requestedPRBSet = localResolvePRBSet(cfg, grant, root);
existingPRBSet = double(sixgr.util.structGet(existing, "ResourceAllocation.PRBSet", []));
if ~localNumericVectorMatches(requestedPRBSet, existingPRBSet)
    return;
end

requestedSymbolAllocation = localResolveSymbolAllocation(cfg, grant, root);
existingSymbolAllocation = double(sixgr.util.structGet(existing, "ResourceAllocation.SymbolAllocation", []));
if ~localNumericVectorMatches(requestedSymbolAllocation, existingSymbolAllocation)
    return;
end

requestedNumLayers = localPositiveInteger(localFirstFiniteScalar( ...
    sixgr.util.structGet(grant, "NumLayers", []), ...
    sixgr.util.structGet(grant, "Layers", []), ...
    sixgr.util.structGet(cfg, root + ".numLayers", []), ...
    sixgr.util.structGet(cfg, root + ".nLayers", []), 1), 1);
existingNumLayers = localFirstFiniteScalar(sixgr.util.structGet(existing, "CodingLayout.NumLayers", []), NaN);
if ~localScalarMatches(requestedNumLayers, existingNumLayers, 0)
    return;
end

requestedModulation = char(string(localFirstNonempty( ...
    sixgr.util.structGet(grant, "Modulation", ""), ...
    sixgr.util.structGet(cfg, root + ".modulation", "QPSK"))));
existingModulation = char(string(sixgr.util.structGet(existing, "CodingLayout.Modulation", "")));
if ~localTextMatches(requestedModulation, existingModulation)
    return;
end

requestedTargetCodeRate = localFirstFiniteScalar( ...
    sixgr.util.structGet(grant, "TargetCodeRate", []), ...
    sixgr.util.structGet(cfg, root + ".codeRate", []), NaN);
existingTargetCodeRate = localFirstFiniteScalar(sixgr.util.structGet(existing, "CodingLayout.TargetCodeRate", []), NaN);
if ~localScalarMatches(requestedTargetCodeRate, existingTargetCodeRate, 1e-12)
    return;
end

requestedTBSBits = localFirstFiniteScalar( ...
    sixgr.util.structGet(grant, "TBSBits", []), ...
    sixgr.util.structGet(grant, "TransportBlockSize", []), ...
    sixgr.util.structGet(grant, "TBSize_bits", []), NaN);
existingTBSBits = localFirstFiniteScalar(sixgr.util.structGet(existing, "CodingLayout.TBSBits", []), NaN);
if ~localScalarMatches(requestedTBSBits, existingTBSBits, 0)
    return;
end

requestedXOverhead = localFirstFiniteScalar( ...
    sixgr.util.structGet(grant, "XOverhead", []), ...
    sixgr.util.structGet(cfg, root + ".xOverhead", []), 0);
existingXOverhead = localFirstFiniteScalar(sixgr.util.structGet(existing, "CodingLayout.XOverhead", []), NaN);
if ~localScalarMatches(requestedXOverhead, existingXOverhead, 1e-12)
    return;
end

tf = true;
end

function tf = localScalarMatches(requested, actual, tol)
if nargin < 3
    tol = 0;
end
tf = true;
if ~(isscalar(requested) && isfinite(double(requested)))
    return;
end
tf = isscalar(actual) && isfinite(double(actual)) && abs(double(requested) - double(actual)) <= tol;
end

function tf = localNumericVectorMatches(requested, actual)
requested = double(requested(:).');
actual = double(actual(:).');
requested = requested(isfinite(requested));
actual = actual(isfinite(actual));
if isempty(requested)
    tf = true;
    return;
end
tf = numel(requested) == numel(actual) && all(abs(requested - actual) <= 1e-9);
end

function tf = localTextMatches(requested, actual)
requested = upper(strtrim(string(requested)));
actual = upper(strtrim(string(actual)));
if strlength(requested) < 1
    tf = true;
    return;
end
tf = strlength(actual) >= 1 && requested == actual;
end

function prbSet = localResolvePRBSet(cfg, grant, root)
prbSet = sixgr.util.structGet(grant, "PRBSet", []);
if isempty(prbSet)
    prbStart = localFirstFiniteScalar(sixgr.util.structGet(grant, "PRBStart", []), NaN);
    prbCount = localFirstFiniteScalar( ...
        sixgr.util.structGet(grant, "AllocatedPRBCount", []), ...
        sixgr.util.structGet(grant, "PRBCount", []), ...
        sixgr.util.structGet(grant, "PRBs", []), NaN);
    if isfinite(prbStart) && isfinite(prbCount) && prbCount >= 1
        prbSet = round(prbStart):(round(prbStart) + round(prbCount) - 1);
    end
end
if isempty(prbSet)
    prbSet = sixgr.util.structGet(cfg, root + ".prbSet", []);
end
if isempty(prbSet)
    nSizeGrid = localFirstFiniteScalar(sixgr.util.structGet(cfg, "phy.carrier.NSizeGrid", []), 1);
    prbSet = 0:(max(1, round(nSizeGrid)) - 1);
end
prbSet = localExpandPRBSet(prbSet);
if isempty(prbSet)
    error("sixgr:phy:grant:EmptyPRBSet", "PHYGrant requires a non-empty PRBSet.");
end
end

function prbSet = localExpandPRBSet(raw)
raw = double(raw(:).');
raw = raw(isfinite(raw) & raw >= 0);
if isempty(raw)
    prbSet = [];
    return;
end
if numel(raw) == 2 && raw(2) > raw(1)
    prbSet = round(raw(1)):round(raw(2));
else
    prbSet = unique(round(raw), "stable");
end
end

function symbolAllocation = localResolveSymbolAllocation(cfg, grant, root)
symbolAllocation = sixgr.util.structGet(grant, "SymbolAllocation", []);
if isempty(symbolAllocation)
    symbolAllocation = sixgr.util.structGet(cfg, root + ".symbolAllocation", [0 14]);
end
symbolAllocation = double(symbolAllocation(:).');
if numel(symbolAllocation) < 2 || ~all(isfinite(symbolAllocation(1:2)))
    error("sixgr:phy:grant:BadSymbolAllocation", ...
        "PHYGrant requires SymbolAllocation [start numSymbols].");
end
symbolAllocation = round(symbolAllocation(1:2));
if symbolAllocation(1) < 0 || symbolAllocation(2) < 1
    error("sixgr:phy:grant:BadSymbolAllocation", ...
        "Invalid SymbolAllocation [%d %d].", symbolAllocation(1), symbolAllocation(2));
end
end

function [ant, prec] = localResolveAntennaAndPrecoding(cfg, grant, direction, numLayers, numCodewords)
isUL = direction == "UL";
if isUL
    txEntity = "UE";
    rxEntity = "gNB";
    numElements = localPositiveInteger(localFirstFiniteScalar( ...
        sixgr.util.structGet(grant, "NumElements", []), ...
        sixgr.util.structGet(grant, "TxElements", []), ...
        sixgr.util.structGet(cfg, "antenna.ue.numElements", []), ...
        sixgr.util.structGet(cfg, "scenario.ue.nTxAnt", []), ...
        sixgr.util.structGet(cfg, "mimo.ue_n_tx_ant", []), ...
        sixgr.util.structGet(cfg, "phy.pusch.NumAntennaPorts", []), 1), 1);
    numRx = localPositiveInteger(localFirstFiniteScalar( ...
        sixgr.util.structGet(grant, "NumRxAntennas", []), ...
        sixgr.util.structGet(grant, "RxAntennas", []), ...
        sixgr.util.structGet(cfg, "antenna.bs.numElements", []), ...
        sixgr.util.structGet(cfg, "scenario.bs.nRxAnt", []), ...
        sixgr.util.structGet(cfg, "channel.ul.nRxAnt", []), ...
        sixgr.util.structGet(cfg, "phy.ul.nRxAnt", []), ...
        sixgr.util.structGet(cfg, "scenario.bs.nTxAnt", []), numLayers), numLayers);
    logicalPorts = localPositiveInteger(localFirstFiniteScalar( ...
        sixgr.util.structGet(grant, "NumLogicalPorts", []), ...
        sixgr.util.structGet(grant, "PortCount", []), ...
        sixgr.util.structGet(grant, "PrecodingNumPorts", []), ...
        sixgr.util.structGet(cfg, "phy.pusch.NumAntennaPorts", []), ...
        sixgr.util.structGet(cfg, "phy.pusch.numPorts", []), ...
        sixgr.util.structGet(cfg, "phy.pusch.nPorts", []), ...
        sixgr.util.structGet(grant, "NumTxAnt", []), numElements), numLayers);
    logicalPorts = min(max(logicalPorts, numLayers), max(numElements, numLayers));
    numWaveformColumns = logicalPorts;
    matrixPorts = localRectIdentity(logicalPorts, numLayers);
    active = logical(sixgr.util.structGet(grant, "PrecodingActive", false));
    mode = localFirstNonempty(sixgr.util.structGet(grant, "PrecodingMode", ""), "ul_direct_mapping");
    source = localFirstNonempty(sixgr.util.structGet(grant, "PrecoderSource", ""), "ul_frozen_logical_ports");
    stage = localFirstNonempty(sixgr.util.structGet(grant, "PrecodingApplicationStage", ""), "nrPUSCH_native_or_direct_mapping");
else
    txEntity = "gNB";
    rxEntity = "UE";
    wRaw = localFirstMatrix( ...
        sixgr.util.structGet(grant, "PrecodingMatrix", []), ...
        sixgr.util.structGet(cfg, "phy.pdsch.precoding.matrix", []), ...
        sixgr.util.structGet(cfg, "phy.pdsch.precodingMatrix", []), ...
        sixgr.util.structGet(cfg, "phy.pdsch.W", []));
    numElements = localPositiveInteger(localFirstFiniteScalar( ...
        sixgr.util.structGet(grant, "NumElements", []), ...
        sixgr.util.structGet(grant, "TxElements", []), ...
        sixgr.util.structGet(cfg, "antenna.bs.numElements", []), ...
        sixgr.util.structGet(cfg, "scenario.bs.nTxAnt", []), ...
        sixgr.util.structGet(cfg, "mimo.n_tx_ant", []), ...
        sixgr.util.structGet(cfg, "channel.nTxAnt", []), ...
        sixgr.util.structGet(cfg, "phy.nTxAnt", []), numLayers), numLayers);
    numRx = localPositiveInteger(localFirstFiniteScalar( ...
        sixgr.util.structGet(grant, "NumRxAntennas", []), ...
        sixgr.util.structGet(grant, "RxAntennas", []), ...
        sixgr.util.structGet(cfg, "antenna.ue.numElements", []), ...
        sixgr.util.structGet(cfg, "scenario.ue.nRxAnt", []), ...
        sixgr.util.structGet(cfg, "mimo.n_rx_ant", []), ...
        sixgr.util.structGet(cfg, "channel.nRxAnt", []), ...
        sixgr.util.structGet(cfg, "phy.nRxAnt", []), numLayers), numLayers);
    logicalPorts = localResolveDLLogicalPortCount(cfg, grant, numLayers);
    logicalPorts = min(max(logicalPorts, numLayers), max(numElements, numLayers));
    matrixPortCount = localMatrixPortCount(wRaw, numLayers);
    matrixSourceOverride = "";
    inputMatrixUsed = false;
    if isempty(wRaw)
        matrixPorts = localRectIdentity(logicalPorts, numLayers);
        matrixSourceOverride = "frozen_identity_ports";
    elseif isfinite(matrixPortCount) && round(double(matrixPortCount)) == logicalPorts
        matrixPorts = localNormalizeDLMatrix(wRaw, logicalPorts, numLayers);
        inputMatrixUsed = true;
    elseif isfinite(matrixPortCount) && matrixPortCount > logicalPorts && ~localDLHybridElementDomainEnabled(cfg)
        [matrixPorts, matrixSourceOverride] = localResolveDLLogicalPrecoder(cfg, grant, numLayers, logicalPorts);
    else
        matrixPorts = localNormalizeDLMatrix(wRaw, logicalPorts, numLayers);
        inputMatrixUsed = true;
    end
    numWaveformColumns = logicalPorts;
    active = logicalPorts > 1 || numLayers > 1 || inputMatrixUsed;
    mode = localFirstNonempty(sixgr.util.structGet(grant, "PrecodingMode", ""), ...
        localTernary(active, "explicit-wideband", "siso-bypass"));
    source = localFirstNonempty(matrixSourceOverride, sixgr.util.structGet(grant, "PrecoderSource", ""), ...
        localTernary(inputMatrixUsed, "frozen_explicit_matrix", "frozen_identity_ports"));
    stage = localFirstNonempty(sixgr.util.structGet(grant, "PrecodingApplicationStage", ""), ...
        localTernary(active, "nrPDSCHPrecode_before_RE_mapping", "none"));
end

ant = struct( ...
    "Direction", char(direction), ...
    "TxEntity", char(txEntity), ...
    "RxEntity", char(rxEntity), ...
    "NumElements", double(numElements), ...
    "NumPanels", double(localPositiveInteger(localFirstFiniteScalar( ...
        sixgr.util.structGet(grant, "NumPanels", []), 1), 1)), ...
    "NumRFChains", double(localPositiveInteger(localFirstFiniteScalar( ...
        sixgr.util.structGet(grant, "NumRFChains", []), logicalPorts), logicalPorts)), ...
    "NumTxRUs", double(localPositiveInteger(localFirstFiniteScalar( ...
        sixgr.util.structGet(grant, "NumTxRUs", []), logicalPorts), logicalPorts)), ...
    "NumLogicalPorts", double(logicalPorts), ...
    "NumLayers", double(numLayers), ...
    "NumCodewords", double(numCodewords), ...
    "NumWaveformColumns", double(numWaveformColumns), ...
    "NumRxAntennas", double(numRx), ...
    "NumTxAntennas", double(numWaveformColumns));

prec = struct( ...
    "Active", logical(active), ...
    "Mode", char(string(mode)), ...
    "Source", char(string(source)), ...
    "ApplicationStage", char(string(stage)), ...
    "NumPorts", double(logicalPorts), ...
    "NumLayers", double(numLayers), ...
    "NumCodewords", double(numCodewords), ...
    "Matrix", double(matrixPorts), ...
    "MatrixPorts", double(matrixPorts), ...
    "MatrixRows", double(size(matrixPorts, 1)), ...
    "MatrixCols", double(size(matrixPorts, 2)), ...
    "WidebandOnly", true, ...
    "PMI", localFirstFiniteScalar(sixgr.util.structGet(grant, "PMI", []), ...
        sixgr.util.structGet(grant, "AppliedPrecoderPMI", []), NaN), ...
    "TPMI", localFirstFiniteScalar(sixgr.util.structGet(grant, "TPMI", []), ...
        sixgr.util.structGet(grant, "PMI", []), NaN), ...
    "BeamIndices", double(sixgr.util.structGet(grant, "BeamIndices", [])));
end

function W = localNormalizeDLMatrix(Wraw, nPorts, nLayers)
if isempty(Wraw)
    W = localRectIdentity(nPorts, nLayers);
    return;
end
Wraw = double(Wraw);
if ndims(Wraw) > 2 && size(Wraw, 3) == 1
    Wraw = squeeze(Wraw);
end
if ~ismatrix(Wraw)
    error("sixgr:phy:grant:BadPrecodingMatrix", ...
        "PHYGrant DL PrecodingState.Matrix must be a 2-D matrix.");
end
if size(Wraw, 2) == nLayers
    W = Wraw;
elseif size(Wraw, 1) == nLayers
    W = Wraw.';
elseif size(Wraw, 2) > nLayers && size(Wraw, 1) >= nLayers
    W = Wraw(:, 1:nLayers);
else
    error("sixgr:phy:grant:BadPrecodingMatrix", ...
        "DL precoding matrix must be Nports-by-Nlayers or transpose. Got %dx%d for %d layer(s).", ...
        size(Wraw, 1), size(Wraw, 2), nLayers);
end
end

function nPorts = localResolveDLLogicalPortCount(cfg, grant, nLayers)
nLayers = max(1, round(double(nLayers)));
configuredPorts = localFirstFiniteScalar( ...
    sixgr.util.structGet(cfg, "phy.maxDLLayers", []), ...
    sixgr.util.structGet(cfg, "phy.pdsch.maxLayers", []), ...
    sixgr.util.structGet(cfg, "phy.pdsch.dmrs.nPorts", []), ...
    sixgr.util.structGet(cfg, "phy.pdsch.numPorts", []), ...
    sixgr.util.structGet(cfg, "phy.pdsch.nPorts", []), ...
    sixgr.util.structGet(cfg, "phy.pdsch.NumAntennaPorts", []), ...
    sixgr.util.structGet(cfg, "phy.pdsch.numAntennaPorts", []), ...
    sixgr.util.structGet(cfg, "phy.pdsch.numLayers", []), ...
    sixgr.util.structGet(cfg, "phy.pdsch.nLayers", []), NaN);
if isfinite(configuredPorts)
    if configuredPorts <= localMaxNRLogicalPDSCHPorts()
        nPorts = localPositiveInteger(configuredPorts, nLayers);
        return;
    end
end

grantPorts = localFirstFiniteScalar( ...
    sixgr.util.structGet(grant, "NumLogicalPorts", []), ...
    sixgr.util.structGet(grant, "PortCount", []), NaN);
if isfinite(grantPorts) && grantPorts <= localMaxNRLogicalPDSCHPorts()
    nPorts = localPositiveInteger(grantPorts, nLayers);
    return;
end

nPorts = nLayers;
end

function nPorts = localMaxNRLogicalPDSCHPorts()
% Prevent element-array counts such as 64 from becoming logical NR waveform
% ports unless the scenario explicitly requests that logical port count.
nPorts = 32;
end

function [W, source] = localResolveDLLogicalPrecoder(cfg, grant, nLayers, nPorts)
source = "frozen_logical_identity_ports_from_element_domain_matrix";
W = localRectIdentity(nPorts, nLayers);
pmi = localFirstFiniteScalar( ...
    sixgr.util.structGet(grant, "AppliedPrecoderPMI", []), ...
    sixgr.util.structGet(grant, "PMI", []), ...
    sixgr.util.structGet(grant, "TPMI", []), ...
    sixgr.util.structGet(cfg, "phy.pdsch.PMI", []), ...
    sixgr.util.structGet(cfg, "phy.pdsch.pmi", []), NaN);
mode = localFirstNonempty( ...
    sixgr.util.structGet(grant, "AppliedPrecoderCodebookMode", ""), ...
    sixgr.util.structGet(grant, "PMICodebookMode", ""), ...
    sixgr.util.structGet(cfg, "phy.csi.pmiCodebookMode", ""), ...
    "type1_su_mimo");
try
    [candidates, ~] = sixgr.phy.dl.pmiCodebookCandidates(cfg, nLayers, nPorts, "Mode", mode);
    if isempty(candidates)
        return;
    end
    idx = 1;
    if isfinite(pmi)
        pmi0 = round(double(pmi));
        if pmi0 >= 0 && pmi0 < numel(candidates)
            idx = pmi0 + 1;
        end
    end
    Wcand = double(candidates(idx).W);
    if isequal(size(Wcand), [nPorts nLayers])
        W = Wcand;
        source = "frozen_logical_pmi_codebook_from_element_domain_matrix";
    end
catch
    % Keep the grant executable with a logical-port identity. The input
    % element-domain matrix cannot define NR PDSCH waveform ports unless
    % explicit hybrid element-domain waveform generation is enabled.
end
end

function tf = localDLHybridElementDomainEnabled(cfg)
tf = logical(sixgr.util.structGet(cfg, "phy.pdsch.hybridBeamformingEnabled", ...
    sixgr.util.structGet(cfg, "phy.pdsch.hybridBeamforming", ...
    sixgr.util.structGet(cfg, "rf.bs.hybridBeamformingEnabled", ...
    sixgr.util.structGet(cfg, "rf.bs.hybridBeamforming", ...
    sixgr.util.structGet(cfg, "antenna.bs.hybridBeamformingEnabled", ...
    sixgr.util.structGet(cfg, "antenna.bs.hybridBeamforming", ...
    sixgr.util.structGet(cfg, "phy.beamManagement.hybridBeamformingEnabled", false))))))));
end

function W = localRectIdentity(nPorts, nLayers)
W = zeros(max(1, nPorts), max(1, nLayers));
for i = 1:min(size(W, 1), size(W, 2))
    W(i, i) = 1;
end
end

function ports = localMatrixPortCount(W, nLayers)
ports = NaN;
if isempty(W) || ~isnumeric(W)
    return;
end
if ndims(W) > 2 && size(W, 3) == 1
    W = squeeze(W);
end
if ~ismatrix(W)
    return;
end
if size(W, 2) == nLayers
    ports = double(size(W, 1));
elseif size(W, 1) == nLayers
    ports = double(size(W, 2));
else
    ports = double(size(W, 1));
end
end

function W = localFirstMatrix(varargin)
W = [];
for i = 1:nargin
    raw = varargin{i};
    if isnumeric(raw) && ~isempty(raw)
        W = raw;
        return;
    end
end
end

function profile = localResolveFadingProfile(cfg)
model = upper(string(sixgr.util.structGet(cfg, "channel.model", "")));
if startsWith(model, "TDL")
    profile = string(sixgr.util.structGet(cfg, "channel.tdlProfile", model));
elseif startsWith(model, "CDL")
    profile = string(sixgr.util.structGet(cfg, "channel.cdlProfile", model));
else
    profile = model;
end
end

function value = localFirstFiniteScalar(varargin)
value = NaN;
for i = 1:nargin
    raw = varargin{i};
    if isempty(raw) || ~(isnumeric(raw) || islogical(raw))
        continue;
    end
    raw = double(raw(:));
    raw = raw(isfinite(raw));
    if ~isempty(raw)
        value = raw(1);
        return;
    end
end
end

function value = localPositiveInteger(value, fallback)
if ~(isscalar(value) && isfinite(double(value)) && double(value) >= 1)
    value = fallback;
end
value = max(1, round(double(value)));
end

function value = localFirstNonempty(varargin)
value = "";
for i = 1:nargin
    raw = string(varargin{i});
    raw = raw(~ismissing(raw));
    if ~isempty(raw) && strlength(strtrim(raw(1))) > 0
        value = raw(1);
        return;
    end
end
end

function out = localTernary(tf, a, b)
if logical(tf)
    out = a;
else
    out = b;
end
end

function token = localComposeContextId(direction, servingCell, ueIndex, rnti, frame, slot)
token = sprintf('%s|cell=%s|ue=%s|rnti=%s|frame=%s|slot=%s', ...
    char(direction), localIntegerToken(servingCell), localIntegerToken(ueIndex), ...
    localIntegerToken(rnti), localIntegerToken(frame), localIntegerToken(slot));
end

function token = localIntegerToken(value)
value = round(double(value));
if ~(isscalar(value) && isfinite(value))
    token = "na";
else
    token = sprintf('%d', value);
end
end
