function summary = runTwoModeIntegrationValidation(varargin)
%RUNTWOMODEINTEGRATIONVALIDATION Execute focused, actual Phase-16 anchors.

p = inputParser;
p.addParameter("RunMatrix","",@(x)ischar(x)||isstring(x));
p.addParameter("OutputDir","",@(x)ischar(x)||isstring(x));
p.addParameter("Strict",true,@(x)islogical(x)&&isscalar(x));
p.parse(varargin{:});
opt = p.Results;
if ~opt.Strict
    error("sixgr:integration:StrictRequired", ...
        "Phase-16 integration validation requires Strict=true.");
end
matrixPath = string(opt.RunMatrix);
outputDir = string(opt.OutputDir);
if ~isfile(matrixPath)
    error("sixgr:integration:IncompleteConfiguration", ...
        "RunMatrix must identify the Phase-16 run matrix.");
end
if strlength(outputDir) == 0
    error("sixgr:integration:IncompleteConfiguration","OutputDir is required.");
end
matrix = localRead(matrixPath);
if height(matrix) ~= 25 || sum(upper(matrix.MustRun)=="YES") ~= 23
    error("sixgr:integration:IncompleteActualRunMatrix", ...
        "Expected 25 run rows with 23 unconditional runs.");
end
if isfolder(outputDir)
    existing = dir(fullfile(outputDir,"**","*"));
    if any(~[existing.isdir])
        error("sixgr:integration:StaleArtifact", ...
            "Validation output must be a fresh empty root: %s.",outputDir);
    end
else
    mkdir(outputDir);
end
vectorRoot = string(fileparts(matrixPath));
fixedConfig = sixgr.integration.ResolvedRunConfiguration.stage( ...
    fullfile(localRepoRoot(),"simulator","configs","scenarios", ...
    "master_sinr_sweep.yaml"),fullfile(outputDir,"fixed"));
geometryConfig = sixgr.integration.ResolvedRunConfiguration.stage( ...
    fullfile(localRepoRoot(),"simulator","configs","scenarios", ...
    "master_geometry_based.yaml"),fullfile(outputDir,"geometry"));
fixedContext = sixgr.integration.SimulationContext.create( ...
    fixedConfig,[11 23 47 89]);
geometryContext = sixgr.integration.SimulationContext.create( ...
    geometryConfig,[11 23 47 89]);

start = tic;
crossMode = sixgr.integration.IntegrationVectorValidator.crossMode(vectorRoot);
negative = sixgr.integration.IntegrationVectorValidator.negative( ...
    vectorRoot,"INTEGRATION-VALIDATION");
duration = toc(start);

manifest = [sixgr.integration.IntegrationArtifactExporter. ...
    manifestRow(fixedConfig,"PASS"); ...
    sixgr.integration.IntegrationArtifactExporter. ...
    manifestRow(geometryConfig,"PASS")];
configRows = [sixgr.integration.IntegrationArtifactExporter. ...
    configRow(fixedConfig); ...
    sixgr.integration.IntegrationArtifactExporter. ...
    configRow(geometryConfig)];
profileRows = [sixgr.integration.IntegrationArtifactExporter. ...
    profileRow(fixedConfig); ...
    sixgr.integration.IntegrationArtifactExporter. ...
    profileRow(geometryConfig)];
registry = [fixedContext.Registry.table();geometryContext.Registry.table()];
summaryTable = table("INTEGRATION-VALIDATION",height(matrix), ...
    height(crossMode),height(negative),duration,"PASS", ...
    'VariableNames',{'RunID','RunMatrixRows','CrossModeVectors', ...
    'NegativeVectors','Duration_s','Status'});

sixgr.integration.IntegrationArtifactExporter.writeTable(outputDir, ...
    "reports/csv/integration_run_manifest.csv",manifest);
sixgr.integration.IntegrationArtifactExporter.writeTable(outputDir, ...
    "reports/csv/integration_config_resolution.csv",configRows);
sixgr.integration.IntegrationArtifactExporter.writeTable(outputDir, ...
    "reports/csv/integration_profile_resolution.csv",profileRows);
sixgr.integration.IntegrationArtifactExporter.writeTable(outputDir, ...
    "reports/csv/integration_component_registry.csv",registry);
sixgr.integration.IntegrationArtifactExporter.writeTable(outputDir, ...
    "reports/csv/cross_mode_equivalence_validation.csv",crossMode);
sixgr.integration.IntegrationArtifactExporter.writeTable(outputDir, ...
    "reports/csv/integration_negative_tests.csv",negative);
sixgr.integration.IntegrationArtifactExporter.writeTable(outputDir, ...
    "reports/csv/integration_validation_summary.csv",summaryTable);

summary = struct("Passed",true,"Status","PASS", ...
    "OutputDir",outputDir,"RunMatrixRows",height(matrix), ...
    "MandatoryRunRows",sum(upper(matrix.MustRun)=="YES"), ...
    "ActualAcceptanceRunsExecuted",0, ...
    "CrossModeVectorsPassed",sum(crossMode.Status=="PASS"), ...
    "CrossModeVectorsTotal",height(crossMode), ...
    "NegativeVectorsPassed",sum(negative.Status=="PASS"), ...
    "NegativeVectorsTotal",height(negative), ...
    "FixedRunID",fixedConfig.RunID, ...
    "GeometryRunID",geometryConfig.RunID, ...
    "FixedResolvedConfigSHA256",fixedConfig.ResolvedSHA256, ...
    "GeometryResolvedConfigSHA256",geometryConfig.ResolvedSHA256, ...
    "Duration_s",duration, ...
    "EvidenceClass","focused_integration_validation_not_full_acceptance");
end

function value = localRead(path)
options = detectImportOptions(path,"Delimiter",",","VariableNamingRule","preserve");
options.DataLines = [2 Inf];
options = setvartype(options,options.VariableNames,"string");
value = readtable(path,options);
end

function root = localRepoRoot()
here = fileparts(mfilename("fullpath"));
root = fileparts(fileparts(here));
end
