classdef FilteredOFDMProfile
    %FILTEREDOFDMPROFILE Explicit non-normative filtered-OFDM definition.

    methods (Static)
        function profile = resolve(profileID,coefficients,matchedReceiver)
            profileID = string(profileID);
            if startsWith(profileID,"nr_rel19_")
                error("WAVEFORM:NormativeResearchMix", ...
                    "Filtered OFDM cannot be enabled under a strict NR profile.");
            end
            coefficients = double(coefficients(:));
            if isempty(coefficients) || any(~isfinite(coefficients)) || ...
                    sum(abs(coefficients))==0
                error("WAVEFORM:UnsupportedResearchCandidate", ...
                    "Filtered OFDM requires explicit finite FIR coefficients.");
            end
            coefficients = coefficients/sum(coefficients);
            profile = struct( ...
                "ProfileID",profileID, ...
                "Coefficients",coefficients, ...
                "CoefficientSHA256", ...
                    sixgr.phy.waveform.WaveformHash.numeric(coefficients), ...
                "GroupDelaySamples",(numel(coefficients)-1)/2, ...
                "MatchedReceiver",logical(matchedReceiver), ...
                "NormativeClaimAllowed",false);
        end
    end
end
