function snapshot=capturePUSCHChannelEstimate(rx)
% Compact actual pilot estimates, with the executed receiver clock/operator.
% No waveform regeneration, TX payload, fitted gain or independent H enters
% this capture. Failed CRCs retain the same measured pilot evidence.
refs=sixgr.phy.ul.puschChannelEstimateReferences(rx);
h=rx.ChannelEstimate;
shape=[size(h,1) size(h,2) size(h,3) size(h,4)];
[k,l,p]=ind2sub(shape([1 2 4]),double(refs.Indices(:)));
values=complex(zeros(numel(k),shape(3),'like',h));
for r=1:shape(3)
    values(:,r)=h(sub2ind(shape,k,l,repmat(r,size(k)),p));
end
assert(all(isfinite(values),'all') && ...
    isfield(rx,'ReceiverChannelOperator') && isfield(rx,'ReceiverOFDMInfo'), ...
    'sixgr:phy:ul:IncompleteChannelEstimateCapture', ...
    'Retain every actual pilot estimate and its executed receive operations.');
snapshot=struct('Contract',"PUSCH_pilot_channel_capture/v1", ...
    'GridShape',shape,'PilotIndices',refs.Indices,'PilotSymbols',refs.Symbols, ...
    'PilotChannelValues',values,'Carrier',rx.Carrier, ...
    'ReceiverOFDMInfo',rx.ReceiverOFDMInfo, ...
    'ReceiverChannelOperator',rx.ReceiverChannelOperator, ...
    'Source',refs.Source,'Domain',"effective_layer_channel", ...
    'ReferenceUsedByReceiver',false);
end
