classdef DCIContextFactory
    %DCICONTEXTFACTORY Build strict contexts from operator-owned control config.

    methods (Static)
        function context = fromRuntimeConfig(cfg, dciFormat)
            control = sixgr.util.structGet(cfg, "phy.pdcch.operatorControl", []);
            if isempty(control)
                error("sixgr:phy:pdcch:missing_dci_context", ...
                    "Runtime config does not carry phy.pdcch.operatorControl.");
            end
            context = sixgr.phy.pdcch.DCIContextFactory.fromOperatorControl( ...
                control, dciFormat);
        end

        function context = fromOperatorControl(control, dciFormat)
            if ~(isstruct(control) && isscalar(control))
                error("sixgr:phy:pdcch:missing_dci_context", ...
                    "Operator control configuration must be one scalar structure.");
            end
            strict = localRequired(control, "pdcch_strict");
            raw = localRequired(strict, "dci_context");
            fmt = sixgr.phy.pdcch.normalizeDCIFormat(dciFormat);
            formats = string(localRequired(control, "dci_formats"));
            for ii = 1:numel(formats)
                formats(ii) = sixgr.phy.pdcch.normalizeDCIFormat(formats(ii));
            end
            rnti = localRequired(strict, "rnti");
            searchSpaceType = upper(string(localRequired(control, "search_space_type")));
            if any(searchSpaceType == ["UE","UE_SPECIFIC"])
                searchSpaceType = "USS";
            elseif searchSpaceType == "COMMON"
                searchSpaceType = "CSS";
            end
            data = struct( ...
                "SpecRelease", string(localRequired(strict, "spec_release")), ...
                "SpecVersion", string(localRequired(strict, "spec_version")), ...
                "DCIFormat", fmt, ...
                "RNTIType", string(localRequired(rnti, "type")), ...
                "RNTIValue", double(localRequired(rnti, "value")), ...
                "SearchSpaceType", searchSpaceType, ...
                "SearchSpaceID", double(localRequired(raw, "search_space_id")), ...
                "CORESETID", double(localRequired(raw, "coreset_id")), ...
                "ControlServingCell", double(localRequired(raw, "control_serving_cell")), ...
                "ControlCarrier", double(localRequired(raw, "control_carrier")), ...
                "ControlBWP", double(localRequired(raw, "control_bwp")), ...
                "ScheduledServingCell", double(localRequired(raw, "scheduled_serving_cell")), ...
                "ScheduledCarrier", double(localRequired(raw, "scheduled_carrier")), ...
                "ScheduledBWP", double(localRequired(raw, "scheduled_bwp")), ...
                "InitialDLBWPSize", double(localRequired(raw, "initial_dl_bwp_size")), ...
                "InitialDLBWPStart", double(localRequired(raw, "initial_dl_bwp_start")), ...
                "ActiveDLBWPSize", double(localRequired(raw, "active_dl_bwp_size")), ...
                "ActiveDLBWPStart", double(localRequired(raw, "active_dl_bwp_start")), ...
                "InitialULBWPSize", double(localRequired(raw, "initial_ul_bwp_size")), ...
                "InitialULBWPStart", double(localRequired(raw, "initial_ul_bwp_start")), ...
                "ActiveULBWPSize", double(localRequired(raw, "active_ul_bwp_size")), ...
                "ActiveULBWPStart", double(localRequired(raw, "active_ul_bwp_start")), ...
                "FrequencyAllocationType", string(localRequired(raw, "frequency_allocation_type")), ...
                "DLTimeDomainAllocations", double(localRequired(raw, "dl_time_domain_allocations")), ...
                "ULTimeDomainAllocations", double(localRequired(raw, "ul_time_domain_allocations")), ...
                "CarrierIndicatorPresent", logical(localRequired(raw, "carrier_indicator_present")), ...
                "CarrierIndicatorWidth", double(localRequired(raw, "carrier_indicator_width")), ...
                "CarrierIndicatorValue", double(localRequired(raw, "carrier_indicator_value")), ...
                "BWPIndicatorPresent", logical(localRequired(raw, "bwp_indicator_present")), ...
                "BWPIndicatorWidth", double(localRequired(raw, "bwp_indicator_width")), ...
                "SULIndicatorPresent", logical(localRequired(raw, "sul_indicator_present")), ...
                "FrequencyHoppingEnabled", logical(localRequired(raw, "frequency_hopping_enabled")), ...
                "TransformPrecodingEnabled", logical(localRequired(raw, "transform_precoding_enabled")), ...
                "HARQProcessCount", double(localRequired(raw, "harq_process_count")), ...
                "DAIWidth", double(localRequired(raw, "dai_width")), ...
                "AntennaPortFieldWidth", double(localRequired(raw, "antenna_port_field_width")), ...
                "LayerCapability", double(localRequired(raw, "layer_capability")), ...
                "TCIPresent", logical(localRequired(raw, "tci_present")), ...
                "TCIWidth", double(localRequired(raw, "tci_width")), ...
                "ActiveTCIStateID", double(localRequired(raw, "active_tci_state_id")), ...
                "SRSResourceIndicatorWidth", double(localRequired(raw, "srs_resource_indicator_width")), ...
                "SRSRequestWidth", double(localRequired(raw, "srs_request_width")), ...
                "CSIRequestWidth", double(localRequired(raw, "csi_request_width")), ...
                "RateMatchIndicatorWidth", double(localRequired(raw, "rate_match_indicator_width")), ...
                "ZPCSIRSTriggerWidth", double(localRequired(raw, "zp_csirs_trigger_width")), ...
                "CBGFieldsPresent", logical(localRequired(raw, "cbg_fields_present")), ...
                "CBGTransmissionWidth", double(localRequired(raw, "cbg_transmission_width")), ...
                "CBGFlushWidth", double(localRequired(raw, "cbg_flush_width")), ...
                "DMRSSequenceInitializationPresent", logical(localRequired(raw, ...
                    "dmrs_sequence_initialization_present")), ...
                "MonitoredFormats", formats(:).', ...
                "ConfigurationEpoch", double(localRequired(raw, "configuration_epoch")), ...
                "ExecutionProfile", string(localRequired(strict, "execution_profile")), ...
                "ResearchClass", string(localRequired(strict, "research_class")), ...
                "LegacyCompatibility", false);
            context = sixgr.phy.pdcch.DCIContext(data);
        end
    end
end

function value = localRequired(source, name)
if ~(isstruct(source) && isscalar(source) && isfield(source, name))
    error("sixgr:phy:pdcch:missing_dci_context", ...
        "Operator PDCCH configuration is missing '%s'.", name);
end
value = source.(name);
if isempty(value)
    error("sixgr:phy:pdcch:missing_dci_context", ...
        "Operator PDCCH configuration field '%s' is empty.", name);
end
end
