classdef DecodedGrantMaterializer
    %DECODEDGRANTMATERIALIZER Sole strict dynamic grant authority.

    methods (Static)
        function assignment = materialize(decodedEvent, installedState)
            if ~isa(decodedEvent, "sixgr.phy.pdcch.DecodedDCIEvent")
                error("sixgr:phy:pdcch:decoded_event_required", ...
                    "Strict dynamic grant creation requires a DecodedDCIEvent.");
            end
            if ~(isstruct(installedState) && isscalar(installedState))
                error("sixgr:phy:pdcch:decoded_event_required", ...
                    "Installed RRC/MAC/HARQ state is required.");
            end
            required = ["ConfigurationEpoch","ActiveServingCell","ActiveCarrier", ...
                "ActiveDLBWP","ActiveULBWP","DLMCSTable","ULMCSTable", ...
                "ControlBWPContext","CrossCarrierControlContext","ControlBeamState"];
            missing = required(~isfield(installedState, cellstr(required)));
            if ~isempty(missing)
                error("sixgr:phy:pdcch:decoded_event_required", ...
                    "Installed state is missing: %s.", strjoin(missing, ", "));
            end
            event = decodedEvent.Data;
            if ~isa(installedState.ControlBWPContext, ...
                    "sixgr.phy.pdcch.ControlBWPContext") || ...
                    ~isa(installedState.CrossCarrierControlContext, ...
                    "sixgr.phy.pdcch.CrossCarrierControlContext") || ...
                    ~isa(installedState.ControlBeamState, ...
                    "sixgr.phy.pdcch.ControlBeamState")
                error("sixgr:phy:pdcch:decoded_event_required", ...
                    "Installed control BWP, cross-carrier and beam contexts must be validated objects.");
            end
            if double(event.ConfigurationEpoch) ~= double(installedState.ConfigurationEpoch)
                error("sixgr:phy:pdcch:stale_bwp_context", ...
                    "Decoded event epoch %d differs from installed epoch %d.", ...
                    event.ConfigurationEpoch, installedState.ConfigurationEpoch);
            end
            if double(event.ScheduledServingCell) ~= double(installedState.ActiveServingCell) || ...
                    double(event.ScheduledCarrier) ~= double(installedState.ActiveCarrier)
                error("sixgr:phy:pdcch:wrong_scheduled_carrier", ...
                    "Decoded scheduled serving-cell/carrier identity is not active.");
            end
            fields = event.ParsedFields;
            binding = installedState.ControlBWPContext.Data;
            identities = ["ControlServingCell","ControlCarrier","ControlBWP", ...
                "ScheduledServingCell","ScheduledCarrier","ScheduledBWP", ...
                "SearchSpaceID","CORESETID","ConfigurationEpoch"];
            for identityIndex = 1:numel(identities)
                identity = identities(identityIndex);
                if double(event.(identity)) ~= double(binding.(identity))
                    error("sixgr:phy:pdcch:stale_bwp_context", ...
                        "Decoded event %s=%d differs from installed binding %d.", ...
                        identity, event.(identity), binding.(identity));
                end
            end
            carrierIndicator = double(sixgr.util.structGet( ...
                fields, "carrier_indicator", 0));
            routedCarrier = installedState.CrossCarrierControlContext.resolve( ...
                carrierIndicator);
            if routedCarrier ~= double(event.ScheduledCarrier)
                error("sixgr:phy:pdcch:wrong_scheduled_carrier", ...
                    "Decoded carrier indicator routes to %d, not event carrier %d.", ...
                    routedCarrier, event.ScheduledCarrier);
            end
            installedState.ControlBeamState.validateForSlot(event.AbsoluteSlot);
            beam = installedState.ControlBeamState.Data;
            if double(event.TCIStateID) ~= double(beam.TCIStateID) || ...
                    double(event.BeamID) ~= double(beam.BeamID)
                error("sixgr:phy:pdcch:inactive_tci_state", ...
                    "Decoded TCI/beam identity is not the active measured control beam.");
            end
            if startsWith(string(event.DCIFormat), "1_")
                direction = "DL";
                activeBWP = double(installedState.ActiveDLBWP);
                tableName = string(installedState.DLMCSTable);
            else
                direction = "UL";
                activeBWP = double(installedState.ActiveULBWP);
                tableName = string(installedState.ULMCSTable);
            end
            if double(event.ScheduledBWP) ~= activeBWP
                error("sixgr:phy:pdcch:stale_bwp_context", ...
                    "Decoded scheduled BWP %d is not active BWP %d.", ...
                    event.ScheduledBWP, activeBWP);
            end
            mcs = double(fields.mcs);
            profile = sixgr.link.resolveMCSProfile(tableName, mcs);
            if ~(isstruct(profile) && logical(sixgr.util.structGet(profile, "Valid", false)))
                error("sixgr:phy:pdcch:field_out_of_range", ...
                    "MCS %d is invalid for installed table %s.", mcs, tableName);
            end
            payload = struct( ...
                "Direction", direction, ...
                "GrantType", string(fields.grant_type), ...
                "DCIFormat", string(event.DCIFormat), ...
                "DecodedDCIEventID", decodedEvent.EventID, ...
                "RNTIType", string(event.RNTIType), ...
                "RNTIValue", double(event.RNTIValue), ...
                "ServingCell", double(event.ScheduledServingCell), ...
                "Carrier", double(event.ScheduledCarrier), ...
                "BWP", double(event.ScheduledBWP), ...
                "PRBStart", double(fields.prb_start), ...
                "NumPRB", double(fields.num_prb), ...
                "SymbolStart", double(fields.symbol_start), ...
                "NumSymbols", double(fields.num_symbols), ...
                "TimingOffsetSlots", double(fields.timing_offset_slots), ...
                "MCS", mcs, ...
                "MCSTable", tableName, ...
                "Modulation", string(profile.Modulation), ...
                "TargetCodeRate", double(profile.TargetCodeRate), ...
                "HARQProcess", double(fields.harq_process), ...
                "NDI", double(fields.ndi), ...
                "RV", double(fields.rv), ...
                "ConfigurationEpoch", double(event.ConfigurationEpoch), ...
                "ContextDigest", string(event.ContextDigest), ...
                "Authority", "decoded_dci_event_plus_installed_rrc_mac_harq_state", ...
                "TBSBits", NaN, ...
                "TBSCalcSource", "not_materialized_without_data_channel_allocation_math");
            assignment = payload;
            assignment.AssignmentDigest = string(sixgr.rrc.asn1.asn1SHA256Hex(uint8( ...
                unicode2native(jsonencode(orderfields(payload)), "UTF-8"))));
            assignment.Valid = true;
            assignment.Status = "PASS";
        end
    end
end
