classdef PDCCHSpecificationProfile
    %PDCCHSPECIFICATIONPROFILE Release-pinned strict PDCCH invariants.

    properties (Constant)
        ProfileId = "nr_release18_pdcch_strict"
        Release = "Release-18"
        TS38211Version = "18.8.0"
        TS38212Version = "18.8.0"
        TS38213Version = "18.8.0"
        TS38214Version = "18.8.0"
        TS38321Version = "18.8.0"
        TS38331Version = "18.8.0"
        AggregationLevels = [1 2 4 8 16]
        REGPerCCE = 6
        DMRSREPerREG = 3
        DataREPerREG = 9
        BitsPerCCE = 108
        Modulation = "QPSK"
        CRCPolynomial = "CRC24C"
        CRCLength = 24
    end

    methods (Static)
        function profile = describe()
            profile = struct( ...
                "ProfileId", sixgr.phy.pdcch.PDCCHSpecificationProfile.ProfileId, ...
                "Release", sixgr.phy.pdcch.PDCCHSpecificationProfile.Release, ...
                "TS38211Version", sixgr.phy.pdcch.PDCCHSpecificationProfile.TS38211Version, ...
                "TS38212Version", sixgr.phy.pdcch.PDCCHSpecificationProfile.TS38212Version, ...
                "TS38213Version", sixgr.phy.pdcch.PDCCHSpecificationProfile.TS38213Version, ...
                "TS38214Version", sixgr.phy.pdcch.PDCCHSpecificationProfile.TS38214Version, ...
                "TS38321Version", sixgr.phy.pdcch.PDCCHSpecificationProfile.TS38321Version, ...
                "TS38331Version", sixgr.phy.pdcch.PDCCHSpecificationProfile.TS38331Version, ...
                "AggregationLevels", sixgr.phy.pdcch.PDCCHSpecificationProfile.AggregationLevels, ...
                "REGPerCCE", sixgr.phy.pdcch.PDCCHSpecificationProfile.REGPerCCE, ...
                "DMRSREPerREG", sixgr.phy.pdcch.PDCCHSpecificationProfile.DMRSREPerREG, ...
                "DataREPerREG", sixgr.phy.pdcch.PDCCHSpecificationProfile.DataREPerREG, ...
                "BitsPerCCE", sixgr.phy.pdcch.PDCCHSpecificationProfile.BitsPerCCE, ...
                "Modulation", sixgr.phy.pdcch.PDCCHSpecificationProfile.Modulation, ...
                "CRCPolynomial", sixgr.phy.pdcch.PDCCHSpecificationProfile.CRCPolynomial);
        end

        function E = encodedBits(aggregationLevel)
            aggregationLevel = double(aggregationLevel);
            if ~(isscalar(aggregationLevel) && ...
                    ismember(aggregationLevel, ...
                    sixgr.phy.pdcch.PDCCHSpecificationProfile.AggregationLevels))
                error("sixgr:phy:pdcch:invalid_aggregation_level", ...
                    "AggregationLevel must be exactly one of 1, 2, 4, 8 or 16.");
            end
            E = sixgr.phy.pdcch.PDCCHSpecificationProfile.BitsPerCCE * aggregationLevel;
        end
    end
end
