function context = resolveCandidateContext(carrier, pdcch, aggregationLevel, candidateIndex)
%RESOLVECANDIDATECONTEXT CCE lineage of a received search-space hypothesis.
% Inputs are the monitored carrier/search space and the receiver-selected
% AL and zero-based candidate ordinal, not the scheduled TX candidate.
% TS 38.213 10.1 uses the slot within a radio frame for the USS recurrence.
validateattributes(aggregationLevel,{'numeric'},{'scalar','finite','integer','positive'});
validateattributes(candidateIndex,{'numeric'},{'scalar','finite','integer','nonnegative'});
levels=[1 2 4 8 16];
level=find(levels==aggregationLevel,1);
assert(~isempty(level),'sixgr:phy:pdcch:InvalidReceivedAggregationLevel', ...
    'Received aggregation level must be 1, 2, 4, 8 or 16.');
space=pdcch.SearchSpace;
core=pdcch.CORESET;
assert(space.CORESETID==core.CORESETID, ...
    'sixgr:phy:pdcch:ReceivedCORESETMismatch', ...
    'The monitored search space must reference the actual CORESET.');
counts=double(space.NumCandidates);
assert(candidateIndex<counts(level),'sixgr:phy:pdcch:ReceivedCandidateOutOfRange', ...
    'The received candidate ordinal is outside the monitored aggregation level.');
kind="CSS";
if strcmpi(space.SearchSpaceType,'ue'), kind="USS"; end
slotWithinFrame=mod(double(carrier.NSlot),double(carrier.SlotsPerFrame));
% nrPDCCHResources/nrPDCCHSpace implement nCI=0. Do not introduce an
% independent carrier-indicator shift into metadata for those resources.
enumerated=sixgr.phy.pdcch.PDCCHCandidateEnumerator.enumerate(kind, ...
    double(core.NCCE),double(aggregationLevel),counts(level), ...
    double(space.CORESETID),double(pdcch.RNTI),slotWithinFrame,0);
context=struct('FirstCCE',double(enumerated.Rows(candidateIndex+1).FirstCCE), ...
    'NumCCE',double(core.NCCE),'AggregationLevel',double(aggregationLevel), ...
    'CandidateIndex',double(candidateIndex),'SlotWithinFrame',slotWithinFrame, ...
    'Source',"received_hypothesis_38_213_search_space_cce_mapping");
assert(context.FirstCCE+context.AggregationLevel<=context.NumCCE, ...
    'sixgr:phy:pdcch:ReceivedCandidateCapacityMismatch', ...
    'Received CCEs must fit the actual CORESET.');
end
