classdef ULPTRSDMRSAssociation
    %ULPTRSDMRSASSOCIATION DCI 0_1 UL PT-RS/DM-RS port binding.
    %
    % For the currently supported single-UL-PT-RS-port, non-transform-
    % precoded connected profile, TS 38.212 clause 7.3.1.1.2 assigns a
    % two-bit codepoint when PT-RS is configured and maxRank is above one.
    % The codepoint selects the ordinal scheduled DM-RS port; it is not an
    % absolute antenna-port identifier.

    methods (Static)
        function width = widthFromRuntime(cfg, maxRank)
            enabled = logical(sixgr.util.structGet(cfg, ...
                "phy.pusch.enablePTRS", false));
            transformPrecoding = logical(sixgr.util.structGet(cfg, ...
                "phy.pusch.transformPrecoding", false));
            validateattributes(maxRank, {'numeric'}, ...
                {'scalar','finite','integer','positive'});
            if enabled && ~transformPrecoding && maxRank > 1
                width = 2;
            else
                width = 0;
            end
        end

        function value = encode(dmrsPortSet, ptrsPortSet, width)
            dmrsPortSet = localPortVector(dmrsPortSet, ...
                "sixgr:phy:pdcch:InvalidPTRSDMRSAssociation");
            ptrsPortSet = localPortVector(ptrsPortSet, ...
                "sixgr:phy:pdcch:InvalidPTRSDMRSAssociation");
            validateattributes(width, {'numeric'}, ...
                {'scalar','finite','integer','nonnegative'});
            if width == 0
                assert(numel(dmrsPortSet) == 1 && ...
                    isequal(ptrsPortSet, dmrsPortSet(1)), ...
                    'sixgr:phy:pdcch:InvalidPTRSDMRSAssociation', ...
                    ['A zero-bit PT-RS/DM-RS association is valid only ' ...
                     'for the sole scheduled DM-RS port.']);
                value = 0;
                return;
            end
            assert(width == 2 && numel(ptrsPortSet) == 1, ...
                'sixgr:phy:pdcch:InvalidPTRSDMRSAssociation', ...
                'The installed profile supports one UL PT-RS port and a two-bit association.');
            ordinal = find(dmrsPortSet == ptrsPortSet, 1);
            assert(isscalar(ordinal) && ordinal <= 4, ...
                'sixgr:phy:pdcch:InvalidPTRSDMRSAssociation', ...
                'PT-RS must select one of the first four scheduled DM-RS ports.');
            value = ordinal - 1;
        end

        function ptrsPortSet = decode(value, dmrsPortSet, width)
            dmrsPortSet = localPortVector(dmrsPortSet, ...
                "sixgr:phy:pdcch:InvalidPTRSDMRSAssociation");
            validateattributes(width, {'numeric'}, ...
                {'scalar','finite','integer','nonnegative'});
            validateattributes(value, {'numeric'}, ...
                {'scalar','finite','integer','nonnegative'});
            if width == 0
                assert(value == 0 && numel(dmrsPortSet) == 1, ...
                    'sixgr:phy:pdcch:InvalidPTRSDMRSAssociation', ...
                    'A zero-bit PT-RS association requires rank one.');
                ptrsPortSet = dmrsPortSet(1);
                return;
            end
            assert(width == 2 && value <= 3 && value + 1 <= numel(dmrsPortSet), ...
                'sixgr:phy:pdcch:InvalidPTRSDMRSAssociation', ...
                ['Received PT-RS/DM-RS association codepoint %d does not ' ...
                 'identify a scheduled DM-RS port.'], value);
            ptrsPortSet = dmrsPortSet(value + 1);
        end
    end
end

function values = localPortVector(raw, identifier)
assert((isnumeric(raw) || islogical(raw)) && ~isempty(raw), identifier, ...
    'PT-RS/DM-RS port sets must be non-empty numeric vectors.');
values = double(raw(:).');
assert(all(isfinite(values)) && all(values == fix(values)) && ...
    all(values >= 0) && numel(unique(values)) == numel(values), identifier, ...
    'PT-RS/DM-RS port sets must contain unique nonnegative integers.');
end
