classdef ScenarioRegistry
    %SCENARIOREGISTRY Mandatory AI 10.5.1.3 traceability inventory.

    methods (Static)
        function T = catalog()
            ids=["ANA-001","ANA-002","ANA-003","ANA-004","ANA-005","ANA-006","ANA-007", ...
                "CAL-001","CAL-002", ...
                "DL-001","DL-002","DL-003","DL-004","DL-005","DL-006", ...
                "CTRL-001","CTRL-002", ...
                "RACH-001","RACH-002","RACH-003", ...
                "UL-001","UL-002","UL-003","UL-004", ...
                "POSTIA-001","POSTIA-002","POSTIA-003","POSTIA-004", ...
                "POSTIA-005","POSTIA-006","POSTIA-007", ...
                "IDLE-001","IDLE-002","E2E-001"]';
            family=extractBefore(ids,"-");
            evidence=[repmat("ANALYTICAL_EXACT",7,1); ...
                repmat("SOURCE_REPRODUCTION",2,1); ...
                repmat("CALIBRATED_LLS",3,1); "PROCEDURE_SLS";"PROCEDURE_SLS";"PROCEDURE_SLS"; ...
                repmat("PROCEDURE_SLS",2,1);repmat("PROCEDURE_SLS",3,1); ...
                "ANALYTICAL_EXACT";"CALIBRATED_LLS";"PROCEDURE_SLS";"PROCEDURE_SLS"; ...
                repmat("PROCEDURE_SLS",7,1);repmat("PROCEDURE_SLS",2,1);"PROCEDURE_SLS"];
            title=["SIB1 minimum-RB screening";"SIB1 region geometry";"PBCH payload cost"; ...
                "FDRA and CCE arithmetic";"Power-normalization arithmetic";"RF-span feasibility"; ...
                "Transition-class derivation";"Qualcomm Msg4 source reproduction"; ...
                "MediaTek UL-energy source reproduction";"Controlled SIB1 PDSCH allocations"; ...
                "SIB1 PDCCH reference-width impact";"Joint SIB1 acquisition"; ...
                "Receiver preparation";"Beam-swept SIB1 timing";"SSB containment and tracking"; ...
                "Wider C versus wider S";"Control/data down-selection"; ...
                "RACH common inheritance";"Early bandwidth indication";"Additional configured DL range"; ...
                "Initial UL range containment";"Msg3/MsgA allocation sweep";"UL energy versus range"; ...
                "Aligned/non-aligned TDD";"Capability case A/B";"Confirming-UL activation"; ...
                "Transition preparation classes";"Bounded dual monitoring";"Early cease"; ...
                "Unsupported-profile recovery";"Transition Pareto";"Paging alternatives"; ...
                "Paging RF-span constraint";"End-to-end bandwidth procedure"];
            required=true(numel(ids),1);
            T=table(ids,family,title,evidence,required, ...
                'VariableNames',{'ScenarioID','Family','Title','PrimaryEvidenceClass','Required'});
        end

        function T = figureTraceability()
            ids=["F01","F02","F03","F04","F05","F06","F07","F08","F09", ...
                "R01","R02","R03","R04","R05","R06","R07","R08","R09","R10", ...
                "R11","R12","R13","R14","R15","R16","R17","R18","R19","R20", ...
                "R21","R22","R23","R24","R25"]';
            scenario=["E2E-001";"ANA-002";"ANA-003";"CTRL-001";"ANA-005";"ANA-006"; ...
                "RACH-001";"UL-001";"POSTIA-002"; ...
                "CAL-001";"CAL-001";"CAL-001";"ANA-003";"DL-002";"DL-001";"DL-003"; ...
                "ANA-001";"CTRL-001";"CTRL-001";"DL-004";"DL-005";"DL-006";"ANA-006"; ...
                "UL-002";"UL-003";"UL-004";"RACH-002";"POSTIA-001";"POSTIA-004"; ...
                "POSTIA-004";"POSTIA-006";"IDLE-001";"E2E-001";"E2E-001"];
            kind=[repmat("conceptual",9,1);repmat("result",25,1)];
            T=table(ids,scenario,kind,'VariableNames',{'FigureID','ScenarioID','Kind'});
        end
    end
end
