function [audit,passed]=frameImageAudit(runFolder)
%FRAMEIMAGEAUDIT Verify every CSV-replayed raster and global hash identity.
runFolder=string(char(java.io.File(char(runFolder)).getCanonicalPath()));
manifestPath=fullfile(runFolder,"manifests","figure_manifest.csv");
if exist(manifestPath,"file")~=2
    error("sixgr:csi:MissingFigureManifest", ...
        "Cannot audit raster figures without manifests/figure_manifest.csv.");
end
F=readtable(manifestPath,"Delimiter",",","VariableNamingRule","preserve");
rows=repmat(localRow(),height(F),1); hashes=strings(height(F),1);
for k=1:height(F)
    pngPath=fullfile(runFolder,string(F.PNGPath(k)));
    sourceRel=string(F.SourceCsv(k)); sourceHashesExpected=string(F.SourceCsvSha256(k));
    if ismember("SourceCsvs",string(F.Properties.VariableNames))
        sourceRel=split(string(F.SourceCsvs(k)),"|");
        sourceHashesExpected=split(string(F.SourceCsvHashes(k)),"|");
    end
    sourcePaths=fullfile(runFolder,replace(sourceRel,"/",filesep));
    exists=exist(pngPath,"file")==2;
    width=NaN; heightPx=NaN; nonblank=false; pngHash="";
    if exists
        info=imfinfo(pngPath); width=double(info.Width); heightPx=double(info.Height);
        pixels=double(imread(pngPath)); nonblank=std(pixels,0,"all")>0;
        pngHash=sixgr.csi.fileSHA256(pngPath);
    end
    hashes(k)=pngHash;
    sourceExists=all(isfile(sourcePaths));
    sourceHash=strings(numel(sourcePaths),1);
    if sourceExists
        for j=1:numel(sourcePaths), sourceHash(j)=sixgr.csi.fileSHA256(sourcePaths(j)); end
    end
    pdfExists=false; pdfHash=""; pdfManifestHash="";
    if ismember("PDFSha256",string(F.Properties.VariableNames))
        pdfPath=fullfile(runFolder,string(F.VectorPath(k)));
        pdfExists=exist(pdfPath,"file")==2; pdfManifestHash=string(F.PDFSha256(k));
        if pdfExists, pdfHash=sixgr.csi.fileSHA256(pdfPath); end
    end
    rows(k)=struct("FigureId",string(F.FigureId(k)), ...
        "PNGPath",string(F.PNGPath(k)),"Exists",exists, ...
        "WidthPx",width,"HeightPx",heightPx, ...
        "ExpectedWidthPx",double(F.WidthPx(k)), ...
        "ExpectedHeightPx",double(F.HeightPx(k)), ...
        "DimensionsMatch",exists&&width==double(F.WidthPx(k))&& ...
            heightPx==double(F.HeightPx(k)), ...
        "NonBlank",nonblank,"PNGSha256",pngHash, ...
        "ManifestHashMatch",pngHash==string(F.PNGSha256(k)), ...
        "PDFExists",pdfExists,"PDFSHA256",pdfHash, ...
        "PDFManifestHashMatch",pdfExists&&pdfHash==pdfManifestHash, ...
        "HashUnique",false,"SourceCSVExists",sourceExists, ...
        "SourceCSVHashMatch",sourceExists&&isequal(sourceHash(:),sourceHashesExpected(:)), ...
        "DataReplayCheck",logical(F.DataReplayCheck(k)), ...
        "SemanticAuditStatus",string(F.SemanticAuditStatus(k)), ...
        "Status","FAIL");
end
for k=1:numel(hashes)
    rows(k).HashUnique=strlength(hashes(k))==64&&nnz(hashes==hashes(k))==1;
    rows(k).Status=string(localIf(rows(k).Exists&&rows(k).DimensionsMatch&& ...
        rows(k).NonBlank&&rows(k).ManifestHashMatch&&rows(k).HashUnique&& ...
        rows(k).PDFExists&&rows(k).PDFManifestHashMatch&& ...
        rows(k).SourceCSVExists&&rows(k).SourceCSVHashMatch&& ...
        rows(k).SemanticAuditStatus=="PASS"&& ...
        rows(k).DataReplayCheck,"PASS","FAIL"));
end
audit=struct2table(rows,"AsArray",true);
passed=height(audit)>0&&all(audit.Status=="PASS");
end

function row=localRow()
row=struct("FigureId","","PNGPath","","Exists",false, ...
    "WidthPx",NaN,"HeightPx",NaN,"ExpectedWidthPx",NaN, ...
    "ExpectedHeightPx",NaN,"DimensionsMatch",false,"NonBlank",false, ...
    "PNGSha256","","ManifestHashMatch",false,"HashUnique",false, ...
    "PDFExists",false,"PDFSHA256","","PDFManifestHashMatch",false, ...
    "SourceCSVExists",false,"SourceCSVHashMatch",false, ...
    "DataReplayCheck",false,"SemanticAuditStatus","FAIL","Status","FAIL");
end

function value=localIf(tf,yes,no)
if tf, value=yes; else, value=no; end
end
