function out=runTDocStudyEnergyHypothesisWaveforms(cfg,provenance)
%RUNENERGYHYPOTHESISWAVEFORMS Measured CSI-RS to coded-PDSCH hypotheses.
%
% Each hypothesis executes the canonical high-port CSI-RS mapper, derives a
% rank-one precoder only from its measured estimate, and applies that
% precoder to the production PDSCH Tx/Rx chain on the same physical channel
% snapshot. No BLER lookup or configured-value substitution is used.
names=string(cfg.energy_hypotheses.names(:));
ports=double(cfg.energy_hypotheses.active_port_counts(:));
trps=double(cfg.energy_hypotheses.active_trp_counts(:));
offsetDb=double(cfg.energy_hypotheses.per_hypothesis_power_offset_db(:));
if ~(numel(names)==numel(ports) && numel(ports)==numel(trps) && ...
        numel(trps)==numel(offsetDb))
    error("sixgr:csi:EnergyHypothesisShapeMismatch", ...
        "Energy hypothesis names, ports, TRPs, and power offsets must align.");
end
nRx=double(cfg.arrays.rx_antennas(1)); maxPorts=max(ports);
old=rng; cleanup=onCleanup(@()rng(old)); %#ok<NASGU>
baseSeed=double(cfg.reproducibility.base_seed)+12000;
rng(baseSeed,"twister");
commonH=(randn(nRx,maxPorts)+1j*randn(nRx,maxPorts))/sqrt(2);

[llsCfg,llsProv]=sixgr.lls.loadConfig(string(cfg.execution.pdsch_anchor_config));
snrDb=double(cfg.energy_hypotheses.bounded_pdsch_snr_db);
llsCfg.simulation.snrDb=snrDb;
llsCfg.simulation.minTransportBlocks=1;
llsCfg.simulation.maxTransportBlocks=1;
llsCfg.simulation.minBlockErrors=2;
llsCfg.simulation.statisticalClass="diagnostic_only";
llsCfg=sixgr.lls.validateConfig(llsCfg,"ConfigPath",llsProv.ConfigPath);
phy=sixgr.lls.buildPHYConfig(llsCfg,snrDb);

reconstruction=[]; performance=[]; commonTransportBits=[];
for h=1:numel(names)
    p=ports(h);
    if trps(h)<max(trps)
        selectedPorts=(maxPorts-p+1):maxPorts;
    else
        selectedPorts=1:p;
    end
    H=commonH(:,selectedPorts);
    measured=sixgr.phy.refsig.HighPortCSIRSMapper.runWaveformPoint( ...
        cfg,p,double(cfg.multislot.bounded_cdm_size),"walsh",1, ...
        "fixed_per_port_epre",double(cfg.energy_hypotheses.bounded_csirs_snr_db), ...
        baseSeed+h,"ChannelMatrix",H,"ChannelSeed",baseSeed, ...
        "NoiseSeed",baseSeed+100,"PowerOffsetDb",offsetDb(h));
    [~,~,V]=svd(measured.Estimate,"econ"); W=V(:,1);
    W=W/max(norm(W),eps);
    phyHypothesis=phy;
    % The research CSI-RS hypothesis may expose hundreds of physical
    % elements, but those elements are not hundreds of NR logical PDSCH
    % ports. Bind the measured beam as a one-port hybrid RF/baseband map.
    phyHypothesis.phy.pdsch.numPorts=1;
    phyHypothesis.phy.pdsch.nPorts=1;
    phyHypothesis.phy.pdsch.numRFChains=1;
    phyHypothesis.phy.pdsch.hybridBeamformingEnabled=true;
    phyHypothesis.phy.pdsch.hybridElementToPortMatrix=W;
    phyHypothesis.phy.nTxAnt=p;
    phyHypothesis.channel.nTxAnt=p;
    phyHypothesis.scenario.bs.nTxAnt=p;
    phyHypothesis.antenna.bs.numElements=p;
    phyHypothesis.antenna.bs.numPorts=1;
    phyHypothesis.antenna.bs.numRFChains=1;
    phyHypothesis.antenna.bs.hybridBeamformingEnabled=true;
    phyHypothesis.antenna.bs.hybridElementToPortMatrix=W;
    txArgs={"ExecutionProfile","phy_calibration","NumTxAnt",p, ...
        "PrecodingMatrix",1,"CompactOutput",false};
    if ~isempty(commonTransportBits)
        txArgs=[txArgs,{"TransportBlockBits",commonTransportBits}]; %#ok<AGROW>
    end
    [tx,~]=sixgr.phy.dl.PDSCH_Tx(phyHypothesis,txArgs{:});
    if isempty(commonTransportBits), commonTransportBits=tx.TransportBlock; end
    txScale=10^(offsetDb(h)/20);
    desired=(tx.Waveform*transpose(H))*txScale;
    [rxWaveform,noiseInfo]=sixgr.phy.waveform.addOccupiedREAWGN( ...
        desired,tx.Carrier,snrDb,"Seed",baseSeed+1000, ...
        "SignalEnergyPerOccupiedRE",1);
    [rx,~]=sixgr.phy.dl.PDSCH_Rx(rxWaveform,phyHypothesis, ...
        "Carrier",tx.Carrier,"PDSCH",tx.PDSCH, ...
        "PDSCHIndices",tx.PDSCHIndices, ...
        "TransportBlockSize",tx.TransportBlockSize, ...
        "TargetCodeRate",tx.TargetCodeRate,"RV",tx.RV, ...
        "CodingPlan",tx.CodingPlans,"NoiseVar",noiseInfo.GridNoiseVariance, ...
        "NoiseVarDomain","grid", ...
        "MaxIterations",double(llsCfg.receiver.ldpcMaxIterations), ...
        "Algorithm",char(string(llsCfg.receiver.ldpcAlgorithm)), ...
        "PrecodingMatrix",1,"ExecutionProfile","phy_calibration", ...
        "CompactOutput",false,"FastAWGNPath",false, ...
        "SkipTimingEstimate",true);
    reconstruction=[reconstruction;table(names(h),p,trps(h),offsetDb(h), ...
        measured.NMSE,measured.NMSEdB,measured.SGCS, ...
        measured.PerPortEPRE,measured.TotalCSIRSPower, ...
        string(measured.ExecutionBackend),"none","LLS_CONTROLLED","PASS", ...
        'VariableNames',{'Hypothesis','ActivePorts','ActiveTRPs', ...
        'PowerOffsetDb','NMSELinear','NMSEdB','SGCS','PerPortEPRE', ...
        'TotalCSIRSPower','ExecutionBackend','ApproximationMode', ...
        'EvidenceClass','Status'})]; %#ok<AGROW>
    tbs=sum(double(tx.TransportBlockSize));
    performance=[performance;table(names(h),p,trps(h),offsetDb(h), ...
        snrDb,logical(rx.CRCError),double(~rx.CRCError)*tbs, ...
        double(sixgr.util.structGet(rx,"PostEqSINR_dB",NaN)), ...
        string(sixgr.util.structGet(rx,"PostEqSINRSource","")), ...
        string(sixgr.phy.mimo.MatrixContract.digest(W)), ...
        string(cfg.energy_hypotheses.bounded_channel_model), ...
        "sixgr.phy.dl.PDSCH_Tx_hybrid_element_domain_to_PDSCH_Rx","none", ...
        "LLS_CONTROLLED","PASS",'VariableNames',{'Hypothesis', ...
        'ActivePorts','ActiveTRPs','PowerOffsetDb','ConfiguredSNRdB', ...
        'CRCError','DeliveredBits','PostEqSINRdB','PostEqSINRSource', ...
        'PrecoderSHA256','ChannelModel','ExecutionBackend', ...
        'ApproximationMode','EvidenceClass','Status'})]; %#ok<AGROW>
end
out=struct("Reconstruction",reconstruction,"Performance",performance, ...
    "SuiteConfigSHA256",string(provenance.ConfigSHA256), ...
    "AnchorConfigSHA256",string(llsProv.ConfigSHA256));
end
