function out=runTDocStudyCanonicalFlowTrial(cfg,highPort,pdschTrials)
%RUNCANONICALFLOWTRIAL One bounded measured CSI-to-data/control flow.
%
% This is integration evidence, not a second PHY. It binds one observed
% CSI-RS waveform estimate to the existing immutable measurement state,
% CSI report/codebook, PUCCH UCI waveform, RSLA store, beam state machine,
% and production PDSCH result.
arguments
    cfg (1,1) struct
    highPort (1,1) struct
    pdschTrials table
end
f=cfg.csi.bounded_flow;
if ~logical(f.enabled)
    error("sixgr:csi:BoundedFlowDisabled", ...
        "The canonical bounded flow is mandatory and cannot be skipped.");
end

txPorts=double(f.tx_ports); rankValue=double(f.rank);
if size(highPort.Estimate,2)<txPorts || size(highPort.Estimate,1)<rankValue
    error("sixgr:csi:InsufficientMeasuredCSI", ...
        "The high-port receiver estimate cannot supply the configured bounded MIMO tuple.");
end
H=highPort.Estimate(:,1:txPorts);
nVar=double(highPort.GridNoiseVariance);
measurement=sixgr.phy.mimo.CSIMeasurementState( ...
    MeasurementID="CSI-TDOC-M0",UEID="UE-1",ResourceType="CSI-RS", ...
    ResourceID="CSI-RS-"+string(f.resource_id), ...
    ResourceOrdinal=double(f.resource_id), ...
    Slot=double(f.measurement_slot), ...
    MaxAgeSlots=double(f.maximum_age_slots),ChannelEstimate=H, ...
    NoiseVariance=nVar,Provenance="measured_csirs_high_port_ofdm");

request=struct("ReportConfigID","CSI-TDOC-R0","Epoch",0, ...
    "CodebookType","typeI-SinglePanel","Ports",txPorts, ...
    "Rank",rankValue,"ReportQuantity","cri-RI-PMI-CQI", ...
    "NumCSIResources",1,"FrequencyGranularity","wideband", ...
    "UCIChannel","PUCCH");
feedbackCfg=struct("Strict",true,"CurrentSlot",double(f.consumer_slot), ...
    "MaxRank",rankValue,"RankDomain",rankValue, ...
    "CodebookType","typeI-SinglePanel", ...
    "ReportConfiguration",request,"ReportConfigurationEpoch",0, ...
    "CQISINRThresholdsDB",double(f.cqi_thresholds_db(:).'));
feedback=sixgr.mimo.buildCSIFeedback(H,nVar,feedbackCfg, ...
    "Direction","DL","NominalRank",rankValue, ...
    "MeasurementState",measurement);

detailBits=int8([feedback.CSIPart1Bits(:);feedback.CSIPart2Bits(:)]);
if isempty(detailBits)
    error("sixgr:csi:EmptyEncodedCSI", ...
        "The configured CSI report produced no UCI payload bits.");
end
finitePostEq=double(pdschTrials.PostEqSINRdB( ...
    isfinite(pdschTrials.PostEqSINRdB)));
if isempty(finitePostEq)
    error("sixgr:csi:MissingDMRSRuntimeMeasurement", ...
        "Encoded DMRS refinement requires a finite production PDSCH receiver measurement.");
end
dmrsDelta=finitePostEq(1)-mean(finitePostEq);
deltaAlphabet=double(cfg.csi.cqi_delta_quantizer_db(:));
[~,deltaIndex]=min(abs(deltaAlphabet-dmrsDelta));
deltaWidth=max(1,ceil(log2(numel(deltaAlphabet))));
dmrsBits=int8(sixgr.l2.mac.SchedulerBase.uintToBits(deltaIndex-1,deltaWidth));
eventThreshold=double(cfg.event_csi.thresholds(1));
eventBits=int8([abs(dmrsDelta)>=eventThreshold; ...
    double(pdschTrials.CRCError(1))]);
hypothesisIndex=min(1,numel(cfg.energy_hypotheses.names)-1);
hypothesisWidth=max(1,ceil(log2(numel(cfg.energy_hypotheses.names))));
configuredQBits=double(cfg.energy_hypotheses.differential_quantizer_bits(:));
qBitsCandidates=configuredQBits(configuredQBits>=deltaWidth);
if isempty(qBitsCandidates)
    error("sixgr:csi:InsufficientDifferentialQuantizerBits", ...
        "No configured energy differential quantizer can represent the CSI delta alphabet.");
end
qBits=qBitsCandidates(1);
energyBits=int8([sixgr.l2.mac.SchedulerBase.uintToBits( ...
    hypothesisIndex,hypothesisWidth); ...
    sixgr.l2.mac.SchedulerBase.uintToBits(deltaIndex-1,qBits)]);
payloadRoles=["detailed_csi";"dmrs_delta";"event_stage1"; ...
    "energy_hypothesis_differential"];
payloads={detailBits;dmrsBits;eventBits;energyBits};
formats=double(f.pucch_formats(:));
metricValues=[feedback.WidebandSINR_dB;dmrsDelta;double(eventBits(1));hypothesisIndex];
metricUnits=["dB";"dB";"boolean";"hypothesis_index"];
pucchRows=[]; pucch=[];
for u=1:numel(payloadRoles)
    bits=int8(payloads{u}(:));
    fixture=sixgr.phy.pucch.PUCCHFixtureFactory.connected( ...
        formats(u),bits,"SCS",double(cfg.carrier.scs_khz));
    trial=sixgr.link.runPUCCHWaveformTrial(fixture.Carrier, ...
        "Assignment",fixture.Assignment,"Report",fixture.Report, ...
        "ReceiverContext",fixture.Context,"Carrier",fixture.Carrier, ...
        "ChannelProfile","AWGN","SNR_dB",double(f.pucch_snr_db), ...
        "Seed",double(cfg.reproducibility.base_seed)+7000+u);
    if ~logical(trial.StrictOk)
        error("sixgr:csi:BoundedUCIWaveformFailed", ...
            "Canonical PUCCH %s failed: %s (%s).",payloadRoles(u), ...
            string(trial.FailureReason),string(trial.ErrorID));
    end
    row=table(payloadRoles(u),metricValues(u),metricUnits(u), ...
        formats(u),double(f.pucch_snr_db),numel(bits), ...
        trial.BitErrors,trial.CRCFailed,trial.ContentMismatch, ...
        trial.MeasuredTrialSINR_dB,string(trial.MeasuredTrialSINRSource), ...
        string(trial.PUCCHWaveformHash),string(trial.ExecutionBackend), ...
        "LLS_CONTROLLED","PASS",'VariableNames',{'PayloadRole', ...
        'SourceMetricValue','SourceMetricUnit','Format','SNRdB', ...
        'InformationBits','BitErrors','CRCFailed','ContentMismatch', ...
        'MeasuredSINRdB','MeasuredSINRSource','WaveformSHA256', ...
        'ExecutionBackend','EvidenceClass','Status'});
    pucchRows=[pucchRows;row]; %#ok<AGROW>
    if u==1, pucch=trial; end
end

observed=struct("Valid",true,"MeasurementID","CSI-TDOC-M0", ...
    "UEID",1,"CellID",0,"BWPID",0, ...
    "ResourceID","CSI-RS-"+string(f.resource_id),"BeamID","BEAM-0", ...
    "ConfigurationEpoch",0,"ProducerSlot",double(f.measurement_slot), ...
    "AvailableSlot",double(f.consumer_slot),"ChannelEstimate",H, ...
    "NoiseVariance",nVar,"Source","measured_csirs_high_port_ofdm");
consumer=struct("UEID",1,"CellID",0,"BWPID",0, ...
    "ResourceID",observed.ResourceID,"BeamID",observed.BeamID, ...
    "ConfigurationEpoch",0,"ConsumerSlot",double(f.consumer_slot), ...
    "MaxAgeSlots",double(f.maximum_age_slots));
store=sixgr.phy.rsla.MeasurementStateStore(); store.put(observed);
[stored,validity]=store.newest(consumer);

beam=sixgr.phy.beam.BeamManagementStateMachine();
resource=string(observed.ResourceID);
beam.transition("AUTO_EVENT_FOR_P1_MEASURING");
beam.transition("AUTO_EVENT_FOR_P1_REPORTED", ...
    MeasuredResourceID=resource,MeasuredSINRDB=feedback.WidebandSINR_dB);
beam.transition("AUTO_EVENT_FOR_TCI_PENDING",MeasuredResourceID=resource);
beam.transition("AUTO_EVENT_FOR_TCI_ACTIVE",MeasuredResourceID=resource, ...
    ActivatedTCIState=double(f.active_tci_state));
beam.transition("AUTO_EVENT_FOR_DATA_ACTIVE",MeasuredResourceID=resource);

pdschNames=string(pdschTrials.Properties.VariableNames);
pdschContract=all(ismember(["TxProcessChain","RxProcessChain", ...
    "LLRSource","CRCSource","FallbackUsed"],pdschNames));
pdschPass=pdschContract && height(pdschTrials)>0 && ...
    any(~pdschTrials.CRCError) && ...
    all(strlength(string(pdschTrials.TxProcessChain))>0) && ...
    all(strlength(string(pdschTrials.RxProcessChain))>0) && ...
    all(string(pdschTrials.LLRSource)=="nrPDSCHDecode_soft_llr") && ...
    all(string(pdschTrials.CRCSource)=="decoded_transport_block_crc") && ...
    ~any(pdschTrials.FallbackUsed);
steps=[ ...
    localStep(1,"CSI-RS waveform/estimate", ...
        "sixgr.phy.refsig.HighPortCSIRSMapper",isfinite(highPort.NMSE), ...
        "NMSE_dB="+string(highPort.NMSEdB)); ...
    localStep(2,"Immutable measured state", ...
        "sixgr.phy.mimo.CSIMeasurementState",measurement.Digest~="", ...
        "measurement="+measurement.MeasurementID); ...
    localStep(3,"RI/PMI/CQI report", ...
        "sixgr.mimo.buildCSIFeedback",feedback.MeasurementID==measurement.MeasurementID, ...
        "RI="+string(feedback.RI)+" PMI="+string(feedback.PMI)+" CQI="+string(feedback.CQI)); ...
    localStep(4,"Encoded CSI on PUCCH", ...
        "sixgr.link.runPUCCHWaveformTrial",all(pucchRows.Status=="PASS"), ...
        "payloads="+string(height(pucchRows))+ ...
        " errors="+string(sum(pucchRows.BitErrors))); ...
    localStep(5,"Causal RSLA measurement store", ...
        "sixgr.phy.rsla.MeasurementStateStore",validity.Valid && ...
        string(stored.MeasurementID)==measurement.MeasurementID, ...
        "age_slots="+string(validity.AgeSlots)); ...
    localStep(6,"Measured beam/TCI lifecycle", ...
        "sixgr.phy.beam.BeamManagementStateMachine", ...
        beam.State=="DATA_ACTIVE" && beam.AppliedBeamID==resource, ...
        "state="+beam.State+" beam="+beam.AppliedBeamID); ...
    localStep(7,"Production PDSCH Tx/Rx", ...
        "sixgr.lls.runPDSCHTransportBlock",pdschPass, ...
        "transport_blocks="+string(height(pdschTrials)))];
trace=struct2table(steps,"AsArray",true);
if ~all(trace.Pass)
    failed=trace(~trace.Pass,:);
    error("sixgr:csi:CanonicalFlowGateFailed", ...
        "Canonical bounded CSI flow failed at %s (%s).", ...
        failed.Step(1),failed.CanonicalOwner(1));
end

report=table(feedback.MeasurementID,feedback.MeasurementResourceID, ...
    feedback.MeasurementSlot,feedback.RI,feedback.PMI,feedback.CQI, ...
    feedback.LI,feedback.WidebandSINR_dB,numel(feedback.CSIPart1Bits), ...
    numel(feedback.CSIPart2Bits),string(feedback.RuntimeEvidenceSource), ...
    "LLS_CONTROLLED","PASS",'VariableNames',{'MeasurementID', ...
    'ResourceID','MeasurementSlot','RI','PMI','CQI','LI', ...
    'WidebandSINRdB','CSIPart1Bits','CSIPart2Bits','RuntimeEvidenceSource', ...
    'EvidenceClass','Status'});
beamHistory=beam.History;
beamHistory.EvidenceClass(:)="PROCEDURE"; beamHistory.Status(:)="PASS";
out=struct("Trace",trace,"CSIReport",report,"PUCCH",pucchRows, ...
    "BeamHistory",beamHistory);
end

function row=localStep(index,step,owner,pass,detail)
row=struct("Sequence",double(index),"Step",string(step), ...
    "CanonicalOwner",string(owner),"Pass",logical(pass), ...
    "RuntimeMeasurement",string(detail),"FallbackUsed",false, ...
    "EvidenceClass","LLS_CONTROLLED","Status", ...
    string(localIf(pass,"PASS","FAIL")));
end

function value=localIf(tf,yes,no)
if tf, value=yes; else, value=no; end
end
