function cfg=validateTDocStudyConfig(cfg)
%VALIDATETDOCCONFIG Fail-fast validation for the 10.5.3.1 suite.
required=["schema_version","identity","reproducibility","execution", ...
    "carrier","channel","arrays","power","impairments","csirs", ...
    "pdsch","csi","olla","simulation","state_lifecycle", ...
    "interference_age","early_csi","event_csi","energy_hypotheses", ...
    "occ","multislot","sharing","outputs"];
for name=required
    if ~isfield(cfg,char(name))
        error("sixgr:csi:MissingConfigField", ...
            "Mandatory CSI TDoc configuration field '%s' is absent.",name);
    end
end
if ~strcmp(string(cfg.schema_version),"sixgr.csi.tdoc.10_5_3_1/v1")
    error("sixgr:csi:UnsupportedConfigSchema", ...
        "schema_version must be sixgr.csi.tdoc.10_5_3_1/v1.");
end
if ~logical(cfg.execution.strict) || ~logical(cfg.execution.prohibit_fallback)
    error("sixgr:csi:StrictModeRequired", ...
        "execution.strict and execution.prohibit_fallback must both be true.");
end
if ~any(ismember(upper(string(cfg.channel.models(:))), ...
        ["CDL-A","CDL-C","CDL-D","TDL-C"]))
    error("sixgr:csi:BadChannelProfile", ...
        "channel.models must contain concrete CDL-* or TDL-* profiles.");
end
ports=double(cfg.csirs.port_counts(:));
if ~all(ismember([128;256;512],ports))
    error("sixgr:csi:MissingHighPortCases", ...
        "csirs.port_counts must include 128, 256 and 512 without reduction.");
end
lengths=double(cfg.occ.lengths(:));
if ~all(ismember([8;16;32;64],lengths))
    error("sixgr:csi:MissingOCCLengths", ...
        "occ.lengths must include 8, 16, 32 and 64.");
end
if abs(double(cfg.olla.nack_step_db)/double(cfg.olla.ack_step_db)-9)>1e-12 || ...
        abs(double(cfg.olla.target_bler)-.1)>1e-12
    error("sixgr:csi:InvalidOLLARatio", ...
        "For target BLER 0.1, olla.nack_step_db must equal 9*olla.ack_step_db.");
end
flow=cfg.csi.bounded_flow;
flowRequired=["enabled","tx_ports","rank","resource_id", ...
    "measurement_slot","consumer_slot","maximum_age_slots", ...
    "pucch_formats","pucch_snr_db","active_tci_state", ...
    "cqi_thresholds_db"];
for name=flowRequired
    if ~isfield(flow,char(name))
        error("sixgr:csi:MissingBoundedFlowField", ...
            "csi.bounded_flow.%s is mandatory for the canonical short-run gate.",name);
    end
end
if ~logical(flow.enabled)
    error("sixgr:csi:BoundedFlowRequired", ...
        "csi.bounded_flow.enabled must be true for this qualification suite.");
end
txPorts=double(flow.tx_ports); rankValue=double(flow.rank);
if ~(isscalar(txPorts)&&isfinite(txPorts)&&txPorts==2) || ...
        ~(isscalar(rankValue)&&isfinite(rankValue)&&rankValue>=1&& ...
        rankValue<=txPorts&&rankValue==round(rankValue))
    error("sixgr:csi:InvalidBoundedMIMOTuple", ...
        "The bounded Type-I flow requires tx_ports=2 and rank in [1,2].");
end
formats=double(flow.pucch_formats(:));
if numel(formats)~=4 || any(~ismember(formats,0:4))
    error("sixgr:csi:InvalidBoundedUCIFormat", ...
        ["csi.bounded_flow.pucch_formats must provide four valid formats " ...
         "for detailed CSI, DMRS delta, event stage 1, and energy differential."]);
end
if double(flow.consumer_slot)<double(flow.measurement_slot) || ...
        double(flow.consumer_slot)-double(flow.measurement_slot)> ...
        double(flow.maximum_age_slots)
    error("sixgr:csi:InvalidBoundedMeasurementAge", ...
        "The bounded consumer slot must consume an available finite-age measurement.");
end
cqiThresholds=double(flow.cqi_thresholds_db(:));
if numel(cqiThresholds)~=16 || any(~isfinite(cqiThresholds)) || ...
        any(diff(cqiThresholds)<=0)
    error("sixgr:csi:InvalidBoundedCQIThresholds", ...
        "csi.bounded_flow.cqi_thresholds_db must contain exactly 16 "+ ...
        "finite, strictly increasing thresholds for CQI indices 0 through 15.");
end
boundedSNR=double(cfg.simulation.bounded_snr_points_db(:));
boundedTB=double(cfg.simulation.bounded_transport_blocks_per_point);
boundedRealizations=double(cfg.simulation.bounded_channel_realizations_per_point);
if numel(boundedSNR)<3 || any(~isfinite(boundedSNR)) || ...
        any(diff(boundedSNR)<=0) || ~(isscalar(boundedTB)&&isfinite(boundedTB)&& ...
        boundedTB>=1&&boundedTB==round(boundedTB)) || ...
        ~(isscalar(boundedRealizations)&&isfinite(boundedRealizations)&& ...
        boundedRealizations>=1&&boundedRealizations==round(boundedRealizations))
    error("sixgr:csi:InvalidBoundedSimulationMatrix", ...
        ["simulation.bounded_snr_points_db must contain at least three increasing finite points, and bounded transport-block/channel-realization counts must be positive integers."]);
end
if ~isfield(cfg.execution,"parallel_enabled") || ...
        ~isfield(cfg.execution,"maximum_workers") || ...
        ~(isscalar(cfg.execution.maximum_workers)&& ...
        double(cfg.execution.maximum_workers)>=1&& ...
        double(cfg.execution.maximum_workers)==round(double(cfg.execution.maximum_workers)))
    error("sixgr:csi:InvalidParallelExecutionConfig", ...
        "execution.parallel_enabled and a positive integer maximum_workers are mandatory.");
end
controlledFields=["controlled_transport_blocks_per_point", ...
    "controlled_min_block_errors","controlled_max_transport_blocks_per_point", ...
    "controlled_channel_realizations_per_point","controlled_snr_points_db", ...
    "controlled_preflight","shard_index","shard_count"];
for name=controlledFields
    if ~isfield(cfg.simulation,char(name))
        error("sixgr:csi:MissingControlledSimulationField", ...
            "simulation.%s is mandatory for the controlled CSI-RS campaign.",name);
    end
end
controlledSNR=double(cfg.simulation.controlled_snr_points_db(:));
controlledTB=double(cfg.simulation.controlled_transport_blocks_per_point);
controlledMax=double(cfg.simulation.controlled_max_transport_blocks_per_point);
controlledErrors=double(cfg.simulation.controlled_min_block_errors);
controlledRealizations=double(cfg.simulation.controlled_channel_realizations_per_point);
if numel(controlledSNR)<7 || any(~isfinite(controlledSNR)) || ...
        any(diff(controlledSNR)<=0)
    error("sixgr:csi:InvalidControlledSNRGrid", ...
        "simulation.controlled_snr_points_db must contain at least seven strictly increasing finite physical SNR values.");
end
localPositiveInteger(controlledTB,"simulation.controlled_transport_blocks_per_point");
localPositiveInteger(controlledMax,"simulation.controlled_max_transport_blocks_per_point");
localPositiveInteger(controlledErrors,"simulation.controlled_min_block_errors");
localPositiveInteger(controlledRealizations,"simulation.controlled_channel_realizations_per_point");
if controlledMax<controlledTB || controlledErrors>controlledMax
    error("sixgr:csi:InvalidControlledStoppingRule", ...
        "Controlled max transport blocks must be >= the minimum trial count and >= the requested block-error count.");
end
shardIndex=double(cfg.simulation.shard_index); shardCount=double(cfg.simulation.shard_count);
localPositiveInteger(shardIndex,"simulation.shard_index");
localPositiveInteger(shardCount,"simulation.shard_count");
if shardIndex>shardCount
    error("sixgr:csi:InvalidControlledShard", ...
        "simulation.shard_index must be in [1, simulation.shard_count].");
end
if ~isfield(cfg.execution,"controlled_groups") || ...
        ~all(ismember(string(cfg.execution.controlled_groups(:)), ...
        ["B","C","D","E","F","G","H","I","J"]))
    error("sixgr:csi:InvalidControlledGroups", ...
        "execution.controlled_groups must contain only CSI scenario groups B through J.");
end
if ~logical(cfg.execution.checkpoint_enabled) || ...
        ~logical(cfg.execution.resume_enabled) || ...
        ~logical(cfg.execution.fail_on_incomplete_matrix)
    error("sixgr:csi:ControlledResumeContractRequired", ...
        "Full controlled execution requires checkpoint, resume and fail-on-incomplete-matrix gates.");
end
if ~all(ismember(["E0","E1","E2","E3","E4"], ...
        string(cfg.early_csi.variants(:)))) || ...
        ~all(ismember([1 2 4 8],double(cfg.early_csi.monitored_candidates(:)).'))
    error("sixgr:csi:IncompleteEarlyCSIMatrix", ...
        "early_csi must include E0-E4 and monitored_candidates [1,2,4,8].");
end
if numel(cfg.event_csi.thresholds)<3 || numel(cfg.event_csi.hysteresis)<2 || ...
        ~all(ismember([1 2 4],double(cfg.event_csi.ttt_slots(:)).')) || ...
        numel(cfg.event_csi.minimum_inter_event_slots)<3
    error("sixgr:csi:IncompleteEventCSIMatrix", ...
        "event_csi requires >=3 thresholds, >=2 hysteresis values, TTT [1,2,4], and >=3 minimum intervals.");
end
if ~all(ismember(["LS","LMMSE"],upper(string(cfg.occ.estimators(:))))) || ...
        numel(cfg.occ.controlled_snr_points_db)<7
    error("sixgr:csi:IncompleteOCCControlledMatrix", ...
        "occ.estimators must include LS and LMMSE and occ.controlled_snr_points_db must contain >=7 points.");
end
if ~all(ismember(["split_single_occasion","repeated_full_pattern"], ...
        string(cfg.multislot.cases(:)))) || ...
        ~all(ismember([1 2 4 8],double(cfg.multislot.m1(:)).')) || ...
        ~all(ismember([1 2 4],double(cfg.multislot.m2(:)).'))
    error("sixgr:csi:IncompleteMultiSlotControlledMatrix", ...
        "multislot must include both Case A/B labels, M1 [1,2,4,8], and M2 [1,2,4].");
end
hypotheses=string(cfg.energy_hypotheses.names(:));
if numel(hypotheses)~=numel(cfg.energy_hypotheses.active_port_counts) || ...
        numel(hypotheses)~=numel(cfg.energy_hypotheses.active_trp_counts) || ...
        numel(hypotheses)~=numel(cfg.energy_hypotheses.per_hypothesis_power_offset_db)
    error("sixgr:csi:EnergyHypothesisShapeMismatch", ...
        "Energy names, active ports, active TRPs, and power offsets must align.");
end

if logical(cfg.identity.common_evm_verified)
    fields=["common_evm_source","common_evm_document","common_evm_version","common_evm_hash"];
    for name=fields
        if strlength(string(cfg.identity.(name)))==0
            error("sixgr:csi:UnverifiedCommonEVM", ...
                "identity.%s is mandatory when common_evm_verified=true.",name);
        end
    end
end
if ~logical(cfg.execution.save_csv) || ~logical(cfg.execution.save_png)
    error("sixgr:csi:ArtifactOutputRequired", ...
        "execution.save_csv and execution.save_png must be true.");
end
end

function localPositiveInteger(value,path)
if ~(isscalar(value)&&isfinite(value)&&value>=1&&value==round(value))
    error("sixgr:csi:InvalidControlledInteger", ...
        "%s must be a positive integer.",path);
end
end
