function cfg=validateTDocConfig(cfg)
%VALIDATETDOCCONFIG Fail-fast validation for the 10.5.3.1 suite.
required=["schema_version","identity","reproducibility","execution", ...
    "carrier","channel","arrays","power","impairments","csirs", ...
    "pdsch","csi","olla","simulation","state_lifecycle", ...
    "interference_age","early_csi","event_csi","energy_hypotheses", ...
    "occ","multislot","sharing","outputs"];
for name=required
    if ~isfield(cfg,char(name))
        error("sixgr:csi:MissingConfigField", ...
            "Mandatory CSI TDoc configuration field '%s' is absent.",name);
    end
end
if ~strcmp(string(cfg.schema_version),"sixgr.csi.tdoc.10_5_3_1/v1")
    error("sixgr:csi:UnsupportedConfigSchema", ...
        "schema_version must be sixgr.csi.tdoc.10_5_3_1/v1.");
end
if ~logical(cfg.execution.strict) || ~logical(cfg.execution.prohibit_fallback)
    error("sixgr:csi:StrictModeRequired", ...
        "execution.strict and execution.prohibit_fallback must both be true.");
end
if ~any(ismember(upper(string(cfg.channel.models(:))), ...
        ["CDL-A","CDL-C","CDL-D","TDL-C"]))
    error("sixgr:csi:BadChannelProfile", ...
        "channel.models must contain concrete CDL-* or TDL-* profiles.");
end
ports=double(cfg.csirs.port_counts(:));
if ~all(ismember([128;256;512],ports))
    error("sixgr:csi:MissingHighPortCases", ...
        "csirs.port_counts must include 128, 256 and 512 without reduction.");
end
lengths=double(cfg.occ.lengths(:));
if ~all(ismember([8;16;32;64],lengths))
    error("sixgr:csi:MissingOCCLengths", ...
        "occ.lengths must include 8, 16, 32 and 64.");
end
if abs(double(cfg.olla.nack_step_db)/double(cfg.olla.ack_step_db)-9)>1e-12 || ...
        abs(double(cfg.olla.target_bler)-.1)>1e-12
    error("sixgr:csi:InvalidOLLARatio", ...
        "For target BLER 0.1, olla.nack_step_db must equal 9*olla.ack_step_db.");
end
flow=cfg.csi.bounded_flow;
flowRequired=["enabled","tx_ports","rank","resource_id", ...
    "measurement_slot","consumer_slot","maximum_age_slots", ...
    "pucch_formats","pucch_snr_db","active_tci_state", ...
    "cqi_thresholds_db"];
for name=flowRequired
    if ~isfield(flow,char(name))
        error("sixgr:csi:MissingBoundedFlowField", ...
            "csi.bounded_flow.%s is mandatory for the canonical short-run gate.",name);
    end
end
if ~logical(flow.enabled)
    error("sixgr:csi:BoundedFlowRequired", ...
        "csi.bounded_flow.enabled must be true for this qualification suite.");
end
txPorts=double(flow.tx_ports); rankValue=double(flow.rank);
if ~(isscalar(txPorts)&&isfinite(txPorts)&&txPorts==2) || ...
        ~(isscalar(rankValue)&&isfinite(rankValue)&&rankValue>=1&& ...
        rankValue<=txPorts&&rankValue==round(rankValue))
    error("sixgr:csi:InvalidBoundedMIMOTuple", ...
        "The bounded Type-I flow requires tx_ports=2 and rank in [1,2].");
end
formats=double(flow.pucch_formats(:));
if numel(formats)~=4 || any(~ismember(formats,0:4))
    error("sixgr:csi:InvalidBoundedUCIFormat", ...
        ["csi.bounded_flow.pucch_formats must provide four valid formats " ...
         "for detailed CSI, DMRS delta, event stage 1, and energy differential."]);
end
if double(flow.consumer_slot)<double(flow.measurement_slot) || ...
        double(flow.consumer_slot)-double(flow.measurement_slot)> ...
        double(flow.maximum_age_slots)
    error("sixgr:csi:InvalidBoundedMeasurementAge", ...
        "The bounded consumer slot must consume an available finite-age measurement.");
end
cqiThresholds=double(flow.cqi_thresholds_db(:));
if numel(cqiThresholds)~=16 || any(~isfinite(cqiThresholds)) || ...
        any(diff(cqiThresholds)<=0)
    error("sixgr:csi:InvalidBoundedCQIThresholds", ...
        "csi.bounded_flow.cqi_thresholds_db must contain exactly 16 "+ ...
        "finite, strictly increasing thresholds for CQI indices 0 through 15.");
end
boundedSNR=double(cfg.simulation.bounded_snr_points_db(:));
boundedTB=double(cfg.simulation.bounded_transport_blocks_per_point);
if numel(boundedSNR)<3 || any(~isfinite(boundedSNR)) || ...
        any(diff(boundedSNR)<=0) || ~(isscalar(boundedTB)&&isfinite(boundedTB)&& ...
        boundedTB>=1&&boundedTB==round(boundedTB))
    error("sixgr:csi:InvalidBoundedSimulationMatrix", ...
        "simulation.bounded_snr_points_db must contain at least three increasing finite points and bounded_transport_blocks_per_point must be a positive integer.");
end
hypotheses=string(cfg.energy_hypotheses.names(:));
if numel(hypotheses)~=numel(cfg.energy_hypotheses.active_port_counts) || ...
        numel(hypotheses)~=numel(cfg.energy_hypotheses.active_trp_counts) || ...
        numel(hypotheses)~=numel(cfg.energy_hypotheses.per_hypothesis_power_offset_db)
    error("sixgr:csi:EnergyHypothesisShapeMismatch", ...
        "Energy names, active ports, active TRPs, and power offsets must align.");
end
if logical(cfg.identity.common_evm_verified)
    fields=["common_evm_source","common_evm_document","common_evm_version","common_evm_hash"];
    for name=fields
        if strlength(string(cfg.identity.(name)))==0
            error("sixgr:csi:UnverifiedCommonEVM", ...
                "identity.%s is mandatory when common_evm_verified=true.",name);
        end
    end
end
if ~logical(cfg.execution.save_csv) || ~logical(cfg.execution.save_png)
    error("sixgr:csi:ArtifactOutputRequired", ...
        "execution.save_csv and execution.save_png must be true.");
end
end
