classdef InitialAccessCarrierContext
    %INITIALACCESSCARRIERCONTEXT Immutable resolved carrier facts for IA.

    methods (Static)
        function context = resolve(varargin)
            p = inputParser;
            p.FunctionName = ...
                "sixgr.phy.ia.InitialAccessCarrierContext.resolve";
            addParameter(p, "Profile", ...
                "fr1_four_step_ra_rrc_connection_strict_r18", ...
                @localTextScalar);
            addParameter(p, "FrequencyRange", "FR1", @localTextScalar);
            addParameter(p, "BandContext", "", @localTextScalar);
            addParameter(p, "Spectrum", "", @localTextScalar);
            addParameter(p, "CarrierFrequencyHz", NaN, @localPositiveFinite);
            addParameter(p, "ChannelBandwidthMHz", NaN, @localPositiveFinite);
            addParameter(p, "CarrierSubcarrierSpacingKHz", NaN, ...
                @localPositiveFinite);
            addParameter(p, "CyclicPrefix", "normal", @localTextScalar);
            addParameter(p, "NStartGrid", 0, @localNonnegativeInteger);
            addParameter(p, "NSizeGrid", NaN, @localPositiveInteger);
            addParameter(p, "DLBWPID", 0, @localNonnegativeInteger);
            addParameter(p, "DLBWPStart", 0, @localNonnegativeInteger);
            addParameter(p, "DLBWPSize", NaN, @localPositiveInteger);
            addParameter(p, "ULBWPID", 0, @localNonnegativeInteger);
            addParameter(p, "ULBWPStart", 0, @localNonnegativeInteger);
            addParameter(p, "ULBWPSize", NaN, @localPositiveInteger);
            addParameter(p, "DuplexMode", "", @localTextScalar);
            addParameter(p, "ConfigurationEpoch", 1, ...
                @localNonnegativeInteger);
            parse(p, varargin{:});
            opt = p.Results;

            profile = sixgr.phy.ia.InitialAccessSpecificationProfile.resolve( ...
                opt.Profile);
            range = upper(strtrim(string(opt.FrequencyRange)));
            if range ~= profile.FrequencyRange
                error("sixgr:phy:ia:UnsupportedProfile", ...
                    "The bounded initial-access carrier must be FR1.");
            end
            bandContext = strtrim(string(opt.BandContext));
            spectrum = lower(strtrim(string(opt.Spectrum)));
            if strlength(bandContext) == 0 || ...
                    ~any(spectrum == ["paired", "unpaired"])
                error("sixgr:phy:ia:InvalidCarrierGrid", ...
                    "BandContext and paired/unpaired Spectrum are required.");
            end

            nStartGrid = double(opt.NStartGrid);
            nSizeGrid = double(opt.NSizeGrid);
            dlStart = double(opt.DLBWPStart);
            dlSize = localDefaultFinite(double(opt.DLBWPSize), nSizeGrid);
            ulStart = double(opt.ULBWPStart);
            ulSize = localDefaultFinite(double(opt.ULBWPSize), nSizeGrid);
            localValidateBWP(dlStart, dlSize, nStartGrid, nSizeGrid, "DL");
            localValidateBWP(ulStart, ulSize, nStartGrid, nSizeGrid, "UL");

            payload = struct( ...
                "ProfileID", profile.ProfileID, ...
                "FrequencyRange", range, ...
                "BandContext", bandContext, ...
                "Spectrum", spectrum, ...
                "CarrierFrequencyHz", double(opt.CarrierFrequencyHz), ...
                "ChannelBandwidthMHz", double(opt.ChannelBandwidthMHz), ...
                "CarrierSubcarrierSpacingKHz", ...
                    double(opt.CarrierSubcarrierSpacingKHz), ...
                "CyclicPrefix", lower(strtrim(string(opt.CyclicPrefix))), ...
                "NStartGrid", nStartGrid, ...
                "NSizeGrid", nSizeGrid, ...
                "DLBWPID", double(opt.DLBWPID), ...
                "DLBWPStart", dlStart, ...
                "DLBWPSize", dlSize, ...
                "ULBWPID", double(opt.ULBWPID), ...
                "ULBWPStart", ulStart, ...
                "ULBWPSize", ulSize, ...
                "DuplexMode", lower(strtrim(string(opt.DuplexMode))), ...
                "ConfigurationEpoch", uint64(opt.ConfigurationEpoch));
            context = payload;
            context.ContextSHA256 = sixgr.util.sha256Hex(jsonencode(payload));
            context.Immutable = true;
        end

        function context = fromConfig(cfg)
            if ~isstruct(cfg)
                error("sixgr:phy:ia:InvalidCarrierGrid", ...
                    "Carrier configuration must be a scalar struct.");
            end
            nStart = sixgr.util.structGet(cfg, "phy.carrier.NStartGrid", 0);
            nSize = sixgr.util.structGet(cfg, "phy.carrier.NSizeGrid", NaN);
            context = sixgr.phy.ia.InitialAccessCarrierContext.resolve( ...
                "Profile", sixgr.util.structGet(cfg, ...
                    "initial_access.profile", ...
                    "fr1_four_step_ra_rrc_connection_strict_r18"), ...
                "FrequencyRange", sixgr.util.structGet(cfg, ...
                    "phy.frequencyRange", ...
                    sixgr.util.structGet(cfg, "frequency.range_name", "FR1")), ...
                "BandContext", sixgr.util.structGet(cfg, ...
                    "initial_access.band_context", ...
                    sixgr.util.structGet(cfg, "frequency.band_context", "")), ...
                "Spectrum", sixgr.util.structGet(cfg, ...
                    "initial_access.spectrum", ...
                    sixgr.util.structGet(cfg, "frequency.spectrum", "")), ...
                "CarrierFrequencyHz", sixgr.util.structGet(cfg, ...
                    "phy.carrier.centerFrequency_Hz", ...
                    sixgr.util.structGet(cfg, ...
                    "frequency.center_frequency_hz", NaN)), ...
                "ChannelBandwidthMHz", ...
                    localBandwidthMHz(cfg), ...
                "CarrierSubcarrierSpacingKHz", sixgr.util.structGet(cfg, ...
                    "phy.carrier.SubcarrierSpacing_kHz", ...
                    sixgr.util.structGet(cfg, ...
                    "phy.carrier.SubcarrierSpacing", NaN)), ...
                "CyclicPrefix", sixgr.util.structGet(cfg, ...
                    "phy.carrier.CyclicPrefix", "normal"), ...
                "NStartGrid", nStart, ...
                "NSizeGrid", nSize, ...
                "DLBWPID", sixgr.util.structGet(cfg, ...
                    "phy.bwp.dl.ID", 0), ...
                "DLBWPStart", sixgr.util.structGet(cfg, ...
                    "phy.bwp.dl.NStartBWP", nStart), ...
                "DLBWPSize", sixgr.util.structGet(cfg, ...
                    "phy.bwp.dl.NSizeBWP", nSize), ...
                "ULBWPID", sixgr.util.structGet(cfg, ...
                    "phy.bwp.ul.ID", 0), ...
                "ULBWPStart", sixgr.util.structGet(cfg, ...
                    "phy.bwp.ul.NStartBWP", nStart), ...
                "ULBWPSize", sixgr.util.structGet(cfg, ...
                    "phy.bwp.ul.NSizeBWP", nSize), ...
                "DuplexMode", sixgr.util.structGet(cfg, ...
                    "frame.duplex_mode", ""), ...
                "ConfigurationEpoch", sixgr.util.structGet(cfg, ...
                    "initial_access.configuration_epoch", 1));
        end
    end
end

function localValidateBWP(startValue, sizeValue, gridStart, gridSize, label)
if startValue < gridStart || startValue + sizeValue > gridStart + gridSize
    error("sixgr:phy:ia:InvalidCarrierGrid", ...
        "%s BWP [%g,%g) is outside carrier grid [%g,%g).", ...
        label, startValue, startValue + sizeValue, ...
        gridStart, gridStart + gridSize);
end
end

function value = localDefaultFinite(value, defaultValue)
if ~isfinite(value)
    value = defaultValue;
end
end

function value = localBandwidthMHz(cfg)
value = sixgr.util.structGet(cfg, "phy.channelBandwidth_MHz", NaN);
if ~isfinite(double(value))
    value = double(sixgr.util.structGet(cfg, ...
        "frequency.bandwidth_hz", NaN)) / 1e6;
end
end

function tf = localTextScalar(value)
tf = ischar(value) || (isstring(value) && isscalar(value));
end

function tf = localPositiveFinite(value)
tf = isnumeric(value) && isscalar(value) && isfinite(value) && value > 0;
end

function tf = localNonnegativeInteger(value)
tf = isnumeric(value) && isscalar(value) && isfinite(value) && ...
    value >= 0 && value == fix(value);
end

function tf = localPositiveInteger(value)
tf = isnumeric(value) && isscalar(value) && ...
    ((isfinite(value) && value >= 1 && value == fix(value)) || isnan(value));
end
