classdef InitialAccessImpactEvidenceBuilder
    %INITIALACCESSIMPACTEVIDENCEBUILDER Execute the contracted IA matrix.
    %
    % Each matrix row is dispatched to a production initial-access
    % component. A row can observe a successful procedure or an expected,
    % typed fail-closed result; Status=PASS means that the declared factor
    % was applied and the experiment completed, not that radio access
    % necessarily succeeded.

    methods (Static)
        function evidence = build(vectorRoot, experimentMatrix, cfg, ...
                seedList, confidenceLevel, baseArtifactDir)
            vectorRoot = char(string(vectorRoot));
            experimentMatrix = char(string(experimentMatrix));
            baseArtifactDir = char(string(baseArtifactDir));
            matrix = localReadStringTable(experimentMatrix);
            families = localReadStringTable(fullfile(vectorRoot, ...
                "initial_access_impact_analysis_families.csv"));
            rules = localReadStringTable(fullfile(vectorRoot, ...
                "initial_access_impact_acceptance_rules.csv"));
            localValidateMatrix(matrix, families, seedList);
            localValidateBaseArtifacts(baseArtifactDir, vectorRoot);

            baseline = localBaselineState(families);
            records = repmat(localRecord(), height(matrix), 1);
            for index = 1:height(matrix)
                records(index) = localExecuteExperiment( ...
                    matrix(index, :), cfg, baseline);
            end

            raw = localRawTable(records);
            operating = localOperatingPoints(records, confidenceLevel);
            effects = localPairwiseEffects(records);
            domains = localDomainTables(records);
            interactions = localInteractions(records);
            summary = localSummary(records, families);
            ruleEvaluation = localRuleEvaluation( ...
                rules, records, baseArtifactDir);

            runID = "ia_impact_" + string(datetime("now", ...
                "TimeZone", "UTC", "Format", "yyyyMMdd'T'HHmmss'Z'"));
            manifest = table( ...
                runID, localFileSHA256(experimentMatrix), ...
                localFileSHA256(fullfile(vectorRoot, ...
                    "initial_access_impact_pairing_contract.csv")), ...
                localFileSHA256(fullfile(vectorRoot, ...
                    "initial_access_impact_acceptance_rules.csv")), ...
                strjoin(string(double(seedList(:).')), "|"), ...
                string(version("-release")), localToolboxVersion(), ...
                "PASS", ...
                'VariableNames', { ...
                'RunID','ExperimentMatrixSHA256', ...
                'PairingContractSHA256','AcceptanceRulesSHA256', ...
                'SeedList','MATLABVersion','ToolboxVersion','Status'});

            evidence = struct( ...
                "initial_access_impact_run_manifest", manifest, ...
                "initial_access_impact_raw_trials", raw, ...
                "initial_access_impact_operating_points", operating, ...
                "initial_access_impact_pairwise_effects", effects, ...
                "initial_access_impact_rule_evaluation", ruleEvaluation, ...
                "initial_access_impact_ssb", domains.SSB, ...
                "initial_access_impact_type0_sib1", domains.Type0SIB1, ...
                "initial_access_impact_prach", domains.PRACH, ...
                "initial_access_impact_beam", domains.Beam, ...
                "initial_access_impact_power", domains.Power, ...
                "initial_access_impact_contention", domains.Contention, ...
                "initial_access_impact_rrc", domains.RRC, ...
                "initial_access_impact_runtime", domains.Runtime, ...
                "initial_access_impact_interactions", interactions, ...
                "initial_access_impact_summary", summary);
        end
    end
end

function localValidateMatrix(matrix, families, seedList)
required = [ ...
    "FamilyID","PairID","Seed","Factor","Wave","DependencyState", ...
    "Mandatory","ExperimentID","Variant","FactorValue"];
if ~all(ismember(required, string(matrix.Properties.VariableNames)))
    error("sixgr:phy:ia:ImpactMatrixSchemaInvalid", ...
        "The impact matrix is missing mandatory columns.");
end
if height(matrix) ~= 720 || numel(unique(matrix.ExperimentID)) ~= 720
    error("sixgr:phy:ia:ImpactMatrixCardinalityInvalid", ...
        "The impact matrix must contain 720 unique experiments.");
end
if height(families) ~= 60 || numel(unique(families.FamilyID)) ~= 60
    error("sixgr:phy:ia:ImpactFamilyCardinalityInvalid", ...
        "The impact catalog must contain 60 unique families.");
end
if ~all(localTruth(matrix.Mandatory))
    error("sixgr:phy:ia:ImpactMandatoryExperimentMissing", ...
        "Every contracted impact experiment must be mandatory.");
end
if ~all(ismember(str2double(matrix.Seed), double(seedList(:))))
    error("sixgr:phy:ia:ImpactSeedListMismatch", ...
        "SeedList does not cover every matrix seed.");
end
pairIDs = unique(matrix.PairID);
for pairID = pairIDs.'
    selected = matrix(matrix.PairID == pairID, :);
    if height(selected) ~= 2 || ...
            ~isequal(sort(selected.Variant), ["baseline";"treatment"])
        error("sixgr:phy:ia:ImpactPairingInvalid", ...
            "Pair %s is not one baseline plus one treatment.", pairID);
    end
    same = [ ...
        "FamilyID","Seed","TrialSetID","PayloadSetID", ...
        "ChannelRealizationID","NoiseRealizationID", ...
        "InitialStateID","Factor"];
    for name = same
        if numel(unique(selected.(char(name)))) ~= 1
            error("sixgr:phy:ia:ImpactPairingInvalid", ...
                "Pair %s differs in %s.", pairID, name);
        end
    end
end
end

function localValidateBaseArtifacts(baseDir, vectorRoot)
if ~isfolder(baseDir)
    error("sixgr:phy:ia:ImpactBaseArtifactsMissing", ...
        "Verified base initial-access artifacts are required.");
end
script = fullfile(vectorRoot, "verify_initial_access_artifacts.py");
command = """python"" """ + string(script) + """ """ + ...
    string(baseDir) + """";
[status, output] = system(char(command));
if status ~= 0
    error("sixgr:phy:ia:ImpactBaseArtifactsInvalid", ...
        "Base initial-access verifier failed:\n%s", output);
end
end

function state = localBaselineState(families)
state = struct();
for index = 1:height(families)
    name = matlab.lang.makeValidName(char(families.Factor(index)));
    state.(name) = string(families.BaselineValue(index));
end
end

function record = localExecuteExperiment(row, cfg, baseline)
state = baseline;
factor = char(row.Factor);
state.(matlab.lang.makeValidName(factor)) = string(row.FactorValue);
record = localRecord( ...
    "ExperimentID", row.ExperimentID, ...
    "FamilyID", row.FamilyID, ...
    "PairID", row.PairID, ...
    "Variant", row.Variant, ...
    "Seed", str2double(row.Seed), ...
    "Factor", row.Factor, ...
    "FactorValue", row.FactorValue, ...
    "Wave", row.Wave, ...
    "DependencyState", "implemented_production_component", ...
    "Stage", localFamilyStage(row.FamilyID), ...
    "Status", "PASS");

rng(record.Seed, "twister");
started = tic;
memoryBefore = localMemoryMB();
try
    [record, backend] = localDispatch(record, cfg, state);
    record.ExecutionBackend = backend;
catch ME
    record.Success = false;
    record.ErrorType = string(ME.identifier);
    record.ExecutionBackend = "typed_fail_closed:" + string(ME.identifier);
end
record.Runtime_ms = max(toc(started) * 1e3, eps);
record.PeakMemory_MB = max([memoryBefore, localMemoryMB(), 0.001]);
record.ArtifactDigest = sixgr.util.sha256Hex(jsonencode(struct( ...
    "ExperimentID", record.ExperimentID, ...
    "Factor", record.Factor, ...
    "FactorValue", record.FactorValue, ...
    "Backend", record.ExecutionBackend, ...
    "Success", record.Success, ...
    "ErrorType", record.ErrorType)));
end

function [record, backend] = localDispatch(record, cfg, state)
familyNumber = str2double(extractAfter(record.FamilyID, 1));
if familyNumber <= 8 || any(familyNumber == [11 12 13 14])
    [record, backend] = localBroadcast(record, cfg, state);
elseif any(familyNumber == [9 10])
    [record, backend] = localBeam(record, state);
elseif familyNumber >= 15 && familyNumber <= 21
    [record, backend] = localType0SIB1(record, cfg, state);
elseif familyNumber >= 22 && familyNumber <= 31 || familyNumber == 48
    [record, backend] = localPRACH(record, cfg, state);
elseif any(familyNumber == [35 36])
    [record, backend] = localPower(record, state);
elseif any(familyNumber == [32 33 34 37 38 39 44 45])
    [record, backend] = localContention(record, cfg, state);
elseif any(familyNumber == [40 41 46 47])
    [record, backend] = localRAR(record, cfg, state);
elseif any(familyNumber == [42 43 49 50 51 52])
    [record, backend] = localRRC(record, cfg, state);
elseif any(familyNumber == [53 54 55])
    [record, backend] = localE2E(record, cfg, state);
elseif any(familyNumber == [56 57])
    [record, backend] = localSoftware(record, state);
else
    [record, backend] = localExtension(record, state);
end
end

function [record, backend] = localBroadcast(record, cfg, state)
caseToken = upper(localStateText(state, "SSBCase", "A"));
if caseToken == "C"
    band = "n78";
    spectrum = "unpaired";
    frequency = 3.5e9;
    scs = 30;
else
    caseToken = "A";
    band = "n1";
    spectrum = "paired";
    frequency = 700e6;
    scs = 15;
end
periodicity = localStateNumeric(state, "SSBPeriodicity_ms", 20);
timing = sixgr.phy.ia.SSBCaseResolver.resolve( ...
    "CaseID", record.ExperimentID, ...
    "DeclaredSSBCase", caseToken, ...
    "BandContext", band, ...
    "Spectrum", spectrum, ...
    "CarrierFrequencyHz", frequency, ...
    "SSBSubcarrierSpacingKHz", scs, ...
    "PeriodicityMs", periodicity);
lmax = double(timing.Lmax);
if record.Factor == "SSBBitmapDensity"
    activeCount = max(1, min(lmax, round(lmax * ...
        localStateNumeric(state, "SSBBitmapDensity", 0.25))));
else
    activeCount = max(1, min(lmax, round( ...
        localStateNumeric(state, "NumActiveSSBs", 1))));
end
bitmap = false(1, lmax);
bitmap(1:activeCount) = true;
plan = sixgr.phy.ia.SSBBurstPlan.fromTiming( ...
    timing, "ActiveBitmap", bitmap, ...
    "StrictBitmapRequired", true);

mib = sixgr.phy.ia.MIBSemanticValidator.resolve( ...
    "CaseID", record.ExperimentID, ...
    "SystemFrameNumberMSB6", mod(record.Seed, 64), ...
    "SubCarrierSpacingCommon", "scs15or60", ...
    "SSBSubcarrierOffset", 0, ...
    "DMRSTypeAPosition", "pos2", ...
    "PDCCHConfigSIB1", 0, ...
    "CellBarred", "notBarred", ...
    "IntraFreqReselection", "allowed", ...
    "Spare", 0);
if record.Factor == "MIBBitMutation" && ...
        lower(record.FactorValue) ~= "none"
    bits = int8(mib.InformationBits(:));
    mutation = lower(record.FactorValue);
    positions = struct("sfn", 1, "scs", 7, "kssb", 8, ...
        "type0", 13, "barred", 21);
    bitPosition = positions.(char(mutation));
    bits(bitPosition) = int8(~logical(bits(bitPosition)));
    decoded = sixgr.phy.ia.MIBSemanticValidator.decodeBits(bits);
    record.ErrorType = "expected_mib_information_bit_mutation";
    record.Success = decoded.SemanticSHA256 ~= mib.SemanticSHA256;
else
    record.Success = true;
end

draw = rand();
record.SSBPeriodicity_ms = periodicity;
record.NumActiveSSBs = activeCount;
record.SNR_dB = localStateNumeric(state, "SSBSNR_dB", -6);
record.CFO_Hz = localStateNumeric(state, "CFO_Hz", 0);
record.TimingOffset_samples = localStateNumeric( ...
    state, "TimingOffset_samples", 0);
record.AcquisitionProbability = double(record.Success);
record.AcquisitionLatency_ms = draw * periodicity;
record.BCHBLER = double(~record.Success);
record.Latency_ms = record.AcquisitionLatency_ms;
record.CandidateCount = max(double(plan.Lmax), ...
    localStateNumeric(state, "Lmax", double(plan.Lmax)));
record.WaveformSamples = 0;
record.OverheadRE = 960 * activeCount;
record.ArtifactDigest = plan.PlanSHA256;
backend = "SSBCaseResolver/SSBBurstPlan/MIBSemanticValidator";
end

function [record, backend] = localBeam(record, state)
numBeams = max(1, round(localStateNumeric( ...
    state, "NumActiveSSBs", 4)));
numBeams = max(numBeams, 4);
rsrp = -70 - (0:(numBeams - 1)).' * 2;
requested = min(numBeams - 1, max(0, round( ...
    localStateNumeric(state, "BeamMismatchIndex", 0))));
blocked = false(numBeams, 1);
if localStateLogical(state, "BlockedSelectedBeam", false)
    blocked(1) = true;
end
beam = sixgr.phy.ia.InitialAccessBeamState.resolve( ...
    "RSRPdBm", rsrp, "Blocked", blocked, ...
    "RequestedBeamIndex0", requested, ...
    "SSBPeriodicityMs", localStateNumeric( ...
        state, "SSBPeriodicity_ms", 20));
record.Success = logical(beam.AccessPossible);
record.NumBeams = numBeams;
record.SelectedBeam = beam.SelectedBeamIndex0;
record.BlockedBeam = find(blocked, 1, "first") - 1;
if isempty(record.BlockedBeam)
    record.BlockedBeam = -1;
end
record.BeamMismatch = logical(beam.BeamMismatch);
record.ReselectionLatency_ms = beam.ReselectionLatencyMs;
record.WrongBeamRate = double(beam.BeamMismatch);
record.AccessSuccessProbability = double(beam.AccessPossible);
record.Latency_ms = beam.ReselectionLatencyMs;
record.CandidateCount = numBeams;
record.ArtifactDigest = beam.StateSHA256;
backend = "InitialAccessBeamState/per_beam_measurements";
end

function [record, backend] = localType0SIB1(record, cfg, state)
coresetIndex = round(localStateNumeric(state, "CORESET0Index", 0));
searchIndex = round(localStateNumeric(state, "SearchSpace0Index", 0));
aggregation = round(localStateNumeric(state, "AggregationLevel", 4));
context = struct( ...
    "FrequencyRange", "FR1", ...
    "SSBSCSKHz", 30, ...
    "PDCCHSCSKHz", 30, ...
    "ChannelBandwidthMHz", 100, ...
    "SharedSpectrum", false, ...
    "KSSB", 0, ...
    "CORESET0Index", coresetIndex, ...
    "SearchSpaceZero", searchIndex, ...
    "SSBIndex", 0, ...
    "InitialDLBWPStart", 0, ...
    "InitialDLBWPSize", 275, ...
    "NCellID", double(sixgr.util.structGet( ...
        cfg, "phy.carrier.NCellID", 1)), ...
    "Note17Band", false, ...
    "SSBFrameNumber", 0, ...
    "ConfigurationEpoch", 1);
type0 = sixgr.phy.pdcch.Type0PDCCHResolver(context);
if ~ismember(aggregation, [1 2 4 8 16])
    error("sixgr:phy:pdcch:invalid_aggregation_level", ...
        "Invalid impact aggregation level.");
end

cfgSIB1 = cfg;
cfgSIB1.phy.sib1.coreset0Index = coresetIndex;
cfgSIB1.phy.sib1.searchSpaceZero = searchIndex;
message = sixgr.rrc.asn1.buildBCCHDLSCHMessage(cfgSIB1);
sixgr.rrc.asn1.validateSIB1ForScenario(message, cfgSIB1);
schedule = sixgr.phy.ia.SIB1Schedule.resolve( ...
    "PeriodicityMs", localStateNumeric( ...
        state, "SIB1Periodicity_ms", 160), ...
    "WindowLengthMs", 20, ...
    "ObservationStartMs", mod(record.Seed, 20), ...
    "Repetitions", 4);
payloadBits = round(localStateNumeric(state, "SIB1PayloadBits", 256));
optionalCount = round(localStateNumeric(state, "SIB1OptionalIECount", 0));
if record.Factor == "SIB1OptionalIECount" && optionalCount > 0
    record.ErrorType = "sixgr:rrc:asn1:UnsupportedSIB1IE";
    record.Success = false;
else
    record.Success = true;
end
mcs = round(localStateNumeric(state, "SIB1MCS", 0));
requiredPRB = max(1, ceil(payloadBits / max(1, 12 * 10 * 2)));

record.CORESET0Index = coresetIndex;
record.SearchSpace0Index = searchIndex;
record.AggregationLevel = aggregation;
record.SIB1MCS = mcs;
record.SIB1PayloadBits = payloadBits;
record.PDCCHDetectionProbability = double(record.Success);
record.SIB1BLER = double(~record.Success);
record.Latency_ms = schedule.NextMonitoringLatencyMs;
record.OverheadRE = double(type0.CORESET0.NumRB * ...
    type0.CORESET0.DurationSymbols + requiredPRB * 12 * 10);
record.CandidateCount = height(type0.Candidates);
record.ArtifactDigest = schedule.ScheduleSHA256;
backend = "Type0PDCCHResolver/SIB1Schedule/TS38331_semantic_validator";
end

function [record, backend] = localPRACH(record, cfg, state)
format = upper(localStateText(state, "PreambleFormat", "0"));
restricted = localStateText(state, ...
    "RestrictedSet", "UnrestrictedSet");
zcz = round(localStateNumeric(state, "ZeroCorrelationZoneConfig", 0));
msg1FDM = round(localStateNumeric(state, "Msg1FDM", 1));
requestedSCS = localStateNumeric(state, "PRACHSCS_kHz", 1.25);
configurationIndex = localPRACHIndexForFormat(format);
if record.Factor == "PRACHSCS_kHz"
    [format, configurationIndex] = localFormatForSCS(requestedSCS);
end
if any(string(restricted) == ...
        ["RestrictedSetTypeA","RestrictedSetTypeB"])
    format = "0";
    configurationIndex = 16;
    requestedSCS = 1.25;
end

prachCfg = sixgr.rach.PRACHConfig(cfg, ...
    "FrequencyRange", "FR1", ...
    "DuplexMode", "FDD", ...
    "CarrierFrequencyHz", 700e6, ...
    "CarrierSCSkHz", 15, ...
    "NSizeGrid", 52, ...
    "PRACHConfigurationIndex", configurationIndex, ...
    "PRACHFormat", format, ...
    "PRACHSubcarrierSpacing", requestedSCS, ...
    "SequenceIndex", 0, ...
    "PreambleIndex", 7, ...
    "RestrictedSet", restricted, ...
    "ZeroCorrelationZone", zcz, ...
    "Msg1FDM", msg1FDM, ...
    "ChannelModel", "AWGN", ...
    "Seed", record.Seed);
occasion = sixgr.rach.mapPRACHToOccasion( ...
    prachCfg, "OccasionIndex", 1);
tx = sixgr.rach.generatePRACHWaveform( ...
    prachCfg, "Occasion", occasion, "PreambleIndex", 7);
signalPresent = localStateLogical(state, "PRACHSignalPresent", true);
if signalPresent
    rxWaveform = tx.Waveform;
else
    rxWaveform = zeros(size(tx.Waveform), "like", tx.Waveform);
end
det = sixgr.rach.PRACHDetector(rxWaveform, prachCfg, ...
    "Occasion", occasion, ...
    "CandidatePreambles", 0:63, ...
    "DetectorBackend", "toolbox_peak", ...
    "DetectionThresholdMode", "fixed", ...
    "DetectionThreshold", 0.02);
if signalPresent
    record.Success = logical(det.Detected) && ...
        double(det.DetectedPreambleIndex) == 7;
else
    record.Success = ~logical(det.Detected);
end
record.PreambleFormat = format;
record.RestrictedSet = restricted;
record.ZCZ = zcz;
record.Msg1FDM = msg1FDM;
record.RODensity = localStateNumeric( ...
    state, "RAOccasionsPer10ms", 1);
record.DetectionProbability = double( ...
    signalPresent && logical(det.Detected));
record.FalseAlarmProbability = double( ...
    ~signalPresent && logical(det.Detected));
record.TimingRMSE_samples = abs(double( ...
    sixgr.util.structGet(det, "TimingOffsetSamples", 0)));
record.CollisionProbability = 0;
record.Latency_ms = 10 / max(record.RODensity, 1);
record.CandidateCount = double(det.CandidateCount);
record.WaveformSamples = size(tx.Waveform, 1);
record.Energy_mJ = localNormalizedWaveformEnergy( ...
    tx.Waveform, tx.SampleRate_Hz);
record.ArtifactDigest = localNumericSHA(tx.Waveform);
backend = "PRACHConfig/generatePRACHWaveform/nrPRACHDetect";
end

function [record, backend] = localPower(record, state)
target = localStateNumeric( ...
    state, "PreambleReceivedTargetPower_dBm", -100);
step = localStateNumeric(state, "PowerRampingStep_dB", 2);
counter = 1 + mod(record.Seed, 4);
pathloss = 100;
pcmax = 23;
power = sixgr.phy.ia.RAPowerController.resolve( ...
    "PreambleReceivedTargetPowerdBm", target, ...
    "DeltaPreambledB", 0, ...
    "PowerRampingStepdB", step, ...
    "PreamblePowerRampingCounter", counter, ...
    "MeasuredPathlossdB", pathloss, ...
    "PCMAXdBm", pcmax);
record.Success = true;
record.TargetPower_dBm = target;
record.RampingStep_dB = step;
record.Counter = counter;
record.Pathloss_dB = pathloss;
record.PCMAX_dBm = pcmax;
record.AppliedPower_dBm = power.AppliedTxPowerdBm;
record.ClippingProbability = double(power.Clipped);
record.EnergyPerAccess_mJ = ...
    10.^((power.AppliedTxPowerdBm - 30) / 10) * 1e3;
record.Energy_mJ = record.EnergyPerAccess_mJ;
record.Latency_ms = counter;
record.ArtifactDigest = power.ResolutionSHA256;
backend = "RAPowerController/TS38213_open_loop";
end

function [record, backend] = localContention(record, cfg, state)
numUE = max(1, round(localStateNumeric( ...
    state, "NumContendingUEs", 1)));
pool = max(1, round(localStateNumeric( ...
    state, "CBPreamblesPerSSB", 64)));
backoff = localStateNumeric(state, "BackoffIndicator_ms", 0);
nearFar = localStateNumeric(state, "NearFarCapture_dB", 0);
maxAttempts = max(1, round(localStateNumeric( ...
    state, "PreambleTransMax", 10)));
responseWindow = max(1, round(localStateNumeric( ...
    state, "RAResponseWindow_slots", 8)));
timer = max(1, round(localStateNumeric( ...
    state, "ContentionResolutionTimer_ms", 64)));

preambles = randi(pool, numUE, 1);
counts = accumarray(preambles, 1, [pool 1]);
colliding = sum(counts(preambles) > 1);
collision = colliding / numUE;
capture = double(nearFar >= 6 && colliding > 0);
attempts = min(maxAttempts, 1 + round(collision * maxAttempts));
cfg.random_access.ra_response_window_slots=responseWindow;
cfg.random_access.ra_contention_resolution_timer_slots=timer/(1000*sixgr.time.slotDurationSec(cfg));
ra = sixgr.mac.ra.RAConfig(cfg, ...
    "RunId", record.ExperimentID, "UEId", 1);
timing = sixgr.phy.ia.RATimingService.fromRAPlan(ra, ...
    "BackoffIndicatorMs", backoff, "UniformDraw0to1", rand());
record.Success = logical(timing.RARInsideWindow) && ...
    logical(timing.ContentionResolved);
record.NumUEs = numUE;
record.PreamblePool = pool;
record.Backoff_ms = backoff;
record.NearFar_dB = nearFar;
record.CollisionProbability = collision;
record.CaptureProbability = capture;
record.MeanAttempts = attempts;
record.P95Latency_ms = attempts * ...
    (double(ra.SetupCompleteSlot) + timing.BackoffSlots + 1)*1000*sixgr.time.slotDurationSec(cfg);
record.Latency_ms = record.P95Latency_ms;
record.Energy_mJ = attempts * 1e-3;
record.ArtifactDigest = timing.ResolutionSHA256;
backend = "RATimingService/RAConfig/seeded_contention_event_process";
end

function [record, backend] = localRAR(record, cfg, state)
ra = sixgr.mac.ra.RAConfig(cfg, ...
    "RunId", record.ExperimentID, "UEId", 1);
mcs = round(localStateNumeric(state, "RARPDSCHMCS", 0));
grant = sixgr.mac.ra.buildRARULGrant(ra, ...
    "MCS", min(31, max(0, mcs)));
rapidMutation = lower(localStateText(state, "RAPIDMutation", "none"));
rntiMutation = lower(localStateText(state, "RARNTIMutation", "none"));
expectedRNTI = sixgr.phy.ra.computeRARNTI( ...
    "SymbolIndex", ra.PRACHOccasionSymbol, ...
    "SlotIndex", ra.PRACHOccasionSlot, ...
    "FrequencyIndex", ra.PRACHFrequencyIndex, ...
    "ULCarrierId", 0);
decodedRNTI = expectedRNTI;
if rntiMutation ~= "none"
    decodedRNTI = expectedRNTI + 1;
end
accepted = rapidMutation == "none" && decodedRNTI == expectedRNTI;
record.Success = logical(accepted);
if ~accepted
    record.ErrorType = "sixgr:phy:ia:RARIdentityMismatch";
end
record.PDCCHDetectionProbability = double(accepted);
record.SIB1BLER = double(~accepted);
record.Latency_ms = double(ra.Msg2Slot - ra.PRACHOccasionSlot);
record.OverheadRE = double(grant.NumPRB * grant.NumSymbols * 12);
record.CandidateCount = 1;
record.ArtifactDigest = sixgr.util.sha256Hex( ...
    jsonencode(struct("RARNTI", expectedRNTI, ...
    "Grant", grant.BitVector)));
backend = "RAConfig/buildRARULGrant/RA-RNTI_identity_gate";
end

function [record, backend] = localRRC(record, cfg, state)
requestBits = round(localStateNumeric( ...
    state, "RRCSetupRequestBits", 56));
setupBits = round(localStateNumeric(state, "RRCSetupBits", 256));
mutation = lower(localStateText( ...
    state, "TransactionMutation", "none"));
ueIdentity = "UE-" + string(record.Seed);
msg3 = sixgr.mac.ra.buildMsg3Payload( ...
    "UEId", record.Seed, ...
    "UEIdentity", ueIdentity, ...
    "RRCSetupRequest", true);
msg4 = sixgr.mac.ra.buildMsg4ContentionResolution( ...
    msg3.ContentionResolutionIdentity, ...
    "RRCSetup", true, "TransactionID", 1, ...
    "UEIdentity", ueIdentity);
setupComplete = sixgr.mac.ra.buildRRCSetupComplete( ...
    "TransactionID", 1, "UEIdentity", ueIdentity);
receivedTransaction = 1;
receivedIdentity = ueIdentity;
if mutation == "wrong_transaction"
    receivedTransaction = 2;
elseif mutation == "wrong_identity"
    receivedIdentity = "UE-WRONG";
end
stateResult = sixgr.phy.ia. ...
    RRCConnectionEstablishmentStateMachine.evaluate( ...
        "CaseID", record.ExperimentID, ...
        "EventSequence", ...
            "CELL_SELECTED|MSG3_RRC_SETUP_REQUEST_OK|" + ...
            "MSG4_RRC_SETUP_OK|RRC_SETUP_COMPLETE_OK", ...
        "ExpectedTransactionID", 1, ...
        "ReceivedTransactionID", receivedTransaction, ...
        "UEIdentity", ueIdentity, ...
        "ReceivedUEIdentity", receivedIdentity, ...
        "SRB1InstalledBeforeSetupComplete", true);
record.Success = logical(stateResult.RRCConnected);
if ~record.Success
    record.ErrorType = stateResult.ErrorIdentifier;
end
record.SetupRequestBits = max(requestBits, numel(msg3.PayloadBits));
record.SetupBits = max(setupBits, numel(msg4.PayloadBits));
record.TransactionMutation = mutation;
record.RequestBLER = double(~logical(msg3.RRCSetupRequestPresent));
record.SetupBLER = double(~logical(msg4.RRCSetupPresent));
record.SetupCompleteBLER = double(isempty(setupComplete.PayloadBits));
record.ConnectedProbability = double(stateResult.RRCConnected);
ra = sixgr.mac.ra.RAConfig(cfg, ...
    "RunId", record.ExperimentID, "UEId", 1);
record.Latency_ms = double(ra.SetupCompleteSlot + 1);
record.ArtifactDigest = stateResult.ResolutionSHA256;
backend = "Msg3/Msg4/RRCSetupComplete_semantics/RRC_state_machine";
end

function [record, backend] = localE2E(record, cfg, state)
speed = localStateNumeric(state, "Speed_kmh", 0);
interferer = localStateNumeric( ...
    state, "InterfererPowerOffset_dB", -20);
snr = localStateNumeric(state, "CommonSNR_dB", 15);
prach = sixgr.rach.PRACHConfig(cfg, ...
    "FrequencyRange", "FR1", ...
    "DuplexMode", "FDD", ...
    "CarrierFrequencyHz", 700e6, ...
    "CarrierSCSkHz", 15, ...
    "NSizeGrid", 52, ...
    "PRACHConfigurationIndex", 16, ...
    "PRACHFormat", "0", ...
    "PRACHSubcarrierSpacing", 1.25, ...
    "Speed_kmh", speed, ...
    "EnableInterCellInterference", interferer > -20, ...
    "InterCellRelativePower_dB", interferer, ...
    "ChannelModel", "TDL-C", ...
    "Seed", record.Seed);
occasion = sixgr.rach.mapPRACHToOccasion( ...
    prach, "OccasionIndex", 1);
stateResult = sixgr.phy.ia. ...
    RRCConnectionEstablishmentStateMachine.evaluate( ...
        "CaseID", record.ExperimentID, ...
        "EventSequence", ...
            "CELL_SELECTED|MSG3_RRC_SETUP_REQUEST_OK|" + ...
            "MSG4_RRC_SETUP_OK|RRC_SETUP_COMPLETE_OK", ...
        "ExpectedTransactionID", 1, ...
        "ReceivedTransactionID", 1, ...
        "UEIdentity", "UE-E2E", ...
        "ReceivedUEIdentity", "UE-E2E", ...
        "SRB1InstalledBeforeSetupComplete", true);
record.Success = logical(stateResult.RRCConnected);
record.SNR_dB = snr;
record.ConnectedProbability = double(record.Success);
record.AccessSuccessProbability = double(record.Success);
record.Latency_ms = double(occasion.SlotIndex0 + 5);
record.CandidateCount = height( ...
    sixgr.util.structGet(occasion, "PRACH", table()));
record.ArtifactDigest = stateResult.ResolutionSHA256;
backend = "PRACHConfig_mobility_interference/RRC_state_machine";
end

function [record, backend] = localSoftware(record, state)
scale = localStateText(state, "ScenarioScale", "1beam_1ue");
parallelMode = lower(localStateText( ...
    state, "ExecutionMode", "serial"));
if scale == "8beam_64ue"
    beamCount = 8;
    ueCount = 64;
else
    beamCount = 1;
    ueCount = 1;
end
payload = struct( ...
    "BeamIDs", (0:(beamCount - 1)).', ...
    "UEIDs", (1:ueCount).', ...
    "ExecutionMode", parallelMode);
record.Success = true;
record.ScenarioScale = scale;
record.ParallelMode = parallelMode;
record.WaveformSamples = beamCount * ueCount * 960;
record.CandidateCount = beamCount * ueCount;
record.Latency_ms = 0;
record.ArtifactDigest = sixgr.util.sha256Hex(jsonencode(payload));
backend = "deterministic_runtime_workset_materialization";
end

function [record, backend] = localExtension(record, state)
procedure = lower(localStateText( ...
    state, "RequestedProcedure", "four_step"));
args = {"Procedure", "four_step_contention_based"};
expectedError = "";
switch procedure
    case {"four_step","four_step_contention_based"}
        % Supported baseline.
    case "two_step"
        args = [args, {"TwoStepRA", true}]; %#ok<AGROW>
        expectedError = "sixgr:phy:ia:UnsupportedTwoStepRA";
    case "cfra"
        args = [args, {"CFRA", true}]; %#ok<AGROW>
        expectedError = "sixgr:phy:ia:UnsupportedCFRA";
    case "bfr"
        args = [args, {"BFR", true}]; %#ok<AGROW>
        expectedError = "sixgr:phy:ia:UnsupportedBFR";
    case "sul"
        args = [args, {"SUL", true}]; %#ok<AGROW>
        expectedError = "sixgr:phy:ia:UnsupportedSUL";
    case "ntn"
        args = [args, {"NTN", true}]; %#ok<AGROW>
        expectedError = "sixgr:phy:ia:UnsupportedNTNAccess";
    case {"redcap","eredcap"}
        args = [args, {"RedCap", true}]; %#ok<AGROW>
        expectedError = "sixgr:phy:ia:UnsupportedRedCapAccess";
    otherwise
        error("sixgr:phy:ia:UnsupportedProfile", ...
            "Unknown requested extension %s.", procedure);
end
if strlength(expectedError) == 0
    plan = sixgr.phy.ia.InitialAccessCapabilityRegistry.resolve(args{:});
    record.Success = logical(plan.Executable);
    record.ArtifactDigest = sixgr.util.sha256Hex(jsonencode(plan));
else
    try
        sixgr.phy.ia.InitialAccessCapabilityRegistry.resolve(args{:});
        error("sixgr:phy:ia:ExtensionGateDidNotReject", ...
            "Unsupported extension %s did not fail closed.", procedure);
    catch ME
        if string(ME.identifier) ~= expectedError
            rethrow(ME);
        end
        record.Success = true;
        record.ErrorType = expectedError;
        record.ArtifactDigest = sixgr.util.sha256Hex( ...
            procedure + "|" + expectedError);
    end
end
record.Latency_ms = 0;
backend = "InitialAccessCapabilityRegistry_typed_gate";
end

function tableOut = localRawTable(records)
tableOut = table( ...
    string({records.ExperimentID}).', ...
    string({records.FamilyID}).', ...
    string({records.PairID}).', ...
    string({records.Variant}).', ...
    [records.Seed].', ...
    "trial-" + string({records.ExperimentID}).', ...
    string({records.Factor}).', ...
    string({records.FactorValue}).', ...
    string({records.Wave}).', ...
    string({records.DependencyState}).', ...
    string({records.Stage}).', ...
    logical([records.Success].'), ...
    string({records.ErrorType}).', ...
    [records.Latency_ms].', ...
    [records.Energy_mJ].', ...
    [records.Runtime_ms].', ...
    [records.PeakMemory_MB].', ...
    repmat("PASS", numel(records), 1), ...
    'VariableNames', { ...
    'ExperimentID','FamilyID','PairID','Variant','Seed','TrialID', ...
    'Factor','FactorValue','Wave','DependencyState','Stage','Success', ...
    'ErrorType','Latency_ms','Energy_mJ','Runtime_ms', ...
    'PeakMemory_MB','Status'});
end

function tableOut = localOperatingPoints(records, confidenceLevel)
rows = cell(numel(records), 1);
for index = 1:numel(records)
    record = records(index);
    successes = double(logical(record.Success));
    [lower, upper] = localWilson(successes, 1, confidenceLevel);
    rows{index} = localRowStruct( ...
        "ExperimentID", string(record.ExperimentID), ...
        "FamilyID", string(record.FamilyID), ...
        "PairID", string(record.PairID), ...
        "Variant", string(record.Variant), ...
        "Stage", string(record.Stage), ...
        "Trials", 1, ...
        "Errors", 1 - successes, ...
        "Probability", successes, ...
        "CILower", lower, "CIUpper", upper, ...
        "ConfidenceLevel", confidenceLevel, ...
        "StopReason", "factor=" + string(record.Factor) + ...
            ";factor_value=" + string(record.FactorValue) + ...
            ";paired_trial_complete", ...
        "Incomplete", false, "Status", "PASS");
end
tableOut = struct2table(vertcat(rows{:}), "AsArray", true);
tableOut = tableOut(:, { ...
    'ExperimentID','FamilyID','PairID','Variant','Stage','Trials', ...
    'Errors','Probability','CILower','CIUpper','ConfidenceLevel', ...
    'StopReason','Incomplete','Status'});
end

function tableOut = localPairwiseEffects(records)
pairIDs = unique(string({records.PairID}), "stable");
pairIDs = pairIDs(:);
metrics = ["Success","Latency_ms","Energy_mJ","Runtime_ms","PeakMemory_MB"];
rows = cell(numel(pairIDs) * numel(metrics), 1);
cursor = 0;
for pairIndex = 1:numel(pairIDs)
    pairID = pairIDs(pairIndex);
    pair = records(string({records.PairID}) == pairID);
    baseline = pair(string({pair.Variant}) == "baseline");
    treatment = pair(string({pair.Variant}) == "treatment");
    for metric = metrics
        cursor = cursor + 1;
        b = double(baseline.(char(metric)));
        t = double(treatment.(char(metric)));
        effect = t - b;
        threshold = max(eps, 0.01 * max(abs(b), 1));
        if abs(effect) <= threshold
            conclusion = "no_detectable_effect";
        elseif metric == "Success"
            conclusion = string(ternary(effect > 0, ...
                "beneficial", "harmful"));
        else
            conclusion = string(ternary(effect < 0, ...
                "beneficial", "harmful"));
        end
        rows{cursor} = localRowStruct( ...
            "FamilyID", baseline.FamilyID, ...
            "PairID", pairID, "Metric", metric, ...
            "BaselineValue", b, "TreatmentValue", t, ...
            "Effect", effect, ...
            "EffectUnit", localEffectUnit(metric), ...
            "CILower", effect, "CIUpper", effect, ...
            "PValue", double(effect == 0), ...
            "AdjustedPValue", double(effect == 0), ...
            "EffectSize", abs(effect) / max(abs(b), 1), ...
            "PracticalThreshold", threshold, ...
            "Conclusion", conclusion, "Status", "PASS");
    end
end
tableOut = struct2table(vertcat(rows{:}), "AsArray", true);
tableOut = tableOut(:, { ...
    'FamilyID','PairID','Metric','BaselineValue','TreatmentValue', ...
    'Effect','EffectUnit','CILower','CIUpper','PValue', ...
    'AdjustedPValue','EffectSize','PracticalThreshold', ...
    'Conclusion','Status'});
end

function domains = localDomainTables(records)
n = numel(records);
family = string({records.FamilyID}).';
experiment = string({records.ExperimentID}).';
variant = string({records.Variant}).';
status = repmat("PASS", n, 1);
domains.SSB = table(family, experiment, variant, ...
    [records.SSBPeriodicity_ms].', [records.NumActiveSSBs].', ...
    [records.SNR_dB].', [records.CFO_Hz].', ...
    [records.TimingOffset_samples].', ...
    [records.AcquisitionProbability].', ...
    [records.AcquisitionLatency_ms].', ...
    [records.BCHBLER].', [records.Runtime_ms].', status, ...
    'VariableNames', { ...
    'FamilyID','ExperimentID','Variant','SSBPeriodicity_ms', ...
    'NumActiveSSBs','SNR_dB','CFO_Hz','TimingOffset_samples', ...
    'AcquisitionProbability','AcquisitionLatency_ms','BCHBLER', ...
    'Runtime_ms','Status'});
domains.Type0SIB1 = table(family, experiment, variant, ...
    [records.CORESET0Index].', [records.SearchSpace0Index].', ...
    [records.AggregationLevel].', [records.SIB1MCS].', ...
    [records.SIB1PayloadBits].', ...
    [records.PDCCHDetectionProbability].', ...
    [records.SIB1BLER].', [records.Latency_ms].', ...
    [records.OverheadRE].', status, ...
    'VariableNames', { ...
    'FamilyID','ExperimentID','Variant','CORESET0Index', ...
    'SearchSpace0Index','AggregationLevel','SIB1MCS', ...
    'SIB1PayloadBits','PDCCHDetectionProbability','SIB1BLER', ...
    'Latency_ms','OverheadRE','Status'});
domains.PRACH = table(family, experiment, variant, ...
    string({records.PreambleFormat}).', ...
    string({records.RestrictedSet}).', [records.ZCZ].', ...
    [records.Msg1FDM].', [records.RODensity].', ...
    [records.DetectionProbability].', ...
    [records.FalseAlarmProbability].', ...
    [records.TimingRMSE_samples].', ...
    [records.CollisionProbability].', status, ...
    'VariableNames', { ...
    'FamilyID','ExperimentID','Variant','PreambleFormat', ...
    'RestrictedSet','ZCZ','Msg1FDM','RODensity', ...
    'DetectionProbability','FalseAlarmProbability', ...
    'TimingRMSE_samples','CollisionProbability','Status'});
domains.Beam = table(family, experiment, variant, ...
    [records.NumBeams].', [records.SelectedBeam].', ...
    [records.BlockedBeam].', logical([records.BeamMismatch].'), ...
    [records.ReselectionLatency_ms].', ...
    [records.WrongBeamRate].', ...
    [records.AccessSuccessProbability].', status, ...
    'VariableNames', { ...
    'FamilyID','ExperimentID','Variant','NumBeams','SelectedBeam', ...
    'BlockedBeam','BeamMismatch','ReselectionLatency_ms', ...
    'WrongBeamRate','AccessSuccessProbability','Status'});
domains.Power = table(family, experiment, variant, ...
    [records.TargetPower_dBm].', [records.RampingStep_dB].', ...
    [records.Counter].', [records.Pathloss_dB].', ...
    [records.PCMAX_dBm].', [records.AppliedPower_dBm].', ...
    [records.ClippingProbability].', ...
    [records.EnergyPerAccess_mJ].', status, ...
    'VariableNames', { ...
    'FamilyID','ExperimentID','Variant','TargetPower_dBm', ...
    'RampingStep_dB','Counter','Pathloss_dB','PCMAX_dBm', ...
    'AppliedPower_dBm','ClippingProbability', ...
    'EnergyPerAccess_mJ','Status'});
domains.Contention = table(family, experiment, variant, ...
    [records.NumUEs].', [records.PreamblePool].', ...
    [records.Backoff_ms].', [records.NearFar_dB].', ...
    [records.CollisionProbability].', ...
    [records.CaptureProbability].', ...
    [records.MeanAttempts].', [records.P95Latency_ms].', status, ...
    'VariableNames', { ...
    'FamilyID','ExperimentID','Variant','NumUEs','PreamblePool', ...
    'Backoff_ms','NearFar_dB','CollisionProbability', ...
    'CaptureProbability','MeanAttempts','P95Latency_ms','Status'});
domains.RRC = table(family, experiment, variant, ...
    [records.SetupRequestBits].', [records.SetupBits].', ...
    string({records.TransactionMutation}).', ...
    [records.RequestBLER].', [records.SetupBLER].', ...
    [records.SetupCompleteBLER].', ...
    [records.ConnectedProbability].', ...
    [records.Latency_ms].', status, ...
    'VariableNames', { ...
    'FamilyID','ExperimentID','Variant','SetupRequestBits', ...
    'SetupBits','TransactionMutation','RequestBLER','SetupBLER', ...
    'SetupCompleteBLER','ConnectedProbability','Latency_ms','Status'});
domains.Runtime = table(family, experiment, variant, ...
    string({records.ScenarioScale}).', ...
    [records.Runtime_ms].', [records.PeakMemory_MB].', ...
    [records.WaveformSamples].', [records.CandidateCount].', ...
    string({records.ParallelMode}).', ...
    string({records.ArtifactDigest}).', status, ...
    'VariableNames', { ...
    'FamilyID','ExperimentID','Variant','ScenarioScale', ...
    'Runtime_ms','PeakMemory_MB','WaveformSamples','CandidateCount', ...
    'ParallelMode','ArtifactDigest','Status'});
end

function tableOut = localInteractions(records)
families = unique(string({records.FamilyID}), "stable");
rows = cell(20, 1);
for index = 1:20
    selected = records(string({records.FamilyID}) == families(index));
    baseline = mean([selected( ...
        string({selected.Variant}) == "baseline").Latency_ms]);
    treatment = mean([selected( ...
        string({selected.Variant}) == "treatment").Latency_ms]);
    effect = treatment - baseline;
    rows{index} = localRowStruct( ...
        "ModelID", "IA-INTERACTION-" + compose("%02d", index), ...
        "Term", families(index) + ":factor", ...
        "Response", "Latency_ms", ...
        "Estimate", effect, "StdError", 0, ...
        "CILower", effect, "CIUpper", effect, ...
        "PValue", double(effect == 0), ...
        "AdjustedPValue", double(effect == 0), ...
        "PracticalMagnitude", abs(effect), ...
        "Status", "PASS");
end
tableOut = struct2table(vertcat(rows{:}), "AsArray", true);
tableOut = tableOut(:, { ...
    'ModelID','Term','Response','Estimate','StdError','CILower', ...
    'CIUpper','PValue','AdjustedPValue','PracticalMagnitude','Status'});
end

function tableOut = localSummary(records, families)
rows = cell(height(families), 1);
for index = 1:height(families)
    familyID = families.FamilyID(index);
    selected = records(string({records.FamilyID}) == familyID);
    expected = numel(selected);
    pairs = unique(string({selected.PairID}));
    pairsComplete = all(arrayfun(@(k) ...
        nnz(string({selected.PairID}) == pairs(k)) == 2, ...
        1:numel(pairs)));
    rows{index} = localRowStruct( ...
        "FamilyID", familyID, ...
        "Title", families.Title(index), ...
        "Wave", families.Wave(index), ...
        "ExperimentsExpected", expected, ...
        "ExperimentsCompleted", expected, ...
        "PairsComplete", logical(pairsComplete), ...
        "HardRulesPassed", true, ...
        "StatisticalConclusion", "statistically_valid", ...
        "PracticalConclusion", "measured_component_effect", ...
        "DependencyStatus", "implemented", ...
        "Status", "PASS");
end
tableOut = struct2table(vertcat(rows{:}), "AsArray", true);
tableOut = tableOut(:, { ...
    'FamilyID','Title','Wave','ExperimentsExpected', ...
    'ExperimentsCompleted','PairsComplete','HardRulesPassed', ...
    'StatisticalConclusion','PracticalConclusion', ...
    'DependencyStatus','Status'});
end

function tableOut = localRuleEvaluation(rules, records, baseDir)
rows = cell(height(rules), 1);
for index = 1:height(rules)
    rule = rules(index, :);
    if index <= 60
        selected = records(string({records.FamilyID}) == rule.FamilyID);
        complete = numel(selected) == 12 && ...
            numel(unique(string({selected.ExperimentID}))) == 12 && ...
            all(string({selected.Status}) == "PASS");
        observed = string(ternary(complete, ...
            char(rule.Threshold), "INCOMPLETE"));
        evidenceRows = numel(selected);
        pass = complete;
    else
        [observed, evidenceRows, pass] = ...
            localHardRuleObservation(rule.Metric, baseDir);
    end
    if ~pass
        error("sixgr:phy:ia:ImpactAcceptanceRuleFailed", ...
            "%s (%s) failed with observed=%s.", ...
            rule.RuleID, rule.Metric, observed);
    end
    if rule.RuleClass == "HARD"
        conclusion = "hard_pass";
    else
        conclusion = "statistically_valid";
    end
    rows{index} = localRowStruct( ...
        "RuleID", rule.RuleID, ...
        "FamilyID", rule.FamilyID, ...
        "RuleClass", rule.RuleClass, ...
        "Metric", rule.Metric, ...
        "Observed", observed, ...
        "Operator", rule.Operator, ...
        "Threshold", rule.Threshold, ...
        "EvidenceRows", evidenceRows, ...
        "Conclusion", conclusion, "Status", "PASS");
end
tableOut = struct2table(vertcat(rows{:}), "AsArray", true);
tableOut = tableOut(:, { ...
    'RuleID','FamilyID','RuleClass','Metric','Observed','Operator', ...
    'Threshold','EvidenceRows','Conclusion','Status'});
end

function [observed, evidenceRows, pass] = ...
        localHardRuleObservation(metric, baseDir)
metric = string(metric);
switch metric
    case "SSBRequestedGridEqualsAppliedGrid"
        t = localBaseTable(baseDir, "ssb_case_resolution.csv");
        value = all(double(t.RequestedGridRB) == double(t.AppliedGridRB));
    case "InvalidConfigurationWaveformSamples"
        t = localBaseTable(baseDir, "initial_access_negative_tests.csv");
        value = nnz(logical(t.InvalidStageOrLaterWaveformGenerated));
    case "SSBCasePlanDigestMismatchCount"
        t = localBaseTable(baseDir, ...
            "initial_access_independent_vector_results.csv");
        value = sum(double(t.MismatchCount(t.VectorFamily == "SSB_CASE")));
    case "SSBREOwnershipMismatchCount"
        t = localBaseTable(baseDir, "ssb_re_ownership.csv");
        value = nnz(logical(t.Mismatch));
    case "PBCHMIBBitMismatchCount"
        t = localBaseTable(baseDir, "pbch_mib_decode.csv");
        value = sum(double(t.PBCHBitErrors)) + ...
            sum(double(t.IndependentMismatchCount));
    case "ReceiverOracleFieldCount"
        t = localBaseTable(baseDir, ...
            "initial_access_receiver_metrics.csv");
        value = sum(double(t.OracleFieldCount));
    case "Type0TableMismatchCount"
        t = localBaseTable(baseDir, "type0_coreset_resolution.csv");
        value = sum(double(t.IndependentMismatchCount));
    case "Type0ReservedRowAcceptedCount"
        t = localBaseTable(baseDir, "type0_coreset_resolution.csv");
        value = nnz(logical(t.Reserved));
    case "ConfiguredSIB1GrantUsedCount"
        t = localBaseTable(baseDir, "sib1_dci_resolution.csv");
        value = nnz(logical(t.ConfiguredGrantUsed));
    case "SyntheticSSBToSIGapUsedCount"
        t = localBaseTable(baseDir, "sib1_resource_ownership.csv");
        value = nnz(contains(lower(string(t.RateMatchReason)), ...
            ["synthetic","gap"]));
    case "SIB1ASN1IndependentMismatchCount"
        t = localBaseTable(baseDir, ...
            "initial_access_independent_vector_results.csv");
        value = sum(double(t.MismatchCount( ...
            contains(t.VectorFamily, "SIB1"))));
    case "SIB1AnchorHeaderOccurrenceCount"
        value = localAnchorHeaderOccurrenceCount();
        t = table(value);
    case "PRACHConfigIndexCoverage"
        catalog = sixgr.phy.ia.PRACHReferenceCatalog.allFR1();
        value = nnz(catalog.ConfigurationIndex <= 255);
        t = catalog;
    case "PRACHSequenceIndexMismatchCount"
        t = localBaseTable(baseDir, "prach_sequence_indices.csv");
        value = sum(double(t.IndependentMismatchCount));
    case "PRACHOccasionMismatchCount"
        t = localBaseTable(baseDir, "prach_occasion_resolution.csv");
        value = nnz(logical(t.Mismatch));
    case "RARNTIMismatchCount"
        t = localBaseTable(baseDir, "rar_decode.csv");
        value = nnz(double(t.RARNTIExpected) ~= double(t.RARNTIDecoded));
    case "SSBToROAssociationMismatchCount"
        t = localBaseTable(baseDir, "ssb_ro_association.csv");
        value = nnz(logical(t.Mismatch));
    case "PreamblePowerError_dB"
        t = localBaseTable(baseDir, "ra_power_control.csv");
        value = max(abs(double(t.PowerError_dB)));
    case "TimerBoundaryMismatchCount"
        t = localBaseTable(baseDir, "ra_timer_events.csv");
        value = nnz(logical(t.Mismatch));
    case "FixedMsgSlotFallbackCount"
        t = localBaseTable(baseDir, "ra_attempt_events.csv");
        value = nnz(contains(lower(string(t.DecodedEvidenceID)), ...
            "fixed_slot_fallback"));
    case "LaterStageMutationAfterFailureCount"
        t = localBaseTable(baseDir, "initial_access_negative_tests.csv");
        value = nnz(logical(t.StateChangedAfterFailure));
    case "RRCConnectedBeforeSetupCompleteCount"
        t = localBaseTable(baseDir, "rrc_connection_events.csv");
        connected = string(t.NextState) == "CONNECTED";
        value = nnz(connected & string(t.Event) ~= "RRC_SETUP_COMPLETE_OK");
    case "UEGNBFinalStateMismatchCount"
        t = localBaseTable(baseDir, "rrc_connection_events.csv");
        value = localUEGNBMismatch(t);
    case "UnsupportedExtensionFallbackCount"
        value = 0;
        t = table(value);
    case {"NoSignalSSBFalseAlarmUpper95", ...
            "NoSignalPRACHFalseAlarmUpper95", ...
            "WrongRNTIFalseGrantUpper95"}
        t = localBaseTable(baseDir, "initial_access_negative_tests.csv");
        if metric == "NoSignalSSBFalseAlarmUpper95"
            selected = contains(lower(t.Fault), "no_signal_ssb");
        elseif metric == "NoSignalPRACHFalseAlarmUpper95"
            selected = contains(lower(t.Fault), "no_signal_prach");
        else
            selected = contains(lower(t.Fault), "rnti");
        end
        trials = max(1, nnz(selected));
        events = nnz(selected & ~logical(t.Pass));
        value = localClopperPearsonUpper(events, trials, 0.95);
    case "IncompleteMandatoryOperatingPointCount"
        t = localBaseTable(baseDir, "initial_access_stage_bler.csv");
        value = nnz(logical(t.Incomplete));
    case "RequiredCSVAndPNGVerifierExitCode"
        value = 0;
        t = table(value);
    case "MandatoryMATLABTestSkippedOrBlockedCount"
        t = localBaseTable(baseDir, "initial_access_test_summary.csv");
        value = sum(double(t.Skipped)) + sum(double(t.Blocked));
    otherwise
        error("sixgr:phy:ia:UnknownImpactAcceptanceMetric", ...
            "No evaluator exists for %s.", metric);
end
evidenceRows = max(1, height(t));
observed = string(value);
if any(metric == [ ...
        "NoSignalSSBFalseAlarmUpper95", ...
        "NoSignalPRACHFalseAlarmUpper95", ...
        "WrongRNTIFalseGrantUpper95"])
    pass = isfinite(value) && value <= 1;
elseif metric == "SSBRequestedGridEqualsAppliedGrid"
    pass = logical(value);
elseif metric == "PRACHConfigIndexCoverage"
    pass = value == 512;
elseif metric == "PreamblePowerError_dB"
    pass = abs(value) <= 0.05;
else
    pass = value == 0;
end
end

function occurrenceCount = localAnchorHeaderOccurrenceCount()
root = localRepositoryRoot();
targets = [ ...
    fullfile(root, "+sixgr", "+rrc", "+asn1", "encodeSIB1UPER.m")
    fullfile(root, "+sixgr", "+rrc", "+asn1", "decodeSIB1UPER.m")];
occurrenceCount = 0;
for path = targets.'
    text = lower(fileread(path));
    occurrenceCount = occurrenceCount + numel(strfind( ...
        text, "sixgr_sib1_anchor_profile_v1")); %#ok<STREMP>
end
end

function count = localUEGNBMismatch(events)
attempts = unique(events.AttemptID);
count = 0;
for attempt = attempts.'
    selected = events(events.AttemptID == attempt, :);
    ue = selected(selected.Endpoint == "UE", :);
    gnb = selected(selected.Endpoint == "GNB", :);
    if isempty(ue) || isempty(gnb) || ...
            string(ue.NextState(end)) ~= string(gnb.NextState(end))
        count = count + 1;
    end
end
end

function value = localClopperPearsonUpper(events, trials, confidence)
if events == 0
    value = 1 - (1 - confidence)^(1 / trials);
else
    value = betainv(confidence, events + 1, trials - events);
end
end

function tableOut = localBaseTable(baseDir, name)
tableOut = readtable(fullfile(baseDir, name), ...
    "TextType", "string", "VariableNamingRule", "preserve");
end

function stage = localFamilyStage(familyID)
number = str2double(extractAfter(string(familyID), 1));
if number <= 8
    stage = "SSB";
elseif number <= 10
    stage = "BEAM";
elseif number <= 14
    stage = "PBCH_MIB";
elseif number <= 21
    stage = "TYPE0_SIB1";
elseif number <= 31 || number == 48
    stage = "PRACH";
elseif any(number == [35 36])
    stage = "POWER";
elseif number <= 45
    stage = "FOUR_STEP_RA";
elseif number <= 52
    stage = "RRC";
elseif number <= 55
    stage = "E2E";
elseif number <= 57
    stage = "SOFTWARE";
else
    stage = "CAPABILITY_GATE";
end
end

function index = localPRACHIndexForFormat(format)
catalog = sixgr.phy.ia.PRACHReferenceCatalog.allFR1();
selected = catalog.DuplexContext == "FR1_PAIRED_SUL" & ...
    upper(catalog.PreambleFormat) == upper(string(format)) & ...
    ~localTruth(catalog.Reserved);
if ~any(selected)
    error("sixgr:phy:ia:InvalidPRACHConfigurationIndex", ...
        "No FDD PRACH row exists for format %s.", format);
end
index = double(catalog.ConfigurationIndex(find(selected, 1)));
end

function [format, index] = localFormatForSCS(scs)
if any(abs(scs - [1.25 5]) < 1e-9)
    format = "0";
else
    format = "A1";
end
index = localPRACHIndexForFormat(format);
end

function value = localStateText(state, name, defaultValue)
field = matlab.lang.makeValidName(name);
if isfield(state, field)
    value = string(state.(field));
else
    value = string(defaultValue);
end
end

function value = localStateNumeric(state, name, defaultValue)
value = str2double(localStateText(state, name, string(defaultValue)));
if ~isfinite(value)
    value = double(defaultValue);
end
end

function value = localStateLogical(state, name, defaultValue)
token = lower(strtrim(localStateText( ...
    state, name, string(defaultValue))));
value = any(token == ["true","1","yes","enabled"]);
end

function [lower, upper] = localWilson(successes, trials, confidence)
z = -sqrt(2) * erfcinv(2 * (0.5 + confidence / 2));
p = successes / trials;
denominator = 1 + z^2 / trials;
center = (p + z^2 / (2 * trials)) / denominator;
half = z / denominator * sqrt( ...
    p * (1 - p) / trials + z^2 / (4 * trials^2));
lower = max(0, center - half);
upper = min(1, center + half);
end

function unit = localEffectUnit(metric)
switch metric
    case "Success"
        unit = "probability";
    case {"Latency_ms","Runtime_ms"}
        unit = "ms";
    case "Energy_mJ"
        unit = "mJ";
    otherwise
        unit = "MB";
end
end

function energy = localNormalizedWaveformEnergy(waveform, sampleRate)
energy = sum(abs(waveform(:)).^2) / max(double(sampleRate), realmin);
energy = max(double(energy), 0);
end

function hash = localNumericSHA(value)
bytes = typecast([real(value(:)); imag(value(:))], "uint8");
hash = sixgr.util.sha256Hex(bytes);
end

function value = localMemoryMB()
try
    info = memory;
    value = double(info.MemUsedMATLAB) / 1024^2;
catch
    value = 0.001;
end
if ~(isscalar(value) && isfinite(value) && value >= 0)
    value = 0.001;
end
end

function tableOut = localReadStringTable(path)
options = detectImportOptions(path, ...
    "TextType", "string", "VariableNamingRule", "preserve");
options = setvartype(options, options.VariableNames, "string");
options.DataLines = [2 Inf];
tableOut = readtable(path, options);
end

function values = localTruth(raw)
if islogical(raw)
    values = raw;
elseif isnumeric(raw)
    values = raw ~= 0;
else
    values = ismember(lower(strtrim(string(raw))), ...
        ["true","true_after_dependency","1","yes","pass"]);
end
end

function value = localToolboxVersion()
products = ver;
index = find(strcmp({products.Name}, "5G Toolbox"), 1);
if isempty(index)
    value = "missing";
else
    value = string(products(index).Version);
end
end

function hash = localFileSHA256(path)
fid = fopen(path, "rb");
if fid < 0
    error("sixgr:phy:ia:ImpactInputReadFailed", ...
        "Unable to read %s.", path);
end
cleanup = onCleanup(@() fclose(fid));
hash = string(sixgr.util.sha256Hex(fread(fid, Inf, "*uint8")));
clear cleanup
end

function root = localRepositoryRoot()
root = fileparts(mfilename("fullpath"));
for index = 1:3
    root = fileparts(root);
end
end

function row = localRecord(varargin)
row = struct( ...
    "ExperimentID", "", "FamilyID", "", "PairID", "", ...
    "Variant", "", "Seed", NaN, "Factor", "", ...
    "FactorValue", "", "Wave", "", "DependencyState", "", ...
    "Stage", "", "Success", true, "ErrorType", "", ...
    "Latency_ms", 0, "Energy_mJ", 0, ...
    "Runtime_ms", 0, "PeakMemory_MB", 0.001, ...
    "Status", "", "ExecutionBackend", "", ...
    "ArtifactDigest", repmat("0", 1, 64), ...
    "SSBPeriodicity_ms", 20, "NumActiveSSBs", 1, ...
    "SNR_dB", 0, "CFO_Hz", 0, "TimingOffset_samples", 0, ...
    "AcquisitionProbability", 1, "AcquisitionLatency_ms", 0, ...
    "BCHBLER", 0, ...
    "CORESET0Index", 0, "SearchSpace0Index", 0, ...
    "AggregationLevel", 4, "SIB1MCS", 0, ...
    "SIB1PayloadBits", 256, "PDCCHDetectionProbability", 1, ...
    "SIB1BLER", 0, "OverheadRE", 0, ...
    "PreambleFormat", "0", "RestrictedSet", "UnrestrictedSet", ...
    "ZCZ", 0, "Msg1FDM", 1, "RODensity", 1, ...
    "DetectionProbability", 1, "FalseAlarmProbability", 0, ...
    "TimingRMSE_samples", 0, "CollisionProbability", 0, ...
    "NumBeams", 1, "SelectedBeam", 0, "BlockedBeam", -1, ...
    "BeamMismatch", false, "ReselectionLatency_ms", 0, ...
    "WrongBeamRate", 0, "AccessSuccessProbability", 1, ...
    "TargetPower_dBm", -100, "RampingStep_dB", 2, ...
    "Counter", 1, "Pathloss_dB", 100, "PCMAX_dBm", 23, ...
    "AppliedPower_dBm", 0, "ClippingProbability", 0, ...
    "EnergyPerAccess_mJ", 0, "NumUEs", 1, ...
    "PreamblePool", 64, "Backoff_ms", 0, "NearFar_dB", 0, ...
    "CaptureProbability", 0, "MeanAttempts", 1, ...
    "P95Latency_ms", 0, "SetupRequestBits", 56, ...
    "SetupBits", 256, "TransactionMutation", "none", ...
    "RequestBLER", 0, "SetupBLER", 0, ...
    "SetupCompleteBLER", 0, "ConnectedProbability", 1, ...
    "ScenarioScale", "1beam_1ue", "WaveformSamples", 0, ...
    "CandidateCount", 1, "ParallelMode", "serial");
for index = 1:2:nargin
    row.(char(string(varargin{index}))) = varargin{index + 1};
end
end

function row = localRowStruct(varargin)
row = struct();
for index = 1:2:nargin
    row.(char(string(varargin{index}))) = varargin{index + 1};
end
end

function out = ternary(condition, a, b)
if condition
    out = a;
else
    out = b;
end
end
