classdef RAPowerController
    %RAPOWERCONTROLLER Exact Msg1 open-loop/ramping power resolution.

    methods (Static)
        function result = resolve(varargin)
            p = inputParser;
            p.FunctionName = ...
                "sixgr.phy.ia.RAPowerController.resolve";
            addParameter(p, "PreambleReceivedTargetPowerdBm", ...
                NaN, @localFiniteScalar);
            addParameter(p, "DeltaPreambledB", 0, @localFiniteScalar);
            addParameter(p, "PowerRampingStepdB", ...
                NaN, @localNonnegativeFinite);
            addParameter(p, "PreamblePowerRampingCounter", ...
                NaN, @localPositiveInteger);
            addParameter(p, "MeasuredPathlossdB", ...
                NaN, @localNonnegativeFinite);
            addParameter(p, "PCMAXdBm", NaN, @localFiniteScalar);
            parse(p, varargin{:});
            opt = p.Results;

            target = double(opt.PreambleReceivedTargetPowerdBm) + ...
                double(opt.DeltaPreambledB) + ...
                (double(opt.PreamblePowerRampingCounter) - 1) * ...
                double(opt.PowerRampingStepdB);
            requested = target + double(opt.MeasuredPathlossdB);
            applied = min(requested, double(opt.PCMAXdBm));
            clipped = requested > double(opt.PCMAXdBm);

            payload = struct( ...
                "ContractVersion", "sixgr_ra_power_release18/v1", ...
                "Standard", "3GPP TS 38.213 V18.8.0 clause 7.4", ...
                "PreambleReceivedTargetPowerdBm", ...
                    double(opt.PreambleReceivedTargetPowerdBm), ...
                "DeltaPreambledB", double(opt.DeltaPreambledB), ...
                "PowerRampingStepdB", ...
                    double(opt.PowerRampingStepdB), ...
                "PreamblePowerRampingCounter", ...
                    double(opt.PreamblePowerRampingCounter), ...
                "MeasuredPathlossdB", ...
                    double(opt.MeasuredPathlossdB), ...
                "PCMAXdBm", double(opt.PCMAXdBm), ...
                "PreambleTargetAtGNBdBm", target, ...
                "RequestedTxPowerdBm", requested, ...
                "AppliedTxPowerdBm", applied, ...
                "PowerHeadroomdB", double(opt.PCMAXdBm) - applied, ...
                "Clipped", logical(clipped), ...
                "ProxyUsed", false, ...
                "FallbackUsed", false, ...
                "Status", "resolved");
            result = payload;
            result.ResolutionSHA256 = ...
                sixgr.util.sha256Hex(jsonencode(payload));
        end
    end
end

function tf = localFiniteScalar(value)
tf = isnumeric(value) && isreal(value) && isscalar(value) && ...
    isfinite(value);
end

function tf = localNonnegativeFinite(value)
tf = localFiniteScalar(value) && value >= 0;
end

function tf = localPositiveInteger(value)
tf = localFiniteScalar(value) && value >= 1 && value == fix(value);
end
