classdef RATimingService
    %RATIMINGSERVICE Exact four-step RA window, timer and backoff math.

    methods (Static)
        function result=fromRAPlan(ra,varargin)
            % Planned bounds only: not a received RAR or an executed timer.
            spec=ra.RARMonitoringWindow.Numerology;
            start=sixgr.phy.frame.AbsoluteTime.fromAbsoluteSlotSymbol( ...
                ra.Msg2Slot,ra.Msg2PDSCH.SymbolStart,spec);
            finish=start.plusSymbols(ra.Msg2PDSCH.NumSymbols,spec);
            result=sixgr.phy.ia.RATimingService.resolve( ...
                'NumerologyMu',spec.Mu,'RARMonitoringWindow',ra.RARMonitoringWindow, ...
                'RARReceptionEndTicksExclusive',finish.Ticks, ...
                'PRACHOccasionEndSlot',ra.PRACHOccasionEndSlot, ...
                'RAResponseWindowSlots',ra.RAResponseWindowSlots, ...
                'RARCompletionSlot',ra.Msg2Slot,'Msg3CompletionSlot',ra.Msg3Slot, ...
                'ContentionResolutionTimerSlots',ra.RAContentionResolutionTimerSlots, ...
                'Msg4CompletionSlot',ra.Msg4Slot,varargin{:});
            result.EvidenceRole="planned_timing_not_receiver_or_retry_execution";
            result.ResolutionSHA256=sixgr.util.sha256Hex(jsonencode(rmfield(result,'ResolutionSHA256')));
        end

        function result = resolve(varargin)
            p = inputParser;
            p.FunctionName = "sixgr.phy.ia.RATimingService.resolve";
            addParameter(p, "NumerologyMu", 0, @localNonnegativeInteger);
            addParameter(p, "SlotDurationMs", NaN, @localPositiveOrNaN);
            addParameter(p, "PRACHOccasionEndSlot", ...
                NaN, @localNonnegativeInteger);
            addParameter(p, "RAResponseWindowSlots", ...
                NaN, @localPositiveInteger);
            addParameter(p, "RARMonitoringWindow", struct(), @isstruct);
            addParameter(p, "RARReceptionEndTicksExclusive", NaN, @localNonnegativeInteger);
            addParameter(p, "RARCompletionSlot", ...
                NaN, @localNonnegativeInteger);
            addParameter(p, "Msg3CompletionSlot", ...
                NaN, @localNonnegativeInteger);
            addParameter(p, "ContentionResolutionTimerMs", ...
                NaN, @localNonnegativeOrNaN);
            addParameter(p, "ContentionResolutionTimerSlots", ...
                NaN, @localNonnegativeOrNaN);
            addParameter(p, "Msg4CompletionSlot", ...
                NaN, @localNonnegativeInteger);
            addParameter(p, "BackoffIndicatorMs", ...
                0, @localNonnegativeFinite);
            addParameter(p, "UniformDraw0to1", ...
                0, @localUnitInterval);
            parse(p, varargin{:});
            opt = p.Results;
            if ~localNonnegativeInteger(opt.RARReceptionEndTicksExclusive)
                error('sixgr:phy:ia:MissingRARReceptionEnd', ...
                    'RAR timing needs an explicit reception end on the Tc clock.');
            end

            expectedSlotDuration = 1 / (2 ^ double(opt.NumerologyMu));
            slotDuration = double(opt.SlotDurationMs);
            if ~isfinite(slotDuration)
                slotDuration = expectedSlotDuration;
            elseif abs(slotDuration - expectedSlotDuration) > ...
                    8 * eps(max(slotDuration, expectedSlotDuration))
                error("sixgr:phy:ia:InvalidRATimer", ...
                    "SlotDurationMs=%g conflicts with numerology mu=%d.", ...
                    slotDuration, double(opt.NumerologyMu));
            end

            window=opt.RARMonitoringWindow;
            if ~all(isfield(window,["StartSlot","LastSlot","StartTicks", ...
                    "ExpiryTicksExclusive","MonitoringSlots","DurationSlots","Numerology"])) || ...
                    window.DurationSlots~=opt.RAResponseWindowSlots || ...
                    window.Numerology.Mu~=opt.NumerologyMu
                error('sixgr:phy:ia:MissingRARMonitoringWindow', ...
                    'RA timing requires an explicit Type1 monitoring-window authority.');
            end
            responseStart=window.StartSlot; responseLast=window.LastSlot;
            rarInside=ismember(double(opt.RARCompletionSlot),window.MonitoringSlots) && ...
                int64(opt.RARReceptionEndTicksExclusive)>window.StartTicks && ...
                int64(opt.RARReceptionEndTicksExclusive)<=window.ExpiryTicksExclusive;

            timerSlots = double(opt.ContentionResolutionTimerSlots);
            timerMs = double(opt.ContentionResolutionTimerMs);
            if isfinite(timerSlots) && isfinite(timerMs)
                if abs(timerSlots * slotDuration - timerMs) > ...
                        8 * eps(max(timerMs, 1))
                    error("sixgr:phy:ia:InvalidRATimer", ...
                        "Contention timer slot and millisecond values disagree.");
                end
            elseif isfinite(timerMs)
                timerSlots = timerMs / slotDuration;
            elseif isfinite(timerSlots)
                timerMs = timerSlots * slotDuration;
            else
                error("sixgr:phy:ia:InvalidRATimer", ...
                    "A contention-resolution timer value is required.");
            end
            if timerSlots ~= fix(timerSlots)
                error("sixgr:phy:ia:InvalidRATimer", ...
                    "Contention-resolution timer must map to whole slots.");
            end
            contentionStart = double(opt.Msg3CompletionSlot);
            contentionExpiryExclusive = contentionStart + timerSlots;
            contentionResolved = ...
                double(opt.Msg4CompletionSlot) >= contentionStart && ...
                double(opt.Msg4CompletionSlot) < ...
                    contentionExpiryExclusive;

            % Backoff starts after an unsuccessful response-window expiry,
            % never at its start. Keep continuous delay on the Tc clock;
            % a containing slot is not permission to retransmit early.
            backoffMs=double(opt.BackoffIndicatorMs)*double(opt.UniformDraw0to1);
            backoffTicks=int64(ceil(backoffMs*double(sixgr.phy.frame.AbsoluteTime.TicksPerSecond)/1000));
            restart=sixgr.phy.frame.AbsoluteTime.fromTicks(window.ExpiryTicksExclusive);
            restart=restart.plusTicks(backoffTicks);
            [rf,rs,sy,aligned]=restart.toNumerology(window.Numerology);
            restartEarliest=double(rf)*window.Numerology.SlotsPerFrame+double(rs)+double(sy~=0 || ~aligned);
            backoffSlots=ceil(backoffMs/slotDuration);

            payload = struct( ...
                "ContractVersion", "sixgr_ra_timing_release18/v2", ...
                "Standard", ...
                    "3GPP TS 38.213 clause 8.2 / TS 38.321 V18.8.0 random-access timers", ...
                "NumerologyMu", double(opt.NumerologyMu), ...
                "SlotDurationMs", slotDuration, ...
                "PRACHOccasionEndSlot", ...
                    double(opt.PRACHOccasionEndSlot), ...
                "ResponseWindowStartSlot", responseStart, ...
                "ResponseWindowLastSlot", responseLast, ...
                "ResponseWindowStartTicks", window.StartTicks, ...
                "ResponseWindowExpiryTicksExclusive", window.ExpiryTicksExclusive, ...
                "RARCompletionSlot", ...
                    double(opt.RARCompletionSlot), ...
                "RARInsideWindow", logical(rarInside), ...
                "Msg3CompletionSlot", ...
                    double(opt.Msg3CompletionSlot), ...
                "ContentionResolutionTimerMs", timerMs, ...
                "ContentionResolutionTimerSlots", timerSlots, ...
                "ContentionExpirySlotExclusive", ...
                    contentionExpiryExclusive, ...
                "Msg4CompletionSlot", ...
                    double(opt.Msg4CompletionSlot), ...
                "ContentionResolved", logical(contentionResolved), ...
                "BackoffIndicatorMs", ...
                    double(opt.BackoffIndicatorMs), ...
                "UniformDraw0to1", double(opt.UniformDraw0to1), ...
                "BackoffSlots", backoffSlots, ...
                "BackoffDurationMs", backoffMs, "BackoffDurationTicks", backoffTicks, ...
                "RestartEarliestTicks", restart.Ticks, ...
                "RestartScope", "candidate_after_unsuccessful_response_window_expiry_not_a_retry_execution", ...
                "RestartEarliestSlot", restartEarliest, ...
                "ProxyUsed", false, ...
                "FallbackUsed", false, ...
                "Status", "resolved");
            result = payload;
            result.ResolutionSHA256 = ...
                sixgr.util.sha256Hex(jsonencode(payload));
        end
    end
end

function tf = localNonnegativeInteger(value)
tf = isnumeric(value) && isreal(value) && isscalar(value) && ...
    isfinite(value) && value >= 0 && value == fix(value);
end

function tf = localPositiveInteger(value)
tf = localNonnegativeInteger(value) && value >= 1;
end

function tf = localPositiveOrNaN(value)
tf = isnumeric(value) && isreal(value) && isscalar(value) && ...
    ((isfinite(value) && value > 0) || isnan(value));
end

function tf = localNonnegativeOrNaN(value)
tf = isnumeric(value) && isreal(value) && isscalar(value) && ...
    ((isfinite(value) && value >= 0) || isnan(value));
end

function tf = localNonnegativeFinite(value)
tf = isnumeric(value) && isreal(value) && isscalar(value) && ...
    isfinite(value) && value >= 0;
end

function tf = localUnitInterval(value)
tf = isnumeric(value) && isreal(value) && isscalar(value) && ...
    isfinite(value) && value >= 0 && value <= 1;
end
