classdef PowerControlSpec
%POWERCONTROLSPEC Pure-math TS 38.213 bounded UL-power reference.
    methods(Static)
        function result=resolve(mu,mRB,p0_dBm,alpha,pathloss_dB, ...
                deltaTF_dB,tpc_dB,pCMax_dBm)
            values=double([mu mRB p0_dBm alpha pathloss_dB ...
                deltaTF_dB tpc_dB pCMax_dBm]);
            if any(~isfinite(values))||mu<0||mu~=round(mu)||mRB<1|| ...
                    mRB~=round(mRB)||alpha<0||alpha>1
                error("RFOracle:PowerControlInvalid", ...
                    "Power-control reference inputs are invalid.");
            end
            bandwidthTerm=10*log10(2^mu*mRB);
            requested=p0_dBm+bandwidthTerm+alpha*pathloss_dB+ ...
                deltaTF_dB+tpc_dB;
            result=struct("BandwidthTerm_dB",bandwidthTerm, ...
                "RequestedPower_dBm",requested, ...
                "AppliedPower_dBm",min(requested,pCMax_dBm));
        end
    end
end
