classdef SharedDMRSEngine
    %SHAREDDMRSENGINE Release-pinned DL/UL DM-RS resource and sequence owner.

    methods (Static)
        function plan = planVector(row)
            direction = upper(sixgr.phy.rsla.RSLAUtil.text(row,"Direction",""));
            mapping = upper(sixgr.phy.rsla.RSLAUtil.text(row,"MappingType",""));
            configurationType = sixgr.phy.rsla.RSLAUtil.number( ...
                row,"ConfigurationType",NaN);
            dmrsLength = sixgr.phy.rsla.RSLAUtil.number(row,"Length",NaN);
            additional = sixgr.phy.rsla.RSLAUtil.number( ...
                row,"AdditionalPosition",NaN);
            typeAPosition = sixgr.phy.rsla.RSLAUtil.number( ...
                row,"TypeAPosition",2);
            ports = sixgr.phy.rsla.RSLAUtil.numberList( ...
                sixgr.phy.rsla.RSLAUtil.text(row,"LogicalPorts",""));
            scramblingID = sixgr.phy.rsla.RSLAUtil.number( ...
                row,"ScramblingID",NaN);
            nSCID = sixgr.phy.rsla.RSLAUtil.number(row,"NSCID",NaN);
            startSymbol = sixgr.phy.rsla.RSLAUtil.number( ...
                row,"StartSymbol",NaN);
            symbolLength = sixgr.phy.rsla.RSLAUtil.number( ...
                row,"SymbolLength",NaN);
            valid = ismember(direction,["DL","UL"]) && ...
                ismember(mapping,["A","B"]) && ...
                ismember(configurationType,[1 2]) && ...
                ismember(dmrsLength,[1 2]) && ...
                ismember(additional,0:3) && ...
                ~(dmrsLength==2 && additional==3) && ...
                ~isempty(ports) && all(ports>=0) && ...
                numel(unique(ports))==numel(ports) && ...
                all(diff(ports)>=1) && ...
                ~(direction=="UL" && configurationType==1 && ...
                    any(diff(ports)>1)) && ...
                isfinite(scramblingID) && scramblingID>=0 && scramblingID<=65535 && ...
                ismember(nSCID,[0 1]) && ...
                isfinite(startSymbol) && isfinite(symbolLength) && ...
                startSymbol>=0 && symbolLength>=1 && ...
                startSymbol+symbolLength<=14 && ...
                (mapping=="B" || ismember(typeAPosition,[2 3]));
            if ~valid
                error("RSLA:InvalidDMRSConfiguration", ...
                    "Invalid exact DM-RS tuple for the bounded Release-18 profile.");
            end

            carrier = nrCarrierConfig("NSizeGrid",52, ...
                "SubcarrierSpacing",30,"NCellID",mod(scramblingID,1008), ...
                "NSlot",0);
            try
                if direction=="DL"
                    channel = nrPDSCHConfig;
                    channel.PRBSet = 0:51;
                    channel.SymbolAllocation = [startSymbol symbolLength];
                    channel.MappingType = char(mapping);
                    channel.NumLayers = numel(ports);
                    channel.RNTI = 1;
                    channel.DMRS.DMRSConfigurationType = configurationType;
                    channel.DMRS.DMRSLength = dmrsLength;
                    channel.DMRS.DMRSAdditionalPosition = additional;
                    channel.DMRS.DMRSTypeAPosition = typeAPosition;
                    channel.DMRS.NIDNSCID = scramblingID;
                    channel.DMRS.NSCID = nSCID;
                    channel.DMRS.DMRSPortSet = ports;
                    [indices,symbols,info] = sixgr.phy.refsig.dmrsPDSCH( ...
                        carrier,channel,"IndexBase","0based");
                else
                    channel = nrPUSCHConfig;
                    channel.PRBSet = 0:51;
                    channel.SymbolAllocation = [startSymbol symbolLength];
                    channel.MappingType = char(mapping);
                    channel.NumLayers = numel(ports);
                    channel.TransformPrecoding = false;
                    channel.RNTI = 1;
                    channel.DMRS.DMRSConfigurationType = configurationType;
                    channel.DMRS.DMRSLength = dmrsLength;
                    channel.DMRS.DMRSAdditionalPosition = additional;
                    channel.DMRS.DMRSTypeAPosition = typeAPosition;
                    channel.DMRS.NIDNSCID = scramblingID;
                    channel.DMRS.NSCID = nSCID;
                    channel.DMRS.DMRSPortSet = ports;
                    [indices,symbols,info] = sixgr.phy.refsig.dmrsPUSCH( ...
                        carrier,channel,"IndexBase","0based");
                end
            catch cause
                wrapped = MException("RSLA:InvalidDMRSConfiguration", ...
                    "Toolbox rejected the requested DM-RS tuple without mutation: %s.", ...
                    cause.message);
                wrapped = addCause(wrapped,cause);
                throw(wrapped);
            end
            indices = double(indices(:));
            symbols = symbols(:);
            plan = struct("Direction",direction,"Carrier",carrier, ...
                "ChannelConfig",channel,"IndicesZeroBased",indices, ...
                "Symbols",symbols,"LogicalPorts",ports, ...
                "MappingType",mapping,"ConfigurationType",configurationType, ...
                "Length",dmrsLength,"AdditionalPosition",additional, ...
                "IndexSHA256",sixgr.phy.rsla.RSLAUtil.hash(indices), ...
                "SequenceSHA256",sixgr.phy.rsla.RSLAUtil.hash( ...
                    [real(symbols) imag(symbols)]), ...
                "AppliedResourceSHA256",sixgr.phy.rsla.RSLAUtil.hash(indices), ...
                "Info",info,"ExecutionBackend","matlab_5g_toolbox_waveform_kernel", ...
                "ApproximationMode","none");
        end

        function result = noNoiseRoundTrip(plan)
            symbols = plan.Symbols(:);
            received = symbols;
            channelEstimate = received ./ symbols;
            errorPower = mean(abs(channelEstimate-1).^2);
            result = struct("NMSE",errorPower, ...
                "Passed",isfinite(errorPower)&&errorPower<1e-12);
        end
    end
end
