classdef FullStackAcceptanceEvaluator
    %FULLSTACKACCEPTANCEEVALUATOR Bind all rules to canonical child ledgers.
    methods (Static)
        function results=evaluate(ctx,subcases,components,values,negatives)
            resolver=sixgr.integration.qualification. ...
                ArtifactResolver.create(ctx.RunFolder,ctx.Profile);
            auditPath=fullfile(ctx.CSVDir,"full_stack_artifact_audit.csv");
            if isfile(auditPath)
                audit=readtable(auditPath,"TextType","string", ...
                    "VariableNamingRule","preserve");
            else
                audit=sixgr.integration.qualification. ...
                    ArtifactResolver.audit(resolver,true);
            end
            regressionPath=fullfile(ctx.CSVDir, ...
                "full_stack_regression_summary.csv");
            if isfile(regressionPath)
                regression=readtable(regressionPath, ...
                    "TextType","string","VariableNamingRule","preserve");
            else
                regression=sixgr.integration.qualification. ...
                    FullStackRegressionRunner.pending(ctx);
            end
            results=sixgr.integration.qualification. ...
                QualificationStatusReducer.acceptance( ...
                ctx.Profile,ctx.RunID,subcases,components,values, ...
                negatives,audit,regression,resolver);
            sixgr.util.csvWriteTable(fullfile(ctx.CSVDir, ...
                "full_stack_acceptance_results.csv"),results);
        end
    end
end
