classdef QualificationArtifactSchemaAdapterRegistry
    %QUALIFICATIONARTIFACTSCHEMAADAPTERREGISTRY Versioned adapter facade.
    % All mappings delegate to audited, lossless registries. No configured
    % value is substituted for an absent observation.
    methods (Static)
        function T = auditAliases()
            T = sixgr.integration.qualification. ...
                QualificationArtifactAuditNormalizer.aliasRegistry();
        end

        function T = evidenceAliases()
            T = sixgr.integration.qualification. ...
                EvidenceAdapterRegistry.aliases();
        end

        function [normalized,diagnostic] = normalizeAudit(T)
            [normalized,diagnostic] = sixgr.integration.qualification. ...
                QualificationArtifactAuditNormalizer.normalize(T);
        end

        function [adapted,trace] = adaptEvidence( ...
                fileName,T,expressions,sourceHash)
            [adapted,trace] = sixgr.integration.qualification. ...
                EvidenceAdapterRegistry.adapt( ...
                fileName,T,expressions,sourceHash);
            if ~isempty(trace)
                required = ["SourceSchemaID","TargetSchemaID", ...
                    "AdapterVersion","SourceColumns","TargetColumns", ...
                    "TransformationFormula","Lossless", ...
                    "SourceArtifactSHA256","OutputArtifactSHA256", ...
                    "Status"];
                if any(~ismember(required, ...
                        string(trace.Properties.VariableNames))) || ...
                        any(~logical(trace.Lossless))
                    error("FULLSTACK:LossyEvidenceAdapter", ...
                        "Qualification adapters must publish complete lossless provenance.");
                end
            end
        end
    end
end
