function ok = releaseBaselineSpecAcceptance()
%RELEASEBASELINESPECACCEPTANCE Pin release/spec/toolbox provenance for anchors.

spec = core.releaseBaselineSpecTable();
required = ["pure_math","grid_bit","waveform_loopback","awgn_channel", ...
    "harq_soft_buffer","interference_superposition","random_access", ...
    "rank2_mimo","campaign_convergence","kpi_reproducibility"];
assert(all(ismember(required, string(spec.AnchorID))), ...
    "Release baseline spec table is missing mandatory anchors: %s", ...
    strjoin(setdiff(required, string(spec.AnchorID)), ", "));
assert(all(strlength(string(spec.SpecVersion)) > 0), ...
    "Every release acceptance vector must pin a 3GPP/spec version.");
assert(all(strlength(string(spec.ReferencePath)) > 0), ...
    "Every release acceptance vector must name an independent reference path.");
assert(all(strlength(string(spec.MATLABRelease)) > 0), ...
    "Every release acceptance vector must pin MATLAB release behavior.");
assert(all(strlength(string(spec.NumericTolerance)) > 0), ...
    "Every release acceptance vector must declare a numerical tolerance.");

requiredAPIs = ["nrCarrierConfig","nrPDSCHConfig","nrPUSCHConfig", ...
    "nrPDSCHIndices","nrPUSCHIndices","nrRateMatchLDPC", ...
    "nrOFDMModulate","nrOFDMDemodulate"];
missing = requiredAPIs(arrayfun(@(name) exist(char(name), "file") ~= 2 && ...
    exist(char(name), "class") ~= 8, requiredAPIs));
assert(isempty(missing), "Release numerical acceptance requires NR Toolbox APIs: %s", strjoin(missing, ", "));
ok = true;
end
