function ok = releaseBaselineArchiveAcceptance()
%RELEASEBASELINEARCHIVEACCEPTANCE Verify reproducibility archive manifest.

tmp = tempname;
mkdir(tmp);
cleanup = onCleanup(@() rmdir(tmp, "s")); %#ok<NASGU>
layout = sixgr.report.resultLayout(tmp);
sixgr.util.ensureDir(fullfile(layout.AirInterfaceCSVDir, "dl_pdsch_trials.csv"));
sixgr.util.ensureDir(fullfile(layout.ReportCSVDir, "truth_contract_summary.csv"));

dlT = table((1:2).', ["PASS"; "PASS"], 'VariableNames', {'TrialId','Status'});
truthT = table("PASS", true, 'VariableNames', {'TruthContractStatus','Ok'});
sixgr.util.csvWriteTable(fullfile(layout.AirInterfaceCSVDir, "dl_pdsch_trials.csv"), dlT);
sixgr.util.csvWriteTable(fullfile(layout.ReportCSVDir, "truth_contract_summary.csv"), truthT);

taskPlan = sixgr.util.buildDeterministicTaskPlan(4242, [-2 0 2], ["DL", "UL"], ...
    "MaxTrials", 4, ...
    "TrialsPerDrop", 2, ...
    "IncludePointTasks", true);
acceptance = table(["core"; "phy"; "mac"], [true; true; true], ...
    'VariableNames', {'Anchor','Passed'});
cfg = struct("run", struct("seed", 4242), "meta", struct("scenario_id", "release_archive_fixture"));

out = sixgr.validation.buildReleaseBaselineArchiveManifest(tmp, cfg, ...
    "TaskPlan", taskPlan, ...
    "PrimaryArtifacts", ["air_interface/csv/dl_pdsch_trials.csv", "reports/csv/truth_contract_summary.csv"], ...
    "AcceptanceResults", acceptance, ...
    "WriteArtifacts", true);

assert(exist(char(out.ManifestJSON), "file") == 2, ...
    "Release archive manifest JSON must be written.");
assert(exist(char(out.ArtifactInventoryCSV), "file") == 2, ...
    "Release archive artifact inventory CSV must be written.");
assert(strlength(string(out.ConfigHash)) == 64 && strlength(string(out.TaskPlanHash)) == 64, ...
    "Release archive must hash resolved config and deterministic seed task plan.");
assert(strcmp(string(out.Manifest.FailureFreeManifestStatus), "failure_free"), ...
    "All-passing acceptance rows must produce a failure-free archive manifest status.");
assert(double(out.Manifest.PrimaryArtifactsPresent) == 2 && double(out.Manifest.PrimaryArtifactsMissing) == 0, ...
    "Fixture primary artifacts must be present and counted.");

inventory = out.ArtifactInventory;
assert(all(logical(inventory.Exists)) && all(logical(inventory.CountsTowardArchive)), ...
    "Only real existing artifacts may count toward the archive.");
assert(all(strlength(string(inventory.SHA256)) == 64), ...
    "Every counted archive artifact must carry a SHA-256 digest.");

failed = table("phy", false, 'VariableNames', {'Anchor','Passed'});
outMissing = sixgr.validation.buildReleaseBaselineArchiveManifest(tmp, cfg, ...
    "TaskPlan", taskPlan, ...
    "PrimaryArtifacts", "reports/csv/missing_primary.csv", ...
    "AcceptanceResults", failed, ...
    "WriteArtifacts", false);
assert(strcmp(string(outMissing.Manifest.FailureFreeManifestStatus), "has_failures"), ...
    "Failed acceptance rows must not be promoted to a failure-free manifest.");
assert(double(outMissing.Manifest.PrimaryArtifactsMissing) == 1 && ...
    ~logical(outMissing.ArtifactInventory.CountsTowardArchive(1)), ...
    "Missing archive artifacts must stay missing and not count toward archive coverage.");

ok = true;
end
