function hash = hashCodeBlockLayout(layout)
%HASHCODEBLOCKLAYOUT Return the canonical HARQ code-block layout hash.
% Keep this file ASCII-only.

hash = "";
if ~(isstruct(layout) && ~isempty(fieldnames(layout)))
    return;
end

hash = string(sixgr.util.structGet(layout, "CodingLayoutHash", ...
    sixgr.util.structGet(layout, "CombineSignature", "")));
hash = strtrim(hash);
if strlength(hash) > 0
    hash = char(hash);
    return;
end

payload = struct( ...
    "A", double(sixgr.util.structGet(layout, "A", ...
        sixgr.util.structGet(layout, "TransportBlockSize", NaN))), ...
    "TBCRCType", char(string(sixgr.util.structGet(layout, "TBCRCType", ""))), ...
    "BaseGraph", double(sixgr.util.structGet(layout, "BaseGraph", ...
        sixgr.util.structGet(layout, "BGN", NaN))), ...
    "NumCodeBlocks", double(sixgr.util.structGet(layout, "NumCodeBlocks", ...
        sixgr.util.structGet(layout, "C", NaN))), ...
    "CodeBlockLength", double(sixgr.util.structGet(layout, "CodeBlockLength", ...
        sixgr.util.structGet(layout, "K", NaN))), ...
    "MotherCodeLength", double(sixgr.util.structGet(layout, "MotherCodeLength", ...
        sixgr.util.structGet(layout, "N", NaN))), ...
    "LiftingSizeZc", double(sixgr.util.structGet(layout, "LiftingSize", ...
        sixgr.util.structGet(layout, "Zc", NaN))), ...
    "Nref", double(sixgr.util.structGet(layout, "Nref", NaN)), ...
    "FillerPositions", {sixgr.util.structGet(layout, "FillerPositions", cell(1, 0))});
hash = char(sixgr.util.sha256Hex(localCanonicalBytes(payload)));
end

function bytes = localCanonicalBytes(value)
try
    bytes = uint8(unicode2native(char(jsonencode(orderfields(value))), "UTF-8"));
catch
    bytes = uint8(unicode2native(char(string(value)), "UTF-8"));
end
end
