function T = pruneStructurallyBlankTableColumns(T)
%PRUNESTRUCTURALLYBLANKTABLECOLUMNS Drop columns with no runtime evidence.
%
% This is intentionally conservative: it never fills missing values and it
% preserves false-only logical flags because those can be real evidence that
% a condition did not occur. Empty tables keep their schema so explicitly
% empty primary artifacts remain self-describing.

if ~(istable(T) && ~isempty(T))
    return;
end

keepMask = false(1, width(T));
names = string(T.Properties.VariableNames);
for i = 1:numel(names)
    keepMask(i) = localIsContractEvidenceColumn(names(i)) ...
        || localColumnHasRuntimeContent(T.(char(names(i))));
end

if any(~keepMask)
    T(:, ~keepMask) = [];
end
end

function tf = localIsContractEvidenceColumn(name)
normalized = lower(strtrim(string(name)));
exactKeep = lower([ ...
    "NoiseVar", ...
    "NoiseVarStatus", ...
    "NoiseVarSource", ...
    "SRS_NMSE_dB", ...
    "SRS_NMSE_CI_Low", ...
    "SRS_NMSE_CI_High", ...
    "SRS_TrialCount", ...
    "ScenarioID", ...
    "ConfigHash", ...
    "RunnerProfile", ...
    "File", ...
    "Function", ...
    "ParameterOrConstant", ...
    "Classification", ...
    "OwnerShouldBe", ...
    "ActionTaken", ...
    "StatusAfterPatch", ...
    "Category", ...
    "ParameterName", ...
    "ParameterId", ...
    "ConfiguredValue", ...
    "ResolvedRuntimeValue", ...
    "BrowserExposed", ...
    "YAMLExposed", ...
    "RuntimeDerived", ...
    "HiddenFallbackRemoved", ...
    "SourceOfTruth", ...
    "CanonicalArtifact", ...
    "ResolvedMATLABPath", ...
    "FieldName", ...
    "ValueSource", ...
    "ValueRole", ...
    "ValueStatus", ...
    "ValueDefinition", ...
    "FinalizedFlag", ...
    "PlaceholderFlag", ...
    "FallbackFlag", ...
    "NAReason", ...
    "CanonicalArtifacts", ...
    "BrowserSubmittedValue", ...
    "BrowserSubmittedValueSource", ...
    "BrowserSubmittedValueRole", ...
    "RuntimeOverlayValue", ...
    "RuntimeOverlayValueSource", ...
    "RuntimeOverlayValueRole", ...
    "ResolvedMATLABValue", ...
    "ResolvedMATLABValueSource", ...
    "ResolvedMATLABValueRole", ...
    "DBSnapshotValue", ...
    "DBSnapshotValueSource", ...
    "DBSnapshotValueRole", ...
    "ExportedCSVValue", ...
    "ExportedCSVValueSource", ...
    "ExportedCSVValueRole", ...
    "BrowserDisplayedValue", ...
    "BrowserDisplayedValueSource", ...
    "BrowserDisplayedValueRole", ...
    "ConsistencyStatus", ...
    "ConsistencyNotes", ...
    "RuntimeEvidenceArtifact", ...
    "RuntimeEvidenceField", ...
    "RuntimeEvidenceValue", ...
    "RuntimeEvidenceValueSource", ...
    "RuntimeEvidenceValueRole", ...
    "DerivedValue", ...
    "DerivedValueSource", ...
    "DerivedValueRole", ...
    "DBSnapshotSource", ...
    "DBLogicalPath", ...
    "ExportedCSVLogicalPath", ...
    "BrowserPayloadField", ...
    "SummaryField", ...
    "SummaryValue", ...
    "RawDerivedValue", ...
    "ObservedValue", ...
    "SourceArtifact", ...
    "FeatureFamily", ...
    "InternalCfgPath", ...
    "ConsumerFunction", ...
    "AppliedValue", ...
    "EvidenceStatus", ...
    "UILayer", ...
    "UISection", ...
    "BrowserPath", ...
    "ScenarioPath", ...
    "BrowserVisible", ...
    "BrowserEditable", ...
    "SubmittedValue", ...
    "ResolvedScenarioValue", ...
    "InternalCfgValue", ...
    "MappingStatus", ...
    "RuntimeAppliedStatus", ...
    "RuntimeMeasuredStatus", ...
    "FinalBindingStatus", ...
    "UILabel", ...
    "DisplayedValue", ...
    "RuntimeAppliedValue", ...
    "RuntimeMeasuredValue", ...
    "ConfigStatus", ...
    "ApplicationStatus", ...
    "MeasurementStatus", ...
    "DisplayStatus", ...
    "DisplayReason", ...
    "ParameterCount", ...
    "RuntimeAppliedCount", ...
    "RuntimeMeasuredCount", ...
    "ConfigResolvedStatus", ...
    "SelectionBucket", ...
    "ExclusionReason", ...
    "UEIndex", ...
    "RNTI", ...
    "BaseStationID", ...
    "BSAntennaArrayClass", ...
    "BSAntennaRows", ...
    "BSAntennaCols", ...
    "BSAntennaElements", ...
    "BSAntennaNumPorts", ...
    "UEAntennaArrayClass", ...
    "UEAntennaRows", ...
    "UEAntennaCols", ...
    "UEAntennaElements", ...
    "UEAntennaNumPorts", ...
    "AntennaConfigSource", ...
    "RuntimeAntennaObjectSource", ...
    "AntennaRuntimeObjectCreated", ...
    "ChannelArrayModel", ...
    "ChannelObjectSource", ...
    "ChannelObjectClass", ...
    "ChannelArrayHandlingStatus", ...
    "ChannelArrayHandlingBlocker", ...
    "ChannelGeometryCouplingLevel", ...
    "GeometryAdapterType", ...
    "GeometryAdapterSource", ...
    "GeometryAdapterLimitation", ...
    "GeometryAdapterPortMapping", ...
    "ChannelUsesCountOnlyAntennaModel", ...
    "ChannelUsesSameRuntimeAntennaAssumptions", ...
    "InterferenceChannelObjectSource", ...
    "InterferenceChannelObjectClass", ...
    "InterferenceChannelArrayHandlingStatus", ...
    "InterferenceChannelArrayHandlingBlocker", ...
    "InterferenceUsesSameRuntimeAntennaAssumptions", ...
    "InterferencePathUsesSameArrayAssumptions", ...
    "PropagationDistance_m", ...
    "GeometricPropagationDelay_s", ...
    "PropagationDelay_s", ...
    "ToD_s", ...
    "ToA_s", ...
    "ToDSource", ...
    "ToASource", ...
    "ChannelDelaySource", ...
    "AntennaGeometrySource", ...
    "SameFlowEvidenceSource", ...
    "AppliedBeamIndexSet", ...
    "AppliedPrecoderPMI", ...
    "AppliedPrecoderPMIType", ...
    "AppliedPrecoderCodebookMode", ...
    "RequestedBeamIndexSet", ...
    "RequestedPrecoderPMI", ...
    "RequestedPrecoderSource", ...
    "PrecoderSource", ...
    "PrecodingMode", ...
    "BeamformingApplied", ...
    "AppliedPrecoderSource", ...
    "RequestedVsAppliedPrecoderPMIMatchStatus", ...
    "RequestedBeamTruthClassification", ...
    "RequestedPrecoderPMITruthClassification", ...
    "AppliedBeamApplicationSource", ...
    "AppliedBeamTruthClassification", ...
    "AppliedPrecoderPMIApplicationSource", ...
    "AppliedPrecoderPMITruthClassification", ...
    "SNRConsistencyStatus", ...
    "ConfiguredSNRSource", ...
    "SNRValueRole", ...
    "ReceiverHestSINR_dB", ...
    "ReceiverHestSINRSource", ...
    "ReceiverHestSINRValueRole", ...
    "ReceiverHestSINRValueStatus", ...
    "ReceiverHestSINRNAReason", ...
    "SystemLevelWidebandSINR_dB", ...
    "PostEqWidebandSINR_dB", ...
    "ReceiverHestWidebandSINR_dB", ...
    "DecoderTruthProxyWidebandSINR_dB", ...
    "MeasuredWidebandSINR_dB", ...
    "LargeScaleWidebandSINR_dB", ...
    "WidebandSINRSource", ...
    "WidebandSINRValueRole", ...
    "WidebandSINRValueStatus", ...
    "PostEqSINR_dB", ...
    "PostEqSINRSource", ...
    "PostEqSINRValueRole", ...
    "PostEqSINRValueStatus", ...
    "PostEqSINRNAReason", ...
    "PostEqSINRPerLayer_dB", ...
    "EVMProxySINR_dB", ...
    "EVMProxySINRSource", ...
    "EVMProxySINRValueRole", ...
    "EVMProxySINRValueStatus", ...
    "EVMProxySINRNAReason", ...
    "MeasuredTrialSINR_dB", ...
    "MeasuredTrialSINRSource", ...
    "MeasuredTrialSINRValueRole", ...
    "MeasuredTrialSINRValueStatus", ...
    "MeasuredTrialSINRNAReason", ...
    "MeasuredSINR_dB", ...
    "SINRSource", ...
    "ReceiverUsable", ...
    "DecodeAttempted", ...
    "DecodeUsable", ...
    "SINRValueRole", ...
    "SINRValueStatus", ...
    "SINRValueDefinition", ...
    "PrimaryTruthValueStatus", ...
    "SecondaryFieldGapFlag", ...
    "SecondaryFieldGapCount", ...
    "SecondaryFieldGapReason", ...
    "RowLifecycleState", ...
    "PartialRowFlag", ...
    "FinalizedFlag", ...
    "FallbackFlag", ...
    "PlaceholderFlag", ...
    "BeamIndexSetMaterialized", ...
    "MeasurementRSRP_dB", ...
    "MeasurementRSRQ_dB", ...
    "MeasurementRSSI_dBm", ...
    "MeasurementUsable", ...
    "RuntimeMaterializationStatus", ...
    "RuntimeEvidenceSource", ...
    "RuntimeEvidenceStatus", ...
    "TimingEstimateAvailability", ...
    "CFOEstimateAvailability", ...
    "CorrectionLoopStatus", ...
    "TimingOffsetSamplesRaw", ...
    "TimingOffsetSamplesApplied", ...
    "CQI", ...
    "CQIDerivedMCS", ...
    "CalibrationProfile", ...
    "PBCHCRC", ...
    "MIBRecovered", ...
    "CRCOutcome", ...
    "DCIPayloadBits"]);
if any(normalized == exactKeep)
    tf = true;
    return;
end
tf = false;
end

function tf = localColumnHasRuntimeContent(col)
if isnumeric(col)
    tf = any(isfinite(double(col)));
    return;
end

if islogical(col)
    tf = true;
    return;
end

try
    vals = string(col);
catch
    tf = true;
    return;
end

normalized = lower(strtrim(fillmissing(vals, "constant", "")));
mask = strlength(normalized) > 0 ...
    & normalized ~= "nan" ...
    & normalized ~= "nat" ...
    & normalized ~= "<missing>" ...
    & normalized ~= "not_applicable";
if ~any(mask)
    tf = false;
    return;
end

inactivePrefixes = [ ...
    "not_recorded_by_active_", ...
    "not_emitted_by_active_", ...
    "field_not_emitted_by_active_", ...
    "not_applicable_for_active_"];
uniqueVals = unique(normalized(mask), "stable");
tf = ~all(arrayfun(@(token) any(startsWith(token, inactivePrefixes)), uniqueVals));
end
