classdef EVMMeasurement
%EVMMEASUREMENT Resource/reference-aware RMS EVM measurement.

    methods(Static)
        function result=measure(reference,measured,profile)
            required=["ReferencePlane","MeasurementInterval","Limit_pct", ...
                "CarrierLeakageRemoval"];
            if ~isstruct(profile)||~all(isfield(profile,required))
                error("RF:EVMReferenceInvalid", ...
                    "EVM measurement reference/profile is incomplete.");
            end
            plane=sixgr.rf.runtime.RFReferencePlane.validate(profile.ReferencePlane);
            interval=double(profile.MeasurementInterval(:));
            if isempty(reference)||numel(reference)~=numel(measured)|| ...
                    any(~isfinite(reference(:)))||any(~isfinite(measured(:)))|| ...
                    isempty(interval)||any(interval<1)||any(interval>numel(reference))
                error("RF:EVMReferenceInvalid", ...
                    "EVM reference, measured samples or interval is invalid.");
            end
            corrected=double(measured(:));
            timingCorrected=false;
            frequencyCorrected=false;
            correctionSource="none";
            if isfield(profile,"CorrectionState")
                state=profile.CorrectionState;
                requiredState=["TimingError_samples","FrequencyError_Hz", ...
                    "SampleRate_Hz","Source"];
                if ~isstruct(state)||~all(isfield(state,requiredState))|| ...
                        ~contains(lower(string(state.Source)), ...
                        ["measured","receiver"])
                    error("RF:EVMReferenceInvalid", ...
                        "EVM correction state must be receiver-derived.");
                end
                corrected=sixgr.rf.runtime.oracle.FractionalDelaySpec.apply( ...
                    corrected,-double(state.TimingError_samples),32);
                corrected=sixgr.rf.runtime.oracle.CFOAnalyticalSpec.rotate( ...
                    corrected,-double(state.FrequencyError_Hz), ...
                    double(state.SampleRate_Hz),0);
                timingCorrected=true;
                frequencyCorrected=true;
                correctionSource=string(state.Source);
            end
            ref=double(reference(interval));
            obs=corrected(interval);
            if logical(profile.CarrierLeakageRemoval)
                obs=obs-mean(obs-ref);
            end
            referenceEqualized=false;
            if logical(sixgr.util.structGet(profile,"ReferenceEqualization",false))
                gain=(ref'*obs)/max(ref'*ref,realmin);
                if abs(gain)<=eps
                    error("RF:EVMReferenceInvalid", ...
                        "EVM reference equalization estimate is singular.");
                end
                obs=obs/gain;
                referenceEqualized=true;
            end
            evm=100*sqrt(sum(abs(obs-ref).^2)/max(sum(abs(ref).^2),realmin));
            configForHash=profile;
            if isfield(configForHash,"CorrectionState")
                correctionForHash=configForHash.CorrectionState;
                correctionForHash=orderfields(correctionForHash);
                configForHash.CorrectionState=correctionForHash;
            end
            configHash=string(sixgr.util.sha256Hex(uint8(unicode2native( ...
                jsonencode(orderfields(configForHash)),"UTF-8"))));
            result=struct("EVM_pct",evm,"Limit_pct",double(profile.Limit_pct), ...
                "ReferencePlane",plane,"Passed",evm<=double(profile.Limit_pct), ...
                "CarrierLeakageRemoved",logical(profile.CarrierLeakageRemoval), ...
                "TimingCorrected",timingCorrected, ...
                "FrequencyCorrected",frequencyCorrected, ...
                "CorrectionSource",correctionSource, ...
                "ReferenceEqualized",referenceEqualized, ...
                "MeasurementInterval",sprintf("%d:%d",interval(1),interval(end)), ...
                "MeasurementConfigurationSHA256",configHash, ...
                "SourceWaveformSHA256", ...
                sixgr.rf.runtime.RFStateTrace.sampleHash(measured), ...
                "Method","allocated_samples_rms_after_permitted_correction");
        end
    end
end
