classdef InBandEmissionMeasurement
%INBANDEMISSIONMEASUREMENT Allocated/unallocated resource emission metric.

    methods(Static)
        function result=measure(referenceGrid,measuredGrid,allocatedMask, ...
                limit_dB,referencePlane)
            plane=sixgr.rf.runtime.RFReferencePlane.validate(referencePlane);
            mask=logical(allocatedMask);
            if isempty(referenceGrid)||~isequal(size(referenceGrid), ...
                    size(measuredGrid),size(mask))|| ...
                    any(~isfinite(referenceGrid(:)))|| ...
                    any(~isfinite(measuredGrid(:)))||~any(mask(:))|| ...
                    ~any(~mask(:))||~(isscalar(limit_dB)&&isfinite(limit_dB))
                error("RF:InBandEmissionInvalid", ...
                    "In-band emission measurement inputs are invalid.");
            end
            errorGrid=double(measuredGrid)-double(referenceGrid);
            allocatedPower=mean(abs(double(referenceGrid(mask))).^2);
            unallocatedPower=mean(abs(errorGrid(~mask)).^2);
            emission_dB=10*log10(max(unallocatedPower,realmin)/ ...
                max(allocatedPower,realmin));
            result=struct("Emission_dB",emission_dB, ...
                "Limit_dB",double(limit_dB), ...
                "Margin_dB",double(limit_dB)-emission_dB, ...
                "Passed",emission_dB<=double(limit_dB), ...
                "ReferencePlane",plane, ...
                "AllocatedRE",nnz(mask),"UnallocatedRE",nnz(~mask));
        end
    end
end
