classdef OFDMScalingLedger
%OFDMSCALINGLEDGER Parseval and occupied-resource scaling evidence.

    methods(Static)
        function result = reconcile(grid, waveform, nFFT, cpLengths)
            if isempty(grid) || isempty(waveform) || any(~isfinite(grid(:))) || ...
                    any(~isfinite(waveform(:))) || ~(isscalar(nFFT) && ...
                    isfinite(nFFT) && nFFT == round(nFFT) && nFFT > 0)
                error("RF:OFDMScalingInvalid", ...
                    "OFDM scaling reconciliation requires finite grid/waveform data and integer NFFT.");
            end
            cpLengths = double(cpLengths(:));
            if isempty(cpLengths) || any(~isfinite(cpLengths)) || any(cpLengths < 0)
                error("RF:OFDMScalingInvalid", ...
                    "OFDM scaling reconciliation requires explicit cyclic-prefix lengths.");
            end
            gridEnergy = sum(abs(double(grid(:))).^2);
            waveformEnergy = sum(abs(double(waveform(:))).^2);
            activeRE = nnz(grid);
            result = struct( ...
                "GridEnergy", gridEnergy, ...
                "WaveformEnergy", waveformEnergy, ...
                "ActiveRE", activeRE, ...
                "NFFT", double(nFFT), ...
                "CyclicPrefixSamples", sum(cpLengths), ...
                "WaveformToGridEnergyRatio", waveformEnergy / max(gridEnergy, realmin), ...
                "ParsevalResidual", abs(sum(abs(fft(double(waveform(:)))).^2) / ...
                    numel(waveform) - waveformEnergy));
        end
    end
end
