classdef ReceiverFrontEnd < handle
%RECEIVERFRONTEND Canonical explicit LNA/mixer/filter/AGC/ADC chain.

    properties(SetAccess=private)
        Configuration struct
        ConfigurationEpoch (1,1) double
        MixerSampleIndex (1,1) double = 0
        FilterState double = zeros(0,1)
        AGC sixgr.rf.runtime.AGCState
        NoiseStream
        ADCState struct = struct()
    end

    methods
        function obj=ReceiverFrontEnd(configuration,configurationEpoch)
            required=["SampleRate_Hz","InputPower_dBm","LNAProfile", ...
                "MixerProfile","SelectivityFilterProfile","AGCProfile", ...
                "ADCProfile","Temperature_K","NoiseSeed", ...
                "ReferenceImpedance_Ohm"];
            if ~isstruct(configuration)||~all(isfield(configuration,required))
                error("RF:ReceiverFrontEndIncomplete", ...
                    "Receiver front end requires every explicit stage profile.");
            end
            adcProfile=configuration.ADCProfile;
            if ~isstruct(adcProfile)||~isfield(adcProfile,"FullScale")|| ...
                    ~isnumeric(adcProfile.FullScale)||~isreal(adcProfile.FullScale)|| ...
                    ~isscalar(adcProfile.FullScale)||~isfinite(adcProfile.FullScale)|| ...
                    adcProfile.FullScale<=0
                error("RF:ADCProfileMissing","Receiver AGC requires the explicit ADC full scale.");
            end
            obj.Configuration=configuration;
            obj.ConfigurationEpoch=configurationEpoch;
            obj.AGC=sixgr.rf.runtime.AGCState(configuration.AGCProfile, ...
                configurationEpoch);
            if ~(isscalar(configuration.Temperature_K)&& ...
                    isfinite(configuration.Temperature_K)&& ...
                    configuration.Temperature_K>0&& ...
                    isscalar(configuration.NoiseSeed)&& ...
                    isfinite(configuration.NoiseSeed)&& ...
                    isscalar(configuration.ReferenceImpedance_Ohm)&& ...
                    isfinite(configuration.ReferenceImpedance_Ohm)&& ...
                    configuration.ReferenceImpedance_Ohm>0)
                error("RF:ReceiverFrontEndIncomplete", ...
                    "Receiver temperature, noise seed and impedance must be explicit.");
            end
            obj.NoiseStream=RandStream("Threefry", ...
                "Seed",double(configuration.NoiseSeed));
        end

        function [output,evidence]=apply(obj,input,slot,expectedEpoch)
            if double(expectedEpoch)~=obj.ConfigurationEpoch
                error("RF:StateEpochMismatch", ...
                    "Receiver-front-end state epoch mismatch.");
            end
            cfg=obj.Configuration;
            [lna,lnaEvidence]=sixgr.rf.runtime.LNAProfile.apply(input, ...
                cfg.LNAProfile,cfg.InputPower_dBm);
            [mixed,mixerEvidence]=sixgr.rf.runtime.MixerProfile.apply(lna, ...
                cfg.SampleRate_Hz,cfg.MixerProfile,obj.MixerSampleIndex);
            obj.MixerSampleIndex=mixerEvidence.NextSampleIndex;
            filterProfile=cfg.SelectivityFilterProfile;
            filterProfile.SampleRate_Hz=cfg.SampleRate_Hz;
            [filtered,obj.FilterState,filterEvidence]= ...
                sixgr.rf.runtime.RFSelectivityFilter.apply( ...
                mixed,filterProfile,obj.FilterState);
            noiseLedger=sixgr.rf.runtime.NoisePowerLedger.cascade( ...
                [cfg.LNAProfile.Gain_dB cfg.MixerProfile.ConversionGain_dB], ...
                [cfg.LNAProfile.NoiseFigure_dB cfg.MixerProfile.NoiseFigure_dB], ...
                cfg.SelectivityFilterProfile.ENBW_Hz,cfg.Temperature_K);
            outputNoisePower_dBm=noiseLedger.NoisePower_dBm+ ...
                cfg.LNAProfile.Gain_dB+cfg.MixerProfile.ConversionGain_dB;
            outputNoisePower_mW=10^(outputNoisePower_dBm/10);
            % Time-major I/Q draws preserve the same realization across
            % arbitrary chunks and RX chains. This is a complex-baseband
            % receiver: a real-valued/silent chunk still has I AND Q noise.
            draws=randn(obj.NoiseStream,2*size(filtered,2),size(filtered,1));
            noise=sqrt(outputNoisePower_mW/2).* ...
                (draws(1:2:end,:).'+1j*draws(2:2:end,:).');
            noisy=filtered+cast(noise,"like",filtered);
            % Slot is scheduling metadata, not an analog voltage/amplitude.
            [agcOutput,agcEvidence]=obj.AGC.apply(noisy,cfg.ADCProfile.FullScale,expectedEpoch);
            [adc,obj.ADCState]=sixgr.rf.runtime.ADCModel.quantize(agcOutput,cfg.ADCProfile,obj.ADCState);
            output=adc.Output;
            evidence=struct("LNA",lnaEvidence,"Mixer",mixerEvidence, ...
                "SelectivityFilter",filterEvidence,"AGC",agcEvidence, ...
                "NoiseLedger",noiseLedger, ...
                "MeasuredInjectedNoisePower_dBm",10*log10(max( ...
                mean(abs(noise(:)).^2),realmin)), ...
                "ADC",rmfield(adc,["Output","Code","QuantizationError", ...
                "Dither","ApertureError"]), ...
                "QuantizationErrorCovariance", ...
                (adc.QuantizationError'*adc.QuantizationError)/ ...
                max(size(adc.QuantizationError,1),1), ...
                "ReferencePlane","ADC_OUTPUT", ...
                "StateEpoch",obj.ConfigurationEpoch,"Slot",double(slot));
        end
    end
end
