function raw=resolveMultipolePhaseNoiseProfile(definition,carrierHz,sampleRateHz)
% Explicit research-mask transformation; no normative 7 GHz claim.
required=["profile_id","version","classification","source","carrier_frequency_hz", ...
    "reference_frequency_hz","zero_frequencies_hz","pole_frequencies_hz", ...
    "zero_exponents","pole_exponents","reference_psd_dbchz","minimum_offset_hz", ...
    "mask_point_count","upper_nyquist_fraction","synthesis_method","fir_length","lo_correlation"];
assert(isstruct(definition) && all(isfield(definition,required)), ...
    'RF:PhaseNoiseMaskMissing','Explicit multipole profile parameters and provenance are required.');
validateattributes(carrierHz,{'numeric'},{'scalar','positive','finite'});
validateattributes(sampleRateHz,{'numeric'},{'scalar','positive','finite'});
assert(carrierHz==double(definition.carrier_frequency_hz),'RF:PhaseNoiseCarrierMismatch', ...
    'Profile carrier must match the executed waveform carrier.');
fz=double(definition.zero_frequencies_hz(:)); fp=double(definition.pole_frequencies_hz(:));
az=double(definition.zero_exponents(:)); ap=double(definition.pole_exponents(:));
assert(numel(fz)==numel(az) && numel(fp)==numel(ap) && ~isempty(fz) && ~isempty(fp) && ...
    all(isfinite([fz;fp;az;ap])) && all([fz;fp;az;ap]>0), ...
    'RF:PhaseNoiseMaskMissing','Pole/zero frequencies and exponents must be positive finite matching vectors.');
validateattributes(definition.reference_frequency_hz,{'numeric'},{'scalar','positive','finite'});
validateattributes(definition.reference_psd_dbchz,{'numeric'},{'scalar','real','finite'});
validateattributes(definition.mask_point_count,{'numeric'},{'scalar','integer','>=',2});
validateattributes(definition.upper_nyquist_fraction,{'numeric'},{'scalar','>',0,'<',1});
lo=double(definition.minimum_offset_hz); hi=sampleRateHz/2*definition.upper_nyquist_fraction;
assert(isfinite(lo) && lo>0 && lo<hi,'RF:PhaseNoiseMaskMissing','Invalid mask frequency interval.');
f=logspace(log10(lo),log10(hi),definition.mask_point_count).';
levels=double(definition.reference_psd_dbchz)+20*log10(carrierHz/definition.reference_frequency_hz) ...
    +10*sum(log10(1+(f./fz.').^(az.')),2)-10*sum(log10(1+(f./fp.').^(ap.')),2);
raw=struct('profile_id',string(definition.profile_id),'version',string(definition.version), ...
    'mask_offsets_hz',f,'mask_levels_dbchz',levels,'lo_correlation',definition.lo_correlation, ...
    'synthesis_method',string(definition.synthesis_method),'fir_length',definition.fir_length, ...
    'classification',string(definition.classification),'source',string(definition.source), ...
    'physical_instrument_capability_verified',"UNKNOWN");
end
