function [window,evidence] = applyQCLTimingTransfer(cfg,grant,observation,nominalStart,window,ueIndex)
% Type-A average-delay reuse followed by normal received DM-RS estimation.
% This is not Type-D spatial QCL qualification or channel-truth timing.
evidence=struct('QCLStatus',"not_configured",'QCLType',"", ...
    'QCLSourceRS',"",'QCLSourceResourceID',NaN,'QCLSourceSlot0',NaN, ...
    'QCLSourceAvailableAtSample',NaN,'TCIStateID',NaN,'TCICodepoint',NaN, ...
    'TCIStatus',"not_configured",'TCIInitializationSource',"", ...
    'QCLTimingPriorUsed',false,'QCLTimingPriorSamples',NaN, ...
    'QCLDMRSDelayResidual_samples',NaN, ...
    'QCLMeasurementStatus',"not_measured_requires_QCL_TCI_binding_evidence");
policy=sixgr.util.structGet(cfg,'phy.pdsch.qclTCI',struct());
if isfield(grant,'ReceivedCORESETQCLReference')
        context=sixgr.phy.pdcch.validateConnectedAssignment(cfg,grant);
        reference=sixgr.pdsch.CORESETQCLReference.fromInstalled(cfg,context,grant.ControlAbsoluteSlot);
        assert(~grant.TCIPresent && isequaln(reference,grant.ReceivedCORESETQCLReference), ...
            'sixgr:qcl:CORESETAssociationIdentityMismatch','Default QCL must retain the received scheduling CORESET association.');
        evidence.QCLStatus="installed_CORESET_association_no_measured_parameter_transfer";
        evidence.QCLType=reference.QCLTypes;
        evidence.QCLSourceRS=reference.SourceReferenceSignal;
        evidence.QCLSourceResourceID=reference.Policy.source_reference_signal_id;
        evidence.TCIStatus="field_absent_default_CORESET_QCL_association";
        evidence.TCIInitializationSource=string(reference.Policy.initialization_source);
        evidence.QCLMeasurementStatus=reference.ReceiverParameterReuseStatus;
    return;
end
if ~logical(sixgr.util.structGet(policy,'enabled',false)), return; end
source=sixgr.util.structGet(cfg,'lls6g.userContext.QCLTimingReference',struct());
required={'UEIndex','ServingCellIndex','SourceResourceID','ConfigurationEpoch', ...
    'SourceSlot0','AvailableAtSample','SampleRateHz','TimingPhaseSamples','Source'};
assert(all(isfield(source,required)),'sixgr:qcl:MissingReceivedReference', ...
    'Active QCL requires an earlier received reference for this UE.');
assert(string(source.Source)=="received_nzp_csi_rs_trs_timing_estimator", ...
    'sixgr:qcl:InvalidSource','QCL timing authority must be the received estimator.');
receivedCapsule=isfield(grant,'AssignmentDigest');
assert(receivedCapsule || ~isfield(sixgr.util.structGet( ...
    cfg,'phy.pdcch.operatorControl',struct()),'connected_dci'), ...
    'sixgr:qcl:MissingReceivedTCI', ...
    'Connected QCL cannot substitute scheduler payload-match flags for the received DCI capsule.');
if receivedCapsule
    context=sixgr.phy.pdcch.validateConnectedAssignment(cfg,grant);
    assert(nargin==6 && grant.Direction=="DL" && grant.TCIPresent, ...
        'sixgr:qcl:MissingReceivedTCI','Connected QCL requires received DL TCI and explicit UE identity.');
    validateattributes(ueIndex,{'numeric'},{'scalar','integer','positive','finite'});
    servingCell=double(sixgr.util.structGet(cfg,'lls6g.userContext.RuntimeServingCellIndex',NaN));
    assert(isfield(source,'RRCServingCellIndex') && ...
        source.RRCServingCellIndex==context.Data.ScheduledServingCell, ...
        'sixgr:qcl:ReferenceIdentityMismatch', ...
        'The received RRC serving-cell index must match the reference; it is not the simulator cell index or PCI.');
    codepoint=grant.TCICodepoint; epoch=grant.ConfigurationEpoch;
    assert(grant.DataAbsoluteSlot==cfg.lls6g.runtime.AbsoluteSlotIndex0, ...
        'sixgr:qcl:ReceivedAssignmentClockMismatch','QCL must apply to the actual received data occasion.');
else
assert(all(isfield(grant,{'ReceivedTCICodepoint','ReceivedTCIConfigurationEpoch'})) && ...
    logical(sixgr.util.structGet(grant,'DCICrcPass',false)) && ...
    logical(sixgr.util.structGet(grant,'PDCCHPayloadMatch',false)) && ...
    logical(sixgr.util.structGet(grant,'PDCCHCausalGrantDecodeOk',false)) && ...
    logical(sixgr.util.structGet(grant,'PDCCHGrantBindingOk',false)), ...
    'sixgr:qcl:MissingReceivedTCI','TCI requires actual correctly bound decoded DCI.');
codepoint=grant.ReceivedTCICodepoint; epoch=grant.ReceivedTCIConfigurationEpoch;
ueIndex=grant.UEIndex; servingCell=grant.ServingCell;
end
assert(codepoint==policy.codepoint && ...
    epoch==policy.configuration_epoch && ...
    source.ConfigurationEpoch==policy.configuration_epoch, ...
    'sixgr:qcl:TCIMismatch','Codepoint and epoch must match the installed TCI map.');
slot0=double(sixgr.util.structGet(cfg,'lls6g.runtime.AbsoluteSlotIndex0',NaN));
assert(isfinite(slot0) && slot0>=policy.activation_absolute_slot0 && ...
    source.SourceSlot0<=slot0 && slot0-source.SourceSlot0<=policy.source_max_age_slots && ...
    source.AvailableAtSample<=nominalStart, ...
    'sixgr:qcl:InactiveOrStaleReference','Inactive, future or expired QCL authority is forbidden.');
assert(source.UEIndex==ueIndex && source.ServingCellIndex==servingCell && ...
    source.SourceResourceID==policy.source_resource_id && source.SampleRateHz==observation.SampleRateHz, ...
    'sixgr:qcl:ReferenceIdentityMismatch','QCL cell, UE, resource and sample clock must match.');
prior=nominalStart-observation.StartSample+source.TimingPhaseSamples;
radius=double(policy.timing_search_radius_samples);
validateattributes(prior,{'numeric'},{'scalar','real','finite'});
validateattributes(radius,{'numeric'},{'scalar','integer','positive','finite'});
window=[max(window(1),ceil(prior-radius)),min(window(2),floor(prior+radius))];
assert(window(1)<=window(2),'sixgr:qcl:TimingPriorOutsideObservation', ...
    'Received QCL prior must intersect the actual observation search window.');
evidence.QCLStatus="bound_received_reference_timing_prior";
evidence.QCLType="A";
evidence.QCLSourceRS="NZP-CSI-RS/TRS";
evidence.QCLSourceResourceID=source.SourceResourceID;
evidence.QCLSourceSlot0=source.SourceSlot0;
evidence.QCLSourceAvailableAtSample=source.AvailableAtSample;
evidence.TCIStateID=policy.state_id;
evidence.TCICodepoint=codepoint;
evidence.TCIStatus="received_codepoint_bound_to_preconfigured_state";
evidence.TCIInitializationSource=string(policy.initialization_source);
evidence.QCLTimingPriorUsed=true;
evidence.QCLTimingPriorSamples=prior;
evidence.QCLMeasurementStatus="type_A_average_delay_transfer_only_no_universal_scalar_accuracy";
end
