function evidence=assertFlatStaticAWGNObservation(replay)
% Establish the explicit lab model from executed operator/RF metadata only.
% Never consume channel coefficients, wanted samples, injected SNR or noise
% variance. The practical estimator still fits received known pilot REs.
id='sixgr:phy:rx:FlatAWGNObservationRequired';
assert(strcmp(string(sixgr.util.structGet(replay,'NoiseOperatingMode','')), ...
    'standalone_awgn_snr_argument'),id,'Flat LS requires executed white AWGN.');
segments=sixgr.util.structGet(replay,'ReceiveStreamExecutionSegments',{});
assert(iscell(segments) && ~isempty(segments),id, ...
    'Require actual shared-stream execution, not configuration alone.');
receiverID=string(sixgr.util.structGet(replay,'ReceiverID',''));
transmitterID=string(sixgr.util.structGet(replay,'TransmitterID',''));
assert(isscalar(receiverID) && strlength(receiverID)>0 && ...
    isscalar(transmitterID) && strlength(transmitterID)>0,id, ...
    'Bind eligibility to the actual captured RX and scheduled TX endpoints.');
activeSegments=0;
for k=1:numel(segments)
    e=segments{k}.Execution;
    assert(isfield(e,'Links'),id,'Require executed physical-link metadata.');
    links=e.Links(string({e.Links.RX})==receiverID);
    assert(numel(links)<=1,id, ...
        'This flat white-noise model does not support multiple incoming links.');
    % A TDD receive window can extend into the opposite direction. Check
    % this receiver's RF in every segment, but never treat the opposite
    % endpoint's link as a channel applied to this captured receiver.
    if ~isempty(links)
    link=links;
    assert(string(link.TX)==transmitterID,id,'Incoming link changed transmitter.');
    activeSegments=activeSegments+1;
    source=string(sixgr.util.structGet(link.Replay,'RuntimeChannelTimingTruthSource',''));
    assert(any(source==["executed_identity_operator_zero_delay", ...
        "executed_fixed_matrix_operator_zero_delay"]) && ...
        isequal(sixgr.util.structGet(link.Replay,'ChannelFadingApplied',true),false), ...
        id,'Do not expand flat estimates over a fading or unknown operator.');
    end
    tx=e.TX(string({e.TX.ID})==transmitterID);
    rx=e.RX(string({e.RX.ID})==receiverID);
    assert(isscalar(tx) && isscalar(rx),id,'Execution must identify both RF endpoints.');
    assert(isequal(sixgr.util.structGet(tx.Replay,'RFConfiguredStageCount',NaN),0) && ...
        isequal(sixgr.util.structGet(tx.Replay,'RFAppliedStageCount',NaN),0), ...
        id,'Flat estimator does not support configured or executed TX impairments.');
    r=rx.Replay;
    clean=isequal(sixgr.util.structGet(r,'RFConfiguredStageCount',NaN),0) && ...
        isequal(sixgr.util.structGet(r,'RFAppliedStageCount',NaN),0);
    compensated=isequal(sixgr.util.structGet(replay,'ReceiverGainCompensation.GainOnlyRFExecuted',false),true) && ...
        isequal(sixgr.util.structGet(r,'RFConfiguredStageCount',NaN), ...
            double(sixgr.util.structGet(r,'AGCEnabled',NaN))) && ...
        isequal(sixgr.util.structGet(r,'RFAppliedStageCount',NaN), ...
            double(sixgr.util.structGet(r,'AGCApplied',NaN)));
    assert(clean || compensated,id, ...
        'Require disabled RX impairments or actually inverted gain-only AGC.');
end
assert(activeSegments>0,id,'No executed channel reaches the captured receiver.');
evidence=struct('Source',"executed_flat_operator_and_white_noise_RF_eligibility", ...
    'ReceiverID',receiverID,'ExecutionSegmentCount',numel(segments), ...
    'ActiveLinkSegmentCount',activeSegments, ...
    'ChannelCoefficientsConsumed',false,'InjectedNoiseVarianceConsumed',false);
end
