function [llr,evidence]=demapQPSKEqualizerOutput(result)
%DEMAPQPSKEQUALIZEROUTPUT Exact single-layer conditional QPSK bit likelihood.
% An MMSE output is y=g*s+z, not y=s+z. Use the executed complex WH gain and
% its output variance for every RE, without changing samples or adding noise.
% This does not account for unmodelled channel-estimation error and does not
% qualify signal presence, codeword confidence or physical false/missed ACKs.
required={'EqualizedSymbols','EffectiveResponseWH','OutputNoiseInterferenceCovariance', ...
    'NumTxPorts','NoiseAddedExactlyOnce','SymbolCovarianceConvention'};
assert(isstruct(result) && isscalar(result) && all(isfield(result,required)), ...
    'sixgr:phy:rx:MissingQPSKEqualizerEvidence','Supply the complete executed equalizer result.');
assert(result.NumTxPorts==1 && isequal(result.NoiseAddedExactlyOnce,true) && ...
    string(result.SymbolCovarianceConvention)=="unit_layer_symbol_covariance", ...
    'sixgr:phy:rx:UnsupportedQPSKEqualizerContract', ...
    'This demapper requires one unit-power QPSK layer and noise counted once.');
y=result.EqualizedSymbols; g=result.EffectiveResponseWH;
v=result.OutputNoiseInterferenceCovariance;
assert(isnumeric(y) && isnumeric(g) && isnumeric(v) && iscolumn(y) && ...
    ~isempty(y) && numel(g)==numel(y) && numel(v)==numel(y) && ...
    all(isfinite(y(:))) && all(isfinite(g(:))) && all(isfinite(v(:))), ...
    'sixgr:phy:rx:InvalidQPSKEqualizerShape', ...
    'Every received symbol requires its own finite WH response and output covariance.');
y=double(y(:)); g=double(g(:)); v=double(v(:));
assert(all(abs(imag(v))<=32*eps(max(1,abs(v)))) && all(real(v)>0), ...
    'sixgr:phy:rx:InvalidQPSKOutputVariance', ...
    'Use positive real output disturbance variance; no mean-variance or epsilon rescue.');
v=real(v);
matched=conj(g).*y;
llr=reshape([2*sqrt(2)*real(matched)./v, 2*sqrt(2)*imag(matched)./v].',[],1);
assert(all(isfinite(llr)),'sixgr:phy:rx:NonfiniteQPSKLLR', ...
    'Receiver likelihood overflow must not become fabricated confidence.');
evidence=struct('Source',"received_equalizer_complex_response_and_per_RE_output_covariance", ...
    'LLRConvention',"log_P_bit0_over_P_bit1", ...
    'Equation',"L=[2sqrt(2)Re(conj(g)y)/v,2sqrt(2)Im(conj(g)y)/v]", ...
    'SymbolCount',numel(y),'ZeroResponseRECount',nnz(g==0), ...
    'NoiseAdded',false,'MeanVarianceUsed',false,'TransmittedBitsUsed',false, ...
    'Model',"conditional_on_estimated_channel_and_equalizer_covariance", ...
    'PhysicalQualificationPassed',false);
end
