function evidence=detectFormat2DMRSPresence(carrier,pucch,rxGrid,targetFalseAlarm,hypothesisCount)
% Conditional white-noise presence test from receiver-known Format-2 DM-RS.
% No decoded codeword, TX waveform, injected variance or estimated H is used.
% Caller must establish spatial/RE-white equal-variance Gaussian disturbance,
% native OFDM sampling and the full searched timing/frequency/resource count.
% This is NOT physical qualification or a detector mandated by 3GPP.
assert(isa(carrier,'nrCarrierConfig') && isscalar(carrier) && ...
    isa(pucch,'nrPUCCH2Config') && isscalar(pucch) && ...
    ~(isprop(pucch,'Interlacing') && pucch.Interlacing), ...
    'sixgr:phy:pucch:UnsupportedPilotPresenceResource', ...
    'Use an installed non-interlaced Format-2 receive resource.');
assert(isfloat(rxGrid) && ndims(rxGrid)<=3 && ...
    size(rxGrid,1)==12*carrier.NSizeGrid && ...
    size(rxGrid,2)==carrier.SymbolsPerSlot, ...
    'sixgr:phy:pucch:InvalidPilotPresenceGrid','Use the actual complete received slot grid.');
indices=nrPUCCHDMRSIndices(carrier,pucch);
reference=nrPUCCHDMRS(carrier,pucch);
assert(iscolumn(indices) && iscolumn(reference) && numel(indices)==numel(reference) && ...
    numel(unique(indices))==numel(indices) && ...
    all(indices>=1 & indices<=size(rxGrid,1)*size(rxGrid,2)), ...
    'sixgr:phy:pucch:InvalidPilotPresenceReference','Require distinct, single-port known pilot REs.');
branches=reshape(rxGrid,[],size(rxGrid,3));
% Reuse the already-tested projection/Beta-tail kernel; only resource
% extraction is Format-2-specific. Its null law is conditional, not a label
% that can be attached to an arbitrary colored/selected observation.
evidence=sixgr.phy.trs.whiteNoiseCoherenceDecision( ...
    branches(indices,:),reference,targetFalseAlarm,hypothesisCount);
evidence.ReferenceSource="receiver_known_PUCCH_DMRS_TS_38_211_6_4_1_3_2";
evidence.TransmittedPayloadUsed=false;
evidence.DecodedWordUsed=false;
evidence.InjectedNoiseVarianceUsed=false;
evidence.NoiseModelEstablishedByThisFunction=false;
evidence.PhysicalQualificationPassed=false;
end
