classdef PUCCHPowerController
    %PUCCHPOWERCONTROLLER Pinned open/closed-loop PUCCH power ledger.

    methods (Static)
        function result = resolve(state)
            if isa(state,"sixgr.phy.pucch.PUCCHPowerControlState")
                d = state.Data;
                stateID = d.StateID;
            elseif isstruct(state)
                d = state;
                stateID = sixgr.phy.pucch.PUCCHUtil.field(d,"StateID","");
            else
                error("sixgr:phy:pucch:InvalidPowerControlState", ...
                    "Power control requires a typed state.");
            end
            bandwidth = 10*log10((2^double(d.Mu))*double(d.MRB));
            if string(sixgr.phy.pucch.PUCCHUtil.field(d,'OperatingPointAuthority',''))=="configured_occupied_re_esn0"
                % Also validate struct callers; a mode string alone cannot
                % authorize an incomplete or physically scaled state.
                sixgr.phy.pucch.PUCCHPowerControlState(d);
                result=struct('StateID',stateID,'BandwidthTermdB',bandwidth, ...
                    'Mu',double(d.Mu),'MRB',double(d.MRB), ...
                    'BandwidthSource',string(d.BandwidthSource), ...
                    'RequestedPowerdBm',NaN,'AppliedPowerdBm',NaN,'Clipped',false, ...
                    'PowerHeadroomdB',NaN,'PCMAXdBm',NaN,'PathlossdB',NaN, ...
                    'ConfiguredPathlossdB',NaN,'PathlossSource','not_applicable_normalized_fixed_esn0', ...
                    'PathlossReferenceRS',"",'PathlossMeasurementId',"",'PathlossMeasurementSlot',NaN, ...
                    'RuntimeMeasuredPathlossUsed',false,'PowerError_dB',NaN, ...
                    'NormalizedPowerReference',true,'PhysicalPowerApplicable',false, ...
                    'ReferenceEnergyPerOccupiedRE',1,'OperatingPointAuthority','configured_occupied_re_esn0', ...
                    'Digest',sixgr.phy.pucch.PUCCHUtil.hash(d));
                return;
            end
            requested = double(d.P0dBm)+double(d.PathlossdB)+bandwidth+ ...
                double(d.DeltaFdB)+double(d.DeltaTFdB)+ ...
                double(d.ClosedLoopAdjustmentdB);
            applied = min(double(d.PCMAXdBm),requested);
            result = struct("StateID",stateID,"BandwidthTermdB",bandwidth, ...
                "Mu",double(d.Mu),"MRB",double(d.MRB), ...
                "BandwidthSource",string(sixgr.phy.pucch.PUCCHUtil.field( ...
                    d,"BandwidthSource","explicit_power_control_state")), ...
                "RequestedPowerdBm",requested,"AppliedPowerdBm",applied, ...
                "Clipped",applied < requested, ...
                "PowerHeadroomdB",double(d.PCMAXdBm)-requested, ...
                "PCMAXdBm",double(d.PCMAXdBm), ...
                "PathlossdB",double(d.PathlossdB), ...
                "ConfiguredPathlossdB",double(sixgr.phy.pucch.PUCCHUtil.field( ...
                    d,"ConfiguredPathlossdB",d.PathlossdB)), ...
                "PathlossSource",string(sixgr.phy.pucch.PUCCHUtil.field( ...
                    d,"PathlossSource","unlabelled")), ...
                "PathlossReferenceRS",string(sixgr.phy.pucch.PUCCHUtil.field( ...
                    d,"PathlossReferenceRS","")), ...
                "PathlossMeasurementId",string(sixgr.phy.pucch.PUCCHUtil.field( ...
                    d,"PathlossMeasurementId","")), ...
                "PathlossMeasurementSlot",double(sixgr.phy.pucch.PUCCHUtil.field( ...
                    d,"PathlossMeasurementSlot",NaN)), ...
                "RuntimeMeasuredPathlossUsed",logical( ...
                    sixgr.phy.pucch.PUCCHUtil.field( ...
                    d,"RuntimeMeasuredPathlossUsed",false)), ...
                "PowerError_dB",0, ...
                "Digest",sixgr.phy.pucch.PUCCHUtil.hash(struct( ...
                "Requested",requested,"Applied",applied,"StateID",stateID)));
        end

        function result = resolveVector(row)
            data = struct( ...
                "Mu",sixgr.phy.pucch.PUCCHUtil.number(row,"Mu"), ...
                "MRB",sixgr.phy.pucch.PUCCHUtil.number(row,"MRB"), ...
                "P0dBm",sixgr.phy.pucch.PUCCHUtil.number(row,"P0dBm"), ...
                "PathlossdB",sixgr.phy.pucch.PUCCHUtil.number(row,"PathlossdB"), ...
                "DeltaFdB",sixgr.phy.pucch.PUCCHUtil.number(row,"DeltaFdB"), ...
                "DeltaTFdB",sixgr.phy.pucch.PUCCHUtil.number(row,"DeltaTFdB"), ...
                "ClosedLoopAdjustmentdB",sixgr.phy.pucch.PUCCHUtil.number( ...
                row,"ClosedLoopAdjustmentdB"), ...
                "PCMAXdBm",sixgr.phy.pucch.PUCCHUtil.number(row,"PCMAXdBm"), ...
                "PathlossReferenceRSID",0,"TPCCommandSource", ...
                "independent_vector","StateID", ...
                sixgr.phy.pucch.PUCCHUtil.text(row,"CaseID"));
            result = sixgr.phy.pucch.PUCCHPowerController.resolve( ...
                sixgr.phy.pucch.PUCCHPowerControlState(data));
        end
    end
end
