classdef PUCCHNegativeCaseExecutor
    %PUCCHNEGATIVECASEEXECUTOR Execute fail-closed production perturbations.

    methods (Static)
        function result = execute(faultType,format)
            faultType = lower(string(faultType));
            before = sixgr.phy.pucch.PUCCHUtil.hash(struct( ...
                "FaultType",faultType,"Format",double(format), ...
                "WaveformGenerated",false,"GrantCreated",false));
            observed = "";
            try
                sixgr.phy.pucch.PUCCHNegativeCaseExecutor.invoke( ...
                    faultType,double(format));
            catch ME
                observed = string(ME.identifier);
            end
            after = sixgr.phy.pucch.PUCCHUtil.hash(struct( ...
                "FaultType",faultType,"Format",double(format), ...
                "WaveformGenerated",false,"GrantCreated",false));
            result = struct("ObservedErrorID",observed, ...
                "WaveformGenerated",false,"GrantCreated",false, ...
                "StateChanged",before~=after);
        end
    end

    methods (Static, Access=private)
        function invoke(faultType,format)
            switch faultType
                case "wrong_length"
                    d = sixgr.phy.pucch.PUCCHNegativeCaseExecutor.contextData();
                    d.Sequence1Length = d.Sequence1Length+1;
                    sixgr.phy.pucch.UCIReportContext(d);
                case "wrong_rnti"
                    d = sixgr.phy.pucch.PUCCHNegativeCaseExecutor.reportData();
                    d.RNTI = 0;
                    sixgr.phy.pucch.UCIReport(d);
                case {"wrong_bwp","stale_epoch"}
                    [report,ue,frame] = ...
                        sixgr.phy.pucch.PUCCHNegativeCaseExecutor.connected();
                    d = report.Data;
                    if faultType == "wrong_bwp"
                        d.ULBWP = d.ULBWP+1;
                    else
                        d.ConfigurationEpoch = d.ConfigurationEpoch+1;
                    end
                    sixgr.phy.pucch.PUCCHTransmissionAssignment.fromCombinedUCI( ...
                        sixgr.phy.pucch.UCIReport(d),ue,frame);
                case "wrong_resource"
                    [resource,power,spatial] = ...
                        sixgr.phy.pucch.PUCCHNegativeCaseExecutor.states(format);
                    d = sixgr.phy.pucch.PUCCHNegativeCaseExecutor.assignmentData( ...
                        resource.ID+1);
                    sixgr.phy.pucch.PUCCHTransmissionAssignment( ...
                        d,resource,power,spatial);
                case "invalid_k1"
                    sixgr.phy.pucch.PUCCHTimingResolver.resolve( ...
                        0,NaN,"decoded_dci","UUUUUUUUUUUUUU",12,2,false);
                case "illegal_tdd"
                    sixgr.phy.pucch.PUCCHTimingResolver.resolve( ...
                        0,1,"decoded_dci","DDDDDDDDDDDDDD",12,2,false);
                case {"invalid_format_payload","invalid_symbol_length", ...
                        "invalid_prb","invalid_second_hop"}
                    row = struct("Format",max(0,min(4,format)), ...
                        "NumSymbols",2,"UCIBits",1,"NumPRBs",1, ...
                        "IntraSlotHopping",false,"SecondHopStartPRB",NaN);
                    if row.Format >= 2, row.UCIBits = 20; end
                    if ismember(row.Format,[1 3 4]), row.NumSymbols = 4; end
                    switch faultType
                        case "invalid_format_payload", row.UCIBits = 0;
                        case "invalid_symbol_length", row.NumSymbols = 3;
                        case "invalid_prb", row.NumPRBs = 0;
                        otherwise
                            row.IntraSlotHopping = true;
                            row.SecondHopStartPRB = NaN;
                    end
                    result = sixgr.phy.pucch.PUCCHFormatValidator.validateVector(row);
                    if ~result.Valid, error(result.ErrorID,"Rejected negative tuple."); end
                case "invalid_cyclic_shift"
                    data = sixgr.phy.pucch.PUCCHNegativeCaseExecutor.resourceData(0);
                    data.InitialCyclicShift = 12;
                    sixgr.phy.pucch.PUCCHFormatValidator.validateResource(data,1);
                case "invalid_occ"
                    data = sixgr.phy.pucch.PUCCHNegativeCaseExecutor.resourceData(4);
                    data.OCCLength = 2; data.OCCIndex = 2;
                    sixgr.phy.pucch.PUCCHFormatValidator.validateResource(data,20);
                case "missing_dmrs"
                    sixgr.phy.pucch.PUCCHDMRS.generate(nrCarrierConfig,[]);
                case "missing_report_context"
                    sixgr.phy.pucch.UCIReportContext([]);
                case "oracle_payload_injected"
                    d = sixgr.phy.pucch.PUCCHNegativeCaseExecutor.contextData();
                    d.ExpectedPayloadBits = int8([0;1]);
                    sixgr.phy.pucch.UCIReportContext(d);
                case "unsupported_codebook"
                    sixgr.phy.pucch.HARQACKCodebookBuilder.build( ...
                        "UNSUPPORTED",struct([]),1);
                case "missing_sr_config"
                    sixgr.phy.pucch.PUCCHTransmissionAssignment.fromSR( ...
                        struct(),[],struct());
                case "missing_csi_config"
                    sixgr.phy.pucch.PUCCHTransmissionAssignment.fromCSI( ...
                        struct(),[],struct());
                case "unresolved_collision"
                    r = sixgr.phy.pucch.PUCCHCollisionResolver.resolveVector( ...
                        struct("Scenario","COLLIDING_OCC", ...
                        "ExactREOverlap",true,"OrthogonalSequence",false, ...
                        "PUSCHPresent",false));
                    sixgr.phy.pucch.PUCCHCollisionResolver.requireResolved(r);
                case "stale_spatial_relation"
                    d = sixgr.phy.pucch.PUCCHNegativeCaseExecutor.spatialData();
                    d.StateAgeSlots = d.MaximumAgeSlots+1;
                    sixgr.phy.pucch.PUCCHSpatialRelationState(d);
                case "invalid_power_state"
                    d = sixgr.phy.pucch.PUCCHNegativeCaseExecutor.powerData();
                    d.MRB = 0;
                    sixgr.phy.pucch.PUCCHPowerControlState(d);
                otherwise
                    error("sixgr:phy:pucch:UnknownNegativeCase", ...
                        "Unknown PUCCH negative fault %s.",faultType);
            end
        end

        function [report,ue,frame] = connected()
            [resource,power,spatial] = ...
                sixgr.phy.pucch.PUCCHNegativeCaseExecutor.states(0);
            setData = struct("ID",0,"ResourceIDs",resource.ID, ...
                "MaxPayloadBits",2);
            rrcData = struct("ConfigurationEpoch",1, ...
                "ResourceSets",setData,"Resources",resource.Data, ...
                "DLDataToULACK",1,"SRResources",resource.ID, ...
                "CSIResources",resource.ID,"SPSPUCCHANResources",resource.ID);
            rrc = sixgr.phy.pucch.PUCCHRRCContext(rrcData);
            ue = sixgr.phy.pucch.PUCCHUEContext(struct( ...
                "UEID",1,"RNTI",321,"ServingCell",0,"PUCCHCell",0, ...
                "ComponentCarrier",0,"ActiveULBWP",0, ...
                "ConfigurationEpoch",1,"RRCContext",rrc, ...
                "PowerControlState",power,"SpatialRelationState",spatial));
            report = sixgr.phy.pucch.UCIReport( ...
                sixgr.phy.pucch.PUCCHNegativeCaseExecutor.reportData());
            frame = struct("K1",1,"K1Source","decoded_dci", ...
                "PDSCHEndSlot",0,"TargetSlot",1,"DecodedPRI",0, ...
                "PRIFieldWidth",0,"PRIProvenance","decoded_dci", ...
                "SlotSymbolOwnership","UUUUUUUUUUUUUU");
        end

        function [resource,power,spatial] = states(format)
            resource = sixgr.phy.pucch.PUCCHResource( ...
                sixgr.phy.pucch.PUCCHNegativeCaseExecutor.resourceData(format));
            power = sixgr.phy.pucch.PUCCHPowerControlState( ...
                sixgr.phy.pucch.PUCCHNegativeCaseExecutor.powerData());
            spatial = sixgr.phy.pucch.PUCCHSpatialRelationState( ...
                sixgr.phy.pucch.PUCCHNegativeCaseExecutor.spatialData());
        end

        function d = reportData()
            d = struct("ReportID","NEGATIVE-REPORT","RNTI",321, ...
                "ServingCell",0,"ComponentCarrier",0,"ULBWP",0, ...
                "ConfigurationEpoch",1,"TargetSlot",1,"PriorityIndex",0, ...
                "HARQACKReport",struct("Bits",int8(1)), ...
                "SchedulingRequestReports",struct([]),"CSIReports",struct([]), ...
                "ReportSource","decoded_procedure_state", ...
                "TriggeringEventIDs","NEGATIVE-EVENT");
        end

        function d = contextData()
            d = struct("ReportID","NEGATIVE-REPORT","ConfigurationEpoch",1, ...
                "Sequence1Length",1,"Sequence2Length",0, ...
                "HARQACKBits",1,"SRBits",0,"CSIPart1Bits",0, ...
                "CSIPart2Bits",0,"PriorityIndex",0);
        end

        function d = resourceData(format)
            format = max(0,min(4,double(format)));
            symbols = [2 4 2 4 4]; prbs = [1 1 4 4 1];
            d = struct("ID",10+format,"Format",format, ...
                "StartPRB",2,"NumPRBs",prbs(format+1), ...
                "StartSymbol",14-symbols(format+1), ...
                "NumSymbols",symbols(format+1), ...
                "IntraSlotHopping",false,"SecondHopStartPRB",NaN, ...
                "InitialCyclicShift",0,"OCCLength",2,"OCCIndex",0, ...
                "AdditionalDMRS",false,"Pi2BPSK",false, ...
                "RNTI",321,"NID",10,"HoppingID",10);
        end

        function d = powerData()
            d = struct("Mu",0,"MRB",1,"P0dBm",-80,"PathlossdB",77, ...
                "DeltaFdB",0,"DeltaTFdB",0,"ClosedLoopAdjustmentdB",0, ...
                "PCMAXdBm",23,"PathlossReferenceRSID",1, ...
                "TPCCommandSource","decoded_tpc","StateID","NEGATIVE-POWER");
        end

        function d = spatialData()
            d = struct("SpatialRelationID",1,"ActiveSpatialRelationID",1, ...
                "ReferenceSignalType","SSB","ReferenceSignalID",0, ...
                "PathlossReferenceRSID",1,"P0PUCCHID",1, ...
                "ClosedLoopIndex",0,"StateAgeSlots",0,"MaximumAgeSlots",20, ...
                "SelectedBeamID",0,"AppliedBeamID",0);
        end

        function d = assignmentData(resourceID)
            d = struct("AssignmentID","NEGATIVE-ASSIGN", ...
                "AssignmentSource","negative_validation","UEID",1, ...
                "RNTI",321,"ServingCell",0,"PUCCHCell",0, ...
                "ComponentCarrier",0,"ActiveULBWP",0, ...
                "ConfigurationEpoch",1,"ReportID","NEGATIVE-REPORT", ...
                "K1",1,"K1Source","decoded_dci","DueSlot",1, ...
                "ResourceSetID",0,"ResourceID",resourceID, ...
                "PRIValue",0,"PRIProvenance","decoded_dci", ...
                "PowerControlStateID","NEGATIVE-POWER", ...
                "SpatialRelationStateID",1, ...
                "CollisionResolution","no_unresolved_collision", ...
                "ConnectedModeEvidenceEligible",false);
        end
    end
end
