classdef PUCCHTransmitter
    %PUCCHTRANSMITTER Canonical typed-report PUCCH waveform transmitter.

    methods (Static)
        function tx = transmit(carrier,assignment,report)
            if ~isa(assignment,"sixgr.phy.pucch.PUCCHTransmissionAssignment") || ...
                    ~isa(report,"sixgr.phy.pucch.UCIReport")
                error("sixgr:phy:pucch:MissingUCIReportContext", ...
                    "PUCCH TX requires typed assignment and report.");
            end
            if assignment.ReportID ~= report.ReportID || ...
                    assignment.ConfigurationEpoch ~= report.ConfigurationEpoch
                error("sixgr:phy:pucch:StaleConfiguration", ...
                    "PUCCH report and assignment ownership differ.");
            end
            serialized = sixgr.phy.pucch.UCIReportSerializer.serialize(report);
            bits = [serialized.Sequence1.Bits;serialized.Sequence2.Bits];
            sixgr.phy.pucch.PUCCHFormatValidator.validateResource( ...
                assignment.Resource.Data,numel(bits));
            pucch = assignment.Resource.toolboxConfig();
            [~,info] = nrPUCCHIndices(carrier,pucch);
            if assignment.Format <= 1
                symbols = nrPUCCH(carrier,pucch,bits);
                coding = struct("Plan",sixgr.phy.pucch.UCIEncodingPlan( ...
                    numel(bits),numel(bits)),"CodedBits",bits, ...
                    "CodedDigest",sixgr.phy.pucch.PUCCHUtil.hash(bits.'));
            else
                coding = sixgr.phy.pucch.UCIEncoder.encode( ...
                    sixgr.phy.pucch.UCISequence(1,bits, ...
                    repmat("UCI",numel(bits),1), ...
                    repmat("combined_report_sequence",numel(bits),1)), ...
                    double(info.G),localModulation(pucch));
                symbols = nrPUCCH(carrier,pucch,coding.CodedBits);
            end
            mapped = sixgr.phy.pucch.PUCCHGridMapper.map( ...
                carrier,assignment,symbols);
            [waveform,ofdmInfo] = sixgr.phy.waveform.ofdmModulate( ...
                carrier,mapped.Grid);
            power = sixgr.phy.pucch.PUCCHPowerController.resolve( ...
                assignment.PowerControlState);
            waveform = localApplyPower(waveform,power.AppliedPowerdBm);
            % Canonical simulator samples use sqrt(mW), so mean |x|^2 is
            % directly expressed in mW and converts to dBm without a
            % watts-to-milliwatts factor.
            measured = 10*log10(max(mean(abs(waveform(:)).^2),realmin));
            power.MeasuredWaveformPowerdBm = measured;
            power.PowerError_dB = measured-power.AppliedPowerdBm;
            tx = struct( ...
                "Waveform",waveform,"Grid",mapped.Grid,"Carrier",carrier, ...
                "PUCCH",pucch,"Assignment",assignment,"Report",report, ...
                "PUCCHIndices",mapped.DataIndices, ...
                "DMRSIndices",mapped.DMRS.Indices, ...
                "Serialization",serialized,"Coding",coding, ...
                "Ownership",mapped.Ownership,"DMRS",mapped.DMRS, ...
                "Power",power,"OFDMInfo",ofdmInfo, ...
                "ExecutionProfile",localProfile(assignment), ...
                "ConnectedModeEvidenceEligible",logical( ...
                assignment.Data.ConnectedModeEvidenceEligible), ...
                "AssignmentDigest",assignment.Digest, ...
                "ReportDigest",report.Digest, ...
                "SerializationDigest",serialized.Digest, ...
                "CodingPlanDigest",coding.Plan.Digest, ...
                "ResourceOwnershipDigest",mapped.Ownership.Digest, ...
                "DMRSSequenceDigest",mapped.DMRS.SequenceSHA256, ...
                "DMRSIndexDigest",mapped.DMRS.IndexSHA256, ...
                "PowerStateDigest",assignment.PowerControlState.Digest, ...
                "SpatialStateDigest",assignment.SpatialRelationState.Digest, ...
                "WaveformSHA256",sixgr.phy.pucch.PUCCHUtil.hash( ...
                [real(waveform(:)).' imag(waveform(:)).']));
        end
    end
end

function value = localModulation(pucch)
value = "QPSK";
if isprop(pucch,"Modulation"), value = string(pucch.Modulation); end
end

function waveform = localApplyPower(waveform,powerdBm)
current = mean(abs(waveform(:)).^2);
target = 10^(double(powerdBm)/10);
if current <= 0 || ~isfinite(current)
    error("sixgr:phy:pucch:InvalidPowerControlState", ...
        "Cannot apply PUCCH power to an empty waveform.");
end
waveform = waveform*sqrt(target/current);
end

function value = localProfile(assignment)
if assignment.Data.ConnectedModeEvidenceEligible
    value = "connected_strict";
else
    value = "calibration";
end
end
