classdef PUCCHResourcePlan
    %PUCCHRESOURCEPLAN Pure RRC/UCI/PRI/timing selection, not a TX assignment.
    % No transmit power, waveform, reception, or eligibility is manufactured.
    properties (SetAccess=private)
        Data
        Resource
        ReportDigest
        RRCContextDigest
        Digest
    end
    properties (Dependent)
        Format
    end
    methods
        function obj=PUCCHResourcePlan(report,ue,rrc,frame,source)
            if ~isa(report,'sixgr.phy.pucch.UCIReport') || ...
                    ~isa(rrc,'sixgr.phy.pucch.PUCCHRRCContext')
                error('sixgr:phy:pucch:MissingUCIReportContext', ...
                    'Resource planning requires typed report and RRC configuration.');
            end
            sixgr.phy.pucch.UCIReport.requireFields(ue, ...
                ["UEID","RNTI","ServingCell","PUCCHCell", ...
                "ComponentCarrier","ActiveULBWP","ConfigurationEpoch"]);
            if report.ConfigurationEpoch~=double(ue.ConfigurationEpoch) || ...
                    report.ConfigurationEpoch~=rrc.ConfigurationEpoch
                error('sixgr:phy:pucch:StaleConfiguration','Report/UE/RRC epochs differ.');
            end
            if double(report.Data.ULBWP)~=double(ue.ActiveULBWP)
                error('sixgr:phy:pucch:StaleBWP','Report UL BWP differs from active UE BWP.');
            end
            if double(report.Data.RNTI)~=double(ue.RNTI)
                error('sixgr:phy:pucch:WrongRNTI','Report RNTI differs from active UE context.');
            end
            if double(report.Data.ServingCell)~=double(ue.ServingCell) || ...
                    double(report.Data.ComponentCarrier)~=double(ue.ComponentCarrier)
                error('sixgr:phy:pucch:WrongResource','Report serving cell/carrier differs from UE context.');
            end
            set=sixgr.phy.pucch.PUCCHResourceSetResolver.resolve(report,rrc);
            priRow=struct('ResourceSetID',set.ID,'ResourceListSize',numel(set.ResourceIDs), ...
                'PRIFieldWidth',sixgr.phy.pucch.PUCCHUtil.field(frame,'PRIFieldWidth', ...
                ceil(log2(max(1,numel(set.ResourceIDs))))), ...
                'PRIValue',sixgr.phy.pucch.PUCCHUtil.field(frame,'DecodedPRI',0), ...
                'FirstCCE',sixgr.phy.pucch.PUCCHUtil.field(frame,'FirstCCE',NaN), ...
                'NumCCE',sixgr.phy.pucch.PUCCHUtil.field(frame,'NumCCE',NaN), ...
                'RequiresSet0CCEFormula',set.ID==0 && numel(set.ResourceIDs)>8);
            pri=sixgr.phy.pucch.PUCCHResourceIndicatorResolver.resolveVector(priRow);
            if ~pri.Valid
                error(pri.ErrorID,'Invalid decoded PUCCH PRI: set=%g count=%g PRI=%g firstCCE=%g numCCE=%g.', ...
                    priRow.ResourceSetID,priRow.ResourceListSize,priRow.PRIValue, ...
                    priRow.FirstCCE,priRow.NumCCE);
            end
            resource=rrc.resourceByID(set.ResourceIDs(pri.Ordinal));
            k1=double(sixgr.phy.pucch.PUCCHUtil.field(frame,'K1',NaN));
            k1Source=string(sixgr.phy.pucch.PUCCHUtil.field(frame,'K1Source','decoded_dci'));
            pdschEnd=double(sixgr.phy.pucch.PUCCHUtil.field(frame,'PDSCHEndSlot',report.Data.TargetSlot-k1));
            ownership=string(sixgr.phy.pucch.PUCCHUtil.field(frame,'SlotSymbolOwnership','UUUUUUUUUUUUUU'));
            timing=sixgr.phy.pucch.PUCCHTimingResolver.resolve(pdschEnd,k1,k1Source, ...
                ownership,resource.Data.StartSymbol,resource.Data.NumSymbols, ...
                logical(sixgr.phy.pucch.PUCCHUtil.field(frame,'FlexibleResolutionProvided',false)));
            if timing.DueSlot~=double(report.Data.TargetSlot)
                error('sixgr:phy:pucch:InvalidK1','UCI target differs from the resolved feedback occasion.');
            end
            serialized=sixgr.phy.pucch.UCIReportSerializer.serialize(report);
            sixgr.phy.pucch.PUCCHFormatValidator.validateResource(resource.Data, ...
                numel(serialized.Sequence1.Bits)+numel(serialized.Sequence2.Bits));
            obj.Data=struct('AssignmentID',"PUCCH-"+report.ReportID+"-"+string(timing.DueSlot), ...
                'AssignmentSource',string(source),'UEID',ue.UEID,'RNTI',ue.RNTI, ...
                'ServingCell',ue.ServingCell,'PUCCHCell',ue.PUCCHCell, ...
                'ComponentCarrier',ue.ComponentCarrier,'ActiveULBWP',ue.ActiveULBWP, ...
                'ConfigurationEpoch',report.ConfigurationEpoch,'ReportID',report.ReportID, ...
                'K1',k1,'K1Source',k1Source,'DueSlot',timing.DueSlot, ...
                'ResourceSetID',set.ID,'ResourceID',resource.ID,'PRIValue',priRow.PRIValue, ...
                'PRIProvenance',sixgr.phy.pucch.PUCCHUtil.field(frame,'PRIProvenance','decoded_dci'));
            obj.Resource=resource;
            obj.ReportDigest=report.Digest;
            obj.RRCContextDigest=rrc.Digest;
            obj.Digest=sixgr.phy.pucch.PUCCHUtil.hash(struct('Data',obj.Data, ...
                'ResourceDigest',resource.Digest,'ReportDigest',obj.ReportDigest, ...
                'RRCContextDigest',obj.RRCContextDigest));
        end
        function value=get.Format(obj), value=obj.Resource.Format; end
    end
end
