classdef ProtocolVectorValidator
    %PROTOCOLVECTORVALIDATOR Replay independent bounded protocol floors.

    methods (Static)
        function result = validate(vectorRoot)
            arguments
                vectorRoot (1,1) string
            end
            families = { ...
                "rlc_um_header", "protocol_rlc_um_header_vectors.csv", ...
                    @sixgr.protocol.ProtocolVectorValidator.rlcUM; ...
                "rlc_am_header", "protocol_rlc_am_header_vectors.csv", ...
                    @sixgr.protocol.ProtocolVectorValidator.rlcAM; ...
                "rlc_status", "protocol_rlc_status_vectors.csv", ...
                    @sixgr.protocol.ProtocolVectorValidator.rlcStatus; ...
                "rlc_state", "protocol_rlc_timer_state_vectors.csv", ...
                    @sixgr.protocol.ProtocolVectorValidator.rlcState; ...
                "pdcp_header", "protocol_pdcp_header_vectors.csv", ...
                    @sixgr.protocol.ProtocolVectorValidator.pdcpHeader; ...
                "pdcp_count", "protocol_pdcp_count_vectors.csv", ...
                    @sixgr.protocol.ProtocolVectorValidator.pdcpCount; ...
                "pdcp_security", "protocol_pdcp_security_vectors.csv", ...
                    @sixgr.protocol.ProtocolVectorValidator.pdcpSecurity; ...
                "pdcp_reordering", "protocol_pdcp_reordering_vectors.csv", ...
                    @sixgr.protocol.ProtocolVectorValidator.pdcpReordering; ...
                "sdap_header", "protocol_sdap_header_vectors.csv", ...
                    @sixgr.protocol.ProtocolVectorValidator.sdapHeader; ...
                "sdap_mapping", "protocol_sdap_mapping_vectors.csv", ...
                    @sixgr.protocol.ProtocolVectorValidator.sdapMapping; ...
                "rrc_semantics", "protocol_rrc_message_vectors.csv", ...
                    @sixgr.protocol.ProtocolVectorValidator.rrcSemantics; ...
                "rrc_uper", "protocol_rrc_release18_uper_vectors.csv", ...
                    @sixgr.protocol.ProtocolVectorValidator.rrcUPER; ...
                "bearer_config", "protocol_radio_bearer_vectors.csv", ...
                    @sixgr.protocol.ProtocolVectorValidator.bearerConfig; ...
                "handover", "protocol_handover_state_vectors.csv", ...
                    @sixgr.protocol.ProtocolVectorValidator.stateTable; ...
                "traffic", "protocol_traffic_arrival_vectors.csv", ...
                    @sixgr.protocol.ProtocolVectorValidator.traffic; ...
                "lineage", "protocol_lineage_vectors.csv", ...
                    @sixgr.protocol.ProtocolVectorValidator.lineage};
            n = size(families, 1);
            details = table('Size',[n 9], ...
                'VariableTypes',repmat({'string'},1,9), ...
                'VariableNames',{'VectorFamily','FileName','OracleClass', ...
                'OracleImplementation','OracleVersion','OracleArtifactSHA256', ...
                'Cases','MismatchCount','MaxAbsoluteError'});
            totalCases = 0;
            totalMismatch = 0;
            for index = 1:n
                fileName = string(families{index,2});
                path = fullfile(vectorRoot, fileName);
                rows = sixgr.protocol.ProtocolVectorValidator.read(path);
                [mismatch, maxError] = families{index,3}(rows, vectorRoot);
                cases = height(rows);
                totalCases = totalCases + cases;
                totalMismatch = totalMismatch + mismatch;
                oracleClass = "independent_frozen_vector";
                if string(families{index,1}) == "rrc_semantics"
                    oracleClass = "independent_enablement_guard";
                end
                details(index,:) = {string(families{index,1}), fileName, ...
                    oracleClass, "external_protocol_pack", ...
                    "manifest_v1", sixgr.protocol.ProtocolHash.file(path), ...
                    string(cases), string(mismatch), string(maxError)};
            end
            result = struct("Passed", totalMismatch == 0, ...
                "Cases", totalCases, "MismatchCount", totalMismatch, ...
                "Details", details);
        end
    end

    methods (Static, Access = private)
        function [mismatch, maxError] = rlcUM(rows, ~)
            mismatch = 0;
            for index = 1:height(rows)
                valid = sixgr.protocol.ProtocolVectorValidator.truth( ...
                    rows.ExpectedValid(index));
                try
                    bytes = sixgr.l2.rlc18.RLCHeaderCodec.encodeUM( ...
                        str2double(rows.SNBits(index)), ...
                        str2double(rows.SI(index)), ...
                        sixgr.protocol.ProtocolVectorValidator.number( ...
                        rows.SN(index)), ...
                        sixgr.protocol.ProtocolVectorValidator.number( ...
                        rows.SO(index)));
                    actualValid = true;
                    actualHex = sixgr.l2.rlc18.RLCHeaderCodec.hex(bytes);
                catch
                    actualValid = false;
                    actualHex = "";
                end
                mismatch = mismatch + double(actualValid ~= valid || ...
                    (valid && actualHex ~= upper(rows.HeaderHex(index))));
            end
            maxError = mismatch > 0;
        end

        function [mismatch, maxError] = rlcAM(rows, ~)
            mismatch = 0;
            for index = 1:height(rows)
                valid = sixgr.protocol.ProtocolVectorValidator.truth( ...
                    rows.ExpectedValid(index));
                try
                    bytes = sixgr.l2.rlc18.RLCHeaderCodec.encodeAM( ...
                        str2double(rows.SNBits(index)), ...
                        str2double(rows.D_C(index)), ...
                        str2double(rows.Poll(index)), ...
                        str2double(rows.SI(index)), ...
                        sixgr.protocol.ProtocolVectorValidator.number( ...
                        rows.SN(index)), ...
                        sixgr.protocol.ProtocolVectorValidator.number( ...
                        rows.SO(index)));
                    actualValid = true;
                    actualHex = sixgr.l2.rlc18.RLCHeaderCodec.hex(bytes);
                catch
                    actualValid = false;
                    actualHex = "";
                end
                mismatch = mismatch + double(actualValid ~= valid || ...
                    (valid && actualHex ~= upper(rows.HeaderHex(index))));
            end
            maxError = mismatch > 0;
        end

        function [mismatch, maxError] = rlcStatus(rows, ~)
            mismatch = 0;
            maxError = 0;
            for index = 1:height(rows)
                result = sixgr.l2.rlc18.RLCStatusCodec.encode( ...
                    str2double(rows.SNBits(index)), ...
                    str2double(rows.ACK_SN(index)), ...
                    str2double(rows.NACKCount(index)), ...
                    sixgr.protocol.ProtocolVectorValidator.truth( ...
                    rows.SegmentNACK(index)), ...
                    sixgr.protocol.ProtocolVectorValidator.truth( ...
                    rows.NACKRange(index)));
                delta = max(abs([result.BitCount - ...
                    str2double(rows.ExpectedBits(index)), ...
                    result.ByteCount - str2double(rows.ExpectedBytes(index))]));
                maxError = max(maxError, delta);
                mismatch = mismatch + double(delta ~= 0);
            end
        end

        function [mismatch, maxError] = rlcState(rows, ~)
            validPairs = ["IDLE|TX_POLL|POLL_WAIT"; ...
                "POLL_WAIT|STATUS_ACK|IDLE"; ...
                "POLL_WAIT|t_PollRetransmit_EXPIRE|RETX_PENDING"; ...
                "RX_STABLE|GAP_DETECTED|REASSEMBLY_WAIT"; ...
                "REASSEMBLY_WAIT|GAP_FILLED|RX_STABLE"; ...
                "REASSEMBLY_WAIT|t_Reassembly_EXPIRE|STATUS_PENDING"; ...
                "STATUS_PENDING|STATUS_SENT|STATUS_PROHIBITED"; ...
                "STATUS_PROHIBITED|t_StatusProhibit_EXPIRE|RX_STABLE"; ...
                "ACTIVE|RRC_REESTABLISH|RESETTING"; ...
                "RESETTING|RESET_COMPLETE|ACTIVE"];
            actual = ismember(rows.FromState + "|" + rows.Event + "|" + ...
                rows.ToState, validPairs);
            expected = sixgr.protocol.ProtocolVectorValidator.truth( ...
                rows.ExpectedValid);
            mismatch = sum(actual ~= expected);
            maxError = mismatch > 0;
        end

        function [mismatch, maxError] = pdcpHeader(rows, ~)
            mismatch = 0;
            for index = 1:height(rows)
                valid = sixgr.protocol.ProtocolVectorValidator.truth( ...
                    rows.ExpectedValid(index));
                try
                    bytes = sixgr.l2.pdcp18.PDCPHeaderCodec.encode( ...
                        rows.BearerType(index), ...
                        str2double(rows.SNBits(index)), ...
                        str2double(rows.SN(index)));
                    actualValid = true;
                    actualHex = sixgr.l2.pdcp18.PDCPHeaderCodec.hex(bytes);
                catch
                    actualValid = false;
                    actualHex = "";
                end
                mismatch = mismatch + double(actualValid ~= valid || ...
                    (valid && actualHex ~= upper(rows.HeaderHex(index))));
            end
            maxError = mismatch > 0;
        end

        function [mismatch, maxError] = pdcpCount(rows, ~)
            mismatch = 0;
            maxError = 0;
            for index = 1:height(rows)
                state = sixgr.l2.pdcp18.PDCPCountState( ...
                    str2double(rows.SNBits(index)), ...
                    str2double(rows.HFN(index)), str2double(rows.SN(index)));
                delta = abs(double(state.current()) - ...
                    str2double(rows.COUNT(index)));
                expectedNext = sixgr.protocol.ProtocolVectorValidator.truth( ...
                    rows.ExpectedNextValid(index));
                try
                    state.advance();
                    actualNext = true;
                    delta = max(delta, max(abs([double(state.SN) - ...
                        str2double(rows.NextSN(index)), double(state.HFN) - ...
                        str2double(rows.NextHFN(index))])));
                catch exception
                    actualNext = false;
                    if exception.identifier ~= "sixgr:pdcp:CountExhausted"
                        delta = Inf;
                    end
                end
                mismatch = mismatch + double(actualNext ~= expectedNext || delta ~= 0);
                maxError = max(maxError, delta);
            end
        end

        function [mismatch, maxError] = pdcpSecurity(rows, ~)
            mismatch = 0;
            for index = 1:height(rows)
                key = sixgr.protocol.ProtocolVectorValidator.fromHex( ...
                    rows.KeyHex(index));
                message = sixgr.protocol.ProtocolVectorValidator.fromHex( ...
                    rows.MessageHex(index));
                if rows.Algorithm(index) == "128-NEA2"
                    output = sixgr.l2.pdcp18.PDCPSecurity128.nea2( ...
                        key, str2double(rows.COUNT(index)), ...
                        str2double(rows.Bearer(index)), ...
                        str2double(rows.Direction(index)), message, ...
                        str2double(rows.BitLength(index)));
                    actual = sixgr.l2.pdcp18.PDCPSecurity128.hex(output);
                    expected = upper(rows.ExpectedHex(index));
                else
                    output = sixgr.l2.pdcp18.PDCPSecurity128.nia2( ...
                        key, str2double(rows.COUNT(index)), ...
                        str2double(rows.Bearer(index)), ...
                        str2double(rows.Direction(index)), message, ...
                        str2double(rows.BitLength(index)));
                    actual = sixgr.l2.pdcp18.PDCPSecurity128.hex(output);
                    expected = upper(rows.ExpectedMACIHex(index));
                end
                mismatch = mismatch + double(actual ~= expected);
            end
            maxError = mismatch > 0;
        end

        function [mismatch, maxError] = pdcpReordering(rows, ~)
            mismatch = 0;
            for index = 1:height(rows)
                arrivals = sixgr.protocol.ProtocolVectorValidator.sequence( ...
                    rows.ArrivalSNs(index));
                state = sixgr.l2.pdcp18.PDCPReorderingState( ...
                    str2double(rows.SNBits(index)), arrivals(1));
                for sn = arrivals
                    state.receive(sn);
                end
                actualDelivered = join(string(state.Delivered), "|");
                actualBuffered = join(string(state.Buffered), "|");
                if ismissing(actualDelivered), actualDelivered = ""; end
                if ismissing(actualBuffered), actualBuffered = ""; end
                mismatch = mismatch + double( ...
                    actualDelivered ~= rows.DeliveredSNs(index) || ...
                    actualBuffered ~= rows.BufferedSNs(index) || ...
                    state.DuplicateCount ~= ...
                    str2double(rows.DuplicateCount(index)) || ...
                    state.RX_DELIV ~= str2double(rows.RX_DELIV(index)));
            end
            maxError = mismatch > 0;
        end

        function [mismatch, maxError] = sdapHeader(rows, ~)
            mismatch = 0;
            for index = 1:height(rows)
                valid = sixgr.protocol.ProtocolVectorValidator.truth( ...
                    rows.ExpectedValid(index));
                try
                    byte = sixgr.l2.sdap18.SDAPHeaderCodec.encode( ...
                        rows.Direction(index), rows.PDUType(index), ...
                        str2double(rows.QFI(index)), ...
                        sixgr.protocol.ProtocolVectorValidator.number( ...
                        rows.RDI(index)), ...
                        sixgr.protocol.ProtocolVectorValidator.number( ...
                        rows.RQI(index)));
                    actualValid = true;
                    actualHex = sixgr.l2.sdap18.SDAPHeaderCodec.hex(byte);
                catch
                    actualValid = false;
                    actualHex = "";
                end
                mismatch = mismatch + double(actualValid ~= valid || ...
                    (valid && actualHex ~= upper(rows.HeaderHex(index))));
            end
            maxError = mismatch > 0;
        end

        function [mismatch, maxError] = sdapMapping(rows, ~)
            mismatch = 0;
            for index = 1:height(rows)
                expectedValid = sixgr.protocol.ProtocolVectorValidator.truth( ...
                    rows.ExpectedValid(index));
                defaultDRB = sixgr.protocol.ProtocolVectorValidator.number( ...
                    rows.DefaultDRBID(index));
                configured = sixgr.protocol.ProtocolVectorValidator.number( ...
                    rows.ConfiguredDRBID(index));
                try
                    state = sixgr.l2.sdap18.SDAPMappingState( ...
                        str2double(rows.PduSessionID(index)), defaultDRB);
                    if ~isempty(configured)
                        state.configure(str2double(rows.QFI(index)), ...
                            configured, 1);
                    end
                    actual = state.resolve(str2double(rows.QFI(index)));
                    actualValid = true;
                catch
                    actual = [];
                    actualValid = false;
                end
                expected = sixgr.protocol.ProtocolVectorValidator.number( ...
                    rows.ExpectedDRBID(index));
                mismatch = mismatch + double(actualValid ~= expectedValid || ...
                    (expectedValid && actual ~= expected));
            end
            maxError = mismatch > 0;
        end

        function [mismatch, maxError] = rrcSemantics(rows, ~)
            positive = sixgr.protocol.ProtocolVectorValidator.truth( ...
                rows.ExpectedValid);
            guarded = ismember(upper(rows.FrozenUPERVectorState(positive)), ...
                ["REQUIRED_BEFORE_ENABLE","FROZEN_UPER"]);
            negative = ~positive;
            negativeMarked = upper(rows.FrozenUPERVectorState(negative)) == ...
                "NEGATIVE";
            mismatch = sum(~guarded) + sum(~negativeMarked);
            maxError = mismatch > 0;
        end

        function [mismatch, maxError] = rrcUPER(rows, ~)
            mismatch = 0;
            for index = 1:height(rows)
                expected = upper(rows.UPERHex(index));
                transactionID = str2double(rows.TransactionID(index));
                try
                    encoded = ...
                        sixgr.l3.rrc18.asn1.RRCBoundedUPERCodec.encode( ...
                        rows.MessageType(index), transactionID);
                    actual = upper(string(reshape( ...
                        dec2hex(encoded,2).',1,[])));
                    decoded = ...
                        sixgr.l3.rrc18.asn1.RRCBoundedUPERCodec.decode( ...
                        encoded, rows.Channel(index));
                    valid = decoded.MessageType == rows.MessageType(index) && ...
                        decoded.TransactionID == transactionID;
                catch
                    actual = "";
                    valid = false;
                end
                mismatch = mismatch + double(~valid || actual ~= expected);
            end
            maxError = mismatch > 0;
        end

        function [mismatch, maxError] = bearerConfig(rows, ~)
            mismatch = 0;
            for index = 1:height(rows)
                config = table2struct(rows(index,:));
                config.RLCSNBits = str2double(string(config.RLCSNBits));
                config.PDCPSNBits = str2double(string(config.PDCPSNBits));
                config.SDAPEnabled = ...
                    sixgr.protocol.ProtocolVectorValidator.truth( ...
                    config.SDAPEnabled);
                expected = sixgr.protocol.ProtocolVectorValidator.truth( ...
                    rows.ExpectedValid(index));
                try
                    sixgr.l3.rrc18.RadioBearerTransaction.validate(config);
                    actual = true;
                catch
                    actual = false;
                end
                mismatch = mismatch + double(actual ~= expected);
            end
            maxError = mismatch > 0;
        end

        function [mismatch, maxError] = stateTable(rows, ~)
            key = rows.RLCMode + "|" + rows.FromState + "|" + rows.Event;
            positive = sixgr.protocol.ProtocolVectorValidator.truth( ...
                rows.ExpectedValid);
            expectedValid = strlength(rows.ToState) > 0;
            mismatch = sum(positive ~= expectedValid) + ...
                sum(arrayfun(@(x) sum(key == key(x) & positive) > 1, ...
                (1:height(rows)).'));
            maxError = mismatch > 0;
        end

        function [mismatch, maxError] = traffic(rows, ~)
            deterministic = sixgr.protocol.ProtocolVectorValidator.truth( ...
                rows.ExpectedDeterministic);
            valid = strlength(rows.PacketID) > 0 & ...
                strlength(rows.NamedStream) > 0 & ...
                str2double(rows.PacketBytes) > 0 & ...
                isfinite(str2double(rows.ArrivalTime_ms));
            uniquePackets = numel(unique(rows.PacketID)) == height(rows);
            mismatch = sum(valid ~= deterministic) + double(~uniquePackets);
            maxError = mismatch > 0;
        end

        function [mismatch, maxError] = lineage(rows, ~)
            expected = sixgr.protocol.ProtocolVectorValidator.truth( ...
                rows.ExpectedOwned);
            owned = strlength(rows.PacketID) > 0 & ...
                strlength(rows.SDAPSDUID) > 0 & ...
                strlength(rows.RLCSDUID) > 0 & ...
                strlength(rows.MACSDUID) > 0 & ...
                strlength(rows.TBID) > 0 & ...
                str2double(rows.SegmentOffset) + ...
                str2double(rows.SegmentBytes) <= ...
                str2double(rows.PacketBytes);
            mismatch = sum(owned ~= expected) + ...
                double(numel(unique(rows.LineageID)) ~= height(rows));
            maxError = mismatch > 0;
        end

        function rows = read(path)
            if ~isfile(path)
                error("sixgr:protocol:UnsupportedCapability", ...
                    "Independent protocol vector is missing: %s.", path);
            end
            options = detectImportOptions(path, "Delimiter", ",", ...
                "VariableNamingRule", "preserve");
            options = setvartype(options, options.VariableNames, "string");
            rows = readtable(path, options);
            for index = 1:width(rows)
                rows.(index) = fillmissing(rows.(index), "constant", "");
            end
        end

        function value = truth(input)
            value = ismember(lower(strtrim(string(input))), ...
                ["1","true","yes","pass"]);
        end

        function value = number(input)
            input = string(input);
            if ismissing(input) || strlength(strtrim(input)) == 0
                value = [];
            else
                value = str2double(input);
            end
        end

        function bytes = fromHex(text)
            text = char(string(text));
            if isempty(text)
                bytes = uint8([]);
            else
                bytes = uint8(sscanf(text, "%2x").');
            end
        end

        function values = sequence(text)
            text = string(text);
            if strlength(text) == 0
                values = [];
            else
                values = str2double(split(text, "|")).';
            end
        end
    end
end
