function mode = fixedSNRPowerReferenceMode(cfg)
%FIXEDSNRPOWERREFERENCEMODE Resolve and guard waveform sample-unit authority.
mode = lower(strtrim(string(sixgr.util.structGet(cfg, ...
    "integration.power_reference_mode", "normalized_unit_es"))));
allowed = ["normalized_unit_es", "absolute_calibrated_sqrt_mw"];
if ~(isscalar(mode) && any(mode == allowed))
    error("sixgr:rf:InvalidFixedSNRPowerReferenceMode", ...
        "integration.power_reference_mode must be one of: %s.", ...
        strjoin(allowed, ", "));
end
if sixgr.rf.isFixedSNRLinkAuthority(cfg) && mode ~= "normalized_unit_es"
    error("sixgr:rf:MixedFixedSNRAndAbsolutePower", ...
        ["A configured fixed-SNR campaign must use normalized_unit_es. " + ...
         "absolute_calibrated_sqrt_mw belongs to a receiver-thermal-noise " + ...
         "link-budget run where configured SNR is not link authority."]);
end
end
