function cfg = withCanonicalSchedulerTiming(cfg)
%WITHCANONICALSCHEDULERTIMING Explicit FDD timing fixture for scheduler tests.
%
% This is test configuration, not a production fallback.  It gives focused
% scheduler tests an explicit control/data/feedback allocation, configured
% K rows, timing advance, and pinned Release-18 capability profile.

cfg = sixgr.util.structSet(cfg, "phy.duplex.mode", "FDD");
cfg = sixgr.util.structSet(cfg, ...
    "phy.duplex.fdd.dlCenterFrequencyHz", 4.0e9);
cfg = sixgr.util.structSet(cfg, ...
    "phy.duplex.fdd.ulCenterFrequencyHz", 3.9e9);
cfg = sixgr.util.structSet(cfg, ...
    "phy.tddTiming.allowedK0", 1);
cfg = sixgr.util.structSet(cfg, ...
    "phy.tddTiming.pdcchToPDSCHK0", 1);
cfg = sixgr.util.structSet(cfg, ...
    "phy.tddTiming.dlHARQFeedbackK1Candidates", 2);
cfg = sixgr.util.structSet(cfg, ...
    "phy.tddTiming.pdcchToPUSCHK2", 1);
cfg = sixgr.util.structSet(cfg, ...
    "phy.tddTiming.ulGrantK2", 1);
cfg = sixgr.util.structSet(cfg, ...
    "phy.tddTiming.capabilityProfileID", ...
    "38.214-v18.8.0-cap1-dmrs-pos0-mu1");
cfg = sixgr.util.structSet(cfg, ...
    "phy.tddTiming.n1PDSCHProcessingTimeSymbols", 10);
cfg = sixgr.util.structSet(cfg, ...
    "phy.tddTiming.n2PUSCHPreparationTimeSymbols", 12);
cfg = sixgr.util.structSet(cfg, ...
    "phy.tddTiming.timingAdvanceTicks", 0);

if isempty(sixgr.util.structGet(cfg, ...
        "phy.pdcch.symbolAllocation", []))
    cfg = sixgr.util.structSet(cfg, ...
        "phy.pdcch.symbolAllocation", [0, 2]);
end
if isempty(sixgr.util.structGet(cfg, ...
        "phy.pdsch.symbolAllocation", []))
    cfg = sixgr.util.structSet(cfg, ...
        "phy.pdsch.symbolAllocation", [0, 14]);
end
if isempty(sixgr.util.structGet(cfg, "phy.pdsch.prbSet", []))
    cfg = sixgr.util.structSet(cfg, ...
        "phy.pdsch.prbSet", 0:23);
end
if isempty(sixgr.util.structGet(cfg, ...
        "phy.pusch.symbolAllocation", []))
    cfg = sixgr.util.structSet(cfg, ...
        "phy.pusch.symbolAllocation", [0, 14]);
end
if isempty(sixgr.util.structGet(cfg, "phy.pusch.prbSet", []))
    cfg = sixgr.util.structSet(cfg, ...
        "phy.pusch.prbSet", 0:23);
end
if isempty(sixgr.util.structGet(cfg, ...
        "phy.pucch.symbolAllocation", []))
    cfg = sixgr.util.structSet(cfg, ...
        "phy.pucch.symbolAllocation", [0, 2]);
end

if isfield(cfg, "phy") && isfield(cfg.phy, "frameStructure")
    cfg.phy = rmfield(cfg.phy, "frameStructure");
end
if isfield(cfg, "resolved_runtime_view") && ...
        isfield(cfg.resolved_runtime_view, "frame_structure")
    cfg.resolved_runtime_view = rmfield( ...
        cfg.resolved_runtime_view, "frame_structure");
end
if isfield(cfg.phy, "frame")
    cfg.phy = rmfield(cfg.phy, "frame");
end
cfg = sixgr.phy.frame.FrameRuntimeStateBuilder.attachTimingContext(cfg);
end
