function audit = auditResourceMap(ssbGrid,cfg)
%AUDITRESOURCEMAP Independently validate production C0 RE ownership.
nCellID = double(cfg.waveform.n_cell_id);
pssIndices = nrPSSIndices();
sssIndices = nrSSSIndices();
sets = struct( ...
    "PSS",double(pssIndices(:)), ...
    "SSS",double(sssIndices(:)), ...
    "PBCH",double(nrPBCHIndices(nCellID)), ...
    "DMRS",double(nrPBCHDMRSIndices(nCellID)));
names = string(fieldnames(sets));
allIndices = zeros(0,1);
for k = 1:numel(names)
    idx = sets.(names(k));
    if numel(unique(idx)) ~= numel(idx) || any(idx < 1 | idx > numel(ssbGrid))
        error("sixgr:phy:ia:c0:waveform:InvalidResourceMap", ...
            "%s indices are duplicated or outside the 240x4 SSB grid.",names(k));
    end
    if any(ismember(idx,allIndices))
        error("sixgr:phy:ia:c0:waveform:ResourceCollision", ...
            "%s collides with an earlier C0 resource owner.",names(k));
    end
    allIndices = [allIndices;idx]; %#ok<AGROW>
end
if any(ssbGrid(allIndices)==0) || nnz(ssbGrid) ~= numel(allIndices)
    error("sixgr:phy:ia:c0:waveform:ResourceOwnershipMismatch", ...
        "Nonzero C0 grid RE do not exactly match the PSS/SSS/PBCH/DMRS ownership map.");
end
energy = sum(abs(ssbGrid(:)).^2);
audit = struct( ...
    "Candidate","A20RB4", ...
    "PSSRE",numel(sets.PSS), ...
    "SSSRE",numel(sets.SSS), ...
    "PBCHRE",numel(sets.PBCH), ...
    "DMRSRE",numel(sets.DMRS), ...
    "ActiveRE",numel(allIndices), ...
    "ReservedUnusedRE",numel(ssbGrid)-numel(allIndices), ...
    "TotalEnergy",double(energy), ...
    "MeanActiveREEPRE",double(energy/numel(allIndices)), ...
    "ResourceMapSHA256",string(sixgr.util.sha256Hex(uint8(ismember((1:numel(ssbGrid))',allIndices)))));
end
