function bundle = buildNRAnchorA(cfg,varargin)
%BUILDNRANCHORA Build production NR-like 20-RB by four-symbol C0 anchor.
p = inputParser;
p.addParameter("PayloadSeed",double(cfg.run.seed_set_main),@(x)isnumeric(x)&&isscalar(x));
p.parse(varargin{:});

if string(cfg.waveform.candidate) ~= "A20RB4"
    error("sixgr:phy:ia:c0:waveform:UnsupportedCandidate", ...
        "Phase-1 waveform builder supports only A20RB4.");
end
nCellID = double(cfg.waveform.n_cell_id);
nid2 = mod(nCellID,3);
ssbIndex = double(cfg.waveform.ssb_index);
lmax = double(cfg.waveform.lmax);
hrf = double(cfg.waveform.half_frame_bit);
kSSB = double(cfg.waveform.k_ssb);
sfn = double(cfg.waveform.system_frame_number);

% Resolve C0 through the existing production initial-access contracts.
% The C0 grid remains an explicit 240-by-4 anchor, while timing, bitmap,
% grid placement, and RE ownership have one shared authority with SSB_Tx.
phyCfg = sixgr.phy.ia.c0.config.toPHYConfig(cfg);
timing = sixgr.phy.frame.SSBTimingResolver.resolveFromConfig(phyCfg, ...
    "SSBIndex",ssbIndex);
burstPlan = sixgr.phy.ia.SSBBurstPlan.fromConfig( ...
    phyCfg,timing,"SelectedSSBIndex",ssbIndex);
gridValidation = sixgr.phy.ia.SSBGridValidator.validate( ...
    "CarrierSubcarrierSpacingKHz",double(cfg.carrier.scs_khz), ...
    "SSBSubcarrierSpacingKHz",double(timing.SSBSubcarrierSpacingKHz), ...
    "NStartGrid",0,"NSizeGrid",double(cfg.carrier.n_size_grid), ...
    "NStartBWP",0,"NSizeBWP",double(cfg.carrier.n_size_grid), ...
    "NCRBSSB",double(timing.GridRelationship.NCRBSSB), ...
    "KSSB",double(timing.GridRelationship.KSSB));
resourceOwnership = sixgr.phy.ia.SSBResourceOwnershipMap.resolve(nCellID);

mib = sixgr.phy.ia.MIBSemanticValidator.resolve( ...
    "CaseID",string(cfg.meta.scenario_id), ...
    "SystemFrameNumberMSB6",double(cfg.waveform.mib.system_frame_number_msb6), ...
    "SubCarrierSpacingCommon",string(cfg.waveform.mib.subcarrier_spacing_common), ...
    "SSBSubcarrierOffset",double(cfg.waveform.mib.ssb_subcarrier_offset), ...
    "DMRSTypeAPosition",string(cfg.waveform.mib.dmrs_type_a_position), ...
    "PDCCHConfigSIB1",double(cfg.waveform.mib.pdcch_config_sib1), ...
    "CellBarred",string(cfg.waveform.mib.cell_barred), ...
    "IntraFreqReselection",string(cfg.waveform.mib.intra_freq_reselection), ...
    "Spare",double(cfg.waveform.mib.spare));
transportBlock = int8([double(cfg.waveform.mib.bcch_bch_choice_bit); ...
    double(mib.InformationBits(:))]);
if numel(transportBlock) ~= double(cfg.waveform.pbch_payload_bits)
    error("sixgr:phy:ia:c0:waveform:MIBTransportBlockLength", ...
        "Configured MIB fields must produce exactly 24 BCH transport bits.");
end
indexOffset = kSSB;
if lmax == 64
    indexOffset = ssbIndex;
end
bchCodeword = nrBCH(transportBlock,sfn,hrf,lmax,indexOffset,nCellID);
scramblingPhase = mod(ssbIndex,8);
ibarSSB = ssbIndex;
if lmax == 4
    ibarSSB = ssbIndex + 4*hrf;
end

ssbGrid = complex(zeros(240,4));
pssInd = nrPSSIndices;
sssInd = nrSSSIndices;
pbchInd = nrPBCHIndices(nCellID);
dmrsInd = nrPBCHDMRSIndices(nCellID);
ssbGrid(pssInd) = nrPSS(nid2);
ssbGrid(sssInd) = nrSSS(nCellID);
ssbGrid(pbchInd) = nrPBCH(bchCodeword,nCellID,scramblingPhase);
ssbGrid(dmrsInd) = nrPBCHDMRS(nCellID,ibarSSB);
[ssbGrid,normalizationAudit] = sixgr.phy.ia.c0.waveform.normalizeEnergy( ...
    ssbGrid,nnz(ssbGrid),cfg.waveform.normalization);

carrier = nrCarrierConfig;
carrier.NCellID = nCellID;
carrier.SubcarrierSpacing = double(cfg.carrier.scs_khz);
carrier.CyclicPrefix = char(string(cfg.carrier.cyclic_prefix));
carrier.NSizeGrid = double(cfg.carrier.n_size_grid);
carrier.NStartGrid = 0;
carrier.NSlot = 0;
carrier.NFrame = 0;
if carrier.NSizeGrid ~= 20
    error("sixgr:phy:ia:c0:waveform:C0GridSize", ...
        "C0 A20RB4 requires carrier.n_size_grid=20.");
end
startSymbol = double(cfg.waveform.candidate_start_symbol);
slotGrid = complex(zeros(240,14));
slotGrid(:,startSymbol+(1:4)) = ssbGrid;
[waveform,ofdmInfo] = nrOFDMModulate(carrier,slotGrid,"Windowing",0);

audit = sixgr.phy.ia.c0.waveform.auditResourceMap(ssbGrid,cfg);
audit.Normalization = normalizationAudit;
bundle = struct( ...
    "Carrier",carrier, ...
    "SSBGrid",ssbGrid, ...
    "SlotGrid",slotGrid, ...
    "Waveform",waveform, ...
    "OFDMInfo",ofdmInfo, ...
    "SampleRateHz",double(ofdmInfo.SampleRate), ...
    "TransportBlock",transportBlock, ...
    "MIB",mib, ...
    "PayloadSeed",double(p.Results.PayloadSeed), ...
    "PayloadSource","yaml_mib_semantics", ...
    "BCHCodeword",bchCodeword, ...
    "NCellID",nCellID, ...
    "NID2",nid2, ...
    "SSBIndex",ssbIndex, ...
    "IBarSSB",ibarSSB, ...
    "ScramblingPhase",scramblingPhase, ...
    "CandidateStartSymbol",startSymbol, ...
    "SSBTiming",timing, ...
    "SSBBurstPlan",burstPlan, ...
    "SSBGridValidation",gridValidation, ...
    "SSBResourceOwnership",resourceOwnership, ...
    "ActiveIndices",find(slotGrid~=0), ...
    "SSBActiveIndices",find(ssbGrid~=0), ...
    "ResourceAudit",audit, ...
    "WaveformSHA256",string(sixgr.util.sha256Hex(typecast( ...
        [real(waveform(:));imag(waveform(:))],'uint8'))), ...
    "TransportBlockSHA256",string(sixgr.util.sha256Hex(uint8(transportBlock))));
end
