classdef BWPConfig
    %BWPCONFIG Immutable validated bandwidth-part frame/grid configuration.
    %
    % NStartBWP and NSizeBWP are expressed in the configured carrier-grid
    % Point-A reference domain. Runtime activation is owned by
    % BWPStateMachine; this value object is never mutated by a switch.

    properties (SetAccess = private)
        BWPID (1,1) string
        Direction (1,1) string
        CCID (1,1) string
        ServingCellID (1,1) string
        FrequencyRange (1,1) string
        SCSKHz (1,1) double
        Mu (1,1) double
        CyclicPrefix (1,1) string
        NStartBWP (1,1) double
        NSizeBWP (1,1) double
        CarrierNStartGrid (1,1) double
        CarrierNSizeGrid (1,1) double
        CarrierSCSKHz (1,1) double
        CarrierLowerEdgeOffsetHz (1,1) double
        CarrierUpperEdgeOffsetHz (1,1) double
        BWPLowerEdgeOffsetHz (1,1) double
        BWPUpperEdgeOffsetHz (1,1) double
        PointAAlignmentQuantumHz (1,1) double
        SymbolsPerSlot (1,1) double
        SlotsPerFrame (1,1) double
        TicksPerSlot (1,1) int64
        TicksPerSymbol (1,1) int64
        ControlConfigRef (1,1) string
        DataConfigRef (1,1) string
        ControlBWPID (1,1) string
        DataBWPID (1,1) string
        ActiveInitial (1,1) logical
        ConfiguredActivationTime (1,1) sixgr.phy.frame.AbsoluteTime
        StateVersion (1,1) uint64
        CommonTDDReferenceSCSKHz (1,1) double
        IndexConvention (1,1) string = "zero_based"
    end

    methods
        function obj = BWPConfig(config, carrier)
            if nargin == 0
                return;
            end
            if ~isstruct(config) || ~isscalar(config)
                error("sixgr:phy:frame:InvalidBWPConfig", ...
                    "BWP configuration must be a scalar struct.");
            end
            if nargin < 2 || isempty(carrier)
                carrier = config;
            end
            if ~isstruct(carrier) || ~isscalar(carrier)
                error("sixgr:phy:frame:InvalidCarrierGrid", ...
                    "Carrier grid input for a BWP must be a scalar struct.");
            end

            obj.BWPID = localIdentifier(localRequired(config, ...
                ["BWPID", "bwp_id"], "BWPID"), "BWPID");
            obj.Direction = localDirection(localRequired(config, ...
                ["Direction", "direction"], "Direction"));
            obj.CCID = localIdentifier(localRequired(config, ...
                ["CCID", "cc_id"], "CCID"), "CCID");
            obj.ServingCellID = localIdentifier(localRequired(config, ...
                ["ServingCellID", "serving_cell_id"], "ServingCellID"), ...
                "ServingCellID");
            obj.FrequencyRange = upper(localText(localFirst(config, ...
                ["FrequencyRange", "frequency_range"], ...
                localFirst(carrier, ["FrequencyRange", "frequency_range"], "")), ...
                "FrequencyRange"));
            if ~any(obj.FrequencyRange == ["FR1", "FR2-1", "FR2-2"])
                error("sixgr:phy:frame:InvalidFrequencyRange", ...
                    "BWP FrequencyRange must be FR1, FR2-1, or FR2-2.");
            end

            scs = localRequired(config, ...
                ["SCSKHz", "SubcarrierSpacingKHz", "scs_khz"], "SCSKHz");
            cp = localRequired(config, ...
                ["CyclicPrefix", "cyclic_prefix", "cp_type"], "CyclicPrefix");
            role = lower(obj.Direction) + "_bwp";
            num = sixgr.phy.frame.NumerologyCatalog.resolve( ...
                scs, cp, role, obj.FrequencyRange);
            obj.SCSKHz = double(num.SubcarrierSpacingKHz);
            obj.Mu = double(num.Mu);
            obj.CyclicPrefix = string(num.CyclicPrefix);
            obj.SymbolsPerSlot = double(num.SymbolsPerSlot);
            obj.SlotsPerFrame = double(num.SlotsPerFrame);
            exactNum = sixgr.phy.frame.AbsoluteTime.resolveNumerology(num);
            obj.TicksPerSlot = exactNum.TicksPerSlot;
            obj.TicksPerSymbol = exactNum.TicksPerSymbol;

            obj.CarrierNStartGrid = localNonnegativeInteger(localRequired( ...
                carrier, ["NStartGrid", "n_start_grid", ...
                "CarrierNStartGrid"], "carrier.NStartGrid"), ...
                "carrier.NStartGrid");
            obj.CarrierNSizeGrid = localPositiveInteger(localRequired( ...
                carrier, ["NSizeGrid", "n_size_grid", ...
                "CarrierNSizeGrid"], "carrier.NSizeGrid"), ...
                "carrier.NSizeGrid");
            obj.CarrierSCSKHz = localPositiveFinite(localRequired( ...
                carrier, ["SubcarrierSpacingKHz", "SCSKHz", ...
                "scs_khz", "CarrierSCSKHz"], ...
                "carrier.SubcarrierSpacingKHz"), ...
                "carrier.SubcarrierSpacingKHz");
            carrierNumerology = sixgr.phy.frame.NumerologyCatalog.resolve( ...
                obj.CarrierSCSKHz, obj.CyclicPrefix, ...
                "carrier_transmission_grid", obj.FrequencyRange);
            obj.CarrierSCSKHz = double( ...
                carrierNumerology.SubcarrierSpacingKHz);

            obj.NStartBWP = localNonnegativeInteger(localRequired(config, ...
                ["NStartBWP", "n_start_bwp"], "NStartBWP"), "NStartBWP");
            obj.NSizeBWP = localPositiveInteger(localRequired(config, ...
                ["NSizeBWP", "n_size_bwp"], "NSizeBWP"), "NSizeBWP");
            obj.PointAAlignmentQuantumHz = 12 * 1e3 * ...
                gcd(round(obj.CarrierSCSKHz), round(obj.SCSKHz));
            obj.CarrierLowerEdgeOffsetHz = 12 * 1e3 * ...
                obj.CarrierNStartGrid * obj.CarrierSCSKHz;
            obj.CarrierUpperEdgeOffsetHz = 12 * 1e3 * ...
                (obj.CarrierNStartGrid + obj.CarrierNSizeGrid) * ...
                obj.CarrierSCSKHz;
            obj.BWPLowerEdgeOffsetHz = 12 * 1e3 * ...
                obj.NStartBWP * obj.SCSKHz;
            obj.BWPUpperEdgeOffsetHz = 12 * 1e3 * ...
                (obj.NStartBWP + obj.NSizeBWP) * obj.SCSKHz;
            edgeTicks = [obj.CarrierLowerEdgeOffsetHz, ...
                obj.CarrierUpperEdgeOffsetHz, obj.BWPLowerEdgeOffsetHz, ...
                obj.BWPUpperEdgeOffsetHz] / obj.PointAAlignmentQuantumHz;
            if any(abs(edgeTicks - round(edgeTicks)) > 1e-9)
                error("sixgr:phy:frame:BWPPointAAlignmentMismatch", ...
                    "BWP '%s' and carrier '%s' edges do not align on their common Point-A frequency raster.", ...
                    obj.BWPID, obj.CCID);
            end
            if obj.BWPLowerEdgeOffsetHz < obj.CarrierLowerEdgeOffsetHz || ...
                    obj.BWPUpperEdgeOffsetHz > obj.CarrierUpperEdgeOffsetHz
                error("sixgr:phy:frame:BWPOutsideCarrierGrid", ...
                    "BWP '%s' occupies Point-A offsets [%.15g,%.15g) Hz " + ...
                    "at %.15g kHz SCS, outside carrier '%s' offsets " + ...
                    "[%.15g,%.15g) Hz at %.15g kHz SCS.", ...
                    obj.BWPID, obj.BWPLowerEdgeOffsetHz, ...
                    obj.BWPUpperEdgeOffsetHz, obj.SCSKHz, obj.CCID, ...
                    obj.CarrierLowerEdgeOffsetHz, ...
                    obj.CarrierUpperEdgeOffsetHz, obj.CarrierSCSKHz);
            end

            obj.ControlConfigRef = localNonemptyReference(config, ...
                ["ControlConfigRef", "control_config_ref"]);
            obj.DataConfigRef = localNonemptyReference(config, ...
                ["DataConfigRef", "data_config_ref"]);
            obj.ControlBWPID = localIdentifier(localRequired(config, ...
                ["ControlBWPID", "control_bwp_id"], "ControlBWPID"), ...
                "ControlBWPID");
            obj.DataBWPID = localIdentifier(localRequired(config, ...
                ["DataBWPID", "data_bwp_id"], "DataBWPID"), "DataBWPID");
            obj.ActiveInitial = localLogical(localRequired(config, ...
                ["ActiveInitial", "active_initial", "Active", "active"], ...
                "ActiveInitial"), "ActiveInitial");
            activation = localRequired(config, ...
                ["SwitchActivationTime", "switch_activation_time", ...
                "SwitchActivationTick", "switch_activation_tick"], ...
                "SwitchActivationTime");
            if isa(activation, "sixgr.phy.frame.AbsoluteTime")
                obj.ConfiguredActivationTime = activation;
            else
                obj.ConfiguredActivationTime = ...
                    sixgr.phy.frame.AbsoluteTime.fromTicks(activation);
            end
            obj.StateVersion = uint64(localNonnegativeInteger(localRequired( ...
                config, ["StateVersion", "state_version", "Epoch", "epoch"], ...
                "StateVersion"), "StateVersion"));
            referenceSCS = localFirst(config, ...
                ["CommonTDDReferenceSCSKHz", ...
                "common_tdd_reference_scs_khz"], NaN);
            if isempty(referenceSCS)
                referenceSCS = NaN;
            end
            if ~(isnumeric(referenceSCS) && isreal(referenceSCS) && ...
                    isscalar(referenceSCS) && ...
                    (isnan(double(referenceSCS)) || ...
                    (isfinite(double(referenceSCS)) && double(referenceSCS) > 0)))
                error("sixgr:phy:frame:InvalidTDDReferenceSCS", ...
                    "CommonTDDReferenceSCSKHz must be NaN or a positive finite scalar.");
            end
            obj.CommonTDDReferenceSCSKHz = double(referenceSCS);
            if obj.ActiveInitial
                obj.assertActivationCompatible();
            end
        end

        function assertActivationCompatible(obj)
            if isfinite(obj.CommonTDDReferenceSCSKHz) && ...
                    obj.CommonTDDReferenceSCSKHz > obj.SCSKHz
                error("sixgr:phy:frame:TDDReferenceSCSAboveActiveBWP", ...
                    "BWP '%s' cannot be active because common TDD reference " + ...
                    "SCS %.15g kHz exceeds BWP SCS %.15g kHz.", ...
                    obj.BWPID, obj.CommonTDDReferenceSCSKHz, obj.SCSKHz);
            end
        end

        function dimensions = resourceGridDimensions(obj, numPorts)
            if nargin < 2
                numPorts = 1;
            end
            numPorts = localPositiveInteger(numPorts, "numPorts");
            dimensions = [12 * obj.NSizeBWP, obj.SymbolsPerSlot, numPorts];
        end

        function key = resourceKey(obj, resourceType, resourceID)
            resourceType = upper(localText(resourceType, "resourceType"));
            resourceID = localIdentifier(resourceID, "resourceID");
            key = "CC=" + obj.CCID + "|BWP=" + obj.BWPID + ...
                "|DIR=" + obj.Direction + "|TYPE=" + resourceType + ...
                "|ID=" + resourceID;
        end

        function output = toStruct(obj)
            output = struct( ...
                "BWPID", obj.BWPID, ...
                "Direction", obj.Direction, ...
                "CCID", obj.CCID, ...
                "ServingCellID", obj.ServingCellID, ...
                "FrequencyRange", obj.FrequencyRange, ...
                "SCSKHz", obj.SCSKHz, ...
                "Mu", obj.Mu, ...
                "CyclicPrefix", obj.CyclicPrefix, ...
                "NStartBWP", obj.NStartBWP, ...
                "NSizeBWP", obj.NSizeBWP, ...
                "CarrierNStartGrid", obj.CarrierNStartGrid, ...
                "CarrierNSizeGrid", obj.CarrierNSizeGrid, ...
                "CarrierSCSKHz", obj.CarrierSCSKHz, ...
                "CarrierLowerEdgeOffsetHz", ...
                obj.CarrierLowerEdgeOffsetHz, ...
                "CarrierUpperEdgeOffsetHz", ...
                obj.CarrierUpperEdgeOffsetHz, ...
                "BWPLowerEdgeOffsetHz", obj.BWPLowerEdgeOffsetHz, ...
                "BWPUpperEdgeOffsetHz", obj.BWPUpperEdgeOffsetHz, ...
                "PointAAlignmentQuantumHz", ...
                obj.PointAAlignmentQuantumHz, ...
                "SymbolsPerSlot", obj.SymbolsPerSlot, ...
                "SlotsPerFrame", obj.SlotsPerFrame, ...
                "TicksPerSlot", obj.TicksPerSlot, ...
                "TicksPerSymbol", obj.TicksPerSymbol, ...
                "ControlConfigRef", obj.ControlConfigRef, ...
                "DataConfigRef", obj.DataConfigRef, ...
                "ControlBWPID", obj.ControlBWPID, ...
                "DataBWPID", obj.DataBWPID, ...
                "ActiveInitial", obj.ActiveInitial, ...
                "ConfiguredActivationTick", ...
                obj.ConfiguredActivationTime.tickValue(), ...
                "StateVersion", obj.StateVersion, ...
                "CommonTDDReferenceSCSKHz", ...
                obj.CommonTDDReferenceSCSKHz, ...
                "IndexConvention", obj.IndexConvention);
        end
    end
end

function value = localFirst(input, aliases, defaultValue)
value = defaultValue;
names = string(fieldnames(input));
for alias = string(aliases(:)).'
    index = find(strcmpi(names, alias), 1);
    if ~isempty(index)
        value = input.(char(names(index)));
        return;
    end
end
end

function value = localRequired(input, aliases, label)
names = string(fieldnames(input));
for alias = string(aliases(:)).'
    index = find(strcmpi(names, alias), 1);
    if ~isempty(index)
        value = input.(char(names(index)));
        return;
    end
end
error("sixgr:phy:frame:MissingBWPField", ...
    "BWP configuration field '%s' is required.", label);
end

function value = localText(input, label)
if ~(ischar(input) || (isstring(input) && isscalar(input)))
    error("sixgr:phy:frame:InvalidBWPField", ...
        "%s must be scalar text.", label);
end
value = strtrim(string(input));
if strlength(value) == 0
    error("sixgr:phy:frame:InvalidBWPField", ...
        "%s must not be empty.", label);
end
end

function value = localIdentifier(input, label)
if isnumeric(input) && isreal(input) && isscalar(input) && ...
        isfinite(double(input)) && double(input) >= 0 && ...
        double(input) == fix(double(input))
    value = string(double(input));
else
    value = localText(input, label);
end
if contains(value, "|")
    error("sixgr:phy:frame:InvalidResourceIdentifier", ...
        "%s must not contain the namespace delimiter '|'.", label);
end
end

function value = localDirection(input)
value = upper(localText(input, "Direction"));
if any(value == ["DOWNLINK", "D"])
    value = "DL";
elseif any(value == ["UPLINK", "U"])
    value = "UL";
end
if ~any(value == ["DL", "UL"])
    error("sixgr:phy:frame:InvalidBWPDirection", ...
        "BWP Direction must be DL or UL.");
end
end

function value = localNonnegativeInteger(input, label)
if ~(isnumeric(input) && isreal(input) && isscalar(input) && ...
        isfinite(double(input)) && double(input) >= 0 && ...
        double(input) == fix(double(input)))
    error("sixgr:phy:frame:InvalidBWPField", ...
        "%s must be a nonnegative integer scalar.", label);
end
value = double(input);
end

function value = localPositiveInteger(input, label)
value = localNonnegativeInteger(input, label);
if value < 1
    error("sixgr:phy:frame:InvalidBWPField", ...
        "%s must be a positive integer scalar.", label);
end
end

function value = localPositiveFinite(input, label)
if ~(isnumeric(input) && isreal(input) && isscalar(input) && ...
        isfinite(double(input)) && double(input) > 0)
    error("sixgr:phy:frame:InvalidBWPField", ...
        "%s must be a positive finite scalar.", label);
end
value = double(input);
end

function value = localLogical(input, label)
if ~((islogical(input) || isnumeric(input)) && isscalar(input) && ...
        isfinite(double(input)) && any(double(input) == [0, 1]))
    error("sixgr:phy:frame:InvalidBWPField", ...
        "%s must be a scalar logical.", label);
end
value = logical(input);
end

function value = localNonemptyReference(config, aliases)
label = aliases(1);
value = localText(localRequired(config, aliases, label), label);
end
