function manifest = exportFrameGridArtifacts(outputDirectory, varargin)
%EXPORTFRAMEGRIDARTIFACTS Export deterministic frame/grid conformance evidence.
%
% Every primary CSV is built by invoking the canonical production frame
% resolvers. Golden CSVs are comparison inputs in the tests; they are never
% copied into this output directory. PHY-facing indices in these artifacts
% are zero based.

parser = inputParser;
parser.FunctionName = "sixgr.phy.frame.exportFrameGridArtifacts";
addRequired(parser, "outputDirectory", @localTextScalar);
addParameter(parser, "TestSummary", table(), @istable);
addParameter(parser, "RequireAllPass", true, ...
    @(v) islogical(v) && isscalar(v));
parse(parser, outputDirectory, varargin{:});

outputDirectory = char(string(parser.Results.outputDirectory));
if ~isfolder(outputDirectory)
    mkdir(outputDirectory);
end
vectorDirectory = localVectorDirectory();

tables = struct();
tables.frame_numerology_matrix = localNumerologyMatrix(vectorDirectory);
tables.carrier_grid_matrix = localCarrierGridMatrix(vectorDirectory);
tables.slot_symbol_ownership = localSlotSymbolOwnership(vectorDirectory);
[tables.allocation_legality, tables.resource_grid_occupancy] = ...
    localAllocationArtifacts(vectorDirectory);
tables.ofdm_roundtrip = localOFDMRoundtrip(vectorDirectory);
[tables.timing_matrix, tables.bwp_switch_trace, ...
    tables.component_carrier_trace] = localTimingArtifacts();
tables.ssb_timing_matrix = localSSBTimingMatrix();
tables.prach_occasion_matrix = localPRACHOccasionMatrix();
tables.fdd_grid_trace = localFDDGridTrace();
tables.shortcut_removal_audit = localShortcutRemovalAudit();

summary = parser.Results.TestSummary;
if isempty(summary)
    error("sixgr:phy:frame:MissingFrameGridTestSummary", ...
        "A nonempty table of actually executed MATLAB tests is required.");
end
tables.frame_fix_test_summary = localNormalizeTestSummary(summary);

csvOrder = [ ...
    "frame_numerology_matrix"
    "carrier_grid_matrix"
    "slot_symbol_ownership"
    "resource_grid_occupancy"
    "allocation_legality"
    "ofdm_roundtrip"
    "timing_matrix"
    "bwp_switch_trace"
    "component_carrier_trace"
    "ssb_timing_matrix"
    "prach_occasion_matrix"
    "fdd_grid_trace"
    "shortcut_removal_audit"
    "frame_fix_test_summary"];
for name = csvOrder.'
    tables.(name) = localWithIndexConvention(tables.(name));
    writetable(tables.(name), fullfile(outputDirectory, name + ".csv"));
end

audit = localExportImages(outputDirectory, tables);
audit = localWithIndexConvention(audit);
writetable(audit, fullfile(outputDirectory, "frame_image_audit.csv"));
tables.frame_image_audit = audit;

csvFiles = [csvOrder + ".csv"; "frame_image_audit.csv"];
imageFiles = string(audit.ImageFile);
manifest = struct( ...
    "OutputDirectory", string(outputDirectory), ...
    "CSVFiles", csvFiles, ...
    "ImageFiles", imageFiles, ...
    "CSVCount", numel(csvFiles), ...
    "ImageCount", numel(imageFiles), ...
    "AllStatusPass", localAllStatusPass(tables), ...
    "IndexConvention", "zero_based_phy_indices");

if manifest.CSVCount ~= 15 || manifest.ImageCount ~= 9
    error("sixgr:phy:frame:ArtifactCountMismatch", ...
        "Frame/grid export produced %d CSVs and %d PNGs; expected 15 and 9.", ...
        manifest.CSVCount, manifest.ImageCount);
end
if parser.Results.RequireAllPass && ~manifest.AllStatusPass
    error("sixgr:phy:frame:FrameGridArtifactFailure", ...
        "At least one generated frame/grid evidence row has Status other than PASS.");
end
end

function tableOut = localNumerologyMatrix(vectorDirectory)
vectors = readtable(fullfile(vectorDirectory, ...
    "frame_numerology_test_vectors.csv"), "TextType", "string");
n = height(vectors);
testID = string(vectors.TestID);
mu = double(vectors.Mu);
scs = double(vectors.SCS_kHz);
cp = string(vectors.CyclicPrefix);
expectedValid = strings(n, 1);
resolvedValid = repmat("FALSE", n, 1);
expectedSymbols = double(vectors.ExpectedSymbolsPerSlot);
resolvedSymbols = nan(n, 1);
expectedSlotsSubframe = double(vectors.ExpectedSlotsPerSubframe);
resolvedSlotsSubframe = nan(n, 1);
expectedSlotsFrame = double(vectors.ExpectedSlotsPerFrame);
resolvedSlotsFrame = nan(n, 1);
errorID = strings(n, 1);
status = repmat("FAIL", n, 1);

for index = 1:n
    expected = localTruth(vectors.ExpectedValid(index));
    expectedValid(index) = localBoolText(expected);
    try
        result = sixgr.phy.frame.NumerologyCatalog.resolve( ...
            scs(index), cp(index), "generic_waveform_test", "");
        resolvedValid(index) = "TRUE";
        resolvedSymbols(index) = result.SymbolsPerSlot;
        resolvedSlotsSubframe(index) = result.SlotsPerSubframe;
        resolvedSlotsFrame(index) = result.SlotsPerFrame;
        matches = expected && result.Mu == mu(index) && ...
            result.SubcarrierSpacingKHz == scs(index) && ...
            string(result.CyclicPrefix) == lower(cp(index)) && ...
            result.SymbolsPerSlot == expectedSymbols(index) && ...
            result.SlotsPerSubframe == expectedSlotsSubframe(index) && ...
            result.SlotsPerFrame == expectedSlotsFrame(index);
    catch cause
        errorID(index) = string(cause.identifier);
        matches = ~expected && errorID(index) == ...
            string(vectors.ExpectedErrorID(index));
    end
    status(index) = localPassText(matches);
end

tableOut = table(testID, mu, scs, cp, expectedValid, resolvedValid, ...
    expectedSymbols, resolvedSymbols, expectedSlotsSubframe, ...
    resolvedSlotsSubframe, expectedSlotsFrame, resolvedSlotsFrame, ...
    errorID, status, 'VariableNames', [ ...
    "TestID","Mu","SCS_kHz","CyclicPrefix","ExpectedValid", ...
    "ResolvedValid","ExpectedSymbolsPerSlot","ResolvedSymbolsPerSlot", ...
    "ExpectedSlotsPerSubframe","ResolvedSlotsPerSubframe", ...
    "ExpectedSlotsPerFrame","ResolvedSlotsPerFrame","ErrorID","Status"]);
end

function tableOut = localCarrierGridMatrix(vectorDirectory)
vectors = readtable(fullfile(vectorDirectory, ...
    "frame_carrier_grid_test_vectors.csv"), "TextType", "string");
n = height(vectors);
testID = string(vectors.TestID);
role = string(vectors.Role);
frequencyRange = string(vectors.FrequencyRange);
centerHz = double(vectors.RepresentativeCenterFrequency_Hz);
bandwidthMHz = double(vectors.ChannelBandwidth_MHz);
scsKHz = double(vectors.CarrierSCS_kHz);
expectedValid = strings(n, 1);
resolvedValid = repmat("FALSE", n, 1);
expectedNRB = double(vectors.ExpectedNRB);
resolvedNRB = nan(n, 1);
nStartGrid = nan(n, 1);
occupiedHz = nan(n, 1);
guardLowHz = nan(n, 1);
guardHighHz = nan(n, 1);
channelLowHz = nan(n, 1);
channelHighHz = nan(n, 1);
transmissionLowHz = nan(n, 1);
transmissionHighHz = nan(n, 1);
activeBWPStartRB = nan(n, 1);
activeBWPSizeRB = nan(n, 1);
activeBWPLowHz = nan(n, 1);
activeBWPHighHz = nan(n, 1);
errorID = strings(n, 1);
status = repmat("FAIL", n, 1);

for index = 1:n
    expected = localTruth(vectors.ExpectedValid(index));
    expectedValid(index) = localBoolText(expected);
    try
        result = sixgr.phy.frame.CarrierGridConfig.resolve( ...
            "Role", role(index), ...
            "FrequencyRange", frequencyRange(index), ...
            "CenterFrequencyHz", centerHz(index), ...
            "ChannelBandwidthMHz", bandwidthMHz(index), ...
            "SubcarrierSpacingKHz", scsKHz(index));
        resolvedValid(index) = "TRUE";
        resolvedNRB(index) = result.NSizeGrid;
        nStartGrid(index) = result.NStartGrid;
        occupiedHz(index) = result.OccupiedBandwidthHz;
        guardLowHz(index) = result.MinimumLowGuardbandHz;
        guardHighHz(index) = result.MinimumHighGuardbandHz;
        channelLowHz(index) = centerHz(index) - ...
            bandwidthMHz(index) * 1e6 / 2;
        channelHighHz(index) = centerHz(index) + ...
            bandwidthMHz(index) * 1e6 / 2;
        transmissionLowHz(index) = centerHz(index) - ...
            occupiedHz(index) / 2;
        transmissionHighHz(index) = centerHz(index) + ...
            occupiedHz(index) / 2;
        activeBWPSizeRB(index) = max(1, floor(result.NSizeGrid / 2));
        activeBWPStartRB(index) = result.NStartGrid + ...
            floor((result.NSizeGrid - activeBWPSizeRB(index)) / 2);
        activeBWPLowHz(index) = transmissionLowHz(index) + ...
            (activeBWPStartRB(index) - result.NStartGrid) * ...
            12 * scsKHz(index) * 1e3;
        activeBWPHighHz(index) = activeBWPLowHz(index) + ...
            activeBWPSizeRB(index) * 12 * scsKHz(index) * 1e3;
        expectedGuardHz = double(vectors.ExpectedMinGuardband_kHz(index)) * 1e3;
        matches = expected && result.NSizeGrid == expectedNRB(index) && ...
            result.NStartGrid == 0 && ...
            abs(guardLowHz(index) - expectedGuardHz) < 1e-9 && ...
            abs(guardHighHz(index) - expectedGuardHz) < 1e-9;
    catch cause
        errorID(index) = string(cause.identifier);
        matches = ~expected && errorID(index) == ...
            string(vectors.ExpectedErrorID(index));
    end
    status(index) = localPassText(matches);
end

tableOut = table(testID, role, frequencyRange, centerHz, bandwidthMHz, ...
    scsKHz, expectedValid, resolvedValid, expectedNRB, resolvedNRB, ...
    nStartGrid, occupiedHz, guardLowHz, guardHighHz, ...
    channelLowHz, channelHighHz, transmissionLowHz, transmissionHighHz, ...
    activeBWPStartRB, activeBWPSizeRB, activeBWPLowHz, activeBWPHighHz, ...
    errorID, status, ...
    'VariableNames', [ ...
    "TestID","Role","FrequencyRange","CenterFrequency_Hz", ...
    "ChannelBandwidth_MHz","CarrierSCS_kHz","ExpectedValid", ...
    "ResolvedValid","ExpectedNRB","ResolvedNRB","NStartGrid", ...
    "OccupiedBandwidth_Hz","GuardbandLow_Hz","GuardbandHigh_Hz", ...
    "ChannelLowEdge_Hz","ChannelHighEdge_Hz", ...
    "TransmissionLowEdge_Hz","TransmissionHighEdge_Hz", ...
    "ActiveBWPStartRB","ActiveBWPSizeRB", ...
    "ActiveBWPLowEdge_Hz","ActiveBWPHighEdge_Hz", ...
    "ErrorID","Status"]);
end

function tableOut = localSlotSymbolOwnership(vectorDirectory)
vectors = readtable(fullfile(vectorDirectory, ...
    "frame_tdd_test_vectors.csv"), "TextType", "string");
parts = cell(0, 1);
for index = 1:height(vectors)
    row = vectors(index, :);
    if ~localTruth(row.ExpectedValid)
        continue;
    end
    common = localTDDCommon(row);
    if ismissing(row.DedicatedMode) || ...
            strlength(strtrim(row.DedicatedMode)) == 0
        state = common;
        dedicated = strings(size(common.CommonDirection));
    else
        rule = localDedicatedRule(row);
        state = sixgr.phy.frame.TDDDedicatedConfig.apply(common, rule);
        dedicated = state.DedicatedDirection;
    end
    commonDirection = common.CommonDirection;
    resolved = state.ResolvedDirection;
    [slots, symbols] = size(commonDirection);
    count = slots * symbols;
    testID = repmat(string(row.TestID), count, 1);
    cellID = zeros(count, 1);
    ccid = zeros(count, 1);
    bwpid = zeros(count, 1);
    frame = zeros(count, 1);
    slot = repelem((0:(slots - 1)).', symbols);
    slot = slot(:);
    symbol = repmat((0:(symbols - 1)).', slots, 1);
    commonText = string(reshape(commonDirection.', [], 1));
    dedicatedText = reshape(dedicated.', [], 1);
    resolvedText = reshape(resolved.', [], 1);
    source = repmat("common", count, 1);
    flex = commonText == "F";
    source(flex) = "unresolved_flexible";
    dedicatedConfigured = strlength(dedicatedText) > 0;
    source(dedicatedConfigured & dedicatedText ~= "F") = "dedicated";
    source(dedicatedConfigured & dedicatedText == "F") = ...
        "dedicated_flexible";
    owner = strings(count, 1);
    status = repmat("PASS", count, 1);
    localAssertRowCounts(string(row.TestID), count, ...
        testID, cellID, ccid, bwpid, frame, slot, symbol, commonText, ...
        dedicatedText, resolvedText, source, owner, status);
    parts{end + 1, 1} = table( ... %#ok<AGROW>
        testID, cellID, ccid, bwpid, frame, slot, symbol, ...
        commonText, dedicatedText, resolvedText, source, owner, status, ...
        'VariableNames', [ ...
        "TestID","CellID","CCID","BWPID","Frame","Slot","Symbol", ...
        "CommonDirection","DedicatedDirection","ResolvedDirection", ...
        "ResolutionSource","AllocationOwner","Status"]);
end
tableOut = vertcat(parts{:});
end

function common = localTDDCommon(row)
cp = "normal";
if string(row.TestID) == "TDD-011"
    cp = "extended";
end
p1 = localPattern(row.Pattern1Periodicity_ms, row.P1_DLSlots, ...
    row.P1_DLSymbols, row.P1_ULSlots, row.P1_ULSymbols);
p2 = struct();
if isfinite(row.Pattern2Periodicity_ms)
    p2 = localPattern(row.Pattern2Periodicity_ms, row.P2_DLSlots, ...
        row.P2_DLSymbols, row.P2_ULSlots, row.P2_ULSymbols);
end
common = sixgr.phy.frame.TDDCommonConfig.resolve( ...
    "ReferenceSubcarrierSpacingKHz", row.ReferenceSCS_kHz, ...
    "ActiveSubcarrierSpacingKHz", row.ActiveSCS_kHz, ...
    "CyclicPrefix", cp, "Pattern1", p1, "Pattern2", p2);
end

function pattern = localPattern(period, dlSlots, dlSymbols, ulSlots, ulSymbols)
pattern = struct( ...
    "PeriodicityMilliseconds", double(period), ...
    "NumDownlinkSlots", double(dlSlots), ...
    "NumDownlinkSymbols", double(dlSymbols), ...
    "NumUplinkSlots", double(ulSlots), ...
    "NumUplinkSymbols", double(ulSymbols));
end

function rule = localDedicatedRule(row)
rule = struct( ...
    "SlotIndex", double(row.DedicatedSlotIndex), ...
    "Mode", string(row.DedicatedMode));
if lower(string(row.DedicatedMode)) == "explicit"
    rule.FirstDownlinkSymbols = double(row.DedicatedDLSymbols);
    rule.LastUplinkSymbols = double(row.DedicatedULSymbols);
end
end

function [legality, occupancyOut] = localAllocationArtifacts(vectorDirectory)
vectors = readtable(fullfile(vectorDirectory, ...
    "frame_allocation_test_vectors.csv"), "TextType", "string");
n = height(vectors);
testID = string(vectors.TestID);
channel = string(vectors.Channel);
direction = string(vectors.Direction);
ccid = zeros(n, 1);
bwpid = zeros(n, 1);
absoluteSlot = zeros(n, 1);
startSymbol = double(vectors.StartSymbol);
numSymbols = double(vectors.NumSymbols);
startRB = zeros(n, 1);
numRB = ones(n, 1);
flexDecision = string(vectors.FlexResolution);
expectedValid = strings(n, 1);
actualValid = strings(n, 1);
reasonCode = strings(n, 1);
status = repmat("FAIL", n, 1);

for index = 1:n
    [state, conflict] = localAllocationState( ...
        vectors.SymbolMap(index), vectors.FlexResolution(index));
    if strlength(conflict) > 0
        valid = false;
        reason = conflict;
    else
        allocation = localVectorAllocation(vectors(index, :));
        result = sixgr.phy.frame.ResourceAllocationValidator.validate( ...
            allocation, state);
        valid = result.ActualValid;
        reason = result.ReasonCode;
    end
    expected = localTruth(vectors.ExpectedValid(index));
    expectedValid(index) = localBoolText(expected);
    actualValid(index) = localBoolText(valid);
    reasonCode(index) = reason;
    status(index) = localPassText(valid == expected && ...
        reason == string(vectors.ExpectedReasonCode(index)));
end
legality = table(testID, channel, direction, ccid, bwpid, ...
    absoluteSlot, startSymbol, numSymbols, startRB, numRB, ...
    flexDecision, expectedValid, actualValid, reasonCode, status, ...
    'VariableNames', [ ...
    "TestID","Channel","Direction","CCID","BWPID","AbsoluteSlot", ...
    "StartSymbol","NumSymbols","StartRB","NumRB","FlexDecision", ...
    "ExpectedValid","ActualValid","ReasonCode","Status"]);

p = struct("PeriodicityMilliseconds", 1, ...
    "NumDownlinkSlots", 1, "NumDownlinkSymbols", 0, ...
    "NumUplinkSlots", 0, "NumUplinkSymbols", 0);
slotState = sixgr.phy.frame.TDDCommonConfig.resolve( ...
    "ReferenceSubcarrierSpacingKHz", 15, ...
    "ActiveSubcarrierSpacingKHz", 15, "Pattern1", p);
allocations(1) = sixgr.phy.frame.ResourceAllocationValidator.makeAllocation( ...
    "PDCCH", "DL", "CCID", 0, "BWPID", 0, "AbsoluteSlot", 0, ...
    "StartSymbol", 0, "NumSymbols", 2, "StartRB", 0, "NumRB", 4, ...
    "GridNumRB", 24, "Ports", 0, "TestID", "OCC-PDCCH", ...
    "GridID", "cc0_bwp0_dl_grid");
controlResult = sixgr.phy.frame.ResourceAllocationValidator.validate( ...
    allocations(1), slotState, "GridNumRB", 24);
if ~controlResult.ActualValid
    error("sixgr:phy:frame:OccupancyControlAllocationInvalid", ...
        "Canonical CORESET occupancy failed: %s", ...
        controlResult.ReasonCode);
end
reservedKeys = controlResult.Occupancy.REKey;
allocations(2) = sixgr.phy.frame.ResourceAllocationValidator.makeAllocation( ...
    "PDSCH", "DL", "CCID", 0, "BWPID", 0, "AbsoluteSlot", 0, ...
    "StartSymbol", 0, "NumSymbols", 14, "MappingType", "A", ...
    "StartRB", 0, "NumRB", 24, "GridNumRB", 24, "Ports", 0, ...
    "RateMatchedREKeys", reservedKeys, ...
    "ReservedREKeys", reservedKeys, ...
    "ReservedReason", "coreset_re_reservation", ...
    "TestID", "OCC-PDSCH", "GridID", "cc0_bwp0_dl_grid");
report = sixgr.phy.frame.ResourceAllocationValidator.validateSet( ...
    allocations, slotState, "GridNumRB", 24);
if ~report.ActualValid
    error("sixgr:phy:frame:OccupancyScenarioInvalid", ...
        "Canonical occupancy scenario failed: %s", report.ReasonCode);
end
raw = report.Occupancy;
reservationAudit = controlResult.Occupancy;
reservationAudit.TestID(:) = "OCC-PDSCH-RATE-MATCHED";
reservationAudit.Channel(:) = "PDSCH_EXCLUDED";
reservationAudit.CollisionFlag(:) = true;
reservationAudit.ReservedReason(:) = "coreset_re_reservation";
raw = [raw; reservationAudit];
groups = findgroups( ...
    raw.TestID, raw.CCID, raw.BWPID, raw.Slot, raw.Symbol, raw.RB, ...
    raw.Port, raw.Channel, raw.Direction);
rowCount = max(groups);
collision = splitapply(@any, raw.CollisionFlag, groups);
reserved = splitapply(@(x) strjoin(unique(x), ";"), raw.ReservedReason, groups);
testValue = splitapply(@(x) x(1), raw.TestID, groups);
ccValue = splitapply(@(x) x(1), raw.CCID, groups);
bwpValue = splitapply(@(x) x(1), raw.BWPID, groups);
slotValue = splitapply(@(x) x(1), raw.Slot, groups);
symbolValue = splitapply(@(x) x(1), raw.Symbol, groups);
rbValue = splitapply(@(x) x(1), raw.RB, groups);
portValue = splitapply(@(x) x(1), raw.Port, groups);
channelValue = splitapply(@(x) x(1), raw.Channel, groups);
directionValue = splitapply(@(x) x(1), raw.Direction, groups);
statusValue = repmat("PASS", rowCount, 1);
occupancyOut = table(testValue, ccValue, bwpValue, slotValue, ...
    symbolValue, rbValue, portValue, channelValue, directionValue, ...
    collision, reserved, statusValue, 'VariableNames', [ ...
    "TestID","CCID","BWPID","Slot","Symbol","RB","Port","Channel", ...
    "Direction","CollisionFlag","ReservedReason","Status"]);
end

function allocation = localVectorAllocation(row)
mapping = "";
if any(string(row.Channel) == ["PDSCH", "PUSCH"])
    mapping = "A";
end
start = [];
count = [];
if isfinite(row.StartSymbol)
    start = row.StartSymbol;
end
if isfinite(row.NumSymbols)
    count = row.NumSymbols;
end
allocation = sixgr.phy.frame.ResourceAllocationValidator.makeAllocation( ...
    row.Channel, row.Direction, "CCID", 0, "BWPID", 0, ...
    "AbsoluteSlot", 0, "StartSymbol", start, "NumSymbols", count, ...
    "MappingType", mapping, "StartRB", 0, "NumRB", 1, ...
    "TestID", row.TestID);
end

function [state, conflict] = localAllocationState(symbolMap, decisions)
map = char(symbolMap);
resolved = strings(1, numel(map));
resolved(map == 'D') = "D";
resolved(map == 'U') = "U";
resolved(map == 'F') = "UNRESOLVED_FLEX";
state = struct("DuplexMode", "TDD", ...
    "CommonDirection", map, "DedicatedDirection", strings(size(map)), ...
    "SymbolDirection", map, "ResolvedDirection", resolved, ...
    "ResolutionSource", strings(size(map)), ...
    "AllocationOwner", strings(size(map)));
conflict = "";
decisions = strtrim(string(decisions));
if ismissing(decisions) || any(decisions == ["", "none", "unresolved"])
    return;
end
parts = split(decisions, ";");
for index = 1:numel(parts)
    token = split(parts(index), ":");
    direction = token(1);
    bounds = split(token(2), "-");
    first = str2double(bounds(1));
    last = first;
    if numel(bounds) == 2
        last = str2double(bounds(2));
    end
    request = struct("AbsoluteSlot", 0, "StartSymbol", first, ...
        "NumSymbols", last - first + 1, "Direction", direction, ...
        "Channel", "vector_runtime", "DecisionSource", "test_vector");
    try
        state = sixgr.phy.frame.FlexibleSymbolAllocator.allocate(state, request);
    catch cause
        if string(cause.identifier) == ...
                "sixgr:phy:frame:ConflictingFlexibleSymbolResolution"
            conflict = "conflicting_flexible_symbol_resolution";
            return;
        end
        rethrow(cause);
    end
end
end

function tableOut = localOFDMRoundtrip(vectorDirectory)
vectors = readtable(fullfile(vectorDirectory, ...
    "frame_carrier_grid_test_vectors.csv"), "TextType", "string");
mask = false(height(vectors), 1);
for index = 1:height(vectors)
    mask(index) = localTruth(vectors.ExpectedValid(index));
end
vectors = vectors(mask, :);
n = height(vectors) + 1;
rows = repmat(localEmptyOFDMRow(), n, 1);
for index = 1:height(vectors)
    state = sixgr.phy.frame.CarrierGridConfig.resolve( ...
        "Role", vectors.Role(index), ...
        "FrequencyRange", vectors.FrequencyRange(index), ...
        "CenterFrequencyHz", ...
            double(vectors.RepresentativeCenterFrequency_Hz(index)), ...
        "ChannelBandwidthMHz", double(vectors.ChannelBandwidth_MHz(index)), ...
        "SubcarrierSpacingKHz", double(vectors.CarrierSCS_kHz(index)));
    rows(index) = localRunOFDMPoint( ...
        string(vectors.TestID(index)), state, index);
end
extended = sixgr.phy.frame.CarrierGridConfig.resolve( ...
    "Role", "gNB", "FrequencyRange", "FR1", ...
    "CenterFrequencyHz", 4e9, ...
    "ChannelBandwidthMHz", 20, "SubcarrierSpacingKHz", 60, ...
    "CyclicPrefix", "extended");
rows(end) = localRunOFDMPoint("OFDM-EXTENDED-CP-60", extended, 6002);
tableOut = struct2table(rows);
end

function row = localRunOFDMPoint(testID, state, seed)
carrier = nrCarrierConfig;
carrier.NCellID = 1;
carrier.NSizeGrid = state.NSizeGrid;
carrier.NStartGrid = state.NStartGrid;
carrier.SubcarrierSpacing = state.SubcarrierSpacingKHz;
carrier.CyclicPrefix = string(state.CyclicPrefix);
carrier.NSlot = 0;
carrier.NFrame = 0;

resolved = sixgr.phy.frame.OFDMSamplingResolver.resolve(state);
txGrid = localDeterministicGrid( ...
    12 * carrier.NSizeGrid, resolved.SymbolsPerSlot, seed);
[waveform, ~] = nrOFDMModulate(carrier, txGrid, ...
    "Nfft", resolved.Nfft, ...
    "SampleRate", resolved.SampleRateHz, ...
    "Windowing", resolved.WindowingSamples);
rxGrid = nrOFDMDemodulate(carrier, waveform, ...
    "Nfft", resolved.Nfft, ...
    "SampleRate", resolved.SampleRateHz);
delta = rxGrid - txGrid;
nmse = sum(abs(delta(:)).^2) / sum(abs(txGrid(:)).^2);
evm = 100 * sqrt(nmse);
valid = isequal(size(txGrid), size(rxGrid)) && ...
    resolved.WindowingSamples == 0 && nmse <= 1e-12 && evm <= 1e-4;
numerology = sixgr.phy.frame.NumerologyCatalog.resolve( ...
    carrier.SubcarrierSpacing, carrier.CyclicPrefix, ...
    "generic_waveform_test", "");
row = struct( ...
    "TestID", string(testID), ...
    "Mu", double(numerology.Mu), ...
    "SCS_kHz", double(carrier.SubcarrierSpacing), ...
    "CyclicPrefix", string(carrier.CyclicPrefix), ...
    "NRB", double(carrier.NSizeGrid), ...
    "Nfft", double(resolved.Nfft), ...
    "SampleRate_Hz", double(resolved.SampleRateHz), ...
    "CPLengthsSamples", string(mat2str( ...
        resolved.CyclicPrefixLengthsPerSlot)), ...
    "WindowingSamples", double(resolved.WindowingSamples), ...
    "OccupiedBandwidth_Hz", double(resolved.OccupiedBandwidthHz), ...
    "GuardbandLow_Hz", double(state.MinimumLowGuardbandHz), ...
    "GuardbandHigh_Hz", double(state.MinimumHighGuardbandHz), ...
    "TxGridPower", mean(abs(txGrid(:)).^2), ...
    "RxGridPower", mean(abs(rxGrid(:)).^2), ...
    "NMSE", double(nmse), ...
    "EVMPercent", double(evm), ...
    "AliasingMargin_Hz", double(resolved.AliasingMarginHz), ...
    "Status", localPassText(valid));
end

function row = localEmptyOFDMRow()
row = struct( ...
    "TestID", "", "Mu", NaN, "SCS_kHz", NaN, ...
    "CyclicPrefix", "", "NRB", NaN, "Nfft", NaN, ...
    "SampleRate_Hz", NaN, "CPLengthsSamples", "", ...
    "WindowingSamples", NaN, "OccupiedBandwidth_Hz", NaN, ...
    "GuardbandLow_Hz", NaN, "GuardbandHigh_Hz", NaN, ...
    "TxGridPower", NaN, "RxGridPower", NaN, "NMSE", NaN, ...
    "EVMPercent", NaN, "AliasingMargin_Hz", NaN, "Status", "FAIL");
end

function grid = localDeterministicGrid(subcarriers, symbols, seed)
grid = complex(zeros(subcarriers, symbols));
locations = unique([1, subcarriers, max(1, floor(subcarriers / 4)), ...
    max(1, floor(subcarriers / 2)), ...
    max(1, floor(3 * subcarriers / 4))]);
for location = locations
    for symbol = 1:symbols
        phaseIndex = mod(seed + 17 * location + 29 * symbol, 16);
        grid(location, symbol) = exp(1j * 2 * pi * phaseIndex / 16);
    end
end
end

function [timingTable, bwpTable, carrierTable] = localTimingArtifacts()
[cc0, dl0, ul0, cc1, dl1, ul1, dl1Cross] = ...
    localTimingCarriers();
policy = localArtifactTimingPolicy(dl0, ul0);
engine = sixgr.phy.frame.TimingRelationEngine({cc0, cc1}, policy);
source = sixgr.phy.frame.AbsoluteTime.fromFrameSlotSymbol(0, 0, 0, dl0);
crossSource = source.plusSlots(1, dl0);

requests = cell(5, 1);
requests{1} = localTimingRequest("TIMING-PDSCH-K0", "PDSCH", ...
    source, "CC0", "CC0", 0, "DL0", "DL0", 1, 2, 10, 0, 1);
requests{2} = localTimingRequest("TIMING-PUSCH-K2", "PUSCH", ...
    source, "CC0", "CC0", 0, "DL0", "UL0", 2, 0, 12, 0, 2);
requests{3} = localTimingRequest("TIMING-HARQ-K1", "HARQ_ACK", ...
    source, "CC0", "CC0", 0, "DL0", "UL0", 4, 0, 2, 1, 3);
requests{4} = localTimingRequest("TIMING-UNSUPPORTED-K2", "PUSCH", ...
    source, "CC0", "CC0", 0, "DL0", "UL0", 3, 0, 12, 0, 4);
requests{5} = localTimingRequest("TIMING-CROSS-CC-K0", "PDSCH", ...
    crossSource, "CC0", "CC1", 1, "DL0", "DL1X", ...
    2, 2, 10, 0, 5);
expected = [true; true; true; false; true];
expectedReason = [ ...
    "timing_relation_valid"
    "timing_relation_valid"
    "timing_relation_valid"
    "unsupported_k2"
    "timing_relation_valid"];
results = cell(numel(requests), 1);
for index = 1:numel(requests)
    results{index} = engine.resolve(requests{index});
end

n = numel(results);
testID = strings(n, 1);
procedure = strings(n, 1);
pdcchAbsSlot = zeros(n, 1);
sourceMu = nan(n, 1);
targetMu = nan(n, 1);
k0 = nan(n, 1);
k1 = nan(n, 1);
k2 = nan(n, 1);
targetAbsSlot = nan(n, 1);
startSymbol = nan(n, 1);
processingSymbols = nan(n, 1);
availableSymbols = nan(n, 1);
expectedValid = strings(n, 1);
actualValid = strings(n, 1);
reasonCode = strings(n, 1);
status = repmat("FAIL", n, 1);
for index = 1:n
    result = results{index};
    testID(index) = result.TestID;
    procedure(index) = result.Procedure;
    sourceMu(index) = result.SourceMu;
    targetMu(index) = result.TargetMu;
    k0(index) = result.K0;
    k1(index) = result.K1;
    k2(index) = result.K2;
    targetAbsSlot(index) = result.TargetAbsoluteSlot;
    startSymbol(index) = result.TargetStartSymbol;
    if result.SourceBWPID == "DL0"
        sourceBWP = dl0;
    elseif result.SourceBWPID == "UL0"
        sourceBWP = ul0;
    elseif result.SourceBWPID == "DL1"
        sourceBWP = dl1;
    elseif result.SourceBWPID == "DL1X"
        sourceBWP = dl1Cross;
    else
        error("sixgr:phy:frame:ArtifactUnknownSourceBWP", ...
            "Timing artifact result references unknown source BWP '%s'.", ...
            result.SourceBWPID);
    end
    sourceTime = sixgr.phy.frame.AbsoluteTime.fromTicks(result.SourceTick);
    [sourceFrame, sourceSlot] = sourceTime.toNumerology(sourceBWP);
    pdcchAbsSlot(index) = double(sourceFrame) * ...
        sourceBWP.SlotsPerFrame + double(sourceSlot);
    if isfinite(result.MinimumProcessingTicks)
        processingSymbols(index) = double(result.MinimumProcessingTicks) / ...
            double(sourceBWP.TicksPerSymbol);
    end
    if result.ProcessingGapTicks >= 0
        availableSymbols(index) = double(result.ProcessingGapTicks) / ...
            double(sourceBWP.TicksPerSymbol);
    end
    expectedValid(index) = localBoolText(expected(index));
    actualValid(index) = localBoolText(result.Valid);
    reasonCode(index) = result.ReasonCode;
    status(index) = localPassText(result.Valid == expected(index) && ...
        result.ReasonCode == expectedReason(index));
end
timingTable = table(testID, procedure, pdcchAbsSlot, sourceMu, ...
    targetMu, k0, k1, k2, targetAbsSlot, startSymbol, ...
    processingSymbols, availableSymbols, expectedValid, actualValid, ...
    reasonCode, status, 'VariableNames', [ ...
    "TestID","Procedure","PDCCHAbsSlot","SourceMu","TargetMu", ...
    "K0","K1","K2","TargetAbsSlot","StartSymbol", ...
    "ProcessingTimeSymbols","AvailableSymbols","ExpectedValid", ...
    "ActualValid","ReasonCode","Status"]);

carrierTable = localComponentCarrierTrace( ...
    engine, source, dl0, ul0, dl1, ul1, dl1Cross);
bwpTable = localBWPSwitchTrace();
end

function policy = localArtifactTimingPolicy(dlBWP, ulBWP)
% Pin the configured artifact timing rows to the production catalog.  K0
% and K2 are scenario TDRA selections, while K1 is the configured
% PDSCH-to-HARQ feedback list; none is presented as a universal constant.
k0 = [0, 1, 2];
k1 = [1, 2, 4];
k2 = [1, 2, 4];
dlCapability = sixgr.phy.frame.TimingPolicyCatalog.capability1(dlBWP.Mu);
ulCapability = sixgr.phy.frame.TimingPolicyCatalog.capability1(ulBWP.Mu);
configured = struct( ...
    "AllowedK0", k0, ...
    "AllowedK1", k1, ...
    "AllowedK2", k2, ...
    "K0Rows", sixgr.phy.frame.TimingPolicyCatalog.configuredRows( ...
        "K0", k0, ...
        "exportFrameGridArtifacts.artifactScenario.pdschTDRA"), ...
    "K1Rows", sixgr.phy.frame.TimingPolicyCatalog.configuredRows( ...
        "K1", k1, ...
        "exportFrameGridArtifacts.artifactScenario.harqFeedbackTiming"), ...
    "K2Rows", sixgr.phy.frame.TimingPolicyCatalog.configuredRows( ...
        "K2", k2, ...
        "exportFrameGridArtifacts.artifactScenario.puschTDRA"), ...
    "N1PDSCHProcessingTimeSymbols", dlCapability.PDSCHN1Symbols, ...
    "N2PUSCHPreparationTimeSymbols", ulCapability.PUSCHN2Symbols, ...
    "CapabilityProfileID", ...
        sixgr.phy.frame.TimingPolicyCatalog.CapabilityProfileBase + ...
        "-mu" + string(dlBWP.Mu), ...
    "ControlToDataProcessingTimeSymbols", struct( ...
        "PDCCHToPDSCH", 0, ...
        "PDSCHToHARQACKN1", dlCapability.PDSCHN1Symbols, ...
        "PDCCHToPUSCHN2", ulCapability.PUSCHN2Symbols), ...
    "PolicyID", "frame_grid_artifact_configured_timing", ...
    "Source", "configured_artifact_scenario_plus_pinned_3gpp_catalog");
policy = sixgr.phy.frame.TimingPolicyCatalog.resolveProduction( ...
    configured, dlBWP.Mu, ulBWP.Mu, ["K0", "K1", "K2"]);
end

function request = localTimingRequest(testID, procedure, sourceTime, ...
        schedulingCCID, scheduledCCID, indicator, sourceBWPID, ...
        targetBWPID, k, targetStart, targetLength, ...
        minimumProcessingSymbols, harqProcessID)
request = struct( ...
    "TestID", testID, "Procedure", procedure, ...
    "SourceTime", sourceTime, ...
    "SchedulingCCID", schedulingCCID, ...
    "ScheduledCCID", scheduledCCID, ...
    "CarrierIndicator", indicator, ...
    "SourceBWPID", sourceBWPID, "TargetBWPID", targetBWPID, ...
    "SourceNumSymbols", 1, ...
    "TargetStartSymbol", targetStart, ...
    "TargetNumSymbols", targetLength, ...
    "MinimumProcessingSymbols", minimumProcessingSymbols, ...
    "ProcessingTimeReference", "source", ...
    "TimingAdvanceTicks", 0, ...
    "HARQProcessID", harqProcessID);
switch upper(procedure)
    case "PDSCH"
        request.K0 = k;
    case "PUSCH"
        request.K2 = k;
    otherwise
        request.K1 = k;
end
end

function [cc0, dl0, ul0, cc1, dl1, ul1, dl1Cross] = ...
        localTimingCarriers()
zero = sixgr.phy.frame.AbsoluteTime.fromTicks(0);
grid0 = struct("NStartGrid", 0, "NSizeGrid", 273, ...
    "SubcarrierSpacingKHz", 30, "FrequencyRange", "FR1");
dl0 = sixgr.phy.frame.BWPConfig(localBWPConfig( ...
    "CC0", "CELL0", "DL0", "DL", 30, 0, 273, true, zero, ...
    "DL0", "DL0"), grid0);
ul0 = sixgr.phy.frame.BWPConfig(localBWPConfig( ...
    "CC0", "CELL0", "UL0", "UL", 30, 0, 273, true, zero, ...
    "DL0", "UL0"), grid0);
indicator0(1) = struct("Indicator", 0, "ScheduledCCID", "CC0");
indicator0(2) = struct("Indicator", 1, "ScheduledCCID", "CC1");
cc0 = sixgr.phy.frame.ComponentCarrierConfig(localCCConfig( ...
    "CC0", "CELL0", 2.14e9, 1.95e9, 100, 273, 30, ...
    "CC0", indicator0), ...
    {dl0, ul0});

grid1 = struct("NStartGrid", 0, "NSizeGrid", 65, ...
    "SubcarrierSpacingKHz", 60, "FrequencyRange", "FR1");
dl1 = sixgr.phy.frame.BWPConfig(localBWPConfig( ...
    "CC1", "CELL1", "DL1", "DL", 60, 0, 65, true, zero, ...
    "DL1", "DL1"), grid1);
dl1Cross = sixgr.phy.frame.BWPConfig(localBWPConfig( ...
    "CC1", "CELL1", "DL1X", "DL", 60, 0, 65, false, zero, ...
    "DL0", "DL1X"), grid1);
ul1 = sixgr.phy.frame.BWPConfig(localBWPConfig( ...
    "CC1", "CELL1", "UL1", "UL", 60, 0, 65, true, zero, ...
    "DL1", "UL1"), grid1);
indicator1 = struct("Indicator", 0, "ScheduledCCID", "CC1");
cc1 = sixgr.phy.frame.ComponentCarrierConfig(localCCConfig( ...
    "CC1", "CELL1", 2.65e9, 2.53e9, 50, 65, 60, ...
    ["CC0", "CC1"], indicator1), {dl1, ul1, dl1Cross});
activation = sixgr.phy.frame.AbsoluteTime.fromAbsoluteSlotSymbol( ...
    4, 0, dl1Cross);
decision = cc1.BWPState.scheduleSwitch("DL", "DL1X", activation, ...
    "IssuedTime", zero, "ControlBWPID", "DL1", ...
    "TriggerSource", "configured_cross_carrier_scenario", ...
    "CommandID", "activate-cross-carrier-data-bwp");
if ~decision.Accepted
    error("sixgr:phy:frame:ArtifactCrossCarrierBWPSwitchRejected", ...
        "Configured cross-carrier BWP switch was rejected: %s.", ...
        decision.ReasonCode);
end
end

function config = localBWPConfig(ccid, cellID, bwpid, direction, ...
        scs, startRB, sizeRB, active, activation, controlBWPID, dataBWPID)
config = struct( ...
    "BWPID", bwpid, "Direction", direction, "CCID", ccid, ...
    "ServingCellID", cellID, "FrequencyRange", "FR1", ...
    "SCSKHz", scs, "CyclicPrefix", "normal", ...
    "NStartBWP", startRB, "NSizeBWP", sizeRB, ...
    "ControlConfigRef", lower(direction) + "_control_" + bwpid, ...
    "DataConfigRef", lower(direction) + "_data_" + bwpid, ...
    "ControlBWPID", controlBWPID, "DataBWPID", dataBWPID, ...
    "ActiveInitial", active, "SwitchActivationTime", activation, ...
    "StateVersion", 1, "CommonTDDReferenceSCSKHz", NaN);
end

function config = localCCConfig(ccid, cellID, dlCenterHz, ulCenterHz, ...
        bandwidthMHz, nrb, scs, schedulingCCIDs, indicatorMap)
config = struct( ...
    "CCID", ccid, "ServingCellID", cellID, ...
    "SchedulingCCIDs", schedulingCCIDs, ...
    "CenterFrequencyHz", dlCenterHz, ...
    "DLCenterFrequencyHz", dlCenterHz, ...
    "ULCenterFrequencyHz", ulCenterHz, "Band", "configured_fdd", ...
    "FrequencyRange", "FR1", "ChannelBandwidthMHz", bandwidthMHz, ...
    "DuplexMode", "FDD", ...
    "DLCarrierGrid", struct("NStartGrid", 0, "NSizeGrid", nrb, ...
        "SubcarrierSpacingKHz", scs), ...
    "ULCarrierGrid", struct("NStartGrid", 0, "NSizeGrid", nrb, ...
        "SubcarrierSpacingKHz", scs), ...
    "CarrierIndicatorMap", indicatorMap);
end

function tableOut = localComponentCarrierTrace( ...
        engine, source, dl0, ul0, dl1, ul1, dl1Cross)
crossSource = source.plusSlots(1, dl0);
requests = cell(6, 1);
requests{1} = localTimingRequest("CC0-DL-RESOURCE", "PDSCH", ...
    source, "CC0", "CC0", 0, "DL0", "DL0", 1, 2, 10, 0, 5);
requests{2} = localTimingRequest("CC0-UL-RESOURCE", "PUSCH", ...
    source, "CC0", "CC0", 0, "DL0", "UL0", 2, 0, 12, 0, 5);
requests{3} = localTimingRequest("CC1-DL-RESOURCE", "PDSCH", ...
    source, "CC1", "CC1", 0, "DL1", "DL1", 1, 2, 10, 0, 5);
requests{4} = localTimingRequest("CC1-UL-RESOURCE", "PUSCH", ...
    source, "CC1", "CC1", 0, "DL1", "UL1", 2, 0, 12, 0, 5);
requests{5} = localTimingRequest("CC0-TO-CC1-CROSS-CARRIER", "PDSCH", ...
    crossSource, "CC0", "CC1", 1, "DL0", "DL1X", ...
    2, 2, 10, 0, 5);
requests{6} = localTimingRequest("CC-WRONG-INDICATOR", "PDSCH", ...
    crossSource, "CC0", "CC1", 0, "DL0", "DL1X", ...
    2, 2, 10, 0, 5);
results = cell(6, 1);
for index = 1:numel(requests)
    results{index} = engine.resolve(requests{index});
end
expected = [true; true; true; true; true; false];
n = numel(results);
testID = strings(n, 1);
ueid = repmat("UE0", n, 1);
schedulingCell = strings(n, 1);
scheduledCell = strings(n, 1);
indicator = nan(n, 1);
absSlot = nan(n, 1);
grantType = strings(n, 1);
harqID = nan(n, 1);
bwpID = strings(n, 1);
scheduledCCID = strings(n, 1);
schedulingCCID = strings(n, 1);
direction = strings(n, 1);
startRB = [0; 24; 0; 12; 20; 20];
numRB = [64; 48; 32; 24; 24; 24];
schedulingStartRB = [0; 24; 0; 12; 0; 0];
schedulingNumRB = [64; 48; 32; 24; 64; 64];
startSymbol = nan(n, 1);
numSymbols = [10; 12; 10; 12; 10; 10];
resourceKey = strings(n, 1);
measurementNamespace = strings(n, 1);
schedulingLane = nan(n, 1);
scheduledLane = nan(n, 1);
plotColorCode = nan(n, 1);
ownershipType = [ ...
    "local_cc_resource"; "local_cc_resource"; ...
    "local_cc_resource"; "local_cc_resource"; ...
    "cross_carrier_scheduling_link"; "rejected_cross_carrier_link"];
expectedValid = strings(n, 1);
actualValid = strings(n, 1);
reasonCode = strings(n, 1);
status = repmat("FAIL", n, 1);
for index = 1:n
    result = results{index};
    testID(index) = result.TestID;
    schedulingCCID(index) = result.SchedulingCCID;
    scheduledCCID(index) = result.ScheduledCCID;
    schedulingCell(index) = "CELL" + extractAfter(result.SchedulingCCID, "CC");
    scheduledCell(index) = "CELL" + extractAfter(result.ScheduledCCID, "CC");
    indicator(index) = result.CarrierIndicator;
    absSlot(index) = result.TargetAbsoluteSlot;
    grantType(index) = result.Procedure;
    harqID(index) = result.HARQProcessID;
    bwpID(index) = result.TargetBWPID;
    startSymbol(index) = result.TargetStartSymbol;
    if result.Procedure == "PUSCH"
        direction(index) = "UL";
    else
        direction(index) = "DL";
    end
    schedulingLane(index) = localCarrierLane( ...
        result.SchedulingCCID, direction(index));
    scheduledLane(index) = localCarrierLane( ...
        result.ScheduledCCID, direction(index));
    plotColorCode(index) = scheduledLane(index);
    if result.TargetBWPID == "DL0"
        targetBWP = dl0;
    elseif result.TargetBWPID == "UL0"
        targetBWP = ul0;
    elseif result.TargetBWPID == "DL1"
        targetBWP = dl1;
    elseif result.TargetBWPID == "DL1X"
        targetBWP = dl1Cross;
    else
        targetBWP = ul1;
    end
    resourceKey(index) = targetBWP.resourceKey( ...
        result.Procedure, result.TestID);
    measurementNamespace(index) = result.ScheduledCCID + ...
        "|MEAS=CSI";
    expectedValid(index) = localBoolText(expected(index));
    actualValid(index) = localBoolText(result.Valid);
    reasonCode(index) = result.ReasonCode;
    status(index) = localPassText(result.Valid == expected(index));
end
tableOut = table(testID, ueid, schedulingCell, scheduledCell, ...
    indicator, absSlot, grantType, harqID, bwpID, expectedValid, ...
    actualValid, reasonCode, status, schedulingCCID, scheduledCCID, ...
    direction, startRB, numRB, startSymbol, numSymbols, resourceKey, ...
    measurementNamespace, ownershipType, schedulingStartRB, ...
    schedulingNumRB, schedulingLane, scheduledLane, plotColorCode, ...
    'VariableNames', [ ...
    "TestID","UEID","SchedulingCellID","ScheduledCellID", ...
    "CarrierIndicator","AbsSlot","GrantType","HARQProcessID","BWPID", ...
    "ExpectedValid","ActualValid","ReasonCode","Status", ...
    "SchedulingCCID","ScheduledCCID","Direction","StartRB","NumRB", ...
    "StartSymbol","NumSymbols","ResourceKey","MeasurementNamespace", ...
    "OwnershipType","SchedulingStartRB","SchedulingNumRB", ...
    "SchedulingLane","ScheduledLane","PlotColorCode"]);
end

function tableOut = localBWPSwitchTrace()
grid = struct("NStartGrid", 0, "NSizeGrid", 273, ...
    "SubcarrierSpacingKHz", 30, "FrequencyRange", "FR1");
zero = sixgr.phy.frame.AbsoluteTime.fromTicks(0);
numerology = sixgr.phy.frame.NumerologyCatalog.resolve( ...
    30, "normal", "generic_waveform_test", "");
activation = sixgr.phy.frame.AbsoluteTime.fromFrameSlotSymbol( ...
    0, 4, 0, numerology);
dl0 = sixgr.phy.frame.BWPConfig(localBWPConfig( ...
    "CCB", "CELLB", "DL0", "DL", 30, 0, 273, true, zero, ...
    "DL0", "DL0"), grid);
dl1 = sixgr.phy.frame.BWPConfig(localBWPConfig( ...
    "CCB", "CELLB", "DL1", "DL", 60, 24, 100, false, ...
    activation, "DL1", "DL1"), grid);
ul0 = sixgr.phy.frame.BWPConfig(localBWPConfig( ...
    "CCB", "CELLB", "UL0", "UL", 30, 0, 200, true, zero, ...
    "DL0", "UL0"), grid);
state = sixgr.phy.frame.BWPStateMachine({dl0, dl1, ul0});
issued = sixgr.phy.frame.AbsoluteTime.fromFrameSlotSymbol( ...
    0, 1, 0, numerology);
decision = state.scheduleSwitch("DL", "DL1", activation, ...
    "IssuedTime", issued, "ControlBWPID", "DL0", ...
    "TriggerSource", "DCI", "CommandID", "artifact-dl-switch");
if ~decision.Accepted
    error("sixgr:phy:frame:ArtifactBWPSwitchRejected", ...
        "Canonical BWP artifact switch failed: %s", decision.ReasonCode);
end
after = sixgr.phy.frame.AbsoluteTime.fromFrameSlotSymbol( ...
    0, 5, 0, numerology);
state.applyUntil(after);
history = state.historyTable();
nHistory = height(history);
testID = "BWP-HISTORY-" + compose("%03d", (1:nHistory).');
ueid = repmat("UE0", nHistory, 1);
ccid = string(history.CCID);
direction = string(history.Direction);
absSlot = zeros(nHistory, 1);
for index = 1:nHistory
    time = sixgr.phy.frame.AbsoluteTime.fromTicks(history.Tick(index));
    [~, slot] = time.toNumerology(numerology);
    absSlot(index) = double(slot);
end
oldBWPID = string(history.OldBWPID);
commandedBWPID = string(history.CommandedBWPID);
activationAbsSlot = -ones(nHistory, 1);
hasCommand = strlength(string(history.CommandID)) > 0 & ...
    string(history.Event) ~= "INITIAL_STATE";
activationAbsSlot(hasCommand) = 4;
activeBWPID = string(history.ActiveBWPID);
triggerSource = string(history.TriggerSource);
expectedValid = repmat("TRUE", nHistory, 1);
actualValid = localBoolTextVector(history.Status ~= "rejected");
reasonCode = string(history.ReasonCode);
status = repmat("PASS", nHistory, 1);
eventType = string(history.Event);
grantBWPID = repmat("", nHistory, 1);

grantSlots = [2; 2; 3; 5; 5];
grantDirections = ["DL"; "DL"; "UL"; "DL"; "DL"];
grantIDs = ["DL0"; "DL1"; "UL0"; "DL1"; "DL0"];
controlIDs = ["DL0"; "DL1"; "DL0"; "DL1"; "DL0"];
grantExpected = [true; false; true; true; false];
grantCount = numel(grantSlots);
for index = 1:grantCount
    grantTime = sixgr.phy.frame.AbsoluteTime.fromFrameSlotSymbol( ...
        0, grantSlots(index), 0, numerology);
    grant = struct("CCID", "CCB", "Direction", ...
        grantDirections(index), "BWPID", grantIDs(index), ...
        "ControlBWPID", controlIDs(index), "Time", grantTime);
    result = state.validateGrant(grant);
    active = state.activeBWPAt(grantDirections(index), grantTime);
    testID(end + 1, 1) = "BWP-GRANT-" + compose("%02d", index);
    ueid(end + 1, 1) = "UE0";
    ccid(end + 1, 1) = "CCB";
    direction(end + 1, 1) = grantDirections(index);
    absSlot(end + 1, 1) = grantSlots(index);
    oldBWPID(end + 1, 1) = active.BWPID;
    commandedBWPID(end + 1, 1) = "";
    activationAbsSlot(end + 1, 1) = 4;
    activeBWPID(end + 1, 1) = active.BWPID;
    triggerSource(end + 1, 1) = "grant_validation";
    expectedValid(end + 1, 1) = localBoolText(grantExpected(index));
    actualValid(end + 1, 1) = localBoolText(result.Allowed);
    reasonCode(end + 1, 1) = result.ReasonCode;
    status(end + 1, 1) = localPassText( ...
        result.Allowed == grantExpected(index));
    eventType(end + 1, 1) = "GRANT";
    grantBWPID(end + 1, 1) = grantIDs(index);
end
ulSnapshotTime = sixgr.phy.frame.AbsoluteTime.fromFrameSlotSymbol( ...
    0, 5, 0, numerology);
ulSnapshot = state.activeBWPAt("UL", ulSnapshotTime);
testID(end + 1, 1) = "BWP-UL-SNAPSHOT";
ueid(end + 1, 1) = "UE0";
ccid(end + 1, 1) = "CCB";
direction(end + 1, 1) = "UL";
absSlot(end + 1, 1) = 5;
oldBWPID(end + 1, 1) = ulSnapshot.BWPID;
commandedBWPID(end + 1, 1) = "";
activationAbsSlot(end + 1, 1) = 4;
activeBWPID(end + 1, 1) = ulSnapshot.BWPID;
triggerSource(end + 1, 1) = "state_snapshot";
expectedValid(end + 1, 1) = "TRUE";
actualValid(end + 1, 1) = "TRUE";
reasonCode(end + 1, 1) = "ul_bwp_unchanged_by_dl_switch";
status(end + 1, 1) = "PASS";
eventType(end + 1, 1) = "STATE_SNAPSHOT";
grantBWPID(end + 1, 1) = "";

tableOut = table(testID, ueid, ccid, direction, absSlot, oldBWPID, ...
    commandedBWPID, activationAbsSlot, activeBWPID, triggerSource, ...
    expectedValid, actualValid, reasonCode, status, eventType, grantBWPID, ...
    'VariableNames', [ ...
    "TestID","UEID","CCID","Direction","AbsSlot","OldBWPID", ...
    "CommandedBWPID","ActivationAbsSlot","ActiveBWPID", ...
    "TriggerSource","ExpectedValid","ActualValid","ReasonCode","Status", ...
    "EventType","GrantBWPID"]);
end

function tableOut = localSSBTimingMatrix()
caseName = ["A"; "B"; "C"; "D"; "E"; "F"; "G"];
centerHz = [2e9; 4e9; 4e9; 28e9; 28e9; 60e9; 60e9];
range = ["FR1"; "FR1"; "FR1"; "FR2-1"; "FR2-1"; "FR2-2"; "FR2-2"];
ssbSCS = [15; 30; 30; 120; 240; 480; 960];
lmax = [4; 8; 8; 64; 64; 64; 64];
parts = cell(numel(caseName), 1);
for caseIndex = 1:numel(caseName)
    result = sixgr.phy.frame.SSBTimingResolver.resolve( ...
        "Case", caseName(caseIndex), ...
        "CarrierFrequencyHz", centerHz(caseIndex), ...
        "FrequencyRange", range(caseIndex), ...
        "SSBSubcarrierSpacingKHz", ssbSCS(caseIndex), ...
        "CarrierSubcarrierSpacingKHz", min(ssbSCS(caseIndex), 120), ...
        "Lmax", lmax(caseIndex), "SSBIndex", 0);
    count = result.Lmax;
    testID = "SSB-" + caseName(caseIndex) + "-" + ...
        compose("%02d", result.CandidateIndices(:));
    caseColumn = repmat(caseName(caseIndex), count, 1);
    rangeColumn = repmat(range(caseIndex), count, 1);
    centerColumn = repmat(centerHz(caseIndex), count, 1);
    scsColumn = repmat(ssbSCS(caseIndex), count, 1);
    lmaxColumn = repmat(lmax(caseIndex), count, 1);
    candidate = result.CandidateIndices(:);
    start = result.CandidateStartSymbolsWithinHalfFrame(:);
    slot = result.CandidateSlotsWithinHalfFrame(:);
    symbol = result.CandidateSymbolsWithinSlot(:);
    expectedValid = repmat("TRUE", count, 1);
    actualValid = repmat(localBoolText(result.ResolvedValid), count, 1);
    reasonCode = repmat("ssb_case_candidate_resolved", count, 1);
    status = repmat(localPassText( ...
        result.ResolvedValid && count == lmax(caseIndex)), count, 1);
    parts{caseIndex} = table(testID, caseColumn, rangeColumn, ...
        centerColumn, scsColumn, lmaxColumn, candidate, start, slot, ...
        symbol, expectedValid, actualValid, reasonCode, status, ...
        'VariableNames', [ ...
        "TestID","Case","FrequencyRange","CarrierFrequency_Hz", ...
        "SSBSCS_kHz","Lmax","CandidateIndex","StartSymbol", ...
        "Slot","Symbol","ExpectedValid","ActualValid","ReasonCode","Status"]);
end
tableOut = vertcat(parts{:});
end

function tableOut = localPRACHOccasionMatrix()
scenarios = [ ...
    struct("TestID", "PRACH-FR1-FDD-LONG", ...
        "FrequencyRange", "FR1", "DuplexMode", "FDD", ...
        "ConfigurationIndex", 16, "CarrierSCS", 15, ...
        "NSizeGrid", 52, "PRACHSCS", 1.25); ...
    struct("TestID", "PRACH-FR1-FDD-SHORT", ...
        "FrequencyRange", "FR1", "DuplexMode", "FDD", ...
        "ConfigurationIndex", 87, "CarrierSCS", 15, ...
        "NSizeGrid", 52, "PRACHSCS", 15); ...
    struct("TestID", "PRACH-FR1-TDD-SHORT", ...
        "FrequencyRange", "FR1", "DuplexMode", "TDD", ...
        "ConfigurationIndex", 167, "CarrierSCS", 30, ...
        "NSizeGrid", 106, "PRACHSCS", 30)];
parts = cell(numel(scenarios), 1);
for scenarioIndex = 1:numel(scenarios)
    scenario = scenarios(scenarioIndex);
    result = sixgr.phy.frame.PRACHOccasionResolver.resolve( ...
        "FrequencyRange", scenario.FrequencyRange, ...
        "DuplexMode", scenario.DuplexMode, ...
        "ConfigurationIndex", scenario.ConfigurationIndex, ...
        "CarrierSubcarrierSpacingKHz", scenario.CarrierSCS, ...
        "NSizeGrid", scenario.NSizeGrid, ...
        "PRACHSubcarrierSpacingKHz", scenario.PRACHSCS, ...
        "Msg1FDM", 1);
    occasions = result.Occasions;
    count = height(occasions);
    testID = scenario.TestID + "-" + compose("%04d", (0:(count - 1)).');
    frequencyRange = repmat(string(result.FrequencyRange), count, 1);
    duplexMode = repmat(string(result.DuplexMode), count, 1);
    configurationIndex = repmat(result.ConfigurationIndex, count, 1);
    format = string(occasions.Format);
    periodFrames = repmat(result.PeriodFrames, count, 1);
    frame = double(occasions.Frame);
    absoluteSlot = double(occasions.AbsoluteSlot);
    startSymbol = double(occasions.StartSymbol);
    durationSymbols = double(occasions.DurationSymbols);
    frequencyIndex = double(occasions.FrequencyIndex);
    ulAvailable = localBoolTextVector(occasions.ULAvailable);
    expectedValid = repmat("TRUE", count, 1);
    actualValid = repmat(localBoolText(result.ResolvedValid && ...
        ~result.FallbackUsed && ~result.UnknownIndexDefaulted), count, 1);
    reasonCode = string(occasions.AvailabilityReason);
    reasonCode(strlength(reasonCode) == 0) = "prach_occasion_resolved";
    status = repmat(localPassText(result.ResolvedValid && ...
        ~result.FallbackUsed && ~result.UnknownIndexDefaulted && count > 0), ...
        count, 1);
    parts{scenarioIndex} = table(testID, frequencyRange, duplexMode, ...
        configurationIndex, format, periodFrames, frame, absoluteSlot, ...
        startSymbol, durationSymbols, frequencyIndex, ulAvailable, ...
        expectedValid, actualValid, reasonCode, status, ...
        'VariableNames', [ ...
        "TestID","FrequencyRange","DuplexMode","ConfigurationIndex", ...
        "Format","PeriodFrames","Frame","AbsoluteSlot","StartSymbol", ...
        "DurationSymbols","FrequencyIndex","ULAvailable", ...
        "ExpectedValid","ActualValid","ReasonCode","Status"]);
end
tableOut = vertcat(parts{:});
end

function tableOut = localFDDGridTrace()
fdd = sixgr.phy.frame.FDDCarrierContexts.create( ...
    "CellID", 7, "DLCCID", 1, "ULCCID", 1, ...
    "DLBWPID", 10, "ULBWPID", 20, ...
    "DLCenterFrequencyHz", 2.14e9, ...
    "ULCenterFrequencyHz", 1.95e9, ...
    "SubcarrierSpacingKHz", 30, ...
    "DLNumRB", 106, "ULNumRB", 106, ...
    "ULTimingAdvanceSamples", 32);
directions = ["DL"; "UL"];
slots = [0; 1];
symbols = [0; 7];
rbs = [0; 5];
count = numel(directions) * numel(slots) * numel(symbols) * numel(rbs);
testID = strings(count, 1);
ccid = zeros(count, 1);
direction = strings(count, 1);
gridID = strings(count, 1);
bwpid = zeros(count, 1);
absoluteSlot = zeros(count, 1);
symbol = zeros(count, 1);
startRB = zeros(count, 1);
numRB = ones(count, 1);
resourceKey = strings(count, 1);
expectedValid = repmat("TRUE", count, 1);
actualValid = repmat("FALSE", count, 1);
reasonCode = strings(count, 1);
status = repmat("FAIL", count, 1);
cursor = 0;
for directionIndex = 1:numel(directions)
    link = directions(directionIndex);
    context = fdd.context(link);
    for slotIndex = 1:numel(slots)
        for symbolIndex = 1:numel(symbols)
            for rbIndex = 1:numel(rbs)
                cursor = cursor + 1;
                testID(cursor) = "FDD-" + link + "-" + ...
                    compose("%02d-%02d-%03d", slots(slotIndex), ...
                    symbols(symbolIndex), rbs(rbIndex));
                ccid(cursor) = context.CCID;
                direction(cursor) = link;
                gridID(cursor) = context.GridID;
                bwpid(cursor) = context.BWPID;
                absoluteSlot(cursor) = slots(slotIndex);
                symbol(cursor) = symbols(symbolIndex);
                startRB(cursor) = rbs(rbIndex);
                available = fdd.isAvailable(slots(slotIndex), link, context);
                resourceKey(cursor) = fdd.resourceKey(link, ...
                    slots(slotIndex), symbols(symbolIndex), ...
                    rbs(rbIndex), 0, 0);
                actualValid(cursor) = localBoolText(available);
                reasonCode(cursor) = "separate_" + lower(link) + "_grid";
                status(cursor) = localPassText(available);
            end
        end
    end
end
tableOut = table(testID, ccid, direction, gridID, bwpid, absoluteSlot, ...
    symbol, startRB, numRB, resourceKey, expectedValid, actualValid, ...
    reasonCode, status, 'VariableNames', [ ...
    "TestID","CCID","Direction","GridID","BWPID","AbsSlot","Symbol", ...
    "StartRB","NumRB","ResourceKey","ExpectedValid","ActualValid", ...
    "ReasonCode","Status"]);
end

function tableOut = localShortcutRemovalAudit()
root = localRepositoryRoot();
activeScope = "+sixgr/**/*.m (active production; +compat and audit definition excluded)";
checks = [ ...
    struct("ID", "SHORTCUT-01", ...
        "Behavior", "F converted to D", ...
        "Scope", activeScope, ...
        "Pattern", "(?i)(?:strrep|replace)\s*\([^,;]+,\s*['""]F['""]\s*,\s*['""]D['""]\s*\)"); ...
    struct("ID", "SHORTCUT-02", ...
        "Behavior", "configured grid used after standard table miss", ...
        "Scope", activeScope, ...
        "Pattern", "(?i)(configured_grid_no_standard_bandwidth_scs_match|\bNRB\s*=\s*(?:round\s*\()?[^\r\n;]*ConfiguredGridNumRBs)"); ...
    struct("ID", "SHORTCUT-03", ...
        "Behavior", "FR2-2 classified as FR3", ...
        "Scope", activeScope, ...
        "Pattern", "(?is)(?:FR2-2.{0,180}(?:FrequencyRange|RangeClass)\s*=\s*['""]FR3['""]|(?:FrequencyRange|RangeClass)\s*=\s*['""]FR3['""].{0,180}FR2-2)"); ...
    struct("ID", "SHORTCUT-04", ...
        "Behavior", "nextpow2 implicit standard OFDM resolver", ...
        "Scope", activeScope, ...
        "Pattern", "(?i)nextpow2\s*\(\s*12\s*\*\s*(?:N?RB|NSizeGrid|NumRB|GridNumRBs)\b"); ...
    struct("ID", "SHORTCUT-05", ...
        "Behavior", "12/1/1 or 7/0/7 special-slot fallback", ...
        "Scope", activeScope, ...
        "Pattern", "(?is)(?:(?:fallback|default|isempty|missing).{0,220}(?:12\s*[/,]\s*1\s*[/,]\s*1|7\s*[/,]\s*0\s*[/,]\s*7)|(?:special(?:Slot)?(?:Split|Symbols)|symbolSplit)\s*=\s*\[\s*(?:12\s*,\s*1\s*,\s*1|7\s*,\s*0\s*,\s*7)\s*\])"); ...
    struct("ID", "SHORTCUT-06", ...
        "Behavior", "default DDDSU pattern in standard path", ...
        "Scope", activeScope, ...
        "Pattern", "(?i)(?:(?:fallback|default)\w*(?:Pattern)?\s*=\s*['""]DDDSU['""]|structGet\s*\([^;\r\n]{0,220}(?:pattern|tdd)[^;\r\n]{0,220}['""]DDDSU['""])"); ...
    struct("ID", "SHORTCUT-07", ...
        "Behavior", "PDSCH start derived from CORESET duration", ...
        "Scope", activeScope, ...
        "Pattern", "(?i)PDSCH(?:StartSymbol|SymbolAllocation)\s*=\s*[^;]{0,240}CORESET(?:Duration|NumSymbols)"); ...
    struct("ID", "SHORTCUT-08", ...
        "Behavior", "PUSCH full-slot allocation injected by frame resolution", ...
        "Scope", activeScope, ...
        "Pattern", "(?is)(?:structSet\s*\([^;]{0,240}phy\.pusch\.symbolAllocation[^;]{0,140}\[\s*0\s+(?:14|symbolsPerSlot)\s*\]|if\s+isempty\s*\(\s*(?:symAlloc|symbolAllocation)\s*\).{0,260}(?:symAlloc|symbolAllocation)\s*=\s*\[\s*0\s+(?:14|symbolsPerSlot)\s*\])"); ...
    struct("ID", "SHORTCUT-09", ...
        "Behavior", "2.5%-of-NFFT default windowing", ...
        "Scope", activeScope, ...
        "Pattern", "(?i)(0?\.025\s*\*?\s*Nfft|2\.5\s*%\s*of\s*Nfft)"); ...
    struct("ID", "SHORTCUT-10", ...
        "Behavior", "SSB NSizeGrid clamp/retry", ...
        "Scope", activeScope, ...
        "Pattern", "(?i)(ClampNSizeGrid|WavegenWithClamp|" + ...
        "SSB.{0,120}NSizeGrid.{0,120}(clamp|retry)|" + ...
        "NSizeGrid.{0,120}SSB.{0,120}(clamp|retry))"); ...
    struct("ID", "SHORTCUT-11", ...
        "Behavior", "unknown PRACH index defaulted to A1", ...
        "Scope", activeScope, ...
        "Pattern", "(?is)(?:unknown.{0,100}(?:PRACH|index).{0,100}(?:default|fallback|otherwise).{0,80}A1|fallback.{0,80}A1|(?:format|prachFormat|index)\s*=\s*['""']A1['""'].{0,100}(?:unknown|fallback))"); ...
    struct("ID", "SHORTCUT-12", ...
        "Behavior", "catch-all canonical-to-legacy resolver fallback", ...
        "Scope", activeScope, ...
        "Pattern", "(?im)(?:canonical_to_legacy_fallback|^[ \t]*catch(?:[ \t]+\w+)?[^\r\n]*(?:\r?\n[ \t]+[^\r\n]*){0,12}\b(?:\w*legacy\w*(?:resolver|resolve)\w*|\w*(?:resolver|resolve)\w*legacy\w*)\s*\()"); ...
    struct("ID", "SHORTCUT-13", ...
        "Behavior", "missing data/grant allocation fabricated as full slot or carrier", ...
        "Scope", activeScope, ...
        "Pattern", "(?is)(?:if\s+isempty\s*\(\s*(?:prb|prbSet|prbSetCfg)\s*\).{0,360}(?:prbVec|prbSet)\s*=\s*0\s*:\s*\(\s*(?:nSizeGrid|NSizeGrid|nGrid)[^)]*\)|(?:structGet|localObjectValue)\s*\([^;\r\n]{0,260}SymbolAllocation[^;\r\n]{0,160}\[\s*0\s+14\s*\]|catch.{0,100}(?:sa|symAlloc|symbolAllocation)\s*=\s*\[\s*0\s+14\s*\]|(?:sa|symAlloc|symbolAllocation)\s*=\s*\[\s*0\s+14\s*\]\s*;.{0,220}if\s+(?:nargin|numel|isempty)|if\s+numel\s*\(\s*(?:sa|symAlloc|symbolAllocation)\s*\).{0,160}(?:symbols\s*=\s*0\s*:\s*13|(?:sa|symAlloc|symbolAllocation)\s*=\s*\[\s*0\s+14\s*\]))")];

n = numel(checks);
checkID = strings(n, 1);
behavior = strings(n, 1);
searchScope = strings(n, 1);
files = localResolveAuditFiles(root, "+sixgr");
filesScanned = repmat(numel(files), n, 1);
matchCount = zeros(n, 1);
expectedCount = zeros(n, 1);
status = repmat("FAIL", n, 1);
reason = strings(n, 1);
matchedLocations = strings(n, 1);
matchedEvidence = strings(n, 1);
for index = 1:n
    checkID(index) = checks(index).ID;
    behavior(index) = checks(index).Behavior;
    searchScope(index) = checks(index).Scope;
    count = 0;
    locations = strings(0, 1);
    evidence = strings(0, 1);
    for fileIndex = 1:numel(files)
        source = fileread(files(fileIndex));
        source = regexprep(source, '(?m)%[^\r\n]*$', '');
        if ~localShortcutAuditPrefilter(checks(index).ID, source)
            starts = zeros(1, 0);
            matches = cell(1, 0);
        elseif checks(index).ID == "SHORTCUT-13"
            % The missing-allocation check is intentionally contextual.
            % Implement it with bounded line windows instead of one large
            % dot-all expression: applying the previous nested expression
            % to large production files caused pathological backtracking.
            [starts, matches] = ...
                localMissingAllocationShortcutMatches(source);
        elseif checks(index).ID == "SHORTCUT-12"
            [starts, matches] = ...
                localCanonicalLegacyFallbackMatches(source);
        else
            [starts, matches] = regexp(source, checks(index).Pattern, ...
                "start", "match");
        end
        count = count + numel(starts);
        for matchIndex = 1:numel(starts)
            lineNumber = 1 + nnz( ...
                source(1:(starts(matchIndex) - 1)) == newline);
            relativeFile = erase(string(files(fileIndex)), ...
                string(root) + filesep);
            relativeFile = replace(relativeFile, filesep, "/");
            locations(end + 1, 1) = relativeFile + ":" + ...
                string(lineNumber); %#ok<AGROW>
            snippet = regexprep(string(matches{matchIndex}), "\s+", " ");
            if strlength(snippet) > 180
                snippet = extractBefore(snippet, 178) + "...";
            end
            evidence(end + 1, 1) = snippet; %#ok<AGROW>
        end
    end
    matchCount(index) = count;
    matchedLocations(index) = strjoin(locations, ";");
    matchedEvidence(index) = strjoin(evidence, " | ");
    status(index) = localPassText(count == 0);
    if count == 0
        reason(index) = "no_active_hit";
    else
        reason(index) = "active_shortcut_hit_detected";
    end
end
tableOut = table(checkID, behavior, searchScope, filesScanned, matchCount, ...
    expectedCount, status, reason, matchedLocations, matchedEvidence, ...
    'VariableNames', [ ...
    "CheckID","Behavior","SearchScope","FilesScanned","MatchCount", ...
    "ExpectedCount","Status","Reason","MatchedLocations", ...
    "MatchedEvidence"]);
end

function tf = localShortcutAuditPrefilter(checkID, source)
text = lower(source);
switch string(checkID)
    case "SHORTCUT-01"
        tf = (contains(text, "strrep") || contains(text, "replace")) && ...
            contains(text, "f") && contains(text, "d");
    case "SHORTCUT-02"
        tf = contains(text, "configuredgridnumrbs") || ...
            contains(text, "configured_grid_no_standard_bandwidth_scs_match");
    case "SHORTCUT-03"
        tf = contains(text, "fr2-2") && contains(text, "fr3");
    case "SHORTCUT-04"
        tf = contains(text, "nextpow2");
    case "SHORTCUT-05"
        tf = contains(text, "12/1/1") || contains(text, "7/0/7") || ...
            ~isempty(regexp(text, ...
            '\[\s*(?:12\s*,\s*1\s*,\s*1|7\s*,\s*0\s*,\s*7)\s*\]', ...
            'once'));
    case "SHORTCUT-06"
        tf = contains(text, "dddsu");
    case "SHORTCUT-07"
        tf = contains(text, "pdsch") && contains(text, "coreset") && ...
            (contains(text, "startsymbol") || ...
             contains(text, "symbolallocation"));
    case "SHORTCUT-08"
        tf = contains(text, "pusch") && ...
            contains(text, "symbolallocation") && ...
            (contains(text, "[0 14]") || ...
             contains(text, "symbolsperslot"));
    case "SHORTCUT-09"
        tf = contains(text, ".025") || contains(text, "2.5");
    case "SHORTCUT-10"
        tf = contains(text, "clampnsizegrid") || ...
            contains(text, "wavegenwithclamp") || ...
            (contains(text, "ssb") && contains(text, "nsizegrid") && ...
             (contains(text, "clamp") || contains(text, "retry")));
    case "SHORTCUT-11"
        tf = contains(text, "prach") && contains(text, "a1") && ...
            (contains(text, "unknown") || contains(text, "fallback"));
    case "SHORTCUT-12"
        tf = contains(text, "catch") && contains(text, "legacy") && ...
            (contains(text, "resolve") || contains(text, "resolver"));
    case "SHORTCUT-13"
        tf = (contains(text, "isempty") && contains(text, "prb")) || ...
            contains(text, "[0 14]") || contains(text, "symbols = 0:13") || ...
            contains(text, "symbols=0:13");
    otherwise
        tf = true;
end
end

function [starts, matches] = localCanonicalLegacyFallbackMatches(source)
starts = zeros(1, 0);
matches = cell(1, 0);
lines = regexp(source, '\r\n|\n|\r', 'split');
lineStarts = [1, regexp(source, '\r\n|\n|\r', 'end') + 1];
if numel(lineStarts) > numel(lines)
    lineStarts = lineStarts(1:numel(lines));
end
lowerLines = lower(string(lines));
for lineIndex = 1:numel(lines)
    if isempty(regexp(char(lowerLines(lineIndex)), ...
            '^\s*catch(?:\s+\w+)?\s*$', 'once'))
        continue;
    end
    [window, original] = localAuditLineWindow( ...
        lowerLines, lines, lineIndex, 0, 12);
    hasLegacyResolverCall = ~isempty(regexp(window, ...
        "\b(?:\w*legacy\w*(?:resolver|resolve)\w*|" + ...
        "\w*(?:resolver|resolve)\w*legacy\w*)\s*\(", 'once'));
    if hasLegacyResolverCall || ...
            contains(window, "canonical_to_legacy_fallback")
        starts(end + 1) = lineStarts(lineIndex); %#ok<AGROW>
        matches{end + 1} = original; %#ok<AGROW>
    end
end
end

function [starts, matches] = localMissingAllocationShortcutMatches(source)
% Detect only contextual fabrication of absent time/frequency allocations.
% Offsets refer to SOURCE so the caller can report exact file/line evidence.
starts = zeros(1, 0);
matches = cell(1, 0);
lines = regexp(source, '\r\n|\n|\r', 'split');
lineStarts = [1, regexp(source, '\r\n|\n|\r', 'end') + 1];
if numel(lineStarts) > numel(lines)
    lineStarts = lineStarts(1:numel(lines));
end
lowerLines = lower(string(lines));

for lineIndex = 1:numel(lines)
    line = char(lowerLines(lineIndex));

    % A missing PRB set must not be expanded to the complete carrier.
    if ~isempty(regexp(line, ...
            'if\s+isempty\s*\(\s*(?:prb|prbset|prbsetcfg)\s*\)', ...
            'once'))
        [window, original] = localAuditLineWindow( ...
            lowerLines, lines, lineIndex, 0, 12);
        if ~isempty(regexp(window, ...
                "(?:prbvec|prbset)\s*=\s*0\s*:\s*\(?\s*" + ...
                "(?:nsizegrid|ngrid|gridnumrbs)", 'once'))
            starts(end + 1) = lineStarts(lineIndex); %#ok<AGROW>
            matches{end + 1} = original; %#ok<AGROW>
        end
    end

    % A getter/catch must not inject an implicit full-slot allocation.
    if contains(line, "symbolallocation") || ...
            ~isempty(regexp(line, ...
            '^\s*(?:sa|symalloc|symbolallocation)\s*=', 'once'))
        [window, original] = localAuditLineWindow( ...
            lowerLines, lines, lineIndex, 3, 10);
        hasFullSlot = ~isempty(regexp(window, ...
            '\[\s*0\s+14\s*\]', 'once'));
        hasImplicitContext = contains(window, "structget") || ...
            contains(window, "localobjectvalue") || ...
            contains(window, "catch") || ...
            contains(window, "isempty") || ...
            contains(window, "nargin") || ...
            contains(window, "numel");
        if hasFullSlot && hasImplicitContext
            starts(end + 1) = lineStarts(lineIndex); %#ok<AGROW>
            matches{end + 1} = original; %#ok<AGROW>
        end
    end

    % The equivalent explicit-symbol-vector rescue is also prohibited.
    if contains(line, "symbols = 0:13") || ...
            contains(line, "symbols=0:13")
        [window, original] = localAuditLineWindow( ...
            lowerLines, lines, lineIndex, 8, 4);
        if contains(window, "isempty") || contains(window, "numel") || ...
                contains(window, "catch")
            starts(end + 1) = lineStarts(lineIndex); %#ok<AGROW>
            matches{end + 1} = original; %#ok<AGROW>
        end
    end
end

if ~isempty(starts)
    [starts, uniqueIndex] = unique(starts, "stable");
    matches = matches(uniqueIndex);
end
end

function [normalized, original] = localAuditLineWindow( ...
        lowerLines, lines, anchor, before, after)
first = max(1, anchor - before);
last = min(numel(lines), anchor + after);
normalized = char(strjoin(lowerLines(first:last), " "));
original = char(strjoin(string(lines(first:last)), " "));
end

function files = localResolveAuditFiles(root, scopes)
files = strings(0, 1);
for scope = scopes(:).'
    path = fullfile(root, strrep(char(scope), "/", filesep));
    if isfile(path)
        files(end + 1, 1) = string(path); %#ok<AGROW>
    elseif isfolder(path)
        listing = dir(fullfile(path, "**", "*.m"));
        if ~isempty(listing)
            names = string(fullfile({listing.folder}, {listing.name}));
            files = [files; names(:)]; %#ok<AGROW>
        end
    end
end
files = unique(files, "stable");
relativeFiles = replace(erase(files, string(root) + filesep), ...
    filesep, "/");
excluded = endsWith(relativeFiles, ...
    "+sixgr/+phy/+frame/exportFrameGridArtifacts.m") | ...
    startsWith(relativeFiles, "+sixgr/+compat/");
files(excluded) = [];
end

function audit = localExportImages(outputDirectory, tables)
specs = [ ...
    struct("ImageFile", "frame_slot_symbol_map.png", ...
        "SourceCSV", "slot_symbol_ownership.csv", "Kind", "slot"); ...
    struct("ImageFile", "resource_grid_occupancy.png", ...
        "SourceCSV", "resource_grid_occupancy.csv", "Kind", "occupancy"); ...
    struct("ImageFile", "numerology_timing_matrix.png", ...
        "SourceCSV", "frame_numerology_matrix.csv", "Kind", "numerology"); ...
    struct("ImageFile", "carrier_guardband_map.png", ...
        "SourceCSV", "carrier_grid_matrix.csv", "Kind", "carrier"); ...
    struct("ImageFile", "k0_k1_k2_timeline.png", ...
        "SourceCSV", "timing_matrix.csv", "Kind", "timing"); ...
    struct("ImageFile", "bwp_switch_timeline.png", ...
        "SourceCSV", "bwp_switch_trace.csv", "Kind", "bwp"); ...
    struct("ImageFile", "component_carrier_resource_map.png", ...
        "SourceCSV", "component_carrier_trace.csv", "Kind", "carrier_component"); ...
    struct("ImageFile", "ssb_timing_map.png", ...
        "SourceCSV", "ssb_timing_matrix.csv", "Kind", "ssb"); ...
    struct("ImageFile", "prach_occasion_map.png", ...
        "SourceCSV", "prach_occasion_matrix.csv", "Kind", "prach")];

rows = repmat(localEmptyImageAuditRow(), numel(specs), 1);
for index = 1:numel(specs)
    sourceField = erase(specs(index).SourceCSV, ".csv");
    sourceTable = tables.(sourceField);
    [fig, semantic] = localCreateArtifactFigure( ...
        specs(index).Kind, sourceTable);
    cleanup = onCleanup(@() close(fig));
    imagePath = fullfile(outputDirectory, specs(index).ImageFile);
    exportgraphics(fig, imagePath, "Resolution", 100);
    clear cleanup;

    info = imfinfo(imagePath);
    pixels = imread(imagePath);
    if ndims(pixels) == 3
        gray = mean(double(pixels(:, :, 1:min(3, size(pixels, 3)))), 3);
        mode = "RGB";
        if size(pixels, 3) == 4
            mode = "RGBA";
        end
    else
        gray = double(pixels);
        mode = "L";
    end
    fileInfo = dir(imagePath);
    nonBlank = mean(gray(:) < 250);
    pixelStd = std(gray(:), 1);
    binaryPass = info.Width >= 1200 && info.Height >= 650 && ...
        fileInfo.bytes > 1000 && nonBlank > 0.001 && pixelStd > 1;
    rows(index) = struct( ...
        "ImageFile", string(specs(index).ImageFile), ...
        "SourceCSV", string(specs(index).SourceCSV), ...
        "SourceCSV_SHA256", localSHA256(fullfile( ...
            outputDirectory, specs(index).SourceCSV)), ...
        "ImageSHA256", localSHA256(imagePath), ...
        "Width", double(info.Width), ...
        "Height", double(info.Height), ...
        "Mode", mode, ...
        "FileBytes", double(fileInfo.bytes), ...
        "NonBlankFraction", double(nonBlank), ...
        "PixelStdDev", double(pixelStd), ...
        "ExpectedAxes", double(semantic.ExpectedAxes), ...
        "ObservedAxes", double(semantic.ObservedAxes), ...
        "ExpectedSeries", double(semantic.ExpectedSeries), ...
        "ObservedSeries", double(semantic.ObservedSeries), ...
        "Status", localPassText(semantic.Pass && binaryPass), ...
        "Reason", localImageReason(semantic.Pass, binaryPass));
end
audit = struct2table(rows);
end

function [fig, semantic] = localCreateArtifactFigure(kind, source)
fig = figure("Visible", "off", "Color", "white", ...
    "Units", "pixels", "Position", [10, 10, 1440, 780]);
axesHandle = axes(fig);
hold(axesHandle, "on");
grid(axesHandle, "on");
sourceDetail = "";
switch string(kind)
    case "slot"
        rows = source(source.TestID == "TDD-001", :);
        slots = max(rows.Slot) + 1;
        symbols = max(rows.Symbol) + 1;
        commonMatrix = zeros(slots, symbols);
        resolvedMatrix = zeros(slots, symbols);
        for index = 1:height(rows)
            commonMatrix(rows.Slot(index) + 1, rows.Symbol(index) + 1) = ...
                localDirectionCode(rows.CommonDirection(index));
            resolvedMatrix(rows.Slot(index) + 1, rows.Symbol(index) + 1) = ...
                localDirectionCode(rows.ResolvedDirection(index));
        end
        matrix = [commonMatrix; nan(1, symbols); resolvedMatrix];
        series = imagesc(axesHandle, 0:(symbols - 1), ...
            0:(size(matrix, 1) - 1), matrix);
        colormap(axesHandle, [0.95 0.68 0.28; 0.82 0.82 0.82; 0.12 0.60 0.82]);
        colorbar(axesHandle, "Ticks", [-1, 0, 1], ...
            "TickLabels", ["UL", "Flexible", "DL"]);
        commonLabels = "Common s" + string((0:(slots - 1)).');
        resolvedLabels = "Runtime s" + string((0:(slots - 1)).');
        yticks(axesHandle, [0:(slots - 1), (slots + 1):(2 * slots)]);
        yticklabels(axesHandle, [commonLabels; resolvedLabels]);
        title(axesHandle, ...
            "TDD common ownership and runtime-resolved symbol state");
        xlabel(axesHandle, "zero-based OFDM symbol");
        ylabel(axesHandle, "common map / resolved map");
        sourceMatch = isequaln(double(series.CData), double(matrix));
        expectedSeries = 1;
    case "occupancy"
        symbols = max(source.Symbol) + 1;
        rbs = max(source.RB) + 1;
        matrix = zeros(rbs, symbols);
        for index = 1:height(source)
            if source.Channel(index) == "PDCCH"
                value = 1;
            elseif source.Channel(index) == "PDSCH"
                value = 2;
            else
                value = 3;
            end
            matrix(source.RB(index) + 1, source.Symbol(index) + 1) = value;
        end
        series = gobjects(2, 1);
        series(1) = imagesc(axesHandle, 0:(symbols - 1), ...
            0:(rbs - 1), matrix);
        collision = source(logical(source.CollisionFlag), :);
        series(2) = scatter(axesHandle, collision.Symbol, collision.RB, ...
            70, "x", "MarkerEdgeColor", [0.72 0.08 0.08], ...
            "LineWidth", 1.8, "DisplayName", "explicit rate-match exclusion");
        colormap(axesHandle, [1 1 1; 0.18 0.55 0.78; ...
            0.20 0.70 0.42; 0.90 0.40 0.22]);
        colorbar(axesHandle, "Ticks", [0, 1, 2, 3], ...
            "TickLabels", ["Unused", "PDCCH", "PDSCH", "Reserved"]);
        legend(axesHandle, series(2), "Location", "northeast");
        title(axesHandle, ...
            "Resource-grid ownership (port 0) and explicit CORESET exclusions");
        xlabel(axesHandle, "zero-based OFDM symbol");
        ylabel(axesHandle, "zero-based resource block");
        sourceMatch = isequal(double(series(1).CData), double(matrix)) && ...
            isequal(double(series(2).XData(:)), ...
                double(collision.Symbol(:))) && ...
            isequal(double(series(2).YData(:)), double(collision.RB(:))) && ...
            all(strlength(collision.ReservedReason) > 0);
        expectedSeries = 2;
    case "numerology"
        rows = source(source.ResolvedValid == "TRUE", :);
        rows.CPOrder = double(rows.CyclicPrefix == "extended");
        rows = sortrows(rows, ["Mu", "CPOrder"]);
        rawValues = [rows.SCS_kHz, rows.ResolvedSymbolsPerSlot, ...
            rows.ResolvedSlotsPerSubframe, rows.ResolvedSlotsPerFrame];
        matrix = log2(rawValues);
        series = imagesc(axesHandle, 1:4, 1:height(rows), matrix);
        colormap(axesHandle, parula(64));
        colorbarHandle = colorbar(axesHandle);
        colorbarHandle.Label.String = "log2(value)";
        xticks(axesHandle, 1:4);
        xticklabels(axesHandle, ["SCS kHz", "symbols/slot", ...
            "slots/subframe", "slots/frame"]);
        labels = "\mu=" + string(rows.Mu) + " " + rows.CyclicPrefix;
        yticks(axesHandle, 1:height(rows));
        yticklabels(axesHandle, labels);
        for rowIndex = 1:size(rawValues, 1)
            for columnIndex = 1:size(rawValues, 2)
                text(axesHandle, columnIndex, rowIndex, ...
                    compose("%g", rawValues(rowIndex, columnIndex)), ...
                    "HorizontalAlignment", "center", ...
                    "Color", "black", "FontWeight", "bold");
            end
        end
        title(axesHandle, ...
            "Release-18 numerology timing matrix (normal \mu0-6; extended \mu2)");
        xlabel(axesHandle, "resolved timing property");
        ylabel(axesHandle, "numerology and cyclic prefix");
        sourceMatch = isequal(double(series.CData), double(matrix)) && ...
            nnz(rows.CyclicPrefix == "extended") == 1 && ...
            rows.Mu(rows.CyclicPrefix == "extended") == 2;
        expectedSeries = 1;
    case "carrier"
        row = source(source.TestID == "GRID-FR1-030-0100", :);
        if height(row) ~= 1 || row.ResolvedValid ~= "TRUE"
            error("sixgr:phy:frame:MissingCarrierFigureAnchor", ...
                "The 100 MHz / 30 kHz FR1 carrier anchor is unavailable.");
        end
        center = row.CenterFrequency_Hz;
        x = @(values) (double(values) - center) / 1e6;
        channelX = x([row.ChannelLowEdge_Hz, row.ChannelHighEdge_Hz]);
        transmissionX = x([row.TransmissionLowEdge_Hz, ...
            row.TransmissionHighEdge_Hz]);
        bwpX = x([row.ActiveBWPLowEdge_Hz, row.ActiveBWPHighEdge_Hz]);
        lowGuardX = x([row.ChannelLowEdge_Hz, ...
            row.ChannelLowEdge_Hz + row.GuardbandLow_Hz]);
        highGuardX = x([row.ChannelHighEdge_Hz - row.GuardbandHigh_Hz, ...
            row.ChannelHighEdge_Hz]);
        series = gobjects(5, 1);
        series(1) = plot(axesHandle, channelX, [5, 5], "-", ...
            "LineWidth", 12, "Color", [0.78 0.82 0.88], ...
            "DisplayName", "channel bandwidth");
        series(2) = plot(axesHandle, transmissionX, [4, 4], "-", ...
            "LineWidth", 12, "Color", [0.15 0.48 0.76], ...
            "DisplayName", "transmission grid");
        series(3) = plot(axesHandle, bwpX, [3, 3], "-", ...
            "LineWidth", 12, "Color", [0.14 0.67 0.42], ...
            "DisplayName", "active BWP");
        series(4) = plot(axesHandle, lowGuardX, [2, 2], "-", ...
            "LineWidth", 12, "Color", [0.92 0.57 0.18], ...
            "DisplayName", "minimum low guard");
        series(5) = plot(axesHandle, highGuardX, [1, 1], "-", ...
            "LineWidth", 12, "Color", [0.82 0.35 0.18], ...
            "DisplayName", "minimum high guard");
        yticks(axesHandle, 1:5);
        yticklabels(axesHandle, ["minimum high guard", ...
            "minimum low guard", "active BWP", ...
            "transmission grid", "channel"]);
        ylim(axesHandle, [0.4, 5.6]);
        legend(axesHandle, "Location", "eastoutside");
        title(axesHandle, ...
            "100 MHz FR1 carrier: channel, grid, active BWP and guardbands");
        xlabel(axesHandle, "frequency offset from carrier center (MHz)");
        ylabel(axesHandle, "frequency-domain ownership");
        sourceMatch = isequal(double(series(1).XData(:)), channelX(:)) && ...
            isequal(double(series(2).XData(:)), transmissionX(:)) && ...
            isequal(double(series(3).XData(:)), bwpX(:)) && ...
            isequal(double(series(4).XData(:)), lowGuardX(:)) && ...
            isequal(double(series(5).XData(:)), highGuardX(:));
        expectedSeries = 5;
    case "timing"
        targetY = zeros(height(source), 1);
        targetY(source.Procedure == "PDSCH") = 3;
        targetY(source.Procedure == "PUSCH") = 2;
        targetY(source.Procedure == "HARQ_ACK") = 1;
        valid = source.ActualValid == "TRUE";
        invalid = ~valid;
        [validX, validY] = localTimingSegments(source, targetY, valid);
        [invalidX, invalidY] = localTimingSegments(source, targetY, invalid);
        series = gobjects(7, 1);
        series(1) = plot(axesHandle, validX, validY, "-", ...
            "Color", [0.32 0.45 0.70], "LineWidth", 1.4, ...
            "DisplayName", "accepted timing relation");
        series(2) = plot(axesHandle, invalidX, invalidY, "--", ...
            "Color", [0.78 0.16 0.14], "LineWidth", 1.4, ...
            "DisplayName", "rejected target");
        series(3) = scatter(axesHandle, source.PDCCHAbsSlot, ...
            repmat(4, height(source), 1), 65, "^", "filled", ...
            "MarkerFaceColor", [0.22 0.22 0.26], ...
            "DisplayName", "PDCCH");
        pdsch = source.Procedure == "PDSCH" & valid;
        pusch = source.Procedure == "PUSCH" & valid;
        pucch = source.Procedure == "HARQ_ACK" & valid;
        series(4) = scatter(axesHandle, source.TargetAbsSlot(pdsch), ...
            targetY(pdsch), 80, "o", "filled", ...
            "DisplayName", "PDSCH (K0)");
        series(5) = scatter(axesHandle, source.TargetAbsSlot(pusch), ...
            targetY(pusch), 80, "s", "filled", ...
            "DisplayName", "PUSCH (K2)");
        series(6) = scatter(axesHandle, source.TargetAbsSlot(pucch), ...
            targetY(pucch), 80, "d", "filled", ...
            "DisplayName", "PUCCH/HARQ-ACK (K1)");
        series(7) = scatter(axesHandle, source.TargetAbsSlot(invalid), ...
            targetY(invalid), 110, "x", "LineWidth", 2, ...
            "MarkerEdgeColor", [0.78 0.16 0.14], ...
            "DisplayName", "invalid target");
        for index = 1:height(source)
            if source.Procedure(index) == "PDSCH"
                kLabel = "K0=" + string(source.K0(index));
            elseif source.Procedure(index) == "PUSCH"
                kLabel = "K2=" + string(source.K2(index));
            else
                kLabel = "K1=" + string(source.K1(index));
            end
            text(axesHandle, source.TargetAbsSlot(index), ...
                targetY(index) + 0.12, kLabel, ...
                "HorizontalAlignment", "center", "FontSize", 9);
        end
        yticks(axesHandle, 1:4);
        yticklabels(axesHandle, ["PUCCH / HARQ-ACK", "PUSCH", ...
            "PDSCH", "PDCCH"]);
        legend(axesHandle, "Location", "eastoutside");
        title(axesHandle, ...
            "PDCCH to PDSCH/PUSCH/PUCCH on the exact absolute-time axis");
        xlabel(axesHandle, "zero-based absolute slot");
        ylabel(axesHandle, "procedure event");
        sourceMatch = isequaln(double(series(1).XData(:)), validX(:)) && ...
            isequaln(double(series(1).YData(:)), validY(:)) && ...
            isequaln(double(series(2).XData(:)), invalidX(:)) && ...
            isequaln(double(series(2).YData(:)), invalidY(:)) && ...
            isequal(double(series(3).XData(:)), ...
                double(source.PDCCHAbsSlot(:))) && ...
            isequal(double(series(4).XData(:)), ...
                double(source.TargetAbsSlot(pdsch))) && ...
            isequal(double(series(5).XData(:)), ...
                double(source.TargetAbsSlot(pusch))) && ...
            isequal(double(series(6).XData(:)), ...
                double(source.TargetAbsSlot(pucch))) && ...
            isequal(double(series(7).XData(:)), ...
                double(source.TargetAbsSlot(invalid)));
        expectedSeries = 7;
    case "bwp"
        ids = ["UL0"; "DL0"; "DL1"];
        stateRows = source(source.EventType ~= "GRANT", :);
        dlRows = sortrows(stateRows(stateRows.Direction == "DL", :), "AbsSlot");
        ulRows = sortrows(stateRows(stateRows.Direction == "UL", :), "AbsSlot");
        dlY = localBWPCode(dlRows.ActiveBWPID, ids);
        ulY = localBWPCode(ulRows.ActiveBWPID, ids);
        commandRows = source(source.EventType == "SWITCH_COMMAND", :);
        activationRows = source(source.EventType == "SWITCH_ACTIVATION", :);
        grantRows = source(source.EventType == "GRANT", :);
        validGrant = grantRows.ActualValid == "TRUE";
        grantY = localBWPCode(grantRows.GrantBWPID, ids);
        series = gobjects(6, 1);
        series(1) = stairs(axesHandle, dlRows.AbsSlot, dlY, "o-", ...
            "LineWidth", 2.2, "DisplayName", "active DL BWP");
        series(2) = stairs(axesHandle, ulRows.AbsSlot, ulY, "s-", ...
            "LineWidth", 2.2, "DisplayName", "active UL BWP");
        series(3) = scatter(axesHandle, commandRows.AbsSlot, ...
            localBWPCode(commandRows.CommandedBWPID, ids), ...
            110, "^", "filled", "DisplayName", "switch command");
        series(4) = scatter(axesHandle, activationRows.AbsSlot, ...
            localBWPCode(activationRows.ActiveBWPID, ids), ...
            130, "p", "filled", "DisplayName", "activation");
        series(5) = scatter(axesHandle, grantRows.AbsSlot(validGrant), ...
            grantY(validGrant), 80, "o", "filled", ...
            "DisplayName", "accepted grant");
        series(6) = scatter(axesHandle, grantRows.AbsSlot(~validGrant), ...
            grantY(~validGrant), 100, "x", "LineWidth", 2, ...
            "DisplayName", "rejected inactive-BWP grant");
        commandSlot = commandRows.AbsSlot(1);
        activationSlot = activationRows.AbsSlot(1);
        plot(axesHandle, [commandSlot, activationSlot], [3.45, 3.45], ...
            "k:", "LineWidth", 1.4, "HandleVisibility", "off");
        text(axesHandle, mean([commandSlot, activationSlot]), 3.55, ...
            "configured switch delay", "HorizontalAlignment", "center");
        yticks(axesHandle, 1:numel(ids));
        yticklabels(axesHandle, ids);
        ylim(axesHandle, [0.6, 3.8]);
        legend(axesHandle, "Location", "eastoutside");
        title(axesHandle, "BWP command and activation timeline");
        xlabel(axesHandle, "zero-based absolute slot");
        ylabel(axesHandle, "BWP identity");
        sourceMatch = isequal(double(series(1).XData(:)), ...
                double(dlRows.AbsSlot(:))) && ...
            isequal(double(series(1).YData(:)), double(dlY(:))) && ...
            isequal(double(series(2).XData(:)), ...
                double(ulRows.AbsSlot(:))) && ...
            isequal(double(series(2).YData(:)), double(ulY(:))) && ...
            isequal(double(series(3).XData(:)), ...
                double(commandRows.AbsSlot(:))) && ...
            isequal(double(series(4).XData(:)), ...
                double(activationRows.AbsSlot(:))) && ...
            isequal(double(series(5).XData(:)), ...
                double(grantRows.AbsSlot(validGrant))) && ...
            isequal(double(series(6).XData(:)), ...
                double(grantRows.AbsSlot(~validGrant)));
        expectedSeries = 6;
    case "carrier_component"
        localRows = source(source.OwnershipType == "local_cc_resource", :);
        localRows = sortrows(localRows, ["ScheduledCCID", "Direction"], ...
            ["ascend", "ascend"]);
        laneLabels = ["CC1 / UL1"; "CC1 / DL1"; ...
            "CC0 / UL0"; "CC0 / DL0"];
        series = gobjects(6, 1);
        patchChecks = true(height(localRows), 3);
        for index = 1:height(localRows)
            x = [localRows.StartRB(index), ...
                localRows.StartRB(index) + localRows.NumRB(index), ...
                localRows.StartRB(index) + localRows.NumRB(index), ...
                localRows.StartRB(index)];
            y = localRows.ScheduledLane(index) + ...
                [-0.24, -0.24, 0.24, 0.24];
            c = repmat(localRows.PlotColorCode(index), size(x));
            series(index) = patch(axesHandle, x, y, c, ...
                "FaceColor", "flat", "FaceAlpha", 0.72, ...
                "DisplayName", ...
                localRows.ScheduledCCID(index) + "/" + ...
                localRows.BWPID(index) + " " + localRows.Direction(index));
            patchChecks(index, :) = [ ...
                isequal(double(series(index).XData(:)), double(x(:))), ...
                isequal(double(series(index).YData(:)), double(y(:))), ...
                isequal(double(series(index).CData(:)), double(c(:)))];
            text(axesHandle, mean(x(1:2)), ...
                localRows.ScheduledLane(index), ...
                localRows.BWPID(index) + " | HARQ " + ...
                string(localRows.HARQProcessID(index)), ...
                "HorizontalAlignment", "center", "FontWeight", "bold");
        end
        cross = source(source.OwnershipType == ...
            "cross_carrier_scheduling_link", :);
        rejected = source(source.OwnershipType == ...
            "rejected_cross_carrier_link", :);
        linkX = [cross.SchedulingStartRB(1) + ...
                cross.SchedulingNumRB(1) / 2, ...
            cross.StartRB(1) + cross.NumRB(1) / 2];
        linkY = [cross.SchedulingLane(1), cross.ScheduledLane(1)];
        series(5) = plot(axesHandle, linkX, linkY, "-o", ...
            "LineWidth", 2.2, "Color", [0.70 0.12 0.14], ...
            "DisplayName", "CC0 schedules CC1 (indicator 1)");
        rejectedX = rejected.StartRB + rejected.NumRB / 2;
        rejectedY = rejected.ScheduledLane;
        rejectedC = rejected.CarrierIndicator;
        series(6) = scatter(axesHandle, rejectedX, rejectedY, ...
            130, rejectedC, "x", "LineWidth", 2, ...
            "DisplayName", "wrong indicator rejected");
        otherChecks = [ ...
            isequal(double(series(5).XData(:)), double(linkX(:))), ...
            isequal(double(series(5).YData(:)), double(linkY(:))), ...
            isequal(double(series(6).XData(:)), double(rejectedX(:))), ...
            isequal(double(series(6).YData(:)), double(rejectedY(:))), ...
            isequal(double(series(6).CData(:)), double(rejectedC(:))), ...
            all(localTruthVector(localRows.ActualValid)), ...
            all(~localTruthVector(rejected.ActualValid)), ...
            numel(unique(localRows.MeasurementNamespace)) == 2];
        sourceMatch = all(patchChecks, "all") && all(otherChecks);
        sourceDetail = "patch_x_y_c=" + ...
            strjoin(string(reshape(double(patchChecks).', 1, [])), "") + ...
            ";link_scatter_valid_namespace=" + ...
            strjoin(string(double(otherChecks)), "");
        colormap(axesHandle, parula(4));
        clim(axesHandle, [0.5, 4.5]);
        yticks(axesHandle, 1:4);
        yticklabels(axesHandle, laneLabels);
        ylim(axesHandle, [0.5, 4.5]);
        legend(axesHandle, "Location", "eastoutside");
        title(axesHandle, ...
            "Per-CC/BWP resource ownership and cross-carrier scheduling");
        xlabel(axesHandle, "zero-based resource-block index");
        ylabel(axesHandle, "component carrier / BWP");
        expectedSeries = 6;
    case "ssb"
        x = source.StartSymbol;
        y = source.CandidateIndex;
        rangeCode = zeros(height(source), 1);
        rangeCode(source.FrequencyRange == "FR1") = 1;
        rangeCode(source.FrequencyRange == "FR2-1") = 2;
        rangeCode(source.FrequencyRange == "FR2-2") = 3;
        series = scatter(axesHandle, x, y, 22, rangeCode, "filled");
        colorbar(axesHandle, "Ticks", 1:3, ...
            "TickLabels", ["FR1", "FR2-1", "FR2-2"]);
        title(axesHandle, "SS/PBCH candidate timing by Case A-G");
        xlabel(axesHandle, "zero-based start symbol in half-frame");
        ylabel(axesHandle, "zero-based SSB candidate index");
        sourceMatch = isequal(double(series.XData(:)), double(x(:))) && ...
            isequal(double(series.YData(:)), double(y(:))) && ...
            isequal(double(series.CData(:)), double(rangeCode(:))) && ...
            numel(unique(source.Case)) == 7;
        expectedSeries = 1;
    case "prach"
        [x, order] = sort(source.AbsoluteSlot);
        y = source.StartSymbol(order);
        series = scatter(axesHandle, x, y, 28, ...
            source.FrequencyIndex(order), "filled");
        colorbar(axesHandle);
        title(axesHandle, "PRACH occasions in exact repetition periods");
        xlabel(axesHandle, "zero-based absolute carrier slot");
        ylabel(axesHandle, "zero-based PRACH start symbol");
        sourceMatch = isequal(double(series.XData(:)), double(x(:))) && ...
            isequal(double(series.YData(:)), double(y(:)));
        expectedSeries = 1;
    otherwise
        error("sixgr:phy:frame:UnknownArtifactFigure", ...
            "Unknown artifact figure kind '%s'.", kind);
end
hold(axesHandle, "off");
axesCount = numel(findall(fig, "Type", "axes"));
seriesCount = nnz(isgraphics(series));
labelsPresent = strlength(string(axesHandle.Title.String)) > 0 && ...
    strlength(string(axesHandle.XLabel.String)) > 0 && ...
    strlength(string(axesHandle.YLabel.String)) > 0;
finiteSeries = localFiniteGraphicsData(series);
pass = axesCount == 1 && seriesCount == expectedSeries && labelsPresent && ...
    finiteSeries && sourceMatch;
if ~pass
    error("sixgr:phy:frame:ArtifactFigureSemanticMismatch", ...
        "Semantic verification failed for '%s' " + ...
        "(axes=%d/1, series=%d/%d, labels=%d, finite=%d, source=%d; %s).", ...
        kind, axesCount, seriesCount, expectedSeries, labelsPresent, ...
        finiteSeries, sourceMatch, sourceDetail);
end
semantic = struct("ExpectedAxes", 1, "ObservedAxes", axesCount, ...
    "ExpectedSeries", expectedSeries, "ObservedSeries", seriesCount, ...
    "Pass", pass);
end

function code = localDirectionCode(token)
token = upper(strtrim(string(token)));
if any(token == ["D", "DL"])
    code = 1;
elseif any(token == ["U", "UL"])
    code = -1;
elseif any(token == ["F", "UNRESOLVED_FLEX", "GUARD", "UNUSED"])
    code = 0;
else
    error("sixgr:phy:frame:UnknownDirectionToken", ...
        "Unknown direction token '%s' in figure source.", token);
end
end

function [x, y] = localTimingSegments(source, targetY, mask)
indices = find(mask);
x = nan(3 * numel(indices), 1);
y = nan(3 * numel(indices), 1);
for index = 1:numel(indices)
    row = indices(index);
    positions = (3 * index - 2):(3 * index);
    x(positions) = [source.PDCCHAbsSlot(row); ...
        source.TargetAbsSlot(row); NaN];
    y(positions) = [4; targetY(row); NaN];
end
end

function code = localBWPCode(ids, orderedIDs)
ids = string(ids);
code = nan(size(ids));
for index = 1:numel(orderedIDs)
    code(ids == orderedIDs(index)) = index;
end
if any(~isfinite(code))
    error("sixgr:phy:frame:UnknownBWPInFigure", ...
        "BWP timeline contains an identity absent from its ordered lanes.");
end
end

function lane = localCarrierLane(ccid, direction)
ccid = string(ccid);
direction = upper(string(direction));
if ccid == "CC0" && direction == "DL"
    lane = 4;
elseif ccid == "CC0" && direction == "UL"
    lane = 3;
elseif ccid == "CC1" && direction == "DL"
    lane = 2;
elseif ccid == "CC1" && direction == "UL"
    lane = 1;
else
    error("sixgr:phy:frame:UnknownCarrierLane", ...
        "No component-carrier figure lane exists for %s/%s.", ...
        ccid, direction);
end
end

function tf = localFiniteGraphicsData(series)
tf = true;
for index = 1:numel(series)
    handle = series(index);
    hasFiniteData = false;
    if isprop(handle, "CData") && ~isempty(handle.CData)
        values = double(handle.CData);
        hasFiniteData = hasFiniteData || any(isfinite(values(:)));
    end
    if isprop(handle, "XData") && ~isempty(handle.XData)
        values = double(handle.XData);
        hasFiniteData = hasFiniteData || any(isfinite(values(:)));
    end
    if isprop(handle, "YData") && ~isempty(handle.YData)
        values = double(handle.YData);
        hasFiniteData = hasFiniteData || any(isfinite(values(:)));
    end
    tf = tf && hasFiniteData;
end
end

function row = localEmptyImageAuditRow()
row = struct( ...
    "ImageFile", "", "SourceCSV", "", "SourceCSV_SHA256", "", ...
    "ImageSHA256", "", "Width", NaN, "Height", NaN, "Mode", "", ...
    "FileBytes", NaN, "NonBlankFraction", NaN, "PixelStdDev", NaN, ...
    "ExpectedAxes", NaN, "ObservedAxes", NaN, ...
    "ExpectedSeries", NaN, "ObservedSeries", NaN, ...
    "Status", "FAIL", "Reason", "");
end

function reason = localImageReason(semanticPass, binaryPass)
if semanticPass && binaryPass
    reason = "semantic_source_values_and_binary_checks_pass";
elseif ~semanticPass
    reason = "semantic_source_value_check_failed";
else
    reason = "binary_png_check_failed";
end
end

function output = localNormalizeTestSummary(input)
required = ["Suite","TestsRun","Passed","Failed","Skipped", ...
    "Blocked","Status","ResultFile"];
if ~all(ismember(required, string(input.Properties.VariableNames)))
    error("sixgr:phy:frame:InvalidFrameGridTestSummary", ...
        "TestSummary lacks one or more required columns: %s.", ...
        strjoin(required, ", "));
end
output = input(:, cellstr(required));
output.Suite = string(output.Suite);
output.Status = upper(string(output.Status));
output.ResultFile = string(output.ResultFile);
valid = output.TestsRun > 0 & output.Passed == output.TestsRun & ...
    output.Failed == 0 & output.Skipped == 0 & output.Blocked == 0 & ...
    output.Status == "PASS";
output.Status(~valid) = "FAIL";
end

function tableOut = localWithIndexConvention(tableIn)
tableOut = tableIn;
if ~ismember("IndexConvention", string(tableOut.Properties.VariableNames))
    tableOut.IndexConvention = repmat( ...
        "zero_based_phy_indices", height(tableOut), 1);
end
end

function tf = localAllStatusPass(tables)
tf = true;
names = fieldnames(tables);
for index = 1:numel(names)
    value = tables.(names{index});
    if istable(value) && ismember("Status", ...
            string(value.Properties.VariableNames))
        tf = tf && ~isempty(value) && all(upper(string(value.Status)) == "PASS");
    end
end
end

function value = localSHA256(path)
fid = fopen(path, "rb");
if fid < 0
    error("sixgr:phy:frame:ArtifactHashReadFailure", ...
        "Cannot open artifact for SHA-256: %s", path);
end
cleanup = onCleanup(@() fclose(fid));
bytes = fread(fid, Inf, "*uint8");
digest = javaMethod("getInstance", ...
    "java.security.MessageDigest", "SHA-256");
digest.update(bytes);
signed = digest.digest();
hex = dec2hex(mod(double(signed), 256), 2).';
value = lower(string(hex(:).'));
clear cleanup;
end

function directory = localVectorDirectory()
directory = fullfile(localRepositoryRoot(), "tests", "vectors", "frame_grid");
if ~isfolder(directory)
    error("sixgr:phy:frame:FrameGridVectorsMissing", ...
        "Mandatory frame/grid vector directory is missing: %s", directory);
end
end

function root = localRepositoryRoot()
root = fileparts(mfilename("fullpath"));
root = fileparts(root);
root = fileparts(root);
root = fileparts(root);
end

function text = localBoolText(value)
if logical(value)
    text = "TRUE";
else
    text = "FALSE";
end
end

function text = localBoolTextVector(values)
values = logical(values);
text = repmat("FALSE", size(values));
text(values) = "TRUE";
end

function text = localPassText(value)
if logical(value)
    text = "PASS";
else
    text = "FAIL";
end
end

function tf = localTruth(value)
if islogical(value)
    tf = logical(value);
elseif isnumeric(value)
    tf = logical(value ~= 0);
else
    tf = any(strcmpi(strtrim(string(value)), ["true","1","yes"]));
end
end

function values = localTruthVector(input)
if islogical(input)
    values = logical(input);
elseif isnumeric(input)
    values = input ~= 0;
else
    values = ismember(lower(strtrim(string(input))), ...
        ["true", "1", "yes"]);
end
values = values(:);
end

function tf = localTextScalar(value)
tf = ischar(value) || (isstring(value) && isscalar(value));
end

function localAssertRowCounts(testID, expected, varargin)
rows = cellfun(@(value) size(value, 1), varargin);
if any(rows ~= expected)
    error("sixgr:phy:frame:ArtifactTableRowMismatch", ...
        "%s expected %d rows but observed %s.", ...
        testID, expected, mat2str(rows));
end
end
