classdef FDDCarrierContexts
    %FDDCARRIERCONTEXTS Separate, time-aligned DL and UL FDD grids.

    properties (SetAccess = private)
        DuplexMode (1,1) string = "FDD"
        Downlink struct
        Uplink struct
        SlotsPerFrame (1,1) double
        SymbolsPerSlot (1,1) double
        IndexConvention (1,1) string = "zero_based"
    end

    methods (Static)
        function obj = create(varargin)
            p = inputParser;
            addParameter(p, "CellID", 0);
            addParameter(p, "DLCCID", 0);
            addParameter(p, "ULCCID", 0);
            addParameter(p, "DLBWPID", 0);
            addParameter(p, "ULBWPID", 0);
            addParameter(p, "DLCenterFrequencyHz", []);
            addParameter(p, "ULCenterFrequencyHz", []);
            addParameter(p, "SubcarrierSpacingKHz", 15);
            addParameter(p, "DLNumRB", []);
            addParameter(p, "ULNumRB", []);
            addParameter(p, "CyclicPrefix", "normal");
            addParameter(p, "ULTimingAdvanceSamples", 0);
            parse(p, varargin{:});

            scs = double(p.Results.SubcarrierSpacingKHz);
            cp = lower(string(p.Results.CyclicPrefix));
            dlFc = double(p.Results.DLCenterFrequencyHz);
            ulFc = double(p.Results.ULCenterFrequencyHz);
            if ~(isscalar(dlFc) && isfinite(dlFc) && dlFc > 0 && ...
                    isscalar(ulFc) && isfinite(ulFc) && ulFc > 0)
                error("sixgr:phy:frame:FDDRequiresSeparateFrequencies", ...
                    "FDD requires explicit positive DL and UL center frequencies.");
            end
            if dlFc == ulFc
                error("sixgr:phy:frame:FDDRequiresSeparateFrequencies", ...
                    "FDD DL and UL center frequencies must be distinct.");
            end
            dlRange = sixgr.phy.frame.FrequencyRangeResolver.resolve( ...
                "CenterFrequencyHz", dlFc);
            ulRange = sixgr.phy.frame.FrequencyRangeResolver.resolve( ...
                "CenterFrequencyHz", ulFc);
            dlNumerology = sixgr.phy.frame.NumerologyCatalog.resolve( ...
                scs, cp, "dl_bwp", dlRange.FrequencyRange);
            ulNumerology = sixgr.phy.frame.NumerologyCatalog.resolve( ...
                scs, cp, "ul_bwp", ulRange.FrequencyRange);
            if dlNumerology.SymbolsPerSlot ~= ulNumerology.SymbolsPerSlot || ...
                    dlNumerology.SlotsPerFrame ~= ulNumerology.SlotsPerFrame
                error("sixgr:phy:frame:FDDTimingContextMismatch", ...
                    "FDD DL and UL numerologies must share an exact frame timeline.");
            end
            symbols = double(dlNumerology.SymbolsPerSlot);
            dlRB = double(p.Results.DLNumRB);
            ulRB = double(p.Results.ULNumRB);
            validateattributes(dlRB, {'numeric'}, ...
                {'scalar','integer','positive','finite'});
            validateattributes(ulRB, {'numeric'}, ...
                {'scalar','integer','positive','finite'});
            ta = double(p.Results.ULTimingAdvanceSamples);
            validateattributes(ta, {'numeric'}, ...
                {'scalar','integer','nonnegative','finite'});

            cellID = double(p.Results.CellID);
            dlGridID = "cell" + string(cellID) + "_cc" + ...
                string(p.Results.DLCCID) + "_dl_grid";
            ulGridID = "cell" + string(cellID) + "_cc" + ...
                string(p.Results.ULCCID) + "_ul_grid";
            obj = sixgr.phy.frame.FDDCarrierContexts;
            obj.SlotsPerFrame = double(dlNumerology.SlotsPerFrame);
            obj.SymbolsPerSlot = symbols;
            obj.Downlink = struct( ...
                "Direction", "DL", ...
                "GridID", dlGridID, ...
                "CellID", cellID, ...
                "CCID", double(p.Results.DLCCID), ...
                "BWPID", double(p.Results.DLBWPID), ...
                "CenterFrequencyHz", dlFc, ...
                "FrequencyRange", string(dlRange.FrequencyRange), ...
                "SubcarrierSpacingKHz", scs, ...
                "Mu", double(dlNumerology.Mu), ...
                "CyclicPrefix", string(dlNumerology.CyclicPrefix), ...
                "NumRB", dlRB, ...
                "SymbolsPerSlot", symbols, ...
                "SlotsPerFrame", obj.SlotsPerFrame, ...
                "TimingAdvanceSamples", 0);
            obj.Uplink = struct( ...
                "Direction", "UL", ...
                "GridID", ulGridID, ...
                "CellID", cellID, ...
                "CCID", double(p.Results.ULCCID), ...
                "BWPID", double(p.Results.ULBWPID), ...
                "CenterFrequencyHz", ulFc, ...
                "FrequencyRange", string(ulRange.FrequencyRange), ...
                "SubcarrierSpacingKHz", scs, ...
                "Mu", double(ulNumerology.Mu), ...
                "CyclicPrefix", string(ulNumerology.CyclicPrefix), ...
                "NumRB", ulRB, ...
                "SymbolsPerSlot", symbols, ...
                "SlotsPerFrame", obj.SlotsPerFrame, ...
                "TimingAdvanceSamples", ta);
        end
    end

    methods
        function tf = isAvailable(obj, time, direction, context)
            %ISAVAILABLE Availability always requires an explicit link context.
            validateattributes(time, {'numeric'}, {'scalar','finite','nonnegative'});
            direction = upper(string(direction));
            if direction == "DL"
                expected = obj.Downlink;
            elseif direction == "UL"
                expected = obj.Uplink;
            else
                error("sixgr:phy:frame:DirectionRequiredForFDD", ...
                    "FDD availability direction must be DL or UL.");
            end
            if nargin < 4 || isempty(context) || ~isstruct(context) || ...
                    ~isfield(context, "GridID") || ...
                    string(context.GridID) ~= string(expected.GridID)
                error("sixgr:phy:frame:FDDGridContextMismatch", ...
                    "FDD %s availability requires its explicit grid context.", direction);
            end
            tf = true;
        end

        function grid = createGrid(obj, direction, numSlots, numPorts)
            if nargin < 3
                numSlots = 1;
            end
            if nargin < 4
                numPorts = 1;
            end
            context = obj.context(direction);
            validateattributes(numSlots, {'numeric'}, ...
                {'scalar','integer','positive','finite'});
            validateattributes(numPorts, {'numeric'}, ...
                {'scalar','integer','positive','finite'});
            grid = complex(zeros(12 * context.NumRB, ...
                obj.SymbolsPerSlot * numSlots, numPorts));
        end

        function context = context(obj, direction)
            direction = upper(string(direction));
            if direction == "DL"
                context = obj.Downlink;
            elseif direction == "UL"
                context = obj.Uplink;
            else
                error("sixgr:phy:frame:DirectionRequiredForFDD", ...
                    "Direction must be DL or UL.");
            end
        end

        function key = resourceKey(obj, direction, absoluteSlot, ...
                symbol, rb, subcarrier, port)
            context = obj.context(direction);
            validateattributes(absoluteSlot, {'numeric'}, ...
                {'scalar','integer','nonnegative','finite'});
            validateattributes(symbol, {'numeric'}, ...
                {'scalar','integer','>=',0,'<',obj.SymbolsPerSlot});
            validateattributes(rb, {'numeric'}, ...
                {'scalar','integer','>=',0,'<',context.NumRB});
            validateattributes(subcarrier, {'numeric'}, ...
                {'scalar','integer','>=',0,'<',12});
            validateattributes(port, {'numeric'}, ...
                {'scalar','integer','nonnegative','finite'});
            key = sprintf("%s|slot=%d|sym=%d|rb=%d|sc=%d|port=%d", ...
                context.GridID, absoluteSlot, symbol, rb, subcarrier, port);
        end

        function result = applyUplinkTimingAdvance(obj, waveform)
            %APPLYUPLINKTIMINGADVANCE Place the UL waveform at its FDD time.
            result = sixgr.phy.frame.applyULTimingAdvance(waveform, obj);
        end

        function token = TDDToken(~, varargin) %#ok<INUSD>
            error("sixgr:phy:frame:FDDHasNoTDDToken", ...
                "FDD has separate DL/UL grids and no D/U/F TDD slot token.");
            token = ''; %#ok<UNRCH>
        end
    end

    methods (Access = private)
        function obj = FDDCarrierContexts
        end
    end
end
