function reference = receivedDLTimingReference(cfg, recovered, observation, filterDelaySamples)
% Received SS/PBCH timing, calibrated only for implementation filter delay.
% No TX waveform, geometry, true path delay, or configured SSB index is used.
assert(recovered.BCHCrcPass && recovered.MIBDecoded, ...
    'sixgr:phy:frame:UndecodedDLTiming','A CRC-valid received BCH is required.');
assert(observation.isComplete(),'WAVEFORM:IncompleteObservation','Complete the actual SSB capture first.');
fs = observation.SampleRateHz;
validateattributes(filterDelaySamples,{'numeric'},{'scalar','integer','nonnegative','finite'});
validateattributes(recovered.TimingOffset,{'numeric'},{'scalar','integer','nonnegative','finite'});
validateattributes(recovered.MIBSystemFrameNumber,{'numeric'},{'scalar','integer','>=',0,'<=',1023});
assert(recovered.SampleRateHz==fs && recovered.SSBIndex==recovered.MIBSSBIndex, ...
    'sixgr:phy:frame:InconsistentReceivedSSBTiming','BCH index and observation clocks disagree.');
timing = sixgr.phy.frame.SSBTimingResolver.resolveFromConfig(cfg, ...
    'SSBIndex',recovered.MIBSSBIndex,'HalfFrameIndex',recovered.MIBHalfFrameBit);
symbol = timing.SelectedStartSymbol;
position = sixgr.phy.frame.AbsoluteTime.fromAbsoluteSlotSymbol( ...
    floor(symbol/14),mod(symbol,14),timing.Mu);
ticksPerSample = double(sixgr.phy.frame.AbsoluteTime.TicksPerSecond)/fs;
assert(ticksPerSample==fix(ticksPerSample) && rem(position.Ticks,int64(ticksPerSample))==0, ...
    'sixgr:phy:frame:DLReferenceOffSampleClock','SSB timing must lie on the actual sample clock.');
withinFrame = double(position.Ticks)/ticksPerSample;
frameSamples = double(sixgr.phy.frame.AbsoluteTime.TicksPerFrame)/ticksPerSample;
frameOrigin = observation.StartSample + recovered.TimingOffset - filterDelaySamples - withinFrame;
% The shared lab clock supplies an unwrapped epoch, not a radio phase.
% The measured phase must lie inside the declared receiver search budget.
frameNumber = round(frameOrigin/frameSamples);
phase = frameOrigin - frameNumber*frameSamples;
[guard,guardSource] = sixgr.phy.sync.resolveTimingSearchGuard(cfg,fs);
assert(abs(phase)<=guard && 2*guard<frameSamples, ...
    'sixgr:phy:frame:UnresolvedDLReferenceEpoch','Received timing is outside the declared unambiguous search window.');
reference = struct('Source',"received_SSB_timing_and_decoded_BCH", ...
    'SampleRateHz',fs,'ObservationStartSample',observation.StartSample, ...
    'AvailableAtSample',observation.EndSampleExclusive, ...
    'RawSSBTiming_samples',recovered.TimingOffset,'ImplementationFilterDelay_samples',filterDelaySamples, ...
    'SSBIndex',recovered.MIBSSBIndex,'NCellID',recovered.NCellID, ...
    'ReceivedSFN',recovered.MIBSystemFrameNumber,'ReceivedHalfFrame',recovered.MIBHalfFrameBit, ...
    'AbsoluteFrameNumber',frameNumber,'ReceivedFrameOriginSample',frameOrigin, ...
    'DLPhaseOffsetSamples',phase,'SearchGuardSamples',guard,'SearchGuardSource',guardSource, ...
    'TimingEstimator',"practical_received_PSS_synchronizer_not_true_path_delay", ...
    'WaveformTimingApplied',false);
end
