classdef SSBTimingResolver
    %SSBTIMINGRESOLVER Canonical Release-18 SS/PBCH timing resolution.
    %
    % All symbols and candidate indices returned by this resolver are
    % zero-based. The case must be explicit; this class never guesses an SSB
    % case solely from a carrier-frequency threshold.

    methods (Static)
        function result = resolve(varargin)
            p = inputParser;
            p.FunctionName = "sixgr.phy.frame.SSBTimingResolver.resolve";
            addParameter(p, "Case", "", @localTextScalar);
            addParameter(p, "CarrierFrequencyHz", NaN, @localFiniteOrNaN);
            addParameter(p, "FrequencyRange", "", @localTextScalar);
            addParameter(p, "SSBSubcarrierSpacingKHz", NaN, @localFiniteOrNaN);
            addParameter(p, "CarrierSubcarrierSpacingKHz", NaN, @localFiniteOrNaN);
            addParameter(p, "Lmax", NaN, @localFiniteOrNaN);
            addParameter(p, "HalfFrameIndex", 0, @localNonnegativeInteger);
            addParameter(p, "PeriodicityMs", 20, @localPositiveFinite);
            addParameter(p, "SSBIndex", 0, @localNonnegativeInteger);
            addParameter(p, "NStartGrid", 0, @localNonnegativeInteger);
            addParameter(p, "NSizeGrid", NaN, @localFiniteOrNaN);
            addParameter(p, "NStartBWP", NaN, @localFiniteOrNaN);
            addParameter(p, "NSizeBWP", NaN, @localFiniteOrNaN);
            addParameter(p, "NCRBSSB", NaN, @localFiniteOrNaN);
            addParameter(p, "KSSB", NaN, @localFiniteOrNaN);
            parse(p, varargin{:});
            opt = p.Results;

            caseLetter = localCaseLetter(opt.Case);
            caseNumber = find(caseLetter == ...
                ["A", "B", "C", "D", "E", "F", "G"], 1);
            caseSCS = [15, 30, 30, 120, 240, 480, 960];
            ssbSCS = caseSCS(caseNumber);
            if isfinite(double(opt.SSBSubcarrierSpacingKHz)) && ...
                    double(opt.SSBSubcarrierSpacingKHz) ~= ssbSCS
                error("sixgr:phy:frame:SSBCaseSCSMismatch", ...
                    "Case %s requires SSB SCS %g kHz; configured value is %g kHz.", ...
                    caseLetter, ssbSCS, double(opt.SSBSubcarrierSpacingKHz));
            end

            frequencyRange = localFrequencyRange( ...
                string(opt.FrequencyRange), double(opt.CarrierFrequencyHz));
            localValidateCaseRange(caseLetter, frequencyRange);
            lmax = localResolveLmax(caseLetter, double(opt.Lmax), ...
                double(opt.CarrierFrequencyHz));
            if double(opt.SSBIndex) >= lmax
                error("sixgr:phy:frame:SSBIndexOutOfRange", ...
                    "SSBIndex=%d must be in [0,%d] for Case %s.", ...
                    double(opt.SSBIndex), lmax - 1, caseLetter);
            end

            periodicity = double(opt.PeriodicityMs);
            allowedPeriods = [5, 10, 20, 40, 80, 160];
            if ~any(abs(periodicity - allowedPeriods) <= 1e-12)
                error("sixgr:phy:frame:UnsupportedSSBPeriodicity", ...
                    "SSB periodicity must be one of %s ms; configured value is %g ms.", ...
                    mat2str(allowedPeriods), periodicity);
            end

            startSymbols = localCandidateSymbols(caseNumber, lmax);
            candidateIndices = 0:(lmax - 1);
            candidateSlots = floor(startSymbols ./ 14);
            candidateSymbolsInSlot = mod(startSymbols, 14);
            mu = localMuFromSCS(ssbSCS);
            symbolsPerHalfFrame = 5 * (2 ^ mu) * 14;
            halfFrameIndex = double(opt.HalfFrameIndex);
            absoluteStartSymbols = startSymbols + ...
                halfFrameIndex * symbolsPerHalfFrame;

            grid = localGridRelationship(opt, ssbSCS);
            result = struct( ...
                "ContractVersion", "sixgr_ssb_timing_release18/v1", ...
                "Standard", "3GPP TS 38.213 V18.8.0 clause 4.1", ...
                "IndexConvention", "zero_based_phy_indices", ...
                "Case", caseLetter, ...
                "BlockPattern", "Case " + caseLetter, ...
                "FrequencyRange", frequencyRange, ...
                "CarrierFrequencyHz", double(opt.CarrierFrequencyHz), ...
                "SSBSubcarrierSpacingKHz", double(ssbSCS), ...
                "CarrierSubcarrierSpacingKHz", ...
                    double(opt.CarrierSubcarrierSpacingKHz), ...
                "Mu", double(mu), ...
                "SymbolsPerSlot", 14, ...
                "Lmax", double(lmax), ...
                "CandidateIndices", double(candidateIndices), ...
                "CandidateStartSymbolsWithinHalfFrame", double(startSymbols), ...
                "CandidateStartSymbols", double(absoluteStartSymbols), ...
                "CandidateSlotsWithinHalfFrame", double(candidateSlots), ...
                "CandidateSymbolsWithinSlot", ...
                    double(candidateSymbolsInSlot), ...
                "HalfFrameIndex", halfFrameIndex, ...
                "HalfFrameDurationMs", 5, ...
                "PeriodicityMs", periodicity, ...
                "SelectedSSBIndex", double(opt.SSBIndex), ...
                "SelectedStartSymbol", ...
                    double(absoluteStartSymbols(double(opt.SSBIndex) + 1)), ...
                "GridRelationship", grid, ...
                "ToolboxCaseSupported", localToolboxSupportsCase(caseLetter), ...
                "ResolvedValid", true);
        end

        function result = resolveFromConfig(cfg, varargin)
            if ~(isstruct(cfg) || isobject(cfg))
                error("sixgr:phy:frame:InvalidSSBConfig", ...
                    "SSB timing configuration must be a struct or object.");
            end
            args = { ...
                "Case", sixgr.util.structGet(cfg, "phy.ssb.blockPattern", ...
                    sixgr.util.structGet(cfg, "phy.ssb.case", "")), ...
                "CarrierFrequencyHz", sixgr.util.structGet(cfg, ...
                    "phy.carrier.centerFrequency_Hz", ...
                    sixgr.util.structGet(cfg, "channel.fc_Hz", NaN)), ...
                "FrequencyRange", sixgr.util.structGet(cfg, ...
                    "phy.frequencyRange", ...
                    sixgr.util.structGet(cfg, "frequency.range_name", "")), ...
                "SSBSubcarrierSpacingKHz", sixgr.util.structGet(cfg, ...
                    "phy.ssb.scs_kHz", NaN), ...
                "CarrierSubcarrierSpacingKHz", sixgr.util.structGet(cfg, ...
                    "phy.carrier.SubcarrierSpacing_kHz", ...
                    sixgr.util.structGet(cfg, ...
                    "phy.carrier.SubcarrierSpacing", NaN)), ...
                "Lmax", sixgr.util.structGet(cfg, "phy.ssb.Lmax", NaN), ...
                "PeriodicityMs", sixgr.util.structGet(cfg, ...
                    "phy.ssb.periodicity_ms", ...
                    sixgr.util.structGet(cfg, "phy.ssb.period_ms", 20)), ...
                "NStartGrid", sixgr.util.structGet(cfg, ...
                    "phy.carrier.NStartGrid", 0), ...
                "NSizeGrid", sixgr.util.structGet(cfg, ...
                    "phy.carrier.NSizeGrid", NaN), ...
                "NStartBWP", sixgr.util.structGet(cfg, ...
                    "phy.bwp.dl.NStartBWP", NaN), ...
                "NSizeBWP", sixgr.util.structGet(cfg, ...
                    "phy.bwp.dl.NSizeBWP", NaN), ...
                "NCRBSSB", sixgr.util.structGet(cfg, ...
                    "phy.ssb.NCRBSSB", NaN), ...
                "KSSB", sixgr.util.structGet(cfg, "phy.ssb.KSSB", NaN)};
            result = sixgr.phy.frame.SSBTimingResolver.resolve( ...
                args{:}, varargin{:});
        end
    end
end

function value = localCaseLetter(raw)
value = upper(strtrim(string(raw)));
if ~isscalar(value) || strlength(value) == 0
    error("sixgr:phy:frame:MissingSSBCase", ...
        "An explicit SSB case A through G is required.");
end
value = erase(value, "CASE");
value = strtrim(value);
if ~any(value == ["A", "B", "C", "D", "E", "F", "G"])
    error("sixgr:phy:frame:UnsupportedSSBCase", ...
        "Unsupported SSB case '%s'; expected Case A through Case G.", ...
        string(raw));
end
end

function range = localFrequencyRange(configured, carrierFrequencyHz)
configured = upper(strtrim(string(configured)));
if configured == "FR2"
    if isfinite(carrierFrequencyHz) && carrierFrequencyHz >= 52.6e9
        configured = "FR2-2";
    else
        configured = "FR2-1";
    end
end
args = {};
if isscalar(carrierFrequencyHz) && isfinite(carrierFrequencyHz)
    args = [args, {"CenterFrequencyHz", carrierFrequencyHz}]; %#ok<AGROW>
end
if strlength(configured) > 0
    args = [args, {"FrequencyRange", configured}]; %#ok<AGROW>
end
if isempty(args)
    error("sixgr:phy:frame:MissingFrequencyRange", ...
        "SSB timing requires FrequencyRange or a positive carrier frequency.");
end
try
    resolved = sixgr.phy.frame.FrequencyRangeResolver.resolve(args{:});
    range = string(resolved.FrequencyRange);
catch cause
    if string(cause.identifier) == "sixgr:phy:frame:InvalidFrequencyRange"
        error("sixgr:phy:frame:UnsupportedFrequencyRange", ...
            "FrequencyRange must be FR1, FR2-1, or FR2-2, not '%s'.", ...
            configured);
    end
    rethrow(cause);
end
if ~any(range == ["FR1", "FR2-1", "FR2-2"])
    error("sixgr:phy:frame:UnsupportedFrequencyRange", ...
        "Unsupported resolved SSB frequency range '%s'.", range);
end
end

function localValidateCaseRange(caseLetter, range)
if any(caseLetter == ["A", "B", "C"]) && range ~= "FR1"
    error("sixgr:phy:frame:SSBCaseFrequencyRangeMismatch", ...
        "Case %s is an FR1 SSB pattern, not %s.", caseLetter, range);
elseif any(caseLetter == ["D", "E"]) && range ~= "FR2-1"
    error("sixgr:phy:frame:SSBCaseFrequencyRangeMismatch", ...
        "Case %s is an FR2-1 SSB pattern, not %s.", caseLetter, range);
elseif any(caseLetter == ["F", "G"]) && range ~= "FR2-2"
    error("sixgr:phy:frame:SSBCaseFrequencyRangeMismatch", ...
        "Case %s is an FR2-2 SSB pattern, not %s.", caseLetter, range);
end
end

function lmax = localResolveLmax(caseLetter, configured, carrierFrequencyHz)
if any(caseLetter == ["D", "E", "F", "G"])
    expected = 64;
else
    if isfinite(carrierFrequencyHz)
        if carrierFrequencyHz <= 3e9
            expected = 4;
        else
            expected = 8;
        end
    elseif isfinite(configured)
        expected = configured;
    else
        error("sixgr:phy:frame:MissingSSBLmaxBasis", ...
            "Cases A-C require CarrierFrequencyHz or explicit Lmax.");
    end
end
if isfinite(configured) && configured ~= expected
    error("sixgr:phy:frame:SSBLmaxMismatch", ...
        "Configured Lmax=%g does not match required Lmax=%g for Case %s.", ...
        configured, expected, caseLetter);
end
if ~any(expected == [4, 8, 64])
    error("sixgr:phy:frame:InvalidSSBLmax", ...
        "Lmax must resolve to 4, 8, or 64.");
end
lmax = expected;
end

function symbols = localCandidateSymbols(caseNumber, lmax)
m = [14, 28, 14, 28, 56, 14, 14];
i = { ...
    [2; 8], ...
    [4; 8; 16; 20], ...
    [2; 8], ...
    [4; 8; 16; 20], ...
    [8; 12; 16; 20; 32; 36; 40; 44], ...
    [2; 9], ...
    [2; 9]};
nAll = [0:3, 5:8, 10:13, 15:18]; %#ok<NBRAK>
if caseNumber <= 3
    count = lmax / numel(i{caseNumber});
    n = nAll(1:count);
elseif caseNumber == 4
    n = nAll(1:16);
elseif caseNumber == 5
    n = nAll(1:8);
else
    n = 0:31;
end
symbols = reshape(i{caseNumber} + m(caseNumber) .* n, 1, []);
if numel(symbols) ~= lmax
    error("sixgr:phy:frame:SSBCandidateCountMismatch", ...
        "Case candidate construction returned %d symbols for Lmax=%d.", ...
        numel(symbols), lmax);
end
end

function mu = localMuFromSCS(scsKHz)
supported = [15, 30, 60, 120, 240, 480, 960];
mu = find(supported == scsKHz, 1) - 1;
if isempty(mu)
    error("sixgr:phy:frame:UnsupportedSubcarrierSpacing", ...
        "Unsupported SSB subcarrier spacing %g kHz.", scsKHz);
end
end

function grid = localGridRelationship(opt, ssbSCS)
nStartGrid = double(opt.NStartGrid);
nSizeGrid = double(opt.NSizeGrid);
nStartBWP = double(opt.NStartBWP);
nSizeBWP = double(opt.NSizeBWP);
ncrb = double(opt.NCRBSSB);
kssb = double(opt.KSSB);
carrierSCS = double(opt.CarrierSubcarrierSpacingKHz);
if ~(nStartGrid == fix(nStartGrid) && nStartGrid >= 0)
    error("sixgr:phy:frame:InvalidCarrierGrid", ...
        "NStartGrid must be a nonnegative integer.");
end
if isfinite(nSizeGrid) && ...
        (nSizeGrid < 1 || nSizeGrid ~= fix(nSizeGrid))
    error("sixgr:phy:frame:InvalidCarrierGrid", ...
        "NSizeGrid must be a positive integer when supplied.");
end
if isfinite(nSizeGrid) && ...
        ~(isfinite(carrierSCS) && carrierSCS > 0)
    error("sixgr:phy:frame:MissingCarrierGridSCS", ...
        "CarrierSubcarrierSpacingKHz is required when NSizeGrid is supplied.");
end
if any(ssbSCS == [15, 30])
    referenceSCS = 15;
    maxKSSB = 23;
else
    referenceSCS = 60;
    maxKSSB = 11;
end
carrierLowHz = NaN;
carrierHighHz = NaN;
if isfinite(nSizeGrid)
    carrierLowHz = nStartGrid * 12 * carrierSCS * 1e3;
    carrierHighHz = ...
        (nStartGrid + nSizeGrid) * 12 * carrierSCS * 1e3;
end
placementSource = "explicit_point_a_offset";
if ~isfinite(ncrb) && ~isfinite(kssb)
    if isfinite(nSizeGrid)
        referenceHz = referenceSCS * 1e3;
        centeredLowUnits = ((carrierLowHz + carrierHighHz) / 2 - ...
            120 * ssbSCS * 1e3) / referenceHz;
        if abs(centeredLowUnits - round(centeredLowUnits)) > 1e-9
            error("sixgr:phy:frame:SSBCenterNotPointAAligned", ...
                "A centered SS/PBCH block cannot be represented by integer " + ...
                "NCRBSSB/KSSB for this carrier.");
        end
        centeredLowUnits = round(centeredLowUnits);
        ncrb = floor(centeredLowUnits / 12);
        kssb = mod(centeredLowUnits, 12);
        placementSource = "canonical_centered_grid_derivation";
    else
        ncrb = 0;
        kssb = 0;
        placementSource = "point_a_context_not_supplied";
    end
elseif isfinite(ncrb) && ~isfinite(kssb)
    kssb = 0;
elseif ~isfinite(ncrb) && isfinite(kssb)
    error("sixgr:phy:frame:InvalidSSBPointAOffset", ...
        "KSSB cannot be supplied without NCRBSSB.");
end
if ~(ncrb == fix(ncrb) && ncrb >= 0 && ...
        kssb == fix(kssb) && kssb >= 0)
    error("sixgr:phy:frame:InvalidSSBPointAOffset", ...
        "NCRBSSB and KSSB must be nonnegative integers.");
end
if kssb > maxKSSB
    error("sixgr:phy:frame:InvalidKSSB", ...
        "KSSB=%d exceeds the %d-subcarrier limit for SSB SCS %g kHz.", ...
        kssb, maxKSSB, ssbSCS);
end
ssbLowHz = ncrb * 12 * referenceSCS * 1e3 + ...
    kssb * referenceSCS * 1e3;
ssbHighHz = ssbLowHz + 240 * ssbSCS * 1e3;
if isfinite(nSizeGrid)
    toleranceHz = max(1e-9 * carrierHighHz, 1e-6);
    if ssbLowHz < carrierLowHz - toleranceHz || ...
            ssbHighHz > carrierHighHz + toleranceHz
        error("sixgr:phy:frame:SSBOutsideCarrierGrid", ...
            "SS/PBCH occupies Point-A offsets [%.15g,%.15g) Hz, " + ...
            "outside carrier grid [%.15g,%.15g) Hz.", ...
            ssbLowHz, ssbHighHz, carrierLowHz, carrierHighHz);
    end
end
if isfinite(nSizeBWP)
    if ~(isfinite(nStartBWP) && nStartBWP == fix(nStartBWP) && ...
            isfinite(nSizeGrid) && nStartBWP >= nStartGrid && ...
            nSizeBWP == fix(nSizeBWP) && nSizeBWP >= 1 && ...
            nStartBWP + nSizeBWP <= nStartGrid + nSizeGrid)
        error("sixgr:phy:frame:SSBBWPOutsideCarrierGrid", ...
            "The configured SSB BWP [%g,%g) is outside carrier grid [%g,%g).", ...
            nStartBWP, nStartBWP + nSizeBWP, ...
            nStartGrid, nStartGrid + nSizeGrid);
    end
end
grid = struct( ...
    "NStartGrid", nStartGrid, ...
    "NSizeGrid", nSizeGrid, ...
    "NStartBWP", nStartBWP, ...
    "NSizeBWP", nSizeBWP, ...
    "NCRBSSB", ncrb, ...
    "KSSB", kssb, ...
    "PointAReferenceSCSKHz", double(referenceSCS), ...
    "SSBLowOffsetFromPointAHz", double(ssbLowHz), ...
    "SSBHighOffsetFromPointAHz", double(ssbHighHz), ...
    "CarrierLowOffsetFromPointAHz", double(carrierLowHz), ...
    "CarrierHighOffsetFromPointAHz", double(carrierHighHz), ...
    "PlacementSource", placementSource, ...
    "SSBSubcarrierSpacingKHz", double(ssbSCS), ...
    "SSBOccupiedSubcarriers", 240, ...
    "PointAExplicit", isfinite(nSizeGrid));
end

function tf = localToolboxSupportsCase(caseLetter)
tf = false;
try
    tf = any(strcmpi("Case " + caseLetter, ...
        string(nrWavegenSSBurstConfig.BlockPattern_Values)));
catch
end
end

function tf = localTextScalar(v)
tf = ischar(v) || (isstring(v) && isscalar(v));
end

function tf = localFiniteOrNaN(v)
tf = isnumeric(v) && isreal(v) && isscalar(v) && ...
    (isfinite(v) || isnan(v));
end

function tf = localPositiveFinite(v)
tf = isnumeric(v) && isreal(v) && isscalar(v) && isfinite(v) && v > 0;
end

function tf = localNonnegativeInteger(v)
tf = isnumeric(v) && isreal(v) && isscalar(v) && isfinite(v) && ...
    v >= 0 && v == fix(v);
end
