function writeC0Report(folder,cfg,summary,fa,points,crossings)
%WRITEC0REPORT Write the human-readable C0 result reduction.
lines=["# C0 complete-SSB campaign";""; ...
    "- Scenario: `"+string(cfg.meta.scenario_id)+"`"; ...
    "- Mode: `"+string(cfg.run.mode)+"`"; ...
    "- Evidence: actual NR PSS/SSS/PBCH waveform execution"; ...
    "- Trials: "+sum(points.Trials); ...
    "- Global false alarm: "+fa.EmpiricalPFA+" (95% CI ["+ ...
        fa.CILow+", "+fa.CIHigh+"])"; ...
    "- Engineering gate: "+summary.SmokeOrEngineeringPass; ...
    "- TDoc gate: "+summary.TDocPass; ...
    "- Bracketed target crossings: "+nnz(crossings.Bracketed)+ ...
        "/"+height(crossings); ...
    "";"Smoke and quick-sanity results are not contribution-grade numerical claims."];
sixgr.util.writeTextFile(fullfile(folder,"report.md"), ...
    strjoin(lines,newline),"MimeType","text/markdown");
end
