#!/usr/bin/env python3
"""Generate frozen connected-mode UPER vectors with independent pycrate.

The input module must be generated by pycrate_asn1c from the official
3GPP TS 38.331 V18.9.0 ASN.1 segments.  This generator intentionally lives
outside the MATLAB implementation under test.
"""
from __future__ import annotations

import argparse
import csv
import hashlib
import importlib.util
import json
from pathlib import Path
from typing import Any


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as source:
        for chunk in iter(lambda: source.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def canonical(value: Any) -> Any:
    if isinstance(value, bytes):
        return {"octets_hex": value.hex().upper()}
    if isinstance(value, tuple):
        if len(value) == 2 and isinstance(value[0], str):
            return {"choice": value[0], "value": canonical(value[1])}
        if len(value) == 2 and all(isinstance(item, int) for item in value):
            return {"bit_string_value": value[0], "bit_length": value[1]}
        return [canonical(item) for item in value]
    if isinstance(value, dict):
        return {key: canonical(value[key]) for key in sorted(value)}
    if isinstance(value, list):
        return [canonical(item) for item in value]
    return value


def load_module(path: Path):
    spec = importlib.util.spec_from_file_location("sixgr_rrc_nr_v1890", path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Unable to import compiled ASN.1 module {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def transaction(message_type: str, transaction_id: int, mcg: bytes) -> dict:
    empty = {
        "SecurityModeComplete": ("securityModeComplete", {}),
        "UECapabilityInformation": ("ueCapabilityInformation", {}),
        "RRCReconfiguration": ("rrcReconfiguration", {}),
        "RRCReconfigurationComplete": ("rrcReconfigurationComplete", {}),
        "RRCRelease": ("rrcRelease", {}),
        "RRCReestablishmentComplete": ("rrcReestablishmentComplete", {}),
        "RRCResume": ("rrcResume", {}),
        "RRCResumeComplete": ("rrcResumeComplete", {}),
    }
    if message_type in empty:
        choice, ies = empty[message_type]
    elif message_type == "RRCSetup":
        choice = "rrcSetup"
        ies = {"radioBearerConfig": {}, "masterCellGroup": mcg}
    elif message_type == "RRCSetupComplete":
        choice = "rrcSetupComplete"
        ies = {
            "selectedPLMN-Identity": 1,
            "dedicatedNAS-Message": b"\x01",
        }
    elif message_type == "SecurityModeCommand":
        choice = "securityModeCommand"
        ies = {
            "securityConfigSMC": {
                "securityAlgorithmConfig": {
                    "cipheringAlgorithm": "nea2",
                    "integrityProtAlgorithm": "nia2",
                }
            }
        }
    elif message_type == "UECapabilityEnquiry":
        choice = "ueCapabilityEnquiry"
        ies = {"ue-CapabilityRAT-RequestList": [{"rat-Type": "nr"}]}
    elif message_type == "RRCReestablishment":
        choice = "rrcReestablishment"
        ies = {"nextHopChainingCount": 0}
    else:
        raise KeyError(message_type)
    return {
        "rrc-TransactionIdentifier": transaction_id,
        "criticalExtensions": (choice, ies),
    }


def message_value(message_type: str, transaction_id: int, mcg: bytes) -> dict:
    if message_type == "RRCSetupRequest":
        return {
            "rrcSetupRequest": {
                "ue-Identity": ("randomValue", (0x123456789, 39)),
                "establishmentCause": "mo-Data",
                "spare": (0, 1),
            }
        }
    if message_type == "MeasurementReport":
        return {
            "criticalExtensions": (
                "measurementReport",
                {
                    "measResults": {
                        "measId": 1,
                        "measResultServingMOList": [
                            {
                                "servCellId": 0,
                                "measResultServingCell": {
                                    "measResult": {"cellResults": {}}
                                },
                            }
                        ],
                    }
                },
            )
        }
    if message_type == "RRCReestablishmentRequest":
        return {
            "rrcReestablishmentRequest": {
                "ue-Identity": {
                    "c-RNTI": 1,
                    "physCellId": 0,
                    "shortMAC-I": (0, 16),
                },
                "reestablishmentCause": "otherFailure",
                "spare": (0, 1),
            }
        }
    if message_type == "RRCResumeRequest":
        return {
            "rrcResumeRequest": {
                "resumeIdentity": (0x123456, 24),
                "resumeMAC-I": (0, 16),
                "resumeCause": "mo-Data",
                "spare": (0, 1),
            }
        }
    return transaction(message_type, transaction_id, mcg)


CHANNELS = {
    "RRCSetupRequest": ("UL_CCCH_Message", "UL-CCCH", "rrcSetupRequest"),
    "RRCSetup": ("DL_CCCH_Message", "DL-CCCH", "rrcSetup"),
    "RRCSetupComplete": ("UL_DCCH_Message", "UL-DCCH", "rrcSetupComplete"),
    "SecurityModeCommand": (
        "DL_DCCH_Message",
        "DL-DCCH",
        "securityModeCommand",
    ),
    "SecurityModeComplete": (
        "UL_DCCH_Message",
        "UL-DCCH",
        "securityModeComplete",
    ),
    "UECapabilityEnquiry": (
        "DL_DCCH_Message",
        "DL-DCCH",
        "ueCapabilityEnquiry",
    ),
    "UECapabilityInformation": (
        "UL_DCCH_Message",
        "UL-DCCH",
        "ueCapabilityInformation",
    ),
    "RRCReconfiguration": (
        "DL_DCCH_Message",
        "DL-DCCH",
        "rrcReconfiguration",
    ),
    "RRCReconfigurationComplete": (
        "UL_DCCH_Message",
        "UL-DCCH",
        "rrcReconfigurationComplete",
    ),
    "MeasurementReport": (
        "UL_DCCH_Message",
        "UL-DCCH",
        "measurementReport",
    ),
    "RRCRelease": ("DL_DCCH_Message", "DL-DCCH", "rrcRelease"),
    "RRCReestablishmentRequest": (
        "UL_CCCH_Message",
        "UL-CCCH",
        "rrcReestablishmentRequest",
    ),
    "RRCReestablishment": (
        "DL_DCCH_Message",
        "DL-DCCH",
        "rrcReestablishment",
    ),
    "RRCReestablishmentComplete": (
        "UL_DCCH_Message",
        "UL-DCCH",
        "rrcReestablishmentComplete",
    ),
    "RRCResumeRequest": (
        "UL_CCCH_Message",
        "UL-CCCH",
        "rrcResumeRequest",
    ),
    "RRCResume": ("DL_DCCH_Message", "DL-DCCH", "rrcResume"),
    "RRCResumeComplete": (
        "UL_DCCH_Message",
        "UL-DCCH",
        "rrcResumeComplete",
    ),
}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--compiled-module", required=True, type=Path)
    parser.add_argument("--source-spec", required=True, type=Path)
    parser.add_argument("--catalog", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()

    module = load_module(args.compiled_module)
    definitions = module.NR_RRC_Definitions
    definitions.CellGroupConfig.set_val({"cellGroupId": 0})
    master_cell_group = definitions.CellGroupConfig.to_uper()
    source_hash = sha256(args.source_spec)
    generator_hash = sha256(Path(__file__))

    with args.catalog.open(newline="", encoding="utf-8-sig") as source:
        catalog = list(csv.DictReader(source))
    output = []
    for source_row in catalog:
        if source_row["ExpectedValid"].lower() != "true":
            continue
        message_type = source_row["MessageType"]
        transaction_id = int(source_row["TransactionID"])
        wrapper_name, channel, alternative = CHANNELS[message_type]
        value = message_value(message_type, transaction_id, master_cell_group)
        wrapper_value = {"message": ("c1", (alternative, value))}
        wrapper = getattr(definitions, wrapper_name)
        wrapper.set_val(wrapper_value)
        encoded = wrapper.to_uper()
        wrapper.from_uper(encoded)
        decoded = wrapper.get_val()
        decoded_json = json.dumps(
            canonical(decoded), sort_keys=True, separators=(",", ":")
        )
        vector_identity = "|".join(
            [
                source_row["CaseID"],
                message_type,
                str(transaction_id),
                channel,
                encoded.hex().upper(),
                decoded_json,
                source_hash,
            ]
        )
        output.append(
            {
                "CaseID": source_row["CaseID"],
                "MessageType": message_type,
                "TransactionID": transaction_id,
                "Channel": channel,
                "ASN1Release": "38.331-v18.9.0",
                "UPERHex": encoded.hex().upper(),
                "EncodedBits": len(encoded) * 8,
                "DecodedTreeJSON": decoded_json,
                "DecodedTreeSHA256": hashlib.sha256(
                    decoded_json.encode("utf-8")
                ).hexdigest(),
                "OracleImplementation": "pycrate_asn1c+pycrate_asn1rt",
                "OracleVersion": "0.7.11",
                "SpecificationSourceSHA256": source_hash,
                "GeneratorSHA256": generator_hash,
                "VectorSHA256": hashlib.sha256(
                    vector_identity.encode("utf-8")
                ).hexdigest(),
            }
        )

    columns = list(output[0])
    with args.output.open("w", newline="", encoding="utf-8") as target:
        writer = csv.DictWriter(target, fieldnames=columns)
        writer.writeheader()
        writer.writerows(output)
    print(
        json.dumps(
            {
                "vectors": len(output),
                "specification_source_sha256": source_hash,
                "output_sha256": sha256(args.output),
            },
            indent=2,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
